### ISSUE TITLE
ajax 重复提交

### ISSUE THREAD

**Issue by MEEllis** [PanJiaChen/vue-element-admin#1000]
如何优雅的控制ajax 重复提交呢？我看登录页面加了一个load, 但是到了项目中的 complex-table 页面 ，表单提交 都没有 添加loading。

**Comment by PanJiaChen** [comment]
可以单独为 表单提交的请求 封装一个axios， 并将状态放入到 vuex中。 之后就可以 button上加loading了。

原理都是加一个锁

**Comment by MEEllis** [comment]
我理解你的意思勒 。一个页面有3~6个按钮需要loading . 那不是就需要用到3~6个loading ？

![9opd_ 1z0t9aijbil o082](https://user-images.githubusercontent.com/14042373/44503375-9ba8c880-a6c8-11e8-9d25-f5e277c48734.png)。  有没有类似dva那种 loading的用法呢？

**Comment by MEEllis** [comment]
公用一个（vuex）loading会出现，禁用和启用 的按钮会同时出现loading的效果

**Comment by PanJiaChen** [comment]
我思考了，好像没有啥太偷懒的办法。

**Comment by MEEllis** [comment]
okay.
