### ISSUE TITLE
登录跳转首页

### ISSUE THREAD

**Issue by xiaoyi8** [PanJiaChen/vue-element-admin#1001]
在login的index.vue中把登录按钮 <el-button type="primary" @click.native.prevent="handleLogin"></el-button>中handleLogin方法内容都去掉，点击怎么跳转不到 this.$router.push({ path: '/' })。
内容没去前：
这时候点击按钮能跳转到首页。
```js
 handleLogin() {
          this.loading = true
          this.$store.dispatch('Login', this.loginForm).then(() => {
            this.loading = false
            this.$router.push({ path: '/' })
          }).catch(() => {
            this.loading = false
          })
    }
```
内容去掉后：
```js
 handleLogin() {
            this.$router.push({ path: '/' })
 }
```
这时候点击按钮就不能跳转到首页了。
我的疑问是，内容没去掉前，先判断this.$store.dispatch()这个是否成功，成功了就执行then(() => {
            this.loading = false
            this.$router.push({ path: '/' })
          })这里面的函数，那我直接去掉，直接执行 this.$router.push({ path: '/' })就不行吗？这是为啥？

**Comment by PanJiaChen** [comment]
请看 vuex Login 做的事情。

这涉及到权限，你没登录成功，怎么可能让你跳转到首页，

**Comment by jiudan** [comment]
import { getToken, setToken, removeToken } from '@/utils/auth'

handleLogin() {
      var _this=this;
      
          _this.$store.commit('SET_TOKEN', "admin");
          setToken("admin");
          _this.$router.push({ path: _this.redirect || '/' });

    }

在login的index.vue 这样修改。 我通过ajax关系查找，在store的src\store\modules\user.js 找到结果

**Comment by leafiy** [comment]
如果增加一个注册页呢？怎么跳过去？

**Comment by masterchen** [comment]
@leafiy @PanJiaChen  请问 如果新增加一个注册页面 怎么跳转， 我发现好像url切换了，但是不跳转：
//template
 <el-button type="primary" class="item-btn" size="medium" @click.native.prevent="handleRegister">我要注册</el-button>
 
 
 
 method:
 
     handleRegister() {
      console.log('handleRegister')
      this.$router.push({ path: '/register' })
      console.log('handleRegister end')
    },
    
    
    
 router/index.js   
{
    path: '/register',
    name: 'Register',
    component: () => import('@/views/login/register'),
    hidden: true
  },

**Comment by leafiy** [comment]
> @leafiy @PanJiaChen 请问 如果新增加一个注册页面 怎么跳转， 我发现好像url切换了，但是不跳转：
> //template
> <el-button type="primary" class="item-btn" size="medium" @click.native.prevent="handleRegister">我要注册
> 
> method:
> 
> ```
>  handleRegister() {
>   console.log('handleRegister')
>   this.$router.push({ path: '/register' })
>   console.log('handleRegister end')
> },
> ```
> 
> router/index.js
> {
> path: '/register',
> name: 'Register',
> component: () => import('@/views/login/register'),
> hidden: true
> },

要在`permission.js` 里面的 `whiteList`增加无权限可访问页面。

@PanJiaChen 这个是不是应该写在文档里或作一个config呢

**Comment by leafiy** [comment]
@masterchen 
要在permission.js 里面的 whiteList增加无权限可访问页面。

@PanJiaChen 这个是不是应该写在文档里或作一个config呢

**Comment by masterchen** [comment]
@leafiy @PanJiaChen ，大佬 经过查看权限，和思考，我把注册页面加到白名单就可以了。permission.js中


const whiteList = ['/login', '/auth-redirect', '/register'] // no redirect whitelist

**Comment by masterchen** [comment]
@leafiy  哈哈，谢谢。 我也是今早才发现，昨晚一直开着电脑，今天直接评论，提交刷新了一下，就看到你也发现这个秘密

**Comment by xyhuxin** [comment]
大神，我登录的时候，把登录接口换成动态的接口，调试，接口响应成功，但是无法跳转，这是什么鬼呀？求解答

**Comment by phoebemoon16** [comment]
@xyhuxin  请问你解决了吗 我也遇到了这个问题？ -.-

**Comment by wangxingguo** [comment]
我也是动态成功之后,无法跳转到首页
请问大神们都解决了

**Comment by old-boy** [comment]
我也是登陆成功了，后台返回调用接口成功了，但是不跳转

**Comment by aliliin** [comment]
我也是登陆成功了，后台返回调用接口成功了，但是不跳转
