### ISSUE TITLE
关于左侧菜单和动态路由问题！

### ISSUE THREAD

**Issue by wlLeblanc** [PanJiaChen/vue-element-admin#1002]
请问一下，大佬们，如果我的是路由表是后端返回的，比如
![image](https://user-images.githubusercontent.com/22288871/44561721-a460d380-a788-11e8-9b91-0ee7160debb7.png)   然后我的本地路由表里面
![image](https://user-images.githubusercontent.com/22288871/44561746-bf334800-a788-11e8-911f-c893fe215abe.png)需不需要写？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/293

**Comment by wlLeblanc** [comment]
@PanJiaChen 谢谢潘神的回复！

**Comment by liujie278** [comment]
大佬，解决了吗
