### ISSUE TITLE
token验证问题，更改权限

### ISSUE THREAD

**Issue by dptobat** [PanJiaChen/vue-element-admin#1003]
![image](https://user-images.githubusercontent.com/13936586/44562198-0a4e5a80-a78b-11e8-9cf7-c4c36aa36639.png)
将token放在cookie，如果有人篡改cookie，这样是不是可以获取到更大的权限；还是说这个token最好是一串很难复制的编码；是否存在一定风险，大神是否有更好的方法呢；

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/158
