### ISSUE TITLE
树表3万行数据无法显示

### ISSUE THREAD

**Issue by hql7** [PanJiaChen/vue-element-admin#1004]

**Comment by PanJiaChen** [comment]
不支持这么大量数据，请自行进行分页处理。

**Comment by hql7** [comment]
树表没法分页啊

**Comment by PanJiaChen** [comment]
分页组件 和 树表 没有什么耦合关系。

分页组件控制分页，树表只是负责渲染当前数据而已。

**Comment by hql7** [comment]
那按什么分页呢？第一级数据条数?所有子孙节点条数？

在 2018-09-06 15:34:58，"花裤衩" <notifications@github.com> 写道：


分页组件 和 树表 没有什么耦合关系。

分页组件控制分页，树表只是负责渲染当前数据而已。
