### ISSUE TITLE
请问怎么做才能让路由切换的时候页面不重新加载

### ISSUE THREAD

**Issue by xuzixian** [PanJiaChen/vue-element-admin#1006]
现在的切换已经打开的页面时，会重新加载，需要怎么配置才能不让页面重新加载呢，谢谢
![image](https://user-images.githubusercontent.com/5772313/44566072-11cb2f00-a79e-11e8-860f-9146daa31463.png)

**Comment by PanJiaChen** [comment]
`noCache`

默认会被 cache

https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/router-and-nav.html#%E9%85%8D%E7%BD%AE%E9%A1%B9
