### ISSUE TITLE
svg-icon 组件 通过 className 传入 class 的样式被覆盖

### ISSUE THREAD

**Issue by z1900** [PanJiaChen/vue-element-admin#1008]
![_20180824144358](https://user-images.githubusercontent.com/23111937/44569401-cff5b500-a7ac-11e8-869b-0c93d66349fb.png)

![_20180824144253](https://user-images.githubusercontent.com/23111937/44569416-db48e080-a7ac-11e8-85a3-141479f6a863.png)

![_20180824144318](https://user-images.githubusercontent.com/23111937/44569422-df74fe00-a7ac-11e8-9d37-1e351f669923.png)
通过组件暴露的 **className** 传入 *class* 但是总是会被组件中默认的 *class* **svg-icon** 的样式覆盖，请问这是为什么

**Comment by PanJiaChen** [comment]
这和css加载顺序有关，你通过其它css权重方式覆盖吧。

比如这样写
```css
.svg-icon.icon-class{}
```

**Comment by z1900** [comment]
好的 谢谢
