### ISSUE TITLE
主界面内组件fetch远程接口异常405，options被拒绝，但是 登录组件正常fetch，相同的接口，请问是什么原因啊！已经多次试验过了，没找到问题所在

### ISSUE THREAD

**Issue by Aleczhang1992** [PanJiaChen/vue-element-admin#101]
![default](https://user-images.githubusercontent.com/15828753/27579469-34b529f8-5b5a-11e7-87d1-3d3439ce8843.png)
<img width="497" alt="default" src="https://user-images.githubusercontent.com/15828753/27579487-429a436e-5b5a-11e7-847e-785bcd00482f.png">
![default](https://user-images.githubusercontent.com/15828753/27579563-8d705fa4-5b5a-11e7-9ae4-230ec2bd4f3b.png)

**Comment by PanJiaChen** [comment]
这和该项目没太大关系了，而且报错也很明确了，可以搜索跨域 405相关问题

**Comment by Aleczhang1992** [comment]
同一个接口，在两个组件内访问的，登录组件内成功，主界面内组件失败，可以确认接口没有问题呢

**Comment by PanJiaChen** [comment]
你确定么？ 你一个是get但没发options 但另一个发options了

**Comment by Aleczhang1992** [comment]
调用的是一个方法呢
<img width="980" alt="default" src="https://user-images.githubusercontent.com/15828753/27581173-8a0495ec-5b5f-11e7-803f-c39a032374c7.png">
<img width="848" alt="default" src="https://user-images.githubusercontent.com/15828753/27581192-98a0d1c4-5b5f-11e7-9bb4-cac4a03d4d28.png">
<img width="838" alt="default" src="https://user-images.githubusercontent.com/15828753/27581228-b5a5e818-5b5f-11e7-9624-3f61945c68f5.png">
<img width="862" alt="default" src="https://user-images.githubusercontent.com/15828753/27581244-c028e362-5b5f-11e7-8192-3806564a470a.png">
<img width="962" alt="default" src="https://user-images.githubusercontent.com/15828753/27581286-dcb7fb9e-5b5f-11e7-8422-b40f61f0950e.png">

**Comment by Aleczhang1992** [comment]
@PanJiaChen 谢谢你的帮忙，应该是fetch使用的问题，但是仍未找到原因，感觉有点奇怪，更换axios后，可以正常发送请求了
