### ISSUE TITLE
菜单栏收缩问题

### ISSUE THREAD

**Issue by powhd** [PanJiaChen/vue-element-admin#1014]
请问现在其中一个菜单展开,点击另一个菜单可否把其他展开的菜单栏给收缩回来

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/layout/components/Sidebar/index.vue

`unique-opened`

http://element-cn.eleme.io/#/zh-CN/component/menu
