### ISSUE TITLE
不需要登录即可访问的页面

### ISSUE THREAD

**Issue by X-Mars** [PanJiaChen/vue-element-admin#1015]
大佬你好：
     小弟有这样一个应用场景，后台创建用户后，自动发送一个密码设置链接给用户，用户点击这个链接设置密码。
    现在遇到一个问题：我在 **router/index.js** 添加了链接，但是会跳转到登录页面，请问如何避免跳转，
谢谢

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/325120b65341e559d3af155f146871419b49af79/src/permission.js#L17

**Comment by X-Mars** [comment]
这种方式可以打开页面，但是如果在页面中执行request，依然会跳转到登录页面。求大神赐教

**Comment by PanJiaChen** [comment]
request 是什么

**Comment by X-Mars** [comment]
找到原因了，是我的失误。

**Comment by zyyettie** [comment]
我也遇到过这样的问题，解决方法跟PanJiaChen的一样

**Comment by linzhi** [comment]
假设有一类path不需要先跳转到登陆界面呢，比如/a/b/:id 这种。。如何实现啊

**Comment by linzhi** [comment]
用了个trick的方法...    if ((whiteList.indexOf(to.path) !== -1) || (to.path.startsWith('/a/b/'))) {

**Comment by gzw13999** [comment]
> https://github.com/PanJiaChen/vue-element-admin/blob/325120b65341e559d3af155f146871419b49af79/src/permission.js#L17

要严格匹配，后面多一个/都是失效
