### ISSUE TITLE
src/api这层必要性在哪里？直接调用更容易维护啊

### ISSUE THREAD

**Issue by Chenberg** [PanJiaChen/vue-element-admin#1016]
src/api这层只是简单的配置，但是要多改一个文件，我感觉不如全局注册request.js，然后直接调用，例如：
loginByUsername(username, userInfo.password).then(response => {
改为：
request.post('user/login', { name: username, password: userInfo.password }).then(data => {
或者
this.$http.post('user/login', { name: username, password: userInfo.password }).then(data => {
其实就是一个地址，这样多好维护啊

**Comment by PanJiaChen** [comment]
各人喜欢集中管理。比如你很多搜索接口，它们大部分都是公用的，这种情况下你手写地址就很麻烦了。而且真实业务中其实一个接口还要做其它很多处理，这种情况下公用是更合理的。

不过还是请集合自己的业务挑战，你不要想`src/api`也是可以的。
