### ISSUE TITLE
如何在运行时获取所有页面的按钮权限

### ISSUE THREAD

**Issue by CaiBaoHong** [PanJiaChen/vue-element-admin#1019]
我想在一个页面上列出src/router中路由定义的菜单（这个实现了），然后又想列出所有页面定义的按钮权限（我自己改成按角色下的权限值来判断权限了），比如在book.vue页面上的增加和删除按钮：
`
<el-button v-permission="['add']">新增</el_button>
<el-button v-permission="['delete']">删除</el_button>
`
所以，我想知道vue.js有没有一种方法可以实现在运行时，扫面页面上的指令，来获取指令中的参数？或者是某种实现思路？

**Comment by PanJiaChen** [comment]
其实可以在`v-permission`注册的时候将权限存到 vuex里面就可以了。

**Comment by CaiBaoHong** [comment]
自定义指令的componentUpdated钩子函数吗？

**Comment by PanJiaChen** [comment]
`bind` hook
