### ISSUE TITLE
顶部标签导航栏如何自定义显示名称？

### ISSUE THREAD

**Issue by myrfy001** [PanJiaChen/vue-element-admin#1020]
例如文章管理，有
https://panjiachen.github.io/vue-element-admin/#/example/edit/1
https://panjiachen.github.io/vue-element-admin/#/example/edit/2

当两个标签都打开时，导航栏会显示两个`Edit Article`， 请问如何才能修改显示内容？比如各自显示每篇文章的标题。
谢谢

**Comment by PanJiaChen** [comment]
调用 `this.$store.dispatch('updateVisitedView', route)` 就可以了。

**Comment by PanJiaChen** [comment]
新增了 demo  https://github.com/PanJiaChen/vue-element-admin/pull/1167
