### ISSUE TITLE
在vue项目中 selection.transition 不存在这个函数

### ISSUE THREAD

**Issue by wangyaxinone** [PanJiaChen/vue-element-admin#1021]
![image](https://user-images.githubusercontent.com/23171959/44715055-6dbced00-aae9-11e8-853a-201a66018e8d.png)
您知道这是为什么吗？我看到在你的项目中不存在这个问题

**Comment by wangyaxinone** [comment]
![image](https://user-images.githubusercontent.com/23171959/44715226-cdb39380-aae9-11e8-9562-9194add3b14b.png)
这个是你的项目中d3.select()

**Comment by PanJiaChen** [comment]
`selection.transition`是什么?
