### ISSUE TITLE
是不是不支持  echarts 4 + ？

### ISSUE THREAD

**Issue by X-Mars** [PanJiaChen/vue-element-admin#1022]
大佬您好：
      小弟想使用  vue-echarts   **Built upon ECharts v4.0.1+ and depends on Vue.js v2.2.6+.**    
      但我看到 vue-element-admin  用的  **"echarts": "^3.8.5",**  ，  我按照vue-echarts的例子操作，报错，是不是没法兼容啊。

谢谢

**Comment by PanJiaChen** [comment]
你升级一下不就好了

**Comment by X-Mars** [comment]
好的  我以为 vue-element-admin  不支持 echarts 4.1 呢
谢谢
