### ISSUE TITLE
如何不让url 地址不更改

### ISSUE THREAD

**Issue by wangdan013130** [PanJiaChen/vue-element-admin#1026]
利用 xiprocess.env.BASE_API  进行请求， 打包前端口后为 8080 ， 放到服务器后发送请求端口号就变为了 跟服务器一样的端口号8989，无法发送正确的请求， 有没有好的解决方法

**Comment by PanJiaChen** [comment]
自己配置问题。

**Comment by wangdan013130** [comment]
在 config下的 index.js 里设置 target， 这个地址会随着服务器端口号不同而改变吗，如果不想改变，怎么解决

**Comment by PanJiaChen** [comment]
请自行查看 proxyTable 文档
