### ISSUE TITLE
IE9 下：Failed to resolve async component default

### ISSUE THREAD

**Issue by iamshen** [PanJiaChen/vue-element-admin#1028]
我遇到个可能不是框架的问题？
路由采用异步路由，目前只有一个页面出现这个问题，而其他页面是正常的，出问题的这个页面在其他浏览器下正常显示（ie11 也正常）
Failed to resolve async component default: TypeError: 无法获取未定义或 null 引用的属性“toggle”
uncaught error during route navigation:
下面是截图
![5v 0wr16k_37 4t bb q](https://user-images.githubusercontent.com/15643938/44831655-17bb8700-ac5a-11e8-94e8-2df659439155.png)

**Comment by PanJiaChen** [comment]
不支持 ie9 。 有需求自行添加 polyfil

**Comment by xiaodou1994** [comment]
请问解决了吗？我也遇到了
