### ISSUE TITLE
我参考了作者的项目，其中使用了axios作为请求库，但我司后端人员接收不到数据，我这边却发送过去了

### ISSUE THREAD

**Issue by fanerge** [PanJiaChen/vue-element-admin#103]
想问一下，有关于后端对axios发送的数据的处理方式吗，后端开发人员需要如何改变一些编码方式才能进行正常的数据传输。我们前端还能为他们做点什么吗？谢谢

**Comment by PanJiaChen** [comment]
你的问题描述太抽象了，无法知道问题是什么。

**Comment by fanerge** [comment]
vue项目使用axios进行数据传输，后端应该怎么处理呀？

**Comment by PanJiaChen** [comment]
和传统内的ajax没区别

**Comment by fanerge** [comment]
好的，谢谢了，项目在你这里获得很多经验。

**Comment by edwinhuish** [comment]
应该是跨域问题，昨天在百度找到了这个链接，没有实践过，不知道对你有没有用。

[Segmentfault - laravel axios跨域请求的cookie问题](https://segmentfault.com/q/1010000008993069)

**Comment by PanJiaChen** [comment]
太久没回复 关闭了

**Comment by tong3jie** [comment]
现在chrome里面看看是否真的有请求发往后台，如果有则需要查看报的错误。
