### ISSUE TITLE
file协议如何访问vue-element-admin-master

### ISSUE THREAD

**Issue by 54huige** [PanJiaChen/vue-element-admin#1030]
file协议访问的时候 登陆按钮是用不了的 是路由的问题吗 还是需要修改什么配置

**Comment by PanJiaChen** [comment]
不支持，因为file协议不支持 `cookie`。

你可以`npm run build:prod --preview` 启服务查看。
或者自己随便用node还是其它工具启一个服务就可以了。

**Comment by ykchong45** [comment]
参考网上的方案：
`npm install -g serve`，然后在你的`dist`目录下运行`serve`。
