### ISSUE TITLE
二级菜单只有一个item的话渲染出错

### ISSUE THREAD

**Issue by warmilk** [PanJiaChen/vue-element-admin#1034]
![1](https://user-images.githubusercontent.com/14016918/44902049-8d4b5400-ad3b-11e8-9617-608a822fba78.PNG)
![2](https://user-images.githubusercontent.com/14016918/44902053-8fadae00-ad3b-11e8-90f0-1322cd20e188.PNG)

**Comment by PanJiaChen** [comment]
二级菜单只有一个的情况下，默认会不渲染一级菜单。
所以在你的例子中就显示了 `预约挂号`，你没有加`icon`。
如果你想一直渲染一级菜单，可以使用`alwaysShow:true`，请参考[文档](https://panjiachen.gitee.io/vue-element-admin-site/zh/guide/essentials/router-and-nav.html)
