### ISSUE TITLE
LineChart设置缓存，宽度显示为px，不是默认百分比

### ISSUE THREAD

**Issue by xwlaix** [PanJiaChen/vue-element-admin#1036]
dashboard首页在路由设置缓存为false后，LineChart组件的宽度显示为px，不是默认的百分比

**Comment by xwlaix** [comment]
![image](https://user-images.githubusercontent.com/24643599/44943771-a9fc9000-adfe-11e8-835c-df980235d34f.png)

**Comment by PanJiaChen** [comment]
能说明一下复现步骤么？

我这里没能重现你说的问题。

**Comment by xwlaix** [comment]
具体是路由中设置noCache字段去掉，打开以一个页面再切换回来，首页折线图就会压缩成100px

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/issues/1036
