### ISSUE TITLE
在‘手摸手，带你用vue撸后台 系列四(vueAdmin 一个极简的后台基础模板)’看不到有关面包屑的代码

### ISSUE THREAD

**Issue by hehuangz** [PanJiaChen/vue-element-admin#1038]
如图，点击‘代码’，出来的是404页面
![image](https://user-images.githubusercontent.com/32256818/44966459-e0a4e880-af6d-11e8-91b0-ec89390a8a2c.png)

**Comment by PanJiaChen** [comment]
感谢提醒，已更正地址。
