### ISSUE TITLE
feature: add account profile  page

### ISSUE THREAD

**Issue by PanJiaChen** [PanJiaChen/vue-element-admin#1040]

**Comment by tuandm** [comment]
@PanJiaChen Is there any current progress for this task? If you haven't started, I would like to add this page. I've just finished the similar one in my project: 

<img src="https://cdn.laravue.dev/profile.png" width=600 />

Demo URL: https://laravue.dev/#/administrator/users/edit/2

**Comment by PanJiaChen** [comment]
@tuandm welcome pull request.

**Comment by tuandm** [comment]
@PanJiaChen Pull request: #1953 
I need more tasks to get familiar with the code base and mock api. Here is just a simple profile page with data from user state. We could improve later with mock api, we can also have a user listing page and use this profile template for user detail/edit views.
