### ISSUE TITLE
关于存在服务端的map问题，

### ISSUE THREAD

**Issue by wlLeblanc** [PanJiaChen/vue-element-admin#1041]
![image](https://user-images.githubusercontent.com/22288871/44978773-0ea22100-af9e-11e8-9831-93733852fd9b.png)
请问下，我这样做映射是不是有问题，我的map是存在服务端的！

**Comment by PanJiaChen** [comment]
没懂。。。

但我感觉你想要的是这个 https://github.com/PanJiaChen/vue-element-admin/issues/293

**Comment by wlLeblanc** [comment]
@PanJiaChen   我就是按照这个方法来做的，但是
![image](https://user-images.githubusercontent.com/22288871/44979454-c126b380-af9f-11e8-92d7-f086b03ee9b9.png) 这样找不到组件！
![image](https://user-images.githubusercontent.com/22288871/44979538-f59a6f80-af9f-11e8-9bd1-2cab0db70370.png)
wozh我这边是这样写的。

**Comment by PanJiaChen** [comment]
这种需要自己打断点进行调试，它给的应该只是一个例子，还需要结合自己实际情况进行调整。

**Comment by wlLeblanc** [comment]
@PanJiaChen ，大佬是不是因为这个原因
![image](https://user-images.githubusercontent.com/22288871/44979994-2e871400-afa1-11e8-893c-5a2bd9fee4a1.png)zheshi这是我做个处理，
![image](https://user-images.githubusercontent.com/22288871/44980022-4199e400-afa1-11e8-8627-08c01598499b.png)z这是原本的路由数据！

**Comment by wlLeblanc** [comment]
@PanJiaChen  感谢大佬的回答，问题已经解决！

**Comment by zhuxuda** [comment]
@zyy2008 请问你是在什么地方从服务器获取id的那个数组，在什么地方根据这个数组对路由表进行筛选的？我明白你说的意思，可是不知道在哪添加代码，你能解释一下吗？谢谢。

**Comment by wlLeblanc** [comment]
@zyy2008 谢谢，已经解决了

**Comment by zhuxuda** [comment]
@wlLeblanc 谢谢你，我去试试

**Comment by Elias-cug** [comment]
@wlLeblanc 我也出现了这个问题，和你一样，请问你是怎么解决的

**Comment by wlLeblanc** [comment]
@Elias-cug 看一下你的映射对不对

**Comment by Elias-cug** [comment]
@wlLeblanc 
![image](https://user-images.githubusercontent.com/38312452/87753500-54380200-c835-11ea-9b33-4059f152bd6a.png)
映射没问题呢，但是映射过去引入的组件和前端配置的不一样

**Comment by Elias-cug** [comment]
@wlLeblanc 引入的组件，不是一个对象，貌似是个promise

**Comment by Elias-cug** [comment]
@wlLeblanc 解决了，我忘记addRoutes了
