### ISSUE TITLE
怎么在侧边栏的上边加入logo，且这个logo不会随侧边栏滚动？

### ISSUE THREAD

**Issue by chenweiyj** [PanJiaChen/vue-element-admin#1042]
怎么在侧边栏的上边加入logo，且这个logo不会随侧边栏滚动？

**Comment by mgbq** [comment]
https://github.com/mgbq/nx-admin 这个项目就加了logo @chenweiyj

**Comment by PanJiaChen** [comment]
没有固定时间。

**Comment by xurongjie** [comment]
同求

**Comment by mgbq** [comment]
https://github.com/mgbq/nx-admin，有这个功能，在花裤衩基础上弄的

**Comment by luoshiwei** [comment]
> [https://github.com/mgbq/nx-admin，有logo这个功能，在花裤衩基础上弄的](https://github.com/mgbq/nx-admin%EF%BC%8C%E6%9C%89logo%E8%BF%99%E4%B8%AA%E5%8A%9F%E8%83%BD%EF%BC%8C%E5%9C%A8%E8%8A%B1%E8%A3%A4%E8%A1%A9%E5%9F%BA%E7%A1%80%E4%B8%8A%E5%BC%84%E7%9A%84)

您好，看了您封装的框架，非常好，后悔没早看到，我们已经在用花裤衩的框架了，请问该怎么把您的框架整合进来？

**Comment by mgbq** [comment]
就是个logo组件，你复制粘贴就行

**Comment by PanJiaChen** [comment]
4.0版本已支持。
