### ISSUE TITLE
【build:prod发生错误】TypeError: Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by 158008001** [PanJiaChen/vue-element-admin#1049]
项目下载的是zip解压的，安装依赖后可以本地运行，但build出现如下问题：
**终端报错信息：**

> E:\vue-project\vue-element-admin-master>npm run build:prod
> 
> > vue-element-admin@3.8.1 build:prod E:\vue-project\vue-element-admin-master
> > cross-env NODE_ENV=production env_config=prod node build/build.js
> 
> - building for prod environment...E:\vue-project\vue-element-admin-master\node_modules\script-ext-html-webpack-plugin\lib\plugin.js:50
>       compilation.hooks.htmlWebpackPluginAlterAssetTags.tap(PLUGIN, alterAssetTags);
>                                                         ^
> 
> **TypeError: Cannot read property 'tap' of undefined**
>     at ScriptExtHtmlWebpackPlugin.compilationCallback (E:\vue-project\vue-element-admin-master\node_modules\script-ext-html-webpack-plugin\lib\plugin.js:50:57)
>     at SyncHook.eval [as call] (eval at create (E:\vue-project\vue-element-admin-master\node_modules\tapable\lib\HookCodeFactory.js:17:12), <anonymous>:11:1)
>     at SyncHook.lazyCompileHook [as _call] (E:\vue-project\vue-element-admin-master\node_modules\tapable\lib\Hook.js:35:21)
>     at Compiler.newCompilation (E:\vue-project\vue-element-admin-master\node_modules\webpack\lib\Compiler.js:504:26)
>     at hooks.beforeCompile.callAsync.err (E:\vue-project\vue-element-admin-master\node_modules\webpack\lib\Compiler.js:540:29)
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\vue-project\vue-element-admin-master\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
>     at AsyncSeriesHook.lazyCompileHook [as _callAsync] (E:\vue-project\vue-element-admin-master\node_modules\tapable\lib\Hook.js:35:21)
>     at Compiler.compile (E:\vue-project\vue-element-admin-master\node_modules\webpack\lib\Compiler.js:535:28)
>     at readRecords.err (E:\vue-project\vue-element-admin-master\node_modules\webpack\lib\Compiler.js:274:11)
>     at Compiler.readRecords (E:\vue-project\vue-element-admin-master\node_modules\webpack\lib\Compiler.js:402:11)
>     at hooks.run.callAsync.err (E:\vue-project\vue-element-admin-master\node_modules\webpack\lib\Compiler.js:271:10)
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\vue-project\vue-element-admin-master\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
>     at AsyncSeriesHook.lazyCompileHook [as _callAsync] (E:\vue-project\vue-element-admin-master\node_modules\tapable\lib\Hook.js:35:21)
>     at hooks.beforeRun.callAsync.err (E:\vue-project\vue-element-admin-master\node_modules\webpack\lib\Compiler.js:268:19)
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\vue-project\vue-element-admin-master\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
>     at AsyncSeriesHook.lazyCompileHook [as _callAsync] (E:\vue-project\vue-element-admin-master\node_modules\tapable\lib\Hook.js:35:21)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! vue-element-admin@3.8.1 build:prod: `cross-env NODE_ENV=production env_config=prod node build/build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the vue-element-admin@3.8.1 build:prod script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-09-05T05_37_15_612Z-debug.log

**日志信息：**

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'E:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'build:prod' ]
> 2 info using npm@5.6.0
> 3 info using node@v8.11.4
> 4 verbose run-script [ 'prebuild:prod', 'build:prod', 'postbuild:prod' ]
> 5 info lifecycle vue-element-admin@3.8.1~prebuild:prod: vue-element-admin@3.8.1
> 6 info lifecycle vue-element-admin@3.8.1~build:prod: vue-element-admin@3.8.1
> 7 verbose lifecycle vue-element-admin@3.8.1~build:prod: unsafe-perm in lifecycle true
> 8 verbose lifecycle vue-element-admin@3.8.1~build:prod: PATH: E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\vue-project\vue-element-admin-master\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;E:\Program Files\Java\jdk1.8.0_151\bin;E:\Program Files\Java\jdk1.8.0_151\jre\bin;E:\Program Files\MySQL Server 5.5\bin;E:\Program Files\nodejs\;C:\Users\Administrator\AppData\Roaming\npm;E:\Program Files\Microsoft VS Code\bin
> 9 verbose lifecycle vue-element-admin@3.8.1~build:prod: CWD: E:\vue-project\vue-element-admin-master
> 10 silly lifecycle vue-element-admin@3.8.1~build:prod: Args: [ '/d /s /c',
> 10 silly lifecycle   'cross-env NODE_ENV=production env_config=prod node build/build.js' ]
> 11 silly lifecycle vue-element-admin@3.8.1~build:prod: Returned: code: 1  signal: null
> 12 info lifecycle vue-element-admin@3.8.1~build:prod: Failed to exec build:prod script
> 13 verbose stack Error: vue-element-admin@3.8.1 build:prod: `cross-env NODE_ENV=production env_config=prod node build/build.js`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at EventEmitter.emit (events.js:214:7)
> 13 verbose stack     at ChildProcess.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at ChildProcess.emit (events.js:214:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:925:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 14 verbose pkgid vue-element-admin@3.8.1
> 15 verbose cwd E:\vue-project\vue-element-admin-master
> 16 verbose Windows_NT 6.1.7601
> 17 verbose argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:prod"
> 18 verbose node v8.11.4
> 19 verbose npm  v5.6.0
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error vue-element-admin@3.8.1 build:prod: `cross-env NODE_ENV=production env_config=prod node build/build.js`
> 22 error Exit status 1
> 23 error Failed at the vue-element-admin@3.8.1 build:prod script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
>

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/ba6bf3e21704d274cd3014a7ea1fa75ab98e2bf5

**Comment by linweiwei123** [comment]
@PanJiaChen 有效

**Comment by wql77** [comment]
"html-webpack-plugin": "4.0.0-alpha",就是这样的，但还是报这个错

**Comment by zyyettie** [comment]
"html-webpack-plugin": "4.0.0-alpha"
已经改成这样了，还是报这个错误

**Comment by rootter** [comment]
> "html-webpack-plugin": "4.0.0-alpha"
> 已经改成这样了，还是报这个错误

你好，请问这个问题您解决了么  我也是这个错误 改了也是这个错误

**Comment by rootter** [comment]
> "html-webpack-plugin": "4.0.0-alpha",就是这样的，但还是报这个错

你好，请问这个问题 您解决了么， 我这也是改了  但还是报错
