### ISSUE TITLE
同一个接口请求两次的问题

### ISSUE THREAD

**Issue by hlj2722** [PanJiaChen/vue-element-admin#105]
如下，我请求一个接口时，为什么会有 OPTIONS 请求
2017/07/01 11:53:41 [D] [server.go:2568] | 192.168.31.228| 200 |    201.882µs| nomatch| OPTIONS  /article/list
2017/07/01 11:53:42 [D] [server.go:2568] | 192.168.31.228| 404 |    421.099µs| nomatch| GET      /article/list

**Comment by edwinhuish** [comment]
你可以看看这个：
[为什么axios请求接口会发起两次请求](http://www.cnblogs.com/Upton/p/6183804.html)

**Comment by yilikun** [comment]
axios源码里并不能找到config，但是能不能有其他办法在前端解决呢？
