### ISSUE TITLE
导入excel几百条数据，显示需要分页展示，element-ui table静态数据如何分页展示？

### ISSUE THREAD

**Issue by Samdyddd** [PanJiaChen/vue-element-admin#1050]

**Comment by PanJiaChen** [comment]
这自己前端处理一下不就好了。

你可以借鉴一下这个
https://github.com/PanJiaChen/vue-element-admin/blob/fa54b927f7cce4a6d2aa21746e3b78d7c9bfc28a/src/mock/article.js#L46
