### ISSUE TITLE
3.8.1后新增的刷新按钮，能做到真正的刷新么?

### ISSUE THREAD

**Issue by jiuwuxiaohun** [PanJiaChen/vue-element-admin#1051]
分析了下代码，发现这个还是只执行了activated的钩子。

按照原理：点击了刷新标签，我再对应的位置遍历这个this.$store.state.tagsView.cachedViews数据，的确是将被刷新组件的name移除了，所以AppMain里面include应该是会生效的才对，，但是实际测试，还是按照keep-alive的流程走的，并没有执行到created钩子上。。

<keep-alive :include="cachedViews">
      <router-view :key="key"/>
    </keep-alive>
-----------
老大，确认测试下这个功能到底有没有问题啊。
-----------------------
我去，写到一半的时候，突然想到了数据没有及时更新的问题导致的。。。然后。。就测试成功了。。。如下，刷新这里需要用到nextTick，就可以了。

```js
    refreshSelectedTag(view) {
      this.$store.dispatch('delCachedView', view).then(() => {
        const { fullPath } = view
        this.$nextTick(() => {
          this.$router.replace({
            path: '/redirect' + fullPath
          })
        })
      })
    }
```

**Comment by jiuwuxiaohun** [comment]
嘿嘿。。果然是非正式发布版本不能随便同步啊。。不过等你们发布了新版本，我这边也会手动对比同步的。。

**Comment by PanJiaChen** [comment]
首先讨论一下这个问题，我并没有发现有什么bug，能再详细描述一下bug重现的过程么？

其次，如果真的是有bug，我表示不好意思了，因为本项目是个人项目，所以会有不少问题，所以需要不少热心开源社区的小伙伴一起发现问题和解决问题。

**Comment by jiuwuxiaohun** [comment]
//我是菜鸟,才用vue几天,可能提出的问题根本不是问题.

//我是把3.8.1的项目二次开发了,然后再使用ide工具同步你这边的最新版本的文件差异,新增的功能tag刷新按钮,路由是经过了跳转,看代码你这边是通过 delCachedView 把组件name从缓存白名单数组里删除了,可能vue还没有来得及刷新数据,然后由马上路由到了 path: '/redirect' + fullPath  ,keep-alive组件还是缓存的之前的组件name数组,所以导致组件没有执行created,还是和之前有缓存一样.----然后加上nextTick()刷新了数据之后再执行路由跳转,就可以执行到created了.
 
refreshSelectedTag(view) {
  this.$store.dispatch('delCachedView', view).then(() => {
	const { fullPath } = view
	this.$nextTick(() => { //新增的一行
	  this.$router.replace({
		path: '/redirect' + fullPath
	  })
	}) //新增的一行
  })
}

//谢谢你提供的这个项目给我们使用..

**Comment by PanJiaChen** [comment]
恩，思考了一下是有可能出现这个问题，`this.$nextTick`更为的靠谱。能提一个 `pull request`么？
