### ISSUE TITLE
有关点击相关链接在顶部出现 的问题

### ISSUE THREAD

**Issue by mhxy13867806343** [PanJiaChen/vue-element-admin#1052]
现在的问题是这样的，当我点击编号下面的110时，如下

 当我点击110的时候，会在导航栏处，会多增加一个导航（这个情况我是不需要的）
如下 图1
![12345](https://user-images.githubusercontent.com/4418166/45109980-9725ea80-b173-11e8-8f12-f2ba4c672890.png)

图2
![77777](https://user-images.githubusercontent.com/4418166/45110021-b58be600-b173-11e8-96a2-c7478e043ca3.png)

我需要的是，当点击110的那个编号时，只出现一个只出现一个线路详情的标签，就算再点编号为110的，就只显示一个标签页，请问，有什么办法解决下这个BUG嘛

**Comment by PanJiaChen** [comment]
我不知道我有没有正确理解你的问题，你想要的是，点击一个110，顶部tagsView里面不新增一个tag？

其实就是提供一种不在tagsview里面显示的方法？

**Comment by mhxy13867806343** [comment]
@PanJiaChen 是这样的，我这边要做的是110那号，会跳转到另一个页面（会传递参数过去的），会在顶部添加一个tab菜单，让用户进行相关的操作工作
