### ISSUE TITLE
移动端浏览器样式问题

### ISSUE THREAD

**Issue by airclear** [PanJiaChen/vue-element-admin#1053]
![image](https://user-images.githubusercontent.com/4103690/45138587-8a3ee080-b1df-11e8-80e8-d999ee1b6bbb.png)

**Comment by PanJiaChen** [comment]
的确兼容的不是很好，我来优化一下。

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/1065
