### ISSUE TITLE
vue-cli3.0里如何将svg-sprite-loader配置到vue.config.js?

### ISSUE THREAD

**Issue by Dog-Lee** [PanJiaChen/vue-element-admin#1056]
最近尝试迁移到vue-cli3.0。迁移的过程遇到一个问题。
```
chainWebpack: config => {
    config.module
      .rule('svg')
      .test(/\.svg$/)
      .include
        .add('src/icons')
        .end()
      .use('file-loader')
        .loader('svg-sprite-loader')
        .options({
          symbolId: 'icon-[name]'
        })
      .end();
```
不知道这样的配置是否正确，svg图标一直显示不出来。

麻烦了，谢谢。

**Comment by Dog-Lee** [comment]
命令行出现很多warn
```
 warning  in ./src/icons/svg/theme.svg

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
```

**Comment by Armour** [comment]
@Dog-Lee D #980

**Comment by Dog-Lee** [comment]
Thanks

**Comment by ZacharyRZ** [comment]
> Thanks

能告知一下解决了嘛 看来上面的issue还是不行。不报错界面就是出不来。。然后
const svgRule = config.module.rule('svg')
        svgRule.uses.clear()
        svgRule
            .include.add(resolve('src/icons')).end()
            .use('file-loader')
            .loader('svg-sprite-loader')
            .options({ symbolId: 'icon-[name]' })
会跟bootstrap fontawsome冲突 删除以后跟你一样报了很多这样的错 
warning  in ./src/icons/svg/theme.svg

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
望告知

**Comment by PanJiaChen** [comment]
cli3 遇到问题最好的解决方案 是 `vue inspect`看一下 具体配置是什么。

**Comment by ZacharyRZ** [comment]
> cli3 遇到问题最好的解决方案 是 `vue inspect > output.js`看一下 具体配置是什么。

Thanks。 低级了。之前也看了但是没想到是路径的问题。 return path.join(__dirname, '..', dir)多了一层。
