### ISSUE TITLE
tagsView 界面数据刷新机制

### ISSUE THREAD

**Issue by lixing0323** [PanJiaChen/vue-element-admin#1057]
我使用了tagsView 发现有一个问题：
我有一个edit的界面，里面这样写的。
```js
created() {
    // 获取id
    this.bladeId = this.$route.params.id;
    if (this.bladeId) {
      getBlade(this.bladeId).then(data => {
        console.log(data);
      });
    }
  }
```
从list进入是 1/edit的路由进入，在编辑状态下去获取数据进行填充数据。突然发现，如果在不关闭此编辑界面的状态下，再打开另一个2/edit的界面，由于有tagsView，会重新打开一个新的编辑界面，但是不会触发created()生命周期。请问如何解决？

**Comment by PanJiaChen** [comment]
`keep-alive` 机制导致。

看你想不想要缓存页面，如果不想的话，定义路由的时候加上 `noCache:true`

如果还是想要缓存的话，可以换一个钩子执行这段代码 [activated](https://cn.vuejs.org/v2/api/index.html#activated)

**Comment by lixing0323** [comment]
@PanJiaChen 我用了。
 path: ':id/edit',
        component: () =>
          import ('@/views/blade/edit'),
        name: 'bladeEdit',
        meta: {
          title: 'edit',
          noCache: true
        },
        hidden: true
但是只是解决了打开新的编辑界面的问题。如果同时开2个编辑界面，然后点tagsView上的title标签来切换界面，还是不会触发created()生命周期。我看了你的例子，你的就不会出现这问题，但是不知道你如何解决的。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/62fb5d1e148eadb99ae4aab81deca5f75798f4b6/src/views/layout/components/AppMain.vue#L5

加上合适的key

**Comment by lixing0323** [comment]
@PanJiaChen 额，我看到了。。以前我去掉了，但是不知道是出于什么目的，应该是有bug。。。才去掉的。。。加上这个Key会有啥后遗症没？

**Comment by PanJiaChen** [comment]
稍微多耗点性能，但可以忽略不计

**Comment by lixing0323** [comment]
@PanJiaChen ok，谢谢啦，非常感谢能及时解答。
