### ISSUE TITLE
现在遇到一个难点，关于不同管理员登录后导航和能进入的路由和按钮级别的权限问题，看看大家有没好的解决方案

### ISSUE THREAD

**Issue by fanerge** [PanJiaChen/vue-element-admin#106]
项目中的不同管理员都是通过超级管理为它们授予不同的权限（路由权限和按钮级的权限）通过新创建管理员账号为其选择类似于树状的权限分布，由于管理员级别太多，不能采用预设路由，我应该怎么为不同管理元分配路由和改变左侧导航。

**Comment by PanJiaChen** [comment]
你在后台做一个可视化编辑权限的页面，把这个树形结构存在后端。
 前端登录后(后端或者前端)根据前面存的树形结构判断当前用户有哪些权限 之后就是addRoutes 和正常的预授的模式没什么区别了

**Comment by fanerge** [comment]
意思是说，我在web管理系统中创建一个可视化权限编辑页面，并把创建的管理员权限树发送给后端，当该管理员登录时，再获取该管理员的权限树，然后在利用addRoutes添加路由吗？

**Comment by sunchenguang** [comment]
这是超级管理员来动态控制不同低级管理员的权限了，肯定要有个页面来做。
登录用户 -> role -> 路由和按钮权限

路由和按钮权限 这个数据结构最好自己定义，发给后端存储。
前端获取到该数据后自行解析出 需要`addRoutes`的路由表

左侧导航是根据路由表自动生成的，更新路由表即可

如果搞定了希望发个 `PR` ,丰富这个项目

**Comment by fanerge** [comment]
好的，谢谢
