### ISSUE TITLE
关于table的扩展应用

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#1060]
@PanJiaChen 潘神，
关于Table有没按住shift 或者ctrl 选中后，对选中行分组的深入应用实例？

**Comment by PanJiaChen** [comment]
没太懂具体需求。

**Comment by moonose** [comment]
就是键盘按shift 或者ctrl 后，选中table里的行记录，然后对这些行组合下，分组后类似tree table效果

**Comment by PanJiaChen** [comment]
暂时不考虑添加这种比较特殊的功能。
