### ISSUE TITLE
关于本地代理问题，

### ISSUE THREAD

**Issue by wlLeblanc** [PanJiaChen/vue-element-admin#1063]
请问一下，大佬们，我在本地做了反向代理以后，怎么老是报404错误！
![image](https://user-images.githubusercontent.com/22288871/45195425-0e4da280-b28a-11e8-922f-8eb225c19e7c.png)
调第一个接口的不会报404错误，调第二个接口就会报404错误！
以下是调用接口
![image](https://user-images.githubusercontent.com/22288871/45195455-3d641400-b28a-11e8-8ea8-4292d94ac17a.png)

**Comment by kaisawind** [comment]
代理重写路径的时候，你把CPSI重写成了空。你可以把调用接口时的CPSI去掉试试。

**Comment by wlLeblanc** [comment]
@kaisawind @GitHdu   谢谢这个问题已经解决了

**Comment by zrleo** [comment]
@wlLeblanc 请问怎么解决的跨域问题

**Comment by wlLeblanc** [comment]
@zrleo 你可以做本地代理，但是大部分由后端来解决！代理如上就可以了

**Comment by zrleo** [comment]
@wlLeblanc 本地代理如何坐呢 
![image](https://user-images.githubusercontent.com/21098426/45219106-67462680-b2dc-11e8-9c30-d5cf8ecacbb2.png)
![image](https://user-images.githubusercontent.com/21098426/45219126-77f69c80-b2dc-11e8-8c2d-a837e24d727d.png)
会提示404
