### ISSUE TITLE
gitlab上编译失败的问题

### ISSUE THREAD

**Issue by cocoxiang** [PanJiaChen/vue-element-admin#1064]
1.在本地windows上build成功 

2.服务器上build 报错： “sh: cross-env: 未找到命令”

`build: "cross-env NODE_ENV=production env_config=dev node build/build.js"`

**Comment by PanJiaChen** [comment]
你需要在服务器上安装 `cross-env`

如果你是linux，则可以去掉`cross-env`

直接 `build: "NODE_ENV=production env_config=dev node build/build.js"`
