### ISSUE TITLE
菜单层级问题

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#1066]
@PanJiaChen 

目录结构是“
view
&nbsp;&nbsp;&nbsp;&nbsp;|___ menu1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |____menu11
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;abc1.vue
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;abc2.vue
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |____menu12

代码如下：

     {
       path: '/menu1,
       component: Layout,
       redirect: 'noredirect',
       name: 'menu1',
       meta: { title: 'menu1', icon: menu1', noCache: true },
       children: [
         {
           path: 'menu11',
           name: 'menu11',
           meta: { title: 'menu11', icon: 'menu11' },
           redirect: 'noredirect',
           children: [
                  { name: 'menu111', path: 'menu111', component: () => import('@/views/menu1/menu11/abc1), meta: { title: 'a1', icon: 'a1' }},
                  { name: 'menu112', path: 'menu112', component: () => import('@/views/menu1/menu11/abc2'), meta: { title: 'a2', icon: 'a2' }}
            ]
          },
          {
            path: 'menu12',
            name: 'menu12',
            meta: { title: 'menu12', icon: 'menu12' }
           }
      ]
}

第二层menu11如果没有定义component: 点击 menu111 menu112 都没效果，这是什么原因？
如果 第二层menu11 加上 component: Layout, 那会引起界面嵌套了。

**Comment by PanJiaChen** [comment]
正常现象，请阅读[文档](https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/new-page.html#%E5%A4%9A%E7%BA%A7%E7%9B%AE%E5%BD%95-%E5%B5%8C%E5%A5%97%E8%B7%AF%E7%94%B1)

> 原则上有多少级路由嵌套就需要多少个<router-view>
