### ISSUE TITLE
Feature:  add settings.js

### ISSUE THREAD

**Issue by PanJiaChen** [PanJiaChen/vue-element-admin#1068]
Adding a `settings.js` file allows the user to simply modify the settings to change the effect, instead of requiring the user to modify the code.

**Comment by PanJiaChen** [comment]
Like 

```js
const defaultSettings = {
  lang: 'zh', 
  size: 'medium', 
  permission: true,
  tagsView: true,
  i18n: true,
  viewTransition: 'fade-transform'
}
```

**Comment by ifu25** [comment]
size 设置成 mini 时 Table 下面和分页之间会留下空白。
![20180908104845360](https://user-images.githubusercontent.com/5575008/45249583-600f2f00-b355-11e8-85a9-cdc933f255f5.png)

**Comment by PanJiaChen** [comment]
@ifu25 请关注 https://github.com/PanJiaChen/vue-element-admin/issues/1080

**Comment by PanJiaChen** [comment]
topbar fixed options

**Comment by PanJiaChen** [comment]
logo in sidemenu

**Comment by 1049759078** [comment]
请问下这个settings.js文件在哪个目录下新建呢 @PanJiaChen

**Comment by PanJiaChen** [comment]
有什么区别么？

**Comment by PanJiaChen** [comment]
does not need lang

**Comment by PanJiaChen** [comment]
Double-click the sidebar to refresh the page

**Comment by PanJiaChen** [comment]
Branch https://github.com/PanJiaChen/vue-element-admin/pull/1180
