### ISSUE TITLE
请问下，关于用户登录问题！

### ISSUE THREAD

**Issue by wlLeblanc** [PanJiaChen/vue-element-admin#1069]
请问下潘神大佬，
![image](https://user-images.githubusercontent.com/22288871/45218078-dd488e80-b2d8-11e8-8bd6-4e6b092025e3.png)这里只验证了两个用户，我新建的其他用户就不能登录进入首页，
![image](https://user-images.githubusercontent.com/22288871/45218269-973ffa80-b2d9-11e8-80ab-9952c27c424e.png)

这些用户是从后台获取来？，还是说可以不用验证？

**Comment by ifu25** [comment]
我觉得用户名密码这里可以不用客户端验证，等提交时在服务端验证就行了。

**Comment by LiuZiqi-dual** [comment]
完全在服务器端验证会大大增加服务器负荷吧，正常项目应该是前后端结合验证来的，前台过滤一遍，服务器端再验证一遍

**Comment by wlLeblanc** [comment]
@PanJiaChen @LiuZiqi-dual @ifu25 谢谢几位大佬的解答，我有一个问题还想问一下几位大佬，为什么我不调用这个就不能进入首页？
![image](https://user-images.githubusercontent.com/22288871/45273322-c37b9700-b4e4-11e8-8ac6-3da5d4976f0b.png)

**Comment by PanJiaChen** [comment]
请看 LoginByUsername 做了什么。他设置了 `token`，而这个`token`是前端权限校验的一个关键值。当然这只是一个demo，你也可以根据自己的业务调整逻辑。



https://github.com/PanJiaChen/vue-element-admin/blob/ed4427243daa37c8c4480170926c970a34706262/src/permission.js#L21
