### ISSUE TITLE
[vue-router] uncaught error during route navigation:

### ISSUE THREAD

**Issue by edwinhuish** [PanJiaChen/vue-element-admin#107]
请问下面这种错误是怎么造成的呢？按照浏览器的提示是 ``` next(to.path); ```` 这个代码抛出的错误？

![image](https://user-images.githubusercontent.com/5207925/27769792-8e697f54-5f64-11e7-8b7e-4049428b2e0f.png)

**Comment by edwinhuish** [comment]
已解决

**Comment by reactionic127** [comment]
@edwinhuish 
what was your issue?
I am having same issue right now.
