### ISSUE TITLE
能否支持鼠标中键关闭 Tab 页？

### ISSUE THREAD

**Issue by ifu25** [PanJiaChen/vue-element-admin#1071]
就像浏览器的标签页一样，鼠标中键关闭非常方便，主要是用习惯了，我公司的 WinForm 产品也是这种体验，对用户来说体验一致也比较重要，非常感谢。
![20180908110218934](https://user-images.githubusercontent.com/5575008/45249667-ab760d00-b356-11e8-8ec9-c085d0d58f04.png)

**Comment by PanJiaChen** [comment]
我也是第一次知道游览器有这个功能。。。

**Comment by PanJiaChen** [comment]
Added in https://github.com/PanJiaChen/vue-element-admin/pull/1149
