### ISSUE TITLE
treeTable子节点异步获取

### ISSUE THREAD

**Issue by Big-xiong** [PanJiaChen/vue-element-admin#1072]
点击父节点的时候才异步获取相应的子节点

**Comment by PanJiaChen** [comment]
暂时没有时间搞 treeTable 相关问题，@leij1ang 不知道你可以帮忙回答一下么？

**Comment by leij1ang** [comment]
我最近也比较忙，进度可能会慢点

**Comment by Big-xiong** [comment]
好的，自己改了代码，也可以了

**Comment by mjj137993394** [comment]
@Big-xiong 我也有这样的需求 请问你是怎样实现的

**Comment by Big-xiong** [comment]
@mjj137993394  ![image](https://user-images.githubusercontent.com/25559286/45332744-ff763100-b5a4-11e8-9ae4-88b998e2e661.png)
点击的时候请求子节点，判断当前父节点有没有children字段，我这里改成sonPermission了，如果没有就给当前父节点对象添加children属性，并使用 Utils.MSDataTransfer.treeToArray()将data重新转成treeArray,然后watch data的变化

**Comment by mjj137993394** [comment]
@Big-xiong 嗯嗯 谢谢

**Comment by qwe1234579** [comment]
@Big-xiong 刚开始学这块，不是很懂，方便把改过后得代码发一份看看么

**Comment by PanJiaChen** [comment]
`element` 2.7.0 支持 `tree-tale 了`。所以 `vue-element-admin`就不再自己维护 `tree-table`了。
