### ISSUE TITLE
leaflet not rendering properly 

### ISSUE THREAD

**Issue by rahimramezanian** [PanJiaChen/vue-element-admin#1076]
## How to produce problem

I added a view as follows 

src -> views -> leaflet -> index.vue

```node
<template>
  <div id="app" class="container">
    <l-map :zoom="zoom" :center="center" style="height: 500px">
      <l-tile-layer :url="url" :attribution="attribution"/>
      <!--l-marker :lat-lng="marker"></l-marker-->
    </l-map>
  </div>
</template>

<script>
/* eslint-disable */
import { LMap, LTileLayer, LMarker } from 'vue2-leaflet';
export default {
  name: 'example',
  components: {
    LMap,
    LTileLayer,
    LMarker
  },
  data () {
    return {
      zoom:13,
      center: L.latLng(47.413220, -1.219482),
      url:'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
      attribution:'&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
      // marker: L.latLng(47.413220, -1.219482),
    }
  }
}
</script>
```

and a new route for that
```node
  {
    path: '/leaflet',
    component: Layout,
    redirect: '/leaflet/leaflet_part',
    alwaysShow: true,
    meta: { title: 'leaflet', icon: 'map' },
    children: [
      {
        path: 'leaflet_part',
        component: () => import('@/views/leaflet/index'),
        name: 'Leaflet_Map',
        meta: { title: 'Leaflet_Map' }
      }
    ]
  },
```
The example is from

https://github.com/KoRiGaN/Vue2Leaflet/blob/master/examples/src/components/Simple.vue

## Problem

The leaflet map is not rendering properly. The tiles are not in the correct place.

![screenshot from 2018-09-09 10-40-17](https://user-images.githubusercontent.com/15890835/45261648-d88cf300-b41c-11e8-877f-cc6d2498d224.png)

The example works fine in 'Vue2Leaflet' demo at (https://korigan.github.io/Vue2Leaflet/)

![screenshot from 2018-09-09 10-43-06](https://user-images.githubusercontent.com/15890835/45261687-3cafb700-b41d-11e8-88f3-a4dbd751a220.png)

**Comment by PanJiaChen** [comment]
Not `vue-element-admin` bug

Please add `import "leaflet/dist/leaflet.css";`

**Comment by PanJiaChen** [comment]
https://github.com/KoRiGaN/Vue2Leaflet/issues/157#issuecomment-384307765
