### ISSUE TITLE
我在使用keep-alive遇到问题 请教一下

### ISSUE THREAD

**Issue by hanzhenchaoGit** [PanJiaChen/vue-element-admin#1078]
我现在想着是切换tab页的时候每次打开的页面是上次缓存的页面  但是关闭tab之后应该是没有缓存的页面 应该是一个打开的新页面 我现在是直接把AppMain里的路由包在了keep-alive里 没有做限制  所有页面都缓存 但是在关闭tab后再点击菜单 打开的还是上次缓存的页面 我想问一下这个问题大概出在哪里  我看您的代码里也并没有做多余的处理 就是在路由中加了一个是否缓存的meta 在keep-alive上做的限制 有点搞不懂 到底是出了什么问题  该如何下手

**Comment by hanzhenchaoGit** [comment]
![image](https://user-images.githubusercontent.com/20226394/45265558-571a7c80-b47f-11e8-9c91-cc153959a915.png)
![image](https://user-images.githubusercontent.com/20226394/45265613-34d52e80-b480-11e8-8b3b-d55ee4a7a66e.png)
图2两个页面是用的同一个表单组件 只是挂载到不同的路由上 加上keep-alive之后在切换两个tab时不丢失上次操作的数据  能正常缓存 但点击关闭tab后 再重新打开 还是上次缓存的数据 您的例子就不是这样的  请问这是什么原因呢

**Comment by PanJiaChen** [comment]
使用 keep-alive 的 include 。

调试的话请使用 vue-devtool，能很清楚的知道现在缓存了什么实例。

![image](https://user-images.githubusercontent.com/8121621/45273417-3be25800-b4e5-11e8-9bc1-0da9d93dbc94.png)
