### ISSUE TITLE
左侧菜单栏底部没占满

### ISSUE THREAD

**Issue by 1049759078** [PanJiaChen/vue-element-admin#1079]
![image](https://user-images.githubusercontent.com/24266098/45266399-36592380-b48d-11e8-98f3-38eab85f5634.png)
衩库大大，左侧菜单栏底部高度没占满，新学vue，这么需要改哪部分样式呀，感谢

**Comment by PanJiaChen** [comment]
windows？ 什么游览器？

**Comment by 1049759078** [comment]
windows10 ,Chrome浏览器

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-admin-template/commit/e6271665405925b62e63d25e9562c8563e7d6ba9

**Comment by 1049759078** [comment]
Thanks♪(･ω･)ﾉ
