### ISSUE TITLE
打包的时候特别慢，有啥优化方案吗？

### ISSUE THREAD

**Issue by sunlanlisa** [PanJiaChen/vue-element-admin#108]
有两个问题：
1、webpack打包特别慢，差不多得至少30s，这对于要打包上测试和上线都特别麻烦。vendor.js 也特别的大，整体下来600多kb
2、每次打包的时候，它都会把dist文件删除，然后再生成。对于svn和git的上传更新，也是有点小麻烦。另外有一部分静态文件，比如图片和样式啥的，不想再打包和压缩，这种怎么处理哦？

**Comment by PanJiaChen** [comment]
讲道理30s不算慢的了，
如果还想优化的的话可以用externals 把vendor剔除，或者使用dll.
推荐阅读webpack优化相关文章https://segmentfault.com/a/1190000007891318

**Comment by sunlanlisa** [comment]
好的，今天问了另外的朋友，说他们打包都要几分钟，吓坏宝宝了

**Comment by upcwangying** [comment]
我的项目打包84分钟，8个项目整成了一个项目，我正在优化

**Comment by daiing** [comment]
> 我的项目打包84分钟，8个项目整成了一个项目，我正在优化

请教有优化方案吗，我这边打包要要50分钟左右

**Comment by upcwangying** [comment]
> > 我的项目打包84分钟，8个项目整成了一个项目，我正在优化
> 
> 请教有优化方案吗，我这边打包要要50分钟左右

我这边升级了依赖包就可以了，几分钟搞定

**Comment by daiing** [comment]
@upcwangying 能告知下升级了哪个依赖包改善的嘛，万分感谢啊

**Comment by upcwangying** [comment]
@daiing vue-cli相关的依赖

**Comment by liuxuey123** [comment]
> > 我的项目资源84分钟，8个项目整合成了一个项目，我正在优化
> 
> 请教有优化方案吗，我的雷达预算要50分钟左右

你好 请问打包解决了吗 我这边打包要1小时，重新下载依赖依旧很慢

**Comment by liuxuey123** [comment]
> [@daiing](https://github.com/daiing)vue-cli 相关的依赖

你好 请问之前vue-cli 相关的依赖是哪个版本呀，升级到了哪个版本就快了呀
