### ISSUE TITLE
在select选择器中，中英文切换不起作用

### ISSUE THREAD

**Issue by bobinshen** [PanJiaChen/vue-element-admin#1082]
裤衩大，在select选择器中，中英文切换不起作用，在script中配置如下：
  operationList: [
          {
            value: 'deleteSelected',
            label: this.$t('users.deleteSelected')
          },
          {
            value: 'updateSelected',
            label: this.$t('users.updateSelected')
          },
          {
            value: 'forbidSelected',
            label: this.$t('users.forbidSelected')
          },
          {
            value: 'activeSelected',
            label: this.$t('users.activeSelected')
          }
        ]

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/i18n.html#js-%E4%B8%AD%E4%BD%BF%E7%94%A8-t

https://github.com/PanJiaChen/vue-element-admin/commit/fbb3641406750740140a146a329448c608dfff3b

**Comment by bobinshen** [comment]
可以了，谢谢！

**Comment by buddy-lin** [comment]
可以将operationList放到computed，但面临一个问题，初始值中英文切换不激活
