### ISSUE TITLE
侧边栏当子路由只有一个的时候会直接显示 而不显示父级

### ISSUE THREAD

**Issue by mc7qing** [PanJiaChen/vue-element-admin#1084]
请问我该怎么做 让他始终显示呢

**Comment by PanJiaChen** [comment]
alwaysShow

请查看文档。

**Comment by mc7qing** [comment]
//你可以设置 alwaysShow: true，这样它就会忽略之前定义的规则，一直显示根路由
alwaysShow: true
 
不好意思  没看到
