### ISSUE TITLE
你好，请问一下tagsView多标签组件打开新页签--添加路由数据时怎样可以随时带着自己传的参数

### ISSUE THREAD

**Issue by daisty** [PanJiaChen/vue-element-admin#1086]

**Comment by daisty** [comment]
是一些编辑页面需要传一些列表的参数，tagsView多标签组件打开新页签时会把路由后面带的参数丢失，怎样在多标签组件里面动态添加需传的参数

**Comment by PanJiaChen** [comment]
我试了下并无问题，参数并未丢失。

**Comment by PanJiaChen** [comment]
你列表是否提前渲染过？
就是列表是否会在编辑页之前就已经渲染过了？

**Comment by daisty** [comment]
是的，已经渲染过了，是重新点击之前打开的那个编辑页，会把从列表传的参数丢失

**Comment by PanJiaChen** [comment]
这不能算丢失，算没更新。因为你这是在菜单栏上的tag是你之前渲染的，并不是你带参数那个。

**Comment by daisty** [comment]
是的，为什么没有更新呢？一开始点击正常，如果再点一次tag view上的标签页就会发现之前的参数没了，直接报400

**Comment by daisty** [comment]
我想就是从路由中传过去的参数一直都能保存在url上

**Comment by PanJiaChen** [comment]
Added in https://github.com/PanJiaChen/vue-element-admin/pull/1090

**Comment by daisty** [comment]
谢谢

**Comment by marscj** [comment]
@daisty 
`
<router-link :to="{ path: '/your_path', query: { time: now }, params: { edit: id } }" />
`
