### ISSUE TITLE
默认采用cli-service构建如何？

### ISSUE THREAD

**Issue by guoguolong** [PanJiaChen/vue-element-admin#1087]
Cli Service的“零配置”目标确实中我下怀，如果基于Cli Service，当前vue-element-admin的build、config目录、package.json 中devDependencies中大部分包依赖都不再需要，东西少则心静

JiaChen，你怎么看？

**Comment by PanJiaChen** [comment]
Duplicate of #932

**Comment by guoguolong** [comment]
COOL
