### ISSUE TITLE
keep-alive三级路由就无法加入缓存

### ISSUE THREAD

**Issue by heixin8** [PanJiaChen/vue-element-admin#1094]
cachedViews里有name
但不起反应
是不是keep-alive的bug

**Comment by PanJiaChen** [comment]
已知问题，暂时没太多精力修复。

Duplicate of #700

**Comment by heixin8** [comment]
好的，谢谢

**Comment by gaibian** [comment]
> 已知问题，暂时没太多精力修复。
> 
> Duplicate of #700

有没有什么思路啊，可以先说下哈
