### ISSUE TITLE
登陆页跳转不了到其他页面（比如：注册，忘记密码等公共页面）

### ISSUE THREAD

**Issue by leevane** [PanJiaChen/vue-element-admin#1095]
1、登陆页跳转不了到其他页面（比如：注册，忘记密码等公共页面）
描述：登陆页里面增加一个注册链接，在constantRouterMap里面配置了注册路由的。为什么在登录页面点击调整注册页面不行？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/3277343804f15e6f916122aca2e125ec3722d261/src/permission.js#L17

不需要登入进入的页面，请加入到白名单。

**Comment by javeyG** [comment]
登录之后跳转到其他页面而不是首页，怎么实现
