### ISSUE TITLE
该项目是否没有更新你的文章（升级webpack4）里面说的优化分包策略？

### ISSUE THREAD

**Issue by LuoChengIo** [PanJiaChen/vue-element-admin#1097]
我把项目下载下来。使用npm run build:prod --report命令查看的时候，发现elementui打包进入了chunk-libs里面。并没有单独独立出来，并且与你文章里面查看的 bundle-report不一致。。。
![bef47a5c-f6ec-4ecb-a572-160c26698b8e](https://user-images.githubusercontent.com/28758234/45422985-79510c00-b6c4-11e8-9c27-e733c94eec74.png)

**Comment by PanJiaChen** [comment]
我本地和线上都没有遇到你所说的问题。
https://panjiachen.gitee.io/vue-element-admin/bundle-report

**Comment by LuoChengIo** [comment]
我的环境，另外我也直接下载你的项目的，并没有做修改。。。我再试试看是不是cnpm的原因
![6b080c13-d99d-4ee8-a6a5-0fba498cd81c](https://user-images.githubusercontent.com/28758234/45424182-43158b80-b6c8-11e8-91a6-294fa681e7d0.png)

**Comment by LuoChengIo** [comment]
@PanJiaChen 解决了，把cnpm i 换成npm i 下载包文件就好了 😒，真郁闷。。。

**Comment by PanJiaChen** [comment]
cnpm 会有各种诡异的问题。
