### ISSUE TITLE
顶部栏目是否可以固定？

### ISSUE THREAD

**Issue by MichaelXcy** [PanJiaChen/vue-element-admin#1098]
请问一下，中间内容展示区域，如果内容比较多，会有滚动条，当移动滚动条时，顶部会跟随页面内容一起移出去屏幕了，如果要实现固定这个顶部区域，只是中间内容区域可以滚动出去屏幕外面，如何实现？

**Comment by PanJiaChen** [comment]
下个版本会增加顶部固定的配置项。
https://github.com/PanJiaChen/vue-element-admin/issues/1068

现在的话，自行改css实现。
