### ISSUE TITLE
tab标签页的问题

### ISSUE THREAD

**Issue by xujiale** [PanJiaChen/vue-element-admin#110]
打开页面A后打开页面B，点击tab重新打开页面A后原来的状态未保存

**Comment by PanJiaChen** [comment]
能再具体一点么 没有太了解

**Comment by sunchenguang** [comment]
后台只有user和app配置相关状态使用vuex存在全局，其它数据都由每个业务页面自己管理。
切换页面数据自然又变成初始数据
