### ISSUE TITLE
很多东西都看不懂，谁能讲解一下下面的问题

### ISSUE THREAD

**Issue by BlythDD** [PanJiaChen/vue-element-admin#1100]
好吧，刚才不晓得为啥，。这个中英文切换怎么做到的？没有找到相关的方法，另外，在这个login/index.vue里面，{{ $t('login.title') }}是什么东西？没看到data有关login的字段；<el-form-item prop="username">的username又是从哪里来的数据

**Comment by PanJiaChen** [comment]
$t vue-i18n

https://github.com/PanJiaChen/vue-element-admin/tree/master/src/lang
