### ISSUE TITLE
tagsView 缓存消失

### ISSUE THREAD

**Issue by lixing0323** [PanJiaChen/vue-element-admin#1102]
我的工程加了tagsView，但是没有缓存效果。比如在下面这个list界面，并没有设置noCache: true，但是没有缓存效果。

    path: '/blade',
    component: Layout,
    redirect: '/blade/list',
    name: 'blade',
    meta: {
      title: 'blade'
    },
    children: [{
        path: 'list',
        component: () =>
          import ('@/views/blade/list'),
        name: 'bladeList',
        meta: {
          title: 'blade',
          fa: 'fa fa-leaf',
          noBreadcrumb: true
        }
      }]

appMain.vue 也是这样写的。

 <keep-alive :include="cachedViews">
        <router-view :key="key" />
      </keep-alive>

**Comment by stevenYangx** [comment]
解决了吗？
