### ISSUE TITLE
请问下如何按照Element官方的Container 布局容器方式调整整体的框架布局？

### ISSUE THREAD

**Issue by MichaelXcy** [PanJiaChen/vue-element-admin#1104]
请问下如何按照Element官方的Container 布局容器方式调整整体的框架布局？
比如我想实现的是：顶部header布局水平方向占满，然后header下方是左右方向布局，左边是slider_container，右边是main_container？

**Comment by PanJiaChen** [comment]
特殊需求，自行实现。
