### ISSUE TITLE
请教一个项目部署到服务器的问题

### ISSUE THREAD

**Issue by wakaryry** [PanJiaChen/vue-element-admin#1105]
我练习了个项目，有给用户看的前端页面，也有管理用的后台页面，前端页面我是用bootstrap写的，他们是在服务端直接使用我用来编写后台的框架来进行渲染的。所以这是我的一个服务器，用来支撑数据和前端页面。地址是：`0.0.0.0:8000`。

然后就是后台管理页面，我这些页面是用`vue-element-admin`写的，我在本地开的是dev，`npm run dev`，用的地址是：`0.0.0.0:8081`。

我想统一使用一个地址来访问。于是我设置了`nginx`监听8080端口。

`location / `代理到：`0.0.0.0:8000`。
`location /admin`代理到 `0.0.0.0:8081`。

nginx用的是`localhost:8080`，
`localhost:8080`能够访问到我的`0.0.0.0:8000`，
但是`localhost:8080/admin`给我显示的只是一个空白的页面，也就是我们vue-element-admin中那个空白的`index.html`页面，为什么不是我直接打开`0.0.0.0:8081`的样子。

有谁这么操作过的，告诉我是怎么做的。
是不是我有什么点没有get到。

我是写IOS的，想自己撸一下看看。

感谢解答。

**Comment by nabaonan** [comment]
你的这个问题刚刚是我今天解决的，我记了一下，参考一下这个吧
http://nabaonan.top/note/front/vue/nginx一个域名部署多个vue项目.html

**Comment by wakaryry** [comment]
我本地开dev的是不是不能通过nginx代理转发。我打开就只是一个空白页面，没有vue渲染的内容。

**Comment by wakaryry** [comment]
是我这边配置可能有问题。
```
baseUrl: process.env.NODE_ENV === 'production' ?
    '/my-console/' : '/',
```

这个不知道在vue-element-admin哪里配置。

不然无法完成跳转，只是一个空白的index。

当我的后台管理页面配置为 `location /`， 而不是`location /admin`的时候我是可以渲染出vue的内容的：
```
location / {
            root /Users/wakaryredou/GitHub/web/invest/vue-element-admin;
            index index.html;

            proxy_pass http://node_server;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Scheme $scheme;
            # we don't want nginx trying to do something clever with
            # redirects, we set the Host: header above already.
            proxy_redirect off;
        }
```

但是一换成 `location /admin`，仅仅只是找到了`index.html`这个静态资源而已，没有任何vue渲染的内容。

**Comment by wakaryry** [comment]
我现在的问题就是想在vue-element-admin的项目url中添加一个admin。不知道在哪个文件配置哪个内容。

**Comment by wakaryry** [comment]
好吧。使用base添加了一个sub path:
```js
export default new Router({
  mode: 'history', // require service support
  base: '/admin/',
  scrollBehavior: () => ({ y: 0 }),
  routes: constantRouterMap
})
```

不过貌似在history模式下才生效。

**Comment by wakaryry** [comment]
我发现是我理解错误了。
vue项目的部署，利用nginx的话直接当作静态资源部署就OK了。
我还以为是像dev下一样有一个node服务器，然后代理到那个服务器下。

不过在dev模式下发现利用nginx代理node server的话，有很多问题需要注意，找不到app.js，所以显示的只是空白页面。

**Comment by wakaryry** [comment]
为什么我nginx一个location /，另一个location /admin，死活匹配不到/admin。老是匹配到location /的后台服务器，提示我url不存在。而/static这种却又能够匹配到。不知道是不是还需要配置什么。

而我单独只运行一个location的时候，能够正常nginx。

**Comment by wakaryry** [comment]
哎。整了一天了。还是没有整出来。

网上查了一堆，都是前后端分离的项目。只需要前台路由对外展示即可。

而我这个相当于双路由。一个是由服务器render的前台页面，这种不是前后端分离的，是利用后端框架对数据进行渲染的。

另一个是由vue构建的前后端分离的后台管理页面。

由服务器render的前台页面，包含了用户直接进入域名根目录看到的页面，不带任何的sub path。所以在nginx中，我必须为它设置为`location /`。

利用vue构建的后台管理页面，我给它一个sub path `admin`。在nginx中我设置为`location /admin`。

但是问题来了，竟然无法进入到vue的项目中去。

有谁操作过这种情况的，求指导一下。

懵懵懂懂的，希望指导。

**Comment by nabaonan** [comment]
location配置错了吧应该是/自定义/吧，精确的路径放到前面，还有我的那个笔记中有cli3的也有cli2的，cli2需要改3个地方

**Comment by wakaryry** [comment]
哎。vue的官方文档，是cli3的。这个是cli2的项目。

我是不是还需要在config/index.js中配置assetsPublicPath.

**Comment by wakaryry** [comment]
感谢。
现在可以访问了。

Mac 上nginx配置：

```nginx
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    upstream python_server {
        # fail_timeout=0 means we always retry an upstream even if it failed
        # to return a good HTTP response

        # for UNIX domain socket setups
        # server unix:/var/redou/redou.socket fail_timeout=0;

        # for a TCP configuration
        server 0.0.0.0:8000 fail_timeout=0;
    }

    server {
        listen       8080;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        location / {
            proxy_pass http://python_server;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Scheme $scheme;
            # we don't want nginx trying to do something clever with
            # redirects, we set the Host: header above already.
            proxy_redirect off;
        }

        location /static {
            alias /Users/wakaryredou/GitHub/web/invest/static;
            expires 30d;
        }

        location /media {
            alias /Users/wakaryredou/GitHub/web/invest/media;
            expires 30d;
        }

        location /admin {
            root /Users/wakaryredou/GitHub/vue-element-admin/dist;
            # it will look into admin folder
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
    include servers/*;
}

```

其它配置：
- 因为这是vue-cli2的项目，首先配置Webpack中config/index.js的`assetsPublicPath: '/admin/'`。如果是cli3的话，按照官方vue-cli3的配置vue.config.js中baseUrl即可。

- 然后配置router，添加base：
```js
export default new Router({
  mode: 'history', // require service support
  base: '/admin/',
  scrollBehavior: () => ({ y: 0 }),
  routes: constantRouterMap
})
```

- 还在index.html中添加了一个meta：`<meta base="/admin/">`

然后`npm run build:prod`。

- 将dist中打包好的包统一放入`admin`文件夹中（nginx应该指向这个文件夹的上级目录）.

- 配置nginx，并重启。

一切正常。

谢谢。

不过还有个问题就是history模式下，刷新url以及浏览器中输入url，会直接导致404.

**Comment by ResearchInstituteWeb** [comment]
> 感谢。
> 现在可以访问了。
> 
> Mac上nginx配置：
> 
> ```nginx
> worker_processes   1 ;
> 
> #error_log logs / error.log; 
> #error_log logs / error.log通知; 
> #error_log logs / error.log info;
> 
> #pid logs / nginx.pid;
> 
> events {
>      worker_connections   1024 ;
> }
> 
> 
> http {
>      include        mime.types;
>     default_type   application / octet-stream;
> 
>     #log_format main'$ remote_addr  -  $ remote_user [$ time_local]“$ request”' 
>     ＃'$ status $ body_bytes_sent“$ http_referer”' 
>     ＃'“$ http_user_agent”“$ http_x_forwarded_for”';
> 
>     #access_log logs / access.log main;
> 
>     sendfile        on ;
>     #tcp_nopush on;
> 
>     #keepalive_timeout 0; 
>     keepalive_timeout   65 ;
> 
>     #gzip on;
> 
>     上游 python_server {
>          ＃fail_timeout = 0表示我们总是重试上游，即使它失败
>         ＃也能返回一个好的HTTP响应
> 
>         ＃对于UNIX域套接字设置
>         #server unix：/var/redou/redou.socket fail_timeout = 0;
> 
>         ＃对于TCP配置
>         服务器 0.0.0.0:8000 fail_timeout = 0;
>     }
> 
>     服务器 {
>          listen        8080 ;
>         server_name   localhost;
> 
>         #charset koi8-r;
> 
>         #access_log logs / host.access.log main;
> 
>         ＃重定向服务器错误页面的静态页面/50x.html 
>         ＃
>         error_page    500  502  503  504   /50x.html;
>         location  = /50x.html {
>              root    html;
>         }
> 
>         location  / {
>              proxy_pass http：// python_server;
>             proxy_set_header主机$ http_host ;
>             proxy_set_header X-Real-IP $ remote_addr ;
>             proxy_set_header X-Forwarded-For $ proxy_add_x_forwarded_for ;
>             proxy_set_header X-Scheme $ scheme ;
>             ＃我们不希望nginx尝试使用#reireirects做一些聪明的事情
>             ，我们已经在上面设置了Host：标头。
>             proxy_redirect off ;
>         }
> 
>         location  / static {
>              alias / Users / wakaryredou / GitHub / web / invest / static;
>             到期 30d ;
>         }
> 
>         location  / media {
>              alias / Users / wakaryredou / GitHub / web / invest / media;
>             到期 30d ;
>         }
> 
>         location  / admin {
>              root / Users / wakaryredou / GitHub / vue-element-admin / dist;
>             ＃它将查看admin文件夹
>             索引 index.html;
>             try_files  $ uri  $ uri / /index.html;
>         }
>     }
>     包括服务器/ *;
> }
> ```
> 
> 其它配置：
> 
> * 因为这是vue-cli2的项目，首先配置Webpack中config/index.js的`assetsPublicPath: '/admin/'`。如果是cli3的话，按照官方vue-cli3的配置vue.config.js中baseUrl即可。
> * 然后配置router，添加base：
> 
> ```js
> export default new Router({
>   mode: 'history', // require service support
>   base: '/admin/',
>   scrollBehavior: () => ({ y: 0 }),
>   routes: constantRouterMap
> })
> ```
> 
> * 还在index.html中添加了一个meta：`<meta base="/admin/">`
> 
> 然后`npm run build:prod`。
> 
> * 将dist中打包好的包统一放入`admin`文件夹中（nginx应该指向这个文件夹的上级目录）.
> * 配置nginx，并重启。
> 
> 一切正常。
> 
> 谢谢。
> 
> 不过还有个问题就是history模式下，刷新url以及浏览器中输入url，会直接导致404.

nginx 配置中在location / 内容中增加一行，try_files $uri $uri/ /index.html;

location / {
  try_files $uri $uri/ /index.html;
}
