### ISSUE TITLE
关于文档里说的点击侧边栏刷新当前路由的方法

### ISSUE THREAD

**Issue by bluefantasy728** [PanJiaChen/vue-element-admin#1107]
你好，在你文档里介绍了2种方法刷新当前路由
1. 通过点击`link`后改变`query`来起到`push history`栈的方法确实很有效，但是这种方法最大的问题可能并不是你说的`url`后面会跟个难看的参数，而是，大多数用户可能在多次点击同一个路由后，在按返回键的时候是返回这个`url`之前的那个`url`，而使用这个方法，由于`push`了多个`history`之后，必须按多次返回键才能真正返回到之前的那个`url`，不知道有没有更好的解决办法
2. 第二种方法是你说的你司是判断当前`path`和目标`path`是否一致，如果一致，那就先跳到一个中间需要重定向的路径再跳转回来，我自己写了一个方法是这样的

```javascript
<template>
  <div>
  // 自定义属性写上目标路径path
    <a des="/side" @click="clickLink" >menuA</a><br>
  </div>
</template>

<script>
export default {
  methods: {
    clickLink(ev){
      var dom = ev.target
      //判断目标路径和当前路径$route.path是否相同
      if(this.$route.path === dom.getAttribute('des')) {
        this.$router.push({
          path: '/redirect' //这个路径是中转路径，在route.js里已经设置会跳回当前的url
        })
      }
    }
  }
};
</script>
```
现在问题来了，我以为这里用了push并且用了转发，那应该会在触发当前组件的生命周期函数，然而并没有。不过后来用了$route.go代替了push，就刷新了当前整个页面了，刷新多次后再点返回按钮确实也能返回到之前那个url，虽然最后结果和预想的不太一样，但似乎又起到了同样的效果。我不知道你们公司是不是这样写的，请指教。

**Comment by PanJiaChen** [comment]
this.$router.replace
