### ISSUE TITLE
本地运行报错

### ISSUE THREAD

**Issue by huting66** [PanJiaChen/vue-element-admin#1109]
![_20180917154706](https://user-images.githubusercontent.com/20763839/45611176-0a433100-ba91-11e8-908f-c6682e7cd7ee.png)
什么都没改 刚克隆完，npm版本是5.6.0 node版本是8.12.0，有没有大佬帮忙看下

**Comment by PanJiaChen** [comment]
首先确定是否有正确安装？命令行是否有报错？尝试一下重新下载安装。

若都没有问题，请提供一下操作系统和浏览器相关信息。

**Comment by benyVip** [comment]
我今天也遇到了，贴下这个报错
linyoujiedeMacBook-Pro:vue-element-admin linyoujie$ npm run dev

> vue-element-admin@3.9.0 dev /Users/linyoujie/Documents/coding/github/vue-element-admin
> cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 10% building modules 1/1 modules 0 activeevents.js:167
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
Emitted 'error' event at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1507:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-element-admin@3.9.0 dev: `cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-element-admin@3.9.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/linyoujie/.npm/_logs/2018-09-25T10_43_09_801Z-debug.log

**Comment by PanJiaChen** [comment]
这种报错大部分都是个例，个自己的环境有关，比较难以重现问题。建议自行谷歌问题解决。或者重装一下项目试试。

**Comment by Godricm** [comment]
执行
npm i --save-dev cross-env
