### ISSUE TITLE
tab里面使用富文本编辑器问题

### ISSUE THREAD

**Issue by BlythDD** [PanJiaChen/vue-element-admin#1112]
tab有两个组件，默认进入第一个组件，富文本在第一个组件里；默认是没有问题的，但是点击tab切换到第二个组件，然后再次切换到第一个组件，富文本就加载不出来了。至此还没找到原因；

**Comment by BlythDD** [comment]
另外，是否有一个群来供大家分享以及提出日常问题

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/251

tab切换需要手动`refs.xxx.setContent()`，为了性能考虑，富文本只会监听数据变化一次。

**Comment by BlythDD** [comment]
写在父组件吧？像这样？子组件需要做什么？

**Comment by BlythDD** [comment]
methods: {
      change(x) {
        this.who=this.tabs[x].key;
        if(x == 1){
          this.$refs.child.setContent()
        }

      },
    },

**Comment by BlythDD** [comment]
methods: {
      change(x) {
        this.who=this.tabs[x].key;
        if(x == 1){
          this.$refs.child.setContent()
        }

      },
    },

是这样写在父组件的tab事件里面吗？setContent()需要添加什么东西？子组件里需要做什么

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/87b319d96ac3998f7d496fc3a64a608d8c111151

**Comment by NameWjp** [comment]
我遇到了同样的问题，tabs页切换后富文本丢失内容且无法编辑。
我的解决办法是当tab页切回来时，通过v-if强制富文本重新初始化。
