### ISSUE TITLE
突然浏览器之间样式不一样，不知道什么原因

### ISSUE THREAD

**Issue by wakaryry** [PanJiaChen/vue-element-admin#1113]
![default](https://user-images.githubusercontent.com/7576559/45620731-6a959b00-bab0-11e8-9ff3-ef1025c12fec.png)

上面是火狐，下面是Safari。
以前貌似是一样的，不知道为什么突然有一天变成了这样。

样式里面没有padding和margin啊。

**Comment by BlythDD** [comment]
firefox62.0，用我自己的测试没有问题，你这个问题吧，只能自己先找出原因，否则别人没法帮你

**Comment by PanJiaChen** [comment]
@wakaryry https://panjiachen.gitee.io/vue-element-admin/#/dashboard

确定一下线上demo有问题么？

**Comment by wakaryry** [comment]
线上demo没有问题。我开始的时候也是没有问题的。

我记得是有一次 删除了node_modules，clear了cache，然后重新install之后火狐就出现了这个问题。

等我回去把代码贴出来看下。

**Comment by wakaryry** [comment]
页面挂的IP地址：47.104.142.155/admin/
访问账号：helloVisitor
访问密码：123456

可以线上看一下不知道你们打开有没有问题。

**Comment by PanJiaChen** [comment]
mac chrome firefox 都没有问题，这种样式问题，自己调试一下不就清楚了。

**Comment by wakaryry** [comment]
主要是没有发现样式的问题。firefox莫名其妙左侧多了个空白。样式中也没有padding和margin之类的。

只能先放着。没准哪一天好了。
