### ISSUE TITLE
tagsView自己模仿的时候发现动态路由切换的时候   切换不了   例如edit/1=》edit/2就无法切换

### ISSUE THREAD

**Issue by liutingchao** [PanJiaChen/vue-element-admin#1117]
![image](https://user-images.githubusercontent.com/24770061/45728250-c15abc00-bbf9-11e8-9cc3-4dc3b29debe5.png)

![image](https://user-images.githubusercontent.com/24770061/45728266-cd467e00-bbf9-11e8-894c-2988a8a797ae.png)

别的切换的时候  没问题就动态路由与动态路由切换的时候   就切换不了

**Comment by PanJiaChen** [comment]
请自行参照

https://github.com/PanJiaChen/vue-element-admin/tree/master/src/views/example
