### ISSUE TITLE
TypeError: undefined is not iterable!

### ISSUE THREAD

**Issue by Cling-Clang** [PanJiaChen/vue-element-admin#1118]
![1111](https://user-images.githubusercontent.com/35895796/45737981-d0556480-bc21-11e8-8ddd-15eac4b77c0f.png)
![222](https://user-images.githubusercontent.com/35895796/45737985-d4818200-bc21-11e8-85d6-d62e5502b49c.png)
![333](https://user-images.githubusercontent.com/35895796/45737989-d6e3dc00-bc21-11e8-9a2b-e009bda27a1c.png)
基于模板二次开发，出现意想不到的错误，tagview 和 store 里的内容 都是直接copy过来的 为什么会出现如此错误呢

**Comment by Cling-Clang** [comment]
领 tagview 刷新当前页 跳转到404 页面是否和此相关呢

**Comment by PanJiaChen** [comment]
根据报错信息，应该是某个值的类型不对。大概率是解构的某个值变成了 undefined

**Comment by Cling-Clang** [comment]
> 根据报错信息，应该是某个值的类型不对。大概率是解构的某个值变成了 undefined
我也怀疑过是 tags 这边的问题 可惜在下才疏学浅未能解其深意，所以直接copy的代码 
this.$refs.tag 怎么会获取不到值呢 很疑惑

**Comment by un-hum** [comment]
请问该问题解决了吗，我也出现了一样的问题

**Comment by Cling-Clang** [comment]
> 请问该问题解决了吗，我也出现了一样的问题

没有 百思不得其解 继续沟通吧

**Comment by un-hum** [comment]
我目前直接做了一层判断
![image](https://user-images.githubusercontent.com/16220867/46054626-b6b0a180-c17a-11e8-9c25-126c18cf4249.png)

**Comment by hustfly** [comment]
遇到同样的错误，主要问题是TagsView里边 this.$refs.tag是空，不知道这里在取得是什么值？

**Comment by chang0022** [comment]
![image](https://user-images.githubusercontent.com/6067222/49227503-33365980-f424-11e8-8d12-e02163a096d9.png)
将 `watch route` 里面的` this.moveToCurrentTag()` 移动 `addViewTage(`) 异步回调中

**Comment by lingling68958** [comment]
同样遇到这样的问题，请问各位大神都是怎么解决的啊

**Comment by leiquan** [comment]
已确认本Bug：你只需要在router里面加上name即可。

**Comment by AkiyamaMinami** [comment]
> 已确认本Bug：你只需要在router里面加上name即可。
> 类似这样：
> {
> path: 'user-list',
> component: () => import('@/views/word/list'),
> name: 'UserList',
> meta: { title: '用户列表' }
> }

测试有效

**Comment by yuanqichao514** [comment]
> 已确认本Bug：你只需要在router里面加上name即可。
> 类似这样：
> {
> path: 'user-list',
> component: () => import('@/views/word/list'),
> name: 'UserList',
> meta: { title: '用户列表' }
> }

直接起飞

**Comment by LJYonline** [comment]
遇到同样的问题，我定位了到错误的代码位置，就是一个接口返回的值不确定就遍历，这个遍历的值可能不存在导致。我加了一层if（） 问题就解决了。
