### ISSUE TITLE
如何能实现页面切换还保留页面原有的操作呢？

### ISSUE THREAD

**Issue by wangdan013130** [PanJiaChen/vue-element-admin#1119]
当两个页面间切换时，上个页面执行添加或修改操作，如何在切换至别的页面再返回时之前的弹框不关闭，或者操作不关闭

**Comment by PanJiaChen** [comment]
keep-alive

**Comment by wangdan013130** [comment]
用了 keep-alive , 但是未生效

**Comment by PanJiaChen** [comment]
请确定自己的 keep-alive 是否生效。

我未能重现你的问题。

![keep-alive](https://user-images.githubusercontent.com/8121621/45747416-62686780-bc38-11e8-8d55-35f08511cad8.gif)
