### ISSUE TITLE
npm run build:prod 中断无报错

### ISSUE THREAD

**Issue by callmez** [PanJiaChen/vue-element-admin#112]
![image](https://user-images.githubusercontent.com/1625891/27799117-952f380a-6046-11e7-9975-bb76d9ccec09.png)

原版镜像拷贝在阿里云上1G内存的服务器构建直接中断了，  是不是配置不够吃？

**Comment by PanJiaChen** [comment]
没有遇到过上述问题，可能是你说的问题
