### ISSUE TITLE
TagsView js closing

### ISSUE THREAD

**Issue by Delari** [PanJiaChen/vue-element-admin#1120]
Hi, say how close tagsView on script? example:

this.$store.dispatch('tagsView/delVisitedViews', this(how can I transfer the view object?))

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/11163146c09c6cdf0e2e354a632e1b9b92d46263/src/views/layout/components/TagsView.vue#L106

**Comment by Delari** [comment]
dashboard have component tagsView, i can't find how i can close opening vue-tamplate

**Comment by PanJiaChen** [comment]
Vue is `mvvm`, so it is data driven.
You can only do this by executing `this.$store.dispatch('delView', view)`

**Comment by Delari** [comment]
when i doing 
`this.$router.push({ name: 'MaterialsList' }); `

opening view MaterialsList + tagsView add this View, so how i can close it?
