### ISSUE TITLE
怎么移除语言包 不要英文模式

### ISSUE THREAD

**Issue by answers2017** [PanJiaChen/vue-element-admin#1122]
在 src/main.js 中移除 import i18n from './lang' 并且删除 src/lang 文件夹。

并在 src/layout/components/Levelbar、src/layout/components/SidebarItem、src/layout/components/TabsView 等文件夹中 移除 this.$t('route.xxxx') 使用国际化的方式。
官方提供的方法找不到

**Comment by PanJiaChen** [comment]
你移除了看哪里报错就可以了。

之后会优化相关问题

https://github.com/PanJiaChen/vue-element-admin/issues/1068
