### ISSUE TITLE
一级菜单权限只有管理员可见设置问题

### ISSUE THREAD

**Issue by ChasonHong** [PanJiaChen/vue-element-admin#1123]
请教下非管理员登录看到空白位置怎么去掉

![1537432604638](https://user-images.githubusercontent.com/11606876/45806416-96549300-bcf3-11e8-8ba1-b0f32f2379dc.jpg)

**Comment by PanJiaChen** [comment]
你只有一个children 为什么权限不放 父级。

或者你父级也声明一下 meta信息。

**Comment by ChasonHong** [comment]
ok
