### ISSUE TITLE
一个命名的问题，npm run  build:sit是构建测试环境版本，请问sit什么含义？

### ISSUE THREAD

**Issue by CHCP** [PanJiaChen/vue-element-admin#1128]
一个命名的问题，npm run  build:sit是构建测试环境版本，请问sit什么含义？

**Comment by PanJiaChen** [comment]
- SIT:

System Integration Testing. It is the environment where Internal testing will take place. Say your testing team's work area.

- UAT:

After SIT is over the app and its respective data are moved to UAT schema, where user Acceptance Testing will be done. Say your clients technical team will test that. Finally after every testing is passed the app is moved to PROD environment.

- PROD:

It is a production environment where live data will be there.

- DEV

For developers usually seperate schema called DEV is used for development purposes
