### ISSUE TITLE
关于dropzone解决方案

### ISSUE THREAD

**Issue by VonJane** [PanJiaChen/vue-element-admin#1129]
我是基于template模板进行开发的，目前想做一个相册的功能，然后管理端就要做图片上传，dropzone应该可以满足我的需求，我直接将dropzone的vue文件复制进我的template模板里会报错。
`import Dropzone from 'dropzone'
import 'dropzone/dist/dropzone.css'`
这两个引入找不到，请问大佬我该怎么做？

**Comment by PanJiaChen** [comment]
`npm install dropzone -S`
