### ISSUE TITLE
发现一个动态路由的bug

### ISSUE THREAD

**Issue by koakumaping** [PanJiaChen/vue-element-admin#113]
next(to.fullPath) // hack方法 确保addRoutes已完成
改成这样子就没问题了。我还以为vue-router的bug呢。。

**Comment by PanJiaChen** [comment]
不懂你在说什么。。。你这样和我的有什么区别。。。你这样写只会专递path项，query或者meta这种数据都会被丢失

**Comment by koakumaping** [comment]
![image](https://user-images.githubusercontent.com/4099388/27897212-5eb6ac74-6251-11e7-8842-00ad6b5f6632.png)
@PanJiaChen 这样子不知道你明白我的意思了吗？如果页面有query，next(to.path)会造成ctrl+r之后query信息消失。。

**Comment by PanJiaChen** [comment]
我前几天就修改过了啊。。。https://github.com/PanJiaChen/vue-element-admin/blob/master/src/main.js#L56

**Comment by koakumaping** [comment]
好吧。。。我看的是你的教程里面的代码

**Comment by PanJiaChen** [comment]
@koakumaping 感谢你的反馈
