### ISSUE TITLE
在pad上打开，左侧菜单栏二级菜单点击跳转后会再弹出一次

### ISSUE THREAD

**Issue by XieYuanCode** [PanJiaChen/vue-element-admin#1135]
在pad上打开，左侧菜单栏二级菜单点击后会弹出一次，在页面跳转之后。

**Comment by XieYuanCode** [comment]
测试发现 三级的弹出菜单不会有这个问题，二级的就有这个问题

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/1152

**Comment by lyndonliu89757** [comment]
在谷歌浏览器上仍然存在这个问题。
