### ISSUE TITLE
Tinymce编辑器使用element Dialog弹出框 编辑器数据无法重置

### ISSUE THREAD

**Issue by EightDoor** [PanJiaChen/vue-element-admin#1137]

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/251

**Comment by likowong** [comment]
![image](https://user-images.githubusercontent.com/27354168/125581662-53796bb7-a77e-4ec4-a9d6-2df8008edd80.png)
