### ISSUE TITLE
关于权限登录问题！

### ISSUE THREAD

**Issue by wlLeblanc** [PanJiaChen/vue-element-admin#1138]
请问下我想要直接调用自己的登录接口就进入页面，不用去调用下面的模拟接口，应该怎么改逻辑？

![image](https://user-images.githubusercontent.com/22288871/46138921-d2ea3680-c27f-11e8-97b9-fa7014c7426d.png)

**Comment by PanJiaChen** [comment]
太基础的问题了，请自行学习相关基础。
