### ISSUE TITLE
关于左侧菜单映射路由的问题

### ISSUE THREAD

**Issue by yanjintao** [PanJiaChen/vue-element-admin#1139]
当右侧加入 router-view 后，在appMain 中进行多层嵌套路由 ，  并不希望 用来嵌套的路由页面  作为根目录显示在左侧一级菜单中，该如何怎么做？

**Comment by PanJiaChen** [comment]
没懂你想要的效果。

**Comment by yanjintao** [comment]
{
    path: '',
    component: Layout,
    alwaysShow: true,
    redirect: '/netdisc/index',
    meta: {
      title: '我的网盘',
      icon: '网盘_1'
    },
    children: [
      {
        path: 'netdisc',
        component: () => import('@/ecm/ecmLayOut.vue'),
        name: 'ecmLayOut',
        redirect: '/netdisc/index',
        hidden: true,
        children: [
          {
            path: 'index',
            component: () => import('@/ecm/netdisc/netdisc.vue'),
            name: 'netdisc',
            hidden: true
          }
        ]
      }
    ]
  }
我只希望 最后的那个子集 （netdisc）显示在左侧一级菜单上，不不希望他作为2级菜单展示我该如何做

**Comment by yanjintao** [comment]
> 没懂你想要的效果。

{
path: '',
component: Layout,
alwaysShow: true,
redirect: '/netdisc/index',
meta: {
title: '我的网盘',
icon: '网盘_1'
},
children: [
{
path: 'netdisc',
component: () => import('@/ecm/ecmLayOut.vue'),
name: 'ecmLayOut',
redirect: '/netdisc/index',
hidden: true,
children: [
{
path: 'index',
component: () => import('@/ecm/netdisc/netdisc.vue'),
name: 'netdisc',
hidden: true
}
]
}
]
}
我只希望 最后的那个子集 （netdisc）显示在左侧一级菜单上，不不希望他作为2级菜单展示我该如何做

**Comment by PanJiaChen** [comment]
`alwaysShow: true`
去掉

**Comment by PanJiaChen** [comment]
暂时处理你这种嵌套三层的情况。

那想要在一级显示，那为什么要写成这样呢？为了面包屑？

**Comment by yanjintao** [comment]
我在右侧又做了一层布局，这样会形成嵌套路由，但是我又想要第2层布局下的路由显示在一级菜单中

**Comment by yanjintao** [comment]
> 暂时处理你这种嵌套三层的情况。
> 
> 那想要在一级显示，那为什么要写成这样呢？为了面包屑？

我在右侧又做了一层布局，这样会形成嵌套路由，但是我又想要第2层布局下的路由显示在一级菜单中

**Comment by yanjintao** [comment]
![image](https://user-images.githubusercontent.com/24405904/46185870-62d6c180-c30e-11e8-81b9-99dd6fdf2fe3.png)


> 暂时不能处理你这种嵌套三层的情况。
> 
> 那想要在一级显示，那为什么要写成这样呢？为了面包屑？

![image](https://user-images.githubusercontent.com/24405904/46185876-679b7580-c30e-11e8-86ff-bc180d0e3caa.png)
我对代码进行的修改，可以显示了。

**Comment by PanJiaChen** [comment]
👍

**Comment by MagginZ** [comment]
想问一下 你的this.onlyOnchild是在哪儿使用的
