### ISSUE TITLE
vendor.js 过大的问题

### ISSUE THREAD

**Issue by 450611** [PanJiaChen/vue-element-admin#114]
请问一下， 对于element-UI,  打包之后vendor的大小超过600KB， 而我看你的所有的js都不超过280KB， 但是element-ui cdn下面的js  就有360kb+, 请问你对 element打包有进行什么优化么？

**Comment by PanJiaChen** [comment]
自己拆包 ，加懒加载，gzip只会大小大概只会有原先1/3  不会很大。
element的问题官网写的很清楚了gzip只后只有94.8kb

**Comment by 450611** [comment]
gzip 是服务器端的操作吧？

**Comment by PanJiaChen** [comment]
恩。拆vendor建议看https://zhuanlan.zhihu.com/p/26710831
具体的优化还是要结合自己的业务来的

**Comment by 450611** [comment]
好的 十分感谢
