### ISSUE TITLE
打包编译后，进度不动了，没有在编译

### ISSUE THREAD

**Issue by ontheway1215** [PanJiaChen/vue-element-admin#1145]
node 版本8.11.3，使用npm run build:prod命令打包后，左边那个小圆圈进度条不动了，等了好久还是不动。在本地电脑打包，电脑16G内存。

**Comment by ontheway1215** [comment]
可能是node版本的问题，用公司Mac打包成功，公司node版本10.3.0，回去把家里node升级试试。

**Comment by MillionQW** [comment]
把 node 版本升级后问题解决了吗，我在 windows 下 npm run build:prod 也报 内存泄漏。
node 版本 -v 8.0.0
