### ISSUE TITLE
Windows切换到Linux编译出问题

### ISSUE THREAD

**Issue by goozp** [PanJiaChen/vue-element-admin#1146]
`npm run build`
然后就卡住了：
`building for production...`
前面的图标不动了，也不报错，一直卡着，没有成功，static目录没出来。

proxy什么的也试过了。
因为是后端程序猿，没什么经验，也google不到解决方案，不知道是什么原因，来请教一下。谢谢

环境：
原来是用Windows10，然后用了win10子系统装的Debian
node原先是8.11，linux中是8.12

**Comment by PanJiaChen** [comment]
什么报错信息都没有么

**Comment by goozp** [comment]
是，很奇怪。
![image](https://user-images.githubusercontent.com/17734933/46240235-df34d780-c3d6-11e8-9cbf-cac756d203a2.png)
就是这样，就不动了，多久都不动了。
应该也不是权限问题，有权限

**Comment by PanJiaChen** [comment]
能在确定一下npm版本么？

**Comment by goozp** [comment]
npm是 6.4.1
![image](https://user-images.githubusercontent.com/17734933/46241273-c59c8b80-c3e8-11e8-9903-82ae8fcb82b8.png)

这样装的：
`npm install --registry=https://registry.npm.taobao.org`
也试过开代理直接npm install

现在在想是不是win10的WSL有兼容问题

**Comment by PanJiaChen** [comment]
http://www.195440.com/?p=1141

主要我这里也不能重现你的问题。

**Comment by ontheway1215** [comment]
@goozp 我也遇到这种情况了，在家里用的是win10 的WSL，也出现你这种情况，然后到公司用Mac就build成功了，我也怀疑是win10的WSL兼容问题或者node版本问题。

**Comment by ontheway1215** [comment]
还有一个问题就是在自己的服务器上build会出现⠸ building for production...已杀死 然后就中断了，不清楚是不是因为服务器內存太小了，内存512的。

**Comment by PanJiaChen** [comment]
蛮有可能是内存问题。

**Comment by Mohaiyo** [comment]
我也遇到这个问题，第一次排查是一个vue文件里面用了async的语法会导致这个问题，然后改用Promise then语法解决了，现在又出现了这个问题，再次排查与async无关，暂时找不到具体原因。具体表现就是 npm run build的时候电脑内存一直飙升在90%以上，很想知道这是什么原因导致的？

**Comment by navee** [comment]
不仅仅wsl会出现这个问题，我用docker编译也有这个问题

**Comment by zsodur** [comment]
我也遇到同样的问题, 有解决办法吗

**Comment by tianleiyiji123** [comment]
遇到同样问题，我感觉也是wsl兼容问题，wsl始终build不起来

**Comment by Jjiawen** [comment]
我也遇到同样问题，之前都是可以的，突然就不行了，切换之前版本打包也不行。摸不着头脑
