### ISSUE TITLE
import('@/views/guide/index') 的@ 在 jetbrain 报错

### ISSUE THREAD

**Issue by weituotian** [PanJiaChen/vue-element-admin#1147]
![image](https://user-images.githubusercontent.com/7270968/46241151-224a7700-c3e6-11e8-8951-c916efb93060.png)

大大们是怎么看待这个经典的问题的？文档里没有提到，如果想实现点击跳转到相应文件，应该怎么配置呢？

**Comment by PanJiaChen** [comment]
这是你自己 webstorm 配置的问题。

https://juejin.im/post/5b0287155188251bf66e65fa
