### ISSUE TITLE
关于样式问题

### ISSUE THREAD

**Issue by VonJane** [PanJiaChen/vue-element-admin#1151]
您好，
1：我在admin里移植了example里的文章列表和新增文章到template里，我调用了自己的后台数据，返回的importance是int型，在前段列表页却无法正常显示小星星，没找到问题所在，别的数据都正常渲染上了，就importance有值却无法正常显示。
2：在列表页发现我的pagination样式是不正确的，请问是我缺少了什么文件吗？正常是共X条，前往Y页，而我的是total X,Go to Y

**Comment by PanJiaChen** [comment]
1: 你是让我猜你写的代码么。
2: 请参考element-ui 的国际化。
