### ISSUE TITLE
this.$router.push({ path: that.redirect || '/' }) 无法跳转是什么原因

### ISSUE THREAD

**Issue by BlythDD** [PanJiaChen/vue-element-admin#1153]
this.$store.dispatch('LoginByUsername', requestData).then(response => {
              this.loading = false
                if(response.status == 200 ){
                    let data = response.data
                    if(data.meta.success == true){
                      window.sessionStorage.setItem("jwt", data.data.jwt)
                      console.log(this.$router)
                      that.$router.push({ path: that.redirect || '/' })
                    }
                }
              }).catch(() => {
              this.$message.error('请求错误，请联系管理员')
              this.loading = false
              this.$router.push({ path: '/example/create' || '/example/create' })
              })

查了一下这个that，this指向的是vue的实例，但是无法跳转，报错弹框error；
另外这个跳转的默认地址that.redirect模板是在哪里设置的？默认path:‘’的吗？

**Comment by PanJiaChen** [comment]
- that 问题帮不了你，自己debug找问题。

- redirect：
https://github.com/PanJiaChen/vue-element-admin/blob/935d9aaba891efe80cccb22d87ac86e9cfe6f39d/src/views/login/index.vue#L106

- validate 动态修改？
没明白这个map是动态的？你存到vuex不就好了。

**Comment by BlythDD** [comment]
ok，谢谢
