### ISSUE TITLE
Laravel 5.6

### ISSUE THREAD

**Issue by slamghost** [PanJiaChen/vue-element-admin#1158]
Hi,

Great work!  How can I integrate this into Laravel framework ?

Regards

**Comment by PanJiaChen** [comment]
This project is a pure front-end project, and Laravel is also very friendly to vue. The community already has a lot of complete solutions, so I don’t think there is any big problem with integration.

**Comment by PanJiaChen** [comment]
Maybe [element-in-laravel-starter](https://github.com/ElementUI/element-in-laravel-starter) this will help you
