### ISSUE TITLE
启动后为什么没有“bug”图标？

### ISSUE THREAD

**Issue by CAH-FlyChen** [PanJiaChen/vue-element-admin#1159]
程序启动后没有bug图标

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/616b65c2385d701af77e858c3591085dbc7f9d3c/src/errorLog.js#L5

目前只会在正式环境中开启，你可以自行去掉这个逻辑。
4.0版本中会做成配置项。
