### ISSUE TITLE
前端新人看的好迷茫，有什么学习路线推荐的吗

### ISSUE THREAD

**Issue by chunbobo** [PanJiaChen/vue-element-admin#1160]
俺也看过一些视频和vue demo, 感觉也能用用看。但是下了这个demo怎么感觉啥都看不懂了呢.. 有什么推荐的学习路线吗？提问在这里好像不太好，见谅.

**Comment by PanJiaChen** [comment]
指前端的话：还是先把js基础打好。我觉得刷几遍红宝书-高级程序设计 应该就差不多了。
es6的话 看阮老师-阮一峰的 [es6](http://es6.ruanyifeng.com/#docs/intro) 就可以了。

vue 相关的话 不建议看什么书，直接看官方的文档就够了。扫一遍就差不多了，之后就是实战。随便去做一个东西出来。github 应该有很多。 边做边学咯，平时做写代码的时候我也要时不时的看看vue官方文档。
