### ISSUE TITLE
webpack 2.6.1  vue-loader 13.0.4打包不成功

### ISSUE THREAD

**Issue by zhangaofei** [PanJiaChen/vue-element-admin#1162]
因为懒加载开发太慢 所以把vue-loader升级到13+（https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/lazy-loading.html#%E6%96%B0%E6%96%B9%E6%A1%88  根据上面方法做的）但是打包还是打不成，想请教一下大佬！

**Comment by PanJiaChen** [comment]
不成功，你至少把报错提示出来吧。
