### ISSUE TITLE
多个二级菜单之前切换之前的不会自动缩放

### ISSUE THREAD

**Issue by chunbobo** [PanJiaChen/vue-element-admin#1163]
多个二级菜单之前切换之前的不会自动缩放这个是故意为之还是说可以配置？
还有我发现点折叠菜单那个按钮(就是把整个菜单区变成图标的按钮)，点了之后动画会有掉帧？我试了公司的电脑和家里电脑都是这样，你们是这样吗？
浏览器：
Google Chrome 已是最新版本
版本 69.0.3497.100（正式版本） （64 位）

**Comment by PanJiaChen** [comment]
收缩问题见 https://github.com/PanJiaChen/vue-element-admin/issues/1014

卡顿问题请关注 https://github.com/PanJiaChen/vue-element-admin/issues/937
