### ISSUE TITLE
如何去设置publicPath？

### ISSUE THREAD

**Issue by LuoChengIo** [PanJiaChen/vue-element-admin#1164]
由于项目没有放到根目录，样式文件里面的背景图片打包后有问题
![image](https://user-images.githubusercontent.com/28758234/46643829-5f65f480-cbb0-11e8-8a48-fa2498be0b98.png)
在webpack3中可以这样设置
![image](https://user-images.githubusercontent.com/28758234/46643862-7efd1d00-cbb0-11e8-9b28-fdc58c5d3467.png)
升级到webpack4后我尝试这样配置，但是无效
![image](https://user-images.githubusercontent.com/28758234/46643912-ab189e00-cbb0-11e8-9473-bc3b23ba1adb.png)
请问该如何配置呢，非常谢谢

**Comment by LuoChengIo** [comment]
不好意思，我知道怎么改了。。。。

**Comment by PanJiaChen** [comment]
我常规做法还是用alias。

`background: url('~@/assets/401_images/401.gif');`

**Comment by Yanhongliang100** [comment]
怎么改### 能贴一下代码吗？谢谢

**Comment by PanJiaChen** [comment]
@LuoChengIo https://github.com/vuejs/vue-loader/issues/481

**Comment by LuoChengIo** [comment]
@Yanhongliang100 我并不是背景图片问题，我是项目没有放到服务器根目录导致的问题，我最终是修改了config里面的index.js
![image](https://user-images.githubusercontent.com/28758234/47057660-45ea2b80-d1f4-11e8-83ea-421c953a997a.png)
把这里改成项目放在服务器的文件夹名称就好了

**Comment by tomatojacky** [comment]
这样即可：
=============================================================  
const MiniCssExtractPluginLoader = {
    loader: MiniCssExtractPlugin.loader,
    options: {
      // you can specify a publicPath here
      // by default it use publicPath in webpackOptions.output
      publicPath: '../../'
    }
  }


  // generate loader string to be used with extract text plugin
  function generateLoaders(loader, loaderOptions) {
    const loaders = []

    // Extract CSS when that option is specified
    // (which is the case during production build)
    if (options.extract) {
      loaders.push(MiniCssExtractPluginLoader)
    } else {
      loaders.push('vue-style-loader')
    }

}
