### ISSUE TITLE
嵌套路由父组件会重新渲染

### ISSUE THREAD

**Issue by gaoshijun1993** [PanJiaChen/vue-element-admin#1165]
使用了嵌套路由发现AppMain组件会重新渲染, 排查发现是因为:为了实现点击左侧导航菜单刷新页面的功能, AppMain组件的<router-view>加了一个key属性. 已有可行的解决方法参考: https://github.com/PanJiaChen/vue-element-admin/issues/274, 有没有更好的解决方法呢?

**Comment by PanJiaChen** [comment]
要实现刷新路由 只能加key。

但 AppMain 并不会重渲，只是你加了key的 router-view 会重渲。
