### ISSUE TITLE
uploadExcel上传显示上传进度的问题

### ISSUE THREAD

**Issue by dawayway** [PanJiaChen/vue-element-admin#1168]
裤衩哥，我先在上传excel表格，表格里面的数据有10条到1000条不等，我能不能搞个上传进度的显示条呢，能不能告诉我一下思路，近期这个问题搞得我头疼。

**Comment by PanJiaChen** [comment]
上传和几条数据没啥关系吧，一般都是监听`XMLHttpRequest progress `

[文档](https://developer.mozilla.org/zh-CN/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#%E7%9B%91%E6%B5%8B%E8%BF%9B%E5%BA%A6)
