### ISSUE TITLE
windows下npm i 失败

### ISSUE THREAD

**Issue by brucelpt** [PanJiaChen/vue-element-admin#1171]
win10环境下，使用npm6.4.1,使用管理员运行命令行，到项目目录下安装失败
使用的是淘宝镜像，以下是报错信息

> npm ERR! path F:\vue-element-admin-master\node_modules\.staging\echarts-0a3cee93\dist\echarts.js
> npm ERR! code EPERM
> npm ERR! errno -4048
> npm ERR! syscall lstat
> npm ERR! Error: EPERM: operation not permitted, lstat 'F:\vue-element-admin-master\node_modules\.staging\echarts-0a3cee93\dist\echarts.js'
> npm ERR!  { Error: EPERM: operation not permitted, lstat 'F:\vue-element-admin-master\node_modules\.staging\echarts-0a3cee93\dist\echarts.js'
> npm ERR!   cause:
> npm ERR!    { Error: EPERM: operation not permitted, lstat 'F:\vue-element-admin-master\node_modules\.staging\echarts-0a3cee93\dist\echarts.js'
> npm ERR!      errno: -4048,
> npm ERR!      code: 'EPERM',
> npm ERR!      syscall: 'lstat',
> npm ERR!      path: 'F:\\vue-element-admin-master\\node_modules\\.staging\\echarts-0a3cee93\\dist\\echarts.js' },
> npm ERR!   stack: 'Error: EPERM: operation not permitted, lstat \'F:\\vue-element-admin-master\\node_modules\\.staging\\echarts-0a3cee93\\dist\\echarts.js\'',
> npm ERR!   errno: -4048,
> npm ERR!   code: 'EPERM',
> npm ERR!   syscall: 'lstat',
> npm ERR!   path: 'F:\\vue-element-admin-master\\node_modules\\.staging\\echarts-0a3cee93\\dist\\echarts.js',
> npm ERR!   parent: 'vue-element-admin' }
> npm ERR!
> npm ERR! The operation was rejected by your operating system.
> npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
> npm ERR! or that you lack permissions to access it.
> npm ERR!
> npm ERR! If you believe this might be a permissions issue, please double-check the
> npm ERR! permissions of the file and its containing directories, or try running
> npm ERR! the command again as root/Administrator (though this is not recommended).
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-10-09T11_25_43_480Z-debug.log

报错在echart.js，删除过node_modules重新安装过多次，都是在echart.js处报错，也清空过Npm缓存

我的npm信息 npm version

> { 'vue-element-admin': '3.9.1',
>   npm: '6.4.1',
>   ares: '1.10.1-DEV',
>   cldr: '32.0',
>   http_parser: '2.8.0',
>   icu: '60.1',
>   modules: '57',
>   nghttp2: '1.25.0',
>   node: '8.11.1',
>   openssl: '1.0.2o',
>   tz: '2017c',
>   unicode: '10.0',
>   uv: '1.19.1',
>   v8: '6.2.414.50',
>   zlib: '1.2.11' }

**Comment by PanJiaChen** [comment]
你是通过 `npm install --registry=https://registry.npm.taobao.org`安装的么？

**Comment by PanJiaChen** [comment]
`npm install echarts -S`

**Comment by brucelpt** [comment]
我切换成cnpm镜像单独安装echarts就可以了，谢谢大佬。
总结一下我解决这个问题的步骤
首先现将package.json   dependencies中的 "echarts": "^4.1.0",删除，
然后将nrm镜像切换到淘宝
npm i 安装依赖
将nrm切换到cnpm镜像
npm install echarts@4.1.0 -S  单独从cnpm安装echarts依赖
