### ISSUE TITLE
表单填写与查看详情功能

### ISSUE THREAD

**Issue by Ritusan** [PanJiaChen/vue-element-admin#1172]
请问可以增加表单这一模块吗，用户填写表单，提交表单，修改或重置表单数据，还有查看表单详情的功能，谢谢啦

**Comment by PanJiaChen** [comment]
这有什么问题或者难点么？

**Comment by Ritusan** [comment]
主要是想看一下查看详情的功能怎么复用（就是一个表单上有大量的数据，用户填写完提交之后点击一个按钮可以查看详情，也就是回显数据）

**Comment by PanJiaChen** [comment]
没懂。。你有啥原型或者设计稿可以参考一下吗

**Comment by Ritusan** [comment]
最近接触到一个学校的学生端的平台管理系统项目，就是有很多的表单需要填写提交，这个没有什么难度，但是有一个查看表单详情的功能，我想在查看详情里把学生填写的表单复用，而不是再写一套差不多重复的代码，想请大神点拨一下思路

**Comment by 15036900300** [comment]
@Ritusan 你可以通过传递一个参数判断是编辑还是查看，然后通过这个参数进行不同的效果展示啊，例如编辑显示编辑框，查看直接展示数据

**Comment by nabaonan** [comment]
> 最近接触到一个学校的学生端的平台管理系统项目，就是有很多的表单需要填写提交，这个没有什么难度，但是有一个查看表单详情的功能，我想在查看详情里把学生填写的表单复用，而不是再写一套差不多重复的代码，想请大神点拨一下思路

这个封装一个form组件就可以了吧，然后哪个页面用，就引入

**Comment by Ritusan** [comment]
主要是表单绑定了两种数据（一种是从后台获取的初始化数据，也就是一进入表单就显示出来的数据，一种是需要学生填写的数据，这些数据最后传给后台），有很多表单，每一个表单上显示的东西都不太一样，不知道这个怎么封装

**Comment by nabaonan** [comment]
@Ritusan 我现在是填写表单和查看表单用的两个组件，填写的时候有些操作逻辑是查看没有的，写一起有点乱，不过应该也可以写在一起，传个参数区分吧，有很多表单可以考虑做个表单生成器吧，通过传配置生成表单，表单少的话感觉就凑活写页面吧

**Comment by Ritusan** [comment]
> @Ritusan 我现在是填写表单和查看表单用的两个组件，填写的时候有些操作逻辑是查看没有的，写一起有点乱，不过应该也可以写在一起，传个参数区分吧，有很多表单可以考虑做个表单生成器吧，通过传配置生成表单，表单少的话感觉就凑活写页面吧

表单很多，有十几二十个的样子，传参数和表单生成器这一块大神可以具体指点一下吗，或者有推荐的demo也行
