### ISSUE TITLE
刷新页面后 tagsview失效

### ISSUE THREAD

**Issue by hfengshan** [PanJiaChen/vue-element-admin#1173]
如题，当打开几个页面后，点击浏览器刷新按钮，打开的tagsview标签全部失效，只会保留正在打开的tagsview。调试了一下，感觉是cachedviews在vuex中没有被更新导致的。不知道这个bug是否会被修复？

**Comment by PanJiaChen** [comment]
正常现象，目前所有状态是存在vuex中的，你刷新了页面，所有数据当然都会丢失。
