### ISSUE TITLE
Dont show compenent in nested path

### ISSUE THREAD

**Issue by cr998** [PanJiaChen/vue-element-admin#1175]
### Ejemplo
![captura](https://user-images.githubusercontent.com/6900835/46695773-b7344800-cc10-11e8-9d5b-66f703e1c531.PNG)

### Ruter code
![captura2](https://user-images.githubusercontent.com/6900835/46695818-d206bc80-cc10-11e8-8602-2c785125eba1.PNG)

### Controller code
![captura3](https://user-images.githubusercontent.com/6900835/46695868-fd89a700-cc10-11e8-98d6-0cf35e7d3d29.PNG)

**Comment by PanJiaChen** [comment]
First, please describe your problem in detail. I am not particularly clear about your problem.

By guessing, I think you should add a router-view.

You can learn from [demo](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/nested/menu1/index.vue)

**Comment by cr998** [comment]
the problem is that when I enter the path "/mi-empresa/prooveedores/listado" nothing appears, although in the router has specified the driver for that route

**Comment by PanJiaChen** [comment]
please give online demo

**Comment by cr998** [comment]
vueblock.robledomarketing.com

**Comment by cr998** [comment]
[vueblock.robledomarketing.com](url)

**Comment by PanJiaChen** [comment]
I mean to provide **source code** that can reproduce the problem...

**Comment by cr998** [comment]
you were right, router-view was missing
