### ISSUE TITLE
如何输出build详细日志

### ISSUE THREAD

**Issue by ramboma** [PanJiaChen/vue-element-admin#1179]
问题描述:
现在我们在vue-element-admin项目基础上增加了近50个页面,npm run build:prod耗时达到12分钟,所以想优化一下,可是找了很久也没法输出详细的日志信息(设置stats='verbose'无效),所以只好先把大神推荐的优化步骤做了一遍 [链接](http://www.hangge.com/blog/cache/detail_2105.html)，,但是时间只减少到10分钟,,请问大神们怎样设置能看到详细的日志信息,最好有时间戳显示,折腾好几天了都,多谢！！！

**Comment by 15036900300** [comment]
请问你进行npm run build:prod的时候，出现了

> building for prod environment...(node:4177) UnhandledPromiseRejectionWarning: Error: Cyclic dependency
    at visit (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/toposort/index.js:35:13)
    at visit (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/toposort/index.js:53:9)
    at visit (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/toposort/index.js:53:9)

这个问题吗

**Comment by ramboma** [comment]
没有,我这里npm i,之后npm run build:prod没问题的

**Comment by PanJiaChen** [comment]
`12分钟` 你自己的问题吧，你确定没改过什么配置么？

**Comment by ramboma** [comment]
有改过啊，但是基本都是新增路由已经新增组件啥的,基本配置没动过,我把最初的版本当下来也就30秒,和源代码差不多,但后来有很多次版本提交了，所以想定位下问题

**Comment by PanJiaChen** [comment]
https://github.com/stephencookdev/speed-measure-webpack-plugin#readme

**Comment by ramboma** [comment]
![image](https://user-images.githubusercontent.com/11207494/46719139-b8608600-cc9f-11e8-88a8-408a22a4d4d0.png)

**Comment by PanJiaChen** [comment]
去掉 https://github.com/PanJiaChen/vue-element-admin/blob/90d3e314c0435b700287118d6722a894baa9aeec/build/webpack.dev.conf.js#L44

添加
`stats: 'verbose',`

**Comment by PanJiaChen** [comment]
stats 本来就是 dev才有用。

speed-measure-webpack-plugin 不是明确告诉你每步的花销了么。

**Comment by PanJiaChen** [comment]
https://survivejs.com/webpack/optimizing/build-analysis/

**Comment by ramboma** [comment]
@PanJiaChen speed-measure-webpack-plugin的输出没看懂,你看插件加载时间这个没问题,loader时间好像是vue-loader加载了多次?不知道怎么优化,这个插件的相关问题都看了也没类似的

**Comment by PanJiaChen** [comment]
https://juejin.im/post/5b56909a518825195f499806#heading-12

**Comment by ramboma** [comment]
@PanJiaChen 修改build.js文件中的输出process.stdout.write(stats.toString({
                colors: false,
                modules: true,
                children: false,
                chunks: false,
                chunkModules: true
            }) + '\n\n')就可以看到详细的日志了,多谢大神.

**Comment by dpgirl** [comment]
@ramboma 请问你的能看到日志了吗？我的遇到问题： building for production...null  然后一直在打包，没有成功，也还没进入回调的那里？该怎么办？
