### ISSUE TITLE
上传xlsx遇到的格式问题，当格式不正确时需要用wps重新保存才可以读取；有什么办法解决？

### ISSUE THREAD

**Issue by Samdyddd** [PanJiaChen/vue-element-admin#1181]
在上传读取xlsx文件格式不正确时会卡住十几秒，当将xlsx文件使用wps重新保存再次读取才可以；

**Comment by PanJiaChen** [comment]
错误格式是什么？

**Comment by PanJiaChen** [comment]
你至少要告诉我一个重新bug的方式吧。

**Comment by Samdyddd** [comment]
[
![1539161731 1](https://user-images.githubusercontent.com/23043927/46724841-73dbe700-ccad-11e8-9cc8-9d43887b0e12.png)
](url)

**Comment by PanJiaChen** [comment]
请上传附件。
你把有问题的excel 拖进来。

**Comment by Samdyddd** [comment]
文件是机器生成的，我现在还没有比较简略的文件，到时我在上传附件吧；在const fixedData = this.fixdata(data)，这个函数返回的数据不一样，我看了一下读取的数据格式：
1.原文件
[
![1539162812 1](https://user-images.githubusercontent.com/23043927/46726135-42b0e600-ccb0-11e8-9a0d-cb9e8c74a68d.png)
](url)
2.重新生成的文件
[
![1539162850 1](https://user-images.githubusercontent.com/23043927/46726146-4d6b7b00-ccb0-11e8-9fb6-32ef14ac9e97.png)
](url)

**Comment by PanJiaChen** [comment]
请先研究怎么上传附件。
