### ISSUE TITLE
external-link 外链的问题

### ISSUE THREAD

**Issue by 15036900300** [PanJiaChen/vue-element-admin#1182]
问题描述：
当我需要打开的外链是一个文件时，则会出现权限不足的页面
> {
    path: 'external-link',
    component: Layout,
    children: [
      {
        // path: 'https://github.com/PanJiaChen/vue-element-admin',
        path: 'http://yingyan.ws.netease.com/guide/鹰眼用户手册V1.pdf',
        meta: { title: 'externalLink', icon: 'link' }
      }
    ]
  }

**Comment by PanJiaChen** [comment]
请确定vue-element-admin版本

**Comment by 15036900300** [comment]
> "name": "vue-element-admin",
  "version": "3.8.1",

版本是3.8.1，就是外链如果打开的不是文件就支持，例如下方示例

> {
    path: 'external-link',
    component: Layout,
    children: [
      {
        // path: 'https://github.com/PanJiaChen/vue-element-admin',
        // path: 'http://yingyan.ws.netease.com/guide/鹰眼用户手册V1.pdf',
        path: 'http://www.baidu.com',
        meta: { title: 'externalLink', icon: 'link' }
      }
    ]
  }

可以直接打开百度，但是我想打开鹰眼手册那个连接就不行，他最后是个pdf文件

**Comment by PanJiaChen** [comment]
主要是你有url中文 我的正则没适配中文

**Comment by 15036900300** [comment]
好的，那我改成英文吧

**Comment by 15036900300** [comment]
@PanJiaChen 修改哪一出可以让匹配中文呢

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/323408f8d981bd3c75727a16ed046f2260aa258e
