### ISSUE TITLE
CSS里面引入的图片路径出错了，求怎么改配置解决这个问题

### ISSUE THREAD

**Issue by 470269559** [PanJiaChen/vue-element-admin#1183]
我找了网上，但是发现网上的解决方案不是这个版本的脚手架

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1164

**Comment by 470269559** [comment]
{
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          publicPath:'../../',
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
这样也可以

**Comment by 470269559** [comment]
同样，如果奥森字体引入发生问题，也可以这样解决
