### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by helibin** [PanJiaChen/vue-element-admin#1184]
使用了vuex-persist实现数据持久化结果控制台报错
import VuexPersistence from 'vuex-persist'
const vuexLocal = new VuexPersistence({
  key: 'vuex-admin',
  storage: window.localStorage,
})
vue.runtime.esm.js:587 [Vue warn]: Error in callback for watcher "$route": "TypeError: Converting circular structure to JSON"

![51539221655_ pic_hd](https://user-images.githubusercontent.com/14595752/46776133-d62ff880-cd3c-11e8-9db3-b4ad652b10bc.jpg)

**Comment by PanJiaChen** [comment]
不了解 `vuex-persist`。
请去相关的仓库提问。

**Comment by nabaonan** [comment]
这个报错是因为json对象循环依赖无法转换吧

**Comment by anZong** [comment]
遇到同样的问题，请问你的解决了吗？

**Comment by helibin** [comment]
干掉 vuex-persist即可😂
