### ISSUE TITLE
登录获取用户信息后，生成路由这一步进入无限循环了

### ISSUE THREAD

**Issue by BlythDD** [PanJiaChen/vue-element-admin#1185]
登录获取用户信息后，生成路由这一步进入无限循环了，下面红框里一直循环，找不到原因，打断点也没用
![image](https://user-images.githubusercontent.com/20908252/46785572-b9a7b680-cd64-11e8-8f2f-f78808a85228.png)

**Comment by PanJiaChen** [comment]
next()才是真正的释放钩子。
next(xxx)还会再进beforeEach
