### ISSUE TITLE
always login fail 

### ISSUE THREAD

**Issue by feichangtutu** [PanJiaChen/vue-element-admin#1186]
![image](https://user-images.githubusercontent.com/8478315/46788740-638b4100-cd6d-11e8-9fdd-f471cf284f7a.png)
请问这个是easy-mock的问题吧，有替代方案么
这个问题经常出现，还有一种情况是timeout fail login

**Comment by immafrady** [comment]
这个是因为默认api太多人用了，easy-mock响应不过来吧……

**Comment by nabaonan** [comment]
本地跑一个easymock就行了，没有压力，线上的接口调用还不能过快

**Comment by feichangtutu** [comment]
@immafrady @nabaonan 好的，谢谢！我切自己的mock
