### ISSUE TITLE
请问怎么接入后端SSO系统

### ISSUE THREAD

**Issue by helongjun** [PanJiaChen/vue-element-admin#1188]
请求这个登录怎么改成接入后端的单点登录系统进行登录认证

**Comment by PanJiaChen** [comment]
后端单点登录和前端有什么关系吧。

逻辑都在后端，前端只要根据后端返回的状态码做相应的操作就可以了。

**Comment by helongjun** [comment]
不是，我是想问，怎么在路由直接跳到单点登录系统进行登录

**Comment by PanJiaChen** [comment]
在自行查相关文章。解决方案很多。

**Comment by mygrows** [comment]
@helongjun 请问你最后是怎么处理的？sso 登陆，望赐教 :)

**Comment by liaoyuhanCSDN** [comment]
@helongjun 同问，你是在全局守卫里进行sso吗
