### ISSUE TITLE
您好，想问一下tinymce编辑器的问题

### ISSUE THREAD

**Issue by semyin** [PanJiaChen/vue-element-admin#1191]
编辑器编辑过程中，点击刷新按钮  能恢复之前编辑内容 这个需求能实现吗？是不是需要后台的配合，把编辑的内容实时存到数据库里，再次进入从数据库里面读取。

**Comment by PanJiaChen** [comment]
不需要多人共享的话，本地localstorage就可以了。

**Comment by semyin** [comment]
是多人操作的，不需要共享。具体在tinymce文档里面可以找到怎么设置吗？

**Comment by PanJiaChen** [comment]
请仔细耐心看文档。
