### ISSUE TITLE
怎么实现根据不同的权限显示某些页面的隐藏

### ISSUE THREAD

**Issue by wangdan013130** [PanJiaChen/vue-element-admin#1197]
想通过不同的权限实现某些页面的隐藏,不知道怎么通过权限实现左侧路由的动态加载?
还有生成左侧路由的那个permission.js 里的 GenerateRoutes 函数陷入死循环是什么原因?
有时间方便帮忙看看解决下吗?

**Comment by PanJiaChen** [comment]
请自行看文档。
