### ISSUE TITLE
在v-echart或者echarts封装的组件中，如何实现布局改变触发重绘

### ISSUE THREAD

**Issue by SkyLin0909** [PanJiaChen/vue-element-admin#120]
就好比这个element-admin，在图表页是，收缩和展开侧边栏导航，不会触发window.resize

**Comment by ttop5** [comment]
将侧边导航栏的收缩和展开的状态存入vuex中，然后watch这个状态，状态一发生改变就重绘图表即可哈 @SkyLin0909

**Comment by SkyLin0909** [comment]
主要是我没自己封装echarts，而是选择直接用v-echart。看了下源码是在mixin里面监听resize。直接引用这个组件就不是很清楚如何去重绘了

**Comment by ttop5** [comment]
[https://github.com/Justineo/vue-echarts/issues/18](https://github.com/Justineo/vue-echarts/issues/18)

这里有人问过同样的问题。我的建议是自己封装，挺简单的，而且接口可以根据自己的项目灵活设计多好啊。:bowtie:

**Comment by PanJiaChen** [comment]
@SkyLin0909 侧边栏这个还真不太好做， 不是watch 侧边栏状态变化就能解决的。因为侧边栏有动画，所以监听状态变化之后去resize是不行的，https://github.com/PanJiaChen/vue-element-admin/commit/4ad90406af8d2c051fad6bce5f858633c21b90f7 我这里修改了一下。不过这种需求就和业务强耦合了。
