### ISSUE TITLE
微信扫码登录问题

### ISSUE THREAD

**Issue by lirui9156** [PanJiaChen/vue-element-admin#1201]
裤衩大大,请教一个问题,公司刚好弄微信登录,然后看了您这个文章:https://segmentfault.com/a/1190000009506097#articleHeader14,有个小问题,
截图这个地方到底是传服务器端的接口还是前端什么页面路径,弄了好久了,自己拿到微信code后手动可以通过回调地址跳转,想请您指点一下
![image](https://user-images.githubusercontent.com/28707890/46935007-51224780-d08c-11e8-8635-69913dfe9271.png)

**Comment by PanJiaChen** [comment]
我记得微信必须是你注册网址的根域名。

比如你注册的是app.com 微信授权回调也就必须是app.com。
所以我们做了一个app.com/redirect 的重定向页面。你可以前端做也可以nginx那层做，都可以，只要能回调页面就可以了。具体的看看微信的文档或者相关文章吧，时间太久远了，我也有些忘记了。

**Comment by lirui9156** [comment]
好的,我试试,谢谢裤衩大大😁

**Comment by j770657446** [comment]
“在created里面监听了hash是否有code和state"可以给个demo么 借萌新参考下
