### ISSUE TITLE
router.addRoutes(store.getters.addRouters) 在vuex严格模式下报错

### ISSUE THREAD

**Issue by de1ck** [PanJiaChen/vue-element-admin#1204]
[vue-element-admin链接](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/permission.js#L31)
`router.addRoutes(store.getters.addRouters) // 动态添加可访问路由表
`
[vuex](https://vuex.vuejs.org/zh/guide/strict.html#%E4%B8%A5%E6%A0%BC%E6%A8%A1%E5%BC%8F)

严格模式下，会有报错提示 Error: [vuex] Do not mutate vuex store state outside mutation handlers.

报错原因估计是router.addRoutes会改变store.getters.addRouters的值 
我的解决方案是用deepClone深度克隆对象后在赋值给addRoutes
const addRoutes = deepClone(store.getters.addRouters)
 router.addRoutes(addRoutes)

**Comment by PanJiaChen** [comment]
Trace in https://github.com/PanJiaChen/vue-element-admin/issues/126
