### ISSUE TITLE
切换组件时，第一次怎样进入if 而不是else

### ISSUE THREAD

**Issue by zhangaofei** [PanJiaChen/vue-element-admin#121]
<component ref="child" :is="currentView" :current-user="currentUser" :curData="curData" v-on:update="onUpdate" >
            
        </component>

js： onAdd(){
//dbAuthAdd 是一个组件
                if (this.currentView ==  dbAuthAdd) {
                    this.$refs.child.show()
                    console.log("userset--onAdd -show")
                } else {
                    this.currentView =  dbAuthAdd;
                }

            },
问题：判断添加第一次进入了else 第二次进入if
发起人 ：白加黑

**Comment by PanJiaChen** [comment]
完全不懂你要干嘛
