### ISSUE TITLE
eslint+vscode 自动格式化代码的问题

### ISSUE THREAD

**Issue by brucelpt** [PanJiaChen/vue-element-admin#1211]
https://juejin.im/post/59097cd7a22b9d0065fb61d2
我按照上面作者写的eslint部分在user.setting中配置了
"files.autoSave":"off",
    "eslint.validate": [
       "javascript",
       "javascriptreact",
       "html",
       { "language": "vue", "autoFix": true }
     ],
     "eslint.options": {
        "plugins": ["html"]
     }
但是保存代码的时候还是不能自动格式化代码，只会在终端中打印出哪里格式有问题，请问是为什么
![image](https://user-images.githubusercontent.com/37991444/47059974-2f48d200-d1fe-11e8-95d7-f1cd7efab6cf.png)

![image](https://user-images.githubusercontent.com/37991444/47059937-14765d80-d1fe-11e8-9d50-357dd623565e.png)

**Comment by PanJiaChen** [comment]
请按照最新文档[配置](https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/eslint.html#vscode-%E9%85%8D%E7%BD%AE-eslint)

**Comment by brucelpt** [comment]
> 请按照最新文档[配置](https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/eslint.html#vscode-%E9%85%8D%E7%BD%AE-eslint)

可以了谢谢大佬
