### ISSUE TITLE
多级菜单问题，求解...

### ISSUE THREAD

**Issue by wodeMAX** [PanJiaChen/vue-element-admin#1212]
可能我用的版本比较老。
路由中创建三级路由时候，侧边栏可以正常显示，第一次点击三级路由正常，以后每次一次都会重复添加地址。
比如说我三级路由是/beta/test/main，第二次点击路由地址变成beta/test/test/main，第三次点击路由地址变成beta/test/test/test/main，求大佬不吝赐教。

**Comment by PanJiaChen** [comment]
你先看看目前显示版本有这问题么。

**Comment by wodeMAX** [comment]
多谢大牛回答，当前版本无问题，是通过resolvePath函数处理解决了这个问题吗。

**Comment by PanJiaChen** [comment]
主要是我也不知道你用的是什么版本的代码了，你自己对不一下吧。

**Comment by wodeMAX** [comment]
好的，麻烦大牛了，谢谢啦。

**Comment by hwlv** [comment]
path不是node的模块吗。为啥前端页面上也能用呢。
