### ISSUE TITLE
axios 换成graphql麻烦么？

### ISSUE THREAD

**Issue by callmesoul** [PanJiaChen/vue-element-admin#1214]
axios 换成graphql麻烦么？

**Comment by PanJiaChen** [comment]
这两个不冲突。

**Comment by callmesoul** [comment]
ok

**Comment by gotexis** [comment]
+1 for GraphQL.

It seems that many will consider GraphQL to be the successor of REST due to its simplicity... 

Wouldn't the reason you claim it to be of much trouble to be that it is a rather new thing with less community packages and existing solutions.
