### ISSUE TITLE
tagView切换重新加载问题

### ISSUE THREAD

**Issue by bodekjan** [PanJiaChen/vue-element-admin#1215]
tagView中有A和B两个页面，其中A是数据列表，B是表单页面，我在B中填数据到一半的时候切换到A中看一下然后切换回到B页面的时候，B页面重新加载把之前填到一半的数据弄没了，这个有没有办法B不要总是重新加载？

**Comment by PanJiaChen** [comment]
现在有什么问题么？ 只要你b页面不是具有动态参数的路由，都会被缓存的吧。

**Comment by elf2017spring** [comment]
我也有这个问题，求大神指导。。。。

**Comment by mc7qing** [comment]
看了文档 把
![qq 20181121120712](https://user-images.githubusercontent.com/33148552/48818386-0d56e800-ed86-11e8-80ff-b763558dfb28.png)  :include="cachedViews" 移除了 直接缓存所有页面 应该是比较符合当前的需求了

**Comment by Jamayette** [comment]
> 看了文档 把
> ![qq 20181121120712](https://user-images.githubusercontent.com/33148552/48818386-0d56e800-ed86-11e8-80ff-b763558dfb28.png) :include="cachedViews" 移除了 直接缓存所有页面 应该是比较符合当前的需求了

这样的话 你下次打开这个页面不会刷新

**Comment by zengfan0605** [comment]
这样的话你试试查看详情会不会有问题

**Comment by mudong1991** [comment]
需要把你vue的 name 与router index里面的name保持一致即可
