### ISSUE TITLE
vue-router uncaught error during route navigation

### ISSUE THREAD

**Issue by ZhantongJiang** [PanJiaChen/vue-element-admin#1216]
没有打包之前，路由配置一切正常
after npm run build,  run "this.$router.push(xxx)" call error like this picture
![image](https://user-images.githubusercontent.com/20454330/47084214-76a68100-d245-11e8-8b87-038c121a5e71.png)
![image](https://user-images.githubusercontent.com/20454330/47084301-af465a80-d245-11e8-8d75-023ddaca1abe.png)

**Comment by PanJiaChen** [comment]
你用的是什么版本的 vue-element-admin ？
或者说你webpack什么版本？路由懒加载怎么写的？
