### ISSUE TITLE
代码不懂

### ISSUE THREAD

**Issue by mhtssb6666** [PanJiaChen/vue-element-admin#1220]
actions: {
    // 用户名登录
    LoginByUsername( {commit}, userInfo) {
      const username = userInfo.username.trim()
      return new Promise((resolve, reject) => {
        loginByUsername(username, userInfo.password).then(response => {
          console.log(response)
          if(response.data.state==0){
          console.log('token:' + response.data.data.username)
          commit('SET_TOKEN', response.data.data.username)
          setToken(response.data.data.username)
          }

问一下这个{commit}是方法吗,不是传一个dispatch对象吗，
然后就能直接commit了吗  => commit('SET_TOKEN', response.data.data.username)

**Comment by PanJiaChen** [comment]
请自行看 vuex 文档
