### ISSUE TITLE
tagsView的bug问题？看看尤大是否可以解决

### ISSUE THREAD

**Issue by chengmanxiang** [PanJiaChen/vue-element-admin#1221]
![1 8tg rc0vy ut rg p](https://user-images.githubusercontent.com/18214155/47140532-0fdea180-d2f1-11e8-9b01-76198b654cb2.png)

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/1223

**Comment by zhengjf1988** [comment]
我想问一下为什么在页面初始化之后调用setTagsViewTitle()
面包屑的title并没有改变，我来回切换一些面包屑就改变了。为什么呢？
