### ISSUE TITLE
富文本编辑器bug？

### ISSUE THREAD

**Issue by oYangJingLun** [PanJiaChen/vue-element-admin#1225]
页面布局：一个模态框下有多个富文本编辑器
版本：4.7.5的tinymce
操作：打开模态框，每个富文本编辑器的数据能够显示出来，关闭，再打开，发现数据没有显示在编辑器中，但是发现数据有统计，很奇怪，应该是个bug，求群主帮助
统计是右下角的 25 WORDS POWERED BY TINYMCE，每次打开都有统计

**Comment by PanJiaChen** [comment]
什么版本的 `vue-element-admin`?

**Comment by oYangJingLun** [comment]
3.6.5，必须全部更新到3.9.1吗？我是单独更新的编辑器这块

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/87b319d96ac3998f7d496fc3a64a608d8c111151
你更新一下这块代码 看是不是这个问题。

**Comment by oYangJingLun** [comment]
整个关于editor的代码都已经更新了，是不是tinymce组件下index.vue存在缺陷？

**Comment by PanJiaChen** [comment]
没能重现

**Comment by oYangJingLun** [comment]
晚上下班我再调一下，请先不要close~~
