### ISSUE TITLE
logout tagsview reset

### ISSUE THREAD

**Issue by de1ck** [PanJiaChen/vue-element-admin#1227]
登出后 tagsview  的数据没有重置

**Comment by PanJiaChen** [comment]
没有重现。
理论上也不会，现在登出后会刷新页面，所以不太会出现你说的问题。

**Comment by de1ck** [comment]
> 没有重现。
> 理论上也不会，现在登出后会刷新页面，所以不太会出现你说的问题。
sry,没注意在登出后，你使用了location.reload() 重置了vuex数据
[code](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/layout/components/Navbar.vue#L84)
` this.$store.dispatch('LogOut').then(() => {
        location.reload()// In order to re-instantiate the vue-router object to avoid bugs
      })`
并在 route before [permission](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/permission.js#L55) 把  redirect目前设置为登出前的路由
在登录成功的时候调整到该路由
[Login](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/login/index.vue#L130)
如果这个页面路由没有权限是不是会有问题

**Comment by PanJiaChen** [comment]
> 如果这个页面路由没有权限是不是会有问题
什么意思

**Comment by de1ck** [comment]
> > 如果这个页面路由没有权限是不是会有问题
> > 什么意思

登出后的页面是admin独有页面，切换另一个edirot用户登录 https://panjiachen.github.io/vue-element-admin/#/permission/page

**Comment by PanJiaChen** [comment]
可以加一个判断。

**Comment by yqnetwork** [comment]
element-admin 实现的logout体验很不好。location.reload() 一、会让登出再登陆变得很缓慢，重新加载页面会很慢。二、体现在electron里面登出后登陆会白屏，因为重新加载页面的原因。

**Comment by PanJiaChen** [comment]
@yqnetwork 暂时登出暂时无解。和目前权限实现的机制有关。 vue-router只有 `addroutes`没有版本移除已添加的路由，所以只能刷新页面。

**Comment by hahadaxia** [comment]
后台api给vue-admin发送什么数据，可以让前端实现登出效果。
我在easy-mock没看到有数据发送

**Comment by hahadaxia** [comment]
已经找到答案了https://github.com/PanJiaChen/vue-admin-template/issues/58
