### ISSUE TITLE
怎样兼容chrome 49 

### ISSUE THREAD

**Issue by 764438560** [PanJiaChen/vue-element-admin#1229]
大神们，怎样配置才能兼容chrome 49

**Comment by wodeMAX** [comment]
不可能，Vue最低IE9。

**Comment by 764438560** [comment]
那为什么用chrome 49直接打开项目演示地址没问题，自己打包之后用chrome 49就打不开

**Comment by 764438560** [comment]
> 
> 
> 不可能，Vue最低IE9。

那为什么虚拟机上可以用chrome 49直接打开项目地址，并且没有兼容性，而自己打包的就打不开

**Comment by wodeMAX** [comment]
看错看错。。。看成IE9了，打包有什么提示吗。
