### ISSUE TITLE
请问一下拉取用户信息后是如何存储用户信息的？只用 vuex 吗？还是需要用 localstorage 或 cookie？

### ISSUE THREAD

**Issue by luyilin** [PanJiaChen/vue-element-admin#123]
我在开发过程中发现使用 vuex 存储信息在刷新后会丢失，但是没有看到这个项目里使用 localstorage 或者 cookie 存储用户信息，所以想请问一下你是如何存储这些用户信息并保持信息不丢失的？

**Comment by PanJiaChen** [comment]
刷新页面可能会导致vuex 丢失存储信息的，我这里这是刷新后会重新拉一个接口获取信息，从而看起来像保持住了一样

**Comment by luyilin** [comment]
那在实际项目开发中也是每次刷新都重新拉接口吗？还是使用 localstorage 存储呢？直接存储到 localstorage 里是不是不太安全？能不能请问一下你对这两种方式的看法？

**Comment by PanJiaChen** [comment]
看需求 各有不同用处

**Comment by luyilin** [comment]
能不能请问一下你使用这两种方法的业务场景是怎样的？我比较困惑如何选择这两种方式，望解答，谢谢！

**Comment by PanJiaChen** [comment]
如果你存用户信息的话建议还是不要存在本地了，因为用户信息会一直变 如角色或者其他基本信息。localstorage一般用来存储一些不变的东西，如一些草稿或者table表单的信息

**Comment by luyilin** [comment]
了解了，非常感谢！✌️
