### ISSUE TITLE
我知道后台项目没有seo，但是我还是想问一下，

### ISSUE THREAD

**Issue by dawayway** [PanJiaChen/vue-element-admin#1231]
裤衩哥，我知道后台项目没有seo，但是我还是想问一下，这个项目能不能加上seo，因为我看他element在谷歌和百度上面搜索显示是不一样的，所以我很好奇，我也看了很多文章，好多人推荐使用Next方案，不知道裤衩哥有什么想法呢，打扰了，谢谢！！！
![_20181019172310](https://user-images.githubusercontent.com/26194367/47209545-2e14d200-d3c3-11e8-81d9-e7d821afaef6.png)
![_20181019172328](https://user-images.githubusercontent.com/26194367/47209549-33721c80-d3c3-11e8-82a8-69036f0f3697.png)

**Comment by PanJiaChen** [comment]
google 还 百度的 seo做法是不同的。具体需要查看相关问题。

seo 主流的就两种 ssr 和 pre-render。
