### ISSUE TITLE
在全局守卫中，通过接口查询权限问题

### ISSUE THREAD

**Issue by hefeng1208** [PanJiaChen/vue-element-admin#1234]
* 用户需要开通某个菜单对应的服务才能使用。
* 比如： 点击菜单时，需要判断是否开通，没开通就跳开通页，菜单有另一个团队开发。这个时候，如果查询开通接口慢，可能会造成页面短暂白屏问题？即使加上Nprogress这个效果也不是很理想，请教一下，有什么好的解决办法吗？

**Comment by PanJiaChen** [comment]
为什么要点击菜单时候才判断有没有权限？为什么不能一登录就查询权限，只返回有权限的侧边栏？

**Comment by hefeng1208** [comment]
这个公司业务有关，登录和菜单都是分开的（且域名不同）
请问有办法能够解决吗？ 虽然Nprogress可以，但是效果不理想，接口慢的时候内容区域是空白的。这个体验非常不好

**Comment by nabaonan** [comment]
> 这个公司业务有关，登录和菜单都是分开的（且域名不同）
> 请问有办法能够解决吗？ 虽然Nprogress可以，但是效果不理想，接口慢的时候内容区域是空白的。这个体验非常不好

写个loading呗

**Comment by PanJiaChen** [comment]
你这个问题的根本是接口慢吧。。感觉有点本末倒置了。

加loading只是一个前端hack罢了。

**Comment by hefeng1208** [comment]
@nabaonan写loading,你的意思在全局增加一个loading? 想过，我试一下吧，多谢。
@PanJiaChen 是的 核心其实是接口的问题。我在全局加一个loading页试试吧，多谢。
