### ISSUE TITLE
pagination 

### ISSUE THREAD

**Issue by suen427** [PanJiaChen/vue-element-admin#1239]
异步分页，当page size 大小改变时，pagination事件触发时，pagination的limit还没改过来。这导致请求来的条目数和期望的不同。

**Comment by PanJiaChen** [comment]
你是在说现在封装的[Pagination](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/components/Pagination/index.vue)组件么？

我并没能重现你的问题

**Comment by superZhouDaLu** [comment]
升级一下element-ui版本即可解决此问题。

**Comment by yuduanopen** [comment]
> 在他写得Pagination这个组件里面加入v-if="total"，如下黑色加粗部分，因为异步读取数据时total一开始是没有值的，但是分页控件其他信息已经加载好。

<el-pagination
      **v-if="total"**
      :background="background"
      :current-page.sync="currentPage"
      :page-size.sync="pageSize"
      :layout="layout"
      :total="total"
      v-bind="$attrs"
      @size-change="handleSizeChange"
      @current-change="handleCurrentChange"/>

**Comment by yuduanopen** [comment]
> 你是在说现在封装的[Pagination](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/components/Pagination/index.vue)组件么？
> 
> 我并没能重现你的问题

不是的 因为你读的是mock数据，你异步读取后台数据，就会有个加载延迟的情况

**Comment by Thomastar** [comment]
我也遇到这样的问题。但是加了 v-if="total" 还是不行

**Comment by PanJiaChen** [comment]
升级 element 至 `2.4.7`以上版本就可以了。
