### ISSUE TITLE
vuex 数据共享的问题，求助

### ISSUE THREAD

**Issue by sunlanlisa** [PanJiaChen/vue-element-admin#124]
我的项目中有好些数据很多地方都需要用到，所以想利用vuex，在登录之后就就异步请求这些接口，讲数据存在state中。
登录的时候做了拉取
store.dispatch('getDeptData');
store.dispatch('centersData');

getter中已经设置：
const getters = {
    sidebar: state => state.app.sidebar,
    token: state => state.user.token,
    allDepartmentlist: state => state.user.allDepartmentlist,
    deptJson: state => state.user.deptJson,
    allCenters: state => state.user.allCenters,
};

我在页面中用
computed: {
            ...mapGetters([
                'token'
                'deptJson',
                'allCenters'
            ]),
        }

但是除了token（这个是从cookie中获取，非接口请求），其它数据都取不到。 用this.$state.user 这个打印出来里面每项都有数据，但是再进一层this.$state.user.deptJson  就取不到数据了

**Comment by PanJiaChen** [comment]
个人感觉是你打印的时候数据还未拉倒，this.$state.user能打印出来是应为是一个对象，所以console.log的时候会有，你可以打个断点试试，从你现有提供代码 无法看出问题。

**Comment by sunlanlisa** [comment]
嗯，的确是。现在可以了。~~我这块还有个问题，就是我们的项目很多地方用单页面的连接，这样就丢失了vuex中存的数据~~有这方面的解决方案吗，localstorage？

**Comment by PanJiaChen** [comment]
没懂什么意思

**Comment by sunlanlisa** [comment]
就是vuex提前请求的数据，在页面刷新后就会丢失~~比如我登录之后，接口获取了用户数据及其它许多公用的数据，登陆后的刷新页面，其实这些数据会丢失~

**Comment by PanJiaChen** [comment]
这是合理的啊，vuex作用又不是做这个的
