### ISSUE TITLE
请问您的导航菜单跳转为什么要用router-link包裹el-menu-item？

### ISSUE THREAD

**Issue by tanhualang** [PanJiaChen/vue-element-admin#1240]
我仿照您做的时候，是在el-menu上加router，能正常跳转。但是高亮有点问题，第一次点击的菜单能高亮，但是第二次以后点已经点过的菜单，高亮加不上。:default-active="$route.path"也是有的，不知道什么原因。
![ss](https://user-images.githubusercontent.com/30031243/47285191-a7f3c800-d61c-11e8-8169-b777694b5d9a.jpg)
![aaz](https://user-images.githubusercontent.com/30031243/47285227-c3f76980-d61c-11e8-990d-d0d14d334ec2.jpg)
![ccc](https://user-images.githubusercontent.com/30031243/47285300-f608cb80-d61c-11e8-9802-f0f83368bbb5.jpg)

**Comment by PanJiaChen** [comment]
因为 el-menu 的 调整默认不是 a标签，所以不支持一些快捷键。

你的问题，并没能重现。

**Comment by tanhualang** [comment]
> 因为el-menu的调整默认不是一个标签，所以不支持一些快捷键。
> 
> 你的问题，并没能重现。

没太明白，我写的哪里有问题呢？

**Comment by tanhualang** [comment]
> > 因为EL-菜单的调整默认不是一个标签，所以不支持一些快捷键。
> > 你的问题，并没能重现。
> 
> 没太明白，我写的哪里有问题呢？

导航循环我是循环了三级，没有无限循环，其他都没啥问题，就是高亮这，第一次点击正确，第二次点击就不匹配了。难道是因为addrouters的原因？

**Comment by PanJiaChen** [comment]
若觉得有问题，请提供一个最小可还原demo
