### ISSUE TITLE
求助，是否可以在tag-views行显示同一路由的多个标签

### ISSUE THREAD

**Issue by bufudanqing** [PanJiaChen/vue-element-admin#1244]
就是会有同一个路由的页面，但是这些路由的参数不同，能否类似新建会话，每个人的会话窗口长得一样，但是每个路由会携带不同会话用户ID,能否把这些相同路由不同参数的页面同时显示为标签，然后点不同标签进入不同用户的会话页

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/example/edit.vue

这个页面就是你想要的效果吧。

![image](https://user-images.githubusercontent.com/8121621/47343442-a556a880-d6d8-11e8-9e08-8ce917564521.png)

**Comment by bufudanqing** [comment]
> https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/example/edit.vue
> 
> 这个页面就是你想要的效果吧。
> 
> ![image](https://user-images.githubusercontent.com/8121621/47343442-a556a880-d6d8-11e8-9e08-8ce917564521.png)

谢谢，是我想要的效果，我去研究下，谢谢

**Comment by bufudanqing** [comment]
你好，请问加的是哪个参数来控制相同路由名但参数不同的页面同时出现在标签tag行的，看了tagView页面没找到

**Comment by zaohuayudie** [comment]
> https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/example/edit.vue
> 
> 这个页面就是你想要的效果吧。
> 
> ![image](https://user-images.githubusercontent.com/8121621/47343442-a556a880-d6d8-11e8-9e08-8ce917564521.png)

这个有个严重问题，我编辑后没保存，切换编辑另一个后也未保存，切换回来后又重新还原未初始化数据，并没有保存正在编辑的内容

**Comment by zaohuayudie** [comment]
> > > https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/example/edit.vue
> > > 这个页面就是你想要的效果吧。
> > > ![image](https://user-images.githubusercontent.com/8121621/47343442-a556a880-d6d8-11e8-9e08-8ce917564521.png)
> > 
> > 
> > 这个有个严重问题，我编辑后没保存，切换编辑另一个后也未保存，切换回来后又重新还原未初始化数据，并没有保存正在编辑的内容
> 
> 需要你自己用localstorage保存编辑未完成的内容

**我已经找到了最好的解决方案：**
`给keepalive 里的 route-view 加一个 key就可以了， :key="$route.fullPath"`
