### ISSUE TITLE
右侧页面嵌套router-view的问题

### ISSUE THREAD

**Issue by ljkhello** [PanJiaChen/vue-element-admin#1254]
在views目录中，使用element步骤条做了一个步骤跳转，期望实现上边的步骤条、下边的按钮（上一步、下一步）固定不刷新，之刷新中间的router-view部分。
vue实现如下：
`<el-header>
      <div class="app-container">
        <el-steps :active="step" align-center finish-status="success">
          <el-step title="步骤1" description=""/>
          <el-step title="步骤2" description=""/>          
        </el-steps>
        <hr>
    </div>
</el-header>
    <el-main>
     <router-view/>------这里很重要
      <div class="text-center">
        <el-button@click="nextStep">下一步</el-button>
      </div>
    </el-main>`

其中点击下一步实现的是
this.$router.push('test/step2')

route定义：
{
  path: '/xxxx',
  component: Layout,
  redirect: 'noredirect',
  children: [
  {
    path: 'test',
    component: () => import('../views/test'),
    name: 'test',
    meta: { title: 'EditCampaign', icon: 'dashboard' },
    children: [
      { path: '', component: () => import('../views/step1'), hidden: true },
      { path: 'step1', component: () => import('../views/step1'), hidden: true },
      { path: 'step2', component: () => import('../views/step2'), hidden: true }
   ]
  }
}
但是最终的效果，几个问题：
1、访问对应的test路径时，头部navbar没有展示对应的标题
2、点击下一步时，页面还是刷新整个页面，没有达到预期效果（但是在vue-element-admin框架外单独使用没问题）

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/1a345a7c657bdbd8422103e9034f1a4d19676c0a/src/views/layout/components/AppMain.vue#L5

移除key。

第一个问题，在本项目中不能实现。

解决方案，不要使用路由。直接用组件实现。

**Comment by qinluyang** [comment]
用组件实现当步骤比较多的时候，页面会非常大且复杂，有没有更好的实现方式？或者pan神考虑支持新的模式？

**Comment by PanJiaChen** [comment]
页面和组件有什么区别。。。对于代码来说都算是一个sfc

**Comment by qinluyang** [comment]
对写代码没所谓，但是页面太庞大，客户端加载页面的时候会受影响吧

**Comment by PanJiaChen** [comment]
你现在都是spa。。。有区别么。。
