### ISSUE TITLE
建议TagsView组件的右键菜单增加边界判断

### ISSUE THREAD

**Issue by mygu** [PanJiaChen/vue-element-admin#1255]
> 建议右键菜单增加左右边界的判断来控制显示的浮动方向

![qq 20181025095948](https://user-images.githubusercontent.com/3753924/47471445-c7693b80-d83c-11e8-9414-294d6920fafd.png)

![qq 20181025100107](https://user-images.githubusercontent.com/3753924/47471466-f384bc80-d83c-11e8-822d-3310e6dfd6e0.png)

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/1256
