### ISSUE TITLE
导入excel界面的一个小bug

### ISSUE THREAD

**Issue by djknight1** [PanJiaChen/vue-element-admin#1260]
![image](https://user-images.githubusercontent.com/33688921/47486333-b3403100-d872-11e8-8551-b83a846bc9b0.png)
当你导入excel的时候，browse按钮有时会变成loading状态，有时不会。我在重写你的项目时也遇到了这个bug,不知道是什么问题，尝试过用nextTick和promise都无法解决

**Comment by PanJiaChen** [comment]
有时候上传的文件比较小，解析比较快。所以就看起来没有loading状态。

若还有问题，起提供可复现的步骤。
