### ISSUE TITLE
HELP! 服务器渲染路由遇到莫名问题

### ISSUE THREAD

**Issue by YoRenChen** [PanJiaChen/vue-element-admin#1262]
我想通过服务器拉取权限菜单下来，渲染之后就会出现下面情况
![image](https://user-images.githubusercontent.com/30005394/47549747-91f14a80-d92f-11e8-94cd-06a2ca68816b.png)

对比了一下数据
后端渲染路由数据:
![image](https://user-images.githubusercontent.com/30005394/47550044-85b9bd00-d930-11e8-91c6-5f9c4186592f.png)
然后就不知所措了- -，原谅我的技术
刚起手vue-element-admin框架有些东西弄不是很明白，还请打点指教一下

**Comment by PanJiaChen** [comment]
我还真没明白你想表达什么问题

**Comment by nabaonan** [comment]
这个应该是配置的component有问题导致的吧，看看组件是否引用正确，是不是子组件的component引用了父组件的？感觉是你写了一个redirect：“noreidrect”导致的
![image](https://user-images.githubusercontent.com/17247526/47552024-41c9b680-d936-11e8-8830-c8dfd78c21d2.png)

**Comment by YoRenChen** [comment]
YES，因为我这个是三级嵌套路由，所有第二个分级菜单也加了一个layout作为component，所以就会出现嵌套两层的现象

**Comment by YoRenChen** [comment]
结了- - ，是我的失误操作（尴尬）
