### ISSUE TITLE
解决了static文件下的css、js等静态资源缓存问题

### ISSUE THREAD

**Issue by quqingfei** [PanJiaChen/vue-element-admin#1263]
**由于现在的系统内部会使用大量静态页面，此项目打包时候又没法给html引入的css或者js加时间戳等，导致服务端静态static文件夹中的js或者css文件更新了，但客户端任然缓存着之前未更改的文件。这里我附上自己的解决办法**，如下：

`<link rel="stylesheet" href="./css/style.css?t={vision}">`

添加{vision}标识，在打包时候通过项目自带的copy-webpack-plugin插件的transform功能替换其中{vision}，vision可以自己替换成自己想要的任何字符
```
new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        // to: config.build.assetsSubDirectory,
        to: config.build.assetsStatic,
        ignore: ['.*'],
        transform(content, path) {
          if (/\.[^\.]+$/.exec(path) == '.html') {
            var allstr = content.toString().replace(/{vision}/g, Date.now())
            return allstr
          } else {
            return content
          }
        },
      }
    ])
```
如此炮制，即可得到打包后，自带时间戳，如果引入一些其他第三方的就不需要加{vision}，
<link rel="stylesheet" href="./css/style.css?t=1540536915496">
如法炮制，也可以做到给静态文件提供全局变量，宏设置一些通过webpack的内容

希望PanJiaChen能采用

**Comment by PanJiaChen** [comment]
感觉没啥必要，现在webpack 打包都是基本 contenthash 其实就相当于version了

**Comment by quqingfei** [comment]
不是啊，static文件夹下静态资源只是单纯的从static复制过去的。没有处理任何静态资源缓存的问题

**Comment by PanJiaChen** [comment]
为什么要处理？
![image](https://user-images.githubusercontent.com/8121621/47556351-b0ac0d00-d940-11e8-8a6c-676a85957aa8.png)

不是已经处理好了？为什么要加版本号？

每次版本改动，并不是所有的js都需要变动啊。基于内容的hash才是稳定的吧。

**Comment by quqingfei** [comment]
麻烦大佬用心看一下，我说的是**satic文件夹**内的用html+css+js写的内容，不是src文件夹下面用vue写的页面。vue写的页面都在src下面，static文件夹下面都是html+js+css文件

**Comment by PanJiaChen** [comment]
哦理解你的问题了，你是说html缓存。你这个的确是一个解决方案。
目前我采用方案是，html永不缓存，所有浏览器不会缓存.html

**Comment by quqingfei** [comment]
关键时html引入的css和js会被浏览器缓存，解决html引入的js和css才是关键。而且用我这个方法还可以分其他{ aaa }这种在static下面做宏定义。想必是极好得！

**Comment by PanJiaChen** [comment]
vision 你的怎么控制呢？每次的git版本号还是手动维护？

**Comment by quqingfei** [comment]
直接一个时间戳就行了啊，每次打包每次都生成不同的时间戳， content.toString().replace(/{vision}/g, Date.now())，线上只有一个固定的时间戳，如果只更改了vue没又更改static，可以在命令行传参或者建立一个命令只打包src文件不就Ok了

**Comment by PanJiaChen** [comment]
所以还是需要人工干预的，和直接改源文件 static/下面文件的名字有多大区别呢。

`/static/tinymce3.5` =>`/static/tinymce3.6`

**Comment by quqingfei** [comment]
`/satic/heal/index.html `内有`<link rel="stylesheet" href="./css/health.css">`这个，难道我改动了health.css文件还得跑回去改一次一次html文件内的health.css的版本号么？如果有`/satic/rank/index.html `下面也用到了health.css怎么办？都一起改么？
