### ISSUE TITLE
项目开发

### ISSUE THREAD

**Issue by yuqingzhijie** [PanJiaChen/vue-element-admin#1264]
本来想看项目怎么一步步开发完成的。克隆下来才发现一步到位。。

**Comment by yuqingzhijie** [comment]
![image](https://user-images.githubusercontent.com/18495266/47553570-06c98200-d93a-11e8-97be-c28d4d991766.png)

**Comment by PanJiaChen** [comment]
没懂？你想看 commit记录？

**Comment by yuqingzhijie** [comment]
我想看的是项目的开发过程，不是看现成的项目源代码，commit记录我查了，发现第五次commit----init，项目就基本开发完成了。所以想问下你还保留着开发这项目时的commit记录吗。而不是开发完成后修修补补的commit记录

**Comment by PanJiaChen** [comment]
不还意思，并没有。
本项目也是基于公司项目抽离出来的，所有也不算一步一步从零构建的。

我觉得你想学习的话看 https://github.com/PanJiaChen/vue-admin-template 应该差不多了，代码量不多的。

**Comment by yuqingzhijie** [comment]
这有点简单，算了
