### ISSUE TITLE
项目下载下来VScode编辑器报错

### ISSUE THREAD

**Issue by wengyulin** [PanJiaChen/vue-element-admin#1266]
![jietus](https://user-images.githubusercontent.com/8219669/47559725-d3daba80-d948-11e8-848a-b0c61eb722fa.png)

**下载下来用vscode编辑器打开后这里报红色了，eslint也打开了，是因为什么啊**

**Comment by PanJiaChen** [comment]
你至少hover一下 让我知道报什么错

**Comment by wengyulin** [comment]
![cuowu](https://user-images.githubusercontent.com/8219669/47612288-ac9ffc80-dab2-11e8-835e-f892ca9d03f2.png)
**报了这个错**

**Comment by wengyulin** [comment]
大佬看看这是什么问题

**Comment by PanJiaChen** [comment]
你用了 typescript?

**Comment by wengyulin** [comment]
没有，就是单纯的把你的代码clone下来然后用vscode打开就这样了

**Comment by zthxxx** [comment]
@wengyulin 
vscode 正确配置 nodejs 环境了吗？
node 版本配置的多少，>8 了吗

**Comment by czy** [comment]
> ![cuowu](https://user-images.githubusercontent.com/8219669/47612288-ac9ffc80-dab2-11e8-835e-f892ca9d03f2.png)
> **报了这个错**

![image](https://user-images.githubusercontent.com/1300315/47691091-a8e3b580-dc2b-11e8-84b2-27c9bcd9174b.png)

装上这个插件试试

**Comment by wengyulin** [comment]
正确配置了，node版本是8.9.4

**Comment by ensleep** [comment]
看起来像是vscode的问题，直接cnpm run dev应该是可以运行的吧。

**Comment by wengyulin** [comment]
可以运行 没问题，只是vscode有这个红色波浪线这个。

**Comment by yuxianwen** [comment]
吧vscode 的eslint 禁用掉 本身项目已经装了eslint了 就没必要用vscode插件的eslint了 

看着这么多波浪线 心里发麻~

**Comment by wengyulin** [comment]
> 你用了 typescript? 或者做过其它改动么？
是VScode版本问题，升级就可以了，大佬关了吧

**Comment by wengyulin** [comment]
@PanJiaChen  大佬。是VScode问题，升级版本就可以了，关掉吧
