### ISSUE TITLE
项目中element-ui中tree 节点删除问题及解决办法

### ISSUE THREAD

**Issue by 18106960985** [PanJiaChen/vue-element-admin#1268]
目前项目中使用的element-ui版本tree组件存在问题。
 问题描述：
   使用tree node remove方法时，当前节点不会被删除。
 问题排查：
   经过排查发现 remove时nodeData 数据会被正常的删除，而element-ui的$emit通知出现了异常（这个部分我没有继续深究， 导致改节点的components依旧存在，add方法没有问题。
解决办法：
   对element-ui版本降级处理 可以使用2.3.2。

**Comment by PanJiaChen** [comment]
你指的 tree 是什么？
是element 的 tree组件还是 本项目封装的 table-tree 组件？

**Comment by 18106960985** [comment]
element 里的tree组件

**Comment by PanJiaChen** [comment]
所有为什么要在本项目下提问。。。

**Comment by 18106960985** [comment]
嗯。。这个问题我也不知道。。只是我刚刚好在用你的模板时候遇到了。。
