### ISSUE TITLE
点击侧边栏,刷新当前路由

### ISSUE THREAD

**Issue by wangxu011** [PanJiaChen/vue-element-admin#1269]
**点击侧边栏,刷新当前路由，您的方法是先跳转到一个专门 Redirect 的页面，它会将路由重定向到我想去的页面，能否有demo看一下，我自己写的没有成功，多谢！**

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/0740bb36f7346f9c6c415c9c0cb5a5c3f3982f72/src/components/SizeSelect/index.vue#L39

https://github.com/PanJiaChen/vue-element-admin/blob/0740bb36f7346f9c6c415c9c0cb5a5c3f3982f72/src/views/layout/components/AppMain.vue#L5

**Comment by wangxu011** [comment]
![image](https://user-images.githubusercontent.com/25812979/47696159-78f2dd00-dc40-11e8-9795-37f23664bbc9.png)

**Comment by wangxu011** [comment]
这个跳转不太理解，不是应该跳转到 '/redirect'，然后再 ‘/redirect’页面在就行重定向吗？这是我的代码：
![image](https://user-images.githubusercontent.com/25812979/47696244-cff8b200-dc40-11e8-9200-55b3f65cae71.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/redirect/index.vue

现在不就是么。。。

**Comment by wangxu011** [comment]
解决了，我理解错了，多谢！
