### ISSUE TITLE
小白提问如何实现一个可导入多个vue单文件组件的modal对话框组件

### ISSUE THREAD

**Issue by DaoqiuDong** [PanJiaChen/vue-element-admin#127]
现有的项目需求是让用户在modal弹框进行一系列操作，想自己封装一个可导入组件的modal组件，常见弹框组件无法导入单文件组件，想问一下具体实现思路？

**Comment by PanJiaChen** [comment]
这我觉得你还是找一些现成的modal组件 借鉴着写 比较靠谱。
还有一般modal主体部分都是通过slot传进去的，所以你想传入什么组件都是可以的
