### ISSUE TITLE
this.$router.push 刷新页面问题

### ISSUE THREAD

**Issue by lfyfly** [PanJiaChen/vue-element-admin#1270]
`
this.$router.push({ name: this.$router.name, query: { t: Date.now() } })
`
在你的项目中这样写是可以刷新页面的，但我自己用建的项目不能刷新页面，版本都是vue-router@3.0.1，求解答。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/1d684b76328e3f6bcd3f75ea011087cce1c13a3c/src/views/layout/components/AppMain.vue#L5

**Comment by lfyfly** [comment]
谢谢
