### ISSUE TITLE
如何在切换标签的时候修改页面的标题

### ISSUE THREAD

**Issue by weituotian** [PanJiaChen/vue-element-admin#1272]
发现网页标题一直没有变化，如果选中哪个标签就改变当前网页标题，应该怎么做？
大大们有思路么？

**Comment by daiing** [comment]
网页标题写死在index.html里了吧，好像不太好改

**Comment by PanJiaChen** [comment]
不就一行代码么
```js
document.title = 'xxxx'
```

**Comment by weituotian** [comment]
@PanJiaChen 嗯，主要是网页title根据router变化而变化，还要考虑中英文切换的问题，比较复杂
