### ISSUE TITLE
tinymceId富文本编辑器一个页面只能实例化一个吗？

### ISSUE THREAD

**Issue by IdenPin** [PanJiaChen/vue-element-admin#1274]
tinymceId富文本编辑器一个页面只能实例化一个吗？
同一个页面第一个富文本编辑器展示没有问题，第一个就展示不出来了。也没有报任何错误
![image](https://user-images.githubusercontent.com/8908021/47699836-266ced00-dc4f-11e8-8059-b0e7fcf9d6ff.png)

**Comment by IdenPin** [comment]
```
 props: {
    id: {
      type: String,
      default: 'vue-tinymce-' + +new Date()
    },
}
```

刚看了封装的源码已经解决了，谢谢了。
如果用户调用组件没有传递id使用默认id就会出问题。
建议这块的id的生成规则可以使用uuid来替代

**Comment by PanJiaChen** [comment]
这是bug。。。已经修改了

**Comment by IdenPin** [comment]
@PanJiaChen   哦哦，那可能是我本地项目代码太早了。没更新
