### ISSUE TITLE
关于在request里面使用i18n多语言消息怎么实现？

### ISSUE THREAD

**Issue by 37764844** [PanJiaChen/vue-element-admin#1276]
你好！我在request中的MESSAGE添加多语言，但是运行的时候报错。Cannot read property '$t' of undefined
MessageBox.confirm(
        result.msg,
        this.$t('request.title'),
        {
          confirmButtonText: this.$t('request.confirmtext'),
          cancelButtonText: this.$t('request.canceltext'),
          type: 'warning'
        }）
请问怎么解决

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/730

**Comment by 37764844** [comment]
非常感谢
