### ISSUE TITLE
项目install报错

### ISSUE THREAD

**Issue by winnneror** [PanJiaChen/vue-element-admin#1277]
你好，项目install报错提示   gyp verb `which` failed Error: not found: python2

然后继续 run dev 报错Error: Cannot find module 'node-sass'

node版本8.12   vue 2.9    npm 6.4

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/25

**Comment by winnneror** [comment]
安装node-sass,后提示，

error  in ./src/views/dashboard/admin/components/TodoList/index.vue?vue&type=style&index=0&lang=scss&

**Comment by luohong123** [comment]
mac环境 npm 的时候也报错，解决方法是
```bash
sudo npm install -g cnpm --registry=https://registry.npm.taobao.org
sudo cnpm install
```
下载成功后，执行 `npm run dev` 启动项目，项目报错 
```js
Error: EACCES: permission denied，mkdir /vue-element-admin/node_modules/_mkdirp@0.5.1@mkdirp/index.js:90
                    throw err0;
```
访问被拒绝
在前面加 sudo
```bash 
sudo npm run dev
```
问题可解决，项目运行成功
