### ISSUE TITLE
請問如果項目有更新，可否直接 npm update 就行？

### ISSUE THREAD

**Issue by samuelchlui** [PanJiaChen/vue-element-admin#1281]
1. 會否考慮將安裝方法變成:

`$ vi package.json`

`"dependencies": {
"vue-element-admin": "^v3.9.3",
}`

`$ npm update`

你會繼續更新這個repo，但我要更新都要diff / replace，會用左一些時間，比較沒有效率。

2. 另外請問這個跟你們有關?
https://www.npmjs.com/package/vue-admin-element

**Comment by PanJiaChen** [comment]
1：本项目不算是一个组件，所以不太好作为npm包安装或者更新。之后会考虑出一下怎么方便更新。
2：和本项目无关。我也是第一次知道这个包。
