### ISSUE TITLE
这种多标签能不能缓存？

### ISSUE THREAD

**Issue by chengmanxiang** [PanJiaChen/vue-element-admin#1282]
![image](https://user-images.githubusercontent.com/18214155/47827434-e590e780-ddb8-11e8-9e32-dfedf3e2c800.png)
业务非常要求这种多标签要缓存，这个详情是这个项目最重要的一个页面，所以再次问作者，这种需求能不能做到，或者给个好点的思路？非常感谢

**Comment by PanJiaChen** [comment]
你确定你有好好看之前的issue么

**Comment by chengmanxiang** [comment]
你回复不能实现

**Comment by chengmanxiang** [comment]
> 你确定你有好好看之前的issue么

你说的只能通过name实现，这种不能缓存。

**Comment by PanJiaChen** [comment]
localstorage 自己缓存一下数据不就好了。

**Comment by chengmanxiang** [comment]
> localstorage 自己缓存一下数据不就好了。

没有好的办法吗？关键这个页面特别复杂，多维表，维度指标拖拽之类的，很多数据要保存的

**Comment by PanJiaChen** [comment]
localstorage  缓存数据很复杂么。。。

**Comment by chengmanxiang** [comment]
> localstorage 缓存数据很复杂么。。。

不复杂，就是感觉比较low，实在不行了我再使用。

**Comment by PanJiaChen** [comment]
反正目前用vue的 keep-alive 是肯定不行的。

**Comment by PanJiaChen** [comment]
有空了，我来做一个 `localstorage` 的缓存数据的demo吧。

**Comment by chengmanxiang** [comment]
> 有空了，我来做一个 `localstorage` 的缓存数据的demo吧。

ok，非常感谢

**Comment by chengmanxiang** [comment]
> 有空了，我来做一个 `localstorage` 的缓存数据的demo吧。

我用的keep-alive缓存的，详情页index组件缓存，详情页index组件里面再引入详情页真正的公众页面

**Comment by kankantian** [comment]
请问这个缓存问题解决了吗
我也遇到一样的问题了  keepAlive无法缓存列表数据

**Comment by chengmanxiang** [comment]
> 有空了，我来做一个 `localstorage` 的缓存数据的demo吧。

这个我已经实现，就你的vue-element-admin，设置noCache： true 就可以了，

**Comment by xiongjunwen1111** [comment]
老哥 写好能贴一下代码吗？

**Comment by xiongjunwen1111** [comment]
我也遇到了用keep-alive缓存 无效的问题 如果所有的页面用localstorage 来存 是不是工作量有点大啊
