### ISSUE TITLE
网络请求错误问题

### ISSUE THREAD

**Issue by xiujun58** [PanJiaChen/vue-element-admin#1283]
一个小白的问题，请大佬指教：
前端登录页面：
handleLogin() {
      this.$refs.loginForm.validate(valid => {
        if (valid) {
          this.loading = true
          this.$store.dispatch('LoginByUsername', this.loginForm).then(() => {
            this.loading = false
            this.$router.push({ path: this.redirect || '/' })
          }).catch((e) => {
            console.log(e)
            this.loading = false
          })
        } else {
          return false
        }
      })
    },
request.js代码
const service = axios.create({
  // baseURL: process.env.BASE_API, // api 的 base_url
  baseURL: 'http://app.9898.pro/api',
  withCredentials: true,
  timeout: 5000 // request timeout
})
login.js代码
export function loginByUsername(username, password) {
  const data = {
    username,
    password
  }
  return request({
    url: '/login/login',
    method: 'post',
    data
  })
}
main.js  已注释// import './mock' // simulation data

后端代码
![wechatimg31](https://user-images.githubusercontent.com/39918118/47828434-10316f00-ddbe-11e8-8f24-fc52994e2ef2.png)

控制台报错
![Uploading 1541038151065.jpg…]()

请大佬帮忙看一下，万分感谢

**Comment by xiujun58** [comment]
控制台报错如下
![1541038151065](https://user-images.githubusercontent.com/39918118/47828551-8fbf3e00-ddbe-11e8-9272-0acd0364b68d.jpg)

**Comment by PanJiaChen** [comment]
跨域问题，自行检索解决。

**Comment by lxk0301** [comment]
> 好的，已解决，非常感谢

请问你这个问题如何解决的呢?
