### ISSUE TITLE
部署后的网站加载非常慢

### ISSUE THREAD

**Issue by lixing0323** [PanJiaChen/vue-element-admin#1284]
你好，一直使用您的模板作为后台网站。以前部署后的网站一直加载很快，最近使用您的新代码后，重新做了一个后台网站，发现清除缓存后加载非常慢，请帮忙看下原因，谢谢啦。
部署的命令："build:dev": "cross-env BABEL_ENV=development env_config=dev node build/build.js",

<img width="950" alt="2018-11-01 10 59 59" src="https://user-images.githubusercontent.com/19339814/47830484-fb0d0e00-ddc6-11e8-9f66-97db043cfd01.png">

**Comment by PanJiaChen** [comment]
你静态资源慢，和本项目有什么关系。你觉得慢部署到CDN不就好了。
