### ISSUE TITLE
'removeEventListener' causes error on chart page

### ISSUE THREAD

**Issue by LarchLiu** [PanJiaChen/vue-element-admin#1285]
bug重现路径(MBP chrome)：
打开Charts下的任意chart，然后删除掉Cookie中token，再点击任意页面，此时就会有Error。

原因是在Charts下resize.js中的beforeDestroy通过document取sidebarElm然后removeEventListener，但是此时的document是跳转后的login页面，取不到sidebar导致错误。

同样的在Dashboard页面中的LineChart也有这个问题。

**Comment by PanJiaChen** [comment]
恩，是个bug，愿意的话可以提一个pr。
