### ISSUE TITLE
刷新页面，store.state 当中的数据丢失

### ISSUE THREAD

**Issue by palespring** [PanJiaChen/vue-element-admin#1287]
你好，我有个问题想请教一下：
在dashiboard页面时，如果我刷新页面，根据钩子函数当中的逻辑，都将进入getUserInfo( )当中重新获取用户信息，那么在这边我看到您写的是getUserInfo(state.token).then(response => {}) ，此刻，state.token显然是空值（因为state.token是在登录路由时候赋值进去的），获取不到。

**Comment by PanJiaChen** [comment]
token 存在 cookie 中。

https://github.com/PanJiaChen/vue-element-admin/blob/1d684b76328e3f6bcd3f75ea011087cce1c13a3c/src/store/modules/user.js#L9
