### ISSUE TITLE
使用你的模板,git提交代码的时候, 经常提交失败,报husky的错误

### ISSUE THREAD

**Issue by lxk0301** [PanJiaChen/vue-element-admin#1288]
![image](https://user-images.githubusercontent.com/21308593/47846146-f0bc3580-de01-11e8-9ab3-536c9ddde56b.png)
网上百度过,  也不知道如何解决这个这个,还请指教

**Comment by PanJiaChen** [comment]
打开git 日志 看报什么错

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/git-hook.html

不想要可以在 `package.json`中去掉。
