### ISSUE TITLE
两点建议

### ISSUE THREAD

**Issue by okjesse** [PanJiaChen/vue-element-admin#129]
1.左侧菜单在缩进去的时候，鼠标放上去触发最好不是把菜单显示出来，而是从右边展开，这个用户体验好很多。参照 https://adminlte.io/themes/AdminLTE/index2.html
2. 多tab切换样式最好不用tag,而是用tab，我这里现在是自定义写了个tag

以上，谢谢您的查看

**Comment by PanJiaChen** [comment]
关于第一点侧边栏的建议，体验上是可以优化一下。
tabs切换这个，个人觉得传统的tab是不适用的侵入性太大，还是倾向用tags替代。

**Comment by edwinhuish** [comment]
左边侧边栏可以参考这个的代码[taylorchen709/vue-admin](https://github.com/taylorchen709/vue-admin)

主题可以稍微优化一下，参考这个[lanux/Vue-Admin](https://github.com/lanux/Vue-Admin)

**Comment by edwinhuish** [comment]
@PanJiaChen 另外 “个人觉得传统的tab是不适用的侵入性太大” 这话什么意思?

**Comment by okjesse** [comment]
@PanJiaChen 我们现在也是用tab，可以封装成一个同样的组件，其实只是样式的问题

**Comment by edwinhuish** [comment]
我觉得你说的侵入性太大，应该是因为你既做导航菜单又做tab的原因，tab的话，注重多任务，没有必要导航菜单，一般导航菜单是用在单页的前台页面，后台页面直接tab即可，顶多在修改页面title。

样式可以参考我之前做的这个： [multitabs](http://edwinhuish.oschina.io/multi-tabs/demo/index.html)

**Comment by PanJiaChen** [comment]
侧边栏这个我看了下，如果基于element-ui改不太方便改，要做的话就基本要自己写一个nav了。taylorchen709/vue-admin这个是写了两套nav 个人不是很赞同。
其实最好的方案还是官方做，比如react的[ant](https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed) 就内置了

**Comment by edwinhuish** [comment]
不错，不过群主是否有考虑加入？

**Comment by PanJiaChen** [comment]
暂时给官方提了issue，长时间没答复可能会自己来实现

**Comment by PanJiaChen** [comment]
https://github.com/ElemeFE/element/pull/5941

**Comment by edwinhuish** [comment]
@PanJiaChen 既然官方已经解决了，请问什么时候合并呢?

**Comment by PanJiaChen** [comment]
@edwinhuish 官方的代码还有点问题，等他们完善了在替换

**Comment by Denny-coder** [comment]
最新ie浏览器一点兼容性需求都没有吗？ie11也打不开怎么破。。

**Comment by PanJiaChen** [comment]
@Denny-coder  那是因为有promise

**Comment by Denny-coder** [comment]
@PanJiaChen 如何才能进行兼容呢，还是根本不可能？

**Comment by PanJiaChen** [comment]
看项目的wiki，或习性搜索相关方法

**Comment by Denny-coder** [comment]
@PanJiaChen 好的，谢谢

**Comment by eddiebai** [comment]
@okjesse 这种简单的样式，你不会自己改嘛
