### ISSUE TITLE
vue-router noCache是不是只有在同一级路由下才有效

### ISSUE THREAD

**Issue by CaniceZ** [PanJiaChen/vue-element-admin#1292]
![_20181102164028](https://user-images.githubusercontent.com/23026625/47903072-23c3ff00-debe-11e8-960d-4bf8a61b8089.png)
![_20181102164046](https://user-images.githubusercontent.com/23026625/47903073-245c9580-debe-11e8-8718-528ea2c06e34.png)
公会管理下的view可以缓存，但是一点击其他tab的就会自动刷新

**Comment by PanJiaChen** [comment]
本项目线上demo能重现你的问题么？

**Comment by CaniceZ** [comment]
没下最新的，我对着线上代码看了下，好像也会，你的dashboardr和guild是设置了缓存的，但浏览器还是有请求

**Comment by CaniceZ** [comment]
> 本项目线上demo能重现你的问题么？

没下最新的，我对着线上代码看了下，好像也会，你的dashboardr和guild是设置了缓存的，但浏览器还是有请求

**Comment by PanJiaChen** [comment]
你指静态资源的缓存？

**Comment by CaniceZ** [comment]
> 你指静态资源的缓存？

路由keep-alive,就是会重新发请求，但是vuex的cachedViews是有这个页面

**Comment by PanJiaChen** [comment]
dashboardr和guild 都没有需要请求的数据。。。

所以你指的请求是什么

**Comment by CaniceZ** [comment]
![_20181102170323](https://user-images.githubusercontent.com/23026625/47905112-40ae0180-dec1-11e8-8764-60459ff781b0.png)

**Comment by CaniceZ** [comment]
> dashboardr和guild 都没有需要请求的数据。。。
> 
> 所以你指的请求是什么

我自己的项目是还会有ajax请求...

**Comment by PanJiaChen** [comment]
details.json 是广告的请求。。。和页面没关系

如果缓存失效了
请仔细看[文档](https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/tags-view.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

**Comment by CaniceZ** [comment]
> dashboardr和guild 都没有需要请求的数据。。。
> 
> 所以你指的请求是什么

![1541149603 1](https://user-images.githubusercontent.com/23026625/47905296-bade8600-dec1-11e8-9e9c-fd14b9a56c47.jpg)
比如公会列表我设置nocache；但是和推广小组不是同一级路由，切换的时候公会列表页会刷新

**Comment by CaniceZ** [comment]
> details.json 是广告的请求。。。和页面没关系
> 
> 如果缓存失效了
> 请仔细看[文档](https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/tags-view.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

好的，我自己再看下

**Comment by PanJiaChen** [comment]
目前已知问题是 三级嵌套会有问题，其它情况应该都是的好的。

**Comment by CaniceZ** [comment]
> 目前已知问题是 三级嵌套会有问题，其它情况应该都是的好的。

。。。我也是刚接手别人的项目，好像真的是有三层

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/406

**Comment by CaniceZ** [comment]
> #406

vuex里cacheview是有这个东西。。。而且我2级路由页也设置了nocache
