### ISSUE TITLE
editor角色登录后，手动在地址栏输入/permission/page，会进入到404页面，而不是401页面

### ISSUE THREAD

**Issue by irenetang1993** [PanJiaChen/vue-element-admin#1293]
asyncRouterMap的最后一条路由是{ path: '*', redirect: '/404', hidden: true }，所以当输入/permission/page之后，会直接匹配404错误，不会执行到permission.js中的
```
if (hasPermission(store.getters.roles, to.meta.roles)) {
    next()
 } else {
    next({ path: '/401', replace: true, query: { noGoBack: true }})
 }
```
就算asyncRouterMap中没有路由{ path: '*', redirect: '/404', hidden: true }，当输入/permission/page之后，也不会执行next({ path: '/401', replace: true, query: { noGoBack: true }})，因为路由表中没有该条路由，所以to.meta.roles是undefined，hasPermission返回的就是true。最终看到的就是一个什么都没有的页面

**Comment by PanJiaChen** [comment]
那就不要用 `addRouters`咯

全部都在 `router.beforeEach`进行判断。

**Comment by liaoyuhanCSDN** [comment]
所以楼主最后打算怎么解决的

**Comment by Supposer** [comment]
所以楼主最后打算怎么解决的  -. -!
