### ISSUE TITLE
use render but error

### ISSUE THREAD

**Issue by Hideer** [PanJiaChen/vue-element-admin#1297]
最版本，在使用vue的render函数和demo中一样的方式进行添加标签的时候报错如下
![image](https://user-images.githubusercontent.com/31301552/47961520-97ddde80-e047-11e8-8bc8-ab0406d8baae.png)
这是为什么呢

**Comment by PanJiaChen** [comment]
你确定有 [jsx](https://github.com/vuejs/babel-plugin-transform-vue-jsx)的插件么？

**Comment by Hideer** [comment]
你好，我还不太了解jsx插件，请问是babel-plugin-transform-vue-jsx这个插件么

**Comment by PanJiaChen** [comment]
恩
