### ISSUE TITLE
左侧导航菜单重复弹出

### ISSUE THREAD

**Issue by hioak** [PanJiaChen/vue-element-admin#1298]
当左侧导航栏折叠时候，点击导航栏按钮弹出二级菜单，当点击二级菜单菜单项时，二级菜单本该关闭，但是其关闭后又再次打开。这种情况偶尔会发生。不知道是什么原因。

**Comment by PanJiaChen** [comment]
不太能理解你的bug

**Comment by hioak** [comment]
看下我的截图：
![tim 20181105101546](https://user-images.githubusercontent.com/3831083/47974304-07091080-e0e4-11e8-8228-9c59d4d8768d.png)
我用的浏览器是：
firefox 63.0.1和chrome  69.0.3497.92

**Comment by PanJiaChen** [comment]
https://github.com/ElemeFE/element/issues/12512

**Comment by PanJiaChen** [comment]
官方已合并pr。
