### ISSUE TITLE
后面打算出滚动条组件吗？正常来说浏览器自带的滚动条外观实在一般

### ISSUE THREAD

**Issue by yuqingzhijie** [PanJiaChen/vue-element-admin#1299]

**Comment by PanJiaChen** [comment]
咱没打算。目前使用的 `element-ui`的 [scrollbar](https://github.com/ElemeFE/element/tree/dev/packages/scrollbar)

如果不太追求兼容性，简单的css就可以解决了。

**Comment by liyuchuan86** [comment]
现在是只有菜单有滚动，其他页面的滚动条样式都是原生，希望能解决下

**Comment by PanJiaChen** [comment]
有需求的自行添加。
