### ISSUE TITLE
perfect css of avatar-wrapper on the mobile phone

### ISSUE THREAD

**Issue by jaysunxiao** [PanJiaChen/vue-element-admin#1300]
![mobile-before-click](https://user-images.githubusercontent.com/34591889/47992209-40af3b00-e127-11e8-8d64-07e9ff2cc313.png)
![mobile-click-before-css](https://user-images.githubusercontent.com/34591889/47992240-56246500-e127-11e8-969a-fadb8cebdc9e.png)
### minimize the selected area of avatar on the mobile phone after perfecting css
![mobile-click-after](https://user-images.githubusercontent.com/34591889/47992473-f5e1f300-e127-11e8-9843-69f2fdebfe78.png)
![mobile-click-after-css](https://user-images.githubusercontent.com/34591889/47992483-fbd7d400-e127-11e8-8ce3-d19c0bb17340.png)

**Comment by PanJiaChen** [comment]
Welcome pr
