### ISSUE TITLE
面包屑组件 too much recursion

### ISSUE THREAD

**Issue by gp15237125756** [PanJiaChen/vue-element-admin#1310]
点击菜单 控制台显示src/componentsBreadcrumb/index.vue警告
[Vue warn]: Error in render: "InternalError: too much recursion"

**Comment by gp15237125756** [comment]
面包屑里面有个getBreadcrumb方法调用语句
let matched = this.$route.matched.filter(item => item.name);
应该是 this.$route.matched的问题，暂时没找到去掉警告的办法

**Comment by PanJiaChen** [comment]
你是修改过什么代码么？

**Comment by gp15237125756** [comment]
现在应该好了 没改什么东西 谢谢
