### ISSUE TITLE
登录成功时，后台写入cookie，但是devtool显示没有token，这是因为跨域造成的吗？

### ISSUE THREAD

**Issue by abumphy** [PanJiaChen/vue-element-admin#1311]

**Comment by baidan** [comment]
1，如果是前端打包的dist 扔在后台项目里面，后端是可以直接设置cookie的，浏览器同源策略
2，如果完全分离，后端和前端不在同一个host，或者不同端口下，后端都无法下发给不同源的前端项目中。
3，如果2成立，所以完全分离下，直接以加密的字符串，或者json格式直接返回给前端去存储。
