### ISSUE TITLE
配置路由时，一级路由下里只有一个二级路由，这时页面会把二级路由渲染成一级路由，这算bug吗？

### ISSUE THREAD

**Issue by Lchark** [PanJiaChen/vue-element-admin#1312]
![image](https://user-images.githubusercontent.com/40224100/48116825-39f90300-e2a2-11e8-87bb-7d2a70f16880.png)
![image](https://user-images.githubusercontent.com/40224100/48116907-79275400-e2a2-11e8-92f1-316afb7e99f5.png)

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/router-and-nav.html#%E4%BE%A7%E8%BE%B9%E6%A0%8F

![image](https://user-images.githubusercontent.com/8121621/48117554-86454280-e2a4-11e8-85e0-a1048b3c3daa.png)
