### ISSUE TITLE
Problem on the same route name but difference params??

### ISSUE THREAD

**Issue by thearabbit** [PanJiaChen/vue-element-admin#1313]
I follow this `Tag View` for my Admin Panel.
I have problem on `the same route name`, but difference `params/query`.
Ex:
```js
// Route
{
  path: '/customer/:id?', // Add new and Update Form in one place
  name: 'Customer'
  
}
```

**Comment by PanJiaChen** [comment]
??

So what you problem?

**Comment by thearabbit** [comment]
thanks for your reply.
For example I have `Customer CRUD`.
I use one `Customer Form Component` for `Insert and Update Form`
```js
<template>
Form
</template>
<script>
export default {
  name: 'CustomerForm'
  data(){
    return { 
      updateId: this.$route.params.id // for update form
    }
  }
}
```
```js
// Route
{
  path: '/customer/:id?'
  name: 'CustomerForm'
  .....
}
```
The problem
1- Click `add new` link to open `Customer Form` -> OK
2- Then back to customer list page (don't close above page), and click `edit` link to open `Customer Form` for Update
So it show all cached on `1-`.
And have problem if we click other `edit` link record (don't get data update on form).

**Comment by thearabbit** [comment]
Example img

![image](https://user-images.githubusercontent.com/4495160/48182532-17c4bb00-e35e-11e8-8a54-70f5e0e690c9.png)

![image](https://user-images.githubusercontent.com/4495160/48182540-1eebc900-e35e-11e8-89e7-a829845d8ed2.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/9f1552d98fb85e1e999066c43beb6d970e6b422d/src/views/layout/components/AppMain.vue#L5

Do you add this key?

**Comment by thearabbit** [comment]
I don't use this, could explain???

**Comment by PanJiaChen** [comment]
https://router.vuejs.org/guide/advanced/data-fetching.html

**Comment by thearabbit** [comment]
Now it work fine 💯  🥇
