### ISSUE TITLE
文档里treetable自定义列的文件404

### ISSUE THREAD

**Issue by phpox** [PanJiaChen/vue-element-admin#1315]
treetable文档里 [customTreeTable](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/example/table/treeTable/customTreeTable.vue) 这个文件404了 ,能否提供一下?

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/9df740bcf1a55c7cfc90a1744c39fe4a1d231a14
