### ISSUE TITLE
如何实现侧边栏保持在table页面的状态，但是路由跳转到详情页面？

### ISSUE THREAD

**Issue by liuhuawen** [PanJiaChen/vue-element-admin#1317]
![image](https://user-images.githubusercontent.com/19276993/48251442-9a23ac80-e43c-11e8-9dc6-9594f6bfc048.png)
![image](https://user-images.githubusercontent.com/19276993/48251458-aa3b8c00-e43c-11e8-8f07-975463a5b3df.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/c13b5747940feb74dcf7888b6c4aeada24e5f1cc/src/views/layout/components/Sidebar/index.vue#L5

自行侧边栏高亮逻辑，目前是按照路径匹配。你可以自定义规则。

**Comment by liuhuawen** [comment]
:default-active="$route.path"  这里根据当前路由高亮，但是为什么详情页面会高亮table页面了啊。这里有点搞不懂。

**Comment by PanJiaChen** [comment]
这个是 element-ui bug，已经pr过了，一直没merge。

**Comment by liuhuawen** [comment]
那应该已经merge了，但是现在我就想要它有bug的状态啊。这样既能高亮，又能隐藏那个详情页侧边高亮。现在的状态是没法两个统一。要不就只能高亮，要不不显示table的状态。
