### ISSUE TITLE
布局调整后transition无效

### ISSUE THREAD

**Issue by Liupeng8** [PanJiaChen/vue-element-admin#1319]
用element-ui的布局调整后，transition设置无效，麻烦大神们帮忙看看。。

![1222](https://user-images.githubusercontent.com/23046680/48311832-9892e980-e5e0-11e8-92e5-333d49bb3bd9.png)
![22222](https://user-images.githubusercontent.com/23046680/48311833-9df03400-e5e0-11e8-84e8-cf77edc7be58.png)
![333](https://user-images.githubusercontent.com/23046680/48311836-a34d7e80-e5e0-11e8-91dd-e08826245200.png)

再次感谢！

**Comment by PanJiaChen** [comment]
现在宽度可以自定义。
