### ISSUE TITLE
三级菜单菜单无法渲染

### ISSUE THREAD

**Issue by yuttian** [PanJiaChen/vue-element-admin#1322]

**Comment by laonier** [comment]
hasOnlyOneShowingChild (route) {
      // 判断多级子菜单
      let aloneChild = {}
      let showingChildren = route.children.filter(item => {
        if (!item.hidden) {
          aloneChild = item
        }
        return !item.hidden
      })
      if (showingChildren.length === 1) {
        return this.hasOnlyOneShowingChild(aloneChild)
      } else {
        return false
      }
    }
可以这么试着写一下下
