### ISSUE TITLE
当我登录后调用了router.addRoutes(), 有接口可以直接刷新sidebar吗?

### ISSUE THREAD

**Issue by jingea** [PanJiaChen/vue-element-admin#1323]
当我登录后调用了router.addRoutes(), 有接口可以直接刷新sidebar吗?

**Comment by LonHon** [comment]
应该是在做权限？
sidebar的数据是从vuex里取的，所以add之后更新permission_routers的数据就可以了
见 [sidebar.vue](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/layout/components/Sidebar/index.vue#L23-L27)

**Comment by feelslive** [comment]
这个应该是权限控制，大神在集成版已经实现了，可以看看sidebar源码。基础版大神没有更新代码，所以不会更新sideber

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1067

已经是自动刷新的了，只用你改变vuex里面依赖的值就好了。
