### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by Aopodo** [PanJiaChen/vue-element-admin#1325]
![image](https://user-images.githubusercontent.com/16433585/48410852-d3c92000-e77a-11e8-837a-ccce974f42d3.png)

why?

**Comment by Aopodo** [comment]
重新install所有依赖，并忽略升级插件就可以了.

**Comment by birender** [comment]
Hi All,

After Performing Below Action following error comes:
git clone https://github.com/PanJiaChen/vue-admin-template.git

# enter the project directory
cd vue-admin-template

# install dependency
npm install

Error on : npm run dev
> vue-element-admin@4.2.1 dev /var/www/html/vue-admin-template
> vue-cli-service serve

/usr/bin/env: ‘node’: No such file or directory

npm ERR! Linux 4.15.0-55-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! vue-element-admin@4.2.1 dev: `vue-cli-service serve`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the vue-element-admin@4.2.1 dev script 'vue-cli-service serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-element-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     vue-cli-service serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-element-admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-element-admin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/vue-admin-template/npm-debug.log

![Selection_019](https://user-images.githubusercontent.com/1873263/62920495-89390a80-bdc3-11e9-9313-cacfd74e2fcb.png)
