### ISSUE TITLE
封装axios时使用vuex出现undefined

### ISSUE THREAD

**Issue by WilliamLin1990** [PanJiaChen/vue-element-admin#1326]
想在登录页面修改api地址，从而达到动态登录不同环境的效果。然而，在request.js中console.log(store)出现undefined。
```js
import axios from 'axios'
import { Message } from 'element-ui'
import store from '@/store'
import { getToken } from '@/utils/auth'
import router from '../router'
console.log(store)
// create an axios instance
const service = axios.create({
  baseURL: store.getters.api,
  timeout: 5000 // request timeout
})
```
但是，从[https://github.com/Mrblackant/vue-admin-element-](https://github.com/Mrblackant/vue-admin-element-)可以看到，这个console.log(store)是有内容的。没搞懂是怎么做到的。

**Comment by WilliamLin1990** [comment]
> 没懂你想表达什么。。

你的代码现在console.log(store)是undefined，但是那个人的版本是可以输出的，想问下原因。

**Comment by PanJiaChen** [comment]
因为 request.js 会在 store 之前初始化，所以你执行的时候 store还没有，会是 undefined

**Comment by WilliamLin1990** [comment]
但是那人的项目copy你的，却能打印出来，看了代码， 没看出来差别。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/a51d72f42e27773a1f55beade504b79b3b8a5b46/src/store/modules/user.js#L1

主要是这里导致的。

**Comment by WilliamLin1990** [comment]
> [vue-element-admin/src/store/modules/user.js](https://github.com/PanJiaChen/vue-element-admin/blob/a51d72f42e27773a1f55beade504b79b3b8a5b46/src/store/modules/user.js#L1)
> 
> Line 1 in [a51d72f](/PanJiaChen/vue-element-admin/commit/a51d72f42e27773a1f55beade504b79b3b8a5b46)
> 
>  import { loginByUsername, logout, getUserInfo } from '@/api/login' 
> 主要是这里导致的。

没看出来差别。。。

**Comment by DGM-UL** [comment]
在拦截器里面打印就有了
