### ISSUE TITLE
文档网页中的“Webpack 指南 - webpack 4 和单页应用入门”链接404问题

### ISSUE THREAD

**Issue by jackgreentemp** [PanJiaChen/vue-element-admin#1330]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/webpack.html#webpack-%E6%8C%87%E5%8D%97

Webpack 指南 - webpack 4 和单页应用入门，网页上这个链接地址不能访问了

后来在掘金里找到了链接：https://github.com/wallstreetcn/webpack-and-spa-guide

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin-site/commit/6d8e7ab5c4f05500c8ac6e31e4936f59f25dd561
