### ISSUE TITLE
动态路由的component是undefined,常量路由正常

### ISSUE THREAD

**Issue by cen2** [PanJiaChen/vue-element-admin#1331]
![t 2iift 3u8i_ nzate 5](https://user-images.githubusercontent.com/41353615/48548189-5a126d00-e907-11e8-891e-a07897e1d72d.png)
![8n6 fw _ nyqi5h vu l](https://user-images.githubusercontent.com/41353615/48548195-5f6fb780-e907-11e8-8e87-84c4c578f960.png)

**Comment by PanJiaChen** [comment]
我怎么知道你自己文件层级是怎么样的，自己debug一下不就知道为什么了么。
