### ISSUE TITLE
The document about excel-export is wrong.[Bug Report]

### ISSUE THREAD

**Issue by a631807682** [PanJiaChen/vue-element-admin#1332]
[vue-element-admin-site/feature/component/excel.html#excel-export](https://panjiachen.github.io/vue-element-admin-site/feature/component/excel.html#excel-export)

> npm install js-xlsx file-saver -S

The package's name in npm is `xlsx` not `js-xlsx` .

[SheetJS/js-xlsx)](https://github.com/SheetJS/js-xlsx)

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin-site/commit/1fcafe9c6bda6be0f2e8e3a2ae5d53bceb7f2281
