### ISSUE TITLE
size存在默认选项

### ISSUE THREAD

**Issue by linlinjava** [PanJiaChen/vue-element-admin#1334]
现在项目只支持medium, small, mini三种选项，但是实际上vue-element本身是四种，即存在默认选项，如图所示：

![image](https://user-images.githubusercontent.com/4223779/48658359-67e8ff00-ea7b-11e8-85dd-27f403403d4f.png)

而且我们可以看到其实默认选项的尺寸实际上是最大的，因此建议完善默认值选项。

**Comment by PanJiaChen** [comment]
Added in https://github.com/PanJiaChen/vue-element-admin/pull/1566
