### ISSUE TITLE
如何让:id/view的路由，也匹配到sidebarItem的焦点路由上

### ISSUE THREAD

**Issue by lixing0323** [PanJiaChen/vue-element-admin#1339]
比如说，sidebar菜单有2个子菜单，分别叫a和b，点a和b显示各自的列表和详情，分别对应是/a/list和/a/:id/view的路由。当我从a列表进入详情时候，左侧的菜单焦点还是会在a上。如果我是从/b/list用this.$router.push({ path: '/a/1/view' })的方式，界面是进入到a的详情里了，但是左侧的菜单焦点还是会在b上，根据路由，不是应该显示在a上吗？不知道我是否描述清楚了。。。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1317

**Comment by lixing0323** [comment]
@PanJiaChen 请问这是修改哪处的bug，我好同步。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1833
