### ISSUE TITLE
建议：左侧菜单文字显示使用路由的meta定义，不要用路由的name字段

### ISSUE THREAD

**Issue by Ignorantforce** [PanJiaChen/vue-element-admin#134]
左侧菜单文字显示使用路由的meta定义，不要用路由的name字段，因为使用命名路由的时候会用到name。

**Comment by PanJiaChen** [comment]
你提的建议很不错,但我觉得还是结合业务来看，我个人是不太喜欢用命名路由的，你可以按照自己的需求来改:no_mouth:

**Comment by Ignorantforce** [comment]
@PanJiaChen 我的意思是这个项目作为开源来说，最好更“标准化”一些，避免占用了一些原来就有意义的字段（比如这里是name会"影响”命名路由）。

**Comment by PanJiaChen** [comment]
其实name是中文或者用来做菜单名字没什么太大问题啊，都是一个string

**Comment by Ignorantforce** [comment]
确实是，但这个就好像和电脑里的中文路径一个意思，哈哈

**Comment by PanJiaChen** [comment]
这个提议先暂定吧

**Comment by lilongthinker** [comment]
其实两种意见并不冲突，可以考虑个优先级的问题，优先使用某个meta属性，如果没有就用现在的作为默认动作就好了，不知道是不是get到了两位的点

**Comment by PanJiaChen** [comment]
新版本已都是用meta属性来标示
