### ISSUE TITLE
在谷歌浏览器运行的时候屏幕变形，所有元素都变小了

### ISSUE THREAD

**Issue by RoyBiao** [PanJiaChen/vue-element-admin#1340]
在谷歌浏览器运行的时候屏幕变形，所有元素都变小了
![_20181119171254](https://user-images.githubusercontent.com/13087893/48697031-8804f380-ec1e-11e8-8ca7-aa176f4664fe.png)

**Comment by PanJiaChen** [comment]
你自己缩放页面了吧。

**Comment by RoyBiao** [comment]
> 你自己缩放页面了吧。

果然如此
