### ISSUE TITLE
集成阿里云视频点播组件时会导致阿里云点播sdk出现异常

### ISSUE THREAD

**Issue by flzyup** [PanJiaChen/vue-element-admin#1342]
RT，官方demo使用vue+element-ui加入阿里云点播sdk上传视频没问题 但是一嵌入到admin这个项目下就会出错，官方demo可以下载：https://sunhongjie-hz.oss-cn-hangzhou.aliyuncs.com/vue-upload.zip  这个测试工程，把里面的App.vue作为一个component集成到项目中，会出现阿里云点播sdk读取某些数据出错，同样的代码在demo下运行正常

Request URL: https://videocloud.cn-hangzhou.log.aliyuncs.com/logstores/upload/track?APIVersion=0.6.0&lv=1&av=1.4.0&pd=upload&sm=upload&md=uploader&uuid=5168260F-F0AE-4591-ABF0-6CD442383FFB&os=macOS&ov=10.14.1&et=Chrome&ev=72.0.3610.2&uat=Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_14_1)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/72.0.3610.2%20Safari/537.36&app_n=localhost&tt=pc&dm=h5&ut=vod&t=1542364626454&ll=error&ri=6E9971D1-3EB1-440F-89E1-AF615F072227&e=20006&args=code%3DTypeError%26message%3DCannot%20read%20property%20%27Bucket%27%20of%20null%26requestId%3Dundefined%26fs%3D8203000%26bu%3Doutin-79b9159fe10c11e8a50700163e1c7426%26ok%3DcustomerTrans%2Fa0bdec58f10f1573bc206d525a70c3ea%2F204c1873-1671c187be6-0005-9766-6c9-00718.mp4%26fn%3DVID_20181106_225021.mp4
Request Method: GET
Status Code: 200 
Remote Address: 112.124.141.187:443
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Origin: *
Connection: close
Content-Length: 0
Date: Fri, 16 Nov 2018 10:37:06 GMT
Server: nginx
x-log-requestid: 5BEE9DD242863B372774DA61
Provisional headers are shown
Referer: http://localhost:9527/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3610.2 Safari/537.36
APIVersion: 0.6.0
lv: 1
av: 1.4.0
pd: upload
sm: upload
md: uploader
uuid: 5168260F-F0AE-4591-ABF0-6CD442383FFB
os: macOS
ov: 10.14.1
et: Chrome
ev: 72.0.3610.2
uat: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3610.2 Safari/537.36
app_n: localhost
tt: pc
dm: h5
ut: vod
t: 1542364626454
ll: error
ri: 6E9971D1-3EB1-440F-89E1-AF615F072227
e: 20006
args: **code=TypeError&message=Cannot read property 'Bucket' of null&requestId=undefined**&fs=8203000&bu=outin-79b9159fe10c11e8a50700163e1c7426&ok=customerTrans/a0bdec58f10f1573bc206d525a70c3ea/204c1873-1671c187be6-0005-9766-6c9-00718.mp4&fn=VID_20181106_225021.mp4

**Comment by PanJiaChen** [comment]
和本项目有什么关系？

**Comment by flzyup** [comment]
@PanJiaChen 目前的现象猜测是不是项目的某些打包配置影响了第三方sdk的js，因为用element-ui + vue使用这个sdk是没问题的 但是同样的方法这个sdk嵌入到admin任何界面就会出问题

**Comment by PanJiaChen** [comment]
大概率是`mockjs`，你移除试试

**Comment by flzyup** [comment]
好 我试试看

**Comment by flzyup** [comment]
还真是mockjs的问题 移除后就好了！谢谢 @PanJiaChen
