### ISSUE TITLE
想问一下如何在页面上显示{{}}呢？双大括号默认是vue渲染模板变量的语法，如何覆盖呢，我用大括号的转义&#125;也不行

### ISSUE THREAD

**Issue by gangyahaidao** [PanJiaChen/vue-element-admin#1344]
如：`<h3>通用称呼{{GeneralCall}}</h3>`，我是想将大括号一起显示在页面上，但是总是会被翻译成模板变量，请问有什么解决办法吗？我用这种方式也不行：
`<h3>通用称呼&#123;&#123;GeneralCall&#125;&#125;</h3>`

**Comment by Kanhin** [comment]
你可以在data里定义GeneralCall的时候就带上 {{GeneralCall}}，
` data: {
            GeneralCall: '{{ GeneralCall }}'
        }
`
或者用标签把括号包起来 
`<p>
   <span>{{</span>
   {{ GeneralCall }} 
   <span>}}</span>
</p>
`

**Comment by gangyahaidao** [comment]
试了一下可以，感谢你的帮助！！

**Comment by zikuai** [comment]
如果要想显示{{}}标签，而不是进行替换，使用v-pre就可以跳过这个元素和它的子元素的编译过程
```
<span v-pre><h3>通用称呼{{GeneralCall}}</h3></span>
```
