### ISSUE TITLE
浏览器返回，页面不执行created钩子

### ISSUE THREAD

**Issue by numens** [PanJiaChen/vue-element-admin#1345]
a跳去b页面，然后b返回至a，a页面不执行created钩子，a页面的数据无法刷新

**Comment by zikuai** [comment]
是使用动态路由吗？例如从 /page/foo 导航到 /page/bar，**原来的组件实例会被复用，组件的生命周期钩子不会再被调用**

**Comment by numens** [comment]
> 是使用动态路由吗？例如从 /page/foo 导航到 /page/bar，**原来的组件实例会被复用，组件的生命周期钩子不会再被调用**

从 /page/list 跳转到 /page/detail/1，然后返回至/page/list ，/page/list 的created不执行

**Comment by zikuai** [comment]
> > 是使用动态路由吗？例如从 /page/foo 导航到 /page/bar，**原来的组件实例会被复用，组件的生命周期钩子不会再被调用**
> 
> 从 /page/list 跳转到 /page/detail/1，然后返回至/page/list ，/page/list 的created不执行

可以尝试能否观察到路由的变化，还有路由是否使用了`keepAlive`
```
watch: {
   '$route' (to, from) {
       // 执行代码
   }
}
```

**Comment by numens** [comment]
> > > 是使用动态路由吗？例如从 /page/foo 导航到 /page/bar，**原来的组件实例会被复用，组件的生命周期钩子不会再被调用**
> > 
> > 
> > 从 /page/list 跳转到 /page/detail/1，然后返回至/page/list ，/page/list 的created不执行
> 
> 可以尝试能否观察到路由的变化，还有路由是否使用了`keepAlive`
> 
> ```
> watch: {
>    '$route' (to, from) {
>        // 执行代码
>    }
> }
> ```

好的，已解决，谢谢
