### ISSUE TITLE
关于 Pagination 分页异步的问题，已解决。

### ISSUE THREAD

**Issue by Thomastar** [PanJiaChen/vue-element-admin#1347]
[https://github.com/PanJiaChen/vue-element-admin/blob/master/src/components/Pagination/index.vue#L74](url)

关键代码：
this.$emit('update:page', this.currentPage)
this.$emit('update:limit', val)

this.$emit('update:page', val)
this.$emit('update:limit', this.pageSize)

![image](https://user-images.githubusercontent.com/17611854/48821632-0c798280-ed95-11e8-9560-8ca3f425fe96.png)

**Comment by BerryWang1996** [comment]
的确有这个问题，比如默认每页显示10条，点击选择默认每页20条的时候，还是10条。再次点击每页30条，显示的是每页20条，晚了一步

**Comment by BerryWang1996** [comment]
添加楼主的代码后问题解决

**Comment by PanJiaChen** [comment]
现在线上版本应该是没问题了，都修复了。
