### ISSUE TITLE
二级路由权限问题

### ISSUE THREAD

**Issue by weilai-long** [PanJiaChen/vue-element-admin#1351]
在使用基础模版的得时候，登陆之后跳转到我自己的一个路由页面，然后在这个页面中有通过this.$router来做跳转，但是会提示管理员不允许进去，我是用默认的admin登陆，请问有什么地方修改吗？

**Comment by PanJiaChen** [comment]
没懂你的问题，你再具体描述一下么。

**Comment by weilai-long** [comment]
已经解决了，是我自己路由有点问题，感谢大神回复
