### ISSUE TITLE
跨域问题跪求

### ISSUE THREAD

**Issue by xiaohuido** [PanJiaChen/vue-element-admin#1353]
将模板上的地址改成我的easy-mock地址后  有的时候能够登录成功有的时候却不行,报下面的错:

已拦截跨源请求：同源策略禁止读取位于 https://www.easy-mock.com/mock/5be295301f58bc63631bcd3b/sd/login/login 的远程资源。（原因：CORS 请求未能成功）

**Comment by PanJiaChen** [comment]
easy-mock 支持跨域的。
