### ISSUE TITLE
请教两个问题：①response错误捕获；②路由跳转了页面却是其它页面的问题

### ISSUE THREAD

**Issue by luoxulx** [PanJiaChen/vue-element-admin#1356]
后台接口是restful风格的api，我的请求接口只能这样写吗？有没有其它写法？
求指导
```javascript
export function updateTag(data) {
  return request({
    url: '/tag/' + data.id,
    method: 'put',
    data
  })
}

export function deleteTag(id) {
  return request({
    url: '/tag/' + id,
    method: 'delete'
  })
}
```

**Comment by Moln** [comment]
我的是用 axios 组件

```javascript
function updateTag(data) {
  const url = '/tags/' + data.id;
  return apiRequest.put(url, data);
}

const newData = await updateTag({id: 123, name: 'abc'})
```

**Comment by luoxulx** [comment]
OK，涨姿势了，3Q！

**Comment by luoxulx** [comment]
有个关于捕获response错误消息的问题：无论后台我怎么写exception，request.js里就是捕获不到错误message，只能如下图：所有非2xx的http码都是 ‘request failed with 什么什么的’，
![image](https://user-images.githubusercontent.com/35016570/48943181-62008b80-ef5d-11e8-9197-3162c19d6ce2.png)
但我想的是弹如下图api返回的message
![image](https://user-images.githubusercontent.com/35016570/48943391-0aaeeb00-ef5e-11e8-8994-831f2bd1b109.png)

以下是request.js的部分代码：
```

// request interceptor
service.interceptors.request.use(
  config => {
    // Do something before request is sent
    if (store.getters.token) {
      // 让每个请求携带token-- ['X-Token']为自定义key 请根据实际情况自行修改
      config.headers['Authorization'] = getToken()
    }
    return config
  },
  error => {
    // Do something with request error
    // console.log(error) // for debug
    Promise.reject(error)
  }
)

// response interceptor
service.interceptors.response.use(
  response => response,
  error => {
    // console.log('err' + error) // for debug
    Message({
      message: error.message,
      type: 'error',
      duration: 5 * 1000
    })
    return Promise.reject(error)
  }
)
```

忘指点🤕

**Comment by luoxulx** [comment]
说明：后台api返回没有设计 code啊，status_code啊什么的来标明 这是一个错误的请求，都是以HTTP码。

**Comment by luoxulx** [comment]
还有一个疑问，望解答一下，[http://cdn2.lnmpa.top/issues/slaughter.MP4](url)
说明：点击了按钮路由页进行了相应的跳转，下方链接也显示正确，但是跳转后显示的页面却总是index列表页
以下是相关路由代码：
```

import Layout from '@/views/layout/Layout'

const blogRouter = {
  path: '/blog',
  component: Layout,
  redirect: 'article',
  name: 'Blog',
  meta: {
    title: 'blog',
    icon: 'component'
  },
  children: [
    {
      path: 'article',
      component: () => import('@/views/blog/article/index'),
      name: 'article',
      meta: { title: 'article' },
      children: [
        {
          path: 'create',
          hidden: true,
          component: () => import('@/views/blog/article/create'),
          name: 'CreateArticle',
          meta: { title: 'createArticle', icon: 'edit' }
        },
        {
          path: 'edit/:id(\\d+)',
          hidden: true,
          component: () => import('@/views/blog/article/edit'),
          name: 'EditArticle',
          meta: { title: 'editArticle', noCache: true, icon: 'edit' }
        }
      ]
    },
    {
      path: 'category',
      component: () => import('@/views/blog/category/index'),
      name: 'category',
      meta: { title: 'category' }
    },
    {
      path: 'tag',
      component: () => import('@/views/blog/tag/index'),
      name: 'tag',
      meta: { title: 'tag' }
    }
  ]
}

export default blogRouter

```
views 目录结构如下：
![http://cdn2.lnmpa.top/issues/a_d113b331-0939-4f62-8985-7f5805de5644.png](image)

**Comment by Moln** [comment]
### 问题1

参考 `request.js` 注释的代码,

https://github.com/PanJiaChen/vue-element-admin/blob/ea60729c0a2f69a482b89d9c118789d227119f5a/src/utils/request.js#L38-L64

```javascript
service.interceptors.response.use(
  response => response,
  error => {
   //这个 `error` 是个 js 的异常对象, `message` 是异常消息, 不是你的响应消息内容
  // 要获取响应用:
  // const res = error.response;
  // res.status //状态码
  // res.data  //响应内容json格式
  // res.data.message 这应该是你需要的 message
 }
)
```

**Comment by luoxulx** [comment]
> ### 问题1
> 参考 `request.js` 注释的代码,
> 
> [vue-element-admin/src/utils/request.js](https://github.com/PanJiaChen/vue-element-admin/blob/ea60729c0a2f69a482b89d9c118789d227119f5a/src/utils/request.js#L38-L64)
> 
> Lines 38 to 64 in [ea60729](/PanJiaChen/vue-element-admin/commit/ea60729c0a2f69a482b89d9c118789d227119f5a)
> 
>  // response => { 
>  //   const res = response.data 
>  //   if (res.code !== 20000) { 
>  //     Message({ 
>  //       message: res.message, 
>  //       type: 'error', 
>  //       duration: 5 * 1000 
>  //     }) 
>  //     // 50008:非法的token; 50012:其他客户端登录了;  50014:Token 过期了; 
>  //     if (res.code === 50008 || res.code === 50012 || res.code === 50014) { 
>  //       // 请自行在引入 MessageBox 
>  //       // import { Message, MessageBox } from 'element-ui' 
>  //       MessageBox.confirm('你已被登出，可以取消继续留在该页面，或者重新登录', '确定登出', { 
>  //         confirmButtonText: '重新登录', 
>  //         cancelButtonText: '取消', 
>  //         type: 'warning' 
>  //       }).then(() => { 
>  //         store.dispatch('FedLogOut').then(() => { 
>  //           location.reload() // 为了重新实例化vue-router对象 避免bug 
>  //         }) 
>  //       }) 
>  //     } 
>  //     return Promise.reject('error') 
>  //   } else { 
>  //     return response.data 
>  //   } 
>  // }, 
> ```js
> service.interceptors.response.use(
>   response => response,
>   error => {
>    //这个 `error` 是个 js 的异常对象, `message` 是异常消息, 不是你的响应消息内容
>   // 要获取响应用:
>   // const res = error.response;
>   // res.status //状态码
>   // res.data  //响应内容json格式
>   // res.data.message 这应该是你需要的 message
>  }
> )
> ```

👌，那问题二能指点下哪里写错了吗？

**Comment by Moln** [comment]
问题二: 一切看似正常, 我也不知原因, 需要一步一步调试.
比如  `beforeRoute` 那断点调试. 确认 `to` 参数, 是否正常.

**Comment by luoxulx** [comment]
> 问题二: 一切看似正常, 我也不知原因, 需要一步一步调试.
> 比如 `beforeRoute` 那断点调试. 确认 `to` 参数, 是否正常.

已解决，但我不知原因，link组件里断点是有.log的，blog.js路由改成了如下这样：
```javaScript
import Layout from '@/views/layout/Layout'

const blogRouter = {
  path: '/blog',
  component: Layout,
  redirect: 'article',
  name: 'Blog',
  meta: {
    title: 'blog',
    icon: 'component'
  },
  children: [
    {
      path: 'article',
      component: () => import('@/views/blog/article/index'),
      name: 'article',
      meta: { title: 'article' }
    },
    {
      path: 'category',
      component: () => import('@/views/blog/category/index'),
      name: 'category',
      meta: { title: 'category' }
    },
    {
      path: 'tag',
      component: () => import('@/views/blog/tag/index'),
      name: 'tag',
      meta: { title: 'tag' }
    },
    {
      path: 'article/create',
      hidden: true,
      component: () => import('@/views/blog/article/create'),
      name: 'CreateArticle',
      meta: { title: 'createArticle', icon: 'edit' }
    },
    {
      path: 'article/edit/:id(\\d+)',
      hidden: true,
      component: () => import('@/views/blog/article/edit'),
      name: 'EditArticle',
      meta: { title: 'editArticle', noCache: true, icon: 'edit' }
    }
  ]
}

export default blogRouter

```
