### ISSUE TITLE
麻烦问一下，怎么解决页面刷新store数据丢失的问题

### ISSUE THREAD

**Issue by JeffGannon** [PanJiaChen/vue-element-admin#1357]
麻烦问一下，怎么解决页面刷新store数据丢失的问题，有没有可行的方案解决，能否提供一下思路

**Comment by PanJiaChen** [comment]
这是正常现象。

你想刷新页面保存数据的话就需要用到 或者`localStorage` `indexedDB`等其它浏览器的存储了
