### ISSUE TITLE
问一下这个项目做到企业级的话有必要整合springsecurity或者shiro这种后端安全框架吗

### ISSUE THREAD

**Issue by mhtssb6666** [PanJiaChen/vue-element-admin#1359]

**Comment by lionel-lx** [comment]
那当然了。你需要在后端维护权限。前端只是一个获取数据动态展示的过程

**Comment by mhtssb6666** [comment]
>           那当然了。你需要在后端维护权限。前端只是一个获取数据动态展示的过程

那这个前端的权限方案和springsecurity不是冲突了么，可以整合吗

**Comment by PanJiaChen** [comment]
没啥必然联系吧，前端权限和后端验权又不冲突。
