### ISSUE TITLE
使用中文路由时，可以点击侧连栏进入，但是刷新浏览器就无法访问了！

### ISSUE THREAD

**Issue by f3dfax** [PanJiaChen/vue-element-admin#1362]
children: [
    {
      path: '/文档',
      component: Layout,
      redirect: '/文档/主页',
      children: [
        {
          path: '主页',
          component: () => import('@/views/documentation/index'),
          name: 'Documentation',
          meta: { title: '文档', icon: 'documentation', noCache: true }
        }
      ]
    },

http://localhost:9527/#/文档/主页
这个链接，由菜单跳转可以访问，真接输入网址，或在浏览器上点击刷新，就是404错误了。

**Comment by PanJiaChen** [comment]
https://github.com/vuejs/vue-router/pull/2375

更新 `vue-router`到 3.0.2就好了。
