### ISSUE TITLE
水平滚动条在有dialog显示时鼠标移动上去的时候，滚动条会跑到最顶上覆盖dialog

### ISSUE THREAD

**Issue by flzyup** [PanJiaChen/vue-element-admin#1363]
看图
正常情况
![image](https://user-images.githubusercontent.com/158452/48970508-f9daa400-f047-11e8-901c-764fd797b852.png)

打开对话框后
![image](https://user-images.githubusercontent.com/158452/48970523-0fe86480-f048-11e8-87f4-db0a1098d942.png)

**Comment by PanJiaChen** [comment]
没能重现，确定不是自己改了css的原因么

**Comment by flzyup** [comment]
我没改过模版里面的css 也基本没增加自定义的css 都是调用el的控件

**Comment by PanJiaChen** [comment]
你打开控制台 看一下 css不就知道为什么了么
