### ISSUE TITLE
tabs切换

### ISSUE THREAD

**Issue by menciusKael** [PanJiaChen/vue-element-admin#1367]
![image](https://user-images.githubusercontent.com/29659731/49020047-7ac1a900-f1ca-11e8-8855-6dd036579251.png)
![image](https://user-images.githubusercontent.com/29659731/49020157-bbb9bd80-f1ca-11e8-9007-b64e048a98ac.png)

很多Tab，每个tab对应很多不同的table或者form，怎么控制显示？每个tab下的内容封装成组件吗？

**Comment by PanJiaChen** [comment]
可以封装成组件，之后使用动态组件 ` <component v-bind:is="currentTabComponent"></component>`
