### ISSUE TITLE
在permission.js中获取roles的问题

### ISSUE THREAD

**Issue by seayao** [PanJiaChen/vue-element-admin#1368]
![qq 20181127113222](https://user-images.githubusercontent.com/29435027/49057059-007c3d80-f239-11e8-8dac-e14f5e588286.png)
![qq 20181127113352](https://user-images.githubusercontent.com/29435027/49057066-0540f180-f239-11e8-87cb-9f1e53b4bc19.png)
在permission.js中
从图一标注的1处打印getters结果对应为图二的1处，
可以看出获取到了getters的对象，
但从图一标注的2处打印roles结果对应为图二的2处，
却无法获取到它的下一级即roles数组，
进而会永远走图1中3的if语句，即永远重新拉取用户信息，
这是不太合理的。
不知道是否听懂了我的描述，
还望不吝赐教，
感谢。

**Comment by PanJiaChen** [comment]
这是console的问题。

https://panjiachen.github.io/awesome-bookmarks/blog/js.html#console-log-%E7%9A%84%E5%9D%91
