### ISSUE TITLE
项目现在要上传很多个excel表的话怎么实现

### ISSUE THREAD

**Issue by WenDaaa** [PanJiaChen/vue-element-admin#1369]
项目要使用uploadexcel的组件模块 然后我要遍历出来很多个上传的表的话 是怎么样的  用一个大的form包起来么然后submit上传这样吗我将下面的解析展示excel部分给删除了

**Comment by PanJiaChen** [comment]
没懂你想表达什么

**Comment by WenDaaa** [comment]
尴尬，可能是因为是新手，表达的有点不明确，不好意思啊啊，就是我们要做一个财务类的软件要在一个界面上，上传很多个excel报表，然后不需要下面展示excel的内容，我就把下面的代码删除了，留了上面那个上传文件的框框，遍历了一下 就是一个名称对应一个框框这样，然后是不是想上传的话 就是给他们加一个大的form然后文件提交上去 点一下submit这样

**Comment by WenDaaa** [comment]
> 没懂你想表达什么
尴尬，可能是因为是新手，表达的有点不明确，不好意思啊啊，就是我们要做一个财务类的软件要在一个界面上，上传很多个excel报表，然后不需要下面展示excel的内容，我就把下面的代码删除了，留了上面那个上传文件的框框，遍历了一下 就是一个名称对应一个框框这样，然后是不是想上传的话 就是给他们加一个大的form然后文件提交上去 点一下submit这样

**Comment by WenDaaa** [comment]
好的 谢谢啦 我再看看代码
