### ISSUE TITLE
登录时后台返回400状态码问题

### ISSUE THREAD

**Issue by ginhom** [PanJiaChen/vue-element-admin#137]
见图：
![image](https://user-images.githubusercontent.com/3000284/28456503-21de7b8e-6e35-11e7-9971-73521c929ff6.png)

**Comment by PanJiaChen** [comment]
所以什么意思呢？

**Comment by ginhom** [comment]
不好意思，表达不是很明白。是这样的，登录的时候，如果服务器不是返回200状态码，会出现上面这情况。界面上有提示，但因为JS出错，提示后需要刷新页面才能继续处理。
这里的情况是，如果前台输入账号或密码错误，后台返回400状态码，并以json形式返回错误信息。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/utils/fetch.js#L26
自己按照自己的需求改一下axios拦截器就好了，

**Comment by ginhom** [comment]
我查出问题了，需要把view/login/index.vue里handleLogin方法的“this.$message.error(err);”注释就可以了。这个错误提示与fetch全局错误处理重复了。我不太明白重复提示这个err为什么会出现这些奇怪的错误？

**Comment by ginhom** [comment]
又尝试了下，应该是err是对象，所以出错了。修改为这个可以：this.$message.error(err.message);

**Comment by PanJiaChen** [comment]
的确重复了，我之后改善一下
