### ISSUE TITLE
vue  路由懒加载之后 恶

### ISSUE THREAD

**Issue by git1234567outlookcom** [PanJiaChen/vue-element-admin#1370]
原 ：import NotFound from "./views/404.vue";

现在：const NotFound = () => import("./views/404.vue")

原来的代码改为现在的 之后 ，出现页面黑屏

请教下大佬

**Comment by PanJiaChen** [comment]
什么叫黑屏

**Comment by git1234567outlookcom** [comment]
页面有dom 就是不显示，app页面中设置的背景色是黑色的

**Comment by git1234567outlookcom** [comment]
> 什么叫黑屏
页面有dom 就是不显示，app页面中设置的背景色是黑色的

**Comment by git1234567outlookcom** [comment]
![image](https://user-images.githubusercontent.com/31754926/49192433-02b7d680-f3b6-11e8-974a-bfee16336b41.png)

**Comment by PanJiaChen** [comment]
只靠截图猜不出为什么。
若觉得有问题，请提供一个最小可还原demo。
