### ISSUE TITLE
IE11下兼容问题

### ISSUE THREAD

**Issue by lanfengZhou** [PanJiaChen/vue-element-admin#1372]
IE11 下提示缺少“；”，检查是看到是打包后的文件中有for   of循环，看资料是有transform-es2015-for-of插件，但装了之后还是没有解决，求解答
![image](https://user-images.githubusercontent.com/23160055/49085486-19164300-f28d-11e8-8136-5f849444cf72.png)

![image](https://user-images.githubusercontent.com/23160055/49084991-ef105100-f28b-11e8-897c-7d7937124410.png)

**Comment by PanJiaChen** [comment]
请看readme。

**Comment by PanJiaChen** [comment]
定位一下是什么库咯

**Comment by lanfengZhou** [comment]
get到，elementUI的问题，多谢

**Comment by lanfengZhou** [comment]
> 定位一下是什么库咯
get到，elementUI的问题，多谢

**Comment by Hack-DJ** [comment]
> > 定位一下是什么库咯
> > get到，elementUI的问题，多谢

应该是你引用的第三方库有没转ES5的语法导致,webpack默认值转你自己的代码,你看下webpack有个配置,可以要求把你引用的第三方库也转ES5

**Comment by PanJiaChen** [comment]
那还是element的问题，因为element-ui提供的应该就是打包完的代码。

**Comment by lanfengZhou** [comment]
> > > 定位一下是什么库咯
> > > get到，elementUI的问题，多谢
> 
> 应该是你引用的第三方库有没转ES5的语法导致,webpack默认值转你自己的代码,你看下webpack有个配置,可以要求把你引用的第三方库也转ES5

用babel将elementui强制转换一下就可以了
