### ISSUE TITLE
请问为什么动态路由会影响热更新速度呢，文章写的是说'可能导致了缓存失效'，我想得到一个让人信服的答案。或者切实的证据。

### ISSUE THREAD

**Issue by chentianyuan** [PanJiaChen/vue-element-admin#1376]
如题。或者一个找到证据的思路..

**Comment by chentianyuan** [comment]
@PanJiaChen

**Comment by PanJiaChen** [comment]
https://github.com/webpack/webpack/issues/4636

**Comment by chentianyuan** [comment]
在我司的项目上测试的确是有效果的，但是为什么有效果呢。。。
我看过一个言论是：懒加载的组件未加入modules，无法使用缓存，会被重新编译，只有被模块引用，插入script标签后，异步加载的模块才被缓存。
但是经过我的测试，不论同步还是异步，webpack-runtime的modules内都存储了所有的模块，所以到底是哪里造成了异步组件拖慢热更新速度呢。。

**Comment by PanJiaChen** [comment]
这个问题一直存在了很久了，官方已一直没解决，所有比较玄学了，我也没真正定位到原因，只能靠猜。我觉得可以去官方提一个issue。

**Comment by chentianyuan** [comment]
好的吧，如果哪边有结果了，还希望能相互告知一下，【抱拳】

**Comment by chenyiqiao** [comment]
如果的你的问题还没解决的话，可以用 babel-plugin-dynamic-import-node。在开发环境把import 转成 require,也就是在开发环境不用code split，这样即便有300个页面也可以在~3s完成热更新。

**Comment by zhuanghongbin** [comment]
@chenyiqiao 请问你的那种方法是怎么配置的？

**Comment by chenyiqiao** [comment]
@zhuanghongbin  BABEL_ENV 为 development 的时候加上这个插件

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/lazy-loading.html#%E6%96%B0%E6%96%B9%E6%A1%88

文档都有啊。

**Comment by PanJiaChen** [comment]
感觉Dan 的回答很有道理。
https://github.com/webpack/webpack/issues/4636#issuecomment-301920118

**Comment by mq-Creator** [comment]
我想看下__import 那种是怎么写，可以吗

**Comment by dongyuwei** [comment]
```
import(/* webpackMode: "lazy-once" */ `${path}`)
```
这种写法可以解决问题。动态import()请求在文件模块很多的情况下，code splitting构建大量js chunk是性能杀手。
