### ISSUE TITLE
在组件中使用elemen-ui过渡动画失效！

### ISSUE THREAD

**Issue by real-jacket** [PanJiaChen/vue-element-admin#1377]
从element-ui引入`el-collapse-transition`展开折叠过渡动画，到页面中失效，使用场景如下：
![7ed9afc5553bd591d87d915f61962aa](https://user-images.githubusercontent.com/36723264/49209341-31a16d00-f3f5-11e8-8414-2146ebc3c139.png)
![1b53b714512279f92be7b87b772a421](https://user-images.githubusercontent.com/36723264/49209538-b8eee080-f3f5-11e8-8827-b60478a29f8a.png)
页面结果：
![1b7c2a49bd752bdcd5fe71e25742bc4](https://user-images.githubusercontent.com/36723264/49209550-c1471b80-f3f5-11e8-958f-131eca9ce9b2.png)
![955188ff6e40960705130662f114003](https://user-images.githubusercontent.com/36723264/49209557-c4daa280-f3f5-11e8-9d77-c27e0054282e.png)

按理说过渡效果引入成功，但是却没有过渡动画

**Comment by PanJiaChen** [comment]
试了下没问题

**Comment by real-jacket** [comment]
回复神速啊，作者怎么使用的，为什么我这失败了

**Comment by PanJiaChen** [comment]
http://element-cn.eleme.io/#/zh-CN/component/transition

就直接官方demo试了下。

**Comment by real-jacket** [comment]
很奇怪，我也是直接用的官方demo，但是没作用，目前找不到原因，能给个思路么？

**Comment by PanJiaChen** [comment]
看是不是样式覆盖了。

**Comment by hupan508** [comment]
我也是这样。没效果 有解决吗？

**Comment by Thawsoar** [comment]
```
 <el-collapse-transition>
     <div v-show="form_hidden">
          .......
     </div>
</el-collapse-transition>
```
套一层div

**Comment by hellowuxin** [comment]
同样失效

**Comment by xianshenglu** [comment]
https://jsfiddle.net/xianshenglu/5eztxnvq/3/   repo demo.
Change `div` to `el-form`, then `el-collapse-transition` wouldn't work. 
If using `div` or move `el-form` into a `div`, it will work. So, I think it is a bug of `el-form`.

**Comment by xianshenglu** [comment]
https://github.com/ElemeFE/element/issues/17096

**Comment by MurcielagoGo** [comment]
需要将内部的标签都用一个div包裹一下 并且判断条件需要加在这个div上
![Uploading 111.png…]()

**Comment by MurcielagoGo** [comment]
需要将内部的标签都用一个div包裹一下 并且判断条件需要加在这个div上
![111](https://github.com/PanJiaChen/vue-element-admin/assets/51854804/a6556018-2812-43e3-88fc-af9840779b67)
