### ISSUE TITLE
修改动态权限问题

### ISSUE THREAD

**Issue by w5400013936** [PanJiaChen/vue-element-admin#1379]
首先使用admin账号登录，进入PagePermission页面，在该页面中切换至editor角色，接着会因为权限不足而跳转至404页面，点击404页面的“返回首页”按钮，再手动点击进入DirectivePermission页面，在页面中切换至admin角色，最后点击进入PagePermission页面，居然是跳转到404页面，望潘大能解决一下疑惑，谢谢。

**Comment by PanJiaChen** [comment]
Fixed in 4d6e9a5
