### ISSUE TITLE
eslint实际上没有启用吧？

### ISSUE THREAD

**Issue by EliazTray** [PanJiaChen/vue-element-admin#138]
放开webpack.base.config.js的注释之后，主要是semi没有控制。看上面有说开启了eslint，不知道是通过什么另外的方式启用的，还是说暂时没有使用eslint.....

**Comment by PanJiaChen** [comment]
全局可以通过 `lint run lint`
或者通过取消这段注释 https://github.com/PanJiaChen/vue-element-admin/blob/master/build/webpack.base.conf.js#L45
也可以通过配置vscode或者其它ide的eslint 详情见https://segmentfault.com/a/1190000009275424#articleHeader8

**Comment by EliazTray** [comment]
恩，取消注释就飚红(你模块里面的代码)了。yarn run dev跑起来之后，各种eslint关于semi的错，我想表达的就是这个意思

**Comment by PanJiaChen** [comment]
你是windows？这可能是ide自动格式化导致的

**Comment by EliazTray** [comment]
yeah，可能是ide的原因吧，我自己捣鼓一下.close吧

**Comment by PanJiaChen** [comment]
增加了一个[.editorconfig](https://github.com/PanJiaChen/vue-element-admin/blob/master/.editorconfig)
