### ISSUE TITLE
有请求，但是network里看不到请求是什么情况

### ISSUE THREAD

**Issue by as236676674** [PanJiaChen/vue-element-admin#1380]
有请求，但是network里看不到请求是什么情况

**Comment by w5400013936** [comment]
因为mock把请求拦截了。

**Comment by as236676674** [comment]
> 因为mock把请求拦截了。

但是请求成功了 打印返回的数据 看得到 就是看不到请求信息

**Comment by heyingjie** [comment]
> > 因为mock把请求拦截了。
> 
> 但是请求成功了 打印返回的数据 看得到 就是看不到请求信息

MOCK拦截了请求，是MOCK给的数据，不会产生真正的网络请求。

**Comment by as236676674** [comment]
> > > 因为mock把请求拦截了。
> > 
> > 
> > 但是请求成功了 打印返回的数据 看得到 就是看不到请求信息
> 
> MOCK拦截了请求，是MOCK给的数据，不会产生真正的网络请求。

这样，懂了
