### ISSUE TITLE
执行npm run dev 操作后，页面显示空白

### ISSUE THREAD

**Issue by userpengke** [PanJiaChen/vue-element-admin#1383]
从git上copy了项目到本地，执行npm run dev，提示“Your application is running here: http://localhost:9527”，打开浏览器，页面只显示空白，控制台有个错误，‘Uncaught ReferenceError: t is not defined’（最后一行是at module: ResizeHandler.js:1），请问是什么原因呢？

**Comment by userpengke** [comment]
浏览器是Chrome ---版本 70.0.3538.110

**Comment by PanJiaChen** [comment]
你确定你npm把所有包都安装成功了么。

还有能截一下报错页面么。

**Comment by userpengke** [comment]
嗯，都安装成功了。目前通过不同的浏览器测试，ms edge能正常打开，ie也不行。
chrome报错信息：
![image](https://user-images.githubusercontent.com/36985832/49271359-34a96580-f4a8-11e8-9e74-3b22c9da6699.png)

edge：
![image](https://user-images.githubusercontent.com/36985832/49271374-425eeb00-f4a8-11e8-8818-f47c40473108.png)

不知道图片能否正常显示

**Comment by userpengke** [comment]
是无痕窗口吗？刚刚试了下，也能显示且没报错。

**Comment by PanJiaChen** [comment]
那是不是你什么chrome插件导致的问题？

**Comment by userpengke** [comment]
嗯，果然是这样的。是这个插件vue.js devtools 5.0.0 beta 2造成的，关闭之后就能正常显示了，真是个大坑。非常感谢帮我解决了这个问题。
