### ISSUE TITLE
TinyMCE 图片编辑问题

### ISSUE THREAD

**Issue by david2tdw** [PanJiaChen/vue-element-admin#1384]
请问 我在用tinymce 上传一个图片的之后 在点击图片却没有出现图片编辑的选项， 这个东西是需要哪些配置，是否需要在TinyMce 的网站上申请密钥？

你的示例点击图片的效果：
![tim 20181130101510](https://user-images.githubusercontent.com/24794474/49264379-f2bcf700-f488-11e8-8bf4-9f52757dd284.png)

我的点击图片的效果：
![tim 20181130102214](https://user-images.githubusercontent.com/24794474/49264520-8ee6fe00-f489-11e8-94fd-01b2087ada1c.png)

plugins.js
const plugins = ['advlist anchor autolink autosave colorpicker colorpicker contextmenu directionality hr image imagetools importcss insertdatetime link lists nonbreaking noneditable pagebreak paste preview print save searchreplace spellchecker tabfocus table template textcolor textpattern visualblocks visualchars wordcount']

toolbar.js
const toolbar = ['searchreplace bold italic underline strikethrough alignleft aligncenter alignright outdent indent  blockquote undo redo removeformat subscript superscript code codesample', 'hr bullist numlist link image charmap preview anchor pagebreak insertdatetime media emoticons forecolor backcolor fullscreen']

tinyMCE init方法：
initTinymce () {
      const _this = this
      window.tinymce.init({
        language: 'zh_CN',
        selector: `#${this.tinymceId}`,
        height: this.height,
        object_resizing: false,
        toolbar: this.toolbar.length > 0 ? this.toolbar : toolbar,
        plugins: plugins,
        end_container_on_empty_block: true,
        powerpaste_word_import: 'clean',
        default_link_target: '_blank',
        link_title: false,
        nonbreaking_force_tab: true,
        imagetools_cors_hosts: ['www.tinymce.com', 'codepen.io'],
        imagetools_toolbar: 'rotateleft rotateright | flipv fliph | editimage imageoptions',
        content_style: 'img {max-width:640px; display:block;height:auto;}',
        init_instance_callback: editor => {
          if (_this.value) {
            editor.setContent(_this.value)
          }
          _this.hasInit = true
          editor.on('NodeChange Change KeyUp SetContent', () => {
            this.hasChange = true
            this.$emit('input', editor.getContent())
          })
        }
      })
    },

**Comment by david2tdw** [comment]
我的是在本地测试的， 测试url
http://localhost:8888/xxxxx

在文档里貌似要做一些设置
https://www.tiny.cloud/docs/plugins/imagetools/

**Comment by PanJiaChen** [comment]
https://www.tiny.cloud/docs/plugins/imagetools/#imagetools_cors_hosts

**Comment by david2tdw** [comment]
不是太懂为什么你要配置这两个地址
imagetools_cors_hosts: ['www.tinymce.com', 'codepen.io']

把你的代码拿下来在本地跑就会显示图片编辑按钮， 但把代码放到我的项目里就显示不出来， 是我少了什么配置吗？

thanks

**Comment by PanJiaChen** [comment]
你图片的地址是什么

**Comment by david2tdw** [comment]
http://192.168.10.xxx:7003/42caxxxa084fadb58506f448e8c685.png
这个是我们自己服务器的地址 专门用来下载上次过的图片

**Comment by PanJiaChen** [comment]
所以你仔细看一下 imagetools_cors_hosts 文档 是干啥用的。

**Comment by de1ck** [comment]
> 所以你仔细看一下 imagetools_cors_hosts 文档 是干啥用的。

@PanJiaChen 有些用户可能不太熟悉tinymce的配置，而且上传图片是编辑器常用功能项， 所以这块有文档说明会不会更友好？
