### ISSUE TITLE
npm install 失败 一定要依赖git? 安装了git依旧失败

### ISSUE THREAD

**Issue by authasme** [PanJiaChen/vue-element-admin#1385]
问题1：win7环境，无论是下载zip包还是通过git clone，npm install项目的时候都报 找不到git（no git binary in $PATH）。请问项目为什么要依赖git客户端？如果我不想用git,如何处理安装问题？
![image](https://user-images.githubusercontent.com/22970441/49265740-57c71b80-f48e-11e8-8d65-2f336f2dc50f.png)
问题2：安装了git客户端，报错找不到github.com( fetal: Unable to look up github.com( port 9418) )
![image](https://user-images.githubusercontent.com/22970441/49265848-cf954600-f48e-11e8-8830-0d73295acdc6.png)
问题3：安装过程中，工程目录下没有生成依赖包管理目录node_modules，如果我希望本地安装，而不是全局安装怎么处理？

期待不吝赐教，非常感谢

**Comment by PanJiaChen** [comment]
这种问题请自己随手百度。

**Comment by authasme** [comment]
@PanJiaChen 百度过了，找不到原因才提问的，麻烦提示下百度关键字，感谢

**Comment by PanJiaChen** [comment]
1. 可以不用git 直接 download （windows git安装教程很多了）
2. 感觉和你git没完整clone项目有关
3. npm install 就是本地安装

**Comment by authasme** [comment]
我开始是download zip ，然后解压 npm install ，一直提示 no git binary in $PATH
![image](https://user-images.githubusercontent.com/22970441/49271312-ff047c80-f4a7-11e8-9b63-257293997d16.png)
 然后我才尝试的安装git的的指导方法，那我再clone一次试试

**Comment by PanJiaChen** [comment]
git 其实可以不需要的。但我觉得git已经是程序开发的标配了。

python 是因为 node-sass依赖。windows需要手动安装，mac内置。

**Comment by chenwendonguser** [comment]
我也出现这个问题了。。这什么鬼啊？？怎么弄的

**Comment by authasme** [comment]
@chenwendonguser 上面说了，报图一中那个git执行失败的问题是git2.19.2版本有bug,换个版本

**Comment by dxxzst** [comment]
git2.19.1 解决
