### ISSUE TITLE
 v-if v-else 代码块内来回切换时<el-table-column fixed=right>中的按钮无法显示，如下

### ISSUE THREAD

**Issue by ihmLouie** [PanJiaChen/vue-element-admin#1388]
先别考虑数据的问题，一个页面中
例如：
<el-button @click="aa = 1">显示if模块内容</el-button>
<el-button @click="aa = 0">显示else模块内容</el-button>
<div v-if="value ">
   <el-table>
            <el-table-column :data="aInfos" label="操作" fixed="right">
              <template slot-scope="scope">
                <el-button type="text" size="small">编辑</el-button>
                <el-button type="text" size="small">删除</el-button>
              </template>
            </el-table-column>
   </el-table>
</div>
<div v-if="">
   <el-table>
            <el-table-column :data="bInfos" label="操作" fixed="right">
              <template slot-scope="scope">
                <el-button type="text" size="small">编辑</el-button>
                <el-button type="text" size="small">删除</el-button>
              </template>
            </el-table-column>
   </el-table>
</div>

以上代码点击按钮切换时，无法显示编辑、删除按钮，上面代码为大致意思，请自行编译；
盼复~~~~~~~

**Comment by PanJiaChen** [comment]
请提供一个在线可还原demo   https://jsfiddle.net/qvzw3j5t/
