### ISSUE TITLE
使用文档的方法删除mock后,请求数据和上传数据都报错

### ISSUE THREAD

**Issue by lxk0301** [PanJiaChen/vue-element-admin#1390]
你好 , 根据文档https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/mock-api.html#swagger   提供的方法删除mock后,

### 我这边get请求出现如下错误
![image](https://user-images.githubusercontent.com/21308593/49285428-561f4700-f4d2-11e8-8139-95c836f4b745.png)
### post请求就出现403的错误
![image](https://user-images.githubusercontent.com/21308593/49285449-63d4cc80-f4d2-11e8-9eb3-7bc969997156.png)
![image](https://user-images.githubusercontent.com/21308593/49285456-68998080-f4d2-11e8-8edc-c16892c4a699.png)

## 如果不移除mock,就一切正常.  请问这是怎么回事?如何移除才不会导致如上的错误

**Comment by PanJiaChen** [comment]
你能不能把错误自己随手搜一下为什么。自己的接口不支持跨域。

**Comment by lxk0301** [comment]
> 你能不能把错误自己随手搜一下为什么。自己的接口不支持跨域。

你好 ,我们后端说接口是支持跨域的,  还有就是如果不支持跨域,和删除mock ,又有啥关系呢?

**Comment by PanJiaChen** [comment]
你mock了，请求都被拦截了，都不会发真正的请求。相关问题请自行检索。
