### ISSUE TITLE
引导页错位问题

### ISSUE THREAD

**Issue by dreamfinally** [PanJiaChen/vue-element-admin#1391]
引导页，点击下一步，到Tags view之后，再返回上一步，会出现错位

**Comment by PanJiaChen** [comment]
没能重现。
请说明系统 浏览器版本 和重现的截图或者gif。

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/46d6f455afb596b6d05a8a61676cbc52ba9214c6

主要是因为 focus  Tagsview 的时候出现了滚动条，所以导致定位不准了。修改一下样式就好了。

**Comment by dreamfinally** [comment]
好的，期待4.0
