### ISSUE TITLE
根据服务端数据生成菜单后点击菜单 进入页面 按F5 刷新 出现404

### ISSUE THREAD

**Issue by yangqifang** [PanJiaChen/vue-element-admin#1392]

**Comment by PanJiaChen** [comment]
请用真确的姿势提问，你这种提问方式没人能帮得了你。

**Comment by yangqifang** [comment]
好的 换个姿势 

根据服务端 数据 生成动态路由后 点击生成的菜单 进入页面后 
![qq 20181203103400](https://user-images.githubusercontent.com/32587968/49349730-f8177d00-f6e6-11e8-971b-52e0bcac6a4b.png)

再按F5刷新 刷新直接跳到404 
![qq 20181203103611](https://user-images.githubusercontent.com/32587968/49349816-60665e80-f6e7-11e8-9a9f-30ba1d8546ea.png)

**Comment by PanJiaChen** [comment]
刷新页面 你是不是没有重现 addRouters

**Comment by yangqifang** [comment]
重现 addRouters后 router.options中并没有我添加的数据 所以我使用router.options.routers.push方法 添加路由 可以在router.options中成功的添加数据并渲染侧栏 但是就会出现之前所说的那种情况 大神 救救我这个后端猿吧😭

**Comment by yangqifang** [comment]
![image](https://user-images.githubusercontent.com/32587968/49501465-e2a07f80-f8ad-11e8-994e-99831e3bc856.png)

![image](https://user-images.githubusercontent.com/32587968/49501505-fba93080-f8ad-11e8-93c5-e53716826527.png)

**Comment by airzhanglin** [comment]
> 好的 换个姿势
> 
> 根据服务端 数据 生成动态路由后 点击生成的菜单 进入页面后
> ![qq 20181203103400](https://user-images.githubusercontent.com/32587968/49349730-f8177d00-f6e6-11e8-971b-52e0bcac6a4b.png)
> 
> 再按F5刷新 刷新直接跳到404
> ![qq 20181203103611](https://user-images.githubusercontent.com/32587968/49349816-60665e80-f6e7-11e8-9a9f-30ba1d8546ea.png)

楼主有解决吗？刷新之后就进了404

**Comment by nongfuguoyuan016** [comment]
@airzhanglin @yangqifang 在roter/index.js 文件中, 必须把 { path: '*', redirect: '/404', hidden: true } 放在最后 , 如果你只是放在 constantRoutes 的最后是不行的 , 必须要放在 asyncRoutes 的最后

**Comment by lee-ever** [comment]
@yangqifang @airzhanglin 你们都解决了吗？一样的问题...

**Comment by sqlnice** [comment]
> @airzhanglin @yangqifang 在roter/index.js 文件中, 必须把 { path: '*', redirect: '/404', hidden: true } 放在最后 , 如果你只是放在 constantRoutes 的最后是不行的 , 必须要放在 asyncRoutes 的最后

很有帮助，谢谢，一直以为只要放在constantRoutes 后面就行了
