### ISSUE TITLE
Ie下的问题，已经加了babel-polyfill,急！！！！

### ISSUE THREAD

**Issue by LookingForWord** [PanJiaChen/vue-element-admin#1395]
![image](https://user-images.githubusercontent.com/25653463/49349448-9dc9ec80-f6e5-11e8-8d9c-4d28566c0cd2.png)
![image](https://user-images.githubusercontent.com/25653463/49349495-c81baa00-f6e5-11e8-8226-2a2b504f22b1.png)

**Comment by lxk0301** [comment]
加了就正常了,  还有问题就是你自己的代码有问题(比如多写了一个 border,又或者多写了id等等),  或者使用的插件(比如网上找的图片预览插件)导致出错, 你自己去看IE浏览器的报错,去排除问题
