### ISSUE TITLE
axios response 异常处理

### ISSUE THREAD

**Issue by sanliu2015** [PanJiaChen/vue-element-admin#1397]
请问想手工处理某部分异常（比如自定义弹出信息），而不再走全局拦截那种提示信息怎么处理，因为会弹出两次框不友好

**Comment by PanJiaChen** [comment]
要么在创建一个没有错误提示的请求实例。
要么在加一个参数，请求的时候通过控制这个参数来判断需要默认提示。

**Comment by ensleep** [comment]
其实，就不应该全局处理，真的。重新window.alert，传入两个参数，使用的时候如下：
```
axios.get().then(resp=>{}).catch(error=>{alert(error,"某数据处理失败");//do something other});
```
重载的alert方法中，对error的类型和数据结构 进行判断，符合直接显示的则显示 ，401之类的该跳至登陆界面就跳，从response里面能拿到msg的直接作为内容提示出来，否则，将状态码的中文释义作为内容提示出来，提示的时候，弹窗的title使用第二参数，即上面例子中的"某数据处理失败"
