### ISSUE TITLE
第二次进入编辑页面，url显示错误。

### ISSUE THREAD

**Issue by thj8** [PanJiaChen/vue-element-admin#1398]
```
<el-table-column :label="$t('common.operation')" align="left">
  <template slot-scope="scope">
    <router-link :to="{name: 'UserEdit', params: {id: scope.row.id}}">
    <!-- <router-link :to="'/admin/system/user/detail/edit/'+scope.row.id"> -->
      <el-button type="primary" icon="el-icon-edit">{{ $t('common.edit') }} {{ scope.row.id }}</el-button>
    </router-link>
  </template>
</el-table-column>
```
第一次进去列表页面，显示正常，所有a标签href显示正常，点击一个进入到详细页面，再点击浏览器返回，此时所有编辑页面href全部变为一致，但是点击进去获取到的id又是正常，很疑惑？
列表页按钮上的id又是正确。用注释的代码又没有啥问题。
谢谢！
![image](https://user-images.githubusercontent.com/6202705/49380591-fd0f1780-f74c-11e8-81ad-7135a227c1b5.png)

**Comment by thj8** [comment]
![image](https://user-images.githubusercontent.com/6202705/49380828-86bee500-f74d-11e8-9a34-79ec00fc0feb.png)
望大佬指教

**Comment by PanJiaChen** [comment]
没能重现

**Comment by thj8** [comment]
根据调试代码，发现是面包屑导致的，很不幸的是大约26天前，看到了文件更新，我还用的是老版本的代码。 @PanJiaChen 谢谢。

**Comment by PanJiaChen** [comment]
恩，这个bug已经修掉了。

**Comment by yixius** [comment]
> 根据调试代码，发现是面包屑导致的，很不幸的是大约26天前，看到了文件更新，我还用的是老版本的代码。 @PanJiaChen 谢谢。

请教下，这个问题的修复，是因为哪个文件的修复啊

@PanJiaChen @thj8

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/a51d72f42e27773a1f55beade504b79b3b8a5b46
