### ISSUE TITLE
菜单渲染时如果三级菜单下只有一个子菜单，则无法正常渲染三级菜单出来

### ISSUE THREAD

**Issue by applepear0812** [PanJiaChen/vue-element-admin#1399]
![image](https://user-images.githubusercontent.com/44150584/49426089-6d17af00-f7da-11e8-8a5c-ac4b9152f117.png)

**Comment by laonier** [comment]
hasOnlyOneShowingChild (route) {
      // 判断多级子菜单
      let aloneChild = {}
      let showingChildren = route.children.filter(item => {
        if (!item.hidden) {
          aloneChild = item
        }
        return !item.hidden
      })
      if (showingChildren.length === 1) {
        return this.hasOnlyOneShowingChild(aloneChild)
      } else {
        return false
      }
    }

**Comment by PanJiaChen** [comment]
没能重现你的问题，如果还有问题，请提供 `vue-element-admin` 的版本号，和能重现你问题的路由配置。

**Comment by laonier** [comment]
> 
> 
> 没能重现你的问题，如果还有问题，请提供 `vue-element-admin` 的版本号，和能重现你问题的路由配置。

这个我遇到过，菜单A下面只有一个菜单B菜单B下面也只有一个菜单C，
C菜单就无法渲染出来
