### ISSUE TITLE
建议增加国际化处理，至少支持中英文。

### ISSUE THREAD

**Issue by CHCP** [PanJiaChen/vue-element-admin#14]

**Comment by johncade** [comment]
It would be nice to support english, it makes the page impossible to use without English support. Thanks!

**Comment by CHCP** [comment]
国际化中英文的选择应该设计在登录界面的顶部，请参考。@PanJiaChen

**Comment by PanJiaChen** [comment]
暂时只做了 侧边栏的中英文切换 只是暂时的。

**Comment by mingyec** [comment]
你好，我看到中英文的切换有借助Vuex，我想问下如果不用Vuex的话有没有办法？
效果：不刷新页面的前提下，切换中英文（就跟你当前的效果一样）

**Comment by PanJiaChen** [comment]
我只是用了vuex来存储当前的lang是zh还是en，方便下次进来的时候不用重新设置

**Comment by mingyec** [comment]
@PanJiaChen 谢谢大神回复，我参考了你的项目代码，切换中英文最主要的是`this.$i18n.locale = language`这句，但为啥我无法像你的项目一样动态切换呢？如果大神有空&心情好的话请赐教~

**Comment by PanJiaChen** [comment]
@mingyec 建议看vue-i18n文档

**Comment by mingyec** [comment]
谢谢

**Comment by PanJiaChen** [comment]
trace in #64
