### ISSUE TITLE
TinyMCE 点全屏，再点浏览器回退按钮，右侧滚动条消失

### ISSUE THREAD

**Issue by xiak** [PanJiaChen/vue-element-admin#1400]
步骤：

1. 点 TinyMCE 全屏按钮
2. 在全屏状态下点击浏览器 回退按钮 <-， 回退到前一个页面

问题:

右侧滚动条消失了，切换到其他 menu 下也不会出现滚动条

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/999ea3a44339c0dc86400075570ffbbd7c6ed720
