### ISSUE TITLE
about  proxyTable 

### ISSUE THREAD

**Issue by menciusKael** [PanJiaChen/vue-element-admin#1402]
我设置了代理 
proxyTable: {
      '/api': {    
        target: 'http://www.webserver.com/api/',   
        changeOrigin: true,
        pathRewrite: {
          '^/api': '' 
        }
      }
    }, 
然后封装请求
export function allgoods(member_id) {
  return request({
    url: '/api/managepage/allgoods',     
    method: 'post',
    data: {
      member_id
    }
  })
}
然后本地运行 npm run dev

然后地址栏访问 http://localhost:9528/#/shop/index，请求成功，但是查看Network

Request URL :  http://localhost:9528/api/managepage/allgoods 

整个过程是没出问题，但是没有理解到。

我理解如下：

Network中 请求Request URL显示的是 http://localhost:9528/api/managepage/allgoods ，但实际上相当于请求的是，http://www.webserver.com/api/managepage/allgoods， 然后我本地查看的是没有经过npm run build构建之前的代码，运行在 webpack-devserver 搭建的开发环境本地服务器上面的，然后9528端口是我本地接受数据的端口，与后端无关，是这样理解吗

**Comment by jingyulong** [comment]
[[issues#1416](https://github.com/PanJiaChen/vue-element-admin/issues/1416)]
跟我提的问题类似，其实我也不太理解

**Comment by PanJiaChen** [comment]
proxyTable 问题请自行检索解决方案。和本项目无关。
