### ISSUE TITLE
Mock去掉后的登录问题

### ISSUE THREAD

**Issue by gongph** [PanJiaChen/vue-element-admin#1403]
感觉系统登录这部分做的浸入式太强了，这部分完全可以交给用户自己来做了。比如根据登陆后的信息自己读写 cookie 啥的，还有菜单栏的权限问题，因为有些项目根本不需要前台做权限验证。

我在去掉 Mock 之后，没进行后台登录联调的情况下，是登陆不了的，因为 Router 做了拦截，还要校验一些列的权限啊，Token 啥的，这些我都用不到，改起来麻烦。

后续能不能有一种简单的方式，比如开关，关闭 Mock 就不用验证登录和权限啥的了。还发现一个 Mock的一个不知道算不算bug的bug，就是 socketio 连接问题，强行给我替换掉了导致连接不上。

另，作者辛苦了。

**Comment by gangyahaidao** [comment]
主要是想表达什么？没有看明白，觉得不满意最好是提出自己认为可能的解决办法比较好
