### ISSUE TITLE
新拉项目 依赖包被弃用了怎么办 跑不起来

### ISSUE THREAD

**Issue by web-var** [PanJiaChen/vue-element-admin#1407]
$ npm install
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\mingw64\bin\git.EXE ls-remote -h -t git://github.com/adobe-webplatform/eve.git
npm ERR!
npm ERR! fatal: unable to look up github.com (port 9418) (Ӧ�ó���û�е��� WSAStartup������ WSAStartup ʧ�ܡ� )
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\123\AppData\Roaming\npm-cache\_logs\2018-12-07T10_13_35_309Z-debug.log

**Comment by web-var** [comment]
本来想删了那个依赖 但是package.json里面找不到那个包

**Comment by eMeab** [comment]
您可以使用以下命令告诉git使用https而不是git://：
git config --global url."https://".insteadOf git://

**Comment by axhello** [comment]
![1544240172 1](https://user-images.githubusercontent.com/10368684/49681492-a5bacf80-fadd-11e8-9648-d99ae0c77497.png)

是jsonlint这个包么？

**Comment by web-var** [comment]
thanks 已经解决了 我看到作者在其他的地方有引用这个问题 更新webpack-bundle-analyzer的版本就ok了

**Comment by web-var** [comment]
thanks 已经通过更新webpack-bundle-analyzer的版本解决了

**Comment by 176177082** [comment]
小白问一下，具体怎么解决的，更新不了，指定版本也不行

**Comment by 176177082** [comment]
@joker-ssh 问下具体怎么解决的这个问题，“更新webpack-bundle-analyzer的版本就ok了”

**Comment by guwan** [comment]
我更新了webpack-bundle-analyzer这个包还是报错

**Comment by guwan** [comment]
解决了,
git ls-remote -h -t git://github.com/adobe-webplatform/eve.git
这一行报错,因为git://github.com/adobe-webplatform/eve.git不是有效的地址,
要么是https://github.com/adobe-webplatform/eve.git
要么是git@github.com:adobe-webplatform/eve.git
地址错了,
git config --global url."https://".insteadOf git://
