### ISSUE TITLE
为什么我在这个框架中引入vue-video-player插件失败？

### ISSUE THREAD

**Issue by gangyahaidao** [PanJiaChen/vue-element-admin#1408]
想播放视频，引入了vue-video-player插件，操作如下：
安装：`npm install vue-video-player --save`
在文件中引入：
```
import VideoPlayer from 'vue-video-player'
import 'video.js/dist/video-js.css'
import 'vue-video-player/src/custom-theme.css'
```
在加载文件的时候显示如下错误，提示找不到组件：
![image](https://user-images.githubusercontent.com/25075558/49684746-c5b8b600-fb12-11e8-97c0-096bb3412e6d.png)

请问有什么解决办法吗？

**Comment by gangyahaidao** [comment]
也许是这个插件的原因，换了一个d-player可以
[https://github.com/MoePlayer/vue-dplayer](https://github.com/MoePlayer/vue-dplayer)

**Comment by wuxin1210** [comment]
> 也许是这个插件的原因，换了一个d玩家可以
> http://dplayer.js.org/#/home?id=options

大佬, 有能兼容IE9+或者IE10+的好用的音频播放器插件么(vue项目中使用)

**Comment by gangyahaidao** [comment]
@wuxin1210 一般我都是用chrome浏览器，基本不去适配IE的
