### ISSUE TITLE
你好，想向你请教一个问题，关于`tinymce`和`<keep-alive>`

### ISSUE THREAD

**Issue by hezhongfeng** [PanJiaChen/vue-element-admin#141]
在使用这种路由进行切换的时候，发现`tinymce`会变得不能编辑，toolbar还可以点击，您遇到过这种情况吗？
```
        <keep-alive>
          <router-view></router-view>
        </keep-alive>
```

**Comment by PanJiaChen** [comment]
这涉及到tinymce init 之后会创建一个动态iframe 而keep-alive回来之后iframe是空的。
两种解决方案，使用`<keep-alive exclude="a,b">` 让tinymce页面不keep-alive
或者
```javascript
activated() {
  init tinymce
},
deactivated(){
  destroy tinymce
}
```
在这两个keep-alive的生命周期内重新销毁和初始化tinymce

**Comment by hezhongfeng** [comment]
@PanJiaChen 
谢谢花裤衩，这可帮了我大忙了~被这个问题坑了好久，一直以为是自己的问题，最后才发现是`<keep-alive>`

**Comment by chendind** [comment]
可以试试这样
activated() {
    tinymce.EditorManager.execCommand('mceAddEditor', true, `tinymce容器的id`)
  },
  deactivated() {
    tinymce.EditorManager.execCommand('mceRemoveEditor', true, `tinymce容器的id`)
  }
