### ISSUE TITLE
大佬, 可以做个生成PDF的demo吗？

### ISSUE THREAD

**Issue by xerxesxiaohua** [PanJiaChen/vue-element-admin#1413]
有时候需要打印PDF, 看了你这个网站确实挺好, 想学习下怎么打印PDF~  动态PDF.从后台接受数据生成PDF的那种~

**Comment by PanJiaChen** [comment]
[window.print](https://www.google.com/search?q=window.print&oq=window.pr&aqs=chrome.2.69i58j69i57j69i59.13968j0j1&sourceid=chrome&ie=UTF-8)

**Comment by Fighter888** [comment]
用iText pdf 库操作PDF

**Comment by PanJiaChen** [comment]
Add demo in https://github.com/PanJiaChen/vue-element-admin/pull/1469
