### ISSUE TITLE
如何设置默认语言？是在lang中的index吗？为啥我设置没有效果

### ISSUE THREAD

**Issue by toKnowMore** [PanJiaChen/vue-element-admin#1420]
![image](https://user-images.githubusercontent.com/31891099/49787823-a1531880-fd62-11e8-88a0-fb0e7df239da.png)

**Comment by 15036900300** [comment]
你把src/store/modules/app.js中
<img width="594" alt="image" src="https://user-images.githubusercontent.com/15808969/49790247-b6cb4100-fd68-11e8-833f-e39bb6ac8fdf.png">

**Comment by toKnowMore** [comment]
thanks

**Comment by 15036900300** [comment]
如果解决了，看看自己关闭了吧

**Comment by zky86** [comment]
已经这样设置，设置语言无效，请问是什么原因？ 右上角点击切换语言又可以。。
按 src/store/modules/app.js  这样设置中文 "zh" 还是设置不了默认中文

**Comment by zky86** [comment]
解决了，原来 vue-element-admin-master\src\lang\index.js  里面还得设置一个 "zh" 才可以默认中文。2个地方，一个src/store/modules/app.js， 一个src\lang\index.js   都设置zh才行。 作者可以对设置语言版本给个提示么，找了好久才找到。

**Comment by 15036900300** [comment]
@zky86 哈哈，看来我也没看仔细

**Comment by PanJiaChen** [comment]
4.0版本之后可以在settings 里面设置。

**Comment by jiashiwen** [comment]
settings里面怎么设置？文档里也没找到
