### ISSUE TITLE
导航菜单背景颜色能修改问题

### ISSUE THREAD

**Issue by Jarryham** [PanJiaChen/vue-element-admin#1422]
通过修改variables.scss这个文件的颜色，发现一级菜单的hover不起效，只对一级以下的有效
![image](https://user-images.githubusercontent.com/18054284/49846115-a668a400-fe04-11e8-8c93-3fe7706a30ba.png)
强行用css覆盖后会发现一个问题，点击菜单后，不点击其他页面元素，直接切换其他窗口，然后回到页面，发现菜单上的颜色变为#ccc的颜色，需要点击其他页面元素才能恢复
![image](https://user-images.githubusercontent.com/18054284/49846224-3ad30680-fe05-11e8-8c82-e400899ef41d.png)
![image](https://user-images.githubusercontent.com/18054284/49846245-4de5d680-fe05-11e8-9f96-9733a9defdd1.png)

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/1568
