### ISSUE TITLE
语言切换报错

### ISSUE THREAD

**Issue by toKnowMore** [PanJiaChen/vue-element-admin#1423]
this.$i18n.locale = lang
![image](https://user-images.githubusercontent.com/31891099/49845978-f8f59080-fe03-11e8-805a-a0f0ec6fc2e7.png)

切换的时候报错

vue.runtime.esm.js:587 [Vue warn]: You may have an infinite update loop in a component render function.
found in
---> <SidebarItem> at src\views\layout\components\Sidebar\SidebarItem.vue
       <ElMenu>
         <ElScrollbar>
           <Sidebar> at src\views\layout\components\Sidebar\index.vue
             <Layout> at src\views\layout\Layout.vue
               <App> at src\App.vue
                 <Root>

**Comment by toKnowMore** [comment]
注掉 this.$i18n.locale = lang 就不会报错

**Comment by PanJiaChen** [comment]
没能重现你的问题。
