### ISSUE TITLE
图标的尺寸规范

### ISSUE THREAD

**Issue by heuuLZP** [PanJiaChen/vue-element-admin#1425]
建议在 [生成图标库代码](https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/icon.html#%E7%94%9F%E6%88%90%E5%9B%BE%E6%A0%87%E5%BA%93%E4%BB%A3%E7%A0%81) 文档中添加如下描述。

项目图标是有设计尺寸的，建议说明以下，因为从iconfont找的图标和本项目的设计规范不一致。

从 [iconfont.cn](http://iconfont.cn/) 上面找的图标，需要编辑，将图标尺寸调整为最大

![image](https://user-images.githubusercontent.com/18410118/49914723-5f92b100-fecd-11e8-858c-000f07918d63.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin-site/commit/737b0d6810347748bbc749d4d37b42e7c581e3d0
