### ISSUE TITLE
较低版本升级到webpack3.x的版本，出现找不到文件

### ISSUE THREAD

**Issue by zhangaofei** [PanJiaChen/vue-element-admin#1427]
从一个之前版(webbpack32.X)本升级到（webbpack3.X）且都是用群主的配置，没有dev-client和dev-server后发现路经对不上的错位，感觉vue-loader解析有问题，但不知从何入手，群主给点指导；错误如下：
* api/admin in ./src/store/modules/admin.js
* api/enDNS/cache in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/views/admin/dns/cache/edit.vue, ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/views/admin/dns/cache/add.vue and 1 other
* api/enDNS/cartogram in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/views/admin/dns/domainStatistic/domainStatistic.vue, ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/views/admin/dns/lineStatistic/lineStatistic.vue and 4 others

**Comment by PanJiaChen** [comment]
重新安装依赖过么？
