### ISSUE TITLE
关于异步路由里的权限问题

### ISSUE THREAD

**Issue by yuanyuanyuan** [PanJiaChen/vue-element-admin#143]
```
{ path: 'form/edit', component: Form, name: '编辑Form', meta: { isEdit: true } },
```
这里的 meta 不是用 role，好像看到代码里面没有处理这个，我看代码本身可以做 role 的判断，但是没看到细致权限的判断，如果加上这个细致权限处理，那么hasPermission和filterAsyncRouter的过滤好像会变得好复杂，请问是有什么考虑，或者应该怎么处理比较好呢？ 谢谢

**Comment by PanJiaChen** [comment]
`meta` 你可以理解为就是一个可以随便传什么的自定义字段，`isEdit` [这里用到了](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/example/form.vue#L193)

`role` 同理也是一个人为自定义的规则而已。`hasPermission` 和 `filterAsyncRouter` 的复杂也是不能避免的，毕竟要兼容无限嵌套的权限验证。如果你自己的业务中没这么复杂，可自行修改。

**Comment by yuanyuanyuan** [comment]
喔，原来是是写在了组件本身，其实我是有一个地方不明白，既然用了 role 来做权限，然后又要在其他地方做编辑这种细致权限验证，会不会很乱？我开始是想，为什么不是一个地方做完了所有的权限验证，所以直接判断这个页面是否有read edit or delete 的权限，那么这样的话，好像 role 的作用就没了。

**Comment by PanJiaChen** [comment]
你好像理解错 `isEdit` 的作用了，详情见[文章](https://segmentfault.com/a/1190000009762198#articleHeader17)

**Comment by yuanyuanyuan** [comment]
噢。。。。。。。。。原来如此，谢谢。
