### ISSUE TITLE
keep-alive，缓存页面的问题

### ISSUE THREAD

**Issue by zhenxionglv** [PanJiaChen/vue-element-admin#1430]
设置：
          1.已经根据作者大大的方法看了文档，结合，tagsView+keep-Alive在主要缓存的路由的meta下设置
![default](https://user-images.githubusercontent.com/22031113/49995437-17f05000-ffc7-11e8-8697-74bc12d577d4.png)

           2.在appMian设置了:include="cachedViews"
![default](https://user-images.githubusercontent.com/22031113/49995491-44a46780-ffc7-11e8-8519-1caac72e6b2b.png)

         3.我使用的是基础版的开发版本store里面已经添加了tagsView.js的配置方法

问题：
        1.我从侧边栏点击进入列表页，点击了筛选条件
           图一是刚进入的初始化页面
![default](https://user-images.githubusercontent.com/22031113/49995702-db712400-ffc7-11e8-8cf6-63cae3e0dada.png)
           图二是我选着筛选的页面
![default](https://user-images.githubusercontent.com/22031113/49995745-03f91e00-ffc8-11e8-8951-4f510df6ccea.png)

       2.我需要缓存的页面是我选着筛选条件后列表页面

      3.当我点击查看跳转到详情页
![default](https://user-images.githubusercontent.com/22031113/49995835-43276f00-ffc8-11e8-80be-27f96c8196ec.png) 
      4.再返回销售报表的时候列表页没有缓存到
![default](https://user-images.githubusercontent.com/22031113/49995896-72d67700-ffc8-11e8-90fe-1f9c59090dc2.png)
![default](https://user-images.githubusercontent.com/22031113/49995906-7a961b80-ffc8-11e8-84c0-730eac3ba354.png)
请问是什么原因呢？我已经全部都设置了，然后我打印发现没有缓存的路由数据，求大大解答
![default](https://user-images.githubusercontent.com/22031113/49995941-97caea00-ffc8-11e8-8f1c-263dc462fecb.png)
![default](https://user-images.githubusercontent.com/22031113/49995956-a74a3300-ffc8-11e8-97a8-9052e58a282b.png)

**Comment by axhello** [comment]
router name要和组件里面的name一毛一样，组件才会缓存

**Comment by zhenxionglv** [comment]
问题暂时已经解决，

**Comment by Fun005** [comment]
> router name要和组件里面的name一毛一样，组件才会缓存

感谢~

**Comment by stevenYangx** [comment]
怎么解决的啊？请教

**Comment by zoujianliang1994** [comment]
请教下 那三级路由怎么做缓存啊

**Comment by yushengling** [comment]
请教下 那三级路由怎么做缓存啊 ,同问

**Comment by fya0122** [comment]
按你的方法一模一样的写下去，还是不能缓存啊
