### ISSUE TITLE
将assetsPublicPath设置为cdn地址，编译之后的index.html中文件引用地址不是cdn地址

### ISSUE THREAD

**Issue by Nomia** [PanJiaChen/vue-element-admin#1431]
如题：
将`assetsPublicPath`设置为cdn地址，如`https://cdn.xxx.com/static`，编译之后的`index.html`中引用的文件(`css`,`js`)地址不会替换，还是`/static/xxxx.js /static/xxx.css`。

![image](https://user-images.githubusercontent.com/1707818/49996235-846c4e80-ffc9-11e8-9289-bcf1878f7722.png)

下面是build的配置:
![image](https://user-images.githubusercontent.com/1707818/49996299-a2d24a00-ffc9-11e8-8b24-da0e1d321275.png)

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/50510334-4a6c7380-0ac4-11e9-9c87-ac1631fa9d77.png)


测试了下没没什么问题，请确定是否自己代码问题，
