### ISSUE TITLE
TagsView右键菜单获取当前tag问题

### ISSUE THREAD

**Issue by phoenixor** [PanJiaChen/vue-element-admin#1433]
![image](https://user-images.githubusercontent.com/6568115/50061864-a2f76300-01de-11e9-9182-ec21b043185d.png)
请问这里下拉菜单的点击事件中，直接传入selectedTag就能获取到当前右击的tag，是怎么做到的？？不知道这个参数是怎么传入的。

**Comment by PanJiaChen** [comment]
`openMenu`方法中传入的。
