### ISSUE TITLE
Extend as GNU/Gpl v3 License

### ISSUE THREAD

**Issue by yamelsenih** [PanJiaChen/vue-element-admin#1434]
Hi @PanJiaChen @all 
We have a ERP project named [ADempiere ERP](https://github.com/adempiere/adempiere) and we want to user your great contribution as new UI/UX for [ADempiere ERP](https://github.com/adempiere/adempiere), for it we want to extend this project and add a sub-license or change license to GNU/GPL v3, I have a some questions for you:

- I know that MIT licence allows change or create a new license with a new project from base licence. I want to kow if you allows it?

- Exists other way for use your project? We are fine with GPL/ v3.

we have a fork of your project [here](https://github.com/adempiere/vue-element-admin) and I am waiting for your reply.

Best Regard

Yamel Senih (ADempiere Contributor)

**Comment by PanJiaChen** [comment]
No problem, welcome to use :smile:

**Comment by yamelsenih** [comment]
Thank you @yamelsenih
