### ISSUE TITLE
treeTable 树形控件添加复选框

### ISSUE THREAD

**Issue by zouzonghua** [PanJiaChen/vue-element-admin#1435]
如题 如何添加复选框选中父级默认选中所有 希望有做出来的大佬 分享一下 Demo

**Comment by hql7** [comment]
https://www.npmjs.com/package/@weilan/el-tree-table,擅自在treetable基础上添加了复选框功能，，，

**Comment by hql7** [comment]
擅自在treetable的基础上扩展了复选框功能，，，地址：https://www.npmjs.com/package/@weilan/el-tree-table

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1587
