### ISSUE TITLE
Doesn't work on IE 10, 11

### ISSUE THREAD

**Issue by Rizwan-Qamar** [PanJiaChen/vue-element-admin#1436]
Promise is undefined on IE 10, 11.
![image](https://user-images.githubusercontent.com/1522223/50088171-94906200-0245-11e9-9c40-7dd97762ece9.png)

Documentation says IE 10, 11 is supported and for lower versions find polyfills.

**Comment by lynhao** [comment]
first step:  install babel-polyfill 
second step:  add the following configuration to the  webpack configuration file.
`entry: {
    app: ['babel-polyfill', './src/main.js']
  }`
finally： entry file import the  babel-polyfill  such as  ‘main.js’

**Comment by PanJiaChen** [comment]
Currently does not support ie, please install polyfill yourself.
