### ISSUE TITLE
权限树checkbox的需求

### ISSUE THREAD

**Issue by suguoyao** [PanJiaChen/vue-element-admin#1439]
后续是否有checkbox树的设置权限功能呢？其中可以全选和半选。🙂
![image](https://user-images.githubusercontent.com/16471605/50141883-9ad51b80-02e3-11e9-9fef-caa99e535d96.png)

**Comment by PanJiaChen** [comment]
关注 https://github.com/PanJiaChen/vue-element-admin/issues/900

**Comment by suguoyao** [comment]
@PanJiaChen 好的，谢谢了
