### ISSUE TITLE
发现了雷同项目

### ISSUE THREAD

**Issue by eddiebai** [PanJiaChen/vue-element-admin#144]
https://github.com/LuLuCodes/vue-back-end-template，
dashboard相同，很多代码都是基于你的改的，并且没有fork，也没有说明源码出处。

**Comment by PanJiaChen** [comment]
谢谢你的反馈，不过开源项目被人借鉴也是很正常的事情，本项目也标注了 ` MIT` 证书，所以他说不说明来源全靠自觉了。再次谢谢你的反馈。
