### ISSUE TITLE
upload-excel 日期和返回值的问题

### ISSUE THREAD

**Issue by xerxesxiaohua** [PanJiaChen/vue-element-admin#1445]
我自己下载了个template, 从admin复制了部分代码.  
1. 同一份 excel 上传的情况下, 在 table 里面可以显示数据, 但是在 template 里面显示日期的是 43434(在 excel 中的值是 43434, 但通过修改单元样式变成日期的这种状态), 在 admin 里面显示的是 2018/11/30. 我想请问下这个东西是在哪里修改, 并且我需要的是 yyyy-MM-dd 样式.
2. 例如在一份 excel 里面有 34列, 上传之后 table 显示的确实是34列, 但是获取到 handleSuccess({ results, header }) 里面的 results[index] 却只有十几列的数据. 因为这些数据需要传到后台, 所以需要一次获取完(这个地方是有延迟加载之类的东西?).

**Comment by xerxesxiaohua** [comment]
返回值的那个问题我已经解决了..
日了狗了..
XLSX.utils.sheet_to_json(worksheet)这个方法在获取值的时候只获取非空的.. 所以导致excel中值是空的字段并没有添加到里面去..  我原本以为是会出现
{
 "a":"",
 "b":"",
}
这种样子..
结果居然返回个{}

**Comment by xerxesxiaohua** [comment]
@PanJiaChen 第一个问题 显示格式是在哪里设置的呢？  我想要这样的 yyyy-MM-dd

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/311796a14b034fdd6e670fbb0f415dc12f3a3df6/src/views/excel/uploadExcel.vue#L37

table的数据你可以随便自己二次处理。
