### ISSUE TITLE
在打包部署后，首次访问，在js下载完之前，发现index.html里的body里是空的，包括<div id="app"></div>和我定义的动画div，js下载完才显示出来，不知道是什么情况

### ISSUE THREAD

**Issue by sniper52237** [PanJiaChen/vue-element-admin#1448]

**Comment by sniper52237** [comment]
这样导致 我在加载白屏时  加的动画没能显示出来，是webpack注入 做了额外的什么事吗

**Comment by sniper52237** [comment]
找到原因了 把index.html的body标签下的<script src="<%= htmlWebpackPlugin.options.path %>/tinymce4.7.5/tinymce.min.js"></script>

放到 body内最后一行div标签之后， 之前是放在div前面出现此问题

**Comment by PanJiaChen** [comment]
的确有点问题，很多页面不需要 tinymce 也会阻塞页面的加载。之后改善一下。

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/2102
