### ISSUE TITLE
登陆页面token的值一定要admin才能登陆，如果更改别的一直提示error submit!!

### ISSUE THREAD

**Issue by zky86** [PanJiaChen/vue-element-admin#1449]
登陆页面token的值一定要admin才能登陆，如果更改别的一直提示error submit!!
用默认的admin正常登陆没问题的，改为自己的token，就一直error submit登陆不了

**Comment by PanJiaChen** [comment]
这个是demo，请根据自己的需求进行修改。

https://github.com/PanJiaChen/vue-element-admin/blob/1b394ae41757a91e7288820f8e3a24e561ff095a/src/mock/login.js#L25-L32
