### ISSUE TITLE
关于dialog的建议

### ISSUE THREAD

**Issue by mc7qing** [PanJiaChen/vue-element-admin#1450]
我用dialog来做添加/修改 有时候添加到一半需要查看其他地方的数据才能添加 这时候需要关闭dialog 或者新开一个页面来查看 体验非常不好 能否多一种选择 比如这种
![default](https://user-images.githubusercontent.com/33148552/50333572-bd17a500-0540-11e9-8b23-bb4b2d5ef3b0.png)

灰色部分只在红框内 这样可以从侧边栏或者顶部切换到别的tagsview 再切回来

不知道能否这样做... 本人后端一枚 

最后感谢作者提供这么好用的后台集成解决方案

**Comment by PanJiaChen** [comment]
本项目本身就支持你说的东西。

现在你的问题是怎么解决 element-dialog 怎么点击其它空白地方或者元素不关闭 dialog。

加上 ` :modal="false" :close-on-click-modal="false"	:lock-scroll="false"`
并且找到 dialog的 `el-dialog__wrapper` 将它的的 z-index 调低。
