### ISSUE TITLE
使用tinymce发现style_formats无法设置

### ISSUE THREAD

**Issue by beausoft** [PanJiaChen/vue-element-admin#1452]
引入tinymce，不管有没有设置 style_formats，格式下拉框都是空的

![_20181223130338](https://user-images.githubusercontent.com/9295882/50380921-320aec00-06b3-11e9-8a79-28108ab92b1d.png)

**Comment by PanJiaChen** [comment]
移除 importcss plugin 就好了。
https://github.com/PanJiaChen/vue-element-admin/commit/a56145509d25ce16adfba9d4419f5b1fcc173f2c

**Comment by beausoft** [comment]
好的，稍后试试，谢谢。
