### ISSUE TITLE
怎样使用原生的 XMLHTTPRequest

### ISSUE THREAD

**Issue by imfht** [PanJiaChen/vue-element-admin#1453]
在vue-elemnt-admin 的页面创建 XMLHTTPRequest 发现返回的是 Mock 的对象
![image](https://user-images.githubusercontent.com/15059493/50391350-947cee80-077e-11e9-8fe8-2949ea59ac53.png)‘
请问怎样能够使用到原生的XMLHTTPRequest？
谢谢！

**Comment by PanJiaChen** [comment]
当前版本除了移除 mockjs 之外无解。

**Comment by imfht** [comment]
@PanJiaChen 谢谢。
