### ISSUE TITLE
ScrollPane无用代码和冗余代码

### ISSUE THREAD

**Issue by rainydayDY** [PanJiaChen/vue-element-admin#1457]
moveToTarget这个方法中，我认为cuurentTag为第一个和最后一个时，不用去遍历节点找preTag和nextTag，此外，visitedViews[i].length > 1，我认为是没有意义的，我不理解为什么要这样用，为什么要去判断当前节点的length，是undifined啊，还有不是很理解当currentTag为中间的tag时的移动的计算方式，期待您的reply

**Comment by PanJiaChen** [comment]
欢迎pr

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1460
