### ISSUE TITLE
vue 单页面的其中一个页面，有七八个接口，间隔十秒刷新，页面打开五个小时左右页面崩溃，在不用websocket的情况下，这个有木有解决办法

### ISSUE THREAD

**Issue by asxw00** [PanJiaChen/vue-element-admin#1458]

**Comment by fearlessfe** [comment]
在页面的销毁方法中清楚定时器没有？

**Comment by PanJiaChen** [comment]
我怎么知道为什么？

**Comment by EricShen-ESStudio** [comment]
这个问题，第一感觉还是因为你10s内发起的7、8个api返回不及时或者返回数据还没有处理完毕的情况下，又开始了下一个10s的逻辑操作。
原则上从如下角度分析：

1. 10s内发起新一轮api调用时，确认一定要清除掉定时器（10s不一定就是10s，又可能>10s或者<10s，导致定时器出错，进而随着时间增长倒是内存暴增）

1. 确保7、8个api中没有存在变量未释放或置空的情况；

1. 考虑业务模式，启用websocket。

至少可以确认的是，你代码中肯定存在变量为置空或者未回收导致内存泄露！
