### ISSUE TITLE
页面一直报错，不明所以

### ISSUE THREAD

**Issue by Aopodo** [PanJiaChen/vue-element-admin#1461]
![image](https://user-images.githubusercontent.com/16433585/50421207-bb6b1b80-0877-11e9-97d3-6862995e1932.png)
![image](https://user-images.githubusercontent.com/16433585/50421221-d9388080-0877-11e9-922d-3fd4543233cd.png)

如上图，项目一启动就一直报错，但是我并未使用websocket，不明白什么情况，有办法关闭么？

**Comment by surahe** [comment]
将disableHostCheck 设置为true试下，我2部电脑一个不需要设置，另一部不设置的话也会出现这种情况，不清楚为什么

**Comment by Aopodo** [comment]
> 将 webpack.dev.config.js 的 devServer 添加参数 disableHostCheck 设置为 true 试下，我2部电脑一个不需要设置，另一部不设置的话也会出现这种情况，不清楚为什么
> 
> ```
>   // ...
>   devServer: {
>      // ...
>      disableHostCheck: true
>   },
>   // ...
> ```

可以了！
