### ISSUE TITLE
TabsView点击刷新

### ISSUE THREAD

**Issue by tianfuhou** [PanJiaChen/vue-element-admin#1464]
您好
看之前的issue说3.0以后，已经修复了TabsView点击会刷新的问题，为什么包含您的演示地址在内，点击TabsView还是每次都会刷新呢？

**Comment by PanJiaChen** [comment]
请具体说明。

**Comment by tianfuhou** [comment]
您好，就是快捷导航TabsView，打开多个页面时，在标签栏上切换，怎么设置它，点击时不刷新页面？

**Comment by tianfuhou** [comment]
> 请具体说明。

您好，就是快捷导航TabsView，打开多个页面时，切换页签，不要刷新页面

**Comment by PanJiaChen** [comment]
所以现在哪个页面刷新了？

**Comment by tianfuhou** [comment]
> 所以现在哪个页面刷新了？

![image](https://user-images.githubusercontent.com/16412365/50441554-3a268e00-0936-11e9-8109-5859718f268a.png)
我同时打开角色管理和车企管理，如果在车企管理页面填写了一些数据，点tab切换到角色管理，再切回到车企管理，车企管理页面全部刷新了，填写的数据也会丢失。怎么设置才会保持缓存呢？

**Comment by PanJiaChen** [comment]
请自行看文档 
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/tags-view.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
