### ISSUE TITLE
asyncRouterMap 怎么样用过异步加载的方式动态获取？

### ISSUE THREAD

**Issue by hoosin** [PanJiaChen/vue-element-admin#147]
假如我路由是动态来获取的，怎么样会方便一点？

**Comment by WiXiM** [comment]
你指的是从后端接口获取？现在vue-element-admin的逻辑是，后端接口给角色数组“roles”，通过router里的meta标签来确认，该用户是否有权限访问该路由。实际和后端通信环境下，后端会再次验证权限。

**Comment by PanJiaChen** [comment]
asyncRouterMap你可以在 `getInfo` 中返回咯[代码](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/main.js#L52) 我文章里也有写，权限map放在后端也是可以的，原理都一样的。

**Comment by hoosin** [comment]
@PanJiaChen 文章链接能看看吗？谢谢

**Comment by PanJiaChen** [comment]
https://segmentfault.com/a/1190000009506097

**Comment by hoosin** [comment]
@PanJiaChen 多谢
