### ISSUE TITLE
Google浏览器点击全屏按钮控制台报错

### ISSUE THREAD

**Issue by tangcaiyue** [PanJiaChen/vue-element-admin#1470]
Google浏览器点击全屏报错：
screenfull.js:97 Uncaught (in promise) TypeError: Failed to execute 'requestFullscreen' on 'Element': parameter 1 ('options') is not an object.
    at Object.request (screenfull.js:97)
    at Object.toggle (screenfull.js:107)
    at VueComponent.click (index.vue?c52b:64)
    at invoker (vue.runtime.esm.js:2023)
    at SVGSVGElement.fn._withTask.fn._withTask (vue.runtime.esm.js:1822)
然后查看源代码发现是elem[request](keyboardAllowed && Element.ALLOW_KEYBOARD_INPUT);这行报错，但是在浏览器的控制台执行document.documentElement的requestFullscreen方法可以实现全屏
源码如下：
request: function (elem) {
			var request = fn.requestFullscreen;

			elem = elem || document.documentElement;
			// Work around Safari 5.1 bug: reports support for
			// keyboard in fullscreen even though it doesn't.
			// Browser sniffing, since the alternative with
			// setTimeout is even worse.
			if (/ Version\/5\.1(?:\.\d+)? Safari\//.test(navigator.userAgent)) {
				elem[request]();
			} else {
                               //源码中调试代码跑到这个else了，不知道为啥这样做，而且报错了
				elem[request](keyboardAllowed && Element.ALLOW_KEYBOARD_INPUT);
			}
		},

**Comment by PanJiaChen** [comment]
`screenfull`更新到 3.3.3
