### ISSUE TITLE
发布后的chunk-  主要js文件太大，达到1.2m以上，怎么优化？

### ISSUE THREAD

**Issue by zky86** [PanJiaChen/vue-element-admin#1472]
发布后的chunk-  主要js文件太大，达到1.2m以上，怎么优化？
怎么压缩小一点？或者怎么分开几份小一点的js？
另外，有什么办法可以一开始整站加一个loading，等主要js加载完毕关闭loading，让用户在打开时候，由于白屏等待的时候过渡体验好一点。

**Comment by PanJiaChen** [comment]
https://juejin.im/post/5b5d6d6f6fb9a04fea58aabc
