### ISSUE TITLE
npm run dev 为什么不能监控文件的实时变化并更新到网页上？

### ISSUE THREAD

**Issue by robin521111** [PanJiaChen/vue-element-admin#1476]
我试着在package.json 的 dev 节点中添加了 --watch 参数，但是仍然需要每次做完修改之后再重新运行npm run dev 打开新的页面查看结果。而这个过程非常慢， 大概需要30秒。

**Comment by PanJiaChen** [comment]
确定一下node版本 和什么操作系统？

**Comment by robin521111** [comment]
谢谢，因为webpack版本的问题。重新安装之后解决了。
