### ISSUE TITLE
为什么原生axios可以，系统自带post就是不行，

### ISSUE THREAD

**Issue by jimGJW** [PanJiaChen/vue-element-admin#1478]
axios({
          method: 'post',
          url: url,
          data: param
        }).then(res => {
        })

        return

        fetchPostList(url, params).then(res => {
        })

两个传递的param=[{},{},{}]
但是就是自带的post 请求无法成功

想问下原因

**Comment by PanJiaChen** [comment]
谁知道你 `fetchPostList` 怎么写的

**Comment by jimGJW** [comment]
export function fetchPostList(url,query) {
  return request({
    url:  url,
    method: 'post',
    params: query
  })
}

**Comment by PanJiaChen** [comment]
```diff
export function fetchPostList(url,query) {
  return request({
    url:  url,
    method: 'post',
-   params: query
+   data: query
  })
}
```
