### ISSUE TITLE
侧边栏会自动刷新，收起

### ISSUE THREAD

**Issue by Ttxy0105** [PanJiaChen/vue-element-admin#148]
在localhost下，点击切换路由时，侧边栏不会刷新；
但是打包出来后，点击切换路由，侧边栏会刷新，都会先收回，再展开

**Comment by PanJiaChen** [comment]
@Ttxy0105  这个bug有点诡异，暂时没知道原因

**Comment by craftsman-li** [comment]
我打包以后也会刷新一下，是什么问题呢？？？

**Comment by PanJiaChen** [comment]
已修复

**Comment by PanJiaChen** [comment]
相关commit https://github.com/PanJiaChen/vue-element-admin/commit/391e7703ed137e3ee17df16d41fc215e31731af9
