### ISSUE TITLE
npm 安装失败

### ISSUE THREAD

**Issue by ZenoJHZhang** [PanJiaChen/vue-element-admin#1486]
版本如图：

![15464095716916](https://user-images.githubusercontent.com/31884789/50581898-ec130c80-0e98-11e9-8b3b-bf38b3d239c9.png)

错误如下：
![image](https://user-images.githubusercontent.com/31884789/50581916-0f3dbc00-0e99-11e9-97f4-4907bbe75b7b.png)

请问如何解决，谢谢！

**Comment by JamesDream87** [comment]
以后尽量自己Google一下 exited with error code :128，以下是链接地址
[https://stackoverflow.com/questions/50969217/npm-err-exited-with-error-code-128](url)
