### ISSUE TITLE
修改布局后样式的问题

### ISSUE THREAD

**Issue by Jaydenz** [PanJiaChen/vue-element-admin#1487]
![2019-01-02 143020](https://user-images.githubusercontent.com/21174651/50582123-21b8f500-0e9b-11e9-9260-351b026a136e.jpg)
改了布局之后这里出现一条白色细线，请问相关css在哪定义的，找了半天没找到

**Comment by Jaydenz** [comment]
>           不知道你新的布局是怎么样的，原布局navbar下面tags-view-container有一个box-shadow属性是给navbar和tags-view-container中间加了一个灰白色阴影，我想应该是这个吧

这个tags-view组件被我去掉了的，找了一下box-shadow并没有发现相关属性

**Comment by PanJiaChen** [comment]
我咋知道你改了布局，写了啥。如果有问题，请提供一个在线可调试demo.
