### ISSUE TITLE
npm install 出错

### ISSUE THREAD

**Issue by likunru** [PanJiaChen/vue-element-admin#1488]
>npm install
npm WARN npm npm does not support Node.js v7.9.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/sohee-lee7/Squire.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ThinkPad\AppData\Roaming\npm-cache\_logs\2019-01-02T06_56_32_898Z-debug.log

**Comment by godIsAProgrammer** [comment]
先卸载 npm:    $ npm uninstall -g npm    然后在重新安装node。

**Comment by likunru** [comment]
> 先卸载 npm: $ npm uninstall -g npm 然后在重新安装node。

这个是因为node版本问题造成的吗

**Comment by godIsAProgrammer** [comment]
> > 先卸载 npm: $ npm uninstall -g npm 然后在重新安装node。
> 
> 这个是因为node版本问题造成的吗

看了报错信息，应该是这个问题。

**Comment by likunru** [comment]
> > > 先卸载 npm: $ npm uninstall -g npm 然后在重新安装node。
> > 
> > 
> > 这个是因为node版本问题造成的吗
> 
> 看了报错信息，应该是这个问题。�

上面那个版本信息那个是警告，报错的是这个：
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/sohee-lee7/Squire.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

**Comment by focusdada** [comment]
同样的问题

**Comment by PanJiaChen** [comment]
自己Git环境变量的问题。
https://juejin.im/post/5b1f31f7f265da6e1a603e1e

自己把错误搜索一下 就有解决方案了。

**Comment by GaoXuelLiang** [comment]
> 先卸载 npm: $ npm uninstall -g npm 然后在重新安装node。
> 
> 这个是因为node版本问题造成的吗
> 
> 看了报错信息，应该是这个问题。�
> 
> 上面那个版本信息那个是警告，报错的是这个：
> npm ERR! code ENOGIT
> npm ERR! Error while executing:
> npm ERR! undefined ls-remote -h -t ssh://git@github.com/sohee-lee7/Squire.git
> npm ERR!
> npm ERR! undefined
> npm ERR! No git binary found in $PATH
> npm ERR!
> npm ERR! Failed using git.
> npm ERR! Please check if you have git installed and in your PATH.
请问解决了没 盼回
