### ISSUE TITLE
请教一个关于vue-router中的别名alias的问题

### ISSUE THREAD

**Issue by moxuanluo** [PanJiaChen/vue-element-admin#1489]
大神您好，在学习您的教程时，
我在vue-router的index.js文件中，编写了router路径代码如下
//不需要权限 就可进入的页面
export const constantRouterMap = [
    {
        path: '/redirect',
        component: () => import('@/views/layout/layout'),
        alias: '/redirect123123',
        hidden: true,
        type: "menu",
        children: [
          {
            path: '/login',
            component: () => import('@/views/login/login'),
            alias: '/redirect123123'
          }]
    }
]
//只抛出 不需要权限 就可进入的页面router
export default new Router({
    // mode: 'history', // require service support
    scrollBehavior: () => ({ y: 0 }),
    routes: constantRouterMap,
})

在项目运行后，发现 别名alias的配置没有起任何作用，
尝试百度一下后，没有解决这个问题，
只好来问问大神，需要如何设置alias才能起作用

**Comment by PanJiaChen** [comment]
https://webpack.docschina.org/configuration/resolve/#resolve-alias

你大概率没有重启项目吧，这种配置要重启才能生效。

**Comment by Mr-xzq** [comment]
我也遇见这个问题了， 但是大神好像回答的不是这个问题，楼主说的是vue-router的alias没有生效的问题，大神回答的是webpack的alias的问题。
