### ISSUE TITLE
addRoutes之后可以访问，但是侧边栏不更新

### ISSUE THREAD

**Issue by cms631083639** [PanJiaChen/vue-element-admin#1491]
1、我用的是简单模板，
2、在store 复制了复杂模板的 store/modules/permission.js 并在getter里新增了俩个属性
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters；
3、然后在store/modules/user.js  的GetInfo的promise里resolve()了一个固定的对象
           {
              code: 20000,
              data: {
                avatar:
                  'https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif',
                name: 'admin',
                roles: ['super_editor']
              }
            }
4、之后在src/permission.js 里 通过router.addRoutes(store.getters.addRouters)，动态添加路由
5、①登陆②侧边栏没有权限测试页③可以手动修改路由进入权限测试页④权限测试页，页面是空的⑤这里我理解为addRoutes成功了，但是页面并没有在侧边栏更新出来。
6、不好意思，由于一直提示图片上传失败，我只能用描述的，不知道能不能看懂

**Comment by cms631083639** [comment]
我也不知道为什么可以 手动修改路由进入http://localhost:9529/#/permission  ，但是页面中没有任何东西 <section data-v-6beed8bc="" data-v-60f35ab6="" class="app-main"></section>  是空的

**Comment by cms631083639** [comment]
我也不知道为什么可以 手动修改路由进入http://localhost:9529/#/permission ，但是页面中没有任何东西

是空的<section data-v-6beed8bc="" data-v-60f35ab6="" class="app-main"></section>

**Comment by cms631083639** [comment]
解决了，在layout/components/SideBar/index.vue 也复制过来就行了

**Comment by godIsAProgrammer** [comment]
> 1、我用的是简单模板，
> 2、在store 复制了复杂模板的 store/modules/permission.js 并在getter里新增了俩个属性
> permission_routers: state => state.permission.routers,
> addRouters: state => state.permission.addRouters；
> 3、然后在store/modules/user.js 的GetInfo的promise里resolve()了一个固定的对象
> {
> code: 20000,
> data: {
> avatar:
> 'https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif',
> name: 'admin',
> roles: ['super_editor']
> }
> }
> 4、之后在src/permission.js 里 通过router.addRoutes(store.getters.addRouters)，动态添加路由
> 5、①登陆②侧边栏没有权限测试页③可以手动修改路由进入权限测试页④权限测试页，页面是空的⑤这里我理解为addRoutes成功了，但是页面并没有在侧边栏更新出来。
> 6、不好意思，由于一直提示图片上传失败，我只能用描述的，不知道能不能看懂

可以通过 localstorage 去维护侧边栏。
