### ISSUE TITLE
page分页组件的page从1开始，如何改写?

### ISSUE THREAD

**Issue by zyyanzi** [PanJiaChen/vue-element-admin#1492]
后台接口请求参数要求 page:0 limit:10
page分页组件和饿了么 ui里的分页标签 page =1，无法自定义，导致每次传到后台的为1，咋办。

**Comment by mu-yu** [comment]
方法1：手动减一
方法2：computed
方法3：让后端改😆

**Comment by zyyanzi** [comment]
> 方法1：手动减一
> 方法2：computed
> 方法3：让后端改😆

手动减一不行，试过啦，分页插件还是每次都会提交page =1 。谢谢 我试试2

**Comment by Chasers9527** [comment]
我是写PHP的。。说实话 page 为0开始 而且是强制要求的。。。就过分了。。。我们的都是从1开始的 。。。建议后端改

**Comment by mu-yu** [comment]
你可以在提交的时候手动减一。@zyyanzi

**Comment by zyyanzi** [comment]
> 你可以在提交的时候手动减一。@zyyanzi

提交时减一了，可插件还是改为1啦

**Comment by zyyanzi** [comment]
> 我是写PHP的。。说实话 page 为0开始 而且是强制要求的。。。就过分了。。。我们的都是从1开始的 。。。建议后端改

改造老系统，原来的逻辑不变哈

**Comment by Chasers9527** [comment]
@zyyanzi  这个吧？
![Uploading image.png…]()

**Comment by PanJiaChen** [comment]
前台交互上肯定是从1还是的。
