### ISSUE TITLE
mock/index.js 中怎么添加id的参数

### ISSUE THREAD

**Issue by Chasers9527** [PanJiaChen/vue-element-admin#1493]
在 restful 设计中，更新数据使用的是 `patch` 方法，id 参数需要放在链接中，怎样在 `mock/index.js` 中设计 patch 方法的链接并在参数中带入 `id`
我暂时使用了如下的修改：

```javascript
Mock.mock(/\/users\/visitor\/*/, 'patch', usersAPI.updateVisitor)
```
调用 url 地址为 `/users/visitor/1`  但是不知道在 `updateVisitor` 方法中如何获取这个 id

MockJs 好像无法设计 RestFul 的 API吧~ 求助

**Comment by likunru** [comment]
import { param2Obj } from '@/utils'
updateVisitor:  (config) => {
    const {id} = param2Obj(config.url)
}

**Comment by PanJiaChen** [comment]
`mockjs` 的 回调参数中只会 `url`、`type` 和 `body` 三个属性。所以你只能手动对 `url`进行正则筛选出的 `id`。
