### ISSUE TITLE
希望可以像ant pro那样通过配置修改整体风格和导航样式

### ISSUE THREAD

**Issue by cqzongjian** [PanJiaChen/vue-element-admin#1495]
![image](https://user-images.githubusercontent.com/24648402/50753873-822aa680-128e-11e9-9cc4-1edb254c329d.png)
如上图，期待能加入这个功能！

**Comment by PanJiaChen** [comment]
4.0版本正在做这件事。

**Comment by chenweibo** [comment]
@PanJiaChen  大佬 4.0什么时候大体上完成

**Comment by PanJiaChen** [comment]
已发布。
