### ISSUE TITLE
token添加问题，Access-Control-Request-Headers: x-token

### ISSUE THREAD

**Issue by XguangY** [PanJiaChen/vue-element-admin#1496]
![1546847015](https://user-images.githubusercontent.com/31021895/50755457-092e4d80-1294-11e9-8def-6532cc580034.png)
使用上图中的拦截器，实际请求头中是这样的，看下图：
![1546847632 1](https://user-images.githubusercontent.com/31021895/50755602-780ba680-1294-11e9-8e3e-0eb6f5d8dd59.png)
大佬们怎么看，挺急的

**Comment by XguangY** [comment]
另外说一句这个是我用动态路由的那个模板分支，permission-control
之前用的那个webpack3 分支是正常的可以用这个方法修改请求头

**Comment by zhengjunren** [comment]
请问您是怎么解决的呀

**Comment by sunpu007** [comment]
看一下警告信息`provisional header are shown`，跨域请求被拦截了，并没有发出去，可以看下你是否是你安装的扩展程序引起的
