### ISSUE TITLE
本地运行和线上部署登陆页面不显示

### ISSUE THREAD

**Issue by chenzhangwei** [PanJiaChen/vue-element-admin#1498]
![_20190107162904](https://user-images.githubusercontent.com/24539195/50757332-e868f680-1299-11e9-9caf-e32e44407e5d.png)
![_20190107163120](https://user-images.githubusercontent.com/24539195/50757333-e9018d00-1299-11e9-83b7-fe7ecc66d5bf.png)
如图所示，本地加载login页面不显示，里面没有任何内容，需要清理一次浏览器缓存后刷新页面才显示登陆内容，请问是什么回事呢？

**Comment by JamesDream87** [comment]
能看一下代码吗？估计是router或者是permission的问题。你查一下这两个文件先
