### ISSUE TITLE
[Bug Report] Name of some sidebar menu does not display

### ISSUE THREAD

**Issue by zhenzou** [PanJiaChen/vue-element-admin#150]
## Version 
v1.2.0

## OS/Browser
Ubuntu 16.04/Chrome 60.0.3112.90

## Problem
Name of some sidebar menu does not show,like this. It's ok in V1.1.1 .
![image](https://user-images.githubusercontent.com/7829073/28996771-d38d6868-7a38-11e7-8f15-a4e679ce743e.png)

**Comment by PanJiaChen** [comment]
我在Ubuntu 17.04  Chrome 60.0.3112.90 实测并无上述问题，所以不太能定位问题所在。

**Comment by iedwin** [comment]
我在macOS 10.12.6, Chrome(Version 59.0.3071.115 (Official Build) (64-bit))下也遇到了相同的问题。同问题主，v1.1.1是没问题的

**Comment by zhenzou** [comment]
After some more test, I believe the bug comes with  this [commit](https://github.com/PanJiaChen/vue-element-admin/commit/dd9ef5145dad4a7ee44c5a5bf6d72bc474755c43)

**Comment by zhenzou** [comment]
测试了一下，把SideBarItem组件的第7行的slot="title"删掉就正常了，只是不知道有什么其他影响。

**Comment by PanJiaChen** [comment]
@zhenzou https://jsfiddle.net/b1mg9mL1/
看看这个demo有问题吗？

**Comment by zhenzou** [comment]
@PanJiaChen 没问题。。

**Comment by PanJiaChen** [comment]
反正我先把slot去掉吧 这里slot本来就是冗余的

**Comment by PanJiaChen** [comment]
@zhenzou 线上我更新了 能看看还有问题吗？

**Comment by zhenzou** [comment]
@PanJiaChen 可以了。

**Comment by PanJiaChen** [comment]
@zhenzou 这问题比较诡异。。。应该是css的问题，但由于我这里不能重现所以比较难以定位问题。
感谢提出并解决了问题:thumbsup:
