### ISSUE TITLE
执行   npm install --registry=https://registry.npm.taobao.org

### ISSUE THREAD

**Issue by zengnanhua** [PanJiaChen/vue-element-admin#1500]
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and
ew features!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support
pmjs.com for more info.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only,
atted is its successor.
npm ERR! code 128
npm ERR! Command failed: C:\Program Files\Git\mingw64\bin\git.EXE submodule up
te -q --init --recursive
npm ERR! fatal: 'submodule' appears to be a git command, but we were not
npm ERR! able to execute it. Maybe git-submodule is broken?
npm ERR!

**Comment by JamesDream87** [comment]
Google一下Npm ERR code 128.自然有答案
[https://blog.csdn.net/u014182690/article/details/78598769](url)
