### ISSUE TITLE
模板中不能直接写img标签吗，eslint校验不通过，该怎么显示图片

### ISSUE THREAD

**Issue by zhangshuzhen** [PanJiaChen/vue-element-admin#1504]

**Comment by PanJiaChen** [comment]
请贴出你的代码和错误提示。

**Comment by zhangshuzhen** [comment]
✘  https://google.com/#q=vue%2Fhtml-self-closing  Disallow self-closing on HTML void elements (<img/>)
  src/views/login/index.vue:36:9
          <img :src="captchaUrl" class="get-code" @click="getCode"/>



就写了个img标签，控制台一直编译提示错误，其实是生效的

**Comment by PanJiaChen** [comment]
你能截图么，通过代码没看出什么问题。

**Comment by zhangshuzhen** [comment]
![default](https://user-images.githubusercontent.com/3645554/50891771-0b311180-1438-11e9-9833-8b11a23f1551.png)
想显示一个图片，校验一直不通过

**Comment by PanJiaChen** [comment]
`<img :src="captchaUrl" class="get-code" @click="getCode">`

**Comment by zhangshuzhen** [comment]
原来要去掉斜杠，非常感谢，对eslint不熟
