### ISSUE TITLE
chunkFilename中的name，被自动分配为id了，想要自己独自命名是否可以

### ISSUE THREAD

**Issue by sunlanlisa** [PanJiaChen/vue-element-admin#151]
chunkFilename中的name，被分配为id了，我想要自己独自命名是否可以？ 比如
搜索找到了这个 https://github.com/webpack/webpack/issues/1610 ，但是不知道怎么应用到咱们这个项目中

**Comment by sunlanlisa** [comment]
已经解决

**Comment by tailgo** [comment]
能说说是怎么解决的吗
