### ISSUE TITLE
mock的真实数据格式，哪位大佬能贴一份出来么

### ISSUE THREAD

**Issue by hahadaxia** [PanJiaChen/vue-element-admin#1510]

**Comment by hahadaxia** [comment]
想把数据放到数据库里面测试一下

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/tree/master/src/mock

源代码都有了。

**Comment by hahadaxia** [comment]
> https://github.com/PanJiaChen/vue-element-admin/tree/master/src/mock
> 
> 源代码都有了。
本人初学， 现在是拿着vue-element-template的模版在开发，template数据是easymock模拟的，都可以抓包，我将真实数据按照你的格式封装后入库即可。目前想（尽量不想改你的vue-element-admin代码）把我的数据继续在你admin里面的complextable展现，按这个思路是不是会快一点。所以直接想拿到你的admin里面的所有数据格式，后面我想展现的数据，就全按你目前admin 的格式封装了。

**Comment by hahadaxia** [comment]
> https://github.com/PanJiaChen/vue-element-admin/tree/master/src/mock
> 
> 源代码都有了。

本人初学， 现在是拿着vue-element-template的模版在开发，template数据是easymock模拟的，都可以抓包，我将真实数据按照你的格式封装后入库即可。目前想（尽量不想改你的vue-element-admin代码）把我的数据继续在你admin里面的complextable展现，按这个思路是不是会快一点。所以直接想拿到你的admin里面的所有数据格式，后面我想展现的数据，就全按你目前admin 的格式封装了。

**Comment by hertough** [comment]
你完成了吗，登录格式是怎么样的，我登录不报错就是不跳转

**Comment by hahadaxia** [comment]
明天我贴出来

发自我的 iPhone

**Comment by Jorian93** [comment]
我也是吧admin的组件拉过来，但是数据格式对不上，登录返回的数据20000，admin，但是提示error不跳转

**Comment by hahadaxia** [comment]
{password: "admin",username: "admin"}
---python后端代码
class Userlogin(Resource):
    def get(self):
        data = {"code": CODE, "data": {"token": "admin"}}
        return jsonify(data)

**Comment by PanJiaChen** [comment]
4.0版本 所以mock数据都可以在 dev环境下通过 network 查看到了。
