### ISSUE TITLE
在文章列表中点击进入详情页，怎样才能不打开新标签，而是在原有的标签页打开

### ISSUE THREAD

**Issue by chengxianyi** [PanJiaChen/vue-element-admin#1511]

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/51025899-334f7a80-15c8-11e9-9188-2d90ba14ae77.png)

你指这个地方？

**Comment by chengxianyi** [comment]
> ![image](https://user-images.githubusercontent.com/8121621/51025899-334f7a80-15c8-11e9-9188-2d90ba14ae77.png)
> 
> 你指这个地方？

是的

**Comment by zhangxiequan** [comment]
可以在列表页使用模态框弹出详情信息，这样就能避免多一个tab

**Comment by chengxianyi** [comment]
> 请问你这个解决了吗？

我现在是直接把列表页与详情页写在了一个页面，详情页作为组件在列表页引入
