### ISSUE TITLE
客户端长时间不操作页面,会导致OPTIONS预检请求或其他请求变慢5-8s左右

### ISSUE THREAD

**Issue by SmileFacehhh** [PanJiaChen/vue-element-admin#1512]
初步排查前端请求一直没法出去,后端执行响应速度很快,所以认为可能在跨域、请求头上问题

登录用的jwt机制,变慢后重启浏览器可短暂解决问题,求大佬帮看,解决根本问题,以下图片axios cors jwt过滤器配置

![image](https://user-images.githubusercontent.com/34115282/51025290-94764e80-15c6-11e9-8188-55639fc413c3.png)
![image](https://user-images.githubusercontent.com/34115282/51025313-a5bf5b00-15c6-11e9-9535-4cebb3a2f843.png)
![image](https://user-images.githubusercontent.com/34115282/51025377-ce475500-15c6-11e9-9fab-3505f5c6e573.png)

**Comment by PanJiaChen** [comment]
你先看看是所以浏览器还是只有chrome？

**Comment by SmileFacehhh** [comment]
这几天测试下来edge长时间开着应用程序不会卡,chrome大概一小时左右请求会变慢

**Comment by PanJiaChen** [comment]
https://stackoverflow.com/questions/46218440/super-slow-preflight-options-in-chrome-only
