### ISSUE TITLE
关于局部刷新的问题

### ISSUE THREAD

**Issue by linrong** [PanJiaChen/vue-element-admin#1513]
你好，我使用的是vue-admin-template版本，我在顶部处新增加了一个el-select控件，我希望可以通过选择el-select来实现局部更新AppMain组件,因为vue-admin-template版本中并没有这个功能，但我发现vue-element-admin中实现了这个功能，就是在首页点击顶部的布局大小按钮进行选择时会刷新AppMain，我去代码里面寻找却没有找到对应的代码，所以希望可以告诉一下我实现代码或者提供一些思路，非常感谢！！

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/c54e99d0a9c9a5ec18300ad60409b8b444771cd9/src/components/SizeSelect/index.vue#L39

https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/redirect/index.vue

等于是会重定向导一个redirect页面之后再重定向回来，这样就刷新了AppMain组件。当然 你要在AppMain 上一个key。

https://github.com/PanJiaChen/vue-element-admin/blob/c54e99d0a9c9a5ec18300ad60409b8b444771cd9/src/views/layout/components/AppMain.vue#L5

**Comment by chenjing0823** [comment]
我用了一个比较简单的方式实现AppMain区域的刷新。即通过v-if，个人觉得使用起来还是很方便。
首先在layout.vue 添加一个刷新的key`<wh-app-main v-if="isRefresh"></wh-app-main>`
然后再methods内写一个简单的方法
receive() {
      Vm.$on('is-refresh', (data) => {
        if (data === 1) {
          this.isRefresh = false
          this.$nextTick(() => {
            this.isRefresh = true
          })
        }
      })
    }（算是最简单的刷新方法了吧？）
记得在mounted内调用`mounted() {
    this.receive()
  }`
之后只要用到刷新该区域 只需要调用`Vm.$emit('is-refresh', 1)`即可 一劳永逸

Vm哪里来？此时每次刷新属于兄弟组件通信时 作为中介者创建一个event.js 内容如下
`const Vm = new Vue()
export default Vm`
 导包的时候import即可
（我直接放在main.js里）
