### ISSUE TITLE
在换肤功能中，如果点击清空颜色，但是没有再去选择颜色，下次换肤的时候oldVal为空，这样就会导致报错

### ISSUE THREAD

**Issue by GitACDreamer** [PanJiaChen/vue-element-admin#1516]
Error in callback for watcher "theme": "TypeError: Cannot read property 'replace' of null"
需要将清空按钮禁用或者 添加oldVal、val是否为空的判断

**Comment by GitACDreamer** [comment]
换肤成功后的那个图标本身没有变，其他的页面的控件颜色是变化了，其实是可以将theme的值用 vuex 的state管理起来，像改变控件大小的那个size字段一样

**Comment by PanJiaChen** [comment]
第一个问题：`如果点击清空颜色，但是没有再去选择颜色` 怎么清空颜色？没有这按钮啊。

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/1517
