### ISSUE TITLE
You may have an infinite update loop in a component render function. 

### ISSUE THREAD

**Issue by nattanlucena** [PanJiaChen/vue-element-admin#1518]
Hi, I've created a new role and set in routes.js, on each route. When I try to open the dashboard, throws the error:

`[Vue warn]: You may have an infinite update loop in a component render function.

found in

---> <SidebarItem> at src/views/layout/components/Sidebar/SidebarItem.vue
       <ElMenu>
         <ElScrollbar>
           <Sidebar> at src/views/layout/components/Sidebar/index.vue
             <Layout> at src/views/layout/Layout.vue
               <App> at src/App.vue
                 <Root> vue.runtime.esm.js:567
warn
vue.runtime.esm.js:567
flushSchedulerQueue
vue.runtime.esm.js:2877
nextTick/<
vue.runtime.esm.js:1779
flushCallbacks
vue.runtime.esm.js:1700
`

In my routes.js:

`{
    path: '/minhas-ordens',
    component: Layout,
    meta: { roles: ['USER'] },
    children: [
      {
        path: '',
        component: () => import('@/views/dashboard/user/index'),
        name: 'Ordens',
        meta: { title: 'Mnhas ordens', icon: 'poker_chip', roles: ['USER'] }
      }
    ]
  },`

Also, the menu doesn't render correctly.

**Comment by PanJiaChen** [comment]
I don't know if you have modified the code?

**Comment by nattanlucena** [comment]
Hi PanJiaCHen, 

I just modified the routes.js, with custom routes. The file sidebaritem.vue has the code bellow, with no changes:

`<template>
  <div v-if="!item.hidden && item.children" class="menu-wrapper">
    <template v-if="hasOneShowingChild(item.children, item) && (!onlyOneChild.children || onlyOneChild.noShowingChildren) && !item.alwaysShow">
      <app-link :to="resolvePath(onlyOneChild.path)">
        <el-menu-item :index="resolvePath(onlyOneChild.path)" :class="{'submenu-title-noDropdown':!isNest}">
          <item v-if="onlyOneChild.meta" :icon="onlyOneChild.meta.icon || item.meta.icon" :title="generateTitle(onlyOneChild.meta.title)" />
        </el-menu-item>
      </app-link>
    </template>

    <el-submenu v-else ref="submenu" :index="resolvePath(item.path)">
      <template slot="title">
        <item v-if="item.meta" :icon="item.meta.icon" :title="generateTitle(item.meta.title)" />
      </template>

      <template v-for="(child, index) in item.children" :index="index" v-if="!child.hidden">
        <sidebar-item
          v-if="child.children && child.children.length>0"
          :is-nest="true"
          :item="child"
          :key="child.path"
          :base-path="resolvePath(child.path)"
          class="nest-menu" />

        <app-link v-else :to="resolvePath(child.path)" :key="child.name">
          <el-menu-item :index="resolvePath(child.path)">
            <item v-if="child.meta" :icon="child.meta.icon" :title="generateTitle(child.meta.title)" />
          </el-menu-item>
        </app-link>
      </template>
    </el-submenu>

  </div>
</template>

<script>
import path from 'path';
import { generateTitle } from '@/utils/i18n';
import { isExternal } from '@/utils';
import Item from './Item';
import AppLink from './Link';
import FixiOSBug from './FixiOSBug';

export default {
  name: 'SidebarItem',
  components: { Item, AppLink },
  mixins: [FixiOSBug],
  props: {
    // route object
    item: {
      type: Object,
      required: true
    },
    isNest: {
      type: Boolean,
      default: false
    },
    basePath: {
      type: String,
      default: ''
    }
  },
  data() {
    return {
      onlyOneChild: null
    };
  },
  methods: {
    hasOneShowingChild(children, parent) {
      const showingChildren = children.filter(item => {
        if (item.hidden) {
          return false;
        } else {
          // Temp set(will be used if only has one showing child)
          this.onlyOneChild = item;
          return true;
        }
      });
      // When there is only one child router, the child router is displayed by default
      if (showingChildren.length === 1) {
        return true;
      }

      // Show parent if there are no child router to display
      if (showingChildren.length === 0) {
        this.onlyOneChild = { ...parent, path: '', noShowingChildren: true };
        return true;
      }

      return false;
    },
    resolvePath(routePath) {
      if (this.isExternalLink(routePath)) {
        return routePath;
      }
      return path.resolve(this.basePath, routePath);
    },
    isExternalLink(routePath) {
      return isExternal(routePath);
    },
    generateTitle
  }
};
</script>
`

**Comment by PanJiaChen** [comment]
I'm sorry, I can't reproduce your problem. 
Can you provide an online demo that can reproduce bug

**Comment by nattanlucena** [comment]
Hi, 

I change the function 'GenerateRoutes' in 'permission.js' (vuex) and that's ok now.

`GenerateRoutes({ commit }, data) {
      return new Promise(resolve => {
        const { roles } = data;
        const accessedRouters = filterAsyncRouter(asyncRouterMap, roles);

        commit('SET_ROUTERS', accessedRouters);
        resolve();
      });`
