### ISSUE TITLE
有个这个warning，loader应该是要修改什么吗，求助

### ISSUE THREAD

**Issue by sunlanlisa** [PanJiaChen/vue-element-admin#152]
DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

**Comment by PanJiaChen** [comment]
本项目现在没有这个warning了吧，它主要是一些第三方webpack插件导致了

**Comment by PanJiaChen** [comment]
太久没回复，先关闭
