### ISSUE TITLE
以后会切换到vue-cli 3模板么

### ISSUE THREAD

**Issue by liuchong1995** [PanJiaChen/vue-element-admin#1523]

**Comment by PanJiaChen** [comment]
会，4.0版本会使用vue-cli 3

**Comment by faxinter** [comment]
> 会，4.0版本会使用vue-cli 3

不知道什么时候发布，之前不是说年前么？

**Comment by wuxin1210** [comment]
大佬, 4.0什么时候发布呀

**Comment by qq1329705997** [comment]
用vue-cli 3 启动不了项目，一直会报
vue-element-admin@3.10.0 dev: `cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js "cross-env" "BABEL_ENV=development" "webpack-dev-server" "build/webpack.dev.conf.js"

**Comment by ZenoJHZhang** [comment]
大佬加油鸭

**Comment by jgsrty** [comment]
参考pan大神的2版本做的vue-cli3简易模板
接口用的easy-mock，，经常会502，接口不通的话把源码的请求改成本地
可以看看我这个整体的目录结构--有不足的望指点下
https://github.com/jgsrty/vue-cli3-jianshu

**Comment by cklwblove** [comment]
借助 `vue-cli3` 及 `typescript` 语法重构了此项目，有需要的，可以参考下，附上源码地址 [vue-element-admin-ts](https://github.com/cklwblove/vue-element-admin-ts)

**Comment by PanJiaChen** [comment]
已发布。
