### ISSUE TITLE
npm install 出错

### ISSUE THREAD

**Issue by weianmeng** [PanJiaChen/vue-element-admin#1526]
2905 verbose cwd D:\Code\Person\vue-element-admin
2906 verbose Windows_NT 10.0.17763
2907 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
2908 verbose node v10.13.0
2909 verbose npm  v6.4.1
2910 error Error while executing:
2910 error C:\Program Files\Git\cmd\git.EXE ls-remote -h -t git://github.com/adobe-webplatform/eve.git
2910 error
2910 error fatal: unable to look up github.com (port 9418) (Ӧ�ó���û�е��� WSAStartup������ WSAStartup ʧ�ܡ� )
2910 error
2910 error exited with error code: 128
2911 verbose exit [ 1, true ]

**Comment by PanJiaChen** [comment]
能把报错完整的截图一下么？

**Comment by weianmeng** [comment]
看了下其他人有遇到同样的问题，就重新安装了最新版本的git ，又安装了node-sass ，然后在npm install 就莫名奇妙的安装好了，可以关闭这个issue。
