### ISSUE TITLE
出个skeleton吧，搞的复杂繁乱了，什么组件都塞就

### ISSUE THREAD

**Issue by jiankian** [PanJiaChen/vue-element-admin#1529]

**Comment by PanJiaChen** [comment]
能具体说明一下诉求么？

**Comment by jiankian** [comment]
https://github.com/d2-projects/d2-admin-start-kit
就是一个基础骨架，其它功能按需添加，而不是按“不需”删除！

**Comment by PanJiaChen** [comment]
不就是 [vue-admin-template](https://github.com/PanJiaChen/vue-admin-template) 么
