### ISSUE TITLE
npn run dev 报错

### ISSUE THREAD

**Issue by yangJianWeb** [PanJiaChen/vue-element-admin#1532]
把改项目下载到本地之后解压，然后npm install 安装依赖之后在npm run dev结果报了下面的错误:
![image](https://user-images.githubusercontent.com/45889142/51291447-25737c80-1a42-11e9-9a81-3ee093400382.png)
之后尝试过几个方法：
1：以为是包依赖没有安装全，删除本地的node_module重新npm install.  依然报改错
2：百度了一下，以为是环境问题没有设置好，于是按照别人的解决方案尝试了一下，于是就先
   a:删除本地node_module
   b: npm install --global cross-env
   c: npm install --no-bin-links
   d: npm install --no-bin-links
但是依然没有解决该问题

**Comment by PanJiaChen** [comment]
你能吧你的错误信息自己去搜索一下为什么么。。。报错这么明显了

![image](https://user-images.githubusercontent.com/8121621/51291940-f100c000-1a43-11e9-9dcc-613224d82c37.png)

**Comment by yangJianWeb** [comment]
ok,已解决，thx.
