### ISSUE TITLE
el-checkbox-group 换行对齐问题

### ISSUE THREAD

**Issue by lirui9156** [PanJiaChen/vue-element-admin#1533]
裤衩老大，我用这个控件的时候发现第二行就开始不对齐了，不知道您发现没，还是说故意为之，我这边发现是.el-checkbox+.el-checkbox {
    margin-left: 30px;
}惹的祸，我试着改成margin-right: 30px;就ok了，控件显示没啥影响，暂时不知道其他地方会不会受到波及

**Comment by PanJiaChen** [comment]
https://github.com/ElemeFE/element/pull/14127

**Comment by PanJiaChen** [comment]
官方已合并。
等官方发版本就好了。
暂时你可以按照我demo里面那样hack。
