### ISSUE TITLE
怎么设置某些路由不在标签栏导航展示

### ISSUE THREAD

**Issue by chengxianyi** [PanJiaChen/vue-element-admin#1534]
如题，我需要从一个路由跳转到另一个路由，但是我不希望这个路由显示在快捷导航栏，而是在当前导航栏打开

**Comment by milklook** [comment]
修改一下源码，在路由的meta上多加个属性，类似：isVisited:false/true；
然后在store的ADD_VISTED_VIEW里去判断这个属性，true的就push，false则不处理

**Comment by grace618** [comment]
请问你实现了吗，怎么做的
