### ISSUE TITLE
IE11显示空白

### ISSUE THREAD

**Issue by Jackhyg001** [PanJiaChen/vue-element-admin#1535]
根据文档里的配置，我再webpack.base.conf.js做了一下修改
`module.exports = {
  context: path.resolve(__dirname, '../'),
  entry: {
    app: ['./node_modules/babel-polyfill/dist/polyfill.js', './src/main.js']
  },`

也在main.js引入了
import 'babel-polyfill';
package.js也有依赖
"dependencies": {
    "axios": "0.18.0",
    "babel-polyfill": "^6.26.0",

为啥我运行npm run dev IE下还是空白
IE只报这一个错
SCRIPT5022: [vuex] vuex requires a Promise polyfill in this browser.

**Comment by PanJiaChen** [comment]
使用姿勢不對，你的错误随手一百度就有答案了。
