### ISSUE TITLE
关于大文件上传的分片传输

### ISSUE THREAD

**Issue by zzguoxuefeng** [PanJiaChen/vue-element-admin#1536]
能整合进来一个大文件上传的VUE控件吗？支持文件的分片传输

**Comment by PanJiaChen** [comment]
你可以使 类似 https://github.com/lian-yue/vue-upload-component 这种 vue 上传组件。

本项目暂时应该不会增加类似demo。

**Comment by zhychao** [comment]
现在项目支持大文件上传了吗？支持分片上传这种组件
