### ISSUE TITLE
如何理解这个数据流？

### ISSUE THREAD

**Issue by jzendo** [PanJiaChen/vue-element-admin#1537]
![vue-element-admin-problem](https://user-images.githubusercontent.com/21156898/51434767-61f1e300-1ca3-11e9-95e6-daecd7a7ab7b.png)

上面这个现象，请问如何解释？
@PanJiaChen

**Comment by jzendo** [comment]
@PanJiaChen

**Comment by PanJiaChen** [comment]
这个其实和webpack的运行机制有关。
简而言之，就是执行`permission.js`的时候`constantRouterMap`并没有好。
`settimeout`因为已经是下一个loop了，所以能拿到。

**Comment by Debiancc** [comment]
为什么不在layout runtime的时候去判断有没有当前页面的权限，从而reject掉。
这样代码比较符合直觉

**Comment by jzendo** [comment]
我觉得不对，这个把ES6模块的概念 “模糊”了。

我有一种解决方法（如下），
main.js 里按这个顺序：
`
import store from './store'
import App from './App'
import router from './router'

`

**Comment by PanJiaChen** [comment]
你这改法其实本质区别不大，但的确是可以解决你的问题。
但其实为什么new vue之前知道 `constantRouterMap`知道的值呢？

**Comment by jzendo** [comment]
你看看我图里的那个**undefined**位置,  这个是你代码, 
我想你不是想要一个**undefined** . 代码里应该是**route array**.

**Comment by PanJiaChen** [comment]
因为你 console 的时候 vue 都没 init。 `undefined` 并不会有什么问题。

**Comment by jzendo** [comment]
我觉得你这样做会明显误导用户。

不建议，不如直接空数组

**Comment by PanJiaChen** [comment]
恩，的确不够优化。欢迎 pr。

**Comment by PanJiaChen** [comment]
Refine in https://github.com/PanJiaChen/vue-element-admin/commit/9daeb1cb340136fdbbec021fe20941a97dc41d5b

**Comment by huaiyue** [comment]
> 因为你 console 的时候 vue 都没 init。 `undefined` 并不会有什么问题。

console的时候 vue 都没 init，这个我理解。但如按着您的代码，真正项目跑起来时候，下面引用到constantRoutes时候，是空的，并不是希望的引入的已定义的一个数组，这是为什么呢？另外上面您说的webpack解析问题，我还是觉着有点奇怪，比如我先impirt router，再import store，store里调用router的变量，为啥会不行呢？我理解的是，import router后，它里面的变量应该都存在了，可以直接被其他文件引用了不是么？

**Comment by PanJiaChen** [comment]
我上面已经解释了 webpack import 的机制。你还是不理解，可以自己找一个小demo测一下。

**Comment by huaiyue** [comment]
好的呢~Thx




------------------ 原始邮件 ------------------
发件人: "花裤衩"<notifications@github.com>;
发送时间: 2019年5月13日(星期一) 中午11:41
收件人: "PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com>;
抄送: "淮"<935775694@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [PanJiaChen/vue-element-admin] 如何理解这个数据流？ (#1537)




我上面已经解释了 webpack import 的机制。你还是不理解，可以自己找一个小demo测一下。
