### ISSUE TITLE
web-pack-dev-server改成3.1.14后npm install出错

### ISSUE THREAD

**Issue by IEB-Richard** [PanJiaChen/vue-element-admin#1541]
我在Mac系统下，把webpack-dev-server升级到3.1.14后，然后完全删除node_modules，然后npm install会报错：

$ npm install
npm ERR! Unexpected end of JSON input while parsing near '...yl7lXIX2EBDAU9pAM7fSd'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2019-01-21T14_45_46_329Z-debug.log

把github的项目clone到本地，也不成，出现同样的错误。有遇到这个问题的吗？我现在只能把版本改回3.1.5，错误就没有了。

**Comment by PanJiaChen** [comment]
`npm cache clean --force`
之后重新安装。

**Comment by IEB-Richard** [comment]
多谢，已经解决！完整流程：

1. 先删除已经存在的node_modules
2. 删除package-lock.json
3. npm cache clean --force
4. npm install
