### ISSUE TITLE
表格分页绑定数据更新问题

### ISSUE THREAD

**Issue by wuweiminhuo** [PanJiaChen/vue-element-admin#1542]
![1](https://user-images.githubusercontent.com/13430122/51519778-e2a80f00-1e5c-11e9-8237-74f0134685ef.png)
![2](https://user-images.githubusercontent.com/13430122/51519783-e76cc300-1e5c-11e9-8a55-1e8362980a1d.png)
分页组件更新的limit值，在获取的时候没有刷新？是有缓存？

**Comment by PanJiaChen** [comment]
https://github.com/ElemeFE/element/pull/12530

更新 element-ui 版本 至 2.4.7 以上就能修复这个了。
