### ISSUE TITLE
Sticky 应用在隐藏/显示元素高度不会重新计算

### ISSUE THREAD

**Issue by xiaolong0612** [PanJiaChen/vue-element-admin#1549]
包裹Sticky的标签隐藏后在显示，Sticky高度为0

**Comment by PanJiaChen** [comment]
由于内部组件 是无法感知父组件的 v-show 的变化的，所以需要你在 v-show 变化的时候手动处理一下。

![image](https://user-images.githubusercontent.com/8121621/51652031-1f911480-1fc9-11e9-850a-3a79126fa032.png)

**Comment by xiaolong0612** [comment]
> 由于内部组件是无法感知父组件的v-show的变化的，所以需要你在v-show变化的时候手动处理一下。
> 
> ```js
> click（）{
>        this。show  =  ！这个。显示
>       这个。$ refs。粘的。重置（）
>     }
> ```
> 
> ps：[＃1550](https://github.com/PanJiaChen/vue-element-admin/pull/1550)更新一下代码

当应用在响应式布局中，无法使用事件的方式处理。例如:sm='0' :md='1'的元素下无法用事件的方式，可能我要想其它方式实现了

**Comment by PanJiaChen** [comment]
我又更新了下，你可以试试
https://github.com/PanJiaChen/vue-element-admin/commit/8ef6c7ee7dc7cd78ccbc2545a1ec29fad5243cee

**Comment by xiaolong0612** [comment]
谢谢大大
