### ISSUE TITLE
children路由，出现hidden为true，router动态添加父路由后，hidden为true的添加后跳转出现空白页，hidden为false的正常

### ISSUE THREAD

**Issue by tianlin95310** [PanJiaChen/vue-element-admin#1554]
![image](https://user-images.githubusercontent.com/24774290/51734167-ad026080-20be-11e9-9106-71e75947f9f5.png)

如图所示，这个是准备addRoutes的route，问题应该是出在，hidden为true的没有显示__ob__的属性出现空白界面的情形，而有__ob__的则是正常的

**Comment by PanJiaChen** [comment]
你确定有问题的 路由 `hidden` 改为 `false` 就没有问题了么？

**Comment by tianlin95310** [comment]
没有设置，默认为false

**Comment by tianlin95310** [comment]
> 你确定有问题的 路由 `hidden` 改为 `false` 就没有问题了么？

没有设置，默认为false

**Comment by tianlin95310** [comment]
> 你确定有问题的 路由 `hidden` 改为 `false` 就没有问题了么？

谢谢，找到问题了，是我的问题，你可以关闭了，感谢

**Comment by king-fang** [comment]
@tianlin95310 你好，我跟你一样遇到这样的问题，就是后台返回数据和前台map之后，侧边栏的展示全部正常，但是只要跳转就是空白的，请问您和我遇到的问题是一样么？
`
[
    {
        "path":"",
        "redirect":"",
        "component":"Layout",
        "name":"Permission",
        "hidden":false,
        "meta":{
            "title":"权限",
            "icon":"lock",
            "roles":[
                "admin"
            ]
        },
        "children":[
            {
                "path":"/admins",
                "redirect":"",
                "component":"admin",
                "name":"Admins",
                "hidden":false,
                "meta":{
                    "title":"管理员",
                    "roles":[
                        "admin"
                    ]
                }
            },
            {
                "path":"/roles",
                "redirect":"",
                "component":"role",
                "name":"Roles",
                "hidden":false,
                "meta":{
                    "title":"角色",
                    "roles":[
                        "admin"
                    ]
                }
            },
            {
                "path":"/menus",
                "redirect":"",
                "component":"menu",
                "name":"Menus",
                "hidden":false,
                "meta":{
                    "title":"菜单",
                    "roles":[
                        "admin"
                    ]
                }
            }
        ]
    }
]
`
前台
`
export const routerMap = {
  Layout:() => Layout,
  admin:()  => import('@/views/permission/admin'),
  role:()   => import('@/views/permission/role'),
  menu:()   => import('@/views/permission/menu'),
  pdf:()   => import('@/views/pdf/index')
}

`

**Comment by Marcabo** [comment]
> > 你确定有问题的 路由 `hidden` 改为 `false` 就没有问题了么？
> 
> 谢谢，找到问题了，是我的问题，你可以关闭了，感谢

你好.请问你的问题是怎样解决的呢.我现在也遇到了这个问题.动态添加的路由点击后空白
![Snipaste_2020-04-22_13-58-45.png](https://i.loli.net/2020/04/22/IL75M9qF62mvOwu.png)
![Snipaste_2020-04-22_13-59-13.png](https://i.loli.net/2020/04/22/zl6MVkovqR85NSJ.png)

**Comment by liwei478** [comment]
检查一下子路由里面的路径地址前面是否有加/
