### ISSUE TITLE
ubuntu 16.04 上安装依赖有warning，

### ISSUE THREAD

**Issue by pythonfirst** [PanJiaChen/vue-element-admin#1555]
win10 上用VMware虚拟机装的 ubuntu16.04，npm install 完成后有如下提醒，请问是什么原因？

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN script-ext-html-webpack-plugin@2.0.1 requires a peer of html-webpack-plugin@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

接下来 npm run dev 时报错

ERROR  Failed to compile with 1 errors                               6:25:51 PM

This dependency was not found:

* @/views/index/index in ./src/router/index.js

To install it, you can run: npm install --save @/views/index/index
请问是什么原因呢？

**Comment by PanJiaChen** [comment]
warning 可以忽略。
