### ISSUE TITLE
分页直接拿来用为什么显示是英文的

### ISSUE THREAD

**Issue by Pan-YP** [PanJiaChen/vue-element-admin#1556]
为什么我直接从vue-element-admin拿过来用的分页显示的不是中文而是英文的，我项目中并没有使用国计化语言包
![default](https://user-images.githubusercontent.com/31329779/51743343-56ede700-20d7-11e9-818b-bf8df744bef9.png)

**Comment by PanJiaChen** [comment]
http://element-cn.eleme.io/#/zh-CN/component/i18n

请将element-ui 的语言设成中文。
