### ISSUE TITLE
如何单独设置axios超时时间？

### ISSUE THREAD

**Issue by XiaoNode** [PanJiaChen/vue-element-admin#1558]
项目中统一的axios config中配置了超时时间，如何在一个单独接口中重置这个时间？

**Comment by daiing** [comment]
同问

**Comment by PanJiaChen** [comment]
https://github.com/axios/axios#request-config

文档写得很清楚了。

**Comment by Vicky000** [comment]
import axios from 'axios';
let ax = axios.create({timeout:300000});

**Comment by 0x3f97** [comment]
不是，配置axios不是全局的么，如果走封装的request，怎么给一个单独的接口设置超时啊0.0

**Comment by yuanjunming** [comment]
request.post('url', data, { timeout: 180000 })

**Comment by marklinglon** [comment]
import axios from 'axios';

export const CodeCommitCheckOnekeyDiff = (brancha,branchb) => axios.request({
    url: '/codecommit/onekey/checkdiff',
    method: 'get',
    params: {
        "token": process.env.VUE_APP_TOKEN,
        "brancha": brancha,
        "branchb": branchb
    },
    data: {},
    timeout: 30000000,
})

这样设置的超时时间，不生效，每到3分钟后，就又发送了一次请求
