### ISSUE TITLE
请问构建项目的时候 是怎么进行构建的  ？

### ISSUE THREAD

**Issue by johnsky123** [PanJiaChen/vue-element-admin#156]
从零开始构建一个后台管理系统   请问 是怎么样一步步搭起来的   有构建工具可以完成吗？

**Comment by PanJiaChen** [comment]
本项目只是一个后台集成方案，且本项目主要是是 vue-cli 的 [webpack-template](https://github.com/vuejs-templates/webpack) 搭建，所以构建可以参考官方文档就行。
