### ISSUE TITLE
和服务端进行交互问题

### ISSUE THREAD

**Issue by hertough** [PanJiaChen/vue-element-admin#1563]
为什么向服务器请求时请求的一直是9527端口呢，这里怎么改成请求后台端口，这里在请求自己前台自己的端口所以拿不到数据
，比如本地我想请求后台80端口，admin-vue-element自己是9527端口，我在dev.env.js设置了BASE_API和index.js里的proxyTable设置了 target。但是请求的还是9527端口怎么回事

**Comment by mixueer** [comment]
楼主的问题解决了吗？我也是遇到这个问题，想请教一下
