### ISSUE TITLE
两个不同的页面用同一个组件，连接websocket是数据会相互影响

### ISSUE THREAD

**Issue by qiulove** [PanJiaChen/vue-element-admin#1564]
我有两个页面，页面上获取不同的websocket信息，一个是获取全部的，一个是获取其中某一条的，但是当我两个页面同时打开时，一个页面在active状态，另一个不是，但是不是active状态的那个页面的数据会影响到active显示状态中的页面，切换不同页面显示默认不会触发beforeDestroy钩子函数的，这两个页面间的数据相互影响问题，怎么回事啊？求教

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/example/create.vue

你不用直接公用一个 component，如上面的例子，再包一层。很大可能性是 `keep-alive`导致的问题。

**Comment by qiulove** [comment]
> https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/example/create.vue
> 
> 你不要直接公用一个组件，如上面的例子，再包一层。很大可能性是`keep-alive`导致的问题。

找到了，不是keep-alive的问题，我自己定义了一个全局的属性的问题，自己搞死自己了，谢谢
