### ISSUE TITLE
可以给AppMain组件加上滚动吗

### ISSUE THREAD

**Issue by jave-joe** [PanJiaChen/vue-element-admin#1565]
目前主体滚动条是整体main-container下的所有组件上的
能不能只把滚动条放到app-main组件，从而navbar和tags-view在主体滚动的时候会悬浮

**Comment by wbc505357999** [comment]
AppMain.vue里面的样式改成这个就可以了
`
.app-main {
  /*84 = navbar + tags-view = 50 +34 */
  height: calc(100vh - 84px);
  width: 100%;
  position: relative;
  overflow-y: scroll;
}
`

**Comment by zhengzhibo** [comment]
> AppMain.vue里面的样式改成这个就可以了
> `.app-main { /*84 = navbar + tags-view = 50 +34 */ height: calc(100vh - 84px); width: 100%; position: relative; overflow-y: scroll; }`

overflow-y: auto;

**Comment by wbc505357999** [comment]
> > AppMain.vue里面的样式改成这个就可以了
> > `.app-main { /*84 = navbar + tags-view = 50 +34 */ height: calc(100vh - 84px); width: 100%; position: relative; overflow-y: scroll; }`
> 
> overflow-y: auto;

都ok

**Comment by PanJiaChen** [comment]
暂没这打算。
