### ISSUE TITLE
小屏幕下左侧菜单收缩后仍有菜单项残留

### ISSUE THREAD

**Issue by justforuse** [PanJiaChen/vue-element-admin#1567]
在小屏幕下，当选择某个菜单后鼠标立刻上移会有菜单仍然在屏幕上，需要加判断
![20190129184458](https://user-images.githubusercontent.com/11868477/51903008-42229380-23f6-11e9-8466-be04d1b6f7f5.png)

需要在小屏幕下设置menu的collapse为false,或者禁止menu的collapse动画

**Comment by PanJiaChen** [comment]
Fixed in  https://github.com/PanJiaChen/vue-element-admin/pull/1569
