### ISSUE TITLE
如何将右键关闭的页面取消缓存

### ISSUE THREAD

**Issue by nullwu** [PanJiaChen/vue-element-admin#1570]
![image](https://user-images.githubusercontent.com/32824912/51963744-8027c200-249f-11e9-8306-dcf53a954f5e.png)

目前我是将所有页面进行缓存，并没有使用include属性,想要将右键关闭的页面的缓存清除，这个怎么办到呢

**Comment by PanJiaChen** [comment]
没有办法实现。
