### ISSUE TITLE
github上展示打包之后的项目刷新404

### ISSUE THREAD

**Issue by luggege** [PanJiaChen/vue-element-admin#1572]
通过点击左侧导航正常跳转展示页面, 但是地址栏刷新页面会404(https://xxx.github.io/admin/dashboard形式展示的)

**Comment by PanJiaChen** [comment]
你把404页面去掉，看看到底是重定向到什么页面了。

**Comment by luggege** [comment]
我这没放404页面, 所有页面刷新都会404, 我的项目位置是: https://luggege.github.io/admin/

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/3b9abde89a56a18b089252d02062b095e26911ce/src/router/index.js#L108

router mode 不能用 `history`。

**Comment by luggege** [comment]
好了, 谢谢
