### ISSUE TITLE
空白的错误提示！！！！

### ISSUE THREAD

**Issue by ywhs** [PanJiaChen/vue-element-admin#1574]
如图所示，我输入一个错误的用户名或者错误的密码就会弹出一个空白的错误提示，我如何能去掉它，或者自定义我自己的错误信息，我试着把全局中（request.js）的错误注释掉，它还是会提示，我实在是找到是在哪能解决。

![在这里插入图片描述](https://img-blog.csdnimg.cn/20190130180311700.jpg?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM2OTU2MTU0,size_16,color_FFFFFF,t_70)

我也在request.js中尝试编写我自己的错误码，但是效果不是我想要的，我只是想要提示输入的密码或者用户名不正确

![在这里插入图片描述](https://img-blog.csdnimg.cn/20190130181014644.jpg?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM2OTU2MTU0,size_16,color_FFFFFF,t_70)

大神救我！！！！

**Comment by kaisawind** [comment]
你可以试一下这里
![image](https://user-images.githubusercontent.com/4010613/51974760-9e9bb680-24bb-11e9-9537-d465eb99fc18.png)

**Comment by PanJiaChen** [comment]
所以你后端有什么什么验证么？

最好能提供一个在线demo，这样描述问题，很难定位。

**Comment by ywhs** [comment]
潘大好，我后端并没用什么特别的认证。我尝试用新的vue-admin不连接后端，再把login.vue中验证用户名的代码注释，输入不是admin用户，随便什么，也会出现空白的错误提示，是我操作有误吗？不该这样做吗

**Comment by PanJiaChen** [comment]
没能重现。
