### ISSUE TITLE
easy-mock服务器挂了导致项目请求失败，登陆界面弹出“Network error”,请问大神该怎么解决

### ISSUE THREAD

**Issue by zhangxiongfeng** [PanJiaChen/vue-element-admin#1575]
早上过来的时候突然登陆不上去，登陆界面弹出“Network error”弹窗，浏览器报错
![reliao_img_1548904372608](https://user-images.githubusercontent.com/24224037/52028227-398ea200-2549-11e9-9da3-cbdbf6a5fb0c.png)

后面问了一下easy-mock的同事，是他们服务器那边的问题
![image](https://user-images.githubusercontent.com/24224037/52028314-84101e80-2549-11e9-8660-4bc63b1f41fb.png)

请问如果是这种情况怎样才能绕过他们的mock

大神求救

**Comment by kaisawind** [comment]
看起来是easy-mock 服务不支持跨域
1. 让easy-mock支持跨域
2. 前端设置跨域代理
![image](https://user-images.githubusercontent.com/4010613/52036421-13c4c580-2568-11e9-95ec-4db7e631eec8.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/issues/241
