### ISSUE TITLE
页面刷新如何停留在原来的页面？而不是跑到首页去

### ISSUE THREAD

**Issue by lubianniu** [PanJiaChen/vue-element-admin#1576]
我们公司用作者的结构（很早的版本）。现在的问题是刷新页面的时候，会默认跑到首页。有什么办法刷新的时候停留在原来的页面

**Comment by PanJiaChen** [comment]
至少给一个版本号吧。而且我觉得大概率你们改动过代码。
所以最方便的方式，你提供一个最小可还原代码。

**Comment by kaisawind** [comment]
刷新页面时，会getuserinfo，如果失败就会跳转到首页。

**Comment by lubianniu** [comment]
@PanJiaChen  （"name": "vue-admin-template","version": "3.0.0"），作者，不知您需要我提供那一块的代码，我们的项目是在您这个vue-admin-template，3.0.0基础上修改的。您可否告知我一下，控制刷新页面依旧停留在原来的页面的那文件或者那段代码我研究研究。（非常感谢您的回答，谢谢）

**Comment by lubianniu** [comment]
@kaisawind getuserInfo 这个接口一直的都是正确的。我觉得还是听听作者怎么说吧。（谢谢你的意见）

**Comment by PanJiaChen** [comment]
@lubianniu 能提供一个可还原问题的demo么？纯靠你的描述比较难猜出你的问题。

**Comment by lubianniu** [comment]
@PanJiaChen 非常感谢您的关注。由于现在春节期间，代码在公司，我初七正式上班。而且路由权限部分比较复杂，我需要回去研究一下权限，直接打开的方式。然后在上传到这个号上面。再次非常感谢关注（上传完成之后我@您）。 
新年快乐！阖家欢乐！

**Comment by lubianniu** [comment]
@PanJiaChen 作者你好！这个问题我处理好了。我的思路是：在permission.js里面，router.beforeEach()路由守卫，每次to的时候先把to.path存到sessionStorage里面，每次跳转的时候先看sessionStorage里面有没有path参数，有就停留。再次感谢你的回复，谢谢
