### ISSUE TITLE
关于管理员权限的疑问

### ISSUE THREAD

**Issue by Kunine** [PanJiaChen/vue-element-admin#158]
自己刚好在类似的然后关于权限这部分
如果直接修改 cookie 中的 admin-token 为 admin 就能直接切换权限了
自己也想过加密的思路，但总觉得不是很完善。
望不吝赐教，谢谢。

**Comment by PanJiaChen** [comment]
本项目只是模拟了一个最简单的token，真正业务项目的 token 都是由后端生成的 如：
![image](https://user-images.githubusercontent.com/8121621/29207529-16ceccf0-7eb9-11e7-98be-a9e5107281e7.png)，是不可能随便猜出来的(具体可靠性由自己公司生成 token 规则而定)，而且写入的也只是一个token，后端会通过token来返回给前端真正的权限。
随便改cookie这个也是可以解决的可以使用 `HttpOnly `来解决

**Comment by Kunine** [comment]
好的谢谢解答，大概知道怎么做了。同时感谢您的项目给我了很大启发。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/379
