### ISSUE TITLE
echart 4.1.0 有小问题

### ISSUE THREAD

**Issue by mayunhai** [PanJiaChen/vue-element-admin#1580]
在设置 series[i]-line.label.show 时候 label不会自适应的 部分不展示而会变成全部展示 很拥挤，和4.0.0及之前对比 体验较差
`                itemStyle: {
                  normal: {
                    color: color,
                    barBorderRadius: 0,
                    label: {
                      show: true,
                      position: 'top',
                      offset: [0, -10],
                      formatter(p) {
                        return p.value > 0 ? p.value : ''
                      }
                    }
                  }
                },`

**Comment by PanJiaChen** [comment]
和本项目有什么关系？

**Comment by mayunhai** [comment]
推荐使用4.0.0版本

**Comment by mayunhai** [comment]
嘿嘿 我都提了
