### ISSUE TITLE
Refresh of page will remove everything from state

### ISSUE THREAD

**Issue by rtrachelteng** [PanJiaChen/vue-element-admin#1581]
Hi, 

I tried to use the template but incorporate my own login api. However, the invoke and everything works. But once any page is refreshed, everything in the state management is gone. Hope you are able to provide some advice.

**Comment by PanJiaChen** [comment]
Currently all the state is stored in vuex, if you want to refresh the page, it also retains the state, can be stored in the cookie, localstorage, or server, etc.

And you can try this [vuex-persistedstate](https://github.com/robinvdvleuten/vuex-persistedstate).
