### ISSUE TITLE
Know How: How can i apply multi tenant at Vue Router ?

### ISSUE THREAD

**Issue by somosarado** [PanJiaChen/vue-element-admin#1583]
Hi team, 

I would like to add at the beggining just a router.parameter, without changing any behaivour.

Example: 

current:  localhost/user/list
needed localhost/companyName/user/list

This it would be needed at all pages, how is it possible to be done ?

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/6e42b4c896a712bad9a4494c4bedd9a3df163daf/config/index.js#L63

just set `assetsPublicPath: 'companyName' `

**Comment by somosarado** [comment]
Thanks for your answer PanJiaChen, what i need is this "companyName" to be a variable, 

if I access to 

localhost/name1
localhost/name1/home
localhost/name1/user/list

I need to get the parameter company with value> "name1"

if I access to 

localhost/name2
localhost/name2/home
localhost/name2/user/list

I need to get the parameter company with value> "name2"

**Comment by PanJiaChen** [comment]
I don't know exactly what your `access` here means? 
Who controls this `access`?

**Comment by somosarado** [comment]
Backend will, i will show the result information, role, users, data by the
company written at the url.
That make sense for you?

I know that at any place of the project i will need to control if there is
no company name at the url.

Its a multi tenant mode what i would like to play

**Comment by PanJiaChen** [comment]
Maybe this meet your need.

```js
export default new Router({
  mode: 'history',
  base: 'bar' //get from backend
})
```

But this need init `vue router` after you get backend information.

**Comment by somosarado** [comment]
Great, ok. So I need to create a new home, in order to detect by myself the
tenant company, and then, set the vue router with this value?

**Comment by JGarrido** [comment]
@somosarado how did you wind up accomplishing this?
