### ISSUE TITLE
请问路由根据 后台用户角色动态配置 现在 有了嘛

### ISSUE THREAD

**Issue by 1228857713** [PanJiaChen/vue-element-admin#1585]
请问路由根据 后台 动态配置 现在 有了嘛，如果没有 我要自己写了

**Comment by PanJiaChen** [comment]
没有，暂时也不会添加该功能。

可关注该issue https://github.com/PanJiaChen/vue-element-admin/issues/900

**Comment by PanJiaChen** [comment]
已添加 https://github.com/PanJiaChen/vue-element-admin/pull/1605
