### ISSUE TITLE
一个直接连接页面能不能搭建多个tab路由级页面

### ISSUE THREAD

**Issue by lubianniu** [PanJiaChen/vue-element-admin#1588]

**Comment by lubianniu** [comment]
这样可以得到一个直接连接页面
{
  path: '/icon',
  component: Layout,
  children: [{
    path: 'index',
    component: ()=>import('svg-icons/index'),
    name: 'icons',
    meta: { title: 'icons', icon: 'icon' }
  }]
},但是我想要在这个页面上添加tab栏路由级别的。下面这样写没有实现
{
        path: "/ResumeManagement",
        component: Layout,
        redirect: "/ResumeManagement/ResumeManagement",
        meta: {
            id: "15"
        },
        alwaysShow: true,
        children: [
            {
                path: "ResumeManagement",
                name: "ResumeManagement",
                component: () =>
                import ("@/views/ResumeManagement/index"),
                meta: {
                    icon: "zhiwei",
                    title: "路由管理",
                },
                children: [
                    {
                        path: "alreadyEmployment",
                        name: "alreadyEmployment",
                        component: () =>
                        import ("@/views/ResumeManagement/alreadyEmployment"),
                    },
                    {
                        path: "alreadyEntry",
                        name: "alreadyEntry",
                        component: () =>
                        import ("@/views/ResumeManagement/alreadyEntry"),
                    },
                    {
                        path: "atInterview",
                        name: "atInterview",
                        component: () =>
                        import ("@/views/ResumeManagement/atInterview"),
                    },
                    {
                        path: "newResume",
                        name: "newResume",
                        component: () =>
                        import ("@/views/ResumeManagement/newResume"),
                    },
                    {
                        path: "waitCommunicate",
                        name: "waitCommunicate",
                        component: () =>
                        import ("@/views/ResumeManagement/waitCommunicate"),
                    },
                ]

            }
        ]
    },如果这样写那么就可以实现（想实现上面的一种效果需要怎么做）
{
    path: "/myInterview",
    component: Layout,
    name: "myInterview",
    redirect: "myInterview/InterviewList",
    meta: {
      title: "任务表",
      icon: "my",
      roles: "RECRUITER",
      id: "8"
    },
    children: [{
        path: "InterviewList",
        name: "InterviewList",
        component: () =>
          import ("@/views/myInterview/InterviewList/index"),
        meta: {
          title: "任务列表",
        },
        children: [{
            path: "interviewPage",
            name: "interviewPage",
            component: () =>
              import ("@/views/myInterview/InterviewList/interviewPage"),
            meta: {
              title: "以后的"
            },
          },
          {
            path: "nonFeedbackPage",
            name: "nonFeedbackPage",
            component: () =>
              import ("@/views/myInterview/InterviewList/nonFeedbackPage"),
            meta: {
              title: "以前的"
            },
          },
          {
            path: "feedbackPage",
            name: "feedbackPage",
            component: () =>
              import ("@/views/myInterview/InterviewList/feedbackPage"),
            meta: {
              title: "今后的"
            },
          },
          {
            path: "cancelPage",
            name: "cancelPage",
            component: () =>
              import ("@/views/myInterview/InterviewList/cancelPage"),
            meta: {
              title: "已取消"
            },
          }
        ]

      },
      {
        path: "InterviewCalendarOne",
        name: "InterviewCalendarOne",
        component: () =>
          import ("@/views/myInterview/InterviewCalendarOne/index"),
        meta: {
          title: "任务日历",
          id: "8"
        }

      },
    ]
  },

**Comment by PanJiaChen** [comment]
不太理解你的问题是什么？

**Comment by lubianniu** [comment]
![2](https://user-images.githubusercontent.com/34875176/52607706-2a491600-2eb2-11e9-8060-d51d4d2c1bed.png)如图（2）所示的路由搭建方式,放到图（1）就不行了
![1](https://user-images.githubusercontent.com/34875176/52607773-68463a00-2eb2-11e9-8286-8bf647277cb5.png)

**Comment by PanJiaChen** [comment]
还是没懂

**Comment by lubianniu** [comment]
![22](https://user-images.githubusercontent.com/34875176/52688473-98b0d580-2f91-11e9-95ac-cef5de243117.jpg)
我想要 侧边栏是 路由样本 下面的 子菜单路由设置页面（路由搭建方式），用到 侧边栏是 直接连接页面2 的页面。
我按照 侧边栏是 路由样本 下面是 子菜单路由设置页面的搭建方式，用到 侧边栏是 直接连接页面2的页面，没有起到效果，请问如何实现 这种需求呢？

**Comment by PanJiaChen** [comment]
请先能正确表达自己的问题。

> 我想要 侧边栏是 路由样本 下面的 子菜单路由设置页面（路由搭建方式），用到 侧边栏是 直接连接页面2 的页面。

你觉得你这句通么？侧边栏到底是什么？

**Comment by lubianniu** [comment]
我想要的效果是 直接连接页面2 和 路由样本 下面的 子菜单路由设置 页面一样的效果。

**Comment by PanJiaChen** [comment]
引用一个component不就好了。

**Comment by lubianniu** [comment]
@PanJiaChen 嗯 谢谢指点。用 component 实现了
