### ISSUE TITLE
git到本地 install的时候报错

### ISSUE THREAD

**Issue by as236676674** [PanJiaChen/vue-element-admin#1590]
npm ERR! path D:\vue-admin\vue-element-admin\node_modules\.staging\echarts-0ab63e43\dist\echarts.simple.min.js
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'D:\vue-admin\vue-element-admin\node_modules\.staging\echarts-0ab63e43\dist\echarts.simple.min.js'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'D:\vue-admin\vue-element-admin\node_modules\.staging\echarts-0ab63e43\dist\echarts.simple.min.js']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'D:\vue-admin\vue-element-admin\node_modules\.staging\echarts-0ab63e43\dist\echarts.simple.min.js'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'D:\\vue-admin\\vue-element-admin\\node_modules\\.staging\\echarts-0ab63e43\\dist\\echarts.simple.min.js' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'D:\\vue-admin\\vue-element-admin\\node_modules\\.staging\\echarts-0ab63e43\\dist\\echarts.simple.min.js\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'D:\\vue-admin\\vue-element-admin\\node_modules\\.staging\\echarts-0ab63e43\\dist\\echarts.simple.min.js',
npm ERR!   parent: 'vue-element-admin' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-02-12T06_09_47_162Z-debug.log

**Comment by PanJiaChen** [comment]
请重新安装。
