### ISSUE TITLE
How to add Font Awesome to Route config (left navigator bar)

### ISSUE THREAD

**Issue by ndphuong** [PanJiaChen/vue-element-admin#1592]
Hello

On the router config, I see the ` meta: { icon: 'time' }`
How to change icon to using Font Awesome ?

Thanks

**Comment by PanJiaChen** [comment]
You can use [vue-fontawesome](https://github.com/FortAwesome/vue-fontawesome).

https://github.com/PanJiaChen/vue-element-admin/blob/fe381503eb0f6700ea18a9405e38c0d7cd16132e/src/views/layout/components/Sidebar/Item.vue#L20

Then change `svg-icon` to `font-awesome-icon`.
