### ISSUE TITLE
弹出框无法兼容移动端,所以想着引入bootstrap,是否可行呢

### ISSUE THREAD

**Issue by a28997753** [PanJiaChen/vue-element-admin#1593]
弹出框无法兼容移动端,所以想着引入bootstrap,是否可行呢?

**Comment by PanJiaChen** [comment]
有些本末倒置。。如果只是 模态框的话 随便找一个支持移动端的轻量级模态框就好了吧。

**Comment by a28997753** [comment]
> 有些本末倒置..如果只是模态框的话随便找一个支持移动端的轻量级模态框就好了吧。

好的,那我找找,谢谢
