### ISSUE TITLE
您好，大佬，我是一个前端小白，我们项目用了你的这个开源框架，我们需求提出了一个问题，我看了您的文档，但是也找不出解决方案，能否帮忙解决一下

### ISSUE THREAD

**Issue by long1234511** [PanJiaChen/vue-element-admin#1596]
![image](https://user-images.githubusercontent.com/30490307/52711562-1514da00-2fcd-11e9-99c2-5e2b41a42815.png)
就是当着两个tab之前互相切换的时候，每次切换，都会重新刷新页面，有没有办法每次切换的时候，不让他刷新，我看了一下你的前端代码，您是这也写的，但是我不知道该改动哪里
```
 <router-link
        v-for="tag in visitedViews"
        ref="tag"
        :class="isActive(tag)?'active':''"
        :to="{ path: tag.path, query: tag.query, fullPath: tag.fullPath }"
        :key="tag.path"
        tag="span"
        class="tags-view-item"
        @click.middle.native="closeSelectedTag(tag)"
        @contextmenu.prevent.native="openMenu(tag,$event)">
        {{ tag.title }}
        <span class="el-icon-close" @click.prevent.stop="closeSelectedTag(tag)" />
      </router-link>
```
能否帮忙看看，谢谢

**Comment by long1234511** [comment]
大佬，帮帮忙，十分感谢

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/tags-view.html#visitedviews-cachedviews

请先看文档

**Comment by long1234511** [comment]
感谢大佬，膜拜大佬，解决了，谢谢

**Comment by liulongyuemenglong** [comment]
@long1234511 怎么解决的tab切换刷新的问题？

**Comment by lgx211** [comment]
有事件在监听tab的切换，当切换的时候，就去重新加载该页面。也就是页面被重新刷新了。要想达到不被刷新的效果，就要同时保留好几个路由。如果只是想达到效果不被刷新，可以效果回显，找到那个监听事件，重新改写




------------------ 原始邮件 ------------------
发件人: "liulongyuemenglong"<notifications@github.com>;
发送时间: 2019年7月15日(星期一) 下午2:31
收件人: "PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [PanJiaChen/vue-element-admin] 您好，大佬，我是一个前端小白，我们项目用了你的这个开源框架，我们需求提出了一个问题，我看了您的文档，但是也找不出解决方案，能否帮忙解决一下 (#1596)




@long1234511 怎么解决的tab切换刷新的问题？
