### ISSUE TITLE
tagsview 可以关闭首页

### ISSUE THREAD

**Issue by z7z** [PanJiaChen/vue-element-admin#1598]
![441550127238_ pic](https://user-images.githubusercontent.com/7941245/52768480-9a010180-3068-11e9-9c32-6447730cefe5.jpg)
![451550127238_ pic](https://user-images.githubusercontent.com/7941245/52768489-9d948880-3068-11e9-9e15-fc25762c3697.jpg)
![461550127238_ pic_hd](https://user-images.githubusercontent.com/7941245/52768492-9ff6e280-3068-11e9-9779-7c9c81594aa4.jpg)
我是个不会前端的iOS程序猿，最近正在学习前端。
我知道这个问题的代码位置，但是就是不会修改，我想判断如果是首页，就不会删除 tags 标签。

**Comment by PanJiaChen** [comment]
其实已经修掉了 https://github.com/PanJiaChen/vue-element-admin/pull/1577

**Comment by z7z** [comment]
> 其实已经修掉了 #1577

抱歉，我的标题和内容可能说反了，我想在点击首页那个关闭按钮的时候，它不会消失掉。

**Comment by z7z** [comment]
@PanJiaChen 
![471550134016_ pic_hd](https://user-images.githubusercontent.com/7941245/52774462-3252b280-3078-11e9-87cf-74f6702f33b1.jpg)
首先我确实不会前端，我只是想默认的首页不能被关闭掉，要不tagsview就空了，我现在只能在后面添加个时间戳，让他重新加载一下....好像很智障，确实不会前端么，哈哈哈。

**Comment by PanJiaChen** [comment]
你可以更新到最新代码，通过在路由配置 `affix:true` 可以实现你的效果。
