### ISSUE TITLE
侧边栏展开时，Menu-Item延时显示，SubMenu及时显示

### ISSUE THREAD

**Issue by ruanhuhu** [PanJiaChen/vue-element-admin#1604]
不知道是那一部分会出问题，完全没有头绪...
[录屏](https://drive.google.com/file/d/1GW-kqbieD5-Iy4Ol0-v5uts0fmk7dEIJ/view)
仓库地址：https://coding.net/u/ruanhuhu/p/system/git

不好意思，是新手，把代码按照自己的理解搭起来的，可能有些乱....

**Comment by PanJiaChen** [comment]
https://jsfiddle.net/ymftapxe/

就是正常的展开动画。

**Comment by ruanhuhu** [comment]
可是为什么您那个官网上的demo是没有延时的？

**Comment by ruanhuhu** [comment]
![image](https://user-images.githubusercontent.com/3184110/52832187-67abde80-3112-11e9-8a91-94a7ea401cef.png)
展开的时候 感觉“首页”比“车辆监控”那几个有子项目的title延时显示蛮多的（包括SubMenu那个组件的向下箭头好像显示也延时了），但是看官网页面并没有这个问题？

**Comment by PanJiaChen** [comment]
给你的demo就是官方的代码。没加任何其它的css修改。

**Comment by ruanhuhu** [comment]
哦 我说的官网是您的项目的官网 https://panjiachen.github.io/vue-element-admin/#/dashboard
那边侧边栏的展开好像都没什么延时，至少是统一的。（我上面录屏里，“首页”那个Menu-Item就迟了一些，如果说延时是正常的，为什么SubMenu的title都是及时显示的，没有延时？）

![_h_ s lx5f jtos_rbj6h l](https://user-images.githubusercontent.com/3184110/52835963-b3b34f00-3123-11e9-87f6-000a40757b48.png)
然后我看了您这边的navbar组件上的el-menu组件有一个show-timeout的prop值，但是我看element官网上：
![SubMenu Attribute](https://user-images.githubusercontent.com/3184110/52836019-ed845580-3123-11e9-8c90-cb810c91247e.png)
![Menu Attribute](https://user-images.githubusercontent.com/3184110/52836069-1573b900-3124-11e9-9d46-54b761edf083.png)
这个是SubMenu的属性，并不是Menu的属性。请问这个属性到底是什么用的？和我的问题有关联么？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/8c18c000d42d913be7bd03c933964d388852cc43/src/styles/sidebar.scss#L25-L27

我的项目覆盖了它默认的css。

**Comment by ruanhuhu** [comment]
哈哈哈 就是这个 解决了 谢谢~ 
感觉和明星说上话的感觉~嘻嘻
