### ISSUE TITLE
三级菜单

### ISSUE THREAD

**Issue by zhudaoyuan** [PanJiaChen/vue-element-admin#1607]
请问怎么正确在路由中添加三级菜单？添加三级菜单后，点击菜单没有页面显示。
![image](https://user-images.githubusercontent.com/17665636/52896583-2cd6a300-3205-11e9-86e0-ad14d9ba3872.png)

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/new-page.html#%E5%A4%9A%E7%BA%A7%E7%9B%AE%E5%BD%95-%E5%B5%8C%E5%A5%97%E8%B7%AF%E7%94%B1

請自行参考nested 页面。

我猜测你少写了 `router-view`
