### ISSUE TITLE
运行npm run build:prod出警告

### ISSUE THREAD

**Issue by ninki51** [PanJiaChen/vue-element-admin#1608]
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
static/js/chunk-elementUI.916cd2bb.js (562 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
app (984 KiB)
static/js/runtime.f70cc7c6.js
static/css/chunk-elementUI.8441406c.css
static/js/chunk-elementUI.916cd2bb.js
static/css/chunk-libs.0404713a.css
static/js/chunk-libs.cee28661.js
static/css/app.10fde728.css
static/js/app.45c065fc.js

**Comment by ninki51** [comment]
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
static/js/chunk-elementUI.916cd2bb.js (562 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
app (984 KiB)
static/js/runtime.f70cc7c6.js
static/css/chunk-elementUI.8441406c.css
static/js/chunk-elementUI.916cd2bb.js
static/css/chunk-libs.0404713a.css
static/js/chunk-libs.cee28661.js
static/css/app.10fde728.css
static/js/app.45c065fc.js

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/issues/279
