### ISSUE TITLE
v4.0 用的 element-ui@2.4.10 点击其它区域会自动收缩侧边栏

### ISSUE THREAD

**Issue by xiaopingfeng** [PanJiaChen/vue-element-admin#1609]
v4.0分支 点击其它区域会自动收缩侧边栏
后来发现是用的 element-ui@2.4.10 的bug， 2.4.11 修复了
 element-ui 会升级到2.4.11 或 2.5.x 吗？

另外请问下v4.0版本大概还有多久可以发版，我打算先用 v4.0 分支做项目不知道会不会有问题

**Comment by xiaopingfeng** [comment]
改用 3.10 了 ...........

**Comment by PanJiaChen** [comment]
v4.0分支 暂且还不能用。
