### ISSUE TITLE
npm  install报错什么情况 

### ISSUE THREAD

**Issue by galary** [PanJiaChen/vue-element-admin#161]
npm ERR! Unexpected end of input at 1:45312
npm ERR! "directories":{},"dist":{"shasum":"b0e40d8a344bf652a7be950589c6a4cac6
npm ERR!                                                                      ^

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-08-16T06_33_52_054Z-debug.log

**Comment by PanJiaChen** [comment]
@galary 需要完整的截图

**Comment by galary** [comment]
![image](https://user-images.githubusercontent.com/17908869/29351086-be8736fc-8293-11e7-8b27-399831892b19.png)

**Comment by PanJiaChen** [comment]
你是不是用了yarn？
这是
![image](https://user-images.githubusercontent.com/8121621/29352673-3548f266-829a-11e7-83e7-af8bd2b26d73.png) yarn 才会生成的东西

**Comment by PanJiaChen** [comment]
太久没回复 先close
