### ISSUE TITLE
编译一直出现Attribute "xxx" should go before "xxx"

### ISSUE THREAD

**Issue by mahaoming** [PanJiaChen/vue-element-admin#1610]
![_20190218095741](https://user-images.githubusercontent.com/31064550/52923670-d764d800-3363-11e9-9e89-3d692759883c.png)
这样的问题在eslint中要怎么忽视掉呢

**Comment by PanJiaChen** [comment]
提示很清楚了。自己不能搜一下么。

**Comment by emptycitys** [comment]
同问，检验这个问题的是eslint哪个选项，表示想关掉这个校验
