### ISSUE TITLE
页面无法加载!清除缓存以后就可以加载！这个什么原因？

### ISSUE THREAD

**Issue by wlLeblanc** [PanJiaChen/vue-element-admin#1616]
![image](https://user-images.githubusercontent.com/22288871/53065088-2c8c1f80-3505-11e9-8baa-88da059a5b1b.png)

**Comment by PanJiaChen** [comment]
请用正确的姿势提问。
让我猜么。

**Comment by wlLeblanc** [comment]
@PanJiaChen   就是页面的路由我是缓存起来的！然后进入网站有时候就会出现上面这种情况，一直进入不了登录页面！然后把浏览器的缓存清除掉，刷新页面就能进入了！谢谢大佬！

**Comment by PanJiaChen** [comment]
你指的缓存是 静态资源缓存还是别的什么？

**Comment by wlLeblanc** [comment]
@PanJiaChen 静态资源

**Comment by PanJiaChen** [comment]
请提供一个可还原的在线demo
