### ISSUE TITLE
当左侧栏缩小为图标时，页面高度过低导致二级菜单不能滚动

### ISSUE THREAD

**Issue by chenchenwuai** [PanJiaChen/vue-element-admin#1617]
![image](https://user-images.githubusercontent.com/32892396/53140465-b00e4500-35c7-11e9-9fa5-a9b1eaffb4de.png)
页面高度很高会显示完全
![image](https://user-images.githubusercontent.com/32892396/53140482-c87e5f80-35c7-11e9-91c8-726d2040c409.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/320

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1619

暂时用 纯 css 解决，不过有一些兼容性问题，低版本浏览器样式会丑一点。
不过这种场景本身也不会很多，当一个 subMenu 过长时可以考虑一下是否要拆分一下业务。
