### ISSUE TITLE
嵌套路由下，怎样缓存组件

### ISSUE THREAD

**Issue by hanz520** [PanJiaChen/vue-element-admin#1620]
因为在开发的系统菜单太多，层级做了三层，大致和demo中的相似。
![image](https://user-images.githubusercontent.com/24839877/53154049-c5e62f00-35f4-11e9-92b7-3c3b6806d18d.png)
现在我在 menu1-2-1组件中做了一些数据收集，然后切换tab页，再切回来，发现原来收集的数据都没有，这个页面组件重新渲染过了，请问，怎么缓存下来？ 有什么思路可以提供一下，感谢！

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/700
