### ISSUE TITLE
About Login Page

### ISSUE THREAD

**Issue by UMUTBAYGUT** [PanJiaChen/vue-element-admin#1622]
Hi,
I want to using login control with our api . 
I changed /src/api/login.js   line 9 = "https://loginmvc20190221105915.azurewebsites.net/Login/Login"
But When I try to login , system have a error "Network Error" . But I can using in the postman this api .

What can I do ?

Thanks

**Comment by PanJiaChen** [comment]
Please provide a screenshot of network

**Comment by UMUTBAYGUT** [comment]
![untitled](https://user-images.githubusercontent.com/9067506/53165423-ba3e3c80-35e3-11e9-9cc8-62a7916eff73.png)

**Comment by PanJiaChen** [comment]
I think it may be a cross-domain issue, your request is only sent out to the options.

**Comment by UMUTBAYGUT** [comment]
https://github.com/UMUTBAYGUT/LoginMVC-VueJS    simple code for testin login. I adding to CORS future but again it is same .

**Comment by PanJiaChen** [comment]
Sorry, please search for the relevant solution yourself.

**Comment by UMUTBAYGUT** [comment]
![login](https://user-images.githubusercontent.com/9067506/54031134-eb5f6500-41be-11e9-8fc3-719e22e0f745.png)
Hello , I create a api in my backend for login process. 
I changed the api/login.js 
`export function loginByUsername(username, password) {
  const data = {
    username,
    password
  }
  return request({
    url: 'https://localhost:5001/service/Login/LoginByUsernamePassword',
    method: 'post',
    data
  })
}`

But when I display the `this.$store.getters.name` value , in the screen I see ahain Super Admin. How can I disabled mock login.js ?

**Comment by PanJiaChen** [comment]
remove this 

https://github.com/PanJiaChen/vue-element-admin/blob/3e92814f13c62aa626542859c2927ccbad81baf6/src/mock/index.js#L22-L24

**Comment by shweiki** [comment]
same issue 
@UMUTBAYGUT  Hello  i want do same issues can u help me 
taha shweiki

**Comment by AlexDeng09** [comment]
the system uses mockjs to mock login request handling, and it is only enabled in production. In main.js, try change `if (process.env.NODE_ENV === 'production') {
  mockXHR()
}` to `mockXHR()`
