### ISSUE TITLE
关于PDF新打开页面路由传参的问题（params, query)

### ISSUE THREAD

**Issue by dawayway** [PanJiaChen/vue-element-admin#1624]
裤衩哥，目前pdf打印是新开一个页面，然后打印的数据还是写死的，现在我们要求打印路由传参过去的数据，使用this.$router.push(' /路径 ',params:{ 数据 }， query: { 数据 } ），发现query穿过去的少量数据可以接收，大量数据会显示成[object， object]，但是params传的数据一点都接收不到，这是什么原因呢？

**Comment by PanJiaChen** [comment]
大数据通过路由传是不合理的（会有些异常需要处理）。

最简单的方案是放到vuex里面 或者通过 localstorage 或者先存到后端再通过接口的方式来交互。
