### ISSUE TITLE
上侧导航栏可以做成与左侧导航一样可以隐藏吗

### ISSUE THREAD

**Issue by MoneyHacker** [PanJiaChen/vue-element-admin#1625]
上侧导航栏可以做成与左侧导航一样可以隐藏吗

**Comment by PanJiaChen** [comment]
没懂你想要的效果。
有实例么？

**Comment by MoneyHacker** [comment]
就是上侧的导航栏也可以隐藏或展开，跟左侧的一样，不然内容区数据显示的太少了，空间不够

**Comment by MoneyHacker** [comment]
![default](https://user-images.githubusercontent.com/2275266/53226959-c4316f80-36b7-11e9-9f17-fc99fa997d66.png)

**Comment by PanJiaChen** [comment]
意义是什么？

**Comment by mingxuan0624** [comment]
我也没看明白是什么意思
