### ISSUE TITLE
关于设备类型判断的一点疑问

### ISSUE THREAD

**Issue by gongming1982** [PanJiaChen/vue-element-admin#1626]
在@/views/layout/mixin/ResizeHandler.js 文件中做的设备类型判断是否应该是：
return rect.width * RATIO < WIDTH

而不是项目中原有的：
return rect.width - RATIO < WIDTH

设备width减去一个比率是否有意义呢？

而且RATIO写死为3是不是合适，现在仍有很多设备是2 的。

**Comment by PanJiaChen** [comment]
我的问题，这里这个RATIO变量名词取得有问题。其实是你`减去一个比率`的意思。

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/1633
