### ISSUE TITLE
[Vue warn]: Error in render: "TypeError: Cannot create property 'default' on boolean 'true'"

### ISSUE THREAD

**Issue by youarefoodie** [PanJiaChen/vue-element-admin#1628]
![1](https://user-images.githubusercontent.com/20119824/53235143-17adb880-36cc-11e9-8619-4da27845c6f5.png)
只要改变el-table里面的slot-scope="scope"，编译后页面就会报这个错误
如：
![2](https://user-images.githubusercontent.com/20119824/53235313-78d58c00-36cc-11e9-876b-cca463279a09.png)

**Comment by PanJiaChen** [comment]
没能重现，确定用的是线上最新版本么？
或者重装一下 node_modules 试试。

https://github.com/PanJiaChen/vue-element-admin/issues/1541

**Comment by youarefoodie** [comment]
是刚下载master的代码
步骤：
1、npm install
2、npm run dev跑起来后
3、注释example/list.vue  第七行的代码
4、ctrl + s 保存编译后，就出现上面的错误

**Comment by dongsuo** [comment]
更新一下这个就好了 ：
`npm i vue-hot-reload-api@2.3.3` 
参见：https://github.com/vuejs/vue-hot-reload-api/pull/74

**Comment by youarefoodie** [comment]
按照这样解决了
* 先删除已经存在的node_modules
* 删除package-lock.json
* npm cache clean --force
* npm install
