### ISSUE TITLE
导出excel

### ISSUE THREAD

**Issue by TianYouH** [PanJiaChen/vue-element-admin#163]
我在使用导出excel报错：提示无法找打 vendor/ExportExcel

已安装loader
"xlsx": "^0.11.2"
"file-saver": "^1.3.3",
"script-loader": "^0.7.0",
库定义方式和例子是一样的，
 require.ensure([], () => { 
                const { export_json_to_excel } = require('vendor/ExportExcel');
在这里报错，是不是缺少那些配置？

详细报错
* vendor/ExportExcel in ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader                            @11.3.4@vue-loader/lib/selector.js?type=script&index=0!./src/views/zxks/lmkmxzsd                            .vue

To install it, you can run: npm install --save vendor/ExportExcel

**Comment by PanJiaChen** [comment]
不要忘记引入 https://github.com/PanJiaChen/vue-element-admin/blob/master/src/vendor/Export2Excel.js
和
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/vendor/Blob.js

教程见：https://segmentfault.com/a/1190000009762198#articleHeader15

**Comment by TianYouH** [comment]
@PanJiaChen 
![image](https://user-images.githubusercontent.com/15323122/29393065-36d1c15e-8334-11e7-949e-9a93cb511566.png)  
上图是vue-element-admin结构  
![image](https://user-images.githubusercontent.com/15323122/29393091-69fd6920-8334-11e7-9a3a-1545608c8ae1.png)  
上图是我的项目结构。Blob和Export2Excel.js是直接复制的模版里的  
下面是我在项目里使用该库时
  
![image](https://user-images.githubusercontent.com/15323122/29393157-b709afda-8334-11e7-96f5-d9d779198532.png)

报错
![image](https://user-images.githubusercontent.com/15323122/29393196-fadb8e04-8334-11e7-93ab-b27ef0fedd74.png)

**Comment by PanJiaChen** [comment]
我这样写是应为我`vendor` 配置了 `alias` [代码](https://github.com/PanJiaChen/vue-element-admin/blob/master/build/webpack.base.conf.js#L34)
你可以使用相对路径或者也配置`alias`

**Comment by TianYouH** [comment]
@PanJiaChen   
Thanks, the problem has been resolved. Your example makes me learned a lot
