### ISSUE TITLE
npm install 出错

### ISSUE THREAD

**Issue by Lxjazni7** [PanJiaChen/vue-element-admin#1630]
``` npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/xiaojunli/workspaces/VueWorkspace/vue-element-admin/node_modules/highlight.js/tools/build.js' ```

**Comment by sa1148260** [comment]
+1

**Comment by cnxinan** [comment]
# 建议不要用 cnpm 安装 会有各种诡异的bug 可以通过如下操作解决 npm 下载速度慢的问题
npm install --registry=https://registry.npm.taobao.org

**Comment by hailun168** [comment]
我使用 npm安装依赖也会出现这种问题！！！

**Comment by SerkoAlexX** [comment]
+1 和CNPM没关系啊看起来 是不是要升级node.js吗

**Comment by Lxjazni7** [comment]
[https://github.com/highlightjs/highlight.js/issues/1984](url) 是依赖库的问题 等修复吧

**Comment by Lxjazni7** [comment]
> # 建议不要用 cnpm 安装 会有各种诡异的bug 可以通过如下操作解决 npm 下载速度慢的问题
> npm install --registry=https://registry.npm.taobao.org

不是源的问题- -

**Comment by PanJiaChen** [comment]
https://github.com/highlightjs/highlight.js/issues/1984

暂时方案 `package.json`中移除 `tui-editor`。

**Comment by hailun168** [comment]
> 
> 
> [highlightjs/highlight.js#1984](https://github.com/highlightjs/highlight.js/issues/1984)
> 
> 暂时方案 `package.json`中移除 `tui-editor`。

**去掉tui-editor后出现以下问题**
![default](https://user-images.githubusercontent.com/18624494/53326615-f85b9900-3920-11e9-875e-2a023c3049f6.png)

**Comment by PanJiaChen** [comment]
* 先删除已经存在的node_modules
* 删除package-lock.json
* npm cache clean --force
* npm install

**Comment by chenbo941007** [comment]
![image](https://user-images.githubusercontent.com/26104052/53331975-2ba42500-392d-11e9-9ace-6adb120a33d8.png)
去掉后启动报错

**Comment by PanJiaChen** [comment]
@chenbo941007  
同时在 `@/src/router/modules/components`中 注释`markdown` 路由。

**Comment by fengmk2** [comment]
cnpm i highlight.js 可以安装成功的，因为 cnpm 已经第一时间紧急修复。

**Comment by abc2001x** [comment]
install 不过去.浪费了一天,烦躁

**Comment by UMUTBAYGUT** [comment]
> * 先删除已经存在的node_modules
> * 删除package-lock.json
> * npm cache clean --force
> * npm install

Still I have a error in highlight module

**Comment by PanJiaChen** [comment]
@UMUTBAYGUT 

Highlight.js has released a revised [version](https://github.com/highlightjs/highlight.js/releases/tag/9.15.5), I think there should be no problem now.

**Comment by Lxjazni7** [comment]
Highlight.js 修复了应该
