### ISSUE TITLE
npm install出错

### ISSUE THREAD

**Issue by chenbo941007** [PanJiaChen/vue-element-admin#1631]
![image](https://user-images.githubusercontent.com/26104052/53323436-1a511d80-3919-11e9-85a9-2b9b0eea0ce1.png)
麻烦问下怎么处理

**Comment by cnxinan** [comment]
# 建议不要用 cnpm 安装 会有各种诡异的bug 可以通过如下操作解决 npm 下载速度慢的问题
npm install --registry=https://registry.npm.taobao.org

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1630
