### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by NuniTelo** [PanJiaChen/vue-element-admin#1632]
Hello, 
I am trying to login and implement my API with your login method. I login successfully but when it comes to permissions none of menues is shown. Even when i pass role "admin" as hardcoded , still is the same issue.
Please help.

![screenshot 2019-02-25 at 10 20 58](https://user-images.githubusercontent.com/24767579/53326948-0f7d9500-38e7-11e9-80c6-8b591dff65a4.png)

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/53382936-d4e02f00-39b0-11e9-9c10-93ee5b0f6203.png)

Your `permission_routers` may be is empty.

**Comment by newbeekk** [comment]
> ![image](https://user-images.githubusercontent.com/8121621/53382936-d4e02f00-39b0-11e9-9c10-93ee5b0f6203.png)
> 
> Your `permission_routers` may be is empty.

我的也是这样，请问大佬，为什么换成自己的api接口之后，permission_routers是没有数据的，哪一步出现的问题啊？  我排查好久了，issues也看了好久，没解决，望大神指点迷津
谢谢

**Comment by NuniTelo** [comment]
I created endpoint for taking roles of a user. It's seems that is working.
