### ISSUE TITLE
懒加载的应用

### ISSUE THREAD

**Issue by Dracomes** [PanJiaChen/vue-element-admin#1634]
hello，我在项目中使用懒加载加载组件，但是发现切换路由时发生明显的延迟切换页面，这样的情况是因为加载组件和渲染页面引起的嘛？求大神指点，感谢！！

**Comment by Dracomes** [comment]
hello，我在项目中使用懒加载加载组件，但是发现切换路由时发生明显的延迟切换页面，这样的情况是因为加载组件和渲染页面引起的嘛？求大神指点，感谢！！

**Comment by PanJiaChen** [comment]
请提供在线最小可还原demo。

**Comment by jiuwuxiaohun** [comment]
是不是你自己没有关闭那页面切换动画,代码好像在layout的文件夹里面,关闭动画了之后,切换很快的

**Comment by Dracomes** [comment]
谢谢大佬，，应该不是动画效果的原因，切换时候会顿一下再切换过去，而不是流畅的切换，猜测可能是因为渲染组件的原因，，渲染组件花费300多ms，再加上懒加载组件可能需要300多
