### ISSUE TITLE
添加polyfill后线上报错，本地编译不报错

### ISSUE THREAD

**Issue by haoyinag** [PanJiaChen/vue-element-admin#1635]
如题，添加了之后报错：only one instance of babel-polyfill is allowed
找遍项目都没找到问题，求解决

**Comment by PanJiaChen** [comment]
报错很明显了，随手一搜就有相关问题了。

**Comment by haoyinag** [comment]
大哥，真搜索不到

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 花裤衩 <notifications@github.com>
发送时间: Tuesday, February 26, 2019 10:15:19 AM
收件人: PanJiaChen/vue-element-admin
抄送: ChenHaoYin; Author
主题: Re: [PanJiaChen/vue-element-admin] 添加polyfill后线上报错，本地编译不报错 (#1635)


报错很明显了，随手一搜就有相关问题了。

―

**Comment by PanJiaChen** [comment]
那你至少也要给一在线代码啊，不然我靠猜？

**Comment by haoyinag** [comment]
我换了别的方式实现项目，重现不了了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 花裤衩 <notifications@github.com>
发送时间: Wednesday, February 27, 2019 3:30:25 PM
收件人: PanJiaChen/vue-element-admin
抄送: ChenHaoYin; Author
主题: Re: [PanJiaChen/vue-element-admin] 添加polyfill后线上报错，本地编译不报错 (#1635)


那你至少也要给一在线代码啊，不然我靠猜？

―
