### ISSUE TITLE
How can I access the dev server from phone browser?

### ISSUE THREAD

**Issue by andrewlamyw** [PanJiaChen/vue-element-admin#1636]
May I know how can I use my phone browser to view the page from vue-element-admin?

Just like the `npm run serve` from vue-cli generated project
![image](https://user-images.githubusercontent.com/11419166/53341114-a2e5b300-3945-11e9-9f7a-0a94e704eaab.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/c0f378e50a1d7bb7e2be1f365ba414ef31340988/config/index.js#L16-L18

Version 4.0 will support this feature.

**Comment by jiuwuxiaohun** [comment]
If you set the IP to 0.0.0.0, you may cause some errors in Windows. You can set your own LAN IP and then use wifi to access this IP for debugging.

**Comment by andrewlam-mbaex** [comment]
> If you set the IP to 0.0.0.0, you may cause some errors in Windows. You can set your own LAN IP and then use wifi to access this IP for debugging.

I manually change the address to localhost on the browser.

**Comment by PanJiaChen** [comment]
4.0 is released
