### ISSUE TITLE
treeTable 自定义列怎么样把序号去掉

### ISSUE THREAD

**Issue by linqunshan** [PanJiaChen/vue-element-admin#1638]
treeTable 自定义列怎么样把序号去掉
![image](https://user-images.githubusercontent.com/35292015/53345770-9f0b5e00-3950-11e9-858c-911fe1b3194c.png)

**Comment by zhoutaiping** [comment]
浏览一下代码注释掉你不需要的

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/c0f378e50a1d7bb7e2be1f365ba414ef31340988/src/components/TreeTable/index.vue#L10

暂时注释这个就好了。

https://github.com/PanJiaChen/vue-element-admin/pull/1587

新版 tree-table 组件在重构中了。
