### ISSUE TITLE
我用cnpm i安装依赖包时报错，

### ISSUE THREAD

**Issue by wnyjk** [PanJiaChen/vue-element-admin#164]
我这是win10的系统。node是8.2.1版本的。在自己win7上都没问题，在win10上一直安装不了，其他几个项目也是这样。下面是报错的截图。有什么好的解决办法吗
![absowd q o0adaa uxd5ljd](https://user-images.githubusercontent.com/22720943/29392999-e55894ce-8333-11e7-8de2-e013e9fadcc3.jpg)

**Comment by PanJiaChen** [comment]
看着像网路问题，而且推荐 `npm install --registry=https://registry.npm.taobao.org` 这样使用淘宝镜像

**Comment by pcjgithub** [comment]
这个我遇到过，好像node版本不行，我把node版本降低一下就好了，还要安装Python环境（我也是win10才出的bug）

**Comment by PanJiaChen** [comment]
太久没回复 先close
