### ISSUE TITLE
建议出一个不带国际华的版本

### ISSUE THREAD

**Issue by tonalll** [PanJiaChen/vue-element-admin#1642]
文档上面说的
移除国际化

在 src/main.js 中移除 import i18n from './lang' 并且删除 src/lang 文件夹。

并在 src/layout/components/Levelbar、src/layout/components/SidebarItem、src/layout/components/TabsView 等文件夹中 移除 this.$t('route.xxxx') 使用国际化的方式。

结果并没有取消，而且项目报错跑不起来了。

细看相关组件，发现里面有调用国际华方法，要修改的地方有很多。

建议出一个仅中文版的，不带国际化

**Comment by PanJiaChen** [comment]
这个可以有。

**Comment by xzqyun** [comment]
实际上你只需要把在lang/index 里面把en es 两个语言干掉，只留下一个zh，在下面new的 VueI18n实例里面的locale 默认成zh就可以了.

**Comment by Lxjazni7** [comment]
> 实际上你只需要把在lang/index 里面把en es 两个语言干掉，只留下一个zh，在下面new的 VueI18n实例里面的locale 默认成zh就可以了.

还有app.js

**Comment by wayne-xuli** [comment]
如果是在基础版的基础上开发，只要在mian.js里import locale from 'element-ui/lib/locale/lang/en'中en改成zh-CN就可以了

**Comment by PanJiaChen** [comment]
已更新。

默认 master 将不带有国际化。
有国际化需求的请使用 i18n 分支。

**Comment by 89360944** [comment]
@PanJiaChen  不带国际化才应该作为分支 ：）
多语言都是次要的，主要是文字信息便于维护，这是开发和运维中不可避免的必须工作，大部分人和大部分情况都应该要面对这个的。
