### ISSUE TITLE
userInfo中roles为空会无限制调用userInfo接口

### ISSUE THREAD

**Issue by ydykid** [PanJiaChen/vue-element-admin#1643]
在permissions.js中，使用roles.length === 0判断是否拉取到用户信息。
如果后端给的roles为空，这个地方就会无休止地去拉取用户信息。。。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/c0f378e50a1d7bb7e2be1f365ba414ef31340988/src/store/modules/user.js#L72-L76

已经做了判断了。
