### ISSUE TITLE
npm install时出错

### ISSUE THREAD

**Issue by wulw** [PanJiaChen/vue-element-admin#1644]
![qq 20190227130902](https://user-images.githubusercontent.com/27892974/53467453-3ed00580-3a91-11e9-9c4a-cd1036f0fa47.png)

请问大佬 这个git的错误怎么处理

**Comment by PanJiaChen** [comment]
https://juejin.im/post/5b1f31f7f265da6e1a603e1e

遇到问题请先随手查一查。
