### ISSUE TITLE
IE10不兼容白屏，我引入了babel-polyfill 也不行

### ISSUE THREAD

**Issue by huiofe** [PanJiaChen/vue-element-admin#1645]
webpack.base.conf和main.js 里面都配置了

webpack.base.conf
module.exports = {
  context: path.resolve(__dirname, '../'),
  entry: ["babel-polyfill","./src/main.js"]
} 

mian.js
import 'babel-polyfill'
import Vue from 'vue'
import 'normalize.css/normalize.css'  // A modern alternative to CSS resets

![default](https://user-images.githubusercontent.com/29764938/53487381-69888100-3ac6-11e9-8caf-9e77b4246b5f.png)
![1](https://user-images.githubusercontent.com/29764938/53487383-6a211780-3ac6-11e9-9758-0ee2ecbcc4e4.png)

babel-polyfill  都没有生效，求大神帮忙
@PanJiaChen

**Comment by Arrluo** [comment]
webpack.base.conf 配置 babel-polyfill
entry: {
    app: ['babel-polyfill', './src/main.js']
}
再安装 babel-polyfill 依赖即可
npm install --save babel-polyfill

**Comment by huiofe** [comment]
@Arrluo 感谢你的帮助，我找到问题了，到最后发现是因为我在 vue 的prototype上绑定了axios 导致转义失败，我猜测是由于原型上的 Promise 无法转义，具体的我也不太清楚。。

**Comment by family2hu** [comment]
一定是某个第三方依赖，我也找了半天，终于找到了~~

**Comment by xiaopenggithub** [comment]
大佬，兼容解决了吗？我也遇到ie11不兼容问题？不知道怎么配置，没有webpack.base.conf这个文件

**Comment by wdj577** [comment]
> 一定是某个第三方依赖，我也找了半天，终于找到了~~
请问怎么解决的？我的也没有webpack.base.config这个文件
