### ISSUE TITLE
npm install err

### ISSUE THREAD

**Issue by BobSadan** [PanJiaChen/vue-element-admin#1646]
Hi, I try to npm install this project, but is appearing stopped and errors.
![npmerror](https://user-images.githubusercontent.com/30033641/53536984-58318a00-3b43-11e9-86e7-26237578c871.jpeg)

**Comment by PanJiaChen** [comment]
Your screenshot shows only warning and no errors are displayed.

**Comment by guwan** [comment]
昨晚我可以install,今天换台电脑,我也无法install了,出现如下错误:
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t git://github.com/adobe-webplatform/eve.git
npm ERR!
npm ERR! fatal: read error: Invalid argument
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     d:\user\****\Application Data\npm-cache\_logs\2019-03-01T02_31_42_104Z-debug.log

[2019-03-01T02_31_42_104Z-debug.log](https://github.com/PanJiaChen/vue-element-admin/files/2917692/2019-03-01T02_31_42_104Z-debug.log)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1407
