### ISSUE TITLE
请问 下面这种需求,  这系统的路由配置还能用吗?改如何修改比较好?

### ISSUE THREAD

**Issue by lxk0301** [PanJiaChen/vue-element-admin#1647]
![tim 20190228155412](https://user-images.githubusercontent.com/21308593/53550382-8928b380-3b71-11e9-982f-040c670098d9.png)

我现在 要 改成截图 这种路由的  ,顶部上面三个是大的路由,  然后 第一个大的路由,  又包含左边的路由,,第二个大的,第三个大的路由,  就都好一点 , 直接一个页面了.
这种需求 ,  这系统的路由配置改如何修改呢?

**Comment by jiuwuxiaohun** [comment]
也喜欢这种,自己技术不够啊,,,老大可以参考下d2-admin的项目,把那项目里面的动态设定菜单的功能整合下

**Comment by lxk0301** [comment]
> 也喜欢这种,自己技术不够啊,,,老大可以参考下d2-admin的项目,把那项目里面的动态设定菜单的功能整合下

行,  我去看看

**Comment by PanJiaChen** [comment]
其实和这个类似 https://github.com/PanJiaChen/vue-admin-template/issues/123

暂时应该没空搞这个。
