### ISSUE TITLE
运行时node_modules报了一个警告，node_modules删了重新npm install还是一样，请问问题出在哪里？

### ISSUE THREAD

**Issue by zsrzsrzsr-zsr** [PanJiaChen/vue-element-admin#1648]
WARNING  Compiled with 1 warnings                                                                        16:41:12
 warning  in ./node_modules/vue-datetime/dist/vue-datetime.js

Module not found: Error: Can't resolve 'weekstart' in 'C:\vue-element-admin-master\node_modules\vue-datetime\dist'

**Comment by PanJiaChen** [comment]
https://github.com/mariomka/vue-datetime/issues/112

和本项目无关。
