### ISSUE TITLE
刷新404

### ISSUE THREAD

**Issue by vcoderlele** [PanJiaChen/vue-element-admin#1649]
在打开的选项卡右击，点击刷新按钮会跳转到404页面

**Comment by PanJiaChen** [comment]
没能重现。
请提供具体重现步骤。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/48e47e86f176ac63b420331dfb5e56211c720a35#commitcomment-32528043
