### ISSUE TITLE
怎么才能完全删除mock.js,更换成ajax的真实后台数据呢

### ISSUE THREAD

**Issue by pcjgithub** [PanJiaChen/vue-element-admin#165]
vue新手，怎么才能完全删除mock.js,更换成ajax的真实后台数据呢？我想按照现有的这个作为模板，但是删除mockjs之后没办法遍历出来路由

**Comment by PanJiaChen** [comment]
mock.js 和路由没有关系。
而且二次开发推荐使用[vueAdmin-template](https://github.com/PanJiaChen/vueAdmin-template)
删除这段就可以[代码](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/main.js#L21)
之后自己去api文件夹改自己的api

**Comment by toeasy** [comment]
借此问题再问下：真实项目的后端跟前端是同一服务器（同源请求），后端提供api接口，前端通过api去获取后端的数据。问题来了：在此项目工程结构下看不到后台的代码，如何把后台（java、node任意）集成进来。能否给些vue / element前后端整合的工程化结构实践参考，谢谢！

**Comment by PanJiaChen** [comment]
@toeasy 
前后端协调问题:不管前后端是否分离，后端都应该出一个api接口文档吧，或者自动生成，各大公司都有自己的api平台，我司在用的是[swagger](https://swagger.io/),其实我之前的文章也提到过这方便的问题[地址](https://segmentfault.com/a/1190000009275424#articleHeader11)
后面一个问题不是很懂，什么叫吧后台集成进来？

**Comment by toeasy** [comment]
例如我们的很多项目是前后端同一个工程（也是前后分离的），也看了许多vue脚手架项目，包括您的，把后台的代码忽略了。最终前后端交互肯定是api,我是想知道有没有带后端代码结构的脚手架，或这方面的实践。
前端通过跨域请求不存在这个问题，这样前端和后端是两个独立项目，各自管理各自就好了。
你提供的方案webpack-dev-server和nginx反代思路挺好，可以研究研究， @PanJiaChen  
谢谢

**Comment by rognoni** [comment]
:confused: Do we have to comment this part? (我们必须评论这部分吗？) 

```javascript
import Mock from 'mockjs'
import loginAPI from './login'
import articleAPI from './article'
import remoteSearchAPI from './remoteSearch'

Mock.setup({
  timeout: '350-600'
})

// 登录相关
// Mock.mock(/\/login\/login/, 'post', loginAPI.loginByUsername)
// Mock.mock(/\/login\/logout/, 'post', loginAPI.logout)
// Mock.mock(/\/user\/info\.*/, 'get', loginAPI.getUserInfo)

// 文章相关
// Mock.mock(/\/article\/list/, 'get', articleAPI.getList)
// Mock.mock(/\/article\/detail/, 'get', articleAPI.getArticle)
// Mock.mock(/\/article\/pv/, 'get', articleAPI.getPv)

// 搜索相关
// Mock.mock(/\/search\/user/, 'get', remoteSearchAPI.searchUser)

export default Mock
```

https://github.com/PanJiaChen/vue-element-admin/blob/master/src/mock/index.js

**Comment by JessicaDinDin** [comment]
樓上有人提問~怎么才能完全删除mock.js,更换成ajax的真实后台数据呢？
然後作著你回答: 删除这段就可以代码。
可是~還是不太懂是哪段?可在說明一下嗎?

**Comment by xiaomai7758** [comment]
//main.js
if (process.env.NODE_ENV === 'development') {
  require('./mock') // simulation data
}
木有这个啊.
时间: 2018-12-12 版本: v3.9.3
main.js L:20
import './mock' // simulation data

**Comment by yangbinqiang** [comment]
4.2.1文档地址是什么

**Comment by guotanxiang** [comment]
第一步： vue.config.js
  // 这里写你调用接口的基础路径，来解决跨域，如果设置了代理，那你本地开发环境的axios的baseUrl要写为 '' ，即空字符串


`  devServer: {
    proxy: {
      '/api': {
        target: 'api url'
      }
    }
  }
`

第二步：src/config/index.js

`
  baseUrl: {
    dev: '/api/',
    pro: '/api/'
  }
`
