### ISSUE TITLE
Why store sidebar opened state in cookie?

### ISSUE THREAD

**Issue by andrewlam-mbaex** [PanJiaChen/vue-element-admin#1651]
Hi, may I know what is the reason of storing sidebar opened state both in vuex and browser cookie? Isn't it sufficient to only store it in vuex?

**Comment by PanJiaChen** [comment]
`cookie`: allows the browser to remember your user behavior, and remember your last state when you open the page next time.

`vuex`: is to better communicate and manage state.

**Comment by andrewlam-mbaex** [comment]
Thanks for the response Jia Chen :)

For the case of sidebar opened state, every time the page is refreshed or newly opened, it is always set to 0, which means it doesn't pick up the sidebar opened state from the previous session, doesn't it defeat the purpose of using cookie and is sufficient just by using veux only?

**Comment by PanJiaChen** [comment]
You can only use `vuex`.

**Comment by andrewlam-mbaex** [comment]
May I do a pull request on this?

**Comment by PanJiaChen** [comment]
I'm sorry, I might have misunderstood what you meant. 

This project will remember your last sidebar status, [online demo](https://panjiachen.github.io/vue-element-admin/#/dashboard). 

If not, it could be a bug. 
**So still need to use cookie**.
