### ISSUE TITLE
svg-sprite-loader 不试用webpack4吗？

### ISSUE THREAD

**Issue by Liuyicong-git** [PanJiaChen/vue-element-admin#1652]

**Comment by Liuyicong-git** [comment]
{
				test: /\.svg$/,
				loader: 'svg-sprite-loader',
				include: [ resolve('src/icons') ],
				options: {
					symbolId: 'icon-[name]'
				}
			},

**Comment by Liuyicong-git** [comment]
Module build failed (from ./node_modules/svg-sprite-loader/lib/loader.js):
TypeError: Cannot read property 'target' of undefined

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/980

**Comment by TwoOld** [comment]
> Module build failed (from ./node_modules/svg-sprite-loader/lib/loader.js):
> TypeError: Cannot read property 'target' of undefined

npm i svg-sprite-loader@latest -D

尝试一下，我的可以解决
