### ISSUE TITLE
树状表格和拖拽功能结合报错 

### ISSUE THREAD

**Issue by mynameismaosheng** [PanJiaChen/vue-element-admin#1655]
![ae9f8ec96859843f7397fe15f7a7186](https://user-images.githubusercontent.com/19756360/53692346-0ac64e80-3dc9-11e9-997a-0f4249cbb969.png)

**Comment by PanJiaChen** [comment]
`element` 2.7.0 支持 `tree-tale 了`。所以 `vue-element-admin`就不再自己维护 `tree-table`了。
