### ISSUE TITLE
表格数据的获取方式

### ISSUE THREAD

**Issue by AJinglalala** [PanJiaChen/vue-element-admin#166]
您好，在用您的框架时遇到几个问题想请教您
1.  表格中的数据如何设置可以从一个url中获取呢，获取的过程中如果遇到跨域问题要怎样解决呢？
2.  如果url中的数据是实时更新的，那么是否可以通过添加定时器或是使用signalR的方式来实时更新表格中的数据呢？

**Comment by PanJiaChen** [comment]
1.表格通过一个uri获取？跨域问题：见其他相关文章吧，解决方案很多。
2.实时更新如果还是通过api 请求形式的话，就做成轮训咯，不断调用 [getList](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/example/table/table.vue#L226) 就可以了

**Comment by AJinglalala** [comment]
好的  我试一试   谢谢
