### ISSUE TITLE
run build 报错：ERROR in static/js/app.2ad31ea2.js from UglifyJs Unexpected token: punc (,) [static/js/app.2ad31ea2.js:6740,11]

### ISSUE THREAD

**Issue by KouYidong** [PanJiaChen/vue-element-admin#1661]
报错信息如下：
`ERROR in static/js/app.2ad31ea2.js from UglifyJs
Unexpected token: punc (,) [static/js/app.2ad31ea2.js:6740,11]`
在网上查了之后知道是uglifyjs不支持ES6，所以编译时报错，但是用了网上的解决办法都没有办法解决，想问一下大佬有没有遇到这种问题，该怎么解决

**Comment by PanJiaChen** [comment]
究其原因，babel没配对。

**Comment by KouYidong** [comment]
@PanJiaChen 大佬，再次麻烦您一下，从您回复我babel没配对我就一直在看，现在又出现了一个问题：
SyntaxError: D:\dzy_workspace_kou\rockets\src\views\layout\components\Sidebar\Item.vue: Unexpected token (20:18)

if (icon) {
    vnodes.push(<svg-icon icon-class={icon}/>)
                         ^
}
但是我看了一下您的 vue-admin-template，那上边就是这样写的，但是没有报错，我想问一下，出现这个错也还是 babel 没配对的原因吗？

**Comment by PanJiaChen** [comment]
jsx 不支持。
究其原因babel没配对。
 
https://github.com/PanJiaChen/vue-element-admin/blob/96774060020a2d80436faf08dd1089fae5a17ff7/.babelrc#L11

**Comment by KouYidong** [comment]
@PanJiaChen 感谢大佬，十分感谢。成功了。

**Comment by panyazhong** [comment]
我最近也遇到了这个问题   我尝试了 "plugins": ["transform-vue-jsx", "transform-runtime"], 但是仍没有效果，请问要如何解决？
