### ISSUE TITLE
dragTable,如果同一个页面组件内有多个dragTable

### ISSUE THREAD

**Issue by oujin-nb** [PanJiaChen/vue-element-admin#1664]
dragTable,如果同一个页面组件内有多个dragTable,我看了下大神你的代码
`const el = document.querySelectorAll('.el-table__body-wrapper > table > tbody')[0]`
应该是只有第一个表格可以拖拽，是否应该将0变成动态值，从外部传进来比较好？

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/1666
