### ISSUE TITLE
左侧边栏多级菜单且字数较多时,无法显示全面

### ISSUE THREAD

**Issue by jkga007** [PanJiaChen/vue-element-admin#1665]
能否增加左侧菜单栏的拉伸功能？鼠标hover后并且菜单字体浮动在屏幕上方
目前固定180px宽度,请大神赐教

**Comment by tuandm** [comment]
Is it $sideBarWidth in https://github.com/PanJiaChen/vue-element-admin/blob/master/src/styles/variables.scss ?

**Comment by jkga007** [comment]
> Is it $sideBarWidth in https://github.com/PanJiaChen/vue-element-admin/blob/master/src/styles/variables.scss ?

我用的版本是3.9.0 ,您说的按我理解是方便修改宽度,通过$sideBarWidth在该css的配置；
我想像的是左侧菜单栏可以主动拉伸宽度，而不是固定宽度

**Comment by PanJiaChen** [comment]
侧边栏拉伸功能是一个比较小众或者业务针对性比较强的功能，一般情况下侧边栏的宽度都是定死的。
所以暂时也不会做这个功能，有需求的请自行完成。欢迎PR

**Comment by favorer** [comment]
我也遇到了，切换中英文时，英文菜单的宽度都比较长，显示不完整。寻求解决方式。

**Comment by PanJiaChen** [comment]
自己调整 `$sideBarWidth`

**Comment by DeluxeYang** [comment]
如果可以拖拽宽度就太好了，或者过长的标签，或者加上overflow tip
