### ISSUE TITLE
vue-admin-template 项目切换路由会刷新页面，vue-element-admin项目却不会刷新

### ISSUE THREAD

**Issue by Even-Lau** [PanJiaChen/vue-element-admin#1670]
您好，

vue-admin-template 项目切换路由会刷新页面，vue-element-admin项目却不会刷新，

请问这两种方法分别是如何实现的？

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/tags-view.html#%E5%BF%AB%E6%8D%B7%E5%AF%BC%E8%88%AA-%E6%A0%87%E7%AD%BE%E6%A0%8F%E5%AF%BC%E8%88%AA
