### ISSUE TITLE
菜单 scrollbar滚动问题

### ISSUE THREAD

**Issue by Erik5169** [PanJiaChen/vue-element-admin#1675]
左侧菜单初始菜单量比较少的话， 滚动条不显示， 但是当菜单展开后超出滚动区域的时候，滚动条还是不显示， 不过菜单可以滚动，但是改变浏览器的窗口后，滚动条立马显示了

**Comment by PanJiaChen** [comment]
请提供重现gif。
目前侧边栏滚动条是hover才会出现。

**Comment by Erik5169** [comment]
![bar](https://user-images.githubusercontent.com/25293699/53942558-0fa33f00-40f6-11e9-88e8-21529423ad77.gif)

**Comment by Erik5169** [comment]
裤衩哥， gif图片你看一下

**Comment by PanJiaChen** [comment]
暂时用了一个比较脏的办法来hack。

https://github.com/PanJiaChen/vue-admin-template/pull/296

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/1853
