### ISSUE TITLE
裤哥求助，打包文件多了一个eLi文件夹，有一个js读取不到，怀疑是因为以.开头的

### ISSUE THREAD

**Issue by snowyme** [PanJiaChen/vue-element-admin#1676]
![image](https://user-images.githubusercontent.com/13547390/53941248-98b87700-40f2-11e9-939f-40480e2bb91b.png)

**Comment by PanJiaChen** [comment]
请用正确的姿势提问。

**Comment by snowyme** [comment]
解决了，因为在linux中.开头的是隐藏文件，访问不了。加个前缀就好了
![image](https://user-images.githubusercontent.com/13547390/53942499-e84c7200-40f5-11e9-946f-0fdb10884847.png)
