### ISSUE TITLE
tag切换菜单不高亮

### ISSUE THREAD

**Issue by zjh726** [PanJiaChen/vue-element-admin#1679]
![image](https://user-images.githubusercontent.com/17276674/53948839-ade9d180-4103-11e9-8ec2-1f991c86436e.png)

tag切换时菜单不能高亮

**Comment by PanJiaChen** [comment]
这并不是我的显示demo，所以我不能重现。
请提供一个可重现步骤或者demo。

**Comment by zjh726** [comment]
好的，谢谢大佬回复[鞠躬]
因为我是照着大佬的demo改的，中间不知道改了什么导致这个问题，所以想请教下大佬知道是哪里控制这一块的么？

**Comment by PanJiaChen** [comment]
侧边栏高亮和路由关联。
