### ISSUE TITLE
左侧样式

### ISSUE THREAD

**Issue by nevermind123456** [PanJiaChen/vue-element-admin#168]
左侧样式是sidebar.scss 文件吗？我把这个文件引进来但是并没有实现点击收回的效果啊

**Comment by nevermind123456** [comment]
是我自己没有改相应的sidebar.vue 和Layout.vue文件。改过之后已经好了

**Comment by nevermind123456** [comment]
请问一下  为什么左边的样式我改不了呢？我发现左侧的那个小图标太靠右了  想把小图标往左挪一点，可是怎么都动不了那个图标的

**Comment by PanJiaChen** [comment]
`.sidebar-container .svg-icon` 不就是css么

**Comment by nevermind123456** [comment]
在哪个文件里面设置的呢？没有看到啊

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/a3b1dd81fd03fbf6e6a3aeb05e61982272f159ec/src/styles/sidebar.scss#L7
