### ISSUE TITLE
Any plan for tests application?

### ISSUE THREAD

**Issue by tuandm** [PanJiaChen/vue-element-admin#1680]
Hi @PanJiaChen, is there any plan to apply tests to this project? It's great if the project can be covered by tests in some parts (main functions and components).

**Comment by PanJiaChen** [comment]
In [v4.0](https://github.com/PanJiaChen/vue-element-admin/pull/1291) has add jest and some test cases.

**Comment by tuandm** [comment]
It's awesome, can't wait to see this update. I tried to add some tests to my repo but it's not easy :). Thank you so much.
