### ISSUE TITLE
依赖包安装出错

### ISSUE THREAD

**Issue by EVEN168** [PanJiaChen/vue-element-admin#1681]
请大神指教，公司的项目没有这么多依赖包，可以正常跑起来没问题，这个一安装就报错![default](https://user-images.githubusercontent.com/10571833/54012394-e398c400-41b0-11e9-94c1-fdabb67138d9.png)
下面是错误日志
![default](https://user-images.githubusercontent.com/10571833/54012753-ff509a00-41b1-11e9-901f-fd8437b6bb2a.png)

**Comment by cactus-x** [comment]
Same as above

**Comment by shu15172353123** [comment]
我也出现了这个问题
