### ISSUE TITLE
tinymce编辑时候自动跳到第一行最左边， 无法正常编辑

### ISSUE THREAD

**Issue by Evan-Liao** [PanJiaChen/vue-element-admin#1682]
![微信截图_20190309105716](https://user-images.githubusercontent.com/43663210/54065315-35495900-425a-11e9-86ca-201af522a020.png)

**Comment by PanJiaChen** [comment]
无法重现你的问题。
请提供可重现步骤或者 `gif` 或者 `视频`。

**Comment by Evan-Liao** [comment]
sorry，检查了代码，是我这边代码的问题。content变化的时候，调用了this.$refs.xxx.setContent()，造成了死循环，光标不断跳到首行最开头位置，感谢回复~~~
