### ISSUE TITLE
npm run build:sit后在本地只能打开登录页面，其它页面打不开

### ISSUE THREAD

**Issue by kongdexiaochina** [PanJiaChen/vue-element-admin#1683]
请问大神，我打包用npm run build:sit 打包后，在本地点击index.html只能进入登录页面，但是输入用户名跟密码后点击登录按钮一直没页面不跳转。我在config->index.js中的  build下面的assetsPublicPath改为“./”加了个“.”  以前的项目我是直接npm run build打包后双击index.html就可以把项目打开的，为什么这个不行呢？求大神帮忙解答？很着急啊，谢谢

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1030

**Comment by Wbqqqq** [comment]
@kongdexiaochina  一样的问题，想请教一下 之后是如何解决的。。。。

**Comment by SuperZiLu** [comment]
@PanJiaChen 大佬 我是用npm run build:prod 打包的 但是我在本地打开dist/index 文件后一开始显示空白 后面我在网上看到有人把vue.config.js文件下面的publicPath改成了'./'  就加了一个"." 果然能打开界面了 但是点击登录不能跳转 服务器的登录接口也调成功了 基本问题应该跟@kongdexiaochina差不多 我看你引用了#1030这个问题 但是我看了 没看懂 能具体告诉我原因跟解决方法嘛？多谢。

**Comment by zhaoyoushuai** [comment]
> @PanJiaChen 大佬 我是用npm run build:prod 打包的 但是我在本地打开dist/index 文件后一开始显示空白 后面我在网上看到有人把vue.config.js文件下面的publicPath改成了'./' 就加了一个"." 果然能打开界面了 但是点击登录不能跳转 服务器的登录接口也调成功了 基本问题应该跟@kongdexiaochina差不多 我看你引用了#1030这个问题 但是我看了 没看懂 能具体告诉我原因跟解决方法嘛？多谢。

我遇到了跟你一样的情况，请教下解决了吗

**Comment by zhaoyoushuai** [comment]
> @PanJiaChen 大佬 我是用npm run build:prod 打包的 但是我在本地打开dist/index 文件后一开始显示空白 后面我在网上看到有人把vue.config.js文件下面的publicPath改成了'./' 就加了一个"." 果然能打开界面了 但是点击登录不能跳转 服务器的登录接口也调成功了 基本问题应该跟@kongdexiaochina差不多 我看你引用了#1030这个问题 但是我看了 没看懂 能具体告诉我原因跟解决方法嘛？多谢。

我遇到了跟你一样的情况，请教下解决了吗

**Comment by zhaoyoushuai** [comment]
我遇到了跟楼上一样的情况，请教下解决了吗
