### ISSUE TITLE
the :export directive is the magic sauce for webpack

### ISSUE THREAD

**Issue by 2017coding** [PanJiaChen/vue-element-admin#1687]
:export {
  menuText: $menuText;
  menuActiveText: $menuActiveText;
  subMenuActiveText: $subMenuActiveText;
  menuBg: $menuBg;
  menuHover: $menuHover;
  subMenuBg: $subMenuBg;
  subMenuHover: $subMenuHover;
  sideBarWidth: $sideBarWidth;
}
你好，请问这段是在哪里配置的呀，找了好久没找到

**Comment by PanJiaChen** [comment]
https://www.bluematador.com/blog/how-to-share-variables-between-js-and-sass
