### ISSUE TITLE
如何改title

### ISSUE THREAD

**Issue by zwbckmy** [PanJiaChen/vue-element-admin#1695]
![11](https://user-images.githubusercontent.com/7113870/54183687-b1080780-44df-11e9-9f8c-661802254431.png)

如图 红框内默认是 vue-element-admin 怎么改成中文标题？
谷歌了一下 package.json中的name不支持中文，请大神指点下要改哪里？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/9574643e927788826082c05db59a2f0ca458f4c3/build/webpack.dev.conf.js#L60

https://github.com/PanJiaChen/vue-element-admin/blob/9574643e927788826082c05db59a2f0ca458f4c3/build/webpack.prod.conf.js#L58

**Comment by zwbckmy** [comment]
改了这两个文件是要重启吗？我一开始也是改这两处 但是没起作用以为改错地方了

**Comment by PanJiaChen** [comment]
webpack任何配置都要重启。
话说你有时间问。。。为什么不重启一下试试呢。。

**Comment by tokenIsme** [comment]
@PanJiaChen   基础模板的index.html title 是写死的名字 希望改下哟 <%= htmlWebpackPlugin.options.title %>
