### ISSUE TITLE
menu菜单选中后当前选中菜单背景颜色怎么改变

### ISSUE THREAD

**Issue by dawayway** [PanJiaChen/vue-element-admin#1696]
裤衩哥，侧边栏menu菜单选中后当前选中菜单背景颜色怎么改变，类似这种
![1552380251(1)](https://user-images.githubusercontent.com/26194367/54186309-12cb7000-44e6-11e9-87f9-ae696ee698ef.png)
我在 variables.scss中没有看到可以修改的变量，请问，这个问题怎么改呢？

**Comment by PanJiaChen** [comment]
element-ui 默认高亮的是字不是背景。

![image](https://user-images.githubusercontent.com/8121621/54189571-0d255880-44ed-11e9-9b29-286dc29c5102.png)

**Comment by dawayway** [comment]
谢谢裤衩哥，已经解决啦。
