### ISSUE TITLE
npm install err

### ISSUE THREAD

**Issue by xiechunhao** [PanJiaChen/vue-element-admin#1697]
没有跑起来。不知道哪里错了。
undefined ls-remote -h -t https://github.com/nhnent/raphael.git
git 环境变量已经配置了

![image](https://user-images.githubusercontent.com/30240638/54218623-e38a2280-4528-11e9-9464-50145698a918.png)
![image](https://user-images.githubusercontent.com/30240638/54218698-04527800-4529-11e9-9c3b-a31599c51312.png)

**Comment by PanJiaChen** [comment]
你的核心问题是这个错误吧 `npm ERR! No git binary found in $PATH`

自己检索一下相关问题

**Comment by XiMenSaMa** [comment]
我也是同一个问题，请问解决了吗

**Comment by PanJiaChen** [comment]
看着像tui-editor 的依赖有问题。

**Comment by XiMenSaMa** [comment]
> 看着像tui-editor 的依赖有问题。

我解决了，一开始我是直接下载ZIP压缩包解压，然后npm install就报错了，后面我就把原来的删了，通过git clone的方式拉取项目，然后npm install就没有报错了。。。

**Comment by xiechunhao** [comment]
已经解决了，跟下面兄弟办法一样。
