### ISSUE TITLE
Expected '<component>' elements to have 'v-bind:is' attribute.

### ISSUE THREAD

**Issue by Luqir** [PanJiaChen/vue-element-admin#1698]
```
//  src\views\layout\components\Sidebar\Link.vue
<template>
  <!-- eslint-disable vue/require-component-is -->
  <component v-bind="linkProps(to)">
    <slot/>
  </component>
</template>
```

- 已经是加了忽略了，还是会报错。
```
[vue/require-component-is]
Expected '<component>' elements to have 'v-bind:is' attribute.
```

直接在.eslintignore中忽略这个文件也不行。但是删除了这行忽略的代码会出现两个eslint报错，但那个是eslint报错，不是eslint-plugin-vue插件报错，请问这个如何解决，处理好久了没有解决，很烦恼。

**Comment by PanJiaChen** [comment]
https://github.com/vuejs/vetur/issues/1074

这是 `vetur`的问题。这只是展示error，但实际不会报错，不会影响你的开发。

**Comment by Luqir** [comment]
是的，不影响开发，但是直接在vscode里面git提交的时候会失败，所以我暂时是不打开这个页面提交，嗯嗯，谢谢大大，我去研究下vetur

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1700

我暂时行改了下写法，兼容这个warning。

**Comment by Luqir** [comment]
感谢感谢，我一直以为我的eslint+prettier有问题...hhhh，舒服

**Comment by jonnzer** [comment]
死磕component为什么返回a，原来是用了is，少侠好操作，怒赞。

**Comment by DrCord** [comment]
Should this be closed? The original reporter's issue seems to be resolved.
