### ISSUE TITLE
The asynchronous menu is not displayed when reloading

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [PanJiaChen/vue-element-admin#1699]
An api is being used to generate the menu, but when reloading the page, the menu that is generated from the server is not displayed. You have to close the session and restart to regenerate the menu

**Comment by PanJiaChen** [comment]
Refreshing the page is the need to `gegenerate the menu`.

**Comment by leonel1524** [comment]
the files that make the request are loaded, and the request is made again to the server but the corresponding items are not shown in the menu

**Comment by Raul-mz** [comment]
> Refreshing the page is the need to `gegenerate the menu`.

Hi, this method is called only when the user to login
` GenerateRoutes({ commit }, data) {
      return new Promise(resolve => {
        const { roles } = data
        let accessedRouters
        if (roles.includes('admin')) {
          accessedRouters = asyncRouterMap
        } else {
          accessedRouters = filterAsyncRouter(asyncRouterMap, roles)
        }
        commit('SET_ROUTERS', accessedRouters)
        resolve()
      })
    }`

It is probably that this causes the error.

**Comment by EdwinBetanc0urt** [comment]
The menu is loaded in the login page before starting the session, it should be loaded after the login, for the user to send and determine the accesses to generate the menu.
