### ISSUE TITLE
401 unauthorized 情况下想刷新 token，再发起相同的请求，这样是否好？

### ISSUE THREAD

**Issue by wyudong** [PanJiaChen/vue-element-admin#17]
我想改写 utils/fetch.js，让网路请求返回 401（unauthorized） 时，也就是用户 token 过期时，自动请求刷新 token，然后以新 token 发起上一次的请求。这样做是为了即延续 token 的有效性，又不让用户重新登录。但我不清楚这样做是否可行？刷新 token 之后发起相同的请求，怎样写不至于显得啰嗦？希望能得到指点，谢谢。

```
export default function _fetch(options) {
    return new Promise((resolve, reject) => {
        const instance = axios.create({
            baseURL: process.env.BASE_API,
            headers: {
                'X-Ivanka-Token': store.getters.token
            }
        });
        instance(options).then(response => {
            const res = response.data;

            // 401 unauthorized
            if (res.code === 401) {
                refreshToken().then(response => {
                    // 得到新 token
                    const token = response.data.token;

                    //
                    // 接下去如何以新 token 发起上一次的请求？
                    //
                }).catch(error => {
                    reject(error);
                })
                reject(res);
            }

            // everything's fine
            resolve(res);
        }).catch(error => {
            reject(error);
        });
    });
}
```

**Comment by PanJiaChen** [comment]
我个人觉得在有后端支持的情况下，延续token应该给后端来做更合理，我司现在就是这样做的。
如果还是想前端来做的话，token是用vuex管理的，所以
store.dispatch('refreshToken').then(() => {
  //重新请求
 _fetch(options)就好了
})

**Comment by wyudong** [comment]
@PanJiaChen 谢谢回复。假设由后端来刷新 token，什么情况下会刷新？是前端发起一次请求，后端发现是过期的 token，然后回给前端一个新 token 吗？这样这次请求就没拿到预期的数据。

**Comment by PanJiaChen** [comment]
我司策略是 每次一个前端请求都会续24小时， 如果过期就返回一个特殊的状态码，前端直接弹出，让其重新登录，我们觉得安全性比一些操作更重要。因为我们大部分操作其实也都做了保存，所以不会丢失太多东西。

**Comment by KelvinFanXian** [comment]
vue-auth的做法是后端设置过期时间大于2小时，前端setTimeout每2小时自动发起请求以旧的token换取新的token（Refresh token）

**Comment by KelvinFanXian** [comment]
以前自己搭过一个类似的框架，但整体结构相比较low。用了vue-auth。做法是后端设置过期时间大于2小时，前端setInterval每2小时自动发起请求以旧的token换取新的token（Refresh token）
