### ISSUE TITLE
博主是否做过菜单权限管理？

### ISSUE THREAD

**Issue by wqb2017** [PanJiaChen/vue-element-admin#170]
![33333333333333333333png](https://user-images.githubusercontent.com/25101583/29521594-c0a68be4-86b8-11e7-879f-38e6d1a3e47a.png)

我现在要做的一个功能点是：
1、选中左边的权限，右边的只读不做处理
2、取消左边的权限，右边只读取消勾选
3、选中右边的只读，左边的权限勾选
4、取消右边的只读，左边权限不做处理

博主有做过类似的功能点吗？能否提供解决的思路？多谢！

**Comment by PanJiaChen** [comment]
通过自定义节点内容 生成一个checkbox 
通过判断当前node.id是否包含在 `current-node-key`中
