### ISSUE TITLE
v-waves bug fixed

### ISSUE THREAD

**Issue by jsjzh** [PanJiaChen/vue-element-admin#1704]
问题
- 在使用 v-waves 的时候，起初设置 v-waves="{color: 'red'}"，之后热更新更改 color 的值为 v-waves="{color: 'blue'}" 没有生效

思考
- 颜色没有更改是因为没有在组件 update hook 的阶段重新赋值

解决
- 添加 update hook，在更新的时候重新赋值

附加
- 因为要在 update 阶段重新绑定点击函数，遂增加了一个上下文 '@@wavesContext'，里面保存点击事件对应的移除事件函数
- 在 update 阶段先移除上一次的点击事件，再进行绑定，另外，该移除函数在 unbind hook 阶段也要调用一次，执行完毕之后执行内存销毁

**Comment by PanJiaChen** [comment]
欢迎pr。
