### ISSUE TITLE
npm安装的时候老提示

### ISSUE THREAD

**Issue by 1055031918** [PanJiaChen/vue-element-admin#1706]
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/sohee-lee7/Squire.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-03-13T07_26_33_371Z-debug.log

**Comment by LiuZiqi-dual** [comment]
环境变量

**Comment by 1055031918** [comment]
是因为git的问题   找到了

**Comment by zm52hz** [comment]
请问是怎么解决的？
