### ISSUE TITLE
npm install git 报错

### ISSUE THREAD

**Issue by liyoy** [PanJiaChen/vue-element-admin#1708]
node : 10.15.0
npm : 6.4.1
nrm: https://registry.npm.taobao.org/

npm 安装依赖时报以下错
![QQ截图20190313191846](https://user-images.githubusercontent.com/23376936/54275979-0b2fc800-45c7-11e9-9754-d0c02150cf56.png)

找了好多资料都没找到解决办法，请大佬帮老看看吧！谢谢呀！

**Comment by liyoy** [comment]
可能是git版本问题，换了一台电脑就可以了

**Comment by PanJiaChen** [comment]
安装失败大部分都是自己环境问题导致的，每个人或者说每台机器都不太一样。遇到问题把报错信息检索一下相关问题。
