### ISSUE TITLE
请问怎么生成不在侧边栏显示的router呢？比如详情页

### ISSUE THREAD

**Issue by haihuilai123** [PanJiaChen/vue-element-admin#171]
如题

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/router/index.js#L13

**Comment by lllsmiling** [comment]
那么跳转后怎么选中跳转之前的菜单？hidden菜单要设置成跳转之前选中菜单的子菜单？

**Comment by lllsmiling** [comment]
就比如有个文章管理的菜单，进入一个页面以后，页面内有个添加按钮，点击添加按钮进入一个添加文章的页面，但是这时候菜单其实还是选中的文章管理的菜单。

**Comment by lllsmiling** [comment]
好吧，还是没描述清楚么……
1、有一个菜单我设置了hidden，然后左侧就不会显示了。
2、我想做到的是进入这个隐藏的菜单地址，但是还想在左侧菜单中选中一个菜单。

**Comment by PanJiaChen** [comment]
暂时 `element` 官方并没有提供手动set高亮的接口，日后可能会有。
目前的解决方案有两种
1. 现在 `default-active` 设置是根据 `$route.path`来的，这样设置是不能满足你的需求的，所以你可以在router里面自定义一个字段来实现你要的效果。
2.简单点，就是在进入你隐藏的页面的时候操作menu的dom给它加上一个active的class

**Comment by lllsmiling** [comment]
好的，多谢了……

**Comment by leeycode** [comment]
您好，我通过操作dom的方式，在侧边栏实现高亮，但是点击收缩侧边栏，再打开的时候类名就丢失了，请问这是什么原因呢？
进入页面高亮侧边栏：
` mounted () {
         document.getElementById('account').classList.add('nav-active');
    },`
![_15320734123731](https://user-images.githubusercontent.com/20038428/42990689-0000bcb4-8c36-11e8-9d41-3f55d11eb425.png)
点击导航栏的收缩侧边栏按钮然后再展开：
![qq 20180720160454](https://user-images.githubusercontent.com/20038428/42990910-b1d90306-8c36-11e8-87e6-1421e85b451c.png)

**Comment by gengchen528** [comment]
目前这个问题有好的解决办法了吗？

**Comment by gengchen528** [comment]
`
defaultActive() {
      console.log('/' + this.$route.path.split('/'))
      return '/' + this.$route.path.split('/')[1]
    },
`
目前定义defaultActive为这样发现可以，只匹配父路由来决定是否高亮

**Comment by azhai** [comment]
假设左侧的导航最多两层

* 交易管理 (/trade)
     * 产品列表 (/trade/product)
         * 查看产品  **hidden** (/trade/product/detail/:id)
         * 编辑产品  **hidden** (/trade/product/edit/:id)
     * 订单列表 (/trade/order)
         * 查看订单  **hidden** (/trade/order/detail/:id)
         * 编辑订单  **hidden** (/trade/order/edit/:id)
* 其他管理 (/other)

要让访问 查看产品/编辑产品 页面时，菜单高亮在 产品列表 上
可以修改这里 src/layout/components/Sidebar/index.vue 第34行开始
原来的代码是
```js
    activeMenu() {
      const route = this.$route
      const { meta, path } = route
      // if set path, the sidebar will highlight the path you set
      if (meta.activeMenu) {
        return meta.activeMenu
      }
      return path
    }
```
改为
```js
    activeMenu() {
      const route = this.$route
      const { meta, path } = route
      // if set path, the sidebar will highlight the path you set
      if (meta.activeMenu) {
        return meta.activeMenu
      }
      // get the first and second parts of path
      let n = path.indexOf('/', 1)
      if (n > 0) {
        n = path.indexOf('/', n+1)
      }
      return n > 0 ? path.substring(0, n) : path
    }
```
