### ISSUE TITLE
修改url中id后 需要2次enter或者访问才可以更新数据

### ISSUE THREAD

**Issue by youngchen1987** [PanJiaChen/vue-element-admin#1710]
问题描述：
比如说url地址是XXXx?id=1  然后我手动修改成id=2  然后enter   没有刷新数据，也没有掉接口，再enter一下  才会刷新页面 重新获取数据

**Comment by PanJiaChen** [comment]
没有重现你的问题，其提供demo或者gif等可还原步骤。

**Comment by Lionad-Morotar** [comment]
@youngchen1987 修改URL哈希后需要两次enter才能刷新页面, 这个是浏览器的功能特征
