### ISSUE TITLE
utils 里面的 param2Obj 似乎无法处理带空格的param值

### ISSUE THREAD

**Issue by OtaconBYF** [PanJiaChen/vue-element-admin#1711]
utils 里面的 param2Obj 似乎无法处理带空格的param值，会把空格变加号。
加了一行 .replace(/\+/g, ' ')  解决
请问这个是bug还是feature >.<

**Comment by PanJiaChen** [comment]
有test case 例子么

**Comment by byf1987** [comment]
https://jsfiddle.net/71tvs4op/6/

前提是空格是encode成加号的情况，https://stackoverflow.com/questions/2678551/when-to-encode-space-to-plus-or-20

**Comment by PanJiaChen** [comment]
我看了，的确没处理这种情况。

欢迎提pr。

**Comment by OtaconBYF** [comment]
十分感谢！
