### ISSUE TITLE
How to display landing page before goto login page

### ISSUE THREAD

**Issue by ndphuong** [PanJiaChen/vue-element-admin#1714]
Hi

I want view a landing at the first time user visit, then we have register, login...

How to do that?

many thanks

**Comment by PanJiaChen** [comment]
But how do you know if the user is registered?

**Comment by ndphuong** [comment]
@PanJiaChen 
I mean we will display Login button on landing page
We always show landing page when user visit site (don't need care about registered or unregistered users)

**Comment by PanJiaChen** [comment]
The page's jump logic control is here.

https://github.com/PanJiaChen/vue-element-admin/blob/master/src/permission.js

You can adjust the logic according to your needs.

**Comment by ndphuong** [comment]
@PanJiaChen 
Do you have any landing page template create by vue element ?

**Comment by kirbiyik** [comment]
Hi @ndphuong, I created a class project based on this template. It has landing page and directs to login or sign up. Feel free to use that. 
https://github.com/bounswe/bounswe2018group6/tree/master/frontend
Deployed version: http://cultidate.ml/#/

**Comment by ndphuong** [comment]
@kirbiyik 
Very nice, thank you
I think we should add this landing page to this repository

**Comment by kirbiyik** [comment]
You're welcome @ndphuong, it's up to author's decision I could make a PR if it is requested. @PanJiaChen I think you can close this issue since sufficient example is provided.

**Comment by PanJiaChen** [comment]
I don't think that the landing page is a general requirement. If you have a requirement, you can add it yourself.
