### ISSUE TITLE
创建新角色用户，第一次登录404

### ISSUE THREAD

**Issue by toKnowMore** [PanJiaChen/vue-element-admin#1715]
创建新角色用户时，这个用户和admin有不同的权限，第一次登录跳转到404页面，但是点击进入首页之后，再次退出、登录就没有这种现象了，请问，为啥第一次进入404，明明redirect是dashboard

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/54405538-ebf18180-4711-11e9-937b-e46a3f795360.png)


确定一下登录要进入的页面是否有权限。

还有问题请提供一个在线可还原demo。

**Comment by toKnowMore** [comment]
我明白了，一个是admin权限，另一个是普通权限，普通权限不能创建用户。我正是在admin创建用户界面时退出，此时的redirect还是创建用户的页面的路由，而其它权限不能看到这个页面，因此404
