### ISSUE TITLE
script-loader是安装在dependencies里还是devDependencies里？

### ISSUE THREAD

**Issue by ruanhuhu** [PanJiaChen/vue-element-admin#1716]
问题1. 看到Export2Excel的介绍 [Excel 导出](https://panjiachen.github.io/vue-element-admin-site/zh/feature/component/excel.html#excel-%E5%AF%BC%E5%87%BA)
npm install script-loader -S -D  
但是看github仓库中，package.json文件中的dependencies字段并没有script-loader
有点不明白它的运作时间？因为不是是懒加载，是在打包后动态加载的么？所以按道理是应该在devDependencies里也有？

问题2. 懒加载Export2Excel后，下面的then中的第一个参数为什么是excel实例?
import('@/vendor/Export2Excel').then(excel => {
  excel.export_json_to_excel({
    header: tHeader, //表头 必填
    data, //具体数据 必填
    filename: 'excel-list', //非必填
    autoWidth: true, //非必填
    bookType: 'xlsx' //非必填
  })
})

**Comment by ruanhuhu** [comment]
但是好像即使npm install script-loader -S安装后，script-loader也没有在package.json的dependencies字段里？这是为啥？

**Comment by PanJiaChen** [comment]
你问的问题都能检索到。

- 问题一

`-D: devDependencies`

https://github.com/PanJiaChen/vue-element-admin/blob/f38d5810d91101c1ec38f1270c57302bfdf92a0f/package.json#L106

- 问题二 
https://webpack.js.org/api/module-methods/#import-1

**Comment by ruanhuhu** [comment]
> 你问的问题都能检索到。
> 
> * 问题一
> 
> `-D: devDependencies`
> 
> [vue-element-admin/package.json](https://github.com/PanJiaChen/vue-element-admin/blob/f38d5810d91101c1ec38f1270c57302bfdf92a0f/package.json#L106)
> 
> Line 106 in [f38d581](/PanJiaChen/vue-element-admin/commit/f38d5810d91101c1ec38f1270c57302bfdf92a0f)

可是为什么-S的话这个模块在package.json 的 dependencies 字段里没有？
![npm install script-loader -S -D](https://user-images.githubusercontent.com/3184110/54434253-cb084b00-4768-11e9-8b28-541ded5288bf.png)
npm install script-loader -S -D 不是在生产devDependencies和开发dependencies环境都安装吗？

**Comment by PanJiaChen** [comment]
这种问题你自己去查一下npm文档不就知道了。

**Comment by ruanhuhu** [comment]
![image](https://user-images.githubusercontent.com/3184110/54439419-b8474380-4773-11e9-93fb-23b610c39010.png)
额，看了，真的不知道是哪个部分没注意到。
就是对执行npm install script-loader -S -D安装script-loader包后，package.json的dependencies字段为什么没有script-loader不明白。
大侠如果知道，还请给点提示吧～

难道是说以及没有-S这个选项了，变成-P的原因么？
另外我觉得script-loader应该是要打包进生产环境代码里的吧，所以我纠结为什么dependencies字段没有script-loader。

不好意思，打扰大佬了。

**Comment by PanJiaChen** [comment]
我看了下文档

> npm install saves any specified packages into dependencies by default. 

install 了就会自动 save 和 `yarn`一样了。

`-S` 的确没用了 我去改一下文档。

`script-loader`作用只是让他全局引入而已，所以只有打包的时候需要，放到`devDependencies`就够了。

**Comment by ruanhuhu** [comment]
嗯 谢谢谢谢解惑~
