### ISSUE TITLE
登录传参问题

### ISSUE THREAD

**Issue by hertough** [PanJiaChen/vue-element-admin#1719]
想请问登录时request只传入username和password我想传入其他参数在那个文件里写呢，我在login组件的index.vue没有loginform和login.js都传递了但是还是没有传递成功

**Comment by PanJiaChen** [comment]
`this.$store.dispatch('LoginByUsername', this.loginForm)`

点击登录的时候调用的是这个，所以会先去执行 `vuex`里面相应的`action`，然后`action`再调用 api的。
