### ISSUE TITLE
给作者的一些建议

### ISSUE THREAD

**Issue by liyuan900226** [PanJiaChen/vue-element-admin#1720]
看了这个框架，界面真的很不错，比我之前的漂亮多了，但是还是发现了一些问题：1、路由没有使用懒加载，首次加载页面的时间很长。2、为什么不把axios封装一下，然后绑定到Vue原型上，这样在vue实例中直接通过this.就可以调用。3、项目中的axios请求都放在了api文件夹下，感觉这个模块化优点麻烦，每次都要调用request包，直接把请求写在组建里面多好啊

**Comment by PanJiaChen** [comment]
首先感谢你的建议。

1. 路由使用了懒加载，而且也进行了拆包处理。

2，3. axios的问题之前也就是过，个人喜好的问题。而且项目大了之后模块化是有好处，。比如有些接口会在多个页面公用。
