### ISSUE TITLE
登录后不跳转弹错没有信息问题

### ISSUE THREAD

**Issue by hertough** [PanJiaChen/vue-element-admin#1721]
你好，我拿到了后台返回token，点击登录不跳转，弹出的错误框只有×号没有具体错误提示怎么回事

**Comment by PanJiaChen** [comment]
请用正确的姿势提问。

**Comment by xyhuxin** [comment]
大神，我也遇到和他一样的问题，这个是报错链接，如下：
https://user-images.githubusercontent.com/31687962/57937294-36e96a00-78f8-11e9-94b7-b977f1a82842.png，求解答？
