### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by SunnyZhX** [PanJiaChen/vue-element-admin#1722]
2843 error code 1
2844 error Command failed: G:\Git\bin\git.EXE submodule update -q --init --recursive
2844 error fatal: G:/Git/mingw64/libexec/git-core\git-submodule cannot be used without a working tree.
2845 verbose exit [ 1, true ]

**Comment by SunnyZhX** [comment]
重装了几个版本的git还是会不行~~

**Comment by PanJiaChen** [comment]
你能把完整的命令行截一下么？

**Comment by SunnyZhX** [comment]
![image](https://user-images.githubusercontent.com/36977577/54492648-71885380-4903-11e9-8dbd-cc30680efe6a.png)

**Comment by PanJiaChen** [comment]
`git-submodule` 你为什么会用到这个？

你试试新开一个目录，不要放在 vue-project 下面，重新再拉一边项目。

**Comment by SunnyZhX** [comment]
奇怪，换个目录也不行。难道是git配置的有问题？

**Comment by PanJiaChen** [comment]
这种问题一般都是个人问题，我这里重现不了，也提供不了什么帮助。

**Comment by SunnyZhX** [comment]
但是template这个 项目是可以成功安装的

**Comment by dadawanan** [comment]
我也是这个问题

**Comment by SunnyZhX** [comment]
> 我也是这个问题

你解决了么

**Comment by longfeiyu127** [comment]
npm 搜了nomnom，好像已经被废弃了

**Comment by PanJiaChen** [comment]
现在是jsonlint 依赖这个，我考虑一下有什么替代方案么。

**Comment by sczhoubing** [comment]
这个问题昨天我也遇到了，我的问题是**权限**问题，之前是用windows普通帐号npm install，今天脑子一闪，用管理员权限就OK了，不过deprecated警告有点多，不知有无影响

`λ npm install                                                                                                
npm WARN deprecated runjs@4.4.2: This project has been renamed to 'tasksfile'. Install using 'npm install tas
le' instead.                                                                                                 
npm WARN deprecated microcli@1.3.3: This project has been renamed to @pawelgalazka/cli . Install using @pawel
zka/cli instead                                                                                              
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.      
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your d
dencies as this version is no longer maintained an may contain bugs and security issues.                     
npm WARN deprecated microargs@1.1.2: This project has been renamed to @pawelgalazka/cli-args. Install using @
lgalazka/cli-args instead                                                                                    
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your 
ndencies as this version is no longer maintained an may contain bugs and security issues.                    
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your 
ndencies as this version is no longer maintained an may contain bugs and security issues.                    
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old 
ax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).                      
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor. 
...     
`

**Comment by JingweiXiong** [comment]
你解决了么？我也遇到了。。

**Comment by scalerone** [comment]
npm ERR! Command failed: d:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
npm ERR! fatal: d:/Program Files/Git/mingw64/libexec/git-core\git-submodule cannot be used without a working tree.

**Comment by scalerone** [comment]
遇到这个问题+1

**Comment by scalerone** [comment]
> 2843 error code 1
> 2844 error Command failed: G:\Git\bin\git.EXE submodule update -q --init --recursive
> 2844 error fatal: G:/Git/mingw64/libexec/git-core\git-submodule cannot be used without a working tree.
> 2845 verbose exit [ 1, true ]

找到解决方案了，使用 cnpm install 就可以了

**Comment by teemoooo** [comment]
也遇到这个问题，现已解决。列出供参考。
之前使用nvm管理多版本npm，`npm install`  执行时报该错误。尝试关闭nvm，将12.14.0的路径直接写入 path ，执行成功。

**Comment by mvpyb** [comment]
我也遇到这个问题了，也是安装nvm之后才出现 的这个问题，想问下你们怎么解决的
