### ISSUE TITLE
登录跳转问题

### ISSUE THREAD

**Issue by jiudan** [PanJiaChen/vue-element-admin#1725]
import { getToken, setToken, removeToken } from '@/utils/auth'

handleLogin() {
      var _this=this;

          _this.$store.commit('SET_TOKEN', "admin");
          setToken("admin");
          _this.$router.push({ path: _this.redirect || '/' });

    }

登录设置Token为admin，能成功跳转 

src\store\modules\user.js

**Comment by jiudan** [comment]
修改src\views\login\index.vue文件

**Comment by PanJiaChen** [comment]
想表达什么？

**Comment by jiudan** [comment]
登录跑太多逻辑了

**Comment by jiudan** [comment]
我只想ajax成功就缓存跳转，简单，方便

**Comment by PanJiaChen** [comment]
`vue-admin-template` 不就是这个逻辑么。

**Comment by jiudan** [comment]
说的是vue-element-admin，
其他没安装过，不知道，
总有我这种用户想按自己的想法 修改代码，这问题 对你不是问题，对用户使用上是问题

**Comment by jiudan** [comment]
以我菜鸟知识。
我现在在本地跨域请求，不会用工具request.js跨域，
自己用jq的ajax jsonp，只能改改

**Comment by PanJiaChen** [comment]
我是开源项目，本身就不可能满足所有人需求。
而且本项目要实现路由权限管理，所以肯定会复杂。
对应你的需求，我在文档中也说明了，建议使用`vue-admin-template`。

**Comment by jiudan** [comment]
嗯，但我代码写多了，不想用别的了

**Comment by ZhuRuiHeng** [comment]
你好，我执行登录会打印两次request.js拦截器处代码，第一次请求数据，打印出来正常，运行完vuex中login方法会又打印一次，这一次是错误的，不知道是哪里执行了获取用户信息方法

**Comment by jiudan** [comment]
> 你好，我执行登录会打印两次request.js拦截器处代码，第一次请求数据，打印出来正常，运行完vuex中login方法会又打印一次，这一次是错误的，不知道是哪里执行了获取用户信息方法
> ![1](https://user-images.githubusercontent.com/28189090/54812883-300ef400-4cc7-11e9-88fe-d2a16911bbbe.png)
> 全局搜索了一下Login failed, unable to get user details.这个是mock/user.js getInfo方法返回的，这里不清楚怎么执行的getInfo

我用自己封装的axios公共方法，不是用request.js的
设置好setToken，就不会出问题

**Comment by ZhuRuiHeng** [comment]
解决了，登录成功以后全局钩子router.beforeEach中拦截路由，判断是否已获得token，在获得token之后我们就要去获取用户的基本信息了
作者详解https://juejin.im/post/591aa14f570c35006961acac

**Comment by xyhuxin** [comment]
各位大神，我遇到了这个问题，我把登录接口修改为自己所使用的接口时，发送登录请求，不报错，但是跳转不到首页，链接如下：https://user-images.githubusercontent.com/31687962/57937294-36e96a00-78f8-11e9-94b7-b977f1a82842.pn

**Comment by fzg2lj** [comment]
> import { getToken, setToken, removeToken } from '@/utils/auth'
> 
> handleLogin() {
> var _this=this;
> 
> ```
>       _this.$store.commit('SET_TOKEN', "admin");
>       setToken("admin");
>       _this.$router.push({ path: _this.redirect || '/' });
> 
> }
> ```
> 
> 登录设置Token为admin，能成功跳转
> 
> src\store\modules\user.js

大佬 我按照你说的,跳不了
