### ISSUE TITLE
Missing required prop: "chartData"

### ISSUE THREAD

**Issue by feihui2014** [PanJiaChen/vue-element-admin#1727]
![image](https://user-images.githubusercontent.com/9604618/54519694-0e99c980-49a2-11e9-928f-8b8b20fbcc17.png)
每次刷新页面, 控制台都会输出这个红点, 虽然一切都可以正常运行, 有强迫症的表示伤不起, 请问这个怎么解决呢? 后端兼职做页面发开, 所以菜鸟一枚.

**Comment by PanJiaChen** [comment]
首先报错已经说了`History.vue`中，`chartData`这个props参数是必填项。
而且这是你自己的写的组件吧。
