### ISSUE TITLE
treetable更新带有子节点的数据后展开/关闭功能失效

### ISSUE THREAD

**Issue by CuiYang16** [PanJiaChen/vue-element-admin#1728]
更新子节点数据，数据成功更新（只更新当前条，不是全部刷新，然后将返回修改的结果替换），展开的图标也可以点，但是没有展开关闭的效果。好像他的子节点已经不是他的一部分了，但是输出数据还是有子节点（新人上路，求帮忙）

**Comment by PanJiaChen** [comment]
已知问题。因为没有记住状态需要一个位移确定的 `ID`，比如`el-tree`，它就需要你提供一个确定的key。

之后修复完善一下这个问题吧。

**Comment by PanJiaChen** [comment]
@Liugq5713

**Comment by CuiYang16** [comment]
> 已知问题。因为没有记住状态需要一个位移确定的`ID`，比如`el-tree`，它就需要你提供一个确定的关键。
> 
> 之后修复完善一下这个问题吧。m

> 已知问题。因为没有记住状态需要一个位移确定的`ID`，比如`el-tree`，它就需要你提供一个确定的关键。
> 
> 之后修复完善一下这个问题吧。

麻烦可以把解决办法说的稍微详细一点吗？新手有些地方不太懂，谢谢啦

**Comment by PanJiaChen** [comment]
就是现在还不支持这功能。

**Comment by wuyouhuaz** [comment]
我增加了多选框父子级联动，根据全选中、非全选中和没选中的情况去增加了checkbox的显示状态，怎么提交代码上github仓库

**Comment by PanJiaChen** [comment]
正常提pr就好了

**Comment by PanJiaChen** [comment]
`element` 2.7.0 支持 `tree-tale 了`。所以 `vue-element-admin`就不再自己维护 `tree-table`了。
