### ISSUE TITLE
搜索框不能显示

### ISSUE THREAD

**Issue by wanglunhui2012** [PanJiaChen/vue-element-admin#1729]
自己用的是vue cli 3新建的项目（不用vue cli是正常运行的），其他的都正常运行，只是点击搜索按钮时没有反应，去看了一下发现以下`\src\components\HeaderSearch\index.vue>`中的代码：
```
show(value) {
      if (value) {
        document.body.removeEventListener('click', this.close)    -------------1
      } else {
        document.body.addEventListener('click', this.close)    -------------2
      }
}
```
会执行两次,，分别执行1和2，请问是什么原因？

**Comment by PanJiaChen** [comment]
事件冒泡的问题。
```js
 <svg-icon class-name="search-icon" icon-class="search" @click.stop="click" />
```
加一个`stop`就好了。

**Comment by wanglunhui2012** [comment]
**6666666666666666666**，但为什么一下载就构建运行不会有这种现象，而用vue cli新建项目并导入代码才会出现这种现象呢？我需要配置什么吗？

**Comment by PanJiaChen** [comment]
主要是vue版本问题 vue2.6 改了一下 microtask 东西。会导致 event 的执行顺序发生以下变化。
https://github.com/vuejs/vue/issues/9478
