### ISSUE TITLE
404跳转登录

### ISSUE THREAD

**Issue by nevermind123456** [PanJiaChen/vue-element-admin#173]
404页面怎么能调转到登录页面呢？代码在哪里设置的呢？

**Comment by PanJiaChen** [comment]
不懂需求

**Comment by nevermind123456** [comment]
就是假如发生404错误，就会跳转到404页面，怎么在404页面设置一个按钮，点击按钮可以跳转到登录页面。或者说发生404错误的时候直接跳转到登录页面，这样的一个需求

**Comment by PanJiaChen** [comment]
按钮直接$router.push不就好了
错误跳转到登录
` { path: '*', redirect: '/login', hidden: true }`

**Comment by nevermind123456** [comment]
$router.push可以跳转到左边侧方的路由的任何一个页面  但是跳转不了登录页面的，好像是跟路由是有关系的

**Comment by PanJiaChen** [comment]
这肯定啊，你在登录状态，为什么要跳到登录页？
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/permission.js#L20

**Comment by goofunc** [comment]
> 这肯定啊，你在登录状态，为什么要跳到登录页？ https://github.com/PanJiaChen/vue-element-admin/blob/master/src/permission.js#L20

哥们说得有点意思
