### ISSUE TITLE
TextHoverEffect Mallki.vue有问题？ Dashboard页面宽度小于1500PX左右，会出现 上面的字 ‘vue-element-admin’消失的BUG

### ISSUE THREAD

**Issue by opohacker** [PanJiaChen/vue-element-admin#1730]
TextHoverEffect Mallki.vue有问题？ Dashboard页面宽度小于1500PX左右，会出现 上面的字 ‘vue-element-admin’消失的BUG

**Comment by PanJiaChen** [comment]
你看源码可以发现是故意隐藏的。

https://github.com/PanJiaChen/vue-element-admin/blob/e601da38d0791b3ec115741dea7e763a1e75ed35/src/views/dashboard/admin/components/BoxCard.vue#L112-L116

**Comment by opohacker** [comment]
> 你看源码可以发现是故意隐藏的。
> 
> [vue-element-admin/src/views/dashboard/admin/components/BoxCard.vue](https://github.com/PanJiaChen/vue-element-admin/blob/e601da38d0791b3ec115741dea7e763a1e75ed35/src/views/dashboard/admin/components/BoxCard.vue#L112-L116)
> 
> Lines 112 to 116 in [e601da3](/PanJiaChen/vue-element-admin/commit/e601da38d0791b3ec115741dea7e763a1e75ed35)
> 
>    @media only screen and (max-width: 1510px){ 
>      .mallki-text{ 
>        display: none; 
>      } 
>    }

谢谢大神指导
