### ISSUE TITLE
Failed to resolve async component default: Error: Loading chunk 2 failed. (error: http://localhost:3030/2.js)

### ISSUE THREAD

**Issue by Penguin-Lin** [PanJiaChen/vue-element-admin#1731]
你好，我使用了vue-admin-template。我移除了mock.js和easy-mock。使用了nodejs express作为后台。将接口定义如下，但是页面控制台一直弹出错误。以下还有nodejs控制台截图。
![image](https://user-images.githubusercontent.com/33897969/54546807-6dc9ff00-49df-11e9-996b-a56360a0f6ae.png)
![image](https://user-images.githubusercontent.com/33897969/54546894-9ce07080-49df-11e9-96ab-7a72dac75c23.png)
![image](https://user-images.githubusercontent.com/33897969/54546933-b4b7f480-49df-11e9-8004-23994f39e380.png)
而且nodejs启动后，刷新页面，会重定向到404页面。请问该怎么解决？万分谢谢。

**Comment by PanJiaChen** [comment]
loading chunk failed 大概率是 path 没设对

https://github.com/PanJiaChen/vue-element-admin/blob/715fe3e6841ef19cc36e26895e336adbbdb94db6/config/index.js#L11

重定向问题 返回的数据格式不对。

https://github.com/PanJiaChen/vue-admin-template/blob/4bbdf5ee0e92e910f266a78d8fb3a8b882e9c0c5/src/store/modules/user.js#L48-L51

**Comment by Penguin-Lin** [comment]
@PanJiaChen  path和你发的是一样的。问题描述说错。不是404页面，而是页面直接就是Cannot GET /。目前我的修改只是移除了easy-mock，mock，其他没有动过。当main.js重新引入mock时，是没有问题的。另外我console.log()了一下，node后台下user.js 里的Login() 和 GetInfo()  的response.data 与使用mock时数据是一样的。问题出在哪里了？实在是搞不懂。恳请指教，万分感谢。

**Comment by Penguin-Lin** [comment]
![image](https://user-images.githubusercontent.com/33897969/54586033-bb358300-4a56-11e9-805a-2264d061f01f.png)
![image](https://user-images.githubusercontent.com/33897969/54586238-65ada600-4a57-11e9-9d40-a07ad1956260.png)
上面的一张图是我npm run dev后，出来页面了。然后再运行node后台后的页面报错。第二张图，当我node后台还是开着时，一去刷新页面就一直是cannot get，后退直接输地址都没有用。 这里请求 (2.js) 3.js 是哪里冒出来的。AJAX请求中并没有这东西。

**Comment by Penguin-Lin** [comment]
问题已解决，非常感谢。

**Comment by uwcong** [comment]
你好，我想请教一下你最后怎么解决这个问题的呢？

**Comment by Penguin-Lin** [comment]
> 
不好意思，太久了，已经忘记了是什么原因了。如果你有遇到什么问题，也可以附上。也许我可以回答。

**Comment by Penguin-Lin** [comment]
> 

不好意思，太久了，已经忘记了是什么原因了。如果你有遇到什么问题，也可以附上。也许我可以回答。
