### ISSUE TITLE
eslint

### ISSUE THREAD

**Issue by Hewaller** [PanJiaChen/vue-element-admin#1735]
![error](https://user-images.githubusercontent.com/29259394/54587776-0ef69b00-4a5c-11e9-96af-956c47769675.jpg)
`eslint` 是否应该重新配置一下

![ui](https://user-images.githubusercontent.com/29259394/54587859-4d8c5580-4a5c-11e9-9d8d-a36838a64239.jpg)
首页的背景色没有盖住

**Comment by PanJiaChen** [comment]
你说的两个问题都没能重现。你觉得有问题的话，欢迎pr。

**Comment by Hewaller** [comment]
我在 `.eslintrc.js` 中加入了 `'vue/attributes-order': [0]`， 解决了eslint的警告，不知道是不是我本地的原因而造成的
