### ISSUE TITLE
请教一个vuex的问题

### ISSUE THREAD

**Issue by summer1874** [PanJiaChen/vue-element-admin#1737]
现在在参考这个项目搭建一个后台管理，但是有个地方觉得很神奇（大抵是我学艺不精）

- `this.$store.dispatch('setLanguage', lang)`

- `this.$store.dispatch('app/setLanguage', lang)`

最下面的代码是我的，想问一下，为什么大佬你不要命名空间就可以调用`modules>app` 的actions

**Comment by PanJiaChen** [comment]
https://vuex.vuejs.org/zh/guide/modules.html#%E5%91%BD%E5%90%8D%E7%A9%BA%E9%97%B4

你可以仔细看一下稳定。

>默认情况下，模块内部的 action、mutation 和 getter 是注册在全局命名空间的——这样使得多个模块能够对同一 mutation 或 action 作出响应。

**Comment by PanJiaChen** [comment]
我思考了下 还是加上 `namespaced: true`更加的好。

4.0版本已经全部修改了。

https://github.com/PanJiaChen/vue-element-admin/commit/0c50029cf76c3ee560acfb18b0980509892a8c0e

**Comment by summer1874** [comment]
@PanJiaChen 感谢大佬的解惑~ 谢谢！

**Comment by PiaoRongZhen** [comment]
谢大佬解惑
