### ISSUE TITLE
npm install --registry=https://registry.npm.taobao.org  error

### ISSUE THREAD

**Issue by Gray-coder** [PanJiaChen/vue-element-admin#1738]
PS C:\Jet\Project\vue-element-admin> npm install --registry=https://registry.npm.taobao.org
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

> husky@0.14.3 install C:\Jet\Project\vue-element-admin\node_modules\husky
> node ./bin/install.js

husky
setting up Git hooks
done

> node-sass@4.11.0 install C:\Jet\Project\vue-element-admin\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-57_binding.node
Download complete  ] - :
Binary saved to C:\Jet\Project\vue-element-admin\node_modules\node-sass\vendor\win32-x64-57\binding.node
Caching binary to C:\Users\15921932797\AppData\Roaming\npm-cache\node-sass\4.11.0\win32-x64-57_binding.node

> node-sass@4.11.0 postinstall C:\Jet\Project\vue-element-admin\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Jet\Project\vue-element-admin\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine
npm ERR! path C:\Jet\Project\vue-element-admin\node_modules\fsevents\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'C:\Jet\Project\vue-element-admin\node_modules\fsevents\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'C:\Jet\Project\vue-element-admin\node_modules\fsevents\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Jet\\Project\\vue-element-admin\\node_modules\\fsevents\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'C:\\Jet\\Project\\vue-element-admin\\node_modules\\fsevents\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\15921932797\AppData\Roaming\npm-cache\_logs\2019-03-19T14_17_07_328Z-debug.log

**Comment by Gray-coder** [comment]
项目可以正常运行的

**Comment by PanJiaChen** [comment]
* 先删除已经存在的node_modules
* 删除package-lock.json
* npm cache clean --force
* npm install

如果项目可以正常运行了，那就忽略吧。
