### ISSUE TITLE
富文本编辑器可以添加上传图片功能吗

### ISSUE THREAD

**Issue by logyoo** [PanJiaChen/vue-element-admin#174]
客户端上传图片到服务器，得到图片路径然后在编辑区预览

**Comment by logyoo** [comment]
![08d05229604dffdec4a0b5b4e68291ab_t](https://user-images.githubusercontent.com/16537800/29739060-649d3c64-8a67-11e7-9775-6e935bebeac9.jpg)

**Comment by xinshuimiaolun** [comment]
解决了吗？是怎么解决的？

**Comment by PanJiaChen** [comment]
通过`insertContent` 回塞就好了

**Comment by xinshuimiaolun** [comment]
代码里，貌似没有这些部分的代码。如主页上的：富文本(整合七牛 打水印等个性化功能).GIF效果。
另外，是否可以整合用element-ui的Upload组件实现上传呢？

**Comment by PanJiaChen** [comment]
因为这些功能都需要耦合七牛 不是很方便模拟

**Comment by xinshuimiaolun** [comment]
@PanJiaChen 多谢。辛苦了！
