### ISSUE TITLE
element官网所示的这种三级类目是可以实现的么

### ISSUE THREAD

**Issue by HelloZouYou** [PanJiaChen/vue-element-admin#1741]
当后台菜单比较复杂时，会需要有两列菜单，目前看到element的[官网文档](http://element-cn.eleme.io/2.0/#/zh-CN/guide/nav)有显示所谓“三级类目”，也就是最左侧图标为主菜单，中间是副菜单，请问这样的是可以实现的么。

**Comment by PanJiaChen** [comment]
可以实现，其实就是现在的sidebar相当于二级菜单，你每次点击一级菜单的时候，再被内容动态的传给二级菜单。
