### ISSUE TITLE
npm install 出错

### ISSUE THREAD

**Issue by cjm0810151** [PanJiaChen/vue-element-admin#1742]
环境：mac
npm -v: 6.4.1
node -v v10.14.1

5220 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2ffloating-point-hex-parser 5ms (from cache)
5221 silly fetchPackageMetaData error for @webassemblyjs/floating-point-hex-parser@1.5.13 Unexpected end of JSON input while parsing near '...js/floating-point-hex'
5222 verbose stack RangeError: Maximum call stack size exceeded
5222 verbose stack     at RegExp.test (<anonymous>)
5222 verbose stack     at isDepOptional (/usr/local/lib/node_modules/npm/lib/install/deps.js:405:45)
5222 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:414:9)
5222 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
5222 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
5222 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
5222 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
5222 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
5222 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
5222 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
5222 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
5222 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
5222 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
5222 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
5222 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
5222 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
5223 verbose cwd /Users/chenjiaming/project/vue-element-admin
5224 verbose Darwin 18.2.0
5225 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
5226 verbose node v10.14.1
5227 verbose npm  v6.4.1
5228 error Maximum call stack size exceeded

**Comment by cjm0810151** [comment]
npm -v: 6.4.1
node -v v10.14.1

**Comment by PanJiaChen** [comment]
个人的环境问题，自行谷歌相关解决方案。
