### ISSUE TITLE
页面数据高度超出屏幕高度时导航栏的固定问题

### ISSUE THREAD

**Issue by pleier** [PanJiaChen/vue-element-admin#1746]
![image](https://user-images.githubusercontent.com/22049306/54730182-73336f00-4bc2-11e9-8266-101a2beb2cb9.png)
滚动页面时导航栏也跟着滚动，有办法不滚动吗？
![image](https://user-images.githubusercontent.com/22049306/54730206-9827e200-4bc2-11e9-9f6e-da60d5342202.png)

**Comment by PanJiaChen** [comment]
暂时自己css改一下吧，
之后4.0版本会做成配置项。

**Comment by pleier** [comment]
.
