### ISSUE TITLE
数据更新，页面重新渲染

### ISSUE THREAD

**Issue by CuiYang16** [PanJiaChen/vue-element-admin#1747]
数据更新后，是否可以不全局刷新，只是刷新更新的部分

**Comment by PanJiaChen** [comment]
你想表达什么？

你指webpack的热更新还是vue的？

**Comment by CuiYang16** [comment]
当数据更新之后，监听会执行addAttrs方法，_expand就会都会变成全局设置的值。也就是说无法记住当前行的展开状态，数据更新后都变成到了全局设置的那个值

**Comment by PanJiaChen** [comment]
你说的是 tree-table?

**Comment by CuiYang16** [comment]
> 你说的是树桌？

对，抱歉，没注明

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1728

请关注改issue，不过暂时没有时间来修复。

**Comment by CuiYang16** [comment]
treetable

**Comment by CuiYang16** [comment]
> [＃1728](https://github.com/PanJiaChen/vue-element-admin/issues/1728)
> 
> 请关注该问题，不过暂时没有时间来修复。

ok
