### ISSUE TITLE
喜欢究根问底哈

### ISSUE THREAD

**Issue by lzm422250295** [PanJiaChen/vue-element-admin#1749]
![TIM截图20190321163055](https://user-images.githubusercontent.com/24729949/54740621-ebb42300-4bf6-11e9-8580-cdc378f238a3.png)
如图  那个好像没有用过吧。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/store/getters.js#L15

你可以全局搜一下，不少地方用到了。

**Comment by lzm422250295** [comment]
傻了  ，，刚刚全局搜了没有，现在有了，估计搞错项目了。。。
