### ISSUE TITLE
sidebar  显示问题

### ISSUE THREAD

**Issue by kokiy** [PanJiaChen/vue-element-admin#175]
sidebar 大于屏幕高度,就不显示了,加了overfolow scroll, sidebar 收缩之后,就不显示悬浮的弹框

**Comment by PanJiaChen** [comment]
这个本来就是一个交互上的取舍问题
如 [AdminLTE](https://adminlte.io/themes/AdminLTE/index2.html) sidebar就直接不fixed
或者像我之前那种交互形式 [vueAdmin-template](http://panjiachen.github.io/vueAdmin-template/#/dashboard)

**Comment by kokiy** [comment]
有没有办法可以在 sidebar 加 overflow-y: auto 之后,折叠还是正常显示 hover 呢? 这个问题我纠结好久了,哈哈

**Comment by PanJiaChen** [comment]
目前没找到很完美的解决方案
