### ISSUE TITLE
Integrate Whit laravel

### ISSUE THREAD

**Issue by ehsanbagherzadegan** [PanJiaChen/vue-element-admin#1751]
Hi do you have any plan for integrate this project whit Laravel or do you have any document for do this?
thanks a lot

**Comment by PanJiaChen** [comment]
I am not very familiar with `laravel `, but there are many cases in the community.

https://dev.to/tuandm/laravel--vuejs--laravue---a-beautiful-dashboard-for-laravel-3h11
