### ISSUE TITLE
"本项目的定位是后台集成方案，不适合当基础模板来开发。"怎么理解?能说的详细点吗?怎么使用

### ISSUE THREAD

**Issue by gotexis** [PanJiaChen/vue-element-admin#1753]
新手，刚接触这个项目，阅读文档还没有看代码。如果说不适合二次开发，那这个项目的意义是什么？

如果我要开发admin如何使用这个项目？

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/54797656-f53d9980-4c8f-11e9-8b68-7f8d8aa139a6.png)

**Comment by gotexis** [comment]
Thanks for replying...

Just found this - some1 asked the same question as I did 8 months ago. On reddit ...

I found it hard to comprehend either in English or Chinese XD

https://www.reddit.com/r/vuejs/comments/904m89/what_does_background_integration_solution_mean_in/
