### ISSUE TITLE
Feature request: Oauth - Github oauth2?

### ISSUE THREAD

**Issue by gotexis** [PanJiaChen/vue-element-admin#1754]
Hey I think this is a great project.

The oauth components looks really promising and I would really love to be able to test it locally.

We know that WeChat set some pretty high barriers on Oauth2 since you have to 备案 servers and pay money in order to test which is pretty shit.

Has anyone successfully tested WeChat Oauth? Does it work if I just provide my own APPID/ secret?

I would be grateful if we could add a github or Google Oauth backend,

**Comment by PanJiaChen** [comment]
I don't think this has anything to do with this project.

My own company's project is based on OAuth login. If has problem, please check the relevant documents by yourself.

>  add a github or Google Oauth backend

The third-party login here is just a demo, and you need to implement it yourself.
