### ISSUE TITLE
addRoutes问题

### ISSUE THREAD

**Issue by okaxuan** [PanJiaChen/vue-element-admin#1757]
使用以下方法在.then回调里取不到router和store，显示未定义，只有先保存一下才能取到，我看你们的例子也没有保存就可以，这是为什么
```
import router from './routers'
import store from './stores'
router.beforeEach((to, from, next) => {

  //var selfRouter=router;
  //var selfStore=store;
     if(sessionStorage.getItem('token')){
      if(store.state.login.roles==null){
        store.dispatch('GetUserRoles').then(res=>{
          var roles = res.data.roles;
          store.dispatch('GenerateRoutes', roles).then(accessRoutes=>{
            router.options.routes = selfRouter.options.routes.concat(accessRoutes);
            router.addRoutes(accessRoutes); // 动态添加可访问路由表
            next({...to,replace:true})
          })
        }).catch((err)=>{
  
        })
       }
    
     }else{
       if(to.path=='/login'){
         next()
       }else
         next('/login')
     }
  })
```

**Comment by PanJiaChen** [comment]
你两种写法没区别。
你拿不拿得到，自己debug一下就知道了。

**Comment by okaxuan** [comment]
我一开始只有'/login'页面，我发现我导航守卫里addRoutes路由能动态加载进去，但是我跳转到指定path时也一片空白，地址栏变了。。；我换了一种方式在login.vue动态加载，加载后跳到我想要跳的路由是可以正确跳转的
方法一：
logIn() {
      var that = this;
      that.$store.dispatch("LoginByUerName").then(res => {
        // that.$store.dispatch("GetUserRoles").then(() => {
        //   var roles = that.$store.state.login.roles;
        //   that.$store.dispatch("GenerateRoutes", roles).then(accessRoutes => {
        //     that.$router.options.routes = that.$router.options.routes.concat(
        //       accessRoutes
        //     );
        //     that.$router.addRoutes(accessRoutes); // 动态添加可访问路由表
        //   });
        // });
        that.$router.push({path:'/cooperator'});
      });
    }
import router from './routers'
import store from './stores'
router.beforeEach((to, from, next) => {
  // next()
  var selfRouter=router;
  var selfStore=store;
    if(sessionStorage.getItem('token')){
      if(selfStore.state.login.roles==null){
        selfStore.dispatch('GetUserRoles').then(res=>{
          var roles = res.data.roles;
          selfStore.dispatch('GenerateRoutes', roles).then(accessRoutes=>{
            selfRouter.options.routes = selfRouter.options.routes.concat(accessRoutes);
            selfRouter.addRoutes(accessRoutes); // 动态添加可访问路由表
            next({...to,replace:true})
          })
        }).catch((err)=>{
  
        })
       }else{
         next()
       }
    
    }else{
      if(to.path=='/login'){
        next()
      }else
        next('/login')
    }
  })
方法二：
logIn() {
      var that = this;
      that.$store.dispatch("LoginByUerName").then(res => {
         that.$store.dispatch("GetUserRoles").then(() => {
           var roles = that.$store.state.login.roles;
           that.$store.dispatch("GenerateRoutes", roles).then(accessRoutes => {
             that.$router.options.routes = that.$router.options.routes.concat(
              accessRoutes
            );
            that.$router.addRoutes(accessRoutes); // 动态添加可访问路由表
         });
         });
        that.$router.push({path:'/cooperator'});
      });
    }
