### ISSUE TITLE
三级菜单有时点击时会出现页面和菜单不匹配的的问题，仅仅只出现在三级菜单的时候

### ISSUE THREAD

**Issue by Chasen-Zhang** [PanJiaChen/vue-element-admin#1758]

**Comment by Chasen-Zhang** [comment]
三级菜单有时点击时会出现页面和菜单不匹配的的问题，仅仅只出现在三级菜单的时候

**Comment by PanJiaChen** [comment]
请提供可复现步骤或者gif。

**Comment by Chasen-Zhang** [comment]
![image](https://user-images.githubusercontent.com/15354455/54861380-04414c00-4d63-11e9-82d0-a6616ed44737.png)

**Comment by Chasen-Zhang** [comment]
![image](https://user-images.githubusercontent.com/15354455/54861393-23d87480-4d63-11e9-883b-343aa58a2371.png)

**Comment by Chasen-Zhang** [comment]
![image](https://user-images.githubusercontent.com/15354455/54861411-3eaae900-4d63-11e9-9b46-6f108bc975eb.png)

**Comment by Chasen-Zhang** [comment]
![image](https://user-images.githubusercontent.com/15354455/54861418-5b472100-4d63-11e9-9e2f-153678146250.png)

**Comment by PanJiaChen** [comment]
我这里无法重现你的问题。

**Comment by Chasen-Zhang** [comment]
如果在router-view外面包一层keep-alive呢？

**Comment by Chasen-Zhang** [comment]
有可能是keep-alive的影响

**Comment by Chasen-Zhang** [comment]
我现在已经解决了这个问题，如果报了keep-alive，最好给router-view加一个唯一的key值。

**Comment by Chasen-Zhang** [comment]
又发现问题了，跟作者的框架无关，是我自己keep-alive嵌套导致的。是自己造成的！跟作者无关哈
