### ISSUE TITLE
我一开始只有'/login'页面，我发现我导航守卫里addRoutes路由能动态加载进去，但是我跳转到指定path时也一片空白，地址栏变了。。；我换了一种方式在login.vue动态加载，加载后跳到我想要跳的路由是可以正确跳转的

### ISSUE THREAD

**Issue by okaxuan** [PanJiaChen/vue-element-admin#1759]
我一开始只有'/login'页面，我发现我导航守卫里addRoutes路由能动态加载进去，但是我跳转到指定path时也一片空白，地址栏变了。。；我换了一种方式在login.vue动态加载，加载后跳到我想要跳的路由是可以正确跳转的；问题是导航守卫里我调试看到路由也存在了就是不跳转
方法一：
{
  path: '/cooperator',
  component: layout,
  redirect: '/cooperator/supplier',
  meta: {
    roles: ['admin', 'cooperator']
  },
  children: [{
    path: 'supplier',
    component: () => import( /* webpackChunkName: "supplier" */ '../views/cooperators/Supplier.vue'),
    name: 'supplier'
  }, {
    path: 'vehicle',
    component: () => import( /* webpackChunkName: "supplier" */ '../views/cooperators/Vehicle.vue'),
    name: 'vehicle'
  }, {
    path: 'driver',
    component: () => import( /* webpackChunkName: "supplier" */ '../views/cooperators/Driver.vue'),
    name: 'driver'
  }]
},
logIn() {
      var that = this;
      that.$store.dispatch("LoginByUerName").then(res => {
        // that.$store.dispatch("GetUserRoles").then(() => {
        //   var roles = that.$store.state.login.roles;
        //   that.$store.dispatch("GenerateRoutes", roles).then(accessRoutes => {
        //     that.$router.options.routes = that.$router.options.routes.concat(
        //       accessRoutes
        //     );
        //     that.$router.addRoutes(accessRoutes); // 动态添加可访问路由表
        //   });
        // });
        that.$router.push({path:'/cooperator'});
      });
    }
import router from './routers'
import store from './stores'
router.beforeEach((to, from, next) => {
  // next()
  var selfRouter=router;
  var selfStore=store;
    if(sessionStorage.getItem('token')){
      if(selfStore.state.login.roles==null){
        selfStore.dispatch('GetUserRoles').then(res=>{
          var roles = res.data.roles;
          selfStore.dispatch('GenerateRoutes', roles).then(accessRoutes=>{
            selfRouter.options.routes = selfRouter.options.routes.concat(accessRoutes);
            selfRouter.addRoutes(accessRoutes); // 动态添加可访问路由表
            next({...to,replace:true})
          })
        }).catch((err)=>{
  
        })
       }else{
         next()
       }
    
    }else{
      if(to.path=='/login'){
        next()
      }else
        next('/login')
    }
  })
方法二：
logIn() {
      var that = this;
      that.$store.dispatch("LoginByUerName").then(res => {
         that.$store.dispatch("GetUserRoles").then(() => {
           var roles = that.$store.state.login.roles;
           that.$store.dispatch("GenerateRoutes", roles).then(accessRoutes => {
             that.$router.options.routes = that.$router.options.routes.concat(
              accessRoutes
            );
            that.$router.addRoutes(accessRoutes); // 动态添加可访问路由表
         });
         });
        that.$router.push({path:'/cooperator'});
      });
    }

_Originally posted by @okaxuan in https://github.com/PanJiaChen/vue-element-admin/issues/1757#issuecomment-475512058_

**Comment by PanJiaChen** [comment]
想要人家帮助你，请先学会提问，我都不知道你想表达什么。贴的代码还这么乱。
如果有问题，请提供一个在线可还原问题demo。

**Comment by okaxuan** [comment]
@PanJiaChen 好的，谢谢
