### ISSUE TITLE
大佬我编译的时候出现了一个警告但是我按照警告来 安装这个依赖后报错

### ISSUE THREAD

**Issue by chenweibo** [PanJiaChen/vue-element-admin#1761]
![1553243444036](https://user-images.githubusercontent.com/19586007/54810173-5f6e3280-4cc0-11e9-9666-37d6e9acdcf8.jpg)
如上图所示。 安装后这个包直接报错了。 逼死强迫症 用的是4.0  yarn装的

**Comment by PanJiaChen** [comment]
暂时不想修了。。马上4.0版本了。

**Comment by chenweibo** [comment]
好。 那我直接等着上4.0 大概什么时候有个准确的消息。   我这个分支其实就是4.0的分支

**Comment by PanJiaChen** [comment]
`WARNING` 是一个上游的错误，和我的配置关系不大。

**Comment by PanJiaChen** [comment]
https://github.com/vuejs/vue-cli/issues/3695

等cli更新之后，我更新一下版本就好了。

**Comment by medmin** [comment]
这个是vue的warning

不是这个库的

**Comment by sodatea** [comment]
Fixed in @vue/babel-preset-app v3.5.2
