### ISSUE TITLE
试用4.0分支，run dev可以成功,但是run build:prod老是失败。

### ISSUE THREAD

**Issue by csdudu** [PanJiaChen/vue-element-admin#1763]
![Image](https://user-images.githubusercontent.com/5706088/54816710-ea0a5e00-4ccf-11e9-8b52-c2282d3a8093.png)

webpack -v  //4.29.6  
vue -V   //vue-cli版本 ,3.2.1
node -v // v8.9.3
npm -v //5.5.1
----------------------
奇怪的是，我用这个环境跑别的Vue-cli3的项目，都没事。
跑vue-element-admin 的master分支，都没事。

**Comment by PanJiaChen** [comment]
你可以更新一下分支代码，之前已经修复了

**Comment by csdudu** [comment]
我就是今天下午刚拉下的代码，请问是刚刚做的更新么？

**Comment by PanJiaChen** [comment]
你拉一下 跑一下不就知道了。。。

**Comment by kuaitukeji** [comment]
请问4.0大概什么时候发布正式版

**Comment by PanJiaChen** [comment]
下周上beta版本。 四月上正式版本和更新文档。

**Comment by kuaitukeji** [comment]
@PanJiaChen v3.10版本，在GIT拉取代码后安装依赖，运行测试，发现换肤有点问题，然后刷新又正常，是什么原因呢 
![image](https://user-images.githubusercontent.com/32607562/54893734-23221880-4ef2-11e9-9e4b-896864263f89.png)

**Comment by PanJiaChen** [comment]
看着像 element-ui 样式丢失了。

**Comment by kuaitukeji** [comment]
@PanJiaChen  是的，操作过程是：来回的换不同皮肤，然后就生效了，
![image](https://user-images.githubusercontent.com/32607562/54893953-5022fb00-4ef3-11e9-9784-15748ab5290f.png)
