### ISSUE TITLE
Sidebar not rendering when using real API

### ISSUE THREAD

**Issue by erikaraujo** [PanJiaChen/vue-element-admin#1764]
When I switch to real API, sidebar does not render.
I hardcoded the Roles to get an array ['admin'] on every GetUserInfo request, since I'm implementing roles differently, so roles isn't the issue here. I could really use some help.

**Comment by PanJiaChen** [comment]
The sidebar is generated according to state.permission.routes, so you can determine if it is empty.

**Comment by kumjShid4** [comment]
> The sidebar is generated according to state.permission.routes, so you can determine if it is empty.

Sorry for my knowledges but I couldn't find any way to change state.permission.routes after logged in successfully except hardcode in store/modules/permission.js. Is there any way to generate sidebar via permission (role)? Thank for any response!

**Comment by huzaifah-ivan** [comment]
hii @erikaraujo i would like to know the way you render the sidebar from API. could you give me some real code to do this please...

Thanks
