### ISSUE TITLE
为什么a标签会自动加个路径

### ISSUE THREAD

**Issue by zhaoshibo** [PanJiaChen/vue-element-admin#1766]
页面代码`<a href="www.baidu.com">qqqq</a>`这样
但是

![](https://user-images.githubusercontent.com/8072325/54863066-93a82880-4d7e-11e9-8166-7b6c3d9dc997.png)

浏览器的地址是这样

**Comment by PanJiaChen** [comment]
这是正常行为。
正确的写法是
`<a href="https://www.baidu.com">qqqq</a>`
