### ISSUE TITLE
初次编译项目，没有成功，请大佬解决一下

### ISSUE THREAD

**Issue by chensiyuan12138** [PanJiaChen/vue-element-admin#1768]
/Users/chensiyuan/.nvm/versions/node/v8.11.4/bin/node /Users/chensiyuan/.nvm/versions/node/v8.11.4/lib/node_modules/npm/bin/npm-cli.js run dev --scripts-prepend-node-path=auto

> vue-element-admin@3.10.0 dev /Users/chensiyuan/Work/com.chensiyuan/zazhi
> cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 ERROR  Failed to compile with 4 errors00:33:55

 error  in ./src/lang/index.js

Syntax Error: SyntaxError: Unexpected token (15:4)

  13 | const messages = {
  14 |   en: {
> 15 |     ...enLocale,
     |     ^
  16 |     ...elementEnLocale
  17 |   },
  18 |   zh: {

 @ ./src/main.js 16:0-26 26:24-28 40:2-6
 @ multi (webpack)-dev-server/client?http://localhost:9527 (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/store/modules/permission.js

Syntax Error: SyntaxError: Unexpected token (25:18)

  23 | 
  24 |   routes.forEach(route => {
> 25 |     const tmp = { ...route }
     |                   ^
  26 |     if (hasPermission(roles, tmp)) {
  27 |       if (tmp.children) {
  28 |         tmp.children = filterAsyncRoutes(tmp.children, roles)

 @ ./src/store/index.js 5:0-46 16:4-14
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:9527 (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/permission.js

Syntax Error: SyntaxError: Unexpected token (39:21)

  37 |               // 根据roles权限生成可访问的路由表
  38 |               router.addRoutes(accessRoutes) // 动态添加可访问路由表
> 39 |               next({ ...to, replace: true }) // hack方法 确保addRoutes已完成 ,set the replace: true so the navigation will not leave a history record
     |                      ^
  40 |             })
  41 |           })
  42 |           .catch(err => {

 @ ./src/main.js 19:0-22
 @ multi (webpack)-dev-server/client?http://localhost:9527 (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/router/index.js

Syntax Error: SyntaxError: Unexpected token (44:25)

  42 |       {
  43 |         path: '/redirect/:path*',
> 44 |         component: () => import('@/views/redirect/index')
     |                          ^
  45 |       }
  46 |     ]
  47 |   },

 @ ./src/main.js 14:0-30 38:2-8
 @ multi (webpack)-dev-server/client?http://localhost:9527 (webpack)/hot/dev-server.js ./src/main.js

**Comment by PanJiaChen** [comment]
看这个报错，大概率是 `babel`没配对。
