### ISSUE TITLE
依赖vue-loader升级13版本后，加载不到模块

### ISSUE THREAD

**Issue by sdhery** [PanJiaChen/vue-element-admin#177]
vue.esm.js:479 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Anonymous>
       <APP> at src\App.vue
         <Root>

**Comment by PanJiaChen** [comment]
https://github.com/vuejs/vue-loader/releases/tag/v13.0.0
vue-loader 升级之后 `esModule` 是`true`了，所以要改写一下`require`的写法
https://github.com/PanJiaChen/vue-element-admin/blob/bae698c9ad314c1815f8eefd5f6dc4b4d09fa103/src/router/_import_development.js#L1

**Comment by sdhery** [comment]
3Q，问题解决了

**Comment by yehoan** [comment]
我降级了vue-loader 和那个 vux-loader 为什么还是提示我升级到最新的vux-loader
