### ISSUE TITLE
有关于这个项目中eslint规则的描述吗？

### ISSUE THREAD

**Issue by HankBass** [PanJiaChen/vue-element-admin#1770]
作者手上有关于这个项目的eslint的规则描述吗？之前用eslint不多，想了解下，如果作者手上没有的话，那我就唯有手动去查了哈

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/eslint.html#eslint

所有配置也都列出来了。
https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/eslint.html#eslint

具体每个配置解释，请自行看 eslint 官网。

**Comment by emptycitys** [comment]
没有看到每一项的描述的？想改下配置，但这些配置都不认识，一个个去百度也不实际啊，太多了
