### ISSUE TITLE
使用echarts时的问题

### ISSUE THREAD

**Issue by RainbowYano** [PanJiaChen/vue-element-admin#1771]
1.模板里面应该是全局引用，不是按需引用的吧？
2.引入的这个resize文件的作用是？而且这样引入的话里面的mounted与自己本身的mounted不会冲突吗
![Snipaste_2019-03-25_17-09-30](https://user-images.githubusercontent.com/43380578/54907565-c853e580-4f20-11e9-8b25-c65e9439e668.png)

**Comment by PanJiaChen** [comment]
1 是全局引用，有需求可以自己按需加载。
2 mixin 你请自行看vue文档。 resize作用：看名字都能猜出吧。
