### ISSUE TITLE
替换mockjs

### ISSUE THREAD

**Issue by eggachecat** [PanJiaChen/vue-element-admin#1778]
mock.js 似乎很久没有更新了..

有一个问题在于mock会替换原本的'XMLHttpRequest'

导致一些问题,例如

[#275@mock](https://github.com/nuysoft/Mock/issues/275)

[#285@mock](https://github.com/nuysoft/Mock/issues/285)

还有很多...

**Comment by PanJiaChen** [comment]
你可以用4.0分支版本，已经换了。
