### ISSUE TITLE
引入vue-pdf报错

### ISSUE THREAD

**Issue by tacy** [PanJiaChen/vue-element-admin#178]
我想用vue-pdf显示pdf, 在开发环境没问题, 但是在生产环境它报错:

GET http://ip/569d2d2aea278436377d.worker.js 404 (Not Found)    pdf.worker.js?d0ca:2 404 (Not Found)

找了一下, 发现vue-pdf编译的结果放在dist目录下, 而其他js编译完之后都放在dist/static/js目录下, 这个需要怎么解决呢

**Comment by PanJiaChen** [comment]
我怎么知道你代码怎么写的。。

**Comment by tacy** [comment]
目前水平只会抄你的demo, pdf显示也是vue-pdf的代码, 大致是下面这样: 

```
    <el-dialog title="打印" size="small" :visible.sync="dialogFormVisible">
      <pdf ref="pdf" :src="pdfsrc"></pdf>
      <div slot="footer" class="dialog-footer">
        <el-button @click="dialogFormVisible=false">取 消</el-button>
        <el-button type="primary" @click="$refs.pdf.print()">打 印</el-button>
      </div>
    </el-dialog>

<script>
  import { fetchPDF } from 'api/orders';
  import pdf from 'vue-pdf';

  export default {
    components: {
      pdf
    },
    data() {
      return {
        pdfsrc: undefined,
	dialogFormVisible: false,
	xloboData: {
	  BillCode: undefined
	}
      }
    },
    methods: {
      handlePDF(row) {
        this.msData.BillCode = row.db_number;
	this.pdfsrc = '';
        fetchPDF(this.msData).then(response => {
	  this.pdfsrc = "data:application/pdf;base64, " + response.data.BillPdfLabel;
          this.dialogFormVisible = true;
	});
      }
    }
  }
</script>
```
我想请教的是: 为什么我添加了vue-pdf依赖, 但是它编译出来的js却存放在dist目录下, 而不是dist/statics/js目录下.

**Comment by PanJiaChen** [comment]
那它打包到去哪里了？

**Comment by tacy** [comment]
vue-pdf依赖的pdfjs编译之后存放在frontend/dist目录下, 其他的js都存放在frontend/static/js目录下

**Comment by PanJiaChen** [comment]
不是很能理解你的问题，如果你基于我项目的话 所有打包的js都会在dist/static/js下面

**Comment by tacy** [comment]
估计是我哪里弄错了, 我看了build配置, 应该都会往dist/static/js目录下放才对. 

请问一下, 我添加依赖到项目是否只需要执行`npm install vue-pdf save`这个指令呢?

**Comment by PanJiaChen** [comment]
`npm install vue-pdf --save` 或者 `npm install vue-pdf -S`

**Comment by tacy** [comment]
谢谢, 我找找原因

**Comment by leo0828** [comment]
同样的问题，打包后dist目录下会生成一个worker.js文件，而且dist/static/js目录下会生成许多序号命名的js文件

**Comment by DaiShengloda** [comment]
> 谢谢, 我找找原因
请问解决了吗，我也碰到这个问题了

**Comment by D1995** [comment]
我也遇到了同样的问题，请问有解决方案了吗

**Comment by wxlv** [comment]
我在开发环境都跑不起来这个插件！！！！
`报错如下：`
`Unknown custom element: <pdf> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`
代码如下：
```
<pdf :src="pdfSrc" :page="pdfCurrentPage" @num-pages="pdfPageCount=$event" @page-loaded="pdfCurrentPage=$event" @loaded="pdfLoadHandler" />

import { pdf } from 'vue-pdf'
components: {
    pdf
  },
```
