### ISSUE TITLE
views目录下的所有vue文件都会被打包，即使它没有被任何文件依赖（导入）。

### ISSUE THREAD

**Issue by PandaTsui** [PanJiaChen/vue-element-admin#1781]
环境：使用的是您webpack4.0配置，
情况：如下图，我在view目录下新建了cpe目录和cpe.vue，此文件是独立的，还没有被其他任何文件导入。
结果：但是最终打包确把这个cpe.vue的文件给打包进去了。
期望结果：可以动态打包，路由文件没有导入的模块，不进行打包操作。
![image](https://user-images.githubusercontent.com/21979377/55055827-30c8d100-509f-11e9-8daa-114908284b85.png)
![image](https://user-images.githubusercontent.com/21979377/55055829-31f9fe00-509f-11e9-8788-6c8cc657236c.png)
![image](https://user-images.githubusercontent.com/21979377/55055831-33c3c180-509f-11e9-87dd-c7ee0b0c72cd.png)

**Comment by PanJiaChen** [comment]
我试了下没能重现你的问题。你是最新版本么？

**Comment by PandaTsui** [comment]
不好意思，我只改了配置，路由那个import() 问题没有改，是这个导致的。@PanJiaChen

**Comment by lushfe** [comment]
老哥 views 不打包，你在后台配置的菜单，前端怎么取呢，你打包会获取后端的所有菜单组件关联吗？
