### ISSUE TITLE
我的异步路由超过200多个之后，就报 Cannot read property 'dispatch' of null

### ISSUE THREAD

**Issue by gaoxiaopang** [PanJiaChen/vue-element-admin#1784]
我的异步路由个数超过200多个之后，
就报 Cannot read property 'dispatch' of null
但我的开发环境并不会报这个错，
上传到qa环境就会有个这个错误
会卡在登录的环节登录不了
![image](https://user-images.githubusercontent.com/8706879/55060166-ce2a0200-50ab-11e9-8e26-d7a879069305.png)

**Comment by PanJiaChen** [comment]
这你自己代码问题吧。。。

**Comment by luchuan163** [comment]
你的路由是怎么加载的，贴一下代码看看

**Comment by gaoxiaopang** [comment]
> 你的路由是怎么加载的，贴一下代码看看

感谢大佬。这个问题已经解决了，我把线上打的包放在线下试一了一下发现不可以 ，，，后面才知道因为线上环境node版本过低导致的
