### ISSUE TITLE
处理自定义指令时遇到的不懂得问题

### ISSUE THREAD

**Issue by RainbowYano** [PanJiaChen/vue-element-admin#1785]
###### 在每一个directive的index.js中
1. 为什么要做if(window.Vue)的判断，Vue好像不会自动挂载到window上，而且我打印window.Vue的时候是undefined,
2. 为什么要在每一个指令的身上挂载一个install

![Snipaste_2019-03-27_16-59-20](https://user-images.githubusercontent.com/43380578/55062849-b5bce600-50b1-11e9-8c8c-b815840a4aec.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1613
