### ISSUE TITLE
v4.0 fixed-header

### ISSUE THREAD

**Issue by penjay** [PanJiaChen/vue-element-admin#1787]
建议fixed-header也使用el-scrollbar

**Comment by PanJiaChen** [comment]
什么意思?

**Comment by seayao** [comment]
sticky组件有个bug
当fixedHeader为true的时候，
sticky的stickyTop应为84（ /* 84 = navbar + tags-view = 50 + 34 */）

**Comment by PanJiaChen** [comment]
我觉得不能这么算，应该还是相对页面的top

**Comment by penjay** [comment]
> 什么意思?

您好，请看图（这样调整一下感觉更精致一点，另外tagsview的样式也建议稍微美化一下）：
![image](https://user-images.githubusercontent.com/23008915/55135866-cb8ce280-5167-11e9-9e81-8a6e37397daa.png)

**Comment by penjay** [comment]
> > 什么意思?
> 
> 您好，请看图（这样调整一下感觉更精致一点，另外tagsview的样式也建议稍微美化一下）：
> ![image](https://user-images.githubusercontent.com/23008915/55135866-cb8ce280-5167-11e9-9e81-8a6e37397daa.png)

手残，自己一直改不好。。。

**Comment by PanJiaChen** [comment]
这个暂时不准备实现。你可以看一下市面上目前 `fixed-header` 的情况下，也都是这样的滚动条。

**Comment by wbc505357999** [comment]
/* Scroll Bar 全局样式*/
::-webkit-scrollbar-track{border-radius: 10px;-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0);}
::-webkit-scrollbar-thumb{background-color: rgba(0,0,0,0.05);border-radius: 10px;-webkit-box-shadow: inset 1px 1px 0 rgba(0,0,0,.1);}
::-webkit-scrollbar-thumb{background-color: rgba(0,0,0,0.2);border-radius: 10px;-webkit-box-shadow: inset 1px 1px 0 rgba(0,0,0,.1);}
::-webkit-scrollbar{width: 16px;height: 16px;}
::-webkit-scrollbar-track,
::-webkit-scrollbar-thumb{border-radius: 999px;border: 5px solid transparent;}
::-webkit-scrollbar-track{box-shadow: 1px 1px 5px rgba(0,0,0,.2) inset;}
::-webkit-scrollbar-thumb{min-height: 20px;background-clip: content-box;box-shadow: 0 0 0 5px rgba(0,0,0,.2) inset;}
::-webkit-scrollbar-corner{background: transparent;}

自用滚动条样式，哈哈美观
![image](https://user-images.githubusercontent.com/20452728/55382541-792d3680-5558-11e9-9f1a-8f8d5ee063f0.png)
