### ISSUE TITLE
啥问题，install有错误， run dev也失败

### ISSUE THREAD

**Issue by taotiejun** [PanJiaChen/vue-element-admin#1789]
npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"4.4.3
,"npm":"2.15.1"})
|
> node-sass@4.11.0 install D:\dev\vue-element-admin\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\Administrator\AppData\Roaming\npm-cache\node-sa
s\4.11.0\win32-x64-46_binding.node

> node-sass@4.11.0 postinstall D:\dev\vue-element-admin\node_modules\node-sass
> node scripts/build.js

Binary found at D:\dev\vue-element-admin\node_modules\node-sass\vendor\win32-x6
-46\binding.node
Testing binary
Binary is fine
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package html-webpack-plugin@4.0.0-alpha does not satis
y its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer script-ext-html-webpack-plugin@2.0.1 wants html-webpa
k-plugin@^3.0.0

npm ERR! Please include the following file with any support request:
npm ERR!     D:\dev\vue-element-admin\npm-debug.log

**D:\dev\vue-element-admin>npm run dev**

> vue-element-admin@3.10.0 dev D:\dev\vue-element-admin
> cross-env BABEL_ENV=development webpack-dev-server --inline --progress --conf
g build/webpack.dev.conf.js

D:\dev\vue-element-admin\node_modules\webpack-dev-server\bin\webpack-dev-server
js:30
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by seayao** [comment]
手动安装一下
"node-sass": "^4.9.0"和"core-js": "^2.6.5",
试试。

**Comment by taotiejun** [comment]
> 手动安装一下
> “node-sass”：“^ 4.9.0”和“core-js”：“^ 2.6.5”，
> 试试。

多谢！
node和npm版本问题，跟新了下就可以了。
