### ISSUE TITLE
引用page组件后 事件调用不起作用

### ISSUE THREAD

**Issue by encrylife** [PanJiaChen/vue-element-admin#1790]
```js
<pagination v-show="total>0" :total="total" :page.sync="listQuery.page" :limit.sync="listQuery.limit" @pagination="getList" @current-change="handleCurrentChange" @size-change="sizeChange" />
```

事件如下
 sizeChange: function(size) {
      console.log('-------')
      this.logInfo(size)
      this.listQuery.pageSize = size
      this.listQuery.limit = size
      this.getList()
    },
事件执行时 一点反应都没有 只调用了 组件里的方法

**Comment by PanJiaChen** [comment]
你自己的代码的问题吧，和组件有什么关系。

**Comment by encrylife** [comment]
@current-change="handleCurrentChange" @size-change="sizeChange" 这两个事件里面的方法不执行，代码也是用的例子里的表格，连简单的console.log 都没反应

**Comment by PanJiaChen** [comment]
我不知道你用的是什么版本的。
现在是直接监听 `pagination`就可以了

`@pagination="getList"` 其它不需要了。
文档 https://panjiachen.github.io/vue-element-admin-site/zh/feature/component/pagination.html#%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F

example 代码冗余了 我删一下。
