### ISSUE TITLE
关于路由配置不进行打包，在dist中随改随用。

### ISSUE THREAD

**Issue by seayao** [PanJiaChen/vue-element-admin#1791]
项目中有一些配置，比如：接口的地址，路由导航等等，
开发版和线上版可能存在差异，
在不需要开发版重新打包的情况下，
直接修改dist中static文件下的配置，
做到即改即用，
接口地址那些简单配置一下就可以，
不知道路由是否也可以做到不打包，随改随用。

**Comment by PanJiaChen** [comment]
可以，但不是一言两语能说清楚的。
但核心问题是，你为什么不重新打包呢？简单省事，不用改什么代码。

**Comment by seayao** [comment]
因为线上的环境可能随时会改，
他们那边的技术人员不会看源码，
只有dist的内容，
他们要自己改，
木得办法。

**Comment by PanJiaChen** [comment]
那就专门搞一个 config.js webpack打包的时候不要打包它，直接复制到dist目录下。

**Comment by xuexiongyao** [comment]
所以最后怎么解决的呢 seayao

**Comment by seayao** [comment]
类似于最原始的js引用，我自己的方案如下：
在public文件夹下的static中新建config.js（名字随意），config.js的内容如下图：
![QQ截图20190626111550](https://user-images.githubusercontent.com/29435027/60148476-cd684f80-9803-11e9-8113-8e20a45f6fcd.png)
在需要引用BASE_API或者其他config.js中的配置时，直接引用，如下图：
![QQ截图20190626111734](https://user-images.githubusercontent.com/29435027/60148516-09031980-9804-11e9-8837-7652411e1f16.png)
最后但最重要的一步，在index.html中引入config.js，如下图：
![QQ截图20190626111823](https://user-images.githubusercontent.com/29435027/60148550-2fc15000-9804-11e9-8803-acf666fbc95e.png)

**Comment by xuexiongyao** [comment]
多谢大佬 我试试

**Comment by zhengwei1209** [comment]
@seayao 大佬，请问能再发下图吗
