### ISSUE TITLE
Mockjs不兼容axios的responseType

### ISSUE THREAD

**Issue by 724399396** [PanJiaChen/vue-element-admin#1793]
使用了mockjs以后，所有axios返回的data类型都是String, mockjs那边已经修复，但是npm上没有发布新包，希望能够在README上增加一个注释，防止后人继续遇到这个问题.

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1779

**Comment by 724399396** [comment]
@PanJiaChen 抱歉，刚刚没搜到

**Comment by ninachowcn** [comment]
> #1779
Mock.XHR.prototype.send = function() {
  if (this.custom.xhr) {
    this.custom.xhr.withCredentials = this.withCredentials || false
    // 确保 responseType 不会丢失
    this.custom.xhr['responseType'] = this['responseType']
  }
  this.proxy_send(...arguments)
}
修改了上面的代码，但是依然报错啊？？
DOMException: Failed to set the 'responseType' property on 'XMLHttpRequest': The response type cannot be changed for synchronous requests made from a document.
    at MockXMLHttpRequest../mock/index.js.mockjs__WEBPACK_IMPORTED_MODULE_0___default.a.XHR.send (http://localhost:8099/app.js:933:37)
