### ISSUE TITLE
切换页面过渡动画时间

### ISSUE THREAD

**Issue by xiaopingfeng** [PanJiaChen/vue-element-admin#1794]
总感觉在点击侧边栏后，切换app-main部分过渡动画时间有点长。
请问这个时间在哪可以调整，或者怎么把过渡动画去掉
我试了 src/styles/ 里的 transition.scss和 sidebar.scss 两个问题里的相关参数。好像都没成功

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/styles/transition.scss
