### ISSUE TITLE
dragtable如何拖放至kanban上

### ISSUE THREAD

**Issue by Thomas-Lei** [PanJiaChen/vue-element-admin#1796]
我在一个页面的右边有个dragtable，左边有kanban。我想实现的功能是把dragtable拖到kanban上时根据拖过来的一行中的字段信息新加一个任务。比如dragtable中拖过来有ID,日期等等，想根据ID,日期在kanban中产生一个新的任务。因为kanban是用来vuedraggable实现的，而dragtable是用sortablejs实现的，所以不知道该怎么样把数据从dragtable传到kanban来。

**Comment by PanJiaChen** [comment]
这种问题请去 `vuedraggable`提问。
