### ISSUE TITLE
elementui更新了2.7.0版本

### ISSUE THREAD

**Issue by wuyouhuaz** [PanJiaChen/vue-element-admin#1797]
elementui更新了最新的2.7.0版本，支持树表操作，升级elementui版本会导致树表组件报错

**Comment by PanJiaChen** [comment]
恩，既然官方支持 tree-table 所以就得tree-table组件就不会在维护了。

**Comment by facestar** [comment]
tree-table的data换为从数据库查出的数据，删除的时候老半天没反应，查看数组要半天才删除掉相应的元素，并且页面上的数据也不会变化

**Comment by PanJiaChen** [comment]
tree-table 已经不维护了，请使用 element- ui  2.7.0 官方自带 tree-table。
