### ISSUE TITLE
v4.0登录页面密码可视切换问题

### ISSUE THREAD

**Issue by kurobanekid** [PanJiaChen/vue-element-admin#1799]
v4.0-beta下登录页面点击密码可视按钮进行切换，密码会被清空。
预期：密码可视切换后不会被清空密码，直接显示明文密码

**Comment by PanJiaChen** [comment]
已修复 https://github.com/PanJiaChen/vue-element-admin/commit/9fb324f0f0d69b8cfb81eb061d45bde0d2b33ee5
