### ISSUE TITLE
backtoTop组建

### ISSUE THREAD

**Issue by Alex-0407** [PanJiaChen/vue-element-admin#180]
我在其他项目中使用这个组建，向下滚动没任何反应，是不是有什么依赖包？

**Comment by dongsuo** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/components/BackToTop/index.vue
这个组件没有任何依赖。
默认的显示高度是400px，可以检查一下是否向下滚动的高度不够。

**Comment by dongsuo** [comment]
也有可能是被AdBlock屏蔽掉了，改了一下类名，可以再一下
