### ISSUE TITLE
vue-cli3.0如何兼容低版本浏览器

### ISSUE THREAD

**Issue by seayao** [PanJiaChen/vue-element-admin#1800]
兼容低版本浏览器（安卓浏览器）
我按照官方的配置
![1sadas1d3](https://user-images.githubusercontent.com/29435027/55215289-3c99cc00-5234-11e9-8f0a-9baf314e00ce.png)
并在package.json中的browserslist增加"Android >= 4.2"，
可以在安卓4.2打开首页但是只能打开首页点击任何都无效，
![QQ截图20190329150756](https://user-images.githubusercontent.com/29435027/55215385-9601fb00-5234-11e9-82cd-e3adf48f2510.png)
是我babel配置的不对吗？
求指点。

**Comment by PanJiaChen** [comment]
这个问题 请看 vue-cli3 文档

**Comment by seayao** [comment]
原因是我使用URLSearchParams处理axios发送的数据，
在低版本ie浏览器及低版本android浏览器无法识别，
解决方案：npm install --save url-search-params-polyfill
在使用URLSearchParams的地方 import进来就可以了。
