### ISSUE TITLE
左侧菜单栏滚动太慢

### ISSUE THREAD

**Issue by androidvm** [PanJiaChen/vue-element-admin#1801]
1.滚动太慢，如果菜单项目表多，滚动要半天才能到底
2.而且滚动条的位置也不对，滚动条到底之后， 还能继续往下滚动，直到消失
3.最好只有一个展开的同级菜单，其他菜单点击的时候自动收起来

**Comment by PanJiaChen** [comment]
- 第一个问题，我在mac滚动速度还行，请提供一下你的测试环境
- 第二个问题，能提供还原步骤或者gif么？
- 第三个问题，https://github.com/PanJiaChen/vue-element-admin/issues/1014

**Comment by androidvm** [comment]
1. mac + firefox 66.0.2 (64-bit)，左侧滚动速度跟右侧相比明显慢
2.
<img width="245" alt="image" src="https://user-images.githubusercontent.com/17350432/55275655-210dee80-5324-11e9-9d2c-a461ead87c83.png">
把菜单都打开，然后从上往下滚动就可以看到， 图片里面滚动条正在消失

**Comment by androidvm** [comment]
1.mac 10.13.6 13寸 鼠标滚轮转一圈，菜单才走一个。其实左右对比一下很明显的，可能笔记本屏幕小的关系？
2.从dashboard开始，鼠标按住滚动条往下拖，可以看到滚动条逐渐离开鼠标自己消失了。

**Comment by androidvm** [comment]
滚动条的问题我找到原因了，在sidebar.scss里面去掉下面的内容就行了。
`.el-scrollbar__view {
        height: 100%;
      [}](url)
`
设置100%高度导致滚动条无法计算自己的内容大小。
PanJiaChen/vue-admin-template#296 其实是同一个问题

**Comment by PanJiaChen** [comment]
@androidvm 的确不需要。

你可以pr一下。

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/1853
