### ISSUE TITLE
4.0 test:unit 运行 Jest 单元测试不起来

### ISSUE THREAD

**Issue by Thomas-Lei** [PanJiaChen/vue-element-admin#1804]
提示如下：
   Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

**Comment by Thomas-Lei** [comment]
项目本身可以，是我重新配置了jest造成的错误。

**Comment by XiaYuYing** [comment]
我也遇到了这个错误，但是我没有改babel.config.js和jest.config.js，只是删了一些用不到的文件，加了自己的文件，也报了这个错，不知道从哪里入手，有什么思路可以提供一下么

**Comment by XiaYuYing** [comment]
#https://github.com/vuejs/vue-cli/issues/1584#issuecomment-491555534
如果有人遇到相同情况，可以看一下这里，babel-jest的版本`^23.6.0` 然后删掉`package-lock.json`重新再`npm i `一下，我是这么解决的。
