### ISSUE TITLE
怎么把导航栏的Dashboard名称改为home

### ISSUE THREAD

**Issue by gulang12** [PanJiaChen/vue-element-admin#1808]
怎么把导航栏的Dashboard名称改为home,并且点击时默认跳转 /home页面

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/26d1bf09fd7e1c2663ad761b67dda9d1262edf5a/src/components/Breadcrumb/index.vue#L36-L39


https://github.com/PanJiaChen/vue-element-admin/blob/26d1bf09fd7e1c2663ad761b67dda9d1262edf5a/src/router/index.js#L73-L85
