### ISSUE TITLE
npm install err

### ISSUE THREAD

**Issue by lixin5257xx** [PanJiaChen/vue-element-admin#1810]
依赖安装不上，第一种方法npm install 报错如下
![image](https://user-images.githubusercontent.com/11715376/55321001-1f226780-54ab-11e9-8c82-12a9ea1cd33e.png)

第二种方法npm install --registry=https://registry.npm.taobao.org 报错如下：
![image](https://user-images.githubusercontent.com/11715376/55321091-627cd600-54ab-11e9-943a-ceaf6bb9dffb.png)

备注：git 版本已经更新到2.21.0，node 版本10.15.1
![image](https://user-images.githubusercontent.com/11715376/55321169-90621a80-54ab-11e9-9e7d-3bf094c3ce86.png)

**Comment by PanJiaChen** [comment]
你确定不是自己ssl有问题么。。

**Comment by lixin5257xx** [comment]
git clone https://github.com/nhnent/raphael.git可以下载下来，下载完成后，继续安装，还是同样的报错，网上查看一些相关报错资料，也都是git版本问题，我今天刚刚更新的git，版本蛮高的。不知道具体原因了。。。
![image](https://user-images.githubusercontent.com/11715376/55322762-ce613d80-54af-11e9-83a6-defaff6dd55d.png)

**Comment by lixin5257xx** [comment]
已经启动起来了，最终解决方案是，卸载自己的git，然后下载最新的git，单纯的依靠新版本git覆盖旧版本git是不可以的
