### ISSUE TITLE
固定header开启后，github-corner显示不全

### ISSUE THREAD

**Issue by AnnieYoung** [PanJiaChen/vue-element-admin#1811]
![image](https://user-images.githubusercontent.com/32160859/55371421-c2699000-5530-11e9-8dab-ccbe3c42f4df.png)
大约是这样....

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/a8c6e11ee66e5c9902a09bddf6d8aecccd9866ad
