### ISSUE TITLE
为什么发起http的post请求，浏览器的method显示是OPTIONS

### ISSUE THREAD

**Issue by gulang12** [PanJiaChen/vue-element-admin#1813]
Request URL: http://www.vuetpadmin.com/admin/index/login
Request Method: OPTIONS
Status Code: 200 OK
Remote Address: 127.0.0.1:80
Referrer Policy: no-referrer-when-downgrade

**Comment by moonose** [comment]
https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request

跨域请求会先发option请求，如果server返回access-control-allow-origin头为*或者和当前域名一致的话，才会进入第二段的真正请求。不然就会报 cross origin request is forbidden错误。
