### ISSUE TITLE
关于table :span-method的一点问题

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#1814]
实在不知道怎么解决了，望各位大大们提供下思路。
 
我动态生成了card， 每个card里又动态产生不同的table，每个table有不同的row span效果。我的代码如下。很显然，所有table目前都调用同一个方法objectSpanMethod，我想实现不同table有不同的row span效果，那需要往objectSpanMethod里增加参数，但element-ui里的table好像参数定死了。有什么好的思路？

非常感谢！
```
<el-card v-for="(f, i) in arrangedflightInDay" :key="f.id" :name="f.name" class="box-card" >
    <div class="clearfix">
        <el-table
            :data="arrangedPlanInDay[i].content"
            :span-method="objectSpanMethod"
            >
            <el-table-column type="selection" width="40">&nbsp;</el-table-column>
        </el-table>
    </div>
</el-card>
```

**Comment by PanJiaChen** [comment]
有问题请提供一个在线demo 方便人家。比如element-ui 用的 `codepen`

**Comment by moonose** [comment]
https://codepen.io/moonose/pen/oOzpqv

见样例，我想能传个参数给objectSpanMethod， 这样我就能分辨是具体哪个table了。
目的是为了实现同一个页面中不同表格的行合并

**Comment by PanJiaChen** [comment]
https://codepen.io/anon/pen/WWGMxK

用一个高阶函数套一下就可以了。

**Comment by moonose** [comment]
赞，受教了！谢谢大神。

**Comment by moonose** [comment]
https://codepen.io/moonose/pen/MROGqZ?editors=1111

@PanJiaChen  只能再请教下了，我在 @selection-change 套用你说说的高阶函数，但没什么效果。不知道什么原因。同样，我打算在@selection-change,多传一个参数.

又骚扰你了，非常麻烦！

**Comment by PanJiaChen** [comment]
一个是 methods 一个是 event, 所以`selection-change`是不支持这样写的。

最简单的解决方案是，把你想穿的参数实现写写进每个table的row里面。

**Comment by moonose** [comment]
@PanJiaChen  谢了
尝试了下这个方法，selection-change="(p)=>selectionRecords(p, i)"  但好像会引起this指针的不知道什么问题。但目前用这个方法可行。

**Comment by Huhaikang** [comment]
<el-form label-position="left">
        <el-form-item label="发货明细：">
          <el-table v-loading="tableLoading" :data="orderDeliveryList" :span-method="spanMethod" border style="width:100%; margin-bottom:30px;">
            <el-table-column label="产品名称" :formatter="formatter" prop="productName" column-key="span" />
            <el-table-column label="商品编码" :formatter="formatter" prop="code" column-key="span" />
            <el-table-column v-for="(name,index) in attributeNames" :key="index" :label="name" column-key="span">
              <template slot-scope="{row}">{{ getAttributeValueByOrder(name,row) }}</template>
            </el-table-column>
            <el-table-column label="单位" :formatter="formatter" prop="unitId" column-key="span" />
            <el-table-column label="应发数量" prop="deliveryQuantity" column-key="span" />
            <el-table-column v-if="isFinish" label="实发数量" prop="quantity" />
            <el-table-column v-if="isFinish" :formatter="formatter" label="仓位" prop="warehouseId" />
          </el-table>
        </el-form-item>
        <el-form-item label="备注：">{{ value.remark || '无' }}</el-form-item>
      </el-form>
这个情况下数据显示不正常而v-show 就可以不知道什么问题

**Comment by Huhaikang** [comment]
`<el-form label-position="left">
        <el-form-item label="发货明细：">
          <el-table v-loading="tableLoading" :data="orderDeliveryList" :span-method="spanMethod" border style="width:100%; margin-bottom:30px;">
            <el-table-column label="产品名称" :formatter="formatter" prop="productName" column-key="span" />
            <el-table-column label="商品编码" :formatter="formatter" prop="code" column-key="span" />
            <el-table-column v-for="(name,index) in attributeNames" :key="index" :label="name" column-key="span">
              <template slot-scope="{row}">{{ getAttributeValueByOrder(name,row) }}</template>
            </el-table-column>
            <el-table-column label="单位" :formatter="formatter" prop="unitId" column-key="span" />
            <el-table-column label="应发数量" prop="deliveryQuantity" column-key="span" />
            <el-table-column v-show="isFinish" label="实发数量" prop="quantity" />
            <el-table-column v-show="isFinish" :formatter="formatter" label="仓位" prop="warehouseId" />
          </el-table>
        </el-form-item>
        <el-form-item label="备注：">{{ value.remark || '无' }}</el-form-item>
      </el-form>`

**Comment by Huhaikang** [comment]
`<el-form label-position="left">`
      `  <el-form-item label="发货明细：">`
          `<el-table v-loading="tableLoading" :data="orderDeliveryList" :span-method="spanMethod" border style="width:100%; margin-bottom:30px;">`
          `  <el-table-column label="产品名称" :formatter="formatter" prop="productName" column-key="span" />`
           ` <el-table-column label="商品编码" :formatter="formatter" prop="code" column-key="span" />`
          `  <el-table-column v-for="(name,index) in attributeNames" :key="index" :label="name" column-key="span">`
             ` <template slot-scope="{row}">{{ getAttributeValueByOrder(name,row) }}</template>`
           ` </el-table-column>`
           ` <el-table-column label="单位" :formatter="formatter" prop="unitId" column-key="span" />`
           ` <el-table-column label="应发数量" prop="deliveryQuantity" column-key="span" />`
           ` <el-table-column v-show="isFinish" label="实发数量" prop="quantity" />`
           ` <el-table-column v-show="isFinish" :formatter="formatter" label="仓位" prop="warehouseId" />`
         ` </el-table>`
        `</el-form-item>`
      `  <el-form-item label="备注：">{{ value.remark || '无' }}</el-form-item>`
     ` </el-form>`

这个情况下数据显示不正常而v-show 就可以不知道什么问题
