### ISSUE TITLE
滚动侧边栏，app-main部分分跟着滚动

### ISSUE THREAD

**Issue by xiaopingfeng** [PanJiaChen/vue-element-admin#1816]
用鼠标滚轮滚动侧边栏的时候，如果滚动到底了继续滚动。有时候会造成app-main部分滚动。

验证过  sticky 和 complex table 两个页面试过。

有的时候，光标进入到侧边栏后。鼠标滚轮滚动生效的还是主体部分，侧边栏不动

**Comment by PanJiaChen** [comment]
滚到底滚页面是正常现象。
