### ISSUE TITLE
路由跳转没有反应是怎么回事

### ISSUE THREAD

**Issue by gulang12** [PanJiaChen/vue-element-admin#1817]
我登入成功后想跳转到下面的路由，但是没有反应
 login(this.loginForm.username, this.loginForm.password, this.loginForm.vertify).then(response => {
                if(response.code==1) {

                    this.$router.push({path: '/example/table'}); // 跳转到后台
                    console.log(this.$router)
                }else{
                    this.notice = response.msg
                    this.refreshVertify()  // 刷新验证码
                }
                this.loading = false
            })

**Comment by PanJiaChen** [comment]
请在 `@src/permission.js`中自行debug。
或者你确定`login`函数走到回调里面了么。

**Comment by gulang12** [comment]
> 请在 `@src/permission.js`中自行debug。
> 或者你确定`login`函数走到回调里面了么。

是的，已经执行到这了，但是就是不跳转
this.$router.push({path: '/example/table'}); // 跳转到后台
   console.log(this.$router)
