### ISSUE TITLE
面包屑文字修改

### ISSUE THREAD

**Issue by magengxin** [PanJiaChen/vue-element-admin#1818]
请问如何做到面包屑文字和路由里面配置的文字不一样，我在面包屑组件里面修改了一下，发现它们是一个变量，左侧名称可以修改，但是面包屑文字跟左侧都一样了，现在想做到不一样，该如何设置？

**Comment by PanJiaChen** [comment]
自己加一个变量不就好了。
比如meta:{title:'foo',breadcrumb:'bar'}

或者做一次映射
```js
const breadcrumb = {
  foo:'bar'
}

function getTitle(title){
	if(breadcrumb[title]){
		return breadcrumb[title]
	}
	
	return title
}

```

**Comment by magengxin** [comment]
meta:{title:'foo',breadcrumb:'bar'}
试了上面的方法，还是没成功，面包屑文字和左侧一样改变了 
![Snipaste_2019-04-03_15-39-54](https://user-images.githubusercontent.com/23067574/55461355-cd065100-5626-11e9-9074-6601ff38e9fa.png)

**Comment by PanJiaChen** [comment]
你当然也要改`breadcrumb`源码

**Comment by magengxin** [comment]
怎么修改呢？
