### ISSUE TITLE
你好，使用的模板分支，没有测试环境配置， 自己参考著项目配置sit，打包报错

### ISSUE THREAD

**Issue by Kevinl7** [PanJiaChen/vue-element-admin#1819]
使用 npm run build:prod 打包正常，
自己配置的 npm run build:sit 打包报错
![image](https://user-images.githubusercontent.com/22197685/55448532-ae8a6080-55fa-11e9-8c52-48e6777c2744.png)

**Comment by PanJiaChen** [comment]
你babel没配对。

**Comment by Kevinl7** [comment]
我是参考 master分支，配置的。 我的理解 npm run build:sit  和 npm run build:prod 只是读取不同的配置URL，之后的打包应该是一样的吧？ npm run build:prod 是可以正常打包的。
