### ISSUE TITLE
页面刷新调到404

### ISSUE THREAD

**Issue by nevermind123456** [PanJiaChen/vue-element-admin#182]
我自己又创建了一个路由，登录跳转到这个路由之后，如果刷新就会跳转到404页面。跳转到404之后，改变浏览器上面的路径，无论改变路径成什么，都是跳转到404页面。不知道怎么回事

**Comment by PanJiaChen** [comment]
你创建的路由不正确
任何不正确的路由都会重定向到404
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/router/index.js#L166

**Comment by nevermind123456** [comment]
怎么通过不同的权限登录跳转之后，左侧显示不同的路由列表呢？这个现在可以实现吗

**Comment by PanJiaChen** [comment]
本项目已实现，详情看参考https://segmentfault.com/a/1190000009506097

**Comment by nevermind123456** [comment]
roles.some这是是什么啊？好像没有看到some是哪里来的呢？

**Comment by PanJiaChen** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

**Comment by nevermind123456** [comment]
meta: { role: ['admin','super_editor'] },这个权限好像并没有效果啊，不同的权限进去之后，左侧都是全部展示出来了呢，没有根据权限展示左侧的路由的呢。

**Comment by PanJiaChen** [comment]
请自己好好看文章和代码

**Comment by Zephyen** [comment]
@nevermind123456 我也遇到一刷新后本来能够正常显示的页面。就变成404了。你是怎么解决的？

**Comment by luggege** [comment]
子路径下部署的项目,一刷新为什么会404
