### ISSUE TITLE
官网有错误

### ISSUE THREAD

**Issue by lixin5257xx** [PanJiaChen/vue-element-admin#1820]
链接也有问题：
https://github.com/PanJiaChen/vue-element-admin/tree/master/src/views/layout更改为
https://github.com/PanJiaChen/vue-element-admin/tree/master/src/layout
![image](https://user-images.githubusercontent.com/11715376/55448664-35d7d400-55fb-11e9-947d-a19c64f317ba.png)

**Comment by PanJiaChen** [comment]
恩文档还没来得及更新为4.0版本。
欢迎pr。

**Comment by lixin5257xx** [comment]
我头一次PR，我尝试下，如果弄得不对，请忽略。。。。
