### ISSUE TITLE
改变vuex里的值后，页面没更新过来

### ISSUE THREAD

**Issue by liaohongsen** [PanJiaChen/vue-element-admin#1821]
我在页面点击按钮触发一个事件提交actions然后commit修改vuex里的值，值是修改成功了，但是另外个页面渲染的这个值还是之前那个
![QQ图片20190403110906](https://user-images.githubusercontent.com/16487300/55450298-2f4c5b00-5601-11e9-8323-1df088ab17f6.png)
![QQ图片20190403111204](https://user-images.githubusercontent.com/16487300/55450387-805c4f00-5601-11e9-8f90-720bb91f882b.png)
![QQ图片20190403111216](https://user-images.githubusercontent.com/16487300/55450390-82261280-5601-11e9-8c49-afb9f162545c.png)
![QQ图片20190403111257](https://user-images.githubusercontent.com/16487300/55450395-83efd600-5601-11e9-9d24-a9f11d96843f.png)
![QQ图片20190403111424](https://user-images.githubusercontent.com/16487300/55450435-aaae0c80-5601-11e9-9c39-b818309f6003.png)
麻烦大哥看一下，这个name是修改成功了，但是我希望另外个页面及时更新

**Comment by PanJiaChen** [comment]
没看出什么问题。有问题请提供在线demo。

**Comment by liaohongsen** [comment]
> 没看出什么问题。有问题请提供在线演示。

![QQ图片20190403133802](https://user-images.githubusercontent.com/16487300/55455326-d1763e00-5615-11e9-8672-5e9c7d7eceb1.png)
![QQ图片20190403133813](https://user-images.githubusercontent.com/16487300/55455335-d4712e80-5615-11e9-968d-bf5c848af1a2.png)
就是我点击第一张图的btn，然后修改store里面的值，我想让第二张图的test333跟着我修改的值变化，它的值来源于store里面,但是没任何反应

**Comment by PanJiaChen** [comment]
你不给一个在线复现的demo。。我怎么debug

**Comment by liaohongsen** [comment]
> 你不给一个在线复现的demo。。我怎么debug
> 
> 通过你的截图，我肉眼没看出什么问题。

我的问题，我用的两个浏览器窗口来观察，这样是不行的

**Comment by PanJiaChen** [comment]
...
