### ISSUE TITLE
日期组件无法调用type为monthrange

### ISSUE THREAD

**Issue by leishihong** [PanJiaChen/vue-element-admin#1823]
<el-date-picker
      v-model="value15"
      type="monthrange"
      range-separator="至"
      start-placeholder="开始月份"
      end-placeholder="结束月份">
    </el-date-picker>
本地引入无法使用

**Comment by PanJiaChen** [comment]
https://github.com/ElemeFE/element/releases/tag/v2.6.2

element v2.6.2 之后才支持。
