### ISSUE TITLE
更换主题颜色为黄色的问题！

### ISSUE THREAD

**Issue by HelloMeme** [PanJiaChen/vue-element-admin#1825]
## Bug report 
更换主题颜色为黄色「#E6A23C」，或者在正常颜色下更换时输入「#E6A23C」这个值，页面显示会有问题，左侧菜单栏消失，右侧样式错位。

#### Screenshot or Gif（截图或动态图）
1.开始选择
![image](https://user-images.githubusercontent.com/7801690/55464846-8b79a400-562e-11e9-9713-f57c48a96d61.png)
2.选择后
![image](https://i.loli.net/2019/04/03/5ca471b956d46.png)

#### Other relevant information（格外信息）
- Your OS: MacOS  Mojave
- Node.js version: v11.10.0
- vue-element-admin version: v3.11.0

**Comment by PanJiaChen** [comment]
能提供一下截图么

**Comment by HelloMeme** [comment]
> 能提供一下截图么

已上传

**Comment by PanJiaChen** [comment]
你试试 `v4.0`版本

**Comment by HelloMeme** [comment]
> 你试试 `v4.0`版本

官网 demo：https://panjiachen.github.io/vue-element-admin#/dashboard 没问题

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/components/ThemePicker/index.vue

你可以借鉴一下。老版本不在维护了。
