### ISSUE TITLE
把此模板换成自己请求配置完之后报错

### ISSUE THREAD

**Issue by ROSEMUSE** [PanJiaChen/vue-element-admin#1827]
#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/32162134/55468946-0cd53480-5637-11e9-9ec1-855cb43a2c80.png)

#### Link to minimal reproduction（最小可在线还原demo）
![image](https://user-images.githubusercontent.com/32162134/55468989-237b8b80-5637-11e9-890f-685b3e76fb75.png)

#### Ot- Node.js version_- vue-element-admin version_her relevant information（格外信息）
- Your O

**Comment by PanJiaChen** [comment]
报错已经很明显了吧。
