### ISSUE TITLE
example/ArticleList编辑页面 刷新导航条高亮丢失

### ISSUE THREAD

**Issue by 1142338114** [PanJiaChen/vue-element-admin#1829]
![image](https://user-images.githubusercontent.com/35951066/55477245-26807700-564b-11e9-90e7-8694567d6dc1.png)

**Comment by 1142338114** [comment]
点击edit

**Comment by PanJiaChen** [comment]
Added in https://github.com/PanJiaChen/vue-element-admin/pull/1833
