### ISSUE TITLE
When `Fixed Header` is enabled, the error log dialog does not appear correctly

### ISSUE THREAD

**Issue by ansonhorse** [PanJiaChen/vue-element-admin#1830]
## Bug report（问题描述）
When `Fixed Header` is enabled, the error log dialog does not appear correctly.

#### Steps to reproduce（问题复现步骤）
1. Enable `Fixed Header`
2. Fire some errors (visit `/error-log/log` for example)
3. Click the the bug icon to open the error log dialog

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/7548142/55484673-841cbf80-565b-11e9-9552-cf7982f5e250.png)

#### Other relevant information（格外信息）
- Your OS: MacOS
- Node.js version: 8.12.0
- vue-element-admin version: 4.0.0

#### Temporary solution
Make the dialog append to body by set `append-to-body` to `true`
```html
<el-dialog :visible.sync="dialogTableVisible" :append-to-body="true">
```

**Comment by PanJiaChen** [comment]
PR Welcome @ansonhorse

**Comment by ansonhorse** [comment]
PR https://github.com/PanJiaChen/vue-element-admin/pull/1844
