### ISSUE TITLE
请问怎么使用jquery

### ISSUE THREAD

**Issue by aloncn** [PanJiaChen/vue-element-admin#1831]
新手问题，看到[网上说](https://blog.csdn.net/JEFF_luyiduan/article/details/88124509)在webpack.base.conf.js里面的plugins:[]添加相应的jquery插件，不过我看build下面并没有webpack.base.conf.js ，只有 build/index.js

**Comment by bruceKP** [comment]
在vue里面使用jquery有点多此一举啊

**Comment by PanJiaChen** [comment]
https://github.com/vuejs/vue-cli/issues/1647#issuecomment-399093605

4.0版本改用 vue-cli 构建。你依然可以使用`ProvidePlugin`来自动注册 `jQuery`。

**Comment by 1xiongyuwen1** [comment]
我已经引入成功了，请问在vue页面中怎么调用，谢谢
