### ISSUE TITLE
How can I check permission who did direct access?

### ISSUE THREAD

**Issue by ubitoffee** [PanJiaChen/vue-element-admin#1834]
## Question（提问）

I have permission in router like below (it's children route of 'recruit')
```javascript
{
      path: 'group-recruit',
      component: () => import('@/views/recruit/groupRecruitManagement'),
      name: 'group-recruit',
      meta: {
        title: 'groupRecruit',
        roles: ['admin', 'recruit-admin']
      }
}
```

But when I access like '/recruit/group-recruit', there is no meta in to (router.beforeEach)
```javascript
if (hasPermission(store.getters.roles, to.meta.roles)) {
          console.log(to)
          next()
        } else {
          next({ path: '/401', replace: true, query: { noGoBack: true }})
        }
}
```

like below
![image](https://user-images.githubusercontent.com/14308115/55528697-c33d2600-56d8-11e9-8f93-386b83922c85.png)

How can I handle it?

**Comment by PanJiaChen** [comment]
I haven't been able to reproduce your problem. On normal, you can get `meta`.

**Comment by ubitoffee** [comment]
@PanJiaChen 
I migrate 3.1.X to 4.0 and now it works.
I do appreciate about your vue-element-admin. Thanks a lot.

Anyway, Is there a best practice to migrate from the previous version to the next?

**Comment by PanJiaChen** [comment]
no....

Too many breaking changes.

**Comment by ubitoffee** [comment]
OK.. I should follow up minor version update. Thanks a lot!
