### ISSUE TITLE
master 4.0.0 版本需要安装 postcss

### ISSUE THREAD

**Issue by NemoHzy** [PanJiaChen/vue-element-admin#1838]
## Bug report（问题描述）
master 版本 4.0.0 npm run dev 失败，无法启动， 缺少 autoprefixer

#### Steps to reproduce（问题复现步骤）

错误日志截取
 @ multi ./node_modules/@vue/cli-service/node_modules/webpack-dev-server/client?http://172.16.25.91:9527/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/components/ErrorLog/index.vue?vue&type=style&index=0&id=cf51e862&scoped=true&lang=css&

Module build failed (from ./node_modules/@vue/cli-service/node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: Cannot find module 'autoprefixer'

npm i -D \
  postcss-loader \
  postcss-import \
  postcss-cssnext \
  cssnano \
  sugarss \
  autoprefixer

或者

yarn add --dev \
  postcss-loader \
  postcss-import \
  postcss-cssnext \
  cssnano \
  sugarss \
  autoprefixer

可编译通过，是不是都要手动装一下？还是可以直接加到 package.json 里面？

**Comment by PanJiaChen** [comment]
这是`@vue/cli-service`做的事情。

**Comment by xiaojia21190** [comment]
这个不能编译通过。有解决方法吗？

**Comment by PanJiaChen** [comment]
@xiaojia21190 最新代码拉下来没做任何改动就有这问题？若有问题请提供系统消息。

**Comment by 15036900300** [comment]
<img width="1639" alt="image" src="https://user-images.githubusercontent.com/15808969/55771473-d37b4980-5aba-11e9-913c-d449b00e543c.png">
<img width="1645" alt="image" src="https://user-images.githubusercontent.com/15808969/55771506-e857dd00-5aba-11e9-92db-b417e31f96a8.png">

@PanJiaChen 下载的代码没做任何改动，就是上方的问题

**Comment by 15036900300** [comment]
已经解决`npm install autoprefixer --save`，缺少对应模块，该命令解决问题

**Comment by PanJiaChen** [comment]
应该是 npm 没完全安装成功。
我这里你不能复现。

**Comment by luwzchn** [comment]
虽然讨论关闭了，我也遇到了同样的问题，下载的代码没有任何改动一样跑不起来。
node v10.15.3
npm 6.4.1
 @vue/cli  3.5.5

**Comment by PanJiaChen** [comment]
@luwzchn 也是少 `autoprefixer`?

**Comment by luwzchn** [comment]
@PanJiaChen  是的，提示少 autoprefixer 过不了sass ，我去\vue-element-admin\node_modules\@vue\cli-service\node_modules\autoprefixer 是存在的， 删了重新install也进来，问题依旧

**Comment by 15036900300** [comment]
> @PanJiaChen 是的，提示少 autoprefixer 过不了sass ，我去\vue-element-admin\node_modules@vue\cli-service\node_modules\autoprefixer 是存在的， 删了重新install也进来，问题依旧
> 
> 使用 vue create my-project 创建的项目配置 sass 正常。

`npm install autoprefixer --save`这个命令使用了也还不行啊？

**Comment by luwzchn** [comment]
@15036900300 用这个是可行的，但是这个东西不是已经@vue/cli-service 自动管理的，为什么还要自己引入，这是个问题

**Comment by easin** [comment]
> npm install autoprefixer --save

我也是这样子解决的，master分支建议加上

**Comment by PanJiaChen** [comment]
已加上。
