### ISSUE TITLE
可拖拽面板，firebox触发搜索

### ISSUE THREAD

**Issue by CuiYang16** [PanJiaChen/vue-element-admin#1839]
## Bug report（问题描述）
可拖拽面板，拖拽是，在Firefox浏览器会触发搜索弹出新的tab

#### Steps to reproduce（问题复现步骤）
1.拖拽面板
2.弹出新的tab

#### Other relevant information（格外信息）
- Your OS:window 7
- Node.js version:6.4.1
- vue-element-admin version:4.0.0

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/1841
