### ISSUE TITLE
prettier 在项目好像完全没用到

### ISSUE THREAD

**Issue by hipi** [PanJiaChen/vue-element-admin#1843]

**Comment by PanJiaChen** [comment]
恩，没有必要。eslint已经满足大部分需求。

**Comment by cyea** [comment]
如果 我想 引入 `eslint-config-prettier`  + `prettier` 作为格式化工具该怎么引入呢

**Comment by PanJiaChen** [comment]
你可以 参照 vue-cli 的做法 https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/eslint-config-prettier/README.md

**Comment by superAo005** [comment]
> 恩，没有必要。eslint已经满足大部分需求。
prettier保证多人协作统一代码风格 怎么回没有必要呢
