### ISSUE TITLE
v4.0.0 mock 不支持热更新

### ISSUE THREAD

**Issue by AleynHe** [PanJiaChen/vue-element-admin#1849]
## Bug report（问题描述）
v4.0.0 开发环境 mock/* 相关代码不支持热更新。

#### Steps to reproduce（问题复现步骤）
1. npm run dev 启动应用
2. 动态添加mocks模块 或者 只变更已注册API响应方法体
3. 热更新失效

#### Screenshot or Gif（截图或动态图）
无

#### Link to minimal reproduction（最小可在线还原demo）
无

#### Other relevant information（格外信息）
- Your OS:  windows 10
- Node.js version:  v8.12.0
- vue-element-admin version:  v4.0.0

**Comment by PanJiaChen** [comment]
暂时是的，mock server 不支持热更新。我优化一下吧。

**Comment by AleynHe** [comment]
优化这么迅速，赞

**Comment by xuxihai123** [comment]
很久没看这个仓库了，前些天写了一个vue-cli3的mock插件。
可以减少一些工作, 感觉可以简化这个项目。https://github.com/xuxihai123/vue-cli-plugin-mock
