### ISSUE TITLE
Example of optional url params and aliases for routes 

### ISSUE THREAD

**Issue by Abdulsametileri** [PanJiaChen/vue-element-admin#1851]
Is it possible to implement examples of aliases and optional url params? I'm having a hard time integrating these structures because many things is handled automatically in this project.

**Comment by PanJiaChen** [comment]
I don't quite understand what `aliases and optional url params` is? 
What exactly is your problem?

**Comment by Abdulsametileri** [comment]
### I just want to use route below with optional param what is userId.

` 
{

        path: '/cetele-doldur/:userId?', 
        component: Layout,
        meta: { title: 'Çetele Doldur', icon: 'form' },
        children: [
            {
                path: '',
                name: 'CeteleDoldur',
                component: () => import('@/views/cetele/ceteledoldur/index.vue'),
            },
        ]
    }`

When I click this this route in the sidebar, the url comes out automatically.
> http://localhost:8080/cetele-doldur/:userId 

I don't want user id to appear in the url because it is optional. 

How can I solve this? @PanJiaChen

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/083a4ada9db5fc9de9988d1b1a959dc17dd8bcd8/src/router/index.js#L195-L199

Dynamic param routing, should not appear in the sidebar.

**Comment by Abdulsametileri** [comment]
Hmm. Okay great. I suppose my problem is to use this template. 

[](https://github.com/Armour/vue-typescript-admin-template/tree/master/src/views/layout)

**Comment by Abdulsametileri** [comment]
> [vue-element-admin/src/router/index.js](https://github.com/PanJiaChen/vue-element-admin/blob/083a4ada9db5fc9de9988d1b1a959dc17dd8bcd8/src/router/index.js#L195-L199)
> 
> Lines 195 to 199 in [083a4ad](/PanJiaChen/vue-element-admin/commit/083a4ada9db5fc9de9988d1b1a959dc17dd8bcd8)
> 
>  path: 'edit/:id(\\d+)', 
>  component: () => import('@/views/example/edit'), 
>  name: 'EditArticle', 
>  meta: { title: 'editArticle', noCache: true }, 
>  hidden: true 
> Dynamic param routing, should not appear in the sidebar.

I also have a one question.
For example, How can I use this route with two params article name and id.

I want url to be like (id will not appear in the url. But I send with route params.)
http://localhost:9527/#/example/edit/article_name,

**Comment by PanJiaChen** [comment]
https://router.vuejs.org/api/#routes

use `meta:{id:1}`

**Comment by Abdulsametileri** [comment]
> ### I just want to use route below with optional param what is userId.
> `
> {
> 
> ```
>     path: '/cetele-doldur/:userId?', 
>     component: Layout,
>     meta: { title: 'Çetele Doldur', icon: 'form' },
>     children: [
>         {
>             path: '',
>             name: 'CeteleDoldur',
>             component: () => import('@/views/cetele/ceteledoldur/index.vue'),
>         },
>     ]
> }`
> ```
> When I click this this route in the sidebar, the url comes out like below automatically.
> 
> > http://localhost:8080/cetele-doldur/:userId
> 
> I don't want user id to appear in the url because it is optional.
> 
> I just need two url's like
> 
> > http://localhost:8080/cetele-doldur/
> 
> and
> 
> > http://localhost:8080/cetele-doldur/:userId
> 
> with the same component.
> 
> How can I solve this without breaking your structure? @PanJiaChen

Is there any recommendation to solve this problem? May you look implementation of vue-typescript-admin-template to help me?

**Comment by Abdulsametileri** [comment]
> https://router.vuejs.org/api/#routes
> 
> use `meta:{id:1}`

When ı reload page? Can I lose route's meta information?

**Comment by PanJiaChen** [comment]
I don't think this has anything to do with admin-template. It is completely related to vue-router.

If you want to refresh the page and remember the parameters, please use `query`

**Comment by Abdulsametileri** [comment]
> I don't think this has anything to do with admin-template. It is completely related to vue-router.
> 
> If you want to refresh the page and remember the parameters, please use `query` or `params`

**Comment by Abdulsametileri** [comment]
When I use params 

> this.$route.push({name: 'CeteleDoldur', params: { name: studentName, id: studentId}) 
the url appears like 
http://localhost:8080/cetele-doldur/PanJiaChen 
when I reload,
the id information has gone. But name is still stand.

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/55700834-6c4e8e00-5a03-11e9-857a-665456ee37fa.png)
https://router.vuejs.org/guide/essentials/dynamic-matching.html#reacting-to-params-changes

**Comment by Abdulsametileri** [comment]
> Dynamic param routing, should appear in the sidebar. @PanJiaChen 
When I change your example/list/edit route, _removing (\d+)_ and _hidden: false_
{
        path: **'edit/:id',**
        component: () => import('@/views/example/edit'),
        name: 'EditArticle',
        meta: { title: 'editArticle', noCache: true },
        ### hidden: false
},

Then Click Edit Article in the sidebar

![Screen Shot 2019-04-08 at 10 11 52 AM](https://user-images.githubusercontent.com/19360039/55705161-cdb43400-59e6-11e9-975e-429bb97ae3c4.png)

 the url appears like

> http://localhost:9527/#/example/edit/:id

Same problem.

How can I handle this?

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/55705834-4e3c5a00-5a12-11e9-81d4-a2c09acb1ea9.png)

**Comment by Abdulsametileri** [comment]
I cannot tell.

![Screen Shot 2019-04-08 at 10 25 38 AM](https://user-images.githubusercontent.com/19360039/55706028-d279e780-59e8-11e9-9ac6-e1cee3cf9059.png)

This is my sidebar. I want to use this way.

> When I click (1) the url appears http://localhost:8080/cetele-doldur/Abdulsamet-İleri

> When I click (2) the url appears http://localhost:8080/cetele-doldur/

But now 
> When I click (1) the url appears http://localhost:8080/cetele-doldur/Abdulsamet-İleri That's OK.
> When I click (2) the url appears http://localhost:8080/cetele-doldur/:name

this is my problem. 


```
{
        path: '/cetele-doldur/:name',
        component: Layout,
        meta: { title: 'Çetele Doldur', icon: 'form' },
        children: [
            {
                path: '',
                name: 'CeteleDoldur',
                component: () => import('@/views/cetele/ceteledoldur/index.vue'),
                props: true,
            },
        ]
    }
```

**Comment by PanJiaChen** [comment]
How do you write the route of `cetele-doldur/Abdulsamet-İleri`?

**Comment by Abdulsametileri** [comment]
```
this.$router.push(
              { name: 'CeteleDoldur',
                 params: {
                  name: row.first_name + '-' + row.last_name,
                }});
```

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/55708029-81cdb300-5a17-11e9-8d59-0e923c403021.png)

So what is `cetele-doldur` used for? Why does it not require a name.

**Comment by Abdulsametileri** [comment]
In my project there are two roles. Student and Teacher.

The Student can enter the number of questions he solved on his own via 'Çetele Doldur (2)'. So name is not required. 

The Teacher can also enter the number of solved questions from his students via Çetele Doldur(1). Teacher selects student in the table as above and enter his/her solved questions.

**Comment by PanJiaChen** [comment]
So they should not be the same route.

```js
//for teacher
{
        path: '/cetele-doldur/:name?',
        component: Layout,
        meta: { title: 'Çetele Doldur', icon: 'form' },
        children: [
            {
                path: '',
                name: 'CeteleDoldur',
                component: () => import('@/views/cetele/ceteledoldur/index.vue'),
                props: true,
            },
        ]
    }

//for student
{
        path: '/cetele-doldur/',
        component: Layout,
        meta: { title: 'Çetele Doldur', icon: 'form' },
        children: [
            {
                path: '',
                name: 'CeteleDoldur',
                // maybe the component also not the same
                component: () => import('@/views/cetele/ceteledoldur/index.vue'),
                props: true,
            },
        ]
    }
```

**Comment by Abdulsametileri** [comment]
// maybe the component also not the same

Everything same(template, styles, variables etc.) just api calls are different for teacher and student. Is reasonable to use two components?
