### ISSUE TITLE
移动端问题

### ISSUE THREAD

**Issue by yizantianxia** [PanJiaChen/vue-element-admin#1852]
在ios上，顶部下拉会在顶部出现空白，底部上拉会在底部出现空白，如何不允许顶部下拉和底部上拉呢？
![微信图片_20190408082028](https://user-images.githubusercontent.com/32086491/55692179-08fb3680-59d8-11e9-8467-13a15a557124.png)
![微信图片_20190408082042](https://user-images.githubusercontent.com/32086491/55692181-0bf62700-59d8-11e9-9232-bbcf92fc6d91.png)

**Comment by PanJiaChen** [comment]
请按照正确的issue模板提问。

我在ios12上的safari上没能重现你的问题。

**Comment by yizantianxia** [comment]
@PanJiaChen 
可能我描述不太清，就是按住屏幕往下拉，在浏览器地址栏和页面顶部会出现空白。
  safari也是，只要在ios上都是，安卓没有。
![55692179-08fb3680-59d8-11e9-8467-13a15a557124](https://user-images.githubusercontent.com/32086491/55694875-bc6c2700-59e8-11e9-9953-7515f5598ded.png)

**Comment by PanJiaChen** [comment]
没能重现？什么手机型号和系统？

**Comment by yizantianxia** [comment]
> 没能重现？什么手机型号和系统？

7p ，ios11.4

**Comment by PanJiaChen** [comment]
试了几台机器，都没能重现你的问题。

**Comment by yizantianxia** [comment]
> 试了几台机器，都没能重现你的问题。

抱歉，这个不是你项目问题，页面下拉回弹是ios特性，阻止下就ok了
