### ISSUE TITLE
文档布局layout那里，对应代码点击显示404

### ISSUE THREAD

**Issue by xiaofeng1994** [PanJiaChen/vue-element-admin#1854]
#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/45890549/55700106-8d61af80-5a00-11e9-8bd6-1b5f453f9b37.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
文档还没来得及更新。
