### ISSUE TITLE
固定 Header 下面的内容被覆盖

### ISSUE THREAD

**Issue by xiaoxiaoyu995** [PanJiaChen/vue-element-admin#1855]
## Bug report（问题描述）
1、固定 Header 没有开启的时候
![image](https://user-images.githubusercontent.com/24727136/55701484-e849d580-5a05-11e9-8ded-55c597ecc764.png)
2、开启的时候
![image](https://user-images.githubusercontent.com/24727136/55701516-01eb1d00-5a06-11e9-88bf-05e10d0a6660.png)

**Comment by PanJiaChen** [comment]
已修复。
