### ISSUE TITLE
侧边栏显示不到底

### ISSUE THREAD

**Issue by huangyus** [PanJiaChen/vue-element-admin#1858]
## Question（提问）
侧边栏显示不到底

![image](https://user-images.githubusercontent.com/45846300/55711634-a75eba80-5a1f-11e9-890f-520e74b2903c.png)

请问是在哪里可以配置吗？

**Comment by PanJiaChen** [comment]
没懂？

**Comment by huangyus** [comment]
我想要的效果是侧边栏显示到页面底部

**Comment by huangyus** [comment]
我用最新版本显示是这样的，我研究了一下，没看到在哪里来设置这个高度
![image](https://user-images.githubusercontent.com/45846300/55712913-310f8780-5a22-11e9-8482-bf76f612066e.png)

**Comment by PanJiaChen** [comment]
什么叫页面底部？

**Comment by huangyus** [comment]
你试着把router里面的路由信息删掉部份，  侧边栏就会显示白底了。当侧边栏显示的长度不够时，  背景色不会显示到底部

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/afb62edc58b61cc190ff07214c4ac37486c80850
