### ISSUE TITLE
vue.config.js中的chunk-elementUI 打包未生效

### ISSUE THREAD

**Issue by DemoHu** [PanJiaChen/vue-element-admin#1859]
## Bug report（问题描述）

clone最小的vue-cli3版本后，执行build之后发现打包的dist中并没有单独的chunk-elementUI.js
即配置了将element单独打包这个功能，但是没有生效

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin/report.html

`vue-element-admin` 并没有你说的问题。

**Comment by DemoHu** [comment]
@PanJiaChen  你好，我是直接clone您的master分支，然后npm run build:prod 
在dist/static/js下确实没有找到chunk-elementUI.js相关的js 文件

**Comment by PanJiaChen** [comment]
应该没关系。

**Comment by PanJiaChen** [comment]
```bash
npm run preview -- --report
```
你可以看一下包分析

**Comment by DemoHu** [comment]
@PanJiaChen  好像确实是因为cnpm 的原因，cnpm 下载的element包名称好像无法匹配到你的`test: /[\\/]node_modules[\\/]element-ui[\\/]/` 这个正则，我刚刚改用`npm i`后，重新build `就生成了chunk-elemnt.js了`   不过考虑到使用cnpm的用户也挺多的，不知道可不可以优化一下这个正则匹配

**Comment by PanJiaChen** [comment]
欢迎pr

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/c833cb6efabdef7f2d1241d1b204e2701f8a04c1
