### ISSUE TITLE
master 分支mock-server 热更新兼容问题及建议

### ISSUE THREAD

**Issue by AleynHe** [PanJiaChen/vue-element-admin#1860]
## 问题（/mock/mock-server.js ）
   1. 方法getMockRoutesIndex循环溢出，去除=
   2. 热更新后，mockRoutesLength 长度不更新，导致增加、减少mock路由后异常express异常，应在每次调用registerRoutes后，刷新长度值
   3. 不兼容（windows），unregisterRoutes、getPath；路径字符串'/'问题导致。
   4. getPath是否一定有必要存在？？

## 优化建议
  现有mock api路由前缀固定，并在mock-server热更新代码中写死，不太适用于前后端项目，联调阶段（一键切换联调接口，特别是后端微服务化之后）
  解决：
  1. 去掉/mock/index.js responseFake中写死mock 路由前缀/mock
  2. 记录registerRoutes（/mock/mock-server.js）第一次注册进express的路由正则 URL，并转换为源字符串mockFirstRouteUrl返回（同mockRoutesLength)
  3. getMockRoutesIndex（/mock/mock-server.js）将IF判断includes('mock')更改为b)步骤中记录的includes(mockFirstRouteUrl)
  4. vue.config.js 代理/mock前缀，本地mock api是否有必要配置代理？

#### Steps to reproduce（问题复现步骤）
见问题描述

#### Screenshot or Gif（截图或动态图）
无

#### Link to minimal reproduction（最小可在线还原demo）
无

#### Other relevant information（格外信息）
- Your OS: windows 10
- Node.js version: v8.12.0
- vue-element-admin version: master-2019-04-08

**Comment by PanJiaChen** [comment]
欢迎pr

**Comment by AleynHe** [comment]
有点忙，争取本周抽空给PR

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/dbee6ff707479967c8d843fd89b040b6e7828fb0

我优化了下，用更简单的方式来清除 `_router.stack`

**Comment by dingangang** [comment]
win10下还是热更新失效。
修改mock返回数据，页面返回数据不会改变，需要重启工程才能生效，

**Comment by PanJiaChen** [comment]
@dingangang 我晚点找台windows测一下。

**Comment by dingangang** [comment]
大佬，我在ubuntu上跑了一下是正常的。win10还是不正常。
mock-server.js:
console.log(chalk.magentaBright(`\n > Mock Server hot reload success! changed  ${path}`))
win10上控制台上面这条语句是执行了的。就是页面刷新后接口返回的数据还是原来的。
/mock 文件夹下的任何修改当前都不会有反应。

**Comment by PanJiaChen** [comment]
感谢你的反馈。

**Comment by hswyxj** [comment]
mock-server.js:
unregisterRoutes 路径字符串'/'问题导致。
把 i.includes('/mock')  改成i.includes('./mock')即可

我的Windows7正常了

**Comment by dingangang** [comment]
> mock-server.js:
> unregisterRoutes 路径字符串'/'问题导致。
> 把 i.includes('/mock') 改成i.includes('./mock')即可
> 
> 我的Windows7正常了

win10下我修改后还是不正常。

**Comment by dingangang** [comment]
win10下我修改成 i.includes('\\mock') 可行了。

**Comment by dingangang** [comment]
if (i.includes('/mock') || i.includes('\\mock') || i.includes('./mock'))
修改了一下函数，我提了一个pr。这样应该都正常了。
