### ISSUE TITLE
tagviews 关闭最后一个是首页时，跳转首页没有刷新页面的问题

### ISSUE THREAD

**Issue by de1ck** [PanJiaChen/vue-element-admin#1861]
[code](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/layout/components/TagsView/index.vue#L166)
由于router,对跳转的路由没有改变时，不会触发页面刷新，所以需要使用其他方式去触发，以下是我的解决方案，利用vue-element-admin本身实现当前路由刷新的方案。
```
//   添加 view 入参
toLastView(visitedViews， view) {
      const latestView = visitedViews.slice(-1)[0]
      if (latestView) {
        this.$router.push(latestView)
      } else {
        // 添加一层判断，当前页是否为首页
       if (view.name=== 'Dashboard') this.$router.push('/redirect' + view.fullPath)
        // You can set another route
       else  this.$router.push('/')
      }
    },
```

**Comment by PanJiaChen** [comment]
按照逻辑来讲，好像的确是不需要刷新的。

**Comment by de1ck** [comment]
我的页面在router before 中使用了过度效果，会导致过度效果一直存在，直到点击其他菜单

**Comment by PanJiaChen** [comment]
恩，的确在没有 设置`affix`的情况下，会有问题。
欢迎把你的代码改动作为pr提交。

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/1866
