### ISSUE TITLE
vue-config.js中开启eslint,没有生效

### ISSUE THREAD

**Issue by DemoHu** [PanJiaChen/vue-element-admin#1862]
## Bug report（问题描述）
将`vue.config.js`中的 `lintOnSave`设置为true后，eslint没有启用，请问除了这里，还有哪里需要修改

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
你重启过服务么？

**Comment by DemoHu** [comment]
@PanJiaChen  重启了 ，没有生效

**Comment by PanJiaChen** [comment]
https://cli.vuejs.org/zh/config/#lintonsave

这个和本项目基本没什么关系。完全是cli的配置。

**Comment by DemoHu** [comment]
@PanJiaChen  嗯，在之前的vue-cli2.x 版本上没有这个问题，但是升级到vue-cli3 之后就发现了这个情况，不知道你那里有没有这个情况

**Comment by PanJiaChen** [comment]
你为什么会觉得没效果？目前项目的配置是只会显示错误，warning不显示。

**Comment by DemoHu** [comment]
PanJiaChen 额，我就是像要的是warning 也显示出来

**Comment by PanJiaChen** [comment]
```js
 overlay: {
      warnings: true,
      errors: true
    },
```

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/55718252-e562db00-5a2d-11e9-8c03-82d40232f41b.png)

**Comment by DemoHu** [comment]
@PanJiaChen   好像是这个问题 
![Snipaste_2019-04-08_18-42-53](https://user-images.githubusercontent.com/26042365/55718415-3a9eec80-5a2e-11e9-9091-a53c6dc2b5b0.png)

**Comment by DemoHu** [comment]
@PanJiaChen   测试发现，安装这个插件，并将`.eslintrc.js` 中的 `extends`改成   `extends: ["plugin:vue/essential"]`  就生效了

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/342b7b428a7e87951a03228bc2ee750cbb551eb9
