### ISSUE TITLE
Show ElementUI icons besides Icon Fonts

### ISSUE THREAD

**Issue by tuandm** [PanJiaChen/vue-element-admin#1864]
## Feature request（新功能建议）
It would be nice if we can show all supported icons so that users will easily lookup icons just in one place, [example](https://laravue.dev/#/icon/index): 
![image](https://user-images.githubusercontent.com/490446/55737384-0e03c880-5a60-11e9-9234-12929b771d7d.png)

**Comment by PanJiaChen** [comment]
Added in https://github.com/PanJiaChen/vue-element-admin/pull/1865
