### ISSUE TITLE
建议做一个websocket版的分支

### ISSUE THREAD

**Issue by guopenglun** [PanJiaChen/vue-element-admin#1868]
## Feature request（新功能建议）
建议做一个websocket版的分支

**Comment by PanJiaChen** [comment]
意义是什么？

**Comment by 15036900300** [comment]
新版我找不到配置文件了，跟3.X中的`dev.env.js`和`prod.env.js`这样的配置文件了

**Comment by guopenglun** [comment]
> 意义是什么？

个人感觉很多时候后台控制面板需要从服务器不断的拉取同一个信息，例如实时更新在线人数，
并且websocket可以规避客户端跨域的问题，只要服务器支持即可。

**Comment by PanJiaChen** [comment]
这个自己实现就好了。
