### ISSUE TITLE
侧边栏中外链 alwaysShow: true 就打不开页面

### ISSUE THREAD

**Issue by jian22446688** [PanJiaChen/vue-element-admin#1869]
侧边栏中外链 alwaysShow: true 就打不开页面 相当于路由跳转了

链接前面加了一个 ‘#/’ 

求大神帮忙看下啊

`<a href="#/https:/panjiachen.github.io/vue-element-admin-site/#" class=""><li role="menuitem" tabindex="-1" class="el-menu-item" style="padding-left: 40px;"><span>External Link</span></li></a>`

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/1870
