### ISSUE TITLE
大神，想问下左侧的导航里面的滚动条是如何隐藏的？

### ISSUE THREAD

**Issue by Paul0523** [PanJiaChen/vue-element-admin#187]

**Comment by PanJiaChen** [comment]
`::-webkit-scrollbar {display:none}`

https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

**Comment by Paul0523** [comment]
@PanJiaChen 谢谢了。

**Comment by wqb2017** [comment]
这个隐藏IE还有火狐是实现不鸟的

**Comment by PanJiaChen** [comment]
下个版本直接用js模拟了滚动 就没这问题了
