### ISSUE TITLE
左侧导航栏隐藏问题

### ISSUE THREAD

**Issue by RainbowYano** [PanJiaChen/vue-element-admin#1871]
#### 查看代码后发现element-ui中点击隐藏后，相关元素会发生变化，但是我隐藏的时候没有发生变化，只是宽度变宅，然后出现滚动条，找了一天了，发现还是不知道什么原因，烦请大佬看看
![1](https://user-images.githubusercontent.com/43380578/55847527-3c76c600-5b7c-11e9-92d8-22f632e64e9d.png)
### 总体的layout
![4](https://user-images.githubusercontent.com/43380578/55847553-56b0a400-5b7c-11e9-838a-31c95a000afe.png)

### sidebar-nav
![2](https://user-images.githubusercontent.com/43380578/55847610-8e1f5080-5b7c-11e9-8a22-f667762372d0.png)

### dynamic-menu
![3](https://user-images.githubusercontent.com/43380578/55847576-66c88380-5b7c-11e9-977f-8e251f60b242.png)

**Comment by PanJiaChen** [comment]
对不起，没有在线调试demo，我帮不了你。
你可以仔细对比一下css。

**Comment by lijing233** [comment]
我升级了vue的版本后这个问题自动就好了；之前2.5.10 升级到了2.5.17
