### ISSUE TITLE
代码执行顺序问题？

### ISSUE THREAD

**Issue by MaxZzyo** [PanJiaChen/vue-element-admin#1873]
## Question（提问）

getData: function() {
    this.$axios.get(api).then(res => {
        console.info(1)
        console.info(2)
    })
}

这段代码怎么让他每次都绝对按 1,2 的顺序输出？
现在这种写法导致我每次执行这个函数，都是随机的顺序，12 或者 21
（实际代码没法放出，只能用这个举例）

**Comment by PanJiaChen** [comment]
这和本项目没什么关系。

执行顺序看你你的 `1`、`2`是否是异步操作了。至少你的demo来看肯定是顺序执行的。
