### ISSUE TITLE
大神,为什么我设置NAVbarmenu 为水平方向的,会变成纵向的

### ISSUE THREAD

**Issue by fzg2lj** [PanJiaChen/vue-element-admin#1875]
## Question（提问）
<el-menu :default-active="$route.path" background-color="#fff" class="el-menu-demo" mode="horizontal" menu-trigger="click" collapse-transition="true" @select="handleSelect" >
    <navbar-item v-for="route in permission_routes" :key="route.path" :item="route" :base-path="route.path"  />
 </el-menu>

**Comment by PanJiaChen** [comment]
不知道你在说什么。
请走issue模板。按照模板填写内容。
