### ISSUE TITLE
vue-element-admin，使用多级导航keep-alive的问题

### ISSUE THREAD

**Issue by 1055031918** [PanJiaChen/vue-element-admin#1876]
使用三级导航的时候，切换当前打开的tagView的每次离开三级页面的时候三级页面的公用router组件都会销毁，因为AppMain的cachedViews(也就是vuex状态管理中的tagsView.cachedViews不会push三级页面的公共router组件)，我想要实现切换多级页面能使用缓存，并且刷新三级页面tag能实现重载该页面，关闭三级页面tag也能销毁该组件
![QQ截图20190410154729](https://user-images.githubusercontent.com/44112017/55860976-f9cae300-5ba7-11e9-97e6-ae869b417e93.png)

**Comment by PanJiaChen** [comment]
请关注 https://github.com/PanJiaChen/vue-element-admin/issues/1177

**Comment by 1055031918** [comment]
@PanJiaChen 谢谢大佬  我正好之前看到了
