### ISSUE TITLE
README文档更新

### ISSUE THREAD

**Issue by linlinjava** [PanJiaChen/vue-element-admin#1878]
## Bug report（问题描述）

README里面的一段话需要修改一下吧：
```
目前版本为 4.0-beta，若发现问题，欢迎提issue。若你想使用旧版本-稳定版，可以切换分支到tag/3.11.0
```
现在已经是4.0正式版或者4.0.1版本

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
已更新
