### ISSUE TITLE
io地址必须是https了  否则访问不了

### ISSUE THREAD

**Issue by CodingBo** [PanJiaChen/vue-element-admin#1881]
## Question（提问）
http://panjiachen.github.io/vue-element-admin
友情提示：地址必须是https了  否则访问不了

**Comment by PanJiaChen** [comment]
感谢你的提醒，已经把能换成https的链接都换了。

https://github.com/PanJiaChen/vue-element-admin/commit/035c7d78f18b23d33ffadf47d97da91c00e1f2fe
