### ISSUE TITLE
配置侧边栏子菜单的权限，点击子菜单会报错（内存溢出）

### ISSUE THREAD

**Issue by blueOMG** [PanJiaChen/vue-element-admin#1886]

**Comment by PanJiaChen** [comment]
请按照issue模板来提交问题。

**Comment by blueOMG** [comment]
{
    path: '/permission',
    component: Layout,
    redirect: '/permission/index',
    alwaysShow: true, // will always show the root menu
    meta: {
      title: 'permission',
      icon: 'lock',
      roles: ['admin', 'editor'] // you can set roles in root nav
    },
    children: [
      {
        path: 'page',
        component: () => import('@/views/permission/page'),
        name: 'PagePermission',
        meta: {
          title: 'pagePermission',
          roles: ['admin'] // or you can only set roles in sub nav
        }
      },
      {
        path: 'directive',
        component: () => import('@/views/permission/directive'),
        name: 'DirectivePermission',
        meta: {
          title: 'directivePermission'
          // if do not set roles, means: this page does not require permission
        }
      },
    ]
}

**Comment by blueOMG** [comment]
按照这种方式写的，但是点击子菜单就报错  内存溢出了，
