### ISSUE TITLE
yarn安装运行后，input的required属性验证异常

### ISSUE THREAD

**Issue by SuperRight** [PanJiaChen/vue-element-admin#1887]
你好，我用npm install以后，运行时正常的，但是用yarn安装以后，input标签的rules中的required属性如果为true，即使已经填写，还会有提示。
![image](https://user-images.githubusercontent.com/43947662/55938928-11b96a00-5c6f-11e9-9825-e0e7367bc463.png)
代码如下所示：
![image](https://user-images.githubusercontent.com/43947662/55939137-96a48380-5c6f-11e9-9caf-37ab68b08d96.png)

**Comment by PanJiaChen** [comment]
无法重现，而且我感觉关系不大。
