### ISSUE TITLE
路由嵌套里面，如果只有一个子级菜单，会直接显示子级菜单，请问设计的初衷就是这样的吗？不是很明白这样设计的好处是什么？

### ISSUE THREAD

**Issue by sunfloweryll** [PanJiaChen/vue-element-admin#1888]
![image](https://user-images.githubusercontent.com/15272750/55939480-6dd0be00-5c70-11e9-86db-7018ba101948.png)

![image](https://user-images.githubusercontent.com/15272750/55939427-47128780-5c70-11e9-831b-b04d2ea9798c.png)

**Comment by PanJiaChen** [comment]
请查看文档

https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/router-and-nav.html#%E4%BE%A7%E8%BE%B9%E6%A0%8F
