### ISSUE TITLE
加载导出功能模块提示vendor/Export2Excel

### ISSUE THREAD

**Issue by haocm123** [PanJiaChen/vue-element-admin#189]
```
* vendor/Export2Excel in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/ael/myItems.vu
e

To install it, you can run: npm install --save vendor/Export2Excel
> Listening at http://localhost:9530
```
我用的工程
git clone https://github.com/PanJiaChen/vueAdmin-template.git

参考的
git clone https://github.com/PanJiaChen/vue-element-admin

将导出代码copy到vueAdmin-template里面运行提示如上错误
vendor 文件夹也copy过来了
也尝试了将vue-element-admin完整的package.json copy过来
然后npm install --registry=https://registry.npm.taobao.org

仍然提示错误
执行  npm install --save vendor/Export2Excel
```
npm ERR! Error while executing:
npm ERR! C:\Program Files (x86)\SmartGit\git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/vendor/Export2Excel.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\haocm\AppData\Roaming\npm-cache\_logs\2017-09-05T06_01_54_268Z-debug.log
```

请大神指导~~

**Comment by haocm123** [comment]
已经解决
alias里面需要配置'vendor': path.resolve(__dirname, '../src/vendor'),相对路径；

**Comment by PanJiaChen** [comment]
👍

**Comment by UnnikrishnanBhargavakurup** [comment]
Hi,

same error for me could you please explain me how i can resolve this in English?

**Comment by PanJiaChen** [comment]
@UnnikrishnanBhargavakurup 

webpack [alias](https://webpack.js.org/configuration/resolve/#resolve-alias)

https://github.com/PanJiaChen/vue-element-admin/blob/62fb5d1e148eadb99ae4aab81deca5f75798f4b6/build/webpack.base.conf.js#L39
