### ISSUE TITLE
mock目录，希望import能提供别名支持

### ISSUE THREAD

**Issue by AleynHe** [PanJiaChen/vue-element-admin#1890]
## Feature request（新功能建议）
1.mock目录，希望import能提供别名支持

**Comment by PanJiaChen** [comment]
没懂什么意思？

**Comment by AleynHe** [comment]
不支持@别名
import yourmodule from '@/utils/xxx'

**Comment by PanJiaChen** [comment]
因为 `alias` 是`webpack`特有的，但 `mock-server` 和`webpack`没什么关系，所以不支持。
如果你想支持可以自己加 [module-alias](https://github.com/ilearnio/module-alias)
