### ISSUE TITLE
Open create and edit in the same view and tag

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [PanJiaChen/vue-element-admin#1892]
## Feature request（新功能建议）

When you edit an article or open a component that indicates editing or create a new record, another label is added.

Could you keep the same view and label to create or edit?

https://panjiachen.github.io/vue-element-admin/#/example/create
https://panjiachen.github.io/vue-element-admin/#/example/edit/1

If you are editing an article or a record, and you want to create a new one and in that view there is a direct access to the route https://panjiachen.github.io/vue-element-admin/#/example/create
the best would not be to clean the form and all the fields.

Also if you are looking at a list of 100 records and you want to see each one or edit, it would be overloading the window by opening so many records in difentes tag.

![Screenshot_2019-04-11 vue-element-admin](https://user-images.githubusercontent.com/20288327/55974057-d7db6a00-5c54-11e9-9b4d-d19c4b9b1145.png)

My proposal or request is that they should open the create and edit in the same view and update the tag with the identifier of the record ultimately, however I think that should not show in the tag the identifier of the record.

**Comment by PanJiaChen** [comment]
Everyone's needs are different. Some people just want to open multiple different tabs.

You can use name as a unique identifier.

![image](https://user-images.githubusercontent.com/8121621/56007684-15e79500-5d0c-11e9-9681-bee852b43e24.png)


![image](https://user-images.githubusercontent.com/8121621/56007663-07997900-5d0c-11e9-8e08-2c5929bc2c50.png)

**Comment by EdwinBetanc0urt** [comment]
Thank you for taking your time and answering the request. It works for the edition of records, however not when adding the path /new to the end.
