### ISSUE TITLE
页面中的组件不应该显式设置size

### ISSUE THREAD

**Issue by linlinjava** [PanJiaChen/vue-element-admin#1893]
## Bug report（问题描述）

如果全局搜索“size=”，可以看到页面里面很多组件设置了size，例如
```
          <el-button type="primary" size="small" @click="handleEdit(scope)">
```

但是，如果这里显式设置size，会导致系统切换size时不起作用。
建议，组件的size不应该显式设置，除非开发者真的觉得没有必要。

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
我检查了下，这些 `size` 就是故意写死的，不然 `default`、`medium`都太丑了。如果有需求可自己修改。
