### ISSUE TITLE
点击 tags-view 可以不刷新页面吗？ 求教

### ISSUE THREAD

**Issue by jian22446688** [PanJiaChen/vue-element-admin#1894]
## Question（提问）

![image](https://user-images.githubusercontent.com/9110852/56009389-3adf0680-5d12-11e9-9b41-1dddc755fb88.png)

就是 <Message> <基本表单>  tags-view 已经出现在上面，tags-view 切换不刷新、不重新请求数据。
求教大神指导哈

**Comment by PanJiaChen** [comment]
tags-view实现方案文档写的很清楚了吧。

**Comment by jian22446688** [comment]
> tags-view实现方案文档写的很清楚了吧。

我给文档看了好多遍了，tags-view 怎么用啊，求教了

**Comment by PanJiaChen** [comment]
我源码和文档都有了，我还能怎么帮你。

**Comment by jian22446688** [comment]
> 源码和文档都有了，我还能怎么帮你。

我错了，给我说说文档位置

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/tags-view.html#visitedviews-cachedviews

**Comment by xinnicai** [comment]
@ @jian22446688 这个解决了么

**Comment by wissen1995** [comment]
> @ @jian22446688 这个解决了么

这个痛点应该就是如何手动清除keep-alive缓存的组件，可以参考这个https://github.com/vuejs/vue/issues/6509，我现在就是这么做的
