### ISSUE TITLE
table 单元格 宽度自适应 

### ISSUE THREAD

**Issue by magengxin** [PanJiaChen/vue-element-admin#1897]
应用场景：在一列单元格中，我有两个按钮；有时候接收一个值的时候显示一个按钮，接收两个值的时候显示两个按钮，请问在这种情况下单元格宽度如何自适应。
附加：单元格表头居中显示，内容 align:left 显示。

**Comment by PanJiaChen** [comment]
请提供一个在线demo。

**Comment by magengxin** [comment]
在线 demo 太麻烦了，我以图片代替吧。
这是一个表格中的单元格，需求是如果是两个按钮，就这样显示，但是宽度不要自己设置，希望是自适应的。如果是一个按钮，单元格宽度是一个按钮的宽度，不要想这样是两个按钮的宽度，希望是自适应。
![image](https://user-images.githubusercontent.com/23067574/56015054-44746880-5d2a-11e9-8138-43823c84434a.png)
![image](https://user-images.githubusercontent.com/23067574/56015337-45f26080-5d2b-11e9-9537-bf15cc674ebf.png)

**Comment by PanJiaChen** [comment]
这个也可以理解为是一个feature,你可以去element官方提。

目前可以动态的 设置该栏的width。

**Comment by magengxin** [comment]
但是宽度可能是一个或者是两个，改如何设置width呢？按照一个宽度或者是两个宽度都不合适
