### ISSUE TITLE
关于dropzone图片上传

### ISSUE THREAD

**Issue by RainbowYano** [PanJiaChen/vue-element-admin#1899]
## 关于dropzone图片上传
下图的这个我想实现在点击按钮时获取所有的图片信息，利用formdata格式数据，然后自己请求到后台，传送数据，我自己将你这个组件改吧改吧能实现吗
![1](https://user-images.githubusercontent.com/43380578/56023683-020a5600-5d41-11e9-943e-e2e378ed5289.png)

**Comment by PanJiaChen** [comment]
有问的时间，自己试一下咯。
