### ISSUE TITLE
如何把代码交给服务端

### ISSUE THREAD

**Issue by zhangl10** [PanJiaChen/vue-element-admin#19]
您好，这种方式如何把前端文件交给php服务端呢？

**Comment by PanJiaChen** [comment]
不是很懂什么意思，这是一个纯前端项目，将打包好的dist文件放在一个服务上，配好nginx就可以了，无所谓服务端是什么语言。

**Comment by zhangl10** [comment]
vue小白。现在如何把这个项目进行数据操作，所有数据从数据读取。那要把文件给服务端吧，以往的开发度是把页面写好了给后端程序员，经过webpack打包之后如何做？

**Comment by PanJiaChen** [comment]
webpack 打包之后就是一个index.html 和一堆js css文件。。。我建议还是让后端出api，前后端分离比较好

**Comment by zhangl10** [comment]
我看到你的index.html里面引入了tinymce.min.js这个文件，这个是压缩后所有的js代码都里面吧。

**Comment by PanJiaChen** [comment]
这是因为我用了tinymce富文本，如果不用可以不用引。
你执行npm run build:prod
在根目录下会多一个dist文件 里面就是你要给服务端的东西。。。
