### ISSUE TITLE
table 单元格中 上传图片 功能

### ISSUE THREAD

**Issue by magengxin** [PanJiaChen/vue-element-admin#1900]
应用场景：在table单元格中实现上传图片功能。
遇到问题：使用`element-ui`----用户头像上传 功能，实现上传图片的功能，上传单个图片可以成功。如果是多行，同样功能上传会出问题，问题是无法获取当前索引，不能把图片上传到指定的数据中进行保存进而全部一次提交给后台。

图中单元行有多行的情景
![image](https://user-images.githubusercontent.com/23067574/56028516-e0ae6780-5d4a-11e9-878e-880f0bdb2133.png)

**Comment by PanJiaChen** [comment]
请提供最小demo

**Comment by magengxin** [comment]
https://www.jianshu.com/p/33175c3a6ba4
demo类似于上面的例子，只不过我增加了一个 图片单元格，需求是需要上传一个图片在每列中，
问题是：其他输入框里面的数据可以上传，但是图片路径没法传入成功，我使用的是el-upload组件。

**Comment by PanJiaChen** [comment]
我不是很清楚那你的需求，问问题首先要学会提问。没有人有义务来帮助你。我不可能来猜你想要干什么。

反正不管怎么样，有一个建议，像你这种table 上传图片 应该是整个页面共享一个上传组件，而不是每一行都有一个上传组件。

**Comment by magengxin** [comment]
![image](https://user-images.githubusercontent.com/23067574/56122905-01bec480-5fa6-11e9-8fbf-490edf233cdf.png)
请问我有办法把 1 获取的值 传到 2 里面么？

**Comment by magengxin** [comment]
https://codepen.io/magengxin/pen/YMrdJZ
这是在线demo
主要功能：添加数据

**Comment by magengxin** [comment]
问题：不能上传图片，获取图片的path，在 createBannerImgSuccess 函数中可以正确赋值给data[this.tableActionIndex].img

但是，保存之后，this.master_user.data里面没有图片url

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/56126928-a9d88b80-5fae-11e9-9019-86a4602372ea.png)

**Comment by magengxin** [comment]
整个页面使用一个上传组件也是可以的，不过问题是：上传成功执行的回调函数中把图片路径赋值给data，但是保存没法获取，所以还是不成功。

**Comment by Dade-jj** [comment]
为什么要共享一个呢
