### ISSUE TITLE
动态加载的路由刷新后失效

### ISSUE THREAD

**Issue by gulang12** [PanJiaChen/vue-element-admin#1901]
handleLogin() {
        if(!this.loading) {
            this.loading = true
            login(this.loginForm.username, this.loginForm.password, this.loginForm.vertify).then(response => {
                if(response.code==1) {

                    setToken(response.token) 
                    this.$store.commit("SET_NAME", [response.userInfo.user_login, response.userInfo.role_name]);

                    this.$store.dispatch("AddPermissionRoutes").then(() =>{  
                      
                        this.$router.addRoutes(this.$store.getters.permission_routes); //动态添加路由

                        this.$router.push({path: '/'}); // 跳转到后台首面
                    });
                    
                }else{
                  
                    this.notice = response.msg
                    this.refreshVertify()  // 调用其它方法方式
                }
                this.loading = false
            })
        }
    },

**Comment by PanJiaChen** [comment]
请按照issue模板提问。
