### ISSUE TITLE
修改后的mock如何实现后端接口和mock接口共用

### ISSUE THREAD

**Issue by wzhz** [PanJiaChen/vue-element-admin#1902]
之前的mock在

> npm run dev

之后，默认使用的是mock接口，mock接口没有定义的会访问后端接口，现在的mock如何配置，而且个人觉得现在的配置更复杂了，需要修改
```
vue.config.js--proxy属性
mock/index.js
main.js
```

另外，有没有大佬讲解一下main.js中的
`if (process.env.NODE_ENV === 'production') { mockXHR() }`
是什么意思~
为什么要在生成环境时调用mockXHR()

另外，如果后端去前端不在同一个系统，该如何配置下面的三个文件：

> src/utils/request.js
> .env.production
> vue.config.js

菜鸟一个，望各位大佬讲解，不是感激。

**Comment by PanJiaChen** [comment]
我晚点更新一下文档。

**Comment by wzhz** [comment]
> 我晚点更新一下文档。

感谢大佬

**Comment by Xanthuim** [comment]
文档在哪里呢？
