### ISSUE TITLE
请问npm run  build 打包部署后的js有加version吗

### ISSUE THREAD

**Issue by GJFlying** [PanJiaChen/vue-element-admin#1903]
## Question（提问）
请问npm run  build 打包部署后的js有加version吗，部署后需要强制刷新浏览器是因为没加版本号吗

**Comment by PanJiaChen** [comment]
现在js的后缀是基于content hash 来做的，所以不需要加版本号。
你现在有缓存，我猜测是`index.html`有缓存，你将它设置为永不缓存就好了。
