### ISSUE TITLE
Unable to get property 'opened' of undefined or null reference

### ISSUE THREAD

**Issue by shudongW** [PanJiaChen/vue-element-admin#1907]
## Bug report（问题描述）
控制台刷新报错，无法识别sidebar的opend
#### Screenshot or Gif（截图或动态图）

[Vue warn]: Error in render: "TypeError: Unable to get property 'opened' of undefined or null reference"

found in

---> <Sidebar> at src/views/layout/components/Sidebar/index.vue
       <Layout> at src/views/layout/Layout.vue
         <App> at src/App.vue
           <Root>
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by shudongW** [comment]
Unable to get property 'forEach' of undefined or null reference

**Comment by PanJiaChen** [comment]
报错已经很明显了。
