### ISSUE TITLE
如何关闭eslint校验

### ISSUE THREAD

**Issue by CuiYang16** [PanJiaChen/vue-element-admin#1909]

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/26d0f40df21fa5e5583a20cb3df14ae9d475bb3c/vue.config.js#L24

`lintOnSave:false`

https://github.com/PanJiaChen/vue-element-admin/blob/26d0f40df21fa5e5583a20cb3df14ae9d475bb3c/package.json#L18-L22

移除这段，不然在你提交代码的时候还是会检验。
