### ISSUE TITLE
收起侧边栏这个功能很好

### ISSUE THREAD

**Issue by SteveCruise** [PanJiaChen/vue-element-admin#191]
但是没有详细的文档，代码也看不懂啊

**Comment by PanJiaChen** [comment]
这能写什么文档。。。

**Comment by SteveCruise** [comment]
这个功能由哪些组件完成的？点击时触发的函数是哪个？改变宽度的原理是改变了什么？就像这个样子

**Comment by SteveCruise** [comment]
总体感觉功能很全很强大了，但文档要扩充好几倍呢，像这个样子才好
http://element.eleme.io/#/zh-CN/component/installation

**Comment by PanJiaChen** [comment]
个人觉得没什么必要，本来大部分组件就是基于 `element-ui` 的，其次本项目定位是一个解决方案，也配套了几篇文章
 > 这个功能由哪些组件完成的？点击时触发的函数是哪个？改变宽度的原理是改变了什么？
这种需求，市面上没有那个开源项目能做到吧，源码都在了，也没有很复杂，我觉得本项目只是提供一个各种情况的一种解决方案和思路，最重要的还是自己理解其中的原理

**Comment by SteveCruise** [comment]
好吧~
