### ISSUE TITLE
Select a tab without reload page

### ISSUE THREAD

**Issue by yamelsenih** [PanJiaChen/vue-element-admin#1912]
Hi everyone, this framework is nice. I was testing it with many tabs opened and I note that if you select a tab the page is reloaded. Exists a way for no reload it?
See it: https://panjiachen.github.io/vue-element-admin/#/dashboard

When I select other tab the info is reloaded: https://panjiachen.github.io/vue-element-admin/#/documentation/index

I think that is unnecessary reload it, if I have a form by each tab then the info will be reloaded and is very lazy it.

**Comment by yamelsenih** [comment]
Hi everyone, any suggestion for it?

Best regards

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/guide/essentials/tags-view.html#affix

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/f24b64392e70bcfbfb6f60e72dc9d9b552d99220/src/router/index.js#L82

You can remove `noCache`
