### ISSUE TITLE
clone下来的源码中的Excel下载Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by hlbj105** [PanJiaChen/vue-element-admin#1914]
## Bug report（问题描述）
```
Export2Excel.js:167 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at Module.export_json_to_excel (Export2Excel.js:167)
    at exportExcel.vue?3e43:96
    at <anonymous>
```
Export2Excel中的multiHeader得不到数据，所以length报错，exportExcel.vue没有传入multiHeader参数，但是线上Demo中可以下载

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/16408650/56116176-c3baa400-5f97-11e9-826d-8876975d57aa.png)
![image](https://user-images.githubusercontent.com/16408650/56116189-cf0dcf80-5f97-11e9-898e-30826990abde.png)

**Comment by PanJiaChen** [comment]
你这不是最新版吧，这个bug修复了一段时间了。

**Comment by hlbj105** [comment]
额、、、重新clone下。。
