### ISSUE TITLE
图片上传组件

### ISSUE THREAD

**Issue by menciusKael** [PanJiaChen/vue-element-admin#1915]
图片组件中，上传成功后返回的 url = ‘/group/index/a.png’ ， 然后为了能够渲染，又执行了一次请求获取 token并拼接域名， 最后 ImgUrl = http://xxxx/group/index/a.png?token=sadfafda
使用的时候渲染都没问题了，但最后提交数据的时候需要提交 url（不带前缀和token的），
所以使用的时候v-model好像只能绑定一个值 ImgUrl （为了能渲染），对v-model组件通信理解不够，求解决思路

图片组件：
![image](https://user-images.githubusercontent.com/29659731/56116150-b69db500-5f97-11e9-8e47-d9bbeef4fa76.png)
使用组件：
![image](https://user-images.githubusercontent.com/29659731/56116180-cc12df00-5f97-11e9-9b4f-3e351b49c09b.png)

**Comment by PanJiaChen** [comment]
v-model 绑定的是` url = ‘/group/index/a.png’ `

渲染图片需要的url 用 computed来实现。
