### ISSUE TITLE
npm run dev，可以成功运行，可是调试的时候代码背压缩了

### ISSUE THREAD

**Issue by xuzz123** [PanJiaChen/vue-element-admin#1916]
npm run dev，可以成功运行，可是调试的时候代码背压缩了

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/26d0f40df21fa5e5583a20cb3df14ae9d475bb3c/vue.config.js#L90

可以自己设置soucemap
