### ISSUE TITLE
要是能整合出uniapp的就更ok了

### ISSUE THREAD

**Issue by future-c** [PanJiaChen/vue-element-admin#1917]
## Feature request（新功能建议）
针对uniapp弄一套，那就方便了

**Comment by PanJiaChen** [comment]
这两者没任何联系。
之后也不会做相关工作。
本项目的定位就只是pc。

**Comment by bei612** [comment]
> 
> ## Feature request（新功能建议）
> 
> 针对uniapp弄一套，那就方便了

https://ext.dcloud.net.cn/plugin?id=1476
