### ISSUE TITLE
路由元信息meta里的默认值在哪里设置的

### ISSUE THREAD

**Issue by XLZK** [PanJiaChen/vue-element-admin#1918]
## Question（提问）

作者，你好，我想问下路由元信息meta里面的选项默认值怎么设置呀，我看你项目里面的noCache默认是false,我想增加一个其他选项，也设定一个默认值，这个该哪里增加呢

**Comment by PanJiaChen** [comment]
就拿`noCache`举例，你没有设置的话就是`undefined`，下面判断就为真。

https://github.com/PanJiaChen/vue-element-admin/blob/26d0f40df21fa5e5583a20cb3df14ae9d475bb3c/src/store/modules/tagsView.js#L17-L19

所以没有具体的设置默认值。

**Comment by XLZK** [comment]
> 就拿`noCache`举例，你没有设置的话就是`undefined`，下面判断就为真。
> 
> [vue-element-admin/src/store/modules/tagsView.js](https://github.com/PanJiaChen/vue-element-admin/blob/26d0f40df21fa5e5583a20cb3df14ae9d475bb3c/src/store/modules/tagsView.js#L17-L19)
> 
> Lines 17 to 19 in [26d0f40](/PanJiaChen/vue-element-admin/commit/26d0f40df21fa5e5583a20cb3df14ae9d475bb3c)
> 
>  if (!view.meta.noCache) { 
>    state.cachedViews.push(view.name) 
>  } 
> 所以没有具体的设置默认值。

感谢大神，明白了
