### ISSUE TITLE
全局配置，fixedHeader 设置为true时，右侧垂直滚动条起始位置问题

### ISSUE THREAD

**Issue by AleynHe** [PanJiaChen/vue-element-admin#1919]
## Feature request（新功能建议）
全局配置，fixedHeader 设置为true时，右侧垂直滚动条起始位置建议从header区域下方开始比较好。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1787

暂时不准备修改。
