### ISSUE TITLE
文件多了以后，热重载极慢，怎么解决的？

### ISSUE THREAD

**Issue by a346721573** [PanJiaChen/vue-element-admin#192]
如题，总之启动、热重载都极慢。

**Comment by PanJiaChen** [comment]
热更新并不会慢，我这里很大项目也保持在2000ms左右。
所以你能详细说明一下么。
启动慢可以通过webpack dll 或者external 来解决了

**Comment by a346721573** [comment]
其实我们这个项目是参考了很多你的这个项目的，但是vue-cli生成的，很多配置可能和你的不一样，热重载要将近20s，感觉像是webpack的配置问题，你有调整过什么吗？webpack dll 和external 如何配置呢？

**Comment by PanJiaChen** [comment]
webpack dll 和external  请自行查阅相关文章
我这里dev做的主要优化是 [文章](https://segmentfault.com/a/1190000010043013#articleHeader1)

**Comment by a346721573** [comment]
非常感谢您的解答，再次仔细阅读了一遍，定位大概是懒加载那个部分的原因，也顺带升个webpack3，谢谢。
