### ISSUE TITLE
icon不能正确显示

### ISSUE THREAD

**Issue by Adele0** [PanJiaChen/vue-element-admin#1923]
## Bug report（问题描述）
不是直接用的本框架（vue版本号"vue": "^2.5.2"）。根据《手摸手，带你优雅的使用 icon》和本框架引入icon相关组件和图标，不能在自己的项目中正确显示。

#### Steps to reproduce（问题复现步骤）and Screenshot or Gif（截图或动态图）

icons文件夹和components下的SvgIcon.vue直接从vue-element-admin中拷贝
![image](https://user-images.githubusercontent.com/32303661/56178855-4f830d80-6036-11e9-97f9-3a5c5c2fe259.png)

项目依赖已经相应的安装
![image](https://user-images.githubusercontent.com/32303661/56178425-cfa87380-6034-11e9-8ab4-5e11251c5110.png)

webpack.base.conf.js也修改了
![image](https://user-images.githubusercontent.com/32303661/56178976-bb657600-6036-11e9-913f-5170e1b2cae9.png)

在组件中使用
<svg-icon icon-class="excel" /> 

#### Link to minimal reproduction（最小可在线还原demo）
项目中DOM已生成，但是没有icon路径(下图对比自己和大神的DOM)
![image](https://user-images.githubusercontent.com/32303661/56179121-3333a080-6037-11e9-8cc0-89807a6fbb79.png)
![image](https://user-images.githubusercontent.com/32303661/56179176-5cecc780-6037-11e9-8f57-f3d9658d986f.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version: v8.12.0
- vue-element-admin version: 没有直接用大神的框架

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/26d0f40df21fa5e5583a20cb3df14ae9d475bb3c/src/main.js#L17
引入了么

**Comment by Adele0** [comment]
引入了呢

**Comment by Adele0** [comment]
> [vue-element-admin/src/main.js](https://github.com/PanJiaChen/vue-element-admin/blob/26d0f40df21fa5e5583a20cb3df14ae9d475bb3c/src/main.js#L17)
> 
> Line 17 in [26d0f40](/PanJiaChen/vue-element-admin/commit/26d0f40df21fa5e5583a20cb3df14ae9d475bb3c)
> 
>  import './icons' // icon 
> 
> 引入了么

引入了呢

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/56180486-1cdc1380-603c-11e9-9b85-55e12cf9bca8.png)

？？

**Comment by Adele0** [comment]
> ![image](https://user-images.githubusercontent.com/8121621/56180486-1cdc1380-603c-11e9-9b85-55e12cf9bca8.png)
> 
> ？？

私密麻生，劳烦大神了，浪费大神时间，我是大傻逼....
