### ISSUE TITLE
日期选择器，内部的文字和其他输入框位置不一致，并且无法闭合

### ISSUE THREAD

**Issue by renjunchi** [PanJiaChen/vue-element-admin#1926]
#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/7802934/56185590-0c359880-6050-11e9-96b0-15c9dd7f4dcc.png)

#### Other relevant information（格外信息）
<el-date-picker v-model="listQuery.created_at" type="daterange" value-format="yyyy-MM-dd" range-separator="至" start-placeholder="开始日期" end-placeholder="结束日期" class="filter-item" />

![image](https://user-images.githubusercontent.com/7802934/56185523-f58f4180-604f-11e9-86ea-aa33fc068ffb.png)

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/952da3287983728e164c45c8364cfef4353774eb 

加入这段代码就可以了 
```css
.el-range-editor.el-input__inner {
  display: inline-flex !important;
}
```
