### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by ZYL215** [PanJiaChen/vue-element-admin#1927]
## Question（提问）

最新版本的启动时报错
![image](https://user-images.githubusercontent.com/45197780/56194710-1e223600-6066-11e9-8773-61296bec5449.png)

**Comment by ZYL215** [comment]
在百度找了好几种方法，都没有解决掉

**Comment by PanJiaChen** [comment]
重新安装依赖

**Comment by ZYL215** [comment]
重新安装到Downloading node-sass下载的时候下载进度就不走了，怎么解决，麻烦大佬看一下。已经过去有一个半小时了，我的网速很好，但是这个进度条就是不走，npm安装。
![image](https://user-images.githubusercontent.com/45197780/56201521-a0652700-6073-11e9-8d5a-20fccc284a50.png)

**Comment by PanJiaChen** [comment]
node-sass 的安装方式我文档和issue都有写。

没全局翻墙的情况下，建议`npm install --registry=https://registry.npm.taobao.org
`

**Comment by ZYL215** [comment]
解决了，第一遍npm install安装以后启动不起来，需要再重新安装一遍，第二遍安装的时候要把VPN打开，不然下载进度条就不走，安装以后启动就可以用了。
