### ISSUE TITLE
侧边栏菜单如何同时只展开一个呢?

### ISSUE THREAD

**Issue by hncg** [PanJiaChen/vue-element-admin#1929]
## Feature request（新功能建议）

![image](https://user-images.githubusercontent.com/8074553/56251921-04c1ce00-60e8-11e9-9905-25c7ba8f99bf.png)
如图，我展开了下面那个菜单，上面菜单那个能配置吗自动收起来？

**Comment by androidvm** [comment]
`el-menu`可以添加一个属性`unique-opened`

**Comment by PanJiaChen** [comment]
楼上正解。

相关[文档](https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/router-and-nav.html#%E8%B7%AF%E7%94%B1)已更新

**Comment by hncg** [comment]
感谢两位的快速支持。
@PanJiaChen @androidvm

**Comment by xiechunhao** [comment]
哇！谢谢大佬，已解决
