### ISSUE TITLE
新加了一个tab标签栏,切换tab还是会重新加载数据怎么办?

### ISSUE THREAD

**Issue by yifangts** [PanJiaChen/vue-element-admin#193]
大神,我看到有最近新添加了一个tab栏,正是我想要的,感觉超嗨,但是切换tab仍然是通过切换路由的方式,我用keepAlive这种方式仍然重新加载数据,我获取数据的方法是写在created里面的.
在store.app 里面
ADD_VISITED_VIEWS: (state, view) => {
      if (state.visitedViews.some(v => v.path === view.path)) return
      state.visitedViews.push({ name: view.name, path: view.path,meta:{ keepAlive: true } })
    },
这种方式并不会在路由那边添加keepAlive;
这样的话有什么好的解决办法吗?

**Comment by PanJiaChen** [comment]
保存状态一般就两种方法 一种`router-view` 外面加 `keep-alive` #181 
或者就是你说的存贮之前的state，回到该页面的时候再回赛

**Comment by yifangts** [comment]
谢谢大神的思路,这两天忙别的事去了,没来得及回复.
