### ISSUE TITLE
改为后台获取路由的方式实现侧边栏遇到的问题

### ISSUE THREAD

**Issue by wzhz** [PanJiaChen/vue-element-admin#1930]
> 现在我做的一个项目是动态通过后台获取路由的方式实现的侧边栏

### 背景

我参考的是[Vue 动态路由的实现](https://segmentfault.com/a/1190000015419713); 这个项目作者提供了地址[git](https://github.com/Mrblackant/dynamicRouter), [预览地址](http://an888.net/antRouter/)

但是我现在做的项目是通过本项目的最新的`master`分支构建, 然后通过上面的文章和案例修改为动态加载.

**同时我也参考了您发布的文档: [路由懒加载](https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/lazy-loading.html#%E5%8C%BA%E5%88%86%E5%BC%80%E5%8F%91%E4%B8%8E%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83-%E8%AF%A5%E6%96%B9%E6%A1%88%E5%B7%B2%E6%B7%98%E6%B1%B0)以及[淘汰原因](https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/lazy-loading.html#%E6%B7%98%E6%B1%B0%E5%8E%9F%E5%9B%A0)**

### 问题

通过`npm run dev`运行项目没有发现问题, 但是通过`npm run build`编译项目之后, 却不能使用.

### 部分代码

*src/store/modules/permission.js*

```
// 获取后台的AsyncRoutes, 参考: mock/role/routes.js文件中的asyncRoutes
import { getAsyncRoutes } from '@/api/role'
// 将后台获取的路由数据生成Routes
import { getAsyncRouter } from '@/utils/route'

.
.
.

const actions = {
  generateRoutes({ commit }, roles) {
    return new Promise(async resolve => {
      const { data } = await getAsyncRoutes() // 获取后台路由菜单信息
      const routers = getAsyncRouter(data) // 通过后台回去的菜单信息生成路由
      console.log(routers)
      let accessedRoutes
      if (roles.includes('admin')) {
        accessedRoutes = routers
      } else {
        accessedRoutes = filterAsyncRoutes(routers, roles)
      }
      commit('SET_ROUTES', accessedRoutes)
      resolve(accessedRoutes)
    })
  }
}

.
.
.

```

*src/utils/route.js*

```

// Layout 是架构组件，不在后台返回，在文件里单独引入
import Layout from '@/layout'
import Skin from '@/layout/skin'

// 获取组件的方法
// 参考https://www.cnblogs.com/llcdxh/p/9778491.html
// 该方式有瑕疵，因项目中需求问题，暂时做该方式调整
// 文章中描述DllPlugin和DllReferencePlugin处理，适用于vue-cli2.0，cli3.0的开发是否适用后续研究。
const _import = require('@/router/_import_' + process.env.NODE_ENV) // eslint-disable-line import/no-dynamic-require

/**
 * 通过后台数据生成动态路由
 * 遍历后台传来的路由字符串，转换为组件对象
 * @param {Array} asyncRouterMap
 * @returns {Boolean}
 * @example see @/store/modules/permission.js
 */
export function getAsyncRouter(asyncRouterMap) {
  const accessedRouters = asyncRouterMap.filter(route => {
    const component = route.component
    if (component) {
      if (component === 'Layout') { // Layout组件特殊处理
        route.component = Layout
      } else if (component === 'Skin') { // Skin组件特殊处理
        route.component = Skin
      } else {
        try {
          route.component = _import(component)
        } catch (error) {
          console.log(error)
        }
      }
    }
    if (route.children && route.children.length > 0) {
      route.children = getAsyncRouter(route.children)
    }
    return true
  })

  return accessedRouters
}

```

*src/router/_import_development.js*

```
// vue-loader at least v13.0.0+
module.exports = path => require('@/views/' + path).default // eslint-disable-line import/no-dynamic-require

```

*src/router/_import_production.js*

```
module.exports = path => () => import(
  /* webpackChunkName: "async-chunk-routes" */
  /* webpackMode: "lazy" */
  /* webpackPrefetch: true */
  '@/views/' + path)

```

### 错误

*`npm run build`之后再浏览器打开,通过`console.log()`打印路由对象的 `component`*

```
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Function.invokeGetter (<anonymous>:2:14)
```

*当点击菜单时`console`报错:*

```
Error: Cannot find module '@/views/business/complexTable'
```

### 控制台截图

*`npm run build`之后再浏览器打开,通过`console.log()`打印路由对象的 `component`*

<p align="center">
  <img width="100%" src="https://wzhz.xyz/github/0.png">
</p>

*当点击菜单时`console`报错:*

<p align="center">
  <img width="100%" src="https://wzhz.xyz/github/1.png">
</p>

`请大佬帮忙看一下是什么问题，可否解决或遇到过这种类似问题`

**Comment by PanJiaChen** [comment]
`@/views/` 只是一个webpack的识别符号，游览器不能识别，你要替换为正式路径。
具体哪里写错了没看出来。

**Comment by liaohc** [comment]
真巧，我也刚刚做从后台获取菜单遇到这个问题，不知道怎么解决
![image](https://user-images.githubusercontent.com/9366991/56273098-a966fe80-612e-11e9-80e6-3c94169f079a.png)

**Comment by PanJiaChen** [comment]
理论上正常操作是不会出现这种问题的，因为 `npm run  build`的时候 webpack会转化掉的。

**Comment by wzhz** [comment]
> `@/views/` 只是一个webpack的识别符号，游览器不能识别，你要替换为真实路径。
> 具体哪里写错了没看出来。
> 
> 你完全可以不用`_import`这种方式了，有问题的。

如果要把`@/views/`改为真实路径，我不知道觉得路径是什么..
我现在是用的`_import`，如果直接使用`require`或者是`import`都会出现问题。

**Comment by wzhz** [comment]
> 理论上正常操作是不会出现这种问题的，因为 `npm run build`的时候 webpack会转化掉的。

可能出现这个问题的原因是什么？可能..
或者是我应该向那个方向研究，才能解决这个问题..

**Comment by wzhz** [comment]
> 真巧，我也刚刚做从后台获取菜单遇到这个问题，不知道怎么解决
> ![image](https://user-images.githubusercontent.com/9366991/56273098-a966fe80-612e-11e9-80e6-3c94169f079a.png)

那你那边的问题解决了么？什么原因？

**Comment by liaohc** [comment]
> > 真巧，我也刚刚做从后台获取菜单遇到这个问题，不知道怎么解决
> > ![image](https://user-images.githubusercontent.com/9366991/56273098-a966fe80-612e-11e9-80e6-3c94169f079a.png)
> 
> @liaohc
> 那你那边的问题解决了么？什么原因？

没有解决呢！我贴一下我的代码和报错信息吧：
![image](https://user-images.githubusercontent.com/9366991/56274604-9f92ca80-6131-11e9-9d68-a06556f40251.png)

**Comment by wzhz** [comment]
> > > 真巧，我也刚刚做从后台获取菜单遇到这个问题，不知道怎么解决
> > > ![image](https://user-images.githubusercontent.com/9366991/56273098-a966fe80-612e-11e9-80e6-3c94169f079a.png)
> > 
> > 
> > @liaohc
> > 那你那边的问题解决了么？什么原因？
> 
> 没有解决呢！我贴一下我的代码和报错信息吧：
> ![image](https://user-images.githubusercontent.com/9366991/56274777-f9939000-6131-11e9-8d18-2beb039b398a.png)

@liaohc 和需求差不多，错误也一样，什么时候解决了这个问题，分享一下吧，这个问题我已经研究了3天了~

**Comment by liaohc** [comment]
> @liaohc 和需求差不多，错误也一样，什么时候解决了这个问题，分享一下吧，这个问题我已经研究了3天了

好的，要是你解决了也通知我一下，我今天下午刚刚遇到这个问题

**Comment by wzhz** [comment]
@PanJiaChen @liaohc  我这边的问题解决了, 原因是我在根目录添加了下面的三个常量配置文件：

> .env
> .env.development
> .env.production

一开始我配置的`.env`文件和`.env.development`一致;

然后我把复制`.env.production`文件中的内容到`.env`中就可以了，

我通过调试，关键的一行是：**NODE_ENV = production**

### `.env.production`中的配置:

```
# just a flag
ENV = production
NODE_ENV = production

# 项目的默认全局语言、文字大小配置
VUE_APP_LANGUAGE = zh
VUE_APP_TEXT_SIZE = medium

# 项目调用后端API配置
VUE_APP_BASE_API = https://www.wzhz.xyz/vue-element-admin-api
VUE_APP_SRC = https://wzhz.xyz/

```
### `.env.development`中的配置:

```
# just a flag
ENV = development
NODE_ENV = development

# 项目的默认全局语言、文字大小配置
VUE_APP_LANGUAGE = zh
VUE_APP_TEXT_SIZE = medium

# 项目调用后端API配置
VUE_APP_BASE_API = https://www.wzhz.xyz/vue-element-admin-api
VUE_APP_SRC = https://wzhz.xyz/

```

***或者删除或清空`.env`中的数据***

**Comment by anrananran** [comment]
正确的引用姿势应为：
`menu.component = resolve => require(['@' + menu.url + '.vue'], resolve)`

**Comment by hubangmao** [comment]
> 正确的引用姿势应为：
> `menu.component = resolve => require(['@' + menu.url + '.vue'], resolve)`
成功 非常nice

**Comment by jackC58** [comment]
> 正确的引用姿势应为：
> `menu.component = resolve => require(['@' + menu.url + '.vue'], resolve)`
我这边报Cannot find module './function (resolve) {  错误，请问你是怎么解决的？

**Comment by yin11** [comment]
> > 正确的引用姿势应为：
> > `menu.component = resolve => require(['@' + menu.url + '.vue'], resolve)`
> > 我这边报Cannot find module './function (resolve) {  错误，请问你是怎么解决的？

请问解决了嘛？我遇到这个问题，也改成route.component = (resolve)=> require([`@${name}`],resolve)  ，还是报错Cannot find module '@/views/xx'
    at webpackEmptyContext  。应该怎么处理呀，头秃
