### ISSUE TITLE
Error When Run 'npm install'

### ISSUE THREAD

**Issue by goforu** [PanJiaChen/vue-element-admin#1931]
## Bug report（问题描述）
Error when I run 'npm install'
#### Steps to reproduce（问题复现步骤）
npm install

#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/5236864/56271630-80913a00-612b-11e9-9643-6054b896527d.png)

#### Other relevant information（格外信息）
- Your OS: Red Hat 7
- Node.js version: v10.15.3
- vue-element-admin version: 3.10.0

**Comment by PanJiaChen** [comment]
https://github.com/typicode/husky/issues/196
