### ISSUE TITLE
右侧内容有滚动条，左侧导航栏也出现滚动条时，鼠标在左侧导航栏滚动操作的时会影响右侧内容的滚动

### ISSUE THREAD

**Issue by bessoft** [PanJiaChen/vue-element-admin#1932]
## Bug report（问题描述）
右侧内容有滚动条，左侧导航栏也出现滚动条时，鼠标在左侧导航栏滚动操作的时会影响右侧内容的滚动

1. 进入系统直接到首页
2. 鼠标在左侧导航栏里滚动
3. 右侧内容如果有滚动条目前会受左侧滚动条滚动影响
![55](https://user-images.githubusercontent.com/44956391/56274857-25af1100-6132-11e9-94d6-1836c945af36.gif)

- vue-element-admin version: 4.0.1

**Comment by PanJiaChen** [comment]
这是游览器默认行为。
