### ISSUE TITLE
table边框问题

### ISSUE THREAD

**Issue by niubilitynoob** [PanJiaChen/vue-element-admin#1934]
本地运行代码表格没有上边框，并且表头偏移一像素；侧边栏收起后，表格右边框也消失；

重现步骤:
1.克隆项目
2.安装依赖
3.运行项目
4.进入拖拽table和table内编辑

![image](https://user-images.githubusercontent.com/35186865/56330581-39528a00-61bb-11e9-9b2f-d193c6a0ff0e.png)

![image](https://user-images.githubusercontent.com/35186865/56330612-5ab37600-61bb-11e9-8a4c-456387ce01cd.png)

- Your OS: win7
- Node.js version: v10.15.0
- vue-element-admin version: 4.0.1

**Comment by krazychen** [comment]
解决了吗？怎么解决的？
