### ISSUE TITLE
请问我已经引用jquery了，但是怎么在Vue页面中调用呢，谢谢！

### ISSUE THREAD

**Issue by 1xiongyuwen1** [PanJiaChen/vue-element-admin#1938]

**Comment by 1xiongyuwen1** [comment]
我在vue页面中加上：console.log($('选择器'))会报错1 error potentially fixable with the `--fix` option.

**Comment by longfeiyu127** [comment]
其实我想反问,都用上了vue了,为啥还要用jq?开上宝马了,还在后面挂个拖拉机?

**Comment by PanJiaChen** [comment]
请先学会提问。你这样子提问是没人能帮你的。 @1xiongyuwen1

**Comment by longfeiyu127** [comment]
你调用的地方,引入了$了吗?
