### ISSUE TITLE
有没有前台分页呢vue-smart-table

### ISSUE THREAD

**Issue by haocm123** [PanJiaChen/vue-element-admin#194]
el-pagination 可以实现分页，这只是每次都访问后台进行获取数据；
有没有类似angularjs的smart-table 这种构成前台分页的功能；
建议大神将vue-smart-table 也整合进来

**Comment by PanJiaChen** [comment]
暂时我觉得 element 的 table 已经满足了大部分需求了，没必要在引入一个新的table组件了。
你说的数据缓存其实自己也很好做，你可以把请求过页数的数据cache住，每次filter list 先去看看cache 里有没有，没有的情况下再去发起get 请求数据

**Comment by haocm123** [comment]
谢谢。这个路子暂时先可以一试一试，希望以后会考虑加上前台分页功能；
如后台缓存一个地区的数据。前台一次查询全部拿到，最多json数据大概6M，经过压缩也就几百K。前端通过这些数据进行列表的分页 筛选过滤 排序 等，会大大提高用户对列表查询的体验；
