### ISSUE TITLE
动态嵌套路由缓存问题 列表和详情在同一个tagView里面时无法缓存上一个页面的搜索数据

### ISSUE THREAD

**Issue by kankantian** [PanJiaChen/vue-element-admin#1940]
![image](https://user-images.githubusercontent.com/8832463/56342346-56eb1800-61ea-11e9-9c69-469062bdf070.png)
点击查看后，同一个tagview打开查看详情页
![image](https://user-images.githubusercontent.com/8832463/56342397-7da94e80-61ea-11e9-8117-f5351b93e8c9.png)
再次点击返回上一级，列表搜索结果并未缓存，重新请求了一次数据
![image](https://user-images.githubusercontent.com/8832463/56342484-b9441880-61ea-11e9-8cd8-d3d61d83abd0.png)
路由配置如下：
![image](https://user-images.githubusercontent.com/8832463/56342526-d5e05080-61ea-11e9-9fbe-bc89c9da498e.png)
文件目录结果如下：
![image](https://user-images.githubusercontent.com/8832463/56342564-eabce400-61ea-11e9-9393-26b67f79c436.png)
index.vue:
![image](https://user-images.githubusercontent.com/8832463/56342580-f6a8a600-61ea-11e9-9e92-ae049136ceed.png)
求救，困扰了好多天了

**Comment by curryhh** [comment]
解决了吗？我也有同样的问题

**Comment by yushengling** [comment]
同问,有解决方案吗?
