### ISSUE TITLE
tar dependencies issue

### ISSUE THREAD

**Issue by Mahinanas** [PanJiaChen/vue-element-admin#1942]
Error while installing dependencies by npm i.
![Capture](https://user-images.githubusercontent.com/16433325/56393149-92b2cb80-6244-11e9-85ec-afc2258d6b67.JPG)

**Comment by PanJiaChen** [comment]
Please provide error message

**Comment by Mahinanas** [comment]
When am doing 'npm i'
i got this error and after i did 'npm audit' and then i got the error details which i attached first screenshot

![1](https://user-images.githubusercontent.com/16433325/56420664-f1f9f580-62af-11e9-91d2-1c7db3ed713e.JPG)

**Comment by PanJiaChen** [comment]
just warning.

**Comment by Mahinanas** [comment]
one high vulnerabiliy is exist in project that am telling.
