### ISSUE TITLE
热更新无法准确刷新组件

### ISSUE THREAD

**Issue by billycat** [PanJiaChen/vue-element-admin#1945]
## Bug report（问题描述）
目前发现，npm run dev 开发过程中，在一些页面中（比如 asyncRouterMap 里面定义的vue页面），增加了element组件后，热更新无法立即刷新出对应组件。这种情况，在vue页面指定了 name: 'xxx' 的情况下比较突出。

#### Steps to reproduce（问题复现步骤）

1. git clone 代码（master分支）
2. npm install
3. npm run dev
4. 选取一个页面，比如 src\views\permission\page.vue
5. 在 template 里面添加一个element组件，比如 el-button，保存，热更新刷新页面
```html
<template>
  <div class="app-container">
    <switch-roles @change="handleRolesChange" />
    <el-button type="primary">Button A</el-button>
  </div>
</template>
```
这时候，Button A 正常得到渲染
![image](https://user-images.githubusercontent.com/6973133/56449494-608c9100-634c-11e9-8f6f-71730493ab10.png)

6. 接着在 ButtonA 底下增加ButtonB，保存，热更新刷新页面
```html
<template>
  <div class="app-container">
    <switch-roles @change="handleRolesChange" />
    <el-button type="primary">Button A</el-button>
    <el-button type="primary">Button B</el-button>
  </div>
</template>
```
![image](https://user-images.githubusercontent.com/6973133/56449512-9af62e00-634c-11e9-8752-66797b9466c6.png)
这时候，Button B 无法被渲染出来，但热更新过程，页面可观察到有重新加载的过度动画，切换 tabView 的标签，也无法令到 ButtonB显示出现。

7. 将 ButtonB 的文字部分改成 buttonB，保存，热更新刷新页面
```html
<template>
  <div class="app-container">
    <switch-roles @change="handleRolesChange" />
    <el-button type="primary">Button A</el-button>
    <el-button type="primary">button B</el-button>
  </div>
</template>
```
![image](https://user-images.githubusercontent.com/6973133/56449540-3f787000-634d-11e9-9b7d-ad7ff3d5b951.png)
这时候，ButtonB 能够成功渲染

8. 假如，将src\views\permission\page.vue 的 name: 'PagePermission' 去掉，增删element组件但热更新无法正确渲染的情况，似乎不会出现

#### Other relevant information（格外信息）
虽然增删组件后，浏览器 ctrl + R 刷新页面是能够得到正确的渲染，但在开发过程中，的确有些困扰

- Your OS: Win7 or OSx 
- Node.js version: v10.15.3
- vue-element-admin version: master or tag.3.11.0

**Comment by PanJiaChen** [comment]
可能是 keep-alive 导致的问题，你试试不要缓存页面。

**Comment by billycat** [comment]
谢谢，的确是 noCache 默认给缓存了，问题解决了。
