### ISSUE TITLE
多次换肤，页面错乱问题

### ISSUE THREAD

**Issue by jipeigong** [PanJiaChen/vue-element-admin#1946]
分支版本：tag/3.11.0

## Bug report（问题描述）
我运行此分支代码不做修改，在多次换肤之后页面会乱掉，左侧菜单会消失

#### Steps to reproduce（问题复现步骤）
右上角换肤，多次更换

#### Screenshot or Gif（截图或动态图）
![微信截图_20190420105331](https://user-images.githubusercontent.com/7414916/56450903-735a9200-635b-11e9-896a-03b2664bb8b2.png)

#### Other relevant information（格外信息）
- Your OS: window10 chrome
- Node.js version: v8.12.0
- vue-element-admin version:tag/3.11.0

**Comment by PanJiaChen** [comment]
`tag/3.11.0`版本的已经不准备维护了。

**Comment by jipeigong** [comment]
新版本经测试没有此问题，此tag版本应该是4.0+前的最后一个版本，如果作者有时间的话可以帮忙看下，非常感谢

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/6b88c41ffc7d3794467481629f3025837e6d54a8#diff-732df266ef7fc719b32e782b712343ca

应该是这个 pr 导致的，你回退一下代码应该就好了。

**Comment by jipeigong** [comment]
回退代码后已正常，谢谢
