### ISSUE TITLE
富文本编辑器toolbar显示超过宽度

### ISSUE THREAD

**Issue by CuiYang16** [PanJiaChen/vue-element-admin#1948]
#### Steps to reproduce（问题复现步骤）
1，当窗口宽度小于文本编辑器最大宽度后，toolbar宽度超过文本编辑器宽度

![image](https://user-images.githubusercontent.com/42668875/56479722-6370b880-64e9-11e9-8a67-a6cece35b584.png)

**Comment by PanJiaChen** [comment]
这没办法的，自己调整 dialig宽度 或者调整toolbar的宽度。做不到自适应的。
