### ISSUE TITLE
在哪里可以把自带的登录拦截暂时关闭

### ISSUE THREAD

**Issue by zsjabjj** [PanJiaChen/vue-element-admin#1949]
请教作者, 怎么暂时关闭自带的登录拦截, 因为想自己添加登录校验, 还请告知, 谢谢

**Comment by PanJiaChen** [comment]
不理解你所谓的登录拦截指什么。

**Comment by zsjabjj** [comment]
就是说, 想知道是在哪里判断用户是否登录

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/d8dbf92b4714cd4f222d546413b6e15c63685e33/src/permission.js#L29-L55

**Comment by PanJiaChen** [comment]
建议你自己仔细看文档和源码。

**Comment by zsjabjj** [comment]
感谢, 以后一定多仔细看看文档
