### ISSUE TITLE
路由children中只有一个子路由的时候，menu菜单能依然显示父子关系吗？

### ISSUE THREAD

**Issue by DemoHu** [PanJiaChen/vue-element-admin#1954]
## Feature request（新功能建议）

当嵌套路由的children中只有一个子路由的时候，菜单组件会将这个子路由作为菜单显示在menu中，而不显示父路由的title, 期待的效果是，尽管children中只有一个路由，依然显示父子层级的菜单

**Comment by PanJiaChen** [comment]
`alwaysShow: true`

https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/router-and-nav.html#%E9%85%8D%E7%BD%AE%E9%A1%B9
