### ISSUE TITLE
更新4.0后如何去掉mock，改为直接调用后台api

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#1957]
## Question（提问）
更新4.0后，感觉好复杂，请问下如何去掉mock，改为直接调用后台api，

**Comment by vincentSea** [comment]
作者文档已经有详细说明、花点时间看看文档。
4.0的更新、其实不复杂。反而更加突出项目的完善性。
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/mock-api.html

**Comment by PanJiaChen** [comment]
4.0 mock 文档我晚点更新一下。

**Comment by moonose** [comment]
@PanJiaChen 

我改了下 .env.development 里的内容，直接定位到后台api服务
VUE_APP_BASE_API = 'http://localhost:9999/api'

问题是报错，错误信息如下
Access to XMLHttpRequest at 'http://localhost:9999/api/user/login' from origin 'http://localhost:9527' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

问题是，后台api server没有改动，是允许此ip访问的，前台还需要改动什么吗？

**Comment by PanJiaChen** [comment]
都提示你跨域错了。

**Comment by sun546970360** [comment]
> 4.0 mock 文档我晚点更新一下。
请问更新了吗

**Comment by GirHubCom** [comment]
请问作者啥时候更新，小白表示很无助

**Comment by moonose** [comment]
@PanJiaChen 
更新4.0后 npm run dev 提示

  App running at:
  - Local:   http://localhost:9527/
  - Network: http://10.86.197.119:9527/


后台服务启动在9999端口，后台部分代码见

   let cors = require('cors'); // 跨域访问
   let port = process.env.PORT || 9999;
   let app = express();

   app.use(cors({
        origin:['http://localhost:9527','http://127.0.0.1:9527'], // 允许的跨域访问地址
        methods:['GET','POST', 'OPTIONS'],
        alloweHeaders:['Conten-Type', 'Authorization']
   }));

原来版本没任何问题，在config目录下的dev.env.js里改的
   BASE_API: '"http://localhost:9999/api"',

新版改了下 .env.development 里的内容，直接定位到后台api服务
VUE_APP_BASE_API = 'http://localhost:9999/api'

  就报错了。有点晕。

**Comment by GirHubCom** [comment]
这个下面我也改了，但是还是访问的http://localhost:9527/dev-api/user/login
NODE_ENV = production

# just a flag
ENV = 'staging'

# base api
VUE_APP_BASE_API = 'http://localhost:8080/rest'
请问还需要改什么吗

**Comment by moonose** [comment]
> production

.env.development  是开发环境，改了再把mock给

**Comment by moonose** [comment]
我刚注释掉 request.js 里的
   // withCredentials: true, // send cookies when cross-domain requests

发现好了，继续晕，开启了这个设置，后台cors 还需要如何设置啊？
