### ISSUE TITLE
关于后端接口登录后跳转dashboard，侧边栏菜单不显示

### ISSUE THREAD

**Issue by jcops** [PanJiaChen/vue-element-admin#1958]
## Bug report（问题描述）
使用自己的后端接口实现了登录， 页面跳转到首页，侧边栏菜单不显示
#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/24266098/56628804-d27f1600-667d-11e9-9fa3-633d7e09c3c6.png)

#### Other relevant information（格外信息）
- Your OS:win10
- Node.js version:v10.15.3
- vue-element-admin version:4.0.1

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/3625f920411a831b60b1d650107e37b0517c3db0/src/layout/components/Sidebar/index.vue#L31

请自行debug

**Comment by jcops** [comment]
这个菜单 必须要有roles才能显示吗， 我是使用固定菜单的，没有roles， 请问要改哪几个地方呀， 谢谢啊

**Comment by PanJiaChen** [comment]
请自己看文档和源码。

**Comment by jcops** [comment]
你好，我侧边栏菜单经过如下配置可以显示出来了
store\modules\permission.js
![image](https://user-images.githubusercontent.com/24266098/56643454-3e787300-66ac-11e9-951b-b469ddf00fa4.png)
src\permission.js
![image](https://user-images.githubusercontent.com/24266098/56643483-4cc68f00-66ac-11e9-8df1-52746f2ba7af.png)

但有一些问题，登录页点击登录第一次会报以下错
![image](https://user-images.githubusercontent.com/24266098/56643619-8a2b1c80-66ac-11e9-9714-cf6e6a0db68d.png)
点击第二次登录就可以进入dashboard了
![image](https://user-images.githubusercontent.com/24266098/56643685-aaf37200-66ac-11e9-8491-07aff8e64289.png)

还有如果在首页刷新的话就跳转到登录页面去了。。因为该状态没保存？ 麻烦大佬指点指点

**Comment by jcops** [comment]
大佬，我弄好了，谢谢啊

**Comment by qihuayu88** [comment]
我也碰到这个问题了，我一直都跳转不到首页，请问你是怎么解决的？
![](https://user-images.githubusercontent.com/24266098/56643619-8a2b1c80-66ac-11e9-9714-cf6e6a0db68d.png)

**Comment by cardsix** [comment]
> 大佬，我弄好了，谢谢啊

老哥你怎么弄的？

**Comment by 1145523635** [comment]
有代码看看嘛
