### ISSUE TITLE
@components: pagination

### ISSUE THREAD

**Issue by skylingfly** [PanJiaChen/vue-element-admin#1959]
## Question（提问）

// 在 example/list.vue & table/complexTable.vue 均未使用到 pagination 携带的参数，在如下公共组件Pagination中handleCurrentChange方法是参数不需要携带。

```js
    handleCurrentChange(val) {
      this.$emit('pagination', { page: val, limit: this.pageSize })
      if (this.autoScroll) {
        scrollTo(0, 800)
      }
    }
```

**Comment by PanJiaChen** [comment]
没懂你想问什么？

**Comment by skylingfly** [comment]
只是问下如下是否为多余代码？
![image](https://user-images.githubusercontent.com/31003691/56634670-67d9d480-6695-11e9-9359-3a48eea05fa5.png)
![image](https://user-images.githubusercontent.com/31003691/56634717-9c4d9080-6695-11e9-9092-92448f0f16e1.png)

**Comment by PanJiaChen** [comment]
这是组件设计问题，没用到不代表没有意义。

这里没用到的原因是我用了`page.sync`，但有的人不喜欢这样写，那他就可以从回调函数中获取`page`参数。
