### ISSUE TITLE
无权限时一级菜单仍显示

### ISSUE THREAD

**Issue by cuizhihua127** [PanJiaChen/vue-element-admin#1962]
#### Steps to reproduce（问题复现步骤）

router/index.js  如下：
```js
    {
    path: '实时监控',
    redirect: 'noredirect',
    meta: { title: '实时监控', icon: 'example' },
    children: [
      {
        path: externalLinkUrl,
        name: 'T9000',
        meta: { title: '实时监控', icon: 'link', name: 'T9000' }
      }
    ]
  }
```
src/store/modules/permission.js   
 改了 hasPermission 方法  其中roles 为后端返回的权限数组
格式为:["T1001", "T1002", "T0015", "T0014", "T0013", "T0009"]
function hasPermission(roles, route) {
  if (route.meta && route.meta.name) {
    return roles.includes(route.meta.name)
  } else {
    return true
  }
}

#### Screenshot or Gif（截图或动态图）
一级目录仍旧显示
![image](https://user-images.githubusercontent.com/29140367/56637837-336b1600-669f-11e9-9bcd-a277c535e6e0.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
没设权限的意思是所有人都能看。

**Comment by cuizhihua127** [comment]
意思是没有权限 
预期结果是  整个目录都不出现

**Comment by PanJiaChen** [comment]
但你路由并没有设权限啊

**Comment by cuizhihua127** [comment]
1、我没有用你的思路  即 在路由那设置roles  
2、我的思路是 ：
后台返回一个权限数组，例如：list：["T1001", "T1002", "T0015", "T0014", "T0013", "T0009"]
hasPermission 方法里如果权限数组list  包含route.meta.name  则说明有权限
现状是：后端返回的权限数组 不包含 实时监控 即T9000 那么实时监控这个 目录就不应该显示
结果是显示

**Comment by PanJiaChen** [comment]
那就是你的问题，我怎么知道你具体哪里有问题。

**Comment by chengmanxiang** [comment]
> 1、我没有用你的思路 即 在路由那设置roles
> 2、我的思路是 ：
> 后台返回一个权限数组，例如：list：["T1001", "T1002", "T0015", "T0014", "T0013", "T0009"]
> hasPermission 方法里如果权限数组list 包含route.meta.name 则说明有权限
> 现状是：后端返回的权限数组 不包含 实时监控 即T9000 那么实时监控这个 目录就不应该显示
> 结果是显示

{
    path: '实时监控',
    redirect: 'noredirect',
    meta: { title: '实时监控', icon: 'example' },
    children: [
      {
        path: externalLinkUrl,
        name: 'T9000',
        meta: { title: '实时监控', icon: 'link', name: 'T9000' }
      }
    ]
  }



一级菜单也加上这个T900之类的东西，后台不返回一级的菜单就可以
