### ISSUE TITLE
选中某个菜单，能否收起其他大菜单

### ISSUE THREAD

**Issue by DemoHu** [PanJiaChen/vue-element-admin#1964]
## Feature request（新功能建议）
例如选中了权限测试页中的子页面，组件菜单能否收起

![Snipaste_2019-04-24_18-08-02](https://user-images.githubusercontent.com/26042365/56651608-04af6880-66bc-11e9-85f6-35ec48f0684c.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1929
