### ISSUE TITLE
改变了当前页面的title,TagsView显示的是未改变之前的Title

### ISSUE THREAD

**Issue by HoweZhang** [PanJiaChen/vue-element-admin#1967]
## Question（提问）

当前页面类似综合实力的文章详情页，我看每篇文章详情的TagsView都带上了id
![image](https://user-images.githubusercontent.com/13114024/56717408-32091e80-676f-11e9-931d-db9efcf2147b.png)

**Comment by iamjojo1225** [comment]
所以你想問甚麼?  只看到title 沒看到你所謂的ID

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1973
