### ISSUE TITLE
Paused on promise rejection

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#1968]
## Question（提问）
@PanJiaChen 

用自己的API返回结果， 假设结果为  res.json({code: 400, message: 'failed'});

浏览器会报 Paused on promise rejection 错误，出现  Paused in debugger
request.js 定位到 return Promise.reject(res.message || 'error')

请问下这怎么处理？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/f9f51986e611fc2b14b2bff32344cf68208d5bd8/src/utils/request.js#L33-L82

**Comment by fuoridallarete** [comment]
I get stuck at this point too.  I get the token, I don't know where the error is coming from.
