### ISSUE TITLE
问下有什么方法可以让左侧菜单在展开模式下也能让子菜单向有弹出展示？

### ISSUE THREAD

**Issue by wangyegg1989** [PanJiaChen/vue-element-admin#1971]
## Question（提问）

问下有什么方法可以让左侧菜单在展开模式下也能让子菜单向有弹出展示？

就是左侧菜单展开时子菜单的效果和收起时子菜单的效果相同？有什么快捷的方法吗？

**Comment by PanJiaChen** [comment]
没有，侧边栏是基于 `element-ui`实现的。你除了改它源码，没有其他什么简洁方案。

或者说你就让侧边栏一直收缩状态，自己强行修改css。
