### ISSUE TITLE
抛给 Request.js的错误信息，为什么不能显示？

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#1972]
## Question（提问）

在登录时，我修改了下返回代码，让 res.code = 401，使逻辑走到 request.js里的 response interceptor。
   
调用到return Promise.reject(res.message || 'error')，语句返回到 login函数里的 catch
    login: function login(_ref, userInfo) {
        ....
      }).catch(function (error) {
        reject(error);
      });

至此一切顺利，error为 需要显示的错误信息字符串。继续程序调用到 vuex.esm.js 里的 function registerAction (store, type, handler, local) 函数。
    
      return res.catch(function (err) {
        store._devtoolHook.emit('vuex:error', err);
        throw err
      })
err 同样为显示的错误信息，再走下去 throw err 就结束了。问题是，显示的提示内容依旧是 'error', 不是想要显示的错误提示，请教下这是什么问题？

**Comment by PanJiaChen** [comment]
`Promise.reject(res.message || 'error')` 你都自己指出来。

**Comment by PanJiaChen** [comment]
你不写`message`当然是`error`

 https://github.com/PanJiaChen/vue-element-admin/blob/c58e2078bc06a22d1d71c8eb6ea532bf2248ad9f/mock/user.js#L62

**Comment by moonose** [comment]
@PanJiaChen 大神，message我写的啊，

![1](https://user-images.githubusercontent.com/37356039/56779225-80202f80-680c-11e9-96e1-8c49e73a4af6.png)
![2](https://user-images.githubusercontent.com/37356039/56779226-80202f80-680c-11e9-9723-d7dd57af405a.png)

但跳出来就是没信息
![3](https://user-images.githubusercontent.com/37356039/56779228-80b8c600-680c-11e9-88c1-a9763f91e64c.png)

**Comment by moonose** [comment]
是我错了，羞愧下。谢谢大神指点。
