### ISSUE TITLE
您好，能回答我一下关于tagview的问题么

### ISSUE THREAD

**Issue by liuchong1995** [PanJiaChen/vue-element-admin#1973]
![image](https://user-images.githubusercontent.com/28603937/56777897-5237ec80-6806-11e9-850a-5e40a2fc34ea.png)
这里面编辑文章后面的 “ -1 ” 是在哪里添加的？我找了半天没找到.......

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/c58e2078bc06a22d1d71c8eb6ea532bf2248ad9f/src/views/example/components/ArticleDetail.vue#L186-L190

**Comment by liuchong1995** [comment]
> [vue-element-admin/src/views/example/components/ArticleDetail.vue](https://github.com/PanJiaChen/vue-element-admin/blob/c58e2078bc06a22d1d71c8eb6ea532bf2248ad9f/src/views/example/components/ArticleDetail.vue#L186-L190)
> 
> Lines 186 to 190 in [c58e207](/PanJiaChen/vue-element-admin/commit/c58e2078bc06a22d1d71c8eb6ea532bf2248ad9f)
> 
>      setTagsViewTitle() { 
>        const title = this.lang === 'zh' ? '编辑文章' : 'Edit Article' 
>        const route = Object.assign({}, this.tempRoute, { title: `${title}-${this.postForm.id}` }) 
>        this.$store.dispatch('tagsView/updateVisitedView', route) 
>      },

谢谢 之前一直在tagView找......
