### ISSUE TITLE
记住标签栏打开问题

### ISSUE THREAD

**Issue by chenzhenhu** [PanJiaChen/vue-element-admin#1979]
vue-element-admin 4

切换用户会打开之前用户打开过的标签栏，且该用户没有该页面权限，也会被打开。

**Comment by PanJiaChen** [comment]
理论上切换用户都需要重新登录，所以不存在你说的问题。

**Comment by xinnian1992** [comment]
快捷标签按钮确实被缓存了，在切换账户登录的时候
