### ISSUE TITLE
打包后再次刷新出现空白的问题

### ISSUE THREAD

**Issue by wu7zhi** [PanJiaChen/vue-element-admin#198]
路由跳转如下代码，刷新直接走最后的else了，之后页面就空白了，资源也都加载，也没报错

if (!store.getters.permission_routers) {
                console.log('-------2---------')
                const userStr = store.getters.user;
                if (common.isDefine(userStr)) {
                    console.log('-------3---------')
                    const user = JSON.parse(userStr);
                    const roles = user.roles;
                    console.log(roles)
                    store.dispatch('GenerateRoutes', {
                        roles
                    }).then(() => {
                        router.addRoutes(store.getters.addRouters);
                        router.addRoutes(store.getters.topRouters);
                        next({ ...to});
                    })
                } else {
                    common.cookie.delete('spider-token')
                    next('/login');
                    NProgress.done();
                }
            } else {
                console.log('-----------4-------------');
                next();
            }

**Comment by PanJiaChen** [comment]
你刷新了之后 `store.getters.permission_routers)` store就空了 当然会走下面else的逻辑

**Comment by wu7zhi** [comment]
这么快就有回复了，给力！！可是我在开发的时候没问题啊

**Comment by PanJiaChen** [comment]
这要看你具体的代码了，你只提供了一个代码判断，看不出具体原因

**Comment by wu7zhi** [comment]
与你的代码差不多的，现在的问题是没打包之前登陆，store.getters.permission_routers == undefined，打包之后登陆就有数据了，我的登陆逻辑与你的一样，成功后   this.$router.push({ path: '/' });
if (store.getters.permission_routers == undefined) {
                const roles = getLocUser().roles;
                console.log(roles);
                store.dispatch('GenerateRoutes', {
                    roles
                }).then(() => {
                    router.addRoutes(store.getters.addRouters);
                    router.addRoutes(store.getters.topRouters);
                    next({ ...to});
                })
            } else {
                next();
            }

**Comment by PanJiaChen** [comment]
我还有一步根据本地token 拉取用户信息的操作
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/permission.js#L23
详情见文章 https://segmentfault.com/a/1190000009506097
