### ISSUE TITLE
同一个tab，怎么可以多开呢？

### ISSUE THREAD

**Issue by xixigiggling** [PanJiaChen/vue-element-admin#1980]
可以在sidebar里面的菜单项，每次点击同一菜单项都打开一个新tab吗？（例如每次点开文档项，都重新打开一个文档标签页）

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/f24b64392e70bcfbfb6f60e72dc9d9b552d99220/src/store/modules/tagsView.js#L8

目前通过 `path`来判断是否需要新开一个 `tab`。
你可以自己改规则。
