### ISSUE TITLE
使用element-ui中upload组件上传成功会自动刷新页面

### ISSUE THREAD

**Issue by CuiYang16** [PanJiaChen/vue-element-admin#1982]
#### Steps to reproduce（问题复现步骤）
使用element-ui的upload组件上传图片成功后，自动刷新整个页面，但是其他操作不会，只有上传图片

#### Other relevant information（格外信息）
- Your OS:win7

**Comment by PanJiaChen** [comment]
这个和本项目基本没什么关系，大概率是自己的问题。
如果你还是觉得有问题，请提供重现步骤或者在线demo。

**Comment by CuiYang16** [comment]
我可能改了配置，都在什么情况下会触发刷新页面
