### ISSUE TITLE
为什么 设置布局大小，我默认 是 medium 第一次进来的时候 是default， 然后点击切换的时候 可以生效， 但是手动刷新页面 就变回了default

### ISSUE THREAD

**Issue by 32388626** [PanJiaChen/vue-element-admin#1985]
![image](https://user-images.githubusercontent.com/50081882/56867782-29894000-6a1c-11e9-9594-2412b88b4b92.png)
![image](https://user-images.githubusercontent.com/50081882/56867784-327a1180-6a1c-11e9-976f-4f84926757c4.png)
![image](https://user-images.githubusercontent.com/50081882/56867791-46be0e80-6a1c-11e9-9673-21cef499e57f.png)

**Comment by 32388626** [comment]
![image](https://user-images.githubusercontent.com/50081882/56867803-6b19eb00-6a1c-11e9-8c8a-f8989c25d68b.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/9c28b1dd924fe0a2d8541759569fda046fb62eb7/src/main.js#L33
