### ISSUE TITLE
Dynamic load of routers from server after login

### ISSUE THREAD

**Issue by yamelsenih** [PanJiaChen/vue-element-admin#1986]
## Question（提问）

Hi everybody thanks for make changes for Improve this great app.

I have a question about dynamic routes from app.

I follow the documentation from it: https://panjiachen.github.io/vue-element-admin-site/guide/essentials/permission.html#permission

My main question is that I have a app with 3 main components to use:
- Window: Generic Window where is add info or showed. Basically is a UI for CRUD 
- Process: Used for get parameters and run a process on background
- Report: Used for get parameters and return a PDF report

My problem is that the Window component load dynamically all need field for show to end user, then I can use the same component for show many windows, see:
Name of component: Window

- Case 1: BPartner Window
  - Table for CRUD: BPartner
- Case 2: Product Window
  - Table for CRUD: Product

How is showed the component is the same but the route is distinct and field showed is distinct for route.

I resolved it add dynamically the same component with distinct route.

All is ok but I find that when login page is loaded, all routes are loaded before press login button.

Exist a way or event for get routes from server dynamically after press login button?

Best regards.

**Comment by PanJiaChen** [comment]
https://router.vuejs.org/guide/advanced/lazy-loading.html

This project is now lazy loading, there is no problem you said
