### ISSUE TITLE
更新4.0后如何去掉mock，改为直接调用后台api ,文档还未更新，旧文档已经不可用

### ISSUE THREAD

**Issue by MNWPRO** [PanJiaChen/vue-element-admin#1989]

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/mock-api.html#%E6%96%B0%E6%96%B9%E6%A1%88

**Comment by MNWPRO** [comment]
@PanJiaChen 谢大佬
