### ISSUE TITLE
时间日期筛选项，单个的日期和时间筛选，设置了默认的时间参数，更改日期时，时间没有更新为默认的时间参数。

### ISSUE THREAD

**Issue by athousandsplendidsuns** [PanJiaChen/vue-element-admin#1990]
#### Steps to reproduce（问题复现步骤）
复现步骤：
1.选时间日期组建的第一个，设置默认的时间default-time="00:00:00"
2.更新了时间之后，时间为02:00:00
3.选择其他的日期，期望时间重置为00:00:00
4.但是时间还是02:00:00

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/33248111/57192021-7a3df300-6f5e-11e9-8a7c-77df1cdb1883.png)

#### Other relevant information（格外信息）
- Your OS: mac 10.13.4 
- Node.js version: v10.13.0
- vue-element-admin version: v2.3.7

**Comment by PanJiaChen** [comment]
你给的demo是空的。

**Comment by athousandsplendidsuns** [comment]
好的，抱歉，我稍等检查一下再重新贴上


 
---原始邮件---
发件人: "花裤衩"<notifications@github.com>
发送时间: 2019年4月29日(星期一) 下午2:54
收件人: "PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"athousandsplendidsuns"<846784609@qq.com>;
主题: Re: [PanJiaChen/vue-element-admin] 时间日期筛选项，单个的日期和时间筛选，设置了默认的时间参数，更改日期时，时间没有更新为默认的时间参数。 (#1990)



你给的demo是空的。

**Comment by athousandsplendidsuns** [comment]
> 你给的demo是空的。

我重新编辑了信息，麻烦看后回复一下，谢谢

**Comment by PanJiaChen** [comment]
请给线上demo

**Comment by athousandsplendidsuns** [comment]
> 请给线上可重现你问题的demo，节约彼此时间。

https://codesandbox.io/s/8nqxjry5pl

**Comment by PanJiaChen** [comment]
合理想象。


如果想实现你要的效果，可以在确定之后，你重新设置`dateValue`为空值就可以了。
