### ISSUE TITLE
怎么升级

### ISSUE THREAD

**Issue by chunbobo** [PanJiaChen/vue-element-admin#1994]
## Question（提问）

弱弱的问一下，我使用了这个框架，怎么进行升级...我今天发现好多element的图标我都用不了

**Comment by PanJiaChen** [comment]
我不知道你所谓的升级是 `vue-element-admin` 3.0 => 4.0 还是什么？

`element`图标是官方新版本新增的，你只要在`package.json`中升级`element-ui`版本就好了。

**Comment by chunbobo** [comment]
我的意思就是当你升级了框架时，我使用的框架怎么升级

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/504
