### ISSUE TITLE
关于逐步替换掉MOCK接口的问题

### ISSUE THREAD

**Issue by tomkai** [PanJiaChen/vue-element-admin#1997]
## Question（提问）
根据文档，4.0中使用proxy拦截了请求转到mock.js中
逐步替换的时候只需将mock中的模拟业务屏蔽即可

按vue-cli3官网文档，proxy本意是解决本地开发时，后端提供接口跨域地址的问题
现在Proxy被使用

我开发是在本地，request拼接出来的请求地址是localhost域，我如果本地mock业务取消，请求变成Localhost本机，本机本身是没有后端服务，有没有办法再代理一次到其它公网域使用后端提供的真实接口地址。

**Comment by PanJiaChen** [comment]
`proxy`本质就是代理，跨域和mock都是一个道理。

第二个问题：`proxy`可以写多个代理规则，请自行查看相关文档。

**Comment by cuiyinming** [comment]
//把项目根目录下的.env.development 中的mock 代理改为自己的跨域地址即可
`  publicPath: '/',
  outputDir: 'dist',
  assetsDir: 'static',
  lintOnSave: process.env.NODE_ENV === 'development',
  productionSourceMap: false,
  devServer: {
    port: port,
    open: true,
    overlay: {
      warnings: false,
      errors: true
    },
    proxy: {
      // change xxx-api/login => mock/login
      // detail: https://cli.vuejs.org/config/#devserver-proxy
      [process.env.VUE_APP_BASE_API]: {
        target: `http://paofen.9subi.com/api`,
        changeOrigin: true,
        pathRewrite: {
          ['^' + process.env.VUE_APP_BASE_API]: ''
        }
      }
    }
    // after: require('./mock/mock-server.js')
  },
`

服务端nginx 添加：
`add_header Access-Control-Allow-Origin $http_origin;
			add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
			add_header Access-Control-Allow-Credentials true;
			add_header Access-Control-Allow-Headers X-Token,X-Requested-With;`
重启nginx 就可以了

**Comment by mixueer** [comment]
按照上面这个做了，但是还是提示报错？
