### ISSUE TITLE
表格 动态刷新

### ISSUE THREAD

**Issue by linuxMengfan** [PanJiaChen/vue-element-admin#1998]
## Question（提问）

使用表格，在触发删除操作   this.list.splice(index, 1)。 日志确定真确返回是我删除的行。 但是页面的刷新永远我删除的第一行（实际后台并没用真的触发删除）。
现在我的办法是触发删除操作后 location.reload()刷新整个页面。 
请问下第一种单行删除刷新怎么修改

**Comment by PanJiaChen** [comment]
基本是你自己代码的问题。

有问题，请提供在线demo。

**Comment by linuxMengfan** [comment]
网上Demo 我全部试了一次……
