### ISSUE TITLE
使用element-ui steps组件，每个el-step中的数字及连接线都向右下偏移

### ISSUE THREAD

**Issue by shandafu** [PanJiaChen/vue-element-admin#200]
使用element-ui steps组件，每个el-step中的数字及连接线都向右下偏移（未垂直居中），请问如何解决？谢谢
<img width="654" alt="11" src="https://user-images.githubusercontent.com/3531338/30191553-0d6fe8ee-9474-11e7-9003-aa00cd419dbc.png">

**Comment by PanJiaChen** [comment]
首先这是element的问题，你可以去[这里提问](https://github.com/ElemeFE/element),
其次人家官方描述就是这样的，你想自定义可以自己覆盖css
