### ISSUE TITLE
在打开el-dialog时，主页面的滚动条会消失，导致主页面的内容会加宽，轻微的向右移动

### ISSUE THREAD

**Issue by l54808821** [PanJiaChen/vue-element-admin#2000]
#### Steps to reproduce（问题复现步骤）
1. 设置fixedHeader: true
2. 在主页面弹出dl-dialog
3. 观察头内容
备注，如果设置fixedHeader为false，这个问题是没有的

#### 
![test](https://user-images.githubusercontent.com/49773498/57078416-d9aebf80-6d20-11e9-8e20-b7277e41c2a0.gif)

#### 
- vue-element-admin version: vue-admin-template-permission-control

**Comment by l54808821** [comment]
您好，问题，我已经解决，在layout组件的index组件中的.fixed-header样式中right 减去滚动条样式的宽度，就可以完美解决表格位移和主页面多余空白问题

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/76198201698bd5c0b4a61553035317b2b5e6d7ff

**Comment by NameWjp** [comment]
这样改有点粗暴。。会导致本来没有滚动条的页面都出现滚动条了
