### ISSUE TITLE
build:prod and error:MIME type ('text/html') is not a supported stylesheet MIME type

### ISSUE THREAD

**Issue by Rex-Man** [PanJiaChen/vue-element-admin#2003]
#### Steps to reproduce（问题复现步骤）

1. npm run build:prod
2. run server
3. access index.html

```
Refused to apply style from 'http://localhost:63342/static/css/chunk-libs.3dfb7769.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Refused to apply style from 'http://localhost:63342/static/css/app.ae89c2cc.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

#### Screenshot or Gif（截图或动态图）

<img width="630" alt="Screen Shot 2019-05-03 at 5 08 41 PM" src="https://user-images.githubusercontent.com/8547085/57128466-1385d180-6dc6-11e9-81b0-a4ca3afbf940.png">

#### Other relevant information
- Your OS: macOs
- Node.js version: v11.8.0
- vue-element-admin version:v4.0.1

**Comment by Sicmatr1x** [comment]
same issue, but my version is 3.10.0

**Comment by PanJiaChen** [comment]
你改过什么？
感觉像 `publicPath`设置的不对。
