### ISSUE TITLE
面包屑问题

### ISSUE THREAD

**Issue by cuizhihua127** [PanJiaChen/vue-element-admin#2006]
## Question（提问）

![image](https://user-images.githubusercontent.com/29140367/57187331-50191080-6f1f-11e9-8cfd-428ffe00a650.png)
你好，route多加一层就会多一层导航栏

**Comment by PanJiaChen** [comment]
太个性化需求了，请自己实现。

**Comment by cuizhihua127** [comment]
为什么会多一层呢？  想要效果是只有一层导航栏，就跟你的demo 那样的。

**Comment by PanJiaChen** [comment]
这你自己代码的问题吧。
