### ISSUE TITLE
 npm run dev报错  10% building 2/2 modules 0 active ERROR  SyntaxError: Unexpected string

### ISSUE THREAD

**Issue by jy1989** [PanJiaChen/vue-element-admin#2008]
## Bug report（问题描述）
npm install 貌似没问题

npm run dev的时候报错

> 10% building 2/2 modules 0 active ERROR  SyntaxError: Unexpected string     
/Users/chen/Documents/svnproject/PJ-jxc/trunk/app/mock/index.js:1
(function (exports, require, module, __filename, __dirname) { import "core-js/modules/es6.regexp.constructor";

 
#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/1291756/57188513-99269000-6f32-11e9-953b-0d36feef3be2.png)

#### Other relevant information（格外信息）
- Your OS: macOS 10.14.1 (18B75)
- Node.js version:6.4.1
- vue-element-admin version:4.0.1

**Comment by PanJiaChen** [comment]
重新安装一下依赖，看着像少了 babel的一些东西。
```bash
npm cache clean --force
npm install
```

**Comment by jy1989** [comment]
> 重新安装一下依赖，看着像少了 babel的一些东西。
> 
> ```shell
> npm cache clean --force
> npm install
> ```

重重复复试过几次  node_modules也删过了  还是一样，奇怪了。

![image](https://user-images.githubusercontent.com/1291756/57189978-b6b22480-6f47-11e9-88cb-fb82c4371b5c.png)

**Comment by jy1989** [comment]
node modules 删了  重新用yarn装了一次  也是一样

![image](https://user-images.githubusercontent.com/1291756/57190675-a0a86200-6f4f-11e9-9514-577f5e229712.png)

**Comment by PanJiaChen** [comment]
重新基于 master clone 一下试试？

**Comment by jy1989** [comment]
> 重新基于 master clone 一下试试？

我明白了   是缺少几个.开头的隐藏文件导致的
感谢回复

**Comment by pylixm** [comment]
遇到同样问题，应该是 .env.development 中的这个参数的问题：
```
VUE_CLI_BABEL_TRANSPILE_MODULES = true
```
加上解决 ~

**Comment by airzhanglin** [comment]
为什么  .env.development  简写为.env.dev就不行？

**Comment by KevinBlack** [comment]
> 遇到同样问题，应该是 .env.development 中的这个参数的问题：
> 
> ```
> VUE_CLI_BABEL_TRANSPILE_MODULES = true
> ```
> 
> 加上解决 ~
求代码！能详细说下怎么加的么？

**Comment by huabulai** [comment]
> > 重新基于 master clone 一下试试？
> 
> 我明白了 是缺少几个.开头的隐藏文件导致的
> 感谢回复

兄弟，具体是缺失什么文件，都找到了，放出来给我们看看嘛

**Comment by Bill70058** [comment]
> > > 重新基于 master clone 一下试试？
> > 
> > 
> > 我明白了 是缺少几个.开头的隐藏文件导致的
> > 感谢回复
> 
> 兄弟，具体是缺失什么文件，都找到了，放出来给我们看看嘛

![image](https://user-images.githubusercontent.com/36560656/71334434-2af21480-2579-11ea-826c-b507ad662af3.png)

**Comment by Bill70058** [comment]
> > > 重新基于 master clone 一下试试？
> > 
> > 
> > 我明白了 是缺少几个.开头的隐藏文件导致的
> > 感谢回复
> 
> 兄弟，具体是缺失什么文件，都找到了，放出来给我们看看嘛

可能是这几个，我的话是这个几个的问题

**Comment by jy1989** [comment]
> > > > 重新基于 master clone 一下试试？
> > > 
> > > 
> > > 我明白了 是缺少几个.开头的隐藏文件导致的
> > > 感谢回复
> > 
> > 
> > 兄弟，具体是缺失什么文件，都找到了，放出来给我们看看嘛
> 
> 可能是这几个，我的话是这个几个的问题

就是.开头的这些隐藏文件
