### ISSUE TITLE
在使用el-popover的v-model控制插槽的显示，无法使用click触发方式，建议群大封装一个更好的小组件

### ISSUE THREAD

**Issue by l54808821** [PanJiaChen/vue-element-admin#2009]
## Feature request（新功能建议）
在使用el-popover的v-model控制插槽的显示，无法使用click触发方式，建议群大封装一个更强大的小组件
另外el-popover在这个方式下，会显示两个el-popover元素，

**Comment by PanJiaChen** [comment]
暂时没有这打算，我觉得你有需求可以向官方提。
