### ISSUE TITLE
如果路由带有参数格式为?username=aaa，的情况下token失效跳转到登陆界面，重新登陆后路由中的参数会被去除

### ISSUE THREAD

**Issue by l54808821** [PanJiaChen/vue-element-admin#2011]
## Bug report（问题描述）
如果路由带有参数格式为?username=aaa，的情况下token失效跳转到登陆界面，重新登陆后路由中的参数会被去除

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/2013
