### ISSUE TITLE
dev环境与prod环境打包出来的效果不一样

### ISSUE THREAD

**Issue by xiaowan** [PanJiaChen/vue-element-admin#202]
使用场景：在组件的dialog中使用了子组件，子组件中还有一个dialog，dev环境下子组件的dialog可以完全覆盖在父组件的dialog上，这是正常的想要的效果，但是打包到prod环境，子组件的dialog就被套在了外围的dialog之中

**Comment by PanJiaChen** [comment]
如果你指的是 element-ui 的 dialog 的话 请参见
https://github.com/ElemeFE/element/issues/3499

**Comment by PanJiaChen** [comment]
升级 `element` 到@2.x.x版本就可以了
