### ISSUE TITLE
登录请求自己接口要怎么弄？

### ISSUE THREAD

**Issue by mygirlmy2** [PanJiaChen/vue-element-admin#2021]

**Comment by PanJiaChen** [comment]
看文档 https://panjiachen.gitee.io/vue-element-admin-site/zh/guide/essentials/mock-api.html

**Comment by mygirlmy2** [comment]
按这个弄的现在报错了
![image](https://user-images.githubusercontent.com/47839720/57276707-fb1efb00-70d4-11e9-8ab7-e25ca9e37f3f.png)

**Comment by PanJiaChen** [comment]
报错很明显。 请自己去学习 vuex 该怎写。

**Comment by mygirlmy2** [comment]
我就把你的路径换了，还要改写法吗？

**Comment by mygirlmy2** [comment]
我定义了then为什么还报错啊？

**Comment by mygirlmy2** [comment]
我定义了then为什么还报错啊

**Comment by PanJiaChen** [comment]
你是自我过滤了第一条报错信息了么？

**Comment by mygirlmy2** [comment]
跨域需要改哪里

**Comment by mygirlmy2** [comment]
![image](https://user-images.githubusercontent.com/47839720/57283371-91591e00-70e1-11e9-8667-8fee77d16626.png) 我已经配置了跨域为什么还不能解决

**Comment by mygirlmy2** [comment]
![image](https://user-images.githubusercontent.com/47839720/57286021-0549f500-70e7-11e9-907f-3aaf02fd27f2.png)
我配置好跨域了 为什么访问接口还是你的 要怎么修改
