### ISSUE TITLE
本地测试当Fixed Header为true时，back to top组件不显示

### ISSUE THREAD

**Issue by DewittPerry** [PanJiaChen/vue-element-admin#2023]
## Bug report（问题描述）
本地测试当Fixed Header为true时，back to top组件不显示
#### Steps to reproduce（问题复现步骤）
1. 全局设置Fixed Header为true
2. 选择菜单栏Components->Back To Top，测试发现组件未正常显示

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
我测了下线上的版本，没能重现你的问题。

**Comment by DewittPerry** [comment]
> 我测了下线上的版本，没能重现你的问题。

线上版本
![image](https://user-images.githubusercontent.com/9127719/57292077-755e7800-70f3-11e9-8dfa-43df0e729a62.png)有这个显示，本地测试的时候没有才会有问题

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/e8e6c7e79c2488779090f00efc5f1bbfcb04bd5b

这段代码导致的，我看一下怎么修

**Comment by PanJiaChen** [comment]
我会退了代码 https://github.com/PanJiaChen/vue-element-admin/commit/2364fecbdd2972c56e03f8eb6ebb8f144a60839d
