### ISSUE TITLE
冒昧的问下，下载本地打开就没有切换语言功能是什么骚操作？

### ISSUE THREAD

**Issue by maokeng** [PanJiaChen/vue-element-admin#2024]

**Comment by PanJiaChen** [comment]
文档写的很清楚了，国际化需要使用 i18n 分支。

**Comment by maokeng** [comment]
vue-element-admin 是一个后台前端解决方案，它基于 vue 和 element-ui实现。它使用了最新的前端技术栈，内置了 i18 国际化解决方案....。。。。。。。..糟老头子坏得很。

**Comment by tkggusraqk** [comment]
今天也遇到了个问题，最好明确说明下

**Comment by theForagingPawns** [comment]
大佬  使用了i18n分支  但是main.js的同级并没有文档内说的lang语言文件
是不是更新的略有问题 @PanJiaChen

**Comment by theForagingPawns** [comment]
![image](https://user-images.githubusercontent.com/45359620/69114675-052ca800-0ac1-11ea-9a68-8a5c2071f54d.png)
属实拉的i18n分支的代码
