### ISSUE TITLE
点击登录报错【Request failed with status code 404】

### ISSUE THREAD

**Issue by PineSongCN** [PanJiaChen/vue-element-admin#2025]
看了下错误，是请求不到mock接口，有没遇到过的？请问是怎么解决的？
![image](https://user-images.githubusercontent.com/39976617/57291322-c9685d00-70f1-11e9-98fc-fd5438ea55c8.png)

**Comment by PanJiaChen** [comment]
你是不是开了多个9527的端口？或者说当前的启动的端口不是你在 `config`里设置的 `port`.

**Comment by PineSongCN** [comment]
谢谢，把【vue.config.js】的9527改成了网址上的9528就可以了。
