### ISSUE TITLE
为什么我把登录数据换成自己 登录的时候会弹出error 而不是跳转到指定页面呢？ 请大神指教啊

### ISSUE THREAD

**Issue by mygirlmy2** [PanJiaChen/vue-element-admin#2026]

**Comment by PanJiaChen** [comment]
大概率数据返回的不对，请自行对比 debug。

**Comment by mygirlmy2** [comment]
![image](https://user-images.githubusercontent.com/47839720/57347208-0bda7a00-7184-11e9-8b3f-37fc6195cffb.png)跑通之后为什么会报这些错呢

**Comment by Jasmineysj** [comment]
请问题主的warn解决了吗

**Comment by xyhuxin** [comment]
大神，我也遇到了同样的问题，求解答？

**Comment by phoebemoon16** [comment]
相同问题，请问解决了吗？--
