### ISSUE TITLE
Fixed Header模式下，下拉框问题

### ISSUE THREAD

**Issue by alvis-u** [PanJiaChen/vue-element-admin#2028]
## Bug report（问题描述）
在4.1.0版本中，使用Fixed Header模式，下拉列表会出现多次弹出显示，像弹簧一样。

#### Steps to reproduce（问题复现步骤）

1.启动vue-elment-admin
2.在设置中打开Fixed Header
3.打开菜单中Table-Complex Table
4.点击下拉框，可发现问题，像弹簧一样弹多次才展示出来列表

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version: 4.1.0

**Comment by PanJiaChen** [comment]
这段代码导致的 e8e6c7e

**Comment by PanJiaChen** [comment]
我会退了代码 https://github.com/PanJiaChen/vue-element-admin/commit/2364fecbdd2972c56e03f8eb6ebb8f144a60839d
