### ISSUE TITLE
表格分页问题

### ISSUE THREAD

**Issue by 799535610** [PanJiaChen/vue-element-admin#203]
查询触发：
handleFilter() {
      this.listQuery.page = 1
      this.getList()
}

查询条件切换时， 并不会返回到第1页

**Comment by PanJiaChen** [comment]
并没有重现你说的问题

**Comment by 799535610** [comment]
综合table

选择查询条件日本，有2页数据。现在点击第2页， 这时定义在第2页。
这时我切换到美国，点击搜索，这时依旧在第2页。

切换了查询条件，应该定位在第1页

**Comment by PanJiaChen** [comment]
这个交互上的确可以优化一下

**Comment by PanJiaChen** [comment]
@v2.1.0 已优化该细节
