### ISSUE TITLE
左侧菜单三级目录全部隐藏二级菜单无法跳转

### ISSUE THREAD

**Issue by zarte** [PanJiaChen/vue-element-admin#2031]
## Question（提问）
一级菜单
  菜单二 （跳转到菜单二）
    菜单 2-1 （隐藏）

尝试修改
侧边栏类
 <template v-for="child in item.children" v-if="!child.hidden">
          <sidebar-item :is-nest="true" class="nest-menu" v-if="!child.islink&...尝试这里加判断返回false实现

结果报 Maximum call stack size exceeded错误
# 484

**Comment by PanJiaChen** [comment]
其提供可复现问题的 声明的侧边栏路由
