### ISSUE TITLE
手机端加载时界面样式存在问题

### ISSUE THREAD

**Issue by cobnst** [PanJiaChen/vue-element-admin#2033]
手机端访问时加载样式存在问题

## Bug report（问题描述）
1. Safari 访问在线模板及git 下来的模板时都存在加载完成后 折线图未能按照正确的大小渲染，上下滑动页面后尺寸回复正常。
2. 六边形图在手机端 图名与图例之间部分重叠

#### Steps to reproduce（问题复现步骤）

1. Iphone XR Safari 直接访问

#### Screenshot or Gif（截图或动态图）
1.以下为折线图加载时及加载完成后截图
![1](https://user-images.githubusercontent.com/11661996/57374058-95159f00-71cc-11e9-834e-7fdf0df42d03.jpg)
![2](https://user-images.githubusercontent.com/11661996/57374060-95159f00-71cc-11e9-95a4-e72516848b2f.jpg)
2.以下为六边形图加载完成后截图
![3](https://user-images.githubusercontent.com/11661996/57374061-95ae3580-71cc-11e9-997a-a841cb35ea08.jpg)

#### Other relevant information（格外信息）
- Your OS: IOS12.2

**Comment by PanJiaChen** [comment]
有部分是 echarts 的问题。
https://github.com/apache/incubator-echarts/pull/8513

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/2060
