### ISSUE TITLE
svg-icon 是否可以通过url地址加载svg图标呢？

### ISSUE THREAD

**Issue by Erik5169** [PanJiaChen/vue-element-admin#2034]
类似于img标签通过url连接从网络上加载图片一样

**Comment by PanJiaChen** [comment]
svg 本身是支持的。 https://stackoverflow.com/questions/34097191/using-a-svg-file-in-html-from-a-url

不过你这样做的意义是什么？

**Comment by Erik5169** [comment]
服务端返回的是一个icon的地址，我在想如果用svg图标的地址是否一样可以用svg-icon组件

**Comment by PanJiaChen** [comment]
我来实现一下吧。

**Comment by PanJiaChen** [comment]
我测了下，使用 url 加载的方式有一个弊端，不能修改 svg 的颜色。

**Comment by Erik5169** [comment]
把svg源文件中的fill 跟stroke填充颜色去掉的话，应该能修改吧，不能修改颜色也没关系，可以加载就行了

**Comment by PanJiaChen** [comment]
Added in https://github.com/PanJiaChen/vue-element-admin/pull/2052

**Comment by Erik5169** [comment]
多谢裤衩哥
