### ISSUE TITLE
我的main.js里先import router再import store，此时在store里import router里的constantRoutes 时候，总显示undefined，改成在main.js里先import store再import router才成功，请问这是为什么呢？我的理解是，main.js先import router，正好被store文件import啊

### ISSUE THREAD

**Issue by huaiyue** [PanJiaChen/vue-element-admin#2035]

**Comment by huaiyue** [comment]
我的main.js里先import router再import store，此时在stor/modules/permissionse里import router里的constantRoutes 时候，总显示undefined，改成在main.js里先import store再import router才成功，请问这是为什么呢？我的理解是，main.js先import router，正好被store文件import啊

**Comment by PanJiaChen** [comment]
这是是webpack的问题。

https://github.com/PanJiaChen/vue-element-admin/issues/1537
