### ISSUE TITLE
浏览器标题图标

### ISSUE THREAD

**Issue by zhubufang** [PanJiaChen/vue-element-admin#2039]
浏览器标题图标 怎么修改不了

**Comment by PanJiaChen** [comment]
浏览器有缓存，请关闭浏览器之后重启服务再试试。

**Comment by zhubufang** [comment]
> 浏览器有缓存，请关闭浏览器之后重启服务再试试。

还是没有用   

请问这个图标是在哪个文件设置的

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/public/favicon.ico

**Comment by XguangY** [comment]
这个版本可以修改，那个ts版本的修改不了。确认不是缓存问题

**Comment by JslinSir** [comment]
> 这个版本可以修改，那个ts版本的修改不了。确认不是缓存问题 @PanJiaChen

确实改不了，你怎么解决的

**Comment by JslinSir** [comment]
打包后生成的是这样的，所以在对应文件加上即可

```
 <link rel=icon type=image/png sizes=32x32 href=/img/icons/favicon-32x32.png>
    <link rel=icon type=image/png sizes=16x16 href=/img/icons/favicon-16x16.png>
```

**Comment by codedance98** [comment]
@XguangY 在`vue-typescript-admin-template`中通过下面两个标签可以看到，`ico`是从`/img/icons/`加载的。尝试改ico名，可打包出来dist中ico名字不变，不生效。所以把你的ico文件改名为`favicon-32x32`和`favicon-16x16`两份放入`/public/img/icons`下，亲测有效。
```html
 <link rel="icon" type="image/png" sizes="32x32" href="/img/icons/favicon-32x32.png">
 <link rel="icon" type="image/png" sizes="16x16" href="/img/icons/favicon-16x16.png">
```
