### ISSUE TITLE
动态修改variables.scss主题样式改不了hover 样式

### ISSUE THREAD

**Issue by BetwayM** [PanJiaChen/vue-element-admin#2040]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by BetwayM** [comment]
找到sidebar.scss,去掉颜色设置后面的!important,不然改不了侧边栏展开的背景和hover
// menu hover
    .submenu-title-noDropdown,
    .el-submenu__title {
      &:hover {
        background-color: $menuHover;
      }
    }

    .is-active > .el-submenu__title {
      color: $subMenuActiveText;
    }

    & .nest-menu .el-submenu > .el-submenu__title,
    & .el-submenu .el-menu-item {
      min-width: $sideBarWidth;
      background-color: $subMenuBg;

      &:hover {
        background-color: $subMenuHover;
      }
    }

**Comment by liudao008** [comment]
我取消!important后，所有颜色都变成$menuBg的颜色。是我的改变variables.scss的方法实现有问题吗。方便看下您的demo是怎么实现的吗

**Comment by PanJiaChen** [comment]
没能重现。有问题，请新开issue，详细描述问题。
