### ISSUE TITLE
npm run build:prop 之后无法登录，

### ISSUE THREAD

**Issue by chuz** [PanJiaChen/vue-element-admin#2041]
npm run build:prod 之后，我安装了
npm install -g serve
之后运行打包的文件
serve -s dist
浏览器访问，界面可以显示，但是无法登录，提示prod-api/user/login 找不到

![image](https://user-images.githubusercontent.com/2840119/57446482-55f85400-7287-11e9-90f2-07beff26e417.png)

- Your OS: win10
- Node.js version:  v10.15.3
- vue-element-admin version:  013f4fd91b7fe6c92f05dbece197bd244180ba8f   4.1.0+

**Comment by PanJiaChen** [comment]
文档里写的很清楚了，mock-serve 只支持dev。
线上环境切换自己的api接口，或者启用 mockjs.

https://github.com/PanJiaChen/vue-element-admin/blob/0bf339b6db44fb6f8484865f15748cbd95b0c958/src/main.js#L22-L29

**Comment by chuz** [comment]
响应速度非常快！赞
测试可以了，不过我觉得可以在readme那边备注下，我网上看到都是发布后，直接放server里面...没提到要启用mock。就是在build那一段落下面

**Comment by PanJiaChen** [comment]
好我晚点完善一下文档。
