### ISSUE TITLE
请问在JS里如何设置本地图片路径？设置的'@/assets/图片'在vue解析后是原样输出

### ISSUE THREAD

**Issue by PineSongCN** [PanJiaChen/vue-element-admin#2045]
![image](https://user-images.githubusercontent.com/39976617/57448924-32380c80-728d-11e9-80e0-de39b323aeec.png)

![image](https://user-images.githubusercontent.com/39976617/57448874-0fa5f380-728d-11e9-971f-c2ee62630f48.png)

**Comment by chengmanxiang** [comment]
require（）就可以了，或者用相对路径../../之类的

**Comment by PineSongCN** [comment]
> require（）就可以了，或者用相对路径../../之类的

谢谢，小白刚接触，请问有没有示例？
不知道这里怎么用require，试了相对路径，大概是我理解的不对，也是不行。
