### ISSUE TITLE
Why function init tinymce error when mounted?

### ISSUE THREAD

**Issue by CuongStf** [PanJiaChen/vue-element-admin#2048]
I have copy folder tinymce in github into my project, but when invoke in my component, error is window.tinymce.init is undefined.
Can you recommend solution for me?
I find in github but not find config window prototype tinymce.

` 
<Tinymce
       ref="editor"
       v-model="modelEvent.content"
       :height="700"
/>
`

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/feature/component/rich-editor.html#tinymce

You should import `Tinymce.js` in window.

https://github.com/PanJiaChen/vue-element-admin/blob/7b0d527bf90a3391c17586215f3012c9855d0176/vue.config.js#L60-L64

**Comment by unssnu** [comment]
Same error+1
and if I change tinymce to 4.9.3, another error with css occured, connection error

**Comment by CuongStf** [comment]
> Same error+1
> and if I change tinymce to 4.9.3, another error with css occured, connection error

let's use 4.9.2 version. it's ok
