### ISSUE TITLE
tagviews多页签 同时打开多个多页签

### ISSUE THREAD

**Issue by chengmanxiang** [PanJiaChen/vue-element-admin#2049]
## Feature request（新功能建议）

我们项目有这样的需求，有个按钮生成作业，成功之后跳转作业页面，作业页面是公用的，但是生成作业有可能是多个id;也就是要打开多个作业页面的多页签，只是id的值不同，这样的话能实现而且能做到缓存吗？谢谢

**Comment by luoxiang666** [comment]
根据路由打开的。。。路由发生变化 就能打开

**Comment by ansonhorse** [comment]
这个项目的综合示例里的文章列表，不就是可以打开多个编辑页么。
至于缓存，也是可以做到的，你可以看一下：https://github.com/PanJiaChen/vue-element-admin/issues/1629
