### ISSUE TITLE
左侧菜单栏出现滚动条，过于丑陋，顶部导航栏不固定……

### ISSUE THREAD

**Issue by ren-liang** [PanJiaChen/vue-element-admin#205]
1.最好能修改左侧菜单栏滚动条的样式，或者这将菜单栏宽度可以拖动大小这样比较完美；
2.顶部导航栏随着页面的下拉竟然跑了，让它回来，别跑啊，哈哈

**Comment by PanJiaChen** [comment]
第一个问题是值得改价一下。
第二个问题没太懂，能具体说明一下问题么。

**Comment by liuxiaochuan111** [comment]
意思是 当页面高度大于屏幕高度时，向下滚动，让头部导航栏固定下来

**Comment by leij1ang** [comment]
顶部导航栏已经完成，等requests把上个requests合上去就提交

**Comment by slovebj** [comment]
头部导航栏tabs选项卡建议参照B-JUI的navtab修改

**Comment by jianliulin** [comment]
bjui已经不更新了，要是tab能改进点，估计很多bjui的用户会转到这里来，我就其中一个，哈哈

**Comment by jdlindu** [comment]
左侧菜单栏出现滚动条的问题要怎么解决有进展么

**Comment by PanJiaChen** [comment]
新版本会用js模拟滚动 预计下周会发布vue-element-admin@3.0.x 版本

**Comment by PanJiaChen** [comment]
已发布新版本
