### ISSUE TITLE
切换布局大小 跳转到404页面

### ISSUE THREAD

**Issue by redwolf1996** [PanJiaChen/vue-element-admin#2056]
想把完整版的size-select功能 移植到vue-admin-template项目，但每次切换布局大小的时候都跳转到404页面了，请问是哪里出错了～～

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/redirect/index.vue

需要一个重定向页面。请仔细看源码。

**Comment by redwolf1996** [comment]
感谢，解决了
