### ISSUE TITLE
父组件里同时加载五个echarts的子组件和高德地图过一段时间无法释放内存

### ISSUE THREAD

**Issue by QMZhao** [PanJiaChen/vue-element-admin#2057]
## Question（提问）

大神，请教一下，我在进入到该组件后过了一段时间内存无法释放，我在beforeDestroy销毁定时器，高德地图，echarts还有声明的一些变量，我在该页面和其他页面进行路由切换的时候发现高德地图的一些组件还占用在内存当中，请问我该往怎样一个思路去解决一下呢

**Comment by PanJiaChen** [comment]
这种组件都是有 `destroy` 方法的，我觉得看着他们的文档来就可以了。

**Comment by QMZhao** [comment]
谢谢大神的回答
