### ISSUE TITLE
两个问题，是打算直接劝退我么？

### ISSUE THREAD

**Issue by jiadaoyun** [PanJiaChen/vue-element-admin#2059]
clone报错。没办法直接下载整个压缩文件下来。
npm install 以后，屏幕花了，死机了=。=
我还抱有侥幸心理，觉得是和其他应用冲突。开机以后，什么都不开，继续npm install 一下，又见花屏。咋办啊，啥原因啊？
![image](https://user-images.githubusercontent.com/12387480/57516804-0594fb00-7348-11e9-9d53-60fa66543f3c.png)
![image](https://user-images.githubusercontent.com/12387480/57516837-16de0780-7348-11e9-86f7-e8f37ae302e1.png)

**Comment by PanJiaChen** [comment]
和本项目没有有什么直接关系。

**Comment by dongsuo** [comment]
建议换台电脑试一下……

**Comment by jiadaoyun** [comment]
> 和本项目没有有什么直接关系。

那clone失败为啥啊

**Comment by wangxu1206** [comment]
八成是电脑配置不够,这也能和项目扯上关系...

**Comment by PanJiaChen** [comment]
https://blog.csdn.net/huihut/article/details/79404421

你可以自己搜搜错误信息。

**Comment by microkof** [comment]
clone 一下别的库试试，以及，重装系统试试，或者不想重装就下载zip试试
