### ISSUE TITLE
博主左边菜单的无滚动条滚动是怎么实现的？拜谢

### ISSUE THREAD

**Issue by wqb2017** [PanJiaChen/vue-element-admin#206]
跑了博主的项目发现左侧菜单并没有使用什么插件就可以实现，左侧菜单滚动，不知博主是怎么做的？能否说说？

**Comment by PanJiaChen** [comment]
目前左边侧边栏主要是基于 [element-menu](http://element.eleme.io/#/zh-CN/component/menu)
滚动主要是用 `overflow-y: auto;`
Duplicate of #187
