### ISSUE TITLE
使用v-el-height-adaptive-table时出错 Failed to resolve directive: el-height-adaptive-table

### ISSUE THREAD

**Issue by xuzhenlei** [PanJiaChen/vue-element-admin#2061]
#### Steps to reproduce（问题复现步骤）
1.import adaptive from '@/directive/el-table'
2.directives: { adaptive },
3.添加v-el-height-adaptive-table="{bottomOffset: 30}"和height="100px"到el-table

#### Screenshot or Gif（截图或动态图）
![WPV1)6{1U0410VI( )BG_~A](https://user-images.githubusercontent.com/49263609/57537600-3ccfd000-7379-11e9-8717-9d80f7bc3f98.png)

#### Other relevant information（格外信息）
- Your OS: windows 10
- Node.js version: 8.9.3
- vue-element-admin version: 4.1 i18n分支

**Comment by xuzhenlei** [comment]
把指令名称改为adaptive就可以自适应了；又发现新的问题：keep-live的页面只有第一次打开能生效，关闭页面，再打开就失效了，不会自适应！
![EKHG93PR6S`92GUD7P8{GLC](https://user-images.githubusercontent.com/49263609/57541242-2594e080-7381-11e9-81de-28fc381afc91.png)

**Comment by xuzhenlei** [comment]
又发现新的问题：
1.同时设置complex-table.vue和inline-edit-table.vue页面的el-table自适应，如果打开complex-table.vue，可以达到自适应的效果，接着打开inline-edit-table.vue，该页面的el-table不能自适应
keep-live的页面只有第一次打开能生效，关闭页面，再打开就失效了，不会自适应！

**Comment by xiezhuoxun** [comment]
发现同样的问题，期待大神修复。

**Comment by suyana** [comment]
同发现问题，跟踪发现是非首次时，设置表格高度的时候不生效。
目前处理方法是adaptive.js的doResize方法内，最后2行加个setTimeout....

`$table.layout.setHeight(height)
 $table.doLayout()`
改为：
`  setTimeout(function(){
    $table.layout.setHeight(height)
    $table.doLayout()
  },1)`

**Comment by superZhouDaLu** [comment]
@xuzhenlei  fixed in #3131

**Comment by eeezgame** [comment]
可以这样处理 先让el-table渲染高度为100px后 再执行设置适应高度

`doResize()`函数里
```
  $table.layout.setHeight(height)
  $table.doLayout()
```
更改为:
```
  $table.$nextTick(() => {
    $table.layout.setHeight(height)
  })
```

**Comment by yangguangwuwu** [comment]
v-el-height-adaptive-table 我也出现了
