### ISSUE TITLE
tinymce移到cdn后，设置语言出错

### ISSUE THREAD

**Issue by zss007** [PanJiaChen/vue-element-admin#2067]
## Question（提问）

tinymce移到cdn后，在src/components/Tinymce/index.vue中给window.tinymce.init设置language: 'zh_CN'报错，报错信息：Failed to load plugin url: https://cdn.jsdelivr.net/npm/tinymce-all-in-one@4.9.2/langs/zh_CN.js

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/2096ae1b6ec0fbe0ccf31ed56f5257208d3a71c8

更新一下 cdn 版本就好了
