### ISSUE TITLE
修改请求地址,请求后台接口

### ISSUE THREAD

**Issue by MingLiuHN** [PanJiaChen/vue-element-admin#2068]
![image](https://user-images.githubusercontent.com/34367398/57604853-d248ab00-7597-11e9-9d65-50d5596d05ef.png)
已经注释掉了webpack-dev-server中after这个Middleware。
修改成了自己需要请求后台地址,还是一直请求不过去,麻烦大佬了.

**Comment by PanJiaChen** [comment]
自己看proxy文档。主要修给配置需要重启服务。

**Comment by fantasthu** [comment]
@MingLiuHN 兄弟,你解决了么,我启动之后换了个easy-mock的地址修改login的返回数据
```
proxy: {
			// change xxx-api/login => mock/login
			// detail: https://cli.vuejs.org/config/#devserver-proxy
			[process.env.VUE_APP_BASE_API]: {
				target: `https://easy-mock.com/mock/5d3e96445fbc7d4183fa97f5/user`,
				// target: `http://127.0.0.1:${port}/mock`,
				changeOrigin: true,
				pathRewrite: {
					['^' + process.env.VUE_APP_BASE_API]: ''
				},
				bypass: consoleProxy
			}
		},
```

**Comment by lihua123569** [comment]
可以用代理
也可以直接在utils里面的request.js里面改这行： baseURL: process.env.VUE_APP_BASE_API_URL
VUE_APP_BASE_API_URL，这个在vue.config.js里面改后台的地址
