### ISSUE TITLE
Uploading Exel file

### ISSUE THREAD

**Issue by javapad** [PanJiaChen/vue-element-admin#207]
could you add excel uploading feature?  https://codepen.io/Event_Horizon/pen/WodMjp

**Comment by PanJiaChen** [comment]
@javapad 
http://panjiachen.github.io/vue-element-admin/#/excel/upload
v2.1.0已加上该功能

**Comment by javapad** [comment]
Thanks,
If possible,  could you add drop zone feature?

**Comment by power315cn** [comment]
你好，首先感谢作者的开源，在使用上传EXCEL功能，发现可以改进的地方，提一个小意见：
1.同一个excel要上传多次，目前的功能无法实现，由于没有触发change事件

**Comment by power315cn** [comment]
补充我的写法：
```
    handleUpload() {
      document.getElementById('excel-upload-input').click()
      document.getElementById('excel-upload-input').addEventListener('click', function() {
        this.value = ''
      }, false)
    }

**Comment by PanJiaChen** [comment]
@power315cn  欢迎pull request

**Comment by PanJiaChen** [comment]
Drag and drop upload is supported. https://github.com/PanJiaChen/vue-element-admin/commit/1d0b26cec887144cc5d42a1a2603f6cbc760f25a
