### ISSUE TITLE
开发者模式调试找不到源码

### ISSUE THREAD

**Issue by sunnycreate** [PanJiaChen/vue-element-admin#2074]
![Capture](https://user-images.githubusercontent.com/20456456/57680919-38e5cb80-7661-11e9-865b-db73128d71f6.PNG)

**Comment by PanJiaChen** [comment]
![Uploading image.png…]()

**Comment by sunnycreate** [comment]
是经过编译过了的吧，请问可以配置成和项目源码一样吗？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/dbfcc9dc19e5ef160146a9ef87efce1ac0857240/vue.config.js#L102-L105

请自行看文档。
