### ISSUE TITLE
使用VUE_CLI_BABEL_TRANSPILE_MODULES导致module加载失败

### ISSUE THREAD

**Issue by de1ck** [PanJiaChen/vue-element-admin#2075]
#### Steps to reproduce（问题复现步骤）

 测试环境开启该环境变量会导致动态获取import无效，但是直接引用没有问题。

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/26627486/57682477-8879c680-7664-11e9-97b8-f634cb00002c.png)

![image](https://user-images.githubusercontent.com/26627486/57682522-a6472b80-7664-11e9-9fcb-d73e0155f162.png)

![image](https://user-images.githubusercontent.com/26627486/57682634-da225100-7664-11e9-8956-528a4fa41c97.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
这和本项目没什么关系。

**Comment by PanJiaChen** [comment]
你这样做的确会有问题。

你要么移除`VUE_CLI_BABEL_TRANSPILE_MODULES`这个环境变量
要么开发环境不要用异步加载的方式改用`module.exports = file => require('@/views/' + file + '.vue').default // vue-loader at least v13.0.0+
`

不过总的来说都不推荐 `import('@/views/')`这种写法，会有问题。https://github.com/PanJiaChen/vue-element-admin/issues/292
