### ISSUE TITLE
请求用户信息生成路由会阻塞页面渲染

### ISSUE THREAD

**Issue by sunchenguang** [PanJiaChen/vue-element-admin#2076]
```
const { roles } = await store.dispatch('user/getInfo')
const accessRoutes = await store.dispatch('permission/generateRoutes', roles)
router.addRoutes(accessRoutes)
next({ ...to, replace: true })
```
如题，请求用户信息生成路由会阻塞页面渲染。
如果获取用户信息接口返回数据较慢，就会造成页面长时间白屏

我现在的处理方法：
1. 初始时正常挂载所有路由
2. 获取用户信息时不阻塞渲染，在获取用户信息promise的then中generateRoutes， 重新生成一套routes。
3. 使用新routes创建newRouter，替换现有router的matcher。 router.matcher = newRouter.matcher
4. 继续在then中判断，用户在当前路由是否有权限，如果没权限，页面跳转redirect，达到refresh的效果，即显示401页面

**Comment by PanJiaChen** [comment]
我觉得这是合理操作，用户权限是能进入页面的前提。
