### ISSUE TITLE
tab路由问题

### ISSUE THREAD

**Issue by allen-hxn** [PanJiaChen/vue-element-admin#208]
你好，我发现在使用动态路由匹配时，如/product/create_apply/:id，匹配到product/create_apply/4路由，浏览器地址栏显示 http://localhost:9527/#/product/create_apply/4
结果在切换tab时，地址变成http://localhost:9527/#/product/create_apply/:id 了，
请问要如何解决呀？

**Comment by PanJiaChen** [comment]
没太理解你的问题

**Comment by allen-hxn** [comment]
不好意思，可能我描述的不清楚。
我的意思的是    
动态匹配后的进入了   A页面http://localhost:9527/#/create_apply/123。这时我点击B页面tab切换到B页面。 然后点击刚才的A页面tab，想切回到A页面，发现切换回来的地址变成http://localhost:9527/#/product/create_apply/:id   导致我在A页面$route.params.id从 123 变成了 :id

**Comment by PanJiaChen** [comment]
个人感觉是你自己代码的问题
能否提供一个重现demo

**Comment by Nc32** [comment]
遇到了同样的问题, 
进入类似这样的路由时发生
```javascript
{ path: 'edit/:id', component: _import('pushproduct/edit'), name: 'Edit Product', props: true }
```
假设进入一个 edit/4
此时生成的visited_view中存的地址是 edit/:id .而不是 edit/4
之后点击tag访问的地址就是edit/:id,就会出错

原因是this.$route.matched传回来的对象中 path 是解析之前的.

我试了下修改TabsView.vue中的addViewTabs()方法, 直接传进解析好的地址. 目前为止还没发现问题
```javascript
addViewTabs() {
  const view = Object.assign({}, this.generateRoute()) // 不clone直接修改会出现神奇的bug
  if (view.props) view.path = this.$route.fullPath
  this.$store.dispatch('addVisitedViews', view) 
},
```
