### ISSUE TITLE
关闭右侧tab页，请求仍然在发送给后台

### ISSUE THREAD

**Issue by git-ruoshui** [PanJiaChen/vue-element-admin#2081]
#### Steps to reproduce（问题复现步骤）

1.下载项目后，在其中一个页面写一个向后台定时发送请求的例子，当关闭右侧tab页，发现请求仍然在发送给后台，给后台造成额外的压力

#### Other relevant information（格外信息）
- Your OS:win10
- Node.js version:8.12
- vue-element-admin version:3.9.2

**Comment by PanJiaChen** [comment]
你自己在关闭页面前 清理定时器。
