### ISSUE TITLE
resetRouter 

### ISSUE THREAD

**Issue by ccccccode** [PanJiaChen/vue-element-admin#2088]
请教一个问题：

退出登陆后重新登陆，控制台报路由重复的问题

在router/index.js中看见有resetRoute()这个方法，我现在在退出的时候调用，再次登陆的时候还是会报路由重复

logout：

![1557978665(1)](https://user-images.githubusercontent.com/41566488/57825242-99474b00-77d0-11e9-8974-e683a756e7c6.jpg)

![1557978617(1)](https://user-images.githubusercontent.com/41566488/57825216-7ddc4000-77d0-11e9-9f8d-60273fda5d38.jpg)

resetRoute：

![1557978714(1)](https://user-images.githubusercontent.com/41566488/57825286-c0058180-77d0-11e9-8291-8b9dcbf4faf1.jpg)

**Comment by ccccccode** [comment]
我这里有3个登陆页面 index agent store，在退出的时候已经做好了判断，通过哪个颜面登陆的，退出就会在哪个页面

现在用刷新的办法解决路由重复的问题，会直接跳转到index，我在agent登陆页面登陆的，我想退出的时候还是在agent登陆页面，

**Comment by PanJiaChen** [comment]
你说的 本项目都实现了，请自行阅读源码和debug。
