### ISSUE TITLE
NavMenu 导航菜单 路由跳转后如何动态设置当前菜单高亮

### ISSUE THREAD

**Issue by kingdee88** [PanJiaChen/vue-element-admin#209]
请问个大神一个 navMenu的问题

如题， 路由跳转后如何动态设置当前菜单高亮？

**Comment by PanJiaChen** [comment]
https://segmentfault.com/a/1190000009762198#articleHeader3

相关代码：https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/layout/Sidebar.vue#L2
