### ISSUE TITLE
this.$store.dispatch('user/login', this.loginForm)

### ISSUE THREAD

**Issue by jijianchao** [PanJiaChen/vue-element-admin#2096]
在登录页面中
this.$store.dispatch('user/login', this.loginForm) 为什么dispatch的第一个参数是'user/login' 而不是action 的名字login

**Comment by PanJiaChen** [comment]
vuex 命名空间

https://vuex.vuejs.org/zh/guide/modules.html#%E5%91%BD%E5%90%8D%E7%A9%BA%E9%97%B4

**Comment by michael2299** [comment]
学习了
