### ISSUE TITLE
发布命令报错，提示  'NODE_ENV' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by limars874** [PanJiaChen/vue-element-admin#21]
我这边安装成功之后，npm run dev没有任何问题。但在输入发布命令时报错，不论是npm run build:sit-preview还是npm run build:prod，都提示同一个错误：
```
'NODE_ENV' 不是内部或外部命令，也不是可运行的程序。
```
想问问这个是要需要在那里设置一下这个NODE_ENV吗？

平台是windows，node安装在c盘根目录，版本7.9。
注：windows下面，需要把.eslintrc.js下面的
```
'linebreak-style': 'error',
```
修改为
```
'linebreak-style': ['error','windows'],
```
否则run dev也会报错，会提示一堆如" Expected linebreaks to be 'LF' but found 'CRLF'"之类的错误。

**Comment by wyudong** [comment]
try: http://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-in-windows

**Comment by limars874** [comment]
嗯，我刚搜到这篇，解决了，还说来自问自答.

win下面修改package.json，把里面相应的改掉就行。
```
"build:prod": "set NODE_ENV=production && node build/build.js",
 "build:sit": "set NODE_ENV=sit && node build/build.js",
 "build:sit-preview": "set NODE_ENV=sit && npm_config_preview=true && npm_config_report=true && node build/build.js",
```

**Comment by limars874** [comment]
补充一下，后来莫名其妙run dev又不行了，于是安装了一个cross-env，把package的dev改成如下：
```
"dev": "cross-env NODE_ENV=development node build/dev-server.js",
```
就可以了。理论上下面的也可以这样加cross-env前缀。

**Comment by tyhyly** [comment]
windows系统下尽量用cross-env，上面set那种有时候还是会报错~~
npm install cross-env（该插件作用是windows环境下可执行linux命令）

**Comment by cocoxiang** [comment]
本地build ok，服务器上build报错“sh: cross-env: 未找到命令”
