### ISSUE TITLE
axios 在IE下发送请求失败，老是说network error

### ISSUE THREAD

**Issue by lecykx** [PanJiaChen/vue-element-admin#210]
axios 在IE下发送请求失败，老是说network error，搞了差不多一周也没折腾到点上，所以发上来问问大家有没有遇到过。

代码：
let qs = require('qs');
export function login(username, password) {
    const data = {
        username,
        password
    };
    return axios({
        url: 'oauth/token',
        method: 'post',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
        },
        data: qs.stringify(data)
    });
}

**Comment by PanJiaChen** [comment]
请确定你的ie版本啊，人家axios 写着只支持ie8+

**Comment by gaoshijun1993** [comment]
我的ie版本已经是11了,并且使用了poly-fill,但还是报错...
