### ISSUE TITLE
登录成功之后，无法跳转到首页，报以下异常

### ISSUE THREAD

**Issue by 7Q2019** [PanJiaChen/vue-element-admin#2104]
您好！
我把登录接口替换为真实接口后，服务器验证成功后返回了数据。但无法跳转到首页，报以下异常，请问是什么原因？
![QQ截图20190517225308](https://user-images.githubusercontent.com/31687962/57937294-36e96a00-78f8-11e9-94b7-b977f1a82842.png)

**Comment by 7Q2019** [comment]
已解决，谢谢大神！

**Comment by xyhuxin** [comment]
大神你这个问题怎么解决的，我也遇到了这个问题？

**Comment by xyhuxin** [comment]
https://user-images.githubusercontent.com/31687962/57937294-36e96a00-78f8-11e9-94b7-b977f1a82842.png

**Comment by fzg2lj** [comment]
> 已解决，谢谢大神！

大神怎么解决的

**Comment by phoebemoon16** [comment]
大神 如何解决的 被这个问题困扰好久 --
