### ISSUE TITLE
请问旧版3.9.0怎么更新到4.0？

### ISSUE THREAD

**Issue by hlbj105** [PanJiaChen/vue-element-admin#2106]
请问旧版3.9.0怎么更新到4.0？
4.0改了很多bug，而且用的是cli 3 的，想更新，请问怎么更新？有哪些需要注意的？谢谢

**Comment by PanJiaChen** [comment]
其实主要改了构建。

你可以重新下载新的 master 代码，你的大部分业务代码都在 views里面，覆盖就好了。之后就是一些细节问题，按照报错来改就行了。
