### ISSUE TITLE
如果侧边栏条目太多，则无法向下滑动显示完整的菜单

### ISSUE THREAD

**Issue by redwolf1996** [PanJiaChen/vue-element-admin#2108]
菜鸟请教，如题，路由里添加N多个菜单，那么左侧显示满后无法向下滑动显示更多的条目了

**Comment by PanJiaChen** [comment]
请提供截图。

**Comment by redwolf1996** [comment]
![WechatIMG40](https://user-images.githubusercontent.com/9690393/57994359-67dfbf80-7aef-11e9-8ac3-9c34577c42ea.jpeg)

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/57994542-3e736380-7af0-11e9-8d41-17f060852615.png)

请确定使用的最新版本，已经支持滚动条很久了。

**Comment by redwolf1996** [comment]
这个总部系统设置下面还有一堆菜单 但是显示不出来了 也滑不动了。。。

**Comment by redwolf1996** [comment]
对了 我用的 template 那个版本 难道说跟完整版的没同步么 我自己再看看

**Comment by redwolf1996** [comment]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/9690393/57996378-a4181d80-7af9-11e9-92bf-7d13c5c8c00c.png">
可以了 原因是自己加了个组件 没放到 el-scrollbar里 导致的问题

**Comment by SuperZiLu** [comment]
我也是出现这种情况 感谢大佬们的问题 解决了。
