### ISSUE TITLE
请问一下，在methods里图片路径找不到的问题

### ISSUE THREAD

**Issue by songzhikui** [PanJiaChen/vue-element-admin#211]
`function getImg() {
	                if (arr[i].FLAG === 'RUN') {
	                    return './../../assets/monitor_images/car1.png';
	                } else if (arr[i].FLAG === 'STOP') {
	                    return './../../assets/monitor_images/car2.png';
	                } else if (arr[i].FLAG === 'OFF') {
	                    return './../../assets/monitor_images/car3.png';
	                }
	            }`

报错
GET http://localhost:9527/assets/monitor_images/car3.png 404 (Not Found)
GET http://localhost:9527/assets/monitor_images/car2.png 404 (Not Found)
GET http://localhost:9527/assets/monitor_images/car1.png 404 (Not Found)

**Comment by PanJiaChen** [comment]
这是图片资源问题了，你都没引入这个图片资源 怎么会有？

**Comment by songzhikui** [comment]
@PanJiaChen  但是我把这几张图片放到static目录下 是可以找到的，是不是需要在哪里配置一下？

**Comment by PanJiaChen** [comment]
建议看https://vue-loader.vuejs.org/zh-cn/configurations/asset-url.html
