### ISSUE TITLE
tinymce 数据绑定问题

### ISSUE THREAD

**Issue by KouYidong** [PanJiaChen/vue-element-admin#2111]
## Question（提问）
在 element-ui 中的 dialog 中使用 tinymce, 新增时对 tinymce 输入内容并保存，
保存 tinymce 之后对其进行编辑，光标进入之后点击取消（并未保存，只是关闭 dialog）。
此时再次点击其他数据，tinymce 中的数据都是第一次的数据，其值并不会改变。
通过 watch 看到是对 tinymce 进行了两次赋值，第一次赋值赋的是正确的值，第二次赋值赋的是错误的值，导致显示的是错误的值。
提问：
想知道 dalao 有没有遇到过这种问题（保存之后进行编辑会对其进行赋值两次），提供一下思路。谢谢

**Comment by PanJiaChen** [comment]
文档写了
awesome-comment (https://github.com/Blankj/awesome-comment) 里面收集了很多有趣的代码注释

**Comment by KouYidong** [comment]
文档看过了，一直提示没有 setContent() 这个方法，我再去看看这个方法，多谢大佬
