### ISSUE TITLE
关于tinymcel离线问题

### ISSUE THREAD

**Issue by Royal0302** [PanJiaChen/vue-element-admin#2112]
您好，tinymcel 富文本编辑器是在index.html页面通过https://cdn.jsdelivr.net/npm/tinymce-all-in-one@4.9.3/tinymce.min.js的方式来加载，如果要是在离线环境，需要如何配置tinymce.js？我试过拉取cdn上的JS文件然后通过src的方式引用，但是会一直报错？请问有什么好的解决办法吗？
![1558345127(1)](https://user-images.githubusercontent.com/28776154/58012053-2ae2ef80-7b26-11e9-97be-34b9ef8113f2.jpg)
![TIM截图20190520174059](https://user-images.githubusercontent.com/28776154/58012168-75fd0280-7b26-11e9-8a18-4b4e5925f923.png)
![TIM截图20190520174047](https://user-images.githubusercontent.com/28776154/58012176-7ac1b680-7b26-11e9-8764-08a883c9ecc1.png)

**Comment by PanJiaChen** [comment]
静态资源怎么离线？

**Comment by Royal0302** [comment]
就是在内网环境，不能通过cdn的方式拉取js,想着能不能将js放在项目内，然后引用进去。试了下发现还是不行┗( T﹏T )┛

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/releases/tag/4.0.1

这个版本的富文本没使用cdn。

https://github.com/PanJiaChen/vue-element-admin/pull/1996

**Comment by Royal0302** [comment]
好的，多谢(❤ ω ❤)
