### ISSUE TITLE
首页图表宽度错误导致样式错乱

### ISSUE THREAD

**Issue by a1029382825** [PanJiaChen/vue-element-admin#2116]
## Bug report（问题描述）
首页图表宽度错误导致样式错乱

#### Steps to reproduce（问题复现步骤）
1. 登陆vue-element-admin到首页
2. 点击左侧菜单跳转到任意页面
3. 按f12或邮件点击检查按钮
4. 关闭控制台
5. 点击左侧菜单返回首页

#### Other relevant information（格外信息）
- Your OS: MacOS 10.14.5
- Node.js version: 10.15.3
- vue-element-admin version: 4.2.0
- Browser version: Chrome 74.0.3729.157

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/2119
