### ISSUE TITLE
sockjs.js:1683 WebSocket connection to 'ws://localhost:9527/sockjs-node/717/a2osh2ln/websocket' failed: Invalid frame header

### ISSUE THREAD

**Issue by loverto** [PanJiaChen/vue-element-admin#2118]
#### Other relevant information（格外信息）
- Your OS:  macos
- Node.js version: 10.x
- vue-element-admin version: 4.1

**Comment by PanJiaChen** [comment]
https://github.com/vuejs/vue-cli/issues/1850
