### ISSUE TITLE
build:sit 打包配置会有问题

### ISSUE THREAD

**Issue by zmami0523** [PanJiaChen/vue-element-admin#212]
npm run build:sit 的情况下
因为NODE_ENV=sit，后续很多需要判断===production的地方都会问题的吧

**Comment by PanJiaChen** [comment]
不是很了解你的需求

**Comment by zmami0523** [comment]
`  "scripts": {
    "build:sit": "cross-env NODE_ENV=sit node build/build.js",
  },`

vue-element-admin/build/utils.js
`exports.assetsPath = function (_path) {
  var assetsSubDirectory = process.env.NODE_ENV === 'production'
    ? config.build.assetsSubDirectory
    : config.dev.assetsSubDirectory
  return path.posix.join(assetsSubDirectory, _path)
}

exports.cssLoaders = function (options) {
  options = options || {}

  var cssLoader = {
    loader: 'css-loader',
    options: {
      minimize: process.env.NODE_ENV === 'production',
      sourceMap: options.sourceMap
    }
  }`

vue-element-admin/build/vue-loader.conf.js
`var isProduction = process.env.NODE_ENV === 'production'

module.exports = {
    loaders: utils.cssLoaders({
        sourceMap: isProduction
            ? config.build.productionSourceMap
            : config.dev.cssSourceMap,
        extract: isProduction
    })
}`

**Comment by PanJiaChen** [comment]
@zmami0523 
https://github.com/PanJiaChen/vue-element-admin/pull/233 
现加入一个 `env-config` 变量来区分
