### ISSUE TITLE
vue-element-admin与vue-admin-template在Navbar上的dropdown-menu位置不一样。通过修改right-menu的line-height解决。

### ISSUE THREAD

**Issue by nelsonxuan** [PanJiaChen/vue-element-admin#2121]
## Question（提问）
在Navbar上点击avatar后弹出的dropdown-menu的element.style中top设置不一样，导致在vue-admin-template中会出现偏下效果。（在vue-admin-template中为65px，在vue-element-admin为50px）

请问下什么原因以及如何将vue-admin-template中的top也设置为50px。

留意到vue-element-admin的element-ui版本为2.7.0，template的为2.7.2，不过将template的element-ui版本改为2.7.0后还是不行。

**Comment by nelsonxuan** [comment]
已解决，通过修改right-menu的line-height

**Comment by t60wl** [comment]
> 已解决，通过修改right-menu的line-height

根本不需要去修改它的CSS，直接在Navbar上 <el-dropdown class="avatar-container right-menu-item hover-effect" trigger="click"> 加上right-menu-item hover-effect 两个样式就好了

没添加样式前效果
![image](https://user-images.githubusercontent.com/7663478/228450016-f5105cd6-5d85-4174-889a-c2acc3276594.png)

添加样式后效果：
![image](https://user-images.githubusercontent.com/7663478/228449772-e483dd77-62ae-40a0-96ee-69cc8d4ea0cd.png)
