### ISSUE TITLE
switch开关在table中点击切换 滞后问题

### ISSUE THREAD

**Issue by redwolf1996** [PanJiaChen/vue-element-admin#2125]
小弟在用element ui的switch组件 将它放到表格中后 点击的时候没有发生切换，要等鼠标离开它所在的那一行才发生改变 这是怎么回事

![image](https://user-images.githubusercontent.com/9690393/58160566-4dedda80-7cb1-11e9-9862-c9079307ba72.png)

**Comment by PanJiaChen** [comment]
请学会提问。使用issue模板。
