### ISSUE TITLE
table中的switch开关组件切换滞后于table行的hover事件

### ISSUE THREAD

**Issue by redwolf1996** [PanJiaChen/vue-element-admin#2126]
## Bug report（问题描述）
如题在table中放入switch组件，点击后不能立刻切换状态，要等到鼠标离开那一行，才会切换

#### Steps to reproduce（问题复现步骤）

1. 点击switch按钮
2. 没有立马切换
3. 鼠标离开switch开关的表格那一行才切换成功

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/9690393/58166797-2bfa5500-7cbd-11e9-91ae-0264d9ff8070.png)
![image](https://user-images.githubusercontent.com/9690393/58166814-31f03600-7cbd-11e9-8383-24d36a627f2a.png)

#### Link to minimal reproduction（最小可在线还原demo）
下面是codeopen里的demo，但出现的一个很奇葩的问题，就是点击witch按钮后，离开表格还是不切换，要点codeopen下面的console控制台才发生改变，跟我实际情况有所不一样，麻烦大神给小弟看下，可能想到的是事件切换顺序问题或者css问题？但是封装在组件里，本人不知道从何下手了 ：(  

https://codepen.io/syx9527/pen/gJoPdd?editors=1111

#### Other relevant information（格外信息）
- Your OS: macOS 10.13
- Node.js version: 11.14.0
- vue-element-admin version: 4.2.0

**Comment by PanJiaChen** [comment]
https://codepen.io/anon/pen/arEZLr

**Comment by redwolf1996** [comment]
> https://codepen.io/anon/pen/arEZLr

感谢 大兄弟
