### ISSUE TITLE
菜单栏反复切换导致浏览器内存占用增加

### ISSUE THREAD

**Issue by QMZhao** [PanJiaChen/vue-element-admin#2129]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
使用了 `TagsView`，就会依赖 `keep-alive`，这样打开的页面越多，占用的内存就会越多。

你可以关闭`TagsView`再试试。

**Comment by QMZhao** [comment]
谢谢回答，我按照这个方法试试
