### ISSUE TITLE
菜单栏反复切换导致浏览器内存占用空间增加

### ISSUE THREAD

**Issue by QMZhao** [PanJiaChen/vue-element-admin#2130]
#### Steps to reproduce（问题复现步骤）
1.我从“动态 Table” 挨个点击到“文章列表”
2.反复执行该操作30分钟
3.内存占用空间增加且无法释放

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/35327942/58226790-ce1c4a80-7d5a-11e9-859f-1c907549f0c5.png)
![image](https://user-images.githubusercontent.com/35327942/58226837-06bc2400-7d5b-11e9-912b-c270ebaae34a.png)

**Comment by PanJiaChen** [comment]
你为什么要反复创建issue。。。
https://github.com/PanJiaChen/vue-element-admin/issues/2129

**Comment by QMZhao** [comment]
网络卡了(捂脸.)

**Comment by wzch333** [comment]
> 你为什么要反复创建issue。。。
> #2129

不关闭tagview有解决办法吗 现实业务场景中 有用到keepalive

另外关闭标签页为何内存不能及时释放??
