### ISSUE TITLE
右侧窗体内容动态更换

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#2132]
## Feature request（新功能建议）

大神能提供个例子动态切换右边setting框内容吗？

**Comment by PanJiaChen** [comment]
不懂你想要什么效果。

**Comment by moonose** [comment]
目前 rightpanel里是用的 settings 页面，我的想法是能不能也改成动态路由形式，当app-main内容页面需要rightpanel显示什么，就能显示自定义的页面，这样rightpanel能充分利用起来。另外在 src\components\RightPanel\index.vue 页面里，可以加个变量 <div :class="isMaskOthers ? 'rightPanel-background' : ''" /> 用来判断rightpanel显示时是否要遮蔽其他区域。不知道这样的想法是否合适。谢谢大神。

**Comment by PanJiaChen** [comment]
遮罩的问题可以加一个参数，
动态的问题，自己实现就好了。
