### ISSUE TITLE
访问Network地址，浏览器报sockjs-node连接localhost地址

### ISSUE THREAD

**Issue by huangyus** [PanJiaChen/vue-element-admin#2135]
## Bug report（问题描述）
访问Network地址，浏览器报sockjs-node连接localhost地址

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/45846300/58239131-177c9200-7d7b-11e9-96ab-1ae1fb75bae3.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
https://segmentfault.com/q/1010000005045512
