### ISSUE TITLE
安装成功后启动 登录页一直报500

### ISSUE THREAD

**Issue by liuguangsen0409** [PanJiaChen/vue-element-admin#2138]
点击登录时 调用这个接口 http://localhost:9527/dev-api/user/login 然后 控制台 说 Proxy error: Could not proxy request /user/login from localhost:9527 to http://localhost:9527/mock (ECONNREFUSED). 请问这个怎么解决

**Comment by PanJiaChen** [comment]
请按照issue模板提问。
