### ISSUE TITLE
运行项目 点击登录 报500

### ISSUE THREAD

**Issue by liuguangsen0409** [PanJiaChen/vue-element-admin#2139]
## Question（提问）

使用 yarn install 安装 运行 yarn run dev

可以调到 登录页 输入用户名密码 点击登录 控制台 显示 Proxy error: Could not proxy request /user/login from localhost:9527 to http://localhost:9527/mock.

问下 怎么解决 谢谢

**Comment by liuguangsen0409** [comment]
我也没有设置什么呀 别人都可以 跑起来吗？

**Comment by liuguangsen0409** [comment]
麻烦 花裤衩大大 看到回下啊 查不到相关内容

**Comment by liuguangsen0409** [comment]
会不会跟 host 有关？我这边的 host 如下 
![image](https://user-images.githubusercontent.com/22491714/58313219-9c30e400-7e3f-11e9-800e-010ec4509ff0.png)

**Comment by PokerTiger** [comment]
怎么解决的？

**Comment by liuguangsen0409** [comment]
> 怎么解决的？

还没有解决呀

**Comment by PokerTiger** [comment]
怪了 前几天跑这个好好地 今天回来弄 和你出了一样的问题

**Comment by liuguangsen0409** [comment]
> 怪了 前几天跑这个好好地 今天回来弄 和你出了一样的问题

我让几个 同事 也试了试 他们 都没问题的

**Comment by PokerTiger** [comment]
> > 怪了 前几天跑这个好好地 今天回来弄 和你出了一样的问题
> 
> 我让几个 同事 也试了试 他们 都没问题的

好像是localhost的问题，我把vue.config.js中代理的target值改成了Adress对应的地址，现在好了。

**Comment by PokerTiger** [comment]
> > 怪了 前几天跑这个好好地 今天回来弄 和你出了一样的问题
> 
> 我让几个 同事 也试了试 他们 都没问题的

你也改成127.0.0.1这个看看 localhost对于的地址

**Comment by liuguangsen0409** [comment]
> > > 怪了 前几天跑这个好好地 今天回来弄 和你出了一样的问题
> > 
> > 
> > 我让几个 同事 也试了试 他们 都没问题的
> 
> 你也把“localhost”改成“127.0.0.1”这个看看

果然可以 老铁很赞 我之前也尝试过 改成 127.0.0.1 但是 好像忘记重启了

**Comment by PanJiaChen** [comment]
的确没考虑到会改 `localhost`的情况。我优化一下吧。

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/2142

**Comment by shuizhongmose** [comment]
现在config中是127.0.0.1然后还是localhost。
环境：阿里云 centos 7.6 server， 通过vnc viewer 访问 http://localhost:14688/还是报proxy error的错误。
config下proxy的配置如下：
```
proxy: {
      // change xxx-api/login => mock/login
      // detail: https://cli.vuejs.org/config/#devserver-proxy
      [process.env.VUE_APP_BASE_API]: {
        target: `http://127.0.0.1:${port}/mock`,
        changeOrigin: true,
        pathRewrite: {
          ['^' + process.env.VUE_APP_BASE_API]: ''
        }
      }
    }
```
报错如下：
···
Proxy error: Could not proxy request /user/login from 127.0.0.1:14688 to http://127.0.0.1:9527/mock.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
···
