### ISSUE TITLE
跨域配置问题

### ISSUE THREAD

**Issue by Danbaoshan** [PanJiaChen/vue-element-admin#214]
请问大神，跨域怎么配置啊，下面是我自己配置，但是老是不对，proxyTable:
`'/api': {
        target: 'http://127.0.0.1:8888/api',
        changeOrigin:true,
        pathRewrite: {
          '^api':''
        }
      }`
然后请求的时候,请求不到。

**Comment by PanJiaChen** [comment]
建议参考： https://segmentfault.com/q/1010000007337440
http://www.jianshu.com/p/95b2caf7e0da
和官方文档：https://github.com/chimurai/http-proxy-middleware

**Comment by Danbaoshan** [comment]
感谢指导，问题已发现，拦截器 因为没有token 所以拦截了，一直请求不到，又有一个问题，axios 拦截器 怎么设置  不拦截指定的请求地址（如登录和注册），还是 只能重新创建新的 axios 实例？

**Comment by PanJiaChen** [comment]
公用一个实例做特殊判断或者创建一个新的实例都是可行的方法
