### ISSUE TITLE
vue-count-to无法使用

### ISSUE THREAD

**Issue by OGweixin007** [PanJiaChen/vue-element-admin#2140]
npm install vue-count-to

npm ERR! path D:\vue\github_projects\vue-admin-template-master\node_modules\chalk\node_modules\has-ansi
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access 'D:\vue\github_projects\vue-admin-template-master\node_modules\chalk\node_modules\has-ansi'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2019-05-24T09_18_26_152Z-debug.log

**Comment by PanJiaChen** [comment]
https://segmentfault.com/q/1010000008554921
