### ISSUE TITLE
使用CDN引入element-ui后，提示These dependencies were not found

### ISSUE THREAD

**Issue by lijiasen** [PanJiaChen/vue-element-admin#2141]
提示内容如下：
`
These dependencies were not found:

* element-ui/lib/locale/lang/en in ./src/lang/index.js
* element-ui/lib/locale/lang/zh-CN in ./src/lang/index.js
* element-ui/package.json in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??v
ue-loader-options!./src/components/ThemePicker/index.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save element-ui/lib/locale/lang/en element-ui/lib/locale/lang/zh-CN element-ui/package.json
`

疑问：这个是国际化文件里的引用了element-ui的文件，请问如何解决

**Comment by PanJiaChen** [comment]
你还是要 `npm install element-ui -save`的。
详细看[文档](https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/cdn.html#%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F)
