### ISSUE TITLE
富文本编辑器问题4.2.0 init multiple tinymce at the same time

### ISSUE THREAD

**Issue by secretFED** [PanJiaChen/vue-element-admin#2144]
4.2.0 这一版，改了富文本编辑器。在一个页面的两个tab里调用会报错 。
Error in mounted hook: "TypeError: Cannot read property 'init' of undefined"

**Comment by secretFED** [comment]
应该是引用cdn那个js文件处

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/2152

**Comment by shanguoteng** [comment]
使用富文本上传视频。无法正常显示视频，而是显示成图片。

**Comment by lichunlei1225** [comment]
cdn 如何使用中文呢

**Comment by tb3706666** [comment]
> cdn 如何使用中文呢

可以参考：http://tinymce.ax-z.cn/general/localize-your-language.php
然后对应配置
