### ISSUE TITLE
history模式 地址回车  beforeEach 监听不到

### ISSUE THREAD

**Issue by sishen2** [PanJiaChen/vue-element-admin#2145]
## Question（提问）

 我是参照源码从头学习搭建学习的，采用的是history模式，在一级目录下，比如/about，在地址树输入，可以显示，但是要是二级旧显示不出来 ，一片空白，查看了下router beforeEach  也都没监听到，还有要是随便输入地址，也无法跳到404  我路由最后是有加* 跳到404的 ，一级到时会 比如 /abccccc  请问大大 ，这是什么原因呢
![1558801700(1)](https://user-images.githubusercontent.com/16297734/58372226-2f0b7480-7f4d-11e9-8d1b-68de0b4629a2.jpg)

**Comment by sishen2** [comment]
还有 地址输入 /about 有内容   ，输入 /about/index 一片空白

**Comment by PanJiaChen** [comment]
这和history模式没有关系。
如果你觉得有问题，请提供一个可复现你问题的步骤或者demo。
