### ISSUE TITLE
ElementUI 按需引入,loading,message等组件引入失败

### ISSUE THREAD

**Issue by DengRiGuang** [PanJiaChen/vue-element-admin#2156]
## Bug report（问题描述）
我用vue-cli3.7.0 按需导入配置element是可以的,修改vue配置文件后,loading无法导入
#### Steps to reproduce（问题复现步骤）

1. 加了vue.config.js文件后导入失败

#### Link to minimal reproduction（最小可在线还原demo）
[https://tx8lc.codesandbox.io/](url)

#### Other relevant information（格外信息）
- Your OS:window10
- Node.js version:10.15.3
- vue-element-admin version:4.0

**Comment by PanJiaChen** [comment]
试了下没有什么问题

**Comment by DengRiGuang** [comment]
不好意思，现在才回复，是这样的，我只要一打开vue.config.js中注释的after: require('./mock/mock-server.js')运行就报(function (exports, require, module, __filename, __dirname) { import "core-js/modules/es6.regexp.constructor";
复现链接:[https://codesandbox.io/embed/github/DengRiGuang/element-demand/tree/master/](url)

**Comment by DengRiGuang** [comment]
@PanJiaChen
