### ISSUE TITLE
富文本编辑器是英文

### ISSUE THREAD

**Issue by secretFED** [PanJiaChen/vue-element-admin#2157]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by secretFED** [comment]
我看之前的代码，在富文本里还取了language.但新版本，在data里定义了languageTypeList，完全没有用到啊，导致默认就是英文版

**Comment by GuanLola** [comment]
Tinymce/index.vue文件中
![image](https://user-images.githubusercontent.com/37822389/64915718-337bc780-d7a0-11e9-9b6e-b3c0e1f730f8.png)
改成“zh”即可
