### ISSUE TITLE
富文本编辑器英文显示

### ISSUE THREAD

**Issue by secretFED** [PanJiaChen/vue-element-admin#2158]
我看之前的代码，在index里还定义了Language,但新版本在data里定义了languageTypeList，完全没有用到啊，导致默认是英文显示

**Comment by PanJiaChen** [comment]
请使用i18n分支

**Comment by secretFED** [comment]
我自己本地改了，在初始化的时候定义了zh_CN

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/2159

我在master分支也加了language选项
