### ISSUE TITLE
ECharts部分图表的title等组件不能设置颜色问题

### ISSUE THREAD

**Issue by shandafu** [PanJiaChen/vue-element-admin#216]
问题描述：如题。
（1）线上demo首页，地址 http://panjiachen.github.io/vue-element-admin/#/dashboard ，
title设置生效，显示正确：WEEKLY WRITE ARTICLES 为蓝色；
（2）git clone代码（master及2.2.0发行版）运行后，设置title颜色不生效：WEEKLY WRITE ARTICLES 为黑色；
（3）生成仪表盘（参见 http://echarts.baidu.com/demo.html#gauge-car-dark ），
title及axisLabel颜色设置不生效。

**Comment by PanJiaChen** [comment]
是否能提供更佳完整的问题描述？

**Comment by shandafu** [comment]
目前发现的情况是，所有图表title的颜色设置不能生效，只显示默认的黑色，谢谢。

**Comment by PanJiaChen** [comment]
并不能重现你的问题

**Comment by shandafu** [comment]
请问http://panjiachen.github.io/vue-element-admin/#/dashboard使用的是哪个版本？

**Comment by shandafu** [comment]
最新master分支，title为黑色


线上demohttp://panjiachen.github.io/vue-element-admin/#/dashboard <http://panjiachen.github.io/vue-element-admin/#/dashboard>
title为蓝色

**Comment by PanJiaChen** [comment]
没懂什么意思，我的项目中使用了echarts macarons 这个theme 而已，其它的就是echarts本身的东西，并没有做什么特殊的处理

**Comment by shandafu** [comment]
不好意思，我想问的是http://panjiachen.github.io/vue-element-admin/ 使用的vue-element-admin的版本？因为vue-element-admin最新的master本地发布后 http://localhost:9527/#/dashboard 的图表与线上Demo http://panjiachen.github.io/vue-element-admin/#/dashboard 中的图表显示不一致，谢谢关注。

**Comment by PanJiaChen** [comment]
是的同一个版本，而且我这里并没有什么问题

**Comment by PanJiaChen** [comment]
暂时先关闭
