### ISSUE TITLE
4.2.0版本install报错

### ISSUE THREAD

**Issue by chenhao19931008** [PanJiaChen/vue-element-admin#2163]
## Question（提问）

1.使用4.2.0版本npm install 后提示This project has been renamed to 'tasksfile'
2.按照提示npm install tasksfile后，npm run dev报错

#### Steps to reproduce（问题复现步骤）
1.npm install
2.npm install tasksfile
3.npm run dev

#### Screenshot or Gif（截图或动态图）

![QQ截图20190527172526](https://user-images.githubusercontent.com/26437527/58410498-e36bde80-80a4-11e9-8fd6-430c0eba0367.png)
![QQ截图20190527173116](https://user-images.githubusercontent.com/26437527/58410600-0f875f80-80a5-11e9-8432-6a9fada8fca5.png)
![QQ截图20190527173210](https://user-images.githubusercontent.com/26437527/58410648-25952000-80a5-11e9-8431-c8f45c0cc94f.png)

#### Other relevant information（格外信息）
- Your OS:win10
- Node.js version:10.15.1
- vue-element-admin version:4.2.0

**Comment by PanJiaChen** [comment]
https://segmentfault.com/a/1190000015646531
