### ISSUE TITLE
标签栏导航会重复

### ISSUE THREAD

**Issue by shimh-develop** [PanJiaChen/vue-element-admin#2171]
## Bug report（问题描述）
使用vue-router 的path缺省配置会出现2个相同的标签栏导航，2个相同的标签栏导航的path是不一样的。
#### Steps to reproduce（问题复现步骤）
比如：1 修改一下guide的路由配置为：
![image](https://user-images.githubusercontent.com/22723262/58459637-6c931c00-815e-11e9-8d18-ddd4bba84535.png)
以前的路由是：
![image](https://user-images.githubusercontent.com/22723262/58459699-95b3ac80-815e-11e9-8d31-92c4242f8edd.png)
2 点击guide菜单，此时url路径是这样的：
![image](https://user-images.githubusercontent.com/22723262/58459973-35713a80-815f-11e9-99a4-af633edff071.png)
3 随便点击一个菜单，guide为倒数第二个：
![image](https://user-images.githubusercontent.com/22723262/58460065-6b162380-815f-11e9-96d8-f2f31398f6f5.png)
4 关闭最后一个：此时guide的url路径多了一条 /
![image](https://user-images.githubusercontent.com/22723262/58460129-8d0fa600-815f-11e9-85d0-717f3e16be72.png)
5 此时，点击一个别的菜单，再点击guide菜单，就会出现2个相同的tag了
![image](https://user-images.githubusercontent.com/22723262/58460358-11622900-8160-11e9-84c9-710d6e49dd13.png)

#### Other relevant information（格外信息）
- Your OS: Mac
- Node.js version: v8.10.0
- vue-element-admin version: master

**Comment by sscfaith** [comment]
修改 src/layout/components/TagsView/index.vue  158行

**Comment by sscfaith** [comment]
修改 src/layout/components/TagsView/index.vue 158行
this.$router.push(latestView) =>  this.$router.push(latestView.path)

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/2634
