### ISSUE TITLE
eslint无法检测语法错误，保存时无法自动修复错误

### ISSUE THREAD

**Issue by ChaseChan** [PanJiaChen/vue-element-admin#2174]
#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/31701489/58523466-1c1bcd00-81f7-11e9-9134-50642498bd74.png)

![image](https://user-images.githubusercontent.com/31701489/58523481-28078f00-81f7-11e9-9e5e-067eeb78f48a.png)

![image](https://user-images.githubusercontent.com/31701489/58523563-69983a00-81f7-11e9-9f8f-3116f33deb92.png)

![image](https://user-images.githubusercontent.com/31701489/58523618-b419b680-81f7-11e9-8557-31a6af6ca5a3.png)

#### Other relevant information（格外信息）
- Your OS: MAC
- Node.js version: 10.10.0
- vue-element-admin version: 4.x

**Comment by PanJiaChen** [comment]
请参照文档或者其他文章。

**Comment by ChaseChan** [comment]
@PanJiaChen 就是按照文档来的。。。
