### ISSUE TITLE
Where is the database placed?

### ISSUE THREAD

**Issue by vonsogt** [PanJiaChen/vue-element-admin#2176]
## Question（提问）
So, i wanna input query or post how it working? someone can explain how to use the database like mysql

#### Other relevant information（格外信息）
- Your OS: Windows 10
- Node.js version: v8.16.0
- vue-element-admin version: 4.2.1

**Comment by PanJiaChen** [comment]
This is a pure front-end project.

All data is mocked by `MockJs`.

**Comment by EdwinBetanc0urt** [comment]
@vonsogt We work with an api using grpc to exchange data to the backend:
https://github.com/erpcya/adempiere-vue
https://github.com/EdwinBetanc0urt/adempiere-vue

**Comment by vonsogt** [comment]
> @vonsogt We work with an api using grpc to exchange data to the backend:
> https://github.com/erpcya/adempiere-vue
> https://github.com/EdwinBetanc0urt/adempiere-vue

I just run the project that you said, and I things I need to read & learn the code where the server code placed. But if you have tutorial links, it would be better
