### ISSUE TITLE
属性写错了

### ISSUE THREAD

**Issue by mgbq** [PanJiaChen/vue-element-admin#2177]
具体代码地址  https://github.com/PanJiaChen/vue-element-admin/blob/cd30d254590e267cea5066305ae132dfaa47356c/src/views/login/index.vue#L20 

element-ui文档是： autocomplete	原生属性，自动补全，
大大写的是auto-complete，

element-ui 文档地址 https://element.eleme.cn/#/zh-CN/component/input#autocomplete-attributes

**Comment by PanJiaChen** [comment]
恩，的确要改一下。
欢迎pr。
