### ISSUE TITLE
从git上下的源码运行后是英文的

### ISSUE THREAD

**Issue by 897633560** [PanJiaChen/vue-element-admin#2181]
从git上下的源码运行后是英文的，有没有中文版本的，谢谢大家

**Comment by SwordSealCity** [comment]
下载分支：https://github.com/PanJiaChen/vue-element-admin/tree/i18n

**Comment by 897633560** [comment]
![image](https://user-images.githubusercontent.com/44360117/58678571-c1b77380-8392-11e9-9215-0bd02e776740.png)更改系统布局配置中的主题色后，没效果一直显示这个页面。
