### ISSUE TITLE
再次提问，重写api之后，已从后台拿到返回值了，但是页面跳转无反应是什么原因呢？？

### ISSUE THREAD

**Issue by whatkind** [PanJiaChen/vue-element-admin#2182]
![image](https://user-images.githubusercontent.com/35456622/58633903-6fd40680-831c-11e9-8abf-9ffa90874841.png)

** api/login
![image](https://user-images.githubusercontent.com/35456622/58633963-9a25c400-831c-11e9-999e-245ce3ad809d.png)

route index没有改变

## 不是很懂vue，困扰好几天了，心很累

![image](https://user-images.githubusercontent.com/35456622/58634231-51bad600-831d-11e9-9ac0-2a00d720224e.png)

点击登陆后，浏览器地址栏的效果

后来我用`reject(error)`发现有个异常
![image](https://user-images.githubusercontent.com/35456622/58675197-ccb7d700-8385-11e9-83f3-e66deb531aad.png)

@PanJiaChen 作者能指导下吗？？非常感谢

**Comment by wmhello** [comment]
@whatkind 可以加我微信私聊（xpyzwm）   能帮到你  但我不是作者

**Comment by huzaifah-ivan** [comment]
hii @whatkind you should add proxy in vue.config.js file to use external API URL.
this is what i've done. let see we have api http://localhost:8080/base-api/api/v1/user-auth. the framework will catch exception if we add full url to hit api using axios (request). so i added proxy like this in vue.config.js:

```
proxy: {
      // change xxx-api/login => mock/login
      // detail: https://cli.vuejs.org/config/#devserver-proxy
      [process.env.VUE_APP_BASE_API+'/base-api']: {
        target: `http://localhost:8080`,
        changeOrigin: true,
        pathRewrite: {
          ['^' + process.env.VUE_APP_BASE_API]: ''
        }
      },
      [process.env.VUE_APP_BASE_API]: {
        target: `http://localhost:${port}/mock`,
        changeOrigin: true,
        pathRewrite: {
          ['^' + process.env.VUE_APP_BASE_API]: ''
        }
      }
    },

```

the proxy tell us, every url we hit with context /base-api will redirect to http://localhost:8080, not from mock (that framework provided).

and in our api.js we will add api like this

```
import request from '@/utils/request'

export function fetchData() {
  return request({
    url: '/base-api/api/v1/user-auth',
    method: 'get'
  })
}
```
and than, use our api as you want...

hope thats help you

**Comment by whatkind** [comment]
> want

thank for your help,I‘ll try it first!👍
