### ISSUE TITLE
font awesome 如何在侧边栏 icon 上引用 

### ISSUE THREAD

**Issue by masterchen** [PanJiaChen/vue-element-admin#2189]
font awesome图标我可以在其他页面使用并显示 ，我想把页面左侧边栏的图标也替换成fontawesome图标 比方说dashboad 对应的图标 替换成fa fa-user，需要怎么写 直接写显示不出来。
另外 我猜测是不是要在解析icon的地方做适配 如果是这样 请问在哪个文件？ 谢谢

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/layout/components/Sidebar/Item.vue
