### ISSUE TITLE
element-ui 选择框多选的时候会无限增高，怎么解决呢？或者有啥替代品？

### ISSUE THREAD

**Issue by dty1992** [PanJiaChen/vue-element-admin#219]
唉，element-ui多选的时候不能设置限制高度，让我好忧伤

**Comment by PanJiaChen** [comment]
首先你可以通过 css 覆盖 `element-ui` 的样式实现想要的效果，
其次我觉得这个交互挺合理的啊。

**Comment by dty1992** [comment]
唉，由于无限增高，导致布局不统一，和其他输入框\单选框等布局格格不入

那你没碰到这种情况吗？

**Comment by PanJiaChen** [comment]
有啊。。。但不增加高度 怎么搞？
无限增加宽度 或者内部滚动？ 其实都也没好很多
