### ISSUE TITLE
Element版本到了2.9.1

### ISSUE THREAD

**Issue by HelloZouYou** [PanJiaChen/vue-element-admin#2198]
### ElementUI官方版本目前到了2.9.1
目前使用vue-admin-template开发，项目中会使用级联选择器的多选功能，当前2.7.2中没有
请问若自行升级到最新会有冲突么

**Comment by simplast** [comment]
同问

**Comment by zhychao** [comment]
同问

**Comment by lemonCarlJ** [comment]
同问

**Comment by cashZhang27** [comment]
同问

**Comment by hqingx** [comment]
先卸载：npm uninstall element-ui
重新安装：npm install element-ui --save
然后把版本号改成对应的版本，最后重新编译
