### ISSUE TITLE
能否在点击删除按钮时增加popover

### ISSUE THREAD

**Issue by xsstc1** [PanJiaChen/vue-element-admin#22]
你好，请问在点击删除按钮的时候弹出[Popover](http://element.eleme.io/#/zh-CN/component/popover#qian-tao-cao-zuo)，然后再点击确定后再删除，这个可以加上吗，正在学习，自己做一直出错

**Comment by PanJiaChen** [comment]
简单给一个demo:https://jsfiddle.net/704g5bp0/2/
这些去element issue https://github.com/ElemeFE/element/issues
或者去https://gitter.im/ElemeFE/element 这里问啊
