### ISSUE TITLE
win10  以管理员身份运行npm  install  会报错

### ISSUE THREAD

**Issue by joseanluo** [PanJiaChen/vue-element-admin#220]
PS F:\Repository\GIT\github\vue-element-admin>  npm install --registry=https://registry.npm.taobao.org
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! path F:\Repository\GIT\github\vue-element-admin\node_modules\js-beautify\js\bin\css-beautify.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'F:\Repository\GIT\github\vue-element-admin\node_modules\js-beautify\js\bin\css-beautify.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JoseanLuo\AppData\Roaming\npm-cache\_logs\2017-09-18T15_55_25_285Z-debug.log

然后运行下面命令一样报错：

PS F:\Repository\GIT\github\vue-element-admin>  npm -g install js-beautify  --registry=https://registry.npm.taobao.org
npm ERR! path C:\Users\JoseanLuo\AppData\Roaming\npm\node_modules\js-beautify\js\bin\css-beautify.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\JoseanLuo\AppData\Roaming\npm\node_modules\js-beautify\js\bin\css-beautify.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JoseanLuo\AppData\Roaming\npm-cache\_logs\2017-09-18T15_56_02_502Z-debug.log
PS F:\Repository\GIT\github\vue-element-admin>

**Comment by rognoni** [comment]
Already closed here:
https://github.com/beautify-web/js-beautify/issues/1247

**Comment by PanJiaChen** [comment]
@rognoni is right 。
