### ISSUE TITLE
npm run dev 编译后，app.js 过大

### ISSUE THREAD

**Issue by handalin** [PanJiaChen/vue-element-admin#2207]
用的是 i18n 分支，npm run dev 之后，app.js 竟然达到了 16.1M 大小，这个有办法优化么？求

**Comment by luwzchn** [comment]
我现在 dev 之后已经39.42MB 还在堆功能预计还有堆20MB...每次改了调试都要等10秒。
用的 cheap-module-eval-source-map 模式，
如果用 cheap-source-map 会好些缩减到18MB，但是vue文件不能调试源码了，也痛苦。

**Comment by PanJiaChen** [comment]
https://juejin.im/post/5b56909a518825195f499806
https://juejin.im/post/5b5d6d6f6fb9a04fea58aabc

合理的拆包+gzip。
