### ISSUE TITLE
打包不能覆盖原来的dist文件夹，只能删除后再打包

### ISSUE THREAD

**Issue by PomL** [PanJiaChen/vue-element-admin#2211]
每次打包都要删掉原来的dist文件夹，不然就会报错，要怎么样才能覆盖dist文件夹打包，不然每次都要删除打包很不方便

**Comment by oyty** [comment]
不会啊，直接 npm run build:prod就可以了

**Comment by MeMeLeevv** [comment]
我也遇到这种情况了，他提示“Error: EBUSY: resource busy or locked, rmdir 'E:\lw\blog\MeMeLeevv.github.io\dist'”，然后我才发现我在build文件夹里打开了cmd...，关掉后便能重新覆盖打包了，你可以在vscode的终端运行命令行

**Comment by PanJiaChen** [comment]
默认是删除原来dist的，如果有问题，看看是不是自己文件权限的问题。
