### ISSUE TITLE
建议：icon命名改成英语好一点吧…拼音感觉有点格格不入

### ISSUE THREAD

**Issue by YiuTerran** [PanJiaChen/vue-element-admin#222]
感谢作者的分享，小小建议🙂

**Comment by PanJiaChen** [comment]
谢谢你的建议，主要是之前svg导出都是iconfont[](http://iconfont.cn/) 直接导出的，它都是通过拼音命名的。
我抽空改成英文吧

**Comment by PanJiaChen** [comment]
@YiuTerran 
v2.1.1 版本已将所有 icon-class 调整为英文
https://github.com/PanJiaChen/vue-element-admin/pull/227
