### ISSUE TITLE
关于国际化语言部分

### ISSUE THREAD

**Issue by huanglaofu** [PanJiaChen/vue-element-admin#2227]
2019年6月12日官方下载的admin为什么没有国际化语言选择界面，是不是我下载错了

**Comment by youngHcy** [comment]
我也感觉没中文

**Comment by dnsritch** [comment]
默认没有国际化了

**Comment by longmengyu** [comment]
不知道额，之前下载初始国际版一直开发在

**Comment by han1169** [comment]
![image](https://user-images.githubusercontent.com/13098352/59575334-98fee000-90ed-11e9-9cad-9c7881684e73.png)
git clone -b i18n https://github.com/PanJiaChen/vue-element-admin.git
这是国际版分支

**Comment by PanJiaChen** [comment]
下个大版本还是会改为 master 默认国家化。 在单独写一个不含国际化的分支版本。
