### ISSUE TITLE
next({ ...to, replace: true })死循环的问题（已解决）

### ISSUE THREAD

**Issue by wangshaojie** [PanJiaChen/vue-element-admin#2228]
#### Steps to reproduce（问题复现步骤）
我看过
[大神 我这个地方这么写怎么会死循环呢](https://github.com/PanJiaChen/vue-element-admin/blob/5070e20dea0ed659df20d2610d70ef8115d0cefd/src/permission.js#L40-L49)

1. const accessRoutes = await store.dispatch('permission/generateRoutes', userInfo.id) 我这里是用用户id取到权限表，权限表是个数组，就是拥有权限的页面如：['a','b']，然后权限表里的['a','b']跟asyncRoutes里的name对比，过滤出存拥有权限的路由，即 accessRoutes ，
但是当我router.addRoutes(accessRoutes) 
next({ ...to, replace: true }) 之后死循环了router.beforeEach
我改为next()的话，进去页面刷新后就是空白页了（异步添加的路由）
没找到原因，，，请教下

![image](https://user-images.githubusercontent.com/15683944/59338889-c8040300-8d35-11e9-8d5a-cc2e97430811.png)

![image](https://user-images.githubusercontent.com/15683944/59338958-e23de100-8d35-11e9-8417-4e5ce04a053f.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version: 3.7.1

**Comment by chenruir** [comment]
请问是怎么解决的呢

**Comment by whateveryoudo** [comment]
你好,我也是最近才看这个项目，感觉 next({...to})，再次进入了路由,重点是hasRoles是否为true,（确保addRouter完成）,如果一直为false了 就会一直 next({...to})，就死循环了，你要去检查下getInfo为什么未更新roles,这是我个人理解

**Comment by apgyapgy** [comment]
请问下你是怎么解决的？

**Comment by PanJiaChen** [comment]
自行在permission里面debug，最终一定要有`next()`作为终止，其它的`next(xxx)`都会再次进入`router.beforeEach`的。

**Comment by ghostcode** [comment]
`  
router.beforeEach(async(to, from, next) => {
  
  const accessRoutes = await store.dispatch('permission/generateRoutes', ['admin'])

  router.addRoutes(accessRoutes)

  next()

})`

这是我测试的代码，这样就死循环。

**Comment by 15560099568** [comment]
> 你好,我也是最近才看这个项目，感觉 next({...to})，再次进入了路由,重点是hasRoles是否为true,（确保addRouter完成）,如果一直为false了 就会一直 next({...to})，就死循环了，你要去检查下getInfo为什么未更新roles,这是我个人理解

可以通过hasRoutes的长度进行判断。
``
const hasRoutes = store.getters.permission_routes && store.getters.permission_routes.length > 0

  if (hasRoutes) {
          next()
    } else {
      await store.dispatch('user/getInfo') // 获取登录用户信息
      const accessRoutes = await store.dispatch('permission/generateRoutes', [])
      router.addRoutes(accessRoutes)
      next({ ...to, replace: true })
    }
``
这样就不会导致死循环

**Comment by gayshub** [comment]
> > 你好,我也是最近才看这个项目，感觉 next({...to})，再次进入了路由,重点是hasRoles是否为true,（确保addRouter完成）,如果一直为false了 就会一直 next({...to})，就死循环了，你要去检查下getInfo为什么未更新roles,这是我个人理解
> 
> 可以通过hasRoutes的长度进行判断。
> ``
> const hasRoutes = store.getters.permission_routes && store.getters.permission_routes.length > 0
> 
> if (hasRoutes) {
> next()
> } else {
> await store.dispatch('user/getInfo') // 获取登录用户信息
> const accessRoutes = await store.dispatch('permission/generateRoutes', [])
> router.addRoutes(accessRoutes)
> next({ ...to, replace: true })
> }
> ``
> 这样就不会导致死循环

It works
