### ISSUE TITLE
关于axios拦截的疑惑

### ISSUE THREAD

**Issue by 799535610** [PanJiaChen/vue-element-admin#223]
看了群主的拦截器代码

this.a()
this.b()
this.c()

假设axios时token非法， 那么会连续3次提示非法访问， 群主有何解决方法

**Comment by 799535610** [comment]
不会插入图片，不好意思

**Comment by 799535610** [comment]
`const res = response.data
    if (res.code !== 20000) {
      Message({
        message: res.data,
        type: 'error',
        duration: 5 * 1000
      })

      // 50008:非法的token; 50012:其他客户端登录了;  50014:Token 过期了;
      if (res.code === 50008 || res.code === 50012 || res.code === 50014) {
        MessageBox.confirm('你已被登出，可以取消继续留在该页面，或者重新登录', '确定登出', {
          confirmButtonText: '重新登录',
          cancelButtonText: '取消',
          type: 'warning'
        }).then(() => {
          store.dispatch('FedLogOut').then(() => {
            location.reload()// 为了重新实例化vue-router对象 避免bug
          })
        })
      }
      return Promise.reject('error')
    } else {
      return response.data
    }`

**Comment by PanJiaChen** [comment]
你可以在 message 弹出的时候把之前所有的 message 先 close 了 `this.$message.closeAll()`
demo：https://jsfiddle.net/api/post/library/pure/

**Comment by 799535610** [comment]
多谢，我试下
