### ISSUE TITLE
后端开启了允许跨域，vue-element-admin 还是提示跨域错误

### ISSUE THREAD

**Issue by sanxun0325** [PanJiaChen/vue-element-admin#2232]
我clone 项目后
1：创建了project.js 
![image](https://user-images.githubusercontent.com/28588342/59421402-20540700-8e01-11e9-965d-63934b7a2036.png):
2：在组件中发送请求
![image](https://user-images.githubusercontent.com/28588342/59421489-41b4f300-8e01-11e9-8ca6-eada480c34cb.png)
3：后端已经开启 允许cros，但是前端还是报错
![image](https://user-images.githubusercontent.com/28588342/59421542-598c7700-8e01-11e9-8de2-b9d6c6c312f8.png)
4:我用axios 原生的 访问后端 没有问题
![image](https://user-images.githubusercontent.com/28588342/59422148-783f3d80-8e02-11e9-98f3-f6b2ae609170.png)

**Comment by sanxun0325** [comment]
@PanJiaChen 大佬帮忙看一下呗、

**Comment by sanxun0325** [comment]
问题解决了，原因是  虽然后台开启了 允许跨域，但是由于在vue-element-admin 项目中 request.js 会传递一个X-Token ，所以后台需要在AllowHeaders 中增加X-TOKEN。增加完成后，即可正常访问
![image](https://user-images.githubusercontent.com/28588342/59477464-de21d880-8e87-11e9-9b02-639efc0e9d67.png)

**Comment by wangshiminhome** [comment]
我接收的是*，但是还是出现无法跨域的问题

**Comment by Xanthuim** [comment]
> 我接收的是*，但是还是出现无法跨域的问题

同样，什么鬼，心累

**Comment by zhufaming** [comment]
后台需要在AllowHeaders 中增加X-TOKEN  什么意思 java SSM
