### ISSUE TITLE
加个中文版行不行，

### ISSUE THREAD

**Issue by hongenge** [PanJiaChen/vue-element-admin#2233]

**Comment by sanxun0325** [comment]
有中文版，看官方文档。https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/i18n.html

**Comment by longmengyu** [comment]
每次更新都会有国际版，请下载国际版里面包含中文

**Comment by han1169** [comment]
![image](https://user-images.githubusercontent.com/13098352/59575284-5dfcac80-90ed-11e9-9590-e26455a2a1c6.png)
请先阅读readme,养成良好习惯

**Comment by hahadaba** [comment]
看了几个消失了，也没搞明白怎么弄成中文的。关于国际化的说明关键链接都是错的。

**Comment by zgh-yuanshang** [comment]
@hahadaba  你用 git clone 下来以后，使用下面命令，切换到 i18n
```
git checkout i18n
```

**Comment by hahadaba** [comment]
panjiajie大神能不能弄的浅显易懂一些啊？
国际化是不是多语言？我只想要中文。
关于国际化文档里的链接，这两个都是404：
https://github.com/PanJiaChen/vue-element-admin/tree/master/src/lang
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/lang/index.js

**Comment by ww-wangwei** [comment]
同！master是个英文版的。我也没有国际化需求，就是要个中文版本

**Comment by liunancun** [comment]
默认是英文版吧，切换中文版需要修改main.js的第7行
import locale from 'element-ui/lib/locale/lang/zh-CN' // lang i18n

**Comment by luchunhui2056** [comment]
master分支不再支持国际化，那么就应该只有一种语言，然后他们就设置为英文版，自然是不会有中文版的master分支，所以需要去 i18n分支，这里的国际版中有中文，（楼上的方法已经试过，除了切分支外，都失败了）

**Comment by PanJiaChen** [comment]
其实master分支，改一点文案就是中文了。
