### ISSUE TITLE
顶部tagView删除时，路由拦截后，路由未跳转，页签已经被删除

### ISSUE THREAD

**Issue by real-jacket** [PanJiaChen/vue-element-admin#2235]
## Question（提问）

页签关闭时，路由拦截引起的问题！

#### Steps to reproduce（问题复现步骤）
1. 从页签处关闭当前页面
2. 触发设置的弹窗操作，路由被拦截
3. 然后路由未跳转，停留在当前页面，但是页签已经被删除

#### Link to minimal reproduction（最小可在线还原demo）
代码上，一点击就直接先删除了页签，然后再进行的跳转

期待结果：
此时是否应该进行路由导航，在路由跳转后，根据路由状态来判断页签的关闭与否！

在github上查看最新的处理方式跟这个应该是一样的

![image](https://user-images.githubusercontent.com/36723264/59479472-bdf61780-8e8f-11e9-8ebb-cb458a0cbf27.png)

#### Other relevant information（格外信息）
- Your OS: windows10
- Node.js version: 
- vue-element-admin version:目前已经无法获知版本号，是没有使用vue-cli3的版本

**Comment by longmengyu** [comment]
每次更新都会有国际版，请下载国际版里面包含中文
