### ISSUE TITLE
现在的element-ui是用的2.7.0版本的吗？我升级到2.9版本会有问题吗？

### ISSUE THREAD

**Issue by zhychao** [PanJiaChen/vue-element-admin#2237]
现在的element-ui是用的2.7.0版本的吗？我升级到2.9版本会有问题吗？

**Comment by linmq** [comment]
Try it yourself, it doesn't take many time.

**Comment by PanJiaChen** [comment]
element-ui 没有breaking changes的话，不会有任何问题。
