### ISSUE TITLE
你好，请问下当头部固定时，el-select下拉列表挡住头部，如何处理？

### ISSUE THREAD

**Issue by yuanlee-hub** [PanJiaChen/vue-element-admin#2241]
## Bug report（问题描述）
当头部固定时，el-select下拉列表挡住头部

#### Steps to reproduce（问题复现步骤）
1.设置头部固定
2.展开el-select下拉列表
3.向下拖动`body`标签滚动条，即可复现

#### Screenshot or Gif（截图或动态图）
![vue-element-admin-el-select-层级问题](https://user-images.githubusercontent.com/7900338/59518840-24fbe680-8ef9-11e9-8c67-7154fedb62df.png)

#### Other relevant information（格外信息）
- Your OS:Windows 10
- Node.js version:10.14.1
- vue-element-admin version:4.2.1

**Comment by libaolei168** [comment]
请问解决了么
