### ISSUE TITLE
下载下来是英语，怎么切换到中文

### ISSUE THREAD

**Issue by jianggangsheng** [PanJiaChen/vue-element-admin#2244]

**Comment by longmengyu** [comment]
international-icon图标点击切换
如果没有的话，有可能你下载的不是国际版，切换不了

**Comment by han1169** [comment]
git clone -b  i18n   https://github.com/PanJiaChen/vue-element-admin.git
这是国际版分支

**Comment by ixi** [comment]
国际版分支也有一点不好的，就是很多内容得跑到i18nl里改，普通页面处理起来麻烦。如果明确没有多语言，还不如直接拿英文版自己自己改一下好
