### ISSUE TITLE
左侧导航栏无法收回的bug

### ISSUE THREAD

**Issue by dreamfinally** [PanJiaChen/vue-element-admin#2245]
左侧导航栏在收起情况下，多级导航菜单在弹出之后，点击其他地方无法收回

**Comment by dreamfinally** [comment]
![微信截图_20190617105724](https://user-images.githubusercontent.com/9589356/59575737-4cb49f80-90ef-11e9-8fe0-76e77b411698.png)

**Comment by dongsuo** [comment]
这个应该是 hover 效果，这个 bug 不能重现

**Comment by dreamfinally** [comment]
![bug](https://user-images.githubusercontent.com/9589356/60315083-ab9fd180-9997-11e9-9e80-8bd474f1c3d8.gif)

**Comment by dreamfinally** [comment]
@dongsuo 已上传gif图

**Comment by PanJiaChen** [comment]
已知问题，更新到最新版本 element-ui 就可以了。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/2004
