### ISSUE TITLE
用element的上传组件上传excel和用你写的有啥区别吗

### ISSUE THREAD

**Issue by zhangshuaigit123** [PanJiaChen/vue-element-admin#2253]
提问

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by loverto** [comment]
上传组件本身没什么区别的吧

**Comment by PanJiaChen** [comment]
任何轮子都是为特定需求而定制的。看你自己需求，选择用哪个。
