### ISSUE TITLE
3.11 版本 element-ui 升级到2.9 报错

### ISSUE THREAD

**Issue by toKnowMore** [PanJiaChen/vue-element-admin#2257]
本来是能运行的...
npm i element-ui -S

然后 npm run dev

Property or method "visible" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
warn @ vue.runtime.esm.js:587
warnNonPresent @ vue.runtime.esm.js:1872
get @ vue.runtime.esm.js:1914
mainvue_type_template_id_455b9f60_render @ element-ui.common.js:30096
Vue._render @ vue.runtime.esm.js:4540
updateComponent @ vue.runtime.esm.js:2784
get @ vue.runtime.esm.js:3138
Watcher @ vue.runtime.esm.js:3127
mountComponent @ vue.runtime.esm.js:2791
./node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount @ vue.runtime.esm.js:7995
Message @ element-ui.common.js:30317
main_Message.<computed> @ element-ui.common.js:30338
(anonymous) @ request.js:84
Promise.then (async)
request @ Axios.js:51
wrap @ bind.js:9
getUser @ login.js:26
(anonymous) @ user.js:92
F @ _export.js:36
GetUser @ user.js:91
wrappedActionHandler @ vuex.esm.js:704
dispatch @ vuex.esm.js:426
boundDispatch @ vuex.esm.js:332
(anonymous) @ permission.js:29
iterator @ vue-router.esm.js:1935
step @ vue-router.esm.js:1709
step @ vue-router.esm.js:1713
runQueue @ vue-router.esm.js:1717
confirmTransition @ vue-router.esm.js:1964
transitionTo @ vue-router.esm.js:1866
push @ vue-router.esm.js:2267
push @ vue-router.esm.js:2529
(anonymous) @ index.vue?9e05:123
Promise.then (async)
(anonymous) @ index.vue?9e05:121
(anonymous) @ element-ui.common.js:22801
(anonymous) @ element-ui.common.js:23319
complete @ index.js:89
(anonymous) @ index.js:225
next @ util.js:148
next @ util.js:116
cb @ index.js:173
required @ required.js:8
(anonymous) @ index.js:216
next @ util.js:114
asyncSerialArray @ util.js:120
(anonymous) @ util.js:154
asyncMap @ util.js:151
validate @ index.js:141
validate @ element-ui.common.js:23315
(anonymous) @ element-ui.common.js:22795
validate @ element-ui.common.js:22794
handleLogin @ index.vue?9e05:118
click @ index.vue?3ea5:138
invoker @ vue.runtime.esm.js:2023
fn._withTask.fn._withTask @ vue.runtime.esm.js:1822
vue.runtime.esm.js:587 [Vue warn]: Property or method "type" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
warn @ vue.runtime.esm.js:587
warnNonPresent @ vue.runtime.esm.js:1872
get @ vue.runtime.esm.js:1914
mainvue_type_template_id_455b9f60_render @ element-ui.common.js:30102
Vue._render @ vue.runtime.esm.js:4540
updateComponent @ vue.runtime.esm.js:2784
get @ vue.runtime.esm.js:3138
Watcher @ vue.runtime.esm.js:3127
mountComponent @ vue.runtime.esm.js:2791
./node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount @ vue.runtime.esm.js:7995
Message @ element-ui.common.js:30317
main_Message.<computed> @ element-ui.common.js:30338
(anonymous) @ request.js:84
Promise.then (async)
request @ Axios.js:51
wrap @ bind.js:9
getUser @ login.js:26
(anonymous) @ user.js:92
F @ _export.js:36
GetUser @ user.js:91
wrappedActionHandler @ vuex.esm.js:704
dispatch @ vuex.esm.js:426
boundDispatch @ vuex.esm.js:332
(anonymous) @ permission.js:29
iterator @ vue-router.esm.js:1935
step @ vue-router.esm.js:1709
step @ vue-router.esm.js:1713
runQueue @ vue-router.esm.js:1717
confirmTransition @ vue-router.esm.js:1964
transitionTo @ vue-router.esm.js:1866
push @ vue-router.esm.js:2267
push @ vue-router.esm.js:2529
(anonymous) @ index.vue?9e05:123
Promise.then (async)
(anonymous) @ index.vue?9e05:121
(anonymous) @ element-ui.common.js:22801
(anonymous) @ element-ui.common.js:23319
complete @ index.js:89
(anonymous) @ index.js:225
next @ util.js:148
next @ util.js:116
cb @ index.js:173
required @ required.js:8
(anonymous) @ index.js:216
next @ util.js:114
asyncSerialArray @ util.js:120
(anonymous) @ util.js:154
asyncMap @ util.js:151
validate @ index.js:141
validate @ element-ui.common.js:23315
(anonymous) @ element-ui.common.js:22795
validate @ element-ui.common.js:22794
handleLogin @ index.vue?9e05:118
click @ index.vue?3ea5:138
invoker @ vue.runtime.esm.js:2023
fn._withTask.fn._withTask @ vue.runtime.esm.js:1822
vue.runtime.esm.js:587 [Vue warn]: Property or method "center" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
warn @ vue.runtime.esm.js:587
warnNonPresent @ vue.runtime.esm.js:1872
get @ vue.runtime.esm.js:1914
mainvue_type_template_id_455b9f60_render @ element-ui.common.js:30103
Vue._render @ vue.runtime.esm.js:4540
updateComponent @ vue.runtime.esm.js:2784
get @ vue.runtime.esm.js:3138
Watcher @ vue.runtime.esm.js:3127
mountComponent @ vue.runtime.esm.js:2791
./node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount @ vue.runtime.esm.js:7995
Message @ element-ui.common.js:30317
main_Message.<computed> @ element-ui.common.js:30338
(anonymous) @ request.js:84
Promise.then (async)
request @ Axios.js:51
wrap @ bind.js:9
getUser @ login.js:26
(anonymous) @ user.js:92
F @ _export.js:36
GetUser @ user.js:91
wrappedActionHandler @ vuex.esm.js:704
dispatch @ vuex.esm.js:426
boundDispatch @ vuex.esm.js:332
(anonymous) @ permission.js:29
iterator @ vue-router.esm.js:1935
step @ vue-router.esm.js:1709
step @ vue-router.esm.js:1713
runQueue @ vue-router.esm.js:1717
confirmTransition @ vue-router.esm.js:1964
transitionTo @ vue-router.esm.js:1866
push @ vue-router.esm.js:2267
push @ vue-router.esm.js:2529
(anonymous) @ index.vue?9e05:123
Promise.then (async)
(anonymous) @ index.vue?9e05:121
(anonymous) @ element-ui.common.js:22801
(anonymous) @ element-ui.common.js:23319
complete @ index.js:89
(anonymous) @ index.js:225
next @ util.js:148
next @ util.js:116
cb @ index.js:173
required @ required.js:8
(anonymous) @ index.js:216
next @ util.js:114
asyncSerialArray @ util.js:120
(anonymous) @ util.js:154
asyncMap @ util.js:151
validate @ index.js:141
validate @ element-ui.common.js:23315
(anonymous) @ element-ui.common.js:22795
validate @ element-ui.common.js:22794
handleLogin @ index.vue?9e05:118
click @ index.vue?3ea5:138
invoker @ vue.runtime.esm.js:2023
fn._withTask.fn._withTask @ vue.runtime.esm.js:1822
vue.runtime.esm.js:587 [Vue warn]: Property or method "showClose" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
warn @ vue.runtime.esm.js:587
warnNonPresent @ vue.runtime.esm.js:1872
get @ vue.runtime.esm.js:1914
mainvue_type_template_id_455b9f60_render @ element-ui.common.js:30104
Vue._render @ vue.runtime.esm.js:4540
updateComponent @ vue.runtime.esm.js:2784
get @ vue.runtime.esm.js:3138
Watcher @ vue.runtime.esm.js:3127
mountComponent @ vue.runtime.esm.js:2791
./node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount @ vue.runtime.esm.js:7995
Message @ element-ui.common.js:30317
main_Message.<computed> @ element-ui.common.js:30338
(anonymous) @ request.js:84
Promise.then (async)
request @ Axios.js:51
wrap @ bind.js:9
getUser @ login.js:26
(anonymous) @ user.js:92
F @ _export.js:36
GetUser @ user.js:91
wrappedActionHandler @ vuex.esm.js:704
dispatch @ vuex.esm.js:426
boundDispatch @ vuex.esm.js:332
(anonymous) @ permission.js:29
iterator @ vue-router.esm.js:1935
step @ vue-router.esm.js:1709
step @ vue-router.esm.js:1713
runQueue @ vue-router.esm.js:1717
confirmTransition @ vue-router.esm.js:1964
transitionTo @ vue-router.esm.js:1866
push @ vue-router.esm.js:2267
push @ vue-router.esm.js:2529
(anonymous) @ index.vue?9e05:123
Promise.then (async)
(anonymous) @ index.vue?9e05:121
(anonymous) @ element-ui.common.js:22801
(anonymous) @ element-ui.common.js:23319
complete @ index.js:89
(anonymous) @ index.js:225
next @ util.js:148
next @ util.js:116
cb @ index.js:173
required @ required.js:8
(anonymous) @ index.js:216
next @ util.js:114
asyncSerialArray @ util.js:120
(anonymous) @ util.js:154
asyncMap @ util.js:151
validate @ index.js:141
validate @ element-ui.common.js:23315
(anonymous) @ element-ui.common.js:22795
validate @ element-ui.common.js:22794
handleLogin @ index.vue?9e05:118
click @ index.vue?3ea5:138
invoker @ vue.runtime.esm.js:2023
fn._withTask.fn._withTask @ vue.runtime.esm.js:1822
vue.runtime.esm.js:587 [Vue warn]: Property or method "customClass" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
warn @ vue.runtime.esm.js:587
warnNonPresent @ vue.runtime.esm.js:1872
get @ vue.runtime.esm.js:1914
mainvue_type_template_id_455b9f60_render @ element-ui.common.js:30105
Vue._render @ vue.runtime.esm.js:4540
updateComponent @ vue.runtime.esm.js:2784
get @ vue.runtime.esm.js:3138
Watcher @ vue.runtime.esm.js:3127
mountComponent @ vue.runtime.esm.js:2791
./node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount @ vue.runtime.esm.js:7995
Message @ element-ui.common.js:30317
main_Message.<computed> @ element-ui.common.js:30338
(anonymous) @ request.js:84
Promise.then (async)
request @ Axios.js:51
wrap @ bind.js:9
getUser @ login.js:26
(anonymous) @ user.js:92
F @ _export.js:36
GetUser @ user.js:91
wrappedActionHandler @ vuex.esm.js:704
dispatch @ vuex.esm.js:426
boundDispatch @ vuex.esm.js:332
(anonymous) @ permission.js:29
iterator @ vue-router.esm.js:1935
step @ vue-router.esm.js:1709
step @ vue-router.esm.js:1713
runQueue @ vue-router.esm.js:1717
confirmTransition @ vue-router.esm.js:1964
transitionTo @ vue-router.esm.js:1866
push @ vue-router.esm.js:2267
push @ vue-router.esm.js:2529
(anonymous) @ index.vue?9e05:123
Promise.then (async)
(anonymous) @ index.vue?9e05:121
(anonymous) @ element-ui.common.js:22801
(anonymous) @ element-ui.common.js:23319
complete @ index.js:89
(anonymous) @ index.js:225
next @ util.js:148
next @ util.js:116
cb @ index.js:173
required @ required.js:8
(anonymous) @ index.js:216
next @ util.js:114
asyncSerialArray @ util.js:120
(anonymous) @ util.js:154
asyncMap @ util.js:151
validate @ index.js:141
validate @ element-ui.common.js:23315
(anonymous) @ element-ui.common.js:22795
validate @ element-ui.common.js:22794
handleLogin @ index.vue?9e05:118
click @ index.vue?3ea5:138
invoker @ vue.runtime.esm.js:2023
fn._withTask.fn._withTask @ vue.runtime.esm.js:1822
vue.runtime.esm.js:587 [Vue warn]: Property or method "iconClass" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
warn @ vue.runtime.esm.js:587
warnNonPresent @ vue.runtime.esm.js:1872
get @ vue.runtime.esm.js:1914
mainvue_type_template_id_455b9f60_render @ element-ui.common.js:30112
Vue._render @ vue.runtime.esm.js:4540
updateComponent @ vue.runtime.esm.js:2784
get @ vue.runtime.esm.js:3138
Watcher @ vue.runtime.esm.js:3127
mountComponent @ vue.runtime.esm.js:2791
./node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount @ vue.runtime.esm.js:7995
Message @ element-ui.common.js:30317
main_Message.<computed> @ element-ui.common.js:30338
(anonymous) @ request.js:84
Promise.then (async)
request @ Axios.js:51
wrap @ bind.js:9
getUser @ login.js:26
(anonymous) @ user.js:92
F @ _export.js:36
GetUser @ user.js:91
wrappedActionHandler @ vuex.esm.js:704
dispatch @ vuex.esm.js:426
boundDispatch @ vuex.esm.js:332
(anonymous) @ permission.js:29
iterator @ vue-router.esm.js:1935
step @ vue-router.esm.js:1709
step @ vue-router.esm.js:1713
runQueue @ vue-router.esm.js:1717
confirmTransition @ vue-router.esm.js:1964
transitionTo @ vue-router.esm.js:1866
push @ vue-router.esm.js:2267
push @ vue-router.esm.js:2529
(anonymous) @ index.vue?9e05:123
Promise.then (async)
(anonymous) @ index.vue?9e05:121
(anonymous) @ element-ui.common.js:22801
(anonymous) @ element-ui.common.js:23319
complete @ index.js:89
(anonymous) @ index.js:225
next @ util.js:148
next @ util.js:116
cb @ index.js:173
required @ required.js:8
(anonymous) @ index.js:216
next @ util.js:114
asyncSerialArray @ util.js:120
(anonymous) @ util.js:154
asyncMap @ util.js:151
validate @ index.js:141
validate @ element-ui.common.js:23315
(anonymous) @ element-ui.common.js:22795
validate @ element-ui.common.js:22794
handleLogin @ index.vue?9e05:118
click @ index.vue?3ea5:138
invoker @ vue.runtime.esm.js:2023
fn._withTask.fn._withTask @ vue.runtime.esm.js:1822
vue.runtime.esm.js:587 [Vue warn]: Property or method "dangerouslyUseHTMLString" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
warn @ vue.runtime.esm.js:587
warnNonPresent @ vue.runtime.esm.js:1872
get @ vue.runtime.esm.js:1914
mainvue_type_template_id_455b9f60_render @ element-ui.common.js:30116
Vue._render @ vue.runtime.esm.js:4540
updateComponent @ vue.runtime.esm.js:2784
get @ vue.runtime.esm.js:3138
Watcher @ vue.runtime.esm.js:3127
mountComponent @ vue.runtime.esm.js:2791
./node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount @ vue.runtime.esm.js:7995
Message @ element-ui.common.js:30317
main_Message.<computed> @ element-ui.common.js:30338
(anonymous) @ request.js:84
Promise.then (async)
request @ Axios.js:51
wrap @ bind.js:9
getUser @ login.js:26
(anonymous) @ user.js:92
F @ _export.js:36
GetUser @ user.js:91
wrappedActionHandler @ vuex.esm.js:704
dispatch @ vuex.esm.js:426
boundDispatch @ vuex.esm.js:332
(anonymous) @ permission.js:29
iterator @ vue-router.esm.js:1935
step @ vue-router.esm.js:1709
step @ vue-router.esm.js:1713
runQueue @ vue-router.esm.js:1717
confirmTransition @ vue-router.esm.js:1964
transitionTo @ vue-router.esm.js:1866
push @ vue-router.esm.js:2267
push @ vue-router.esm.js:2529
(anonymous) @ index.vue?9e05:123
Promise.then (async)
(anonymous) @ index.vue?9e05:121
(anonymous) @ element-ui.common.js:22801
(anonymous) @ element-ui.common.js:23319
complete @ index.js:89
(anonymous) @ index.js:225
next @ util.js:148
next @ util.js:116
cb @ index.js:173
required @ required.js:8
(anonymous) @ index.js:216
next @ util.js:114
asyncSerialArray @ util.js:120
(anonymous) @ util.js:154
asyncMap @ util.js:151
validate @ index.js:141
validate @ element-ui.common.js:23315
(anonymous) @ element-ui.common.js:22795
validate @ element-ui.common.js:22794
handleLogin @ index.vue?9e05:118
click @ index.vue?3ea5:138
invoker @ vue.runtime.esm.js:2023
fn._withTask.fn._withTask @ vue.runtime.esm.js:1822
vue.runtime.esm.js:587 [Vue warn]: Property or method "message" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
warn @ vue.runtime.esm.js:587
warnNonPresent @ vue.runtime.esm.js:1872
get @ vue.runtime.esm.js:1914
mainvue_type_template_id_455b9f60_render @ element-ui.common.js:30118
Vue._render @ vue.runtime.esm.js:4540
updateComponent @ vue.runtime.esm.js:2784
get @ vue.runtime.esm.js:3138
Watcher @ vue.runtime.esm.js:3127
mountComponent @ vue.runtime.esm.js:2791
./node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount @ vue.runtime.esm.js:7995
Message @ element-ui.common.js:30317
main_Message.<computed> @ element-ui.common.js:30338
(anonymous) @ request.js:84
Promise.then (async)
request @ Axios.js:51
wrap @ bind.js:9
getUser @ login.js:26
(anonymous) @ user.js:92
F @ _export.js:36
GetUser @ user.js:91
wrappedActionHandler @ vuex.esm.js:704
dispatch @ vuex.esm.js:426
boundDispatch @ vuex.esm.js:332
(anonymous) @ permission.js:29
iterator @ vue-router.esm.js:1935
step @ vue-router.esm.js:1709
step @ vue-router.esm.js:1713
runQueue @ vue-router.esm.js:1717
confirmTransition @ vue-router.esm.js:1964
transitionTo @ vue-router.esm.js:1866
push @ vue-router.esm.js:2267
push @ vue-router.esm.js:2529
(anonymous) @ index.vue?9e05:123
Promise.then (async)
(anonymous) @ index.vue?9e05:121
(anonymous) @ element-ui.common.js:22801
(anonymous) @ element-ui.common.js:23319
complete @ index.js:89
(anonymous) @ index.js:225
next @ util.js:148
next @ util.js:116
cb @ index.js:173
required @ required.js:8
(anonymous) @ index.js:216
next @ util.js:114
asyncSerialArray @ util.js:120
(anonymous) @ util.js:154
asyncMap @ util.js:151
validate @ index.js:141
validate @ element-ui.common.js:23315
(anonymous) @ element-ui.common.js:22795
validate @ element-ui.common.js:22794
handleLogin @ index.vue?9e05:118
click @ index.vue?3ea5:138
invoker @ vue.runtime.esm.js:2023
fn._withTask.fn._withTask @ vue.runtime.esm.js:1822
vue.runtime.esm.js:587 [Vue warn]: Property or method "showClose" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)

**Comment by dongsuo** [comment]
看这个报错，你应该是在对应的组件里少了一个 visible 的值，可能是 dialog 之类的。element 的升级可能会有一些不兼容，建议你一个一个地方对应改一下。
