### ISSUE TITLE
手摸手教程中route.js代码变量 route 与现有代码不一致，导致路由失败~

### ISSUE THREAD

**Issue by sun-wenming** [PanJiaChen/vue-element-admin#2261]
## Bug report（问题描述）
手摸手教程中route.js变量route 与现有代码不一致。
现有代码逻辑已经改为[routes](https://github.com/PanJiaChen/vue-element-admin/blob/d3a2b6b34ed2f4ba69b78f2d07483747eb6ea7dd/src/router/index.js#L150)
望大佬有时间改下，小白已踩坑。
https://juejin.im/post/591aa14f570c35006961acac#heading-7
```
//异步挂载的路由
//动态需要根据权限加载的路由表 
export const asyncRouterMap = [
  {
    path: '/permission',
    component: Layout,
    name: '权限测试',
    meta: { role: ['admin','super_editor'] }, //页面需要的权限

```

建议：可以把教程放在github上可以pull  request

**Comment by PanJiaChen** [comment]
感谢你的建议，不过这是两年多前的文章了，不想改了。这里只是给出一个思路。
自己踩坑才更加印象深刻。
