### ISSUE TITLE
页面刷新 Tags-View 会丢失吗？

### ISSUE THREAD

**Issue by analyzesm** [PanJiaChen/vue-element-admin#2272]

**Comment by PanJiaChen** [comment]
目前所有状态都是存在vuex里的。
如果你想刷新保持状态的的话，需要自己将状态存储在如`localstorage`等浏览器存储中。

**Comment by sagittaria** [comment]
@PanJiaChen 大佬你们实际场景中，roles是存vuex吗？万一刷新就要重新去getUserInfo有可能比较频繁，但存cookie或localstorage的话前端直接手改了，然后刷新下就能显示一些原本没权限的菜单，想问下实际中怎么做的呢
