### ISSUE TITLE
粘贴时，img 标签变成了[img]

### ISSUE THREAD

**Issue by luoxulx** [PanJiaChen/vue-element-admin#2273]
## Question（提问）
直接粘贴时图片标签问题，粘贴时，img 标签变成了[img]，在编辑器里正常显示，但无法预览，保存到数据库的也是[img]的样子
#### Steps to reproduce（问题复现步骤）
- command + c 带图片的文本
- command + v

**Comment by PanJiaChen** [comment]
你试过线上版本么？我试了下没什么问题。

**Comment by luoxulx** [comment]
粘贴线上的代码可以用
