### ISSUE TITLE
表格分页搜索和删除BUG！！！

### ISSUE THREAD

**Issue by SourceLin** [PanJiaChen/vue-element-admin#2278]
## Bug report（问题描述）
问题一
  第二页时点搜索，表格数据刷新到第一页，但当前页码数不变！
问题二
  删除第二页最后一条数据时，第一页的最后一条数据不显示；

#### Screenshot or Gif（截图或动态图）
问题一：
![image](https://user-images.githubusercontent.com/40617196/59989718-fa392d00-9672-11e9-8443-fcd9ffb9b64e.png)
问题二：
![image](https://user-images.githubusercontent.com/40617196/59989938-cad6f000-9673-11e9-8330-c761e725c7c2.png)
![image](https://user-images.githubusercontent.com/40617196/59989962-e5a96480-9673-11e9-8f68-2538dccec2bc.png)

#### Link to minimal reproduction（最小可在线还原demo）
字典管理模块11条数据进行测试

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by Geosurf-gaoming** [comment]
这问题没解决吧
