### ISSUE TITLE
请问component: Layout是什么意思，怎么生效的

### ISSUE THREAD

**Issue by Dothegod** [PanJiaChen/vue-element-admin#2279]
现在所有的菜单和路由必须要外面嵌套一层才能生效。比如这个
{
    path: '/guide',
    component: Layout,
    redirect: '/guide/index',
    children: [
      {
        path: 'index',
        component: () => import('@/views/guide/index'),
        name: 'Guide',
        meta: { title: 'Guide', icon: 'guide', noCache: true }
      }
    ]
  }

这个只写前端没什么问题，但是如果对接后台以后，就意味着每创建一个菜单就要创建一个空目录才行。太麻烦
我把代码改成这样
{
    path: '/guide',
    name: 'guide',
    component: () => import('@/views/guide/index'),
    meta: { title: 'Guide', icon: 'guide', noCache: true },
    type: 2
  }
也能跳转，但是页面上只有guide的内容，侧边栏什么的都没有了，就像跳转了一个新页面一样。
导致这个问题的原因是什么，有什么解决方法吗？
自己折腾了一个星期了，实在搞不定。
我看有的框架好像直接写一层没什么问题，https://github.com/xiaolannuoyi/element-navmenu
思路也和这个框架基本一致，但是人家就是可以的，是有什么我没注意到的吗？

**Comment by dongsuo** [comment]
这个问题我建议你看一下 layout 组件都做了什么

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/layout.html#layout
