### ISSUE TITLE
tags-view初始化只有首页，无法显示其他的设置了true的tag

### ISSUE THREAD

**Issue by shiguoqing** [PanJiaChen/vue-element-admin#2286]
## Bug report（问题描述）
你好，我看你的在线demo，tags-view进来就有首页和文档两个，可是我使用的时候，路由中已经设置了固定，但是只有首页？请问如何初始化多个出事的tags-view

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/tags-view.html#affix-%E5%9B%BA%E9%92%89

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/tags-view.html#affix-%E5%9B%BA%E9%92%89
