### ISSUE TITLE
有关于Mock的功能和文档的描述问题

### ISSUE THREAD

**Issue by moosoul** [PanJiaChen/vue-element-admin#2287]
具体版本 vue-admin-template 4.2.1
问题是，我通过npm run build:prod构建的生产环境的包，推到线上API被Mock，没有修改过任何配置文件。

解决方案是
1. vue.config.js中devServer下面proxy之后的after删除
2. main.js中的  if (process.env.NODE_ENV === 'production') { mockXHR() }  代码注释掉

问题已解决，但是很疑惑。
1. vue.config.js下面，明明是devServer配置的mock，为何在build:prod之后会在线上环境生效？
2. main.js 中的这段代码 if (process.env.NODE_ENV === 'production') { mockXHR() } 难道不是生产环境开启mock的意思？
3. 在提问的issure看到了相关提问，但是文档中没有看到什么明确的说明，感觉你说的跟我这边使用的情况不太对。

最后提一个建议，这个默认生产环境打开了mock不是坑么？
正常来说只考虑开发环境才使用mock吧。
建议修改为默认开发环境mock而不是生产来mock

**Comment by minhail** [comment]
1、生产会用因为main.js引入了mock
2、文档不是都说了这是用来模拟的，因为这是一个用来展示的demo方案

生产环境开了mock，这是一个集成方案，通俗说就是个demo。
作者没做一个后台给接口数据，然后不想数据写在View里面，不用mock用什么。

**Comment by moosoul** [comment]
好的，我又去仔细查了一次文档，发现有一个描述mockjs和mock-server的地方，这两个是不同的地方，我这边疏忽了。希望还是能着重标记一下，这个吧。

发自我的 iPhone

**Comment by tunghsingw** [comment]
这似乎是一个作者文档定位的问题。
现在的文档大都体现了思维路径，对于学习源码很有帮助。
但是使用框架的有些人(比如我)，不想了解思思，只想知道怎么做。
因此，如果能够增加几个 HowTo类的说明会大赞！！
