### ISSUE TITLE
关于TagsView右键刷新的问题

### ISSUE THREAD

**Issue by Sliect** [PanJiaChen/vue-element-admin#2291]
TagsView的标签右键刷新之后为什么老的标签仍然存在，没有丢失
能不能大致解释一下原理，我看了store和TagsView文件都没找到哪一步能做到保存这些记录

**Comment by Sliect** [comment]
我自己试过$router.replace 不能保留vuex数据
我也试过注释掉TagsView下mounted的initTags方法和addTags，但是仍能保存旧的标签
这里也没用到resetRouter方法，还是百思不得其解，到底是如何保留下来的

**Comment by Sliect** [comment]
总算搞明白了
首先路由的重定向页面路由层级必须和刷新的组件层级一致
其次通过keep-alive 的include来保证指定的组件能被缓存下来

**Comment by shengxiaoliang** [comment]
q
