### ISSUE TITLE
最新版 .env.developmen和 .env.production，如何进行切换？

### ISSUE THREAD

**Issue by WuLBin** [PanJiaChen/vue-element-admin#2292]
新版vue-element-admin不使用原有vue的环境配置文件，改为 .env.developmen和 .env.production。
       这时候我想在开发的时候，随意切换development和production，但我找不到相关配置！

**Comment by MaskHao** [comment]
和旧版没什么区别啊，建议看vue-cli官文。

**Comment by PanJiaChen** [comment]
参考 vue-cli 文档。
