### ISSUE TITLE
操作table数据后刷新页面，如何回到之前的位置

### ISSUE THREAD

**Issue by kankantian** [PanJiaChen/vue-element-admin#2293]

**Comment by PanJiaChen** [comment]
你指的位置是什么?

**Comment by kankantian** [comment]
就是记录滚动条的位置啊 我在想能不能把scrollTop写进vuex，刷新之后回滚到之前的位置。但是好像浏览器自带这个功能。

**Comment by PanJiaChen** [comment]
table 目前不能记住位置的原因是它的内容是异步获取的。所以你需要在渲染完数据之后在滚动页面到你想要期望的位置。
