### ISSUE TITLE
tooltip 在 el-form-item 中label上不显示

### ISSUE THREAD

**Issue by CAH-FlyChen** [PanJiaChen/vue-element-admin#2294]
## Bug report（问题描述）
tooltip 在 el-form-item label中不显示

#### Link to minimal reproduction（最小可在线还原demo）
                      <el-form-item class="postInfo-container-item" label="广告价" prop="string_price">
                        <label slot="label">
                          广告价
                          <el-tooltip placement="right">
                            <div slot="content">指对应账号以多图头条文形式将 </div>
                            <i class="el-icon-info" />
                          </el-tooltip>
                        </label>
                        <el-input style="width: 217px" placeholder="请输入价格" />
                      </el-form-item>

**Comment by CAH-FlyChen** [comment]
修复可以参考  https://github.com/ElemeFE/element/pull/5921

**Comment by Dovahkinn** [comment]
加个 label-width
