### ISSUE TITLE
为什么运行后首页一直有个小人在不停的走？不显示仪表盘的图标了？

### ISSUE THREAD

**Issue by liuyuemozhu** [PanJiaChen/vue-element-admin#2297]
#### Steps to reproduce（问题复现步骤）
1. 下载项目后，运行npm install和npm run dev
2. 项目跑起来后，首页是一个小人在一直走啊走，不显示仪表盘的图表了

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by liuyuemozhu** [comment]
原来是因为需要登录admin（密码：111111）后才能出现图表

**Comment by PanJiaChen** [comment]
恩，不同权限有不同的 `dashboard`。

https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/dashboard/index.vue
