### ISSUE TITLE
clipboard.off()主要是用来干什么的呢

### ISSUE THREAD

**Issue by wuxin1210** [PanJiaChen/vue-element-admin#2299]
clipboard.off()主要是用来干什么的呢

**Comment by mayunhai** [comment]
查了官方文档以及源码，Clipboard好像确实没有 .off() 这个方法

**Comment by mayunhai** [comment]
已提交修改 待合并

**Comment by PanJiaChen** [comment]
https://github.com/zenorocha/clipboard.js/blob/d17eca050e705ae4932fd1be3e96abe38bd3397c/dist/clipboard.js#L670

`off`是`tiny-emitter`的方法，不过这里的确没什么用，可以去除。

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/2307

**Comment by wuxin1210** [comment]
> https://github.com/zenorocha/clipboard.js/blob/d17eca050e705ae4932fd1be3e96abe38bd3397c/dist/clipboard.js#L670
> 
> `off`的英文`tiny-emitter`的方法，不过这里的确没什么用，可以去除。

了解，感谢大佬解答。
