### ISSUE TITLE
异步获取数据后，重新调用 ECharts 的 setOption， animation 动画不生效

### ISSUE THREAD

**Issue by atzcl** [PanJiaChen/vue-element-admin#230]
写死数据动画会生效，但是异步获取数据后重新 setOption 更新数据是，animation 动画会丢失
------------------------------
Vue版本：2.4.2
ECharts版本：3.7.1
系统：Mac 10.13

**Comment by PanJiaChen** [comment]
并不能重新上述问题

**Comment by atzcl** [comment]
@PanJiaChen https://jsfiddle.net/vvmpmatn/ 在这里的确没有，我再测试下，感谢您的回复！
