### ISSUE TITLE
关于打包出静态文件,无法访问api接口

### ISSUE THREAD

**Issue by MoonCheung** [PanJiaChen/vue-element-admin#2302]
#### Steps to reproduce（问题复现步骤）

1.我想将整个项目通过`npm run preview`打包出来静态文件，通过nginx配置文件内已经写好api接口，可看到登录页面显示的，但是无法访问api接口的, 而且报错404的，本以为是找不到api接口无法访问。
2.我的线上api接口`https://api.*******.com/`可以访问，另外.env.production这个文件内:

```javascript
# base api
VUE_APP_BASE_API = '/api'
```
3.我觉得打包出来静态文件和devServer对象无关的，具体什么问题可解决，当初我自行搜索谷歌仍未解决...
#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/19801190/60341344-c21e4b00-99e0-11e9-9880-57f96623bb60.png)
![image](https://user-images.githubusercontent.com/19801190/60341379-dcf0bf80-99e0-11e9-948c-7650170d8881.png)
![image](https://user-images.githubusercontent.com/19801190/60341599-9c457600-99e1-11e9-8612-7bde1a998d6b.png)

#### Other relevant information（格外信息）
- Your OS: Win10专业版
- Node.js version: node 版本: v10.15.3
- vue-element-admin version: v4.1.0(element模板)

**Comment by MoonCheung** [comment]
nginx配置文件有错误需修改，当生产环境时，本人觉得.env.production文件内应该将`VUE_APP_BASE_API = '/'`可登录，自行解决...

**Comment by wang4978** [comment]
同样404错误，请问你的nginx是怎么修改的

**Comment by MoonCheung** [comment]
嗯，不好意思，我刚才收到邮件看到消息的
```nginx
location ~ /api {
        proxy_pass 线上服务器链接地址
        proxy_set_header   X-Forwarded-Proto $scheme; 
        proxy_set_header   X-Real-IP         $remote_addr;
   }
```
按照这个nginx文件修改尝试呢

**Comment by MoonCheung** [comment]
@wang4978

**Comment by MoonCheung** [comment]
> 同样404错误，请问你的nginx是怎么修改的

嗯，不好意思，我刚才收到邮件看到消息的
```nginx
location ~ /api {
        proxy_pass 线上服务器链接地址
        proxy_set_header   X-Forwarded-Proto $scheme; 
        proxy_set_header   X-Real-IP         $remote_addr;
   }
```
按照这个nginx文件修改尝试呢
