### ISSUE TITLE
彩色svg显示的是黑白颜色的，请问有办法设置吗？

### ISSUE THREAD

**Issue by Panhaiwei** [PanJiaChen/vue-element-admin#2305]
#### Steps to reproduce（问题复现步骤）

1. 添加彩色的svg
2. 页面引入
3. 刷新查看

#### Screenshot or Gif（截图或动态图）
原图如下
![image](https://user-images.githubusercontent.com/13009686/60378723-6512ab80-9a59-11e9-9a9d-e343b831c996.png)
导入项目后显示如下
![image](https://user-images.githubusercontent.com/13009686/60378726-6f34aa00-9a59-11e9-9526-c0f34890baa5.png)

**Comment by mayunhai** [comment]
双击引入 svg 文件打开 ，确定原本就是彩色的么

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/60391976-00c11c00-9b2d-11e9-8a79-0dd639699767.png)

测试了下没发现问题，若有问题，请提供复现demo
