### ISSUE TITLE
请问权限全是由后端进行控制,怎么生成侧边栏

### ISSUE THREAD

**Issue by fzg2lj** [PanJiaChen/vue-element-admin#2306]
## Question（提问）

潘神,我是一个小白,请问我们项目是由后台来控制和增加权限 数据结构是这样的, 请问该怎么实现生成侧边栏

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/45679359/60383966-17269380-9aab-11e9-8e1c-5022eac90e40.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by mayunhai** [comment]
路由信息里可以配置权限集合，服务端鉴权接口也会返回一个权限的数组，两者有交集便会生成，没有交集则会自动不生成，代码里面已经做了处理了

**Comment by geniustonyas** [comment]
我的办法是，前端路由和后端路由，都起个别名(如果对这个name要求不高,可以考虑前后端的name一致)，在后端保存一份和侧边菜单一模一样结构的路由别名表. 例如:
`return [
    //首页面板路由
    [
        'routeName'     => 'index',
        'isMenu'        => true,
        'title'         => '首页',
        'childMenu'      => [
            [
                'routeName'     => 'indexMenu',
                'title'         => '首页报表',
                'isMenu'        => true,
                'childMenu'      => [
                    [
                        'routeName'     => 'dashboard',
                        'title'         => '首页报表',
                        'isMenu'        => false,
                    ],
                    [
                        'routeName'     => 'profile',
                        'title'         => '编辑资料',
                        'isMenu'        => false,
                    ]
                ],
            ]
        ],
    ],`

前端的路由不需要再使用role来判断权限了. 而是直接在获取用户信息接口得到该用户权限数组:
getInfo接口返回:
`{
    "ret": 0,
    "data": {
        "adminId": 1,
        "groupId": 1,
        "userName": "test",
        "permission": [
            "admin",
            "adminList",
            "adminMenu",   
        ],
        "email": "test@qq.com",
        "mobile": "13311112222",
        "avataUrl": "",
        "lastLoginIp": "172.17.0.1",
        "lastLoginTime": "2019-06-30 14:05:08",
        "status": 1,
        "addTime": "2019-05-22 20:12:57"
    }
}`
然后在src/permission中的30行 将roles 改成permission
`const { permission } = await store.dispatch('user/getInfo')
  // 动态生成路由
 const accessRoutes = await store.dispatch('permission/generateRoutes', permission)
 router.addRoutes(accessRoutes)`

接着修改store中permission的动态生成路由的方法
`/**
 * 利用路由名称是否在权限数组中来验证是否有权限
 * @param permission
 * @param route
 */
function hasPermission(permission, route) {
  if (typeof permission === 'object') {
    return permission.includes(route.name)
  } else {
    return false
  }
}

/**
 * 递归异步动态路由 过滤掉无权限的路由, 生成可访问路由列表.
 * @param routes asyncRoutes
 * @param permission
 */
export function filterAsyncRoutes(routes, permission) {
  const res = []
  routes.forEach(route => {
    const tmp = { ...route }
    if (hasPermission(permission, tmp)) {
      if (tmp.children) {
        tmp.children = filterAsyncRoutes(tmp.children, permission)
      }
      res.push(tmp)
    }
  })
  res.push(notFoundRoute)
  return res
}`

然后... 侧边栏 .  基本上可以用原有的代码就行, 不用做任何更改

**Comment by fzg2lj** [comment]
> 路由信息里可以配置权限集合，服务端鉴权接口也会返回一个权限的数组，两者有交集便会生成，没有交集则会自动不生成，代码里面已经做了处理了

谢谢大神

**Comment by fzg2lj** [comment]
> 我的办法是，前端路由和后端路由，都起个别名(如果对这个name要求不高,可以考虑前后端的name一致)，在后端保存一份和侧边菜单一模一样结构的路由别名表. 例如:
> `return [ //首页面板路由 [ 'routeName' => 'index', 'isMenu' => true, 'title' => '首页', 'childMenu' => [ [ 'routeName' => 'indexMenu', 'title' => '首页报表', 'isMenu' => true, 'childMenu' => [ [ 'routeName' => 'dashboard', 'title' => '首页报表', 'isMenu' => false, ], [ 'routeName' => 'profile', 'title' => '编辑资料', 'isMenu' => false, ] ], ] ], ],`
> 
> 前端的路由不需要再使用role来判断权限了. 而是直接在获取用户信息接口得到该用户权限数组:
> getInfo接口返回:
> `{ "ret": 0, "data": { "adminId": 1, "groupId": 1, "userName": "test", "permission": [ "admin", "adminList", "adminMenu", ], "email": "test@qq.com", "mobile": "13311112222", "avataUrl": "", "lastLoginIp": "172.17.0.1", "lastLoginTime": "2019-06-30 14:05:08", "status": 1, "addTime": "2019-05-22 20:12:57" } }`
> 然后在src/permission中的30行 将roles 改成permission
> `const { permission } = await store.dispatch('user/getInfo') // 动态生成路由 const accessRoutes = await store.dispatch('permission/generateRoutes', permission) router.addRoutes(accessRoutes)`
> 
> 接着修改store中permission的动态生成路由的方法
> `/**
> 
> * 利用路由名称是否在权限数组中来验证是否有权限
> * @param permission
> * @param route
>   */
>   function hasPermission(permission, route) {
>   if (typeof permission === 'object') {
>   return permission.includes(route.name)
>   } else {
>   return false
>   }
>   }
> 
> /**
> 
> * 递归异步动态路由 过滤掉无权限的路由, 生成可访问路由列表.
> * @param routes asyncRoutes
> * @param permission
>   */
>   export function filterAsyncRoutes(routes, permission) {
>   const res = []
>   routes.forEach(route => {
>   const tmp = { ...route }
>   if (hasPermission(permission, tmp)) {
>   if (tmp.children) {
>   tmp.children = filterAsyncRoutes(tmp.children, permission)
>   }
>   res.push(tmp)
>   }
>   })
>   res.push(notFoundRoute)
>   return res
>   }`
> 
> 然后... 侧边栏 . 基本上可以用原有的代码就行, 不用做任何更改

谢谢大佬写的这么详细
