### ISSUE TITLE
问题.

### ISSUE THREAD

**Issue by EliazTray** [PanJiaChen/vue-element-admin#231]
之前在router文件夹下的import和require是不需要.default去导入模块的,是哪一项的改动,才需要这么做呢.

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/30961520-0184e768-a479-11e7-8b3d-bb5c16bdfd30.png)

因为vue-loader v13.0.0 的Breaking Changes
vue默认导出变成了 ` ES module `格式
相关链接：https://github.com/vuejs/vue-loader/releases

**Comment by EliazTray** [comment]
thanks~
