### ISSUE TITLE
asyncRoutes  生成的 侧边栏 每个路由 meta 信息的 标题（title） 怎么动态生成？

### ISSUE THREAD

**Issue by zss1004504439** [PanJiaChen/vue-element-admin#2310]
## Question（提问）

怎么动态改变侧边栏 路由列表 的title值，根据 不同的角色权限
（可以复制多个重复路由 ，然后改变 meta信息 的 title 值 ；但不想这么做）
#### Steps to reproduce（问题复现步骤）
 无

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/24915880/60434339-83370200-9c39-11e9-87c8-eafdb61b41b8.png)

#### Link to minimal reproduction（最小可在线还原demo）
无

#### Other relevant information（格外信息）
- Your OS: Windows
- Node.js version: 
- vue-element-admin version: 4.2

**Comment by hedekun** [comment]
异步路由，整个路由信息都可以动态。不需要复制多个。

**Comment by zss1004504439** [comment]
> 异步路由，整个路由信息都可以动态。不需要复制多个。

是修改 src/store/modules/permission.js   actions 的 generateRoutes 方法？

**Comment by hedekun** [comment]
> > 异步路由，整个路由信息都可以动态。不需要复制多个。
> 
> 是修改 src/store/modules/permission.js actions 的 generateRoutes 方法？

是的。
