### ISSUE TITLE
小白提问

### ISSUE THREAD

**Issue by gjfei** [PanJiaChen/vue-element-admin#2316]
## Question（提问）
这里的that=this有何用意？
![TIM图片20190702173336](https://user-images.githubusercontent.com/33827314/60501994-88ef1f00-9cef-11e9-97ec-b6b0719460ca.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by mayunhai** [comment]
大多数情况是为了修改 this 指向，不过这里不做转化也是可以的，因为里面没有用函数，或者直接改用箭头函数
