### ISSUE TITLE
小白提问

### ISSUE THREAD

**Issue by gjfei** [PanJiaChen/vue-element-admin#2318]
在src\views\dashboard\admin\components\LineChart.vue下的组件中
在mounted钩子中DOM已经渲染挂载为何还要加上$nexTick？
![TIM图片20190703135509](https://user-images.githubusercontent.com/33827314/60566818-a3ca9d80-9d9a-11e9-8127-af7d8551d774.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/2060

因为侧边栏其实是会根据屏幕宽度动态调整的，这就会导致，在移动端的情况下，侧边栏会隐藏，这时候如果不加`nextTick`会导致 图表初始化的宽度是不对的。

简而言之加上`nextTick`是为了保证初始化图表的时候的宽度
