### ISSUE TITLE
首页里的多页面标签状态无法保持

### ISSUE THREAD

**Issue by daiing** [PanJiaChen/vue-element-admin#232]
在不同的标签切换后，原来的标签页内容被重置了
能否保持切换前的内容，比如编辑文章到一半，打开一个查询报表，回到编辑文章，希望文章还在
否则多标签页的意义不大

**Comment by PanJiaChen** [comment]
Duplicate of #193 
Duplicate of #181

**Comment by daiing** [comment]
看到了，谢谢大佬
