### ISSUE TITLE
项目打包路径

### ISSUE THREAD

**Issue by qiufeihong2018** [PanJiaChen/vue-element-admin#2322]
#### Steps to reproduce（问题复现步骤）

目标:是将下图中的dist文件夹放在其他项目中

更改其中的serveStatic无效
 app.use(
    publicPath,
    serveStatic('./dist', {
      index: ['index.html', '/']
    })
  )
#### Screenshot or Gif（截图或动态图）
![a](https://user-images.githubusercontent.com/36500514/60571535-6409b300-9da6-11e9-8543-68f98eaac35f.png)

#### Other relevant information（格外信息）
- Your OS:Linux devue-System-Product-Name 4.15.0-54-generic #58~16.04.1-Ubuntu SMP Mon Jun 24 13:21:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Node.js version:v11.2.0

- vue-element-admin version:4.0.0

**Comment by 563912432** [comment]
jiejuelema?
