### ISSUE TITLE
今天mock服务是不是崩了？

### ISSUE THREAD

**Issue by liuyuemozhu** [PanJiaChen/vue-element-admin#2324]
vue-template-admin中的complex-table组件的数据请求不到，报Request failed with status 404

**Comment by PanJiaChen** [comment]
请按照issue模板提问。

现在的mock都是本地mock的，所以不会有你说的问题。你的问题，也在 vue-template-admin issue 中置顶了相关问题。

**Comment by liuyuemozhu** [comment]
> 请按照issue模板提问。
> 
> 现在的mock都是本地mock的，所以不会有你说的问题。你的问题，也在 vue-template-admin issue 中置顶了相关问题。

可是我的一直报Request failed with status 404是什么鬼？

**Comment by binxyz** [comment]
我的也是，照着文档新建api, 再在 mock文件夹下建mock数据，还是报404
