### ISSUE TITLE
npm run dev启动报错 

### ISSUE THREAD

**Issue by nyanboard** [PanJiaChen/vue-element-admin#2326]
**npm run dev出现以下问题**
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module 'E:\work\vue-element-admin\node_modules\eslint\lib\api
.js/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.module.exports (E:\work\vue-element-admin\node_modules\eslint-load
er\index.js:170:23)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

**Comment by comacs** [comment]
》我已经找到发生问题的地方，就在“eslint-loader/index.js 163-170”代码块内重新引用了“webpack.query”中定义的“EslintPath”
》现在我也需要官方帮忙给出解决方案！！！
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/12652775/60638362-a8ea2400-9e50-11e9-88bf-d246ab621817.png">

**Comment by nyanboard** [comment]
那能否告诉我现在哪个版本能够跑起来，4.2.0可以吗

**Comment by 974988176** [comment]
我也是这个问题,在我取消了 ESLint 校验,在文档中,
如果你不想使用 ESLint 校验（不推荐取消），只要找到 vue.config.js 文件。 
进行如下设置:
将原来的lintOnSave: process.env.NODE_ENV === 'development'改为 lintOnSave: false 即可

**Comment by upiota** [comment]
package.json中@vue/cli-plugin-eslint版本改为"^3.9.1"

**Comment by 974988176** [comment]
> package.json中@vue/cli-plugin-eslint版本改为"^3.9.1"

试过了,可以,谢谢

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/2327

**Comment by jozhi** [comment]
package.json
`
  "rules": {
    "generator-star-spacing": "off",
    "no-tabs": "off",
    "no-unused-vars": "off",
    "no-console": "off",
    "no-irregular-whitespace": "off",
    "no-debugger": "off"
  }
}
`
.eslintrc.js
`
  rules: {
    "no-unused-vars": 'warn'
  }
`

bingo!
