### ISSUE TITLE
关于页面缓存

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#2329]
## Question（提问）

请问下潘神，在router里的index.js未设置noCache的状态下，分别打开两个页面，其中一个搜索出结果，切换到另一个页面，再切换回搜索，此时页面的搜索结果会被清除，相当于页面被重新载入。有没什么设定可以让页面不被重新载入？

**Comment by yangtuo5541** [comment]
我也想做个类似的功能，求你的方法 --
