### ISSUE TITLE
！！！！！！！！！！！！！唉

### ISSUE THREAD

**Issue by QiangFangcn** [PanJiaChen/vue-element-admin#2332]
![image](https://user-images.githubusercontent.com/29371991/60649937-a9e17c80-9e75-11e9-8682-766f189fdc8e.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/2326

**Comment by QiangFangcn** [comment]
这个解决不了的，您可以自己down下项目跑一下吗，另外一个项目没问题
