### ISSUE TITLE
npm install和npm run dev都有错误

### ISSUE THREAD

**Issue by cnsdwu** [PanJiaChen/vue-element-admin#2334]
报错信息如下

![menu saveimg savepath20190704170226](https://user-images.githubusercontent.com/23513790/60654300-50ca1680-9e7e-11e9-9894-7360bacb9aea.jpg)
![menu saveimg savepath20190704170119](https://user-images.githubusercontent.com/23513790/60654301-51fb4380-9e7e-11e9-80b1-490395661be9.jpg)

谢谢解答~

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/2326

**Comment by huangshizhan** [comment]
> #2326

![image](https://user-images.githubusercontent.com/26118170/65828988-6f03af00-e2d3-11e9-8c73-5666314179e7.png)
花老师，出现这个是什么原因，我看好多人都有出现这种状况，电脑装不了git,项目我是直接下载下来的!
