### ISSUE TITLE
小白关于左侧菜单栏活跃状态的疑惑

### ISSUE THREAD

**Issue by shexm** [PanJiaChen/vue-element-admin#2339]
看了大神用了elementui的el-menu组件，将default-active设置为当前路由，将el-menu-item的index设置为各自的路由名。当我从一个路由进入隐藏路由（从 /example/list进入/example/edit/1 ），此时当前路由已经变为隐藏路由了但是原路由却还是能够显示为活跃状态（蓝字）。

**Comment by aqaaqa** [comment]
我也遇到了，有解决办法了吗
