### ISSUE TITLE
导航tag不覆盖，且组件状态保留

### ISSUE THREAD

**Issue by Demon2** [PanJiaChen/vue-element-admin#234]
每次点击左侧导航，顶部导航都新增一个tag且不覆盖，如点击左侧导航的 富文本编辑器 3次就生成3个tag,且点击tag切换时可保留输入的内容

**Comment by PanJiaChen** [comment]
保留问题
Duplicate of #193 
Duplicate of #181 

覆盖问题：你确定线上会这样吗？并不能重现你说的问题

**Comment by Demon2** [comment]
我需要实现这样的功能，尝试几天没有方案。希望能得到帮助

**Comment by PanJiaChen** [comment]
我都给方案了。。。

**Comment by Demon2** [comment]
keep-live 这个我是知道，也是实现ok的，但前置条件是每个路由对应唯一个tag;
我现在需要的实现的是每次点击导航都生成一个tag（tag不去重）。
如“编辑器”我点击3次就生成3个tag ；切换这3个tag时里面的输入的内容保留且相互不影响

**Comment by PanJiaChen** [comment]
我都说了我不能重现你的问题
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/store/modules/app.js#L20
我做了判断的

**Comment by Demon2** [comment]
大神,
**我需要实现的是就是去掉你这个判断。**
上面问题再重复一遍，你仔细读下

我现在     需要的实现     的是每次点击导航都生成一个tag（tag不去重）。
如“编辑器”我点击3次就生成3个tag ；切换这3个tag时里面的输入的内容保留且相互不影响

**Comment by Demon2** [comment]
大神：
麻烦仔细读下我的问题

**我需要实现的是就是去掉你这个判断**
**这样每次点击导航都生成一个tag（tag不去重）。**
**如“编辑器”我点击3次就生成3个“编辑器”tag ；**
分别点击这3个“编辑器”tag 时都对应到编辑器这个组件，但组件里的输入内容相互不影响；

**Comment by PanJiaChen** [comment]
每次点击生成不同的路由不就好了，如`edit/1` `edit/2` 这样

**Comment by Demon2** [comment]
额，，还是自己去研究吧，感谢。
