### ISSUE TITLE
请问一下Table的文章数据是怎么来的，没找到Rest接口

### ISSUE THREAD

**Issue by frontng** [PanJiaChen/vue-element-admin#235]
请问一下综合Table的文章数据是怎么来的，就算改了，BASE_URL以及REST接口地址，数据还是没变化。 就算乱写一个URL，照样可以请求到数据。

**Comment by PanJiaChen** [comment]
> 由于是个人项目，所以数据请求都是用了 `mockjs` 模拟 

文档写了,本项目所有数据均有前端 mock 生成

**Comment by frontng** [comment]
看到了，谢谢

**Comment by yursile** [comment]
有点蒙逼了，我看api里直接调的axios，没有哪里调用了mock呀，本地全局搜渲染出的数据也搜不到呀

**Comment by yursile** [comment]
而且也没有请求发出，本地也搜不到数据，一脸蒙蔽呀

**Comment by yursile** [comment]
哦懂了懂了
