### ISSUE TITLE
下载ZIP文件无法安装，只能依靠git clone下载的项目才成功。

### ISSUE THREAD

**Issue by smallwl** [PanJiaChen/vue-element-admin#2359]
## Question（提问）
项目无法 npm install
无法确定ZIP包的文件和GIT CLONE的文件是否一致，或其它原因造成偏差。

#### Steps to reproduce（问题复现步骤）
安装环境：腾讯云，CENTOS 7.6，BT面板
1、从GITHUB下载的ZIP文件，上存到服务器，解压。
2、进入目录运行 NPM INSTALL 。出错无法安装，错误代码在下面(WINDOWS 本地一样，贴的是WINDOWS本地出错信息)。
3、按照官方的文档，SSH远程登录服务器。git clone 到服务器目录，可以 NPM INSTALL 和NPM RUN DEV ，并能运行起来。

#### Link to minimal reproduction（最小可在线还原demo）
PS D:\htdocs\vue-element-admin> C:\nodejs\npm.cmd install
npm WARN deprecated runjs@4.4.2: This project has been renamed to 'tasksfile'. Install using 'npm install tasksfile' ins
tead.
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Vis
it <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/sohee-lee7/Squire.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxxx\AppData\Roaming\npm-cache\_logs\2019-07-10T07_20_36_801Z-debug.log

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
git config --global url."https://github".insteadOf github:

**Comment by vegetablelong** [comment]
1.环境配置成功后
2.若采用git clone项目，则直接在目录下使用npm install，若提示无git，安装并设置环境变量后再进行run
3.若直接下载压缩包，则在目录下采用cnpm install
