### ISSUE TITLE
开发环境浏览器不打印console信息

### ISSUE THREAD

**Issue by aogutong** [PanJiaChen/vue-element-admin#2399]
遇到个问题，在开发环境想打印一些信息，怎么也打印不出来了
我看生产环境可以清除console，开发环境没见有啊，不知道哪里错了

**Comment by mydaoyuan** [comment]
webpack 会清除掉console debugger 之类的关键字的，可以自己去修改

**Comment by PanJiaChen** [comment]
本项目没做任何处理。

**Comment by KangDongHui** [comment]
这是什么东西阿，怎么全给我邮箱发过来了，好疑惑啊

在 2020-05-05 21:15:30，"花裤衩" <notifications@github.com> 写道：

Closed #2399.

**Comment by PanJiaChen** [comment]
你是不是 watch了项目，然后绑了邮箱？@KangDongHui
