### ISSUE TITLE
关于工具函数：parseTime的疑问

### ISSUE THREAD

**Issue by fyj0846** [PanJiaChen/vue-element-admin#2402]
大神，框架中有提供一个工具函数parseTime，存在一个疑问
## 现象
现在的逻辑是如果传入的时间参数转成字符为10位，则自动乘以1000。

## 疑问
不考虑传入的10位时间参数确实是毫秒数的情况吗？
```
new Date(8888888888)  // 10位毫秒级时间戳
```

**Comment by linmq** [comment]
You can modify this parseTime function to fit your requirement.

**Comment by bihell** [comment]
我也看到了这个函数， 自己写吧。

**Comment by fyj0846** [comment]
> You can modify this parseTime function to fit your requirement.

got it, thanks
