### ISSUE TITLE
左侧栏路由不支持 Element UI 图标吗？

### ISSUE THREAD

**Issue by razonyang** [PanJiaChen/vue-element-admin#2414]

**Comment by bihell** [comment]
应该不支持，我后来直接把要的图标下载下来放图标目录解决

**Comment by razonyang** [comment]
@bihell 似乎真的不支持，我还是按照[文档](https://panjiachen.gitee.io/vue-element-admin-site/zh/guide/advanced/icon.html)单独下载吧

**Comment by kapaez** [comment]
不支持，他的路由使用的svg-icon组件，你可以自己看看组件怎么写的
