### ISSUE TITLE
导航栏收缩时，文字没有隐藏，图标也没有居中。

### ISSUE THREAD

**Issue by softshield** [PanJiaChen/vue-element-admin#2415]
## Bug report（问题描述）
导航栏收缩时，文字没有隐藏，图标也没有居中

#### Steps to reproduce（问题复现步骤）

1. 因为我这个项目是基于原项目升级，所以都是一步步的复制配置弄过来的。
2. 其他的功能基本上都移过来了，就是导航栏这个bug不知道怎么回事。模板工程的导航栏没这个bug。
3. element ui版本都是对的。如果我强行改CSS样式也能解决这个问题。
如下：
`
.el-menu--collapse {
    .el-menu-item {
      padding-left: 20px !important;
      span {
        display: none;
      }
    }
  }`

4.对比了Dom上的区别，模板工程在导航栏收缩时，图标外层有这样一个DIV，如下
`<div class="el-tooltip" aria-describedby="el-tooltip-5247" tabindex="0" style="position: absolute; left: 0px; top: 0px; height: 100%; width: 100%; display: inline-block; box-sizing: border-box; padding: 0px 20px;"><svg data-v-c8a70580="" aria-hidden="true" class="svg-icon"><use data-v-c8a70580="" xlink:href="#icon-dashboard"></use></svg></div>`
而我的工程并没有产生这一层div(class="el-tooltip"的那个div)。

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/24540701/61865472-d84af880-af05-11e9-9005-2b054f4f2af5.png)
![image](https://user-images.githubusercontent.com/24540701/61865491-e3058d80-af05-11e9-9812-c341de555a16.png)

**Comment by cnsummer** [comment]
在这里是做过伸缩多少的判断的 这个状态存储在store中，具体代码应该就在左侧的这个菜单组件里，你自己找一找吧

**Comment by chenxxing** [comment]
楼主问题解决了吗  我也遇到了

**Comment by Scyh** [comment]
看了代码，发现也是通过css解决的。。折叠情况下，直接隐藏标签和箭头

**Comment by PanJiaChen** [comment]
应该是css问题，对着线上代码看一下吧。
