### ISSUE TITLE
大数据量tree的处理

### ISSUE THREAD

**Issue by yuleiQ** [PanJiaChen/vue-element-admin#2426]
## Feature request（新功能建议）

场景： 数据架构树数据量可能在10万数据左右，虽然可能使用懒加载解决，但是下面节点加载使用element节点超过2k也会卡顿。同样的情况如果放在tree-table里 数据多了应该也会卡顿吧。
参考文献： https://zhuanlan.zhihu.com/p/55528376
解决： 我目前采用vue-virtual-scroller把数据展成平级，但貌似节点的关闭展开会有问题，因为el-tree是递归调用组件，貌似之后不好处理。
希望大佬能考虑我的issue

**Comment by PanJiaChen** [comment]
这种大数据 不能用element的tree，你可以社区里找找有什么处理大数据表格好的组件。

**Comment by wheelo** [comment]
同问

**Comment by wheelo** [comment]
同问

**Comment by defghy** [comment]
同问，没有找到比较成熟的大数据树形组件
