### ISSUE TITLE
可以不从侧边栏进入新页面吗？

### ISSUE THREAD

**Issue by grace618** [PanJiaChen/vue-element-admin#2430]
## Question（提问）

不从侧边栏进入新页面，而是通过页面里的按钮进入。
#### Steps to reproduce（问题复现步骤）

例如有个列表，列表里每条数据都有按钮‘查看‘操作，点击查看进入新页面。
我目前的方法是也放到侧边栏导航，只是隐藏了，请问还有其他什么好的方法吗
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by CjoyHome** [comment]
在页面中给按钮添加事件 通过this.$router.push等路由操作达到你的目的

**Comment by PanJiaChen** [comment]
可以入楼上所说用`router.push`或者使用<router-link>
