### ISSUE TITLE
动态改变meta的title并进行国际化

### ISSUE THREAD

**Issue by CjoyHome** [PanJiaChen/vue-element-admin#2434]
需求是需要一个编辑页面和一个添加页面，我想在进入编辑页面时候 面包屑 tab显示的是编辑，新增时候显示新增，并且做了国际化， 这两个页面都走一个path 
我尝试过
`      this.$route.query.type == "edit" ? this.$route.meta.title = "appVersionEdit" : this.$route.meta.title = "appVersionAdd"
`
有时ok有时候不行，希望潘神能帮我看看有什么办法，谢谢

**Comment by CjoyHome** [comment]
这个是当前的路由配置
`{
        hidden: true,
        path: 'appVersionEdit',
        component: () => import('@/views/setting-manage/appVersionEdit'),
        name: 'AppVersionEdit',
        meta: {
          title: 'appVersionEdit',
          roles: ['0', '1'],
          noCache: true
        }
      }`

**Comment by PanJiaChen** [comment]
meta.title 国际化不就好了，你可以借鉴一下i18n分支
