### ISSUE TITLE
 :unique-opened="false"

### ISSUE THREAD

**Issue by lilysuperHTML** [PanJiaChen/vue-element-admin#2436]
<el-scrollbar wrap-class="scrollbar-wrapper">
      <el-menu
        :default-active="activeMenu"
        :collapse="isCollapse"
        :background-color="variables.menuBg"
        :text-color="variables.menuText"
        :unique-opened="true"
        :active-text-color="variables.menuActiveText"
        :collapse-transition="false"
        mode="vertical"
      >
    :unique-opened="true"为什么没有起作用？

**Comment by sunxueyi888** [comment]
我设置了也无效

**Comment by PanJiaChen** [comment]
试了没问题，有问题请提供在线可还原demo
