### ISSUE TITLE
展开/隐藏的过程的动画不平滑，会跳动

### ISSUE THREAD

**Issue by lain1936** [PanJiaChen/vue-element-admin#244]
隐藏过程
先64px然后36px，把动画transition关掉，很明显看出Navbar的宽度会跳动一下

展开过程
会在动画完成之后 出现白底 快速跳动到180px

el-menu-collapse-transition   默认动画结束好像是64px 和  scrollWidth
.app-wrapper.hideSidebar .sidebar-container 设置的是36px

**Comment by lain1936** [comment]
https://github.com/ElemeFE/element/blob/dev/packages/menu/src/menu.vue#L72  是这个的原因？

**Comment by PanJiaChen** [comment]
新版本已修复该问题
