### ISSUE TITLE
./src/layout/components/Sidebar/Item.vue编译报错

### ISSUE THREAD

**Issue by chuxin-fly** [PanJiaChen/vue-element-admin#2441]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by chuxin-fly** [comment]
![image](https://user-images.githubusercontent.com/52024337/62378059-88f47000-b576-11e9-9661-ff180588d2f6.png)
if (icon) {
      vnodes.push(<svg-icon icon-class={icon}/>) #这一行编译报错在<处
   }

   if (title) {
     vnodes.push(<span slot='title'>{(title)}</span>) #这一行编译报错在<处
   }
Node.js version:11.7.0
vue-element-admin version:4.2.1,vue-element-admin-i18n

**Comment by hedekun** [comment]
缺依赖吧，重新`npm install`一下

**Comment by zuiqiangqishao** [comment]
改成这个
![image](https://user-images.githubusercontent.com/20850040/72327622-6e5d2000-36ec-11ea-937b-665dca17992d.png)

**Comment by PanJiaChen** [comment]
依赖问题。

**Comment by yeah188** [comment]
我意外碰到了这情况，用VCS对比了下，误删了根目录下的babel.config.js导致
