### ISSUE TITLE
建议同步element-ui版本

### ISSUE THREAD

**Issue by cranehe** [PanJiaChen/vue-element-admin#2447]
## Feature request（新功能建议）
建议同步element-ui版本，版本目前最新已经到2.11.0，框架还在2.7.0落下的有点多，不知道升级会涉及到的改动多吗？看看能不能帮上忙

**Comment by hedekun** [comment]
基于element封装的组件大多是应用层面的，升级应该没什么问题。

**Comment by PanJiaChen** [comment]
没什么不兼容的东西，可自行更新。
下个版本会同步更新。
