### ISSUE TITLE
大佬，tinymce文档中实在没找到相关配置

### ISSUE THREAD

**Issue by varSmallRookie** [PanJiaChen/vue-element-admin#245]
想要tinymce在code的head中输出link标签，但找遍tinymce的文档，都没有发现相关配置，恳请大神指点一下

**Comment by PanJiaChen** [comment]
没有太懂你的具体需求是什么

**Comment by varSmallRookie** [comment]
tinymce富文本编辑器中的source code中默认只显示body中的标签标签，我通过fullpage插件将整个html内容都给展示出来，但head标签中是空的，没有link标签，而我在content_css明明已经引入了css文件样式，，不知道这回我表达清楚了没

**Comment by PanJiaChen** [comment]
不是很能理解你要修改head干嘛
