### ISSUE TITLE
关于icon的疑惑

### ISSUE THREAD

**Issue by XdyGoGo** [PanJiaChen/vue-element-admin#2450]
请问icons下svg文件夹里的icon是动态生成还是你自己一个个创建的

**Comment by dongsuo** [comment]
https://juejin.im/post/59bb864b5188257e7a427c09

**Comment by XdyGoGo** [comment]
这里面有说我就不来问了 我目前是自己一个个创建的

**Comment by dongsuo** [comment]
哦，没注意，是自己创建的，应该主要是 iconfont.cn 上下载的

**Comment by PanJiaChen** [comment]
都是 [iconfont](https://www.iconfont.cn/)  下载的。

**Comment by huangshizhan** [comment]
> 都是 [iconfont](https://www.iconfont.cn/) 下载的。

在项目总我想用其他的字体图标

> 都是 [iconfont](https://www.iconfont.cn/) 下载的。

请问在哪可以看到下载到项目中所有的icon  ，我想用用其他的

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/tree/master/src/icons/svg

只有这些。
