### ISSUE TITLE
最新版本交互组件渲染问题

### ISSUE THREAD

**Issue by zszq** [PanJiaChen/vue-element-admin#2452]
最新版本的集成方案（没有国际化的）和基础模板按钮等渲染有问题，边角缺失等，在360和chrome上经常出现，而火狐没有出现过。最新版本的集成方案（国际化的）没有出现这个问题，不知道是什么问题。

![](http://ww1.sinaimg.cn/large/7459d5dbgy1g5s0cvfchyj20pu03smx3.jpg)

**Comment by PanJiaChen** [comment]
能在具体一点么？
