### ISSUE TITLE
请教一下大神们，如何在下拉框中选择图标icon，麻烦提供一下思路

### ISSUE THREAD

**Issue by imkinman** [PanJiaChen/vue-element-admin#2455]
## Question（提问）
如题，请大神们提供一下解决思路，万分感谢！！！

#### Steps to reproduce（问题复现步骤）

目前做出来的效果如下图所示。
问题1：如何获取所有本地支持的图标的名字，用于展示备选列表（是否需要创建一个array，将图标名称手动写入）
问题2：选择后如何将图标显示在输入框内

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/26222917/62671906-2e6e7000-b9cb-11e9-8647-f96e45e68026.png)

十分感谢~

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by babyyage** [comment]
应该很好弄的吧   1.在data里面定义一个list require图片地址 2下拉框的选项option 里面用的img标签 引用图片的list  不知道是不是你要的效果呢

**Comment by PanJiaChen** [comment]
1. 获取所以本地icons
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/icons/svg-icons.js

2. 显示icon

https://element.eleme.cn/#/zh-CN/component/select#zi-ding-yi-mo-ban

使用 element 的自定义模板。
