### ISSUE TITLE
是否能够做一下webpack升级到3.0+版本后，webpack相关配置的迁移方案呢？

### ISSUE THREAD

**Issue by GodStream** [PanJiaChen/vue-element-admin#246]
目前想试试升级webpack到3.0，但是会有不少的报错，希望可以提供一些参考。

**Comment by PanJiaChen** [comment]
本项目暂时不会升级`webpack`
`webpack2` => `webpack3` 并没有太多的 breaking change ，也不是很麻烦
参照 [vuejs-templates/webpack](https://github.com/vuejs-templates/webpack/tree/develop/template)

**Comment by PanJiaChen** [comment]
已发布@3.0 版本
webpack 使用了最新的@3.8.1
