### ISSUE TITLE
面包屑用 vue function api 重写报错

### ISSUE THREAD

**Issue by Ttou** [PanJiaChen/vue-element-admin#2460]
#### Screenshot or Gif（截图或动态图）
![深度截图_选择区域_20190809095129](https://user-images.githubusercontent.com/4298437/62748467-4efdff00-ba8b-11e9-90f3-5b2a1d3521cd.png)
![深度截图_选择区域_20190809095228](https://user-images.githubusercontent.com/4298437/62748492-6b9a3700-ba8b-11e9-99b1-52f89e3c32ae.png)

#### Other relevant information（格外信息）
- Your OS: DeepinLinux
- Node.js version: 10.16.0

**Comment by PanJiaChen** [comment]
等vue3.0正式发布之后会重构，暂时不会去兼容。

**Comment by Ttou** [comment]
这个问题在 `vue-function-api: 2.1.2` 版本中修复了：https://github.com/vuejs/vue-function-api/issues/53
