### ISSUE TITLE
vue-admin 通过 npm build:prod 打包后运行报 Uncaught SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by developersPHP** [PanJiaChen/vue-element-admin#2462]
## Question（提问）
vue-admin 通过 npm build:prod 打包后在nginx上运行当请求login后端服务时，报 Uncaught SyntaxError: Unexpected token u in JSON at position 0。其中，还没有发起post请求，在浏览器中就直接报错了

#### Steps to reproduce（问题复现步骤）
1、nginx配置
server{
        listen 8090;
        server_name localhost;
        client_max_body_size 100M;
        # vhost_traffic_status_filter_by_set_key $uri uris::$server_name;

    location / {
                root /usr/share/nginx/html;
                index index.html index.htm;
        }

        location /api {
                proxy_redirect off;
                #proxy_set_header Host $host;
                #proxy_set_header X-Real-IP $remote_addr;
                #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded for;
                proxy_pass http://192.168.8.69:8085/api;
                #include uwsgi_params;
                #uwsgi_pass 127.0.0.1:9002;
        }
    location /static {
                alias /usr/share/nginx/html/static;
        }
    # location /status {
       # vhost_traffic_status_display;
       # vhost_traffic_status_display_format html;
    # }
    # location /file {
    #     alias /data/yw_ops/gitlab;
    # }

2、镜像Dockerfile
FROM nginx:latest

COPY ./data/tt-smdb/vue-admin/dist /usr/share/nginx/html
COPY ./data/tt-smdb/ci/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 8090

3、package.json
{
  "name": "vue-admin-template",
  "version": "4.2.1",
  "description": "A vue admin template with Element UI & axios & iconfont & permission control & lint",
  "author": "Pan <panfree23@gmail.com>",
  "license": "MIT",
  "scripts": {
    "dev": "vue-cli-service serve",
    "build:prod": "vue-cli-service build",
    "build:stage": "vue-cli-service build --mode staging",
    "preview": "node hbuild/index.js --preview",
    "lint": "eslint --ext .js,.vue src",
    "test:unit": "jest --clearCache && vue-cli-service test:unit",
    "test:ci": "npm run lint && npm run test:unit",
    "svgo": "svgo -f src/icons/svg --config=src/icons/svgo.yml"
  },

  "dependencies": {
    "axios": "0.18.1",
    "element-ui": "2.7.2",
    "eslint-loader": "^2.1.2",
    "js-cookie": "2.2.0",
    "normalize.css": "7.0.0",
    "nprogress": "0.2.0",
    "path-to-regexp": "2.4.0",
    "vue": "2.6.10",
    "vue-router": "3.0.6",
    "vuex": "3.1.0"
  },

  "devDependencies": {
    "@babel/core": "7.0.0",
    "@babel/register": "7.0.0",
    "@vue/cli-plugin-babel": "3.6.0",
    "@vue/cli-plugin-eslint": "^3.9.1",
    "@vue/cli-plugin-unit-jest": "3.6.3",
    "@vue/cli-service": "3.6.0",
    "@vue/test-utils": "1.0.0-beta.29",
    "autoprefixer": "^9.5.1",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "10.0.1",
    "babel-jest": "23.6.0",
    "chalk": "2.4.2",
    "connect": "3.6.6",
    "eslint": "5.15.3",
    "eslint-plugin-vue": "5.2.2",
    "html-webpack-plugin": "3.2.0",
    "mockjs": "1.0.1-beta3",
    "node-sass": "^4.9.0",
    "runjs": "^4.3.2",
    "sass-loader": "^7.1.0",
    "script-ext-html-webpack-plugin": "2.1.3",
    "script-loader": "0.7.2",
    "serve-static": "^1.13.2",
    "svg-sprite-loader": "4.1.3",
    "svgo": "1.2.2",
    "vue-template-compiler": "2.6.10"
  },
  "engines": {
    "node": ">=8.9",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}

#### Other relevant information（格外信息）
- Your OS:
 centos7
- Node.js version: 
v10.16.1
- vue-element-admin version:  
v4.0+

**Comment by AdrianTao** [comment]
我也遇到了同样的问题，最后我注释掉main.js中的
```
import { mockXHR } from '../mock'
if (process.env.NODE_ENV === 'development') {
  mockXHR()
}
```
然后就不会出现这个错误了

**Comment by developersPHP** [comment]
好的，我已经解决了。
