### ISSUE TITLE
2019-08-09 master  分支，npm install 404  

### ISSUE THREAD

**Issue by hellothejava** [PanJiaChen/vue-element-admin#2464]
win10
nodejs：v10.16.2
错误如下：
![image](https://user-images.githubusercontent.com/19324069/62759541-2807f300-bab4-11e9-8d5f-58572435e397.png)

尝试nodejs重装、npm cache clean 、cnpm 都无效
望大神答疑

**Comment by wumoxi** [comment]
把package-lock.json删除、node_modules删除、npm cache clean，之后使用yarn替代npm安装即可！

**Comment by wumoxi** [comment]
> win10
> nodejs：v10.16.2
> 错误如下：
> ![image](https://user-images.githubusercontent.com/19324069/62759541-2807f300-bab4-11e9-8d5f-58572435e397.png)
> 
> 尝试nodejs重装、npm cache clean 、cnpm 都无效
> 望大神答疑

把package-lock.json删除、node_modules删除、npm cache clean，之后使用yarn替代npm安装即可！
