### ISSUE TITLE
项目的Eslint完全是灾难级别的啊

### ISSUE THREAD

**Issue by Rain20188** [PanJiaChen/vue-element-admin#2468]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by hedekun** [comment]
习惯了就好。

**Comment by zangxx66** [comment]
我也这么觉得，看着那些报错很无语

**Comment by PanJiaChen** [comment]
可以参看阅读 https://panjiachen.gitee.io/vue-element-admin-site/zh/guide/advanced/eslint.html

lint 能保证你写出更好的代码。如果你不想要也可以关闭，文档已标注。
