### ISSUE TITLE
在permission.js路由权限管理中

### ISSUE THREAD

**Issue by liudid** [PanJiaChen/vue-element-admin#2469]
![1941d9397dad93d6b18e8d10350b43d](https://user-images.githubusercontent.com/31311845/62831970-211ae500-bc5a-11e9-817e-bef2f256aa76.png)

这个地方，如果获取角色的请求reject了，会catch到这个error，但是这个error的报错信息是与vue相关的，就导致了跳转到login 和resetToken不会执行。

我用的是最新版本的vue-element-admin  没有修改过项目本身的代码，登录的时候有时候会出现这种问题，请问怎么解决呢，请求大神帮助呀
![bcfe2b18571e2c2490a7eb3ae8980c3](https://user-images.githubusercontent.com/31311845/62832010-d9488d80-bc5a-11e9-9632-fb464ee8b10c.png)

**Comment by XiaAok** [comment]
你好，怎么解决的
