### ISSUE TITLE
浏览器或者页面的宽度发生变化时, element表格会出现滚动条

### ISSUE THREAD

**Issue by hchaojie** [PanJiaChen/vue-element-admin#247]
步骤：
1. 点击左侧菜单“综合实例” -> “table” -> "动态table"，
2. 点击顶部的汉堡包按钮，收起菜单栏
3. 再次点击汉堡包按钮，展开菜单栏
现象：步骤3的过程中，页面中间的表格会出现横向的滚动条。动画结束后消失。
环境：
windows10 + chrome 61
怀疑是element-ui本身的问题

**Comment by PanJiaChen** [comment]
我试了新版本的 `element-ui@2.0` 也还有这个问题
暂时解决方案 可以将 `.el-table__body-wrapper`  改成 `overflow: hidden;`  , 不过可能有位置bug。
建议可以去 `element-ui` 提一个issue

**Comment by PanJiaChen** [comment]
新版本element-ui 已修复该问题。
