### ISSUE TITLE
TypeError: (0 , xxxxxx) is not a function

### ISSUE THREAD

**Issue by Xiaohantx** [PanJiaChen/vue-element-admin#2471]
## Question（提问）

```
[Vue warn]: Error in mounted hook: "TypeError: (0 , _utils.debounce) is not a function"

found in
```

```
user.js?0f9a:104 Uncaught (in promise) TypeError: (0 , _auth.removeAuth) is not a function
```

```
TypeError: (0 , _auth.setAuth) is not a function
```

git clone 最仓库最新代码后很多操作上都出现了这个错误，不知道是为什么...

#### Screenshot or Gif（截图或动态图）

![](https://cdn.markone.xyz/images/20190812134451.png)

#### Other relevant information（格外信息）
- Your OS: mac os
- vue-element-admin version: 2.7.0

**Comment by Xiaohantx** [comment]
https://cdn.markone.xyz/images/20190812134451.png

**Comment by Xiaohantx** [comment]
是把老版本的部分自己写的页面，utils和store代码移动到新的里面

**Comment by hedekun** [comment]
是在`utils`里没有`debounce`这个方法吧。

**Comment by vermilionlovewz** [comment]
遇到一样的问题了
