### ISSUE TITLE
登录进去之后点击左侧菜单栏，浏览器控制台报这个错误Error in nextTick: "TypeError: undefined is not iterable!"

### ISSUE THREAD

**Issue by Twf520** [PanJiaChen/vue-element-admin#2474]
[Vue warn]: Error in nextTick: "TypeError: undefined is not iterable!"

found in

---> <TagsView> at src/views/layout/components/TagsView.vue
       <Layout> at src/views/layout/Layout.vue
         <App> at src/App.vue
           <Root>

![image](https://user-images.githubusercontent.com/45480915/62930228-9a4b4100-bdee-11e9-97fa-e424f92bc7b0.png)

**Comment by Twf520** [comment]
只有每次登录之后，第一次点击菜单栏会出现这个问题。页面刷新之后，或者第二次点击其他菜单栏，都是正常的，项目继续正常运行。退出登录再进，又出现。

**Comment by Twf520** [comment]
就没人出现这种错误吗？

**Comment by Twf520** [comment]
已解决

**Comment by Twf520** [comment]
> [Vue warn]: Error in nextTick: "TypeError: undefined is not iterable!"
> 
> found in
> 
> ---> at src/views/layout/components/TagsView.vue
> at src/views/layout/Layout.vue
> at src/App.vue
> ![image](https://user-images.githubusercontent.com/45480915/62930228-9a4b4100-bdee-11e9-97fa-e424f92bc7b0.png)

**Comment by Twf520** [comment]
已解决

**Comment by binxyz** [comment]
咋解决的，
![image](https://user-images.githubusercontent.com/16433644/66450319-a3712b00-ea8a-11e9-99b8-d531c384dec9.png)

![image](https://user-images.githubusercontent.com/16433644/66450329-aec45680-ea8a-11e9-87fb-77a5a002101f.png)


w我报这两个错误，找不到原因

**Comment by smwanyi** [comment]
[我也遇到这个问题，找到解决方法了](https://github.com/PanJiaChen/vue-element-admin/issues/2955#issuecomment-627699588)
