### ISSUE TITLE
左侧路由导航不刷新

### ISSUE THREAD

**Issue by MichaelPorter0** [PanJiaChen/vue-element-admin#2476]
![1565755819](https://user-images.githubusercontent.com/38281116/62994041-8229ff00-be8c-11e9-93f6-cb0f8631d14f.png)

我的路由导航不会自动刷新，我尝试把他们都打印了出来
![1565755906(1)](https://user-images.githubusercontent.com/38281116/62994083-b7cee800-be8c-11e9-8377-5f3e933fc08e.png)
其中accessRoutes是我的动态路由，他确实与他的权限匹配到了但是，执行
`router.addRoutes(accessRoutes)`
后左侧的导航栏却并没有刷新
下方我也调用了
` next({ ...to, replace: true })`
来等待router刷新完成
但是他还是没有变化。。。。。

**Comment by MichaelPorter0** [comment]
我发现只要是asyncRoutes里的就不会出现，即使roles里没有设置

**Comment by hedekun** [comment]
这是两个不同的逻辑。
左侧导航栏`@/layout/components/sidebar/index.vue`中
` <sidebar-item v-for="route in permission_routes" :key="route.path" :item="route" :base-path="route.path" />`可以看到要生成导航栏需要当前符合的权限数组。
在`addRoutes`之前，需要将这`accessRoutes`放在`permission_routes`里哦。
作者通过vuex实现的。具体代码看一下就懂了

**Comment by MichaelPorter0** [comment]
@hedekun  
谢谢。成功解决了

**Comment by yuuhou** [comment]
nice,解决了...弄了一个下午才发现布局组件Sidebar遍历的是permission_routes.
