### ISSUE TITLE
Can i add custom header in file xlsx when export excel?

### ISSUE THREAD

**Issue by CuongStf** [PanJiaChen/vue-element-admin#2478]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by vickenliu** [comment]
certainly you can, you can change the header at the excel-export part, eg: https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/excel/export-excel.vue#L82

**Comment by CuongStf** [comment]
> certainly you can, you can change the header at the excel-export part, eg: https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/excel/export-excel.vue#L82

No, my mean is header on row in file excel which exported. example, when export i'm want insert line "CUSTOM HEADER IN A ROW" in row
