### ISSUE TITLE
会导致element-ui时间选择器里面小时分钟秒选择偏移

### ISSUE THREAD

**Issue by Lelouch-Xue** [PanJiaChen/vue-element-admin#2484]
#### Screenshot or Gif（截图或动态图）

![7626CA4E-1146-4281-BC5E-CD0267352598](https://user-images.githubusercontent.com/15809929/63137795-34d39c00-c00a-11e9-9dca-6b635fd0b971.png)

会导致element-ui时间选择器里面小时分钟秒选择偏移

**Comment by PanJiaChen** [comment]
什么版本的?

**Comment by cncp20** [comment]
我也遇到同样的问题了，element-ui版本2.11.1

**Comment by PanJiaChen** [comment]
@cncp20 我指 vue-element-admin 什么版本？
