### ISSUE TITLE
账户切换，快捷标签栏按钮显示的是上一个账户的

### ISSUE THREAD

**Issue by xinnian1992** [PanJiaChen/vue-element-admin#2485]
账户切换，快捷标签栏按钮显示的是上一个账户的

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/2632

**Comment by fmy518** [comment]
这个问题没有人遇到吗   项目中已经是最新的登出写法，但是还是有这个问题。
dispatch('tagsView/delAllViews', null, { root: true })
确实清空了tagsview。不过新账户进来还是默认打开上一次的页面，真的奇怪。

**Comment by kevinchuxu** [comment]
> 这个问题没有人遇到吗 项目中已经是最新的登出写法，但是还是有这个问题。
> dispatch('tagsView/delAllViews', null, { root: true })
> 确实清空了tagsview。不过新账户进来还是默认打开上一次的页面，真的奇怪。

确认一下退出后的重置链接hash地址是否为空

**Comment by violetrosez** [comment]
貌似还是有整个问题啊，换个用户登录不该打开上一次的页面了

**Comment by fmy518** [comment]
我已经解决了。在Navbar.vue中的退出方法中
 async logout() {
      await this.$store.dispatch('user/logout')
      this.$router.push(`/login?redirect=${this.$route.fullPath}`)
    },
路由push后面的日志不要加redirect。

**Comment by caohuiboss** [comment]
退出的时候清除redirect=${this.$route.fullPath}

**Comment by oracle-gbc** [comment]
我遇到的问题是，退出登录之后，在登录，登录不上， 、src/store/modlues/user.js/(getInfo)这个方法显示里面的参数为空，但是我在打印出发之前的方法显示是有数据的，还望有人讲解一下

**Comment by FightingLeek** [comment]
嗯挺好

**Comment by zhouxingxing495132314** [comment]
登录时判断query惹的祸

**Comment by hikktn** [comment]
好像完全没解决。。。还是切换用户，登录进来还是上一个用户打开的页面。
我这边的改动是，Navbar.vue
`this.$router.push(`/login?redirect=/`)`
