### ISSUE TITLE
换位置无法运行！报错！

### ISSUE THREAD

**Issue by KevinBlack** [PanJiaChen/vue-element-admin#2488]
下载zip包解压，然后安装依赖可以运行。但是拷贝到别处就不能运行，无论是重新安装依赖，还是连依赖一起拷贝过去都不行！
报错信息：
SyntaxError: Unexpected string
/Users/fu/Downloads/ele-admin/ele-admin/mock/index.js:1
(function (exports, require, module, __filename, __dirname) { import "core-js/modules/es6.regexp.constructor";
求教大神这是为什么呢？

**Comment by yu513517** [comment]
同样的问题，求解答

**Comment by KevinBlack** [comment]
> 差不多的问题
> 
> SyntaxError: Unexpected string
> /Applications/aaa/mock/index.js:1
> import "core-js/modules/es6.regexp.constructor";
> 
> 这是我的提示
> 
> 想把mock-server拿到自己项目中用，但是总提示这个，没法启动程

**Comment by KevinBlack** [comment]
> 差不多的问题
> 
> SyntaxError: Unexpected string
> /Applications/aaa/mock/index.js:1
> import "core-js/modules/es6.regexp.constructor";
> 
> 这是我的提示
> 
> 想把mock-server拿到自己项目中用，但是总提示这个，没法启动程

应该是跟包里的隐藏文件有关！我的就是没拷贝隐藏文件，所以导致运行失败的！
