### ISSUE TITLE
为什么框架里要实现两种mock？

### ISSUE THREAD

**Issue by bi-kai** [PanJiaChen/vue-element-admin#2490]
main.js中：
![image](https://user-images.githubusercontent.com/15070379/63209744-a3525000-c117-11e9-804c-39e53ac492a6.png)
改成开发模式，实现纯前端的mock。

为什么还要模拟后端的mock？
![image](https://user-images.githubusercontent.com/15070379/63209740-95043400-c117-11e9-9e02-4391fac04152.png)

**Comment by PanJiaChen** [comment]
文档写了。
https://panjiachen.gitee.io/vue-element-admin-site/zh/guide/essentials/mock-api.html
