### ISSUE TITLE
login页面登录时出错

### ISSUE THREAD

**Issue by yh88205** [PanJiaChen/vue-element-admin#2493]
## Question（提问）
安装成功，个人抱着学习态度看模板，但一开始就出现登录出错，刚刚开始学习，希望能够获得解答。
个人感觉是代理问题，查了很久也没不知道该怎么解决。

#### Screenshot or Gif（截图或动态图）
![截图1](https://user-images.githubusercontent.com/22805187/63215705-192cda80-c15d-11e9-9302-07551bfd49e8.png)
![截图2](https://user-images.githubusercontent.com/22805187/63215706-1f22bb80-c15d-11e9-84e2-3e6527a35b6a.png)
![截图3](https://user-images.githubusercontent.com/22805187/63215709-2649c980-c15d-11e9-8016-0fff282b5315.png)

#### Other relevant information（格外信息）
- Your OS:win10 64bit
- Node.js version:v10.16.2
- vue-element-admin version:最新

**Comment by cjy365535149** [comment]
你这个应该是代理问题，注释掉proxy和after。
看你的端口也有些怪。我现在遇到端口的问题了。

**Comment by qcmoke** [comment]
我也遇到了同样的问题，请求答复

**Comment by sachinbhutani** [comment]
i get the same error on mac OS x Node.js version:v10.16.2

**Comment by cjy365535149** [comment]
新的pakage-lock会加载一个有问题的依赖，用一个老的pakage-lock应该就行了。看看我仓库下的cjy365535149/JayWeb pakage-lock可用不

**Comment by yh88205** [comment]
> 新的pakage-lock会加载一个有问题的依赖，用一个老的pakage-lock应该就行了。看看我仓库下的cjy365535149/JayWeb pakage-lock可用不

用了您的package-lock还是不行，也看了您的解决端口的那个方法，端口也无法锁定为9528，不知道是什么问题

**Comment by cjy365535149** [comment]
楼上朋友是否重新install

**Comment by happyliyingzhi** [comment]
按照楼上朋友的操作，可以解决问题，感谢大佬

**Comment by MH121017** [comment]
@happyliyingzhi 请问你是如何解决的，我也遇到了同样的问题

**Comment by zhaojun0193** [comment]
> 新的pakage-lock会加载一个有问题的依赖，用一个老的pakage-lock应该就行了。看看我仓库下的cjy365535149/JayWeb pakage-lock可用不

感谢，已经解决了这个问题

**Comment by xxt1901981503** [comment]
> @happyliyingzhi 请问你是如何解决的，我也遇到了同样的问题

用cjy365535149/JayWeb pakage-lock的文件，重新执行以下命令就可以了
npm install --registry=https://registry.npm.taobao.org
npm run dev

**Comment by MH121017** [comment]
> > @happyliyingzhi 请问你是如何解决的，我也遇到了同样的问题
> 
> 用cjy365535149/JayWeb pakage-lock的文件，重新执行以下命令就可以了
> npm install --registry=https://registry.npm.taobao.org
> npm run dev

好的，我试试

**Comment by Ray0401** [comment]
我也是用的你的package-lock.json文件，然后重新install了，项目启动起来登录的时候还是报错> 新的pakage-lock会加载一个有问题的依赖，用一个老的pakage-lock应该就行了。看看我仓库下的cjy365535149/JayWeb pakage-lock可用不

**Comment by Ray0401** [comment]
> 新的pakage-lock会加载一个有问题的依赖，用一个老的pakage-lock应该就行了。看看我仓库下的cjy365535149/JayWeb pakage-lock可用不

我按照你的方法试了后，还是不行

**Comment by Ray0401** [comment]
请问有谁解决登录报错的问题了吗

**Comment by mybichu** [comment]
> > > @happyliyingzhi 请问你是如何解决的，我也遇到了同样的问题
> > 
> > 
> > 用cjy365535149/JayWeb pakage-lock的文件，重新执行以下命令就可以了
> > npm install --registry=https://registry.npm.taobao.org
> > npm run dev
> 
> 好的，我试试

感谢，用了您的办法，解决了这个问题。定位了一个下午，是真的坑。

**Comment by Ray0401** [comment]
> > > > @happyliyingzhi 请问你是如何解决的，我也遇到了同样的问题
> > > 
> > > 
> > > 用cjy365535149/JayWeb pakage-lock的文件，重新执行以下命令就可以了
> > > npm install --registry=https://registry.npm.taobao.org
> > > npm run dev
> > 
> > 
> > 好的，我试试
> 
> 感谢，用了您的办法，解决了这个问题。定位了一个下午，是真的坑。

你好，我也是用的这个package-lock,然后重新安装并启动也不行呀~

**Comment by mybichu** [comment]
> > > > > @happyliyingzhi 请问你是如何解决的，我也遇到了同样的问题
> > > > 
> > > > 
> > > > 用cjy365535149/JayWeb pakage-lock的文件，重新执行以下命令就可以了
> > > > npm install --registry=https://registry.npm.taobao.org
> > > > npm run dev
> > > 
> > > 
> > > 好的，我试试
> > 
> > 
> > 感谢，用了您的办法，解决了这个问题。定位了一个下午，是真的坑。
> 
> 你好，我也是用的这个package-lock,然后重新安装并启动也不行呀~

得把package-lock和package两个文件一起替换，再重新安装，启动试试。

**Comment by Ray0401** [comment]
> > > > > > @happyliyingzhi 请问你是如何解决的，我也遇到了同样的问题
> > > > > 
> > > > > 
> > > > > 用cjy365535149/JayWeb pakage-lock的文件，重新执行以下命令就可以了
> > > > > npm install --registry=https://registry.npm.taobao.org
> > > > > npm run dev
> > > > 
> > > > 
> > > > 好的，我试试
> > > 
> > > 
> > > 感谢，用了您的办法，解决了这个问题。定位了一个下午，是真的坑。
> > 
> > 
> > 你好，我也是用的这个package-lock,然后重新安装并启动也不行呀~
> 
> 得把package-lock和package两个文件一起替换，再重新安装，启动试试。

试了，还是不行

**Comment by YC-Cheung** [comment]
登录出错跟没有成功启用配置文件设置的端口有关。请参考 [#2492 ](url)

**Comment by Ray0401** [comment]
问题已经解决。昨天就是用的cnpm intstall，导致一直没能解决这个问题，刚才试了下npm install ，端口号的问题解决了，谢谢各位

**Comment by Ray0401** [comment]
> 问题已经解决。昨天就是用的cnpm intstall，导致一直没能解决这个问题，刚才试了下npm install ，端口号的问题解决了，谢谢各位


portfinder 版本降为  1.0.21

**Comment by yh88205** [comment]
谢谢，问题已解决

**Comment by pythonzm** [comment]
同样的问题，试了楼上各位大佬的方法都还是不行，不过我在Win10的系统没有问题，但是在Win7系统上就有问题，这跟系统有关系么？
