### ISSUE TITLE
windows 运行建议

### ISSUE THREAD

**Issue by tyhyly** [PanJiaChen/vue-element-admin#25]
依赖都安装了，node是7.9版本，执行npm run build：prod命令时，报错NODE_ENV不是内部或外部命令，sit同理。执行npm run dev的时候也报错，不支持es6...扩展符，看了下babelrc配置，好像也没啥问题，试了n次，去babel官网查了下也没有，这个问题有没有遇到过的~~（windows7系统）

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/21

**Comment by tyhyly** [comment]
成功了，提醒下其他童鞋，windows下有几个问题：node-sass的问题，通过cnpm解决或者单独下载node-sass包，拷贝到项目node_modules目录下；（注意：该项目不能删除package.json文件夹下的node-sass，因为里面很多文件依赖sass-loader，sass-loader需要依赖node-sass）；第二个是要安装npm install cross-env,修改package.json文件，具体配置见楼主issue21NODE_ENV的问题；第三个问题，凡是关于编辑器或IDE问题语法报错，查找对应编辑器插件或在IDE里面进行ES6语法设置（如果设置完，run项目时候还报错，那要考虑是环境的问题和依赖的问题）

**Comment by Selina9101118** [comment]
npm install --registry=https://registry.npm.taobao.org执行的时候，
出现错误
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
然后又去下载python安装后设置了环境变量，
然后又重新执行npm install --registry=https://registry.npm.taobao.org
启动项目，一直报没有sass-loader和node-sass模块，
然后我的解决方案是分别执行这两条命令：
1、npm install sass-loader --save-dev
2、npm install node-sass --save-dev
头痛了一下午的问题终于解决了，泪奔啊。
希望对你们有帮助。

**Comment by shaojingjing** [comment]
安装完成以后，npm run dev的时候 报错404。   查看了一下报错信息 ，  发现是node-sass 安装失败，重新安装两次还是失败以后  :用cnpm install node-sass安装成功，现在运行成功了

**Comment by dpcrman** [comment]
`graphic.extendShape = function (opts) {
        return Path.extend(opts);
    };`
Path.extend is not a function
I can't handle this problem

**Comment by PanJiaChen** [comment]
@dpcrman https://github.com/PanJiaChen/vue-element-admin/issues

**Comment by tomatojacky** [comment]
搞了一小时没启动起来，我啥都不说了
cnpm install node-sass@4.8.3

**Comment by bestshanjinghao** [comment]
npm install 一直出错
1. 克隆了下项目
2. npm install cnpm
3. cnpm install
4. cnpm install cross-env
5. npm run dev
这么做之后就可以了

npm run build 出错  提示missing script: build
看了下package.json中有build

使用npm run build:prod 可以了

**Comment by dpcrman** [comment]
> @dpcrman #278

thanks a lot,it works

**Comment by Annriy07** [comment]
win10系统，1、git clone https://github.com/PanJiaChen/vue-element-admin.git
进入vue-element-admin目录里
2、npm install  系统蓝屏
有遇到过种的吗？

**Comment by zhuph** [comment]
npm i node-sass --sass_binary_site=https://npm.taobao.org/mirrors/node-sass/

**Comment by xiaolitudd01** [comment]
我试过了很多办法，最后。。。都不行
放弃npm使用yarn，然后成功了！

**Comment by WanKang512** [comment]
Error: Cannot find module 'D:\admin\node_modules\@vue\cli-service\bin\vue-cli-service.js'
npm run dev后报上面这个错，什么原因

**Comment by Shirleyice** [comment]
> 

请问你解决了吗
我也遇到了

**Comment by wuningfei** [comment]
npm install always errors
