### ISSUE TITLE
自动更新

### ISSUE THREAD

**Issue by lijiasusu** [PanJiaChen/vue-element-admin#250]
保存页面，浏览器不能自动刷新是怎么回事？

**Comment by PanJiaChen** [comment]
能说的具体一点么？

**Comment by lijiasusu** [comment]
就是webpack热加载自动更新问题，比如我修改了页面某个地方展示内容，得手动刷新一下浏览器，才会发生变化

**Comment by PanJiaChen** [comment]
webpack hmr 没发现什么问题，能再具体一点吗

**Comment by lijiasusu** [comment]
比如说tablel栏目里面的综合table，我把“序号”这个字段改成“xuhao”,保存文件后页面会自动更新为“xuhao”,
把序号下面对应的变量{{scope.row.id}}改成“aa”,保存文件，页面没有变化，需要我刷新浏览器，才会变成“aa”

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/31703625-11ae6cf2-b3a3-11e7-896d-758f0c24c3c3.png)

可以看一下eventstream是否有东西，有问题可以去webpack issue下搜搜，和本项目关系不大。
话说你webpack版本是什么

**Comment by lijiasusu** [comment]
我直接克隆的你的项目，然后就改了这么一个地方，然后就不对了，webpack版本:2.6.1

**Comment by PanJiaChen** [comment]
和你操作环境也有关系

**Comment by lijiasusu** [comment]
![image](https://user-images.githubusercontent.com/23130595/31704699-0b83aad2-b415-11e7-945a-3f9094252e1e.png)

**Comment by Shaco223** [comment]
table内的数据好像是需要刷新才能改变的，其他页面的热加载是好的

**Comment by shichengjiao** [comment]
> table内的数据好像是需要刷新才能改变的，其他页面的热加载是好的

不是的 在对应路由meta设置noCache: true就可以自动刷新显示了
