### ISSUE TITLE
为什么npm run dev会打开两个浏览器标签页

### ISSUE THREAD

**Issue by qq284590533** [PanJiaChen/vue-element-admin#2506]
如题

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/2410

**Comment by microkof** [comment]
> #2410

衩哥，真不是vue-cli的锅，我的全新系统装了最新版vue-cli依然是打开2个窗口，虽然不影响使用，但真不是vue-cli的锅。我的版本 3.11.0 是最新的啊。
