### ISSUE TITLE
修改哪些配置文件可以解决生产环境下的跨域问题

### ISSUE THREAD

**Issue by wangshiminhome** [PanJiaChen/vue-element-admin#2509]
前端需要修改哪些文件内容可以解决跨域问题？

**Comment by Twf520** [comment]
const merge = require('webpack-merge')
const prodEnv = require('./prod.env')
const testEnv = require('./test.env')

**Comment by Twf520** [comment]
build里面的webpack文件，还有package.json里面的scripts

**Comment by Twf520** [comment]
多环境配置

**Comment by wangshiminhome** [comment]
> build里面的webpack文件，还有package.json里面的scripts

您好 目前我已经修改
![image](https://user-images.githubusercontent.com/46372007/63562775-6d86ee80-c591-11e9-8cb7-381f2ce38c53.png)
![image](https://user-images.githubusercontent.com/46372007/63562791-7d063780-c591-11e9-8c79-2330e1df4794.png)
并且后端也已经设置了跨域
![image](https://user-images.githubusercontent.com/46372007/63562829-97401580-c591-11e9-8f4d-6c0e148a55bd.png)
但是还是出现跨域问题
![image](https://user-images.githubusercontent.com/46372007/63562847-aaeb7c00-c591-11e9-94f7-fb11804db29a.png)
这需要怎么解决呢
