### ISSUE TITLE
tinymce 中我输入的内容  清空问题

### ISSUE THREAD

**Issue by youngchen1987** [PanJiaChen/vue-element-admin#251]
tinymce 中我输入的内容 我可以通过v-model 获取到，但是如果我清空v-model对应的内容   却没有情况tinymce中的内容  该如何清空？

**Comment by PanJiaChen** [comment]
不是很理解你为什么要在用 tinymce 的值。。。
如果真要清空的话 可以通过 `refs.xxx.setContent()` 来设置 tinymce 的值

**Comment by youngchen1987** [comment]
因为我是新建表单功能   我新建完成后  需要把新建表单里边的内容都清空

**Comment by youngchen1987** [comment]
![image](https://user-images.githubusercontent.com/11566474/31709461-b835e8bc-b424-11e7-99c1-1d6d74000095.png)

**Comment by youngchen1987** [comment]
按照你说的方式 好像不行哦

**Comment by PanJiaChen** [comment]
更新一下代码，刚刚新增了这个方法
https://github.com/PanJiaChen/vue-element-admin/commit/9463c50e06ee4dfbe1956d48fc4df68bc55507fa

**Comment by youngchen1987** [comment]
谢谢  可以了！

**Comment by c-yyy** [comment]
> 我今天刚用 tynymce，发现只要编辑器打开过一次后，再修改了v-model中的值（如切换了另一个文章），编辑器中的内容不会变化呢。
> 这个要如何解决，必须自己调用 `refs.xxx.setContent()` 吗？
> ![20180916161642114](https://user-images.githubusercontent.com/5575008/45594364-fda8d500-b9cb-11e8-9735-9020ad6736d8.png)
> ![20180916161713671](https://user-images.githubusercontent.com/5575008/45594365-00a3c580-b9cc-11e8-9e9c-dc35f9541c3d.png)

解决了么？用了refs.xxx.setContent()就多监听了一次，后面还是不改变了。

**Comment by lab023** [comment]
> > 我今天刚用 tynymce，发现只要编辑器打开过一次后，再修改了v-model中的值（如切换了另一个文章），编辑器中的内容不会变化呢。
> > 这个要如何解决，必须自己调用 `refs.xxx.setContent()` 吗？
> > ![20180916161642114](https://user-images.githubusercontent.com/5575008/45594364-fda8d500-b9cb-11e8-9735-9020ad6736d8.png)
> > ![20180916161713671](https://user-images.githubusercontent.com/5575008/45594365-00a3c580-b9cc-11e8-9e9c-dc35f9541c3d.png)
> 
> 解决了么？用了refs.xxx.setContent()就多监听了一次，后面还是不改变了。

解决的问题是对象更新了, Tinymce不刷新数据. 这样写是可以解决问题的, 相当于每次点击都手动更新编辑框内容. 如果你多点两次就不更新了, 把对象打印出来看看.

**Comment by imyaba** [comment]
element Dialog弹出框 tinymce编辑器内置的弹出菜单弹出 在该编辑下面不能用

![图片展示](https://user-images.githubusercontent.com/41137603/91284289-496e7680-e7be-11ea-9831-fe012948ae15.png)

**Comment by fengxingsoft** [comment]
_21212****_

> ````
