### ISSUE TITLE
在utils/index.js 引入@/store 报错 ，是写法出错吗

### ISSUE THREAD

**Issue by zhangneil** [PanJiaChen/vue-element-admin#2510]
![image](https://user-images.githubusercontent.com/6257293/63505410-1851cb00-c506-11e9-95e8-bcbedf1a5e04.png)

**Comment by zhangneil** [comment]
即便是下载了新的包 下来 引用就会报错

**Comment by zhangneil** [comment]
npm 版本6.9.0

**Comment by Twf520** [comment]
import store from '../store'
试试这样
