### ISSUE TITLE
此框架下axios onDownloadProgress 功能失效 单页面正常

### ISSUE THREAD

**Issue by hiair2323** [PanJiaChen/vue-element-admin#2512]
onDownloadProgress has progressEvent.total property with zero value
`                
axios.get('https://32323233.oss-cn-beijing.aliyuncs.com/1.pdf', {
                                    onDownloadProgress: function(progressEvent) {
                                      console.log(progressEvent);
                                      
                                    },
                                  })
                                  .then(response => {})
                                  .catch(res => {})`

[https://s2.ax1x.com/2019/08/23/mDLV1g.png](url)
[https://s2.ax1x.com/2019/08/23/mDOFbR.png](url)
已经尝试了axios升级 重新安装  页面里面单独引入  还是老样子
是跟什么插件有冲突吗

**Comment by PengMai1998** [comment]
请问你是怎么解决的？
