### ISSUE TITLE
require default 问题

### ISSUE THREAD

**Issue by Xiongzhenyu** [PanJiaChen/vue-element-admin#252]
你好，我在使用 _import_development.js 的时候发现会报错，请问是什么原因：

![image](https://user-images.githubusercontent.com/5298655/31730333-3e9fed40-b3f7-11e7-841f-8511681aa69c.png)
![image](https://user-images.githubusercontent.com/5298655/31730281-13c505e2-b3f7-11e7-8421-6305e0e47e9f.png)
![image](https://user-images.githubusercontent.com/5298655/31730305-2ab95744-b3f7-11e7-9bd4-3b3795c21249.png)

**Comment by PanJiaChen** [comment]
Duplicate of #231 
注意vue-loader 需v13.0.0 以上版本

**Comment by Xiongzhenyu** [comment]
当前package.json "vue-loader": "^13.0.5"

**Comment by Xiongzhenyu** [comment]
npm list vue-loader
vue-loader@13.3.0

**Comment by PanJiaChen** [comment]
仔细看了一下报错
![image](https://user-images.githubusercontent.com/8121621/31750494-0a2be100-b446-11e7-8316-31603a032a9f.png)
怎么感觉是你路径没写对

**Comment by Xiongzhenyu** [comment]
component: require('@/views/login/index.vue').default  这样是可以正确打开的

module.exports = file => require('@/views/' + file + '.vue').default   
component: _import('login/index')     这样就报错了   😕

**Comment by PanJiaChen** [comment]
你能截一下你具体的代码么？

**Comment by Xiongzhenyu** [comment]
我找到原因了：
// import { Navbar, Sidebar, AppMain, Footerbar } from 'views/layout'

import Navbar from './Navbar'

import Sidebar from './Sidebar'

import AppMain from './AppMain'

import Footerbar from './Footerbar'

注释的那行的错误 :)   我和你项目采用了相同的写法  在 layout 文件夹下写了一个 index.js 

export { default as Navbar } from './Navbar'

export { default as Sidebar } from './Sidebar'

export { default as AppMain } from './AppMain'

export { default as Footerbar } from './Footerbar'

不过看起来并没有生效

**Comment by Xiongzhenyu** [comment]
已解决 happy weekday 😘

**Comment by PanJiaChen** [comment]
👍
