### ISSUE TITLE
npm run dev的时候报错

### ISSUE THREAD

**Issue by jackC58** [PanJiaChen/vue-element-admin#2521]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:
![image](https://user-images.githubusercontent.com/22877055/63756117-6857d580-c8ea-11e9-964f-e0a49e12acae.png)

**Comment by Ant-Xiaohui** [comment]
问题解决了吗 我跟你一样的问题

**Comment by jackC58** [comment]
解决了，是我的node版本太低  升下级就OK了，但是现在大多的vue项目都不太支持最新版本，最好不要把现在的版本覆盖了

**Comment by Ant-Xiaohui** [comment]
不覆盖现在的版本？这个要如何操作？

**Comment by jackC58** [comment]
这个你就自己百度把，我当时是升级完后   原来的vue项目启动不了了，才告诉你的

**Comment by jackC58** [comment]
如果你就这一个vue项目的话，就不必担心了
