### ISSUE TITLE
Performance of `TagView`

### ISSUE THREAD

**Issue by thearabbit** [PanJiaChen/vue-element-admin#2522]
Excuse me, It have problem or not (performance) if we use a lot of `TagView`? (Slow????)
(It have a big data on any pages)

**Comment by PanJiaChen** [comment]
This is because `TagView` is based on keep-alive. When you open a lot of pages, it will cache a lot of `vnode` and `componentInstance` in memory.

**Comment by thearabbit** [comment]
@PanJiaChen for your reply 👍 
This is the problem for me.
Could you example `Open Modal with Router` option in this template?
I tried any solution about this, but not work fine, because I would like to use dynamic `default component` (Open modal from anywhere)
```js
<div id="app">
  <h1>Modal with Router</h1>
  <ul>
    <li>
      <router-link to="/">/foo</router-link>
    </li>
  </ul>
  <router-view class="page"></router-view>
  <router-view class="modal" name="modal"></router-view>
</div>

const Foo = { template: '<div>foo <br><router-link to="/modal">/Modal</router-link></div>' }
const Bar = { template: '<div>bar</div>' }

const router = new VueRouter({
  mode: 'history',
  routes: [
    { path: '/',
      components: {
      	default: Foo
      }
    },
    {
      path: '/modal',
      components: {
        /* default: Foo, */ // Would like to use dynamic current component, because I open `Modal` from anywhere
        modal: Bar,
      }
    }
  ]
})
```

**Comment by PanJiaChen** [comment]
Like this https://medium.com/@rmmmsy/creating-and-animating-a-modal-component-as-a-child-route-using-vue-41a275a51d0c ?

**Comment by thearabbit** [comment]
thanks again, but my case is:
Open others `Modal` from difference pages.
Example:
- `Modal A` could open from many `Page A, Page B, Page C...`. and all pages have own router
- `Page A` have many dynamic `Modal`...

**Comment by thearabbit** [comment]
I closed, if you have any share please
