### ISSUE TITLE
Tinymce 富文本怎么汉化成中文的知道吗

### ISSUE THREAD

**Issue by xiechunhao** [PanJiaChen/vue-element-admin#2523]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/46cc375d0d91261a7962715dd48e66e10e8c5872/src/components/Tinymce/index.vue#L119
