### ISSUE TITLE
怎么没有static静态资源文件夹

### ISSUE THREAD

**Issue by acgta5** [PanJiaChen/vue-element-admin#2524]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by KyleChen2019** [comment]
因为现在版本使用的脚手架是vue-cli3.
vue-cli3.0默认项目目录与2.0的相比:
1.移除了static文件夹，新增了public文件夹，并且index.html移动到public中。

**Comment by acgta5** [comment]
xx

> 因为现在版本使用的脚手架是vue-cli3.
> vue-cli3.0默认项目目录与2.0的相比:
> 1.移除了static文件夹，新增了public文件夹，并且index.html移动到public中。

谢谢
