### ISSUE TITLE
vue-baidu-map 在此框架下IE浏览器无法显示

### ISSUE THREAD

**Issue by mjp1992** [PanJiaChen/vue-element-admin#2526]
使用vue-baidu-map插件,百度地图在IE浏览器无法显示,谷歌浏览器正常

**Comment by PanJiaChen** [comment]
所以很本项目关系是什么？

**Comment by mjp1992** [comment]
没有,只是想问一下有些IE上不支持的插件在此项目上需要怎么配置,网上一时没找出解决方案。

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/63828928-97c61b00-c99a-11e9-948a-0230c4993965.png)
