### ISSUE TITLE
axios请求拦截器设置Authorization无效

### ISSUE THREAD

**Issue by 515445681** [PanJiaChen/vue-element-admin#253]
设置后请求中没有加入此key
设置其他key可以显示，是不是需要配置？
config.headers['Authorization']

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/31759091-d52d0648-b475-11e7-807d-ce337809bec4.png)

详情建议查阅 [axios](https://github.com/axios/axios) 文档

**Comment by 515445681** [comment]
已经找到原因。
跨域时会发起options验证请求。
与spring boot security 集成时，security默认验证options请求有没有权限，因options请求不会携带header，故security认为没有权限，返回401错误码。导致下一步请求发送失败。。
配置security放行options拦截即可。
