### ISSUE TITLE
侧边栏似乎不能默认展开了，之前好像可以在路由里设置一个参数就可以默认展开的状态

### ISSUE THREAD

**Issue by DcxIt** [PanJiaChen/vue-element-admin#2534]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by CjoyHome** [comment]
默认全展开吗？找到了吗？

**Comment by PanJiaChen** [comment]
自己设 `default-openeds`
https://element.eleme.cn/#/zh-CN/component/menu

**Comment by zhujinhu21** [comment]
@DcxIt 怎么设置的，default-openeds 是el-menu的属性，但是SidebarItem.vue并没有el-menu标签

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/router-and-nav.html#%E4%BE%A7%E8%BE%B9%E6%A0%8F%E9%BB%98%E8%AE%A4%E5%B1%95%E5%BC%80

**Comment by ykchong45** [comment]
还有一种展开方式，就是修改`store/modules/app.js`里 sidebar的state。
教程来自[这里](https://blog.csdn.net/jiangyue2694/article/details/109157171)。

**Comment by K439-co** [comment]
Please be advised whoever is hacking and monitoring me is the one with the router. I removed my router along with all WiFi because of them. I only have an iPhone. NOTHING ELSE, NO ROUTER
