### ISSUE TITLE
el-button标签内的字体显示问题

### ISSUE THREAD

**Issue by imaemo** [PanJiaChen/vue-element-admin#254]
最近在用vue-element-admin做一个管理系统，发现在综合Table的页面上，filter 的几个按钮，发现字体和页面其它文字不一样。font-family的style好像被normalize.css 覆盖了。截图如下：

![capture](https://user-images.githubusercontent.com/11534313/31771181-b7932e1c-b50d-11e7-99c0-aebc2ac53391.JPG)

**Comment by imaemo** [comment]
我刚试了一下，在windows下才这样，mac下显示没多大区别

**Comment by PanJiaChen** [comment]
的确是因为normalize.css
![image](https://user-images.githubusercontent.com/8121621/31801489-2b925a4a-b50e-11e7-93f1-6b066aca420a.png)
我试了下windows 也没看出有没太大问题

**Comment by imaemo** [comment]
我稍微改了一下，第二个搜索按钮是我手动加了
`font-family: Helvetica Neue, Helvetica, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Arial, sans-serif;`  
![capture](https://user-images.githubusercontent.com/11534313/31802616-c3813a60-b581-11e7-9fe8-2040bf3f9d49.png

浏览器是 chrome 61 64bit, 不知能看出差别吗

**Comment by PanJiaChen** [comment]
你可以在[index.scss](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/styles/index.scss)
添加 `button`的css，它会盖掉 normalize.css 的样式

**Comment by imaemo** [comment]
可以了，谢谢哈。
