### ISSUE TITLE
为什么最新的i18n拉取后页面没有语言切换的按钮呀？

### ISSUE THREAD

**Issue by carveybunt** [PanJiaChen/vue-element-admin#2541]
大佬，您好。

今天无意间发现您的在线demo支持国际化，本着边学习开发，边学英语的态度重新拉取了新的i18n分支，发现登录页与头部并无语言切换按钮，在setting里面也没有发现相关的设置，是否需要自己手写呀？

同时在mock/role目录中发现了i18n的路由
`  {
    path: '/i18n',
    component: 'layout/Layout',
    children: [
      {
        path: 'index',
        component: 'views/i18n-demo/index',
        name: 'I18n',
        meta: { title: 'I18n', icon: 'international' }
      }
    ]
  },`
但是在views目录先并没有i18n-demo文件。想看下切换语言的是如何实现的。望大佬有闲余时间的时候指点下。

**Comment by CjoyHome** [comment]
你可能要去找下国际化的分支了

**Comment by CjoyHome** [comment]
https://github.com/PanJiaChen/vue-element-admin/tree/i18n

**Comment by PanJiaChen** [comment]
4.3版本后，会默认显示国际化分支。

**Comment by carveybunt** [comment]
多谢，我试试更新到最新版本吧，最近在忙考试都没怎么看。
