### ISSUE TITLE
npm install 安装失败 怎么破？

### ISSUE THREAD

**Issue by youngchen1987** [PanJiaChen/vue-element-admin#255]
![image](https://user-images.githubusercontent.com/11566474/31773644-f774ef54-b515-11e7-9cf7-cbf2b781f078.png)

**Comment by imaemo** [comment]
好像是 node版本过低，或者看下这个 #60 ，我之前也遇到过这个

**Comment by youngchen1987** [comment]
@imaemo  我刚装的node 8  运行也报错  我以为最新版本node的问题  然后我就又重新按照的node6.8   结果还是报错

**Comment by youngchen1987** [comment]
不过不应该是node的问题  我办公环境的  node  版本才是6.2了

**Comment by PanJiaChen** [comment]
单独重新安装一下 node-sass 试试
