### ISSUE TITLE
富文本能不能整合一下从word文件复制粘贴的功能(图片和文字同时出现)

### ISSUE THREAD

**Issue by forzenzhou** [PanJiaChen/vue-element-admin#2551]
## Feature request（新功能建议）
问题:我用了powerpaste插件,如果单独复制word中的文字内容不带图片是正常显示的;单独保存本地图片不带文字而不是使用上传图片按钮也可以上传文件,但是文字和图片同时图片无法上传;
如图:同时出现情况如下
![image](https://user-images.githubusercontent.com/21830743/64106285-73a77700-cdaa-11e9-8b8d-327d99c1da57.png)
相关配置如下:
                powerpaste_word_import: 'propmt',
                powerpaste_html_import: 'propmt',
                powerpaste_allow_local_images: true,
                paste_data_images: true,

**Comment by PanJiaChen** [comment]
`powerpaste`是 `Tinymce` 的付费功能，所以不会整合。

**Comment by LionlyloveK** [comment]
请问题主是怎么将插件加入的呢

**Comment by forzenzhou** [comment]
> 请问题主是怎么将插件加入的呢

http://tinymce.ax-z.cn/general/work-with-plugins.php

**Comment by LionlyloveK** [comment]
> > 请问题主是怎么将插件加入的呢
> 
> http://tinymce.ax-z.cn/general/work-with-plugins.php

作者用的是CDN的方式，不太清楚怎么加入插件，方便留下QQ吗 交流一下

**Comment by forzenzhou** [comment]
> > > 请问题主是怎么将插件加入的呢
> > 
> > 
> > http://tinymce.ax-z.cn/general/work-with-plugins.php
> 
> 作者用的是CDN的方式，不太清楚怎么加入插件，方便留下QQ吗 交流一下

时间比较久我不太记得了，我这个是需要下载放在自己的项目中配置一下就好了，并不复杂
