### ISSUE TITLE
打包到正式环境后，接口一直报405，而且奇怪的是接口地址等于页面地址

### ISSUE THREAD

**Issue by liaohongsen** [PanJiaChen/vue-element-admin#2558]
页面地址 mudi.xywykj.com  接口地址  test.xywykj.com

**Comment by liaohongsen** [comment]
![wen1](https://user-images.githubusercontent.com/16487300/64269730-009a2e00-cf6d-11e9-82f5-b89079025c50.png)
![wen2](https://user-images.githubusercontent.com/16487300/64269738-042db500-cf6d-11e9-9c60-246684d34267.png)
![wen3](https://user-images.githubusercontent.com/16487300/64269742-05f77880-cf6d-11e9-8b9b-1cd358fd69d2.png)
![wen4](https://user-images.githubusercontent.com/16487300/64269748-0728a580-cf6d-11e9-92b7-15b0dcf69bcf.png)
![wen5](https://user-images.githubusercontent.com/16487300/64269751-098aff80-cf6d-11e9-897c-818dad3b43d5.png)
![wen6](https://user-images.githubusercontent.com/16487300/64269756-0b54c300-cf6d-11e9-9d95-45afb7a38dee.png)

这是我相关的所有截图，麻烦指导一下，困扰我几天了，我这个接口请求地址一来就不对，应该是test.xywykj.com

**Comment by liaohongsen** [comment]
![image](https://user-images.githubusercontent.com/16487300/64272367-cb440f00-cf71-11e9-9019-4df81488cf2b.png)
更新一下最新情况，我这里写死的话，就OK，貌似是 没抓到这两个值，用第二个就不行，必须要写死

**Comment by gdoudeng** [comment]
你两个baseUrl相加干嘛 不是VUE_APP_URL+VUE_APP_BASE_URL吗

**Comment by Yanqilong** [comment]
@gdoudeng 我也碰到了一样的问题，解决了吗？
@PanJiaChen 可以帮忙解释下吗？

**Comment by Yanqilong** [comment]
@liaohongsen  重启 serve 后可以获取到

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/2929

重新拉取最新代码已修复。
