### ISSUE TITLE
多标签页缓存，AppMain中的keep-alive的include属性要想正常工作，有一个前提

### ISSUE THREAD

**Issue by anrananran** [PanJiaChen/vue-element-admin#2560]
## Feature request（新功能建议）
看了一下tagsView.js中的cachedViews依赖的是路由上的name，来收集需要缓存的组件，而keep-alive中include实际上需要的是组件的name，所以前提是必须将组建的名称写成和路由的名称一样才能收集到正确的组件名称，这一点在文档中似乎没有提及？

**Comment by EmiyaYang** [comment]
[LINK](https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/tags-view.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)
