### ISSUE TITLE
[NPM] npm install 后window10系统蓝屏

### ISSUE THREAD

**Issue by carolcoral** [PanJiaChen/vue-element-admin#2561]
### npm install 直接蓝屏
1.从github上clone项目到desktop
2.使用webstorm打开项目
3.运行 npm install
4.windows10系统蓝屏
5.再次按照上述步骤操作，100%复现蓝屏
6.蓝屏提示 system_service_exception

**Comment by feng005211** [comment]
使用vscode试试 ☺

**Comment by gdoudeng** [comment]
这难道不是你自己电脑的问题。。。

**Comment by carolcoral** [comment]
@feng005211 用的webstorm
@gdoudeng 稳定运行pycharm，idea和webstorm，并运行各类项目

**Comment by chenxofhit** [comment]
MS 的人员看到这个 issue 会打你

**Comment by PanJiaChen** [comment]
这真不知道为什么。。https://github.com/PanJiaChen/vue-element-admin/issues/2059
