### ISSUE TITLE
ie11 路由跳转报错

### ISSUE THREAD

**Issue by airzhanglin** [PanJiaChen/vue-element-admin#2564]
#### Steps to reproduce（问题复现步骤）
在ie11上使用this.$router.push进行路由跳转出现以下错误：

#### Screenshot or Gif（截图或动态图）
[object Error]{description: "Loading chu...", message: "Loading chu...", name: "Error", request: "http://192....", stack: "Error: Load...", Symbol()_l.i9rjji3bewl: undefined, Symbol()_n.i9rjji3bewl: undefined, Symbol()_o.i9rjji3bewl: undefined, Symbol()_q.i9rjji3bewl: undefined, Symbol(react.element)_m.i9rjji3bewl: undefined, Symbol(Symbol.observable)_p.i9rjji3bewl: undefined, type: "missing"}

**Comment by cnsummer** [comment]
正常页面比如说侧边栏跳转有问题吗？
