### ISSUE TITLE
新增测试环境后，打包后的dist文件会多出很多js

### ISSUE THREAD

**Issue by tmj1220** [PanJiaChen/vue-element-admin#2566]
新增的测试打包
![image](https://user-images.githubusercontent.com/45507545/64499487-be197e00-d2eb-11e9-919f-98ac667db9e8.png)
原本项目的生产打包
![image](https://user-images.githubusercontent.com/45507545/64499520-e4d7b480-d2eb-11e9-86ad-6d9c6ef4af5b.png)
是需要配置哪里吗

**Comment by PanJiaChen** [comment]
请用正确的姿势提问，请提供可复现demo。
