### ISSUE TITLE
登出 怎么去重置路由

### ISSUE THREAD

**Issue by zhubufang** [PanJiaChen/vue-element-admin#2572]
登出 怎么去重置路由

不要使用强制刷新页面，这样用户体验不太好

**Comment by mayunhai** [comment]
登出 并没有强制刷新页面，是不是本地版本 被人修改过?

**Comment by hanxiaosss** [comment]
同，调用的充值路由的方法好像没有用

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/5890499077589db1c04c7a72c4dacaa97a58f87c/src/router/index.js#L390-L402

已实现。
