### ISSUE TITLE
项目打包越来越慢问题

### ISSUE THREAD

**Issue by lubianniu** [PanJiaChen/vue-element-admin#2576]
## Question（提问）
这个项目的name：vue-admin-template。版本是：3.0.0。 webpack版本：3.10.0。请问作者有什么方法提交打包和编译的速度吗？

#### Screenshot or Gif（截图或动态图）

![Image text](https://raw.githubusercontent.com/lubianniu/text1/master/1.png)
![Image text](https://raw.githubusercontent.com/lubianniu/text1/master/2.png)
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
请按照规则提问。
