### ISSUE TITLE
组件中引用<el-divider></el-divider>报错

### ISSUE THREAD

**Issue by xin7c** [PanJiaChen/vue-element-admin#2578]
#### Steps to reproduce（问题复现步骤）
组件中引用<el-divider></el-divider>报错

**Comment by JynStar725** [comment]
`divider`组件是`ElementUI` `2.8.0`之后才新增的组件

截至回答时，目前这个`vue-element-admin`使用的`ElementUI`是`2.7.0`版本的，当然用不了的

**Comment by xin7c** [comment]
> `divider`组件是`ElementUI` `2.8.0`之后才新增的组件
> 
> 截至回答时，目前这个`vue-element-admin`使用的`ElementUI`是`2.7.0`版本的，当然用不了的
> 
> 建议升级下`ElementUI`到最新版应该就可以使用了

确实，我更改了json，重新升级就好啦。

**Comment by PanJiaChen** [comment]
已升级。
