### ISSUE TITLE
希望提供一个很简单的，只包含Layout的模板

### ISSUE THREAD

**Issue by tkggusraqk** [PanJiaChen/vue-element-admin#2579]
## Feature request（新功能建议）
不包含任何封装的，路由也是原vue路由，我只是为了用 “响应式”，其他的不想用，可以让我自己来控制。按照现在的这个需要修改的东西太多。

**Comment by isfighting** [comment]
我也是这样想的，里面的东西还是太多了，只需要一个最间接的末模板，能实现响应式就可以了

**Comment by jingchaocheng** [comment]
@tkggusraqk https://github.com/PanJiaChen/vue-admin-template

**Comment by PanJiaChen** [comment]
已提供简单模板 `vue-admin-template` 了
