### ISSUE TITLE
config配置

### ISSUE THREAD

**Issue by tomsure** [PanJiaChen/vue-element-admin#2582]
之前在做项目的时候看到vue-element-admin 文件夹中有 一个config 目录
![image](https://user-images.githubusercontent.com/15616904/65102059-8a7dd880-d9fc-11e9-838a-8cf2fd9ba9b8.png)
现在为什么没看到了，这样的话生产环境和开发环境如何配置呢

**Comment by mayunhai** [comment]
根目录下
.env.development
.env.production
.env.staging
