### ISSUE TITLE
dashboard页面图表resize的防抖并没有防住抖动

### ISSUE THREAD

**Issue by caobaibai** [PanJiaChen/vue-element-admin#2586]
#### Steps to reproduce（问题复现步骤）
1. 在views->dashoard->admin->components->mixins->resize.js页面的30行$_resizeHandler()方法第一行console.log(1),在if内部console.log(2)
2. 在dashboard页面多次resize页面，时间间隔小于设定的防抖时间
3.发现1输出了N次，2也输出了多次

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/37610085/65209033-60deb300-dac9-11e9-90f8-ceadf5ed81c8.png)
![image](https://user-images.githubusercontent.com/37610085/65209063-823f9f00-dac9-11e9-9ae5-267b32f003d0.png)
![image](https://user-images.githubusercontent.com/37610085/65209135-badf7880-dac9-11e9-8d08-b7c0428726a5.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by caobaibai** [comment]
步骤补充：1.在dashboard页面中的resize.js中31行console.log(1)，在其后if语句中console.log(2)，
2.resize dashboard页面查看控制台。
3.发现输出多次1和多次2.没有防抖
4.改写以后可以防抖，两种写法有什么区别吗？

**Comment by mayunhai** [comment]
参考  #2597
