### ISSUE TITLE
在项目中打断点 看到的是编译后的文件，怎么能看到源文件的内容

### ISSUE THREAD

**Issue by wangwenjie666** [PanJiaChen/vue-element-admin#2589]
![1568949048(1)](https://user-images.githubusercontent.com/24708291/65296509-45da7480-db97-11e9-80dc-4d2fe1a434c0.jpg)

**Comment by mayunhai** [comment]
试试 `debugger;` 我这里看没问题啊，实在不行就 `console.log(xx)`

**Comment by somggud** [comment]
![image](https://user-images.githubusercontent.com/26177037/65581400-f7b9dc80-dfad-11e9-9745-350754c61743.png)
把这个配置换掉就行了

**Comment by somggud** [comment]
找到vue.config.js中的 config => config.devtool('cheap-source-map')这句话，
把cheap-source-map替换成source-map就行了

**Comment by wangwenjie666** [comment]
可以 十分感谢

**Comment by lizhenxiu** [comment]
666

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/3097
