### ISSUE TITLE
我是个很low的javer，请问这么多页面，怎么弄成类似全HTML的页面，方便开发

### ISSUE THREAD

**Issue by ExtremeYu** [PanJiaChen/vue-element-admin#259]

**Comment by PanJiaChen** [comment]
这是spa但也没开发，不支持多页面

**Comment by ExtremeYu** [comment]
@PanJiaChen 那后端怎么去开发呢，这是用nodejs渲染的吗

**Comment by leij1ang** [comment]
restful，暴露相应后台接口就行了

**Comment by srw962** [comment]
@ExtremeYu ，我想你应该是想把vue项目整合到java项目里。
目前我尝试的有以下几种方式：
1、直接在java项目的html页里通过script标签引入vue以及其他ui库，比如element-ui
2、单建一个node.js项目，主要用来做界面，然后通过rest方式调用java的方法
3、把vue项目放到java项目里，然后通过修改vue的config.js修改vue生成的路径，然后java项目首页引入vue项目打包生成的main.js，后续java项目只提供controller给vue的请求，不再写界面；所有的界面都在vue里写。
我参考https://github.com/kucharzyk/vuejs-java-starter （采用spring-boot、vue1）这个项目写了个类似的vue2的项目：https://github.com/srw962/MicroCommercial。
你可以参考下
