### ISSUE TITLE
master分支最新版本不提供中文的吗？

### ISSUE THREAD

**Issue by syhcgo** [PanJiaChen/vue-element-admin#2591]
我进去登录上之后显示的是英文界面，但是国际化模块已经被移除了。默认英文语言吗？

**Comment by mayunhai** [comment]
#2595 如果是关于 element 语言设置可以参照这个问题答案，如果需要国际化模块切换分支到 i18n

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed

我之后思考一下有没有更好的解决方案。
