### ISSUE TITLE
pagination不能设置中文

### ISSUE THREAD

**Issue by fourierr** [PanJiaChen/vue-element-admin#2595]
在pagination组件中，如何设置中文，例如total、page、go to等英文
如何改为中文

**Comment by fourierr** [comment]
![1](https://user-images.githubusercontent.com/35767528/65400210-846c6b00-ddf3-11e9-84dd-5a024e0ecc4f.png)
![Uploading 1.png…]()

**Comment by mayunhai** [comment]
参考[element官方文档](https://element.eleme.cn/#/zh-CN/component/i18n)

**Comment by mayunhai** [comment]
src\main.js里面
```js
Vue.use(Element, {
  size: Cookies.get('size') || 'medium' // set element-ui default size
})
```
修改成
```js
import locale from 'element-ui/lib/locale/lang/zh-CN'
Vue.use(Element, {
  locale,
  size: Cookies.get('size') || 'medium' // set element-ui default size
})
```

**Comment by huangmin1006** [comment]
main.js 我改了还是全面板都是en

**Comment by mayunhai** [comment]
> main.js 我改了还是全面板都是en

最好贴出来 main.js的代码 不然看不出来问题

**Comment by lxge** [comment]
`import Vue from 'vue'

import Cookies from 'js-cookie'

import 'normalize.css/normalize.css' // a modern alternative to CSS resets

import Element from 'element-ui'
import './styles/element-variables.scss'
import enLang from 'element-ui/lib/locale/lang/en'// 如果使用中文语言包请默认支持，无需额外引入，请删除该依赖

import '@/styles/index.scss' // global css

import App from './App'
import store from './store'
import router from './router'

import './icons' // icon
import './permission' // permission control
import './utils/error-log' // error log

import * as filters from './filters' // global filters

/**
 * If you don't want to use mock-server
 * you want to use MockJs for mock api
 * you can execute: mockXHR()
 *
 * Currently MockJs will be used in the production environment,
 * please remove it before going online ! ! !
 */
if (process.env.NODE_ENV === 'production') {
  const { mockXHR } = require('../mock')
  mockXHR()
}

Vue.use(Element, {
  size: Cookies.get('size') || 'medium', // set element-ui default size
  locale: enLang // 如果使用中文，无需设置，请删除
})

// register global utility filters
Object.keys(filters).forEach(key => {
  Vue.filter(key, filters[key])
})

Vue.config.productionTip = false

new Vue({
  el: '#app',
  router,
  store,
  render: h => h(App)
})
`
最新版的是这样的 注释掉语言的那两行 还是英文, 系统明明说删掉就可以了

**Comment by lxge** [comment]
`import Vue from 'vue'

import Cookies from 'js-cookie'

import 'normalize.css/normalize.css' // a modern alternative to CSS resets

import Element from 'element-ui'
import './styles/element-variables.scss'
import enLang from 'element-ui/lib/locale/lang/en'// 如果使用中文语言包请默认支持，无需额外引入，请删除该依赖

import '@/styles/index.scss' // global css

import App from './App'
import store from './store'
import router from './router'

import './icons' // icon
import './permission' // permission control
import './utils/error-log' // error log

import * as filters from './filters' // global filters

/**
 * If you don't want to use mock-server
 * you want to use MockJs for mock api
 * you can execute: mockXHR()
 *
 * Currently MockJs will be used in the production environment,
 * please remove it before going online ! ! !
 */
if (process.env.NODE_ENV === 'production') {
  const { mockXHR } = require('../mock')
  mockXHR()
}

Vue.use(Element, {
  size: Cookies.get('size') || 'medium', // set element-ui default size
  locale: enLang // 如果使用中文，无需设置，请删除
})

// register global utility filters
Object.keys(filters).forEach(key => {
  Vue.filter(key, filters[key])
})

Vue.config.productionTip = false

new Vue({
  el: '#app',
  router,
  store,
  render: h => h(App)
})
`
最新版的是这样的 注释掉语言的那两行 还是英文, 系统明明说删掉就可以了
