### ISSUE TITLE
关于动态拼接的 import() 的问题

### ISSUE THREAD

**Issue by hubangmao** [PanJiaChen/vue-element-admin#2596]
如果写死的话 import('@/views/demo/form/index') 左侧菜单就能正常打开
我的项目中权限菜单import 是通过变量拼接上去的就出现了下面的错误 。

## 代码部分
![image](https://user-images.githubusercontent.com/20508257/65411392-5866df00-de1f-11e9-8489-0bcbb3739860.png)

## 出现的bug
![image](https://user-images.githubusercontent.com/20508257/65411449-7c2a2500-de1f-11e9-88d3-8108f7e4985c.png)

**Comment by mayunhai** [comment]
如果想要实现动态路由 参考官方文档 [router.addRoutes](https://router.vuejs.org/zh/api/#router-addroutes)

**Comment by hubangmao** [comment]
已经解决了：动态拼接左侧菜单的 component 参数应该使用如下方式
![image](https://user-images.githubusercontent.com/20508257/65475001-7deff900-deb0-11e9-9e1c-078b703d4854.png)

**Comment by swinm** [comment]
正确的引用姿势可以，很棒。
就是不知道为啥 return () => import('@/views' + file + '.vue') 不可以呢

**Comment by 4550155** [comment]
跟你一样的问题,貌似还是没解决了

**Comment by AP0rPi7uQ9** [comment]
正确的引用姿势可以，很棒。非常感谢
