### ISSUE TITLE
左侧的菜单数据只有一级菜单也必须包含 children吗 ?

### ISSUE THREAD

**Issue by hubangmao** [PanJiaChen/vue-element-admin#2598]
1、必须得这样子写吗 ？
![image](https://user-images.githubusercontent.com/20508257/65474954-5731c280-deb0-11e9-8bca-062630bc54f4.png)

2、数据内容不能这样写吗 ？
![image](https://user-images.githubusercontent.com/20508257/65474963-5e58d080-deb0-11e9-9619-b56bb5cd0626.png)

**Comment by mayunhai** [comment]
对啊 不然没有 Layout ，然后就没有侧边菜单 顶部等一系列 公共组件，如果非要一级可以参考
```
  {
    path: '/login',
    component: () => import('@/views/login/index'),
    hidden: true
  },
```
