### ISSUE TITLE
顶部的快捷导航存在有何意义，点击依然会刷新页面?

### ISSUE THREAD

**Issue by Duke19911212** [PanJiaChen/vue-element-admin#260]
如果顶部快捷导航和左侧导航栏的功能是一样的，那就没有存在的必要，建议做成easy-ui一样的tab切换，顶部导航切换不会重新加载页面。这样新增数据加到一半需要切换页面时不至于原来的数据被清空。

**Comment by PanJiaChen** [comment]
正在优化中

**Comment by qyjs** [comment]
请问，页面刷新，顶部的加载条怎么写的

**Comment by PanJiaChen** [comment]
@qyjs nprogress

**Comment by PanJiaChen** [comment]
已发布3.0  
Duplicate of #270
