### ISSUE TITLE
Possible causes of '[Vue warn]: data functions should return an object:'

### ISSUE THREAD

**Issue by sumantafinarb** [PanJiaChen/vue-element-admin#2602]
I'm trying to login and get authenticated to an admin dashboard. When I click Login I get the token back as expected, but then, on console, I see: [Vue warn]: data functions should return an object:, and a list of red lines like this: [Vue warn]: Property "visible" must be accessed with "$data.visible" because properties starting with "$" or "_" are not proxied in the Vue instance to prevent conflicts with Vue internal. (found in <Root>).

And 8 more like this one.

I understand why data needs to be a function and not an object in Vuejs, I searched in Google and I just found clarification on this. But I double checked my code and data is in fact a function returning an object. I don't know then, if all the other warnings below are there because of it. Also, the login, if successful, should redirect to the dashboard page. It actually does (the url on the browser changes), but the view does not update.

Are all these things related?

I am now using a real api, before, with a fake one, everything was working fine. Sorry if for someone this can sound a stupid question, yes I am new to Vue and programming in general, but I don't know what to look at on Google to solve it.

Thank you.

I'm running on localhost, the apis point to a server with a different address (I avoided CORS running Chrome without it). I checked all the data() in my code to be sure there wasn't any of them declared as objects but everything looks fine.

**Comment by mayunhai** [comment]
[Vue warn]: The "data" option should be a function that return...
[Reference to official documents](https://vuejs.org/v2/api/#Options-Data) or [#data-Must-Be-a-Function](https://vuejs.org/v2/guide/components.html#data-Must-Be-a-Function)
```Restriction: Only accepts Function when used in a component definition.```

**Comment by mayunhai** [comment]
[Vue warn]: Property "visible" must be accessed with "$data.visible" because properties starting with "$" or "_" a...

VUE source code

```
  const warnReservedPrefix = (target, key) => {
    warn(
      `Property "${key}" must be accessed with "$data.${key}" because ` +
      'properties starting with "$" or "_" are not proxied in the Vue instance to ' +
      'prevent conflicts with Vue internals' +
      'See: https://vuejs.org/v2/api/#data',
      target
    )
  }
```
[官方文档](https://vuejs.org/v2/api/#data) 

>After the instance is created, the original data object can be accessed as vm.$data. The Vue instance also proxies all the properties found on the data object, so vm.a will be equivalent to vm.$data.a.

>Properties that start with _ or $ will not be proxied on the Vue instance because they may conflict with Vue’s internal properties and API methods. You will have to access them as vm.$data._property.

**Comment by numa001** [comment]
Message.error(error || 'Has Error') 换成 Message.error('Has Error')

**Comment by inspire22** [comment]
Any solution to this?  I'm getting this warning with a property named "card_on_file" - clearly not starting with $ or _, which feels very mysterious.  

Vue 2.6.11
