### ISSUE TITLE
你好：await / async es7语法 需要配置那些才能支持

### ISSUE THREAD

**Issue by lzread** [PanJiaChen/vue-element-admin#2605]

**Comment by mayunhai** [comment]
await / async 项目中有用到的啊

**Comment by lzread** [comment]
> await / async 项目中有用到的啊

在我自己搭建的项目里，我想使用ES7的语法

**Comment by PanJiaChen** [comment]
![Uploading image.png…]()

**Comment by lzread** [comment]
我还想知道 你的项目是在哪里配置的，谢谢

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/babel.config.js

**Comment by lzread** [comment]
> https://github.com/PanJiaChen/vue-element-admin/blob/master/babel.config.js
> 
> https://cli.vuejs.org/zh/config/#babel

打扰了？ 我看你的项目中的babel.config.js，只有
![image](https://user-images.githubusercontent.com/5275003/66627341-f505eb00-ec2d-11e9-8bd8-e545f3046c25.png)
但是我看你的项目中使用了 await / async

**Comment by PanJiaChen** [comment]
请先学会自己谷歌。
