### ISSUE TITLE
vue-element-admin/src/views/example/create.vue Cache error

### ISSUE THREAD

**Issue by NEALWE** [PanJiaChen/vue-element-admin#2608]
## create.vue Cache error

in `vue-element-admin/src/views/example/create.vue` line 9
```
name: 'CreateForm',
```
but in `vue-element-admin/src/router/index.js` line 209 ,the name is 
```
name: 'CreateArticle',
```

## Resolvent
Change the two names into the same value.

**Comment by mayunhai** [comment]
The same field in these two places has different meanings.
[vue name](https://vuejs.org/v2/api/#name)
[vue router name](https://router.vuejs.org/guide/essentials/named-routes.html)

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/e3cbf4ad90130ba3637f267bad0058d2824b2a12
