### ISSUE TITLE
请问tinymce可以添加阿拉伯语言吗?

### ISSUE THREAD

**Issue by gudehuang** [PanJiaChen/vue-element-admin#2613]
#### Steps to reproduce（问题复现步骤）

1.
![image](https://user-images.githubusercontent.com/20537541/65754977-c3c4ef80-e144-11e9-9f8b-031c73d29c71.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
https://www.jsdelivr.com/package/npm/tinymce-all-in-one?path=langs

4.9.5 版本已支持。

**Comment by gudehuang** [comment]
好的,十分感谢
