### ISSUE TITLE
侧边导航变成鼠标hover时间，子导航向右侧展开了，怎么变成鼠标点击下拉式的

### ISSUE THREAD

**Issue by kaimengxin** [PanJiaChen/vue-element-admin#2614]
什么都没有该，直接clone下来的项目代码，导航怎么这种向右侧展开了，怎么修改成下拉式，在线坐等，谢谢。
![image](https://user-images.githubusercontent.com/20276380/65760404-887bee00-e14f-11e9-8d3e-80ec3ad9ada6.png)

**Comment by mmqic** [comment]
那个。。点上面 Dashboard 左边的菜单图标
