### ISSUE TITLE
通过webpack打包之后通过ie9浏览器打开非常慢非常慢

### ISSUE THREAD

**Issue by claudiazhu** [PanJiaChen/vue-element-admin#262]
请问有什么好的解决办法吗？就是打开网页平均需要5分钟的时间，以及在网页上操作每次点击都很慢，已经用了polyfill了，不知道还有其他什么地方需要改的

**Comment by PanJiaChen** [comment]
首先你确定一些是否是网络问题，五分钟我感觉已经不太可能是js运行的耗时了
其次排除网络问题的话，打开游览器控制台的performance具体看看是慢在哪里了

**Comment by claudiazhu** [comment]
找到原因了，因为里面一个css路径不对找不到文件，然后在ie里就打开很慢了。已经解决了，谢谢
