### ISSUE TITLE
请问小图片如何保持图片地址，不自动转base64？

### ISSUE THREAD

**Issue by wzfjesun** [PanJiaChen/vue-element-admin#2624]
## Question（提问）
`<span><img class="emoji-icon" @click="selectEmoji($event)" title="[微笑]" src="@/assets/emoji/smile.gif?v=1" /></span>`
` <span><img class="emoji-icon" @click="selectEmoji($event)" title="[微笑]" src="@/assets/emoji/weixiao.gif?v=1" /></span>`
`<span><img class="emoji-icon" @click="selectEmoji($event)" title="[微笑]" src="../../assets/emoji/weixiao.png?v=1" /></span>`

![Screenshot from 2019-10-05 23-20-57](https://user-images.githubusercontent.com/6768736/66257051-121e6200-e7c7-11e9-9a9c-47ff356a4926.png)

如上图的三个图片，第一个图片大小有6k，浏览器显示的是图片url，第二和第三张只有3k就转成base64显示了。请问如何才能保持显示图片url，不让他自动转成base64呢？

**Comment by mayunhai** [comment]
把不想被转化的图片放 根目录/public里面

**Comment by mayunhai** [comment]
或者通过配置文件修改图片转化大小限制 [【参考官方文档】](https://cli.vuejs.org/zh/guide/html-and-static-assets.html#%E4%BB%8E%E7%9B%B8%E5%AF%B9%E8%B7%AF%E5%BE%84%E5%AF%BC%E5%85%A5)

**Comment by wzfjesun** [comment]
谢谢 @mayunhai
