### ISSUE TITLE
yorkie@2.0.0 error

### ISSUE THREAD

**Issue by fightlikeagirl** [PanJiaChen/vue-element-admin#2628]
Hello, last time when I upgraded my project everything works fine. But today when I run npm install command I get that error,
` yorkie@2.0.0 install E:\e\e\web\backend\sanaldevriyeclient\node_modules\yorkie
> node bin/install.js
'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yorkie@2.0.0 install: `node bin/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yorkie@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tekint35\AppData\Roaming\npm-cache\_logs\2019-10-07T07_05_17_461Z-debug.log`

I try 'npm install --unsafe-perm'  an change by node version but it didn't worked. I need yoru help .Thank you so much. (My node version 10.13.0)

**Comment by mayunhai** [comment]
`npm install --registry=https://registry.npm.taobao.org`

**Comment by fightlikeagirl** [comment]
Thank you, I pulled all codes from git and it becomes normal

**Comment by fightlikeagirl** [comment]
Oh no, I faced same error again and try `npm install --registry=https://registry.npm.taobao.org` but this get me same error :( any other solutions ?

**Comment by PanJiaChen** [comment]
@fightlikeagirl https://github.com/vuejs/vue-cli/issues/3466 may be help.

**Comment by fightlikeagirl** [comment]
I just copied yorkie folder to my node_modules then I got node_sass error . And I run `npm rebuild node-sass` . then my problem solved.

**Comment by Veitor** [comment]
I'm also 醉了.  that's not work with your solution.
anybody has same question?

**Comment by Cebape** [comment]
Hi! I had this problem but I solved it changing the atributies from project directories permissions althrough chmod command like "chmod -R 777 my-directory/".  Early level directories could has permission change too.

**Comment by Cebape** [comment]
In fact, this error (Yorkie@2.0.0) is related to the security attributes of the project-vuejs folder. So, create your projects outside the root / folder, make Linux updates (Ubuntu ...) and success to everyone!
