### ISSUE TITLE
constantRoutes 似乎不能绕过登陆验证

### ISSUE THREAD

**Issue by kernelogic** [PanJiaChen/vue-element-admin#2629]
刚刚开始了最新版的代码，想增加一个注册模块，但是发现配置到constantRoutes以后，访问的时候依然还是会直接到login，无法绕过登陆验证。请问这个如何解决？

```
export const constantRoutes = [
  {
    path: '/redirect',
    component: Layout,
    hidden: true,
    children: [
      {
        path: '/redirect/:path*',
        component: () => import('@/views/redirect/index')
      }
    ]
  },
  {
    path: '/login',
    component: () => import('@/views/login/index'),
    hidden: true
  },
  {
    path: '/register',
    component: () => import('@/views/register/index'),
    hidden: true
  },
  {
    path: '/auth-redirect',
    component: () => import('@/views/login/auth-redirect'),
    hidden: true
  },
```

**Comment by mayunhai** [comment]
src\permission.js
注意这个行代码
`const whiteList = ['/login', '/auth-redirect'] // no redirect whitelist`
给你想要新增的注册页面添加白名单

**Comment by jeromemar** [comment]
这样还是不能解决问题，此js(src/permission.js)61行处有如下:
if (whiteList.indexOf(to.path) !== -1) {
      // in the free login whitelist, go directly
      next()
    } else {
      // other pages that do not have permission to access are redirected to the login page.
      next(`/login?redirect=${to.path}`)
      NProgress.done()
    }
意思是加入whiteList 数组皆为白名单，界面无需跳转登录。
实际上登录以后，界面左侧的菜单，右侧的头像信息等都需从登录后的信息中取得。
所以应该先弄个 游客信息，能查看一定菜单和界面.... 我还在研究怎么加。
这个办法不知道行不行,我还在试.
在 src\store\modules\user.js 的 getInfo( 里加个判断条件，返回
      return new Promise((resolve, reject) => {
        const data = { roles: 'guest', name: '游客', avatar: '//cube.elemecdn.com/9/c2/f0ee8a3c7c9638a54940382568c9dpng.png' }
        const { roles, name, avatar } = data
        commit('SET_ROLES', roles)
        commit('SET_NAME', name)
        commit('SET_AVATAR', avatar)
        resolve(data)
      })......

**Comment by mayunhai** [comment]
你是要新增一个注册页面拿来的登陆后的信息....参照 404、401页面 把  路由里面把 layout 移除掉就可以了

**Comment by jeromemar** [comment]
呵呵，不好意思，没看请要求， 是要增加一个注册模块。
新增界面，而且不受路由限制的方法，以楼上说的为准。
如果仅仅增加注册模块，建议参照项目里的 tab方式,同一个界面，登录/注册/改密码。使用比较方便。

**Comment by kernelogic** [comment]
Make sense, thanks a bunch!
