### ISSUE TITLE
菜单父级加导航

### ISSUE THREAD

**Issue by by-oneself** [PanJiaChen/vue-element-admin#2637]
![image](https://user-images.githubusercontent.com/25608788/66449908-34470700-ea89-11e9-81a1-6ca297f2d29c.png)
在菜单父级上面加导航，添加了@click 不起作用

**Comment by mayunhai** [comment]
你这个截图 并没有看到 click 问题很难定位
不过大致可以想象应该是没有添加 .native 修饰符
参考文档 [将原生事件绑定到组件](https://cn.vuejs.org/v2/guide/components-custom-events.html#将原生事件绑定到组件)

**Comment by by-oneself** [comment]
> 你这个截图并没有
> 看到click问题很难定位不过大致可以想象应该是没有添加.native修饰符，不能在组件上方直接使用@click
> 参考文档[将原生事件绑定到组件](https://cn.vuejs.org/v2/guide/components-custom-events.html#%E5%B0%86%E5%8E%9F%E7%94%9F%E4%BA%8B%E4%BB%B6%E7%BB%91%E5%AE%9A%E5%88%B0%E7%BB%84%E4%BB%B6)

加native试过了 不行的

**Comment by mayunhai** [comment]
`$listeners` 试试 文档上面都写了的

**Comment by PanJiaChen** [comment]
`@click.native`试了下没什么问题。有问题，请提供重新demo
