### ISSUE TITLE
退出登录后，所有打开的标签页中，最后打开的那个（selectedTag）无法关闭

### ISSUE THREAD

**Issue by GitACDreamer** [PanJiaChen/vue-element-admin#2638]
## Bug report（问题描述）
登录打开一些标签，退出登录，然后重新登录，发现所有打开的标签页中，最后打开的那个（selectedTag）未关闭
![image](https://user-images.githubusercontent.com/19402747/66450410-ff3bb400-ea8a-11e9-874f-4f1573cff63f.png)

#### Steps to reproduce（问题复现步骤）
1. 登录后随便打开一些标签页
![image](https://user-images.githubusercontent.com/19402747/66450466-314d1600-ea8b-11e9-8237-5c236d52d445.png)
2. 点击注销后，再登录，发现最后打开的那个标签页仍然未关闭
![image](https://user-images.githubusercontent.com/19402747/66450499-58a3e300-ea8b-11e9-8bbe-e1f95fb2c546.png)

#### Other relevant information（格外信息）
- Your OS: win10
- Node.js version: 10.16.0
- vue-element-admin version: v4.2.1

**Comment by PanJiaChen** [comment]
并不是这个问题，退出后登录默认会重定向到你之前打开的页面
![image](https://user-images.githubusercontent.com/8121621/66450646-dff15680-ea8b-11e9-8442-29ab57216e3a.png)

**Comment by GitACDreamer** [comment]
@PanJiaChen 谢谢，已经解决，在登录函数里面handleLogin，不想重定向到打开的页面，直接push到'/'就好了
`this.$router.push({ path: this.redirect || '/', query: this.otherQuery })` 
改成`this.$router.push('/')`
感谢！！
