### ISSUE TITLE
tagsView Error in mounted hook: "TypeError: 

### ISSUE THREAD

**Issue by binxyz** [PanJiaChen/vue-element-admin#2639]
想在vue-template-admin 中使用tagsView功能，复制好相关文件，报错
![image](https://user-images.githubusercontent.com/16433644/66450819-83426b80-ea8c-11e9-94f3-c9e3cacf46c0.png)
![image](https://user-images.githubusercontent.com/16433644/66450832-8f2e2d80-ea8c-11e9-9127-ee2fab7dea04.png)
啥原因

**Comment by PanJiaChen** [comment]
报错已经很清楚了，请根据报错来定位问题。
