### ISSUE TITLE
npm安装包列表麻烦给一个

### ISSUE THREAD

**Issue by que0080** [PanJiaChen/vue-element-admin#264]
装了半天的安装包还没好, 坑好多啊,  运行一下 缺一个包,  运行起来太难了

**Comment by SIGAOYI** [comment]
我猜package.json里应该有列表吧
今天刚入手,还没开始run

**Comment by que0080** [comment]
包含vue自带的安装包  已经装了 879个了  还运行不起来,  还有坑....  想死的心都有了

**Comment by PanJiaChen** [comment]
所有需要的包都在  `package.json` 里面了 ，安装失败建议使用淘宝镜像安装，`readme` 已写使用方法

**Comment by que0080** [comment]
node-sass 改名成  sass-loader了, 
需要使用 cnpm install node-sass  安装,  
目前能运行起来了  3q  不容易

**Comment by que0080** [comment]
ok  结贴!
