### ISSUE TITLE
Tinymce富文本上传图片如果我的图片域名和网站域名一样会被替换成“../”,导致图片无法访问

### ISSUE THREAD

**Issue by w22296437978** [PanJiaChen/vue-element-admin#2640]

**Comment by PanJiaChen** [comment]
https://www.tiny.cloud/docs/plugins/imagetools/#imagetools_cors_hosts

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/1b8f726529b6d2b6384ee55db44b24daadc3dfa8
