### ISSUE TITLE
vue cli 3.x + webpack 4 + element ui 如何使用 @babel/polyfill 兼容 IE9 浏览器

### ISSUE THREAD

**Issue by luggege** [PanJiaChen/vue-element-admin#2644]
## Question（提问）

经测试发现IE9 浏览器,axios请求能正常使用, 但使用的element ui中的flex导致布局错乱, 其他主流浏览器正常.
博主wiki中的(https://github.com/PanJiaChen/vue-element-admin/wiki#babel-polyfill) babel-polyfill解决方案是vue cli 2.x的, 而我用的是3.x版本.
现按官方文档如下操作后发现还是不行, SOS~

#### Steps to reproduce（问题复现步骤）
1. // .browserslistrc
> 1%
last 2 versions
not ie <= 8

2. // babel.config.js
module.exports = {
  presets: [
    ['@vue/app', 
      {
        useBuiltIns: 'entry'
      }
    ]
  ]
}

2. // main.js
import '@babel/polyfill'

3. 官网中有三种选择, 我尝试在 vue.conifig.js中添加了
transpileDependencies: ['element-ui']
也不行

#### Other relevant information（格外信息）
- 运行项目不报错, IE9 布局依然错乱

**Comment by luggege** [comment]
// .browserslistrc
> 1%
last 2 versions
not ie <= 8

// babel.config.js
module.exports = {
  presets: [
    ['@vue/app', 
      {
        useBuiltIns: 'entry'
      }
    ]
  ]
}

// main.js
import '@babel/polyfill'

//vue cli 官网中关于兼容的(https://cli.vuejs.org/zh/guide/browser-compatibility.html#browserslist)解决方案有三种选择, 看到说vue cli 项目默认的babel不会处理node_modules中的东西, 然后我尝试在vue.config.js中添加
transpileDependencies: ['element-ui'],
还是不行

**Comment by kililixi** [comment]
@luggege 请问您解决了吗

**Comment by GhostCatcg** [comment]
ie9 不支持flex呀
