### ISSUE TITLE
在线预览登录不进去

### ISSUE THREAD

**Issue by JingweiXiong** [PanJiaChen/vue-element-admin#2646]
在线预览的相关接口不再维护了么？登录不进去，接口404.

**Comment by PanJiaChen** [comment]
请帖地址或者报错截图。

**Comment by JingweiXiong** [comment]
地址：https://panjiachen.gitee.io/vue-element-admin/#/login?redirect=%2Fdashboard
截图：
![Snipaste_2019-10-10_18-45-32](https://user-images.githubusercontent.com/19570679/66562875-211e5f00-eb8f-11e9-8161-9af99278118a.png)
![Snipaste_2019-10-10_18-46-06](https://user-images.githubusercontent.com/19570679/66562883-25e31300-eb8f-11e9-8004-85477e81953e.png)

**Comment by PanJiaChen** [comment]
试了下没什么问题。而且本身预览页面的请求是纯前端mock的，不会发送实际请求。

**Comment by JingweiXiong** [comment]
那就奇怪了，我再次尝试还是一样。

**Comment by PanJiaChen** [comment]
清一下缓存，或者用隐藏窗口试试。

**Comment by JingweiXiong** [comment]
忘记回复了。
是我装了请求代理插件导致的，关闭掉就正常的了。
