### ISSUE TITLE
TagsView组件中，鼠标滚轮按下的时候，可以关闭不可关闭的tag

### ISSUE THREAD

**Issue by Zq986928835** [PanJiaChen/vue-element-admin#2648]
TagsView做了很有意思的掩藏操作，不看代码还真不知道，鼠标滚轮按下的时候可以关闭不可关闭的tag。
![image](https://user-images.githubusercontent.com/20550145/66622352-d39b0400-ec19-11e9-84dc-7babb5d39e66.png)
如上图 documentation 是不可关闭的
但是滚轮按下后，真的关闭了
![image](https://user-images.githubusercontent.com/20550145/66622442-34c2d780-ec1a-11e9-9061-d51e8b7abd58.png)

<^-^> 说实话，web真的是很少这类便捷的操作，不像手机设备，这个操作 nice

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/2649
