### ISSUE TITLE
是否尝试用elementui2.0呢

### ISSUE THREAD

**Issue by nevermorever** [PanJiaChen/vue-element-admin#265]

**Comment by PanJiaChen** [comment]
改动较大，暂时在优化其它东西，过一段时间会升级。
个人觉得可能要等elementui2.1版本了。。。

**Comment by nevermorever** [comment]
好, 支持楼主!(~~)

**Comment by jianliulin** [comment]
希望早日支持eleme 2.0

**Comment by Leopoldthecoder** [comment]
关于升级到 2.0，如果有什么需要我们帮忙的可以直接在这里 @ 我。

**Comment by dingyi1993** [comment]
其实改动不算太大，照着release log全局搜索替换掉费兼容性的代码就好，目前我司的项目已经升级了elementUI2.0.0，有什么问题可以@我哦。

**Comment by PanJiaChen** [comment]
目前已在 [refacor/style](https://github.com/PanJiaChen/vue-element-admin/tree/refacor/style) 分支升级为2.0 升级成本主要就是一些 breaking changes 而已

**Comment by srw962** [comment]
是否可以使用element-ui 2.0的container重新设计框架布局？感觉顶部随上下滚动条滚动不太好，最好是顶部固定住。
另外现在refacor/style里当打开的页面多时会导致上部的导航超出横向范围，出现横向滚动条

**Comment by PanJiaChen** [comment]
吸附问题应该不会调整，市面上主流的admin有吸顶的也有没有的，所以还是按照自己的需求来吧，自行修改也很方便。
refacor/style 分支目前还在不断迭代调整中，尽请期待

**Comment by PanJiaChen** [comment]
已发布3.0 使用了element@2.0.5版本

**Comment by PetersonLian** [comment]
厉害了。正好在一个小时前，发布了使用element 2.0.5的版本。先围观。ok就切换
