### ISSUE TITLE
引用图表源码// import { debounce } from '@/utils'，不理解这个是在引入什么东西？

### ISSUE THREAD

**Issue by isfighting** [PanJiaChen/vue-element-admin#2657]
源码：
```
加上下面的代码就报错，提示不是一个方法；
import { debounce } from '@/utils'，

    // this.$_resizeHandler = debounce(() => {
    //   if (this.chart) {
    //     this.chart.resize()
    //   }
    // }, 100)
```
这段代码注释了就没问题了，貌似是因为调用了debounce方法，但这个方法没有定义；并且在引入的时候，貌似就没有引入什么。。。

**Comment by PanJiaChen** [comment]
请先学会提问。
我都不知道你想问什么？
人家报错不是已经告诉你什么问题了么。

**Comment by isfighting** [comment]
> 请先学会提问。
> 我都不知道你想问什么？
> 人家报错不是已经告诉你什么问题了么。

感谢大佬百忙之中的回答，我就问下import { debounce } from '@/utils'，这句话在引入什么，utils文件里也没有导出debounce 这个东西；

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/6a214f0eac0a4cbf712853480f4477dec427978e/src/utils/index.js#L244
这个不就是么

**Comment by isfighting** [comment]
> https://github.com/PanJiaChen/vue-element-admin/blob/6a214f0eac0a4cbf712853480f4477dec427978e/src/utils/index.js#L244
> 
> 
> 这个不就是么

多谢指教，是我疏忽了。
