### ISSUE TITLE
npm install 出现错误，依赖已不支持

### ISSUE THREAD

**Issue by 839588378** [PanJiaChen/vue-element-admin#2660]
## Bug report（问题描述）
按照文档，下载下来，npm install的时候出现错误

#### Steps to reproduce（问题复现步骤）
按照文档，下载下来，npm install的时候出现错误

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/23494356/66823658-45a47d80-ef79-11e9-813e-1ae20dc08a74.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
warning 暂时忽略。
https://github.com/PanJiaChen/vue-element-admin/issues/2046
