### ISSUE TITLE
刚开始使用element-admin,克隆下来的项目跑不了什么情况，登录报404

### ISSUE THREAD

**Issue by PotCharlesLee** [PanJiaChen/vue-element-admin#2661]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
请确定服务的端口正确 是否为9527？

**Comment by PotCharlesLee** [comment]
> 请确定服务的端口正确 是否为9527？

应该是我同时起了多个项目，端口被占用了的原因，我就说怎么一直报404，感谢大大百忙抽空回复问题！！
