### ISSUE TITLE
[请教下]如何在这个项目里增加多个管理员账号呢；目前好像只有admin和editor两个账号

### ISSUE THREAD

**Issue by yonghui666** [PanJiaChen/vue-element-admin#2662]
## 问：如何增加多个管理员账号？
>  实在找不到这个验证账号的逻辑放在哪里了；求大佬指教；

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/mock/user.js

https://github.com/PanJiaChen/vue-element-admin/blob/master/src/store/modules/user.js
