### ISSUE TITLE
v-waves修饰的组件如果也监听的click事件比如@click ,水波纹失效。

### ISSUE THREAD

**Issue by shizuka0958** [PanJiaChen/vue-element-admin#2663]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
如果有问题，请提供可还原demo。

https://github.com/PanJiaChen/vue-element-admin/blob/46cc375d0d91261a7962715dd48e66e10e8c5872/src/views/table/complex-table.vue#L14

**Comment by QuachDuy** [comment]
@PanJiaChen: v-waves not working if use @click="handleFilter".

**Comment by Ximeng0918** [comment]
v-waves not working if use @click="handleFilter".

**Comment by Ximeng0918** [comment]
> @PanJiaChen: v-waves not working if use @click="handleFilter".

更改自定义指令js中绑定事件为在捕获阶段执行。
`el.addEventListener('click', handleClick(el, binding), false)`
false更改为true
