### ISSUE TITLE
ie兼容

### ISSUE THREAD

**Issue by dml5775** [PanJiaChen/vue-element-admin#2668]

**Comment by xiaopenggithub** [comment]
大佬，兼容解决了吗？我也遇到ie11不兼容问题？

**Comment by kuangqie** [comment]
我也没有解决,网上说的都试了,没效果,白屏报语法错误
![image](https://user-images.githubusercontent.com/46955073/102873619-4f2e4d00-447c-11eb-8ecb-733b05067d70.png)
