### ISSUE TITLE
props 字段命名问题-驼峰与横线

### ISSUE THREAD

**Issue by Nolin-Lin** [PanJiaChen/vue-element-admin#2670]
## Question（提问）

![image](https://user-images.githubusercontent.com/26018639/67174105-79f1c100-f3f3-11e9-82d3-4493df4be855.png)

props 的字段名问题，我想只用驼峰，不用横线，需要怎么配置eslint?
因为我用的是 $attrs 的
![image](https://user-images.githubusercontent.com/26018639/67174199-cf2dd280-f3f3-11e9-9dd8-738aee28abbd.png)

#### Other relevant information（格外信息）
- Your OS: Mac
- Node.js version:v10.15.3
- vue-element-admin version: "4.2.1",

**Comment by PanJiaChen** [comment]
https://eslint.vuejs.org/rules/attribute-hyphenation.html
