### ISSUE TITLE
关于使用引导的bug

### ISSUE THREAD

**Issue by JingweiXiong** [PanJiaChen/vue-element-admin#2671]
当右边的顶部导航和标签栏使用fixed header模式时，使用引导的功能大概是因为fixed定位z-index的问题导致引导的内容显示不出来：
![image](https://user-images.githubusercontent.com/19570679/67182480-e8457c00-f411-11e9-96f1-32f0fcdaac12.png)

**Comment by JingweiXiong** [comment]
粗略建议做法如下：
![image](https://user-images.githubusercontent.com/19570679/67189808-7aa14c00-f421-11e9-84b7-68bc2983d59e.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1920
