### ISSUE TITLE
在一个浏览器打开多个标签页登陆不同的用户，貌似现在的token都是公用一个

### ISSUE THREAD

**Issue by zhychao** [PanJiaChen/vue-element-admin#2672]
在一个浏览器打开多个标签页登陆不同的用户，貌似现在的token都是公用一个

**Comment by lzq920** [comment]
在同一个浏览器中，多标签访问到cookie都是一样的，你换个浏览器就是不一样的了

**Comment by PanJiaChen** [comment]
实现不了。
除非你种不同的key的 cookie。
而且我个人认为，你的需求本身就比较特殊。
