### ISSUE TITLE
执行npm install电脑蓝屏问题

### ISSUE THREAD

**Issue by wangxiaoyi3** [PanJiaChen/vue-element-admin#2675]
克隆项目后，执行npm install命令安装，结果安装过程中电脑就蓝屏了，每次都一样，感觉不是node-sass的问题，看文档说node-sass问题是npm install失败，一直不知道问题出在哪里，安装其他项目都是正常的，求大佬指点，急求！

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
