### ISSUE TITLE
导航标签切换时，可以不刷新吗？

### ISSUE THREAD

**Issue by githubFarwalker** [PanJiaChen/vue-element-admin#2679]
导航标签切换时，可以不刷新吗？
用户设置了列表的查询条件，切换到其他标签，再回来，查询的数据有变成无条件了
![ab](https://user-images.githubusercontent.com/45278099/67376441-b6b9e580-f5b6-11e9-8ef8-a5e6572a1404.png)

**Comment by PanJiaChen** [comment]
你确定是不是自己的问题。
https://panjiachen.github.io/vue-element-admin/#/table/complex-table
能记住筛选项。

如有问题，请提供重现步骤。
