### ISSUE TITLE
老板，有没有打算换UI ？

### ISSUE THREAD

**Issue by cloupusone** [PanJiaChen/vue-element-admin#268]
https://github.com/iview/iview

**Comment by PanJiaChen** [comment]
不考虑替换 `element-ui`

**Comment by cloupusone** [comment]
什么原因呢，从UI效果来看，ivew的更好

**Comment by PanJiaChen** [comment]
个人选择问题，做一个产品不能单从ui层面考虑，维护成本和社区活跃度也是一个需要考量的问题，详细见之前写的[分析](https://segmentfault.com/a/1190000009762198#articleHeader1)，如有需求可以自行替换，陈本不是很大的。

**Comment by zhangalex** [comment]
iview 功能设计和健壮性都没有elementui好，还有个大问题就是iview是个小厂做的，问题反馈基本上不处理，比较小众。

**Comment by bi-kai** [comment]
现在来看没有换iview是正确的，那边搞收费后，免费版几乎不维护了。iview admin已一年未更新了。
