### ISSUE TITLE
二级路由刷新空白问

### ISSUE THREAD

**Issue by gitapteryx** [PanJiaChen/vue-element-admin#2682]
## Question（提问）
不论本地与线上都是如此，二级地址刷新后是大白板
试过google的各种办法包括 更改vue.config.js 的 publicPath、路由的index.js的baseUrl:"/ "(我看缺省值就是这个)  还有nginx try_files 的设置 依然无效。
还请裤衩兄指点一二 ，本人前端小白还请谅解，谢谢！！~

![image](https://user-images.githubusercontent.com/20149184/67450391-d6511c80-f64f-11e9-9fd0-ecb0fe50dd4f.png)

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/67563766-f8cc5e00-f753-11e9-83d6-161988e11272.png)
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/router-and-nav.html#%E5%A4%9A%E7%BA%A7%E7%9B%AE%E5%BD%95-%E5%B5%8C%E5%A5%97%E8%B7%AF%E7%94%B1
