### ISSUE TITLE
Response to preflight request doesn't pass access control check

### ISSUE THREAD

**Issue by Xanthuim** [PanJiaChen/vue-element-admin#2684]
登录成功后重定向到/dashboard的时候报错，从错误信息来看是跨域问题。但后端已经解决了跨域问题，不然登录接口用不了。
![微信截图_20191025142430](https://user-images.githubusercontent.com/23351958/67548037-57351480-f733-11e9-85ee-f64747c3b914.png)

**Comment by Xanthuim** [comment]
我项目本身的问题，原因是因为集成了Shiro。。。

**Comment by wswang1** [comment]
你们是怎么解决的啊，我们也遇到了一样的问题
