### ISSUE TITLE
isFullscreen判断是否全屏的属性改了

### ISSUE THREAD

**Issue by ForAFuture** [PanJiaChen/vue-element-admin#2695]
screenfull插件，因为install的时候版本是最新的5.0.0，里面判端是否全屏属性screenfull.enabled变成了screenfull.isEnabled

**Comment by PanJiaChen** [comment]
是的
详情见：https://github.com/PanJiaChen/vue-element-admin/pull/2642/commits/459bef2d2f76a9212a6546039105109b5a37fca7
