### ISSUE TITLE
登录时除了把token存在Cookie里，别的参数要怎么存在请求头header里

### ISSUE THREAD

**Issue by yu-aa** [PanJiaChen/vue-element-admin#2699]

**Comment by bihell** [comment]
请求里面设置就可以了 config.headers  ，可以参考我的代码 https://github.com/bihell/Dice/blob/master/dice-admin/src/utils/request.js

**Comment by code-admin** [comment]
![image](https://user-images.githubusercontent.com/43529409/77899745-96056280-72af-11ea-8918-222f6f11c459.png)

**Comment by PanJiaChen** [comment]
在 `service.interceptors` 里设置就好了。
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/utils/request.js
