### ISSUE TITLE
如何将Levelbar组件点击不是刷新页面，而是保留历史页面？

### ISSUE THREAD

**Issue by D-T-Y** [PanJiaChen/vue-element-admin#270]
近期，我有个问题困扰着我，
如何将Levelbar组件点击不是刷新页面，而是保留历史页面？

**Comment by PanJiaChen** [comment]
使用<keep-alive> 之后的新版本会保留历史页。
不过目前有一些小问题，待vue官方解决了之后会更新

**Comment by dty1992** [comment]
好的，我也先用<keep-alive>尝鲜一下

**Comment by D-T-Y** [comment]
我刚才尝试了一下，正常

我很想知道你说的小问题是什么

**Comment by D-T-Y** [comment]
我刚才尝试了一下，正常

我很想知道你说的小问题是什么

**Comment by PanJiaChen** [comment]
比较复杂 如如何清除 `keep alive` 的 `cache`, 路由嵌套，公用view等一些小细节问题，之后3.0版本会包含该些功能

**Comment by daiing** [comment]
期待3.0早日完工

**Comment by PanJiaChen** [comment]
已发布3.0 看看是否满足你们的需求
