### ISSUE TITLE
父级导航加click不起作用

### ISSUE THREAD

**Issue by by-oneself** [PanJiaChen/vue-element-admin#2701]
![image](https://user-images.githubusercontent.com/25608788/67858412-0f0f5b00-fb54-11e9-84a6-feb10f1e11b9.png)

**Comment by sunpu007** [comment]
没事多看看VueAPI文档，这是一个很低级的错误

**Comment by by-oneself** [comment]
> 没事多看看VueAPI文档，这是一个很低级的错误

那你倒是说怎么解决呀

**Comment by sunpu007** [comment]
> > 没事多看看VueAPI文档，这是一个很低级的错误
> 
> 那你倒是说怎么解决呀

template压根就不是一个标签，也不会解析成标签，下来自己去想
