### ISSUE TITLE
请问一下，各位，怎么webpack配置gzip压缩，谢谢

### ISSUE THREAD

**Issue by guoxiao158** [PanJiaChen/vue-element-admin#2704]

**Comment by xlb** [comment]
在vue.config.js中添加
`const CompressionWebpackPlugin = require('compression-webpack-plugin')
const productionGzipExtensions = ['js', 'css']`

然后再添加
`  configureWebpack: {
    // provide the app's title in webpack's name field, so that
    // it can be accessed in index.html to inject the correct title.
    name: name,
    resolve: {
      alias: {
        '@': resolve('src')
      }
    },
    plugins: [
      new CompressionWebpackPlugin({
        filename: '[path].gz[query]', // 提示compression-webpack-plugin@3.0.0的话asset改为filename
        algorithm: 'gzip',
        test: new RegExp('\\.(' + productionGzipExtensions.join('|') + ')$'),
        threshold: 10240,
        minRatio: 0.8
      })
    ]

  },`

**Comment by PanJiaChen** [comment]
https://zhuanlan.zhihu.com/p/69864841

https://github.com/vuejs/vue-cli/issues/978

**Comment by wanqianjin** [comment]
打包后的.gz文件没有的名称不对
