### ISSUE TITLE
为啥没有webpack 的配置文件

### ISSUE THREAD

**Issue by jojoguang** [PanJiaChen/vue-element-admin#2708]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by cnsummer** [comment]
具体可以查看一下vue-cli3的配置

**Comment by dongshaofei666** [comment]
vue-cli3封装了webpack,在vue-cli的配置文件中就可以配置webpack，配置方法与之前一样

**Comment by PanJiaChen** [comment]
收敛到了 https://github.com/PanJiaChen/vue-element-admin/blob/master/vue.config.js
