### ISSUE TITLE
TabsView.vue 无法保存带参数的url

### ISSUE THREAD

**Issue by laogui** [PanJiaChen/vue-element-admin#272]
TabsView 这个组件对于频繁切换最近几个页面很有用，但无法保存带参数的URL，本来页面是/detail/50，点击 tabview 页面url就成了/detail/:id

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/660ff765f5f8ad29884a201e463ed68196bc94e8
已修复
