### ISSUE TITLE
一个high vulnerabilities: lodash版本不满足 >=4.17.12

### ISSUE THREAD

**Issue by Raven98** [PanJiaChen/vue-element-admin#2724]
## Bug report（问题描述）
第一次 `npm install` 原始项目即出现此问题
#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/23434964/68297279-7f2c5c80-00d1-11ea-87b7-f3fcab148623.png)

#### Other relevant information（格外信息）
- Your OS: MacOS 10.14.5
- Node.js version: 6.11.3
- vue-element-admin version: the newest

**Comment by kukukakiki** [comment]
lower npm version to 5.6.0（npm版本降到5.6.0）

**Comment by PanJiaChen** [comment]
依赖问题，可以忽略。
或者自己手动升级相关依赖。
