### ISSUE TITLE
element-ui自带的小图标都变成框框了，还有多次自动打开浏览器

### ISSUE THREAD

**Issue by AK47-dadada** [PanJiaChen/vue-element-admin#2736]
最新版本
我只是搬运了一下，npm install 了一下  npm run dev了一下，结果小图标它居然不见了。。。。，唯有你的svg图标都还在。
![image](https://user-images.githubusercontent.com/30396595/68455844-48705680-0237-11ea-88a0-1320c15bdc52.png)
![image](https://user-images.githubusercontent.com/30396595/68455879-5b832680-0237-11ea-9976-bfe646b96329.png)
还会有重新启动之后页面跳转不对
![image](https://user-images.githubusercontent.com/30396595/68456001-a4d37600-0237-11ea-8dae-e366cd2e360c.png)
还有项目启动会多次弹出自动打开浏览器，望解答

**Comment by wudongyu1994** [comment]
我也是，同求洁解
