### ISSUE TITLE
vue 配置别名@->’src‘后引入@antv/f2 

### ISSUE THREAD

**Issue by mouday** [PanJiaChen/vue-element-admin#2737]
配置别名
alias: {
                '@': resolve('src')
            },

导包报错， 提示模块不存在

import F2 from "@antv/f2"

如何解决？在线等，挺急的

**Comment by PanJiaChen** [comment]
```
alias: {
'node_modules': resolve('node_modules')
}
```

`import F2 from 'node_modules/@antv/f2'`
