### ISSUE TITLE
能否增加一个表头自定义的示例

### ISSUE THREAD

**Issue by zsedcbm** [PanJiaChen/vue-element-admin#275]
table-column的render-header 方法 不是很明白怎么用.
element组件提供了filter为数组形式的过滤,我想搞一个通过日期范围选择的方式进行过滤,但是对于写法不熟悉,不知道怎么下手.

**Comment by PanJiaChen** [comment]
这都是 element 官方文档写明的东西不认为有添加demo的需求
有需求可以去 [segmentfault](https://segmentfault.com/) 等网站咨询

[render-header demo](http://jsfiddle.net/770tasuc/)
