### ISSUE TITLE
production deployment is super slow

### ISSUE THREAD

**Issue by alexanderkraemer** [PanJiaChen/vue-element-admin#2754]
After deploying this project to production, i see, that it's super slow, and the browser crashes a few seconds to minutes after the first load.
Anything I might be missing here?

#### Other relevant information（格外信息）
- Your OS: ubuntu 18.04 @ 2vCPU 4gb RAM
- Node.js version: 9.x
- vue-element-admin version: latest

**Comment by alexanderkraemer** [comment]
I Also tried with node version 8.x Still very slow!

**Comment by PanJiaChen** [comment]
Import large dependencies such as `element-ui` 、`echarts`, by way of cdn.

https://panjiachen.gitee.io/vue-element-admin-site/guide/advanced/cdn.html#way-of-use
