### ISSUE TITLE
最新版本 vue-element-admin chrome下http://localhost:9527/ 样式异常问题

### ISSUE THREAD

**Issue by chenweihan** [PanJiaChen/vue-element-admin#2755]
使用IP              chrome IE都正确
使用localhost  IE正确  chrome异常
![QQ图片20191116102648](https://user-images.githubusercontent.com/1927864/68986585-cfd35080-085b-11ea-8ef5-e5374ec4ec14.png)
![QQ图片20191116103044](https://user-images.githubusercontent.com/1927864/68986627-2b054300-085c-11ea-9af2-245331156c0f.png)

测试发现 localhost  下html的高宽不正常？ IP下是正常的

**Comment by PanJiaChen** [comment]
你这是页面缩放了。
