### ISSUE TITLE
为什么会请求https://mc.yandex.ru/，怎么关掉

### ISSUE THREAD

**Issue by zhangpanfei** [PanJiaChen/vue-element-admin#2756]
我的站点一直请求https://mc.yandex.ru/这个地址，请问这是什么，怎么关掉

**Comment by PanJiaChen** [comment]
![Uploading image.png…]()

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/68996127-d2bc5880-08d0-11ea-8633-bd9126c0b0e5.png)

**Comment by zhangpanfei** [comment]
谢谢，是某个chrome插件的问题，关闭了就没有这种请求了

**Comment by michaelsss1** [comment]
是哪个插件啊？谢谢
