### ISSUE TITLE
点击浏览器刷新按钮后页面空白什么都没有

### ISSUE THREAD

**Issue by wxxtqk** [PanJiaChen/vue-element-admin#276]
store.dispatch('GenerateRoutes', store.getters.roles).then(() => {
              console.log('路由表', store.getters.addRouters)
              router.addRoutes(store.getters.addRouters) // 动态添加可访问的路由
              // next({...to}) // hack方法,确保addRutes已完成
              next() // 直接使用该方法刷新页面后不会保留在历史页，而页面是空白的
            })
      如果直接使用next()，在页面中刷新后页面什么都没有，只有一个#app跟节点.
      如果使用next({...to})的话页面就正常，刷新后还是在历史页面，
      虽然文档写的hack方法，确保addRutes已完成，但是这儿还是不要理解，麻烦楼主详细说一下好么，非常感谢

**Comment by PanJiaChen** [comment]
主要是 `addRoutes` 没有callback function 所以 你不能确定你 `next()` 之后进去的页面已成功被 `addRoutes` 添加。 而next(xxx) 会重新再次进入 `router.beforeEach` 这个钩子 这时候 `addRoutes` 已success 所以能直接 next()
