### ISSUE TITLE
QQ付费群踢人是什么操作?

### ISSUE THREAD

**Issue by dengshenkk** [PanJiaChen/vue-element-admin#2765]
## Question（提问）
QQ付费群踢人是什么操作?

#### Steps to reproduce（问题复现步骤）
踢人有没有理由?

#### Screenshot or Gif（截图或动态图）
[http://q0yfsobff.bkt.clouddn.com/11.png](url)
[http://q0yfsobff.bkt.clouddn.com/22.png](url)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
定时清人吧，应该会按最后发言时间倒序清理。

**Comment by dengshenkk** [comment]
@PanJiaChen 付费群也踢人?  卧槽无情! unstar

**Comment by PanJiaChen** [comment]
搞笑。你付费是付了多少？
![image](https://user-images.githubusercontent.com/8121621/69143830-e6500500-0b04-11ea-899c-3862826af2f0.png)
