### ISSUE TITLE
DatePicker 没有读到简体中文的语言档

### ISSUE THREAD

**Issue by mukiwu** [PanJiaChen/vue-element-admin#2766]
## Question（提问）

自己写的语言档可以成功读取到并切换语言。
但是 element-ui 的语言档却只能读到 en.js，简体中文读不到，不仅是 date picker，所有 element 套件都没办法切换语系。

这是在 lang/index.js 的 code (我用的是基础模板)

import Vue from 'vue'
import VueI18n from 'vue-i18n'
import elementEnLocale from 'element-ui/lib/locale/lang/en' // element-ui lang
import elementZhLocale from 'element-ui/lib/locale/lang/zh-CN'// element-ui lang
import enLocale from './en'
import zhLocale from './zh'

Vue.use(VueI18n)

const messages = {
  en: {
    ...enLocale,
    ...elementEnLocale
  },
  zh: {
    ...zhLocale,
    ...elementZhLocale
  } 
}
export function getLanguage() {
  const chooseLanguage = Cookies.get('language')
  if (chooseLanguage) return chooseLanguage

  // if has not choose language
  const language = (navigator.language || navigator.browserLanguage).toLowerCase()
  const locales = Object.keys(messages)
  for (const locale of locales) {
    if (language.indexOf(locale) > -1) {
      return locale
    }
  }
  console.log(messages)
  return 'en'
}
const i18n = new VueI18n({
  // set locale
  // options: en | zh | es
  locale: getLanguage(),
  // set locale messages
  messages
})

export default i18n

**Comment by hyysgit** [comment]
找到 main.js  下的代码
`Vue.use(ElementUI, { locale })`
定位到
`import locale from 'element-ui/lib/locale/`
改成如下:
`import locale from 'element-ui/lib/locale/lang/zh-CN' // lang i18n`
就可以成功切换到中文
