### ISSUE TITLE
npm instal

### ISSUE THREAD

**Issue by liangkai1986** [PanJiaChen/vue-element-admin#277]

**Comment by liangkai1986** [comment]
npm ERR! code EINTEGRITY
npm ERR! sha1-Ozd2TYvAyKtJy+oWvAtVcmRRyqo= integrity checksum failed when using
sha1: wanted sha1-Ozd2TYvAyKtJy+oWvAtVcmRRyqo= but got sha1-DfnM8NsWE2F7gi/PCcPa
eeJ66Uc=. (1279510 bytes)

**Comment by PanJiaChen** [comment]
该错误和本项目无关，请自行 google 相关错误
