### ISSUE TITLE
有的组件不能用需要怎么添加？？？？？？

### ISSUE THREAD

**Issue by BigData-YC** [PanJiaChen/vue-element-admin#2771]
https://element.eleme.cn/#/zh-CN/component/backtop
在这个网站上找的组件有的不能用是什么情况？？？
要怎么接进来啊？？？？？
比如：<el-backtop></el-backtop>
<el-divider></el-divider>
--------------------------------------错误信息-----------------------------------------
Unknown custom element: <el-backtop> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by BigData-YC** [comment]
比如：el-backtop 、el-divider

**Comment by TopTopFly** [comment]
同样遇到该问题，是不是版本2.70太低了？

**Comment by BigData-YC** [comment]
可能是吧！！！！！！！
网站上人家的版本已经是2.12.0版本了
而我们用的还是2.7.2版本

**Comment by TopTopFly** [comment]
我把Element UI升级到2.12.0后，就可以用了。

**Comment by gongjyGithut** [comment]
先卸载原来的element在重新安装一下最新版就行了

**Comment by kawais** [comment]
重新安装最新版依然提示did you register the component correctly?
请问是还需要什么操作吗？

**Comment by BigData-YC** [comment]
npm run dev&nbsp; 。也既重启一下



---原始邮件---
发件人: "kawais"<notifications@github.com&gt;
发送时间: 2019年11月30日(星期六) 下午4:50
收件人: "PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"YC"<1528271058@qq.com&gt;;
主题: Re: [PanJiaChen/vue-element-admin] 有的组件不能用需要怎么添加？？？？？？ (#2771)



重新安装最新版依然提示did you register the component correctly?
 请问是还需要什么操作吗？

**Comment by kawais** [comment]
thanks

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/b57f2008bd6edec9daf4d22b0fa8a2da352cc6a9
已更新
