### ISSUE TITLE
Pagination and Calendar Components Are not Localizable to English

### ISSUE THREAD

**Issue by mazz** [PanJiaChen/vue-element-admin#2775]
## Bug report（问题描述）

Pagination component found at this path is not localizable to English:
`import Pagination from '@/components/Pagination'`

Calendar component is not localizable to English:
`el-date-picker`

Year, month and day values appear in Chinese.

#### Other relevant information（格外信息）
- Your OS:
Mac OS X 10.15
- Node.js version:
11.15.0
- vue-element-admin version:
2.7.0

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/2741
