### ISSUE TITLE
Chrome 中 开启 Vuejs devtool后报错信息

### ISSUE THREAD

**Issue by nshusr** [PanJiaChen/vue-element-admin#2777]
## Bug report（问题描述）
响应错误为：
vue.runtime.esm.js:619 [Vue warn]: Property or method "then" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <Navbar> at src/layout/components/Navbar.vue
       <Layout> at src/layout/index.vue
         <App> at src/App.vue
           <Root>

会打印多条类似错误

#### Steps to reproduce（问题复现步骤）
运行项目后，在浏览器控制选择 Vue ，就会在Console中输出

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/45023042/69396861-a7959700-0d1e-11ea-9e6c-259c3e48eabb.png)

#### Other relevant information（格外信息）
- Your OS: Manjaro Linux
- Node.js version: 13.1.0
- vue-element-admin version: next

**Comment by PanJiaChen** [comment]
没有返回promise。
你可以看一下报错的地方。

**Comment by nshusr** [comment]
克隆框架后运行就会返回错误，我试过却没法解决
希望大佬们看看这个 :bug: 
![image](https://user-images.githubusercontent.com/45023042/69506345-2a119700-0f69-11ea-803a-84fba0135b37.png)

**Comment by PanJiaChen** [comment]
https://github.com/vuejs/vue-devtools/issues/1099
