### ISSUE TITLE
面包屑部分的样式是如何实现的，感觉很流畅舒服。

### ISSUE THREAD

**Issue by X1aoHei** [PanJiaChen/vue-element-admin#2778]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/components/Breadcrumb/index.vue
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/styles/transition.scss#L31-L48
