### ISSUE TITLE
<social-sign />

### ISSUE THREAD

**Issue by wangliang4896** [PanJiaChen/vue-element-admin#2780]
登录界面关于分享的dialog qq,微信的代码login/index.vue中的&lt;social-sign / &gt;标签为什么就可以显示components/SocialSignin，我查了element ui中也没有这个标签呀？
刚刚接触vue，学习中，哪位道友知道解释一下，谢谢

**Comment by sunpu007** [comment]
`social-sign`是一个自定义的组件，通过`import SocialSign from './components/SocialSignin'`引入，并在`components: { LangSelect, SocialSign }`中注册后，就可以作为一个标签来使用，内容就是`/components/SocialSignin`中编写的内容

**Comment by wangliang4896** [comment]
多谢，明白的。
