### ISSUE TITLE
多国语

### ISSUE THREAD

**Issue by wangliang4896** [PanJiaChen/vue-element-admin#2784]
文档中说src/lang(是我理解的多国语吗)是国际化，但是代码中我没有发现有这个src/lang目录呀？请问这个项目是支持多国语的吗

**Comment by sunpu007** [comment]
因为大部分不会用到国家化，所有此项目开发者将i18n从主分支移除，如果有需要使用可以切换至`i18n`分支查看，文档地址：https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/i18n.html

**Comment by haiya6** [comment]
切换至`i18n`分支
Switch to the i18n branch

**Comment by wangliang4896** [comment]
好的，了解，谢谢
