### ISSUE TITLE
打包部署到服务器nginx后，访问后端接口404

### ISSUE THREAD

**Issue by zhangyu-yxff** [PanJiaChen/vue-element-admin#2788]
打包没问题，部署到服务器nginx后，主页可以正常访问，调用后端接口时报404并且提示：We're sorry but 网上报销系统 doesn't work properly without JavaScript enabled. Please enable it to continue.
修改了router的模式 history 还是不行 ，刚开始接触，麻烦大佬帮忙看看，多谢多谢~
`  publicPath: '/',
  outputDir: 'dist',
  assetsDir: 'static',
  lintOnSave: process.env.NODE_ENV === 'development',
  productionSourceMap: false,
  devServer: {
    port: port,
    open: false,
    overlay: {
      warnings: false,
      errors: true
    },
    proxy: {
      // change xxx-api/login => mock/login
      // detail: https://cli.vuejs.org/config/#devserver-proxy
      [process.env.VUE_APP_BASE_API]: {
        ws: false,
        target: `http://localhost:8090/`,
        changeOrigin: true,
        pathRewrite: {
          ['^' + process.env.VUE_APP_BASE_API]: ''
        }
      }
    }
    // after: require('./mock/mock-server.js')
  },
  configureWebpack: {
    // provide the app's title in webpack's name field, so that
    // it can be accessed in index.html to inject the correct title.
    name: name,
    resolve: {
      alias: {
        '@': resolve('src')
      }
    },`

**Comment by sunpu007** [comment]
需要你配置自己的服务端api

**Comment by sunpu007** [comment]
用最新版本打包部署Nginx未发现你所遇到的问题，可以把url贴出来看看，这是我部署的`http://test.myjerry.cn`

**Comment by zhangyu-yxff** [comment]
> 用最新版本打包部署Nginx未发现你所遇到的问题，可以把url贴出来看看，这是我部署的地址`http://test.myjerry.cn`

我这边调用了后端接口，本地run没有问题，麻烦发一下vue.config.js 和 nginx.conf 的 配置文件 是不是有什么地方没有修改

**Comment by zhangyu-yxff** [comment]
> 用最新版本打包部署Nginx未发现你所遇到的问题，可以把url贴出来看看，这是我部署的地址`http://test.myjerry.cn`

![image](https://user-images.githubusercontent.com/31466515/69684843-02e7d080-10f5-11ea-958f-39767d88ce9e.png)
这是我调用后端的配置，本地run是正常的 都部署在一台服务器上

**Comment by sunpu007** [comment]
根据你的描述，我暂判定你是自己写了一个服务端api，自己写的服务端api需要在Nginx上配置相应请求转发，类似这样
![image](https://user-images.githubusercontent.com/20461171/69685804-a5ee1980-10f8-11ea-8d95-572fbdb0057e.png)

**Comment by zhangyu-yxff** [comment]
> 根据你的描述，我暂判定你是自己写了一个服务端api，自己写的服务端api需要在Nginx上配置相应请求转发，类似这样
> ![image](https://user-images.githubusercontent.com/20461171/69685804-a5ee1980-10f8-11ea-8d95-572fbdb0057e.png)

![image](https://user-images.githubusercontent.com/31466515/69685893-eea5d280-10f8-11ea-977f-feb0d55d0969.png)
这是我目前nginx的配置

**Comment by sunpu007** [comment]
综上所述，你可以将你的配置改成如下：
![image](https://user-images.githubusercontent.com/20461171/69686213-02056d80-10fa-11ea-974b-10a745461ea2.png)

**Comment by zhangyu-yxff** [comment]
> 综上所述，你可以将你的配置改成如下：
> ![image](https://user-images.githubusercontent.com/20461171/69686213-02056d80-10fa-11ea-974b-10a745461ea2.png)

好的 我试下 非常感谢~

**Comment by zhangyu-yxff** [comment]
> 综上所述，你可以将你的配置改成如下：
> ![image](https://user-images.githubusercontent.com/20461171/69686213-02056d80-10fa-11ea-974b-10a745461ea2.png)

参照这种方式，重新安装了一遍nginx，调试了半天，终于跑通，非常感谢~
