### ISSUE TITLE
启动npm run build:site-preview 后，后台接口调用不成功

### ISSUE THREAD

**Issue by xulihua123** [PanJiaChen/vue-element-admin#279]
开发模式npm run dev 启动后，系统登录后没有问题，但是使用npm run build:site-preview发布到测试环境后，系统登录没有反应，查看控制台没有任何异常日志。
接口返回值如下：
![222](https://user-images.githubusercontent.com/5866093/32590284-959bdbea-c554-11e7-8efd-04ad8b105f96.png)

从返回结果来看，应该是json结构，为什么是html值？

**Comment by PanJiaChen** [comment]
不是很能理解你的问题

**Comment by xulihua123** [comment]
问题现在是，object为response返回对象，object 返回data值应该是登录接口返回的json对象，以下为打印object对象地方
/src/utils/fetch.js
> // respone拦截器
> service.interceptors.response.use(
>   response => {
>     /**
>      * 下面的注释为通过response自定义code来标示请求状态，当code返回如下情况为权限有问题，登出并返回到登录页
>      * 如通过xmlhttprequest 状态码标识 逻辑可写在下面error中
>      */
>     console.log('response success');
>     console.log(response);

`npm run build:prod` 运行编译生成的文件，运行时没有问题，object打印值为返回json对象
