### ISSUE TITLE
前端页面打包放nginx做代理报 Network Error 错，这是什么情况呢？

### ISSUE THREAD

**Issue by liqiang-p** [PanJiaChen/vue-element-admin#2792]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by liqiang-p** [comment]
能够访问登录页面，但是登录就会报 Network Error 的错误

**Comment by sunpu007** [comment]
希望你能将详细报错信息贴出来，`Network Error`只是一个错误类型，无法判定什么问题

**Comment by liqiang-p** [comment]
> 希望你能将详细报错信息贴出来，`Network Error`只是一个错误类型，无法判定什么问题
![avatar](https://ftp.bmp.ovh/imgs/2019/11/286649cca34bcb0d.png)
第一次用nginx做代理，做的反向代理，按网上给的配置把静态文件放在nginx上之后访问就报这个错

**Comment by sunpu007** [comment]
兄弟，你跨域了，根据提示，我暂判定你在项目中调用了自己的api服务，解决方法有两种，一种在api服务端代码中写入允许跨域，另一种使用nginx进行代理https://github.com/PanJiaChen/vue-element-admin/issues/2788#issuecomment-558890340

**Comment by liqiang-p** [comment]
> 兄弟，你跨域了，根据提示，我暂判定你在项目中调用了自己的api服务，解决方法有两种，一种在api服务端代码中写入允许跨域，另一种使用nginx进行代理[#2788 (comment)](https://github.com/PanJiaChen/vue-element-admin/issues/2788#issuecomment-558890340)

就是用 nginx 做了反向代理才这样啊，第一次用 nginx ,不会配置

**Comment by sunpu007** [comment]
Nginx配置你可以自行百度，上面，我也粘贴了其他人的Nginx配置问题链接
