### ISSUE TITLE
项目上线遇到的vue 报错Cannot read property 'uuid' of null

### ISSUE THREAD

**Issue by jaylun521521** [PanJiaChen/vue-element-admin#2797]
## Bug report（问题描述）
而且二图中的请求不知道是哪里产生的，不是我后台的接口
![image](https://user-images.githubusercontent.com/25146486/69788258-167c5f80-11f9-11ea-81a7-556afc5c6b88.png)
![image](https://user-images.githubusercontent.com/25146486/69788291-2431e500-11f9-11ea-9bba-f7318187e554.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by jaylun521521** [comment]
![image](https://user-images.githubusercontent.com/25146486/69788358-4af01b80-11f9-11ea-8d72-31407578360f.png)

**Comment by PanJiaChen** [comment]
和本项目无关，请确认是不是装了什么浏览器插件。

**Comment by jaylun521521** [comment]
这是一台新的服务器，很干净，上线之前只装了一个宝塔，项目放到宝塔中运行，我没有手动去安装浏览器插件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"花裤衩"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 晚上7:32
收件人:&nbsp;"PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com&gt;;
抄送:&nbsp;"名扬"<544032062@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 项目上线遇到的vue 报错Cannot read property 'uuid' of null (#2797)




和本项目无关，请确认是不是装了什么浏览器插件。

**Comment by jaylun521521** [comment]
而且本地跟测试环境是没有问题，只有这一台服务器的线上有这个问题。我也找不到哪里请求的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"花裤衩"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 晚上7:32
收件人:&nbsp;"PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com&gt;;
抄送:&nbsp;"名扬"<544032062@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 项目上线遇到的vue 报错Cannot read property 'uuid' of null (#2797)




和本项目无关，请确认是不是装了什么浏览器插件。
