### ISSUE TITLE
账号登录和注销问题

### ISSUE THREAD

**Issue by Lin07ux** [PanJiaChen/vue-element-admin#28]
在浏览器中，同时打开两个 tab，均登录到网站中。此时，在其中一个 tab 中注销登录，而另一个 tab 中可以正常切换路由，除非刷新页面才会自动退出到登录页面。

**Comment by PanJiaChen** [comment]
这部分我没放到前端做，因为我觉得后端做更安全。
就拿我司项目来说，每次操作都会向后端发请求验证token，如果你注销了，token自然验证不过，这时候返回一个状态码，前端来处理。
代码可见https://github.com/PanJiaChen/vue-element-admin/blob/master/src/utils/fetch.js#L24
