### ISSUE TITLE
如何将本项目跑在github.io下的

### ISSUE THREAD

**Issue by sunchenguang** [PanJiaChen/vue-element-admin#280]
`http://panjiachen.github.io/vue-element-admin`是使用了Github Pages的功能，默认会读`index.html`。但是在`source`选项中只看到`gh-pages branch, master branch, mater branch /docs folder`这3个选项。

本项目没看到有`gh-pages`分支， 或 /docs目录，请问是如何做的呢

**Comment by PanJiaChen** [comment]
本项目没使用分支的形式部署 `github.io` 是另行打包之后 手动放到  [PanJiaChen.github.io](https://github.com/PanJiaChen/PanJiaChen.github.io) 下的

**Comment by sunchenguang** [comment]
`User or orhanization site & Project site`。挂在`PanJiaChen.github.io`项目里了。

一直以为只有Project site

**Comment by PanJiaChen** [comment]
一样的
