### ISSUE TITLE
富文本 tinymce 本地怎么引入

### ISSUE THREAD

**Issue by redwolf1996** [PanJiaChen/vue-element-admin#2804]
#### Steps to reproduce（问题复现步骤）
1. 项目中tinymce是通过CDN的方式引入的
2. 我将cdn地址的js下载到本地的tinymce组件目录下
3. 加载无效

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/9690393/69935246-41272a80-150f-11ea-988f-70e9ad1964e9.png)
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by 2rever** [comment]
我是在`public`文件夹就是和`index.html`同级的地方，建立一个文件夹`plugins`，里面放库的文件
然后 改为`const tinymceCDN = window.location.origin + '/plugins/tinymce-all-in-one/tinymce.min.js'`

**Comment by redwolf1996** [comment]
> 我是在`public`文件夹就是和`index.html`同级的地方，建立一个文件夹`plugins`，里面放库的文件
> 然后 改为`const tinymceCDN = window.location.origin + '/plugins/tinymce-all-in-one/tinymce.min.js'`

见笑了兄弟，是我没引对，其实主要是由于网络差提出这样的问题，在生产环境中像这些可复用的插件一般也会放到文件存储云平台，然后做cdn加速吧

**Comment by mcq-rgba** [comment]
我按照您说的操作，会报 Uncaught SyntaxError: Unexpected token '<' _ _ _ _ /plugins/langs/zh_CN.js:1 ,请问你们有遇到这样的问题吗

**Comment by mcq-rgba** [comment]
> 我是在`public`文件夹就是和`index.html`同级的地方，建立一个文件夹`plugins`，里面放库的文件
> 然后 改为`const tinymceCDN = window.location.origin + '/plugins/tinymce-all-in-one/tinymce.min.js'`

https://github.com/PanJiaChen/vue-element-admin/issues/2804#issuecomment-613934566
