### ISSUE TITLE
npm run build:prod点击其他页面加载对应的js会出错

### ISSUE THREAD

**Issue by BibBin** [PanJiaChen/vue-element-admin#282]
比如我的路由是这样子：
{
    path: '/report',
    component: Layout,
    redirect: '/report/agent-report',
    name: '报表管理',
    icon: 'chart',
    children: [
      { path: 'member-report', component: _import('report/agentRpt'), name: '课程列表 ' },
    ]
  },
当我点击整个课程列表的时候会在路径上加多一个report;
http://........./report/static/js/22.c6b0ffdba103f7fecb4c.js
正确的应该是：
http://........./static/js/22.c6b0ffdba103f7fecb4c.js
其他模块也是一样。。。。。求解怎么办

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/config/index.js#L10
请在这里配置自己需要的路径

**Comment by BibBin** [comment]
登录之后到首页是没问题的，在点击左侧的一个菜单，也是正常访问的，加载js的路径也是对的
像这样子
http://localhost:8080/static/js/22.c6b0ffdba103f7fecb4c.js
但是再点击其他菜单的时候
加载的js路径就会错了
像 我一开始描述的那样
http://localhost:8080/menber/static/js/22.c6b0ffdba103f7fecb4c.js

**Comment by BibBin** [comment]
@PanJiaChen 
登录之后到首页是没问题的，在点击左侧的一个菜单，也是正常访问的，加载js的路径也是对的
像这样子
http://localhost:8080/static/js/22.c6b0ffdba103f7fecb4c.js
但是再点击其他菜单的时候
加载的js路径就会错了
像 我一开始描述的那样
http://localhost:8080/menber/static/js/22.c6b0ffdba103f7fecb4c.js

**Comment by PanJiaChen** [comment]
`assetsPublicPath:'/'` 设置成这样试试
https://github.com/PanJiaChen/vue-element-admin/blob/master/config/index.js#L11

**Comment by BibBin** [comment]
@PanJiaChen 跟这个有点像
https://segmentfault.com/q/1010000007350931
以上的配置文件最后输出的静态文件的路径和上面给的那个图吻合。但是在我的业务逻辑当中使用了require.ensure([], function() {}, 'js/name')去异步加载业务模块。

现在遇到的问题就是通过HtmlWebpackPlugin因为filename的配置带有'pages'这个路径，需要异步加载这些模块的时候也因为多了这个pages而导致异步加载模块加载失败(404 Not Found).正确的路径是dist/js/xxxx.js, dist/css/xxxxx.css，现在却变成了dist/pages/js/xxxx.js, dist/pages/css/xxxx.css.请问如何在不改变最后打包出来的文件路径的情况下进行配置。

**Comment by BibBin** [comment]
@PanJiaChen 
assetsPublicPath:'/' 设置成这样可以了
