### ISSUE TITLE
npm run build:prod 生成的dist放在nginx下面以后，访问全是mock的数据，不能请求实际的项目地址。

### ISSUE THREAD

**Issue by Leo0426** [PanJiaChen/vue-element-admin#2822]
#### Steps to reproduce（问题复现步骤）
1. 我通过npm run build:prod  以后把生成的dist放在了nginx路径下面
2. 我实际的请求路径是  http:localhost:8080/db-api
3. 我的vue.config.js,nginx配置如下

#### nginx的config：
   server {
        charset utf-8;
        listen       80;
        server_name  localhost;
	    location / {
            root /Users/leolu/Public/Docker/Nginx/html;
            index index.html;
	    }
        location ^~ /prod-api/ { // <-----这里尝试修改成各种拦截路径均没有起效
		    proxy_pass http://localhost:8080/db-api;
	    }   
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }

#### vue配置：
module.exports = {
  publicPath: './',   // 《---这里配置了相对路径
  outputDir: 'dist',
  assetsDir: 'static',
  lintOnSave: process.env.NODE_ENV === 'production',  // 《---这里也改成了 生产配置
  productionSourceMap: false,
  devServer: {
    port: port,
    open: true,
    overlay: {
      warnings: false,
      errors: true
    },
    proxy: {
      [process.env.VUE_APP_BASE_API]: {
        target: `http://localhost:8080/db-api`,   // 《--这里也改了，但是会vue的朋友告诉我这里prod不会读取
        changeOrigin: true,
        pathRewrite: {
          ['^' + process.env.VUE_APP_BASE_API]: ''
        }
      }
    },
    after: require('./mock/mock-server.js')
  },

## .env.production 

ENV = 'production'
VUE_APP_BASE_API = 'http://localhost:8080/db-api'

#  我现在的情况是访问localhost:80 地址，可以访问到vue的后台页面，但是所有的请求都是mock的数据，服务请求到我localhost：8080/db-api的项目地址。 

#### 如果静态页面代理不了，我最后只能在线上用npm run dev的形式启动了，但是我不想这么做，还是想通过dist放入nginx里面的方式访问，求各位大神帮我看看是哪里的问题。

**Comment by wuhuisiyue** [comment]
实际开发是需要去掉mock的

**Comment by Leo0426** [comment]
> 实际开发是需要去掉mock的

我已经把 after: require('./mock/mock-server.js') 注释掉了，但是替换晚静态文件以后还是会访问mock数据，我需要怎么做呢？

**Comment by wuhuisiyue** [comment]
在main.js里面有个 引入 mock 也要去掉

**Comment by Leo0426** [comment]
> main.js

谢谢谢谢，一下子就好了。哇，我整了2天的问题。一直在翻看各种文档，第一次写vue的项目，我会重新再把相关知识点实践一遍的，太感谢了。

**Comment by maple5233** [comment]
把`.env.production`的`VUE_APP_BASE_API `改成`/prod-api` 
然后`lintOnSave`改回去这个和你这个问题没啥关系 只影响保存之后是不是自动执行eslint fix

**Comment by Leo0426** [comment]
> 把`.env.production`的`VUE_APP_BASE_API `改成`/prod-api`
> 然后`lintOnSave`改回去这个和你这个问题没啥关系 只影响保存之后是不是自动执行eslint fix

好的好的，谢谢啦。

**Comment by Romantic-Jan** [comment]
学习了
