### ISSUE TITLE
今天刚clone了项目，有2个问题，1是 run dev后 20%会打开一次浏览器 然后编译完毕会打开第二次。。。

### ISSUE THREAD

**Issue by hugselina2019** [PanJiaChen/vue-element-admin#2826]
1、1是 run dev后 20%会打开一次浏览器 然后编译完毕会打开第二次
2、按照issue里的回答 main.js添加 element的中文后 编译出来的项目仍然是英文。。下面上图
![image](https://user-images.githubusercontent.com/20763416/70518120-c4cac200-1b74-11ea-8e2f-2b2d3b6ef31a.png)
![image](https://user-images.githubusercontent.com/20763416/70518133-cac0a300-1b74-11ea-8238-f1b707b6bd82.png)
有没有老哥知道是怎么肥事吗 ？

**Comment by hugselina2019** [comment]
图片还挂了。。。崩溃

**Comment by jingchaocheng** [comment]
@hugselina2019  
1. `package.json` 中在 dev 命令后面加上 `--open` 参数
2. `vue.config.json` 中注释 devServer 下面的 open: true

**Comment by hugselina2019** [comment]
> @hugselina2019
> 
> 1. `package.json` 中在 dev 命令后面加上 `--open` 参数
> 2. `vue.config.json` 中注释 devServer 下面的 open: true

注释了，现在只有编译完成后打开一次了 感谢老哥。 不过为什么还是英文的。。。

**Comment by hugselina2019** [comment]
解决了 打开页面2次不知道为什么 所以直接用了@jingchaocheng 老哥的open:false，  然后切换了i18n分支 安装了i18n再次dev就是中文版了 感谢作者
