### ISSUE TITLE
How to create the tabs and maintain the state of the components without reloading them with each click?

### ISSUE THREAD

**Issue by farnetani** [PanJiaChen/vue-element-admin#284]
I would like to load some tab and it will NOT RECHARGE the route, ie assuming I have already loaded a certain component, for example a form where I fill a certain value within some input. So if I click on another option and want to go back to that form component I'd like it to be the way I left it.

**Comment by PanJiaChen** [comment]
you can add `keep-alive` and remove the key in https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/layout/AppMain.vue#L4

like
```html
<keep-alive>
  <router-view></router-view>
</keep-alive>
```

**Comment by farnetani** [comment]
Fantastic ... Thank you so much !!! I've been looking for this for a long time!

It worked!

Congratulations!!!
