### ISSUE TITLE
手机模式下文档tab里的系列文章和其他的不对称

### ISSUE THREAD

**Issue by Silentdoer** [PanJiaChen/vue-element-admin#2842]
手机模式下文档tab里的系列文章和其他的不对称

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/262c0ba08e80df87768c1bd855374ef2ec93432e

**Comment by Silentdoer** [comment]
你好，请问下这个改动是会同时同步到master和i18n吧？

**Comment by Silentdoer** [comment]
还有个问题就是我npm install时提示很多过时的包。。

**Comment by Silentdoer** [comment]
你好，我按你的改了后系列文章比之前更歪一些了，好像是改错方向了吧？

**Comment by Silentdoer** [comment]
master可以了，不过i18n的还是有问题

**Comment by PanJiaChen** [comment]
已更新i18n了
