### ISSUE TITLE
登陆界面 Request failed with status code 405

### ISSUE THREAD

**Issue by zgx950813** [PanJiaChen/vue-element-admin#2859]
npm run dev后到登陆界面后，点击登陆出现Request failed with status code 405
![微信截图_20191219004104](https://user-images.githubusercontent.com/37904817/71105297-4915e880-21f8-11ea-856e-b175189c72cb.png)

**Comment by wgliyuli** [comment]
同问

**Comment by woo123123** [comment]
同问

**Comment by fengjiegithub** [comment]
启用纯前端 Mock
现在在mock/index.js也封装了一个纯前端 mock 的方法，你只需要在src/main.js中：

import { mockXHR } from '../mock'
mockXHR()
这样就会变成纯前端 mock 数据了和v4.0版本之前的 mock 方案是一样的，原理见上文。目前你看到的线上demo就是采用该种方式。

**Comment by Huberyfight** [comment]
![image](https://user-images.githubusercontent.com/23059411/71142661-fe758a00-2252-11ea-85f0-ee1574416664.png)
楼上的防范好用，不过我直接把它换成development了

**Comment by zgx950813** [comment]
> 启用纯前端 Mock
> 现在在mock/index.js也封装了一个纯前端 mock 的方法，你只需要在src/main.js中：
> 
> import { mockXHR } from '../mock'
> mockXHR()
> 这样就会变成纯前端 mock 数据了和v4.0版本之前的 mock 方案是一样的，原理见上文。目前你看到的线上demo就是采用该种方式。

多谢！！！

**Comment by theForagingPawns** [comment]
> 启用纯前端 Mock
> 现在在mock/index.js也封装了一个纯前端 mock 的方法，你只需要在src/main.js中：
> 
> import { mockXHR } from '../mock'
> mockXHR()
> 这样就会变成纯前端 mock 数据了和v4.0版本之前的 mock 方案是一样的，原理见上文。目前你看到的线上demo就是采用该种方式。

多谢大佬管用

**Comment by yuwenyes** [comment]
注释了这个判断就可以了：if (process.env.NODE_ENV === 'production') {
“在main.js中，在下面这处把production改为development” 这个改法不可以---不知道为什么

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/2929

重新拉取最新代码已修复。

**Comment by JaneChelle** [comment]
用的 后端接口 ，没用到 mock，根本没有这段代码，求解
