### ISSUE TITLE
无法启动项目

### ISSUE THREAD

**Issue by 875908494** [PanJiaChen/vue-element-admin#2862]
## Bug report（问题描述）

执行npm install 的时候回提示我没有设置python环境

## Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/38024532/71148856-cd538480-2267-11ea-957b-479cccd0eb59.png)
请问一下这个该怎么解决，是需要安装python吗

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/24

请自行查询Windows安装node-sass
