### ISSUE TITLE
npm run dev 打开网页登陆报 405

### ISSUE THREAD

**Issue by DarrenLuo** [PanJiaChen/vue-element-admin#2865]
#### Steps to reproduce（问题复现步骤）

直接 `npm run dev` 后打开网页直接登陆会报405，method not allowed

#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/6427009/71153534-4ce75080-2274-11ea-948e-d9ae95fa49a1.png)

#### Other relevant information（格外信息）
- Your OS: macos 10.15.2
- Node.js version: 12.12.0
- vue-element-admin version:  v4.0.0

需要将 main.js 中的

```js
if (process.env.NODE_ENV === 'production') {
  mockXHR()
}
```

中的 if 部分去掉即可

**Comment by Tit1e** [comment]
这个判断是生产环境启用mock，把 production 改为 development 就行了

**Comment by DarrenLuo** [comment]
嗯，只是直接根据教程 git clone 下来之后再 npm run dev 无法使用会让一些新手懵逼

**Comment by roblues** [comment]
在main.js中，在下面这处把production改为development，因为在dev模式下，原来的代码没有启动mock
if (process.env.NODE_ENV === 'development') {
  mockXHR()
}

**Comment by Sow-Hunter** [comment]
> 嗯，只是直接根据教程 git clone 下来之后再 npm run dev 无法使用会让一些新手懵逼

确实。对着教程来做，结果一直无法登录。对着 Google 搜了半天一直以为是 npm install 那步有问题，重试了好多次。教程对这块完全没有说明，对新人很不友好。

**Comment by yuwenyes** [comment]
注释了这个判断就可以了：if (process.env.NODE_ENV === 'production') {
“在main.js中，在下面这处把production改为development” 这个改法不可以---不知道为什么

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/2929

重新拉取最新代码已修复。
