### ISSUE TITLE
样式重复

### ISSUE THREAD

**Issue by Lowsik0522** [PanJiaChen/vue-element-admin#2867]

**Comment by PanJiaChen** [comment]
请按照规则提问，你这样问，谁知道什么问题。

**Comment by Lowsik0522** [comment]
不好意思哈 我是想搜索的。&nbsp;手贱。
感谢回复


&nbsp;

&nbsp;&nbsp;&nbsp; &nbsp;God bless you ! ! !&nbsp;
&nbsp; &nbsp;your sincerely

&nbsp; &nbsp;贵州师范学院物理班 管艳国


&nbsp; &nbsp;E-mail:553392278@qq.com


&nbsp; &nbsp;Mobile : 155-1909-8345
&nbsp; &nbsp;
&nbsp; &nbsp;地址：贵州师范学院&nbsp;



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "花裤衩"<notifications@github.com&gt;; 
发送时间: 2019年12月20日(星期五) 下午3:43
收件人: "PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com&gt;; 
抄送: "Jsguan"<gyg0522@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PanJiaChen/vue-element-admin] 样式重复 (#2867)




请按照规则提问，你这样问，谁知道什么问题。
