### ISSUE TITLE
点击左侧错误日志菜单后，控制台中出现错误信息

### ISSUE THREAD

**Issue by grath10** [PanJiaChen/vue-element-admin#287]
vue.esm.js:479 [Vue warn]: Property or method "a" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <ErrCode> at src\views\errlog\errcode.vue
       <Index> at src\views\errlog\index.vue
         <AppMain> at src\views\layout\AppMain.vue
           <Layout> at src\views\layout\Layout.vue
             <APP> at src\App.vue
               <Root>
warn @ vue.esm.js:479
warnNonPresent @ vue.esm.js:1634
get @ vue.esm.js:1675
render @ errcode.vue?a732:2
Vue._render @ vue.esm.js:4128
updateComponent @ vue.esm.js:2538
get @ vue.esm.js:2881
Watcher @ vue.esm.js:2870
mountComponent @ vue.esm.js:2542
Vue$3.$mount @ vue.esm.js:7863
Vue$3.$mount @ vue.esm.js:10066
init @ vue.esm.js:3501
createComponent @ vue.esm.js:5147
createElm @ vue.esm.js:5090
createChildren @ vue.esm.js:5218
createElm @ vue.esm.js:5123
patch @ vue.esm.js:5570
Vue._update @ vue.esm.js:2414
updateComponent @ vue.esm.js:2538
get @ vue.esm.js:2881
Watcher @ vue.esm.js:2870
mountComponent @ vue.esm.js:2542
Vue$3.$mount @ vue.esm.js:7863
Vue$3.$mount @ vue.esm.js:10066
init @ vue.esm.js:3501
createComponent @ vue.esm.js:5147
createElm @ vue.esm.js:5090
patch @ vue.esm.js:5606
Vue._update @ vue.esm.js:2424
updateComponent @ vue.esm.js:2538
get @ vue.esm.js:2881
run @ vue.esm.js:2958
flushSchedulerQueue @ vue.esm.js:2724
(anonymous) @ vue.esm.js:701
nextTickHandler @ vue.esm.js:648
Promise resolved (async)
timerFunc @ vue.esm.js:663
queueNextTick @ vue.esm.js:711
queueWatcher @ vue.esm.js:2811
update @ vue.esm.js:2948
Vue.$forceUpdate @ vue.esm.js:2445
(anonymous) @ vue.esm.js:7649
wrappedHook @ vue.esm.js:1863
invoker @ vue.esm.js:1810
(anonymous) @ vue.esm.js:7164
(anonymous) @ vue.esm.js:304
end @ vue.esm.js:6871
(anonymous) @ vue.esm.js:6882
setTimeout (async)
whenTransitionEnds @ vue.esm.js:6880
(anonymous) @ vue.esm.js:7195
requestAnimationFrame (async)
(anonymous) @ vue.esm.js:6838
requestAnimationFrame (async)
nextFrame @ vue.esm.js:6837
performLeave @ vue.esm.js:7188
leave @ vue.esm.js:7172
remove$$1 @ vue.esm.js:7263
removeAndInvokeRemoveHook @ vue.esm.js:5315
removeVnodes @ vue.esm.js:5289
patch @ vue.esm.js:5632
Vue._update @ vue.esm.js:2424
updateComponent @ vue.esm.js:2538
get @ vue.esm.js:2881
run @ vue.esm.js:2958
flushSchedulerQueue @ vue.esm.js:2724
(anonymous) @ vue.esm.js:701
nextTickHandler @ vue.esm.js:648
Promise resolved (async)
timerFunc @ vue.esm.js:663
queueNextTick @ vue.esm.js:711
queueWatcher @ vue.esm.js:2811
update @ vue.esm.js:2948
notify @ vue.esm.js:778
reactiveSetter @ vue.esm.js:1000
(anonymous) @ vue-router.esm.js:2390
(anonymous) @ vue-router.esm.js:2389
updateRoute @ vue-router.esm.js:1924
(anonymous) @ vue-router.esm.js:1802
(anonymous) @ vue-router.esm.js:1911
step @ vue-router.esm.js:1649
step @ vue-router.esm.js:1656
step @ vue-router.esm.js:1656
runQueue @ vue-router.esm.js:1660
(anonymous) @ vue-router.esm.js:1906
step @ vue-router.esm.js:1649
(anonymous) @ vue-router.esm.js:1653
(anonymous) @ vue-router.esm.js:1891
(anonymous) @ vue-router.esm.js:1727
iterator @ vue-router.esm.js:1870
step @ vue-router.esm.js:1652
step @ vue-router.esm.js:1656
step @ vue-router.esm.js:1656
(anonymous) @ vue-router.esm.js:1653
(anonymous) @ vue-router.esm.js:1891
(anonymous) @ permission.js:40
iterator @ vue-router.esm.js:1870
step @ vue-router.esm.js:1652
step @ vue-router.esm.js:1656
step @ vue-router.esm.js:1656
runQueue @ vue-router.esm.js:1660
confirmTransition @ vue-router.esm.js:1899
transitionTo @ vue-router.esm.js:1801
push @ vue-router.esm.js:2173
push @ vue-router.esm.js:2416
handler @ vue-router.esm.js:404
invoker @ vue.esm.js:1814
vue.esm.js:479 [Vue warn]: Error in render function: "TypeError: Cannot read property 'a' of undefined"

found in

---> <ErrCode> at src\views\errlog\errcode.vue
       <Index> at src\views\errlog\index.vue
         <AppMain> at src\views\layout\AppMain.vue
           <Layout> at src\views\layout\Layout.vue
             <APP> at src\App.vue
               <Root>
warn @ vue.esm.js:479
handleError @ vue.esm.js:562
Vue._render @ vue.esm.js:4130
updateComponent @ vue.esm.js:2538
get @ vue.esm.js:2881
Watcher @ vue.esm.js:2870
mountComponent @ vue.esm.js:2542
Vue$3.$mount @ vue.esm.js:7863
Vue$3.$mount @ vue.esm.js:10066
init @ vue.esm.js:3501
createComponent @ vue.esm.js:5147
createElm @ vue.esm.js:5090
createChildren @ vue.esm.js:5218
createElm @ vue.esm.js:5123
patch @ vue.esm.js:5570
Vue._update @ vue.esm.js:2414
updateComponent @ vue.esm.js:2538
get @ vue.esm.js:2881
Watcher @ vue.esm.js:2870
mountComponent @ vue.esm.js:2542
Vue$3.$mount @ vue.esm.js:7863
Vue$3.$mount @ vue.esm.js:10066
init @ vue.esm.js:3501
createComponent @ vue.esm.js:5147
createElm @ vue.esm.js:5090
patch @ vue.esm.js:5606
Vue._update @ vue.esm.js:2424
updateComponent @ vue.esm.js:2538
get @ vue.esm.js:2881
run @ vue.esm.js:2958
flushSchedulerQueue @ vue.esm.js:2724
(anonymous) @ vue.esm.js:701
nextTickHandler @ vue.esm.js:648
Promise resolved (async)
timerFunc @ vue.esm.js:663
queueNextTick @ vue.esm.js:711
queueWatcher @ vue.esm.js:2811
update @ vue.esm.js:2948
Vue.$forceUpdate @ vue.esm.js:2445
(anonymous) @ vue.esm.js:7649
wrappedHook @ vue.esm.js:1863
invoker @ vue.esm.js:1810
(anonymous) @ vue.esm.js:7164
(anonymous) @ vue.esm.js:304
end @ vue.esm.js:6871
(anonymous) @ vue.esm.js:6882
setTimeout (async)
whenTransitionEnds @ vue.esm.js:6880
(anonymous) @ vue.esm.js:7195
requestAnimationFrame (async)
(anonymous) @ vue.esm.js:6838
requestAnimationFrame (async)
nextFrame @ vue.esm.js:6837
performLeave @ vue.esm.js:7188
leave @ vue.esm.js:7172
remove$$1 @ vue.esm.js:7263
removeAndInvokeRemoveHook @ vue.esm.js:5315
removeVnodes @ vue.esm.js:5289
patch @ vue.esm.js:5632
Vue._update @ vue.esm.js:2424
updateComponent @ vue.esm.js:2538
get @ vue.esm.js:2881
run @ vue.esm.js:2958
flushSchedulerQueue @ vue.esm.js:2724
(anonymous) @ vue.esm.js:701
nextTickHandler @ vue.esm.js:648
Promise resolved (async)
timerFunc @ vue.esm.js:663
queueNextTick @ vue.esm.js:711
queueWatcher @ vue.esm.js:2811
update @ vue.esm.js:2948
notify @ vue.esm.js:778
reactiveSetter @ vue.esm.js:1000
(anonymous) @ vue-router.esm.js:2390
(anonymous) @ vue-router.esm.js:2389
updateRoute @ vue-router.esm.js:1924
(anonymous) @ vue-router.esm.js:1802
(anonymous) @ vue-router.esm.js:1911
step @ vue-router.esm.js:1649
step @ vue-router.esm.js:1656
step @ vue-router.esm.js:1656
runQueue @ vue-router.esm.js:1660
(anonymous) @ vue-router.esm.js:1906
step @ vue-router.esm.js:1649
(anonymous) @ vue-router.esm.js:1653
(anonymous) @ vue-router.esm.js:1891
(anonymous) @ vue-router.esm.js:1727
iterator @ vue-router.esm.js:1870
step @ vue-router.esm.js:1652
step @ vue-router.esm.js:1656
step @ vue-router.esm.js:1656
(anonymous) @ vue-router.esm.js:1653
(anonymous) @ vue-router.esm.js:1891
(anonymous) @ permission.js:40
iterator @ vue-router.esm.js:1870
step @ vue-router.esm.js:1652
step @ vue-router.esm.js:1656
step @ vue-router.esm.js:1656
runQueue @ vue-router.esm.js:1660
confirmTransition @ vue-router.esm.js:1899
transitionTo @ vue-router.esm.js:1801
push @ vue-router.esm.js:2173
push @ vue-router.esm.js:2416
handler @ vue-router.esm.js:404
invoker @ vue.esm.js:1814
vue.esm.js:566 TypeError: Cannot read property 'a' of undefined
    at Proxy.render (errcode.vue?a732:2)
    at VueComponent.Vue._render (vue.esm.js:4128)
    at VueComponent.updateComponent (vue.esm.js:2538)
    at Watcher.get (vue.esm.js:2881)
    at new Watcher (vue.esm.js:2870)
    at mountComponent (vue.esm.js:2542)
    at VueComponent.Vue$3.$mount (vue.esm.js:7863)
    at VueComponent.Vue$3.$mount (vue.esm.js:10066)
    at init (vue.esm.js:3501)
    at createComponent (vue.esm.js:5147)

**Comment by PanJiaChen** [comment]
错误日志不故意写错点东西。。。哪来的错误日志。。。。
