### ISSUE TITLE
tagsView模式下引入vuex的createLogger导致页面卡死

### ISSUE THREAD

**Issue by qfwfqf** [PanJiaChen/vue-element-admin#2875]
同时开启tagsView和vuex的createLogger，会导致页面卡死

store=> index.js:
import createLogger from 'vuex/dist/logger'
const store = new Vuex.Store({
  modules,
  getters,
  plugins: [createLogger()]
})

**Comment by PanJiaChen** [comment]
createLogger 本身会影响性能

**Comment by PanJiaChen** [comment]
用看vuex的话建议用vue-devtool

**Comment by mayongze** [comment]
tagsview有啥逻辑会导致用了createLogger之后卡死

**Comment by wsyxl365** [comment]
确实会导致页面卡死 关闭tagsview就好了 有时间研究下吧
