### ISSUE TITLE
为什么我下载了项目登陆的时候 出现405错误

### ISSUE THREAD

**Issue by wch959** [PanJiaChen/vue-element-admin#2877]
下载项目配置好打开端口报405错误

**Comment by haokan123456** [comment]
同问，刚刚部署好，启动后登录，也是提示405错误

**Comment by wch959** [comment]
前期没有后端支持，直接把那句判断环境变量的直接删除就行了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"haokan123456"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月24日(星期二) 中午11:24
收件人:&nbsp;"PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com&gt;;
抄送:&nbsp;"六块腹肌的王富帅"<649815404@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 为什么我下载了项目登陆的时候 出现405错误 (#2877)




同问，刚刚部署好，启动后登录，也是提示405错误

**Comment by zky105043058** [comment]
也是报405

**Comment by HH-Ge** [comment]
> 前期没有后端支持，直接把那句判断环境变量的直接删除就行了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"haokan123456"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月24日(星期二) 中午11:24 收件人:&nbsp;"PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com&gt;; 抄送:&nbsp;"六块腹肌的王富帅"<649815404@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 为什么我下载了项目登陆的时候 出现405错误 (#2877) 同问，刚刚部署好，启动后登录，也是提示405错误 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

改哪个文件的判断？

**Comment by HH-Ge** [comment]
修改 main.js ，注释31行和33行，保留32行即可，可以参照一下其中的注释

**Comment by wch959** [comment]
已经搞定 谢谢了！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"HH-Ge"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月25日(星期三) 上午10:23
收件人:&nbsp;"PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com&gt;;
抄送:&nbsp;"六块腹肌的王富帅"<649815404@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 为什么我下载了项目登陆的时候 出现405错误 (#2877)




修改 main.js ，注释31行和33行，保留32行即可，可以参照一下其中的注释

**Comment by zhuzhh** [comment]
> 修改 main.js ，注释31行和33行，保留32行即可，可以参照一下其中的注释

不一定是31行和33行，我下载的代码是在27行左右
这个问题的起因是mock服务没起来引起的
![image](https://user-images.githubusercontent.com/41102272/71446244-191c9700-275c-11ea-9f4e-dc1991c3192c.png)
把 "production" 改成  “development”即可，或者把这个判断语句去掉
在 development 环境下，启用mock服务

**Comment by shoppingzh** [comment]
提问的人是否看了官方文档或已看懂了源码？如果把`if (process.env.NODE_ENV === 'production')`改为`development`，`mockXHR()`函数会将ajax的`XMLHttpRequest`重写，把`send`函数指向mockjs的模拟数据，所以根本不会将数据发送到服务器，当然看似问题就解决了，但是你仔细看看控制台，并没有发生网络请求就知道，问题压根就没有解决！

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/2929

重新拉取最新代码已修复。
