### ISSUE TITLE
路由懒加载的疑问

### ISSUE THREAD

**Issue by BibBin** [PanJiaChen/vue-element-admin#288]
module.exports = file => () => import('@/views/' + file + '.vue')
这样子就可以实现lazy load了吗？
我之前都是这样子的
component: resolve => require(['components/Hello.vue'], resolve)

**Comment by PanJiaChen** [comment]
Duplicate of #231

**Comment by zhangaofei** [comment]
我用发布环境用这个方式（webpack2.6.1  vue-loader13.0.4）module.exports = file => () => import('@/views/admin' + file + '.vue') 发现打不成包也不报错

**Comment by zzp0373** [comment]
import 是一个变量改如何解决

**Comment by zzp0373** [comment]
路由在配置的时候是变量，该如何配置异步路由，现在使用的是 Promise.resolve(require(`pageConsole/${path}.vue`).default) 这种方式，但是不是异步路由，vue-loader 是 15.9.6
