### ISSUE TITLE
ipad横屏的情况下无法调出键盘进行菜单搜索

### ISSUE THREAD

**Issue by MikuBlog** [PanJiaChen/vue-element-admin#2885]
## Bug report（问题描述）

ipad横屏的情况下无法调出键盘进行菜单搜索

#### Steps to reproduce（问题复现步骤）

1. ipad横向状态下打开chrome
2. 输入线上版本网址
3. 点击搜索菜单icon
4. 无法调出键盘进行输入搜索

我初步研究发现，element-ui的el-select组件在移动端搜索的状态下都是无法调出键盘的。该问题已经向element-ui官方提出。

#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/43233731/71463962-043f1280-27f3-11ea-9eb9-309b63dd2d0e.png)

#### Link to minimal reproduction（最小可在线还原demo）

可访问线上版本在ipad横屏的情况下尝试~

截图：
![image](https://user-images.githubusercontent.com/43233731/71463493-88909600-27f1-11ea-9dcd-2f90ae57a7e1.png)

#### Other relevant information（格外信息）
- Your OS: ipados/chrome
- vue-element-admin version: online/lastest

**Comment by MikuBlog** [comment]
该系统基于`vue-element-admin`。

**Comment by PanJiaChen** [comment]
https://github.com/ElemeFE/element/issues/17117
