### ISSUE TITLE
切换用户登录，vuex中name不发生改变

### ISSUE THREAD

**Issue by 329988300** [PanJiaChen/vue-element-admin#2886]
![image](https://user-images.githubusercontent.com/43880841/71499424-5a679080-289b-11ea-90ed-43fbf31a7e92.png)
切换另一个身份登录时候，vuex中的角色name不会发生改变，token发生了改变，sessionstorge也改变了，ctrl+f5后name才会发生改变
这是什么原因啊

**Comment by PanJiaChen** [comment]
vue_admin_template_token 是 https://panjiachen.github.io/vue-admin-template/#/dashboard 的 key

Admin-Token 才是本项目的。

**Comment by 329988300** [comment]
> vue_admin_template_token 是 https://panjiachen.github.io/vue-admin-template/#/dashboard 的 key
> 
> Admin-Token 才是本项目的。

不好意思发错了，那我这个问题是什么原因呢，还是无关紧要的小问题呢

**Comment by PanJiaChen** [comment]
没能重现你的问题。如有问题，你提供重现方式。

**Comment by 329988300** [comment]
> 没能重现你的问题。如有问题，你提供重现方式。

![image](https://user-images.githubusercontent.com/43880841/71551026-2796d700-2a18-11ea-9d17-defa1d94cbb5.png)
先使用admin账号登录，退出登录，在使用editor登录，出现上述情况

**Comment by PanJiaChen** [comment]
能录个gif或者视频么？
或者说关掉浏览器重新试试

**Comment by 329988300** [comment]
> 能录个gif或者视频么？
> 或者说关掉浏览器重新试试

在qq中私聊发您了，不太会使用github

**Comment by PanJiaChen** [comment]
已修复：https://github.com/PanJiaChen/vue-admin-template/commit/616957799001d5b161ea8bb9cd0846e6255863f9

**Comment by wanqianjin** [comment]
在退出登录的接口里面，调用location.reload()即可。
