### ISSUE TITLE
进度条结束的语句NProgress.done()分在几处写的原因？

### ISSUE THREAD

**Issue by roblues** [PanJiaChen/vue-element-admin#2888]
## Question（提问）
这不是问题，这是我的不解，想不明白，所以请教楼主。
无疑，这是个伟大的产品，佩服。

我的问题是
在src/permission.js中的NProgress.done()，分在了几个if语句中来写。
那么，能不能其他地方都不写，写在
if (hasToken) {｝else{}语句之后？

**Comment by mayunhai** [comment]
不行，得考虑 next() 的情况，关于 next() 作用详见 [官方文档](https://router.vuejs.org/zh/guide/advanced/navigation-guards.html#%E5%85%A8%E5%B1%80%E5%89%8D%E7%BD%AE%E5%AE%88%E5%8D%AB)
