### ISSUE TITLE
地址栏路径中/#直接可以任意加字符，而进入界面一样

### ISSUE THREAD

**Issue by roblues** [PanJiaChen/vue-element-admin#2889]
# Bug report（问题描述）
启动引用，在浏览器地址栏输入http://localhost:9527/，进入登录页面没有问题。

但是，如果我在地址栏中输入http://localhost:9527/guide(总之，这里加了个字符串)
回显之后，地址栏变成了
http://localhost:9527/asdf#/login?redirect=%2Fdashboard
也就是它把加入的字符串部分当成了应用名称。

此外，在登录之后，如果在#号前面部分，添加字符，界面没有变化。

**Comment by mayunhai** [comment]
src\router\index.js    mode: 'history', 这行注释打开即可 详细阅读下面官方文档
[vue-router mode](https://router.vuejs.org/zh/api/#mode)

**Comment by roblues** [comment]
感谢。
也就是说在hash模式下，用url创建路由时，是从第一个#开始的。
这样在hash模式下，所有的路由与#前面的内容都没有关系了。
我的直觉，在hash模式下，用url创建路由前，应该有一个钩子，这里可以用来限定。
回头看看源码去。
