### ISSUE TITLE
请问本项目是如何实现的ElementUI的按需加载？

### ISSUE THREAD

**Issue by CityBoyStar** [PanJiaChen/vue-element-admin#2890]
您好，请问vue-element-admin项目，是如何实现ElementUI的按需加载？
我查看了源码中的【main.js】文件，也是按照全局加载方式引入的
![image](https://user-images.githubusercontent.com/39644629/71563149-c9c0c880-2ac5-11ea-9b7e-e6e13c5cd6ff.png)

但是运行本项目，并未出现
#### 但是运行本项目，请求中并未出现好几M的js文件，
![image](https://user-images.githubusercontent.com/39644629/71563160-fd035780-2ac5-11ea-9b50-5ded4792ddf7.png)

#### 而我自己创建的项目，并引入ElementUI，访问时会请求一个7M多的js
![image](https://user-images.githubusercontent.com/39644629/71563177-2e7c2300-2ac6-11ea-9c76-361cd1204e0c.png)

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/cdn.html#%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F
