### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by hcking** [PanJiaChen/vue-element-admin#2894]
## Bug report（问题描述）
npm install 之后，npm run dev报错

#### Screenshot or Gif（截图或动态图）
# cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'bugs', 'vue-element-admin' ]
2 info using npm@3.10.10
3 info using node@v6.17.1
4 silly fetchPackageMetaData vue-element-admin
5 silly fetchNamedPackageData vue-element-admin
6 silly mapToRegistry name vue-element-admin
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry data Result {
9 silly mapToRegistry   raw: 'vue-element-admin',
9 silly mapToRegistry   scope: null,
9 silly mapToRegistry   escapedName: 'vue-element-admin',
9 silly mapToRegistry   name: 'vue-element-admin',
9 silly mapToRegistry   rawSpec: '',
9 silly mapToRegistry   spec: 'latest',
9 silly mapToRegistry   type: 'tag' }
10 silly mapToRegistry uri https://registry.npmjs.org/vue-element-admin
11 verbose request uri https://registry.npmjs.org/vue-element-admin
12 verbose request no auth needed
13 info attempt registry request try #1 at 上午9:31:31
14 verbose request id 51c8a34581836773
15 http request GET https://registry.npmjs.org/vue-element-admin
16 http 200 https://registry.npmjs.org/vue-element-admin
17 verbose headers { date: 'Tue, 31 Dec 2019 01:31:32 GMT',
17 verbose headers   'content-type': 'application/json',
17 verbose headers   'transfer-encoding': 'chunked',
17 verbose headers   connection: 'keep-alive',
17 verbose headers   'set-cookie': [ '__cfduid=da5eb55383d4320476b70c33bd9380e431577755892; expires=Thu, 30-Jan-20 01:31:32 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
17 verbose headers   'cf-ray': '54d87e952b3ae7f9-LAX',
17 verbose headers   'cache-control': 'public, max-age=300',
17 verbose headers   etag: 'W/"bf73f0ccad778f8a49ecb11d18f23c74"',
17 verbose headers   'last-modified': 'Sun, 20 Jan 2019 14:42:45 GMT',
17 verbose headers   vary: 'accept-encoding, accept',
17 verbose headers   'cf-cache-status': 'REVALIDATED',
17 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
17 verbose headers   server: 'cloudflare',
17 verbose headers   'content-encoding': 'gzip' }
18 silly get cb [ 200,
18 silly get   { date: 'Tue, 31 Dec 2019 01:31:32 GMT',
18 silly get     'content-type': 'application/json',
18 silly get     'transfer-encoding': 'chunked',
18 silly get     connection: 'keep-alive',
18 silly get     'set-cookie': [ '__cfduid=da5eb55383d4320476b70c33bd9380e431577755892; expires=Thu, 30-Jan-20 01:31:32 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
18 silly get     'cf-ray': '54d87e952b3ae7f9-LAX',
18 silly get     'cache-control': 'public, max-age=300',
18 silly get     etag: 'W/"bf73f0ccad778f8a49ecb11d18f23c74"',
18 silly get     'last-modified': 'Sun, 20 Jan 2019 14:42:45 GMT',
18 silly get     vary: 'accept-encoding, accept',
18 silly get     'cf-cache-status': 'REVALIDATED',
18 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
18 silly get     server: 'cloudflare',
18 silly get     'content-encoding': 'gzip' } ]
19 verbose get saving vue-element-admin to /root/.npm/registry.npmjs.org/vue-element-admin/.cache.json
20 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
21 silly bugs url https://github.com/PanJiaChen/vue-element-admin/issues
22 verbose stack Error: Command failed: xdg-open https://github.com/PanJiaChen/vue-element-admin/issues
22 verbose stack xdg-open: no method available for opening 'https://github.com/PanJiaChen/vue-element-admin/issues'
22 verbose stack
22 verbose stack     at ChildProcess.exithandler (child_process.js:199:12)
22 verbose stack     at emitTwo (events.js:106:13)
22 verbose stack     at ChildProcess.emit (events.js:191:7)
22 verbose stack     at maybeClose (internal/child_process.js:920:16)
22 verbose stack     at Socket.<anonymous> (internal/child_process.js:351:11)
22 verbose stack     at emitOne (events.js:96:13)
22 verbose stack     at Socket.emit (events.js:188:7)
22 verbose stack     at Pipe._handle.close [as _onclose] (net.js:509:12)
23 verbose cwd /data/vue-element-admin
24 error Linux 3.10.0-1062.4.3.el7.x86_64
25 error argv "/usr/bin/node" "/usr/bin/npm" "bugs" "vue-element-admin"
26 error node v6.17.1
27 error npm  v3.10.10
28 error code 3
29 error Command failed: xdg-open https://github.com/PanJiaChen/vue-element-admin/issues
29 error xdg-open: no method available for opening 'https://github.com/PanJiaChen/vue-element-admin/issues'
30 error If you need help, you may report this error at:
30 error     <https://github.com/npm/npm/issues>
31 verbose exit [ 1, true ]

#### Other relevant information（格外信息）
- Your OS: CentOS7
- Node.js version: v6.17.1
- vue-element-admin version: git clone 最新版本

**Comment by BOSSLMH** [comment]
虽然不知道什么原因 但是先npm install 在cnpm install就解决了

**Comment by hcking** [comment]
找到原因了，node 和vue版本不对，都安装最新版本就好了
