### ISSUE TITLE
关于elementUI 使用Image组件双击图片会给body添加overflow: hidden;

### ISSUE THREAD

**Issue by vanness30214** [PanJiaChen/vue-element-admin#2898]
在使用该image组件时候，双击图片会导致给body添加overflow：hidden属性导致右侧滚动条隐藏无法滚动，关于这个想象官网element UI也有此状况，请问如何有其他方案避免双击图片隐藏滚动条，
此操作会导致无法滚动页面，只能F5刷新解决了

**Comment by ixi** [comment]
这个问题好像还会导致 和 iviewer 组件冲突，滚动条丢失

**Comment by CCYYZZNN** [comment]
我今天也遇到这个问题了，官方好像没有解释

**Comment by CCYYZZNN** [comment]
这个是BUG，绑定previewSrcList属性就好了，接收一个数组，开启大图预览以后 这个就没问题了。

**Comment by vanness30214** [comment]
但绑定previewSrcList属性后会触发点击开启大图预览，但心目中预期是不需要使用此功能点击不打开预览图。我也向Element ui 提出ISSUES,解决方案只能不使用此组件，等官方解决此bug[https://github.com/ElemeFE/element/issues/18567](url)

**Comment by yuexueyu** [comment]
暂时可以这样解决一下：
```
body {
        overflow: auto !important;
    }
```

**Comment by lclancey** [comment]
我单击都会出这问题!
用的el-card, 上半边图片下半边文本, 监听el-card的点击, 点下半部分文本没问题, 点上半部分图片就overflow:hidden, 然后失去滚动效果了...
目前只能照着楼上的方法解决...

**Comment by PanJiaChen** [comment]
已升级至最新
https://github.com/PanJiaChen/vue-element-admin/commit/1c943509f9788297f0ddc188208f9501648c8e7f
