### ISSUE TITLE
比如这样的路径“http://xxx.com/introduction/index”无法找到js

### ISSUE THREAD

**Issue by YuxinChou** [PanJiaChen/vue-element-admin#29]
下面两种路径，一种可以，另一种会出现找不到文件错误
http://xxx.com/dashboard       正常访问
http://xxx.com/introduction/index     找不到js

我在build之后，nginx的配置如下：
    listen 80;
    server_name xxx.com;
    location / {
        root /home/ubuntu/vue-demo/dist;
        index index.html;
        try_files $uri $uri/ /index.html =404;
    }

是否还需要其他配置，谢谢🙏

**Comment by PanJiaChen** [comment]
配置上没看出什么问题
能截个图么？

**Comment by YuxinChou** [comment]
nginx配置如下：
![nginx配置](https://cloud.githubusercontent.com/assets/7675333/25741717/a977d04e-31be-11e7-9dd3-b1b57e13103a.png)
错误如下：
图1:
![b8551af4-3dfd-4acb-bbe3-0d0ce141bd63](https://cloud.githubusercontent.com/assets/7675333/25741796/0e085f2e-31bf-11e7-9c45-3cb7bd6097e9.png)
图2:
![1f40dfb6-9c72-4fc5-b22a-69f6fb615efc](https://cloud.githubusercontent.com/assets/7675333/25741758/d61f2af2-31be-11e7-8077-bffe35eea0da.png)

**Comment by PanJiaChen** [comment]
introduction/js 是什么 哪来的。。。

**Comment by YuxinChou** [comment]
原本的页面“简述”  http://localhost:9528/#/introduction/index
我只是把#去掉了，在router的mode这里，改成了history。
export default new Router({
  mode: 'history',

**Comment by YuxinChou** [comment]
js所有文件都在dist/js文件夹下面，但是URL如果是localhost:9528/introduction/index等localhost:9528/###/***格式，网页会去dist的###文件夹下找js，这就导致不对。我估计

**Comment by baselin** [comment]
不是说去掉#号history模式需要node配合吗？vue官方的配置也是这种错误，搞了一天nginx配置都不行，你们有谁配置成功了告诉我一下谢谢~~~~~

**Comment by YuxinChou** [comment]
@baselin 你好，找到问题了，不是nginx问题，上面的配置是对的。

当换成history模式，可能引用路径和hash # 是不一样的。
这里修改config文件夹下的**index.js**，原来：
```
assetsPublicPath: './',
staticPath:'./',
```
修改后：
```
assetsPublicPath: '/',
staticPath:'/',
```

主要问题出在这里，重新打包、部署，测试可行。问题关闭啦。

**Comment by baselin** [comment]
@YuxinChou 谢谢啦  ~~~~
