### ISSUE TITLE
使用socket.io-client过程中，npm run build:prod后连接不上服务器，npm run dev正常

### ISSUE THREAD

**Issue by dengpju** [PanJiaChen/vue-element-admin#2900]
## Question（提问）

使用socket.io-client过程中，npm run build:prod后连接不上服务端，响应400 BAD REQUEST，服务端与开发使用同一台，开发环境npm run dev正常，这个问题困扰我几天了，不知道其他大神有遇到过吗？求帮助，感谢万分！

#### Steps to reproduce（问题复现步骤）

1. 在组件中，引入import io from 'socket.io-client'
2. 创建连接 io.connect(location.protocol + '//' + document.domain + ':' + port+ namespace)
3.开发环境npm run dev正常
4.构建生产环境npm run build:prod，无法连接服务器（可以确保服务端是正常的，我独立使用页面测试过，与开发环境连接的相同的服务端，如果服务端有问题，开发环境下也应该连接不上）
5.开发环境，在连接服务端时，第二个post请求带上sid发送给服务端，并且request payload中会指向我的命名空间(8:40/test)，但npm run build:prod构建后的dist访问时，第二个post请求，却没有带上sid这个参数,request payload也没有指向我的命名空间，而是指向了(1:1)
6.因为我不是专业前端，很多原理上的都不是很清楚，百度了很多，都没能找到问题的原因，这个过程中也根据网上的一些资料，跟换了好几种，使用socket.io的方式，但最终都是相同的结果，我可以再次确认服务端没有问题，因为我单独写html静态页面测试了，是正常可以连接，收发数据的

#### Screenshot or Gif（截图或动态图）
开发环境截图
![图片](https://user-images.githubusercontent.com/33408765/71642794-20a7e700-2cec-11ea-997d-adbd7a0b9d13.png)
开发环境服务端推送的数据
![图片](https://user-images.githubusercontent.com/33408765/71643037-e9870500-2cee-11ea-927c-992b32bdce9f.png)
生产环境截图
![图片](https://user-images.githubusercontent.com/33408765/71642828-bcd1ee00-2cec-11ea-9746-5760a2271ae0.png)

#### Other relevant information（格外信息）
- Your OS: docker镜像  node:8.16-alpine
- Node.js version: v13.1.0
- vue-element-admin version:4.2.1

**Comment by PanJiaChen** [comment]
你线上环境溢出 mockjs 了么？ 在main.js里

**Comment by tx321-4** [comment]
这个问题我遇到过 是因为线上的192.168.8.99:5125 要换成 域名
