### ISSUE TITLE
http://localhost:9527/dev-api/user/login 405 (Method Not Allowed)

### ISSUE THREAD

**Issue by meizhuhanxiang** [PanJiaChen/vue-element-admin#2901]
#### Steps to reproduce（问题复现步骤）
重新clone最新的项目，重新npm install，重新运行也会出现上面的问题
是不是最近做了什么npm依赖或者项目的变动导致这个问题出现，之前是不存在这个问题的，突然就这样了

**Comment by xionglongxiang** [comment]
我也刚刚遇到这个问题。以前跑的代码没这个问题，2020-01-02 最新代码有问题了。

**Comment by jianhao2010303** [comment]
代理配置的路径无法匹配到，这个是我自己的:
 proxy: {
      // change xxx-api/login => mock/login
      // detail: https://cli.vuejs.org/config/#devserver-proxy
      [process.env.VUE_APP_BASE_API]: {
        target: `http://localhost/admin`,
        changeOrigin: true,
        pathRewrite: {
          ['^' + process.env.VUE_APP_BASE_API]: ''
        }
      }
    },

**Comment by yrhgame** [comment]
看样子真的是依赖库调整了，掉坑~

**Comment by hcking** [comment]
我也遇到了，还没找到解决办法。。

**Comment by chenwenbo236** [comment]
process.env.NODE_ENV  这个变量的问题 大多数是开发环境

**Comment by xcainiao** [comment]
+1

**Comment by levai** [comment]
+1

**Comment by mayunhai** [comment]
mock\user.js
src\api\user.js
修改 post为get 写死入参可以暂时登陆进去，

**Comment by luobin01** [comment]
npm安装包时遇到这个问题，但改用yarn不会

**Comment by levai** [comment]
3Q 按照其他伙伴的修改 在入口main.js 改如下设置

if (process.env.NODE_ENV === 'development') {
  mockXHR()
}

**Comment by mayunhai** [comment]
666

> 3Q 按照其他伙伴的修改 在入口main.js 改如下设置
> 
> if (process.env.NODE_ENV === 'development') {
> mockXHR()
> }

**Comment by chenwenbo236** [comment]
直接写cookie也进去了



---Original---

**Comment by fenyuang** [comment]
Hi,guys.The temporary methods to solve this problem is set cookie then sit down and waiting for the author fix this problem.
1. Project [vue-element-admin](https://panjiachen.github.io/vue-element-admin) set cookie 
```
Admin-Token:admin-token
```
2. Project [vue-element-template](https://panjiachen.github.io/vue-admin-template) set cookie 
```
vue_admin_template_token:admin-token
```

**Comment by lvtraveler** [comment]
除了该成development，有其他好的解决方法吗

**Comment by DusuWen** [comment]
> 3Q 按照其他伙伴的修改 在入口main.js 改如下设置
> 
> if (process.env.NODE_ENV === 'development') {
> mockXHR()
> }

这样改了之后，就不可以在network中看到相关请求了

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/2929

重新拉取最新代码已修复。
