### ISSUE TITLE
切换tab，列表页重新加载

### ISSUE THREAD

**Issue by jianhao2010303** [PanJiaChen/vue-element-admin#2904]
您好：
        我现在遇到一个问题，当我在列表页点击详情，新打开详情页时，点击列表页后，重新调用了create钩子，但是我并没有把缓存关闭，路由如下：

{
    path: '/conference',
    component: Layout,
    redirect: '/conference/list',
    name: 'Conference',
    meta: {
      title: '会议主题',
      icon: 'example'
    },
    alwaysShow: true,
    children: [
      {
        path: 'list',
        component: () => import('@/views/conference/list/index'),
        name: 'ConferenceList',
        meta: {
          title: '会议信息',
          icon: 'list'
        }
      },
      {
        path: 'party/:id',
        component: () => import('@/views/conference/party/index'),
        name: 'ConferenceParty',
        meta: {
          title: '与会者信息',
          noCache: true,
          activeMenu: '/conference/list'
        },
        hidden: true
      }

**Comment by mayunhai** [comment]
noCache: true                if set true, the page will no be cached(default is false)
