### ISSUE TITLE
语言问题

### ISSUE THREAD

**Issue by wshengcheng** [PanJiaChen/vue-element-admin#2906]
## Question（提问）
请问src目录下没有lang文件夹，目前依靠什么控制语言选择

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by mayunhai** [comment]
master分支没有国际化，请切换到 i18n 分支就能找到 lang 文件夹了

**Comment by wshengcheng** [comment]
万分感谢，已经找到了
