### ISSUE TITLE
左侧菜单能否根据用户的角色权限来实现动态显示呀？

### ISSUE THREAD

**Issue by carveybunt** [PanJiaChen/vue-element-admin#2914]
由于业务需要，每个用户可能拥有多个角色，每个角色下又拥有多个权限。
#### 如果按照vue-element-admin目前的左侧菜单显示，是根据角色来实现的。

                {
                  path: '/permission',
                  component: Layout,
                  redirect: '/permission/index', //重定向地址，在面包屑中点击会重定向去的地址
                  hidden: true, // 不在侧边栏线上
                  alwaysShow: true, //一直显示根路由
                  meta: { roles: ['admin','editor'] }, //你可以在根路由设置权限，这样它下面所以的子路由都继承了这个权限
                  children: [{
                    path: 'index',
                    component: ()=>import('permission/index'),
                    name: 'permission',
                    meta: {
                      title: 'permission',
                      icon: 'lock', //图标
                      role: ['admin','editor'], //或者你可以给每一个子路由设置自己的权限
                      noCache: true // 不会被 <keep-alive> 缓存
                    }
                  }]
                }

我项目的角色很多，后期对角色的修改会比对权限的修改频繁的多（比如，对角色的增删，以及角色的权限重新调整）。而且子菜单也是单独控制限制的。

 不知道能否实现通过权限来控制左侧菜单的显示，因为权限是根据业务功能来定义的，基本上不会有变更。

                {
                  path: '/permission',
                  component: Layout,
                  redirect: '/permission/index', //重定向地址，在面包屑中点击会重定向去的地址
                  hidden: true, // 不在侧边栏线上
                  alwaysShow: true, //一直显示根路由
                  meta: { permission: ['permission_manage','admin'] }, //你可以在根路由设置权限，这样它下面所以的子路由都继承了这个权限，‘permission_manage’、‘admin’二选一，此处的admin是权限不是角色。
                  children: [{
                    path: 'index',
                    component: ()=>import('permission/index'),
                    name: 'permission_add',
                    meta: {
                      title: '权限添加',
                      icon: 'lock', //图标
                      permission: ['permission_add','admin'], //或者你可以给每一个子路由设置自己的权限
                      noCache: true // 不会被 <keep-alive> 缓存
                    }
                  }]
                }

这样路由表一旦生成，就不需要后期的修改，无论角色怎么增删改，最终都由角色所拥有的权限来控制显示的左侧菜单内容。

**Comment by acgta5** [comment]
可以  为需要权限的路由加上一个标识，和上面meta里一样的原理，在获取用户信息的时候后台把这些权限信息返回来自己判断过滤一下 重新加载就可以了

**Comment by smwanyi** [comment]
我这里需求也是根据后端返回的菜单来控制菜单显示。后端返回数据，菜单的id是确定的，我是再给每个路由对象添加了个menuId，与接口的id一一对应。获取数据后递归组装一下，重新排序，addRoutes一下就行了。

**Comment by zhujinhu21** [comment]
@smwanyi 你是meta中添加了menuId属性吗，这个值如果后台修改了 怎么办

**Comment by smwanyi** [comment]
> @smwanyi 你是meta中添加了menuId属性吗，这个值如果后台修改了 怎么办
菜单id都改了那也只能改前端代码了，总要有一个写死的。

**Comment by zhujinhu21** [comment]
@smwanyi 动态添加的路由我想放在指定的某个菜单位置下请问怎么操作，addRoutes试了加到最后面了

**Comment by smwanyi** [comment]
你加我qq吧，我把我这里的方法给你看一下
1208868230

**Comment by zhujinhu21** [comment]
@carveybunt  已添加好友，麻烦同意下

**Comment by smwanyi** [comment]
我再详细说下我的思路吧。
我这个是公司自己的项目，缺点就是需要已知菜单或按钮的id，也就是先在后台管理新建菜单。
比如建好首页菜单，已经知道了它的后端id是123，再去前端代码的首页路由对象也写上123。
新建菜单需要前后端一起改，再上线。
一开始的路由只有登录页这种不需要权限的，登录后，后端返回账号能进的页面和按钮。
后端返回的菜单、按钮数据肯定是有id的，那么前端给每个路由对象加一个id，两个对象一“比较”，对上了，router.addRoutes添加就行了。
如下图，你的index.js
![1](https://user-images.githubusercontent.com/44425545/94565031-43772400-029b-11eb-8ed6-f5fcebc28690.png)
比如说后端返回了这样的数据
![微信截图_20200929213815](https://user-images.githubusercontent.com/44425545/94566005-75d55100-029c-11eb-8781-a4b0d91c81dc.png)
如何造的话，我写的很乱，首先把图1所有的对象，递归，转成一个以id为key值的对象。二级/三级子路由也升到外层提出来，如下图。
![222](https://user-images.githubusercontent.com/44425545/94567002-96ea7180-029d-11eb-9849-c95684fff365.png)
下一步就是上一步的逆向，把图2那样的数组，用上一步造出的对象，造一个新的“路由”，router.addRoutes添加就行了。当然也要递归，恢复正确的children层级，还要保持正确的顺序，使生成的菜单顺序和后端一样。
我改了PanJiaChen大佬的Sidebar代码，没有用他的逻辑，为了让我自己更顺手。
确实有点麻烦，但是简单粗暴，效果一步到位。
反正是递归，支持无限层子路由。
看你想玩多少花样，替换菜单名字，logo，控制显示隐藏......
```javascript 
// 菜单类型 menuType
// 将所有路由allRoute和接口返回的角色有的菜单对比，生成角色对应菜单
// allRoute就是图3的对象
function recursionFn(list) {
  const rs = []
  for (const i of list) {
    if (i.menuType === 'F') {
      // 这里是所有的按钮，这个buttonConfig最后被存到了vuex，按钮也是用id判断有没有，显示隐藏
      buttonConfig[i.menuId] = true
      continue
    }
    // 菜单
    const temp = allRoute[i.menuId]
    if (temp) {
      if (i.children && i.children.length) {
        const innerrs = recursionFn(i.children)
        if (innerrs) {
          if (temp.children && temp.children.length) {
            temp.children = [...temp.children, ...innerrs]
          } else {
            temp.children = innerrs
          }
        }
      }
      if (temp.meta && i.menuName) {
        // 用接口的菜单名称
        temp.meta.title = i.menuName
      }
      rs.push(temp)
    }
  }
  if (rs.length) {
    return rs
  }
}
```
![asaas3](https://user-images.githubusercontent.com/44425545/94570510-81774680-02a1-11eb-93c8-779f4da015e7.png)
自己想的笨办法，刚参加工作，大佬们随意看看吧
