### ISSUE TITLE
封装axios请求时，设置了‘axios.defaults.withCredentials = true’,但是get请求中有cookie，post请求没有

### ISSUE THREAD

**Issue by xinnicai** [PanJiaChen/vue-element-admin#2916]
## Question（提问）
封装axios请求时，设置了‘axios.defaults.withCredentials = true’,但是get请求中有cookie，post请求没有

#### Screenshot or Gif（截图或动态图）
get请求
![图片](https://user-images.githubusercontent.com/30997380/71946377-976d4480-3204-11ea-977b-cd8f3bf29fa3.png)

post请求
![图片](https://user-images.githubusercontent.com/30997380/71946342-760c5880-3204-11ea-9187-f7cfe38546f7.png)

**Comment by flg717** [comment]
我也有类似问题，后台过滤器中也设置了 response.setHeader("Access-Control-Allow-Origin", request.getHeader("Origin"));，可request中依旧没有cookie！！！postman测试是OK的， 你有解决吗？
