### ISSUE TITLE
npm run dev一直报如下错误

### ISSUE THREAD

**Issue by Vicjoy88** [PanJiaChen/vue-element-admin#2923]
npm ERR! code ELIFECYCLE
npm ERR! errno 9009
npm ERR! vue-admin-template@4.2.1 dev: `vue-cli-service serve`
npm ERR! Exit status 9009
npm ERR!
npm ERR! Failed at the vue-admin-template@4.2.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Vicjoy88** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Joe\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@6.13.4
3 info using node@v8.11.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-admin-template@4.2.1~predev: vue-admin-template@4.2.1
6 info lifecycle vue-admin-template@4.2.1~dev: vue-admin-template@4.2.1
7 verbose lifecycle vue-admin-template@4.2.1~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vue-admin-template@4.2.1~dev: PATH: C:\Users\Joe\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\vue-admin-template\node_modules\.bin;C:\Users\Joe\bin;D:\Program Files\Git\mingw64\bin;D:\Program Files\Git\usr\local\bin;D:\Program Files\Git\usr\bin;D:\Program Files\Git\usr\bin;D:\Program Files\Git\mingw64\bin;D:\Program Files\Git\usr\bin;C:\Users\Joe\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;%JAVA_HOME%\bi;%JAVA_HOME%\jre\bin";D:\Program Files\Git\cmd;C:\Program Files\MySQL\MySQL Utilities 1.6;D:\Program Files (x86)\Brackets\command;C:\WINDOWS\System32\OpenSSH;D:\Program Files\nodejs;D:\android-sdk-windows\tools;C:\Program Files\OpenSSL-Win64\bin;D:\Program Files\TortoiseSVN\bin;D:\Program Files (x86)\Yarn\bin;D:\Program Files\Redis;D:\Program Files\JetBrains\IntelliJ IDEA 2018.3.6\plugins\maven\lib\maven3\bin;C:\Users\Joe\AppData\Local\Programs\Python\Python38\Scripts;C:\Users\Joe\AppData\Local\Programs\Python\Python38;C:\Users\Joe\AppData\Local\Microsoft\WindowsApps;C:\Users\Joe\AppData\Roaming\npm;D:\flutter\bin;D:\android-sdk-windows\platform-tools;C:\Users\Joe\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Joe\AppData\Local\Yarn\bin;D:\Program Files\Git\usr\bin\vendor_perl;D:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle vue-admin-template@4.2.1~dev: CWD: E:\vue-admin-template
10 silly lifecycle vue-admin-template@4.2.1~dev: Args: [ '/d /s /c', 'vue-cli-service serve' ]
11 silly lifecycle vue-admin-template@4.2.1~dev: Returned: code: 9009  signal: null
12 info lifecycle vue-admin-template@4.2.1~dev: Failed to exec dev script
13 verbose stack Error: vue-admin-template@4.2.1 dev: `vue-cli-service serve`
13 verbose stack Exit status 9009
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Joe\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Joe\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid vue-admin-template@4.2.1
15 verbose cwd E:\vue-admin-template
16 verbose Windows_NT 10.0.17134
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Joe\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v8.11.2
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 9009
22 error vue-admin-template@4.2.1 dev: `vue-cli-service serve`
22 error Exit status 9009
23 error Failed at the vue-admin-template@4.2.1 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 9009, true ]

**Comment by PanJiaChen** [comment]
error errno 9009
自己搜一下相关问题。
自己环境的问题。
