### ISSUE TITLE
下载源码运行之后,一直报错Proxy error: Could not proxy request /user/login from localhost:9527 to http://127.0.0.1:9527/mock (ECONNREFUSED).

### ISSUE THREAD

**Issue by gaomengmengl** [PanJiaChen/vue-element-admin#2926]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/2929

重新拉取最新代码已修复。

**Comment by yijinc** [comment]
添加一个开发代理 还是报错
Proxy error: Could not proxy request /api/saas/login from localhost:9527 to http://devsaas.example.cn.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).


vue.config.js
`
proxy: {
      '/api': {
        target: 'http://devsaas.myexample.cn',
        ws: true,
        changeOrigin: true
      }
    }
`

**Comment by xiaochenchen86** [comment]
> 添加一个开发代理 还是报错
> Proxy error: Could not proxy request /api/saas/login from localhost:9527 to http://devsaas.example.cn.
> See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
> 
> vue.config.js
> `proxy: { '/api': { target: 'http://devsaas.myexample.cn', ws: true, changeOrigin: true } }`

我也遇到同样问题，求问

**Comment by xiaochenchen86** [comment]
Proxy error: Could not proxy request /api/v1/release/project/create from localhost:9527 to http://127.0.0.1:9002.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).

get 请求可以代理过去

post 就报这个

**Comment by yuyanghui** [comment]
大佬们的帮助下找到了这个问题：
vue.config.js注销这段代码before: require('./mock/mock-server.js')

**Comment by bjmajiancheng** [comment]
> Could not proxy request /api/v1/release/project/create from localhost:9527

我也遇到了这个问题，现在解决了吗？

**Comment by bjmajiancheng** [comment]
> Proxy error: Could not proxy request /api/v1/release/project/create from localhost:9527 to http://127.0.0.1:9002.
> See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
> 
> get 请求可以代理过去
> 
> post 就报这个

我也遇到了这个问题，现在解决了吗
