### ISSUE TITLE
大神，请问根据权限添加路由，在有权限的时候，一切正常，但是没有权限的普通用户账号登录，路由陷入死循环

### ISSUE THREAD

**Issue by Jonathan-Rao** [PanJiaChen/vue-element-admin#2931]
## Question（提问）
1.先初始化了公共路由，去除了404路由配置：
export const constantRouterMap = [
    {
    alwaysShow: true,
    hidden: true,
    path: '/a',
    name: 'a',
    component: () => import('@/views/a'),
    meta: { title: 'a', icon: '' }
  }
]
2.定义了有权限的路由数组
export const asyncRouterMap = [
    {
    alwaysShow: true,
    hidden: true,
    path: '/b',
    name: 'b',
    component: () => import('@/views/b'),
    meta: { title: 'b', icon: '' }
  },
{ path: '*', redirect: '/404', hidden: true }
]

有权限的用户登录，一切正常，但是普通用户登录，却死循环了，很奇怪

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/16660755/72124123-9839de00-339e-11ea-8cdb-47d2daa746ed.png)
![image](https://user-images.githubusercontent.com/16660755/72124180-c3243200-339e-11ea-88f2-ac4b45751748.png)

**Comment by Jonathan-Rao** [comment]
已解决

**Comment by fangwandong** [comment]
@Jonathan-Rao  你好，请问下怎么解决的？ 也遇到相同问题

**Comment by liaoyuhanCSDN** [comment]
同求，我也遇到
