### ISSUE TITLE
能不能在请求时间超时的时候给它一个提示 ‘网络超时’呢

### ISSUE THREAD

**Issue by jojoguang** [PanJiaChen/vue-element-admin#2936]

**Comment by mayunhai** [comment]
/src/utils/request.js  74 行 有响应拦截器啊 自己按照想要的稍微修改下即可

**Comment by jojoguang** [comment]
> /src/utils/request.js 74行有响应拦截器啊自己跟随想要的稍微修改下即可

我做了，但是问题又来了，我多个请求都超时了，它就出现多次出现 '网络超时' 的 提示，有没有办法说只能让它出现一次

**Comment by yunfeizhu** [comment]
> > /src/utils/request.js 74行有响应拦截器啊自己跟随想要的稍微修改下即可
> 
> 我做了，但是问题又来了，我多个请求都超时了，它就出现多次出现 '网络超时' 的 提示，有没有办法说只能让它出现一次

this,$message.closeAll();

**Comment by PanJiaChen** [comment]
楼上两位已经解答了。

**Comment by mubeishao** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"花裤衩"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 下午3:07
收件人:&nbsp;"PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 能不能在请求时间超时的时候给它一个提示 ‘网络超时’呢 (#2936)

您好:
&nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;项目npm install&nbsp;后会有报错&nbsp; 这个项目不能启动成功&nbsp; 可以帮忙解决下吗&nbsp; &nbsp;下面是报错内容 &nbsp; 谢谢

npm ERR! code 128

npm ERR! Command failed: git submodule update -q --init --recursive

npm ERR! fatal: 'submodule' appears to be a git command, but we were not

npm ERR! able to execute it. Maybe git-submodule is broken?

npm ERR!




npm ERR! A complete log of this run can be found in:

npm ERR!&nbsp; &nbsp; &nbsp;C:\Users\1\AppData\Roaming\npm-cache\_logs\2020-01-16T07_12_55_975Z-debug.log
