### ISSUE TITLE
本地开发怎么去掉http://10.99.40.101:9528/sockjs-node/info?t=1578982763539

### ISSUE THREAD

**Issue by gulang12** [PanJiaChen/vue-element-admin#2938]
## Question（提问）
我本地开发的时候总是显示 http://10.99.40.101:9528/sockjs-node/info?t=1578982763539 这个请求，怎么把它去掉。我在代码里看了，没有什么地方有配置这个请求的IP呢？

**Comment by PanJiaChen** [comment]
webpack 热更新。不清楚你为啥要去掉。正常情况下，你不需要关注它。
