### ISSUE TITLE
开启keep-alive后能否点击左侧菜单时能否重新渲染页面

### ISSUE THREAD

**Issue by zogeli100** [PanJiaChen/vue-element-admin#294]
在AppMain里添加了keep-alive缓存操作记录后，关闭对应的tag，然后在左侧菜单点击之前操作过的模块，出来的页面是之前缓存过的。
想问一下博主有没有什么办法或者方案能实现tag里切换的时候保持操作记录，关闭后在左侧重新打开功能的时候是重新渲染过的页面。

**Comment by PanJiaChen** [comment]
现有的条件下要实现你想要的效果比较难，现在 `keep-alive` 的机制主要是基于每一个router 的name来实现的。
如果你想实现左侧路由点击进入的页面没有缓存，这还是能实现的，当然随之如果你之前点开过这个页面的tag也会被覆盖。

**Comment by zogeli100** [comment]
@PanJiaChen 只要左侧进入就没有缓存也是可行的，也给已开启页面提供了刷新的途径。是配置时间戳？

**Comment by PanJiaChen** [comment]
缓存和刷新两者是有冲突的。。。(可能) 没有具体是测过
刷新方法：https://segmentfault.com/a/1190000009275424#articleHeader16

**Comment by zogeli100** [comment]
@PanJiaChen   key不是在开启keep-alive后去掉了吗。。

**Comment by PanJiaChen** [comment]
> 想问一下博主有没有什么办法或者方案能实现tag里切换的时候保持操作记录，关闭后在左侧重新打开功能的时候是重新渲染过的页面
现版本应该已经满足你的需求了。

**Comment by Youcongcong** [comment]
@PanJiaChen 请问是哪个分支
