### ISSUE TITLE
请问，部署的网站，登录成功后，不进入首页，疑似被拦截，如何解决？

### ISSUE THREAD

**Issue by yangyuditest** [PanJiaChen/vue-element-admin#2940]
![image](https://user-images.githubusercontent.com/59871187/72340322-fd753280-3702-11ea-88d3-63199989233c.png)
请问，部署的网站，登录成功后，不进入首页，疑似被拦截，如何解决？

**Comment by yangyuditest** [comment]
求助，求助，大牛

**Comment by PanJiaChen** [comment]
拦截问题，你上网有很多解决方案的。
