### ISSUE TITLE
有没有人懂这个项目的详细构建教程，布局，菜单的映射。太多api有点看不懂也没有注释

### ISSUE THREAD

**Issue by VeryRise** [PanJiaChen/vue-element-admin#2941]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by liufei96** [comment]
我现在在整合公司的前端，原来用的是thmleaf模板，现在全部使用vue，有问题可以一起交流下

**Comment by 152016726** [comment]
作者写的很详细，您要抠他代码下来仔细看，不懂就去看api很快就会掌握的
