### ISSUE TITLE
使用vue-element-admin-master开发的前端，疑似被劫持

### ISSUE THREAD

**Issue by yangyuditest** [PanJiaChen/vue-element-admin#2942]
使用vue-element-admin-master开发的前端，疑似被劫持
![image](https://user-images.githubusercontent.com/59871187/72394475-61cedb00-3771-11ea-94d5-079be9e7c2b4.png)

有大牛看看是不是框架问题

**Comment by yangyuditest** [comment]
使用vue-element-admin-master开发的前端，疑似被劫持
![image](https://user-images.githubusercontent.com/59871187/72394549-9c387800-3771-11ea-8a21-c7091a4b28d2.png)

**Comment by PanJiaChen** [comment]
这个本项目没关系。

**Comment by yangyuditest** [comment]
能否指导一下，是编码的问题？或者后期安装组件的问题？
--------------
yangyudi@smc.com.cn
