### ISSUE TITLE
为什么任何路由前都有个 Dashboard 路由前缀？

### ISSUE THREAD

**Issue by Matyman** [PanJiaChen/vue-element-admin#2947]
可以不以去掉这个前缀路由，看起来很烦恼。

**Comment by Matyman** [comment]
![image](https://user-images.githubusercontent.com/42082811/72580082-e8bcb880-3915-11ea-9827-9e6a30d31243.png)

**Comment by sunpu007** [comment]
![image](https://user-images.githubusercontent.com/20461171/72580489-38e84a80-3917-11ea-92c7-cc758532ff30.png)
这行代码隐藏即可

**Comment by Matyman** [comment]
谢谢，已看到这块代码了。
