### ISSUE TITLE
select选择器无法显示选中的内容

### ISSUE THREAD

**Issue by jieblog** [PanJiaChen/vue-element-admin#295]
vue-element-admin 版本 2.2.1

和这个问题一样：https://segmentfault.com/q/1010000009295579，尝试升级版本 无效。

**Comment by PanJiaChen** [comment]
请参照 element-ui 提供在线代码的方法如 https://jsfiddle.net/6fa0L0ff/

提供可复现效果的代码

**Comment by PanJiaChen** [comment]
太久没回复 新关闭了
