### ISSUE TITLE
路由懒加载的疑问

### ISSUE THREAD

**Issue by XdyGoGo** [PanJiaChen/vue-element-admin#2958]
这不是一个bug，只是一个疑问。
在大神的项目里，我没有看到控制台显示的懒加载对应的文件
![image](https://user-images.githubusercontent.com/28619491/72953531-6aa65900-3dd0-11ea-908f-333b049065c9.png)
可是我自己的是有的，这是做了啥配置？？？
![image](https://user-images.githubusercontent.com/28619491/72953545-75f98480-3dd0-11ea-9762-9252555c2959.png)

**Comment by XdyGoGo** [comment]
I u

**Comment by BenXi630** [comment]
为什么

**Comment by rmlzy** [comment]
图一是 production 环境, 你是 development 环境吧

https://github.com/PanJiaChen/vue-element-admin/blob/1bc2e5c1980b2e5131164849f66dd4f03216806d/babel.config.js#L11
