### ISSUE TITLE
Wish List

### ISSUE THREAD

**Issue by robinxym** [PanJiaChen/vue-element-admin#296]
1. 增加CRUD范例
2. 增加简单后台示范代码和数据库机构
3. 动态修改role，并影响路由（是否考虑，菜单对应路由，菜单分属于不同role，role分属于不同用户或用户组）

现有Issue：
1. 升级element-ui（升级改动不大）
2. 升级webpack（还未深入研究）

**Comment by PanJiaChen** [comment]
1. crud 其实 table 和 form 的例子已经满足需求了，所以你不知道想要的范例指的是那种？
2. 暂时本项目定位是纯前端项目，日后可能会配套一个后端项目吧。
3. 暂时已公司项目的经验来说(我司权限大概有三十多种),用本项目目前的权限划分 ['editor','develop'] 多权限组合的方式，没有遇到什么问题。所以能详情说明一下你的痛点么？

issue:
这周本项目会有一个大版本更新，目测有七八十个 commit。新版本所有都使用了最新版本号，如`webpack:3.8.1` `element-ui:2.0.5`

**Comment by robinxym** [comment]
谢谢及时的回复。
花了1、2天看完你的文章和代码，先点100个赞。
1. 比我自己搭的架构成熟，如果有CRUD范例，我就可以在代码级别比较，找出自己的不足。
2. 后台也是自己搭的，restify的升级又让人懵逼了，包括cors，如果你有restify后台范例，那就太棒了。
3. 你目前的权限是定义在路由里的，如果用户要新增一个role和权限，岂不是要改代码？

期待webpack element-ui的升级

**Comment by PanJiaChen** [comment]
权限问题目前是的，因为前端方面总归会要写路由，所以顺带把权限写一下权限，也没有什么工作量。而且理论上权限的变动也不是一个很高频的操作。
当然如果你一个页面的权限经常换，或则你觉得权限手写太麻烦，也是可以将权限存在后端的。后期可能会修改成这样的模式。详细的进程可关注 #167

**Comment by tlianglstyle** [comment]
这几天我把vue和elementUI升级到最高版本时出现icon错乱的情况，暂时还没找到原因，希望更新后能解决 @PanJiaChen

**Comment by PanJiaChen** [comment]
@tlianglstyle
 新版本已修复，如果你用的是本项目的话 ，出现原因是换肤页 会引入需要换肤的css 但这是element-ui 老版本构建出来的 所以会冲突。
解决方案：你暂时注释掉代码就可以。

**Comment by jianliulin** [comment]
我的路由是动态的，就是用户可以新建新的路由，比如采购单，用户可以添加多个类别的采购单，没种类别对应一个路由(url)，前端是无法预设是什么路由，请教像我这种需求改怎么设置权限呢？

**Comment by no3forfuk** [comment]
是啊, 我司老大要求前端路由可以右键复制或者删除, 这可难倒我们了, 一点思路都没有.

**Comment by PanJiaChen** [comment]
太久之前的issue了。如果4.0版本还是不满足需求的话，请再重新开一个新的issue。
