### ISSUE TITLE
options.compilerOptions.preserveWhitespace = true 的用意是什么？

### ISSUE THREAD

**Issue by microkof** [PanJiaChen/vue-element-admin#2961]
## Question（提问）
vue.config.js 里有这么一句：
```
options.compilerOptions.preserveWhitespace = true
```
查了vue手册，[https://github.com/vuejs/vue-docs-zh-cn/blob/master/vue-template-compiler/README.md#选项](https://github.com/vuejs/vue-docs-zh-cn/blob/master/vue-template-compiler/README.md#选项)，默认就是 true。
那么我们专门在 vue.config.js 里重复写一遍，是什么用意？

**Comment by PanJiaChen** [comment]
主要有两个原因：
1：之前默认值并不是 true
2：后来默认值改了，但我这里并不想删，有需求的可以自己改，这个值的改动对页面布局是有不小影响的。
