### ISSUE TITLE
Guide icon is not showing when header fixed

### ISSUE THREAD

**Issue by dihak** [PanJiaChen/vue-element-admin#2965]
## Bug report（问题描述）
Guide icon is not showing when header fixed

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/10445482/73601938-cb861c00-459c-11ea-9d05-8975b08692dd.png)

**Comment by dihak** [comment]
Solved, set animate to false will fix the issue

`    this.driver = new Driver({
      animate: false
    })
`

**Comment by PanJiaChen** [comment]
Welcome to pull request.
