### ISSUE TITLE
Safari 左侧菜单图标无法显示

### ISSUE THREAD

**Issue by kanouken** [PanJiaChen/vue-element-admin#2978]
#### Steps to reproduce（问题复现步骤）

1. 访问 https://panjiachen.github.io/vue-element-admin/#/icon/index

#### Screenshot or Gif（截图或动态图）
![QQ20200212-151235](https://user-images.githubusercontent.com/4925886/74311446-7622e980-4daa-11ea-9440-3d8313ea09c6.png)

#### Other relevant information（格外信息）
- Your OS:   Safari  11.1.2 (13605.3.8)
- Node.js version: 
- vue-element-admin version:

**Comment by kanouken** [comment]
@PanJiaChen  大佬看看呗 。

**Comment by kanouken** [comment]
解决了 ，关了吧。

**Comment by Luffy-D-Monkey** [comment]
> 解决了 ，关了吧。

我的Safari仍然无法显示导航栏title前的svg图标，请问解决了？

- macOS 10.12.4, Safari Version 10.1
