### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by freedeaths** [PanJiaChen/vue-element-admin#2987]
#### Steps to reproduce（问题复现步骤）

我是一个前端初学者，纯靠猜和console.log在学习，过程中发现一个问题，LOGIN以后无法获取TOKEN，因为我的后端是flask，不是NODE，我的解决方式如下
@/utils/request.js中响应拦截器const res = response.data; return res
@/store/modules/user.js中login和其它action中，then(resonse => const { data } = response为空，直接response即可
因为我不确定是否为前端本身的BUG，所以我就先不提交PR了，还没玩过NODE

#### Other relevant information（格外信息）
- Your OS: Ubuntu 18.04
- Node.js version: 无
- vue-element-admin version: 4.0.0（master分支我看了也是一样的）

**Comment by mayunhai** [comment]
能够正常获取啊，还有你这个说实话没看懂....

**Comment by mayunhai** [comment]
如果是初学接口不通，大部分应该是因为跨域，至少得有报错信息不然没法定位

**Comment by freedeaths** [comment]
不是跨域问题，因为我把@/store/modules/user.js中login和其它action中，then(resonse => const { data } = response这一行注释掉，下面data.token改成response.token就可以正常读到了。
在拦截器里返回的res已经是response.data了

**Comment by freedeaths** [comment]
抱歉，我大概知道原因了，是我没看懂{}，因为我的reponse.data里没有data的字段了，应该是这个原因
