### ISSUE TITLE
package.json "browserslist"参数名少了个‘s’，如果报错的话

### ISSUE THREAD

**Issue by duhu110** [PanJiaChen/vue-element-admin#299]
![image](https://user-images.githubusercontent.com/11226322/33315379-80f48392-d46b-11e7-9b89-6121cb47bece.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/516897b97af5cf0983ba99e07e8497355f7ba388#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
在一个多月以前已修复该问题
