### ISSUE TITLE
npm run dev 依赖报错！

### ISSUE THREAD

**Issue by lvanboy** [PanJiaChen/vue-element-admin#2997]
## Bug report（问题描述）
项目缺少依赖。

#### Steps to reproduce（问题复现步骤）

1. git clone 发生错误 使用下载压缩的包的形式下载
2. 进入项目目录，npm install 下载卡住不动了，换用cnpm install
3. npm run dev

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/25259733/75105608-721b8500-5650-11ea-820c-462d715a947b.png)

#### Other relevant information（格外信息）
- Your OS:window 10 家庭版
- Node.js version: 12.14.0
- vue-element-admin version:最新版本

**Comment by shengbid** [comment]
我使用cnpm i 之后npm run dev也报错,少了一个依赖 cnpm install core-js@2 -S安装之后再运行就可以了,不知道你是不是这个问题

**Comment by mio4** [comment]
> 我使用cnpm i 之后npm run dev也报错,少了一个依赖 cnpm install core-js@2 -S安装之后再运行就可以了,不知道你是不是这个问题

老哥牛逼，问题解决了
