### ISSUE TITLE
请支持表格按栏目排序

### ISSUE THREAD

**Issue by zh-h** [PanJiaChen/vue-element-admin#30]
http://panjiachen.github.io/vue-element-admin/#/example/table

这里提供的表格还没有支持表格排序，望作者快速实现。

**Comment by PanJiaChen** [comment]
我觉得后端排序才是更好的选择

**Comment by longzhaobi** [comment]
这个即使要实现也是饿了么的事吧！！！

**Comment by PanJiaChen** [comment]
饿了么支持啊。。。

**Comment by zh-h** [comment]
@PanJiaChen 我指的就是后端排序,就列表本来就是有支持排序的选择是吧?

**Comment by PanJiaChen** [comment]
已加
