### ISSUE TITLE
希望侧边栏可以直接使用element的icon

### ISSUE THREAD

**Issue by jayjun0805** [PanJiaChen/vue-element-admin#3001]
## Feature request（新功能建议）

使用svg-icon还需要准备对应的svg文件，麻烦不说，图标还比较少，可以考虑直接使用element的icons。

不过感觉element的icons也不丰富，能扩展集成iconfont图标也可以

**Comment by VivenZZ** [comment]
SVG文件很好搞的，去阿里图标库，一大把

**Comment by PanJiaChen** [comment]
我看了下，element的icon放在侧边栏样式不太好处理，它是icon-font，大小和svg有些差异，只能做到视觉上大致的一样。

**Comment by jayjun0805** [comment]
明白了。

**Comment by jayjun0805** [comment]
> SVG文件很好搞的，去阿里图标库，一大把

谢谢

**Comment by jianhao2010303** [comment]
@PanJiaChen 大佬，您自己项目的图标，和我自己从阿里图标库下来的图标大小不一致。
有没有什么步骤能告诉下怎么才能和你处理的一样
我的图标比你的小

**Comment by PanJiaChen** [comment]
@jianhao2010303 正常的图标库大小是没问题的，但很多不规范的svg会有点问题，我都是sketch自己修改的。

**Comment by jianhao2010303** [comment]
@PanJiaChen ，比较晕的是：

1、我们大多使用win10，使用不了sketch
2、有没有能在windows 修改图标的工具或方法，不吝赐教。

**Comment by VivenZZ** [comment]
可以搜一下云端AI

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/3048

**Comment by shushuquan** [comment]
我是用的是ts版的，左侧栏引入.svg遇到问题，大部分的图标不能显示，偶尔的图标只显示一个左上角。请大佬支招。谢谢，

**Comment by CS-liujf** [comment]
> @PanJiaChen ，比较晕的是：
> 
> 1、我们大多使用win10，使用不了sketch
> 2、有没有能在windows 修改图标的工具或方法，不吝赐教。

我也是遇到了这个问题，用阿里巴巴矢量图图标会显得很小
