### ISSUE TITLE
eslint 动态组件使用is属性应该传入什么属性

### ISSUE THREAD

**Issue by lee-garhou** [PanJiaChen/vue-element-admin#3004]
在views文件夹下的Link组件 里面使用的动态组件
在使用eslint的时候提示要使用属性，根据Vue文档，要传入不同的组件，我在父组件中传入了与路由相匹配的组件（onlyOneChild.component），在子组件中to的属性我设置为Object，结果报错了。Invalid prop: type check failed for prop "to". Expected String with value "undefined", got Undefined 
应该要怎样在eslint正确使用动态组件？

**Comment by lee-garhou** [comment]
> 在views文件夹下的Link组件 里面使用的动态组件
> 在使用eslint的时候提示要使用属性，根据Vue文档，要传入不同的组件，我在父组件中传入了与路由相匹配的组件（onlyOneChild.component），在子组件中to的属性我设置为Object，结果报错了。Invalid prop: type check failed for prop "to". Expected String with value "undefined", got Undefined
> 应该要怎样在eslint正确使用动态组件？

**Comment by lee-garhou** [comment]
> 在views文件夹下的Link组件 里面使用的动态组件
> 在使用eslint的时候提示要使用属性，根据Vue文档，要传入不同的组件，我在父组件中传入了与路由相匹配的组件（onlyOneChild.component），在子组件中to的属性我设置为Object，结果报错了。Invalid prop: type check failed for prop "to". Expected String with value "undefined", got Undefined
> 应该要怎样在eslint正确使用动态组件？

**Comment by PanJiaChen** [comment]
参照 https://github.com/PanJiaChen/vue-element-admin/pull/1700
