### ISSUE TITLE
当标签导航超出页面时，标签被隐藏

### ISSUE THREAD

**Issue by zhixinpeng** [PanJiaChen/vue-element-admin#301]
![image](https://user-images.githubusercontent.com/24643457/33362460-65cdec64-d517-11e7-9695-bbe18d3f5a63.png)
当标签导航超出页面时，标签被隐藏，希望提供标签栏滚动，标签超出时，标签整体自动左移，保持标签导航持续可见。

**Comment by PanJiaChen** [comment]
恩，最新会优化这个问题

**Comment by butterflyjzf** [comment]
切换tags时，路由请求参数query、params丢失

**Comment by PanJiaChen** [comment]
@butterflyjzf 的确会有问题，下个版本我优化一下

**Comment by butterflyjzf** [comment]
@PanJiaChen 大侠，参数query、params丢失这个bug是不是忘记了~

**Comment by PanJiaChen** [comment]
我来看一下

**Comment by PanJiaChen** [comment]
@butterflyjzf 你能详细说明一下使用场景么，其实暂时解决方案 params 和 query 都可以手动拼接path之中来解决

**Comment by butterflyjzf** [comment]
@PanJiaChen 主要是用在列表页打开详情页，路由里又不想配置:id之类的参数，所有就用query传参，然后切换tag的时候?后面的参数就丢了，或者路由里配置:id，然后用params传参 ，是可以解决这个问题，因为看代码是把路由的path存起来的，但是还是希望能解决这个问题吧，用store把路由的name和params、query存起来，应该可行吧

**Comment by PanJiaChen** [comment]
因为涉及keep-alive 还有侧边栏的问题，不是很好改。我开了一个issue  https://github.com/PanJiaChen/vue-element-admin/issues/350
近期考虑一下怎么优化吧。

**Comment by AndsteLyc** [comment]
@butterflyjzf 您的这个问题解决了吗？我目前也是有这样的问题。。。
![image](http://data.andste.cc/developers/github/images/bug.gif)
