### ISSUE TITLE
safari浏览器svg图标不显示

### ISSUE THREAD

**Issue by posistyle** [PanJiaChen/vue-element-admin#3023]
safari浏览器左侧导航栏icon不显示是什么问题呢？求助大神

<img width="401" alt="WX20200302-172922@2x" src="https://user-images.githubusercontent.com/26272895/75663331-93f9b500-5cab-11ea-871b-c201eaf05fed.png">

**Comment by posistyle** [comment]
<img width="401" alt="WX20200302-172922@2x" src="https://user-images.githubusercontent.com/26272895/75663235-73315f80-5cab-11ea-9aaa-9e0fb27644f0.png">

**Comment by Luffy-D-Monkey** [comment]
Me too

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/3085
