### ISSUE TITLE
收徒弟吗？我在学习你写的vue-admin

### ISSUE THREAD

**Issue by lihaoyiming** [PanJiaChen/vue-element-admin#3026]
在努力学习
我微信13803154712

**Comment by PanJiaChen** [comment]
不收。

**Comment by lihaoyiming** [comment]
好嘞。


可以交个朋友吗？ 我是想学习， 今年37岁。。


一直做后端开发，用thinkphp。&nbsp;

**Comment by PanJiaChen** [comment]
实话和你讲，你也知道头条的工作强度的，真没啥空闲时间。

**Comment by lihaoyiming** [comment]
理解。 给我回信息，我已经很高兴了。


我是一个小县城的程序员， 寻求提高自己，以及发展。


换句话说，就是想多赚点钱，多学点东西。


有可以用到我的， 可以带带我的， 麻烦有时间的时候。 叫我。随叫随到。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"花裤衩"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月4日(星期三) 晚上6:51
收件人:&nbsp;"PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com&gt;;
抄送:&nbsp;"唐山昊鸣网络科技有限公司"<521185236@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 收徒弟吗？我在学习你写的vue-admin (#3026)




实话和你讲，你也知道头条的工作强度的，真没啥空闲时间。
