### ISSUE TITLE
asyncRoutes加载的路由，无法显示在侧边栏上

### ISSUE THREAD

**Issue by gsdukbh** [PanJiaChen/vue-element-admin#3035]
## Bug report（问题描述）
asyncRoutes加载的路由，无法显示在侧边栏上
#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/43371824/75980129-da097f80-5f1c-11ea-86a4-cd9e47d6f113.png)

#### Link to minimal reproduction（最小可在线还原demo）
export const asyncRoutes = [
    {
        path: '/home',
        name: 'sccc',
        component: Layout,
        meta: {
            title: '管理员',
            icon: 'dashboard',
            roles: ['ROLE_ADMIN'],
        },
        children: [
            {
                path: '/user',
                name: 'scc',
                component: Home,
                meta: {
                    title: 's',
                }
            }
        ]
    },
    {
        path: '/121',
        name: '121',
        component: Layout,
        // hidden:true,
        meta: {
            title: '登录ssss',
            roles: ['ROLE_ADMIN'],

        }
    },}

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:最新

**Comment by gsdukbh** [comment]
已经解决

**Comment by Steventxy** [comment]
请问是哪里的问题呢，我也碰到了

**Comment by guoshuaiping** [comment]
求指点，哪里的问题？我也遇到了，好容易过了next({ ...to, replace: true })死循环的坑，现在有遇到这个问题了，fk
