### ISSUE TITLE
<img src='@/assets/...'/>可以加载图片 ，但是同样路径用<el-image/>却不行，为什么？

### ISSUE THREAD

**Issue by gujunwuxichina** [PanJiaChen/vue-element-admin#3037]

**Comment by Luis-liu** [comment]
![image](https://user-images.githubusercontent.com/23350984/76599228-806a0c00-653f-11ea-84c3-07999a790154.png)

**Comment by Luis-liu** [comment]
直接src="@/assets/logo.png" 引用没用，需要换成require引用 :src="require('@/assets/logo.png')"，不知道算不算bug
![image](https://user-images.githubusercontent.com/23350984/76599327-bc9d6c80-653f-11ea-961f-4edc5f2d2af1.png)
