### ISSUE TITLE
我是小白 左侧边栏没看懂怎么生成的

### ISSUE THREAD

**Issue by Yanhongliang100** [PanJiaChen/vue-element-admin#304]
求教 谢谢

**Comment by Lxjazni7** [comment]
看文档去呗

**Comment by PanJiaChen** [comment]
@Yanhongliang100  建议看文档
https://panjiachen.github.io/vue-element-admin-site/#/router-and-nav?id=%e4%be%a7%e8%be%b9%e6%a0%8f

或者源码 https://github.com/PanJiaChen/vue-element-admin/tree/master/src/views/layout/components/Sidebar
