### ISSUE TITLE
菜单中支持使用 el-icon 作为图标

### ISSUE THREAD

**Issue by Cat7373** [PanJiaChen/vue-element-admin#3047]
## Feature request（新功能建议）
如题，目前似乎仅支持 svg，而 svg 数量比较少，很多时候 el-icon 里有合适的，但其实并不能用

> 我已经试着在自己的项目里提供了支持，稍后我会抽出来提交一个 PR

**Comment by Jacqueline0905** [comment]
怎么使用el-icon 我用svg-icon 显示不出来

**Comment by Cat7373** [comment]
> 怎么使用el-icon 我用svg-icon 显示不出来

针对 #3048 这个 PR，你需要在菜单中使用 elicon: 'iconName' 来使用 el-icon

**Comment by HelloLogan** [comment]
感谢楼主，这个功能帮了我大忙
