### ISSUE TITLE
为什么router要区分_import_development.js和_import_production.js

### ISSUE THREAD

**Issue by PetersonLian** [PanJiaChen/vue-element-admin#305]
为什么router的import，要根据环境变量的不同，切换到不同的js。
_import_development.js和_import_production.js，为什么一个用关键字require，一个用关键字import？
@PanJiaChen

**Comment by PetersonLian** [comment]
1,关于为什么区分的这个问题，看到注释里头有说明，所以，自己来回答。
答:为了‘懒加载’，develop的时候，不使用懒加载
2,那么，关于我的问题二，为什么一个用require，一个用import，希望指点下

**Comment by PanJiaChen** [comment]
建议查阅文档 https://router.vuejs.org/zh-cn/advanced/lazy-loading.html

关于require，最早应该见于nodejs开发，属于CommonJS规范的一部分

关于import，是ES2015里的新模块化规范

https://www.zhihu.com/question/56820346

**Comment by PetersonLian** [comment]
问题二，我的主要意思是：为什么不统一用import或者require，而要一个require，一个import？
是代码历史遗留问题吗？

**Comment by mkanako** [comment]
@PetersonLian 看代码的时候，我也有这个疑问

**Comment by love596310898** [comment]
1、commonJS 和 ECMA 模块化本身都不支持异步加载模块 
2、import（）这种语法不属于模块化规范的一部分，是webpack提供的异步加载功能
3、由于webpack本身是在node中运行，构建过程中需要执行以上两个文件，所以你写 import  from 这种语法  node也不支持
