### ISSUE TITLE
使用el-select不能回显数据

### ISSUE THREAD

**Issue by flymecode** [PanJiaChen/vue-element-admin#3057]
目的是想点击编辑按钮可以将该行数据进行回显后进行编辑，但是显示的数据出现了下面的异常。
![image](https://user-images.githubusercontent.com/39447768/76852378-23938c00-6886-11ea-8732-d84c01512f15.png)
这是定义的数据
const questionTypeOptions = [
    { key: '0', display_name: '选择题' },
    { key: '1', display_name: '题空题' },
    { key: '2', display_name: '判断题' },
    { key: '3', display_name: '问答题' }
  ]，
temp: {
          id: undefined,
          difficulty: undefined,
          title: '',
          questionType: ''
        },
![image](https://user-images.githubusercontent.com/39447768/76852439-4b82ef80-6886-11ea-971b-1154c45b38db.png)

**Comment by wwwyq** [comment]
不太明白你表达的意思，下面都是猜的
你应该是想通过js来切换选项，而你执行的是`temp.questionType = 0`，正确的做法是`temp.questionType = '0'`
因为你定义的key是字符串，而不是数字

**Comment by flymecode** [comment]
谢谢楼上的回答，是类型错误的问题。
