### ISSUE TITLE
项目报错 “pleaseLetJsLoaded”

### ISSUE THREAD

**Issue by ilxiaoli** [PanJiaChen/vue-element-admin#3059]
## Bug report（问题描述）
打开 https://panjiachen.github.io/vue-element-admin/#/components/split-pane
每点击一个页面都报错
VM1139:1 Uncaught SyntaxError: Identifier 'pleaseLetJsLoaded' has already been declared
    at <anonymous>:1:1

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/26002161/76938320-5d6d9c80-6931-11ea-80b3-f0540327e390.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by Adonis0123** [comment]
这个是因为你下载了web前端助手的原因，跟项目没有关系，删掉这个插件就好了

**Comment by ilxiaoli** [comment]
已解决
