### ISSUE TITLE
注销后，不刷新页面，重新登录会出现空白页

### ISSUE THREAD

**Issue by su0805** [PanJiaChen/vue-element-admin#3067]
![image](https://user-images.githubusercontent.com/55624404/77174240-b6892c00-6afb-11ea-8ee2-e8211d1ae8da.png)
注销后，不刷新页面，重新登录会出现空白页，重新刷新才渲染视图

**Comment by lynweiaini** [comment]
解决了吗，我这边也遇到了

**Comment by yangtongbing** [comment]
我碰到是因为退出时没有执行SET_ROLES, 其实看代码permission.js一路console也能找到问题在哪儿,测试正常流程,跟退出重新登录流程,看哪里没执行,没执行的原因是什么,很好解决.

**Comment by gq630960023** [comment]
解决了吗

**Comment by PanJiaChen** [comment]
登出之后，再次进入需要重新 `addRoutes`
