### ISSUE TITLE
为什么这个框架没有栅格系统

### ISSUE THREAD

**Issue by yejianan** [PanJiaChen/vue-element-admin#307]

**Comment by PanJiaChen** [comment]
具体指哪里？

**Comment by yejianan** [comment]
比如首页，这些在下屏幕是乱的，不会根据屏幕去自动换行

**Comment by PanJiaChen** [comment]
谢谢反馈，之前没有太多考虑适配问题，之后优化一下吧

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/8f9de5c64102a2a77f383c6aa4abac10b8fec986

dashboard 已添加栅格系统
