### ISSUE TITLE
tinymce的字数统计问题

### ISSUE THREAD

**Issue by DuduStyle** [PanJiaChen/vue-element-admin#3070]
## Question（提问）
https://panjiachen.github.io/vue-element-admin/#/components/tinymce
实例中编辑器右下角统计的37个字是怎么统计的，中文，英文，阿拉伯数字是怎么统计的呢

#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/31200868/77245807-67a6d800-6c5c-11ea-8dbf-3c0e3d391692.png)

**Comment by DuduStyle** [comment]
目前我这边是重新按照日常编写习惯重新统计了下，隐藏了编辑器自带的统计

**Comment by PanJiaChen** [comment]
https://www.tiny.cloud/docs/plugins/wordcount/

**Comment by fengxin8144** [comment]
有没有字符统计扩展？

**Comment by XyyF** [comment]
官方文档：在统计栏 字词数 这一栏中，每一个中文被认为是一个字，统计+1；每一个单词被认为是一个词，不管其由几个字母组成，统计+1；数字及符号：不统计（有个别例外，如货币符号）。

这里是字词数，并不是字符数。
