### ISSUE TITLE
开发环境应该是eval-source-map

### ISSUE THREAD

**Issue by xiyoufang** [PanJiaChen/vue-element-admin#3077]
https://github.com/PanJiaChen/vue-element-admin/blob/9e0435ac85da58b74692594be7770c0920cc707d/vue.config.js#L86

https://webpack.js.org/configuration/devtool/#development 
eval-source-map   保留了完整的调试信息。
cheap-source-map 只保留了行信息，并不是很适合开发环境。

**Comment by shenxiang11** [comment]
没错！！！
52k的项目了，难道是想鼓励 console 调试大法？

**Comment by PanJiaChen** [comment]
我思考了很久，也没想起来自己为啥要这么写

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/3097
