### ISSUE TITLE
complexTable.vue里的create和update方法里的时间都是正常值1000倍，datepicker也是默认空白的

### ISSUE THREAD

**Issue by qmwsaa** [PanJiaChen/vue-element-admin#308]
complexTable.vue里的create和update方法里的时间都是正常值1000倍，
datepicker也是默认空白的，点击要选择的话得从1970开始点点点......到2017

我改了一下代码，可以正常处理了，代码在下面
 currenttime() {      //新增
      this.temp.timestamp = +new Date()  /新增
    },  /新增
resetTemp() {
      this.temp = {
……
        timestatmp: 0,
……
      }
      this.currenttime() //新增
    },
create() 和 update方法的时间戳都修改
      this.temp.timestamp = parseInt((+this.temp.timestamp / 1000))

**Comment by qmwsaa** [comment]
然后建议把create()方法完整写一下，提交数据，再注释掉，这样很多新人就知道怎么做了

**Comment by PanJiaChen** [comment]
> 然后建议把create()方法完整写一下，提交数据，再注释掉

不是很理解这里想表达什么

**Comment by qmwsaa** [comment]
方便像我这样的新人，要不然不知道怎么提交数据

    create() {
      this.temp.addtime = parseInt((+this.temp.addtime / 1000))
      // this.list.unshift(this.temp)

      return new Promise((resolve, reject) => {
        createUser(this.temp).then(response => {
          resolve()
          this.dialogFormVisible = false
          this.$notify({
            title: '成功',
            message: '新增数据成功',
            type: 'success',
            duration: 2000
          })
        }).catch(error => {
          reject(error)
        })
      })
    },

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/38192b828d7d88f9a765bd187a3dec3448df6179
已优化
