### ISSUE TITLE
文档在线代码链接失效

### ISSUE THREAD

**Issue by Volcano-Yang** [PanJiaChen/vue-element-admin#3082]
#### Screenshot or Gif（截图或动态图）
![图片](https://user-images.githubusercontent.com/43328103/77710246-80bada80-7008-11ea-91b7-c27a9518d0ed.png)

**Comment by PanJiaChen** [comment]
感谢提醒，已修复。

https://github.com/PanJiaChen/vue-element-admin-site/commit/3e19d7a2ff0064b85096c5e88afb3cba8fc56f6c
