### ISSUE TITLE
克隆代码受限 git clone https://github.com/PanJiaChen/vue-element-admin.git（permission denied）

### ISSUE THREAD

**Issue by Kaelalv** [PanJiaChen/vue-element-admin#3088]
## Question（提问）
![image](https://user-images.githubusercontent.com/25974410/78094292-c875a380-7406-11ea-8aec-b2271d7776ff.png)

#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/25974410/78094301-cc092a80-7406-11ea-868e-93a946f36f47.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
你自己文件目录权限的问题。

https://stackoverflow.com/questions/16376035/fatal-could-not-create-work-tree-dir-kivy

https://blog.csdn.net/qq_20480611/article/details/48138807
