### ISSUE TITLE
路由白名单的问题

### ISSUE THREAD

**Issue by bfqymmt** [PanJiaChen/vue-element-admin#3089]
在permission.js中添加了一个白名单路由，但仍然会跳转到login去`http://localhost:9528/test#/login?redirect=%2Fdashboard`。是哪里设置不当吗？

`const whiteList = ['/login', '/test']`

```
 {
    path: '/test',
    component: () => import('@/views/test'),
    hidden: true
  },
```

**Comment by yuqiaobinbin** [comment]
请问解决了吗
