### ISSUE TITLE
1.x版本升级后好多不兼容

### ISSUE THREAD

**Issue by mysteryHJJ** [PanJiaChen/vue-element-admin#309]

**Comment by PanJiaChen** [comment]
你指vue的不兼容 还是 element-ui 的不兼容 还是本项目？

**Comment by mysteryHJJ** [comment]
element-ui 升级为2.x的版本，之前的这个项目是1.x的，有什么解决方法吗

**Comment by PanJiaChen** [comment]
看element-ui2.0 的release 而且 你用了不合规的控制台会有提示
