### ISSUE TITLE
How to use svg icon defined in @src/icons/svg in el-dropdown-item?

### ISSUE THREAD

**Issue by smoothdvd** [PanJiaChen/vue-element-admin#3090]

**Comment by Faizanq** [comment]
Late, but maybe help someone.

* Import the Component in which page you want to show SVG icon

import Item from '@/layout/components/Sidebar/Item';

* Then pass the props argument for the icon name

<item :icon="dashboard" />

**Comment by PanJiaChen** [comment]
` <svg-icon icon-class="xxx" />`
