### ISSUE TITLE
Drop down box default switching language does not work(下拉框默认值切换语言不起效)

### ISSUE THREAD

**Issue by buddy-lin** [PanJiaChen/vue-element-admin#3098]
Drop down box default switching language does not work(下拉框默认值切换语言不起效)
![lang](https://user-images.githubusercontent.com/52120803/78803612-cce72100-79f1-11ea-854b-022dedbf589d.png)

**Comment by PanJiaChen** [comment]
不懂你想问什么，请提供一个现实demo
