### ISSUE TITLE
路由改为history模式

### ISSUE THREAD

**Issue by guwenchang** [PanJiaChen/vue-element-admin#310]
路由改为history模式后，生产环境打包，只有第一次点击跳转成功之后都会报错

**Comment by guwenchang** [comment]
![image](https://user-images.githubusercontent.com/14830450/33423580-3c0a5c86-d5f4-11e7-996a-7994edaa2a32.png)

**Comment by PanJiaChen** [comment]
需要更详细信息

**Comment by guwenchang** [comment]
![image](https://user-images.githubusercontent.com/14830450/33424829-ee3a33ce-d5f7-11e7-9aa7-147e3d2e83a2.png)

**Comment by guwenchang** [comment]
![image](https://user-images.githubusercontent.com/14830450/33425042-8f9288ca-d5f8-11e7-800e-b94690633dfa.png)

**Comment by PanJiaChen** [comment]
什么浏览器？

**Comment by guwenchang** [comment]
chrome

**Comment by guwenchang** [comment]
其他浏览器也不行，要不你试试你的行不，切换成history之后打包部署，然后就有问题了，我nginx也配置了支持history

**Comment by PanJiaChen** [comment]
目前你提供的信息难以定位到问题。我没有遇到过类似问题

**Comment by guwenchang** [comment]
![image](https://user-images.githubusercontent.com/14830450/33425631-4289b4ca-d5fa-11e7-9172-8e7747937332.png)

**Comment by guwenchang** [comment]
这个是不是写颠倒了

**Comment by PanJiaChen** [comment]
@guwenchang 额 我的锅 写反了 我去改一下

**Comment by zengcul** [comment]
我也遇到同样的问题   history模式  nginx做了`try_files $uri $uri/ /index.html;` 然后出现unexpected token 请问楼主怎么解决的

**Comment by cubemmc** [comment]
请问楼主这个问题怎么解决的？我也遇到了这个问题
