### ISSUE TITLE
动态添加的路由怎么指定位置

### ISSUE THREAD

**Issue by zhujinhu21** [PanJiaChen/vue-element-admin#3103]
## Question（提问）
根据权限动态添加的路由怎么指定位置，不是放在最下面

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by SuperZiLu** [comment]
大佬怎么解决的？我也遇到这个问题 用了router.addRoutes(accessRoutes)这个方法之后  添加进去的路由显示在最后面

**Comment by zhujinhu21** [comment]
没有解决，我是吧所有的菜单都加到权限中

**Comment by SuperZiLu** [comment]
哈哈哈 我也是 把侧边栏显示出来的菜单都加到这个asyncRouter数组里去让他一起筛选 这样顺序还是按数组里面先后去显示的 也不知道这样干是不是合理。
