### ISSUE TITLE
request如何请求后台的二进制验证码图片，并在element中显示

### ISSUE THREAD

**Issue by hahadaxia** [PanJiaChen/vue-element-admin#3107]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by dingangang** [comment]
axios.responseType 支持 blob arraybuffer 可以用这些接

可以往这方面考虑一下

**Comment by PanJiaChen** [comment]
楼上正解。
搜一下 img blob to base64 的方法就可以了。
