### ISSUE TITLE
MarkDown 预览框太小

### ISSUE THREAD

**Issue by homlex** [PanJiaChen/vue-element-admin#3108]
## 如图，Markdown预览框出问题

![image](https://user-images.githubusercontent.com/48396880/79051603-9d3f4f80-7c63-11ea-8677-956b7777940d.png)

我检查了这个预览版的文档结构，发现两者不太一样

![image](https://user-images.githubusercontent.com/48396880/79051661-f313f780-7c63-11ea-93cf-9f40db6a7d29.png)
这个是[在线预览版](https://panjiachen.github.io/vue-element-admin/#/components/markdown)的文档树结构截图，编辑、分割线、预览三个部分是分开的

---

![image](https://user-images.githubusercontent.com/48396880/79051694-379f9300-7c64-11ea-8b96-da94945fd4ce.png)
这个是我clone下来后运行后的文档树结构，预览框成为了spliter的子元素了，spliter成了编辑框的子元素。

只改了setting.js，然后这是setting.js改变的部分
![image](https://user-images.githubusercontent.com/48396880/79051843-05dafc00-7c65-11ea-92bd-630af4736554.png)

**Comment by wujingquan** [comment]
我也遇到了这个问题，原先好好。

**Comment by wujingquan** [comment]
自己升2.0搞定。

**Comment by jukear** [comment]
> 自己升2.0搞定。

什么2.0？

**Comment by jukear** [comment]
@wujingquan 什么2.0？

**Comment by wujingquan** [comment]
tui editor

**Comment by jukear** [comment]
@wujingquan 官网最新才1.4

**Comment by wujingquan** [comment]
@jukear ？？？https://github.com/nhn/tui.editor/releases

**Comment by homlex** [comment]
多谢，那我把这个issue关了哦

**Comment by jukear** [comment]
@wujingquan 请问npm 怎么安装releases2.0版本

**Comment by jukear** [comment]
官方更新了npm版本，多谢各位

**Comment by jukear** [comment]
@wujingquan 你指的是@toast-ui/editor吧，是有npm2.0版本的，但是项目中引入的是tui-editor，最高只有npm1.4.10，
![360截图20200510230937523](https://user-images.githubusercontent.com/33892225/81502892-5a7ca000-9313-11ea-984e-c50c77b28099.jpg)

**Comment by jukear** [comment]
将tui-editor-Editor.js中的第19616行从
`var containerTmpl = ['<div class="tui-editor">', '<div class="te-md-container">', '<div class="te-editor" />', '<div class="te-md-splitter" />', '<div class="te-preview" />', '</div>', '<div class="te-ww-container">', '<div class="te-editor" />', '</div>', '</div>'].join('');`
更改为
`var containerTmpl = ['<div class="tui-editor">', '<div class="te-md-container">', '<div class="te-editor">','</div>', '<div class="te-md-splitter">','</div>', '<div class="te-preview">','</div>', '</div>', '<div class="te-ww-container">', '<div class="te-editor">','</div>', '</div>', '</div>'].join('');`
解决

**Comment by wujingquan** [comment]
> @wujingquan 你指的是@toast-ui/editor吧，是有npm2.0版本的，但是项目中引入的是tui-editor，最高只有npm1.4.10，
> ![360截图20200510230937523](https://user-images.githubusercontent.com/33892225/81502892-5a7ca000-9313-11ea-984e-c50c77b28099.jpg)

scoped-package; tui-editor 2的包名已经改为@toast-ui/editor

**Comment by xiaoyaojiushao** [comment]
> c

厉害了，成功解决
