### ISSUE TITLE
store.state.tagsView.cachedViews没有2级，3级的name导致不缓存

### ISSUE THREAD

**Issue by pursuelu** [PanJiaChen/vue-element-admin#3109]
#### Steps to reproduce（问题复现步骤）
问题再次确定了，我的只能缓存1级，同一个2级目录下兄弟姐妹切换都行，从别的1级或者2级回来就不行了，官网demo可以2级之间随意切换

#### Other relevant information（格外信息）
- Your OS:Windows10
- Node.js version:v10.16.0
- vue-element-admin version:4.2.1

**Comment by pursuelu** [comment]
改动态路由改坏了，也没找到哪里把路由name塞到cachedViews的地方。
官网demo与我的区别就是，官网1级name2级name3级name都有，我的只有最后一级name

**Comment by pursuelu** [comment]
问题再次确定了，我的只能缓存1级，同一个2级目录下兄弟姐妹切换都行，从别的1级或者2级回来就不行了，官网demo可以2级之间随意切换

**Comment by dingangang** [comment]
找到了一个方案，可以参考一下。
https://github.com/PanJiaChen/vue-element-admin/commit/9ad96525af3a26c2f4e8d4e9016f801c44df1f80

**Comment by pursuelu** [comment]
> 找到了一个方案，可以参考一下。
> [9ad9652](https://github.com/PanJiaChen/vue-element-admin/commit/9ad96525af3a26c2f4e8d4e9016f801c44df1f80)

不是，现在我的2级出现了问题,看我的回复

**Comment by pursuelu** [comment]
已解决，动态路由的逻辑中不要用deepClone
