### ISSUE TITLE
没有找到依赖吗？svg-baker-runtime/browser-symbol 

### ISSUE THREAD

**Issue by yuana1** [PanJiaChen/vue-element-admin#311]
> node build/dev-server.js

> Starting dev server...

 ERROR  Failed to compile with 34 errors                                                                        18:29:09

This dependency was not found:

* svg-baker-runtime/browser-symbol in ./src/icons/svg/message.svg, ./src/icons/svg/404.svg and 32 others

To install it, you can run: npm install --save svg-baker-runtime/browser-symbol
> Listening at http://localhost:9527

**Comment by yuana1** [comment]
node 8.9.0

**Comment by PanJiaChen** [comment]
`svg-baker-runtime` 是 `svg-sprite-loader` 其依赖的一个包，很有可能是你npm install 没有完全成功。
不翻墙网速不行的情况下 建议这样安装
```js
npm install --registry=https://registry.npm.taobao.org

```

**Comment by yuana1** [comment]
刚才就是用的 `npm install --registry=https://registry.npm.taobao.org` 这个命令，奇怪了，是网速慢的原因吗？

**Comment by yuana1** [comment]
我用这个命令安装svg-baker-runtime/browser-symbol
 `npm install --save svg-baker-runtime/browser-symbol`
提示这个库不存在


 Error while executing:
npm ERR! D:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/svg-baker-runtime/browser-symbol.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

**Comment by PanJiaChen** [comment]
安装这个 `svg-baker-runtime`

**Comment by yuana1** [comment]
在家里边安装成功了。，公司的网速可能是比较慢，没有下载全！
谢谢。
