### ISSUE TITLE
npm install 报错，请问还需要python吗？？？？？

### ISSUE THREAD

**Issue by wangyin2018** [PanJiaChen/vue-element-admin#3113]
> core-js@3.6.5 postinstall F:\vuepro\vue-element-admin\node_modules\tui-chart\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> node-sass@4.13.1 postinstall F:\vuepro\vue-element-admin\node_modules\node-sass
> node scripts/build.js

Building: D:\nodejs\node.exe F:\vuepro\vue-element-admin\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'D:\\nodejs\\node.exe',
gyp verb cli   'F:\\vuepro\\vue-element-admin\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.16.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\vuepro\vue-element-admin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\vuepro\vue-element-admin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\vuepro\vue-element-admin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\vuepro\vue-element-admin\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\vuepro\vue-element-admin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\vuepro\vue-element-admin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\vuepro\vue-element-admin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\vuepro\vue-element-admin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\vuepro\vue-element-admin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\vuepro\vue-element-admin\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\vuepro\vue-element-admin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\vuepro\vue-element-admin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (F:\\vuepro\\vue-element-admin\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (F:\\vuepro\\vue-element-admin\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (F:\\vuepro\\vue-element-admin\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at F:\\vuepro\\vue-element-admin\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at F:\\vuepro\\vue-element-admin\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at F:\\vuepro\\vue-element-admin\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (F:\vuepro\vue-element-admin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\vuepro\vue-element-admin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\vuepro\vue-element-admin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\vuepro\vue-element-admin\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\vuepro\vue-element-admin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\vuepro\vue-element-admin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (F:\vuepro\vue-element-admin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\vuepro\vue-element-admin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\vuepro\vue-element-admin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\vuepro\vue-element-admin\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\vuepro\vue-element-admin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\vuepro\vue-element-admin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21) {
gyp verb `which` failed   stack: 'Error: not found: python\n' +
gyp verb `which` failed     '    at getNotFoundError (F:\\vuepro\\vue-element-admin\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (F:\\vuepro\\vue-element-admin\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (F:\\vuepro\\vue-element-admin\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at F:\\vuepro\\vue-element-admin\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at F:\\vuepro\\vue-element-admin\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at F:\\vuepro\\vue-element-admin\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (F:\vuepro\vue-element-admin\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (F:\vuepro\vue-element-admin\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at callback (F:\vuepro\vue-element-admin\node_modules\graceful-fs\polyfills.js:295:20)
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "D:\\nodejs\\node.exe" "F:\\vuepro\\vue-element-admin\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd F:\vuepro\vue-element-admin\node_modules\node-sass
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2020-04-14T08_09_48_253Z-debug.log

**Comment by PanJiaChen** [comment]
需要。
https://github.com/PanJiaChen/vue-element-admin/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
