### ISSUE TITLE
请问，配置路由，在左侧菜单没有选中状态，如图

### ISSUE THREAD

**Issue by eizo2200** [PanJiaChen/vue-element-admin#3119]
![image](https://user-images.githubusercontent.com/29911043/79440595-c6b3fe80-8008-11ea-8310-50d10af3cdc5.png)
![image](https://user-images.githubusercontent.com/29911043/79440657-daf7fb80-8008-11ea-9983-dd2154da3f59.png)
我点击新建单课，希望左侧菜单的单课管理是选中状态，如何配置路由

**Comment by dingangang** [comment]
Sidebar\index.vue 中有如下
`activeMenu() {
      const route = this.$route
      const { meta, path } = route
      // if set path, the sidebar will highlight the path you set
      if (meta.activeMenu) {
        return meta.activeMenu
      }
      return path
    },`

所以，你只需要在新建单课的路由中meta里指定activeMenu为单课管理的完整路由即可

**Comment by PanJiaChen** [comment]
楼上正解，设置 activeMenu 就可以了。

相关文档：https://panjiachen.gitee.io/vue-element-admin-site/zh/guide/essentials/router-and-nav.html#%E9%85%8D%E7%BD%AE%E9%A1%B9
