### ISSUE TITLE
master怎么没有中文？崇洋媚外吗？

### ISSUE THREAD

**Issue by guoyanhao** [PanJiaChen/vue-element-admin#3123]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by zwtgit** [comment]
> ## 问题（提问）
> #### 复制步骤（问题复现步骤）
> #### 屏幕截图或Gif（截图或动态图）
> #### 链接到最小复制（最小可在线还原demo）
> #### 其他相关信息（格外信息）
> * 您的操作系统：
> * Node.js版本：
> * vue-element-admin版本：

我相信PanJiaChen真要是拿你这个问题较真，他就输了😊😊😊，你真是杠

**Comment by PanJiaChen** [comment]
@guoyanhao 你咋不用中文编程？崇洋媚外么。。。
