### ISSUE TITLE
如果我需要两个控制台页面，比如说卖家和买家那样子，是不是我需要新增layout以及对应的router

### ISSUE THREAD

**Issue by sjrlyy** [PanJiaChen/vue-element-admin#3126]
比如说买家和卖家的页面通过/XXX进行展示，但是我要怎么登录之后判断是买家或者卖家然后跳转到对应的layout

**Comment by dingangang** [comment]
不是很清楚是什么意思。   登录界面接口返回应该要有用户role的标识吧，然后router.push到不通路径不就可以了？

**Comment by sjrlyy** [comment]
我现在改为了根据登录用户类型，左侧菜单栏展示不同的路由表，但是刷新浏览器之后，路由就不见了，有什么好的办法吗

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/layout/index.vue

在这里判断用户角色，动态渲染不同的layout。

类似这样
![image](https://user-images.githubusercontent.com/8121621/81051805-fd3cb500-8ef4-11ea-86e0-fdd59ded13a1.png)
