### ISSUE TITLE
npm run dev 运行项目有个报错

### ISSUE THREAD

**Issue by libaolei168** [PanJiaChen/vue-element-admin#3127]
http://localhost:9527/#/  http://localhost:9528/#/    vue-admin-template也报同样的错误

vue-router.esm.js:1921 Error: Cannot find module '@/views/login/index'
    at webpackEmptyContext (permission.js:137)
    at index.js:51
abort @ vue-router.esm.js:1921

**Comment by lyxisblog** [comment]
> http://localhost:9527/#/ http://localhost:9528/#/vue-admin模板也报同样的错误
> 
> vue-router.esm.js：1921错误：找不到模块@/view/login/index‘
> 在webPackemptyContext上(允许.js：137)
> at index.js：51
> ABORT@vue-router.esm.js：1921

请问楼主解决了吗

**Comment by libaolei168** [comment]
> > [http：// localhost：9527 /＃/ ](http://localhost:9527/#/) [http：// localhost：9528 /＃/ vue-admin模板也报同样的错误](http://localhost:9528/#/vue-admin%E6%A8%A1%E6%9D%BF%E4%B9%9F%E6%8A%A5%E5%90%8C%E6%A0%B7%E7%9A%84%E9%94%99%E8%AF%AF)
> > vue-router.esm.js：1921错误：找不到模块@ / view / login / index' 
> > 在webPackemptyContext上（允许.js：137）
> > 在index.js：51 
> > [ABORT@vue-router.esm.js](mailto:ABORT@vue-router.esm.js)：1921
> 
> 请问楼主解决了吗吗

没有 我在查解决办法

**Comment by lyxisblog** [comment]
> > > [http：// localhost：9527 /＃/ ](http://localhost:9527/#/) [http：// localhost：9528 /＃/ vue-admin模板也报同样的错误](http://localhost:9528/#/vue-admin%E6%A8%A1%E6%9D%BF%E4%B9%9F%E6%8A%A5%E5%90%8C%E6%A0%B7%E7%9A%84%E9%94%99%E8%AF%AF)
> > > vue-router.esm.js：1921错误：找不到模块@ / view / login / index'
> > > 在webPackemptyContext上（允许.js：137）
> > > 在index.js：51
> > > [ABORT@vue-router.esm.js](mailto:ABORT@vue-router.esm.js)：1921
> > 
> > 
> > 请问楼主解决了吗吗
> 
> 没有 我在查解决办法

好的，我也出现了同样问题 昨天还可以正常跑项目今天早上就不行了，如果楼主找到了解决办法麻烦告知下如何解决的消息了

**Comment by yaowenbin** [comment]
坐等答案。。。

**Comment by JC5** [comment]
Also experience the same problem.

**Comment by libaolei168** [comment]
各位 解决了  把router/index.js 中的 login路由 修改
import Login from '@/views/login/index'
component: Login,
不适用 () => import('@/views/login/index') 懒加载的模式就可以了

**Comment by libaolei168** [comment]
但是 这样登录 还是报错 就是 路由懒加载那里引起的  我在找其他解决办法

**Comment by lyxisblog** [comment]
> 但是 这样登录 还是报错 就是 路由懒加载那里引起的 我在找其他解决办法
好的麻烦了

**Comment by libaolei168** [comment]
> > 但是这样登录还是报错就是路由懒加载那里引起的我在找其他解决方法
> > 好的麻烦了

没事 我也是要用

**Comment by lyxisblog** [comment]
> > > 但是这样登录还是报错就是路由懒加载那里引起的我在找其他解决方法 好的麻烦了
> 
> 没事 我也是要用

用你提供的办法修改后是出来登录页面了，但当点击登录按钮就报错:
Error: Cannot find module '@/views/dashboard/index'
    at webpackEmptyContext (permission.js:161)
    at index.js:82

**Comment by lyxisblog** [comment]
> > > 但是这样登录还是报错就是路由懒加载那里引起的我在找其他解决方法好的麻烦了
> 
> 没事我也是要用

所有懒加载都出问题了  都修改成你说的那样就行了...暂时....

**Comment by libaolei168** [comment]
> > > > 但是这样登录还是报错就是路由懒加载那里引起的我在找其他解决方法好的麻烦了
> > 
> > 
> > 没事我也是要用
> 
> 所有懒加载都出问题了 都修改成你说的那样就行了...暂时....

对 我在找其他解决办法  应该就是懒加载的问题

**Comment by lyxisblog** [comment]
> > > > > 但是这样登录还是报错就是路由懒加载那里引起的我在找其他解决方法好的麻烦了
> > > 
> > > 
> > > 没事我也是要用
> > 
> > 
> > 所有懒加载都出问题了 都修改成你说的那样就行了...暂时....
> 
> 对 我在找其他解决办法 应该就是懒加载的问题

嗯呢   同找 如果找到了麻烦告知下谢谢

**Comment by libaolei168** [comment]
> > > > > > 但是这样登录还是报错就是路由懒加载那里引起的我在找其他解决方法好的麻烦了
> > > > 
> > > > 
> > > > 没事我也是要用
> > > 
> > > 
> > > 所有懒加载都出问题了 都修改成你说的那样就行了...暂时....
> > 
> > 
> > 对 我在找其他解决办法 应该就是懒加载的问题
> 
> 嗯呢 同找 如果找到了麻烦告知下谢谢

好的

**Comment by soleflora** [comment]
用之前的依赖就没有问题，如果重新下载依赖就会出现

**Comment by lyxisblog** [comment]
> 用之前的依赖就没有问题，如果重新下载依赖就会出现

对的  我之前依赖被我删了 今天早上重新下载就出问题了 不管是cnpm还是npm

**Comment by libaolei168** [comment]
应该是哪个依赖更新了

**Comment by ZachGuoMingyu** [comment]
今天也是遇到了这个问题

**Comment by draweye** [comment]
同问

**Comment by wangyunjiegit** [comment]
+1

**Comment by yangzongzhuan** [comment]
临时解决方案，参考 https://gitee.com/y_project/RuoYi-Vue/commit/da5c1328beb06a4c785aa2791a2b9ca3bbeefaa6

**Comment by libaolei168** [comment]
> 临时解决方案，参考 https://gitee.com/y_project/RuoYi-Vue/commit/da5c1328beb06a4c785aa2791a2b9ca3bbeefaa6
谢谢

**Comment by libaolei168** [comment]
router/index.js的路由懒加载 全部替换下
component: () => import('@/views/login'),
替换成
component: (resolve) => require(['@/views/login'], resolve),

**Comment by LYM65177107** [comment]
遇到同样的问题，解决方式：安装一下@babel/plugin-syntax-dynamic-import
[https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import/](url)

**Comment by lyxisblog** [comment]
> 遇到同样的问题，解决方式：安装一下@babel/plugin-syntax-dynamic-import
> [https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import/](url)

 请问这样是不是就可以直接解决了呢

**Comment by LYM65177107** [comment]
> > 遇到同样的问题，解决方式：安装一下@babel/plugin-syntax-dynamic-import
> > [https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import/](url)
> 
> 请问这样是不是就可以直接解决了呢

可以直接解决，你尝试一下，我在找具体原因

**Comment by lyxisblog** [comment]
> > > 遇到同样的问题，解决方式：安装一下@babel/plugin-syntax-dynamic-import
> > > [https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import/](url)
> > 
> > 
> > 请问这样是不是就可以直接解决了呢
> 
> 可以直接解决，你尝试一下，我在找具体原因

好的 谢谢

**Comment by libaolei168** [comment]
> babel-plugin-dynamic-import-node

npm 安装下就可以了吗 ？

**Comment by sigmadfzb** [comment]
> > babel-plugin-dynamic-import-node
> 
> npm 安装下就可以了吗 ？

好像没用哇

**Comment by lyxisblog** [comment]
> > > babel-plugin-dynamic-import-node
> > 
> > 
> > npm 安装下就可以了吗 ？
> 
> 好像没用哇

刚别人发我的在写项目还没试，你可以试下如果好了麻烦告诉我下：
修改package.jason文件："babel-plugin-dynamic-import-node": "2.3.0"
rm -irf node_modules package-lock.json
npm install
fixed

**Comment by duzhenyi** [comment]
恼火哦。报错

**Comment by qiuxianglin** [comment]
删掉   node_modules     package-lock.json

npm install --registry=https://registry.npm.taobao.org

npm  install  babel-plugin-syntax-dynamic-import

我是这样装好像可以开

**Comment by duzhenyi** [comment]
> 删掉 node_modules package-lock.json
> 
> npm install --registry=https://registry.npm.taobao.org
> 
> npm install babel-plugin-syntax-dynamic-import
> 
> 我是这样装好像可以开

具体完整的 npm install 啊，作者呢？处理下啊

**Comment by Mater1996** [comment]
回退 babel-plugin-dynamic-import-node => 2.3.0 就可以了
![image](https://user-images.githubusercontent.com/26322213/79845910-57ffe800-83f0-11ea-99ed-6136a268ac53.png)
原作者提交记录里多出了几个依赖，并更新了babel/core的版本

**Comment by duzhenyi** [comment]
> 回退 babel-plugin-dynamic-import-node => 2.3.0 就可以了
> ![image](https://user-images.githubusercontent.com/26322213/79845910-57ffe800-83f0-11ea-99ed-6136a268ac53.png)
> 原作者提交记录里多出了几个依赖，并更新了babel/core的版本

看不见图片啊

**Comment by duzhenyi** [comment]
> > 删掉 node_modules package-lock.json
> > npm install --registry=https://registry.npm.taobao.org
> > npm install babel-plugin-syntax-dynamic-import
> > 我是这样装好像可以开
> 
> 具体完整的 npm install 啊，作者呢？处理下啊

按你说的不行哦，一样的问题

**Comment by libaolei168** [comment]
> 回退 babel-plugin-dynamic-import-node => 2.3.0 就可以了
> ![image](https://user-images.githubusercontent.com/26322213/79845910-57ffe800-83f0-11ea-99ed-6136a268ac53.png)
> 原作者提交记录里多出了几个依赖，并更新了babel/core的版本

回退了 依然无效

**Comment by qiuxianglin** [comment]
> > > 删掉 node_modules package-lock.json
> > > npm install --registry=https://registry.npm.taobao.org
> > > npm install babel-plugin-syntax-dynamic-import
> > > 我是这样装好像可以开
> > 
> > 
> > 具体完整的 npm install 啊，作者呢？处理下啊
> 
> 按你说的不行哦，一样的问题

我估计这也不是所有人适用，我这是可以，还是等作者具体解决

**Comment by chuzhixin** [comment]
router懒加载的问题临时解决方法：改成require方式
https://github.com/chuzhixin/vue-admin-beautiful/blob/master/src/router/index.js

**Comment by Mater1996** [comment]
看一下你们node_modules里的版本把？

**Comment by libaolei168** [comment]
> 看一下你们node_modules里的版本把？

看了 2.3.0

**Comment by duzhenyi** [comment]
不仅报错，而且npm run dev的时候 一次性给我开启了2个浏览器地址，这个咋回事

**Comment by libaolei168** [comment]
> ### **问题已解决！！！！
> router懒加载的问题临时解决方法：改成require方式
> 打开自己router文件夹下的index.js,把所有的import改成如下方式
> component: (resolve) => require(["@/views/login/index"], resolve),
> 参考地址
> https://github.com/chuzhixin/vue-admin-beautiful/blob/master/src/router/index.js**
这种解决办法上面我就说了

**Comment by xiaodaoM** [comment]
好麻烦.所有的路由都需要改

**Comment by lyxisblog** [comment]
> > ### **问题已解决！！！！
> > router懒加载的问题临时解决方法：改成require方式
> > 打开自己router文件夹下的index.js,把所有的import改成如下方式
> > component: (resolve) => require(["@/views/login/index"], resolve),
> > 参考地址
> > https://github.com/chuzhixin/vue-admin-beautiful/blob/master/src/router/index.js**
> > 这种解决办法上面我就说了

待会去试试

**Comment by FullEnergyManLixp** [comment]
路由改完，没有报错了，但是进入http://localhost:9527/显示空白页面

**Comment by chuzhixin** [comment]
> > http://localhost:9527/#/ [http://localhost:9528/#/vue-admin模板也报同样的错误](http://localhost:9528/#/vue-admin%E6%A8%A1%E6%9D%BF%E4%B9%9F%E6%8A%A5%E5%90%8C%E6%A0%B7%E7%9A%84%E9%94%99%E8%AF%AF)
> > vue-router.esm.js：1921错误：找不到模块@/view/login/index‘
> > 在webPackemptyContext上(允许.js：137)
> > at index.js：51
> > [ABORT@vue-router.esm.js](mailto:ABORT@vue-router.esm.js)：1921
> 
> 请问楼主解决了吗

![Uploading image.png…]()


> 坐等答案。。。



> 路由改完，没有报错了，但是进入[http://localhost:9527/显示空白页面](http://localhost:9527/%E6%98%BE%E7%A4%BA%E7%A9%BA%E7%99%BD%E9%A1%B5%E9%9D%A2)

https://github.com/chuzhixin/vue-admin-beautiful/blob/master/src/router/index.js看下这个 试过了没问题

**Comment by xiaodaoM** [comment]
> > > 遇到同样的问题，解决方式：安装一下@babel/plugin-syntax-dynamic-import
> > > [https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import/](url)
> > 
> > 
> > 请问这样是不是就可以直接解决了呢
> 
> 可以直接解决，你尝试一下，我在找具体原因
安装了.也是不行.

**Comment by LYM65177107** [comment]
@lyxisblog @xiaodaoM 抱歉，上面说的那种方式我自己好使，别人不行，也是很奇怪。。。。
用新的工程指定安装babel-plugin-dynamic-import-node@2.3.0版本，是可以的，已经安装过依赖的话，回滚到指定版本也是可以的

**Comment by libaolei168** [comment]
> @lyxisblog @xiaodaoM 抱歉，上面说的那种方式我自己好使，别人不行，也是很奇怪。。。。
> 用新的工程指定安装babel-plugin-dynamic-import-node@2.3.0版本，是可以的，已经安装过依赖的话，回滚到指定版本也是可以的

安装完以后 npm install 完成以后 在 npm i babel-plugin-dynamic-import-node@2.3.0 -S 在运行 npm run dev 还是不行啊

**Comment by LYM65177107** [comment]
> > @lyxisblog @xiaodaoM 抱歉，上面说的那种方式我自己好使，别人不行，也是很奇怪。。。。
> > 用新的工程指定安装babel-plugin-dynamic-import-node@2.3.0版本，是可以的，已经安装过依赖的话，回滚到指定版本也是可以的
> 
> 安装完以后 npm install 完成以后 在 npm i babel-plugin-dynamic-import-node@2.3.0 -S 在运行 npm run dev 还是不行啊

试试删除node_modules和package-lock.json，在package.json中devDependencies里直接添加指定版本，再install呢？

**Comment by xuanhen2013** [comment]
在 package.json 加入
`
// devDependencies
"babel-plugin-dynamic-import-node": "2.3.0"
`
强行将版本降低到 2.3.0，可以在不修改代码的情况下解决这个问题
就看后续这个要怎么修复了

**Comment by libaolei168** [comment]
> 在 package.json 加入
> 
> ```json
> {
>   "devDependencies": {
>      "babel-plugin-dynamic-import-node": "2.3.0"
>   }
> }
> ```
> 
> 强行将版本降低到 2.3.0，可以在不修改代码的情况下解决这个问题
> 就看后续这个要怎么修复了
> 
> ```shell
> rm -rf package-lock.json
> rm -rf node_modules
> npm i
> ```
可以了 十分感谢 但是现在  npm run dev 后弹出两个窗口是为什么呢
