### ISSUE TITLE
组件加载失败

### ISSUE THREAD

**Issue by dlcheung** [PanJiaChen/vue-element-admin#3132]
## Bug report（问题描述）
拉取下来的项目运行失败，Chrome显示异常

app.js:89629 Error: Cannot find module '@/views/login/index'
at webpackEmptyContext (app.js:106098)
    at app.js:106189

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/9570544/79853712-fa24cd80-83fa-11ea-9150-52ce0a1f1c2a.png)

**Comment by hello-lc** [comment]
请问你找到原因了吗？我也遇到同样的问题
