### ISSUE TITLE
使用es6的模板语法编译不过

### ISSUE THREAD

**Issue by l54808821** [PanJiaChen/vue-element-admin#3140]
使用了模板语法时候，报错，代码如下
export default name => () => import(``@/views/${name}.vue``)
![image](https://user-images.githubusercontent.com/49773498/80307445-ac91d180-87fb-11ea-8abe-4d8f894ec3e7.png)

报错如下：
Failed to compile with 1 errors
in ./src/utils/lazyLoading.js

**Comment by EricPengLong** [comment]
引用：
这大概是因为 babel-plugin-dynamic-import-node 引用最新版本 2.3.2 导致 vue-router 的懒加载写法不支持es写法。
解决方案：
1.安装 babel-plugin-dynamic-import-node 的2.3.0版本即可
2.如果已安装所有模块的再安装该版本未生效，可先移除安装模块，再在package.json中添加该版本，之后重新安装
https://github.com/PanJiaChen/vue-admin-template/issues/570
