### ISSUE TITLE
vue-elment-admin中是如何解决vuex刷新后状态更新的问题的？(没看到localStorage, cookie也只用于少数几个地方)

### ISSUE THREAD

**Issue by wyhimself** [PanJiaChen/vue-element-admin#3146]
## Question（提问）
vue-elment-admin中是如何解决vuex刷新后状态更新的问题的？(没看到localStorage, cookie也只用于少数几个地方)。

**Comment by leeggco** [comment]
什么状态？用户状态在刷新时是会重发请求的。

**Comment by PanJiaChen** [comment]
刷新页面，重新请求用户信息。
本项目基本上没用localStorage或cookie做太多的本地存储。
