### ISSUE TITLE
在演示网站，点登录进不去，需要刷新整页才能进主界面？

### ISSUE THREAD

**Issue by bwangel** [PanJiaChen/vue-element-admin#3154]
在示例网站，点击登录要等好久才进去，而且没有动态过渡效果，
让人容易怀疑人生。

**Comment by PanJiaChen** [comment]
github 预览地址需要翻墙，不然很慢。
你可以直接访问 gitee地址 https://panjiachen.gitee.io/vue-element-admin/#/
