### ISSUE TITLE
Link.vue 报错 更改后出现bug

### ISSUE THREAD

**Issue by z7436** [PanJiaChen/vue-element-admin#3156]
## Bug report（问题描述）
在Link.vue中报了个错误：
![image](https://user-images.githubusercontent.com/45486477/80866217-17da1880-8cc0-11ea-8c9a-b87319841154.png)
此时的页面正常显示，功能看起来也都正常：
![image](https://user-images.githubusercontent.com/45486477/80866242-32ac8d00-8cc0-11ea-91f7-14f607ae5eca.png)
我将这个错误更改后，错误消失了：
![image](https://user-images.githubusercontent.com/45486477/80866303-71424780-8cc0-11ea-9bce-832f3efccbbf.png)
但是页面出现了问题，少了很多侧边栏的标签，并且此时单击并没有事件发生：
![image](https://user-images.githubusercontent.com/45486477/80866307-7b644600-8cc0-11ea-8d14-9b4f5a1a5ee8.png)

#### Steps to reproduce（问题复现步骤）
同上

#### Screenshot or Gif（截图或动态图）
同上

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1700
可以这么改

**Comment by z7436** [comment]
好的
