### ISSUE TITLE
excel 导出时可以指定编码格式吗？

### ISSUE THREAD

**Issue by chenjianeng0201** [PanJiaChen/vue-element-admin#3159]
excel 导出时如果可以指定编码格式的话应该怎么设置呢？使用说明里没有描述相关信息

**Comment by PanJiaChen** [comment]
你指 bookType？

https://panjiachen.github.io/vue-element-admin-site/feature/component/excel.html#params

**Comment by jinjiabin94** [comment]
> 你指 bookType？
> 
> https://panjiachen.github.io/vue-element-admin-site/feature/component/excel.html#params

不是bookType，我这也有这个问题， 在哪里可以设置导出excel或者csv文件的编码

**Comment by chenjianeng0201** [comment]
> 你指 bookType？
> 
> https://panjiachen.github.io/vue-element-admin-site/feature/component/excel.html#params

不是文件格式，是文件编码。我希望能导出 shift-jis 格式的，而不是默认的 utf-8

**Comment by PanJiaChen** [comment]
> > 你指 bookType？
> > [panjiachen.github.io/vue-element-admin-site/feature/component/excel.html#params](https://panjiachen.github.io/vue-element-admin-site/feature/component/excel.html#params)
> 
> 不是bookType，我这也有这个问题， 在哪里可以设置导出excel或者csv文件的编码

你看文档了么，bookType改一下不就是csv了

**Comment by PanJiaChen** [comment]
> shift-jis

https://github.com/SheetJS/sheetjs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc 你可以去给 sheetjs 提一个issue 问一下

**Comment by chenjianeng0201** [comment]
> > shift-jis
> 
> https://github.com/SheetJS/sheetjs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc 你可以去给 sheetjs 提一个issue 问一下

好的，谢谢

**Comment by PanJiaChen** [comment]
https://github.com/SheetJS/sheetjs/issues/1933
