### ISSUE TITLE
综合table案例，时间格式化报错Failed to resolve filter: parseTime

### ISSUE THREAD

**Issue by allinshang** [PanJiaChen/vue-element-admin#316]
vue.esm.js?efeb:574 [Vue warn]: Failed to resolve filter: parseTime
这是什么原因呢

**Comment by gitwillsky** [comment]
没有找到 parseTime 这个filter，看看你的filter文件夹内的代码。

**Comment by allinshang** [comment]
我在complexTable.vue里边引入：import { parseTime } from '@/utils'
这个了，但是还是提示这个问题，时间格式化不了。。显示： “975499709568”

**Comment by PanJiaChen** [comment]
filter 我注册在全局的。
https://github.com/PanJiaChen/vue-element-admin/blob/b4b9d166c4e54a37125e94321edc717738b2632f/src/main.js#L19-L21

`import { parseTime } from '@/utils'` 不是filter 只是一个格式化的function

**Comment by allinshang** [comment]
@PanJiaChen，解决了。谢谢。
