### ISSUE TITLE
配置proxy后，post请求有数据会失败，有人遇到过这种情况吗

### ISSUE THREAD

**Issue by LeeChiChuang** [PanJiaChen/vue-element-admin#3165]
## Question（提问）
devServer: {
    proxy: {
      '/user': {
        target: 'http://test.demo.com',
        ws: true,
        changeOrigin: true
      }
    },
    port: port,
    open: true,
    overlay: {
      warnings: false,
      errors: true
    },

    before: require('./mock/mock-server.js')
  },

![image](https://user-images.githubusercontent.com/26855113/81422630-cc26e380-9185-11ea-9dd4-42b741edce45.png)
上面这样会失败，请求里面有request payload数据，提示超时
![image](https://user-images.githubusercontent.com/26855113/81422905-3fc8f080-9186-11ea-8719-42c9830bd870.png)
去掉request里面的data之后又成功了,返回的是通过代理之后获得的数据。

## 重现步骤
配置proxy
在登录页面提交登录，无法返回数据
修改api/user.js里面 取到login方法的data，又成功了
- Your OS:mac os 10.15.4
- Node.js version:v10.14.2
- vue-element-admin version:4.2.1

**Comment by somenzz** [comment]
我也遇到这种情况，get 可以，post 就不行

**Comment by SylarZing** [comment]
对于Template那个工程也有相同的问题...

**Comment by LeeChiChuang** [comment]
没有使用这种方式了，换成服务端允许跨域方式。
