### ISSUE TITLE
svg的使用：Unknown custom element: <svg-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### ISSUE THREAD

**Issue by allinshang** [PanJiaChen/vue-element-admin#317]
第一步安装：
npm install --save-dev svg-sprite-loader
npm install --save clipboard

第二个：
在webpack.base.conf添加
{
        test: /\.svg$/,
        loader: 'svg-sprite-loader',
        include: [resolve('src/icons')],
        options: {
          symbolId: 'icon-[name]'
        }
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        exclude: [resolve('src/icons')],
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      }
第三步添加相应的
src/components/Icon-svg
src/icons
src/utils/clipboard.js

第四步：在页面中使用：
pages/complexTable.vue
<svg-icon v-for="n in +scope.row.importance" icon-class="star" class="meta-item__icon" :key="n"></svg-icon>

报错：
[Vue warn]: Unknown custom element: <svg-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

求解，不知道这个svg的使用，在哪里出了问题。谢谢

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/main.js#L9
> did you register the component correctly

**Comment by allinshang** [comment]
在src/main.js引入了
import './icons' // icon

**Comment by allinshang** [comment]
![image](https://user-images.githubusercontent.com/914579/33477373-6a3e87ae-d6c0-11e7-983d-ef4ff55513df.png)
页面的节点是这样的。

**Comment by allinshang** [comment]
解决了。谢谢@PanJiaChen
我在src/icons/index.js文件中,下面这句引的位置不正确。
import SvgIcon from '@/components/common/SvgIcon'// svg组件
