### ISSUE TITLE
external-link 外链的问题

### ISSUE THREAD

**Issue by yoyoidea** [PanJiaChen/vue-element-admin#3171]
## Question（提问）
外链放在外面可以，多级之后会多出‘/’
```
  {
    path: '/soc',
    component: Layout,
    meta: {
      icon: 'component',
      title: 'SOC'
    },
    children: [
      {
        path: 'src',
        component: () => import('@/views/soc/bsrc'),
        name: 'src',
        meta: { title: 'src' }
      }, {
        path: 'security-scanning',
        component: () => import('@/views/soc/security-scanning'),
        name: 'security-scanning',
        meta: { title: 'securityScanning' }
      },
     //多出斜杠
      {
        path: 'https://github.com/PanJiaChen/vue-element-admin',
        name: 'github-scanning',
        meta: { title: 'githubScanning' }
      }
    ]
  },
 // 没有问题
  {
    path: 'external-link',
    component: Layout,
    children: [
      {
        path: 'https://github.com/PanJiaChen/vue-element-admin',
        meta: { title: 'githubScanning' }
      }
    ]
  },
```
#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/5858753/81471176-e9a98b00-9221-11ea-9a63-4f10e1fa5442.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
没能重现你的问题

**Comment by mengbaiai** [comment]
path: '/soc'改成
path: 'soc'试试

**Comment by yoyoidea** [comment]
![image](https://user-images.githubusercontent.com/5858753/81662069-a2b0d500-946f-11ea-8ecb-28536bd9bab4.png)
![image](https://user-images.githubusercontent.com/5858753/81662101-ab091000-946f-11ea-96b8-6bc8f8a13e42.png)
我用官网最简单的例子，在二级目录中加外链， 也有同样的问题

**Comment by PanJiaChen** [comment]
你是windows?

**Comment by yoyoidea** [comment]
确定 tag是v4.0.0

**Comment by yoyoidea** [comment]
![image](https://user-images.githubusercontent.com/5858753/81782862-06e59e80-952d-11ea-97e6-be581e012a96.png)

**Comment by PanJiaChen** [comment]
所以你并不是最新版本，把我上面贴的代码，合入你的代码就好了。

**Comment by yoyoidea** [comment]
解决了 非常感谢 我一只以为我的是最新版本
