### ISSUE TITLE
When and where to add side-bar, navbar and breadcrumb to the screen? How do I subtract it?

### ISSUE THREAD

**Issue by 2Seok0** [PanJiaChen/vue-element-admin#3173]
## Question（提问）
Hi.
first of all.. thank you for developed this application. 

this is the question 

I want to make a page without sidebar-container, navbar and breadcrumb.
However, this requires user authentication. (like login page template) 

I'm trying to this 
I made a vue-page and added a router/index.js 
Then it must be attached to the sidebar-container, navbar and breadcrumb.
So I put a new page inside ```export const constantRoutes```.

export const constantRoutes = [
 {
    path: '/report/analyze',
    name: 'analyze',
    meta: { title: 'Daily Report' },
    component: () => import('@/views/report/analyze2'),
    hidden: true
  },
]

Then I got the result I wanted.

I want to know 
When and where to add side-bar, navbar and breadcrumb to the screen?
How do I subtract it?

somebody help me 
thank you

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/layout/index.vue

https://github.com/PanJiaChen/vue-element-admin/blob/master/src/layout/components/Navbar.vue
