### ISSUE TITLE
请问一下你的mock-server里面怎么打印请求头信息

### ISSUE THREAD

**Issue by lnsane** [PanJiaChen/vue-element-admin#3174]
{
    url: 'this is a url',
    type: 'post',
    response: config => {
      if (config.body.orgId === 1258699596985667600) {
        console.log(config.body)  // 打印不出来呀
        return {
          code: 20000,
          data: post_query_data
        }
      } else {
        return {
          code: 20000,
          data: null
        }
      }
    }
  },

**Comment by mengbaiai** [comment]
1.在if前面打印console.log(config)
2.在cmd里面找日志

**Comment by lnsane** [comment]
> 1.在if前面打印console.log(config)
> 2.在cmd里面找日志

thanks
