### ISSUE TITLE
大佬，仿照你的项目做了个react+antd版的，向大佬致敬

### ISSUE THREAD

**Issue by NLRX-WJC** [PanJiaChen/vue-element-admin#3176]
项目地址：https://github.com/NLRX-WJC/react-antd-admin-template
在线预览：https://nlrx-wjc.github.io/react-antd-admin-template/
向大佬致敬！

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/2312
环境在这里加上
