### ISSUE TITLE
npm install mac 会报错 widows 正常 

### ISSUE THREAD

**Issue by 160905** [PanJiaChen/vue-element-admin#318]
Unexpected end of JSON input while parsing near '....4.0","optionator":"^'

**Comment by PanJiaChen** [comment]
需要更具体报错信息

**Comment by 160905** [comment]
<img width="570" alt="wx20171203-120229 2x" src="https://user-images.githubusercontent.com/22002759/33522219-f35c2ee4-d821-11e7-89e8-2b86d23a01ed.png">

**Comment by PanJiaChen** [comment]
试试 `npm cache clean --force`
再不行 请确定一下自己 `npm`和 `node`的版本号

**Comment by 160905** [comment]
问题 解决了 这是什么原因 造成的 
最后 感谢大神相助

**Comment by PanJiaChen** [comment]
你可以理解为重启能解决大部分问题。。。玄学
