### ISSUE TITLE
'scope' is defined but never used.

### ISSUE THREAD

**Issue by libaolei168** [PanJiaChen/vue-element-admin#3182]
## Question（提问）

` <template slot-scope="scope">
          {{ province_id ? province_id : "-" }}
</template>`

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/20697436/81652286-151cb780-9466-11ea-9195-756cf53fa3ae.png)

**Comment by sunpu007** [comment]
scope没有使用

**Comment by libaolei168** [comment]
> scope没有使用

element-ui 文档里面就让这样使用啊·······
