### ISSUE TITLE
drag-table page的未知报错

### ISSUE THREAD

**Issue by mengbaiai** [PanJiaChen/vue-element-admin#3184]
## Bug report（问题描述）

https://panjiachen.github.io/vue-element-admin/#/table/drag-table

Console未知报错

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/40969504/81699847-778fab00-949a-11ea-94e5-cd191560e9fb.png)

**Comment by zhongchuihan** [comment]
这个页面的代码里面，给el-table的data绑定的list变量开始是null，你把它改成一个空数组就行了

**Comment by mengbaiai** [comment]
解决倒是解决了，就是报错有点莫名其妙，感谢

**Comment by mengbaiai** [comment]
难怪Pull requests没通过自动检查，
原来是https://panjiachen.github.io/vue-element-admin/#/error-log/log
这的问题。。
