### ISSUE TITLE
cascader异步加载的情况,无法清空值, 无法获取值

### ISSUE THREAD

**Issue by cycxy** [PanJiaChen/vue-element-admin#3185]
## Bug report（问题描述）

el-cascader ref="addcascader" :props="props" :options="dataList" :style="inputwidth"

data数据......
 props: {
        label: 'name',
        value: 'id',
        lazy: true,
        lazyLoad(node, resolve) {
          _this.getChildrens(node, function(res) {
            if (res.data) {
              alldataList = res.data.concat(alldataList)
            }
            resolve(res.data)
          })
        }
      }

#### Steps to reproduce（问题复现步骤）
 1. 有2个问题, 一个是this.$refs.addcascader 输出的时候 ,能在控制台看到有inputvalue值 , 但是取不到
this.$refs.addcascader.inputvalue  是一个空的
2. 想要选择后进行清除数据 , 试了几个改变dom值 , 也没有效果 ,  clearCheckedNodes这个方法, 调用是is not funciton , 应该是我用的不是 CascaderPanel  , 那么Cascader这种, 如何清除界面上选择的数据. 强制设置的空值 ,界面是没有重新渲染的. 需要再去点一下.其他, 然后才会触发渲染.

#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/8298993/81700064-c2112780-949a-11ea-8d96-fbbfc08fb9fc.png)

**Comment by cycxy** [comment]
> ## Bug report（问题描述）
> data数据...... props: { label: 'name', value: 'id', lazy: true, lazyLoad(node, resolve) { _this.getChildrens(node, function(res) { if (res.data) { alldataList = res.data.concat(alldataList) } resolve(res.data) }) } }
> #### Steps to reproduce（问题复现步骤）
> 1. 有2个问题, 一个是this.$refs.addcascader 输出的时候 ,能在控制台看到有inputvalue值 , 但是取不到
>    this.$refs.addcascader.inputvalue  是一个空的
> 2. 想要选择后进行清除数据 , 试了几个改变dom值 , 也没有效果 ,  clearCheckedNodes这个方法, 调用是is not funciton , 应该是我用的不是 CascaderPanel  , 那么Cascader这种, 如何清除界面上选择的数据. 强制设置的空值 ,界面是没有重新渲染的. 需要再去点一下.其他, 然后才会触发渲染.
> 
> #### Screenshot or Gif（截图或动态图）
> ![image](https://user-images.githubusercontent.com/8298993/81700064-c2112780-949a-11ea-8d96-fbbfc08fb9fc.png)

**Comment by PanJiaChen** [comment]
element-ui 的问题请至 https://github.com/ElemeFE/element 提问
