### ISSUE TITLE
TreeTable 组件更新element版本到2.13.1,样式失效了

### ISSUE THREAD

**Issue by miaomiaoF** [PanJiaChen/vue-element-admin#3189]
默认全部展开,点击‘+’或者‘-’不起作用
![image](https://user-images.githubusercontent.com/34463477/81768714-46e95900-950e-11ea-9bb8-9aea3a9bde3f.png)

**Comment by PanJiaChen** [comment]
不兼容。
新版本请使用element-ui 自带的tree-table。
