### ISSUE TITLE
提一个小小的建议,希望群主可以table做一个树状table

### ISSUE THREAD

**Issue by youdianfan** [PanJiaChen/vue-element-admin#319]
感谢作者的文档,项目,学到很多啊,希望作者可以对table加入一个树状table,这个需求对后台管理来说,大部分都需要,我就是借鉴群主的项目,完成了我公司的后台,其中就有树状table这个需求!只是建议!再次感谢作者!

**Comment by PanJiaChen** [comment]
能具体说一下需求么？我不是很理解树状table

**Comment by youdianfan** [comment]
感谢群主，回复，明日，补充，群里回发送你相关图片。

**Comment by PanJiaChen** [comment]
请在次发

**Comment by youdianfan** [comment]
非常抱歉！！！今天早上，我去找个图，务必描述清楚。的确这个，treetable树状表格，我看到比较完美的，并不多。自己项目中，实践的树状表格，也是借鉴他人的，一直有关注作者的这个项目，所以根据我公司的需求，来给作者提个建议，希望也加入这个功能，让这个项目，更加完美，一应俱全！

**Comment by youdianfan** [comment]
[http://img.blog.csdn.net/20170311164309477](url)

传图好像失败了,我贴上一个项目地址吧.然后在做补充吧

[他人的项目地址:](http://blog.csdn.net/s8460049/article/details/61414751)

**Comment by youdianfan** [comment]
大概就是这样的效果.我再贴上我们ui图吧.
![treetable](https://user-images.githubusercontent.com/27018910/33532432-a3eac9a2-d8d4-11e7-8615-3ca774d9fe0c.png)

**Comment by PanJiaChen** [comment]
这个需求暂时待定吧，如果有更多的人有这需求就考虑在做。

**Comment by youdianfan** [comment]
好的

**Comment by OoObaby** [comment]
我觉得听需要的，虽然现在没用到，但是肯定不久就会

**Comment by mythbobo** [comment]
这个需求在做权限管理的时候会用到。还是很常用的。。希望能加入

**Comment by axhello** [comment]
+1 权限管理确实就用到了

**Comment by zzc-zhichen** [comment]
+1这个需求经常有用到

**Comment by jianliulin** [comment]
财务的会计科目也非常需要treegrid

**Comment by anvi233** [comment]
部门下属管理也非常需要这种的，能少很多大多重复的页面

**Comment by TerrenceFong** [comment]
https://github.com/sunlandong/treeTable
有类似的，改改就能用了
![image](https://user-images.githubusercontent.com/16008881/33756908-98184daa-dc32-11e7-8f55-ae5f79b39384.png)

**Comment by daiing** [comment]
好东西，谢谢推荐

**Comment by leij1ang** [comment]
其实这个实现还是很简单的，利用elementui table的row-style可以很快搭建

**Comment by GeorgeMe** [comment]
希望加上  treetable

![tim 20180106091925](https://user-images.githubusercontent.com/7805207/34634816-c13faa38-f2c2-11e7-96f1-006fe78b7cf3.png)

**Comment by wlyao** [comment]
hope it can provide a tree table. Below is a tree table i'm using.  
https://github.com/wlyao/vue-table-with-tree-gird

**Comment by jiangzhiguos** [comment]
+1这个需求经常有用到

**Comment by PanJiaChen** [comment]
正在做了，做了一半，最近业务有点多耽搁了。尽快开源吧。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/415
新版本已整合 tree table.
之后我会将它抽成独立的npm包并配上文档。

**Comment by youdianfan** [comment]
厉害!期待中!

**Comment by a13514097** [comment]
新项目用了 撸主的框架，  第一个需求就是tree table。。。。恰解燃眉之急，希望大佬尽快上线。。

**Comment by a13514097** [comment]
今天用上了撸主的  tree-table 功能  在 coustomTreeTable  自定义树形表格里 expandAll是无效的   怎么设置都是展开状态

**Comment by a13514097** [comment]
今天用上了 撸主的 tree table 功能 但是在customTreeTable  expendAll设置无效  怎么设置都是展开状态

**Comment by a13514097** [comment]
撸主厉害， 这个功能刚上线，我就用上了。

**Comment by a13514097** [comment]
树形展开后  切换选项卡  keep-alive 记不住 展开或者关闭的 状态  切换选项卡后又恢复原样了

**Comment by leij1ang** [comment]
@a13514097 感谢bug，正在fix

**Comment by leij1ang** [comment]
@a13514097 expandAll的bug已经修改，keep-alive的我的能力有限，个人建议参照[treeTable](https://github.com/PanJiaChen/vue-element-admin/tree/master/src/components/TreeTable)的思路，根据实际情况来重新写一个组件

**Comment by leij1ang** [comment]
@a13514097  expandAll的bug已经修改，keep-alive的我的能力有限，个人建议参照treeTable的思路，根据实际情况来重新写一个组件，不要直接使用，坑还是很多的啊，哈哈哈。。

**Comment by a13514097** [comment]
expendAll  是因为 受了arg参数影响  是我自己改错文件了 一直调试不出来。。。后来删了那个回复了 。。keep-alive  是因为我忘记删二级路由的 include 了  删掉后全局 keep-alive  可行。。。 撸主们反馈又热情又迅速，由衷的感到温暖，好人一生平安！

**Comment by PanJiaChen** [comment]
`element` 2.7.0 支持 `tree-tale 了`。所以 `vue-element-admin`就不再自己维护 `tree-table`了。
