### ISSUE TITLE
打包发布后第一次访问慢

### ISSUE THREAD

**Issue by MQS520** [PanJiaChen/vue-element-admin#3192]
#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/38800589/81944969-10a3fa80-9630-11ea-8afa-16af4f954341.png)

#### Link to minimal reproduction（最小可在线还原demo）
因为是内部项目，所以没有demo

#### Other relevant information（格外信息）
- Your OS: mac
- Node.js version: 12.13.1
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
开启gzip or 上传到cdn or 进行必要的拆包，只加载需要的文件。
