### ISSUE TITLE
sidebar收缩状态下的滚动问题

### ISSUE THREAD

**Issue by Olsondy** [PanJiaChen/vue-element-admin#320]
先感谢一下作者,文档对我帮助太大啦....刚接触vue,不是很熟悉!!
现在有个问题,主菜单只有几个高度不足以滚动,在收缩状态下展开子菜单,高度就超出浏览器了,子菜单被挡住,可是不能滚动.一直想不到解决办法, 求大佬指教一下.感谢感谢

**Comment by PanJiaChen** [comment]
请提在线可复现代码或截图。

**Comment by cayar** [comment]
<img width="436" alt="issue" src="https://user-images.githubusercontent.com/8390373/33540270-4dd07ed2-d905-11e7-853a-032520420d4a.png">
@PanJiaChen 现在这种情况菜单没显示全,但是就滚动不了了,

**Comment by PanJiaChen** [comment]
的确会有这个问题，两种方案。
要么干脆左侧导航栏就不要fixed了，跟随滚动。
要么自己人为限制一下，不要让二级导航太长或者放在前面一点的问题。
暂时想不到什么好的方案来兼容这种情况。

**Comment by cayar** [comment]
Thanks a lot ! @PanJiaChen

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1619
