### ISSUE TITLE
大神能不能加个组件

### ISSUE THREAD

**Issue by jiankian** [PanJiaChen/vue-element-admin#321]
加这个组件
http://uxco.re/components/cascade-multi-select/
本是React的，找不到Vue实现的。不知道大神能不能Vue实现类似的选择器

**Comment by PanJiaChen** [comment]
你这种都不是常规需求。
自己实现难度也还好吧。
[cascader](http://element.eleme.io/#/zh-CN/component/cascader) + [tree](http://element.eleme.io/#/zh-CN/component/tree)
