### ISSUE TITLE
axios获取不到下载进度

### ISSUE THREAD

**Issue by bobliu2020** [PanJiaChen/vue-element-admin#3211]
vue文件里写里一个axios post请求用于下载，然后用onDownloadProgress获取下载进度，不打包前能用，打包后axios onDownloadProgress获取不到下载进度了，请问这是哪里的问题？
打包命令：npm run build:prod
打包前progressEvent正常，打包后progressEvent监听出错，获取不到loaded和total参数丢失，下载一切正常，只是获取不到下载进度
代码位置 src/views下的vue文件
代码如下：
```    
 axios({
          url:'loadFile',
          method: 'post',
          baseURL: 'http://127.0.0.1:5000/api/',
          headers: {
            'X-Token': getToken(),
          },
          data: {
            fileurl: scope.row.FileURL,
          },
          timeout: 100000,
          responseType: 'blob',
          onDownloadProgress: function (progressEvent) {
            console.log('------progressEvent-------', progressEvent)
          },

        }).then(res => {
            const objectUrl = URL.createObjectURL(res.data) // 创建URL
            link.href = objectUrl
            link.download = scope.row.FileURL // 自定义文件名
            link.click() // 下载文件
            console.log('------link-------', link)
            URL.revokeObjectURL(objectUrl) // 释放内存
            this.dialogforloadtitle = '下载完成'
          })
```
补充：
console.log('------progressEvent-------', progressEvent) 截图如下
![image](https://user-images.githubusercontent.com/45416413/83011609-ba31b580-a04c-11ea-80f7-80bea0e5ba88.png)

**Comment by bobliu2020** [comment]
补充：
console.log('------progressEvent-------', progressEvent) 截图如下
![image](https://user-images.githubusercontent.com/45416413/83011491-85256300-a04c-11ea-9560-21116a8dd77e.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/6f80263b4251fa72e04ac3d6a11f147b2d45aeea/src/main.js#L31

这段代码注释一下

**Comment by 806013920** [comment]
请问这个问题如何解决的？

**Comment by PengMai1998** [comment]
这个问题解决了吗？
