### ISSUE TITLE
login页面没有

### ISSUE THREAD

**Issue by tom1jack** [PanJiaChen/vue-element-admin#3220]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by tom1jack** [comment]
我本地跑的时候login页面没有切换语言按钮

**Comment by u4989190** [comment]
master本来就没有语言切换

**Comment by u4989190** [comment]
> 我本地跑的时候login页面没有切换语言按钮

master本来就没有语言切换

**Comment by GreatAuk** [comment]
![image](https://user-images.githubusercontent.com/20253809/83857717-f7353080-a74d-11ea-9afd-80de554316dc.png)

**Comment by tom1jack** [comment]
弄好了 ，在作者的文档网站找到分支连接了，谢谢了
