### ISSUE TITLE
打包時提示 js文件過大,有常識關閉 或 調整最大最小值

### ISSUE THREAD

**Issue by 8337009** [PanJiaChen/vue-element-admin#3222]
## Question（提问）
warning 

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  static/css/app.be084742.css (247 KiB)
  static/js/chunk-14da9915.a022c5dd.js (794 KiB)
  static/js/chunk-5164a781.36378c6c.js (890 KiB)
  static/js/chunk-5e77a1ab.048ba443.js (1.33 MiB)
  static/js/chunk-elementUI.df9735a9.js (662 KiB)
  static/js/chunk-libs.fc577de7.js (391 KiB)

 warning 

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can
impact web performance.
Entrypoints:
  app (1.42 MiB)
      static/js/runtime.927ffccc.js
      static/js/chunk-elementUI.df9735a9.js
      static/css/chunk-libs.3dfb7769.css
      static/js/chunk-libs.fc577de7.js
      static/css/app.be084742.css
      static/js/app.2e02b46b.js

**Comment by PanJiaChen** [comment]
webpack 提示，可以自行调整
