### ISSUE TITLE
个人页点击轮播图切换的时候，页面会闪烁

### ISSUE THREAD

**Issue by laii7** [PanJiaChen/vue-element-admin#3225]
#### Link to minimal reproduction（最小可在线还原demo）

https://panjiachen.github.io/vue-element-admin/#/profile/index

**Comment by Kellercai** [comment]
可以在通过以下css设置暂时解决谷歌浏览器闪屏问题。已在element提交PR。

.el-carousel__container {
   -webkit-backface-visibility: hidden;
    -webkit-transform: translate3d(0,0,0);
    -webkit-transform-style: preserve-3d;
   /* Other css */
}
