### ISSUE TITLE
侧边栏在路由配置怎么设置使用vue element ui内置图标

### ISSUE THREAD

**Issue by zyufstudio** [PanJiaChen/vue-element-admin#3229]
侧边栏在路由配置怎么设置使用vue element ui内置图标
在icon处设置图标类名，在侧边栏页面无法显示图标。
如：
  {
    path: '/',
    component: Layout,
    redirect: '/home',
    children: [{
      path: 'home',
      name: 'Home',
      component: () => import('@/views/home/index'),
      meta: { title: 'Home', icon: 's-home' }
    }]
  },

**Comment by feeldemo** [comment]
icon svg 下面 名字跟 s-home一样 即可


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zyufstudio"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 中午11:11
收件人:&nbsp;"PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[PanJiaChen/vue-element-admin] 侧边栏在路由配置怎么设置使用vue element ui内置图标 (#3229)





 
侧边栏在路由配置怎么设置使用vue element ui内置图标
 在icon处设置图标类名，在侧边栏页面无法显示图标。
 如：
 {
 path: '/',
 component: Layout,
 redirect: '/home',
 children: [{
 path: 'home',
 name: 'Home',
 component: () =&gt; import('@/views/home/index'),
 meta: { title: 'Home', icon: 's-home' }
 }]
 },

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/3048
新版本，直接使用 el-icon-xxx 就可以了
