### ISSUE TITLE
The Markdown Editor should be replaced to @toast-ui/editor

### ISSUE THREAD

**Issue by HuangChenglee** [PanJiaChen/vue-element-admin#3232]
tui-editor Version  is deprecated , and the leatest tui-editor (in npm)has a bug.

markdown编辑器应该从tui-edior换为 @toast-ui/editor，tui-editor 1.4版本有个bug preview 只有50px的宽度

**Comment by Soldier33** [comment]
为啥关闭了，我也遇到了这个问题，是怎么解决的呢
