### ISSUE TITLE
npm install出现问题deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info

### ISSUE THREAD

**Issue by 1750777402** [PanJiaChen/vue-element-admin#3233]
#### Steps to reproduce
npm install 出现异常：
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Socket.stream.socket.on (internal/child_process.js:346:11)
npm WARN addRemoteGit     at emitOne (events.js:116:13)
npm WARN addRemoteGit     at Socket.emit (events.js:211:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:557:12)
npm WARN addRemoteGit  sohee-lee7/Squire#b1e0e1031fa18912d233c204cbe7c7fae4a42621 resetting remote C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sohee-lee7-Squire-git-b1e0e1031fa18912d233c204cbe7c7fae4a42621-80ef77bb because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url  
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Socket.stream.socket.on (internal/child_process.js:346:11)
npm WARN addRemoteGit     at emitOne (events.js:116:13)
npm WARN addRemoteGit     at Socket.emit (events.js:211:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:557:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }

#### Screenshot or Gif

![image](https://user-images.githubusercontent.com/29274319/83776194-74af6100-a6ba-11ea-86bf-e5d2c14a2e69.png)

cnpm install也是报错：
![image](https://user-images.githubusercontent.com/29274319/83778304-1afc6600-a6bd-11ea-8ac2-b550e4ddced0.png)

**Comment by mayunhai** [comment]
npm install core-js@2.6.11 -D

**Comment by mayunhai** [comment]
core-js 3xx 版本兼容性有问题

**Comment by 1750777402** [comment]
> npm install core-js@2.6.11 -D

![image](https://user-images.githubusercontent.com/29274319/83960674-1783fd00-a8be-11ea-97f5-84feb6ddde09.png)
你好 我按照你的提示操作下来并不能解决这个问题 有点懵逼

**Comment by 1750777402** [comment]
> core-js 3xx 版本兼容性有问题

我在使用cnpm之后 依然会有这个提示，但是项目可以跑起来了，没什么报错

**Comment by mayunhai** [comment]
> > npm install core-js@2.6.11 -D
> 
> ![image](https://user-images.githubusercontent.com/29274319/83960674-1783fd00-a8be-11ea-97f5-84feb6ddde09.png)
> 你好 我按照你的提示操作下来并不能解决这个问题 有点懵逼

可能你 npm源被人修改过，或者公司网络限制或者网络状态不太好，cnpm能用也是可以的啊

**Comment by 1750777402** [comment]
> > > npm install core-js@2.6.11 -D
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/29274319/83960674-1783fd00-a8be-11ea-97f5-84feb6ddde09.png)
> > 你好 我按照你的提示操作下来并不能解决这个问题 有点懵逼
> 
> 可能你 npm源被人修改过，或者公司网络限制或者网络状态不太好，cnpm能用也是可以的啊

我的个人电脑，前端小白一个。。。现在用cnpm可以正常使用  谢谢大佬
