### ISSUE TITLE
关于websocket的访问问题

### ISSUE THREAD

**Issue by gxlqssjf** [PanJiaChen/vue-element-admin#3238]
## Question（提问）
就访问就成这样了，不知道哪有进行引用？

#### Screenshot or Gif（截图或动态图）
![图片](https://user-images.githubusercontent.com/1277598/83985355-7e132480-a96b-11ea-8dbc-2ac83b0c1a52.png)
![图片](https://user-images.githubusercontent.com/1277598/83985368-8bc8aa00-a96b-11ea-88ed-ad7cb8dc3f39.png)
![图片](https://user-images.githubusercontent.com/1277598/83985375-95eaa880-a96b-11ea-8d66-818a7ec04baf.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by PanJiaChen** [comment]
webpack-dev-server

**Comment by gxlqssjf** [comment]
> 
> 
> webpack-dev-server
其实我想问如何不用这个websocket,或是哪进行配置
