### ISSUE TITLE
顶部的breadcrumb和tab-view在功能上重复，是否考虑去掉一个？

### ISSUE THREAD

**Issue by CHCP** [PanJiaChen/vue-element-admin#324]
顶部的breadcrumb和tab-view在功能上重复，是否考虑去掉一个？

![image](https://user-images.githubusercontent.com/5645296/33548756-5a94fc38-d93c-11e7-9416-3e3351a62dd0.png)

**Comment by PanJiaChen** [comment]
完全是两种东西。。。为什么说功能重复。。。

**Comment by CHCP** [comment]
点击breadcrumb和tab-view的按钮，功能是一样的。

**Comment by PanJiaChen** [comment]
都是导航栏的一种，但作用又不同。
一个更多的是展现层级关系。另一个展现的是历史记录。一个有keep-alive缓存一个没有

**Comment by CHCP** [comment]
OK。
