### ISSUE TITLE
table先前的版本表格拖拽chorme浏览器不支持

### ISSUE THREAD

**Issue by CloudS-Hu** [PanJiaChen/vue-element-admin#325]
table先前的版本表格拖拽chorme浏览器不支持，我用的之前的版本现在没办法升级，作者可否把修正chorme浏览器不支持的代码贴出来，我手动取改动，非常感谢！

**Comment by PanJiaChen** [comment]
拖拽代码没有更改过

**Comment by CloudS-Hu** [comment]
我这边在chorme浏览器没办法拖拽，在safari是可以拖拽的，你们有同样的情况吗？

**Comment by CloudS-Hu** [comment]
@PanJiaChen

**Comment by PanJiaChen** [comment]
升级 `sortablejs` 到最新版本试试

**Comment by CloudS-Hu** [comment]
@PanJiaChen 升级后问题解决，谢谢
