### ISSUE TITLE
checkbox-group中选中后绑定数值更新了，但是视图没更新

### ISSUE THREAD

**Issue by fewbadboy** [PanJiaChen/vue-element-admin#3253]
## Bug report（问题描述）
弹窗dialog中根据不同的操作去显示tabs中不同的tab-pane的内容。在某一个显示的tab-pane中存在一个form,form中有一个checkbox-group。当点击选中checkbox-group中某一个选项的时候，通过change事件可以发现绑定的值发生了变化，但是视图并没有更新。当点击选择多个的时候，checkbox-group绑定的值只在最原始绑定的值得基础上，添加最后一次选择checkbox的值，同时不会显示选中的状态。只能通过点击一次切换一下tab才会显示上一次点击选中checkbox的状态。我原本以为是elementUI的问题，自己写了一个demo去测试了一下，发现是没问题的。
[codepen地址](https://codepen.io/renekton/pen/OJMXJrQ)

但是在当前开源框架中用同样的结构操作显示有问题

虽然我这通过在每次在选择chexkbox的时候通过来回切换tabs解决了显示的这个问题，但感觉这个好像也算个bug吧

#### Steps to reproduce（问题复现步骤）

在截图中展示的是在现有框架上展示出现的问题

#### Screenshot or Gif（截图或动态图）
![20200613140607](https://user-images.githubusercontent.com/12499323/84561765-cbcfc880-ad81-11ea-97bd-6d1db33561b8.gif)

**Comment by Harry-qi** [comment]
视图更新问题建议看下  [检测变化的注意事项](https://cn.vuejs.org/v2/guide/reactivity.html#%E6%A3%80%E6%B5%8B%E5%8F%98%E5%8C%96%E7%9A%84%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

**Comment by fewbadboy** [comment]
> 视图更新问题建议看下 [检测变化的注意事项](https://cn.vuejs.org/v2/guide/reactivity.html#%E6%A3%80%E6%B5%8B%E5%8F%98%E5%8C%96%E7%9A%84%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

我在问题中已经描述了，
点击选中checkbox-group中某一个选项的时候，通过change事件可以发现绑定的值发生了变化，但是视图并没有更新。
绑定的值都发生了变化，视图没更新，还需要去检测绑定的值发生了变化没？？？？
