### ISSUE TITLE
Open two tabs when run: npm run dev!

### ISSUE THREAD

**Issue by QuachDuy** [PanJiaChen/vue-element-admin#3258]
![image](https://user-images.githubusercontent.com/8982877/84730571-b09ecc00-afc0-11ea-83ce-72f6cf6db9ca.png)

**Comment by noenif** [comment]
我也是，年轻人

**Comment by LovelyYing** [comment]
Running normally in cmd

**Comment by joungle** [comment]
You need to update to vue-cli @ 4.

Check your vue-cli version:
`vue --version`

Update
`npm install -g @vue/cli`

Upgrade in root folder
`vue upgrade`

Same issue
PanJiaChen/vue-element-admin#2944 
vuejs/vue-cli#4088

**Comment by QuachDuy** [comment]
Thank you!

**Comment by netSharks** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/2944#issuecomment-856561747
