### ISSUE TITLE
解决新版本npm install 错误的问题

### ISSUE THREAD

**Issue by zhangga1302** [PanJiaChen/vue-element-admin#3259]
在这里看到很多人碰到npm install 中的各种问题，我今天安装也碰到了，翻看了好多个问题和解决办法，最终拼凑了完整的解决方案
我的是windows系统，我碰到的问题

1）node-sass安装问题
2）git各种报错
3）git 更新失败

**解决办法**
1、`npm config edit`
在npm配置文件中增加两行配置
```
registry = "https://registry.npm.taobao.org/"
sass_binary_site = "https://npm.taobao.org/mirrors/node-sass/"
```
2、更新git 
cmd下输入 git update-git-for-windows

3、在vue-element-admin下安装
`npm install --registry=https://registry.npm.taobao.org`

但是中途碰到了raw-loader一直等待无法继续的问题，终止之后重新执行npm install 又可以了。

顺利完成，npm run dev成功。

**Comment by PanJiaChen** [comment]
建议使用最新代码，基于 dart-sass 构建，解决node-sass的问题

**Comment by zengxiaoliang** [comment]
> 在这里看到很多人碰到npm install 中的各种问题，我今天安装也碰到了，翻看了好多个问题和解决办法，最终拼凑了完整的解决方案
> 我的是windows系统，我碰到的问题
> 
> 1）node-sass安装问题
> 2）git各种报错
> 3）git 更新失败
> 
> **解决办法**
> 1、`npm config edit`
> 在npm配置文件中增加两行配置
> 
> ```
> registry = "https://registry.npm.taobao.org/"
> sass_binary_site = "https://npm.taobao.org/mirrors/node-sass/"
> ```
> 
> 2、更新git
> cmd下输入 git update-git-for-windows
> 
> 3、在vue-element-admin下安装
> `npm install --registry=https://registry.npm.taobao.org`
> 
> 但是中途碰到了raw-loader一直等待无法继续的问题，终止之后重新执行npm install 又可以了。
> 
> 顺利完成，npm run dev成功。



raw-loader一直等待无法继续的问题 ,是啥原因呢，我也遇到了。终止多次后，还是卡在这不动，一个小时了。蛋疼
