### ISSUE TITLE
Git问题请教

### ISSUE THREAD

**Issue by daiing** [PanJiaChen/vue-element-admin#326]
我这边已经用3.0版开发自公司项目了，群主这边项目更新，有没有办法再和我自己的git仓库合并？

**Comment by chunge0328** [comment]
如果使用这个项目，直接合并到你的分支即可

**Comment by daiing** [comment]
我已经放到我自己的git仓库去了，重新建了个项目

**Comment by PanJiaChen** [comment]
本项目区别于框架级别项目，每次同步到自己的公司项目中，可能会造成很多不稳定的问题。
建议基于一个版本之后手动维护更为的靠谱。可以看一下每一次的 [releases](https://github.com/PanJiaChen/vue-element-admin/releases)
