### ISSUE TITLE
import Layout from '@/layout'   引发页面空白的一个玄学问题？希望帮忙解答

### ISSUE THREAD

**Issue by xianzhiyun** [PanJiaChen/vue-element-admin#3262]
## Bug report（问题描述）

页面： srv/App.vue
当前项目就可以复现，只要在src/App.vue 中import Layout from '@/layout' 添加折行代码就会出现整个页面空白，对于小白不知道如何解释这一个问题，即使没有使用，如果放在其他页面不会出现这个问题

#### Screenshot or Gif（截图或动态图）
页面空白

#### Link to minimal reproduction（最小可在线还原demo）

当前项目就可以复现，只要在src/App.vue 中import Layout from '@/layout' 添加折行代码就会出现整个页面空白，对于小白不知道如何解释这一个问题，即使没有使用，如果放在其他页面不会出现这个问题

**Comment by PanJiaChen** [comment]
没太理解你的问题是什么，能提供具体的复现问题的代码么？
