### ISSUE TITLE
import Layout from '@/layout'  导致空白页面，这可能和import原理或webpack有关系，希望帮忙解释一下这种现象原因？

### ISSUE THREAD

**Issue by xianzhiyun** [PanJiaChen/vue-element-admin#3265]
## Bug report（问题描述）

有这种场景需要，当我在src/App.vue中添加 import Layout from '@/layout' 一行代码后，页面空白。

无从解释当前出现这种的情况的原因？希望大佬提供方向解释一下？

![image](https://user-images.githubusercontent.com/23547626/84983413-4d04d200-b16b-11ea-8143-d53e4179b4aa.png)

#### Steps to reproduce（问题复现步骤）

```
<template>
  <div id="app">
    <router-view />
  </div>
</template>

<script>
// 把这行代码注释掉就可以页面就不会出现空白，不知道为什么添加这一行代码就出现问题了
import Layout from '@/layout'  
export default {
  name: 'App'
}
</script>
```

#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/23547626/84983381-3cecf280-b16b-11ea-8f2a-ec5d7d4f9c66.png)

#### Link to minimal reproduction（最小可在线还原demo）
https://github.com/xianzhiyun/vue-admin-template/blob/495798ef3cc1e459a76dccdacec25c9108c788cb/src/App.vue#L13-L12

#### Other relevant information（格外信息）
- Your OS: window
- Node.js version:  v12.15.0
- vue-element-admin version:  最新

**Comment by PanJiaChen** [comment]
Layout 里面还有一个 router-view，所有会导致你路由对不上了。
你业务场景是什么？为什么要在`src/App.vue`里面做操作？layout已经默认挂载到页面了，你还想做什么操作？

**Comment by xianzhiyun** [comment]
```
<template>
  <div id="main-app">
    <!-- 这样主应用和子应用路由内容保持运来层级关系 -->
    <!-- 主应用应用路由走的还是这个router-view -->
    <router-view v-if="$route.matched.length" />
    <!-- 使用qiankun 微前端走下面layout, 挂载节点 放在layout中 -->
    <layout v-else />
  </div>
</template>

<script>
import Layout from '@/layout'
export default {
  name: 'App',
  components: {
    Layout
  },

![image](https://user-images.githubusercontent.com/23547626/85026905-db994380-b1ab-11ea-8d23-dee46218430c.png)

```

**Comment by xianzhiyun** [comment]
小哥哥有没有好的建议，或者参考案例

**Comment by xianzhiyun** [comment]
引入的时候通过异步组件引入实现
```
<template>
  <div id="main-app">
    <!-- 这样主应用和子应用路由内容保持运来层级关系 -->
    <!-- 主应用应用路由走的还是这个router-view -->
    <router-view v-if="$route.matched.length" />
    <!-- 使用qiankun 微前端走下面layout, 挂载节点 放在layout中 -->
    <layout v-else />
  </div>
</template>

<script>
export default {
  name: 'App',
  components: {
    Layout: () => import('@/layout')   
  },
```
