### ISSUE TITLE
项目拉下来运行起来，直接报错

### ISSUE THREAD

**Issue by wurainren** [PanJiaChen/vue-element-admin#3269]
#### Steps to reproduce（问题复现步骤）
Failed to compile.

./src/views/components-demo/avatar-upload.vue
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: ENOENT: no such file or directory, open 'D:\font\vue-element-admin\src\views\components-demo\avatar-upload.vue'

#### Other relevant information（格外信息）
- Your OS: windows
- Node.js version: 
- vue-element-admin version: master

**Comment by PanJiaChen** [comment]
提示很明确了，你确定下载了完成代码？或者自己没误删除过什么?
