### ISSUE TITLE
[bug] sidebar 

### ISSUE THREAD

**Issue by PanJiaChen** [PanJiaChen/vue-element-admin#327]
左侧菜单栏。如果一级菜单下，只有一个二级菜单，二级菜单下不管是否有三级菜单，目前只会显示一个一级菜单

**Comment by AndsteLyc** [comment]
左侧菜单在收起时。如果一级菜单下自由一个二级菜单，一级菜单是空的 有些问题。

![image](http://data.andste.cc/developers/github/images/QQ20180103-120343.png)

**Comment by PanJiaChen** [comment]
@AndsteLyc https://github.com/PanJiaChen/vue-element-admin/commit/9ba2648689d6b9ce78550667ea200cdeb387d2cb
已修复
