### ISSUE TITLE
@vue/cli 4.x build:prod出现'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by TyCoding** [PanJiaChen/vue-element-admin#3271]
本地环境：@vue/cli 4.4.4、node v14.4.0、wepack@4.43.0、MacOS 10.15
使用命名：`npm run build:prod` 项目，部署在Nginx上，访问控制台出现如下错误：

```
ncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
```

项目并未做任何改动，直接clone下build的，请问这是什么原因啊？在dev环境下没有问题

**Comment by TyCoding** [comment]
找到了解决办法，在不改动package.json中版本的情况下：
仅在vue.config.js中添加如下代码：

```js
 config.module
      .rule('js')
      .test(/\.js$/)
      .include.add(resolve('src')).add(resolve('test'))
      .end()
      .use('babel-loader')
      .loader('babel-loader')
      .end()
```

具体原因有知道的大佬可以在下面解答一下

**Comment by shskyc** [comment]
你的解决方法有效，感谢

**Comment by moons7** [comment]
查了下资料，原因可能是最近作者添加了module.exports的语法与import的冲突 。。
临时修改babel.confige.js如下可以解决，但具体原因还是让大佬分析

`module.exports = {
  presets: [
    '@vue/app'
  ],
  sourceType: 'unambiguous'
}
`

**Comment by PanJiaChen** [comment]
https://github.com/vuejs/vue-cli/pull/4797

@moons7 正解

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/ae2aa61880ff2bb1edde0059d87eddebdba18f3c

**Comment by zboboan** [comment]
> 
> 
> 找到了解决办法，在不改动package.json中版本的情况下：
> 仅在vue.config.js中添加如下代码：
> 
> ```js
>  config.module
>       .rule('js')
>       .test(/\.js$/)
>       .include.add(resolve('src')).add(resolve('test'))
>       .end()
>       .use('babel-loader')
>       .loader('babel-loader')
>       .end()
> ```
> 
> 具体原因有知道的大佬可以在下面解答一下

非常感谢

**Comment by DWsande** [comment]
> 找到了解决办法，在不改动package.json中版本的情况下：
> 仅在vue.config.js中添加如下代码：
> 
> ```js
>  config.module
>       .rule('js')
>       .test(/\.js$/)
>       .include.add(resolve('src')).add(resolve('test'))
>       .end()
>       .use('babel-loader')
>       .loader('babel-loader')
>       .end()
> ```
> 
> 具体原因有知道的大佬可以在下面解答一下

非常感谢
