### ISSUE TITLE
刚抄邮件的代码更新了vue-cli@4,mock就出错了

### ISSUE THREAD

**Issue by LanceLoveJava** [PanJiaChen/vue-element-admin#3274]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by LanceLoveJava** [comment]
![2020-06-22_101144](https://user-images.githubusercontent.com/36347513/85242182-dddff400-b470-11ea-883a-c165d4073ce1.png)
我尝试过重新安装core-js,问题依然存在.
对于前端这块webpack不是太熟悉,求教了

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/d3bd933a8e314e5e51d48125dbcda9e3df8ee673

这个改动有同步过么？

**Comment by laudukang** [comment]
+1

![image](https://user-images.githubusercontent.com/6259376/85243956-ceaf7500-b475-11ea-9260-86f97701e07e.png)

**Comment by LanceLoveJava** [comment]
谢谢,原因是我mock代码和新版本没同步
之前是import形式导入现在,改成require就不报错了
