### ISSUE TITLE
关于Vue3重构

### ISSUE THREAD

**Issue by vanoneang** [PanJiaChen/vue-element-admin#3275]
## Question（提问）

@PanJiaChen 请问一下，element-ui看起来升级Vue3希望渺茫，作者是准备自己fork重构吗？

**Comment by PanJiaChen** [comment]
3.0大部分是向下兼容的，ui库会需要做一些兼容的东西，用户侧基本是无感知的。其实成本还好。
其次，社区总是会有新的东西来替代那些不再更新或者维护的东西，所有总会有替代方案的。

**Comment by vanoneang** [comment]
是的，主要是入口的 `vue.prototype` 需要处理下，其他的 `option API` 都是兼容的。
