### ISSUE TITLE
接口调用怎么用表单的形式提交数据

### ISSUE THREAD

**Issue by SuperZiLu** [PanJiaChen/vue-element-admin#3283]
## Question（提问）

怎么用这个模版改成用我们公司自己的接口，我现在写的登录接口参数是拼接的，但是我们后台要求用表单提交，有没有大佬拯救一下我这个初学者，代码基本上就是模版本身的代码 只是改了一些参数数值，都在截图里了，感谢。

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/30061527/85528987-2cdb8400-b63f-11ea-9de9-a4828dbc39a8.png)
![image](https://user-images.githubusercontent.com/30061527/85529098-4ed50680-b63f-11ea-8319-88a57e2daeb3.png)

![image](https://user-images.githubusercontent.com/30061527/85528788-f43baa80-b63e-11ea-83ec-8fa2ec4ebc01.png)

![image](https://user-images.githubusercontent.com/30061527/85528030-06691900-b63e-11ea-94af-68073c300a80.png)

现在用devtools调试发现是拼接的
![image](https://user-images.githubusercontent.com/30061527/85527136-2f3cde80-b63d-11ea-8f63-e0e94b36084e.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by feeldemo** [comment]
post
请求即可&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"SuperZiLu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月24日(星期三) 下午5:26
收件人:&nbsp;"PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[PanJiaChen/vue-element-admin] 接口调用怎么用表单的形式提交数据 (#3283)





 
Question（提问）
 
怎么用这个模版改成用我们公司自己的接口，我现在写的登录接口参数是拼接的，但是我们后台要求用表单提交，有没有大佬拯救一下我这个初学者，代码基本上就是模版本身的代码 只是改了一些参数数值，都在截图里了，感谢。
 
Screenshot or Gif（截图或动态图）
 

 
 

 

 
现在用devtools调试发现是拼接的
 
 
Other relevant information（格外信息）
  
Your OS:
 
Node.js version:
 
vue-element-admin version:

**Comment by SuperZiLu** [comment]
我第三个截图那里就是设置的post哎。

**Comment by feeldemo** [comment]
看不到图片






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SuperZiLu"<notifications@github.com&gt;; 
发送时间: 2020年6月24日(星期三) 下午5:37
收件人: "PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com&gt;; 
抄送: "FeelDemo"<1398361000@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [PanJiaChen/vue-element-admin] 接口调用怎么用表单的形式提交数据 (#3283)





 
我第三个截图那里就是设置的post哎。

**Comment by SuperZiLu** [comment]
大佬帮帮忙等一下 我都能看到

**Comment by feeldemo** [comment]
params 改为data




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SuperZiLu"<notifications@github.com&gt;; 
发送时间: 2020年6月24日(星期三) 下午5:37
收件人: "PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com&gt;; 
抄送: "FeelDemo"<1398361000@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [PanJiaChen/vue-element-admin] 接口调用怎么用表单的形式提交数据 (#3283)





 
我第三个截图那里就是设置的post哎。

**Comment by SuperZiLu** [comment]
![image](https://user-images.githubusercontent.com/30061527/85532007-e4719580-b641-11ea-8e6e-a1e7410a6d7c.png)
改成data之后就变成options了 这个我之前瞎试过 上面是我们后台的截图

**Comment by feeldemo** [comment]
params 改成data




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SuperZiLu"<notifications@github.com&gt;; 
发送时间: 2020年6月24日(星期三) 下午5:39
收件人: "PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com&gt;; 
抄送: "FeelDemo"<1398361000@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [PanJiaChen/vue-element-admin] 接口调用怎么用表单的形式提交数据 (#3283)





 
大佬帮帮忙等一下 我都能看到

**Comment by feeldemo** [comment]
13968361000&nbsp; qq




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SuperZiLu"<notifications@github.com&gt;; 
发送时间: 2020年6月24日(星期三) 下午5:37
收件人: "PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com&gt;; 
抄送: "FeelDemo"<1398361000@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [PanJiaChen/vue-element-admin] 接口调用怎么用表单的形式提交数据 (#3283)





 
我第三个截图那里就是设置的post哎。

**Comment by SuperZiLu** [comment]
qq收不到 你加我吧 845691482

**Comment by feeldemo** [comment]
下班了&nbsp; 你自己百度一下把 登陆都不会写？





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SuperZiLu"<notifications@github.com&gt;; 
发送时间: 2020年6月24日(星期三) 下午5:42
收件人: "PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com&gt;; 
抄送: "FeelDemo"<1398361000@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [PanJiaChen/vue-element-admin] 接口调用怎么用表单的形式提交数据 (#3283)





 

 改成data之后就变成options了 这个我之前瞎试过 上面是我们后台的截图

**Comment by SuperZiLu** [comment]
好吧 多谢了 我自己再研究一下吧

**Comment by SuperZiLu** [comment]
自己摸索出来了 感谢提点。
