### ISSUE TITLE
添加vue-cli-plugin-electron-builder插件后路由跳转到404

### ISSUE THREAD

**Issue by haliuhei** [PanJiaChen/vue-element-admin#3291]
## 左侧导航（Sidebar）点击就跳转到404页面
基于作者提供的electron项目已经停止维护...
1.初始化作者项目后（未安装electron build插件时），dev浏览器运行没有问题,，项目可正常运行了（vue-element-admin最新版本）。

2.然后通过vue ui 页面添加了vue-cli-plugin-electron-builder（2.0.0-rc.2）版本，
此时运行浏览器dev和 electron:serve可以正常跳转，但是在页面上无法引入electron的一些api，
举例：
在guide页面添加
`import { ipcRenderer } from 'electron'`
点击左侧guide导航的时候会提示： **__dirname is not defined**

3.根据[vue-cli-plugin-electron-builder](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html)文档
给vue.config.js添加了以下代码（其他没有改动，安装electron后多了一个background.js，默认配置）：
```
module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true
    }
  }
}
```
此时浏览器运行提示： **require is not defined**(这个不重要，不需要浏览器运行的环境)
electron运行：会正常打开登录页面，点击登陆后Dashboard页面的图表也显示正常，但是点击左侧导航，如guide、documentation等所有导航时会跳转到404页面（除了左侧最后那个外链），也没有报错信息

另外正常创建一个vue-router的项目，然后通过vue ui添加的electron build在修改vue.config.js后调用官方api和是没有问题的。
因此不清楚这块是不是还需要修改下什么配置的东西。请求帮助。

**Comment by haliuhei** [comment]
发现设置
```
 electronBuilder: {
      nodeIntegration: true
    }
```
后，侧边栏的跳转链接变了，之前是

```
<a href="#/dashboard" class="router-link-exact-active router-link-active">...
```
添加后herf的值变成，成为windows下盘符路径文件了。
```
<a href="#/F:\documentation" 
```

**Comment by cnkoala** [comment]
在`vue.config.js`中无需添加代码，如果你是用`vue-cli-plugin-electron-builder`作为插件构建的electron的话，可以直接运行。

需要注意的是，在原`vue-element-admin`中，使用的是`js-cookie`作为本地化存储的方法，这个在electron中不适用，可以替换为`localStorage`或`sessionStorage`。

参见[这里](https://github.com/PanJiaChen/electron-vue-admin/issues/68)

**Comment by haliuhei** [comment]
> 在`vue.config.js`中无需添加代码，如果你是用`vue-cli-plugin-electron-builder`作为插件构建的electron的话，可以直接运行。
> 
> 需要注意的是，在原`vue-element-admin`中，使用的是`js-cookie`作为本地化存储的方法，这个在electron中不适用，可以替换为`localStorage`或`sessionStorage`。
> 
> 参见[这里](https://github.com/PanJiaChen/electron-vue-admin/issues/68)

已经放弃这个模板，自己写了。谢谢
