### ISSUE TITLE
pageSizes修改页面大小的数组不生效

### ISSUE THREAD

**Issue by pronull** [PanJiaChen/vue-element-admin#3299]
## Bug report（问题描述）
Pagination.vue 里，调用<el-pagination>里，:page-sizes=page.sizes缺失，没传进去

#### Other relevant information（格外信息）
- Your OS: windows
- Node.js version: 
- vue-element-admin version: vue-element-admin-web 2.5.0

**Comment by dingangang** [comment]
有个截图可以看看么？描述太不清楚了

**Comment by pronull** [comment]
我看了主线分支没问题了。我这代码看的是有crud封装的那个
