### ISSUE TITLE
图标的颜色怎么修改呀

### ISSUE THREAD

**Issue by 540240126** [PanJiaChen/vue-element-admin#330]

**Comment by 540240126** [comment]
你好，是这样的，我把代码拷贝到我的项目里，图标是可以显示的，但是颜色却不能通过color去设置，请问是有什么要注意的地方吗?

**Comment by PanJiaChen** [comment]
svg-icon 默认会读取其父级的color `fill: currentColor;`

你可以改变父级的color或者直接改变fill的颜色即可。

**Comment by 540240126** [comment]
大佬我就是这样做的, 但是颜色却没有改变

**Comment by 540240126** [comment]
更奇怪的是，我直接修改fill的颜色也没作用

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/33655744-e72d8eee-daae-11e7-9bb4-830204cc7cd0.png)
![image](https://user-images.githubusercontent.com/8121621/33655756-ee6a1524-daae-11e7-8bc9-b9c88ecaff82.png)

实测可行，请确保没有样式覆盖问题。

**Comment by 540240126** [comment]
大佬我发现了，从你这项目拷贝过去的svg就可以改颜色，但是我从iconfont下载的svg就不行,

**Comment by PanJiaChen** [comment]
我项目里所有的icon都是从iconfont上面下载的。。。

**Comment by 540240126** [comment]
刚刚打开看了下svg的源代码，原来下载下来的path上面自带了fill属性......

**Comment by 540240126** [comment]
请问大佬有啥办法可以使下载的图标不自带fill属性吗，我下载的都有, 这样一个一个改岂不是很麻烦。。。

**Comment by PanJiaChen** [comment]
样式覆盖不就好了 设置的时候加一个 `!important`

**Comment by 540240126** [comment]
好的，多选大佬

**Comment by BusyHe** [comment]
@540240126 你是怎么弄的，我的也不行

**Comment by BusyHe** [comment]
@PanJiaChen 能举个例子吗，用!important也不行

**Comment by 540240126** [comment]
@BusyHe 有啊，写个全局的css属性 
`path {
    fill: inherit !important
}`

**Comment by BusyHe** [comment]
@540240126 万分感谢

**Comment by yuanyuanyuan** [comment]
下载http://iconfont.cn/图标的时候，要选白色，就可以 fix 这个问题，但是具体原因不明，
1. 你们可以测试对比一下，官方 github 提供的 svg 跟http://iconfont.cn/下载的默认下载的图标是有区别的，如果默认下载http://iconfont.cn/的图标，依然还是不能变色，如果你选择一个把颜色调整为白色或其他颜色，就可以看到变色效果了，根本不是 css fill 的问题。
2. 我对比了2个 svg 的差别，http://iconfont.cn/重新下载的会多了 fill 属性，而官网 github 自带的是没有的，可能是这里被影响了变色效果。

**Comment by PanJiaChen** [comment]
其实就是楼上所说的fill的问题，最简单全局加一个`path { fill: inherit !important }`。
之后我用 `svgo`来格式化一下`svg`吧。

**Comment by PanJiaChen** [comment]
测试了一下，iconfont网站多色使用的是`fill`，所以也不能一概的将`fill`去除。所以暂时还是需要用户手动判断这个svg是否需要`fill`属性。

**Comment by 540240126** [comment]
是的，其实我那个方法遇到多色是会有问题的，多色还是要自己去做处理

**Comment by ccmanito** [comment]
大小调整为啥不成功呢   有大佬知道吗

**Comment by PanJiaChen** [comment]
@ccmanito 改 `font-size` 不就好了。

**Comment by Dreamwht** [comment]
你好，请问一下，字体图标添加字体阴影不生效怎么办

**Comment by zhanghuaxy** [comment]
你好，请问一下，我从iconfont下载的图标，把自带的fill属性去掉，图标还是不能显示，是不是path里面的问题？

**Comment by Renekton1** [comment]
今天也遇到这个问题，详细看了一下作者的文档 [图标](https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/icon.html#%E7%94%9F%E6%88%90%E5%9B%BE%E6%A0%87%E5%BA%93%E4%BB%A3%E7%A0%81) 下面的那个gif显示的很明显，先将需要的icon 添加入库，然后在库中添加进一个自定义的项目中，去项目中选择Symbol，点击下载就没问题了

**Comment by BestMafen** [comment]
我在iconfont下载的icon，设置到左侧导航的图标时，总是比模版中icon的看起来要小一些，我看模版中的icon预览的时候左右两边都没有多余的空白，我下载的在预览的时候左右两边都有空白，是这个原因吗？要怎么解决呢？以下是svg的内容：
<svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg"
     width="128" height="128">
  <path
    d="M512 0C335.264 0 192 143.264 192 320c0 320 320 704 320 704s320-384 320-704C832 143.264 688.736 0 512 0zM512 512c-106.048 0-192-85.952-192-192s85.952-192 192-192 192 85.952 192 192S618.048 512 512 512z"
  />
</svg>

**Comment by BestMafen** [comment]
```
<svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg"
     width="128" height="128">
  <path
    d="M512 0C335.264 0 192 143.264 192 320c0 320 320 704 320 704s320-384 320-704C832 143.264 688.736 0 512 0zM512 512c-106.048 0-192-85.952-192-192s85.952-192 192-192 192 85.952 192 192S618.048 512 512 512z"
  />
</svg>
```

**Comment by baojiawei** [comment]
> 我在iconfont下载的icon，设置到左侧导航的图标时，总是比模版中icon的看起来要小一些，我看模版中的icon预览的时候左右两边都没有多余的空白，我下载的在预览的时候左右两边都有空白，是这个原因吗？要怎么解决呢？以下是svg的内容：

解决了吗，这个问题

**Comment by fewbadboy** [comment]
我当时遇到的我这上面回答了我的处理步骤，都是按照大佬的文档自己走了一遍，感觉没啥问题的吧。主要是你这在iconfont里面咋下载，没发现图标大了小了的问题

Thanks &amp; Best Regards&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp;Aj_Renekton


&nbsp;

**Comment by ppzxc** [comment]
为什么我需要导入 才能用

**Comment by JasonLamv-t** [comment]
下载的时候把颜色代码删除，下载下来的svg有的是没有fill字段

**Comment by Jenssic** [comment]
我使用了@yuanyuanyuan给的建议从http://iconfont.cn/ 下载默认图标是可以通过color改变图标颜色(没有fill属性)，但发现其中也有不可以通过color改变图标颜色(有fill属性)。
然后我猜想可能和上传图片是选项有关，发现有两个选项一个是"去除颜色并提交“一个是“保留颜色并提交”。选中”去除颜色并提交选项并提交即可。这里还需要注意的是绘制icon软件要用AI。这里是网上查到的为什么要用AI的原因https://www.urcloud.co/archives/94/
最后实践是可以的。

**Comment by qq823626715** [comment]
> 
> 
> > 我在iconfont下载的icon，设置到左侧导航的图标时，总是比模版中icon的看起来要小一些，我看模版中的icon预览的时候左右两边都没有多余的空白，我下载的在预览的时候左右两边都有空白，是这个原因吗？要怎么解决呢？以下是svg的内容：
> 
> 解决了吗，这个问题

图标可以编辑，下载之前编辑放大，不留空白就好

**Comment by walirt** [comment]
@PanJiaChen 请问下多色的需要怎么处理 页面上的fill属性都被删除了 显示是全黑的

**Comment by hu-qi** [comment]
![image](https://user-images.githubusercontent.com/17986122/94388213-ec7c2c80-017e-11eb-92e1-690a2f8193bd.png)

尴尬，各位大佬这个白色背景怎么去掉？

**Comment by hu-qi** [comment]
> ![image](https://user-images.githubusercontent.com/17986122/94388213-ec7c2c80-017e-11eb-92e1-690a2f8193bd.png)
> 
> 尴尬，各位大佬这个白色背景怎么去掉？

换了个svg就行了
![image](https://user-images.githubusercontent.com/17986122/94388650-43cecc80-0180-11eb-944a-3ffd49c7c4c2.png)

**Comment by striving0** [comment]
icon颜色不可以修改的看看配置文件的路径有没有合适

**Comment by heiseyoumo334** [comment]
把svg文件里面的fill去掉 然后选择白色的就可以了

**Comment by jiefangen** [comment]
删除svg文件里的fill属性可以解决，亲测可用

**Comment by Szc219** [comment]
实测有效：
1.删除下载的文件 自带的 fill属性
2.子元素（就是这个svg）设置  fill:颜色 ！important
例如：
.Father{
  color: red;
}
.github-class{
  margin: 0 10px;
  /* 删除掉这个文件fill属性。一般情况下这样是没问题的，如果设置不上把下边这行代码设置为行内样式 */
  fill: aquamarine !important;
}

**Comment by SpongeBob-0513** [comment]
> 我在iconfont下载的icon，设置到左侧导航的图标时，总是比模版中icon的看起来要小一些，我看模版中的icon预览的时候左右两边都没有多余的空白，我下载的在预览的时候左右两边都有空白，是这个原因吗？要怎么解决呢？以下是svg的内容：

替换其他没有空白的图标，我是这样解决的，强迫症大小不统一完全受不了
