### ISSUE TITLE
Markdown components can not preview html content

### ISSUE THREAD

**Issue by geekxingyun** [PanJiaChen/vue-element-admin#3308]
#### Steps to reproduce（问题复现步骤）
1. npm run dev
2. open the catalog on components
3. check markdown page
4. Markdown Mode: when you click preview and you will find can not preview the content.

#### Other relevant information（格外信息）
- Your OS: Mac OSX
- Node.js version:v13.12.0
- vue-element-admin version:4.4.0

could you check the issue when you have free time? thanks a lot.

**Comment by CoderCharm** [comment]
I found a PR to fix the bug, see [PR](https://github.com/PanJiaChen/vue-element-admin/pull/3292)  but the master branch is not merged at present。

**Comment by geekxingyun** [comment]
> I found a PR to fix the bug, see [PR](https://github.com/PanJiaChen/vue-element-admin/pull/3292) but the master branch is not merged at present。

thanks ,i have fixed it as your follow.
