### ISSUE TITLE
最新版本3.1.1的sidebar的菜单问题

### ISSUE THREAD

**Issue by CHCP** [PanJiaChen/vue-element-admin#331]
最新版本3.1.1的sidebar问题，多个一级菜单可以同时打开。在以前的版本是打开一个菜单后，前一个菜单会自动关闭。
![image](https://user-images.githubusercontent.com/5645296/33659652-1244245a-dad5-11e7-94b8-1fed6fc2bdac.png)

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/33667505-f81846f8-dad7-11e7-89b0-00797ccb3729.png)
https://github.com/PanJiaChen/vue-element-admin/commit/c84964d77c019686b4c5cf9354b1d66cdf838ecb
可以自己再加上 `unique-opened`这个属性

**Comment by CHCP** [comment]
OK， 谢谢。
