### ISSUE TITLE
如何新窗口打开VUE页面，新页面不被包裹在侧边栏和顶栏里。

### ISSUE THREAD

**Issue by VivienZhai** [PanJiaChen/vue-element-admin#3318]
我使用路由跳转的方式新窗口打开Vue页面，`let routeData = this.$router.resolve({
         **： ***
       });
       window.open(routeData.href, '_blank');`  新窗口依然被包裹在外面的壳子中。如何进行解决该类问题？谢谢

**Comment by immafrady** [comment]
那个页面不要作为children被Layout包裹就好了。。
