### ISSUE TITLE
设置“全屏”双语，不起作用。

### ISSUE THREAD

**Issue by CHCP** [PanJiaChen/vue-element-admin#332]
最新3.3.1版本，设置Navbar.vue的“全屏”双语，不起作用。代码如下：
已经在en.js， zh.js设置screenfull；Navbar.vue， 第11-13行；
 <el-tooltip effect="dark" content={{generateTitle("screenfull")}} placement="bottom">
        <screenfull class="screenfull right-menu-item"></screenfull>
      </el-tooltip>

![image](https://user-images.githubusercontent.com/5645296/33688875-43cb7ae4-db31-11e7-9831-11ddc8002a77.png)

**Comment by PanJiaChen** [comment]
`:content="generateTitle('screenfull')`

**Comment by CHCP** [comment]
Good, Thanks.
