### ISSUE TITLE
使用mock-server后请求一直都是404，请教一下

### ISSUE THREAD

**Issue by lichq5** [PanJiaChen/vue-element-admin#3324]
#### Steps to reproduce（问题复现步骤）

1. vue.config.js:
devServer: {
    proxy: {
      // change xxx-api/login => mock/login
      // detail: https://cli.vuejs.org/config/#devserver-proxy
      [process.env.VUE_APP_BASE_API]: {
        target: `http://localhost:${port}/`,
        changeOrigin: true,
        pathRewrite: {
          ['^' + process.env.VUE_APP_BASE_API]: ''
        }
      }
    },
    // no proxy
    // port: port,
    // open: true,
    // overlay: {
    //   warnings: false,
    //   errors: true
    // },
    before: require('./mock/mock-server.js')
2. mock/index.js 在原有的代码下增加以下代码：
    / 返回对应请求值 针对中间件
const responseFake = (url, type, respond) => {
  return {
    url: new RegExp(`/mock${url}`),
    type: type || 'get',
    response(req, res) {
      res.json(Mock.mock(respond instanceof Function ? respond(req, res) : respond))
    }
  }
}

export default mocks.map(route => {
  return responseFake(route.url, route.type, route.response)
})
3. 在post login表单的时候出现404的问题

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/13826559/87802748-3776eb00-c884-11ea-9a4a-4fc7e5b86447.png)
network response：
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /plaza/user/login</pre>
</body>
</html>

#### Other relevant information（格外信息）
- Your OS:v13.8.0
- Node.js version:
- vue-element-admin version: 参照这个4.4.0版本的改动

**Comment by lichq5** [comment]
已经解决，是mock的路径问题。

**Comment by edwardraymondhe** [comment]
> 已经解决，是mock的路径问题。

请问在network那栏你发送了两次请求嘛？（预检 & 实际请求）
