### ISSUE TITLE
建议增加 一键关闭所有顶部标签的按钮

### ISSUE THREAD

**Issue by inklake** [PanJiaChen/vue-element-admin#333]
目前顶部标签开多了 需要一个一个点击关闭。  我们小项目自行增加了这个功能  但是不太好看。 建议原版考虑增加  十分感谢

**Comment by PanJiaChen** [comment]
> 每次升级新版以后， 都自行增加一建关闭的功能。 有点反复。风格也不太一致。
不太理解这里想表达什么？

**Comment by inklake** [comment]
抱歉  内容已重新编辑

**Comment by PanJiaChen** [comment]
考虑加一个右键按钮 来选择关闭所有tag的功能。

**Comment by inklake** [comment]
赞一下👍

**Comment by anvi233** [comment]
感觉最好是有按钮可以控制tap是否显示比较好，有的人觉得不需要这个，用的不习惯

**Comment by PanJiaChen** [comment]
@anvi233 没有很理解，是控制整个 `tags-view`？还是指什么？

**Comment by anvi233** [comment]
对，我说的是这个意思的

**Comment by PanJiaChen** [comment]
@anvi233 暂时按照 [文档](https://panjiachen.github.io/vue-element-admin-site/#/tags-view?id=%e7%a7%bb%e9%99%a4) 的方式移除吧，之后考虑做成配置的形式。

**Comment by anvi233** [comment]
好的，谢谢你

**Comment by PanJiaChen** [comment]
已添加 右键操作 https://github.com/PanJiaChen/vue-element-admin/pull/343 
by @leij1ang
