### ISSUE TITLE
我开发了一个nuxt版本，作为代码的搬运工，要有作者的授权，或者开个分支我上传上去？

### ISSUE THREAD

**Issue by euler-king** [PanJiaChen/vue-element-admin#3338]
## Feature request（新功能建议）

我开发了一个nuxt版本，作为代码的搬运工，要有作者的授权，或者开个分支我上传上去？
工程地址：https://github.com/euler-king/chick-element-admin

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/2312
可以在这里贴自己的项目。
