### ISSUE TITLE
当进入登录进入页面后，刷新页面小bug

### ISSUE THREAD

**Issue by timofun** [PanJiaChen/vue-element-admin#334]
当进入登录进入页面后，随便点击几个页面，然后点击浏览器的刷新按钮，再点返回，需要点击两次才能返回。是不是路由守卫引起的

**Comment by PanJiaChen** [comment]
所有你期待的正确表现应该是什么？

**Comment by PanJiaChen** [comment]
主要是由于该行代码导致
https://github.com/PanJiaChen/vue-element-admin/blob/44b180a7b38332b832887bc6696484a5ae5d924a/src/permission.js#L29

暂时没有好的解决方案

**Comment by PanJiaChen** [comment]
@timofun 已修复 https://github.com/PanJiaChen/vue-element-admin/commit/a9d2978c31325d72b8f25ede671b474faf07d3cd
