### ISSUE TITLE
table内编辑问题

### ISSUE THREAD

**Issue by lysk** [PanJiaChen/vue-element-admin#335]
编辑一行的时候，编辑之后，但不想保存，怎么回到原先的值呢

**Comment by anvi233** [comment]
遇到同样的问题
+1

**Comment by PanJiaChen** [comment]
我来加一下这个功能吧

**Comment by PanJiaChen** [comment]
已添加 https://github.com/PanJiaChen/vue-element-admin/commit/ebc2ac08b716804cd6342e7155472337f977fd4a
@lysk @anvi233
