### ISSUE TITLE
生产环境构建后，如何去掉谷歌分析代码？

### ISSUE THREAD

**Issue by upcwangying** [PanJiaChen/vue-element-admin#3355]
## Bug report（问题描述）

生产环境构建后，如何去掉谷歌分析代码？

#### Screenshot or Gif（截图或动态图）

![QQ截图20200803104307](https://user-images.githubusercontent.com/19725091/89141097-27deee00-d576-11ea-8d6f-6b088d20a489.png)

#### Other relevant information（格外信息）
- Your OS: win10
- Node.js version:  v10.18.1
- vue-element-admin version:4.4.0

**Comment by PanJiaChen** [comment]
你用的什么分支代码？理论上不会带ga统计的

**Comment by upcwangying** [comment]
> 你用的什么分支代码？理论上不会带ga统计的

我下载的是release列表里的代码！

**Comment by PanJiaChen** [comment]
哪个版本？

**Comment by upcwangying** [comment]
> 哪个版本？

4.4.0

**Comment by PanJiaChen** [comment]
我看了下源码没有添加任何谷歌分析的东西

**Comment by upcwangying** [comment]
> 我看了下源码没有添加任何谷歌分析的东西

我全局搜索了一下，也确实没有，但是打包出来就会有

**Comment by upcwangying** [comment]
<img width="927" alt="截屏2020-08-04 13 27 46" src="https://user-images.githubusercontent.com/19725091/89256350-7ebbf480-d656-11ea-96d6-89fa94549e9a.png">
<img width="1500" alt="截屏2020-08-04 13 28 49" src="https://user-images.githubusercontent.com/19725091/89256355-8085b800-d656-11ea-8e29-b33fc64e5e1e.png">

**Comment by PanJiaChen** [comment]
这个 gtag 账号都不是本项目的，确定不是什么浏览器或者什么插件注入的么？

**Comment by upcwangying** [comment]
> 这个 gtag 账号都不是本项目的，确定不是什么浏览器或者什么插件注入的么？

确实是Microsoft Edge浏览器注入的
