### ISSUE TITLE
后台返回路由问题

### ISSUE THREAD

**Issue by nycgym** [PanJiaChen/vue-element-admin#336]
潘神，我现在路由是后台返回的，这样一来就不好判断当前访问的路径到底存不存在，之前写死的匹配不到的路径都跳404了，现在我这种情况也不好判断访问路径去跳404，您有什么好的解决办法吗？

**Comment by PanJiaChen** [comment]
不是很理解的问题，路由存前端和后端有什么区别么？不是都会通过 `addRoutes` 来添加，只有最后再添加 `{ path: '*', redirect: '/404' }` 就不会有什么问题。

**Comment by nycgym** [comment]
我明白了，谢谢潘神
