### ISSUE TITLE
大神，请问，一个项目有个前台和后台都是用您这个做的，用后台登录后再访问前台页面 还是保存的后台的token

### ISSUE THREAD

**Issue by gystone** [PanJiaChen/vue-element-admin#3361]
大神，问一个小白问题，一个项目有个前台和后台都是用您这个做的，用后台登录后再访问前台页面 还是保存的后台的token，但是请求接口的token是不正确的，总是提示请重新登录。我是刚接触前端的新手，我感觉应该是cookies 的key冲突了，这块我应该是怎么修改会解决这个bug呢？我想的是每个端登录都有自己端的key，但是这块我看不明白您这块的代码，我应该怎么改才好。感谢了。

**Comment by geekxingyun** [comment]
修改下 src/utils/request.js 里面有一个X-Token 是配置每次请求发送的token字段,非要前后端混在一起的话，或许可以尝试发送不同的token字段，比如前端发送X-Token,后端发送H-Token
