### ISSUE TITLE
提几点建议和问题

### ISSUE THREAD

**Issue by daiing** [PanJiaChen/vue-element-admin#338]
1、首页的todo list 下面的all和 x items left 重叠了
2、现在首页已经加了灰色背景，挺赞的，但是内功能页都没有加背景，能否在框个div，外面包括一层灰底色
3、现在的网站布局，好像网站的logo标题没地方放啊？能否让最上面一栏横跨整个网页，左边可以放logo
4、现在表格会把网页撑得很长，拖到表格底下，表头就看不到了，能否让表格自适应网页高度宽度，表格内上下左右滚动，这样整个网页就不需要滚动，一眼看到全部内容了

**Comment by PanJiaChen** [comment]
1. 3.1.0 版本之后应该没有你所说的重叠问题了。
2,3 两个ui需求暂定吧，之后借鉴一下其它成熟的ui框架吧。
4. 这个需求 `element-ui`的 table 固定表头就满足你的需求吧，若还不满足 可以向它提issue ，本项目应该不会做该方面的处理。

**Comment by daiing** [comment]
多谢群主

**Comment by PanJiaChen** [comment]
关注这个 #266 吧
