### ISSUE TITLE
需求：在界面右上角增加通知，显示有多少条未读消息或待处理消息，浮动红点显示数量

### ISSUE THREAD

**Issue by imgoby** [PanJiaChen/vue-element-admin#3382]
需求：在界面右上角增加通知，显示有多少条未读消息或待处理消息，浮动红点显示数量

**Comment by hatch1994** [comment]
呃....这个功能很简单，自行修改吧。人家是开源，不是义务帮你们改需求； 不要拿来主义😩 代码都给你了，还想咋样

**Comment by imgoby** [comment]
我自己会加呀。但看到其他框架清一色功能都比较完善。对目前这个只是提一个小小的点子。
好吧。我自己加。
