### ISSUE TITLE
后端返回400 拿不到返回的response信息，request.js里面直接跳到error，求问怎么解决

### ISSUE THREAD

**Issue by AllenZhang34** [PanJiaChen/vue-element-admin#3386]
我想拿后端返回给我的错误信息，然后在前端显示出来，后端返回是400，但是我拿不到response
直接跳到error了，返回的也不是后端的信息，求问怎么解决，谢谢🙏

![截屏2020-08-16 下午9 49 51](https://user-images.githubusercontent.com/24819665/90335927-e127d400-e00a-11ea-83b5-02eac1e32f16.png)

**Comment by KeJunMao** [comment]
把 `response interceptor` 注释掉

**Comment by AllenZhang34** [comment]
> 把 `response interceptor` 注释掉

不好意思，我没太看明白，请问下具体是注释哪一部分？
麻烦您再稍微解答一下，谢谢了🙏

**Comment by KeJunMao** [comment]
axios 的拦截器，如果你想要在 `response.status === 400` 的时候给用户个提示，也可以在拦截器里改，具体可以看看[文档](https://github.com/axios/axios#interceptors)

**Comment by AllenZhang34** [comment]
> axios 的拦截器，如果你想要在 `response.status === 400` 的时候给用户个提示，也可以在拦截器里改，具体可以看看[文档](https://github.com/axios/axios#interceptors)

非常感谢 已经解决
