### ISSUE TITLE
为什么去掉了通过permession来管理而是换为了 role呢？

### ISSUE THREAD

**Issue by angrysnail** [PanJiaChen/vue-element-admin#3390]
原来好像是通过v-permisssion写的是资源名称如：role_update等，现在改为了通过role，如admin来进行判断是否显示这个dom.

感觉这样不太合适吧，如果我们搭配一个后台，肯定会是自定义角色，而权限这一块，相对来说是死的，现在用角色名称来进行显示与否的判断，是不是不合适？还是有更深的考虑呢？

**Comment by hatch1994** [comment]
RBAC资源控制

**Comment by passioncsu** [comment]
权限这块也不会死啊,  肯定是后端传过来的权限,然后进行操作.  不同角色拥有不同权限, 然后给不同的账号赋予不同的角色, 这样两个维度基本能覆盖所有自定义的权限需求.   现在以角色为准没什么问题.

**Comment by angrysnail** [comment]
感觉我没说明白。
假设有一个按钮，对应一个权限，如 user_add，其是一个privilege的code
现在我们的逻辑是v-permission中写一个角色的名字如manager，而不是写user_add这个权限的code
但是在我们的后台系统里，manager的角色更大可能是维护进去的，即可以手动添加一百种角色，但是权限就是死的数量，大体对应着我们的rest接口
现在在写代码的时候，要求v-permission里写一个角色的名字，但角色的名字还没有被定义出来 或者 新添加一个角色，就要修改一下v-permission中的值，不应该吧    

想不太明白，感觉是不是作者另有深意在里面呢？

**Comment by hooray** [comment]
你的问题我大概一年多前用 vue-element-admin 的时候也发现了，后来是重构了 premission.js 才解决。如果觉得麻烦的话，可以关注下我写的一款中后台框架 [vue-automation-admin](http://eoner.gitee.io/vue-automation-admin/)，针对权限这块，应该是你想要的那种效果 [权限验证](http://eoner.gitee.io/vue-automation-admin/#/permission)

**Comment by achunCoding** [comment]
不知道解决了吗， @angrysnail 目前方案是什么 是返回权限 还是根据角色进行判断。 如果系统中角色基本不变会不会用角色判断好一点。

**Comment by angrysnail** [comment]
谢谢各位回答，你可以看看四楼的实现，都是通过标签，没毛病，估计大部分人用本项目的时候都会把这个地方调回原来的实现

**Comment by angrysnail** [comment]
gg
