### ISSUE TITLE
火狐浏览器下，左侧菜单展开超出屏幕高度后，无法滚动

### ISSUE THREAD

**Issue by cooooode** [PanJiaChen/vue-element-admin#340]
火狐浏览器版本57.0.2 (64 位)

**Comment by PanJiaChen** [comment]
请提供截图或者详细问题描述

**Comment by cooooode** [comment]
![default](https://user-images.githubusercontent.com/31137050/33863970-5843eef0-df25-11e7-9151-4dfdf4606db4.png)

火狐浏览器下，鼠标在左侧红框区域中，滚动滚轮，菜单不会动，右边内容区域会动

![default](https://user-images.githubusercontent.com/31137050/33864000-7eea871c-df25-11e7-91af-0c0a734d5fec.png)
