### ISSUE TITLE
离线环境npm i安装依赖报错

### ISSUE THREAD

**Issue by yangsenss** [PanJiaChen/vue-element-admin#3405]
公司内部服务器，使用了nexus代理的npm仓库，安装的时候出现这个错误。
检查了git的配置，没有问题。请问下这种情况怎么处理的？
下面是报错信息：
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/sohee-lee7/Squire.git
npm ERR!
npm ERR! ssh: Could not resolve hostname github.com: Temporary failure in name resolution
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

**Comment by SnowerII** [comment]
请问你解决了吗？我这边也是频频出现这种问题，环境到内网之后这个问题就不知道怎么解决了，网上的回答很多说是要配置git环境。。可是根本没用，而且我外网机从来没配置过git环境也没遇到这种问题

**Comment by yangsenss** [comment]
解决了。升级下依赖版本就好了。
1. 先执行npm i，根目录会生成一个package-lock.json的文件
2. 你在package-lock.json搜索关键字“github.com”，就会找到组件名称
3. 再根据组件名称一层一层查找，看是哪个组件引用的，然后去网上查找这个组件没有使用github.com的开发版本组件的版本。
ps: 问题的根本原因是很多开源项目依赖的组件还是开发版本，或者没有发布到npm.org去。升级版本就行。

**Comment by SnowerII** [comment]
k,gj

**Comment by SnowerII** [comment]
还是决定从外网把nodemodules传到内网了
以前写的项目用这个框架发布线上的时候，dockerfiles里面安装依赖可以用淘宝镜像，然后这个问题就解决了
现在我是想拉到内网机上面来跑本地，但是内网机好像配置淘宝镜像就报什么maxium callsize 内存溢出啥的，我觉得可能是it屏蔽了

您说的这个更改版本的话，我在npm网上看不出来他哪些版本没有依赖github组件。。我也不清楚要换啥版本

**Comment by SnowerII** [comment]
还是决定从外网把nodemodules传到内网了
以前写的项目用这个框架发布线上的时候，dockerfiles里面安装依赖可以用淘宝镜像，然后这个问题就解决了
现在我是想拉到内网机上面来跑本地，但是内网机好像配置淘宝镜像就报什么maxium callsize 内存溢出啥的，我觉得可能是it屏蔽了

您说的这个更改版本的话，我在npm网上看不出来他哪些版本没有依赖github组件。。我也不清楚要换啥版本

**Comment by SnowerII** [comment]
我直接修改package.lock文件应该是没有用的吧？
然后我看他的package.json里有的依赖（我查出来是一个tui-chart的包），在npm上已经是最新版了，然后安装出来发现package.lock里面的内容的链接就是github的。
那这样的话岂不是只能选择删除这个依赖...

**Comment by yangsenss** [comment]
@SnowerII 直接修改package-lock.json没用，每次执行npm -i 的时候会重新生成的。我碰到了一个项目当时他们也是引用了tui-editor，但是项目里根本没有使用，直接就删了。

**Comment by SnowerII** [comment]
我搜了半天，所有相关于github.com的依赖包都指向一个叫tui-editor的插件，好像是个富文本。。。。我package.json直接给删了,项目里引用了这个富文本的组件文件我也删了。
我觉得还是蛮奇怪的，为啥要用这样的富文本，就他一个是里面循环套各种辅助依赖而且都是git链接。。。

**Comment by SnowerII** [comment]
好了，解决了，就是这个东西搞得

**Comment by SnowerII** [comment]
谢谢兄弟，像这种问题太难受了，公司的大佬们也没用过这个框架

**Comment by yangsenss** [comment]
> 我搜了半天，所有相关于github.com的依赖包都指向一个叫tui-editor的插件，好像是个富文本。。。。我package.json直接给删了,项目里引用了这个富文本的组件文件我也删了。
> 我觉得还是蛮奇怪的，为啥要用这样的富文本，就他一个是里面循环套各种辅助依赖而且都是git链接。。。

因为，好多项目都是从github上面抄一个模板下来，然后就开始改改改，至于为啥要引用它，他们也不知道。。。。。。我碰到好多项目都是这个问题，他们开发人员根本就不知道那依赖咋来的，直接是抄的模板。

**Comment by etianhai** [comment]
package.json 中删掉tui-editor
src\components\MarkdownEditor\index.vue  这个文件代码也注释起来，就正常跑起来了。
![image](https://user-images.githubusercontent.com/33712660/141403614-861fe0d4-1a89-4a05-88f9-23919c4e6ad2.png)
