### ISSUE TITLE
跨域POST访问超时 Proxy error: Could not proxy request /dev-console-api/school from localhost:9528 to http://localhost:3000. See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).

### ISSUE THREAD

**Issue by SylarZing** [PanJiaChen/vue-element-admin#3408]
#### Steps to reproduce（问题复现步骤）

使用Hapi作为后端service ~ Host：localhost，Port：3000
![image](https://user-images.githubusercontent.com/11436998/91859483-16842100-ec9d-11ea-9894-0e6ef36a4725.png)

vue-element-template 通过proxy调用API
proxy: {
      '/dev-api': {
        target: 'http://localhost:3000',
        changeOrigin: true, // 配置跨域
        pathRewrite: { '^/dev-api': '/dev-console-api' }
      }
    },

访问过程中，GET可以正常获取后端数据，但如果用POST方法则会访问超时并报错：
![image](https://user-images.githubusercontent.com/11436998/91859988-aa55ed00-ec9d-11ea-8aa8-9d0ffc1db2ab.png)

Proxy error: Could not proxy request /dev-console-api/school from localhost:9528 to http://localhost:3000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).

但如果使用params传参，则可以正常操作数据

#### Other relevant information（格外信息）
- Your OS: Mac OS
- Node.js version: v14.4.0

**Comment by SylarZing** [comment]
如果直接通过body传参数的话，就会报如上的错。在服务端添加跨域设置仍然会失败。

**Comment by KuoKongQingYun** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/3020
和这个问题一样，mock-server的原因

**Comment by SylarZing** [comment]
解决方案：
https://github.com/PanJiaChen/vue-element-admin/pull/3044/files
