### ISSUE TITLE
在dialog中使用tinymce，点击tinymce的表情弹框被dialog覆盖

### ISSUE THREAD

**Issue by 418545106** [PanJiaChen/vue-element-admin#3418]
```
<el-dialog
    :title="title"
    :visible.sync="visible"
    width="50%"
    :close-on-click-modal="false"
    class="dialog-wrapper"
    append-to-body
    @close="close"
  >
<el-form-item label="内容">
            <editor
              ref="editor"
              v-model="media.resContents"
              :init="init"
            />
          </el-form-item>
</el-dialog>
```
![image](https://user-images.githubusercontent.com/29942834/92549638-51351d00-f28c-11ea-8be0-8372a89bd0b2.png)
需要关闭dialog才能出现tinymce的弹窗
![image](https://user-images.githubusercontent.com/29942834/92549664-63af5680-f28c-11ea-8e2f-b76eb9578afc.png)

**Comment by veryverylucky** [comment]
请问解决了不 同遇到

**Comment by 418545106** [comment]
最后我自己覆盖了样式
// 解决tinymce 弹窗被覆盖
.tox-tinymce-aux{
  z-index: 3000 !important;
}

**Comment by swatyb123** [comment]
谢谢，已解决
