### ISSUE TITLE
normalize.css的引入会不会有问题？

### ISSUE THREAD

**Issue by mingyec** [PanJiaChen/vue-element-admin#342]
今天在引入normalize.css的时候照抄了你在`src/App.vue`里面的写法 => `~normalize.css/normalize.css`，然后报错了，仔细一看是前面加多了一个`~`，想问大神这个是不是应该去除`~`

**Comment by PanJiaChen** [comment]
并不是 。是 `sass-loader` 的特性
https://github.com/webpack-contrib/sass-loader#imports

**Comment by mingyec** [comment]
明白
