### ISSUE TITLE
echarts放在tabs分页里默认设置的百分比会变成px，调窗口后就恢复正常，这个是什么问题呢？

### ISSUE THREAD

**Issue by NBSeven** [PanJiaChen/vue-element-admin#345]
希望大大能解答一下~

**Comment by PanJiaChen** [comment]
请提供在线demo或者详细描述很截图

**Comment by NBSeven** [comment]
![1](https://user-images.githubusercontent.com/24637074/33887273-39122920-df84-11e7-93d8-5e74c6d6df57.jpg)
![2](https://user-images.githubusercontent.com/24637074/33887274-39752d22-df84-11e7-9a80-a56f11d8a2e9.jpg)
![3](https://user-images.githubusercontent.com/24637074/33887276-39b09efc-df84-11e7-90ca-665ad6d59ae3.jpg)
![4](https://user-images.githubusercontent.com/24637074/33887277-39e51df8-df84-11e7-9cdb-712e99045b36.jpg)
![5](https://user-images.githubusercontent.com/24637074/33887279-3a40b60e-df84-11e7-9388-6ca4f94786e7.jpg)

**Comment by PanJiaChen** [comment]
tab切换的时候容器width会不对，所以要等tab切换完成之后 手动resize echarts,如
```js
watch: {
    active(val) {
        this.$nextTick(() => {
          this.$refs.chart.resize();
      }
    }
}
```

**Comment by NBSeven** [comment]
thanks ~
