### ISSUE TITLE
vue-i18n引入的一个坑

### ISSUE THREAD

**Issue by gaoshijun1993** [PanJiaChen/vue-element-admin#346]
elementui中文文档中这样写:
```
Vue.use(Element, {
  i18n: (key, value) => i18n._t(key, value)
})
```
elementui英文文档中是:
```
Vue.use(Element, {
  i18n: (key, value) => i18n.t(key, value)
})
```
t前面少了一个短划线,发现如果按照第一种的写法,在可编辑表格页面点击编辑按钮就会报错....

**Comment by PanJiaChen** [comment]
所以是element文档有问题 ，和本项目有什么关系。。。

**Comment by rogerscj** [comment]
labels: 'test1 | test2 | test3 | test4'
`$tc('labels', 3)` 与 `$tc('labels', 2)` 的值相同。。。
