### ISSUE TITLE
如果有更新的话, 后续怎么好去合并新的到自己的项目中

### ISSUE THREAD

**Issue by tristan-tsl** [PanJiaChen/vue-element-admin#3489]
## Question（提问）

通过对比文件, 但是花费时间比较多

#### Steps to reproduce（问题复现步骤）
当初次集成一段时间之后

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by yangelar** [comment]
同问啊
