### ISSUE TITLE
关于动态渲染侧边栏的疑惑

### ISSUE THREAD

**Issue by HeroMeiKong** [PanJiaChen/vue-element-admin#3508]
## Question（提问）
想通过服务器返回的文章数量来显示文章，相当于动态显示文章列表里面的内容，如下图：
<img width="218" alt="WechatIMG8517" src="https://user-images.githubusercontent.com/30972348/99209432-1f958080-27fe-11eb-9bee-4d59a3b5df7d.png">
不知道有没有快捷的办法？
我想的是先去请求服务器，然后得到数据，再去构建 router，但是感觉这样不太好，各位大佬有什么方法吗？

**Comment by toesbieya** [comment]
菜单和路由分离，文章页面使用`:id`的方式去访问

但是如果没有文章时不就有问题？

**Comment by HeroMeiKong** [comment]
@toesbieya 这个的话，想的是做个添加个"暂无文章“的页面，或者不添加页面，写成这种<lists><Article></lists>，返回个默认值

**Comment by toesbieya** [comment]
@HeroMeiKong  侧边栏的数据存在[@/store/module/permission.js #route](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/store/modules/permission.js#L38)中，直接改就行

**Comment by HeroMeiKong** [comment]
@toesbieya 好的，我直接在套了个请求在 generateRoutes 里面，效果是达到了
