### ISSUE TITLE
npm run dev  failed

### ISSUE THREAD

**Issue by ertaoxu** [PanJiaChen/vue-element-admin#351]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.3.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.6.0
3 info using node@v9.3.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-element-admin@3.3.0~predev: vue-element-admin@3.3.0
6 info lifecycle vue-element-admin@3.3.0~dev: vue-element-admin@3.3.0
7 verbose lifecycle vue-element-admin@3.3.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vue-element-admin@3.3.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/arter/vue/vue-element-admin/node_modules/.bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin/
9 verbose lifecycle vue-element-admin@3.3.0~dev: CWD: /Users/arter/vue/vue-element-admin
10 silly lifecycle vue-element-admin@3.3.0~dev: Args: [ '-c', 'node build/dev-server.js' ]
11 silly lifecycle vue-element-admin@3.3.0~dev: Returned: code: 1  signal: null
12 info lifecycle vue-element-admin@3.3.0~dev: Failed to exec dev script
13 verbose stack Error: vue-element-admin@3.3.0 dev: `node build/dev-server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid vue-element-admin@3.3.0
15 verbose cwd /Users/arter/vue/vue-element-admin
16 verbose Darwin 17.2.0
17 verbose argv "/usr/local/Cellar/node/9.3.0/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v9.3.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue-element-admin@3.3.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the vue-element-admin@3.3.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by PanJiaChen** [comment]
和本项目无关bug，个人感觉重装一下node试试
