### ISSUE TITLE
tagsview里面的2个默认标签的配置

### ISSUE THREAD

**Issue by helloqingbing** [PanJiaChen/vue-element-admin#3513]
## Question（提问）

vue-element-admin 中tagsview里面的2个默认标签”Dashboard" 和 “documentation” 是在哪里配置的
<img width="443" alt="Screen Shot 2020-11-27 at 6 42 14 PM" src="https://user-images.githubusercontent.com/12151675/100440726-46966100-30e0-11eb-9ee3-29e7da623977.png">

**Comment by strivezc** [comment]
路由文件，affix属性

**Comment by helloqingbing** [comment]
great, should be my tags view issue
