### ISSUE TITLE
裤衩哥，啥时候能把elementUI 的源码介绍一下，

### ISSUE THREAD

**Issue by dawayway** [PanJiaChen/vue-element-admin#353]
裤衩哥，啥时候能把elementUI 的源码介绍一下，

**Comment by PanJiaChen** [comment]
应该不会出系列的文章，我已没有完全看过 elementUI 的源码，只是在用到的时候回去看看，它的目录结构蛮清晰的，可自行去研究。

**Comment by dawayway** [comment]
谢谢裤衩哥，能不能说说看的思路。
