### ISSUE TITLE
为什么白名单不生效？

### ISSUE THREAD

**Issue by yuqiaobinbin** [PanJiaChen/vue-element-admin#3534]
## Question（提问）

为什么白名单不生效？

设置了白名单之后，如果跳转到注册界面：“http://localhost:9528/register”

还是会重定向到 Login界面 “http://localhost:9528/register#/login?redirect=%2Fdashboard”

#### Steps to reproduce（问题复现步骤）
1. 修改permission.js, 添加’/register‘ 的白名单
2. router/index 添加对应的route, 即'/register'
3. 为route 目录添加对应的视图文件
4. 在login视图文件中添加一个导航链接，导航到 ’/register‘

请问哪里出错了？为什么配置的白名单无效呢？

#### picture（截图）

1. 
![1](https://user-images.githubusercontent.com/62179758/101239076-b7143200-371f-11eb-9a26-e218125fa78b.PNG)
2. 
![3](https://user-images.githubusercontent.com/62179758/101239085-c1363080-371f-11eb-927f-8ba73b1ab6f5.PNG)
3.
![2](https://user-images.githubusercontent.com/62179758/101239082-bc717c80-371f-11eb-84d5-d4a96789109d.PNG)
4.
![4](https://user-images.githubusercontent.com/62179758/101239087-c7c4a800-371f-11eb-9eec-03520ab73690.PNG)

**Comment by yuqiaobinbin** [comment]
路由方式的处理修改为history可跳转

**Comment by dalaocu** [comment]
> 路由方式的处理修改为history可跳转

您好，我也碰到了相同的问题，请问history怎么修改，具体改哪个文件？

谢谢。

**Comment by dalaocu** [comment]
找到了，这里把配置打开：

const createRouter = () => new Router({
  mode: 'history', // require service support
  scrollBehavior: () => ({ y: 0 }),
  routes: constantRoutes
})
