### ISSUE TITLE
大神，能不能介绍一下搭建个脚手架的步骤

### ISSUE THREAD

**Issue by daiing** [PanJiaChen/vue-element-admin#354]
等不及大神搭移动脚手架了，想用vux参考这个项目搭个基础项目，可是到处出问题，焦头烂额，前端苦手没办法啊
想请教下，怎么个搭建步骤，或者说，是否可以直接把这项目elementui去掉，换成vux就行了吗？

**Comment by PanJiaChen** [comment]
vux 建议参照它的文档来构建，没有什么捷径或者意见可以传授。

**Comment by daimingchun** [comment]
@daiing 直接换是不行的，vux 的引入不同
