### ISSUE TITLE
使用 svg-sprite-loader 并不能按需加载

### ISSUE THREAD

**Issue by anjia0532** [PanJiaChen/vue-element-admin#357]
按照 [手摸手，带你优雅的使用 icon#进一步改造](https://juejin.im/post/59bb864b5188257e7a427c09#heading-7)

使用 `svg-sprite-loader` 后，并没有按需加载svg，比如，svg目录有100个svg，页面一个没有用到，也会加到body里，并不是按照页面路由，按需加载。

同时，`npm run build --report` 看，还引入了两个依赖js库，gzip后占3K左右，原始占30多K

![snipaste20171217_142920](https://user-images.githubusercontent.com/15098916/34077153-b701edc4-e336-11e7-87d7-4d3be73ea311.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/04d9b849dde8ebad5b819fef5dd03e55f5cf37e9/src/icons/index.js#L8-L10
因为现在icon主要是侧边栏，所以途省事，全部引入了，有需求可以自行import需要的，这样就能按需了。

**Comment by anjia0532** [comment]
@PanJiaChen 感谢提醒，哈哈，对这个不太熟。后端狗一只

**Comment by wplnancy** [comment]
@PanJiaChen 我的 icon 都是来自于阿里巴巴矢量图标库的一个项目里面， 我要把所有图标都下载下来放到项目中的 icon 文件夹中吗？
