### ISSUE TITLE
为什么我直接从master拉取代码，跑起来是英文界面？把国际化注释了还是没用。

### ISSUE THREAD

**Issue by 463755120** [PanJiaChen/vue-element-admin#3572]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by wuqiang-marker** [comment]
主要是在main.js中配置吧，你是不是没引入中文的包

**Comment by 463755120** [comment]
> 主要是在main.js中配置吧，你是不是没引入中文的包
在main.js的注释中写着中文语音包默认支持，无需额外引入

**Comment by 463755120** [comment]
已找到问题。

**Comment by Guorisy** [comment]
无需引入中文包，把master分支down到本地，将main.js中enLang的引入删掉，再将文案改成中文。这样就是单语言（中文）环境了

**Comment by Guorisy** [comment]
无需引入中文包，把master分支down到本地，将main.js中enLang的引入删掉，再将文案改成中文。这样就是单语言（中文）环境了。
如果是利用i18n分支变成单语言环境太过于麻烦了，没有国际化需求的就使用master分支吧。

**Comment by Dream2Land** [comment]
> 已找到问题。

原因是什么啊

**Comment by lxge** [comment]
> 已找到问题。

原因是什么啊
