### ISSUE TITLE
为什么clone下来后，打开项目没有看到两步验证登录 qq和微信

### ISSUE THREAD

**Issue by xmtgithub123** [PanJiaChen/vue-element-admin#36]
就是登录页面后为啥没看过qq、微信登录验证的效果？

**Comment by PanJiaChen** [comment]
qq和微信 都需要授权的 很难模拟的 之后会写一篇关于这个的文章。
不过代码里面都有注释而已https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/login/socialsignin.vue
