### ISSUE TITLE
如何去除登录模块

### ISSUE THREAD

**Issue by jejass** [PanJiaChen/vue-element-admin#3602]
我现在的应用是不需要用户登录的，我尝试去修改permission.js 里的beforeEach，直接调用next(), 但是结果是url转到了我的目标url，但是页面完全空白，没有内容。

想请问以下各位大佬，如何去除 这个登录模块以及权限？

**Comment by sunpu007** [comment]
把你的router打印下就知道什么问题了

**Comment by jejass** [comment]
原来 路由 分为 固定路由 以及 根据权限动态加载的路由， 根据权限动态加载的路由 是在登录之后再去addRouter的，所以解决方案是将新增的路由增加到固定路由中，在配合permission.js中的修改，即可

**Comment by ZAIDU-Miren** [comment]
兄弟在哪个目录啊
