### ISSUE TITLE
你们这玩意已部署到 nginx （npm run build:prod) 就卡死，你们自己不知道吗？ 还有这么多 star？ 我也是服了

### ISSUE THREAD

**Issue by magicnana999** [PanJiaChen/vue-element-admin#3603]

**Comment by sunpu007** [comment]
是你的环境有问题吧，没遇到过这个问题

**Comment by ng86** [comment]
自己技术菜还喜欢瞎逼逼

**Comment by lwm98** [comment]
自己不辣鸡就说自己辣鸡，就你遇到，还解决不了。笑死个人

**Comment by lwm98** [comment]
> 自己辣鸡就说自己辣鸡，就你遇到，还解决不了。笑死个人

况且别人好心开源给你，你不想用、不会用就滚蛋呗。你贡献过一分钱吗上来就一顿bb，你以为你是谁啊

**Comment by kailong321200875** [comment]
> _No description provided._

无能狂怒，实在不行你就自己写个，别人开源又没求着你用，况且你怎么不想想会不会是自己的问题，人家那么多star自然有人家的道理。别总是抱怨

**Comment by IcedMango** [comment]
Kid, do more learning, instead of bbing here.💁

**Comment by magicnana999** [comment]
呵呵

**Comment by magicnana999** [comment]
既然开源，就得允许人家评论，评论肯定有好有坏。 受不得人家说，就别干啊。 不愿意听可以不回啊，什么时候你们受得了负面的评论了，你们就站起来了。

**Comment by lwm98** [comment]
> 既然开源，就得允许人家评论，评论肯定有好有坏。 受不得人家说，就别干啊。 不愿意听可以不回啊，什么时候你们受得了负面的评论了，你们就站起来了。

你就没有考虑过是自己的问题？ 你什么时候能站起来？ 丢人丢到家

**Comment by IcedMango** [comment]
> 既然开源，就得允许人家评论，评论肯定有好有坏。 受不得人家说，就别干啊。 不愿意听可以不回啊，什么时候你们受得了负面的评论了，你们就站起来了。

我真是看笑了，有问题就请Google找原因好吧，错误日志不拿出来，就一张嘴说这个不行那个不行，你咋这么厉害呢。
我电脑上不了网，要不你帮我看看？
自己不会用就不会用，好好学，多看教程，好吧？

**Comment by magicnana999** [comment]
呵呵。 这个项目真棒，特好，我给你们点个星星。

**Comment by magicnana999** [comment]
呵呵。 这个项目真棒，特好，我给你们点个星星。

**Comment by lwm98** [comment]
> 呵呵。 这个项目真棒，特好，我给你们点个星星。

sb。Github上的项目谁被你用到真的是倒八辈子霉

**Comment by Jucyfer** [comment]
一直以为码农人群里不会有键盘侠这种废物。

话都说不清楚也敢来开Issue。

“是什么，为什么，怎么样”，3W1H一个都没。漂亮。

上手就吠。

今天百闻不如一见！

**Comment by breederComrade** [comment]
回到问题 我本地正常 一大包上线 就会崩溃 查了issues 使用了里面的Vue.config.errorHandler 处理才行 发现是只要有undefined的报错就会出现崩溃卡死的现象！在本地是没有问题的 ！不知道是什么情况
