### ISSUE TITLE
编辑页面（跳转新的路由）

### ISSUE THREAD

**Issue by liuxingzhijian1320** [PanJiaChen/vue-element-admin#361]
complex-table的页面 编辑功能，如果编辑页面内容少可以用model来实现，但是如果内容多的话，我要跳转到update的页面去，此时在你的children的里面 是无法配置

**Comment by PanJiaChen** [comment]
不懂你的痛点是什么 再加一个路由不就好了，有什么问题么？

**Comment by liuxingzhijian1320** [comment]
弄好了，谢谢了，改造下路由就行了

**Comment by PanJiaChen** [comment]
那 close 了
