### ISSUE TITLE
询问2.08的table中的header-cell-style属性如何正确使用？

### ISSUE THREAD

**Issue by blueroseslol** [PanJiaChen/vue-element-admin#362]
本人直接在el-table标签中加了
header-cell-style="color:black;"

表头中的文字是正确变成了黑色了，但是Chrome的console中显示报错。

官方文档就写了：

header-row-style |
表头行的 style 的回调方法，也可以使用一个固定的 Object 为所有表头行设置一样的 Style。  Function({row, rowIndex})/Object

本人不太清楚如何构造一个style对象，不知道大神是否知道？

**Comment by PanJiaChen** [comment]
请提供在线demo

**Comment by blueroseslol** [comment]
https://jsfiddle.net/bluerose/srp4vgja/

能正常显示，按F12打开console显示错误：
unpkg.com/vue@2.5.11/dist/vue.js:582 [Vue warn]: Invalid prop: type check failed for prop "headerCellStyle". Expected Object, Function, got String.

found in

---> <ElTable>
       <Root>

然而我不清楚，如何构造Style对象

**Comment by PanJiaChen** [comment]
https://jsfiddle.net/srp4vgja/1/

**Comment by blueroseslol** [comment]
解决了，谢谢大神！
