### ISSUE TITLE
npm install报错128

### ISSUE THREAD

**Issue by ManHuai** [PanJiaChen/vue-element-admin#3639]
## Bug report（问题描述）
使用npm和yarn都出现128的报错，有大佬可以解决一下吗
#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/80633139/111252791-e1458c00-864c-11eb-923a-716b6afda489.png)
![image](https://user-images.githubusercontent.com/80633139/111252869-076b2c00-864d-11eb-8c04-679b910b899b.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by ncumovi** [comment]
> ## Bug report（问题描述）
> 使用npm和yarn都出现128的报错，有大佬可以解决一下吗
> 
> #### Steps to reproduce（问题复现步骤）
> #### Screenshot or Gif（截图或动态图）
> ![image](https://user-images.githubusercontent.com/80633139/111252791-e1458c00-864c-11eb-923a-716b6afda489.png)
> ![image](https://user-images.githubusercontent.com/80633139/111252869-076b2c00-864d-11eb-8c04-679b910b899b.png)
> 
> #### Link to minimal reproduction（最小可在线还原demo）
> #### Other relevant information（格外信息）
> * Your OS:
> * Node.js version:
> * vue-element-admin version:
怎么解决的呀

**Comment by ManHuai** [comment]
我是怎么装都不行，cmd跟右键的git Bash Here都不行，然后我就试了试我自己的办法，希望能帮上你
1、先打开自己本地的git安装的目录
![image](https://user-images.githubusercontent.com/80633139/111440990-d4ef2b00-8741-11eb-861f-1bbe395bdf59.png)
我的是在D盘里，然后点那个git-cmd.exe进去

2、切换到你的vue-element-admin的项目目录
运行一下 
git config --global http.sslverify "false"
和
git config --global url."https://".insteadOf git://
这两条指令

然后我的npm install就好了，如果还不行的话我还改过hosts文件，不行的话再改hosts文件，这个问题也是，我卡了好几天了，用这个方法装了两次都是可以的。

**Comment by ncumovi** [comment]
这是啥原因啊

**Comment by ManHuai** [comment]
我也是小白，这也是野路子摸索出来的哈哈哈哈哈哈哈哈哈

**Comment by ncumovi** [comment]
这么多的star是买的吗 汗。。。 搞一下午了

**Comment by ncumovi** [comment]
太难了 没有大佬回复 @ManHuai

**Comment by ManHuai** [comment]
我的法子能行不

**Comment by sunpu007** [comment]
看样子像是你的本地网络环境连不上github的443端口

**Comment by ncumovi** [comment]
要怎么可以解决呀




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PanJiaChen/vue-element-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 下午5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PanJiaChen/vue-element-admin] npm install报错128 (#3639)





 
看样子像是你的本地网络环境连不上github的443端口

**Comment by sunpu007** [comment]
科学上网试下

**Comment by ncumovi** [comment]
还是不行






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PanJiaChen/vue-element-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 下午5:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PanJiaChen/vue-element-admin] npm install报错128 (#3639)





 
我也是小白，这也是野路子摸索出来的哈哈哈哈哈哈哈哈哈

**Comment by ncumovi** [comment]
![image](https://user-images.githubusercontent.com/24260939/111565126-cf432500-87d5-11eb-9220-9fdb227f3d7e.png)

**Comment by CaptainCodes** [comment]
> ![image](https://user-images.githubusercontent.com/24260939/111565126-cf432500-87d5-11eb-9220-9fdb227f3d7e.png) 亲测可行

你是对的！
