### ISSUE TITLE
关于跨域问题，配置代理依然显示跨域

### ISSUE THREAD

**Issue by quietautumn** [PanJiaChen/vue-element-admin#3654]
#### Steps to reproduce（问题复现步骤）
将访问数据的方式更改为请求服务端数据，出现跨域，配置了代理，并且生效，请求路径已经更改，但是依然会提示跨域，不知是否还有其它地方需要更改

#### Screenshot or Gif（截图或动态图）
![}MHKW9CG~Q3TQ_Y1T%C}KHO](https://user-images.githubusercontent.com/16301518/113730688-aeae2100-972a-11eb-86c0-455fa9421919.png)
![Z`H_}I%$~~{_I_~69EZ 5 X](https://user-images.githubusercontent.com/16301518/113730713-b2da3e80-972a-11eb-843c-bd1571e62cbd.png)
![@ G1OKAMO$U7@J~~ 18UEXU](https://user-images.githubusercontent.com/16301518/113730722-b5d52f00-972a-11eb-8ecb-c071c5110ea9.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by xiaoxian521** [comment]
写法有问题

**Comment by wenkil** [comment]
VUE_APP_BASE_API = '/dev-api'   就可以了

**Comment by quietautumn** [comment]
@wenkil 谢谢
