### ISSUE TITLE
chrome浏览器无法登录，控制台没有报错信息

### ISSUE THREAD

**Issue by ChouJoe** [PanJiaChen/vue-element-admin#3669]
执行npm install build:prod命令编译项目后， 在chrome浏览器中点击login无反应，控制台也没报错， 但是在firefox浏览器中可以正常跳转。
chrome版本： 90.0.4430.72（正式版本） （64 位）
请问有人遇到这个问题吗

**Comment by ChouJoe** [comment]
执行npm install build:prod命令编译项目后， 在chrome浏览器中点击login无反应，控制台也没报错， 但是在firefox浏览器中可以正常跳转。
chrome版本： 90.0.4430.72（正式版本） （64 位）
请问有人遇到这个问题吗

**Comment by ChouJoe** [comment]
点击login后控制台source中index.html显示no resource with given url found。 
![image](https://user-images.githubusercontent.com/31032742/115211505-32f0a300-a132-11eb-9c1d-5be94aca1735.png)
但是开发调试时是正常的

**Comment by ChouJoe** [comment]
好吧 ，因为我是直接打开dist里的index.html，经过一番查找发现Chrome不支持在file//环境下set cookies，所以token并没有存到cookies中，造成登录后在router.beforeach中无法获取token，所以无法跳转路由

**Comment by Przeblysk** [comment]
自己 close 下吧

**Comment by guanzhao-destiny** [comment]
+1，我也碰到了这个问题，切换浏览器就可以了

**Comment by ChouJoe** [comment]
close issue
