### ISSUE TITLE
modules/tagsView.js 删除缓存有误

### ISSUE THREAD

**Issue by tlx6550** [PanJiaChen/vue-element-admin#367]
经测试，在store中 modules/tagsView.js，删除缓存页面原写法有问题
源代码const index = state.cachedViews.indexOf(i)
          state.cachedViews = state.cachedViews.slice(index, i + 1)
应为
const index = state.cachedViews.indexOf(i)
          state.cachedViews = state.cachedViews.slice(index, index + 1)
博主看看是不是这样呢

**Comment by PanJiaChen** [comment]
你说的是对的，是我的疏忽。之前合别人的代码的时候没有做好codereview。
方便提一个pr么？

**Comment by PanJiaChen** [comment]
#368
