### ISSUE TITLE
综合实例-综合table-分页控件有点问题

### ISSUE THREAD

**Issue by niechangxu** [PanJiaChen/vue-element-admin#369]
当改变页面大小时，在左侧导航栏会有一个分页控件一闪而过，

**Comment by PanJiaChen** [comment]
需要更详细错误信息

**Comment by niechangxu** [comment]
![test1](https://user-images.githubusercontent.com/13249740/34315989-35482796-e7c6-11e7-95f5-f435b5edb1a3.gif)
注意看左侧的导航栏

**Comment by PanJiaChen** [comment]
看着像是element-ui的问题，晚点我研究一下。

**Comment by PanJiaChen** [comment]
已修复 https://github.com/PanJiaChen/vue-element-admin/commit/83e56488d85b796e7dd4c56011021f0bad8bee1d

v-show 导致的定位错误
