### ISSUE TITLE
分页点击页码没有效果，数据不刷新

### ISSUE THREAD

**Issue by obiscr** [PanJiaChen/vue-element-admin#3698]
## Question（提问）
刚搞完了后端的动态菜单，分页是按照master分支的 complex-table.vue 写的。  
但是我测试的时候，发现当 点击页码 或者 选择每页显示条数的组件 发送给服  
务器page=1 ， limit =10 这个是设定的初始页码和每页显示的条数。

#### Screenshot or Gif（截图或动态图）
注意下半部分的日志显示区域，一直显示的是：page=1,size=10

![vue-admin-element-pagenation](https://user-images.githubusercontent.com/28687074/118344704-4ee53a00-b562-11eb-9dbf-887900422f55.gif)

**Comment by yeyicheng** [comment]
你好，请问解决了吗？怎么解决的？我的情况是，我这边是好的，但是我朋友那边有问题，page一直是1。
谢谢。

**Comment by obiscr** [comment]
解决了，是我自己的问题，参数传错了。
