### ISSUE TITLE
在没有登录的情况下，访问需要路由权限的页面跳转到登录页面后，NProgress异常

### ISSUE THREAD

**Issue by xqbumu** [PanJiaChen/vue-element-admin#37]
在没有登录的情况下，访问需要路由权限的页面跳转到登录页面后，NProgress无法停止，一直转动显示。
直接访问登录页路由NProgress可以正常消失。

**Comment by PanJiaChen** [comment]
在hash模式下 改变手动改变hash 重定向回来 不会触发afterEach 暂时hack掉了
 ps：history模式下无该问题
