### ISSUE TITLE
将项目打包后发布到apache的www下的vue子目录

### ISSUE THREAD

**Issue by sunchenguang** [PanJiaChen/vue-element-admin#370]
### 先讲结论：
1. 需要修改`router/index.js`中`new Router` 配置，加一个`base: '/vue/'`, 它指定应用的基路径，该应用是服务于`localhost/vue`路径下，所以必须加`base`配置，否则应用会展示404页面
2. 需要修改`config/index.js`中build下的`assetsPublicPath: '/vue/'`，如果用相对路径，chunk文件会报错找不到。
3. 修改`httpd.conf`文件，开启rewrite_module功能。
- `LoadModule rewrite_module libexec/apache2/mod_rewrite.so`，去掉前面的#。
- 然后找到` AllowOverride None`的那行，把它改成`AllowOverride All`，来使`.htaccess`文件生效。
4. 在apache 的`www/vue` 目录下新建`.htaccess`文件, 需要修改`RewriteRule` 为`/vue/index.html`, 否则刷新页面服务端会直接报404错误。

.htaccess文件内容
```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /vue/index.html [L]
</IfModule>


```

第一点文档上没讲，而且不是很详细，希望把这个当例子加上去，花了我好久时间

**Comment by PanJiaChen** [comment]
👍  晚点我将这个加入到文档中。

**Comment by PanJiaChen** [comment]
已添加到文档和wiki。
https://panjiachen.github.io/vue-element-admin-site/#/deploy?id=apache

**Comment by sunchenguang** [comment]
good!

**Comment by webyangpei** [comment]
有nginx的虚拟目录配置方案么？ 不知道咋搞

**Comment by xiejiao** [comment]
请教一下，发布后的文件不是都放在dist里了，为什么会修改router/index.js和config/index.js？是修改完之后再build一遍吗？

**Comment by xiejiao** [comment]
另外config/index.js，这个文件是哪里的？

**Comment by shupeaceful** [comment]
有nginx的虚拟目录配置方案么,想请教一下

**Comment by shanhai1992** [comment]
config/index.js，这个项目里面应该指的是，vue.config.js，公司只有一个域名，不得不用子目录，在哪个文件夹里面修改一个变量即可，楼主说的流程没错！

**Comment by hyysgit** [comment]
为什么我打包之前还可以请求到服务器,导包后请求报404 
`VUE_APP_BASE_API = '/api/admin'`
.env 两个下的配置都是一样的
`proxy: {
      // change xxx-api/login => mock/login
      // detail: https://cli.vuejs.org/config/#devserver-proxy
      /* [process.env.VUE_APP_BASE_API]: {
        target: `http://127.0.0.1:${port}/mock`,
        changeOrigin: true,
        pathRewrite: {
          ['^' + process.env.VUE_APP_BASE_API]: ''
        }
      }*/

      '/api': {
        target: `http://cms.shoptc.vip`, // 这个链接是要代理到的api地址
        changeOrigin: true,
        pathRewrite: {
          '^/api': ''
        }
      }

    }`

**Comment by shanhai1992** [comment]
404找不到资源文件，你肯定哪个地方配置错了，耐心点，伙计

**Comment by nozbwang** [comment]
我的nginx是这么配置的 测试了下可用

server {
        listen       80;
        server_name  localhost;
		
	location /prod-api/ {
                proxy_pass http://127.0.0.1:8028/;  #本地项目
        }

        location ~* \.(html|htm|gif|jpg|jpeg|bmp|png|ico|txt|js|css|woff|ttf)$ {  #代理所有静态资源文件
                root C:\Project\iot\iot-admin\dist; #静态资源地址，本地路径
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

    }
