### ISSUE TITLE
English translation contribution

### ISSUE THREAD

**Issue by beirdostudio** [PanJiaChen/vue-element-admin#371]
Hello,

Congratulations on this project, I think it's really awesome.
I'd like to help you translate it to English (and eventually french), I don't speak Chinese so I will be mainly using google translate for it, is there any requirements or any way you want this done?

Note: I work with git a lot but never forked a repo and used pull requests so if you're interested, please bear with me :)

Thank you.

**Comment by PanJiaChen** [comment]
This looks awesome！
 I have some free time next week，I will try my best to translate the comment and code into English，but the document may take a little more time.

**Comment by beirdostudio** [comment]
yeah, the documentation is pretty big, it wont be easy work, but I'll try to help as much as possible with whatever is understandable using google translate, the project is too good to stay hidden :)

I'll drop a pull request as soon as I do some translations, does the docs have a repo? if so can you pass me a link?

**Comment by wyudong** [comment]
I can help to translate something to English with you. @beirdostudio

**Comment by PanJiaChen** [comment]
@wyudong  I have translated most of the repository in branch https://github.com/PanJiaChen/vue-element-admin/tree/feat/en, later will be officially released.
The next step is to translate the document step by step.I think most of it will be done this week.

**Comment by wyudong** [comment]
@PanJiaChen You mean you can finish [all of this](https://panjiachen.github.io/vue-element-admin-site/#/) by this week!?

**Comment by PanJiaChen** [comment]
I will do my best, of course, there will be many mistakes。Later on, I need community help to maintain it.

**Comment by beirdostudio** [comment]
This is some great news! sorry, I kinda got busy making a working version of this repo with loopback for user auth.

I will definitely proofread the doc once it's done, meanwhile, it wasn't that bad working with google translate, most of the doc is understandable and the code structure is great!

If you want, I can still help you with what's left alongside @wyudong if he's still willing.

**Comment by PanJiaChen** [comment]
The new document has been rewritten based on vuepress, and the English version has been improved. If you find a problem, you can pr.

[The documentation source](https://github.com/PanJiaChen/vue-element-admin-site).
