### ISSUE TITLE
request请求

### ISSUE THREAD

**Issue by aluckyqingchun1** [PanJiaChen/vue-element-admin#3723]
发送post请求 请求数据从浏览器上可以看到 但是后端接收不到 
我用postman和html请求都能拿到数据  但是在这个后台管理请求的post数据拿不到 切换content-type类型也不行
现在不知道是什么问题 后台返回是 请求中止 拿不到post请求的值

**Comment by nroyliu** [comment]
我现在也遇到这个问题了，之前的elementadmin项目都没有这样

**Comment by aluckyqingchun1** [comment]
> 我现在也遇到这个问题了，之前的elementadmin项目都没有这样

vue.config.js 里面有个  before: require('./mock/mock-server.js') 这个配置 把这个注释掉就可以了 这个before中间件处理了东西 应该就是这个问题
