### ISSUE TITLE
当屏幕缩小Tinymce编辑器的工具栏会超出文本编辑区域

### ISSUE THREAD

**Issue by Geralt-TYH** [PanJiaChen/vue-element-admin#3757]
## Bug report（问题描述）
如标题所述，而且如果尝试将外层包裹的div宽度减小也会出现这个问题，bug大概率估计是编辑器那边的，不知道有没有解决办法
#### Steps to reproduce（问题复现步骤）

将屏幕缩小

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/16754661/125596176-de4e773d-67a8-4cc9-8357-24fc0f8d2dc1.png)

#### Link to minimal reproduction（最小可在线还原demo）

无demo

#### Other relevant information（格外信息）
- Your OS: windows 10
- Node.js version: v16.4.0
- vue-element-admin version: 4.4.0 Update to vue-cli@4

**Comment by NierYM** [comment]
在Component文件中找到Tinymce的组件，在其组件文件夹下的Index.vue文件中的Style里添加
.mce-container {
		::v-deep &.mce-btn-group div:first-child {
			display: flex;
			flex-wrap: wrap;
		}
}
就可以了，亲测::v-deep是必要的
![del](https://user-images.githubusercontent.com/64945423/127822670-75f6e715-ad5c-42fd-8cbc-a0e2a526c565.png)

**Comment by Geralt-TYH** [comment]
@NierYM 谢谢，一直忘记回复了，该办法有效的解决了问题，同时get了样式穿透知识点
