### ISSUE TITLE
裤衩哥，complexTable.vue 新建行的时候，你采用的弹出框的形式添加， 为什么不在编辑后面增加一个添加按钮呢？

### ISSUE THREAD

**Issue by dawayway** [PanJiaChen/vue-element-admin#377]
裤衩哥，
问题1： complexTable.vue 新增行的时候，你采用的弹出框的形式添加， 为什么不在编辑后面增加一个添加按钮呢？直接复制这一行的信息，然后在表格里面编辑修改呗，

**Comment by PanJiaChen** [comment]
因为很多时候你添加的内容可能比较复杂，还是放在dialog里面更加的直观。而且还能复用组件。个人交互习惯问题。有需求可自行修改。

**Comment by dawayway** [comment]
我在table里面放了 select 选择框，增加 行 后， select 的值和被复制行 绑定的是一样的
