### ISSUE TITLE
global translateKey method

### ISSUE THREAD

**Issue by beirdostudio** [PanJiaChen/vue-element-admin#378]
hey @PanJiaChen ,
I was looking at the new login/index.vue page and I saw the method:
`translateKey(key) {
      return this.$t('login.' + key)
    },`

Wouldn't it be better if this method was made global as a mixin or something so all component can use it instead of declaring it again on each component?

**Comment by PanJiaChen** [comment]
I have some hesitation in this part of the code. May be direct use vue-i18n global function $t is the most simple and convenient. But I'm afraid a lot of beginners don't know what this is.

**Comment by PanJiaChen** [comment]
I thought about it, l wii direct use vue-i18n global function $t and add it to documentation.

**Comment by beirdostudio** [comment]
Sounds good, anyone delving into an admin interface made with vuejs should be able to search for something he didn't understand.
