### ISSUE TITLE
yarn安装依赖包报错

### ISSUE THREAD

**Issue by Corgis** [PanJiaChen/vue-element-admin#3785]
#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/13865529/129168589-4cacd386-a13d-41a3-a03b-817724890620.png)

#### Other relevant information（格外信息）
- Your OS: Windows 10 家庭版
- Node.js version: v14.15.0
- vue-element-admin version: v14.15.0

**Comment by LixHu** [comment]
+1

**Comment by AdminQQZ** [comment]
+2

**Comment by Corgis** [comment]
先去package.json去除 tui-editor的安装，报错原因是这个
