### ISSUE TITLE
项目初始化需要读取服务端配置，将读取结果放入vuex中

### ISSUE THREAD

**Issue by mingliao** [PanJiaChen/vue-element-admin#380]
您好，请教一下，
   我需要在项目初始化的时候请求服务端接口，读取配置信息，然后把一些信息放在vuex里面，这样的步骤在哪里操作比较好。能在项目src/main.js里项目vue初始化之后与服务端进行交互？然后直接更新store的状态
```
// vue初始化
new Vue({
  el: '#app',
  router,
  store,
  i18n,
  template: '<App/>',
  components: { App }
})
// 读取配置，更新store
......
```

**Comment by PanJiaChen** [comment]
这个很难评价，不是很清楚你具体的业务。比如你这个初始化涉不涉及权限问题，是在登录后呢还是登录前。

**Comment by mingliao** [comment]
@PanJiaChen  您好，不涉及权限，在登录之前，我不太清楚这样的操作是要放在哪里比较合适。

**Comment by PanJiaChen** [comment]
你还是没说清楚啊，比如你求服务端接口的内容必须完成之后才能进入页面，还是可以异步的？

**Comment by mingliao** [comment]
@PanJiaChen  嗯，我们现在的项目就是需要先请求服务端接口的数据A，然后把数据A塞在vuex里面作为初始化状态base state的数据，这个数据在登录前，跟权限什么的没有关系。但是是项目必须要的。也可以像您说的，必须请求完成之后才可以进去界面，不然界面无法运行。

**Comment by PanJiaChen** [comment]
具体还要看你的目录结构。就拿本项目来说，app.vue 是入口文件，里面配置了`<router-view>`，所以我就可以在`@/views/layout/Layout.vue`中使用组件内钩子，
```js
beforeRouteEnter: (to, from, next) => {
    // do some thing
 }
```
当然能这样用的前提是你所有的页面都基于这个layout.

还有一种方法是使用全局的路由钩子，你可以参考本项目获取用户权限的方法，在`router.beforeEach`之中进行拦截。通过一个标识符或者一个vuex里面的值是否存在来判断是否已拉去过数据。
如：
https://github.com/PanJiaChen/vue-element-admin/blob/83e56488d85b796e7dd4c56011021f0bad8bee1d/src/permission.js#L24-L30

**Comment by mingliao** [comment]
@PanJiaChen  好的，非常感谢。我参考下您的处理方式看下。
