### ISSUE TITLE
为何npm run dev报错,运行不起来

### ISSUE THREAD

**Issue by FDLFDL** [PanJiaChen/vue-element-admin#382]
![e pgfpvkc _e iec7 o](https://user-images.githubusercontent.com/16077030/34433955-b9a64b3e-ecbd-11e7-9302-9fbfa49a92db.png)

**Comment by PanJiaChen** [comment]
node-sass 未安装成功。请自行百度相关解决方案。

**Comment by DongLee0504** [comment]
指定node-sass的下载源：
npm config set sass-binary-site http://npm.taobao.org/mirrors/node-sass

**Comment by DongLee0504** [comment]
1、指定node-sass的下载源：
npm config set sass-binary-site http://npm.taobao.org/mirrors/node-sass
2、npm i
3、npm run dev
