### ISSUE TITLE
generated source files should not be edited.

### ISSUE THREAD

**Issue by ybhuxiao** [PanJiaChen/vue-element-admin#383]
Is index.css generated by some other tools?
when i try to edit/format it, this tip showing.
![image](https://user-images.githubusercontent.com/17189297/34466592-021117d4-ef14-11e7-9443-4a815157297d.png)

**Comment by PanJiaChen** [comment]
This is your ide tips, does not affect the normal operation.
And l think if you want generate element-ui theme, you can see [document](https://panjiachen.github.io/vue-element-admin-site/#/theme?id=%e5%a4%9a%e5%a5%97%e4%b8%bb%e9%a2%98%e6%8d%a2%e8%82%a4)
