### ISSUE TITLE
mac 系统报错 

### ISSUE THREAD

**Issue by miaoyinjun** [PanJiaChen/vue-element-admin#384]
npm：5.0.0
node : 8.0.0

$ npm run dev

Module build failed: TypeError: Cannot read property 'length' of null
    at /Users/jimmy/Downloads/vue-element-admin/node_modules/eslint-friendly-formatter/index.js:184:73

**Comment by PanJiaChen** [comment]
Please provide a more complete error message or a screenshot

**Comment by miaoyinjun** [comment]
谢谢，mac重启后，发现是npm有问题
