### ISSUE TITLE
请问，查询或者修改数据库一般采用什么方案？

### ISSUE THREAD

**Issue by lsx1994** [PanJiaChen/vue-element-admin#3842]
直连mysql或者mongo没有看到相关的文档。
我刚接触后台，大家一般是怎么做的啊？ 
在游戏服务器执行查询逻辑，前端页面直接通过http获取结果并显示吗？

**Comment by hobeas** [comment]
1. 区分后台和后端。这个是后台的前端项目，你要的操作数据库属于后端了。
2. 如何连接 mongo。取决于你后端用的技术，比如用NodeJS，可通过 mongoose 库操作。
3. 游戏服务器通过接口和参数，执行查询逻辑；前端使用服务器提供的接口，通过封装的请求库axios获取数据，并由“你”定义如何显示

**Comment by lsx1994** [comment]
> 1. 区分后台和后端。这个是后台的前端项目，你要的操作数据库属于后端了。
> 2. 如何连接 mongo。取决于你后端用的技术，比如用NodeJS，可通过 mongoose 库操作。
> 3. 游戏服务器通过接口和参数，执行查询逻辑；前端使用服务器提供的接口，通过封装的请求库axios获取数据，并由“你”定义如何显示

之前有个同事用thinkphp做后台是直连mongo数据库读取日志的，发奖励才跟服务器交互，那我晓得了。

**Comment by hobeas** [comment]
如果只是读取，在 `mongodb.conf` 配置

```conf
# REST API
rest=true

# 远程访问
bind_ip=0.0.0.0
```

即可开启简单的 REST API，端口是 28017，不支持增删改

**Comment by lsx1994** [comment]
> 如果只是读取，在 `mongodb.conf` 配置
> 
> ```
> # REST API
> rest=true
> 
> # 远程访问
> bind_ip=0.0.0.0
> ```
> 
> 即可开启简单的 REST API，端口是 28017，不支持增删改

 多谢
