### ISSUE TITLE
三级路由缓存解决方案

### ISSUE THREAD

**Issue by heyuying99** [PanJiaChen/vue-element-admin#3847]

**Comment by heyuying99** [comment]
1.添加一个公共组件parent-view，所有三级路由的父组件引用这个组件
![image](https://user-images.githubusercontent.com/22073319/137440935-71bcde3b-ea6f-44cd-b4be-0f264bb15798.png)


2.修改AppMain.vue文件
![image](https://user-images.githubusercontent.com/22073319/137441012-6e80d2b5-9ac4-4d6f-b673-3731f6d78183.png)

**Comment by yellowseasky** [comment]
请问有解决方案吗？我那个项目是后端路由
