### ISSUE TITLE
Can't resolve 'core-js/modules/es.regexp.dot-all.js

### ISSUE THREAD

**Issue by T1986513441** [PanJiaChen/vue-element-admin#3865]
![image](https://user-images.githubusercontent.com/38282613/141489145-d9d1c89c-f53c-4e5f-9722-f36579bd929b.png)
![image](https://user-images.githubusercontent.com/38282613/141489177-3bfb2259-f7be-4a4b-891f-0f640f70f335.png)

**Comment by T1986513441** [comment]
之前那个项目都是好的， 把项目复制出来一份，重新运行就不行

**Comment by T1986513441** [comment]
core-js 库版本太高

**Comment by aote777** [comment]
> core-js 库版本太高

2021/12/7 更新一波

执行
`cnpm install core-js@3 --save`
