### ISSUE TITLE
Vuex 页面刷新 state 数据丢失

### ISSUE THREAD

**Issue by Twitchboy** [PanJiaChen/vue-element-admin#387]
Vuex 页面刷新 state 数据丢失，除了本地缓存 解决方案还有别的吗

**Comment by PanJiaChen** [comment]
vuex作用并不是缓存数据。
刷新保持状态只有两种方案：
- 前端处理 存储在本地
- 后端处理 存储在服务端

**Comment by baozheliu** [comment]
@PanJiaChen 你好，我发现项目中你写存储到vuex中的用户名、用户头像等数据在页面刷新后，这些数据还是存在的，但是我自己加了一个属性，刷新页面后数据被赋为初始值？希望@PanJiaChen 大大解惑？
` 
// 这些数据在页面属性后依然是存在的
const user = {
  state: {
    user: '',
    status: '',
    code: '',
    token: getToken(),
    name: '',
    avatar: '',
    introduction: '',
    roles: [],
    setting: {
      articlePlatform: []
    }
  },
...//省略代码
`

**Comment by miracllife** [comment]
遇到同样问题，不知道各位怎么解决的

**Comment by vermilionlovewz** [comment]
我也遇到这个问题，有人解决了吗？

**Comment by 251205668** [comment]
其实读下源码就能知道解决办法的 刷新的时候校验了权限，然后重新将用户信息保存在了vuex中
