### ISSUE TITLE
 I can't choose the language when I click menu

### ISSUE THREAD

**Issue by zhi3210happy** [PanJiaChen/vue-element-admin#388]
![qq 20180104114836](https://user-images.githubusercontent.com/29395376/34549728-ef3b86ba-f145-11e7-9b57-ebd534e9158d.png)

**Comment by zhi3210happy** [comment]
The Chinese is disable。

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/de08e49f19c10b9e43e59f07cb0699bf4f7dc93e
