### ISSUE TITLE
首页的路由定位问题

### ISSUE THREAD

**Issue by rotate720deg** [PanJiaChen/vue-element-admin#390]
大神你好，有一个小问题
首先是路由这里
```javascript
{
    path: '',
    component: Layout,
    redirect: 'dashboard',
    children: [{
      path: 'dashboard',
      component: _import('dashboard/index'),
      name: 'dashboard',
      meta: { title: 'dashboard', icon: 'dashboard', noCache: true }
    }]
  },
```
这里的path没有写，导致的后果就是，侧边栏如果第一个菜单有下拉选项，是不能匹配到index的，所以下拉选项是收起来的
![image](https://user-images.githubusercontent.com/16872226/34554468-fbd7d6f4-f167-11e7-9f9a-d80c1751dc8b.png)

然后我试着将path改为'/'，又会导致路由错误，多出来一个'/',我将sidebar-item中的+‘/’+去掉，但是又会导致children.length ===1的匹配不到路由。

**Comment by rotate720deg** [comment]
要针对children.length ===1的路由，不能去掉+‘/’+，这样貌似就可以了

**Comment by PanJiaChen** [comment]
不是很懂 你到底要想要描述什么问题

**Comment by rotate720deg** [comment]
如果我把路由改为这样
```javascript
{
    path: '',
    component: Layout,
    redirect: 'dashboard1',
    meta: { title: 'dashboard', icon: 'dashboard', noCache: true }
    children: [{
      path: 'dashboard1',
      component: _import('dashboard/index'),
      name: 'dashboard1',
      meta: { title: 'dashboard', icon: 'dashboard', noCache: true }
    },{
      path: 'dashboard2',
      component: _import('dashboard/index'),
      name: 'dashboard2',
      meta: { title: 'dashboard', icon: 'dashboard', noCache: true }
    }]
  },
```
然后页面跳转到`http://localhost:9527/#/dashboard2`的时候，dashboard这个菜单并没有展开
![image](https://user-images.githubusercontent.com/16872226/34555969-70d32682-f16f-11e7-9192-f84181b490d5.png)

**Comment by PanJiaChen** [comment]
目前是这样的，因为你这里的跟path是'空',所以会导致一些问题。
你什么业务场景下dashboard需同时存在多个？
