### ISSUE TITLE
在钉钉浏览器中遇到各种兼容性问题，请问有办法么。low-end browser adaptation

### ISSUE THREAD

**Issue by a304885433** [PanJiaChen/vue-element-admin#391]
大概有如下几类
1. 首页控制菜单折叠的图标和功能的tab标签，贴近页面顶部。
2. 弹出的dialog页面，无法看到标题等。。。
。。。
不好截图，无法佐证，不知道大神有没有试过在钉钉浏览器中运行，如何解决这种兼容性问题。
在常规浏览器中没有问题的。

**Comment by PanJiaChen** [comment]
This project does not support low-end browser adaptation. Please adapt yourself.

**Comment by a304885433** [comment]
= = 。 钉钉是阿里推出的企业IM工具，类似微信，主要也不知道是哪里有问题。
https://www.dingtalk.com/

**Comment by PanJiaChen** [comment]
钉钉内置游览器很大肯能就是uc，内核一般很低，所以会不适配。请自行解决。

**Comment by a304885433** [comment]
恩，谢谢

**Comment by InsHomePgup** [comment]
> 钉钉内置游览器很大肯能就是uc，内核一般很低，所以会不适配。请自行解决。

好家伙，怪不得呢，这个echarts5的也不能正常显示了，这个调试还真令人头疼。。
