### ISSUE TITLE
codemirror这个包太大了,能问下如何排除打包吗?

### ISSUE THREAD

**Issue by Kikuchiyo1996** [PanJiaChen/vue-element-admin#3915]
## Question（提问）

设置了externals没有用..去官网也没搜到相关问题😭
![image](https://user-images.githubusercontent.com/72541282/149722316-9e7bc59a-ac0e-4b6a-8efa-3923a1c177af.png)
![image](https://user-images.githubusercontent.com/72541282/149722542-6ce5a098-367c-490e-aeb2-b64c1be2ac5a.png)

**Comment by hobeas** [comment]
没使用到就不会打包。
这是用于编辑器的包，如果你用不到 Markdown 和 JSON 编辑器，把这两个组件文件移除即可。
顺便把包从 package.json 和 node_modules 移除，执行 `npm uninstall codemirror -S`

**Comment by bring-down-the-hammer** [comment]
> 

我就是用到这个编辑器了呀 所以想用cdn引入 webpack有个externals选项可以将某个包排除在外 但是设置了没有用..

**Comment by bring-down-the-hammer** [comment]
@hobeas  我就是用到这个编辑器了呀 但这个包太大了 所以想用cdn引入 webpack有个externals选项可以将某个包排除在外 但是设置了没有用..

**Comment by hobeas** [comment]
我试了下 externals 是有效的

1. 在 `vue.config.js` 里配置 externals

```js
// vue.config.js
module.exports = {
  configureWebpack: {
    externals: {
      codemirror: 'CodeMirror'
    }
  }
}
```

2. 注释掉 JsonEditor “导入无声明”的代码

```js
// src/components/JsonEditor/index.vue

import CodeMirror from 'codemirror'
// import 'codemirror/addon/lint/lint.css'
// import 'codemirror/lib/codemirror.css'
// import 'codemirror/theme/rubyblue.css'
// require('script-loader!jsonlint')
// import 'codemirror/mode/javascript/javascript'
// import 'codemirror/addon/lint/lint'
// import 'codemirror/addon/lint/json-lint'
```

3 `public/index.html` 使用 CDN

```html
<!DOCTYPE html>
<html>
  <head>
    <title><%= webpackConfig.name %></title>
    <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/codemirror/5.65.0/addon/lint/lint.min.css" />
    <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/codemirror/5.65.0/codemirror.min.css" />
    <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/codemirror/5.65.0/theme/rubyblue.min.css" />
  </head>
  <body>
    <div id="app"></div>
    <!-- built files will be auto injected -->
    <script src="https://cdn.bootcdn.net/ajax/libs/codemirror/5.65.0/codemirror.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/codemirror/5.65.0/mode/javascript/javascript.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/codemirror/5.65.0/addon/lint/lint.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/jsonlint/1.6.0/jsonlint.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/codemirror/5.65.0/addon/lint/json-lint.min.js"></script>
  </body>
</html>
```

看下效果吧，功能正常

![220129_81905](https://user-images.githubusercontent.com/41267951/151640076-c6f238c9-c64a-46aa-bcfd-598fd8fca75b.jpg)

**Comment by bring-down-the-hammer** [comment]
@hobeas 谢谢您 成功了 还有一个问题,我该如何动态导入这个包呢... 我尝试在不同的环境导入它以便于开发环境下使用 但eslint报错
![图片](https://user-images.githubusercontent.com/72541282/151648864-49f10a93-619d-489b-8393-343c646d2bab.png)
```js
Parsing error: 'import' and 'export' may only appear at the top level
```

**Comment by bring-down-the-hammer** [comment]
@hobeas 谢谢您 成功了 还有一个问题,我该如何动态导入这个包呢... 区别开发环境和生产环境 我试了好几种方案但都不太好使

**Comment by yuhaoz** [comment]
@hobeas 可以帮忙解惑一下吗？为什么要 注释掉 JsonEditor “导入无声明”的代码，不太懂，为什么注释掉后还能运行正常
