### ISSUE TITLE
npm install报错

### ISSUE THREAD

**Issue by g88827929g** [PanJiaChen/vue-element-admin#3919]
#### Steps to reproduce（问题复现步骤）
![360截图20220209144223164](https://user-images.githubusercontent.com/49873606/153136055-04d920e8-7d51-4688-b445-07012b7350d7.jpg)

#### Screenshot or Gif（截图或动态图）
![360截图20220209144223164](https://user-images.githubusercontent.com/49873606/153136087-b865e74e-c6df-4e3b-9f71-898f9db91d34.jpg)

总是无法安装，无权限
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by suzhenghui-sky** [comment]
用淘宝镜像下载。

**Comment by JohnChan1017** [comment]
要把本地电脑生成的SSH 公钥添加到github 设置里面
（补充知识：执行 ssh-keygen命令时，会在home目录下的 .ssh/ 目录里生成两个 Keys ，分别是私钥 (id_rsa) 与公钥 (id_rsa.pub)）
步骤如下，
1. git bash here 输入 ssh-keygen -t rsa -C “你的邮箱名称”
2. 回车，回车，回车
3. 找到C:->用户->你的用户名->.ssh->id_rsa.pub（记事本打开，复制）
4. 回到github个人用户设置->SSH and GPG keys ->new SSH keys, 把刚才的复制的公钥内容粘贴到github上的【new SSH Keys】即可大功告成
