### ISSUE TITLE
建议加流程控制

### ISSUE THREAD

**Issue by GeorgeMe** [PanJiaChen/vue-element-admin#392]
![tim 20180108111616](https://user-images.githubusercontent.com/7805207/34657922-d3fe55b2-f465-11e7-8d63-bda77283aad0.png)

**Comment by daiing** [comment]
这是什么控件？

**Comment by GeorgeMe** [comment]
工作流

**Comment by PanJiaChen** [comment]
个人觉得一般后台使用场景很少吧。

**Comment by GeorgeMe** [comment]
是的  但是用到了就烧脑了  我这边已经找到处理办法了
