### ISSUE TITLE
关于白名单的问题

### ISSUE THREAD

**Issue by Junyi2921** [PanJiaChen/vue-element-admin#393]
在permission这个文件中，当用户并没有登录也就是cookie中不存在token情况下，如果没有白名单，直接跳转到‘/login’会出现死循环问题，但是设置了白名单就没事了..这是为什么？我不太明白有没有白名单的区别..

**Comment by Junyi2921** [comment]
其实也就是说，在访问一个非白名单的地址的情况下，router.beforeEach要走两次才能到login页面，这段代码是否可以优化..可否讨论一下？

**Comment by PanJiaChen** [comment]
合理逻辑，在没登录得情况下，进任何需要登录得页面都重定向到登录页有什么问题么？

**Comment by Junyi2921** [comment]
逻辑没有问题,在没登录情况下，是不是可以让router.beforeEach只走一次就可以重定向到登录页，而不是两次..

**Comment by PanJiaChen** [comment]
因为涉及到权限，所以并不能。如果你有别的更好的写法欢迎pr。
