### ISSUE TITLE
npm install  错误 fatal: remote error: 

### ISSUE THREAD

**Issue by n65312** [PanJiaChen/vue-element-admin#3945]
#### Steps to reproduce（问题复现步骤）

1. npm install 出错 
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/adobe-webplatform/eve.git
npm ERR! 
npm ERR! fatal: remote error: 
npm ERR!   The unauthenticated git protocol on port 9418 is no longer supported.
npm ERR! Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
npm ERR! 
npm ERR! exited with error code: 128

#### Screenshot or Gif（截图或动态图）
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/59176089/159018550-b9d666d7-07d7-43bc-805b-bad7e0ff3f1e.png">

#### Other relevant information（格外信息）
- Your OS: mac
- Node.js version: v14.17.5
- vue-element-admin version: 4.4.0

**Comment by n65312** [comment]
本失败原因是由于tui-editor（富文本编辑器插件）更名造成的，现在已经更名为toast-ui/editor（以下第一步）
并且该插件还进行了文件名的更名（以下第二步）以及方法名的更名（以下第三步）

解决方案如下：
1.首先将package.json中的tui-editor那一行修改为"@toast-ui/editor": "^3.1.3",

2.进入\src\components\MarkdownEditor\index.vue文件，将他的所有import删除换成下面四行
import 'codemirror/lib/codemirror.css'
import '@toast-ui/editor/dist/toastui-editor.css'
import Editor from '@toast-ui/editor'
import defaultOptions from './default-options'

3.把该页面（还是第二条中的文件）的getValue和setValue分别换成getMarkdown和setMarkdown
把页面中的所有tui-editor全部替换为@toast-ui/editor

4.保存文件，npm install 搞定

**Comment by n65312** [comment]
解决方案来自    https://gitee.com/panjiachen/vue-element-admin/issues/I4UQ2X

**Comment by 332lfgb6** [comment]
> 解决方案来自 https://gitee.com/panjiachen/vue-element-admin/issues/I4UQ2X

经过你上面的修复，npm install可以成功了，但是访问markdown这个页面还是会报错，大哥你碰到这个问题吗？

**Comment by wuyaoqing** [comment]
访问markdown这个页面还是会报错

**Comment by leyuyu** [comment]
> 本失败原因是由于tui-editor（富文本编辑器插件）更名造成的，现在已经更名为toast-ui/editor（以下第一步） 并且该插件还进行了文件名的更名（以下第二步）以及方法名的更名（以下第三步）
> 
> 解决方案如下： 1.首先将package.json中的tui-editor那一行修改为"@toast-ui/editor": "^3.1.3",
> 
> 2.进入\src\components\MarkdownEditor\index.vue文件，将他的所有import删除换成下面四行 import 'codemirror/lib/codemirror.css' import '@toast-ui/editor/dist/toastui-editor.css' import Editor from '@toast-ui/editor' import defaultOptions from './default-options'
> 
> 3.把该页面（还是第二条中的文件）的getValue和setValue分别换成getMarkdown和setMarkdown 把页面中的所有tui-editor全部替换为@toast-ui/editor
> 
> 4.保存文件，npm install 搞定

安装是能安装了，但是npm run dev运行后报错：Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'

**Comment by leyuyu** [comment]
> 本失败原因是由于tui-editor（富文本编辑器插件）更名造成的，现在已经更名为toast-ui/editor（以下第一步） 并且该插件还进行了文件名的更名（以下第二步）以及方法名的更名（以下第三步）
> 
> 解决方案如下： 1.首先将package.json中的tui-editor那一行修改为"@toast-ui/editor": "^3.1.3",
> 
> 2.进入\src\components\MarkdownEditor\index.vue文件，将他的所有import删除换成下面四行 import 'codemirror/lib/codemirror.css' import '@toast-ui/editor/dist/toastui-editor.css' import Editor from '@toast-ui/editor' import defaultOptions from './default-options'
> 
> 3.把该页面（还是第二条中的文件）的getValue和setValue分别换成getMarkdown和setMarkdown 把页面中的所有tui-editor全部替换为@toast-ui/editor
> 
> 4.保存文件，npm install 搞定

安装没问题，但是npm run dev运行后报错：Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'

**Comment by duxinyues** [comment]
@n65312 找了这么多，就这个有用，点赞
