### ISSUE TITLE
tagsView页签组件 删除任意页签后，该页签后面的标签页不再被缓存

### ISSUE THREAD

**Issue by CaserLee** [PanJiaChen/vue-element-admin#395]
打开多个标签后，关闭其中任意一个标签，则该标签后面的所有标签页都被从cachedViews中删掉了。
定位问题在：tagsView页签组件 /store/tagsView.js 删除记录 DEL_VISITED_VIEWS 方法有误

复现过程详述如下：
第一步：打开三个标签
![image](https://user-images.githubusercontent.com/22851684/34858290-735afcce-f78a-11e7-85f0-a6e45050866a.png)
AppMain中cachedViews变化如下：
![image](https://user-images.githubusercontent.com/22851684/34858303-93a132b4-f78a-11e7-83f2-334e96ebc066.png)

第二步：关闭中间那个标签
![image](https://user-images.githubusercontent.com/22851684/34858621-5859d9fc-f78c-11e7-8842-3d69db6088d9.png)

AppMain中cachedViews变化如下：
![image](https://user-images.githubusercontent.com/22851684/34858347-cff40d54-f78a-11e7-8c16-ae827e182979.png)
可以看到，在DEL_VISITED_VIEWS  中 splice操作之后，只保留了关闭标签页位置之前的cachedViews记录，其后的都被splice掉了。

源代码  /store/tagsView.js(Line27) 在 DEL_VISITED_VIEWS 方法中
 const index = state.cachedViews.indexOf(i)
 state.cachedViews.splice(index, index + 1)

应为
 const index = state.cachedViews.indexOf(i)
 state.cachedViews.splice(index, 1)

应只删除这一条cachedViews记录，否则后续的标签页不会被 keep-alive

感谢！

**Comment by PanJiaChen** [comment]
的确有问题，谢谢你的反馈。

**Comment by PanJiaChen** [comment]
已修复 https://github.com/PanJiaChen/vue-element-admin/commit/3c0696d1a9582924f6987e6db549836933a010f5
