### ISSUE TITLE
更新部分依赖后,导致加载不到自定义组件

### ISSUE THREAD

**Issue by cayar** [PanJiaChen/vue-element-admin#396]
按照上次作者更新了element 2.x的版本,我更新了部分package.json的依赖js后`npm install`是没有问题的,但是`npm run dev`就提示找不到自己写的这些封装的自定义组件了,原先项目都是正常运行的.
因为刚接触这个前端没有多久,所以很多不懂的地方,就去google了很多可能出现的问题原因,也没有能解决.
现在我从gitlab上clone下项目在新的工作空间进行`npm install & npm run dev`就会出现这个错误,但是把之前项目的node_modules拷贝到新的工作空间项目中就能运行.很奇葩的情况
![image](https://user-images.githubusercontent.com/8390373/34906543-8f2bcd40-f8aa-11e7-854e-51aeebb07fd3.png)
代码我已经传到仓库
https://github.com/cayar/aquarius-face
希望大佬有时间可以clone下来帮忙看看.万分感谢!

**Comment by PanJiaChen** [comment]
https://github.com/cayar/aquarius-face/blob/309fd8d272c95b774ee8a525072f16c5997bdc9a/build/webpack.base.conf.js#L57
你使用iview-loader但并未安装。

**Comment by cayar** [comment]
感激不尽! @PanJiaChen
