### ISSUE TITLE
关于系统环境变量配置问题

### ISSUE THREAD

**Issue by hdhfb** [PanJiaChen/vue-element-admin#3967]
## Question（提问）
env.development

![image](https://user-images.githubusercontent.com/15921799/163668841-11fd05c8-133a-499c-b6d0-3521970b6372.png)
浏览器打印出来的是不一样的
![image](https://user-images.githubusercontent.com/15921799/163668875-17110bec-be9f-45d5-815d-a56b8547e435.png)
是不是vuecli没有加载进去

如何配置才是正确？

#### Other relevant information（格外信息）
- Your OS: windows 10
- Node.js version: v14.15.0
- vue-element-admin version:  v4.1.0+

**Comment by hdhfb** [comment]
官方文档说：只有以 **VUE_APP_**  开头的变量会被 webpack.DefinePlugin 静态嵌入到客户端侧的包中，试过了，也无效

**Comment by CFMJ** [comment]
配置环境变量后要重新启动,重启项目之后试试还可不可以

**Comment by hdhfb** [comment]
> 配置环境变量后要重新启动,重启项目之后试试还可不可以

是的，重启后就可以了，谢谢
