### ISSUE TITLE
每次点击右侧顶部标签都会导致页面初始化的问题

### ISSUE THREAD

**Issue by Webdiyer** [PanJiaChen/vue-element-admin#397]
比如点击左侧的“创建表单”菜单，在右侧的表单中录入一些测试数据，然后点击右侧上部的“首页”标签切换到首页，再点击“创建表单”标签打开创建表单页面时，输入的测试数据全部丢失，页面被重新初始化了，这个问题是否有办法解决？

**Comment by PanJiaChen** [comment]
两种方案 一种使用 <keep-alive> [文档](https://vuejs.org/v2/api/#keep-alive)
或者将信息存储在本地如:localstorage

**Comment by kuhf** [comment]
可以把方案说具体些吗？
看到AppMain.vue中是有用keep-alive的，但还是会刷新页面。
![default](https://user-images.githubusercontent.com/26669917/39340617-b002a946-4a01-11e8-871c-81275d55b0ab.png)

**Comment by kuhf** [comment]
感谢回复，移除include后，页面不会自动刷新了。
现在存在另外一个问题，切换TAB页时，出现短暂的空白等待，页面数据量大时等待时间较长，可有破法？

**Comment by PanJiaChen** [comment]
这就是优化相关的问题，最简单的方法，加一个好看点的loading。其它方面的优化需要结合具体业务和需求来看。

**Comment by kuhf** [comment]
感谢！ @PanJiaChen
