### ISSUE TITLE
富文本组件不能使用

### ISSUE THREAD

**Issue by y1006417797** [PanJiaChen/vue-element-admin#3999]
引入后https://cdn.jsdelivr.net/npm/tinymce-all-in-one@4.9.3/tinymce.min.js访问不到

**Comment by ankns** [comment]
感觉是这CDN(台湾的ip地址)，ban掉大陆内的ip了。

**Comment by y1006417797** [comment]
> 感觉是这CDN(台湾的ip地址)，ban掉大陆内的ip了。

**Comment by daisty** [comment]
> 

那咋办呢，线上项目用的这个突然不能编辑了，大佬能帮忙换个cdn地址吗

**Comment by Mydingyan** [comment]
也是一样，怎么解决呀

**Comment by whateveryoudo** [comment]
换个地址吧，或者使用npm，网上给了部分解决办法[https://blog.csdn.net/qq_35430000/article/details/124838639?spm=1001.2014.3001.5501](url)
