### ISSUE TITLE
相应大家需求开了一个qq群 591724180 大家自行加

### ISSUE THREAD

**Issue by CHCP** [PanJiaChen/vue-element-admin#4]
RT

**Comment by PanJiaChen** [comment]
目前只是第一版，后期还会不断完善，同时会写一些配套的教程，所以还是欢迎通过issue方式来交流，不断完善项目。

**Comment by Tao-Quixote** [comment]
弱弱地问一句：配套文章什么时候上线，等的好焦急啊

**Comment by PanJiaChen** [comment]
最近业务有些多，今天明天会先出一篇基础搭建的文章

**Comment by xsstc1** [comment]
你好，请问在点击删除按钮的时候弹出[Popover](http://element.eleme.io/#/zh-CN/component/popover#qian-tao-cao-zuo)，然后再点击确定后再删除，这个可以加上吗，正在学习，自己做一直出错

**Comment by andy0566** [comment]
好主意，等待微信群的到来

**Comment by xiaojuner** [comment]
辣么微信群呢~~

**Comment by Tao-Quixote** [comment]
我觉着可能是主人比较忙，不想在管理微信群方面耗费太多的时间，那么我提个建议：

由我来建一个微信群，方便大家交流，不知肿么样？
如果大家感觉可以的话，欢迎+我的微信：a34347901a
二维码如下：
![](https://github.com/Tao-Quixote/stylus-doc/blob/master/static/assets/images/QRcode.jpg?raw=true)

注：本人也是一个前端开发，在后台项目的开发中也在使用element。我不是骗子，也不搞各种销售，大家可以放心。

**Comment by CHCP** [comment]
我觉得可以啊，目前star数量已经超千了，群主的努力得到了大家的认可。群主确实可能比较忙，最好群主的同意，才师出有名。@PanJiaChen

**Comment by PanJiaChen** [comment]
已开qq群 591724180 自加

**Comment by PanJiaChen** [comment]
但本群本人基本不维护。
