### ISSUE TITLE
login页面，出现滚动条时，页面底部显示空白。

### ISSUE THREAD

**Issue by phoenix110** [PanJiaChen/vue-element-admin#404]
![image](https://user-images.githubusercontent.com/2277339/35027390-5fe354ca-fb8b-11e7-8b67-b8d12e12c150.png)
如图，当缩小窗口到出现滚动条的情况，会发现页面底部出现空白的情况。

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/700e08b7951e9b6947ec0521af93354280776b2e
