### ISSUE TITLE
Is it possible to hide the sidebar at mobile? 

### ISSUE THREAD

**Issue by javapad** [PanJiaChen/vue-element-admin#405]
Hi!  Can the sidebar hide at mobile phone like vue-admin ( https://admin.vuebulma.com/ )?
thanks...

**Comment by PanJiaChen** [comment]
This project is not ready to support mobile. If you want simple hide the sidebar, you can ` window.addEventListener('resize', resizeFunction)`, in the  `resizeFunction` set the sidebar closed.
After that I come to do a simple adaptation for mobile.

**Comment by PanJiaChen** [comment]
v3.6.6 is support this.
