### ISSUE TITLE
⚡️是时候使用 Vue3 了

### ISSUE THREAD

**Issue by zclzone** [PanJiaChen/vue-element-admin#4068]
想升级和体验Vue3 + Vite的可以试试 [Vue Naive Admin](https://github.com/zclzone/vue-naive-admin)，简洁、清新、优雅，基于vite3+Vue3+Naive UI+Pinia+Unocss，全部使用最新的技术栈，js和ts版本都有。

- 预览：https://template.qszone.com
- github： https://github.com/zclzone/vue-naive-admin

**Comment by LiuShuo6** [comment]
学习了~
