### ISSUE TITLE
token如何存储在本地cookie？

### ISSUE THREAD

**Issue by jiangzhiguos** [PanJiaChen/vue-element-admin#408]
![image](https://user-images.githubusercontent.com/26242617/35092238-ba7b5600-fc79-11e7-86e7-6427aaaa1b41.png)
问题就是这个token值 保存不了，一刷新就没了？请问该如何解决？

**Comment by PanJiaChen** [comment]
不知道你想表达什么问题。如你自己项目有问题请提供更多信息。

**Comment by jiangzhiguos** [comment]
![image](https://user-images.githubusercontent.com/26242617/35094061-276291ca-fc7f-11e7-809a-169c0e3f1f1d.png)
![image](https://user-images.githubusercontent.com/26242617/35094082-33ba774e-fc7f-11e7-988b-8c82a899eda7.png)
就是yishuacxu一刷新页面，admin-token 就没了，然后就得重新登录才行。

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/35101973-72dfdf96-fc9c-11e7-9e8f-91bfeba3ac17.png)
你个人token赋值有问题。而且本项目只是一个demo，具体token是什么值或者登录鉴权判断是什么，请结合自己业务来写。
