### ISSUE TITLE
动态根据权限生成路由表

### ISSUE THREAD

**Issue by jiangzhiguos** [PanJiaChen/vue-element-admin#409]
请问下，如何根绝后端接口返回的数据，动态根据权限生成路由表？ 有demo示例吗？

**Comment by PanJiaChen** [comment]
Duplicate of #293
Trace #167

**Comment by jiangzhiguos** [comment]
你好，就是根据返回的接口，动态生成权限路由表，我看了你给我发的issue，我还是有点不明白，不知道该怎么写。



821565062@qq.com
 
发件人： 花裤衩
发送时间： 2018-01-18 22:18
收件人： PanJiaChen/vue-element-admin
抄送： jiangzhiguos; Author
主题： Re: [PanJiaChen/vue-element-admin] 动态根据权限生成路由表 (#409)
Duplicate of #293
Trace #167

**Comment by RainingNight** [comment]
同求啊， #293 里面一大堆，乱七八糟的，都看懵逼了，还是不知道如何根据后端接口生成菜单！！！！
