### ISSUE TITLE
菜单路由那里为何没有noDropdown字段来判断是否有二级菜单了？

### ISSUE THREAD

**Issue by fantasy525** [PanJiaChen/vue-element-admin#410]
# 以下问题是我自己的理解得出的结论，如有错误请指正
## 问题
+ 之前我在简易模板的permission-control分支看到是通过noDropdown字段来判断是有二级菜单，从而决定展示位一个link还是可点击的菜单的，怎么现在的版本换成用children.length===1来决定了？
```  javascript
   // 新的逻辑
   <router-link 
        v-if="item.children.length===1 && !item.children[0].children" 
        :to="item.path+'/'+item.children[0].path" 
        :key="item.children[0].name"
      >
  // 旧的逻辑
 <router-link
   v-if="!item.hidden&&item.noDropdown&&item.children.length>0" 
   :to="item.path+'/'+item.children[0].path"
 >  
```
## 场景
+ 按照新的逻辑，我的理解是无法实现下面的这个场景的。
+ 需求：某一级菜单栏下可能有一个或多个子菜单展示，但是要求不管几个，样子都统一。
+ 具体场景：本次登录后某一级菜单只有一个子菜单，那么就会展示位一个link,下次登录后该一级菜单的children数量增加了一个，那么就会展示有下拉箭头的link,点击后是二级菜单。这样用户看到的样子会不一致
## 期望
我目前想到的是仍然用noDropdown来标记该一级菜单如何展示，但是不太理解你们的逻辑是处于什么考虑，是有人提过可能出现什么bug还是建议之类的？
 请给指明一个优雅的实现思路满足上述需求

**Comment by PanJiaChen** [comment]
这个建议可以，会恢复noDropdown字段来覆盖默认children.length===1不显示一级菜单的判断。

**Comment by PanJiaChen** [comment]
已新增了 `alwaysShow` 属性，当设置了alwaysShow属性就不会根据子路由的多少来判断是否有子菜单。
https://github.com/PanJiaChen/vue-element-admin/commit/6f2a7ce8040aa759ff8464d1267b1c1ab11d1d73
