### ISSUE TITLE
vue3 + vite，代码结构简洁容易上手（有electron版本）

### ISSUE THREAD

**Issue by 1esse** [PanJiaChen/vue-element-admin#4100]
[vue-clownfish-admin](https://github.com/1esse/vue-clownfish-admin) 是一个由Vue最新技术栈开发的后台管理前端简易框架。代码结构非常简洁容易上手！基于vue3，集成vue3最新生态系统的核心库实现。主要的技术栈有
[ES2015+](http://es6.ruanyifeng.com/)，[typescript](https://www.typescriptlang.org/zh/)，[vue3](https://staging-cn.vuejs.org)，[pinia](https://pinia.vuejs.org/)，[vue-router](https://router.vuejs.org/zh/)，[vite](https://cn.vitejs.dev/)，[antd](https://antdv.com/)。

[在线预览](https://1esse.github.io/vue-clownfish-admin)

[在线预览](https://jesse2hao.gitee.io/vue-clownfish-admin)（国内网络访问）

**Comment by ikcro** [comment]
小星星送给你
