### ISSUE TITLE
npm 下载依赖还是报错, git config --global url."https://".insteadOf git://  这条命令也执行了

### ISSUE THREAD

**Issue by ALEXMORCER87** [PanJiaChen/vue-element-admin#4124]
![(YTOYH%G$TCGHS8 M0U8)HS](https://user-images.githubusercontent.com/75532991/215881846-36248750-f4fb-4535-952d-a74014f3aa95.png)

**Comment by wzc520pyfm** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/4108

**Comment by wzc520pyfm** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/4111

**Comment by ALEXMORCER87** [comment]
![image](https://user-images.githubusercontent.com/75532991/216505624-f0c3a3aa-f2dd-4dd6-8261-dfc7eb7d7db1.png)

该删的都删了，除了警告，又出现了python的错误

**Comment by wzc520pyfm** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/24
