### ISSUE TITLE
tagsView页签组件  在同个路由页面不同ID下同时为active状态

### ISSUE THREAD

**Issue by stefor22** [PanJiaChen/vue-element-admin#414]
在判断tag是否active状态函数：
isActive(route) {
      return route.path === this.$route.path || route.name === this.$route.name
},

我项目中文章详情路由为 ‘/article/：id’的形式，导致了如果同时打开2个不同ID的详情页面，虽然path是不同的，但是route.name相同，造成同时active的情况。

只是个小问题了，想知道大神这类路由是怎么实现的。。

**Comment by PanJiaChen** [comment]
很难，因为keep-alive目前的机制就是通过name-key来区分的。暂时是做不了的。

**Comment by stefor22** [comment]
我这边暂时改成判断path和name都要相同才为active，多谢comment

**Comment by EugeniaZhang** [comment]
我也碰到了这个问题，两个不同id的详情页数据展示相同，用path和name同时判断也不起作用，请大神们帮忙解决下哈 @PanJiaChen @stefor22

**Comment by chengmanxiang** [comment]
加详情页面多个不会同时增加到左则的路由菜单上吗？

**Comment by zhanganyi** [comment]
@stefor22  我也遇到了你这个问题，请问你是怎么解决的？谢谢，另附上：生活愉快！

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/0a196f79ba4bbb78a5ebdbc34a7522468e0e2c48/src/views/layout/components/TagsView.vue#L61-L63

改成
```js
 return route.path === this.$route.path
```

**Comment by PanJiaChen** [comment]
已增加[demo](http://panjiachen.github.io/vue-element-admin/#/example/list)
