### ISSUE TITLE
 插入图片之后图片无法通过鼠标拖住来实现放大和缩小，也不能通过拖拽来控制位置

### ISSUE THREAD

**Issue by HDUysz** [PanJiaChen/vue-element-admin#4158]
## Question（提问）

插入图片之后图片无法通过鼠标拖住来实现放大和缩小，也不能通过拖拽来控制位置

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/91298472/235308552-928efaec-9f8d-474c-9a93-0e52c59567eb.png)

#### Link to minimal reproduction（最小可在线还原demo）

我并没有修改原来的代码，而是查找了很多GitHub上的提问，大多都是由于css引入错误导致的，但是我在使用作者的代码的时候，并没有发现css引入的报错出现在console中，而且我翻阅作者之前的回答的时候，发现作者提到了imagetools，但是我发现作者已经在代码中引入了imagetools，并且在线的demo中我也可以使用imagetools，不过说实话，图片直接实现拖拽放大和缩小，我在tinymce的issue中看到别人说无需引入任何插件理论上就可以实现，不是imagetools的作用，imagetools的作用应该是作者的demo中实现的左右翻转之类的功能，而我在使用作者的demo的时候，同样发现图片不能拖拽放大和缩小，但是在tinymce的官方文档中，这个功能是实现了的，因此我感到很迷惑，搜索了一天也没有解决办法，因此想要来向作者提问一下，是否有解决的办法，因为我直接下载了code之后，在本地连imagetools的插件功能也没有得到实现，这令我很困惑。

#### Other relevant information（格外信息）
- Your OS: Windows
- Node.js version: 8.11.0
- vue-element-admin version:  应该是最新版，刚下载不久

**Comment by gshohat** [comment]
嗨 @HDUysz，
您要在应用程序中的哪个位置尝试调整照片大小？我会重现错误

**Comment by HDUysz** [comment]
> 嗨 @HDUysz， 您要在应用程序中的哪个位置尝试调整照片大小？我会重现错误

正如你在上面的截图中看到的，我想要在tinymce的输入框中调整图片的大小，具体来说，我会先往输入框中插入一张图片，然后我会尝试使用鼠标拖拽去控制它的大小

**Comment by HDUysz** [comment]
> 嗨 @HDUysz， 您要在应用程序中的哪个位置尝试调整照片大小？我会重现错误

![image](https://user-images.githubusercontent.com/91298472/235344162-2d52030e-3534-49a8-b2d9-076d76cbffa1.png)
在官方的文档中，我点击图片会出现这样一个蓝色的框框，然后我就可以拖拽图片让他变大或者变小，但是现在我的项目中无法呈现这样的功能

**Comment by gshohat** [comment]
@HDUysz  you mean in the tinyMce component?

**Comment by gshohat** [comment]
@HDUysz  你的意思是在 tinyMce 组件中？

**Comment by gshohat** [comment]
@HDUysz 这是你想要达到的目标吗？

https://user-images.githubusercontent.com/91323932/235345059-07e8c28e-377b-48a7-be5f-0220acb428c5.mov

**Comment by HDUysz** [comment]
> @HDUysz 这是你想要达到的目标吗？
> 
>  Screen.Recording.2023-04-30.at.12.06.47.mov

是的！这就是我想达到的目标，请问我的代码中是由于出了什么问题，导致我无法使用这个功能了呢？

**Comment by HDUysz** [comment]
> @HDUysz 这是你想要达到的目标吗？
> 
>  Screen.Recording.2023-04-30.at.12.06.47.mov

我是直接在这个项目中下载的代码，我是应该添加一些代码来完成这个功能吗？

**Comment by HDUysz** [comment]
> 

请问你还在关注这个问题吗，如果你能够帮助我，我会非常感谢! orz

**Comment by HDUysz** [comment]
> @HDUysz 这是你想要达到的目标吗？
> 
>  Screen.Recording.2023-04-30.at.12.06.47.mov

请问你还在关注这个问题吗，如果你能够帮助我，我会非常感谢! orz

**Comment by HDUysz** [comment]
> @HDUysz 这是你想要达到的目标吗？
> 
>  Screen.Recording.2023-04-30.at.12.06.47.mov

https://user-images.githubusercontent.com/91298472/236417724-88bef843-3bf8-4725-8ead-0c996f3f8c8b.mp4

如果你还有疑问的话，请你看我的效果，如果您有阅读到我的回信，请你回复我好吗

**Comment by HDUysz** [comment]
> @HDUysz 这是你想要达到的目标吗？
> 
>  Screen.Recording.2023-04-30.at.12.06.47.mov

如果你还有疑问的话，请你看我的效果，如果您有阅读到我的回信，请你回复我好吗

https://user-images.githubusercontent.com/91298472/236418182-11bbdac3-c4ff-4267-a923-cafd0a920620.mp4

**Comment by HDUysz** [comment]
@gshohat 如果你还有疑问的话，请你看我的效果，如果您有阅读到我的回信，请你回复我好吗。再次感谢你。

https://user-images.githubusercontent.com/91298472/236418447-bcf9d007-49da-481d-9535-a35e9df4d7ec.mp4

**Comment by HDUysz** [comment]
> @HDUysz 这是你想要达到的目标吗？
> 
>  Screen.Recording.2023-04-30.at.12.06.47.mov

你好！今天我发现可以用css3中的“resize”属性来完成这个功能，但是我在使用这个属性的时候必须要在img外面套上一层div，这让我出了一些bug，我发现使用了“resize”之后我实现了和你相似的效果，你可以分享一下你的实现过程吗

**Comment by HDUysz** [comment]
> > @HDUysz 这是你想要达到的目标吗？
> > Screen.Recording.2023-04-30.at.12.06.47.mov
> 
> 你好！今天我发现可以用css3中的“resize”属性来完成这个功能，但是我在使用这个属性的时候必须要在img外面套上一层div，这让我出了一些bug，我发现使用了“resize”之后我实现了和你相似的效果，你可以分享一下你的实现过程吗

![image](https://github.com/PanJiaChen/vue-element-admin/assets/91298472/41552c11-ec93-4f57-86fd-3d0bda738e58)
感谢你，我已经找到了原因，是因为作者设置了这个配置项的缘故，我只要把它改成true就可以使用tinymce自带的resize了
