### ISSUE TITLE
addRoutes后，我换一个账号登录权限不一样了，怎么删除之前添加的的路由？

### ISSUE THREAD

**Issue by SherwinChan** [PanJiaChen/vue-element-admin#416]
目前是判断权限生成可访问的路由后addRoutes进去。但是退出登录后换一个账号登录，然后又重新生成一次，之后addRoutes。
问题1：控制台会警告提示[vue-router] Duplicate named routes，就是有重复的路由add进去了。
问题2：可能存在，直接输入地址栏跳转到前一账号可访问的路由（目前是在输地址栏后跳转，整个单页应用会重新init一次，根据当前缓存的账号权限重新生成routes，此问题暂时好像不需要解决）

会不会有方法去删除已经添加的routes？我看过vue-router的文档没有写这个方法。

**Comment by PanJiaChen** [comment]
暂时没有remove routes的方法。所以现在的做法是退出登录之后刷新一下页面。
https://github.com/PanJiaChen/vue-element-admin/blob/700e08b7951e9b6947ec0521af93354280776b2e/src/views/layout/components/Navbar.vue#L74-L77

**Comment by leonwjy** [comment]
同样，当session丢失之后，切换不同权限当账号登陆，那么新的权限菜单不会被立即重新生成，需要刷新页面。

**Comment by PanJiaChen** [comment]
官方相关 issue: https://github.com/vuejs/vue-router/issues/1234

**Comment by caryxiao** [comment]
我的做法是直接location.reload() 跟 @PanJiaChen 一样.... 😂

**Comment by renxianyang** [comment]
router.matcher，了解一下~

**Comment by TY-LIU** [comment]
`const createRouter = () => new VueRouter({
    linkActiveClass: 'active',
    mode: 'hash',
    base: './',
    routes: constantRouterMap
});

const router = createRouter();`

`router.matcher = createRouter().matcher;
router.addRoutes(store.getters.addRouters);`

在addRoutes之前重置matcher 即可解决

**Comment by PanJiaChen** [comment]
@TY-LIU 这个方法可行，4.0版本已经基于这个实现了路由的重置。

之后会写一份文档来说明。

**Comment by pekonchan** [comment]
> @TY-LIU 这个方法可行，4.0版本已经基于这个实现了路由的重置。
> 
> 之后会写一份文档来说明。

请问你在哪里得知4.0版本已经基于这个实现了路由的重置？我也想看看相关资料，谢谢

**Comment by lijin0523** [comment]
router.matcher = createRouter().matcher;
登出的时候resetRouter之后,在登录为什么会报错，刷新就没事了呢
[vue-router] Failed to resolve async component default: Error: Cannot find module './[object Object]/index'
