### ISSUE TITLE
问一下第三方登录时 window.addEventListener('hashchange', this.afterQRScan) 这个事件没触发怎么回事

### ISSUE THREAD

**Issue by luyuanx2** [PanJiaChen/vue-element-admin#417]
弹出窗口二维码扫描后已经重定向到我服务器了，服务器继续重定向到/authredirect,直接跳到了登录页,弹出窗也没关闭

**Comment by PanJiaChen** [comment]
确定这里写的对么？
https://github.com/PanJiaChen/vue-element-admin/blob/700e08b7951e9b6947ec0521af93354280776b2e/src/views/login/authredirect.vue#L6

**Comment by luyuanx2** [comment]
http://192.168.1.55:8999/authredirect?code=0715ltnt1AKiub0WmZkt111int15ltn5这是我服务端重定向的地址，是通过微信重定向的redirect参数和code参数拼接起来的，但是浏览器地址栏里面显示http://192.168.1.55:8999/authredirect?code=0715ltnt1AKiub0WmZkt111int15ltn5#/，多了个#这个地址直接跳到/dashboard,然后跳到登录页面，authredirect组件里面的created()方法也就没执行

**Comment by PanJiaChen** [comment]
建议使用history模式。
https://router.vuejs.org/zh-cn/essentials/history-mode.html

**Comment by luyuanx2** [comment]
使用history模式地址正常了,没有跳转到/dashboard,但是跳转到/authredirect?code=0715ltnt1AKiub0WmZkt111int15ltn5，这个地址不在白名单，被重定向到/login了，而在白名单的是/authdirect

**Comment by PanJiaChen** [comment]
本来就是用的hash 所以没什么关系 主要是你之前路由不对 多了一个`#/`

**Comment by luyuanx2** [comment]
现在还有个问题，我第一次访问登录页，也会触发window.addEventListener('hashchange', this.afterQRScan) ，直接弹出alert('第三方登录失败')

**Comment by PanJiaChen** [comment]
只有hash变化才会触发hashchange

**Comment by luyuanx2** [comment]
那我怎样才能访问登录页不触发hashchangge事件

**Comment by PanJiaChen** [comment]
我怎么知道你怎么写的

**Comment by luyuanx2** [comment]
我没写代码，我只是把你原来的注释的第三方登录代码打开了，然后访问登录页就触发了hashchange事件

**Comment by PanJiaChen** [comment]
并不会
