### ISSUE TITLE
建议树形表格展开加个动画

### ISSUE THREAD

**Issue by zhi3210happy** [PanJiaChen/vue-element-admin#424]
建议树形表格展开加个动画。

**Comment by leij1ang** [comment]
将`TreeTable/index.vue`中的`showRow`返回修改成`return show ? 'animation:treeTableShow 1s' : 'display:none;'`
并且加个css就好啦
```
<style rel="stylesheet/css">
  @keyframes treeTableShow {
    from {opacity: 0;}
    to {opacity: 1;}
  }
</style>
```
**切记<style>不是`scoped`**

**Comment by PanJiaChen** [comment]
已不再维护 tree-table.
