### ISSUE TITLE
阿里图标下载的图片默认颜色无法改变

### ISSUE THREAD

**Issue by haoganduomai** [PanJiaChen/vue-element-admin#425]
path内被加入了 fill=‘#xxxx’ 属性，但是这个svg-sprirt-loader怎么剔除？

**Comment by PanJiaChen** [comment]
https://github.com/svg/svgo/blob/master/plugins/removeUselessStrokeAndFill.js

使用[svgo](https://github.com/svg/svgo) 来处理。

**Comment by tongxin2013** [comment]
fill=“”就可以设置颜色了
