### ISSUE TITLE
您好我想问下,router使用了history模式标签页会刷新呢？而hash模式则不会？

### ISSUE THREAD

**Issue by wangdabaoqq** [PanJiaChen/vue-element-admin#426]

**Comment by PanJiaChen** [comment]
需要更加详细的重现步骤或者提供更加详细的详细。

**Comment by wangdabaoqq** [comment]
这个是history模式。
[history](http://ou2hsk5xb.bkt.clouddn.com/578cb7306e63f31f.gif)

**Comment by PanJiaChen** [comment]
完全不知道你想表达什么。请重新整理的问题和重现步骤。

**Comment by wangdabaoqq** [comment]
问题是这样的,就是在路由上,我使用了history模式,只要我去点击tag标签整个页面就会刷新,而hash模式则不会。所以我想问下,可能造成的原因有那些情况？

**Comment by PanJiaChen** [comment]
并不能重现你的问题。若不能提供可重现的最小demo，则认为是个人代码问题。

**Comment by wangdabaoqq** [comment]
我去检查检查代码，抱歉麻烦了？




| |
王凯
邮箱：wangdabao221@163.com
|

签名由 网易邮箱大师 定制

在2018年01月29日 20:19，花裤衩 写道：

并不能重现你的问题。若不能提供可重现的最小demo，则认为是个人代码问题。

**Comment by wangdabaoqq** [comment]
打错了最后是句号。





| |
王凯
邮箱：wangdabao221@163.com
|

签名由 网易邮箱大师 定制

在2018年01月29日 20:20，宝宝宝 写道：
我去检查检查代码，抱歉麻烦了？




| |
王凯
邮箱：wangdabao221@163.com
|

签名由 网易邮箱大师 定制

在2018年01月29日 20:19，花裤衩 写道：

并不能重现你的问题。若不能提供可重现的最小demo，则认为是个人代码问题。
