### ISSUE TITLE
刷新建议

### ISSUE THREAD

**Issue by JllRogen** [PanJiaChen/vue-element-admin#427]
希望在tags-view那一条上加上一个刷新按钮,  以便可以手动重新加载当前view的数据

**Comment by PanJiaChen** [comment]
目前vue不改变路由刷新component是比较困难的事情，我目前通常的项目中常用的方案是router先重定向到一个代理业马上在replace回来，体验还可以但不算很完美。所以刷新操作我在考虑一下好的实现方案吧。

**Comment by zhengybo** [comment]
可以通过 v-if 对router-view 进行判定 ， 同时移除cache ，再恢复后增加 cache可以解决。

**Comment by PanJiaChen** [comment]
@zhengybo 你说的这个方案并不能在不改变路由的情况下刷新component组件啊。

**Comment by zhengybo** [comment]
这个是手动刷新的，改变路由的话同样的方法，自己封装一个组件(link-to)单独进行跳转在跳转的时候进行判定，判定方式和手动的一样，可以做到 改变url进行跳转 同时更新(先移除缓存跳转后在添加上)跳转到的路由。

**Comment by PanJiaChen** [comment]
@zhengybo 所以你这个不就是我最早说的方案么。。。

**Comment by zhengybo** [comment]
一样？你不是是通过给url后面加时间戳 的方式哇。。。 我看漏了？

**Comment by Samdyddd** [comment]
可不可以这样？点击左侧的是刷新组件，获取最新数据；顶部的tabView是缓存的数据？

**Comment by PanJiaChen** [comment]
Add in https://github.com/PanJiaChen/vue-element-admin/pull/1033
