### ISSUE TITLE
建议写一个 sytlus 版本的项目,  我电脑老是提示node-sass 安装不了,  而且要依赖ruby, 如果是stylus就没有这么多依赖了

### ISSUE THREAD

**Issue by JllRogen** [PanJiaChen/vue-element-admin#428]

**Comment by PanJiaChen** [comment]
暂时不考虑，有需求的可以自行替换。目前`element-ui`的样式也会使用`sass`编写。当你想复写`element-ui`样式的时候配合`sass`是很方便的，详情见[文档](http://element-cn.eleme.io/#/zh-CN/component/custom-theme)
