### ISSUE TITLE
Component menu open, sub menu items can not display all, due to scroll bar not work组件菜单展开后，没有下拉框，菜单显示不全

### ISSUE THREAD

**Issue by linjohn527** [PanJiaChen/vue-element-admin#429]
Component menu open, sub menu items can not display all, due to  scroll bar not work.组件菜单展开后，没有下拉框，菜单显示不全

**Comment by PanJiaChen** [comment]
Can you provide more detailed information or screenshots?

**Comment by chiu0602** [comment]
On the [demo site](http://panjiachen.github.io/vue-element-admin/), full menu on the left cannot be fully shown on my screen. I have to use mouse wheel to scroll. Is it possible to implement a vertical scroll bar for the menu if the content is not enough to be shown? Thanks

**Comment by PanJiaChen** [comment]
I think the scroll bar is ugly, not really want to add.

**Comment by chiu0602** [comment]
The scroll bar can be thin, it able to let people briefly know the height of your menu, and help those who used to use the scroll bar instead of the wheel ([example](http://akveo.com/blur-admin-mint/#/dashboard))

**Comment by PanJiaChen** [comment]
Added in https://github.com/PanJiaChen/vue-element-admin/releases/tag/v3.7.0
