### ISSUE TITLE
Request is not sent, remember comment mock code!

### ISSUE THREAD

**Issue by huangbuyi** [PanJiaChen/vue-element-admin#430]
I am a new user, it waste my many hours to solve this silly problems. By the way, if `roles` is set as a empty array after `getUserInfo`, infinite loop request will bomb your server.

**Comment by PanJiaChen** [comment]
I cannot reproduce this problem locally. Please provide more information.

**Comment by huangbuyi** [comment]
1. Mockjs intercept my AJAX request, I don't find out at beginning.
2.When `roles` is a empty array before navigate to no-whiteList route, it will dispatch `GetUserInfo` and set `roles`. If new `roles` is still a empty array, it will dispatch again and again.

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/09e613b33a2779f7f839b7ec49ab9083a715c5dc/src/permission.js#L27

In this project , `GetUserInfo` must return a roles. 

But there really is a need to improve, then l wii add a check to ensure that you return the data format is correct to avoid a lot of strange problems。
