### ISSUE TITLE
TreeTable怎么做到静态刷新列表?

### ISSUE THREAD

**Issue by blueway** [PanJiaChen/vue-element-admin#432]
如题

**Comment by leij1ang** [comment]
请详细描述一下

**Comment by blueway** [comment]
不请求后台接口数据，直接刷新树形结构数据。看了代码，好像不行。

**Comment by leij1ang** [comment]
数据有变更么，没变更的话，刷新树结构我觉得没必要

**Comment by blueway** [comment]
当然是有数据变化了，不然为什么要刷新，只是现在直接重新请求接口数据的话，整个数的状态就变了。

**Comment by PanJiaChen** [comment]
`element` 2.7.0 支持 `tree-tale 了`。所以 `vue-element-admin`就不再自己维护 `tree-table`了。
