### ISSUE TITLE
themePicker代码写法

### ISSUE THREAD

**Issue by sunchenguang** [PanJiaChen/vue-element-admin#436]
```
const getHandler = (variable, id) => {
        return () => {
          const originalCluster = this.getThemeCluster(ORIGINAL_THEME.replace('#', ''))
          const newStyle = this.updateStyle(this[variable], originalCluster, themeCluster)

```
这里`this[variable]`其实就是请求回来的`element-ui theme-chalk`的css文本字符串，而且是不变的。
一开始以为它是代表当前被替换过颜色变量的`theme-chalk css`，还疑问为啥还要再去拿一次`originalCluster` ，后来仔细看才明白。

挂在`this`上，下意识的以为它是变化的

你看是否要加注释或者改改代码。

**Comment by PanJiaChen** [comment]
不觉得有什么问题。而且这里和element官方写法保持一致，所以暂时不准备修改代码。

**Comment by sunchenguang** [comment]
查到官方代码了，好吧
