### ISSUE TITLE
[Feature]:add a redirect url when not logged in 

### ISSUE THREAD

**Issue by PanJiaChen** [PanJiaChen/vue-element-admin#438]
When not logged in, accessing a page will be redirected to the login page.
Hope to remember before visiting the url, when the landing is successful will be redirected to the front of the page you want to visit.
Such as: 
`https://github.com/PanJiaChen//login?redirect=https://github.com/PanJiaChen//table/list`

**Comment by zhangzunke** [comment]
Hi guys, do you have a plan to implement this feature?

**Comment by PanJiaChen** [comment]
Added in #1046
