### ISSUE TITLE
how to add new plugin to tinymce

### ISSUE THREAD

**Issue by minikiller** [PanJiaChen/vue-element-admin#440]
i want to add a new plugin to tinymce, i add code to 
```
plugins: 'advlist,autolink,code,fullpage,paste,textcolor,
```
fullpage is what i want to add to tinymce. when i run program, it show error 
```
Failed to load plugin: fullpage from url http://localhost:8282/static/tinymce/plugins/fullpage/plugin.min.js
```

I want to know how to add new plugin,thanks

**Comment by PanJiaChen** [comment]
It my falut. Now, the current tinymce.js used in this project is not complete code, I used [Build Customizer](https://www.tinymce.com/download/custom-builds/) to customize the plugin, so you can download the complete tinymce.js Or you  can also customize the code to reduce the bundle size by yourself.

Later, I will update this tinymce to the full plugins.

**Comment by minikiller** [comment]
thanks for your quickly response! it works now!
