### ISSUE TITLE
多层路由嵌套，如何正确显示？

### ISSUE THREAD

**Issue by BangKk** [PanJiaChen/vue-element-admin#442]
例如这样的路由配置：
`[{name: 'user', path: '/user', component: User, children: [
   {name: 'userDetail', path: ':id', component: UserDetail}
]}]`
通过组件嵌套 router-view 可以显示出组件，但是在/user/:id页面，需要隐藏User组件，只显示UserDetail组件，是如何做到的？

**Comment by PanJiaChen** [comment]
所以你为什么要选择嵌套路由的方式呢？平级不就好了。

**Comment by BangKk** [comment]
面包屑的地方需要 “/用户 /用户详情”，如果用嵌套的话，可以拿到正确嵌套的matched进行遍历。
而且你的demo里面也是嵌套的，不过demo里面好像没涉及到类似/user/:id的路由，所以想请教一下。

**Comment by BangKk** [comment]
另外，还想请教下 router-view 和 keep-alive 一起用，router-view 的标签上是不是不能用 :key, 类似这样：
 `<keep-alive>
          <router-view :key="$route.fullPath"></router-view>
   </keep-alive>`
这样用了之后，标签(tagsView) 切换时，组件mounted阶段的请求会发起多次。但是updated 和 mounted 只执行了一次。

**Comment by PanJiaChen** [comment]
首先回答第一个问题：只想面包屑有多级，创建一个空的`router-view`就行了，后面那段话没怎么理解。

第二个问题：
> 组件mounted阶段的请求会发起多次。但是updated 和 mounted 只执行了一次

前后矛盾的问题啊。。。

**Comment by Mr-arvin** [comment]
我添加了下一级路由，table/test01和table/test02也都有，但每次点击test01和test02都会跳转404页面：
children: [
          { path: 'test01', component: _import('table/test01'), name: 'test01', meta: { title: 'test01' }},
          { path: 'test02', component: _import('table/test02'), name: 'test02', meta: { title: 'test02' }},
        ]

------------------- 全部内容显示为-------------------
export const asyncRouterMap = [  
  {
    path: '/example',
    component: Layout,
    redirect: '/example/table',
    name: 'Example',
    meta: { title: 'example', icon: 'example' , roles: ['admin','editor']},
    children: [
      {
        path: 'table',
        name: 'Table',
        component: _import('table/index'),
        meta: { title: 'Table', icon: 'table', roles: ['admin']  },
        redirect: 'noredirect',
        children: [
          { path: 'test01', component: _import('table/test01'), name: 'test01', meta: { title: 'test01' }},
          { path: 'test02', component: _import('table/test02'), name: 'test02', meta: { title: 'test02' }},
        ]
      },
      {
        path: 'tree',
        name: 'Tree',
        component: _import('tree/index'),
        meta: { title: 'treeTable', icon: 'tree', roles: ['admin','editor']  }
      }
    ]
  }
]

**Comment by BangKk** [comment]
嗯嗯，我的表达有些问题。。。
第一个问题我想要的效果是：
1.嵌套路由的父组件和子组件不要同时渲染在一个页面。
2.能拿到嵌套好的matched给面包屑用。
但是路由的嵌套意味着渲染组件的时候也必须用 router-view 嵌套，导致父组件和子组件同时出现在页面中。
第二个问题我再描述清楚一些。
组件的代码大概是这样的：
`
  updated() {
     console.log('updated');
  }
  mounted() {
    get('something'); // 请求
    console.log('mounted');
  }
`
这个组件对应的路由类似这样 /order/:id。
我对你的 tagsView 组件进行了改造，相同name的组件只会渲染一个tab。因此，id发生变化时，因为
`<router-view :key="$route.fullPath"></router-view>`
中 key绑定的 fullPath 的缘故，组件会被缓存下来。
然后就会出现我说的那种情况：比如id变了两次，就会发起两次请求，但是控制台只会打印出一次 updated 和 mounted 。

**Comment by PanJiaChen** [comment]
第一个问题已经解答了 [Nested Routes](https://router.vuejs.org/en/essentials/nested-routes.html)并不是满足你这样的需求的，解决方案也说了设一个空的user router-view。

第二个问题 你自己改造了代码，所以无法定位你的问题。请自行解决。

**Comment by zhu8191553** [comment]
请问解决了吗，我也需要解决相应的问题 @BangKk

**Comment by xiaozhanghui** [comment]
@BangKk 第一个问题大佬，怎么解决的

**Comment by 892390760** [comment]
> 就好了

平级的路由，有没有能够保留之前页面组件dom的方案？

**Comment by 892390760** [comment]
> 所以你为什么要选择嵌套路由的方式呢？平级不就好了。

平级的路由，有没有能够保留之前页面组件dom的方案？

**Comment by Niefee** [comment]
```js
 v-if="$route.path === '/a/b'"
```
我直接使用判断路由是否显示去解决。

**Comment by shmilyxwx** [comment]
加了一个router-view之后那个页面的path怎么写呢,血一样的才能实现效果
这是加了一个router之后的报的错误
Duplicate keys detected: '/merchantManage/netInmerchantsList'. This may cause an update error.

found in

---> <Breadcrumb> at src\components\Breadcrumb\index.vue
       <ElMenu>
         <Navbar> at src\views\layout\components\Navbar.vue
           <Layout> at src\views\layout\Layout.vue
             <App> at src\App.vue
               <Root>

**Comment by Garfield-yin** [comment]
使用一个个空的 <router-view> 展示面包屑试了可行。
`
{ // 展示出来就是 /应用详情/应用部署
    path: 'detail',
    component: () =>
      import('@/views/router-bridge/bridge.vue'),// 这是一个空的router-view
    name: 'detail',
    hidden: true,
    meta: {
      title: '应用详情',
      noCache: true,
      activeMenu: '/store'
    },
    children: [{
      path: 'deploy',
      component: () =>
        import('@/views/app-store/deploy.vue'),
      name: 'DetailDeploy',
      meta: {
        title: '应用部署',
        noCache: true,
        activeMenu: '/store'
      },
      hidden: true
    }]
  }
`

**Comment by hp8980787** [comment]
> 使用一个个空的 展示面包屑试了可行。
> 
> ```
> { // 展示出来就是 /应用详情/应用部署
>     path: 'detail',
>     component: () =>
>       import('@/views/router-bridge/bridge.vue'),// 这是一个空的router-view
>     name: 'detail',
>     hidden: true,
>     meta: {
>       title: '应用详情',
>       noCache: true,
>       activeMenu: '/store'
>     },
>     children: [{
>       path: 'deploy',
>       component: () =>
>         import('@/views/app-store/deploy.vue'),
>       name: 'DetailDeploy',
>       meta: {
>         title: '应用部署',
>         noCache: true,
>         activeMenu: '/store'
>       },
>       hidden: true
>     }]
>   }
> ```

有个bug啊，/ 最高层/应用详情/应用部署,在应用部署页面点击最高层的面包屑，会直接404。必须点击应用详情的面包屑，再点击最高层才可以正常显示。是我写的有问题吗？
