### ISSUE TITLE
路由第三级点击会一直跳转404的问题求解 #nested route could not find

### ISSUE THREAD

**Issue by Mr-arvin** [PanJiaChen/vue-element-admin#444]
现有的目录结构是这样子：
![image](https://user-images.githubusercontent.com/35322029/35656838-66d5c902-0734-11e8-9bad-1ea874d50558.png)

然后路由是这样子的：
![image](https://user-images.githubusercontent.com/35322029/35656861-8bab567a-0734-11e8-8c77-259abcb3e9a3.png)

渲染出来的菜单是这样子的（没有报错）：
![image](https://user-images.githubusercontent.com/35322029/35656809-4809c802-0734-11e8-96ed-2821eab02f49.png)

我把这段单独的代码贴出来：
export const asyncRouterMap = [  
  {
    path: '/example',
    component: Layout,
    redirect: '/example/table',
    name: 'Example',
    meta: { title: 'example', icon: 'example' , roles: ['admin','editor']},
    children: [
      {
        path: 'table',
        name: 'Table',
        component: _import('table/index'),
        meta: { title: 'Table', icon: 'table', roles: ['admin']  },
        redirect: 'noredirect',
        children: [
          { path: 'test01', component: _import('table/test01'), name: 'test01', meta: { title: 'test01' }},
          { path: 'test02', component: _import('table/test02'), name: 'test02', meta: { title: 'test02' }},
        ]
      },
      {
        path: 'tree',
        name: 'Tree',
        component: _import('tree/index'),
        meta: { title: 'treeTable', icon: 'tree', roles: ['admin','editor']  }
      }
    ]
  }
]

但目前所遇到的问题是点击test01和test02的时候，会跳转到404页面，这个问题我参照了vue-element-admin的代码模仿了一遍之后，还是存在，不知道哪里出了问题，求助中。。。

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/35657334-eb9f873e-0736-11e8-8fd6-237dda607504.png)

Should be `path: '/example/table'`

**Comment by Mr-arvin** [comment]
Dear 潘神，我把path改成 path:'/example/table'了，解决了会跳转404的问题👍 。
但现在还有一个问题，就是每次点击test01和test02，/table/test01.vue和/table/test02里面的内容不会显示出来，而每次刷新显示的都是/table/index.vue里面的内容。
如今的路由是：
![image](https://user-images.githubusercontent.com/35322029/35657903-dc1d4f6e-0739-11e8-8ce3-aa418547dca3.png)

**Comment by PanJiaChen** [comment]
`example/table/index` has no  <router-view></router-view>` 
detail see [nested-routes](https://router.vuejs.org/en/essentials/nested-routes.html)

**Comment by Mr-arvin** [comment]
对的，问题已解决, thanks a lot !
