### ISSUE TITLE
el-upload组件的on-progress不能触发

### ISSUE THREAD

**Issue by zangyilin** [PanJiaChen/vue-element-admin#445]
`
<el-upload class="uploader"
			  ref="upload"
			  list-type="picture-card"
			  :show-file-list="false"
			  :action="params.action"
			  :data="params.data"
			  :on-change="uploadOnChange"
			  :on-success="uploadOnSuccess"
			  :on-error="uploadOnError"
			  :on-progress="uploadOnProgress">
     <el-button type="primary">点击上传</el-button>
</el-upload>
`
不知道为啥on-progress永远触发不了，但是单独起个项目，on-progress能被触发

**Comment by PanJiaChen** [comment]
这种问题请去`element-ui` 官方提问 和本项目无关。

**Comment by zangyilin** [comment]
我之前也觉得是element-ui的问题，但是我后来新建了个空项目，然后使用el-upload，没有问题，能触发，然后我把vue文件之前拷贝到这个项目里，on-progress就不能触发。
同时，咱们项目里面也用到了el-upload，我在里面添加on-progress同样触发不了

**Comment by zangyilin** [comment]
多谢

**Comment by gypjoy** [comment]
查找了项目，并没有使用mockjs，但还是没有进度条，作者大大可以在vue-element-admin框架中写个例子吗？

**Comment by chenjiejing** [comment]
请问下我这边上传也遇到这个问题,但是我在这个组件没有用到mock.js还是触发不了on-progress@PanJiaChen

**Comment by gdoudeng** [comment]
感谢这个issue，搞了半天，开始以为更新了vue cli3后element ui打包Loading引入失败，然后看了半天webpack打包，试了element的Loading的各种使用方式，结果打包后就是不行。后来发现有的页面Loading居然是正常使用的，然后我开始觉得是el-upload组件的on-progress方法没触发，结果真的是没触发！！！现在移除了mockjs后一切都正常了。
