### ISSUE TITLE
Electron with Vue.js

### ISSUE THREAD

**Issue by YoussefRekik** [PanJiaChen/vue-element-admin#446]
Please include steps to run this template with electron

**Comment by PanJiaChen** [comment]
l think it is simple use [electron-vue](https://github.com/SimulatedGREG/electron-vue) to generate.
Detail u can see [electron-vue-admin](https://github.com/PanJiaChen/electron-vue-admin).

**Comment by YoussefRekik** [comment]
Is it possible to provide an example of this or update electron-vue-admin to this template ?

**Comment by PanJiaChen** [comment]
No plan.

**Comment by nwashangai** [comment]
Hello please am having similar request, am almost done with my app with this admin, but now I want to make a desktop app, how do I use the electron-vue-admin without recording my work again, or is there a way to run it as electron. 
I just want the simplest way to covert to desktop without coding from scratch again. 

Thanks in advance

**Comment by nwashangai** [comment]
*re-coding
