### ISSUE TITLE
老版本的element1.4升级到2.0之后图标错乱

### ISSUE THREAD

**Issue by maming** [PanJiaChen/vue-element-admin#447]
请问大牛，我之前下的老版本的代码，最近把当时的element-ui1.4升级到2.0，图标错乱的问题该怎么恢复？

**Comment by PanJiaChen** [comment]
移除老版本换肤页面对于旧element style 的引入。
https://github.com/PanJiaChen/vue-element-admin/blob/09e613b33a2779f7f839b7ec49ab9083a715c5dc/src/views/theme/index.vue#L58
