### ISSUE TITLE
打包后token问题

### ISSUE THREAD

**Issue by yuanfuwang** [PanJiaChen/vue-element-admin#453]
store中的代码如下：
return new Promise((resolve, reject) => {
        loginByUsername(username, userInfo.password).then(response => {
          const data = response;
          if (data.code === 0) {
            setToken(data.message)
            commit('SET_TOKEN', data.message)
          } else {
            Message.error(data.message);
            throw new Error()
          }
          resolve()
        }).catch(error => {
          reject(error)
        })
登录调用接口成功后将token保持到cookie中,在开发环境中没有问题，但是通过npm run build:prod命令打包发布后，此处代码无法跑通，如果将setToken(data.message)移除，则可以正常通过。
请问是什么原因造成的这种生产环境和开发环境的差异，谢谢

**Comment by PanJiaChen** [comment]
setToken 只是设置了本地cookie。如有问题请先自行研究和debug，若还有问题请提供更加详细的说明和截图。先关闭此问题了。
