### ISSUE TITLE
文档-“和服务端进行交互”那页“从 mock 直接切换到服务端请求-见 Mock 和联调”中，见 Mock 和联调里没有说明如何切换

### ISSUE THREAD

**Issue by ihwf** [PanJiaChen/vue-element-admin#454]
文档-“和服务端进行交互”那一页“从 mock 直接切换到服务端请求-见 Mock 和联调”中，“Mock 和联调”里没有说明如何从 mock 直接切换到服务端请求
![image](https://user-images.githubusercontent.com/17941662/35805665-b7152fe4-0ab7-11e8-987f-986cef3324b1.png)

**Comment by PanJiaChen** [comment]
感谢你的反馈，之后我会补全这部分文档。

**Comment by PanJiaChen** [comment]
已补上 [文档](https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/mock-api.html#%E6%9C%AC%E5%9C%B0mock%E4%B8%8E%E7%BA%BF%E4%B8%8A%E5%88%87%E6%8D%A2)

**Comment by hertough** [comment]
为什么向服务器请求时请求的一直是9527端口呢，这里怎么改成请求后台端口，这里在请求自己前台自己的端口所以拿不到数据
，比如本地我想请求后台80端口，admin-vue-element自己是9527端口，我在dev.env.js设置了BASE_API和index.js里的proxyTable设置了 target。但是请求的还是9527端口，好郁闷啊，有大佬解释下该怎么操作吗

**Comment by PanJiaChen** [comment]
9527 只是本地前端项目起的端口号，和你请求地址有什么关系？

**Comment by hertough** [comment]
就是在本地测试时请求本地的80端口但是一直显示请求的是9527，确实不太懂，刚入门还望指教

**Comment by PanJiaChen** [comment]
请提供一个network的截图。

**Comment by hertough** [comment]
只有console里面有404错误，network没有请求，我觉得我哪里理解错误了。。

**Comment by PanJiaChen** [comment]
首先你移除了 `mockjs`了么？
其次你 `config` 下面的 `BASE_API`写的是什么？

**Comment by hertough** [comment]
移除了，写的我的本机虚拟域名

**Comment by hertough** [comment]
后端没有实质接口内容，只是返回简单内容看是否打通了，这里是不是拦截器做了处理阻止了提交

**Comment by Bigger-Ma** [comment]
> 后端没有实质接口内容，只是返回简单内容看是否打通了，这里是不是拦截器做了处理阻止了提交

请问你的问题解决了吗，我刚入坑这个项目，也是想本地调用服务端接口，mock看的一头雾水

**Comment by Xanthuim** [comment]
前端就是这么恶心，很简单的事情绕来绕去。。

**Comment by itcuihao** [comment]
前后端端口不一样是正常的，可是想调用后端端口改在哪里设置呢？

**Comment by ykchong45** [comment]
我用的是i18n的版本，解决方案如下。希望能帮到大家！

1. 找到根目录下的`vue.config`，搜索`devServer`，注释掉`before: require('./mock/mock-server.js')`，并添加下面代码（[参考链接](https://panjiachen.gitee.io/vue-element-admin-site/zh/guide/essentials/mock-api.html#%E7%A7%BB%E9%99%A4)）

```vue
devServer: {
	...

	proxy: {
      // change xxx-api/login => mock/login
      // detail: https://cli.vuejs.org/config/#devserver-proxy
      [process.env.VUE_APP_BASE_API]: {
        target: `http://localhost:后端服务端口号`,
        changeOrigin: true,
        pathRewrite: {
          ['^' + process.env.VUE_APP_BASE_API]: ''
        }
      }
    },
	after: require('./mock/mock-server.js')
	// 注释掉before那行
}
```

2. 后端服务也需要遵循原mock.js返回的格式，返回的JSON包含 code（int）和 data（JSON）。以Gin框架为例：

```go
func Login(c *gin.Context) {
	token := "admin-token"
	c.JSON(http.StatusOK, gin.H{
		"code": 20000,
		"data": gin.H{"token": token},
	})
}
```

3. 检查前后端URL是否匹配。以前端`api/user`里的Login为例：`url: '/vue-element-admin/user/login'`，vue会请求`localhost:后端服务端口号/vue-element-admin/user/login`



- 值得注意的是，Chrome的Network界面不能正确显示proxy后的后端URL，显示的请求仍然是发送到`localhost:9527/dev-api/...`
