### ISSUE TITLE
如何将导入excel功能拆分为一个js文件?

### ISSUE THREAD

**Issue by gaoshijun1993** [PanJiaChen/vue-element-admin#455]
将导入excel功能独立成一个方法的话可复用性会更高吧?我的想法如下:执行这个方法后能够生成一个file-input文件框,并且自动点击,选择文件后能够解析表格文件成json数据,然后在then回掉中拿到解析后的json数据.感觉这样似乎是可行的.在npm上找了一下没有找到这样的包,只找到了一个功能接近的包[vue-xlsx-table](https://www.npmjs.com/package/vue-xlsx-table),但是是用vue封装的,复用性还是不够高

**Comment by gaoshijun1993** [comment]
实现了一下,果然可以~

**Comment by Samdyddd** [comment]
如果有几百条数据的话，是需要分页吧？如果在element-ui中如何实现？
