### ISSUE TITLE
使用侧边栏报错,说我改了vuex的state

### ISSUE THREAD

**Issue by bitqiang** [PanJiaChen/vue-element-admin#456]
![vuex](https://user-images.githubusercontent.com/13163400/35857035-d0db4218-0b72-11e8-8f30-a9d7e670f231.jpg)

由于vuex报错也定位不到具体文件。。所以一直找不到错误哦。。
唯一发现的就是。。
![image](https://user-images.githubusercontent.com/13163400/35857068-e76e6bea-0b72-11e8-80c8-bb2f2753f7fd.png)
state里面的routers如果我赋值为空的话，就不会报错。
可是路由都是写死的，真是找不到问题在哪儿。

**Comment by lerit** [comment]
这是vuex最常见的错误，根本找不到源头，不报具体错。一般认为这是因为你的state中有不是简单类型的属性导致的。比如state:{a:1,b:true}是可以的。state:{a:{b:1}}就会在vuex的strict严格模式下报错

**Comment by lerit** [comment]
跟这个一个问题应该
#126

**Comment by bitqiang** [comment]
@lvsmart  谢谢你了
