### ISSUE TITLE
npm run dev后,登录时出错

### ISSUE THREAD

**Issue by bay1ts** [PanJiaChen/vue-element-admin#457]
mock.js?ccd5:8359 OPTIONS http://api-dev/login net::ERR_NAME_NOT_RESOLVED
send @ mock.js?ccd5:8359
dispatchXhrRequest @ xhr.js?ec6c:178
xhrAdapter @ xhr.js?ec6c:12
dispatchRequest @ dispatchRequest.js?c4bb:59
Promise resolved (async)
request @ Axios.js?5e65:51
wrap @ bind.js?24ff:9
loginByUsername @ login.js?33d0:8
(anonymous) @ user.js?6d11:51
F @ _export.js?90cd:35
LoginByUsername @ user.js?6d11:50
wrappedActionHandler @ vuex.esm.js?358c:704
dispatch @ vuex.esm.js?358c:426
boundDispatch @ vuex.esm.js?358c:332
(anonymous) @ index.vue?684d:87
(anonymous) @ element-ui.common.js?ccbf:18234
(anonymous) @ element-ui.common.js?ccbf:18549
complete @ index.js?8f07:89
(anonymous) @ index.js?8f07:225
next @ util.js?7828:148
next @ util.js?7828:116
cb @ index.js?8f07:173
validatePassword @ index.vue?684d:59
(anonymous) @ index.js?8f07:216
next @ util.js?7828:114
asyncSerialArray @ util.js?7828:120
(anonymous) @ util.js?7828:154
asyncMap @ util.js?7828:151
validate @ index.js?8f07:141
validate @ element-ui.common.js?ccbf:18545
boundFn @ vue.esm.js?efeb:187
(anonymous) @ element-ui.common.js?ccbf:18229
validate @ element-ui.common.js?ccbf:18228
boundFn @ vue.esm.js?efeb:188
handleLogin @ index.vue?684d:84
boundFn @ vue.esm.js?efeb:188
click @ index.vue?8705:110
invoker @ vue.esm.js?efeb:1997
fn._withTask.fn._withTask @ vue.esm.js?efeb:1795
request.js?bcb8:56 errError: Network Error

**Comment by PanJiaChen** [comment]
先关闭了，直到提供了相对详细的问题描述，问题重现步骤或者在线demo。
