### ISSUE TITLE
请问什么时候支持element-ui 2.1.0?

### ISSUE THREAD

**Issue by gateslu** [PanJiaChen/vue-element-admin#458]
![tim 20180206221401](https://user-images.githubusercontent.com/1697700/35863896-18f5086e-0b8b-11e8-86b9-f4ddc2e01b78.png)
由于2.0.8的DatePicker有问题，所以我升到2.1.0，但是问题来了，边栏会出现错位现象

**Comment by PanJiaChen** [comment]
的确。2.1.0改了menu和table，尤其table改动还算不小。我个人习惯不用大版本升级后的第一个版本，通常会有一些小问题，通过element的issue也不难发现新版本还是有一些小问题的。所以过段时间之后会升级element的版本。

**Comment by gateslu** [comment]
好的，谢谢哈

**Comment by NBSeven** [comment]
也遇到同样的问题了 。。。这个只能换低版本，可是低版本有的Bug导致我新需求又无法实现   0 0 。。。。

**Comment by PanJiaChen** [comment]
element-ui 发布了新版本 v2.3.0
直接升级就可以了，不用改任何代码。

**Comment by PanJiaChen** [comment]
v3.6.5已升级`element-ui`
