### ISSUE TITLE
前后端交互API采用另外一种方式response.data.data

### ISSUE THREAD

**Issue by linlinjava** [PanJiaChen/vue-element-admin#461]
当前的代码前后端交互API是
```
reponse = {
  code: '200',
  message: 'OK',
  data: ' demo data'
}
```
虽然这样更符合restful规范，但这也导致了mock.js难以模拟。

此外，有的时候实际项目中也不会采用这一种方式，而是另外一种，例如
```
response = {
  code: '200',
  message: 'OK',
  data: {
    errno: '0',
    errmsg: '成功',
    data: 'demo data'
  }
}
```

也就是业务的状态和消息放在response.data中，而业务数据则放在response.data.data中。
这样mock.js也可以模拟不成功的一些状态。

而在后端项目中（例如spring boot）中返回一个普通的R.Object，也可以方便json序列化。
class R {
Integer errno;
String errmsg;
Object data;
}

如果你觉得这样可行，我可以提交一个pull request。
感谢作者的项目。

**Comment by PanJiaChen** [comment]
两种方式都比较常见，各有各的优点。我也特意去看了一些大公司的对外api大部分还是遵循restful规范的格式的。先暂定吧，大家也可以说一说自己的看法。

**Comment by AndsteLyc** [comment]
我们是第一种。。
```javascript
response = {
  code: '200',
  message: '',
  data: {
    user_name: 'xxx',
    userI_id: 123
  }
}
```

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/54600301-69e9bb80-4a77-11e9-9a46-433e8b0eb2ce.png)


4.0版本统一为该形式了。
