### ISSUE TITLE
登录接口的mock数据该怎么造呢？

### ISSUE THREAD

**Issue by Mr-arvin** [PanJiaChen/vue-element-admin#462]
![image](https://user-images.githubusercontent.com/35322029/36386078-8475d5ac-15cf-11e8-99da-d42df895d973.png)

check项目运行之后，其它数据都能请求到，唯独登录的数据无法请求，我也试了Query Parameters参数，也没有请求成功。

准备自己模拟vue-element-admin写接口，注册mock账号后，baseurl改成了(“https://easy-mock.com/mock/5a88463bbf160328124e8211/ark”)，    定义了几个接口，可以请求到，但唯独登录接口不知该怎么写，望能指点一二。

**Comment by PanJiaChen** [comment]
可以参照 http://panjiachen.github.io/vueAdmin-template/#/login 的写法。

**Comment by Mr-arvin** [comment]
感谢，已解决。

**Comment by jing2si** [comment]
```js
{
  "code": 20000,
  "data": {
    "token": function({_req}) {
      return _req.body.username
    }
  },
  "_res": {
    "cookies": {
      "Admin-Token": function({_req}) {
        return _req.body.username
      }
    }
  }
}
```
