### ISSUE TITLE
遇到很神奇的问题，用ali-oss，在vue-element-admin项目中会出错，vueAdmin-template项目中就没问题

### ISSUE THREAD

**Issue by wyymichael** [PanJiaChen/vue-element-admin#465]
我要在项目中使用ali-oss上传
使用方式是在index.html中直接引用js文件
`    <script type="text/javascript" src="//gosspublic.alicdn.com/aliyun-oss-sdk.min.js"></script>`

相同的代码在vueAdmin-template中可以正常运行
但是在vue-element-admin就会出错，
使用的是ali-oss的multipartUpload接口，

- 当上传文件大于100k的时候这个接口会返回相关分片信息，返回数据格式xml能够正常返回，但在vue-element-admin中ali-oss的sdk会取数据失败，请问可能是什么原因，导致两个项目一个可以运行，一个却失败
- 当上传文件小于100k的时候这个接口会直接上传成功，两个项目都能正常运行

已经被搞崩溃两天了

**Comment by PanJiaChen** [comment]
你看一下你是否使用了`mockjs`.

**Comment by wyymichael** [comment]
谢谢，我把mockjs删了后确实好了。。。  我本来因为只会影响设定的几个url。。。
