### ISSUE TITLE
build 之后没有生成dist文件夹

### ISSUE THREAD

**Issue by xiangtianyu** [PanJiaChen/vue-element-admin#466]
在服务器上部署项目，我运行npm run build:prod，但是没有在项目文件夹下生成dist文件夹。（没有修改过任何配置文件）请问这是什么原因？

**Comment by PanJiaChen** [comment]
首先确定你本地编译没有问题，其次确定部署是否成功。若还不行请提供更详细问题描述。

**Comment by xiangtianyu** [comment]
![image](https://user-images.githubusercontent.com/10825900/36627014-8dc98d64-1977-11e8-9ded-e54fd417f0fe.png)
我之前以为这是编译成功了，原来是没有成功。。。请问这是个什么原因？

**Comment by PanJiaChen** [comment]
确定一下node版本，或者有无报错？

**Comment by xiangtianyu** [comment]
node版本v9.5.0，没有报错，我特意找log看了下，没有看到有报错。只是会到了一半退出，然后我以为编译完了。。。

**Comment by xiangtianyu** [comment]
补充一下：info lifecycle 后面是vue-el 然后后面就断掉了

**Comment by PanJiaChen** [comment]
#112 看看是不是这个问题。
