### ISSUE TITLE
sidebar收起状态会出现Menu-Item自带的tooltip. The tooltip will appears in the sidebar of closed state.

### ISSUE THREAD

**Issue by chess99** [PanJiaChen/vue-element-admin#468]
![sidebar_gif](https://user-images.githubusercontent.com/23102610/36650567-300143ca-1adf-11e8-96ea-9a838a67a6ce.gif)

**Comment by PanJiaChen** [comment]
应该是你的`element-ui`版本>=2.1.0 导致的，之后会兼容新版本`element-ui`。
It should be caused by your `element-ui` version > 2. 1. 0, and will later be compatible with the new version of `element-ui`.

**Comment by phoenix110** [comment]
我也遇到这个问题了。已经解决。
1.src\views\layout\components\Sidebar\SidebarItem.vue
主要是增加了slot="title"属性。
![sidebaritem vue](https://user-images.githubusercontent.com/2277339/37015761-fee504d2-2143-11e8-9d99-2427ff89f886.jpg)
2.\src\styles\sidebar.scss
增加.el-tooltip的css。
![sidebar scss](https://user-images.githubusercontent.com/2277339/37015763-ff42437c-2143-11e8-9b49-ae7b3ebfbcae.jpg)
3.验证结果：
![default](https://user-images.githubusercontent.com/2277339/37015762-ff12a194-2143-11e8-9cc2-66645714f9e9.jpg)

**Comment by PanJiaChen** [comment]
https://github.com/ElemeFE/element/pull/8809
由于`element-ui`会和自定义的动画冲突导致不协调，所以这个pr合进去之前无法很完美的解决，

**Comment by PanJiaChen** [comment]
element-ui 发布了新版本 v2.3.0 
直接升级就可以了，不用改任何代码。

**Comment by PanJiaChen** [comment]
v3.6.5已修复。
