### ISSUE TITLE
table表格里面如何嵌入from表单验证？？

### ISSUE THREAD

**Issue by seean-chan** [PanJiaChen/vue-element-admin#469]

**Comment by seean-chan** [comment]
![2](https://user-images.githubusercontent.com/30038138/36656538-db26f67c-1b03-11e8-85f1-c93c30c75450.png)
![1](https://user-images.githubusercontent.com/30038138/36656544-de085f02-1b03-11e8-8b00-9e52caceeb2c.png)
我将elementui的验证提示消息的样式改了下，现在是悬在上面，但是在表格里面因为有overflow这个属性，所以就会被遮住。但是又不能去掉overflow：auto，去掉会影响表格滚动样式

**Comment by PanJiaChen** [comment]
有问题请提供在线demo(建议使用jsfiddle)，先关闭本问题了。

**Comment by jim888666** [comment]
哈喽 问下  table是手动新增的  里面有 嵌套 表单  验证 规则不起作用， 我能借鉴下您的代码吗
