### ISSUE TITLE
这条注释描述有误吗？

### ISSUE THREAD

**Issue by ferrinweb** [PanJiaChen/vue-element-admin#470]
router/index.js line 27
`noCache: true                if fasle ,the page will no be cached(default is false)`
noCache意为无缓存、禁用缓存，如果设置为true，则表示确定禁用缓存。设置为false，则应表示为不禁用缓存。
描述如果无误，则不看注释，可能会造成误解。

**Comment by PanJiaChen** [comment]
@ferrinweb  谢谢的反馈，的确写写错了。
已修改https://github.com/PanJiaChen/vue-element-admin/commit/ae41459cb1826f28332a24f466cdfa76934a1cce
