### ISSUE TITLE
有没有什么优雅的实现方法  使router以及系统角色与router的权限配置能够更加方便配置

### ISSUE THREAD

**Issue by hanzhenchaoGit** [PanJiaChen/vue-element-admin#471]
在做企业管理后台系统的时候常规项目经常用到的动态加载菜单 动态加载用户角色对应的菜单列表
想知道有没有什么优雅的方案去实现这种需求  router可以配置在数据库  可访问router的角色权限也配置在数据库  也就是我需要修改router以及router的访问权限的时候 只需要在界面上修改编辑就可以了  而不是都过修改router.js去实现  修改router.js就意味着需要重新打包发布

**Comment by nmxiaowei** [comment]
动态服务端获取路由@hanzhenchaoGit

**Comment by PanJiaChen** [comment]
恩 @nmxiaowei 说的是对的。

**Comment by nmxiaowei** [comment]
@PanJiaChen  可以加我QQ吗 1634566606  想和你讨论点东西
