### ISSUE TITLE
NavMenu收缩后子菜单过多无法滚动显示的问题

### ISSUE THREAD

**Issue by luchanan** [PanJiaChen/vue-element-admin#472]
![image](http://7qn7ih.com1.z0.glb.clouddn.com/201802261644.png)

当左边的菜单收缩的时候，菜单的最底部的菜单它的子菜单有很多的时候，无法滚动查看它的全部子菜单

请求高见

**Comment by PanJiaChen** [comment]
Duplicate of #320
