### ISSUE TITLE
菜单修改后不能自动首字母大写

### ISSUE THREAD

**Issue by ferrinweb** [PanJiaChen/vue-element-admin#473]
比如把dashboard路由title改为apple，自动构建后不能自动首字母大写：
![tim 20180227110647](https://user-images.githubusercontent.com/3353839/36708602-bbd9e774-1bae-11e8-944b-bb2f1aeeccf4.png)

**Comment by PanJiaChen** [comment]
为什么要自动。。。有需求请自行处理。

**Comment by ferrinweb** [comment]
并非有此需求，而是发现表现不一致的问题。
dashboard → Dashboard
apple → apple
小写dashboard是可以自动大写首字母的，不太懂实现机制，莫非有个字典表对应返回相应大写形式的？

**Comment by ferrinweb** [comment]
我找到了，原来是在国际化部分做了处理。

**Comment by PanJiaChen** [comment]
你可以自己封装一个format function 统一处理一下就好了。
