### ISSUE TITLE
多个tinymce，有时候有些会不加载

### ISSUE THREAD

**Issue by electroapache** [PanJiaChen/vue-element-admin#478]
一个页面加了三个编辑器，结果有时候只显示2个。
随机的，有时候又三个全部加载了

![qq 20180302135910](https://user-images.githubusercontent.com/21041181/36885454-efb1ad96-1e21-11e8-84e6-b3ff614260d6.png)

**Comment by PanJiaChen** [comment]
设置id了么？ 你提供一下你声明的代码。

**Comment by electroapache** [comment]
感谢感谢，设置ID就好了。
