### ISSUE TITLE
Question:大神能不能把用户系统大概的讲一下

### ISSUE THREAD

**Issue by GeorgeGuoCN** [PanJiaChen/vue-element-admin#48]
大神能不能把用户系统大概的讲一下，如用户权限，菜单权限等

**Comment by PanJiaChen** [comment]
之后会出一篇教程关于用户权限的

**Comment by fengbjhqs** [comment]
期待这篇，

**Comment by tianm2009** [comment]
大神，你们后台持续集成大致是怎么做的能透漏下吗

**Comment by PanJiaChen** [comment]
我们公司内部项目是基于[gitlab-ci](https://about.gitlab.com/features/gitlab-ci-cd/),github也有的。
还有下次这种问题单开一个issue啊，不要在一个不相干的issue下提问

**Comment by tianm2009** [comment]
谢谢回答，下次一定注意

**Comment by PanJiaChen** [comment]
已发文https://juejin.im/post/591aa14f570c35006961acac
