### ISSUE TITLE
Error with resizing window [Sidebar: Charts -> Keyboard, Line, Mix]

### ISSUE THREAD

**Issue by Bear4** [PanJiaChen/vue-element-admin#480]
When resizing window, Charts doesn't refresh. 
resizing to smaller window
![err_resize_charts](https://user-images.githubusercontent.com/8928341/36890157-2dfe65c8-1dfd-11e8-9e6c-cbbbd0f833d2.jpg)

resizing to bigger window
![err_resize_chartsline](https://user-images.githubusercontent.com/8928341/36890239-75eace12-1dfd-11e8-85f6-aeeaa8819362.jpg)

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/c398ee0ddc88579beabebe1324573c08115488b3
