### ISSUE TITLE
做登录时，提交的账号密码会显示在herder中的form data中，怎么去掉啊？

### ISSUE THREAD

**Issue by hedekun** [PanJiaChen/vue-element-admin#483]
****
如图
<img width="556" alt="1" src="https://user-images.githubusercontent.com/35363380/36941474-fb123f40-1f96-11e8-9858-485d5ef67287.png">

**Comment by PanJiaChen** [comment]
post 一个form，显示form data有什么问题么？

**Comment by hedekun** [comment]
感谢回答。没什么问题，那不是用户的登录信息都显示了，有什么解决方式吗？

**Comment by linyimeng** [comment]
你可以对用户名和密码进行加密后再提交

**Comment by PanJiaChen** [comment]
你看一个看一下淘宝或者其它主流网站登录普遍做法都是加密+https

**Comment by zhuyuanwen** [comment]
@PanJiaChen 主流网址（主要看了阿里的）的页面登录后都会一下子就跳转，根本找不到这条记录，也看不到f加密后的form记录。还是说因为做了加密所以这个记录就整个看不见了？还是看的见记录，只是是加密后的记录？
