### ISSUE TITLE
一级菜单 不需要二级菜单？

### ISSUE THREAD

**Issue by youngchen1987** [PanJiaChen/vue-element-admin#484]
比如用户管理功能，有用户列表，新增用户，编辑用户  三个功能  ，但是一级菜单只显示用户列表，新增用户，编辑用户是不现实在导航上的  
但是如果按照
 {
    path: '/usermanage',
    component: Layout,
    name:"user",
    redirect: 'noredirect',
    meta: {  permission: 15,   title: 'usermanage',  icon: 'user'},
    children: [
     { path: 'index', component: _import('usermanage/index'), name:"usermanage", meta: {permission: 15,permissionlist: "1501,1502,1503" ,title: 'usermanage',icon: 'user'},},
     { path: 'edit', component: _import('usermanage/edit'), hidden: true, name: 'add_user'},
     { path: 'add', component: _import('usermanage/add'), hidden: true, name: 'edit_user'}
    ]
  },

这样设置的话 就会包含二级菜单

**Comment by MaybeLin** [comment]
我也遇到这个问题了。。您解决了吗

**Comment by MaybeLin** [comment]
比如左侧导航点击 进入列表页 同时列表页的商品点击还要进入详情页。。

**Comment by seean-chan** [comment]
给路由加一个字段，然后在循环侧栏的时候做一下判断，让它不显示在侧栏
![_20180306102952](https://user-images.githubusercontent.com/30038138/37011280-62d3dd52-212a-11e8-84f6-205030fb1e0c.jpg)
![_20180306103823](https://user-images.githubusercontent.com/30038138/37011282-63e2a0f2-212a-11e8-8974-9b6e85405080.jpg)

**Comment by MaybeLin** [comment]
@seean-chan  这个我也搞了 但是面包屑这些都不对了 商品列表->某个商品->商品详情页 这样才是对的

**Comment by youngchen1987** [comment]
找到一种解决方案  参考的是上一个版本的逻辑:

1. 路由上增加   noDropdown: true, 字段
 {
    path: '',
    component: Layout,
    noDropdown: true,
    redirect: 'dashboard',
    children: [{
      path: 'dashboard',
      component: _import('dashboard/index'),
      name: 'dashboard',
      meta: { title: 'dashboard', icon: 'dashboard', noCache: true }
    }]
  } 

2.在views\layout\components\Sidebar目录下的 SidebarItem.vue  修改为
router-link v-if="!item.hidden&&item.noDropdown&&item.children.length>0" :to="item.path+'/'+item.children[0].path" :key="item.children[0].name"

目前可以解决我的问题

**Comment by lixing0323** [comment]
我也遇到了。比如一个订单管理，一级菜单只需要一个列表，下属包括订单详情，订单修改等等内容，都是这个的子路由，但是不需要显示成为二级菜单。如果按照作者文章所属，左侧边栏会乱掉。

**Comment by hanzichi** [comment]
感觉这个问题还是蛮重要的，期待修复下 @PanJiaChen 

类似问题 <https://github.com/PanJiaChen/vue-element-admin/issues/498> <https://github.com/PanJiaChen/vue-element-admin/issues/449>

**Comment by hanzichi** [comment]
我直接新建了个一级菜单，然后 hidden 掉。。。先 hack 了再说

**Comment by PanJiaChen** [comment]
这周末更新版本

**Comment by kingasds** [comment]
假如在views\layout\components\Sidebar line 12 裏的

`<el-submenu v-else :index="item.name||item.path" :key="item.name">`
改成
`<el-submenu v-if="item.children.length>1" :index="item.name||item.path" :key="item.name">`

好像可以暫時解決問題
請各位指教。

**Comment by justdoitweb** [comment]
有相同问题，期待解决

**Comment by lixing0323** [comment]
@PanJiaChen ，我现在是这样解决的。在SidebarItem.vue判断v-if="item.children.length===1的时候替换成
 // 获取当前菜单下有多少个能显示的子菜单
    getShowingChildrenCount(child, item) {
      var showingCount = 0;
      for (let i = 0; i < child.length; i++) {
        var hidden = child[i].hidden;
        showingCount = hidden === true ? showingCount : showingCount + 1;
      }
      return showingCount === 0;
    }
  }

**Comment by chaneyandyou** [comment]
我也遇到了同样的问题，期待解决一下

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/de066192669246d09ae8a04d20ff918dbbf85b64

不知道是否满足你们的需求？

**Comment by xiaozhanghui** [comment]
@MaybeLin 怎么解决的，大佬。

**Comment by airzhanglin** [comment]
相同问题，在当前版本下，二级路由下面新增了一个三级路由新增页面，设置了hidden为true，只是不显示在菜单菜单栏上，二级菜单还有折叠箭头符号

**Comment by lixing0323** [comment]
好滴，谢谢，我试试。






在 2018-07-10 09:54:25，"Lynn" <notifications@github.com> 写道：


相同问题，在当前版本下，二级路由下面新增了一个三级路由新增页面，设置了hidden为true，只是不显示在菜单菜单栏上，二级菜单还有折叠箭头符号

**Comment by mynameismaosheng** [comment]
二级路由下面新增了一个三级路由新增页面，设置了hidden为true，
只是不显示在菜单菜单栏上，二级菜单还有折叠箭头符号

**Comment by mynameismaosheng** [comment]
> 二级路由下面新增了一个三级路由新增页面，设置了hidden为true，
> 只是不显示在菜单菜单栏上，二级菜单还有折叠箭头符号

目前的解决方案:
`children: [{
        path: 'a',
        meta: { title: '列表' },
        component: () => import(''),
        children: [
          {
            path: '',
            component: () => import(''),
            meta: { title: '列表' }
          },
          {
            path: 'b',
            component: () => import(''),
            hidden: true,
            meta: { title: '添加' }
          }
        ]
      }]`
出现的结果是 
**列表/列表
列表/添加**
左侧导航 只显示 列表
