### ISSUE TITLE
tree组件 懒加载 在画面添加树的相关数据如何进行刷新

### ISSUE THREAD

**Issue by lxxoolxx** [PanJiaChen/vue-element-admin#485]
场景 画面左侧有一个组织架构树， 右侧是一个组织架构添加画面， 现在数据添加后 ，无法进行刷新 ，实时体现数据的改变， 通过this.$set(this.item, "children", []); 方法只能实现，触发了load方法的节点实时添加子节点数据，对开始是叶子节点的数据无法添加子节点数据后实时刷新，麻烦各位大神

**Comment by PanJiaChen** [comment]
我其实没太理解具体的需求是什么？

**Comment by phpcyy** [comment]
叶子结点怎么才能添加子节点，然后使叶子结点称为父节点？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1587
