### ISSUE TITLE
弹窗放Tinymce问题  Tinymce in dialog

### ISSUE THREAD

**Issue by sunmorg** [PanJiaChen/vue-element-admin#486]
弹窗内放Tinymce编辑器时  点击上传图片按钮是的弹窗层级有点小问题  请问一下怎么解决

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/31b7fa6f5503fdb9d8a89502f1238d02386340cd
<el-dialog> add append-to-body .

**Comment by sunmorg** [comment]
3q
