### ISSUE TITLE
在TagsView中关闭其他选项有一个bug

### ISSUE THREAD

**Issue by wsuper** [PanJiaChen/vue-element-admin#487]
store->modules->tagsView  代码第28行bug，关闭其他这个选项会导致删除所有缓存，当前页面虽然显示，当再重新打开其他页面，再通过tagsView点击过来，缓存已经消失了，则重新加载
state.cachedViews.splice(i, i+ 1)
i 是一个字符串，
应该修改成
state.cachedViews.splice(index, index + 1)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/913
