### ISSUE TITLE
页面开的多了之后，上方的tab页超出屏幕宽度了，没有滚动条，滑动不过去，关闭标签页也不会调整位置

### ISSUE THREAD

**Issue by aFlappyPig** [PanJiaChen/vue-element-admin#488]
![qq 20180307115200](https://user-images.githubusercontent.com/18723676/37072758-01f9082a-21fe-11e8-940c-1d5a9623b875.jpg)

**Comment by PanJiaChen** [comment]
tabs 一栏是能滚动的，只是没显示滚动条而已。若不能请提供浏览器版本型号。

**Comment by aFlappyPig** [comment]
可能我描述的不是很清楚，我看到你tags的容器是绝对定位的left，但是关闭tag的时候这个left没有改变，会导致过长之后右边始终有tag看不到。滚动条这个确实是改变css就可以实现的。谢谢解答。
