### ISSUE TITLE
如何实现真正的发送账号密码给后台的登陆

### ISSUE THREAD

**Issue by Maipiao** [PanJiaChen/vue-element-admin#489]
不好意思我刚接触前端没多久,可能看这代码还有些吃力.目前是在工作中真正用到了,但是代码中的账号密码还有token身份这些信息都是写死的.我想问一下如果真的需要把登陆页的账号密码发送给后台并得到token需要怎么实现,修改哪些地方?可以帮忙解答一下吗?

**Comment by hanzichi** [comment]
首先你需要修改 config 目录下的 dev.env.js 和 prod.env.js 两个文件的 BASE_API 变量，将其修改成真正后台的服务地址，然后在 src/api/login.js 中修改请求地址

**Comment by delwey** [comment]
还需要将main.js 的的模拟数据去掉，// import './mock' // simulation data，否则会发送到模拟地址。

**Comment by PanJiaChen** [comment]
前面回答的很正确了。

**Comment by gangyahaidao** [comment]
在修改完dev.env.js 和 prod.env.js中的BASE_API之后需要应用重启一下地址才生效

**Comment by CjoyHome** [comment]
一直没留意到main.js 的   import './mock'  ，打包发现没有请求 纳闷了好久
