### ISSUE TITLE
刷新页面或数据加载较慢 跳转到404

### ISSUE THREAD

**Issue by zhanlijian** [PanJiaChen/vue-element-admin#491]
![image](https://user-images.githubusercontent.com/26494898/37082103-8b72318a-2226-11e8-8bcf-a3542f37310c.png)

每次页面上的数据加载不出来，显示暂无数据的时候点击刷新按钮肯定会出现404

**Comment by PanJiaChen** [comment]
你提供更详细信息，本项目并没有做相关处理。

**Comment by zhanlijian** [comment]
差不多 就是 什么情况下 跳转到404

**Comment by zhanlijian** [comment]
我们 没做特殊处理跳转到 404   我的意思就是  用了admin 模板  我想问问 有没有做啥处理 会它自动跳转到 404 的

**Comment by zhanlijian** [comment]
常规跳转到 404  ，很是懵逼

**Comment by PanJiaChen** [comment]
刷新页面到404很有可能是https://github.com/PanJiaChen/vue-element-admin/blob/master/src/permission.js#L32

**Comment by zhanlijian** [comment]
ok，我试试， 项目中没用 这个permission 文件 但实际也差不多，我再琢磨琢磨，谢谢

**Comment by zhanlijian** [comment]
大神，有没有尝试过  vue  文档（word，excel
，ppt ，pdf）在线预览方式

**Comment by PanJiaChen** [comment]
每个都有插件 自己github 就好了。
