### ISSUE TITLE
TinyMce 插入视频时不能播放，并且会被转成img  标签

### ISSUE THREAD

**Issue by SilasDong** [PanJiaChen/vue-element-admin#492]
video 标签在输入时被转换成img标签

**Comment by PanJiaChen** [comment]
这个是Tinymce 做的处理，本项目没做任何的处理。所以有问题可以去[Tinymce](https://github.com/tinymce/tinymce/issues)提问。

**Comment by SilasDong** [comment]
好的，谢谢

**Comment by SilasDong** [comment]
是试了一下，把 this.$emit('input', editor.getContent({ format: 'raw' })) 改成this.$emit('input', editor.getContent()) 就不会了，特此说明一下

**Comment by chending1994** [comment]
> 是试了一下，把 this.$emit('input', editor.getContent({ format: 'raw' })) 改成this.$emit('input', editor.getContent()) 就不会了，特此说明一下

请教下，我这样设置，视频还是出不来，请问你视频上传出来了么

**Comment by rumengkai** [comment]
> 是试了一下，把 this.$emit('input', editor.getContent({ format: 'raw' })) 改成this.$emit('input', editor.getContent()) 就不会了，特此说明一下

确实可以了，谢谢！

**Comment by draculapile** [comment]
[Tinymce issue4210](https://github.com/tinymce/tinymce/issues/4210)
