### ISSUE TITLE
最新版本报错v3.6.2

### ISSUE THREAD

**Issue by wangkang007** [PanJiaChen/vue-element-admin#493]
v3.6.2  在进行运行并且访问的时候无法访问，但是下载了v3.6.1可以正常运行

Failed to load resource: the server responded with a status of 400 (Bad Request)
localhost/:1 Refused to execute script from 'http://localhost:9527/%3C%=' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by meizilove258** [comment]
你好，请问你的问题怎么解决的，谢谢！
