### ISSUE TITLE
上传头像组件，点击缩放，预览图会出现重叠现象

### ISSUE THREAD

**Issue by ixoywell** [PanJiaChen/vue-element-admin#497]
![image](https://user-images.githubusercontent.com/5171978/37196198-e22af8b4-23b0-11e8-9c01-6c391b2d5777.png)
上传头像组件，点击缩放，预览图会出现重叠现象

**Comment by PanJiaChen** [comment]
这不是本项目的组件，引用了https://github.com/dai-siki/vue-image-crop-upload
