### ISSUE TITLE
一级菜单中有子路由，但是设置全部隐藏，左侧栏菜单和面包屑有bug.

### ISSUE THREAD

**Issue by lixing0323** [PanJiaChen/vue-element-admin#498]
一级菜单是审核管理，不要二级菜单，但是他本身底下又会有审核详情的二级路由。如果安装文档，这样设置的话。
{
    path: '/audits',
    component: Layout,
    redirect: '/audits/index',
    children: [{
      path: 'index',
      component: _import('audits/index'),
      name: 'audits',
      meta: {
        title: 'audits',
        icon: 'audits',
        noCache: true
      }
    },
    {
      path: ':id',
      hidden: true,
      component: _import('events/details/index'),
      name: 'details',
      meta: {
        title: 'details',
        icon: 'details',
        noCache: true
      }
    }]
  },
会有二个bug.
第一个是左边菜单栏无法正常显示。
![This is a title](http://chuantu.biz/t6/250/1520590238x-1404764385.png)
第二个是面包屑显示也不正常。
跟这个 #484 情况一模一样。请大神 @PanJiaChen 看看。

**Comment by PanJiaChen** [comment]
Trace in #484
