### ISSUE TITLE
侧边来收缩

### ISSUE THREAD

**Issue by kingdee88** [PanJiaChen/vue-element-admin#5]
收缩功能 用户体验不怎好，感觉固定方式比较好，展出方式有点别扭，个人看法。。。。

**Comment by PanJiaChen** [comment]
优化了一下体验，但在现有element-ui menu的基础上想不到什么好的交互方式。期待官方提供像ant一样的功能。
若有更好的提议，欢迎pr。

**Comment by qzmly100** [comment]
![image](https://user-images.githubusercontent.com/9715929/48536288-16a90600-e8e9-11e8-83af-54e2a7668009.png)
我想知道这个样式 比如收缩的过渡 效果 为什么我找不到这个样式 请问如何在项目中定位这个样式？

**Comment by PanJiaChen** [comment]
请看 element-ui 源码
