### ISSUE TITLE
Tinymce 使用时出现errorLog.js:17 TypeError: Cannot read property 'get' of undefined，errorLog.js:17 TypeError: Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by sunhacker** [PanJiaChen/vue-element-admin#500]
Tinymce 使用时出现errorLog.js:17 TypeError: Cannot read property 'get' of undefined，errorLog.js:17 TypeError: Cannot read property 'init' of undefined

**Comment by PanJiaChen** [comment]
个人猜测是你没有在全局引入`tinymce.min.js` https://github.com/PanJiaChen/vue-element-admin/blob/master/index.html#L10
https://panjiachen.github.io/vue-element-admin-site/#/zh-cn/rich-editor
