### ISSUE TITLE
头像上传组件功能，预览重影

### ISSUE THREAD

**Issue by ixoywell** [PanJiaChen/vue-element-admin#503]
![e54d3c29-f2c0-4542-abaa-d5d908bb14a1](https://user-images.githubusercontent.com/5171978/37261302-67302cb0-25d6-11e8-8d38-fa79cc529ef3.jpg)
头像上传组件，调节缩放比例，预览图出现了重影的现象。
应该是canvas没有清空重绘导致的。

**Comment by PanJiaChen** [comment]
是本项目使用的 [vue-image-crop-upload](https://github.com/dai-siki/vue-image-crop-upload) 版本太低导致的，我近期会升级一下版本。

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/5f4ce7fc71d2f3f38c40668639709f77b7ca7b6d
