### ISSUE TITLE
[Feature]: Iframe websites

### ISSUE THREAD

**Issue by PanJiaChen** [PanJiaChen/vue-element-admin#505]
Ability to display third-party websites with iframe

**Comment by moonose** [comment]
大神，最新代码里哪里有iframe?

**Comment by eggachecat** [comment]
@PanJiaChen 

有一个问题想要请教一下：请问是否有方法让 **iframe** 只render一次呢(例如切换了路由再回来)？

原因是这个页面的载入有些慢,所以希望载入一次以后就保留...

所有和iframe的交互可以使用event来(不需要改变url来刷新iframe)

现在的想法是在layout那边载入iframe,然后某种方法隐藏起来(left-100000这样)，然后在某个route需要的时候再把位置调整到需要的地方?... 有没有更好的方法呢...

**Comment by wangyegg1989** [comment]
@PanJiaChen 
iframe载入是实现了，但是比如我有很多个第三方页面需要通过iframe新标签页打开，在点击标签页切换页面的时候怎么让iframe不重新加载？
