### ISSUE TITLE
sidebar的折叠问题

### ISSUE THREAD

**Issue by nevermorever** [PanJiaChen/vue-element-admin#506]
打开一个多级菜单，该菜单为展开状态，再进入到另外一个多级菜单时，怎么将之前展开的菜单折叠起来？

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/37379982-64bb3e88-2771-11e8-811b-98651eb9e5a4.png)


http://element-cn.eleme.io/#/zh-CN/component/menu

**Comment by nevermorever** [comment]
ok
