### ISSUE TITLE
更换主题颜色

### ISSUE THREAD

**Issue by poemxl** [PanJiaChen/vue-element-admin#508]
在windows 下，运行项目成功，按照更换主题的步骤，执行多套主题换肤，
已安装主题文件
et -i 执行成功
et 执行成功
对照更换主题文档里的动态图片发现我的项目里没有dist目录
执行gulp的时候，报错No gulpfile found，
就卡在这里了

**Comment by PanJiaChen** [comment]
请提供更多信息。
