### ISSUE TITLE
TinyMCE是否可以通过package.json文件定义加载，而不是提前放在static目录进行加载。

### ISSUE THREAD

**Issue by CHCP** [PanJiaChen/vue-element-admin#511]
TinyMCE是否可以通过package.json文件定义加载，而不是提前放在static目录进行加载。

**Comment by PanJiaChen** [comment]
可以参照本分支
https://github.com/PanJiaChen/vue-element-admin/tree/refactor/tinymce4.7.6

**Comment by CHCP** [comment]
这个分支版本还是放在static目录下，没有通过package.json加载，与master分支一样的。

**Comment by PanJiaChen** [comment]
请仔细看，并没有，只是放了skin 和一些图片资源。

**Comment by CHCP** [comment]
看到了，确实不一样。什么时候这个分支同步到master？或是master分支这种处理方式有什么特别的考虑？

**Comment by PanJiaChen** [comment]
不准备合，打包会很慢，当然你可以webpack打包的时候external，但使用难度上去了，还不如直接script简易。富文本基本很久才会更新一个版本，所以手动维护成本不大。

**Comment by CHCP** [comment]
OK，问题关闭了。
