### ISSUE TITLE
Tinymic rich text box has a issue

### ISSUE THREAD

**Issue by Eric-Zhong** [PanJiaChen/vue-element-admin#513]
In the demo ( http://panjiachen.github.io/vue-element-admin/#/components/tinymce). When I click the fullscreen button in the Tinymic rich textbox control, the sidebar will block the control.
![Uploading vue-element-admin.png…]()

![](https://www.evernote.com/l/Asd8_y0ctX9JsZUCWQoXb8rGJsTjwrfVRYMB/image.png 'Issue')

**Comment by PanJiaChen** [comment]
Fixed in 4aa9345
