### ISSUE TITLE
建议/src/components/LangSelect/index.vue中的”中文“修改为”简体中文“。

### ISSUE THREAD

**Issue by CHCP** [PanJiaChen/vue-element-admin#514]
建议/src/components/LangSelect/index.vue中的”中文“修改为”简体中文“。

**Comment by PanJiaChen** [comment]
感谢你的反馈，
不过暂时不准备加繁体中文，所以就叫中文吧。
比如 https://vuejs.org/v2/api/index.html 也叫中文。

**Comment by CHCP** [comment]
理解，不会有繁体中文的版本了。
