### ISSUE TITLE
请问您对信息系统中很重要的消息推送，有比较好的解决方案吗？

### ISSUE THREAD

**Issue by minikiller** [PanJiaChen/vue-element-admin#519]
一直都是使用轮询的方式，很浪费服务器的资源，请问您，vue下有比较好的解决办法吗？请指教！

**Comment by PanJiaChen** [comment]
如果对兼容性要求还可以的话，那就直接websocket吧。前端直接使用[socket.io-client](https://github.com/socketio/socket.io-client)，前端方面基本没有什么工作量。

**Comment by minikiller** [comment]
收到，多谢了，我研究一下

**Comment by HeChengjun** [comment]
@minikiller 这个问题有好的解决方案吗？我在这个项目上使用socket.io-client，会导致不停的重连。

**Comment by PanJiaChen** [comment]
@HeChengjun 看看是不是Mockjs 导致的。

**Comment by ColinSix** [comment]
> @PanJiaChen 谢谢。 io 中的 transport 用 websocket 就没有问题，先这么用着吧。。。

请问后来如何解决的，可以说下吗？
