### ISSUE TITLE
请问书签栏如何缓存页面数据？

### ISSUE THREAD

**Issue by luoruixing** [PanJiaChen/vue-element-admin#521]
![123](https://user-images.githubusercontent.com/8275741/37633471-82883b80-2c2d-11e8-9f4d-58b69523513b.png)

你好，我目前有两个表单，其中一个填写了一些信息之后在书签栏点击了另一个表单，此时在切换回去之前填写的数据就没了，请问有什么办法能够缓存数据吗？

**Comment by PanJiaChen** [comment]
两种方案
- 使用 keep-alive
- 使用一些本地存储，如localstorage
- 如果不需要本地存储，使用vuex也可以

**Comment by luoruixing** [comment]
你好，
 想请教一些keep-alive在哪里写，我在router-view上套一层好像没有起作用

**Comment by PanJiaChen** [comment]
这种细节问题请自行检索解决方案。
