### ISSUE TITLE
修改assets/custom-theme中的样式，不生效

### ISSUE THREAD

**Issue by poemxl** [PanJiaChen/vue-element-admin#525]
请问一下，由于我需要修改一点样式，从浏览器检查到样式是写在assets/custom-theme/index.css中的，我进行了修改，而刷新页面或重新运行项目，修改的参数都不生效，f12检查还是以前的样式设置。我要改的是sidebar的展开收缩图标的位置 ， 在styles/sidebar.csss里面用！important覆盖也不行~

**Comment by andyhu** [comment]
解决了？
