### ISSUE TITLE
[Feature]: TypeScript support

### ISSUE THREAD

**Issue by eladcandroid** [PanJiaChen/vue-element-admin#526]

**Comment by JonChanGit** [comment]
When do you plan to support?

**Comment by JonChanGit** [comment]
计划什么时候支持

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/issues/173

For `typescript` version, you can use [vue-typescript-admin-template](https://github.com/Armour/vue-typescript-admin-template) (Credits: [@Armour](https://github.com/Armour))
