### ISSUE TITLE
Drag Table发生二次DOM更新

### ISSUE THREAD

**Issue by chess99** [PanJiaChen/vue-element-admin#527]
Drag Table发生二次DOM更新, sortablejs更新了一次, onEnd里面splice时又触发了一次vue的DOM更新

效果如图:
![sortable](https://user-images.githubusercontent.com/23102610/37752851-f2710e24-2dd4-11e8-8ac5-e0a68d021322.gif)

但是大大的原版演示程序没有这个问题, 请问是不是我遗漏了什么
(sortablejs都是1.7.0)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/de066192669246d09ae8a04d20ff918dbbf85b64/src/views/example/table/dragTable.vue#L4
是否添加了 `row-key`

**Comment by chess99** [comment]
确实是没加row-key , 灰常感谢!
