### ISSUE TITLE
请问下如何导出多维数组到EXCEL啊？

### ISSUE THREAD

**Issue by electroapache** [PanJiaChen/vue-element-admin#528]
![tim 20180322162354](https://user-images.githubusercontent.com/21041181/37759065-763f6c06-2ded-11e8-801f-ecc6042d6bfb.png)
请问下如何实现类型的效果啊？弄了几天都没写出来

**Comment by PanJiaChen** [comment]
这不就是element-ui 的多级表头么。
http://element-cn.eleme.io/#/zh-CN/component/table#duo-ji-biao-tou

**Comment by electroapache** [comment]
不是啊，我想将这种导出到EXCEL，但是好像只能导二维数组

**Comment by PanJiaChen** [comment]
这样看xlsx, 略复杂。

**Comment by zeroLynn123** [comment]
请问，有导出多维的Excel表格的形式吗

**Comment by zeroLynn123** [comment]
export_json_to_excel这种方法能设置多维的表头的吗？怎么设置？谢谢

**Comment by L0nge** [comment]
定义一个合并规则类似于这样merges = [{s: {r:0,c:0}, e: {r:0,c:1}},{s: {r:0,c:2}, e: {r:0,c:4}}] 这个意思就是单元格0，0和单元格0，1合并，单元格0，2和单元格0，4合并。
export_json_to_excel方法里添加`/* add merges */
    for (let merge of merges) {
      if(!ws['!merges']) ws['!merges'] = [];
      ws['!merges'].push(merge);
    }`

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1718
