### ISSUE TITLE
请问router文件夹下的index.js中const _import为什么要根据开发和生产用两种方式导入？

### ISSUE THREAD

**Issue by qzsk0921** [PanJiaChen/vue-element-admin#529]
_import_development.js文件  
module.exports = file => require('@/views/' + file + '.vue').default
这里一定要用require吗?也用import不行吗，

_import_production.js文件
module.exports = file => () => import('@/views/' + file + '.vue')

**Comment by PanJiaChen** [comment]
https://juejin.im/post/595b4d776fb9a06bbe7dba56#heading-1
文章里有写，之后的版本会改进。

**Comment by qzsk0921** [comment]
哦，怎么改进呢，能在这里说下吗？先睹为快O(∩_∩)O

**Comment by PanJiaChen** [comment]
之后首先会观察一下在webpack@4下的速度。目前我在自己的项目中都是通过babel来实现本地和线上不同的引入方式的。

**Comment by qzsk0921** [comment]
好吧，webpack2s我完全可以接受呢。虽然不知道用babel怎么实现
还有我想请问下module.exports = file => () => import('@/views/' + file + '.vue')
为什么要加上括号直接module.exports = file => import('@/views/' + file + '.vue')动态加载不行吗？？

**Comment by PanJiaChen** [comment]
[文档](https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/lazy-loading.html#%E6%96%B0%E6%96%B9%E6%A1%88)
