### ISSUE TITLE
个别页面刷新时state值没有清空，是如何实现的？并没有看到缓存到本地。

### ISSUE THREAD

**Issue by strongfanfan** [PanJiaChen/vue-element-admin#53]
![image](https://cloud.githubusercontent.com/assets/20250430/26092368/35a71782-3a43-11e7-8921-c069ff6956a9.png)

### 比如这个页面，刷新后并没有提交mutation去获取user信息，但是state值居然不是空的

![image](https://cloud.githubusercontent.com/assets/20250430/26092461/98a76bfc-3a43-11e7-8784-d14b9c459821.png)

而且你也不是本地缓存实现的，请问你的实现思路是怎样的？  被这个问题卡了好久。我写的东西一旦刷新state就会被清空。感谢

**Comment by PanJiaChen** [comment]
本地存一个token 每刷新页面都会根据这个token 去拉一个user_info的接口

**Comment by strongfanfan** [comment]
那不应该有mutation吗？我在首页刷新会看到了三个mutation，但是这个页面没有发起mutation。

**Comment by strongfanfan** [comment]
或者你把相关代码给我，就这个‘http://localhost:9527/#/components/index’页面， 刷新后，state拉取的代码。我目前项目遇到这个问题，只能在父页面上加一个commit('getInfo')，防止刷新后state被清空。所以比较像知道你是怎么解决的

**Comment by PanJiaChen** [comment]
逻辑都在main.js 
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/main.js#L44

**Comment by strongfanfan** [comment]
卧槽。/。。。。。我一直以为在组件里，，，，我特么是笨死的吗

**Comment by redwolf1996** [comment]
> 本地存一个token 每刷新页面都会根据这个token 去拉一个user_info的接口
为什么不存localstorage之类的接口  每次刷新的时候都要去请求一个额外的接口呢  这个问题困扰了好久

**Comment by redwolf1996** [comment]
> 本地存一个token 每刷新页面都会根据这个token 去拉一个user_info的接口
我能想到的场景是 比方说一个超级管理员改了 某个普通角色的权限  然后这个人不需要重新登录只要刷新就能重新获得新的权限了   除了类似这个的 应用场景 就没别的了么？
