### ISSUE TITLE
求教一个关于sidebar收缩之后鼠标移入图标显示提示的问题

### ISSUE THREAD

**Issue by TothingWay** [PanJiaChen/vue-element-admin#530]
当鼠标移入sidebar收缩之后的的icon中（只有一个子路由的菜单），你自定义了提示的样式，而element的官方默认是使用tooltip包裹了<svg-icon>和<span>，作者你是如何删除这个tooltip提示的？修改了源代码吗？

**Comment by PanJiaChen** [comment]
Duplicate of #468
