### ISSUE TITLE
[Feature]: Update to WebPack 4

### ISSUE THREAD

**Issue by eladcandroid** [PanJiaChen/vue-element-admin#537]

**Comment by PanJiaChen** [comment]
In plan, but there are some plugins that are not yet compatible.
It will be updated as soon as possible.

**Comment by PanJiaChen** [comment]
Detail see https://github.com/PanJiaChen/vue-element-admin/pull/889

**Comment by PanJiaChen** [comment]
I will test for a while, and I will also upgrade ·vue-loader` to v15.

**Comment by PanJiaChen** [comment]
New version `v.3.8.0` has been released.
