### ISSUE TITLE
关于vue项目模块化

### ISSUE THREAD

**Issue by minikiller** [PanJiaChen/vue-element-admin#538]
故事的发生是这样的，我们服务端用的是java，使用osgi模块化技术，比如有2个模块，一个是学生，一个是老师，我安装了学生的jar包后，前端访问的时候，就可以返回带学生信息的json串，这样前端就可以获得当前用户的这个模块的权限信息。
现在我们前端采用vue进行开发，此时该如何处理学生和老师2个模块呢，我现在想到的是单独建立2个项目，分别发布到npm上，但问题是如何实现动态按需加载呢，请问您有好的解决办法吗？我知道前端也号称支持模块化，也查过资料，还是不知道这种情况下如何处理。

**Comment by PanJiaChen** [comment]
这还是需要结合具体的业务场景来看。我不是很知道你的学生和老师模板差别有多大，或者公用的东西有多少，差别不大的情况下，完全就可以直接放在一个项目里，通过动态组件或者路由来区分。

**Comment by minikiller** [comment]
学生和老师只是举例，就是2个不同的模块罢了，2者没有之间的依赖，根据用户的需要，在后端已经可以做到按需部署。我想了解的是在vue端，通过webpack如何做到按需部署呢？通过引入npm包吗？还是通过配置文件。

如果都是放在一个项目里，那样的话如果我开发多个应用的话，就会多个模块混在一个项目里。这样维护起来不是很好。

**Comment by PanJiaChen** [comment]
方案有很多种，npm也是一种，可以将每一个模块都看成一个大组件。
