### ISSUE TITLE
个人基于本司业务需求的一些小改动

### ISSUE THREAD

**Issue by smat0096** [PanJiaChen/vue-element-admin#540]
首先感谢作者大大分享， 
1. 配置 defaultLanguage， 虽然国际化是趋势， 但是大部分业务环境还是中文为主， 所以配置 config.js文件 defaultLanguage = zh；
2.由于我司后端不太和谐，接口各种崩崩崩， 忍无可忍下决定使用mockserver方案真实模拟ajax交互请求，
参考文章 https://blog.csdn.net/yyjourney/article/details/78672946的方案,配合mockjs
3,既然使用mockserver，那么previewServer就用express搭个， 完美实现半模拟数据半后台数据开发：
export function getLoginType(username) {
  let url = '/localhost/login/xxx'
  API_PROD && (url = '/api/xxx')
  return requestClientToken({
    url,
    method: 'GET',
    data: {
      username: username
    }
  })
}
4, 权限管理方面使用获取角色对应路由列表的方式进行控制， 代码有点长略
设置getter
hasPermission: (state) => (path) => {
    return hasPermission(state.user.roles, state.user.menus, path)
  }

**Comment by PanJiaChen** [comment]
谢谢你的分享
