### ISSUE TITLE
login/index 页面重新刷新还是默认的admin 和 123456

### ISSUE THREAD

**Issue by qi-wangy** [PanJiaChen/vue-element-admin#544]
views login index 修改了 loginForm 为什么页面每次渲染还是admin 123456,在login/index.vue里面的data没有初始化数据，请问为什么会这样

**Comment by qi-wangy** [comment]
补充代码:

tempalte:
  <el-form-item prop="loginname">
        <span class="svg-container svg-container_login">
          <svg-icon icon-class="user" />
        </span>
        <el-input name="loginname" type="text" v-model="loginForm.loginname" autoComplete="on" placeholder="loginname" />
      </el-form-item>

      <el-form-item prop="password">
        <span class="svg-container">
          <svg-icon icon-class="password" />
        </span>
        <el-input name="password" :type="passwordType" @keyup.enter.native="handleLogin" v-model="loginForm.password" autoComplete="on" placeholder="password" />
        <span class="show-pwd" @click="showPwd">
          <svg-icon icon-class="eye" />
        </span>
      </el-form-item>

data:
`      loginForm: {
        verifyCode: '',
        loginname: '',
        password: ''
      },`

**Comment by PanJiaChen** [comment]
没能重现，请检查自己的代码
