### ISSUE TITLE
$t

### ISSUE THREAD

**Issue by chenchao111** [PanJiaChen/vue-element-admin#547]
页面中大量使用的$t是什么啊  本人实在技术比较low 请教一下

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/utils/i18n.js#L4
为了国际化，vue-i18n。
之后完善一些这块的文档和注释。

**Comment by PanJiaChen** [comment]
Duplicate of #385
