### ISSUE TITLE
【Bug】 菜单栏二级菜单显示不对齐

### ISSUE THREAD

**Issue by ngxlua** [PanJiaChen/vue-element-admin#548]
如图，当存在二级菜单时，图标不对齐，请问是否可以帮忙修复下

![2501522326717_ pic](https://user-images.githubusercontent.com/31426367/38088997-7f1d76a8-3390-11e8-9f9d-dc68ade73ef3.jpg)

**Comment by PanJiaChen** [comment]
@ngxlua 什么版本element-ui?

**Comment by ngxlua** [comment]
@PanJiaChen  最新版本,  我将 tab 调整到 table 前面， 并给 tab 加了 icon ， 就能重现了

```
  {
    path: '/example',
    component: Layout,
    redirect: '/example/table/complex-table',
    name: 'example',
    meta: {
      title: 'example',
      icon: 'example'
    },
    children: [
      {
        path: 'tab/index',
        icon: 'table',
        component: _import('example/tab/index'),
        name: 'tab',
        meta: { title: 'tab', icon: 'table' }
      },
      {
        path: '/example/table',
        component: _import('example/table/index'),
        redirect: '/example/table/complex-table',
        name: 'Table',
        meta: {
          title: 'Table',
          icon: 'table'
        },
        children: [
          {
            path: 'dynamic-table',
            component: _import('example/table/dynamicTable/index'),
            name: 'dynamicTable',
            meta: { title: 'dynamicTable' }
          },
          ...
        ]
      }
    ]
  },
```

**Comment by ngxlua** [comment]
@PanJiaChen  您这边可以复现了吗?

**Comment by ngxlua** [comment]
@PanJiaChen 你好，我这样修改了代码，您看下，是否是我写错了

# git status

```
git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/router/index.js

no changes added to commit (use "git add" and/or "git commit -a")
```

# 当前 master 分支，将代码改为:

<img width="1204" alt="123123" src="https://user-images.githubusercontent.com/31426367/38462576-1ed8cba6-3b1c-11e8-8af8-98edecbcf766.png">



# 修改代码后，预览如下:

![1523156039965](https://user-images.githubusercontent.com/31426367/38462527-3122702e-3b1b-11e8-988e-847239cf2a8f.jpg)

**Comment by ngxlua** [comment]
补充一下， 我发现和修改代码没关系，我将代码置为 master 分支未修改版本然后也会这样， -_-||

**Comment by PanJiaChen** [comment]
看着像兼容性问题，都说一下什么平台什么游览器么？

**Comment by ngxlua** [comment]
@PanJiaChen  

## 系统 : 

Mac OS 10.3.3

## 浏览器: 

safari: Version 11.0.3 
chrome: Version 65.0.3325.181

以上两种浏览器在我机器上都可以复现

----

## node_modules:

无缓存运行 npm install

**Comment by ngxlua** [comment]
@PanJiaChen 你好， 我想请问下，这个问题被确定了吗， 我这边什么也没改就master代码就会这样， 但在线的demo 没有问题

**Comment by PanJiaChen** [comment]
发布了新版本，看是否还有问题
