### ISSUE TITLE
在导入excel那里，先导入一个excel，然后点击导入按钮，把弹出的选择excel框关掉会报一个错

### ISSUE THREAD

**Issue by Ssanmifoguang** [PanJiaChen/vue-element-admin#549]

**Comment by PanJiaChen** [comment]
请详细说明，未能重现

**Comment by Ssanmifoguang** [comment]
首先先导入一个excel
![image](https://user-images.githubusercontent.com/19749754/38127203-a941fb2e-3427-11e8-999a-c03a09a2287a.png)然后继续点击上传按钮，但是不选择文件，而是直接关闭，这时控制台会有报错
![image](https://user-images.githubusercontent.com/19749754/38127258-f65365ec-3427-11e8-8ac1-0ec79288db21.png)

**Comment by Ssanmifoguang** [comment]
如果我导入一个excel，然后我这个excel修改了一些东西，我再选择这个excel上传，数据不会更新，必须刷新再上传才能更新数据，如果是两个不同的excel就不会有这个问题

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/afe975b3c2eb9fa313b348b38880fe77e8f117f6
