### ISSUE TITLE
建议弄一个vue-cli模板

### ISSUE THREAD

**Issue by unhappy224** [PanJiaChen/vue-element-admin#55]
如果直接上手开发的话要删除现有的页面,路由和vuex相关的东西,有点无从下手,希望弄个纯净点的模板工程.

**Comment by PanJiaChen** [comment]
干净的模板你直接用vue-cli就好了啊。。。

**Comment by unhappy224** [comment]
我的意思是包含了element和你里面那些components的模板.
是不是只要删除了page, page相关的vuex,和路由就算纯净的了?

**Comment by PanJiaChen** [comment]
每个人需要都不一样，那权限验证 登录 要不要呢 众口难调的 我是觉得基于vue-cli构建之后 
要什么自己从这个项目里拿就好了 
这个项目并不是一个脚手架，更倾向于是一个集成方案 你要什么就拿生命

**Comment by unhappy224** [comment]
好的 O(∩_∩)O谢谢
