### ISSUE TITLE
Module build failed: Error: No ESLint configuration found.

### ISSUE THREAD

**Issue by HiZhaoxiaoyang** [PanJiaChen/vue-element-admin#553]
10分钟前git clone的，然后就这样了，报错进不去

**Comment by HiZhaoxiaoyang** [comment]
![image](https://user-images.githubusercontent.com/1161835/38144068-e7725a94-3475-11e8-8a74-26c3cbf58b72.png)

重新git clone，yarn taobao源，报如上错，不过凑合能运行了。 可能是npm版本的问题，webpack热加载这里。

**Comment by HiZhaoxiaoyang** [comment]
modules 5 active ...n/node_modules/webpack/hot/emitter.jsURIError: Failed to decode param '/%3C%='

**Comment by HiZhaoxiaoyang** [comment]
是否和yarn有关

**Comment by PanJiaChen** [comment]
有可能，因为我平时不是有`yarn` 所以不是很清楚。暂时先关闭了，若还有该问题，再重新打开。目前认为是个人案例。
