### ISSUE TITLE
A bug in tagsView function

### ISSUE THREAD

**Issue by YangAi** [PanJiaChen/vue-element-admin#555]
I found a bug in tagsView function when I shift a tab to another, and then shift back. the new route will lose its query.

I believe it's because Vuex recorded $route.path instead of $route.fullPath in store/modules.tagsView.js.

the original code:
`ADD_VISITED_VIEWS: (state, view) => {
      if (state.visitedViews.some(v => v.path === view.path)) return
      state.visitedViews.push({
        name: view.name,
        path: view.path,
        title: view.meta.title || 'no-name'
      })
      if (!view.meta.noCache) {
        state.cachedViews.push(view.name)
      }
    }`

the code I modified:
`ADD_VISITED_VIEWS: (state, view) => {
      if (state.visitedViews.some(v => v.path === view.fullPath)) return
      state.visitedViews.push({
        name: view.name,
        path: view.fullPath,
        title: view.meta.title || 'no-name'
      })
      if (!view.meta.noCache) {
        state.cachedViews.push(view.name)
      }
    }`

**Comment by EugeniaZhang** [comment]
This problem still exists

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/765
