### ISSUE TITLE
permission的改动

### ISSUE THREAD

**Issue by chantel186** [PanJiaChen/vue-element-admin#556]
[登录请求成功之后，我应该怎么跳转到首页，我现在一直跳转到的是这样的页面！
![1522634382 1](https://user-images.githubusercontent.com/37990172/38180130-b84e0874-365c-11e8-8dc6-c5480e5b3d79.png)
却不是这个页面
![1522634345 1](https://user-images.githubusercontent.com/37990172/38180134-c286e4a0-365c-11e8-8cef-1474456e48d0.png)
我需要进行怎么样的修改呢 ？

**Comment by PanJiaChen** [comment]
都是首页，只是两个不同权限的首页。`editor`和`admin`。请退出重新永别的账户登录即可。
