### ISSUE TITLE
tags切换 参数丢失

### ISSUE THREAD

**Issue by sunmorg** [PanJiaChen/vue-element-admin#560]
tags切换 参数丢失 
通过页面点击跳转得带参路由
在tags切换时参数丢失

**Comment by PanJiaChen** [comment]
Duplicate of #350

**Comment by Huang-An** [comment]
路由切换时，好像没有在vuex里记录传递的参数。
可以在store/modules/tagsView.js文件里ADD_VISITED_VIEWS时记录下传递的参数
 state.visitedViews.push({
        name: view.name,
        path: view.path,
        title: view.meta.title || 'no-name',
        query: view.query
})
然后在tagsView.vue中循环渲染router-link的时候带上参数，将:to=tag.path改为
:to="{path: tag.path, query: tag.query}"

**Comment by sunmorg** [comment]
那请问是否可以以param的形式

**Comment by tracybug** [comment]
唯一不同的是 通过 push
      this.$router.push({
        name: 'editArticle', params: {
          id: id
        }
      })
我修改了一下demo#713，改成这样也不会有问题。只是去掉中间的edit.vue，直接路由到ArticleDetail则会复现问题，实在搞不懂为什么。。。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/765

**Comment by gaollard** [comment]
我觉得用query来传递参数的话，根本无法保证不丢失，应该尽量用param传参，不重要的参数可以通过 query传参然后设置默认值。
