### ISSUE TITLE
面包屑不支持:id的方式？ Breadcrumb not support params

### ISSUE THREAD

**Issue by lixing0323** [PanJiaChen/vue-element-admin#561]
一. 路由文件是这样设置的： 
path: ':id/details',
hidden: true,

二. 一步一步深入到界面，面包屑是这样显示的，首页/活动管理/详情/单活动分析。

三. 这个时候点击面包屑中的详情。发现取不到:id的真实值。
看样式a标签的内容是这样子的：“data-v-cc995e54="" href="#/events/:id/details" class="">详情”

请问，是我设置错了，还是有bug?

**Comment by PanJiaChen** [comment]
暂时不支持

**Comment by lixing0323** [comment]
@PanJiaChen 绝望啊。。。我自己尝试能否修复。

**Comment by lixing0323** [comment]
@

**Comment by lixing0323** [comment]
@

**Comment by lixing0323** [comment]
@PanJiaChen ，我这样修改的，可以用了。你可以看看。

把这个<router-link v-else :to="item.redirect||item.path">改为
<router-link v-else :to="getGoToPath(item)">

// 获取当前的链接路径
    getGoToPath(item) {
      if (item.path) {
        var path = item.path;
        var startPos = path.indexOf(":");

        if (startPos !== -1) {
          var endPos = path.indexOf("/", startPos);
          var key = path.substring(startPos + 1, endPos);
          path = path.replace(":" + key, this.$route.params[key]);
          return path;
        }
      }

      return item.redirect || item.path;
    }

**Comment by PanJiaChen** [comment]
Added in https://github.com/PanJiaChen/vue-element-admin/pull/1148

**Comment by duyuying** [comment]
没看太懂啊

**Comment by wanglei158** [comment]
> 一. 路由文件是这样设置的：
> path: ':id/details',
> hidden: true,
> 
> 二. 一步一步深入到界面，面包屑是这样显示的，首页/活动管理/详情/单活动分析。
> 
> 三. 这个时候点击面包屑中的详情。发现取不到:id的真实值。
> 看样式a标签的内容是这样子的：“data-v-cc995e54="" href="#/events/:id/details" class="">详情”
> 
> 请问，是我设置错了，还是有bug?

#/events/:id/details是单活动分析页，还是详情页？
