### ISSUE TITLE
axios请求不携带cookie

### ISSUE THREAD

**Issue by ganchaoyang** [PanJiaChen/vue-element-admin#562]
在网上查询是需要设置axios.defaults.withCredentials为true。但是我在/utils/request.js里设置了如下内容后，请求仍然没有携带Cookie。
```
import axios from 'axios'
import { Message } from 'element-ui'
import store from '@/store'
import { getToken } from '@/utils/auth'

axios.defaults.withCredentials = true

```

**Comment by gdxieyue** [comment]
// 创建axios实例
const service = axios.create({
    baseURL: process.env.BASE_API, // api的base_url
    timeout: 5000,                  // 请求超时时间
    withCredentials: true,
    crossDomain: true,
});
同问，如上配置后，我发起跨域请求，无法带上cookie信息

**Comment by PanJiaChen** [comment]
在跨域的情况下不仅前端要设置`withCredentials`，后端也是要设置`Access-Control-Allow-Credentials`的。

**Comment by ganchaoyang** [comment]
后端设置过了这个。在请求头里面看到了。

**Comment by PanJiaChen** [comment]
请提供更多信息。

**Comment by ganchaoyang** [comment]
后端（SpringBoot）跨域的配置：
```
@Configuration
public class MyWebAppConfigurer extends WebMvcConfigurerAdapter {

    @Override
    public void addCorsMappings(CorsRegistry registry) {
        registry.addMapping("/**");
    }
}
```
前端的配置：
```
const service = axios.create({
  baseURL: process.env.BASE_API, // api的base_url
  timeout: 5000, // request timeout
  withCredentials: true
})
```
在请求中的Response Headers中看到了有Access-Control-Allow-Credentials: true。

**Comment by PanJiaChen** [comment]
游览器是否有报错，或者能否截图一下请求。

**Comment by ganchaoyang** [comment]
浏览器没有报错，下面是我截的登录请求。
![1](https://user-images.githubusercontent.com/30206916/38222685-d5f1d68c-3718-11e8-9f15-23806a372a19.png)

**Comment by gdxieyue** [comment]
【背景】:
本地机器开启web前端，localhost:9527（不使用mock，proxyTables）；用户登陆后端系统：192.169.31.100:58001/services/login/Login(Jetty后端)。
【问题】：
请求验证码，发起登陆请求，这两次请求，session都不一样。request不会带上cookies

【详细】：
首先请求验证码，服务器返回如下：
HTTP/1.1 200 OK
Date: Tue, 03 Apr 2018 01:57:43 GMT
Last-Modified: Mon, 26 Jul 1970 05:00:00 GMT
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Access-Control-Allow-Origin: http://localhost:9527
Access-Control-Allow-Credentials: true
Set-Cookie: JSESSIONID=u8kyf0pxga3jcx62butdn9uk;Path=/
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Type: image/jpeg;charset=utf-8
Transfer-Encoding: chunked
Server: Jetty(8.1.15.v20140411)

接着请求登陆，返回如下：
HTTP/1.1 200 OK
Date: Tue, 03 Apr 2018 01:57:44 GMT
Last-Modified: Mon, 26 Jul 1970 05:00:00 GMT
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Access-Control-Allow-Origin: http://localhost:9527
Access-Control-Allow-Credentials: true
Set-Cookie: JSESSIONID=1b9xbr0czbdgv1gjswto6if480;Path=/
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Type: application/json;charset=utf-8
Content-Length: 199
Server: Jetty(8.1.15.v20140411)

请求登陆，返回如下：
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://localhost:9527
Cache-Control:no-cache, must-revalidate
Content-Length:136
Content-Type:application/json;charset=utf-8
Date:Tue, 03 Apr 2018 02:06:10 GMT
Expires:Thu, 01 Jan 1970 00:00:00 GMT
Last-Modified:Mon, 26 Jul 1970 05:00:00 GMT
Pragma:no-cache
Server:Jetty(8.1.15.v20140411)
Set-Cookie:JSESSIONID=hjrug289s0wx1d82bcodon8ie;Path=/

**Comment by PanJiaChen** [comment]
你这个都不跨域，后端和前台都是8088。默认自带cookie，无需任何设置。
如果你基于本项目修改的话，很可能是被`mockjs`影响的。
https://github.com/PanJiaChen/vue-element-admin/blob/afe975b3c2eb9fa313b348b38880fe77e8f117f6/src/main.js#L18
移除试试。

**Comment by ganchaoyang** [comment]
嗯嗯，是这个原因，移除之后就携带Cookie了。万分感谢。

**Comment by gdxieyue** [comment]
import './mock'  移除掉后问题已解决。
多谢大师帮忙解决这个让我百思不得骑姐的问题。

但我又有疑惑，原先我只是注释掉  ./mock/index.js 里面的配置，这样还是会影响axios请求？
`
// Mock.mock(/\/services\/login\/Login/, 'post', loginAPI.loginByUser);
`

**Comment by PanJiaChen** [comment]
mockjs 问题蛮多的他会重新定义httprequest。之后可能不用它了。

**Comment by wuzhihui1123** [comment]
@PanJiaChen  谢谢， 解决了我的问题

**Comment by jiangxiaoxin** [comment]
@gdxieyue Mockjs只要你调用它的mock方法，他就会劫持window的XMLHttpRequest对象，用一个自己的XHR替换，那里面withCredentials是false的，所以你带不上cookie

**Comment by onyz4x** [comment]
这个问题困扰了一个上午，谢天谢地在这里找到了

**Comment by zhangenming** [comment]
一样的问题

但去掉mock之后就没办法登录了呀
我现在还是用的本身的登录账号密码
怎么办呢

**Comment by CfortWang** [comment]
同样遇到这个问题，但是没有引入mock.js，前端设置withCredentials:ture，后台设置Access-Control-Allow-Credentials: true，Access-Control-Allow-Origin: http://localhost:8081但还是获取不到cookie，还有什么其他的原因吗？

**Comment by uwooz** [comment]
感谢，解决了我找了一天的问题

**Comment by DiaoHu** [comment]
这是个巨坑啊，昨天我也被这个问题折腾了一天 o(╥﹏╥)o，去掉了mian.js里的导入mock就搞定了

**Comment by DiaoHu** [comment]
> 08

这是个巨坑啊，昨天我也被这个问题折腾了一天 o(╥﹏╥)o，去掉了mian.js里的导入mock就搞定了，感谢感谢

**Comment by PanJiaChen** [comment]
https://github.com/nuysoft/Mock/issues/300

**Comment by zhangshaolong** [comment]
如果在开发联调中的mock，推荐使用mock-proxy-middleware
如果qa阶段的mock，推荐mock-proxy-tool
不仅比较灵活支持各种mock类型的数据，也可以支持弱网mock，上下文状态mock，动态mock，动态代理及动态path映射等

**Comment by lpy681** [comment]
所以为什么不在readme里面重点标注下这个功能呢？要提醒去掉
一般人真找不到原因啊。哭死

**Comment by Tschiho** [comment]
> 同样遇到这个问题，但是没有引入mock.js，前端设置withCredentials:ture，后台设置Access-Control-Allow-Credentials: true，Access-Control-Allow-Origin: [http://localhost:8081但还是获取不到cookie，还有什么其他的原因吗？](http://localhost:8081%E4%BD%86%E8%BF%98%E6%98%AF%E8%8E%B7%E5%8F%96%E4%B8%8D%E5%88%B0cookie%EF%BC%8C%E8%BF%98%E6%9C%89%E4%BB%80%E4%B9%88%E5%85%B6%E4%BB%96%E7%9A%84%E5%8E%9F%E5%9B%A0%E5%90%97%EF%BC%9F)

问下你解决了吗？ 是怎么解决的。

**Comment by shidashui** [comment]
samSite也要设置为None

**Comment by linzhi** [comment]
删掉mock.js后还是不行

**Comment by 2720851545** [comment]
chrome 78还是79后面的浏览器, cookie 默认SameSite属性会影响到, 你们可以用其他浏览器测试一下
