### ISSUE TITLE
跨域后台API 问题，请教

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#567]
裤衩大大：

新新手问题。我另外建了个后台API，服务启动在 https://localhost:9999

1. 修改了 config\prod.env.js
module.exports = {
  NODE_ENV: '"production"',
  ENV_CONFIG: '"prod"',
  BASE_API: '"https://localhost:9999"' // 修改
}

2. 屏蔽了 src\mock\index.js 中登录相关代码
// 登录相关
// Mock.mock(/\/login\/login/, 'post', loginAPI.loginByUsername)
// Mock.mock(/\/login\/logout/, 'post', loginAPI.logout)
// Mock.mock(/\/user\/info\.*/, 'get', loginAPI.getUserInfo)

3. 正常启动 http://localhost:9527，点击Log in。报网络错误。 F12 看到 XMLHttpRequest: Network Error 0x80070005, Access is denied 错误信息。

请教下：前后分离形式还需要其他修改吗？正式发布环境是不是一样需要同样修改？

谢谢！

**Comment by PanJiaChen** [comment]
跨域，请自行查阅网上跨域方案。网上的回答还是很多的。
