### ISSUE TITLE
为什么我在login.js里面添加一个参数不起作用？

### ISSUE THREAD

**Issue by ttdms** [PanJiaChen/vue-element-admin#572]
`export function login(username, password, verify) {
  return request({
    url: 'base/login',
    method: 'post',
    data: {
      username,
      password,
      verify
    }
  })
}`
因为登录需要用带验证码验证，所以增加了一个verify，但是提交的时候好像并没有把verify一起传过去，只有username和password。
在页面上打印 this.loginForm 是存在 verify 的。

**Comment by PanJiaChen** [comment]
本项目只是demo，有需求请自行修改代码。
https://github.com/PanJiaChen/vue-element-admin/blob/3cff6dcf4c01d1bdf3faa7d0bcae4a16c28e5d2e/src/api/login.js#L3-L13
