### ISSUE TITLE
富文本似乎有些问题？

### ISSUE THREAD

**Issue by bowencool** [PanJiaChen/vue-element-admin#573]
![image](https://user-images.githubusercontent.com/20217146/38424153-b702c476-39e2-11e8-8fbd-1d013f3d7982.png)
windows 10下
chrome 65和edge 41都是这样

**Comment by PanJiaChen** [comment]
因为在`Tinymce`的`plugins`中，不小心引入了`bbcode`导致的。
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/f28a7149fbcccee50620dab3bebbb5433841b483
