### ISSUE TITLE
tree-table 能否添加一个props的配置项，它接收一个object，因为后台返回的数据不都是带有children字段的，

### ISSUE THREAD

**Issue by dawayway** [PanJiaChen/vue-element-admin#574]
裤衩哥，
tree-table 能否添加一个props的配置项，它接收一个object，因为后台返回的数据不都是带有children字段的，我自行添加后不管用，烦请裤衩哥考虑这个需求。

**Comment by Windying** [comment]
我也需要同样的需求。

**Comment by wangxueyou110** [comment]
稍微在代码上改下就好了

**Comment by wangxueyou110** [comment]
![image](https://user-images.githubusercontent.com/30291910/38662435-da983316-3e66-11e8-9541-bf0433738691.png)
在index.vue中改
![image](https://user-images.githubusercontent.com/30291910/38662460-f0727a84-3e66-11e8-8bc2-cdea60e28b70.png)
![image](https://user-images.githubusercontent.com/30291910/38662466-f8a7c664-3e66-11e8-9b71-5465e74a5f2b.png)
在eval.js中改
![image](https://user-images.githubusercontent.com/30291910/38662493-07bdbf3c-3e67-11e8-906c-523cdb336852.png)

**Comment by wangxueyou110** [comment]
在TreeTable 下的index.vue里还要加
![image](https://user-images.githubusercontent.com/30291910/38662672-ab58427a-3e67-11e8-93da-8b0a68cb340a.png)

**Comment by PanJiaChen** [comment]
已不在维护 tree-table. 请使用 element-ui 的 tree-table.
