### ISSUE TITLE
跨域问题请教下！

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#576]
我屏蔽了 main.js里的  import './mock' 
修改了 config\dev.env.js 里的 BASE_API: '"http://localhost:9999/api"',  变成另个端口的服务
起了一个9999端口的服务， 使用了楼主推荐的cors

let cors = require('cors');
app.use(cors({
    origin:['http://localhost:9527'],
    methods:['GET','POST'],
    alloweHeaders:['Conten-Type', 'Authorization']
}));

在vue里点击登录，尝试调用 http://localhost:9999/api/login/login 接口 （独立访问该地址，能正常返回一个json结果）。 结果报了个  errError: Request failed with status code 404 错误

请教下大大是什么原因？

**Comment by moonose** [comment]
[](url)

**Comment by PanJiaChen** [comment]
你method没写对吧，你游览器能访问正确因为是get请求，但你其实想要的是post。

**Comment by moonose** [comment]
膜拜，果然是这个原因！非常感谢～

**Comment by TechFancy** [comment]
前几天也遇到这个问题，开始也搜了很多，也按着上面的 方法操作，最终并没有解决，我拉取的是vue-element-admin国际化的i18n分支，在win10上什么都不用改，就能直接run起来，可是到了macmini上，就是不行，登录都时候报错：Request failed with status code 405，最后搜一个大佬说都，在mac上修改一下就好了。
https://gitter.im/vue-element-admin/discuss
