### ISSUE TITLE
树表的多选不能获取到值

### ISSUE THREAD

**Issue by poemxl** [PanJiaChen/vue-element-admin#577]
请问大神，这个树表的多选，似乎不会触发selection-change，试过select或select-all都不会触发
![image](https://user-images.githubusercontent.com/37215215/38465272-77f4a00e-3b4c-11e8-8f3b-8ec4f28e0dde.png)
![image](https://user-images.githubusercontent.com/37215215/38465275-88de4c12-3b4c-11e8-95ab-82828301dd7c.png)
![image](https://user-images.githubusercontent.com/37215215/38465307-e894b7ea-3b4c-11e8-87f4-8ff0fa24bbfb.png)

**Comment by PanJiaChen** [comment]
抽空会优化一下这个组件。

**Comment by poemxl** [comment]
感谢回复^_^

**Comment by leij1ang** [comment]
这是因为treeTable里并没有`selection-change`这个事件，你可以将函数传到eltable中，在eltable触发

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1587
