### ISSUE TITLE
后台API 返回值问题

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#579]
裤衩大大，请教个问题：

如果调用了后台真实api，如登录验证用户名和密码，后台api返回json值，
以下逻辑里，catch不是就不会走了吗？难道要后台报错   
   loginByUsername(username, userInfo.password).then(response => {
         commit('SET_TOKEN', data.token)
          setToken(response.data.token)
          resolve() 
        }).catch(error => {
          reject(error)
        })
如果 用户名和密码错误，json返回一个错误代码，这时data.token是undefined, 是不是这里的逻辑都要更具后台来改变一下？来判定是否要走 setToken

**Comment by PanJiaChen** [comment]
日常我会在[request.js](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/utils/request.js)统一做处理。
如果是特例你可以自己在then里面特殊判断。

**Comment by ghdestiny** [comment]
请问then里面获取的是undefined是什么原因？？？

**Comment by godIsAProgrammer** [comment]
> 请问then里面获取的是undefined是什么原因？？？

服务端成功接收到参数了吗？

**Comment by godIsAProgrammer** [comment]
> 裤衩大大，请教个问题：
> 
> 如果调用了后台真实api，如登录验证用户名和密码，后台api返回json值，
> 以下逻辑里，catch不是就不会走了吗？难道要后台报错
> loginByUsername(username, userInfo.password).then(response => {
> commit('SET_TOKEN', data.token)
> setToken(response.data.token)
> resolve()
> }).catch(error => {
> reject(error)
> })
> 如果 用户名和密码错误，json返回一个错误代码，这时data.token是undefined, 是不是这里的逻辑都要更具后台来改变一下？来判定是否要走 setToken
可以在 then 里面判断 response，根据不同的结果做不同的响应操作。
