### ISSUE TITLE
多域请求特性

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#581]
既然vue可以做到前后台分离，跨域请求，想到这样的应用场景：一组功能是请求a服务器的，一组功能是请求b服务器的，。。。等等。裤衩大大有什么好想法，或者作为一个待开发功能。😊

**Comment by PanJiaChen** [comment]
这个很常见需求吧。声明多个`BASE_API`就可以了。
https://github.com/PanJiaChen/vue-element-admin/blob/01442ce4d75ea33b7ff8eba55b558a7c1339baeb/config/dev.env.js#L4
![image](https://user-images.githubusercontent.com/8121621/38498214-3ad1e4c6-3c36-11e8-85c3-1823977e7dc3.png)

**Comment by moonose** [comment]
看代码有点糊涂，请教下：
1. config/dev.env.js  里可以设置多个不同的 BASE_API， 如BASE_API1，BASE_API2 是吧
2. request.js里 const service = axios.create({  该如何判断用哪个 BASE_API呢？ API目录下的js文件，每个请求是不是都会被request.js的axios拦截后再封装调用，request.js 里 const service = axios.create({
  baseURL: process.env.BASE_API,   timeout: 5000 }) 这个 instance 的 baseURL 在哪用到？

非常感谢～

**Comment by PanJiaChen** [comment]
两种方案，可以创建多个不同的axios实例。或者就默认写一个，像我上面截图发的那样，特殊的就特备的写一个`baseURL`来覆盖默认的。

**Comment by moonose** [comment]
非常感谢。我在api目录下的js文件里，扩展了个domain属性，在 config/dev.env.js 里可以设置多个不同的 BASE_API，然后在request.js 里可以根据config.domain 的值来 重新设置多域。想问下：
我单独 console.log(config.url) 是，显示的是 /login/login，因为在 api/ login.js里有定义，但是console.log(config) 时，显示的 url值是 http://localhost:9999/api/login/login，已经把 BASE_API 定义的路径给拼装了，这是在哪个js里什么时候做的？

**Comment by PanJiaChen** [comment]
utils/request.js

**Comment by moonose** [comment]
我就是看这个文件来着，const service = axios.create.....service.interceptors.request.use(config => ....
config => 这个方法就自动拼装了？
