### ISSUE TITLE
form表单验证当data多层时不支持

### ISSUE THREAD

**Issue by BlackEyeByLee** [PanJiaChen/vue-element-admin#582]
如果data里边数数据是单层的，那么验证时没问题的

> 
    <el-form v-model="serverData" :rules="rules">
       <el-form-item label="Team Name" prop="teamName">
       <el-input></el-input>
       </el-form-item>
    </el-form>

如果数据是多层   v-model="xx.xx"  ，则验证无效

> 
    <el-form v-model="serverData.team" :rules="rules">
       <el-form-item label="Team Name" prop="teamName">
       <el-input></el-input>
       </el-form-item>
    </el-form>

data里边结构是多层的：
![image](https://user-images.githubusercontent.com/23404946/38531784-3fbc96e8-3ca4-11e8-90ab-30d411d6edc4.png)

**Comment by PanJiaChen** [comment]
该问题，应该去[element](https://github.com/ElemeFE/element)官方提，或者去社区论坛寻求解决方案。

**Comment by BlackEyeByLee** [comment]
@PanJiaChen 官网提了，那边没给方案，我想老哥是不是也遇到过和有思路....

**Comment by PanJiaChen** [comment]
https://github.com/ElemeFE/element/issues/2719

**Comment by BlackEyeByLee** [comment]
@PanJiaChen 老哥，怪我眼瞎，那我关闭问题咯，谢了
