### ISSUE TITLE
裤衩哥，现在有没有将页面内容导出为word格式的内容的插件？

### ISSUE THREAD

**Issue by dawayway** [PanJiaChen/vue-element-admin#584]
裤衩哥，现在有没有将页面内容导出为word格式的内容的插件？

**Comment by PanJiaChen** [comment]
- https://stackoverflow.com/questions/1624485/how-to-convert-html-file-to-word?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
- https://convertio.co/zh/html-doc/
这种比较个人的需求，请自行解决。
