### ISSUE TITLE
点击空白新增按钮，相应的打开一个新的路由

### ISSUE THREAD

**Issue by MrJiangZhiGuo** [PanJiaChen/vue-element-admin#590]
![qq 20180411152723](https://user-images.githubusercontent.com/26242617/38602591-cc564410-3d9d-11e8-9250-e05954ea2639.png)

**Comment by PanJiaChen** [comment]
个人需求。

**Comment by MrJiangZhiGuo** [comment]
请问下，如何实现呢？ 有什么好的方法？

**Comment by PanJiaChen** [comment]
这种功能其实是和spa开发模式违背的。如果不是用<keep-alive>还好做一点。
两种方案：
- 每一个采购入库单对应的路由不同。如：purchase/1  purchase/2
- 还是共有一个路由，新增或者切换页面的时候帮当期页面数据存贮在localstorage, 切换回来的时候再去回显。

**Comment by MrJiangZhiGuo** [comment]
您理解的第一个意思是对的，点击一个空白新增按钮，就打开一个对应的路由，可以打开多个。 就是这样的需求，

**Comment by MrJiangZhiGuo** [comment]
大概就是您说的这个意思，就是每次点击空白新增按钮，就打开新增一个空白的当前的页面，请问下这样如何实现呢？ 我的路由是根据后台接口返回的参数来动态生成的路由，怎么实现好呢？ 请问下有什么好的方法吗？

**Comment by nabaonan** [comment]
你是说跟浏览器标签似的，点击一个按钮在标签栏新增一个页面吧，我感觉这个好像可以通过vuerouter的addrouters方法实现吧，最近也想做这个需求，回头看看能不能实现
