### ISSUE TITLE
如何真正实现和后台的数据交互

### ISSUE THREAD

**Issue by renjiankun12** [PanJiaChen/vue-element-admin#594]
我这几天刚刚下载了这个项目，现在想用这个做一个后台管理系统，想请教一下如何能调用后台给的接口获取数据而不是使用mock模拟数据?

**Comment by PanJiaChen** [comment]
注释mockjs 引入不就好了。
请自行查看文档
https://panjiachen.github.io/vue-element-admin-site/#/zh-cn/mock-api
https://panjiachen.github.io/vue-element-admin-site/#/zh-cn/server
