### ISSUE TITLE
强烈建议优化tab的效果

### ISSUE THREAD

**Issue by fengnex** [PanJiaChen/vue-element-admin#598]
1、tab之间缩小间距，最好做出默认的那种
2、最重要的，添加tab的管理功能，在tab太多的时候，从后面没法直接找到、打开前面的tab，必须点接近前面的tab，然后更前面才会逐渐显示，使用非常不方便

具体的效果可以参考下面这个示例：
![image](https://user-images.githubusercontent.com/26297547/38722403-692d318e-3f30-11e8-96d3-2acae8c0f9e5.png)

**Comment by fengnex** [comment]
上面这个图中，tab太多的时候，就像table分页的效果类似，在tab的开始、结束分别有2个带有箭头的按钮，这样方便找tab，比模板目前的效果要好

**Comment by bmvsnada** [comment]
你研究过源码么，对于tab太多，裤衩其实考虑到了的，你试试用鼠标滚轮看看！

**Comment by fengnex** [comment]
就不能好好说话吗？

**Comment by fengnex** [comment]
谢谢，的确考虑到了，可以关掉了
