### ISSUE TITLE
windows平台运行npm install的依赖问题

### ISSUE THREAD

**Issue by tonymiao2012** [PanJiaChen/vue-element-admin#60]
你好。我把项目fork下来，然后在我的windows机器上运行npm install，发现如下错误：

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

发现这个是platform相关依赖，这种依赖是否能有解决办法呢？能否通过config文件来配置platform环境？

**Comment by PanJiaChen** [comment]
试试
npm cache clear
npm install --no-optional

**Comment by tonymiao2012** [comment]
@PanJiaChen 问题解决了。感谢。我觉得可以附在wiki里面提醒win用户怎么来安装。
