### ISSUE TITLE
点击 调整每页显示条数 分页下拉会在侧边栏上闪动

### ISSUE THREAD

**Issue by zengzhaofei** [PanJiaChen/vue-element-admin#601]
![km0 p bz1 hrf yx fe 53](https://user-images.githubusercontent.com/26245939/38786772-9739109c-415c-11e8-94a6-65e96c1d5d05.png)

**Comment by zengzhaofei** [comment]
在其它位置点击 左上会闪动

**Comment by zengzhaofei** [comment]
![mif w9erpjcm y bxjg6b](https://user-images.githubusercontent.com/26245939/38786837-0cfb5506-415d-11e8-976e-a2e7c74408ba.png)

**Comment by PanJiaChen** [comment]
请确认你使用的版本，很久之前已修复。
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/83e56488d85b796e7dd4c56011021f0bad8bee1d
