### ISSUE TITLE
This dependency was not found:  * svg-baker-runtime/browser-symbol

### ISSUE THREAD

**Issue by henrY2Young** [PanJiaChen/vue-element-admin#603]
This dependency was not found:

* svg-baker-runtime/browser-symbol

- 提示这个错误，安装
- npm install --save svg-baker-runtime/browser-symbol 发现
fatal: Could not read from remote repository.
- 这个要怎么解决？

**Comment by PanJiaChen** [comment]
重新安装这个包就可以了

**Comment by codevvvv9** [comment]
单独安装也安不上，node 16.19.0 LTS版本

**Comment by codevvvv9** [comment]
> 单独安装也安不上，node 16.19.0 LTS版本
单独安装时报错，执行下面命令就解决了：
npm install --save regenerator-runtime svg-baker-runtime vue-style-loader

**Comment by kuchaguangjie** [comment]
pnpm 可以用:
> pnpm add regenerator-runtime svg-baker-runtime vue-style-loader
