### ISSUE TITLE
Tinymce 引用不进来

### ISSUE THREAD

**Issue by weige0088** [PanJiaChen/vue-element-admin#605]
我已经把Tinymce 拷贝到我文件夹内 （我没有用你们的模板，用的是自己搭建的）
组件中也调用了
index.html 中也引入的 那个script  
但是就是出不来啊
指能出现上传图片那，文本编辑器出不来
下面是错误提示， 
Uncaught SyntaxError: Unexpected token <

[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'init' of undefined"

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/index.html
请保证你的Tinymce 引入在你的app.js 引入之前。

**Comment by weige0088** [comment]
在之前引入了 
报错： Uncaught SyntaxError: Unexpected token <
是不是   htmlWebpackPlugin.options.path   这个路径获取不到啊？

**Comment by PanJiaChen** [comment]
那需要你自行配置了。

**Comment by weige0088** [comment]
不晓得怎么去配置啊，在哪个文件里面配置呢？
Tinymce  引用这个文件都需要注意或者修改什么地方呢？
