### ISSUE TITLE
怎样支持顶部->左边两级菜单？

### ISSUE THREAD

**Issue by fengnex** [PanJiaChen/vue-element-admin#608]
如下图所所示，整个菜单包括顶部导航栏和左边栏，点击ding顶部导航栏上的某个菜单，左边栏上的菜单的内容会相应地变化
图片一直无法上传，后面看看能不能补

**Comment by fengnex** [comment]
![default](https://user-images.githubusercontent.com/26297547/38921985-ae470572-4329-11e8-9fe8-032839036feb.png)

**Comment by fengnex** [comment]
上图的这种菜单组织方式，对于功能模块比较多的系统很有帮助，希望能实现，谢谢！

**Comment by PanJiaChen** [comment]
不准备支持。

**Comment by fengnex** [comment]
能否说名下原因？

**Comment by PanJiaChen** [comment]
本项目不可能满足所有的需求，自己加也很简单。

**Comment by fengnex** [comment]
对于vue了解的还不多，能否围绕这个问题提供些参考资源或建议？谢谢

**Comment by PanJiaChen** [comment]
首先和vue关系不大，其次建议补基础。本项目是需要一定基础的。
![image](https://user-images.githubusercontent.com/8121621/38943237-765d565e-4363-11e8-8cc9-821a2b5fe26a.png)
