### ISSUE TITLE
关于封装的 TinyMCE 组件无法修改高度值得问题

### ISSUE THREAD

**Issue by liuzhilinux** [PanJiaChen/vue-element-admin#610]
我左使用 `vue-element-admin` 的过程中发现原来框架所封装的 TinyMCE 组件修改高度无效，以下代码中：
`src/views/components-demo/tinymce.vue` 第 8 行：
```html
      <tinymce :height="300" v-model="content"></tinymce>
```
修改 `height` 的值后页面中的 TinyMCE 编辑器窗体高度没有变化。
我抽离出项目目录下的 `static` 下的 `tinymce4.7.5` 另外进行测试，
将项目下的 `static` 目录复制到一个空白的工作目录下。
新建 `index.html` ，内容如下：
```html
<html>
<head>
    <title>test</title>
    <script src="static/tinymce4.7.5/tinymce.min.js"></script>
</head>
<body>
<textarea></textarea>
<script>
    tinymce.init({
        selector: 'textarea',  // change this value according to your HTML
        height: 300
    });
</script>
</body>
</html>
```
修改其中第 11 行的 `height` ，刷新页面发现 TinyMCE 的编辑区窗体高度发生变化，所有证明项目中所引入的 TinyMCE 是正常的。

另外，补充说明一下，TinyMCE 组件的上传图片功能，当有图片待上传和没有图片待上传的时候，点击上传的框与取消确定按钮的间距不一致，当没有图片待上传的时候，其间距为 0 ，如图：
![_20180419084500](https://user-images.githubusercontent.com/20591624/38965405-3426eb00-43af-11e8-9091-a8591e2e9f3b.png)
![_20180419084531](https://user-images.githubusercontent.com/20591624/38965414-42ce3370-43af-11e8-9a47-32e516fa8e79.png)
我的解决方法是，在 `src/components/Tinymce/components/EditorImage.vue` 下补充样式，另起一个 `<style>` ，注意不带 `scoped` ：
```html
<style>
    .el-upload--picture-card {
        margin-bottom: 16px;
    }
</style>
```
这样就解决了问题，不知道可否有更优解。
以上，谢谢。

**Comment by PanJiaChen** [comment]
Fixed in 8f37950 
发现是`autosize` 插件导致的，已移除。
