### ISSUE TITLE
演示环境的Complex Table->Export Excel错误，无法下载文件。本地环境相同代码也出现相同的错误。

### ISSUE THREAD

**Issue by CHCP** [PanJiaChen/vue-element-admin#611]
演示环境的Complex Table->Export Excel错误，本地环境相同代码也出现相同的错误：

Uncaught (in promise) TypeError: Cannot convert undefined or null to object。
Export2Excel.js:133行：data = [].concat(_toConsumableArray(data));

**Comment by CHCP** [comment]
抱歉，并非源代码Export2Excel.js的第133行，是编译过的，演示环境的截图如下：
![image](https://user-images.githubusercontent.com/5645296/38971983-5e7945b0-43e1-11e8-8794-54a6c32357c1.png)

**Comment by PanJiaChen** [comment]
Fixed in 6821eac

**Comment by powhd** [comment]
我改成你说的那样 还是报TypeError: Cannot convert undefined or null to object。 @PanJiaChen

**Comment by igsnow** [comment]
请问怎么解决的？我也碰到这个问题了
