### ISSUE TITLE
关于token问题

### ISSUE THREAD

**Issue by sht33** [PanJiaChen/vue-element-admin#615]
请问手摸手系列二中，关于“我司现在后台所有token有效期(Expires/Max-Age)都是Session”，这句话是什么意思？后台用到了session？
“就是当浏览器关闭了就丢失了”，是通过设置浏览器cookie实现的吗？
谢谢

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/39092536-8c851f52-4642-11e8-96f7-3a47e84de9b9.png)
