### ISSUE TITLE
代码中的$t导致保存

### ISSUE THREAD

**Issue by fengnex** [PanJiaChen/vue-element-admin#616]
![image](https://user-images.githubusercontent.com/26297547/39084862-cfa20d62-45ad-11e8-95e0-57adbaa1be0b.png)
错误信息如上图，对应的代码例如下面这样，请问该怎么解决？
<el-tooltip effect="dark" :content="$t('navbar.screenfull')" placement="bottom">
        <screenfull class="screenfull right-menu-item"></screenfull>
      </el-tooltip>

**Comment by fengnex** [comment]
<el-tooltip effect="dark" :content="$t('navbar.screenfull')" placement="bottom">
        <screenfull class="screenfull right-menu-item"></screenfull>
      </el-tooltip>

**Comment by fengnex** [comment]
![image](https://user-images.githubusercontent.com/26297547/39085141-03debbf4-45b1-11e8-82c2-910a615b7683.png)

请教像上面这个图中，顶部navBar不显示是什么原因？

**Comment by PanJiaChen** [comment]
`$t` 是[vue-i18n](https://github.com/kazupon/vue-i18n)注入到全局的方法。请自行查阅文档。

**Comment by fengme** [comment]
在国内使用的很多情况下，根本不需要国际化，这时候还硬加上一个函数，是否繁琐、影响性能什么的？

**Comment by fengme** [comment]
另外，请教上，上面的那个navBar不显示是什么原因？

**Comment by fengme** [comment]
$t这个国际化，没需要的话，怎么不用？

**Comment by PanJiaChen** [comment]
[文档](https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/i18n.html#%E7%A7%BB%E9%99%A4%E5%9B%BD%E9%99%85%E5%8C%96)
