### ISSUE TITLE
icon 图标颜色修改，尤其是边栏路由的图标修改问题

### ISSUE THREAD

**Issue by yuanyuanyuan** [PanJiaChen/vue-element-admin#620]
下载http://iconfont.cn/ 图标的时候，要选白色，就可以 fix 这个问题，但是具体原因不明，

你们可以测试对比一下，官方 github 提供的 svg 跟http://iconfont.cn/ 下载的默认下载的图标是有区别的，如果默认下载http://iconfont.cn/ 的图标，依然还是不能变色，如果你选择一个把颜色调整为白色或其他颜色，就可以看到变色效果了，根本不是 css fill 的问题。
我对比了2个 svg 的差别，http://iconfont.cn/ 重新下载的会多了 fill 属性，而官网 github 自带的是没有的，可能是这里被影响了变色效果。

关联问题 #330

**Comment by yuanyuanyuan** [comment]
1. 如果是页面的 icon 的话，不需要这样修改，直接按照官网使用即可。
2. 如果是边栏路由的图标的话，则需要这样处理。

**Comment by PanJiaChen** [comment]
Duplicate of #330
