### ISSUE TITLE
nprograss 在哪里加载的？

### ISSUE THREAD

**Issue by gcpark1210** [PanJiaChen/vue-element-admin#621]
请问 nprograss 在哪里加载的 ？
怎么 找不到 设置文件。。。 
就是 浏览器上面 一个 进度条那个 。。。
我想在我的项目上加上那个组建 但找不到 在哪设置的 能告诉我吗？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/permission.js#L4

**Comment by gcpark1210** [comment]
谢谢
