### ISSUE TITLE
想tinymce.vue编辑框想输入内容后，跳转不提示上方的保存，有偿求解

### ISSUE THREAD

**Issue by noodv** [PanJiaChen/vue-element-admin#626]
场景是这样的，当我编辑文本内容，并点保存后，需要跳转到查看文章页。
但这个跳转过程不需要提示保存提醒
微信 noodv1990

**Comment by PanJiaChen** [comment]
不是很理解你的问题？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/components/Tinymce/plugins.js

移除 `autosave` plugin.
