### ISSUE TITLE
跨域请求问题

### ISSUE THREAD

**Issue by sht33** [PanJiaChen/vue-element-admin#628]
你好，有个问题请教一下。十分感谢！
问题1、vueAdmin-template-master 项目，登录是有预请求，如下：
Request URL:https://easy-mock.com/mock/5950a2419adc231f356a6636/vue-admin/user/login
Request Method:OPTIONS
Status Code:204 No Content
Remote Address:120.27.128.131:443
Referrer Policy:no-referrer-when-downgrade
预请求完成后，才是真正的请求
但是我自己搭建了一个后端，发现就没有这个预请求，直接就是正真的请求，我自己搭建的后端是用的是spring mvc @CrossOrigin 注解，这是为什么呢？服务端需要配置什么吗？
问题2、如果服务端不做任何跨域请求的配置，只在前端通过cors、proxy进行配置，请求时发现
Response headers 中没有Access-Control-Allow-Origin 等相关属性，但是能正常返回数据，请问这是正常的吗？
十分感谢！

**Comment by PanJiaChen** [comment]
首先你要搞清楚什么是跨域，`OPTIONS`请求在跨域的情况下才会有，你本地如果是一个端口其实是不会跨域的。
纯前端是不能解决跨域的，纯jsonp也是需要后端配合的。
详情可见我之前的文章 https://segmentfault.com/a/1190000010043013#articleHeader9

**Comment by sht33** [comment]
我自己搭建的后端不在我的机器上，在一服务器的一台虚拟机上，前端在我本地

**Comment by sht33** [comment]
这个第一个问题的请求头
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.8
Connection:keep-alive
Content-Length:48
Content-Type:application/x-www-form-urlencoded
Cookie:JSESSIONID=EBD8ECD0E9A0C70609B6BBFCC955B56F
Host:10.0.101.24:8080
Origin:http://localhost:8082
Referer:http://localhost:8082/
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36

**Comment by sht33** [comment]
没报错，能正常请求到，但是就是没有预请求。
前端没有做任何跨域的处理，后端用了spring mvc 的@CrossOrigin 注解

**Comment by sht33** [comment]
第一个问题响应头
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://localhost:8082
Content-Type:text/x-json;charset=UTF-8
Date:Fri, 27 Apr 2018 02:12:18 GMT
Transfer-Encoding:chunked
Vary:Origin

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/39344874-b00250a2-4a17-11e8-9146-f7333e01ddbb.png)

并不是所有跨域请求需求发options的

**Comment by sht33** [comment]
3q
