### ISSUE TITLE
Any plans to support webpack4?

### ISSUE THREAD

**Issue by chenyihao2621023** [PanJiaChen/vue-element-admin#630]
In my project, there was a problem of building too slow.So i want to see the configuration of webpack4 with DLL and happypack. 
  I think these are very useful for large projects.

**Comment by PanJiaChen** [comment]
The next big version @v3.7.0 upgrade will use webpack4 and vue-loader@v15, but still have to wait for vue-cli to do the appropriate upgrade.
[issue](https://github.com/vuejs-templates/webpack/issues/1280)

**Comment by chenyihao2621023** [comment]
So about DLL and happypack？

**Comment by PanJiaChen** [comment]
No plan.

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/releases/tag/v3.8.0
