### ISSUE TITLE
tab切换不同组件created被多次调用,v-loading指令变成undefined，导致不能关闭loading

### ISSUE THREAD

**Issue by frame-faker** [PanJiaChen/vue-element-admin#635]
![image](https://user-images.githubusercontent.com/24647589/39504447-46bf3728-4dfe-11e8-8a7b-e6469302dbab.png)
![image](https://user-images.githubusercontent.com/24647589/39504478-757b7842-4dfe-11e8-929d-b51e638bc25c.png)

**Comment by frame-faker** [comment]
this.listloading是我写错了,应该是this.listLoading

**Comment by frame-faker** [comment]
但是我通过tab切换，第一次进来，created钩子执行了4次，请求也请求了4次，这个tab下面有4个组件，第一章图是一个tab包含4个组件，然后我点击一个组件的时候，created被执行了4次

**Comment by frame-faker** [comment]
我是用tab组件然后包了4个组件，每个组件只在tab下面用一次

**Comment by PanJiaChen** [comment]
我理解你想要的效果是：四个组件只想触发一个created?
你生命了四个组件肯定会执行四次创建。除非你是公用一个组件。

**Comment by frame-faker** [comment]
谢谢老哥

**Comment by zhnit** [comment]
遇到相同的问题,看到你这个回答豁然开朗 ,. 感谢!!!
