### ISSUE TITLE
Please convert chinese to english the items.

### ISSUE THREAD

**Issue by mrpehlivan** [PanJiaChen/vue-element-admin#64]
Hi there , 
I am interesting admin panel but i dont understand anything. 

Thanks

**Comment by skapin** [comment]
Same here, english would be perfect, and, a tuto/scratch projet of ur work

thanks a lot

**Comment by RoraxHan** [comment]
Yes. If this is written by English too, then will be more popular than now.

**Comment by PanJiaChen** [comment]
The new document has been rewritten based on vuepress, and the English version has been improved. If you find a problem, you can pr.

[The documentation source](https://github.com/PanJiaChen/vue-element-admin-site).
