### ISSUE TITLE
富文本中有个不理解的地方

### ISSUE THREAD

**Issue by SamoZ** [PanJiaChen/vue-element-admin#640]
### 在 tinymce 富文本编辑器中，根据源码，然后我自己也有百度找资料，发现 tinymec 有自己的 setContent 和 getContent 方法，如下图
![1nhn sxo8m761ru q 7sl](https://user-images.githubusercontent.com/25240164/39610604-24e17e18-4f84-11e8-9ebc-df9a86946a5d.png)
### 但在下面我看到又重写的 setContent 和 getContent 方法，如下图
![bwrto1p8aar 3f8k7 44 d](https://user-images.githubusercontent.com/25240164/39610659-8924df6e-4f84-11e8-91d2-07123b73429c.png)
### 在写这个issues时我又重新看了一遍，感觉可能是下图中用到了重写的 setContent 和 getContent 方法
![jnxu5lp t71te u io e07](https://user-images.githubusercontent.com/25240164/39610714-d47f9b02-4f84-11e8-99c7-f0feeaddb46a.png)
### 但是，我将重写的 setContent 和 getContent 方法注释之后发现并没有影响什么，个人感觉好像是多余的代码，不知道是不是我不熟悉 tinymec 的原因

**Comment by PanJiaChen** [comment]
一个是`tinymce`的方法，另一个只是在`tinymce`方法的基础上进行了再一次封装，简化写法而已。
