### ISSUE TITLE
如何在页面上关闭标签导航

### ISSUE THREAD

**Issue by mjj137993394** [PanJiaChen/vue-element-admin#641]
![2018-05-04 11 28 22](https://user-images.githubusercontent.com/18019921/39612017-503b805e-4f8e-11e8-8607-fec21b561b1e.png)
点击取消关闭标签

**Comment by PanJiaChen** [comment]
`this.$store.dispatch('delVisitedViews', view)`
https://github.com/PanJiaChen/vue-element-admin/blob/f9d510ea78bbb919ed4dbaf0b1ad1577c7b2aa46/src/store/modules/tagsView.js#L57-L62

**Comment by mjj137993394** [comment]
thx

**Comment by zhanganyi** [comment]
@PanJiaChen  您好试了一下你说的this.$store.dispatch('delVisitedViews', view)但好像没用，是不是因为我的view参数传递错了？如果传递错了，那应该传递什么样的格式？本人菜鸟一枚，忘不要见怪，谢谢您！

**Comment by mjj137993394** [comment]
@zhanganyi 
this.$store.dispatch('delVisitedViews', this.$route) 我是这样写的

**Comment by zhanganyi** [comment]
@mjj137993394 谢谢您，后面我也解决了！

**Comment by Hideer** [comment]
@kid1412621 如何主动关闭tab然后跳到某个tab下呢...

**Comment by marscj** [comment]
@kid1412621 
`
this.$store.dispatch('tagsView/delView', this.$route).then(() => {
                this.$nextTick(() => {
                  this.$router.replace({
                    path: '/booking/edit/' + id
                  })
                })
              })
`
这是我的代码

**Comment by marscj** [comment]
@Hideer 
`
this.$store.dispatch('tagsView/delView', this.$route).then(() => {
                this.$nextTick(() => {
                  this.$router.replace({
                    path: '/booking/edit/' + id
                  })
                })
              })

`
这是我的代码 ，

**Comment by KevinBlack** [comment]
> @mjj137993394 谢谢您，后面我也解决了！

能指点下如何解决的么？

**Comment by libaolei168** [comment]
this.$store.dispatch('delVisitedViews', view)  这个关闭一个form表单的页面后 在打开 form里面的数据没被清除 怎么解决？
