### ISSUE TITLE
关于路由嵌套的问题

### ISSUE THREAD

**Issue by lijianqiang** [PanJiaChen/vue-element-admin#643]
一个模块有列表，添加、修改、详情等基本的四个页面
修改页和详情页都是列表右边的按钮进去的，按照代码里写的，这个路由和侧边栏不好设定

不知道有没有大神有类似需求

**Comment by PanJiaChen** [comment]
`{ path: '/login', component: _import('login/index'), hidden: true }`
像这个设置一个hidden？侧边栏就不会显示了。

**Comment by moonose** [comment]
@PanJiaChen 裤衩大大，再问下，是不是路由的页面都需要在router/index.js里定义？
譬如～在navbar.vue 中的 增加了一个连接 <router-link to="/myapp/index">xxxx </router-link>, 在view下建立了myapp/index.vue。点击nav的链接后，后需要在主内容区域显示，这样的情况是否一定要在router/index.js里定义这个index.vue，然后用 hidden隐藏掉？
