### ISSUE TITLE
svg-sprite-loader exception

### ISSUE THREAD

**Issue by GitVitality** [PanJiaChen/vue-element-admin#649]
![image](https://user-images.githubusercontent.com/14938077/39672915-a4842fc0-5165-11e8-9876-8dfa027e9ce2.png)
请问这个是什么原因呢？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/1e103cf151ee55409c8025bd55900e285f2d90e4/build/webpack.base.conf.js#L63-L68
`url-loader` 需要exclude它。
