### ISSUE TITLE
 增加一个preview页面

### ISSUE THREAD

**Issue by gtyang** [PanJiaChen/vue-element-admin#650]
现在这个后台基本内容都挺全的，就是preview页面没有模板，能不能增加一个这样的模板，我也不想因为这个页面再引入其他的css库了。

**Comment by PanJiaChen** [comment]
preview页面是什么？没太理解需求。

**Comment by gtyang** [comment]
比如订单详情的展示页，累死累活这个 https://preview.pro.ant.design/#/profile/advanced

**Comment by PanJiaChen** [comment]
还是不太理解，有什么意义？或者场景需要加这个？

**Comment by chengmanxiang** [comment]
看一下issue#647,和这个类似

**Comment by gtyang** [comment]
嗯，场景就是像issue#647那样

**Comment by PanJiaChen** [comment]
see #647
