### ISSUE TITLE
表格组件重写 其它的table组件 element-ui 卡

### ISSUE THREAD

**Issue by ZHYim** [PanJiaChen/vue-element-admin#651]
当加载大量数据到表格的时候，响应速度会变得巨慢无比，希望作者能重写表格组件
ps:已捐赠

**Comment by PanJiaChen** [comment]
表格组件目前使用的是`element-ui`的table,你可以试试市面上其它的[table组件](https://github.com/search?o=desc&q=vue+table&s=stars&type=Repositories)。
其实解决表格大量数据最好的方法是分页。

**Comment by ZHYim** [comment]
能推荐个吗，element的组件绑定的事件太多了，而且公司的需求是不能分页，开发阶段做了分页，每页15条信息的时候反应已经很迟钝了



15606216623@163.com
 
发件人： 花裤衩
发送时间： 2018-05-08 09:44
收件人： PanJiaChen/vue-element-admin
抄送： ZHYim; Author
主题： Re: [PanJiaChen/vue-element-admin] 表格组件重写 (#651)
表格组件目前使用的是element-ui的table,你可以试试市面上其它的table组件。
其实解决表格大量数据最好的方法是分页。

**Comment by PanJiaChen** [comment]
都没有实际用过，所以不能给你很多建议，你可以按star倒叙来试一试。

**Comment by PanJiaChen** [comment]
把权限封装到`v-directive` 指令里面判断是否显示这个table

**Comment by ZHYim** [comment]
好的，谢谢，我试试

**Comment by PanJiaChen** [comment]
新增了指令权限的demo 你可以看一下 https://github.com/PanJiaChen/vue-element-admin/blob/master/src/directive/permission/permission.js

**Comment by ZHYim** [comment]
15606216623@163.com
 
发件人： 花裤衩
发送时间： 2018-05-30 15:41
收件人： PanJiaChen/vue-element-admin
抄送： RyanZhao; Author
主题： Re: [PanJiaChen/vue-element-admin] 表格组件重写 其它的table组件 element-ui 卡 (#651)
Closed #651.
