### ISSUE TITLE
最合适的加载文件内容

### ISSUE THREAD

**Issue by DHCMediWay** [PanJiaChen/vue-element-admin#652]
现在要读取一个markdown的模板,模板我是新建了一个文件,想要以字符串的格式使用

**Comment by PanJiaChen** [comment]
没懂你想表达什么

**Comment by DHCMediWay** [comment]
你好,我是刚开始使用前端框架,我想知道如果我想加载一个.md后缀名的文件,我要使用什么扩展

**Comment by PanJiaChen** [comment]
还是没表达清楚啊，你想用浏览器加载.md后缀名的文件还是还是本地加载一个.md文件解析出html在浏览器显示？请说清楚你的需求。
