### ISSUE TITLE
关于 TinyMCE 组件中点击全屏后，“上传图片”按钮消失的问题。

### ISSUE THREAD

**Issue by liuzhilinux** [PanJiaChen/vue-element-admin#654]
在编辑文案的情况下，如果在非全屏的情况下是正常的，如图：
![image](https://user-images.githubusercontent.com/20591624/39797938-09cc173a-5391-11e8-803c-73bc9bedbf89.png)

而在全屏模式下，“上传图片”按钮不见了，如图：
![image](https://user-images.githubusercontent.com/20591624/39797962-24d850ac-5391-11e8-8da9-9e99b17807b8.png)
请教解决方案。

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/6795c26d025397110a80a5d4506f820a25c32fda

**Comment by liuzhilinux** [comment]
谢谢。

**Comment by wyf19951122** [comment]
全屏模式下 上传图片按钮，点击无反应

**Comment by PanJiaChen** [comment]
@wyf19951122 感谢反馈，是bug。

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/1e0b9c0055d37bcefa9ae63257903747c3971471
