### ISSUE TITLE
关于table展示隐藏列

### ISSUE THREAD

**Issue by SamoZ** [PanJiaChen/vue-element-admin#656]
![6 nnp7qi 5rx34o xi 6n1](https://user-images.githubusercontent.com/25240164/39854979-9f496c74-545c-11e8-9b96-eea38a1c9e23.png)
如图，在Complex Table页面中，el-table中的key不理解什么意思，我将element文章翻了个遍，自行百度都没有查到，@change改变tableKey与showReviewer有什么关联么，不理解为什么将tableKey+1就可以改变showReviewer的状态，在源码中没有发现，请指教

**Comment by PanJiaChen** [comment]
vue 的 `key`，因为早期`el-table` 在数据变化的时候会有bug，所以加入一个key，保证每次变化都会重新渲染table

**Comment by SamoZ** [comment]
@PanJiaChen 恕我愚钝，既然key是为了保证渲染成功，那么它为什么会改变showReviewer的true和false呢？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/6795c26d025397110a80a5d4506f820a25c32fda/src/views/example/table/complexTable.vue#L47-L50

是`showReviewer`会影响table展示隐藏列.
