### ISSUE TITLE
view权限控制与面包屑问题

### ISSUE THREAD

**Issue by c527380322** [PanJiaChen/vue-element-admin#657]
例如： 当前异步加载路由中 redirect: '/example/table/complex-table', 如果该子节点‘complex-table’ 的meta属性配置角色规则，当前登录角色无法访问，addRouer不加载该路由，当点击面包屑导航时，就会存在404无法访问现象。

**Comment by PanJiaChen** [comment]
有什么问题么？现在就是这样处理的。

**Comment by c527380322** [comment]
如下这种路由配置， 重定向redirect: '/example/table/complex-table'，但是由于{ path: 'complex-table', component: _import('example/table/complexTable'), name: 'complexTable', meta: { title: 'complexTable', roles: ['admin'] }}，配置了admin权限，如果用editor用户登录，点击面包屑导航，就会出现无法重定向的问题。
  {
    path: '/example',
    component: Layout,
    redirect: '/example/table/complex-table',
    children: [
      {
        path: '/example/table',
        component: _import('example/table/index'),
        redirect: '/example/table/complex-table',
        },
        children: [
          { path: 'dynamic-table', component: _import('example/table/dynamicTable/index'), name: 'dynamicTable', 
          { path: 'complex-table', component: _import('example/table/complexTable'), name: 'complexTable', meta: { title: 'complexTable', roles: ['admin'] }}
        ]
      },
    ]
  }

**Comment by PanJiaChen** [comment]
哦理解你的意思了，的确有这个问题，但重定向到没权限页面也没什么逻辑问题啊。虽然可以加一个判断，如果没有该权限面包屑就不让点。

**Comment by c527380322** [comment]
多个子节点路由，每个子节点的规则都不一样，路由在加载时，如何能做到顺序选择存在权限的节点进行重定向呢，这样面包屑导航这样点都没有问题，当然这只是一个建议哈。

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/39861010-d53ff5d6-5471-11e8-9a27-84e8079df386.png)

你可以改造成一个对象。在面包屑组件里面在根据当前权限来渲染不同的路由。

**Comment by c527380322** [comment]
这个提议很好，我试试， 我还在想要不要重新再生成一个路由对象呢，再次感谢支持。
