### ISSUE TITLE
本地nginx代理速度慢

### ISSUE THREAD

**Issue by WwJoyous** [PanJiaChen/vue-element-admin#659]
本地用nginx代理，直接监听9527端口通过访问的时候，首页加载非常非常慢。直接locallhost访问的是正常的，调试发现加载app.js这个文件非常慢 要一分钟多。
请问下这种情况有什么好的解决方式嘛

**Comment by PanJiaChen** [comment]
大概率是你nginx配置问题，还有本地为什么要nginx，直接用webpack 的 proxy更方便一点。
