### ISSUE TITLE
谷歌浏览器点击“在线访问”，无任何反应，一片空白。

### ISSUE THREAD

**Issue by shunichigoo** [PanJiaChen/vue-element-admin#660]
另外，npm install 安装会报出一系列错误，重新指定 registry也会报错，不知道怎么解决。

**Comment by PanJiaChen** [comment]
在线访问地址是github.io 的地址，时不时会被墙。
npm instal报错，请提供详细信息。

**Comment by shunichigoo** [comment]
浏览器开启了代理，f12打开控制台，发现有报错信息。
![default](https://user-images.githubusercontent.com/23553358/39873241-f1836f22-549c-11e8-867a-f5bf3a210ba0.PNG)

npm install 安装错误信息和#658大致相同，第一次指定 registry 来install时node_modules里面什么都没有，第二次直接npm install 时，安装完毕许多文件找不到。

**Comment by shunichigoo** [comment]
npm install

npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

> node-sass@4.9.0 install E:\WebCode\vue-element-admin\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.0/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.0/win32-x64-57_binding.node":

ESOCKETTIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> uglifyjs-webpack-plugin@0.4.6 postinstall E:\WebCode\vue-element-admin\node_modules\webpack\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.9.0 postinstall E:\WebCode\vue-element-admin\node_modules\node-sass
> node scripts/build.js

Building: D:\Nodejs\node.exe E:\WebCode\vue-element-admin\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'D:\\Nodejs\\node.exe',
gyp verb cli   'E:\\WebCode\\vue-element-admin\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\WebCode\vue-element-admin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\WebCode\vue-element-admin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\WebCode\vue-element-admin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\WebCode\vue-element-admin\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\WebCode\vue-element-admin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\WebCode\vue-element-admin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\WebCode\vue-element-admin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\WebCode\vue-element-admin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\WebCode\vue-element-admin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\WebCode\vue-element-admin\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\WebCode\vue-element-admin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\WebCode\vue-element-admin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (E:\\WebCode\\vue-element-admin\\node_modules\\which\\which.js:13:12)\n    at F (E:\\WebCode\\vue-element-admin\\node_modules\\which\\which.js:68:19)\n    at E (E:\\WebCode\\vue-element-admin\\node_modules\\which\\which.js:80:29)\n    at E:\\WebCode\\vue-element-admin\\node_modules\\which\\which.js:89:16\n    at E:\\WebCode\\vue-element-admin\\node_modules\\isexe\\index.js:42:5\n    at E:\\WebCode\\vue-element-admin\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\WebCode\vue-element-admin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\WebCode\vue-element-admin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\WebCode\vue-element-admin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\WebCode\vue-element-admin\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\WebCode\vue-element-admin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\WebCode\vue-element-admin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\WebCode\vue-element-admin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\WebCode\vue-element-admin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\WebCode\vue-element-admin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\WebCode\vue-element-admin\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\WebCode\vue-element-admin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\WebCode\vue-element-admin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (E:\\WebCode\\vue-element-admin\\node_modules\\which\\which.js:13:12)\n    at F (E:\\WebCode\\vue-element-admin\\node_modules\\which\\which.js:68:19)\n    at E (E:\\WebCode\\vue-element-admin\\node_modules\\which\\which.js:80:29)\n    at E:\\WebCode\\vue-element-admin\\node_modules\\which\\which.js:89:16\n    at E:\\WebCode\\vue-element-admin\\node_modules\\isexe\\index.js:42:5\n    at E:\\WebCode\\vue-element-admin\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\WebCode\vue-element-admin\node_modules\node-gyp\lib\configure.js:483:19) gyp ERR! stack     at PythonFinder.<anonymous> (E:\WebCode\vue-element-admin\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at E:\WebCode\vue-element-admin\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\Nodejs\\node.exe" "E:\\WebCode\\vue-element-admin\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\WebCode\vue-element-admin\node_modules\node-sass
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Nodejs\node_cache\_logs\2018-05-10T14_17_34_641Z-debug.log

**Comment by shunichigoo** [comment]
本地安装问题已解决。
