### ISSUE TITLE
发现功能相似代码

### ISSUE THREAD

**Issue by SamoZ** [PanJiaChen/vue-element-admin#661]
filter文件中的 parseTime 和 formatTime方法与utils文件中index.js中的 parseTime 和 formatTime方法功能一致，代码相似度很高，怀疑为冗余代码，请大神查看下
https://github.com/PanJiaChen/vue-element-admin/blob/6795c26d025397110a80a5d4506f820a25c32fda/src/filters/index.js#L19-L76
https://github.com/PanJiaChen/vue-element-admin/blob/6795c26d025397110a80a5d4506f820a25c32fda/src/utils/index.js#L5-L58

**Comment by PanJiaChen** [comment]
谢谢提醒，的确可以优化一下。

**Comment by PanJiaChen** [comment]
fixed in https://github.com/PanJiaChen/vue-element-admin/commit/66613f0373c7fb5e5673a2890b1b435c061a4b04
