### ISSUE TITLE
富文本编辑器 window.tinymce.init is not a function

### ISSUE THREAD

**Issue by leefreeF** [PanJiaChen/vue-element-admin#663]
![096e1f4b193a05f61c769b9010f2573](https://user-images.githubusercontent.com/32056701/39913391-42ce6566-5534-11e8-8a18-e79a0ba347b0.png)
![b16fc7f7bdcd40180fff8954b88a2e5](https://user-images.githubusercontent.com/32056701/39913393-44bbd1d8-5534-11e8-8739-9094bc99a5cb.png)
![264aa193abe64a12cf6d8ab392354e3](https://user-images.githubusercontent.com/32056701/39913395-45d8bebe-5534-11e8-8589-329e7b2464f6.png)
![ee3ef35debe5cf02838f1de54673085](https://user-images.githubusercontent.com/32056701/39913397-47528b76-5534-11e8-90dc-0d3f882dba6a.png)

**Comment by leefreeF** [comment]
完全按照github上的代码搬的   但是还是报错

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/#/zh-cn/rich-editor?id=tinymce

https://github.com/PanJiaChen/vue-element-admin/blob/master/index.html#L11
你还是需要在index.html页面中全局引入它。

**Comment by leefreeF** [comment]
![96e4662e0f27c8e91f76a2ecee138bc](https://user-images.githubusercontent.com/32056701/39914919-f9bd43d8-5538-11e8-88f6-4f1e05a8b297.png)
我修改了index.html 但不是像你那么写的  你那么好像还要修改webpack.config
![1e37c012118ae2b0897b6eb6ed0d8ab](https://user-images.githubusercontent.com/32056701/39915120-addb135e-5539-11e8-89ca-28b399f819c6.png)

**Comment by PanJiaChen** [comment]
你确定你这路径下有文件？

**Comment by leefreeF** [comment]
我在index.htlm那么引入   页面已经出来了  但是有好多报错
![2da2a3239875abdd06e17ce732a6960](https://user-images.githubusercontent.com/32056701/39916001-f85c639a-553b-11e8-8593-03a6d5930b98.png)

**Comment by leefreeF** [comment]
我的webpack.config  没有做对应的path修改  是这个原因么
