### ISSUE TITLE
在切换路由菜单时不刷新页面

### ISSUE THREAD

**Issue by DHCMediWay** [PanJiaChen/vue-element-admin#664]
在切换路由菜单时不刷新页面怎么控制不刷新

**Comment by PanJiaChen** [comment]
没懂你想表达什么？能具体说明一下么？

**Comment by DHCMediWay** [comment]
<img width="254" alt="default" src="https://user-images.githubusercontent.com/38342775/39953688-96df6f24-55e3-11e8-9912-50cc0ab497af.png">
这个tab切换时怎么控制不刷新
