### ISSUE TITLE
tagsViews 页面状态没有被保存

### ISSUE THREAD

**Issue by gtyang** [PanJiaChen/vue-element-admin#665]
直接打开现在的demo站点，http://panjiachen.github.io/vue-element-admin/，

1.  打开几个页面，其中包括 complexTable,
2.  complexTable 翻到第3页，切换tab
3. 切换回 complexTable, 又处于第一页的状态，没有被cache

router的noCache 什么的都应该是设置的可以cache吧

**Comment by PanJiaChen** [comment]
关注 #406吧，本issue先关了。
