### ISSUE TITLE
全局的系统消息应该写在哪里？

### ISSUE THREAD

**Issue by seean-chan** [PanJiaChen/vue-element-admin#669]
![image](https://user-images.githubusercontent.com/30038138/39980522-ea3cfcd0-577e-11e8-820e-8bfe0a4b9624.png)

**Comment by PanJiaChen** [comment]
没懂你的需求?请详细描述。

**Comment by seean-chan** [comment]
就是我登录成功之后跳转到首页，右下角会弹出个系统消息，这个系统消息可以在登录之后的任意界面弹出，我们这边是设置了5分钟刷一次，有消息就会提示。下面是我们之前老版本的，现在改用vue的写不知道该写在哪里？现在放在layout里面写，由于一些可点击的消息弹层通过vuex来异步请求的，登录进来后有些还没加载好，就会报错。

![image](https://user-images.githubusercontent.com/30038138/39982120-e5bea31e-5785-11e8-977d-666c6b83b693.png)

**Comment by PanJiaChen** [comment]
写在`layout`里面没有什么问题，vuex的错就是自己具体代码的问题了。
