### ISSUE TITLE
隐藏VUE后缀源码后, 在浏览器调试工具中 还是 能看到, webpack 打包Vue组件生成的JS文件, 请问能隐藏吗?

### ISSUE THREAD

**Issue by youxdd** [PanJiaChen/vue-element-admin#671]
隐藏VUE后缀源码后, 
但是 在浏览器调试工具中 还是 能看到, webpack 打包Vue组件生成的JS文件,
然后我通过 格式化后,  还是能清晰看到 源码, 请问能隐藏吗?
![tim 20180514164130](https://user-images.githubusercontent.com/17402720/39987153-817bae4a-5796-11e8-9ec9-e108935cd88b.png)

**Comment by PanJiaChen** [comment]
不是很理解你想表达？想让其它用户看不到你的代码？

**Comment by youxdd** [comment]
@PanJiaChen  对呀, 就是 不然 其他人 看到. 因为 里面 写的接口信息 都 暴露了 !

**Comment by PanJiaChen** [comment]
我不是很理解你所谓的接口信息是什么？这些信息不能存放在一个接口里面么？这个接口设置一个权限，不就好了？

**Comment by PanJiaChen** [comment]
理论上纯前端所有做的事情都能被破解。

**Comment by youxdd** [comment]
@PanJiaChen 好吧 , 谢谢了,

**Comment by PanJiaChen** [comment]
不管你怎么处理，总归可以抓包你的api请求。所以还不如在api权限这里做处理，比如特定的token或者判断ref等等，不让其它人调用api更靠谱。
