### ISSUE TITLE
el-dialog能不能在组件内全屏

### ISSUE THREAD

**Issue by DHCMediWay** [PanJiaChen/vue-element-admin#672]
el-dialog全屏时只充满组件
![image](https://user-images.githubusercontent.com/38342775/39997959-2818e72a-57b7-11e8-9d92-4cc399409382.png)

**Comment by PanJiaChen** [comment]
实测加入属性`fullscreen` ，并没有发生你所说的问题。

**Comment by DHCMediWay** [comment]
我是希望对话框只充满组件 而不是全屏

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/40032244-e26a341c-5825-11e8-9d63-86e98919b9bf.png)

自行修改`el-dialog`样式，将它`fixed`修改为`absolute`,再按照自己需求调整其它样式。

**Comment by DHCMediWay** [comment]
我能理解成把对话框的大小改成组件的大小吗
