### ISSUE TITLE
富文本编辑器 window.tinymce.init is not a function

### ISSUE THREAD

**Issue by leefreeF** [PanJiaChen/vue-element-admin#675]
![16a91d963ec1387dfd3a4617b8ea7f1](https://user-images.githubusercontent.com/32056701/40036020-8da87918-5837-11e8-992f-ece1ad085dcf.png)

**Comment by Melonxx** [comment]
在 `index.hhtml` 中引入
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.7.2/tinymce.min.js"></script>
```
