### ISSUE TITLE
类似表单验证的配置提示信息如何国际化呢

### ISSUE THREAD

**Issue by luwzchn** [PanJiaChen/vue-element-admin#676]
您好，想请教，类似表单验证的配置提示信息如何国际化呢？

` name: [
          { required: true, message: "name is required", trigger: "blur" },
          { min: 2, max: 50, message: "长度在2到50个字符", trigger: "blur" }
        ],
        number: [
          { required: true, message: "number is required", trigger: "blur" },
          { min: 1, max: 50, message: "长度在1到50个字符", trigger: "blur" }
        ],`

类似这种 message 信息

**Comment by PanJiaChen** [comment]
同样使用`vue-i18n`。
```js
message:this.$t('你的message key')
```

**Comment by luwzchn** [comment]
哥，先别关闭啊，这样写可行，但是不重载页面 切换语言时，messge 并不会跟着国际化

**Comment by PanJiaChen** [comment]
使用自定义校验规则。
如：
```js
const validatePassword = (rule, value, callback) => {
      if (value.length < 6) {
        callback(new Error(this.$t('login.title')))
      } else {
        callback()
      }
    }
```

**Comment by luwzchn** [comment]
@PanJiaChen 不完美，自带的验证关键字不能用。

**Comment by laboonly** [comment]
我也遇到了这个问题 。。。 你最后怎么解决的啊。

**Comment by Goodwindy** [comment]
自己有了个想法，当登陆的时候，自带的验证方法会判断符合验证规则有没有为空的或者格式不对的，放过来呢，再语言切换时候也可以调用这个验证的方法并在此时给他转换语言，这也只是猜测
