### ISSUE TITLE
这里感觉有点重复

### ISSUE THREAD

**Issue by SamoZ** [PanJiaChen/vue-element-admin#678]
https://github.com/PanJiaChen/vue-element-admin/blob/66613f0373c7fb5e5673a2890b1b435c061a4b04/src/store/modules/user.js#L51-L56
https://github.com/PanJiaChen/vue-element-admin/blob/66613f0373c7fb5e5673a2890b1b435c061a4b04/src/store/modules/user.js#L65-L80

我将数据都打印了以下，上面的两个方法数据获取的都是一样的，个人感觉在登录时就已经获取到用户的信息了，感觉可以合并

**Comment by PanJiaChen** [comment]
建议参考[文章](https://juejin.im/post/591aa14f570c35006961acac#heading-2)
登录和获取用户权限分开比较好。如果`登录时就已经获取到用户的信息了`，那刷新页面该怎么办？再帮它模拟登录一次，调用`loginByUsername`么？
