### ISSUE TITLE
新增一个路由，既不在sidebar中显示，也不再tags-view中显示，请问怎么处理

### ISSUE THREAD

**Issue by Youcongcong** [PanJiaChen/vue-element-admin#681]

**Comment by PanJiaChen** [comment]
这个需求比较个人吧，你可以自行加一个字段来判断。
类似sidebar中的`hidden`
https://github.com/PanJiaChen/vue-element-admin/blob/66613f0373c7fb5e5673a2890b1b435c061a4b04/src/router/index.js#L17
你可以在这里加一个判断，当为`hidden`的时候不添加`tags-view`
https://github.com/PanJiaChen/vue-element-admin/blob/cc5e62d5f50231b89fec65c1d3ce1b82b5b1b8ef/src/views/layout/components/TagsView.vue#L66-L70
