### ISSUE TITLE
报错了 BrowserslistError: `browserlist` key instead of `browserslist`

### ISSUE THREAD

**Issue by wang2650** [PanJiaChen/vue-element-admin#683]
我下了代码报错 ：BrowserslistError: `browserlist` key instead of `browserslist`

然后我把package里的browserlist 改成browserslist 就好了。
初学者，不知道什么原因。

**Comment by PanJiaChen** [comment]
你是老版本的吧，这个问题在很久之前就解决了，请使用新版本。
当然你想继续使用老版本，按照你的说法改一下就好了。
