### ISSUE TITLE
http://localhost:9527/%3C%=

### ISSUE THREAD

**Issue by frankdevhub** [PanJiaChen/vue-element-admin#685]
cnpm install :http://localhost:9527/%3C%= 400 Bad Request求教

**Comment by PanJiaChen** [comment]
请详细描述你的错误。

**Comment by frankdevhub** [comment]
你好，我是新手，就是cnpm install run Dev 后首页爆出这个

**Comment by frankdevhub** [comment]
Failed to load resource: the server responded with a status of 400 (Bad Request)
http://localhost:9527/%3C%= Failed to load resource: the server responded with a status of 400 (Bad Request)

**Comment by PanJiaChen** [comment]
首先确定自己`npm install --registry=https://registry.npm.taobao.org`已经完全安装成功，再着运行`npm run dev`，看一下命令行是否有报错。

**Comment by frankdevhub** [comment]
您好，确认的，cnpm 在镜像安装之后就可以使用 cnpm install 其他模块，冒昧的可以问下您的微信吗，谢谢。工作急用

**Comment by frankdevhub** [comment]
您好！报错的情况和下述链接一致：
https://www.vue-js.com/topic/5a3b7fc9f4eae0865305a770
感谢您的帮助，期待中，谢谢！

**Comment by wangyujie1207** [comment]
兄弟,你解决了没 我遇到了跟你一样的问题

**Comment by PanJiaChen** [comment]
`npm cache clean`之后重新`npm install`试试

**Comment by frankdevhub** [comment]
已解决，node module安装的时候 package.json里没有全部安装

**Comment by frankdevhub** [comment]
C:\Users\Administrator\Desktop\vue-element-admin\node_modules\_webpack@3.10.0@webpack\lib\Template.js:20
module.exports = class Template extends Tapable {
                                        ^

TypeError: Class extends value #<Object> is not a constructor or null
    at Object.<anonymous> (C:\Users\Administrator\Desktop\vue-element-admin\node_modules\_webpack@3.10.0@webpack\lib\Template.js:20:41)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10

**Comment by GreatMagicianHC** [comment]
遇到了同样的问题，啥都没做，就是删除整个项目，重新clone>install>run，就好了。:)

**Comment by frankdevhub** [comment]
是的，我也是
