### ISSUE TITLE
config 文件中  build.assetsPublicPath 改成  '/'

### ISSUE THREAD

**Issue by herrdu** [PanJiaChen/vue-element-admin#686]
我在nginx 部署了之后，刷新总是报错，后发现是路径问题。
config 文件中  build.assetsPublicPath 的默认值是不是改成 '/'  比较好

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/#/zh-cn/deploy?id=%E5%8F%91%E5%B8%83
文档写了需要结合自己的实际情况进行调整，一般nginx不熟的话改成`'/'`就可以了。
