### ISSUE TITLE
Run without npm / node

### ISSUE THREAD

**Issue by SaleRise** [PanJiaChen/vue-element-admin#687]
Hi from Australia,

New to using this but wondering if I can run on production server with php backend without webpack/npm?

My server is restrictive in-terms of resources and so can't afford installing npm/node there...

I see the advantage for NPM and webpack from tooling / testing etc  which I am fine with on my development server but can I load it like we load JQuery or Vue on production server...?

**Comment by PanJiaChen** [comment]
You can `npm run build:prod` locally, Then copy all the files in the dist file to the server, as a static file on it.

**Comment by SaleRise** [comment]
Hi @PanJiaChen Thanks. that worked...
