### ISSUE TITLE
roles.some is not a function

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#688]
前后台我进行了分离，调用 getUserInfo 函数，返回
res.json({code: 200, msg: 'success', 'roles':'admin', 'login_name': item.login_name, 'name': item.first_name + ' ' + item.last_name, 'avatar':'', 'introduction': item.title});

发现一个问题，当'roles'内容是admin时，store\modules\permssion.js不调用，会调用src\permssion.js, 这时菜单正常，当我返回'roles'内容不包含 admin时，譬如叫 abc （如果叫adminabc还是正常）,  这个时候 store\modules\permssion.js被调用了！，报了错误
Uncaught (in promise) TypeError: roles.some is not a function  permission.js:11 

请问下，这是怎么回事？？？

调试信息：
![5](https://user-images.githubusercontent.com/37356039/40348887-7a5336de-5d94-11e8-96a6-f04fa06fab6a.png)
![6](https://user-images.githubusercontent.com/37356039/40348889-7ad542e6-5d94-11e8-8d24-4c8cac05a432.png)
![7](https://user-images.githubusercontent.com/37356039/40348890-7b293ebe-5d94-11e8-88f8-475c2839213c.png)
![8](https://user-images.githubusercontent.com/37356039/40348892-7b7bf82a-5d94-11e8-8d6f-800b01ccae35.png)

**Comment by moonose** [comment]
Leave a comment

**Comment by wakaryry** [comment]
我就咋说了，我返回editor始终进不去。
