### ISSUE TITLE
i18n多语言切换问题

### ISSUE THREAD

**Issue by barray888** [PanJiaChen/vue-element-admin#689]
在切换语言前，点击任意一个双语言的元素，然后再切换语言，发现点击的那个元素的语言未改变，其他未点击的都正常自动切换了语言。
如： demo的登录页，点击“Login Form”  再点击切换为中文，发现Login Form未自动切换

**Comment by PanJiaChen** [comment]
你自己的问题吧，本项没发现你所说的问题。

**Comment by barray888** [comment]
@PanJiaChen 线上demo   你先点击“login form" 再点击切换语言 
![image](https://user-images.githubusercontent.com/28474745/40354269-0ccc0dd2-5de6-11e8-90b3-4e72655dba12.png)

**Comment by PanJiaChen** [comment]
我还是没能重现，`先点击“login form"`是什么意思？

**Comment by barray888** [comment]
你就先点一下嘛  
我发现在切换语言后 之前被点过的元素 不自动切换

**Comment by barray888** [comment]
@PanJiaChen

**Comment by PanJiaChen** [comment]
你说下是mac还是windows,浏览器用的是什么么？

**Comment by barray888** [comment]
mac  chrome

**Comment by barray888** [comment]
@PanJiaChen

**Comment by barray888** [comment]
我刚才在mac下用safari 和 firefox测试  一切正常  难道是chrome浏览器的问题？

**Comment by PanJiaChen** [comment]
比较玄学，我mac chrome 一直没有复现你的问题，有没有可能是你装了什么chrome插件导致的？

**Comment by barray888** [comment]
多谢 应该是我的chrome版本问题 我在旁边电脑试了下正常  应该没问题 多谢提示。

**Comment by a5601564** [comment]
我也发生了同样的问题
