### ISSUE TITLE
多层级TreeTable展开折叠问题

### ISSUE THREAD

**Issue by Elric-H** [PanJiaChen/vue-element-admin#695]
当存在3层或以上的层级时，如果先展开全部数据再折叠1级菜单，会发现虽然2级菜单收起了，但是3级的数据还是显示状态。
跟了下代码发现，应该是这里只判断了该节点的直接父级是否展开才导致了这种状况：
`const show = (row.row.parent ? (row.row.parent._expanded && row.row.parent._show) : true)`

**Comment by PanJiaChen** [comment]
这个好像不会影响你什么操作吧？
你要知道哪些节点折叠与否干嘛？

**Comment by PanJiaChen** [comment]
`element` 2.7.0 支持 `tree-tale 了`。所以 `vue-element-admin`就不再自己维护 `tree-table`了。
