### ISSUE TITLE
如何监听关闭标签

### ISSUE THREAD

**Issue by DHCMediWay** [PanJiaChen/vue-element-admin#696]
在指定标签关闭时执行操作

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/66613f0373c7fb5e5673a2890b1b435c061a4b04/src/views/layout/components/TagsView.vue#L83 
或者你可以自己在vuex新建一个变量，watch 它也可以。

**Comment by zhanganyi** [comment]
@PanJiaChen 请问具体怎么写的，我的需求是我提交了东西，就想把该页面给关闭掉，请问怎样操作？谢谢，另附上：生活愉快1

**Comment by PanJiaChen** [comment]
@zhanganyi  https://github.com/PanJiaChen/vue-element-admin/issues/641
