### ISSUE TITLE
点击左侧路由 , 能不能当网络很慢的时候 , 立即出现一个空白AppMain组件 , 而不是等 组件 所需的 外部资源(比如引入的图表)加载完 才显示 组件?   

### ISSUE THREAD

**Issue by youxdd** [PanJiaChen/vue-element-admin#699]
点击左侧路由 , 能不能当网络很慢的时候 , 立即出现一个空白AppMain组件 , 而不是等 组件 所需的 外部资源(比如引入的图表)加载完 才显示 组件?   
![tim 20180524093821](https://user-images.githubusercontent.com/17402720/40460425-3925b852-5f39-11e8-9a7b-f02f244b6082.png)

**Comment by PanJiaChen** [comment]
不觉得你这种体验会好，还不如加一个全局loading。

**Comment by youxdd** [comment]
嗯 , 仁者见仁吧, 
但是 , 除了  , 加个 全局的 loading 这个外,
能像我说的那样, 先显示目标组件 , 然后 在目标 组件 上 加 loading , 
不然 网络 不好的话. 点击后,  除了 顶部的 nprogress 有反应,  其他地方 都好像 假死了 一样 ,

**Comment by PanJiaChen** [comment]
和`nprogress`一样在那些全局的路由钩子里面设置一个变量，然后根据这个变量来判断显示真正的view或者显示一个空白的view。
https://github.com/PanJiaChen/vue-element-admin/blob/66613f0373c7fb5e5673a2890b1b435c061a4b04/src/views/layout/components/AppMain.vue#L5

或者简单的方法，使用css https://router.vuejs.org/zh-cn/advanced/transitions.html

**Comment by youxdd** [comment]
可以 , 试一下 先
