### ISSUE TITLE
IE 9的的兼容性问题

### ISSUE THREAD

**Issue by fuerpeng** [PanJiaChen/vue-element-admin#70]

**Comment by fuerpeng** [comment]
![Uploading image.png…]()

**Comment by fuerpeng** [comment]
按照 kivi 配置了babel-polyfill  还是有警告
**日志: polyfill-eventsource added missing EventSource to window 
SCRIPT5007: 无法获取属性“isReady”的值: 对象为 null 或未定义** 
而且页面也是错乱 请问还有什么解决办法吗  ——。——

**Comment by PanJiaChen** [comment]
这个错和该项目关系不大，请自行解决。
相关链接：https://segmentfault.com/q/1010000007819785
欢迎解决后，贴出解决方案

**Comment by lisanpeng** [comment]
npm i babel-polyfill
入口文件中添加 import 'babel-polyfill'
webpack中修改： module.exports = {
  entry: ['babel-polyfill', './src/main.js'],
}
亲测可行。

注：支持ie9+。ie如果设置了兼容性模式，需把本站点从兼容性视图中删除。

**Comment by gaoshijun1993** [comment]
@lisanpeng 之前是可以的,可是不知道现在又不行了, 不知道是因为axios版本的原因吗?
