### ISSUE TITLE
Only show side bar when there is nested route

### ISSUE THREAD

**Issue by SaleRise** [PanJiaChen/vue-element-admin#701]
Hi @PanJiaChen

What changes can be made to show sidebar only when child routes exist and parent url is clicked...

For example, for **dashboard** or **Icon** page for example, don't show sidebar (when on that page) but for pages that has child route like **components** or **Example** show sidebar since these pages have child routes...

Hope that makes sense...

**Comment by PanJiaChen** [comment]
Sorry, i didn't understand the effect you wanted. The current effect is that when the child route has only one time, the child route is displayed by default(e.g. **dashboard** or **icon**).

**Comment by SaleRise** [comment]
Yes @PanJiaChen, However I want to not show side bar by default. So for dashboard, since it is only one page, it won't show side bar.

When user clicks on components and for example Mixin, then I want to show side bar and then only show items under Component route ...
Example is as follows:
![chrome_2018-05-25_14-11-04](https://user-images.githubusercontent.com/7464668/40525785-a2756db0-6025-11e8-985c-4bfa288052a5.png)

**Comment by PanJiaChen** [comment]
> However I want to not show side bar by default. So for dashboard, since it is only one page, it won't show side bar.

This effect you can use `hidden: true `

> When user clicks on components and for example Mixin, then I want to show side bar and then only show items under Component route ...
This effect is rather special. I think you can try to use v-show in `SidebarItem.vue`.

**Comment by SaleRise** [comment]
yes that's what I was thinking but thought someone must have already had similar requirement. Thanks

**Comment by moonose** [comment]
Hi @PanJiaChen
I used hidden: true for chgpwd components. 

        { path: '/chgpwd', component: _import('login/chgpwd'), hidden: true },

I have rewrote the code in NavBar.vue

        <el-dropdown-menu slot="dropdown">
          <router-link to="/chgpwd">
            <el-dropdown-item>Change Password</el-dropdown-item>
          </router-link>
        </el-dropdown-menu>

But when i click Change Password, the component page will be shown whole area instead of the content area.
is it the format wrong <router-link to="/chgpwd">? 

Thx

**Comment by PanJiaChen** [comment]
@moonose you should has a base layout.
https://github.com/PanJiaChen/vue-element-admin/blob/66613f0373c7fb5e5673a2890b1b435c061a4b04/src/router/index.js#L95-L104

**Comment by moonose** [comment]
got it~ thx
