### ISSUE TITLE
Sidebar中scroller高度需要调整

### ISSUE THREAD

**Issue by WilliamLin1990** [PanJiaChen/vue-element-admin#702]
sidebar现在底部存在1px的空白，建议作者在下个版本修改sidebar.scss
`.scrollbar-wrapper {
      height: calc(100% + 16px);
      .el-scrollbar__view {
        height: 100%;
      }
    }`
[image](http://wx4.sinaimg.cn/large/6bc06fe1ly1frpplsz957j20950653yf.jpg)

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/d2d323bb027f4335729237a7c6eff4bef199ff44
