### ISSUE TITLE
ie11以下，所有的浮层Popper，类似下拉框，日期选择框都随着滚动条滚动

### ISSUE THREAD

**Issue by Toxicant2** [PanJiaChen/vue-element-admin#703]
看了下element-ui官网在ie11以下是好的，你 http://panjiachen.github.io/vue-element-admin/#/example/table/complex-table，
tab滚动之后点任何一条edit，然后状态下拉框是看不到的，因为已经被滚动到了顶部。ie8,9,10都会有这个问题。希望可以给个解决方法，谢谢。

**Comment by Toxicant2** [comment]
![1527430392 1](https://user-images.githubusercontent.com/19887677/40586916-22d9051c-61fb-11e8-8fe9-8c1090abcd80.jpg)

**Comment by Toxicant2** [comment]
下拉框现在是打开的，但是看不到选择项。

**Comment by Toxicant2** [comment]
![1527430616 1](https://user-images.githubusercontent.com/19887677/40586959-a58e983c-61fb-11e8-9938-d4af74197680.jpg)
本地项目在ie9表现的就是这个样子了，如果滚动条继续滚动，然后就发现弹出层整个就消失了

**Comment by PanJiaChen** [comment]
ie兼容性问题和本项目无关，请到[element](https://github.com/ElemeFE/element/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) 提issue。element 官方其实本身对ie的支持度和关注度就不高。

**Comment by PanJiaChen** [comment]
我看了下，好像官方修复这个问题了，你升级`element-ui`到最新版本试试。

**Comment by Toxicant2** [comment]
不是element-ui版本的缘故，他们官方的网站在IE8都没有出现这个问题，我用element-ui做了其他项目也没发现这个问题，目前只发现你的项目有这个问题。

**Comment by Toxicant2** [comment]
element-ui 升级到了最新，问题还是存在的，我在考虑是不是layout里面布局造成的

**Comment by Toxicant2** [comment]
刚发现问题不是ie出现的，是Edge模拟IE8,9,10会出现。

**Comment by PanJiaChen** [comment]
我暂时也没有windows可以模拟。
