### ISSUE TITLE
关于左侧导航栏和权限的问题

### ISSUE THREAD

**Issue by Orialian** [PanJiaChen/vue-element-admin#704]
![image](https://user-images.githubusercontent.com/34876408/40594352-4e3ec686-6261-11e8-87b7-fc5e88def683.png)
当我把返回的roles 设置成['manager'], 并在路由的一个菜单的meta中的roles属性设置成['admin','manager']时,他的addRouters新添加的路由数组是正确的,它包括含有['manager']的meta所在的路由和404, 但是会出现 上图的错误

**Comment by PanJiaChen** [comment]
你改过其它什么代码么？看着死循坏了。

**Comment by Orialian** [comment]
并没有, 我改成 admin 就可以正常显示的

**Comment by PanJiaChen** [comment]
请提供一下你修改的代码。

**Comment by Orialian** [comment]
![image](https://user-images.githubusercontent.com/34876408/40595491-535f6188-6267-11e8-82fe-be53987e12aa.png)
![image](https://user-images.githubusercontent.com/34876408/40595498-61ba0698-6267-11e8-93d4-567b8aedf20d.png)
![image](https://user-images.githubusercontent.com/34876408/40595553-c0dc96ea-6267-11e8-9fb7-216a00557a29.png)

**Comment by PanJiaChen** [comment]
根据现有代码无法定位你的问题。

**Comment by Orialian** [comment]
@PanJiaChen  我已经找到问题了, 是因为粗心,在初始路有中忘记了去定义 '/404' 的路由...
