### ISSUE TITLE
关于三级嵌套路由侧边栏不响应状态和加载数据

### ISSUE THREAD

**Issue by Orialian** [PanJiaChen/vue-element-admin#705]
![image](https://user-images.githubusercontent.com/34876408/40595338-87afc9ba-6266-11e8-9ef6-1af8364279b1.png)
上图为的左侧菜单栏中的一个
![image](https://user-images.githubusercontent.com/34876408/40595411-dd9a60e2-6266-11e8-8bfb-9eccab64842a.png)
![image](https://user-images.githubusercontent.com/34876408/40595615-3c6c34c8-6268-11e8-9598-018cfbbe15dc.png)
 因为台区管理设置成了3级路由,导致状态响应失败,区域管理是正常的.

**Comment by Willworkgogogo** [comment]
你的redirect地址不对啊，你是想重定向到/Park/ParkIndex，你现在写的会定向要/ParkIndex,  你路由里没有这个地址啊

**Comment by Orialian** [comment]
@Willworkgogogo   我路由没毛病啊,都能跳转到我要的页面啊, 只是跳转到/MeterFile 的时候没有发送数据请求, 不知道为什么

**Comment by Willworkgogogo** [comment]
路由是没问题，我理解错了。可以贴下/MeterFile这个页面的代码逻辑吗？

**Comment by Orialian** [comment]
![image](https://user-images.githubusercontent.com/34876408/40596530-1821fbd8-626e-11e8-8911-c9164b7bc6b6.png)
这是 /MeterFile 的js部分
![image](https://user-images.githubusercontent.com/34876408/40596554-39755622-626e-11e8-93f0-073da725246d.png)
因为很多组件里面的方法相同,所以我是混入进去的, 不知道是不是这里除了问题

**Comment by Orialian** [comment]
@Willworkgogogo  刚发现是数据有接收到, 但是没有渲染出来,
 因为我的组件中大都是数据表格的处理, 所以使用了 Vue,mixin 的方式混入到组件中的, 不知道是不是因为这个原因,导致 /ParkIndex 的数据会渲染而 /MeterFile 中的数据不会渲染

**Comment by Orialian** [comment]
@Willworkgogogo  数据那边没有问题... 是我自己粗心, copy 的时候忘记改单词了...
