### ISSUE TITLE
No parser and no file path given, couldn't infer a parser

### ISSUE THREAD

**Issue by albertShen12** [PanJiaChen/vue-element-admin#706]
![image](https://user-images.githubusercontent.com/31594006/40597922-2ba6bda2-6277-11e8-8c6f-1a2aae8aac76.png)
vue-loader解析每个vue文件的时候都会报错。

**Comment by albertShen12** [comment]
npm install时没出现error，为防万一也rebuild过node-sass，npm install -g过vue-cli。

**Comment by PanJiaChen** [comment]
detail see https://github.com/PanJiaChen/vueAdmin-template/issues/104

**Comment by albertShen12** [comment]
好了，谢谢

**Comment by 8833** [comment]
装了prettier还是报错
