### ISSUE TITLE
路由里面的meta： { roles：[] }权限问题

### ISSUE THREAD

**Issue by chengmanxiang** [PanJiaChen/vue-element-admin#709]
,这个数组不是前端写死的，是后台返回的怎么做呢？，如果后台根据用户role返回用户所有的路由信息，前端显示简单，还是把路由的meta.roles返回前端展示，哪一个比较简单呢

**Comment by PanJiaChen** [comment]
我个人倾向和实际业务中都是前端来存储和控制路由的，后端只返回一个权限，前端根据权限动态生成路由。

**Comment by 107295472** [comment]
那每加个角色 ，更改个角色都要前端改js啊

**Comment by PanJiaChen** [comment]
各有利弊了，后端的话你没新增一个路由也不是要通知后端。或者你可以结合两者，在前台做一个路由可视化配置的页面。

**Comment by 107295472** [comment]
那就是，可视化配置路由，保存写到js文件里

**Comment by 107295472** [comment]
或者做个页面，后端保存就写js路由

**Comment by zsedcbm** [comment]
这个前端不写死的话, webpack能够打包编译所有信息吗?  我是在加载路由的时候重新过滤了一遍路由

**Comment by baidan** [comment]
我现在有个处理方案：
       1，/router/index.js 里面的asyncRouterMap相当于本地所有的菜单数据，每级别必须配置meta: {title:"ify",roles: [] }, children: [{meta: {title:"ify",roles: [] }}]  相当于本地默认的这个都是没有权限的。 除了公共显示的，不需要配置roles
       2，在合并路由之前：GenerateRoutes 这个方法： 通过后台返回配置的权限表，合并进去
              //后台返回的权限表，结构和本地的asyncRouterMap层级一致
       `let rolePaths = [{
          meta: {
            title: 'example',
            roles: ['admin', 'editor']
          },
          children: [{
            meta: {
              title: 'createArticle',
              roles: []
            }
          }]
        }, {
          meta: {
            title: 'table',
            roles: ['admin', 'editor']
          },
          children: [{
            meta: {
              title: 'dynamicTable',
              roles: ['admin', 'editor']
            }
          }, {
            meta: {
              title: 'complexTable',
              roles: ['editor']
            }
          }]
        }] 

     
         //判断是否是管理员
        if (roles.indexOf('admin') >= 0) {
          //动态给所有权限
          for (let j = 0; j < asyncRouterMap_copy.length; j++) {
            if ('roles' in asyncRouterMap_copy[j]['meta']) {
              asyncRouterMap_copy[j]['meta']['roles'] = ['admin'];
            }
            if ('children' in asyncRouterMap_copy[j]) {
              for (let k = 0; k < asyncRouterMap_copy[j]['children'].length; k++) {
                asyncRouterMap_copy[j]['children'][k]['meta']['roles'] = ['admin'];
              }
            }
          }
        } else {
          //如果不是全局配置的管理员
          //判断后端正确返回的路由表
          if (rolePaths.length <= 0) {
            asyncRouterMap_copy = []
          } else {
            for (let j = 0; j < asyncRouterMap_copy.length; j++) {
              for (let i = 0; i < rolePaths.length; i++) {
                //遍历父级
                if (rolePaths[i]['meta']['title'] === asyncRouterMap_copy[j]['meta']['title']) {
                  asyncRouterMap_copy[j]['meta']['roles'] = rolePaths[i]['meta']['roles']
                }

                //遍历子级
                if ('children' in asyncRouterMap_copy[j]) {
                  for (let k = 0; k < asyncRouterMap_copy[j]['children'].length; k++) {

                    if ('children' in rolePaths[i]) {
                      for (let e = 0; e < rolePaths[i]['children'].length; e++) {
                        if (asyncRouterMap_copy[j]['children'][k]['meta']['title'] === rolePaths[i]['children'][e]['meta']['title']) {
                          asyncRouterMap_copy[j]['children'][k]['meta']['roles'] = rolePaths[i]['children'][e]['meta']['roles']
                        }
                      }
                    }
                  }
                }


              }
            }
          }
        }
`

**Comment by SoyMeng** [comment]
实际上是一个动态生成的路由过程，前端的路由列表跟后端返回的路由列表做匹配，重新生成路由列表
