### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by luoxulx** [PanJiaChen/vue-element-admin#711]
In the laravel framework, I used the [element-in-laravel-starter](https://github.com/ElementUI/element-in-laravel-starter) that you proposed last time, everything was configured correctly, but after NPM run dev, the page was open after the page was open, and nothing was wrong.
It's not a blank after build!
It's not a blank after build!
It's not a blank after build!
It's blank after NPM run dev. There is no error message.
How do I fix it?

**Comment by luoxulx** [comment]
![image](https://user-images.githubusercontent.com/35016570/40637463-9fa83986-6337-11e8-95a5-a03720320a99.png)
NPM run prod is running normally, but NPM run dev is blank.

**Comment by PanJiaChen** [comment]
I am not the maintainer of element-in-laravel-starter, so I recommend you go to the official to ask questions.
By the way,there is nothing wrong with the terminal?

**Comment by luoxulx** [comment]
DONE, Compiled successfully in 1344ms ,and the console doesn't have any mistakes.

**Comment by PanJiaChen** [comment]
Sorry, I may not be able to help you. I don't know much about Laravel.

**Comment by luoxulx** [comment]
![image](https://user-images.githubusercontent.com/35016570/40656475-16489150-6377-11e8-96be-14733a591361.png)

I really can't find the cause of the phenomenon. Do you know why these are "empty"?

**Comment by luoxulx** [comment]
![image](https://user-images.githubusercontent.com/35016570/40656989-df822e5e-6378-11e8-8f7d-4cdce99a190c.png)
This picture is the result of 'NPM run prod'
In the picture of the last reply，that picture of result happened by 'NPM run dev'.
In my main.js: ...xxxxxxx... `new Vue({
  router,
  store,
  i18n,
  render: (h) => h(App)
}).$mount('#app')`
App.vue: `<template>
  <div id="app">
    <router-view></router-view>
  </div>
</template>

<script>
  export default{
    name: 'App'
  }
</script>
`
And in my package.json: `{
"scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    }
}`

**Comment by 107295472** [comment]
群主超强啊，国内外通吃
