### ISSUE TITLE
tag-view在进行页面切换的时候，都会出现渲染等待的情况，但是没有从后台拉数据

### ISSUE THREAD

**Issue by honux0906** [PanJiaChen/vue-element-admin#712]
如果将等待渲染的效果去掉，让页面切换更流畅？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/0a196f79ba4bbb78a5ebdbc34a7522468e0e2c48/src/views/layout/components/AppMain.vue#L3

移除`transition`就可以了
