### ISSUE TITLE
请教个思路

### ISSUE THREAD

**Issue by SamoZ** [PanJiaChen/vue-element-admin#715]
![image](https://user-images.githubusercontent.com/25240164/40641782-6e132d5c-634d-11e8-8dad-d6c291a806e1.png)
该项目中路由分为公共路由和异步路由，公共路由不管是admin还是editor都会显示。

### (文字描述可能很乱，不知能否将我的想法表明)

我现在遇到一个问题，就是里面的子路由要根据权限来动态生成，例如上图中Components、Charts等不管角色是谁都显示，但是里面的子路由却要根据角色来区分，同时如果还有嵌套的路由还要根据角色来生成。

个人的解决方案：我将根据角色生成的子路由拿出来放到异步路由来生成，我发现这样我无法确认它的父路由是谁，同时父路由redirect无法实现，所以我在公共路由的子路由中写异步路由，例如这样的

![image](https://user-images.githubusercontent.com/25240164/40642739-96618f9e-6350-11e8-9961-708ebca37d3e.png)

但是我发现，这样写的话，那之前的根据登录的roles获取动态路由便没有用了，因为异步路由都在公共路由里面，同时我在获取异步路由时需要根据roles遍历出想要的，但是如果子路由中还有子路由并且还有子路由，那么就是一个无限遍历的过程，这就很难受，因水平有限，想不到什么好的方法，故来请教，谢谢，谢谢，谢谢

**Comment by PanJiaChen** [comment]
>我现在遇到一个问题，就是里面的子路由要根据权限来动态生成，例如上图中Components、Charts等不管角色是谁都显示，但是里面的子路由却要根据角色来区分，同时如果还有嵌套的路由还要根据角色来生成。

目前的技术方案就满足吧。

```js
{
  path: '/components',
  component: Layout,
  redirect: 'noredirect',
  name: 'component-demo',
  meta: {
    title: 'components',
    icon: 'component'
  },
  children: [
    { path: 'tinymce', component: _import('components-demo/tinymce'), name: 'tinymce-demo', meta: { title: 'tinymce', roles:['admin1'] }},
    { path: 'markdown', component: _import('components-demo/markdown'), name: 'markdown-demo', meta: { title: 'markdown', roles:['admin2'] }},
    { path: 'json-editor', component: _import('components-demo/jsonEditor'), name: 'jsonEditor-demo', meta: { title: 'jsonEditor',  roles:['admin3'] }},
  ]
}
```
