### ISSUE TITLE
关于后端动态获取左侧菜单

### ISSUE THREAD

**Issue by weiaiming** [PanJiaChen/vue-element-admin#717]
你好，请问我想要从后端获取验证权限后的动态菜单该怎么处理，我看别人的博客说是修改permission.js
GenerateRoutes方法，但是我看官方的文档没有相关说明，请问具体该怎么实现？新手多谢。最后感谢作者开源这么好项目。

**Comment by 107295472** [comment]
就是后端生成json路由数据啊，但是那个懒加载方法我不知道怎么拼json啊

**Comment by weiaiming** [comment]
不是获取，关键是怎么动态到路由上去。权限全部交给后端处理，现在的问题就是 如何把数据动态到路由上去。

**Comment by 107295472** [comment]
已经写好了啊，你看权限的js代码

**Comment by weiaiming** [comment]
permission.js ？？

**Comment by moonose** [comment]
应该是改造store\modules\permission.js  ,从后台获取 asyncRouterMap

**Comment by weiaiming** [comment]
谢谢 正在这样改。不过貌似直接跨域获取出了点问题

**Comment by weiaiming** [comment]
哎，后端做前段表示压力山大。再此谢谢各位朋友了。

**Comment by PanJiaChen** [comment]
detail see https://github.com/PanJiaChen/vue-element-admin/issues/293
