### ISSUE TITLE
切换到同一组件时事件不触发。

### ISSUE THREAD

**Issue by a304885433** [PanJiaChen/vue-element-admin#72]
背景： 菜单指向的是同一个页面，只是参数有所区别，控制表格显示的不同列而已。

菜单配置的路由是  common?type=1 , common?type=2，当页面是common?type1=1时，在去切换2，组件的事件，如created并不会触发。这样ef的el-menu，不太好控制选中状态。

然后我尝试配置2个路由表，都指向同一个组件，从 common-1，跳转到common-2，组件的created事件也没有触发。

看起来是因为，组件没有发生变化，所以事件都不会触发。

请问一下，我应该在组件里怎么写，先行谢过。

**Comment by PanJiaChen** [comment]
两种方案
1. 官方推荐的写法，watch router的变化执行相关操作 https://router.vuejs.org/zh-cn/advanced/data-fetching.html
2. 我项目使用的方法是在router-view上面一个唯一的key 强制每次都重新出发create https://segmentfault.com/a/1190000009275424#articleHeader16

**Comment by a304885433** [comment]
@PanJiaChen  感谢解答，很有帮助。key的写法比监视router更方便。
