### ISSUE TITLE
发现Sticky插件 Resiaze 的 bug

### ISSUE THREAD

**Issue by kingkingkids** [PanJiaChen/vue-element-admin#721]
用了Sticky插件，当小窗口的时候滚动一下，再放大窗口，Sticky不会自动计算宽度，还是停留在缩小的宽度，同样当使用左侧菜单栏隐藏功能的时候，Sticky工具条的宽度也不会重新计算一次

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/03e5f762b3892bf2eac800b690844ad7b0a8867e
