### ISSUE TITLE
sticky宽度的resize问题

### ISSUE THREAD

**Issue by kingkingkids** [PanJiaChen/vue-element-admin#725]
再次感谢作者迅速的响应，但是问题仍然存在，收起侧栏的时候NavBar及TagView无法Resize，请看下图
![19](https://user-images.githubusercontent.com/951025/40765922-90e1bdfa-64e0-11e8-9d4b-f66bcad5471d.png)

**Comment by PanJiaChen** [comment]
这和sticky没什么关系吧。

**Comment by kingkingkids** [comment]
试过了，不行的，插入navbar的那一层有一个动态计算宽度，这个宽度如果放在了sticky里面，然后点击menu收藏sidebar不会自动重新计算一次，这个问题是滚动后收起来的时候出现的

**Comment by kingkingkids** [comment]
如下图，滚动过一次后点击hamburger-container的toggleSideBar，就不会自动计算宽度了
![2](https://user-images.githubusercontent.com/951025/40772599-01036284-64f3-11e8-9311-a326a6bd6e27.png)

**Comment by PanJiaChen** [comment]
线上[demo](http://panjiachen.github.io/vue-element-admin/#/example/create) 能重现么？

**Comment by PanJiaChen** [comment]
话说你的布局是不是有问题啊。。。这些为什么会在sticky里面？

**Comment by kingkingkids** [comment]
![image](https://user-images.githubusercontent.com/951025/40773048-4ea6ccd2-64f4-11e8-9508-4b24e3c40c01.png)
我想实现顶部固定的效果，就是navbar 和 tags-view固顶不动，所以我是改了原来的结构的

**Comment by kingkingkids** [comment]
用sticky包裹了 navbar 和 tags-view

**Comment by kingkingkids** [comment]
虽然我用flex重写了这个结构，在main-container那层定义了display:flex，虽然可以固顶了，但是sticky插件不可用了~

**Comment by PanJiaChen** [comment]
Fixed in 320e941
