### ISSUE TITLE
npm install时报错

### ISSUE THREAD

**Issue by itlixiaolong** [PanJiaChen/vue-element-admin#728]
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! Unexpected token v in JSON at position 8220 while parsing near '...17","vue":"^2.3.0","vue-l'

**Comment by PanJiaChen** [comment]
https://github.com/zaach/jsonlint/issues/103

Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/600e75d0a2cc7b6ce51f264982c28e9689093fe4
