### ISSUE TITLE
使用拖拽 dialog  点击下拉框  后拖拽 下拉框里面的信息没一起移动

### ISSUE THREAD

**Issue by shenzhi0222** [PanJiaChen/vue-element-admin#729]
![image](https://user-images.githubusercontent.com/22479716/40786780-7a3e0da4-651e-11e8-876e-10cda3ddf36c.png)

下拉框用的  el-select  

不知道大神有解决方法没有

**Comment by PanJiaChen** [comment]
这主要是`element-ui` 的实现机制问题，不太好更改。所以只能简单hack它，最新提交中增加了一个`@dragDialog`事件回调，你只要监听它在移动的时候就将`select`下拉框隐藏起来就行了。

具体代码：https://github.com/PanJiaChen/vue-element-admin/commit/9ba1ea6933c7b5dfe52d5f6512d2d118cb39e77a

**Comment by shenzhi0222** [comment]
谢谢  已经解决了 由于最近忙  没把解决方案放上来

// 移动当前元素

        const selectList = document.querySelectorAll(".el-select-dropdown");
        console.info(selectList);
        const dropDownDom = selectList[selectList.length - 1];

        dragDom.style.cssText += `;left:${left + styL}px;top:${top + styT}px;`;
        dropDownDom.style.cssText += `display:none`;

**Comment by shenzhi0222** [comment]
通过观察document元素 得到的结果
这是在你那个拖拽指令里面更改的 
暂时能解决问题
