### ISSUE TITLE
权限切换的时候 刷新则变回admin 路由是否要加个params 方便用户

### ISSUE THREAD

**Issue by lsabella** [PanJiaChen/vue-element-admin#73]

**Comment by lsabella** [comment]
@PanJiaChen  thanks

**Comment by PanJiaChen** [comment]
页面只是一个权限的demo，偷懒没做，其实真正的业务中不太会有动态切换权限的需求。
你所说的路由是否要加个params 方便用户是什么意思？

**Comment by lsabella** [comment]
不好意思啊 可能是我没有表述清楚 我的意思是 当切换到editor权限下 再刷新页面  由于url没有加个参数 则又切换到了admin权限  这个demo还是不错的 一直在参考 thanks

**Comment by PanJiaChen** [comment]
不建议这么做，其实权限控制都是基于role和token的。
我已经完善了demo
详情见https://github.com/PanJiaChen/vue-element-admin/commit/ecf7558e8e01cf599a3f7023fc867176a451edc6
谢谢你的建议
