### ISSUE TITLE
怎么在自定义的customTreeTable第一列加上标题？

### ISSUE THREAD

**Issue by kingkingkids** [PanJiaChen/vue-element-admin#733]
![image](https://user-images.githubusercontent.com/951025/40827138-51ccc630-65af-11e8-8502-f1984c891ec1.png)

**Comment by kingkingkids** [comment]
已经解决了~

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1587
