### ISSUE TITLE
页面点击跳转

### ISSUE THREAD

**Issue by syk961118** [PanJiaChen/vue-element-admin#734]
您好,大神.我是一个刚入门的新手  目前正在研究开发新的后台  有个问题想请教  

  就是一个页面上有个按钮,我点击它会跳转到另一个页面   这个跳转的页面 并不是一开始配置的左侧栏里的页面  是点击之后衍生出的一个页面   我需要给这个跳转的页面配置一个路由,但是配置在哪个位置呢 需要配置很多地方吗 一直没搞懂之间的联系  希望您心情好时  指教一下... 万分感谢

(一个小白,许多问题需要研究..  路由,组件,权限  好绝望..)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/router/index.js
在这里配置，路过不想在侧边栏显示加上`hidden:true`就可以。
和vue-router默认配置一样的，建议先看文档。

**Comment by syk961118** [comment]
好的  我在研究研究  谢谢您

**Comment by jackC58** [comment]
这个问题最后解决了？  我目前也遇到了这个问题
