### ISSUE TITLE
example里的edit.vue里存在一个bug

### ISSUE THREAD

**Issue by buliwangzhu** [PanJiaChen/vue-element-admin#736]
原代码：
`<article-detail :is_edit='true'></article-detail>`

应该为：
`<article-detail :isEdit='true'></article-detail>`

因为article-detail组件里的属性为isEdit

**Comment by PanJiaChen** [comment]
并不是bug。
详情见[文档](https://cn.vuejs.org/v2/style-guide/#Prop-%E5%90%8D%E5%A4%A7%E5%B0%8F%E5%86%99-%E5%BC%BA%E7%83%88%E6%8E%A8%E8%8D%90)
