### ISSUE TITLE
在側邊攔加上logo 

### ISSUE THREAD

**Issue by Chen-Michael** [PanJiaChen/vue-element-admin#740]
我嘗試著要在側邊攔加上LOGO，所以改了一下內容
<template>
      <div class="menu-wrapper">
        <template v-for="item in routes" v-if="!item.hidden&&item.children">

          <div v-if="item.meta && item.meta.logo" :index="item.name" :key="item.name">
            <img :src="item.meta.logo" style="width: 100%;" />
          </div>

          <template v-else>
            <router-link v-if="hasOneShowingChildren(item.children) && !item.children[0].children&&!item.alwaysShow" :to="item.path+'/'+item.children[0].path"
              :key="item.children[0].name">
              <el-menu-item :index="item.path+'/'+item.children[0].path" :class="{'submenu-title-noDropdown':!isNest}">
                <svg-icon v-if="item.children[0].meta&&item.children[0].meta.icon" :icon-class="item.children[0].meta.icon"></svg-icon>
                <span v-if="item.children[0].meta&&item.children[0].meta.title" slot="title">{{generateTitle(item.children[0].meta.title)}}</span>
              </el-menu-item>
            </router-link>

            <el-submenu v-else :index="item.name||item.path" :key="item.name">
              <template slot="title">
                <svg-icon v-if="item.meta&&item.meta.icon" :icon-class="item.meta.icon"></svg-icon>
                <span v-if="item.meta&&item.meta.title" slot="title">{{generateTitle(item.meta.title)}}</span>
              </template>

              <template v-for="child in item.children" v-if="!child.hidden">
                <sidebar-item :is-nest="true" class="nest-menu" v-if="child.children&&child.children.length>0" :routes="[child]" :key="child.path"></sidebar-item>

                <router-link v-else :to="item.path+'/'+child.path" :key="child.name">
                  <el-menu-item :index="item.path+'/'+child.path">
                    <svg-icon v-if="child.meta&&child.meta.icon" :icon-class="child.meta.icon"></svg-icon>
                    <span v-if="child.meta&&child.meta.title" slot="title">{{generateTitle(child.meta.title)}}</span>
                  </el-menu-item>
                </router-link>
              </template>
            </el-submenu>
          </template>

運作很正常，但若要讓點下logo會導回首頁直接用a標籤會整頁變成空白

第一次碰VUE，請問應該怎麼實現呢??

**Comment by PanJiaChen** [comment]
router-link

**Comment by Chen-Michael** [comment]
感謝，成功了
