### ISSUE TITLE
关于登录跳转,登录验证器

### ISSUE THREAD

**Issue by syk961118** [PanJiaChen/vue-element-admin#746]
大神你好,在我解决完跨域问题后 调用登录接口返回成功 为什么页面不跳转到首页呢 
![image](https://user-images.githubusercontent.com/33619126/41027549-e4bcf278-69a9-11e8-94f8-90f1eb556a16.png) 这里的代码一直用的是您模板上的 不知道哪里出了问题 导致它不跳转了  

请问您写的登录验证器
![image](https://user-images.githubusercontent.com/33619126/41027629-18143b5e-69aa-11e8-9de7-6e09ea1ed3d1.png)
这里的值限制死了  我该怎么放开它呢 就是输入什么就验证什么  而不是只能输入数组内的值 

希望大神指导一下 万分感谢

**Comment by asxw00** [comment]
大神这个解决了,我目前也遇到这个问题,this.$router.push({ path: '/' })走了无效

**Comment by hoEc** [comment]
也遇见了登录验证的问题，发现在/store/modules/user.js ，SET_TOKEN执行了两次，第二次为空。

![image](https://user-images.githubusercontent.com/20736452/42989802-730d9d74-8c33-11e8-95ba-bde934fd39e9.png)
![image](https://user-images.githubusercontent.com/20736452/42989825-7c2158c4-8c33-11e8-933e-166f979b47d1.png)

**Comment by Panpan0403** [comment]
我也遇见了这个问题，请问你们解决了么？

**Comment by Panpan0403** [comment]
请问解决了么，我也遇到了这个问题

**Comment by newbeekk** [comment]
解决了么。。我也碰到这个问题。实际接口，没法跳转到首页。

**Comment by wangxingguo** [comment]
请问大家解决这个问题了吗?
我也是无法跳转
