### ISSUE TITLE
我是想用后台传值管理路由权限，userinfo接口拿到后台返回的值，通过vuex传递值，赋给router/index.js里面的asyncRouterMap，但每次asyncRouterMap拿到的都是undefined，是不是异步问题？

### ISSUE THREAD

**Issue by Mr-arvin** [PanJiaChen/vue-element-admin#750]
我是想用后台传值管理路由权限，userinfo接口拿到后台返回的值，通过vuex传递值menus，赋给router/index.js里面的asyncRouterMap，但每次asyncRouterMap拿到的都是undefined，是不是异步问题？
我发现在 router/index.js 中打印 console.log(store.state.user.menus),都是undefined，用一个setTimeout就能打印出来。
但如果把 router/index.js 的内容全放在setTimeout里，export方法又回报错。。。
求潘神或者某位有类似经历的大神指点迷津🙏

**Comment by axhello** [comment]
你后端返回的值是什么样的啊？

**Comment by grace618** [comment]
我的好像也是 import {asyncRouterMap} from ‘@/router’  无论从router/index.js里面import什么都是undefined

**Comment by PanJiaChen** [comment]
没太懂什么问题，如果还有问题，请重新开 issue 比提供相关问题描述或者错误。

**Comment by xiuxiuyifan** [comment]
import { asyncRouterMap, constantRouterMap } from '@/router'
console.log(constantRouterMap);
setTimeout(()=>{
  console.log(constantRouterMap)
},0)

我也遇到了  请问大家解决了吗？？？ QQ号 1575243732
