### ISSUE TITLE
初始化的时候总是这个错误，不知道为什么 

### ISSUE THREAD

**Issue by BaoziOR** [PanJiaChen/vue-element-admin#753]
![image](https://user-images.githubusercontent.com/27988506/41146725-c8aeb1c8-6b36-11e8-9fd8-2ba5ad188b22.png)

**Comment by PanJiaChen** [comment]
一般性把`node_modules`删了重装再试试？

**Comment by BaoziOR** [comment]
install 的时候就是这个错误，然后node_modules  文件夹还没有生成呢，

**Comment by PanJiaChen** [comment]
npm cache clean --force 试试咯

**Comment by yilikun** [comment]
用cnpm i安装没问题

**Comment by baidan** [comment]
npm降级下
npm -g i npm@4
