### ISSUE TITLE
transitionend事件监听不到

### ISSUE THREAD

**Issue by zzw118** [PanJiaChen/vue-element-admin#754]
你好，你这边监听侧边栏然后动态更新echarts图表的尺寸，代码只有截图那些吗？我照你的方法，写了一个，但就是监听不到，不知道什么原因，请教下哈~
![adfd](https://user-images.githubusercontent.com/9132607/41153044-2f40f408-6b48-11e8-9bb8-105d8a93309a.jpg)

**Comment by PanJiaChen** [comment]
首先你要确定两个问题：
- 是否获取到了`sidebarElm`
- `transitionend` 事件会在 `CSS transition` 结束后触发的，所以你的`sidebar`是否有`transition`动画

**Comment by zzw118** [comment]
谢谢，重新测试了，原来是有监听到，而是this.__resizeHandler没调用的问题
