### ISSUE TITLE
导航布局问题

### ISSUE THREAD

**Issue by turkeyaa** [PanJiaChen/vue-element-admin#756]
在学习这个项目，我想做水平导航栏布局，设置了Sidebar mode="horizontal"，但是无效？有没有简单的解决方式？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/tree/master/src/views/layout/components/Sidebar

你只能重新写一个水平导航栏，因为目前做了很多css处理，所以不适配水平导航。

**Comment by turkeyaa** [comment]
@PanJiaChen 懂了，感谢！

数据请求的问题：贴上代码：
if (store.getters.token) {
    // config.headers['X-Token'] = getToken() // 让每个请求携带自定义token 请根据实际情况自行修改
  }

只要带上'X-Token'数据请求就失败，注释掉就正常返回json，这个是什么原因？困惑...

这个是错误截图：

<img width="406" alt="error" src="https://user-images.githubusercontent.com/7940089/41210800-584336b6-6d66-11e8-8049-db8f0806a02e.png">

**Comment by PanJiaChen** [comment]
把报错信息百度一下就知道了吧。
