### ISSUE TITLE
关于 页面中 动态 切换组件问题

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#759]
@PanJiaChen 

有个问题请教下：
index.vue 代码如下：定义了listPane 和 addPane 两个组件，默认显示了 listPane 

    <template>
      <div class="tab-container" :is="currentView"></div>
    </template>
    <script>
    import listPane from './listPane'
    import addPane from './addPane'
    export default {
       components: { listPane, addPane },
         data() {
              return {
                  currentView: listPane
              }
         }
     }
    </script>

在listPane  中的表格某行，点击后，要切换到 addPane ,  listPane 里写   this.currentView = addPane 是找不到 addPane 的，这样的切换 该如何处理？

谢谢！

**Comment by PanJiaChen** [comment]
`
<component :is="currentView" :currentView="currentView"></component>
`
`listPane`里面通过props传入并获取`currentView`
