### ISSUE TITLE
怎么解决跳过api拦截，直接访问后端api的问题

### ISSUE THREAD

**Issue by knoixs** [PanJiaChen/vue-element-admin#760]
我现在的后端是API是Django + Django restframework搭建的。
我直接输入127.0.0.1:8080/api/login/会跳转到我API的登录界面，而不是被拦截下来，显示404页面或者直接跳转到登录首页。请问怎么解决？
![1](https://user-images.githubusercontent.com/6317691/41216102-86744fec-6d85-11e8-93a2-0192edb46318.png)

![2](https://user-images.githubusercontent.com/6317691/41216103-870618a0-6d85-11e8-8f07-181140a886b6.png)

**Comment by PanJiaChen** [comment]
没理解你想表达什么？

**Comment by knoixs** [comment]
可能我的表达有问题。
就是我的前端项目域名地址是127.0.0.1:8080，后端API的地址不是这个（这里比如是127.0.0.1:8090）。正常情况下，访问前端域名下的资源http://127.0.0.1:8080/#/login，http://127.0.0.1:8080/#/dashboard这样的URL，都应该是访问的是前端的界面。但是我无意间直接输入127.0.0.1:8080/api/login/，发现显示了我的后端API界面。请问这个是什么问题？

**Comment by PanJiaChen** [comment]
这要看你自己后端项目怎么启动得了，本项目只会启`8080`端口。

**Comment by knoixs** [comment]
不好意思，是我问错了问题。
我刚刚重新看了一下文档，vue-router部分。我现在使用的是hash模式。但是还是可以正常访问127.0.0.1:8080/api/login/，我应该怎么严格限制每个请求必须在域名地址后面都带上"#"，像这样http://127.0.0.1:8080/#/login

**Comment by xiao-2020** [comment]
如果你的接口地址都是 /api 开始的  那倒是 可以配置下重写路径     首先我不知道你的目录结构  如过你是用vue-cli 搭建的  那么 你config/index.js 文件里的dev 配置里面有一个  proxyTable  设置项   这是一个json  名称是你要匹配的路径  后面是你要执行的重写/代理 方案  
 proxyTable: {
      '/api': {
        target: 'http://127.0.0.1:8080', 
        changeOrigin: true,
        pathRewrite: {
          '^/api': '/#/'
        }
      }
    },

proxyTable  可以重写路径 也可以 本地代理    本地开发一样可以调用 其他api接口   你可以查下    其实 这个rewrite 一般用不着的 只需要修改下  target 也是可以 的  target: 'http://127.0.0.1:8080/#/',   随意选择吧

**Comment by xiao-2020** [comment]
![image](https://user-images.githubusercontent.com/23693436/41228096-b70c3704-6da9-11e8-8230-9d9e37754ec2.png)


如果你还需要设置 请求体和响应体的话  可以提出来  随意设置  只需要达到你的要求就行了
