### ISSUE TITLE
upload-excel-component loading效果

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#761]
对handkeFileChange 加了loading 处理，但没有任何效果。看到的反应是excel加载完后 才出来loading，然后loading消失。

    handkeFileChange(e) {
      const files = e.target.files
      const itemFile = files[0] // only use files[0]
      if (!itemFile) return
      this.loading = true // 开始loading
      this.readerData(itemFile)
      this.$refs['excel-upload-input'].value = null // fix can't select the same excel
      this.loading = false // 结束loading
    },

**Comment by PanJiaChen** [comment]
因为`readerData`这里面是异步的，所以就直接执行`this.loading`了
https://github.com/PanJiaChen/vue-element-admin/commit/9f8ac37497a502cb520422e5b91b6d288cc80d80 已将`readerData`改成`promise`形式

**Comment by PanJiaChen** [comment]
又修改了一下，将`loading`放在了`readerData`中，因为拖拽上传并不会触发`handkeFileChange`
https://github.com/PanJiaChen/vue-element-admin/commit/c93fcefe543a5b55ab0179fee453f9d6efded079
