### ISSUE TITLE
不用国际化，webpack打包部分中文乱码，怎么搞

### ISSUE THREAD

**Issue by guoshiqiufeng** [PanJiaChen/vue-element-admin#762]
没使用国际化，直接将菜单的name改成了中文，运行没问题，build 打包js中文乱码，有大神知道怎么解决吗

**Comment by PanJiaChen** [comment]
请提供更详细的错误信息。

**Comment by guoshiqiufeng** [comment]
没有错误日志

**Comment by guoshiqiufeng** [comment]
没有错误日志
好像跟网页默认编码有关，我用chrome的插件将网页编码设置为utf-8就正常了。默认编码中文乱码，在js中中文变成乱码。比如首页> 变成了棣栭〉好像默认是gbk编码

**Comment by PanJiaChen** [comment]
设置`<meta charset="utf-8">`这是中文网页的必要meta标签。

**Comment by guoshiqiufeng** [comment]
设置过了，好像是服务器的问题，我发现网页上的文字没事，js编码有问题，多谢帮助

**Comment by guoshiqiufeng** [comment]
在script引用的时候添加 charset="utf-8" 就可以了
