### ISSUE TITLE
综合Title分页内自动生成的内容如何修改？

### ISSUE THREAD

**Issue by xiang931017** [PanJiaChen/vue-element-admin#763]
综合Title分页内自动生成的内容如何修改？
我想直接套用该模板，但阅读源码有些困难，
![1](https://user-images.githubusercontent.com/39732910/41265326-43beb4b8-6e24-11e8-9d97-507e0ec25a16.PNG)
这部分不知道如何格式化，审查元素的话也是找不到/。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/mock/article.js
内容是在这里通过`mock.js`生成的。
