### ISSUE TITLE
错误消息重复提示

### ISSUE THREAD

**Issue by knoixs** [PanJiaChen/vue-element-admin#766]
请问这种错误消息为什么会重复提示？
当服务器返回的错误代码是400或者401时，先显示我自定义的错误消息，就是下面的第一个，第一个消息消失后，又显示了第二个消息（第一个消息应该是覆盖在第二个消息上了）。
第一个消息是我想显示的，在代码里我写的是this.$message.error("用户账户已禁用")，
第二个不想显示，请问要怎么处理呢？
![1](https://user-images.githubusercontent.com/6317691/41276864-226af536-6e58-11e8-99fc-b0adbb189222.png)
![2](https://user-images.githubusercontent.com/6317691/41276873-272bff98-6e58-11e8-9650-7dde91fd4ea5.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/2a590a208793810dc7f69ed74d2d90c418f43f4e/src/utils/request.js#L62-L70

全局错误提示，可自行修改。
