### ISSUE TITLE
侧边栏跟颜色选择应该优化吧

### ISSUE THREAD

**Issue by jianchengwang** [PanJiaChen/vue-element-admin#767]
侧边栏折叠有很明显的卡顿，筛选主题颜色的时候，界面直接卡死。

**Comment by moonose** [comment]
感觉element的折叠效果不怎么好， 强烈建议潘神借鉴下 https://github.com/iview/iview-admin 效果

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1690
