### ISSUE TITLE
超时登录问题：我的项目中加了一个超时登录

### ISSUE THREAD

**Issue by seean-chan** [PanJiaChen/vue-element-admin#769]
超过设定的时间，点击任何需要刷新数据的地方（点击已有缓存的地方不会弹出超时登录框），就会跳出超时登录框，但此时点击的路由页面已经加载好，数据还没刷新就被超时登录拦截，等我登录进去后页面数据就不会刷新了，要怎么在超时登陆后再调一次请求？

![image](https://user-images.githubusercontent.com/30038138/41283173-799e5d1a-6e68-11e8-98dc-4c9fe0e51797.png)

**Comment by PanJiaChen** [comment]
观察者模式了解一下。
