### ISSUE TITLE
tinymce.vue编辑后，刷新页面都会提示‘系统可能不会保存您所做的更改’，如何去掉这个提示？

### ISSUE THREAD

**Issue by noodv** [PanJiaChen/vue-element-admin#770]
tinymce.vue编辑后，刷新页面都会提示‘系统可能不会保存您所做的更改’，如何去掉这个提示？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/626

回答过你的问题了啊
