### ISSUE TITLE
请问up，页面中的某些按钮、或者表格的某一列该怎么控制权限（根据权限显示或隐藏）啊？

### ISSUE THREAD

**Issue by Jquank** [PanJiaChen/vue-element-admin#771]
请问up，页面中的某些按钮、或者表格的某一列该怎么控制权限（根据权限显示或隐藏）啊？
有没有一劳永逸的解决办法啊cringe

**Comment by PanJiaChen** [comment]
颗粒度的权限建议使用指令。

https://github.com/PanJiaChen/vue-element-admin/blob/2a590a208793810dc7f69ed74d2d90c418f43f4e/src/views/permission/directive.vue#L13
