### ISSUE TITLE
跨域请求不带cookie

### ISSUE THREAD

**Issue by lizhilei** [PanJiaChen/vue-element-admin#772]
在src/utils/request.js  里增加axios.defaults.withCredentials = true;跨域请求也没有带cookies

![image](https://user-images.githubusercontent.com/18048340/41329852-a182cb1e-6f02-11e8-8078-f2afe173cdf5.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/562

**Comment by linguiyuan** [comment]
你有可能遇到了跟他一样的问题,还有是否后台也做了处理https://github.com/PanJiaChen/vue-element-admin/issues/562
