### ISSUE TITLE
请问addRoutes后的路由,如何删除呢?

### ISSUE THREAD

**Issue by 383514580** [PanJiaChen/vue-element-admin#773]
如果不删除, 管理员登陆后退出, 普通用户登陆, 那么普通用户不是有了管理员账号的路由
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/permission.js#L31

如不删除, 那么是如何规避这个问题的呢? 没找到相关代码, 请指点.:apple:

**Comment by PanJiaChen** [comment]
Duplicate of #416 

官方并没有提供相关接口，所以只能通过刷新页面来hack。

**Comment by 383514580** [comment]
刷新这个我在别的文章页有看到, 我在想是不是作者设计addRoutes不是这个意图呢?  不是为了做权限控制?

**Comment by PanJiaChen** [comment]
你可以不用`addRoutes`做权限控制，但稍微麻烦点。

**Comment by PanJiaChen** [comment]
你可以不用`addRoutes`做权限控制，但稍微麻烦点。

**Comment by 383514580** [comment]
好的, 感谢回复
