### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by luoxulx** [PanJiaChen/vue-element-admin#774]
![image](https://githubs.oss-cn-shanghai.aliyuncs.com/screenshot/WechatIMG7.jpeg)
`
export default new Router({
  // mode: 'history', //后端支持可开
  scrollBehavior: () => ({ y: 0 }),
  routes: constantRouterMap
})
`

**Comment by PanJiaChen** [comment]
你编辑器不支持es6吧,或者你babel没配对。

**Comment by luoxulx** [comment]
![image](https://githubs.oss-cn-shanghai.aliyuncs.com/screenshot/WechatIMG8.jpeg) ，编辑器支持的，我只在这里搜到了babel，请问babel如何配置?

**Comment by luoxulx** [comment]
OK已解决，果然babel写错

**Comment by luoxulx** [comment]
![WechatIMG9](https://githubs.oss-cn-shanghai.aliyuncs.com/screenshot/WechatIMG9.jpeg)
但是又有了个新的问题，这是babel配置：
`{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins":["transform-vue-jsx", "transform-runtime"]
}`

**Comment by luoxulx** [comment]
![WechatIMG10](https://githubs.oss-cn-shanghai.aliyuncs.com/screenshot/WechatIMG10.jpeg) 我是漏装了什么吗?

**Comment by luoxulx** [comment]
OK已解决，命令：`ln -s /usr/bin/pngquant node_modules/pngquant-bin/vendor/pngquant
ln -s /usr/bin/optipng node_modules/optipng-bin/vendor/optipng`
