### ISSUE TITLE
调用接口成功后提示Network Error

### ISSUE THREAD

**Issue by Cyuan** [PanJiaChen/vue-element-admin#777]
接口没问题的 ，已经返回数据了，只是一个简单的测试接口

错误:
stack	"Error: Network Error\n   at createError (http://localhost:9527/app.js:2950:3)\n   at handleError (http://localhost:9527/app.js:2521:7)\n   at dispatchEvent (http://localhost:9527/app.js:147245:28)\n   at handle (http://localhost:9527/app.js:147073:14)"

**Comment by PanJiaChen** [comment]
请提供详细报错信息

**Comment by Cyuan** [comment]
找到原因了，又是那CORS的问题
自己再研究下
