### ISSUE TITLE
element-ui 的loading 有偏移现象

### ISSUE THREAD

**Issue by AmadeusSys** [PanJiaChen/vue-element-admin#779]
![image](https://user-images.githubusercontent.com/25811397/41507708-e7583348-726a-11e8-846b-29030bf3cd63.png)
有其他小伙伴遇到的吗

**Comment by PanJiaChen** [comment]
你是指 table 的 loading 么？

**Comment by AmadeusSys** [comment]
是的

**Comment by PanJiaChen** [comment]
页面的转场动画和table loading 的实现冲突了，你可以改一下转场动画。

https://github.com/PanJiaChen/vue-element-admin/blob/master/src/styles/transition.scss

https://github.com/PanJiaChen/vue-element-admin/blob/9cf00fd63a85d4a2c20e7aedc020b832b064772c/src/views/layout/components/AppMain.vue#L3
这里可以换成fade转场模式。

**Comment by PanJiaChen** [comment]
或者`v-loading`的时候不要添加`body`这个修饰符。

https://github.com/PanJiaChen/vue-element-admin/commit/2687b2eb3c96e4fc34f3d62437e97cdfc15bb526
