### ISSUE TITLE
打包之后http请求怎么都变成了file请求

### ISSUE THREAD

**Issue by yy306525121** [PanJiaChen/vue-element-admin#781]
![image](https://user-images.githubusercontent.com/12985872/41519774-a1c796e2-72fc-11e8-8574-f9c54ad0b19e.png)

**Comment by ykchong45** [comment]
我也遇到了相同的问题。请问您是怎么解决的？🙏

**Comment by ZhangWeijie-Z** [comment]
同问，vue-cli3打包好之后 图片路径从http请求变成file请求，请问您是怎么解决的？🙏

**Comment by pyy-pyy** [comment]
大佬这个问题怎么解决啊

**Comment by pyy-pyy** [comment]
> 我也遇到了相同的问题。请问您是怎么解决的？🙏

大佬你这个问题怎么解决的啊

**Comment by Finedl** [comment]
本地打包后需要部署到服务器才正常的（可以通过window下载nginx进行部署检测），因为现在打包是在文件夹下（File），所以file请求没有问题。
https://blog.csdn.net/geidongdong/article/details/122305841
