### ISSUE TITLE
Tabs标签页权限判断问题

### ISSUE THREAD

**Issue by rain-frog** [PanJiaChen/vue-element-admin#782]
Tabs标签页使用指令v-permission判断权限后，只能判断tab-pane内容的显示权限，而tab导航的标题依旧会显示出来

**Comment by PanJiaChen** [comment]
只要这是和element tabs的实现机制有关。`v-permission`的确不适用这种情况，你只能通过自己v-if来处理了。

**Comment by rain-frog** [comment]
好的，感谢回复

**Comment by PanJiaChen** [comment]
增加了一个例子 
https://github.com/PanJiaChen/vue-element-admin/commit/03691739e18ae00b8939d5703ca613e023e64225
