### ISSUE TITLE
upload excel 问题

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#783]
1. 如何限制或者判断上传的文件大小
2 .<upload-excel-component @success='handleSuccess'> 除了success事件外，还有哪个事件是可以在选择文件后触发，或者是在解析过程中触发？
  因为我在handleResults里还需要调用后台函数，所以loading = true 还是不起作用
      this.loading = true
      this.tableHeader = this.handleHeader(header)
      this.handleResults(results)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/commit/cbc3ddd8275d875e860e548dd326a98db1717e54

新增了 `beforeUpload`这个hock 你可以在里面判断文件大小。

loading的话 `on-success`返回的时候代表数据解析完了，但不代表页面就能展示数据了，我试了下两兆以上的excel element的table组件渲染的蛮慢的。
