### ISSUE TITLE
<router-view :key="key"></router-view>里的:key看起来没有任何效果呀？

### ISSUE THREAD

**Issue by zyd** [PanJiaChen/vue-element-admin#785]
src/views/layout/components/AppMain.vue 中新增的
<router-view :key="key"></router-view>
key() {
      return this.$route.fullPath + ‘自定义的字符串’
}
在浏览器地址栏中看不到url新增的部分，是不是vue取消了这个API呀？

**Comment by PanJiaChen** [comment]
请自行了解 vue中key 的作用。

**Comment by zyd** [comment]
thank you.
