### ISSUE TITLE
echart使用时样式污染

### ISSUE THREAD

**Issue by SendTheLinkQuickly** [PanJiaChen/vue-element-admin#786]
![echartserror](https://user-images.githubusercontent.com/21097950/41634165-1086f5ea-7475-11e8-9116-2b366400afda.png)

在使用echart图标放进一个折叠面板时，出现这种情况
![1529462011 1](https://user-images.githubusercontent.com/21097950/41634253-7228ee48-7475-11e8-966a-4848ce6c5055.jpg)
但是一旦进行过页面大小调整，它又会恢复正常
![image](https://user-images.githubusercontent.com/21097950/41634294-af491f0a-7475-11e8-99f7-414e18a52ae2.png)
这个dashboard的页面也会出现这种问题
![image](https://user-images.githubusercontent.com/21097950/41634334-d82b44d4-7475-11e8-9713-80eaed98c332.png)

**Comment by PanJiaChen** [comment]
因为echarts本身并不是自适应的，当你父级容器的宽度发生变化的时候需要手动调用它的`.resize()`方法。所以按你的需求，你可以监听折叠面板的`change`事件，当变化是找到这个图表之后调用它的`.resize()`方法。
