### ISSUE TITLE
建议增加多tab切换

### ISSUE THREAD

**Issue by okjesse** [PanJiaChen/vue-element-admin#79]
后台操作可能在多个功能里面切换，最好能增加个tab切换组件，在点击tab切换回来的时候，数据保持不变

**Comment by wwb568109135** [comment]
使用一下elementUI下面的tab组件处理一下，就好想可以了！

**Comment by PanJiaChen** [comment]
https://segmentfault.com/a/1190000009762198#articleHeader8
相关文章

**Comment by okjesse** [comment]
我自己已经实现了下，现在也是用到了keep-alive,后面准备单独开发出组件，最终达到的效果比如像这个
http://www.sucaihuo.com/modals/16/1653/demo/

**Comment by PanJiaChen** [comment]
已添加
