### ISSUE TITLE
Complextable里动态设置按钮状态问题

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#792]
请教下潘神，

          <template slot-scope="scope">
              <el-button v-if="scope.row[5]=='0'" size="mini" type="success" @click="handleModifyStatus(scope,1)">Yes 
              </el-button>
              <el-button v-if="scope.row[5]=='1'" size="mini" type="danger" @click="handleModifyStatus(scope,0)">No
              </el-button>
          </template>

我在 handleModifyStatus 函数里 用 scope.row[5]=status设置了 状态，可按钮还是没改变，这是什么原因？

**Comment by PanJiaChen** [comment]
请提供更具体代码

**Comment by moonose** [comment]
<template slot-scope="scope">
          <el-button v-if="scope.row[5]=='0'" size="mini" type="success" @click="handleModifyStatus(scope,1)">Yes 
          </el-button>
          <el-button v-if="scope.row[5]=='1'" size="mini" type="danger" @click="handleModifyStatus(scope,0)">No
          </el-button>
      </template>

函数功能是
       handleModifyStatus(rowid, status, scope) {
           const params = { 'status': status, 'rowid': rowid }
           console.log(scope);
           setStatus(params).then(response => {
               scope.row[5] = status
               this.$message({ message: '操作成功', type: 'success' })
           })
        }

F12调试了下， scope 能正确把 row那列的数组值传递进来，scope.row[5] = status 赋值也成功。奇怪的是按钮就是没变化。

**Comment by PanJiaChen** [comment]
首先因为我不清楚你的`scope.row`到底是什么，但从你描述中猜测就是[检测变化的注意事项](https://cn.vuejs.org/v2/guide/reactivity.html)导致的。

**Comment by moonose** [comment]
https://jsfiddle.net/5oks37ru/26/

潘神，为什么连续设置是有问题的？

**Comment by PanJiaChen** [comment]
https://jsfiddle.net/5oks37ru/39/

还是因为数据监测的问题，[数组更新检测](https://cn.vuejs.org/v2/guide/list.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)
