### ISSUE TITLE
丰富的第三方控件来自哪里？

### ISSUE THREAD

**Issue by DrifterD** [PanJiaChen/vue-element-admin#793]
丰富的第三方控件来自哪里？

**Comment by PanJiaChen** [comment]
没理解想表达什么？

**Comment by DrifterD** [comment]
看你的demo里面有很多非element-ui的控件，我想问问哪里有关于vue的第三方组件的。element-ui的框架控件有时候不能满足需求

**Comment by PanJiaChen** [comment]
很多都是组件不是vue的 如 `富文本` 、`markdown`等，是自己封装的。还有些组件如`vue-count-to`是vue的，但是element没有的，可以自行安装。

详情可见[文档](https://panjiachen.github.io/vue-element-admin-site/#/zh-cn/import)
