### ISSUE TITLE
prod 参数问题

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#794]
前后端分离，前台是潘神的这个项目，在prod.nev.js

    module.exports = {
       NODE_ENV: '"production"',
       ENV_CONFIG: '"prod"',
       BASE_API: '"http://localhost:9527/api"',
     }

后台用node写，监听9527端口，访问地址如 http://localhost:9527/api/函数名
npm run build:prod 后部署在Nginx下，访问localhost,可以正常显示页面，但登录时，报Network error错误， 单独访问http://localhost:9527/api/函数名 是成功的。
nginx.conf 也配置了跨域

      server {
            listen       88;
            server_name  localhost;
            location / {
                 #root   html;
                  #index  index.html index.htm;
		  add_header 'Access-Control-Allow-Origin' '*';  
		  add_header 'Access-Control-Allow-Credentials' 'true';
		  add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';					
             }

后台 node程序 也用了跨域处理

        app.use(cors({
            origin:['http://localhost:88'], // 允许的跨域访问地址
            methods:['GET','POST'],
           alloweHeaders:['Conten-Type', 'Authorization']
        }));

请问潘神，这样前后分离，在dev状态下开两个node完全没问题，在prod状态下，把前端部署在Nginx下就call不到后台了，这是什么原因？

![image 14](https://user-images.githubusercontent.com/37356039/41770692-6ee91b3e-7602-11e8-8eb7-0c0a63fc964c.png)
![image 16](https://user-images.githubusercontent.com/37356039/41770693-6f65ae56-7602-11e8-849d-9511d0dfe69f.png)

**Comment by PanJiaChen** [comment]
请截图报错信息。

**Comment by moonose** [comment]
解决了，郁闷下，后台端口写错了～～服了

**Comment by PanJiaChen** [comment]
:sweat_smile:
