### ISSUE TITLE
npm install  出错

### ISSUE THREAD

**Issue by DevondWatch** [PanJiaChen/vue-element-admin#795]
npm install --registry=https://registry.npm.taobao.org
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! Unexpected end of input at 1:40719
npm ERR! "},"_hasShrinkwrap":false,"publish_time":1489390156407},"0.9.4":{"nam
npm ERR!                                                                      ^

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kylin.Woo\AppData\Roaming\npm-cache\_logs\2018-06-24T08_26_58_329Z-debug.log

$ npm -v
5.0.0

$ node -v
v8.0.0

**Comment by PanJiaChen** [comment]
this happens mostly due to poor internet connection.

You can try again `npm install --registry=registry.npm.taobao.org` or use `yarn`.
