### ISSUE TITLE
在左侧菜单中，在子菜单中刷新路由的时候，浏览器直接卡掉了

### ISSUE THREAD

**Issue by Shmaur** [PanJiaChen/vue-element-admin#797]

**Comment by Shmaur** [comment]
[](https://note.youdao.com/yws/public/resource/acdfe7f074ed1cf5aad4b7b2e7c2abca/xmlnote/162724A985E9456B8453BE4F5A36EA5C/4628)

**Comment by Shmaur** [comment]
[photo](https://note.youdao.com/yws/public/resource/acdfe7f074ed1cf5aad4b7b2e7c2abca/xmlnote/162724A985E9456B8453BE4F5A36EA5C/4628)

**Comment by Shmaur** [comment]
只有一两个页面不会一直循环，其他只要刷新就会无限进行循环

**Comment by PanJiaChen** [comment]
请提供详细信息，你的图看不了。

**Comment by Shmaur** [comment]
![image](https://user-images.githubusercontent.com/23330527/41838732-c8e732e0-7893-11e8-8ff4-9d1fd97bfe9a.png)

**Comment by Shmaur** [comment]
首次加载权限的时候不会出错，在刷新后，需要验证权限的路由就会进入到死循环

**Comment by PanJiaChen** [comment]
这种问题我无法提供和有效的帮助，需要自己debug才能定位问题。上面截图的warning提示你重复addrouter了

**Comment by Shmaur** [comment]
问题已解决，感谢🙏

**Comment by airzhanglin** [comment]
> 问题已解决，感谢🙏
大佬，我也遇到这个问题。只要动态生成的路由刷新页面就会进404 然后死循环
