### ISSUE TITLE
多级路由和面包屑导航

### ISSUE THREAD

**Issue by xiaozhanghui** [PanJiaChen/vue-element-admin#800]
门店列表下再打开一个子路由（拜访记录），那么拜访记录和门店列表怎么公用一个view，
想要的导航是  首页/门店列表/拜访记录

**Comment by xiaozhanghui** [comment]
![n5eo niwiemdb5ua7hkt 6x](https://user-images.githubusercontent.com/23646391/41835764-5cb7f468-788b-11e8-8c3f-a3ce89b60064.png)
![pcx17rm3 aq diq cw cj](https://user-images.githubusercontent.com/23646391/41835765-5d3def78-788b-11e8-8d70-21263ba4e356.jpg)

**Comment by xiaozhanghui** [comment]
@PanJiaChen  没明白。我的路由是这样的，根据导航，详情应该是列表的子路由，可是那样就会和列表在同一个容器中
![1114](https://user-images.githubusercontent.com/23646391/41836108-505d0f4a-788c-11e8-8fc2-071b72e3a504.png)

**Comment by PanJiaChen** [comment]
> 门店列表下再打开一个子路由（拜访记录），那么拜访记录和门店列表怎么公用一个view

拜访记录本来就会继承父级的view

**Comment by xiaozhanghui** [comment]
@PanJiaChen https://github.com/PanJiaChen/vue-element-admin/issues/50 #50，其实和他是一个问题，我是因为不知道怎么写才这样写的，按照正常应该是父子关系

**Comment by PanJiaChen** [comment]
你可以在父级路由那里v-if一下 判断当前路径是什么

**Comment by xiaozhanghui** [comment]
@PanJiaChen  是通过判断路由显示和隐藏列表？

**Comment by xiaozhanghui** [comment]
@PanJiaChen 好吧！谢谢了

**Comment by springcold** [comment]
> @PanJiaChen 好吧！谢谢了

怎么弄，没有看懂
