### ISSUE TITLE
timeout 设置

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#801]
能不能对不同的请求，增加不同的timeout 值？默认可以是5秒。因为可能某些实际业务的请求会很长。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/76327a8f2671e3383726faa6dd79266a0e537c6c/src/api/article.js#L3-L9

你可以随便在任何一个请求里面重新设置timeout，覆盖原有实例的设置。
