### ISSUE TITLE
大神在utils/index.js中封装的 debounce 函数如何理解? 看不太明白 

### ISSUE THREAD

**Issue by whkendny** [PanJiaChen/vue-element-admin#802]
![tim 20180625170451](https://user-images.githubusercontent.com/28537245/41841096-f861d0ec-7899-11e8-80d5-42689488f7ca.png)

**Comment by whkendny** [comment]
希望哪位大神能指点指点

**Comment by moonose** [comment]
你可以查下该函数在整个项目中被调用的地方，会发现基本在chart里被调用。。。

**Comment by PanJiaChen** [comment]
其实就是简单的函数防抖，减少重复触发的次数。有兴趣的可以自己搜索一下
debounce(防抖)和throttle(节流)。相关文章还是很多的。
