### ISSUE TITLE
我在列表页缓存了数据，点击增加跳转到增加页面，点击保存关闭增加页面，跳回列表页，怎么能够刷新列表页数据

### ISSUE THREAD

**Issue by guoshiqiufeng** [PanJiaChen/vue-element-admin#803]
我在列表页缓存了数据，点击增加跳转到增加页面，点击保存关闭增加页面，跳回列表页，怎么能够刷新列表页数据，有没有什么办法

**Comment by PanJiaChen** [comment]
首先我不知道你是否使用了 keep-alive组件。其次我不知道你所指的列表页缓存了是怎么实现的。

**Comment by guoshiqiufeng** [comment]
解决了，使用了keep-alive组件，在activated钩子可以监听到

**Comment by lixing0323** [comment]
@guoshiqiufeng 我咋列表界面监听不到activated钩子？你是如何处理的？

**Comment by guoshiqiufeng** [comment]
activated () {
    const flush = this.$route.params.flush;
    if(flush){
      this.getDataGrid()
      this.getShopList()
    }
  }
我就这么写的，至于为啥监听不到就不知道了

**Comment by bufudanqing** [comment]
> activated () {
> const flush = this.$route.params.flush;
> if(flush){
> this.getDataGrid()
> this.getShopList()
> }
> }
> 我就这么写的，至于为啥监听不到就不知道了

你好，请问如何缓存需要缓存的组件呢，我在app.vue里使用v-if来区分是否缓存组件，但是没效果，能否看一下您的代码？

**Comment by guoshiqiufeng** [comment]
我用的作者的模板，在AppMain缓存的<template>
  <section class="app-main" style="min-height: 100%">
    <transition name="fade-transform" mode="out-in">
      <keep-alive :include="cachedViews">
        <router-view :key="key"></router-view>
      </keep-alive>
    </transition>
  </section>
</template>

<script>
export default {
  name: 'AppMain',
  computed: {
    cachedViews () {
      return this.$store.state.tagsView.cachedViews
    },
    key () {
      return this.$route.fullPath
    }
  }
}
</script>

**Comment by frede2010** [comment]
> @guoshiqiufeng 我咋列表界面监听不到activated钩子？你是如何处理的？

检查一下你的router 和路由对应的 view component name 是不是完全一致的，一般activated不生效都是路由或者name的问题。
