### ISSUE TITLE
uploadexcel 判断文件大小有问题

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#810]
假设文件1.3M
isLt2M 值是false，下面的判断错了。

要改成 const isLt2M = file.size / 1024 / 1024 > 2 

         beforeUpload(file) { 
     25       const isLt2M = file.size / 1024 / 1024 < 1 
     26  
     27       if (isLt2M) { 
     28         return true 
     29       } 
     30       this.$message({ 
     31         message: 'Please do not upload files larger than 2m in size.', 
     32         type: 'warning' 
     33       })

**Comment by PanJiaChen** [comment]
感谢指出，的确疏忽写错了。

Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/59789d92cfe6105cff6e6b7411d03ac43296440e
