### ISSUE TITLE
Directive Permission 指令权限不兼容ie吗？

### ISSUE THREAD

**Issue by zhaomengqiao** [PanJiaChen/vue-element-admin#812]
Directive Permission 指令权限不兼容ie吗？
ie10\ie11都不行。edge可以兼容

**Comment by PanJiaChen** [comment]
ie有些兼容性问题，你暂时可以用
https://github.com/PanJiaChen/vue-element-admin/blob/59789d92cfe6105cff6e6b7411d03ac43296440e/src/views/permission/directive.vue#L25
的方法。

我之后修复一下。

**Comment by zhaomengqiao** [comment]
好的谢谢，等于多用if判断下是吧

**Comment by PanJiaChen** [comment]
我在ie 9上测试了一下，没发现有什么问题。能否提供报错信息？

**Comment by PanJiaChen** [comment]
是 `parentNode`不兼容，兼容还是蛮麻烦的，还是自行打`polyfill`. https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove#Browser_compatibility

不准备兼容了，可以用 `checkPermission`代替。

**Comment by zhaomengqiao** [comment]
只用checkPermission 就可以了是吧，就放弃v-permission指令呗
