### ISSUE TITLE
使用Complex Table, Property or method "$t" is not defined

### ISSUE THREAD

**Issue by qirixi** [PanJiaChen/vue-element-admin#813]
<el-input @keyup.enter.native="handleFilter" style="width: 200px;" class="filter-item" :placeholder="$t('table.title')" v-model="listQuery.title">
      </el-input>

$t在哪定义呢，需要别的包么

**Comment by rouyuanfang** [comment]
$t(table.title)中table是在哪里定义的呢

**Comment by PanJiaChen** [comment]
`$t` is `vue-i18n` global function.
