### ISSUE TITLE
使用这个v-if="checkPermission(['admin','editor'])"判断权限 360急速浏览器兼容模式就白屏

### ISSUE THREAD

**Issue by zhaomengqiao** [PanJiaChen/vue-element-admin#815]
使用这个v-if="checkPermission(['admin','editor'])"判断权限 
360急速浏览器兼容模式访问加这个的页面就是白屏
我看咱官方的http://panjiachen.github.io/vue-element-admin/#/ 登录页就是白屏
应该不是ajax通信的兼容问题吧，现在是整页白屏

**Comment by PanJiaChen** [comment]
不兼容，请自行打`polyfill`
