### ISSUE TITLE
如何使用qs.stringify转换数据格式？

### ISSUE THREAD

**Issue by chrwwmm** [PanJiaChen/vue-element-admin#816]
export function msgListV2(params) {
	let para = qs.stringify(params)
	return request({
		url: 'get/message/record/list/new',
		method: 'post',
		para
	})
}
这样写不行

**Comment by PanJiaChen** [comment]
请自行看 axios文档。

```js
export function msgListV2(params) {
let para = qs.stringify(params)
return request({
url: 'get/message/record/list/new',
method: 'post',
data:para
})
}
```
