### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by MicroLord** [PanJiaChen/vue-element-admin#820]
默认拥有admin角色的用户，可以看到editor角色的菜单，严格来讲，admin角色和editor角色没有谁大谁小的概念吧，是不是哪里需要设置一下？

**Comment by PanJiaChen** [comment]
恩，这里按照常规逻辑，`admin`拥有最高的权限，可以看所有的页面。

https://github.com/PanJiaChen/vue-element-admin/blob/e4481a9d3493fffafc8fa30e314abbae897ce6b7/src/store/modules/permission.js#L50-L52

移除这个判断就可以，这样就会按照你说的，所以角色没有大小的概念了。
