### ISSUE TITLE
POST请求后立刻GET请求，出现跨域问题

### ISSUE THREAD

**Issue by chw741852** [PanJiaChen/vue-element-admin#821]
我有一个列表功能，用户删除其中一条记录后，立刻刷新整个列表。在快速”删除 “多条记录时，会小概率性的出现跨域问题。

**代码：**
![7a6ec084d9d04fb62ee1b3a9dfe3800](https://user-images.githubusercontent.com/4208410/42083903-cf9284cc-7bbe-11e8-8526-777870abe547.png)

**问题：**
![5de873e7858a0567b66ea3c776b6936](https://user-images.githubusercontent.com/4208410/42083910-d305ac1a-7bbe-11e8-95cb-29c5fd4d69db.png)

**Comment by PanJiaChen** [comment]
跨域问题请自行解决
