### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by 727023460** [PanJiaChen/vue-element-admin#824]
Failed to load http://192.168.10.182:8000/login/login: Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.

我用python3 模拟请求这个地址，是成功的，但是项目访问报这个错

**Comment by PanJiaChen** [comment]
提示报错已经很明确，跨域问题请自行检索解决。

**Comment by 727023460** [comment]
header contains multiple values '*, http://192.168.10.181:9527', but only one is allowed.   跨域解决了，这个是什么问题，我后端用的iris，  中间没有使用代理

**Comment by xuwankang** [comment]
xhr.js:178 Failed to load localhost:8000**********: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.这个怎么解决
