### ISSUE TITLE
动态加载路由 页面刷新问题

### ISSUE THREAD

**Issue by SunnyYC** [PanJiaChen/vue-element-admin#825]
动态加载的路由，在页面的菜单中可以根据路由跳转到页面，但页面刷新的时候就会跳转到404页面，在地址栏直接输入路径也是跳转到404。
![image](https://user-images.githubusercontent.com/28945380/42122907-bb4b1764-7c7b-11e8-91ec-d8c5fb99a928.png)
测试的动态路由

![image](https://user-images.githubusercontent.com/28945380/42122890-522e30fe-7c7b-11e8-98d7-b31ac8dafa12.png)
1111是有打印出来的

**Comment by PanJiaChen** [comment]
有没有确保`404页面`是最后add的？

**Comment by SunnyYC** [comment]
![Uploading image.png…]()

是把这个放在asyncRouterMap的最后么

**Comment by PanJiaChen** [comment]
恩， 见 [文档](https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/router-and-nav.html#%E8%B7%AF%E7%94%B1)
