### ISSUE TITLE
master 分支，npm install 后，npm run dev报错

### ISSUE THREAD

**Issue by qyjs** [PanJiaChen/vue-element-admin#826]

**Comment by qyjs** [comment]
master 分支，npm install 后，npm  run dev报错
`cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`

**Comment by qyjs** [comment]
yarn run v1.3.2
(node:37824) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack
.dev.conf.js
/bin/sh: cross-env: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
这个报错.

**Comment by PanJiaChen** [comment]
`npm install cross-env` 或者重新install一下依赖。

**Comment by gaosuccess** [comment]
@qyjs

我使用 yarn 安装，没问题。你要不要试一试呢 ?

```
npm install -g yarn

yarn
```
