### ISSUE TITLE
如何动态修改  面包屑  和  标签栏

### ISSUE THREAD

**Issue by X-Mars** [PanJiaChen/vue-element-admin#827]
大佬，你好。
       小弟，再做一个报表系统，希望  动态修改  面包屑  和  标签栏，显示报表的名称。不知道可以实现吗
谢谢

**Comment by PanJiaChen** [comment]
没懂你具体的需求。

**Comment by X-Mars** [comment]
![需求](https://image.ibb.co/m1OqWd/QQ20180702_153722.jpg)

**Comment by X-Mars** [comment]
1. 每当我点击查看，就打开一个新的页面
2. 页面的 标签名称 就显示  报表的名称

疑问：
1. 如何修改 标签 的名称
2. 如何修改 面包屑的名称

**Comment by X-Mars** [comment]
`methods: {

            getBreadcrumb() {
                let matched = this.$route.matched.filter(item => item.name)
                console.log(matched)
                matched[0].name = "abc"
                matched[0].meta.title = "abc"
                console.log(matched)
                const first = matched[0]
                if (first && first.name !== 'dashboard') {
                    matched = [{ path: '/dashboard', meta: { title: 'dashboard' }}].concat(matched)
                }
                this.levelList = matched
                console.log(this.levelList)
            },
}`



通过上述方法实现了需求，不知道大佬有没有更好的做法。

**Comment by PanJiaChen** [comment]
现在默认都是读取 route `meta.title`的属性，要么你改这个属性，要么去改读取的function。

**Comment by X-Mars** [comment]
![2](https://image.ibb.co/cES16d/QQ20180703_140514.jpg)

打开第一个标签，显示异常
打开第二个标签，显示第一个的名字
打开第三个标签，显示第二个的名字

**Comment by X-Mars** [comment]
已解决。以下是解决代码。供后人才考。
VUE：  
`
 this.$route.meta.title = reportName
 this.$store.dispatch('editVisitedViews', this.$route)
`
tagsView.js:
`
        EDIT_VISITED_VIEWS: (state, view) => {
            for (var Index in state.visitedViews) {
                console.log(state.visitedViews[Index].path)
                if (state.visitedViews[Index].path == view.path) {
                    state.visitedViews[Index].title = view.meta.title
                }
            }
        },

............

        editVisitedViews({ commit, state }, view) {
            return new Promise((resolve) => {
                commit('EDIT_VISITED_VIEWS', view)
                resolve([...state.visitedViews])
            })
        },
`

**Comment by sharexia** [comment]
X-Mars大大，我也有你一样的需求，目前跟你上面所述情况一样，标签始终慢一拍，看不懂你的解决方案，可以具体些么？

**Comment by sharexia** [comment]
X-Mars大大，感谢，照你方法完美解决

**Comment by X-Mars** [comment]
sharexia  
```javascript
this.$route.meta.title = reportName    
```
这个是修改面包屑的方法，你找找切换标签的地方，加上这句试试。

**Comment by archsh** [comment]
这个方法连左侧的菜单项都被改了。
