### ISSUE TITLE
代理跨域访问配置无用

### ISSUE THREAD

**Issue by Erik5169** [PanJiaChen/vue-element-admin#829]
hello, 我按照文档配置了   
proxyTable: {
      '/v2': {
        target: 'https://api.douban.com',
        secure: false,
        changeOrigin: true,
        pathRewrite: {
          // /v2将代表target/v2 
          '^/v2': '/v2'
        }
      }
    }
取消了  mock.js  // import './mock' // simulation data

但是资源访问的时候还是提示
Failed to load https://api.douban.com/v2/book/1220562: No 'Access-Control-Allow-Origin' header is present on the requested resource.  能帮我看下什么问题吗? 感觉配置没有问题的呀?

**Comment by moonose** [comment]
此项目是前台，用 cors，写在后台，类似：
let cors = require('cors');
 app.use(cors({
 origin:['http://localhost:9527'],
 methods:['GET','POST'],
 alloweHeaders:['Conten-Type', 'Authorization']
 }));

**Comment by Erik5169** [comment]
我这边是在前端配置代理, 主要是前端开发环境中调试接口, 这边后端CORS还没弄好,所以需要在webpack中配置代理, 但是不起作用

**Comment by Erik5169** [comment]
hello, 这个项目如果修改为前端设置代理跨域访问, 该怎么去修改呢? 主要是为开发环境服务

**Comment by ycg000344** [comment]
在后台没开CORS的时候参考了简书的一篇文章配置了proxytable解决了跨域的问题。
传送门： https://www.jianshu.com/p/95b2caf7e0da
你可以对比一哈，然后...重新npm run dev。。

**Comment by PanJiaChen** [comment]
要将 `axios` 的 `baseURL: ''`

**Comment by lxk0301** [comment]
> 要将 `axios` 的 `baseURL: ''`
> 
> ```js
>  proxyTable: {
>       "/v2": {
>         target: "https://api.douban.com",
>         changeOrigin: true,
>         secure: false
>       }
>     }
> ```

![image](https://user-images.githubusercontent.com/21308593/49860812-843b4a00-fe35-11e8-922e-b9015486dc8f.png)
我这里设置,  好像还是不能解决跨域的问题
