### ISSUE TITLE
引导页指向侧面导航栏不能显示指定内容

### ISSUE THREAD

**Issue by cgq355716727** [PanJiaChen/vue-element-admin#830]
引导页指向侧面导航栏不能显示指定内容，说明文字指示框都显示位置正确，指定的element显示不出来.

**Comment by cgq355716727** [comment]
我在defineSteps.js中添加了如下代码
  {
    element: '.menu-wrapper',
    popover: {
      title: '侧边菜单栏',
      description: '选择相应的侧边菜单栏',
      position: 'left'
    }
只显示一个白框在侧边菜单栏上，菜单上的内容不能显示，

**Comment by PanJiaChen** [comment]
```js
{
  element: '.sidebar-container',
  popover: {
    title: '侧边菜单栏',
    description: '选择相应的侧边菜单栏',
    position: 'right'
  }
}
```

首先不要用`.menu-wrapper`这种一个页面有多个的class，其次应该是`right` 不是`left`。

**Comment by cgq355716727** [comment]
可能我写的没有代表性，我发现一个元素的父元素设置position:fixed;他的子元素就没办法用引导页显示了。因为z-index的从父原则，所以父元素以外的都没办法进行z-index比较

上面你写的例子.sidebar-container设置了position:fixed;它的子元素如果设置成引导页就没办法让指写的元素显示在引导页之上

请教有解决办法吗

**Comment by cgq355716727** [comment]
好的谢谢
