### ISSUE TITLE
使用表单的选择框遇到个问题

### ISSUE THREAD

**Issue by zarte** [PanJiaChen/vue-element-admin#831]
temp={
..
project : ""
..

this.$refs['dataForm'].validate((valid) => {
            if (valid) {
              console.log(this.temp)
              console.log(11)
//异步请求创建
              createGroup(this.temp).then(() => {
               //异步请求获取信息
                getProjectInfo(this.temp.project).then(res => {
                  this.temp.project = {
                    name: res.name,
                    id: res.id
                  }
                  console.log(44)

代码截取如上

现在遇到个问题就是temp.projec打印出来会是后面的对象结构有id和name，但是控制态输出的顺序是temp 
11
44
按道理temp结构应该还没变才对呀

**Comment by PanJiaChen** [comment]
图挂了并且请使用 `jsfiddle` 提供在线demo。

**Comment by zarte** [comment]
没图，jsfiddle弄不了，使用的是views/table/complextable.vue 那个页面改的，dialog的select用带远程搜索功能。

**Comment by PanJiaChen** [comment]
完全不懂你想表达，请重新组织一下问题，格式化一下自己的代码。
