### ISSUE TITLE
如何再次刷新页面

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#836]
我用了  this.$router.push(router) 想再次刷新页面，但没有效果。
该如何解决？

**Comment by PanJiaChen** [comment]
https://github.com/vuejs/vue-router/issues/296

的确可以加一个这个reload的功能。

**Comment by Fan-City** [comment]
vue在route不发生变化的时候，是不会重载画面的吧，试试location.reload()可行么？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/redirect/index.vue

新增了 `redirect`页面。

**Comment by GreatAuk** [comment]
> https://github.com/PanJiaChen/vue-element-admin/blob/master/src/views/redirect/index.vue
> 
> 新增了 `redirect`页面。

请问下用`this.$router.replace({ path: this.$route.path, query: { t: Date.now()}})` 和重定向这两个方案有什么区别吗。

**Comment by PanJiaChen** [comment]
你这个等于每个页面后面都会跟一个时间戳，如果不介意也可以，相关内容文档里有介绍。

https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/router-and-nav.html#%E7%82%B9%E5%87%BB%E4%BE%A7%E8%BE%B9%E6%A0%8F-%E5%88%B7%E6%96%B0%E5%BD%93%E5%89%8D%E8%B7%AF%E7%94%B1
