### ISSUE TITLE
有什么办法可以定义一个模板，自动生成页面吗

### ISSUE THREAD

**Issue by James-jun06** [PanJiaChen/vue-element-admin#84]
比如表单开发，定义好各个字段，和表单页面模板，后台自动建表和生成对应接口，最后利用这个模板生成.vue的页面文件，请高手指点下思路

**Comment by ttop5** [comment]
[yeoman](https://github.com/yeoman/yeoman)  应该能帮你做一部分工作 :bowtie:  @James-jun06

**Comment by PanJiaChen** [comment]
就没太大难度，等于后台接口出了之后 ，约定好一个格式 配置一点东西 按规则生成表单就可以了，和vue关系不大

**Comment by PanJiaChen** [comment]
太久没回应，先关闭了。与需求再打开
