### ISSUE TITLE
Module not found: Error: Can't resolve '@/views'  如何解決呢？

### ISSUE THREAD

**Issue by yuanjianhua** [PanJiaChen/vue-element-admin#840]
![image](https://user-images.githubusercontent.com/948641/42315385-e5505bee-8079-11e8-821d-973d2cda4bf9.png)

**Comment by yuanjianhua** [comment]
![image](https://user-images.githubusercontent.com/948641/42315470-1b8fc29e-807a-11e8-945e-27d25cefb995.png)

直接在component写就没问题

**Comment by PanJiaChen** [comment]
我猜是没配 webpack [alias](https://webpack.js.org/configuration/resolve/#resolve-alias)
