### ISSUE TITLE
need yarn.lock

### ISSUE THREAD

**Issue by Tomatoo** [PanJiaChen/vue-element-admin#842]
we need yarn.lock to lock package version to prevent version change problems.

I will submit a pull request if we think it's necessray.

**Comment by PanJiaChen** [comment]
Sounds Good to Me.

**Comment by Tomatoo** [comment]
ok, I will submit a pr.

**Comment by PanJiaChen** [comment]
Not ready to add yarn.lock, if you need, you can add it locally.
