### ISSUE TITLE
能请教一个问题吗？

### ISSUE THREAD

**Issue by VEMTK** [PanJiaChen/vue-element-admin#85]
Table控件切换List与Grid模式该怎么做了，望指教下。

**Comment by PanJiaChen** [comment]
没太理解什么意思

**Comment by VEMTK** [comment]
表格可以切换 列表模式和网格模式，用element ui好难实现。谢谢指教

**Comment by PanJiaChen** [comment]
是这个意思么？
https://jsfiddle.net/PanJiaChen/86grwy8c/1/

**Comment by VEMTK** [comment]
http://www.htmleaf.com/Demo/20141122563.html 这种效果

**Comment by PanJiaChen** [comment]
那只能靠自己写了 现有element是做不到的

**Comment by VEMTK** [comment]
好的 谢了
