### ISSUE TITLE
Sidebar展开时tag的右键菜单会错位

### ISSUE THREAD

**Issue by ycg000344** [PanJiaChen/vue-element-admin#850]
如图，
1. 展开

![default](https://user-images.githubusercontent.com/36219142/42437493-dae9b47a-838f-11e8-9afc-2bc7e2663a68.jpg)

2. 收

![default](https://user-images.githubusercontent.com/36219142/42437503-e1a57470-838f-11e8-84e6-ec637d57134c.jpg)

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/89ce53e18571e3482fcbf56dfbcc244ce04a7024
