### ISSUE TITLE
热加载慢问题

### ISSUE THREAD

**Issue by osinglee** [PanJiaChen/vue-element-admin#851]
项目中有上百个页面，现在改一点点需要2000+s，很痛苦。看了你的文档。说的是懒加载导致，但你的项目中同样使用了懒加载。

**Comment by PanJiaChen** [comment]
`2000+s`和懒加载没关系了，基本是`dev` 配置没配对。比如`sourcemap`或者执行了一些不要被执行的`js` 比如执行检查了 `node_modules`里面的代码。

**Comment by osinglee** [comment]
谢谢你的回答，是 .babelrc 配置问题
