### ISSUE TITLE
在chrome调试模式下的ipad出现的交互问题

### ISSUE THREAD

**Issue by Samdyddd** [PanJiaChen/vue-element-admin#852]
[
![default](https://user-images.githubusercontent.com/23043927/42485735-8c5d898e-842b-11e8-852b-5427a81e85ae.PNG)
](url)

**Comment by axhello** [comment]
css问题，Layout里的drawer-bg的position改成fixed即可

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/9b7a9a64e56e622f58aca92d6418d18b9446d9a9
