### ISSUE TITLE
DefinePlugin 读取配置的时机问题

### ISSUE THREAD

**Issue by feymanlee** [PanJiaChen/vue-element-admin#854]
https://github.com/PanJiaChen/vue-element-admin/blob/master/build/webpack.dev.conf.js#L16-L17 这两个变量在这个位置还读取不到吧？

**Comment by PanJiaChen** [comment]
你可能理解错了。

https://github.com/PanJiaChen/vue-element-admin/blob/9b7a9a64e56e622f58aca92d6418d18b9446d9a9/build/webpack.dev.conf.js#L16-L17

这两个变量在这里是 `node`的环境变量。 所以这里的意思是查看你是否有手动设置 `HOST` 或者 `PORT`。
如:
```bash
"scripts": {
    "dev": "xxx HOST=XXX PORT=9527"
}
```
