### ISSUE TITLE
有人抄袭这个项目 把作者写的代码当成自己写的

### ISSUE THREAD

**Issue by zuorichongxian** [PanJiaChen/vue-element-admin#855]
[https://github.com/mgbq/nx-admin](https://github.com/mgbq/nx-admin)
[掘金](https://juejin.im/post/5b43226c51882519ad616c2a)

**Comment by daiing** [comment]
有锁屏和首页动画

**Comment by PanJiaChen** [comment]
感谢你的提醒。不过我做这个开源项目的目的很纯粹，帮助和方便大家搭建后台。某些人借鉴或者复制某些功能，都无所谓吧，本来就开源了，不要太过分就行了。 

再次感谢你的提醒。

**Comment by moonose** [comment]
锁屏有问题，首页动画倒是可以借鉴下。不过尽然没提从潘神这项目借鉴的，开了个bug提醒他～～

**Comment by quiteqiang** [comment]
> 感谢你的提醒。不过我做这个开源项目的目的很纯粹，帮助和方便大家搭建后台。某些人借鉴或者复制某些功能，都无所谓吧，本来就开源了，不要太过分就行了。
> 
> 再次感谢你的提醒。

今天下班看到些软件侵权导致吃官司的文章，然后搜了好多关于MIT License 相关的文章，担心我用你的代码会侵权，看到你这句话我就放心了，如果我的产品推出去的话，第一笔收入我一定不自己花，一定拿来打赏你！！！
