### ISSUE TITLE
Exported excel don't have default name(excel-list)

### ISSUE THREAD

**Issue by LoveMeWithoutAll** [PanJiaChen/vue-element-admin#857]
When exporting to excel file, **default name(excel-list) is not work**. So if one doesn't enter the file name in input tag, 'xlsx' is the name of the downloaded file without any extension filename.

![image](https://user-images.githubusercontent.com/4844714/42552781-f12bda44-8518-11e8-9498-be8988f68252.png)

**Comment by PanJiaChen** [comment]
fixed in https://github.com/PanJiaChen/vue-element-admin/pull/858/commits/bcd6d5441a053c940930a6963b668cd04cc4992e
