### ISSUE TITLE
为什么我配置代理了，还出现跨域问题！

### ISSUE THREAD

**Issue by wlLeblanc** [PanJiaChen/vue-element-admin#859]
![image](https://user-images.githubusercontent.com/22288871/42560071-6dc52e3e-8528-11e8-9cdb-5eed4a39309c.png)
![image](https://user-images.githubusercontent.com/22288871/42560119-8466dd90-8528-11e8-9c8b-a1abcaf2e581.png)

**Comment by wlLeblanc** [comment]
麻烦大佬们指点一下，已经纠结了好久了！

**Comment by AngryCatherine** [comment]
老铁 我也遇到了 解决一天了，同等答案 不要沉

**Comment by PanJiaChen** [comment]
将 `axios`的  `baseURL: ''`

如：
``` js
export function getList(params) {
  return request({
    url: '/v2/book/1220562',
    method: 'get',
    params,
    baseURL: ''
  })``
}
```

**Comment by wlLeblanc** [comment]
谢谢，这个问题已经找后端解决了，谢谢！

**Comment by SuperZiLu** [comment]
> 谢谢，这个问题已经找后端解决了，谢谢！

怎么解决的 是后端的问题嘛？
