### ISSUE TITLE
网站打不开什么情况

### ISSUE THREAD

**Issue by guyuewuren** [PanJiaChen/vue-element-admin#860]
无法访问此网站
网址为 http://panjiachen.github.io/vue-element-admin 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_CONNECTION_ABORTED

**Comment by PanJiaChen** [comment]
github 有时候会被墙，我考虑在码云开一个镜像项目吧。提高一下国内访问速度。

**Comment by PanJiaChen** [comment]
码云地址 ： https://panjiachen.gitee.io/vue-element-admin/#/
