### ISSUE TITLE
关于Tinymce编辑器加载优化的疑问

### ISSUE THREAD

**Issue by DavidCao626** [PanJiaChen/vue-element-admin#862]
由于项目中一个很小的业务页面才需要用到富文本编辑器，现在咱们的方案是在index.html文档中引用了tinymce的js，那这样我每次请求都会额外加载这个大块头js。有好的优化解决办法吗？

**Comment by PanJiaChen** [comment]
暂时可直接用 [tinymce-vue](https://github.com/tinymce/tinymce-vue)

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/pull/2102
