### ISSUE TITLE
支持消息中心

### ISSUE THREAD

**Issue by linlinjava** [PanJiaChen/vue-element-admin#863]
管理后台有的会有消息中心，不知道这个特性会不会支持。

**Comment by PanJiaChen** [comment]
如果向其它项目一样做一个纯前端的消息中心还是很方便的。

**Comment by linlinjava** [comment]
采用mock的纯前端就可以。

从个人经验来说，基本功能可能应该实现以下：
1. 右上角显示消息图标，如果有消息，则图标颜色应该明显不同；
2. 点击消息图标，应该出现消息列表；用户可以直接设置已读，而不一定要打开消息；
3. 如果点击消息列表某个消息，应该出现具体的消息详情；

**Comment by luwzchn** [comment]
@moonose websocket

**Comment by ChasLui** [comment]
@luwzchn @moonose 轮询和websocket最好两种都支持, 因为受限于很多因素, ws在生产环境不允许使用

**Comment by 15036900300** [comment]
轮询会不会增加服务器的压力

**Comment by daiing** [comment]
极度需要+1

**Comment by linlinjava** [comment]
+1

作为管理后台，通常只有少数人使用，轮询应该对后台压力不大，实现比较容易。

**Comment by huangyi1214** [comment]
特别需要

**Comment by huangyi1214** [comment]
有例子可以参考一下吗

**Comment by PanJiaChen** [comment]
自己实现也不难吧

**Comment by linlinjava** [comment]
4.0会支持消息中心吗

**Comment by PanJiaChen** [comment]
4.0不会，之后的版本会增加这方面的demo。

**Comment by bi-kai** [comment]
iview-admin的消息中心挺不错的，希望element也能跟进，这是个很实用的功能。

**Comment by snowdream** [comment]
关注，需要这种功能。

**Comment by bi-kai** [comment]
一年半了，持续关注这个功能。
