### ISSUE TITLE
建议加上定时刷新的页面实例。项目太牛了，欣赏

### ISSUE THREAD

**Issue by seeyouguo** [PanJiaChen/vue-element-admin#867]
类似setTimeout的应用

**Comment by PanJiaChen** [comment]
加这个的意义是什么？有什么真实的业务场景么？

**Comment by seeyouguo** [comment]
Pan sann, 其实是有监控方面的应用。如果是监控页面，需要定时刷新，不能总是手动点击刷新。例如12306当前余票这种。thks

**Comment by PanJiaChen** [comment]
不就是一个轮训么

**Comment by seeyouguo** [comment]
是的。这个是太简单了么？之前做的有点问题，点都少次tab就会触发多少次轮训

**Comment by daiing** [comment]
用websocket吧

**Comment by PanJiaChen** [comment]
@seeyouguo 那是因为没有 `clearTimeout` 吧

**Comment by seeyouguo** [comment]
@PanJiaChen 好的。我重新试试，thks!
