### ISSUE TITLE
npm run dev 报404错误 项目启不了

### ISSUE THREAD

**Issue by QWK-001** [PanJiaChen/vue-element-admin#868]
Failed to load resource: the server responded with a status of 400 (Bad Request)
localhost/:1 

Refused to execute script from 'http://localhost:9527/%3C%=' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by QWK-001** [comment]
已解决 克隆项目会造成上述问题，直接下载包就ok了

**Comment by meizilove258** [comment]
你好，请问你的问题怎么解决的，谢谢！！

**Comment by QWK-001** [comment]
不能克隆到本地 会出现master报错 将项目包下载到本地即可




| |
前端求职简历--瞿伟康
邮箱：qwk_001@163.com
|

签名由 网易邮箱大师 定制

在2018年08月14日 11:36，meizilove258 写道：

你好，请问你的问题怎么解决的，谢谢！！

**Comment by meizilove258** [comment]
去是download下载的，同样的报错，跑不起来。

**Comment by meizilove258** [comment]
我是download下载的，同样的报错，跑不起来。
