### ISSUE TITLE
嵌套路由时，左侧菜单和页面左上角表现不一致

### ISSUE THREAD

**Issue by Alexis374** [PanJiaChen/vue-element-admin#869]
![image](https://user-images.githubusercontent.com/2499504/42730288-3629b2de-8824-11e8-8376-a1cde4d460b4.png)
点击menu 1-2时只是展开/关闭菜单，而在这里点击 menu  1-2会跳转页面，是不是表现不一致？
![image](https://user-images.githubusercontent.com/2499504/42730294-698c2210-8824-11e8-890a-e824aee02ae1.png)

**Comment by PanJiaChen** [comment]
本身面包屑和侧边栏功能和作用是就是有一些区别的。可以自己通过 `redirect` 来调整你想要的效果。
