### ISSUE TITLE
关于Vue-cli 引入非 npm 管理的第三方库文件的问题

### ISSUE THREAD

**Issue by my9074** [PanJiaChen/vue-element-admin#87]
你好~请问 我如果要引入几个非npm 管理的 js 库文件,放在哪里比较好？我看你是把 Blob.js 和Export2Excel.js 这样的库文件放在了 vendor 文件夹里。现在有个问题，我的这个库有可能不是 AMD或者cmd 的。并且eslint 一直报语法错误。请问有什么好的解决方案吗?

**Comment by PanJiaChen** [comment]
用script-loader 可以解决amd的问题
`/* eslint-disable */`  解决eslint的问题

**Comment by my9074** [comment]
@PanJiaChen eslint-disable 是不是把所有的语言校验都禁止了？我是想只忽略 vendor 文件夹下的。是不是在.eslintignore 文件里添加就好了?
script-loader  和 ProvidePlugin 有什么区别吗？

**Comment by PanJiaChen** [comment]
`/* eslint-disable */` 是当前文件，当然.eslintignore也是可以的
ProvidePlugin 作用类似注册到全局 你不用写任何import或者require 就可以用了
script-loader 主要是帮你挂载到window对象下 有一些细微的差别
但你ProvidePlugin注册了就不能按需加载，script-loader可以在我想用的时候在加载相关资源。
所以我项目中jquery用的是ProvidePlugin，而 Blob.js用的是script-loader
具体可以参考https://sebastianblade.com/how-to-import-unmodular-library-like-zepto/

**Comment by my9074** [comment]
@PanJiaChen /* eslint-disable */ 明白了。
ProvidePlugin 在非 node_modules 库下引用还是不行。这是我引入的方式:
<img width="195" alt="2017-06-20 2 38 51" src="https://user-images.githubusercontent.com/4555635/27320010-dd1ff24c-55c6-11e7-9dd2-82cf88d89f4d.png">
<img width="429" alt="2017-06-20 2 39 02" src="https://user-images.githubusercontent.com/4555635/27320018-e3194e8c-55c6-11e7-9374-d735f61ef51e.png">
<img width="1020" alt="2017-06-20 2 39 09" src="https://user-images.githubusercontent.com/4555635/27320024-e8246f4c-55c6-11e7-85cd-4f24ae9c41c8.png">

**Comment by PanJiaChen** [comment]
你这'./src' 路径肯定不对啊。。

**Comment by my9074** [comment]
应该指向什么目录呢？
而且我看Blob 的源码里是有 export default xxx 的，但是这个库没有，所以用 require('script-loader!vendor/hterm'); 貌似不好使

**Comment by PanJiaChen** [comment]
script-loader 就是帮你全局创建script 引入。。。。

**Comment by my9074** [comment]
能举个例子吗？ 用 ProvidePlugin 或者 script-loader 配置，研究了一下午也不行

**Comment by PanJiaChen** [comment]
这个项目里都有啊。。。

**Comment by my9074** [comment]
嗯， 看到了。但是你这个结构 static 和 src/vendor 都相当于存放第三方库的作用吧?

**Comment by PanJiaChen** [comment]
对。。。static是不打包的 直接external的， src/vendor还是会进行打包的

**Comment by my9074** [comment]
要不我把项目加你个权限，你帮我看下这个问题？

**Comment by my9074** [comment]
https://github.com/Dataman-Cloud/Elixir/invitations @PanJiaChen 试试能fork 么

**Comment by PanJiaChen** [comment]
不好意思不提供这种帮助
