### ISSUE TITLE
为什么不引入prettier和eslint-plugin-vue来保证代码风格和代码质量呢？

### ISSUE THREAD

**Issue by ghost** [PanJiaChen/vue-element-admin#870]
为什么不引入prettier和eslint-plugin-vue来保证代码风格和代码质量呢？

我在项目中引入eslint-plugin-vue还是爆了不少错误和警告。

**Comment by PanJiaChen** [comment]
因为之前 `prettier` 对 `vue` 和 `eslint` 的支持都不是特别好。

`eslint-plugin-vue`不使用的原因是之前尝试过，但发现它的可配置性不高。我之后会再调研一下新版本的情况的。

**Comment by PanJiaChen** [comment]
`eslint-plugin-vue` 已加入。

`prettier` 暂不考虑。意义不大。
