### ISSUE TITLE
有升级 webpack 4 的教程或者建议么？

### ISSUE THREAD

**Issue by Howie126313** [PanJiaChen/vue-element-admin#871]
最近打算新建个项目使用 webpack 4 有什么升级建议么？

**Comment by PanJiaChen** [comment]
Duplicate of #537

**Comment by Howie126313** [comment]
了解 多谢

**Comment by PanJiaChen** [comment]
你可以关注 https://github.com/PanJiaChen/vue-element-admin/pull/889

在测试几天，下周应该会发布合到master 顺便会在配合着升级一下 `vue-loader`
