### ISSUE TITLE
跨域配置问题请教

### ISSUE THREAD

**Issue by Tomatoo** [PanJiaChen/vue-element-admin#872]
开发模式下，vue element admin项目是9527端口，然后本地使用egg.js开了一个服务占用7002端口。我想把9527的某些请求代理刀7002端口去，所以设置了proxy代理，代码如下：

```
proxyTable: {
      '/api/login': {
        target: 'http://localhost:7002',
        changeOrigin: true,
      }
    },
```

发送请求的代码如下：

```
request({
    url: '/api/login',
    method: 'post',
    data
  });
```

这个调试了大半天了，控制台中一直显示404，这是错误堆栈：

![2018-07-16 4 24 33](https://user-images.githubusercontent.com/15502063/42748999-c6ceed9a-8914-11e8-9e1e-7572be9ca5e1.png)

我看了下webpack的配置文档，还有相关issue也没问题呀，所以我想问下问题可能出在哪里，谢谢～

**Comment by PanJiaChen** [comment]
``` js
request({
    url: '/api/login',
    method: 'post',
    data,
    baseURL: ''
  })
```

**Comment by Tomatoo** [comment]
太惭愧了，是使用egg.js没关闭csrf配置导致的~~
