### ISSUE TITLE
路由active的问题

### ISSUE THREAD

**Issue by itsmyturn** [PanJiaChen/vue-element-admin#873]
![image](https://user-images.githubusercontent.com/11573322/42753258-e9417952-8922-11e8-99fb-86df2fdb7809.png)

这是一级路由控制的，如果点击肥西风场后左侧的active还存在
![image](https://user-images.githubusercontent.com/11573322/42753285-ffa20888-8922-11e8-9f15-b4a85fa53dee.png)
下面这是路由配置代码
![image](https://user-images.githubusercontent.com/11573322/42753340-30b968ee-8923-11e8-8859-41e7aea2099f.png)
请大神指点

**Comment by PanJiaChen** [comment]
其实和 #864 类似。暂时不支持。

你需要自己动态设置 menu 的 `default-active`

**Comment by PanJiaChen** [comment]
Trace in  #864
