### ISSUE TITLE
session id 一致性问题

### ISSUE THREAD

**Issue by wangtianabc** [PanJiaChen/vue-element-admin#874]
const service = axios.create({
  baseURL: process.env.BASE_API, // api的base_url
  timeout: 5000, // request timeout
  withCredentials: true 
})
设置了withCredentials后，依然无法获取一致的sessionid

**Comment by PanJiaChen** [comment]
`sessionid` 是什么？存在哪里？

**Comment by wangtianabc** [comment]
1.解决了，把mock.js注释掉就可以了
2.sessionid 是web容器（tomcat）的会话ID
3.谢谢
