### ISSUE TITLE
upload-excel bug

### ISSUE THREAD

**Issue by mgbq** [PanJiaChen/vue-element-admin#877]
导入excel我选择了ppt文件，没有格式验证，控制台报错

**Comment by mgbq** [comment]
我是拖拽ppt文件

**Comment by mgbq** [comment]
已经解决代码如下,望大佬加上
` beforeUpload(file) {
      const isLt1M = file.size / 1024 / 1024 < 1
      const isExcel = /\.(xlsx|xls)$/.test(file.name)
      if (!isExcel) {
        this.$message.warning(
          '只能上传Excel格式文件'
        )
      }
      if (!isLt1M) {
        this.$message.warning(
          'Please do not upload files larger than 1m in size'
        )
      }
      return isLt1M && isLt1M
    },`

**Comment by PanJiaChen** [comment]
Fixed in #878
