### ISSUE TITLE
菜单显示错误

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#880]
当子菜单全部为 hidden: true，而中间某一个需要显示的情况下，菜单会显示错误，把第一个hidden: true的子菜单显示出来。

    {
    path: '/test,
    component: Layout,
    redirect: 'noredirect',
    meta: { title: test, icon: 'test' }, 
    children: [
      { path: 't1', component: () => import('@/views/test/index'), name: 't1', meta: { title: 't1', icon: 't1' }, hidden: true },
      { path: 't2', component: () => import('@/views/test/t2/index'), name: 't2', meta: { title: 't2', icon: 't2' }},
      { path: 't2/t21', component: () => import('@/views/test/t2/addPane'), name: 't21', meta: { title: 't21' }, hidden: true },
      { path: 't3', component: () => import('@/views/test/t3/index'), name: 't3', meta: { title: 't3', icon: 't3' }, hidden: true }
    ]
  }

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/e254fc6c1a034f5373d7e4abcf241a52aaef48c4
