### ISSUE TITLE
Chrome浏览器显示不完整，Safari浏览器上显示完整

### ISSUE THREAD

**Issue by 122687220** [PanJiaChen/vue-element-admin#881]
![wx20180717-165102](https://user-images.githubusercontent.com/35905503/42806783-cffe9a3c-89e1-11e8-9705-422a8f16ace7.png)
![wx20180717-165118](https://user-images.githubusercontent.com/35905503/42806802-d6dd7184-89e1-11e8-9ff6-2a74a8d9fb47.png)

**Comment by PanJiaChen** [comment]
没懂问题是什么？

**Comment by 122687220** [comment]
我运行项目后，分别在Safari和Chrome上打开，发现两个浏览器显示的效果不一样

**Comment by PanJiaChen** [comment]
没能重现，你是不是缩放页面了。
