### ISSUE TITLE
TreeTable的eval.js有bug

### ISSUE THREAD

**Issue by horizontung** [PanJiaChen/vue-element-admin#882]
![1531827248 1](https://user-images.githubusercontent.com/26265876/42814951-6a2eadca-89f8-11e8-9604-bc5ef90dbd1d.jpg)
会导致计算的结果一直在循环，具体如下：
![1531827376 1](https://user-images.githubusercontent.com/26265876/42815042-b344902e-89f8-11e8-99fe-641afa05e457.jpg)
可以考虑去掉parent中的children属性。我是这么解决的：
![1531827634 1](https://user-images.githubusercontent.com/26265876/42815191-4d23270a-89f9-11e8-8ac6-ef754806949f.jpg)
结果如下：
![1531827812 1](https://user-images.githubusercontent.com/26265876/42815374-c8d9af72-89f9-11e8-9187-193ec8482462.jpg)

customEval.js同理。

**Comment by horizontung** [comment]
@PanJiaChen 发现我的解决方案会造成[#695](https://github.com/PanJiaChen/vue-element-admin/issues/695)的问题，以前那种无穷嵌套的数据结构没有这种问题。😂😂😂
期待大神完善该功能。我自己也在看看有什么解决方法。
谢过😄

**Comment by PanJiaChen** [comment]
主要是 `tree-table`也不是我写的，我暂时在研究别的东西，可能一时半会也不会完善它。

我尽量抽空重新改一下吧。

**Comment by horizontung** [comment]
@PanJiaChen  感谢！这个bug虽然不影响组件的正常使用，但是数据的循环嵌套多少会对浏览器内存有影响。
先贴下我的解决方案吧，虽然不完美，但是能用，在大神没解决这个bug之前也许会给别的伙伴一个思路。
首先去掉eval.js中关于parent中的children属性的部分，如下：
![image](https://user-images.githubusercontent.com/26265876/42870430-6c68c82a-8aaa-11e8-9eb0-c9cbf5270215.png)
然后修改TreeTable中index.vue文件关于子元素显示的部分，如下：
![image](https://user-images.githubusercontent.com/26265876/42870650-f9695582-8aaa-11e8-8d2d-7bf307570219.png)

**Comment by PanJiaChen** [comment]
`element` 2.7.0 支持 `tree-tale 了`。所以 `vue-element-admin`就不再自己维护 `tree-table`了。
