### ISSUE TITLE
exportExcel如何实现导出筛选和排序后的数据？

### ISSUE THREAD

**Issue by pzhxguang** [PanJiaChen/vue-element-admin#883]
能否使用excel.export_json_to_excel导出筛选和排序后的数据？

**Comment by PanJiaChen** [comment]
你传入的数据是什么导出的数据就是什么。

**Comment by pzhxguang** [comment]
可能是我太菜,不知道怎么获取筛选和排序后的数据,使用 table的 :data="tableData"  的 this.tableData,不是筛选和排序后的数据

**Comment by PanJiaChen** [comment]
这是`element-ui`的问题。
