### ISSUE TITLE
Vuex module按需加载会增加吗？

### ISSUE THREAD

**Issue by bowencool** [PanJiaChen/vue-element-admin#884]
类似[这种](https://github.com/ant-design/ant-design-pro/blob/529dff86a6b57b2be88a28d69383c0b054e09e6c/src/common/router.js#L21)

**Comment by bowencool** [comment]
vuex官方好像也有支持[模块动态注册](https://vuex.vuejs.org/zh/guide/modules.html#%E6%A8%A1%E5%9D%97%E5%8A%A8%E6%80%81%E6%B3%A8%E5%86%8C)

**Comment by PanJiaChen** [comment]
官网已经有了，而且感觉一般需求也不太用得到。

**Comment by dielangsea** [comment]
大一点的项目我觉得还是将vuex模块化好一些，因为命名等问题也比较突出的，这里把getter抽出来确实很方便用。

**Comment by PanJiaChen** [comment]
4.0版本加入了命名空间，动态注册的需求，暂时不准备加入。
