### ISSUE TITLE
关于scss问题

### ISSUE THREAD

**Issue by yuanyuanyuan** [PanJiaChen/vue-element-admin#89]
你好,我看到`<style rel="stylesheet/scss" lang="scss" scoped>`使用了scss,但是npm安装的却是sass的loader,这是为什么呢?谢谢

**Comment by PanJiaChen** [comment]
https://github.com/webpack-contrib/sass-loader
两个是一个loader
sass 和scss 是差不多的。只是scss 更加的类css 我更喜欢用scss 个人喜好

**Comment by yuanyuanyuan** [comment]
谢谢

**Comment by ZhuRuiHeng** [comment]
你好，我看到module里边没有配置sass-loader，package.js里边有sass-loader版本，请问无需在webpack.base.conf.js文件module里边配置loader也可以吗

**Comment by PanJiaChen** [comment]
@ZhuRuiHeng https://github.com/PanJiaChen/vue-element-admin/blob/master/build/utils.js
在这里
