### ISSUE TITLE
What does "This project is positioned as a background integration solution and is not suitable for secondary development as a basic template." mean?

### ISSUE THREAD

**Issue by carlosriveros** [PanJiaChen/vue-element-admin#891]
The text: 

"This project is positioned as a background integration solution and is not suitable for secondary development as a basic template."

on the ReadMe is not very clear. What does it mean?

**Comment by PanJiaChen** [comment]
This project have many features that you can't use, so it is not recommended to develop on the basis of this project.

You can develop on the basis of [vueAdmin-template](https://github.com/PanJiaChen/vueAdmin-template) .

**Comment by mrns** [comment]
Hi, sorry but I have the same question. I want to build an admin using several of the features this project contains such as the general admin style Layout, Login, Logout, Permissions, Charts, I18n, TinyMCE, Dropzone, etc.

The template you refer too is minimal and does not have many of these features. Maybe the phrase "background integration solution" has a specific meaning for you and it would be a good idea to re-phrase it. If you provide more details about what it means for you I can suggest some alternatives.

Thanks for your work! I will be glad to donate to this project once I start using it!
