### ISSUE TITLE
webpack配置相关文章

### ISSUE THREAD

**Issue by itsmyturn** [PanJiaChen/vue-element-admin#893]
大神有没有写过此项目webpack配置的相关文章，想了解一下设计思路

**Comment by PanJiaChen** [comment]
暂时没有，最近应该会写一个webpack4的文章。

**Comment by itsmyturn** [comment]
期待，webpack4基础的文章太多了，建议您把这个项目的webpack配置思路讲讲，这样应该对于大多数人实战都是一个提升

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/webpack.html
