### ISSUE TITLE
Admin-Token should not be stored in Cookie

### ISSUE THREAD

**Issue by jinweijie** [PanJiaChen/vue-element-admin#898]
Hi Jia Chen,

First, thanks for the great template. Regarding to the security part, the Admin-Token is stored in the Cookie and not marked as  http only and there's no XSRF check implemented in the template. This may caused XSRF attack.

My suggestion is to store the token in the localStorage and use Cookie to control the expiration of the localStorage token.

P.S. I knew that many people would say about XSS attack because js may read the token from localStorage. But since the token in the Cookie is not marked as http only, for this scenario, it's same. To eliminate XSS attck in the SPA application, vue already helped to sterilize the html output. Also we can use CSP (content security policy) to reduce the risk.

Thanks.

**Comment by PanJiaChen** [comment]
I don't think it is necessary to do this. Only through the front end can not prevent `csrf`.

**Comment by jinweijie** [comment]
CSRF can be prevented if the token not stored in Cookie.

Thanks.

**Comment by jinweijie** [comment]
Example: one application user receive an email containing some malicious link, the user click that link, in the page of that link, a post will be triggered to the application. e.g. sendMoneyTo hack@hack.com. since the user has already logon the application, and CSRF token is not implemented in the application(that's another option to solve the CSRF), the cookie will be carried with that malicious post and the post action will be success.

But if the access token (Admin-Token here) is not stored in the cookie, instead, instead, stored in the localStorage, and set as bearer token during the http calls. Even CSRF-Token is not implemented, the malicious post will not be success. Actually implement CSRF-Token is a little bit tricky in SPA.

Anyway, just FYI. You may close this issue if you don't think this is an issue.

Thanks for your time.

**Comment by PanJiaChen** [comment]
What you said is true, but the verification of this project is judged by the http token, so there is no problem you mentioned.

https://github.com/PanJiaChen/vue-element-admin/blob/8851a6806634a047de3e1f6ea368caceee07efe4/src/utils/request.js#L17

**Comment by jinweijie** [comment]
Agreed there won't be `csrf` if back-end implement properly not using Cookie for permission check.

Thanks for the reply and have a nice day!
