### ISSUE TITLE
能贴一下关于那个懒加载的_import的代码吗

### ISSUE THREAD

**Issue by Caijt** [PanJiaChen/vue-element-admin#899]
我在项目里一直找不到关于那个生产环境就懒加载、调试环境就不使用懒加载的_import的代码
我自己写一个，一直报错
let _import = (a)=>{
  let isProduction = process.env.NODE_ENV === 'production'
   if(isProduction){
    return () => import(a)
   }else{
     return require(a)
   }
}

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/advanced/lazy-loading.html#%E6%96%B0%E6%96%B9%E6%A1%88

建议使用新方案。

或者你可以参照 [_import](https://github.com/PanJiaChen/vue-element-admin/tree/tag/2.x.x/src/router)
