### ISSUE TITLE
富文本问题

### ISSUE THREAD

**Issue by ROSEMUSE** [PanJiaChen/vue-element-admin#901]
富文本复制一段表格显示失败，还有复制一段带颜色的字体也会显示失败：
![image](https://user-images.githubusercontent.com/32162134/43054825-01b91ab0-8e66-11e8-94d2-0ad796b58c3e.png)
原始样式：
![image](https://user-images.githubusercontent.com/32162134/43054835-0bc63cd6-8e66-11e8-98fc-0f126a583497.png)
![image](https://user-images.githubusercontent.com/32162134/43054845-1367214e-8e66-11e8-8702-235d07f023e6.png)

**Comment by PanJiaChen** [comment]
[powerpaste](https://go.tinymce.com/powerpaste/) 了解一下。它是付费插件。反正你想如何用它自己想办法吧。

**Comment by ROSEMUSE** [comment]
除了用这插件没有别的好办法了吗，或者有没有推荐另外比较好用的富文本，大神

**Comment by PanJiaChen** [comment]
除了这个这个插件没办法。

其它富文本参照[文档](https://panjiachen.github.io/vue-element-admin-site/zh/component/rich-editor.html)
