### ISSUE TITLE
无关项目， input的focus 问题

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#902]
input 中按键盘上键时效果，如何保证始终处于focus状态？
代码如下：
https://jsfiddle.net/tk37c5cb/111/

**Comment by moonose** [comment]
在该列某行的input中，按键盘下移或者下移键，input输入框可以实现在该列里的自由移动，且每次移动input都是出于focus状态

**Comment by PanJiaChen** [comment]
这个需求也太和自己的业务相关了吧。。。

https://panjiachen.github.io/vue-element-admin/#/table/inline-edit-table

其实和内联table原理差不多的，你只是加了一个键盘控制。

**Comment by moonose** [comment]
是啊，所以标题是和本项目无关。。^___^
主要是input的focus的问题，一直聚焦不到，郁闷

**Comment by moonose** [comment]
@PanJiaChen 
潘神，有个小问题，关于表格里撤销的实现，我把结果赋给 this.list 的同时，又给了this.originallist，
当点击撤销按钮时，获取所在行index，然后把相对应的 originallist赋还给 list。 代码如下：
https://jsfiddle.net/L8zdcasb/14/

问题是，每次表格修改后 originallist 对应的值竟然也会改变， 我的table 绑定 :data="list" 又不是originallist，怎么会originallist也一起改变？

请教下~
