### ISSUE TITLE
通过操作DOM高亮侧边栏，

### ISSUE THREAD

**Issue by leeycode** [PanJiaChen/vue-element-admin#903]
您好，我通过操作dom的方式，在侧边栏实现高亮，但是点击收缩侧边栏，再打开的时候类名就丢失了，请问这是什么原因呢？
进入页面高亮侧边栏：
mounted () { document.getElementById('account').classList.add('nav-active'); },
![1](https://user-images.githubusercontent.com/20038428/43113361-a7193898-8f2c-11e8-97df-193f9d323620.png)

点击导航栏的收缩侧边栏按钮然后再展开：
![2](https://user-images.githubusercontent.com/20038428/43113367-ad300f54-8f2c-11e8-9f7d-bb11a9c1cc15.png)

发现之前添加的类名丢失，请问这是什么原因呢？

**Comment by PanJiaChen** [comment]
这是 element-ui 的问题。
请求 element-ui 提问。
