### ISSUE TITLE
如何调用自己开发时的后台接口来渲染数据

### ISSUE THREAD

**Issue by rouyuanfang** [PanJiaChen/vue-element-admin#904]
我的思路是：
1.config文件夹下修改 BASE_API，即：https://313cm.cn/181-realestate-manage-web
2.然后在api下的article.js发送异步请求，即：
export function userList(query) {
  return request({ url: '/manage/user/list', method: 'post', params: query })
}
3.接下来在相应的页面发送请求
**但是一直就是Network Error**，请求大神帮忙解决

**Comment by PanJiaChen** [comment]
请用正确的姿势提问。
先关闭了。
待重新提供详细信息之后再打开。
