### ISSUE TITLE
Notification 通知组件，点击多次后，不能正常关闭

### ISSUE THREAD

**Issue by SamoZ** [PanJiaChen/vue-element-admin#907]
https://jsfiddle.net/ojLvtu6h/33/
demo如上，多次点击后，通知组件无法正常关闭，请指教

**Comment by axhello** [comment]
@SamoZ 实测demo可以啊，你是说点了不会自动关闭么？

**Comment by SamoZ** [comment]
@axhello  不好意思，没说清楚，我写的是点击字进行关闭，当出现多次提示消息，点击字就不能关闭了

**Comment by SamoZ** [comment]
@axhello 多谢多谢
