### ISSUE TITLE
点击左侧菜单menu想从menu传参数给对应页面

### ISSUE THREAD

**Issue by pl2476** [PanJiaChen/vue-element-admin#91]
请问怎么实现

**Comment by PanJiaChen** [comment]
看vue-router  咯
https://router.vuejs.org/zh-cn/essentials/named-routes.html

**Comment by pl2476** [comment]
楼主的路由动态渲染的，route-link :to 不能一个个的绑定参数，请问怎么实现？比如我点击动态table菜单，我想传一个参数给动态table这个组件

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/router/index.js#L210
https://segmentfault.com/a/1190000009762198#articleHeader17
把meta 缓存params应该就满足你的需求了

**Comment by pl2476** [comment]
首先感谢楼主，非常感谢，然后告诉楼主感觉是一个bug，我试过parmas和query很多次都没有用，但是meta居然可以，多谢楼主提示，不然我都不会去尝试meta，希望楼主能搞清楚再告诉我们，或者我改动其他地方太多导致params不行的

**Comment by PanJiaChen** [comment]
不好意思误导了你 params是不行的，`article/edit/:id` :id是params 所以不能显示的声明
我觉得meta已经可以满足你的需求了

**Comment by mishengqiang** [comment]
我认为使用Vue Router的[props特性](https://router.vuejs.org/zh/guide/essentials/passing-props.html)更好一些。
