### ISSUE TITLE
request failed with status code 404

### ISSUE THREAD

**Issue by rouyuanfang** [PanJiaChen/vue-element-admin#912]
把import Mock from './mock' 注释掉还是无法获取后台数据

**Comment by PanJiaChen** [comment]
请用正确的姿势提问。
先关闭了。
待重新提供详细信息之后再打开。

**Comment by Androidzwl** [comment]
hello,我在参考您代码做一个登陆功能的时候也遇到了404这个报错，请问这个是什么原因呢？请大神指点一下
