### ISSUE TITLE
build后 打开index.html无法登录 

### ISSUE THREAD

**Issue by bloodspasm** [PanJiaChen/vue-element-admin#916]
![2018-07-26 7 47 02](https://user-images.githubusercontent.com/10420472/43260757-f1a4ce5e-910c-11e8-832d-f3605eaccb63.png)
正常的dev是没有问题的
请问一下,没有后台服务想build运行不知道行不行 ,现在无法登录 如果想想跳过登录要怎么操作呢?

**Comment by PanJiaChen** [comment]
你本地直接打开`index.html`的吧？ 这样`cookie`是无效的。你需要随便启一个服务就可以了。

**Comment by syhcgo** [comment]
随便启动一个服务指的是什么？望前辈指点
