### ISSUE TITLE
怎么才能在request.js进行路由跳转呢

### ISSUE THREAD

**Issue by powhd** [PanJiaChen/vue-element-admin#918]
我想在request.js里面response返回code的时候进行判断，没有权限就跳转。请问作者有解决办法吗

**Comment by PanJiaChen** [comment]
```js
import router from './router'
....
router.push('xxx')
```

**Comment by powhd** [comment]
import router from './router'
console.log(router)  //undefined

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/router/index.js#L67

结合自己项目改，看你哪里 `export default new Router`的

**Comment by powhd** [comment]
我在permission.js中能把router引进来,但是request.js是undefined,模版是采用您提供的vueAdmin-template基础开发的
