### ISSUE TITLE
主页左上方 能否加一个系统名称的占位，支持折叠

### ISSUE THREAD

**Issue by a304885433** [PanJiaChen/vue-element-admin#919]
如题。
另外首页的tab标签，操作起来有点问题，可被关闭，然后依然会显示首页，建议是首页标签，不可被关闭。

**Comment by moonose** [comment]
@a304885433  
https://github.com/mgbq/nx-admin   这有个占位，可以借鉴下，不过布局来说应该如下

Bar 区域
——————————
  菜    |
  单    |     主显示区域
  区    |
  域    |

这样Logo可以始终居于左上方，而不是
          |  bar 区域
  菜    |-----------------------  
  单    |     主显示区域
  区    |
  域    |

**Comment by PanJiaChen** [comment]
tab 问题已修复。
logo 关注 https://github.com/PanJiaChen/vue-element-admin/issues/1042
