### ISSUE TITLE
可以加个 <紧凑> 模式布局吗?

### ISSUE THREAD

**Issue by vmvz** [PanJiaChen/vue-element-admin#920]
目前后台风格, 属于比较舒服的布局, 但是对于客户来说, 有些时候需要紧凑模式来显示更多数据.

可以多加一个模式吗?  (自己一点一点改,也不方便升级)

类似于iview-admin (我们这个比iview-admin更赞)

**Comment by PanJiaChen** [comment]
紧凑模式是什么？那稍微在具体一点么？

**Comment by vmvz** [comment]
iview-admin 打不开, 晚点我截图说明一下.

**Comment by daiing** [comment]
确实，表格单元格和各个元素的布局有点空隙太大，界面显示的数据量太小

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1024
