### ISSUE TITLE
[Feature Request] 打开新页面的 tab 栏支持批量左右滚动

### ISSUE THREAD

**Issue by xkcoding** [PanJiaChen/vue-element-admin#922]
现在看，当打开很多个页面的时候，tab 页面会被置于最左侧，，建议增加左右导向按钮

**Comment by PanJiaChen** [comment]
但支持滚动的。

**Comment by xkcoding** [comment]
@PanJiaChen Mac 下可以通过触摸板或者鼠标横向滚动，但是 windows 下，是出现滚动条吗？还是说其他形式?
建议增加左右导向按钮，类似下图
![image](https://user-images.githubusercontent.com/10429917/43380849-2fde631a-9405-11e8-9abf-5cf8ea0eb3b8.png)

**Comment by PanJiaChen** [comment]
这种略丑，我之后加上滚动条吧。

**Comment by xkcoding** [comment]
@PanJiaChen 那样也行~thanks

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/995

**Comment by xkcoding** [comment]
线上地址已经有了吗？？
