### ISSUE TITLE
子菜单roles问题

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#924]
子菜单在meta里 设置 roles后，对于没有权限的角色依旧可见，感觉应该隐藏掉

**Comment by PanJiaChen** [comment]
未能重现你的问题，你是拿`admin`权限账户测试的吧？`admin`默认能看见所以页面。

**Comment by moonose** [comment]
不会啊，例如如下代码：

    export const constantRouterMap = [
          。。。
       {   path: '/outting', component: Layout, redirect: 'noredirect',  meta: { title: 'outting', icon: 'outting' },
            children: [
            { path: 'register', component: () => import('@/views/outting/register'), name: 'signup', meta: { title: 'register', icon: 'register', noCache: true }},
            { path: 'manage', component: () => import('@/views/outting/manage'), name: 'manage', meta: { title: 'manage', icon: 'manage', roles: ['ZI', 'ZI-PA'] }}
           ]
       },

登录后我的roles 是ZI-P， 但该子菜单还是显示，但点击后会说没权限。

**Comment by moonose** [comment]
应该是吧，你老每个Commits 我都没错过啊。。。。
sidebar 目录下的两个文件比较了下，都是一致～

**Comment by moonose** [comment]
找到原因了，是放在 constantRouterMap 里才会这样。

但如果 移入asyncRouterMap，因为下面只有一个子菜单，父菜单又不会显示。～～就先这样吧

**Comment by PanJiaChen** [comment]
你自行查看文档，`alwaysShow: true `
