### ISSUE TITLE
Chrome 登陆界面 input 背景问题

### ISSUE THREAD

**Issue by xiaotiandada** [PanJiaChen/vue-element-admin#925]
### 因为找不到地方反馈 只能开一个issues ~

Chrome 登陆界面 用户名的input 记住密码之后 变黄的问题已经被处理了

但是我发现 处理之后的颜色和背景不一致 便显示有一丝丝不协调

目前的rgb值是 #2d3a4b

修改的rgb值是 #283443

完美！~

> 虽然只是一个小问题 但是还是开了 issues (希望大佬们不要打我2333~~

**Comment by PanJiaChen** [comment]
。。。。很严谨！

欢迎提一个pr~

**Comment by PanJiaChen** [comment]
#927

**Comment by suser007** [comment]
What
