### ISSUE TITLE
请问下怎么权限配置不管用了！

### ISSUE THREAD

**Issue by wlLeblanc** [PanJiaChen/vue-element-admin#928]
![image](https://user-images.githubusercontent.com/22288871/43496929-83be6a66-9572-11e8-99b5-9fb9713ee5e2.png)
我用的admin登录的！

**Comment by PanJiaChen** [comment]
`admin`具有所以页面权限。

https://github.com/PanJiaChen/vue-element-admin/blob/48a966fe1cdd676d468ba543f2703a5bfcbf07bf/src/permission.js#L12

可自行修改。
