### ISSUE TITLE
你好，我遇的问题：只能渲染一级路由，子路由没有效果无法渲染

### ISSUE THREAD

**Issue by sunlanlisa** [PanJiaChen/vue-element-admin#93]
我在你的基础上去掉了layout菜单，然后router中的一级路由是生效的，二级路由不生效，无法渲染出来。求大神帮忙
import Vue from 'vue';
import Router from 'vue-router';
Vue.use(Router);

export default new Router({
    mode: 'history', //后端支持可开
    scrollBehavior: () => ({y: 0}),
    routes: [
        {
            path: '/loan',
            redirect: '/loan/index',
            meta: { title: '惠人贷申请' },
            name: '惠人贷申请',
            children: [
                { path: 'index', component: resolve => require(['../views/loan/apply'], resolve),meta: { title: '惠人贷申请' }, name: '惠人贷申请 ' },
                {
                    path: 'locallist',
                    component: resolve => require(['../views/loan/localList'], resolve),
                    meta: { title: '申请进度查询' },
                    name: '申请进度查询'
                },
            ]
        },
    ]
});

我就直接这么简单写的
但是二级路由出不来

**Comment by PanJiaChen** [comment]
你`router-view`写了没

**Comment by sunlanlisa** [comment]
写了的。一级路由都没有问题的

**Comment by sunlanlisa** [comment]
主要我也不知道怎么调试它，也没有任何报错，就空白

**Comment by PanJiaChen** [comment]
二级路由所以叫要写两个`router-view`啊

**Comment by sunlanlisa** [comment]
明白啦。已经好啊。。。犯了低级错误😁~~@PanJiaChen，谢谢你~
