### ISSUE TITLE
用Tinymce编辑的内容，在其它页面应该如何去显示？

### ISSUE THREAD

**Issue by VanLiuZhi** [PanJiaChen/vue-element-admin#933]
我编辑了一些内容，包括插入一些代码。我把富文本的内容保存了，在其它页面显示，发现丢失了很多样式，这个富文本的内容，要想完全显示，只能把内容做为值，设置到tinymce 组件上 。
这样Tinymce组件只能编辑，脱离组件无法显示（样式不全），有没有什么好的方案能把编辑的富文本内容原样在其它页面展示出来？

**Comment by VanLiuZhi** [comment]
把content.min.css引入还是不行，由组件生成的富文本内容，对于插入的代码样式，只处理成这样
`<pre class="language-python">`  就是加了个class 后面就是字符串了，只靠引入css没有效果。而且看组件编辑器内的内容，pre标签被渲染成了`<pre class="language-python" contenteditable="false" data-mce-selected="1">` 后面也不再是字符串，而是更多的便签。
应该不只是css，更多的是js来操作的，您有在项目中用这样的方式去处理富文本吗？
我觉得有两个思路：
1.  把组件复用出来，看看能不能裁剪掉只剩能编辑的内容，这样表现为把数据给到组件，帮你渲染回原来的样子
2.  放弃这样的思路，把内容用v-html直接输出，样式无法满意的再做进一步处理。

**Comment by PanJiaChen** [comment]
我不是很理解你的问题？你是指 富文本里面插入代码块的时候 css有问题？

**Comment by VanLiuZhi** [comment]
可能我表述的不是很清楚。就是现在使用框架的Tinymce组件编辑了一些内容，这些内容里面包含了一些代码片段，在富文本编辑器里面，这些代码片段是高亮的。
把编辑好的内容拿出来，在其它页面用类似<div v-html=content></div>把富文本内容输出，大部分样式都丢失了，尤其是代码高亮部分。
我看到您回答把富文本编辑器的content.min.css样式引入就可以了，但是我测试了不行，因为您这么说我就想问下您是不是有在项目中有用这样的解决方案？

我通过浏览器的审查元素，查看组件编辑器里面的内容，假设我插入了这么一段代码
function a(){return 'hi'}
它大概会被渲染成类似这样的：
`<pre class="language-javascript" contenteditable="false" data-mce-selected="1"><span class="token keyword">function</span> <span class="token function">a</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
<span class="token keyword">return</span> <span class="token string">'hi'</span>
<span class="token punctuation">}</span></pre>
`
而我保存出来的内容是这样的
`<pre class="language-javascript"><code>function a(){
return 'hi'
}</code></pre>`
我把保存的内容在其它页面展示，理所当然丢失了样式，但是两个差距这么大不是引入一个css文件就能解决的了的吧？

**Comment by PanJiaChen** [comment]
https://www.tiny.cloud/docs/plugins/codesample/

需要自己使用 [Prism](https://prismjs.com/) 解析

**Comment by VanLiuZhi** [comment]
稍微看了下，这个Prism应该是Tinymce内部用来解析代码的了。那思路和我现在用的第三方插件hightlight.js差不多。因为第一次用富文本，给我一种管杀不管埋的感觉，而且我查到一些资料都是拿第三方插件去高亮代码的。
我的理想情况应该是这个组件还要有个展示的功能，把编辑的内容做为参数传递进去，把内容原样展示出来，现在好多富文本插件都不管展示的。
还是感谢作者的回答，还特意去查了资料。

**Comment by Valar103769** [comment]
> [tinymce/tinymce#4129](https://github.com/tinymce/tinymce/issues/4129)

你好, 在展示页面, 引入了https://github.com/PanJiaChen/vue-element-admin/blob/master/static/tinymce4.7.5/skins/lightgray/content.min.css,但是会跟展示页其他的.css发生样式冲突,请问除了iframe的方法,有其他好的解决方法吗?tinymce编辑器使用的是tinymce-vue,展示页面使用jquery

**Comment by Pelletling** [comment]
大佬请问这个问题您现在有解决吗？我在使用过程中也碰到了一模一样的问题

**Comment by chuswang** [comment]
> 大佬请问这个问题您现在有解决吗？我在使用过程中也碰到了一模一样的问题

我查看了一下preview的时候iframe引入的css，发现  在其他页面如果想要和编辑器渲染的样式差不多，引入 

`<link  rel="stylesheet" type="text/css" crossorigin="anonymous" href="//www.tiny.cloud/css/codepen.min.css">`

 这个css样式就行了   也可以把这个css样式下载到本地使用。

**Comment by madneal** [comment]
这个问题解决了吗，我尝试直接在index.html 直接引入 prism.js 和 prism.css，但是代码还是没有高亮

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="icon" href="<%= BASE_URL %>favicon.ico">
    <title><%= webpackConfig.name %></title>
    <link href="https://cdn.bootcdn.net/ajax/libs/prism/9000.0.1/themes/prism.css" rel="stylesheet">
    <script src="https://www.jsdelivr.com/package/npm/prismjs"></script>
  </head>
  <body>
    <div id="app"></div>
    <!-- built files will be auto injected -->
  </body>
</html>
```
