### ISSUE TITLE
大神，下载你的模板进行开发，怎么把你的mock关掉进行自己的接口渲染

### ISSUE THREAD

**Issue by rouyuanfang** [PanJiaChen/vue-element-admin#934]

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/mock-api.html#easy-mock

**Comment by rouyuanfang** [comment]
![image](https://user-images.githubusercontent.com/34623199/43717012-b54834e6-99b8-11e8-89c0-9c9459370a69.png)

**Comment by rouyuanfang** [comment]
大神，冒昧的问下你说的那个方法之前试过，删掉了就这样了

**Comment by PanJiaChen** [comment]
你去除了mock，当然要自己提供server。
