### ISSUE TITLE
左侧导航菜单收缩展开时卡顿

### ISSUE THREAD

**Issue by shz8** [PanJiaChen/vue-element-admin#937]
左侧导航菜单收缩展开时卡顿，是什么问题。换了几台电脑都有轻微卡顿。大家有没有遇到过，求答，多谢~

**Comment by shz8** [comment]
https://www.useloom.com/share/aaef5624aac5406d819a65db68127dea
录屏地址，谢谢~

**Comment by PanJiaChen** [comment]
谢谢你的反馈，你试过在其它页面收缩侧边栏吗？比如文档页面？

**Comment by shz8** [comment]
嗯，刚试了一下，都有些卡顿。

**Comment by moonose** [comment]
是有这样的卡顿，可以接受吧

**Comment by Leega0** [comment]
最后解决了吗，我发现这种情况一般出现在复杂页面，比如右侧有地图组件（高德有百度没有）和大量echarts，

**Comment by crazy1221** [comment]
其实，我认为这里这个属性还不如不要，体验不是很好。
![Uploading image.png…]()

**Comment by PanJiaChen** [comment]
在页面布局复制的情形下，的确有些卡。

之后着重优化一下吧。

**Comment by 2410655661** [comment]
我也碰到这个问题了，尝试将collapse-transition改为false就ok了

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1690

**Comment by 351699382** [comment]
我的也出现了，有什么办法解决

**Comment by xuyangqiao** [comment]
改成了false也很卡。

**Comment by femaimi9527** [comment]
> 
> 
> 左侧导航菜单收缩展开时卡顿，是什么问题。换了几台电脑都有轻微卡顿。大家有没有遇到过，求答，多谢~

我也是。。firefox ，chrome 浏览器都是这个情况

**Comment by ansonhorse** [comment]
可以把layout相关的transition去掉，虽然没了动画有时候会比较生硬，但是比起卡顿，舒服多了。
据我观察，影响最大的是`.main-container`的transition，开头还以为是里面的el-table渲染有问题。

**Comment by queenlixiaoman** [comment]
> 可以把layout相关的transition去掉，虽然没了动画有时候会比较生硬，但是比起卡顿，舒服多了。
> 据我观察，影响最大的是`.main-container`的transition，开头还以为是里面的el-table渲染有问题。

您好，最后您怎么改的啊？

**Comment by zhihuifanqiechaodan** [comment]
请问解决方案是什么。。问题关掉了。

**Comment by ansonhorse** [comment]
> > 可以把layout相关的transition去掉，虽然没了动画有时候会比较生硬，但是比起卡顿，舒服多了。
> > 据我观察，影响最大的是`.main-container`的transition，开头还以为是里面的el-table渲染有问题。
> 
> 您好，最后您怎么改的啊？

说明一下，去掉`transition`是我可以接受的解决方案，如果需要动画的，这方案就不合适。
至于怎么改，全局搜一下代码里的`transition`，没多少个的。

**Comment by ppp453** [comment]
我也遇到了，页面上展示的内容一多就卡。

**Comment by lizeze** [comment]
设置  `collapse-transition = "false"`

然后给侧边栏添加自定义 动画

```
.el-aside {
 
  transition: width 0.15s;
  -webkit-transition: width 0.15s;
  -moz-transition: width 0.15s;
  -webkit-transition: width 0.15s;
  -o-transition: width 0.15s;
}
```
