### ISSUE TITLE
新增tab时的一个问题?

### ISSUE THREAD

**Issue by weiwenhao** [PanJiaChen/vue-element-admin#938]
![image](https://user-images.githubusercontent.com/24819514/43749786-1cccafb0-9a28-11e8-976d-71a8f896efe5.png)

### 组件结构

```javascript

<order-show>
  <order-amount/>
</order-show>

```
### 问题

当我再次点order-show新增一个tab时, 我的前两个order show tab 中的order-amount组件会被重新挂载并调用组件内的mounted方法. 且props中传入的数据都属于当前点击的show的data.

> 我喜欢在组件的mounted方法中去fetch/handle我的数据.不知道这是什么原因产生的.

我希望我三个order-show中的order-amount是互相独立,互不影响的

### 补充

当我新增order-show时.前面已经打开的order-show不会被重新挂载,但是其子组件却被重新挂载了

**Comment by PanJiaChen** [comment]
首先明确一下 你的几个 `order show`路由path是否一致？ 一样的情况下并不会创建新的实例而是复用。

**Comment by weiwenhao** [comment]
@PanJiaChen 
![image](https://user-images.githubusercontent.com/24819514/43751706-9086026e-9a30-11e8-8c2c-73090dbce3a4.png)
这是我的order show.
 但是这并不是复用. 比如我有三个order show的时候 其实是存在三个order amount(每个order show下一个order amount).

问题是,我打开的第三个 order show是, 我其他order show下的order amount也被重新挂载了一次.
导致我使用tab切换order show时, 我每个order show 下的order amount的数据是一样的.

**Comment by PanJiaChen** [comment]
这是vue的问题，https://juejin.im/post/59097cd7a22b9d0065fb61d2#heading-16

https://github.com/PanJiaChen/vue-element-admin/blob/fe190b61884b6570d4b6e65d064186bc16a861a3/src/views/layout/components/AppMain.vue#L19

**Comment by weiwenhao** [comment]
终于解决了.是我自己的问题
我在order_show的计算属性中调用了this.$route.params.number
导致我的路由变化时.所有的order-show的计算属性都被重新计算(无论激活与否)

感谢comment!

**Comment by jade-liu** [comment]
你好，我也是通过路由跳转新增Tab
![image](https://user-images.githubusercontent.com/48787871/116543928-11a56900-a921-11eb-8d4e-b3616a36d5c7.png)
![image](https://user-images.githubusercontent.com/48787871/116544222-6cd75b80-a921-11eb-958c-8a8ca768ee06.png)
但是通过这种方式，每次点新增都用的是一个组件，不会重新创建组件。请问你是怎么解决的这个问题呀
