### ISSUE TITLE
我这里是后台动态加载菜单路径，但每次刷新整个页面，都会重定向到登录页面

### ISSUE THREAD

**Issue by hjx5309** [PanJiaChen/vue-element-admin#939]
//后台路由处理函数
export function handPath(path) {
  var menusList = []
  for (let i = 0; i < path.length; i++) {
    var obj = {
      path: '/',
      component: Layout,
      redirect: '/' + path[i].children[0].url.split('.')[0],
      name: path[i].name,
      hidden: false,
      meta: { title: path[i].name, icon: 'example' },
      children: []
    }
    for (let j = 0; j < path[i].children.length; j++) {
      var pathObj = {
        path: path[i].children[j].url.split('.')[0],
        meta: { title: path[i].children[j].name, icon: 'table' },
        component: () => import(`@/views/` + path[i].children[j].url.split('.')[0])
      }
      obj.children.push(pathObj)
    }
    menusList.push(obj)
  }
  return menusList
}
//路由处理代码
router.beforeEach((to, from, next) => {
  NProgress.start()
  console.log('登录', getToken())
//发现只有在重新刷新后，token就消失了，不刷新的话，token就还存在，请求是正常返回
  if (getToken()) {
    if (to.path === '/login') {
      next({ path: '/' })
    } else {
      if (store.getters.path.length === 0) {
        store.dispatch('FedLogOut').then(() => {
          Message.error('验证失败,请重新登录')
          next({ path: '/login' })
        })
      } else {
        next()
      }
    }
  } else {
    console.log('没有登录')
    if (whiteList.indexOf(to.path) !== -1) {
      next()
    } else {
      next('/login')
      NProgress.done()
    }
  }
})

**Comment by PanJiaChen** [comment]
刷新页面需要重新从cookie里面获取用户信息，重新登录。

https://github.com/PanJiaChen/vue-element-admin/blob/fe190b61884b6570d4b6e65d064186bc16a861a3/src/permission.js#L28

**Comment by hjx5309** [comment]
**我按照您的方法，老是死循环**
// store.js
 Login({ commit }, userInfo) {
      const username = userInfo.account.trim()
      return new Promise((resolve, reject) => {
        login(username, userInfo.password).then(response => {
          const data = response.data
          commit('SET_TOKEN', getToken())
          commit('SET_NAME', data.name)
          commit('SET_ROLES', data.userType)
          const userMenus = handPath(data.userMenus)
          //设置路径缓存
          localStorage.setItem('menus', JSON.stringify(userMenus))
          commit('SET_PATH', userMenus)
          resolve()
        }).catch(error => {
          reject(error)
        })
      })
    },

    // 获取路径信息
    GetMenu({ commit, state }) {
      return new Promise((resolve, reject) => {
        var menu = localStorage.getItem('menus')
        if (menu) {
          resolve(JSON.parse(menu))
        } else {
          reject(new Error('无路由'))
      })
    },

// permission.js
router.beforeEach((to, from, next) => {
  NProgress.start()
  if (getToken()) {
    if (to.path === '/login') {
      next({ path: '/' })
    } else {
      if (store.getters.path.length === 0) {
        store.dispatch('GetMenu').then(res => { // 拉取info
          router.addRoutes(res.concat([{ path: '*', redirect: '/404', hidden: true }])) // 动态添加可访问路由表
          next({ ...to, replace: true }) // hack方法 确保addRoutes已完成
        }).catch(() => {
          store.dispatch('FedLogOut').then(() => {
            Message.error('Verification failed, please login again')
            next({ path: '/login' })
          })
        })
      } else {
        next()
      }
    }
  } else {
    console.log('没有登录')
    if (whiteList.indexOf(to.path) !== -1) {
      next()
    } else {
      next('/login')
      NProgress.done()
    }
  }
})

router.afterEach(() => {
  NProgress.done() // 结束Progress
})

**Comment by ajjing** [comment]
死循环的问题，可能是store.getters.roles.length一直为0，addRouters阶段没有手动把roles存到store里。

**Comment by airzhanglin** [comment]
> 死循环的问题，可能是store.getters.roles.length一直为0，addRouters阶段没有手动把roles存到store里。

这个问题是，没有等到addRouters阶段没有手动把roles存到store里，但是这个地方在  store.dispatch('GenerateRoutes', { roles }).then(() => { // 根据roles权限生成可访问的路由表
            router.addRoutes(store.getters.addRouters) // 动态添加可访问路由表
            console.log(store.getters.addRouters)//这个地方能够打印了
            next();
            // next({ ...to, replace: true }) // hack方法 确保addRoutes已完成 ,set the replace: true so the navigation will not leave a history record
          })；这里一直是死循环

**Comment by anrananran** [comment]
死循环大概率是你后端返回的roles是空的

**Comment by zinwalin** [comment]
用户Login后， 保存token到cookie里， 再去取user info， 此时getToken返回为空
