### ISSUE TITLE
登录界面如何弹出信息输入错误的提示标签呢？

### ISSUE THREAD

**Issue by gangyahaidao** [PanJiaChen/vue-element-admin#943]
大家好，今天发现登录界面不能使用$message弹出一个提示标签，添加之后没有效果，目前只能使用难看的alert，想问一下如何添加呢？
我想达到的效果是登录成功和失败都弹出一个标签提示，类似于如下代码：
![image](https://user-images.githubusercontent.com/25075558/43777586-d3b33bba-9a85-11e8-8355-0b680378c62e.png)
如何才能使用this.$message的效果呢？
或者是在登录按钮旁边显示从LoginByUsername这个action传递过来的提示信息也可以，如何传递值过来呢？
感谢

另外发现官网的体验链接失效很久了，但是这个还可以使用https://panjiachen.gitee.io/vue-element-admin/#/login，希望作者能更新一下，这样他人可以方便体验

**Comment by gangyahaidao** [comment]
或者是在登录按钮旁边显示从LoginByUsername这个action传递过来的提示信息也可以，如何传递值过来呢？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/utils/request.js

参照它使用 
···js
import { Message } from 'element-ui'
···

**Comment by gangyahaidao** [comment]
好的
