### ISSUE TITLE
关于路由的懒加载请教一下

### ISSUE THREAD

**Issue by jackZongJava** [PanJiaChen/vue-element-admin#944]
这是我的代码：router.component = () => import(`@/${router.componentPath}.vue`)。我是从后台系统获取的路由集合，然后再在前端设置路由组件的import，这里router.componentPath是一个后台获取的变量。最后我用webpack打包之后，比没有用懒加载多了很多js文件。我的疑问是我的路径是变量，webpack打包的时候并不知道我import的路径是什么，它是怎么按照路由懒加载的规则打包的？会不会有潜在的问题？

**Comment by PanJiaChen** [comment]
import(`./locale/${language}.json`)

根路径不能使变量。

> Every module that could potentially be requested on an import() call is included. For example, import(`./locale/${language}.json`) will cause every .json file in the ./locale directory to be bundled into the new chunk. At run time, when the variable language has been computed, any file like english.json or german.json will be available for consumption. Using the webpackInclude and webpackExclude options allows us to add regex patterns that reduce the files that webpack will bundle for this import.
