### ISSUE TITLE
在登录页面添加一个Dialog显示出现问题，应该怎么解决？

### ISSUE THREAD

**Issue by gangyahaidao** [PanJiaChen/vue-element-admin#945]
今天想在登录页面上添加一个Dialog弹出让用户进行注册，但是在添加代码之后出现了显示问题，操作步骤如下图：
1.点击之前
![image](https://user-images.githubusercontent.com/25075558/43833712-4aeb56b4-9b3e-11e8-8ef9-9157f81e2547.png)

2.点击注册按钮之后所要加载的form表单显示不正常，同时出现了一个遮罩层
![image](https://user-images.githubusercontent.com/25075558/43833768-7206e39e-9b3e-11e8-9489-3721fa5c24d3.png)

3.打开调试信息有如下错误：
![qq 20180808191136](https://user-images.githubusercontent.com/25075558/43833908-ec8133e0-9b3e-11e8-9519-9c2ab4197c19.png)

看样子好像是因为element-ui在登录页面加载的问题，这个需要怎么修改呢？
如果需要测试的话也比较简单，直接把element-ui官网的dialog示例放入登录页面就可以重现了

**Comment by PanJiaChen** [comment]
所以和本项目有什么关系？

**Comment by gangyahaidao** [comment]
出现遮罩层的原因发现是因为<el-dialog>标签中少了一个append-to-body属性，按照element-ui的文档加载其他样式之后最好还是找找本项目中的相关写法比较好

**Comment by SirM2z** [comment]
遇到了同样的问题，在 这个后台模板的 登录页加一个 Dialog 就会出现遮罩的问题
element-ui 文档讲的 Dialog 加 append-to-body 是用来解决 Dialog 嵌套的问题的，但放在这里却可以解决
很神奇，难道 登录页 用了 Dialog 里边的一些样式

**Comment by PanJiaChen** [comment]
@SirM2z `.login-container`的 fixed导致的，我修改一下样式。

**Comment by PanJiaChen** [comment]
refactor in https://github.com/PanJiaChen/vue-element-admin/commit/afdb893dcda349502b528812a1ba25795dd12baa
