### ISSUE TITLE
tinymce输入的时候光标一直在最左边，这个问题没有人遇到吗

### ISSUE THREAD

**Issue by docrun** [PanJiaChen/vue-element-admin#946]
光标一直在最左边。

**Comment by PanJiaChen** [comment]
你说明是什么平台和浏览器。

并提供视频或者截图等可在线demo。

**Comment by docrun** [comment]
不好意思表述错误，我使用的是对话框，就是如果外部的value发生改变，比如编辑的时候（载入新的数据。） 绑定的数据已经发生了改变，但是输入框的内容不会变，这应该也是一个bug.

**Comment by docrun** [comment]
![image](https://user-images.githubusercontent.com/3433889/43883122-a9993f36-9be4-11e8-9578-54295d094581.png)

**Comment by gangyahaidao** [comment]
dialog中的数据是从点击的那一行中加载的，你可以打印一下传递给修改按钮的参数，应该是你代码中列所对应的变量与dialog显示所对应的变量不一致导致的，需要仔细检查一下

**Comment by PanJiaChen** [comment]
`this.refs.xxx.setContent()` 手动设置。

https://panjiachen.github.io/vue-element-admin-site/zh/component/rich-editor.html#tinymce
