### ISSUE TITLE
npm install 出错

### ISSUE THREAD

**Issue by marsapolo** [PanJiaChen/vue-element-admin#951]
MarkLeedeMacBook-Pro:vue-element-admin-master-3 marklee$ npm install
npm ERR! Unexpected end of JSON input while parsing near '...,"shasum":"bb1777fcc0'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marklee/.npm/_logs/2018-08-10T02_32_09_503Z-debug.log
MarkLeedeMacBook-Pro:vue-element-admin-master-3 marklee$ 

这是我没有安装什么插件吗？

**Comment by marsapolo** [comment]
看了看之前的问题列表，https://github.com/PanJiaChen/vue-element-admin/issues/161，感觉我两是类似的问题，可我没有用yarn

**Comment by marsapolo** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/161

**Comment by PanJiaChen** [comment]
`npm cache clean --force`

**Comment by marsapolo** [comment]
感谢可以了，我close了。
