### ISSUE TITLE
npm run build:testing 是怎么配置的

### ISSUE THREAD

**Issue by dengxiaozhen** [PanJiaChen/vue-element-admin#953]
我自己用vue-cli构建了一个项目，照着这套源码，在 config  目录下新建testing.env.js，
BASE_API写的是测试的接口地址
然后在 config 下的 index.js  添加了
```
build: {
    testingEnv: require('./testing.env')
}
```
但是在服务器运行了 npm run build:testing 之后。
却发现 接口地址还是 prod.env.js 下面的 BASE_API的接口地址，而不是我测试环境需要的测试接口地址
请问要怎么配置

**Comment by caojiwang** [comment]
加我QQ  864298777



caojiwang@126.com
 
发件人： 狐狸
发送时间： 2018-08-12 16:44
收件人： PanJiaChen/vue-element-admin
抄送： Subscribed
主题： Re: [PanJiaChen/vue-element-admin] npm run build:testing 是怎么配置的 (#953)
Closed #953.

**Comment by PanJiaChen** [comment]
这就是 vue-cli 的问题了吧。

**Comment by dengxiaozhen** [comment]
意思是说，你这套 vue-element-admin  不是基于 vue-cli 搭建的？

**Comment by dengxiaozhen** [comment]
多谢大佬指点，我自己再研究看

**Comment by magengxin** [comment]
那么请问，在此环境下 如何搭建测试环境呢？
功能是和build一样，只是请求地址不一样
