### ISSUE TITLE
关于图标打包优化的问题

### ISSUE THREAD

**Issue by ristona** [PanJiaChen/vue-element-admin#954]
我觉得项目的图标打包方案非常好，我试着将图标通过Webapck打包到专门的一个文件，可没有成功？不知如何解决？

**Comment by caojiwang** [comment]
您遇到什么问题了，我这边是可以的。







caojiwang@126.com
 
发件人： ristona
发送时间： 2018-08-12 15:41
收件人： PanJiaChen/vue-element-admin
抄送： Subscribed
主题： [PanJiaChen/vue-element-admin] 关于图标打包优化的问题 (#954)
我觉得项目的图标打包方案非常好，我试着将图标通过Webapck打包到专门的一个文件，可没有成功？不知如何解决？

**Comment by PanJiaChen** [comment]
webpack3 使用 `CommonsChunkPlugin`

webpack4 使用 `cacheGroups`

```js
function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

commons: {
          name: 'svg-icons',
          test: resolve("src/icons.svg"), // 可自定义拓展你的规则
          priority: 30,
          reuseExistingChunk: true
        }
```

**Comment by ristona** [comment]
在VUE-CLI3环境中，被打包到chunk-common的JS文件中，我希望能将SVG完全 独立打到一个专门的CHUNK中，而不是CHUNK-COMMON中，因为这个CHUNK会打入其它模块。

**Comment by PanJiaChen** [comment]
我代码都给你了。。。自己查看 `vue-cli`文档，如何修改`config`。
