### ISSUE TITLE
el-table中的行如何实现每行的自动化触发事件？

### ISSUE THREAD

**Issue by gangyahaidao** [PanJiaChen/vue-element-admin#955]
大家好，最近最近在做一个公司内部使用的语音翻译系统，为了提高工作效率准备做一个自动播放el-table列表中音频文件的功能，但是翻了一些vue的文档，好像并没有介绍如何进行这种遍历，具体应用场景如下：
1.el-table中的数据是通过标准的列表方式生成的，代码如下图
![image](https://user-images.githubusercontent.com/25075558/44012876-c5036914-9ef4-11e8-8f5f-4b6c50297cea.png)

2.现在在顶部增加了一个按钮，想实现如果我点击这个按钮，程序能自动去遍历列表中的音频文件进行播放，也就是用程序去触发播放按钮，而不是用鼠标去点击，然后音频播放完毕之后会自动聚焦到文本输入框等待用户输入，输入完毕回车之后接着播放下一个录音，操作界面截图如下：
![default](https://user-images.githubusercontent.com/25075558/44013101-1d6cfde4-9ef6-11e8-8e30-a0a7b7bdb995.png)

我知道如果用普通的js可以用getElementById获取特定的一行，然后使用trigger函数去触发点击播放事件，但是用vue我就没想明白可以怎样控制，求解！

**Comment by PanJiaChen** [comment]
建议在 https://forum.vuejs.org/ 这里提问。

**Comment by PanJiaChen** [comment]
维护一个播放列表，通过 `refs` 触发播放器的 `play`事件就可以了。

**Comment by gangyahaidao** [comment]
好的，谢谢！

**Comment by gangyahaidao** [comment]
音频播放插件代码如下，有需要可以参考一下：
`<template>
  <el-row style="margin-top:-18px">
    <el-slider v-model="percentage" :show-tooltip="false" class="slider"></el-slider>
    <span class="demonstration">{{ currentTime }} / {{ duration }}</span>
    <el-button title="播放" size="mini" type="primary" :icon="!playing||paused ? 'el-icon-success' : 'el-icon-view'" circle class="minibtn" style="margin-left:20px" @click.native="playing ? pause() : play()" :disabled="!loaded"></el-button> 
    <el-button title="停止" size="mini" type="danger" icon="el-icon-error" circle class="minibtn" @click.native="stop()" :disabled="!loaded"></el-button> 
    <el-button title="静音" size="mini" type="info" :icon="!isMuted ? 'el-icon-bell' : 'el-icon-minus'" circle class="minibtn" @click.native="mute()" :disabled="!loaded"></el-button> 
    <el-button title="下载" size="mini" type="warning" icon="el-icon-download" circle class="minibtn" @click.native="loaded ? download() : reload()" :disabled="!loaded"></el-button> 
    <audio id="player" ref="player" v-on:ended="ended" v-on:canplay="canPlay" :src="file"></audio>
  </el-row>
</template>

<script>
    const formatTime = second => new Date(second * 1000).toISOString().substr(11, 8)

    export default {
      name: 'vuetify-audio',
      props: {
        file: {
          type: String,
          default: null
        },
        autoPlay: {
          type: Boolean,
          default: false
        },
        ended: {
          type: Function,
          default: () => {}
        },
        canPlay: {
          type: Function,
          default: () => {}
        }
      },
      computed: {
        duration: function() {
          return this.audio ? formatTime(this.totalDuration) : ''
        }
      },
      data() {
        return {
          firstPlay: true,
          isMuted: false,
          loaded: false,
          playing: false,
          paused: false,
          percentage: 0,
          currentTime: '00:00:00',
          audio: undefined,
          totalDuration: 0
        }
      },

      methods: {
        setPosition() {
          this.audio.currentTime = parseInt(this.audio.duration / 100 * this.percentage)
        },
        stop() {
          this.paused = this.playing = false
          this.audio.pause()
          this.audio.currentTime = 0
        },
        play() {
          if (this.playing) return
          this.paused = false
          this.audio.play().then(_ => { this.playing = true })
        },
        pause() {
          this.paused = !this.paused;
          (this.paused) ? this.audio.pause() : this.audio.play()
        },
        download() {
          this.audio.pause()
          window.open(this.file, 'download')
        },
        mute() {
          this.isMuted = !this.isMuted
          this.audio.muted = this.isMuted
          this.volumeValue = this.isMuted ? 0 : 75
        },
        reload() {
          this.audio.load()
        },
        _handleLoaded: function() {
          if (this.audio.readyState >= 2) {
            if (this.audio.duration === Infinity) {
              // Fix duration for streamed audio source or blob based
              // https://stackoverflow.com/questions/38443084/how-can-i-add-predefined-length-to-audio-recorded-from-mediarecorder-in-chrome/39971175#39971175
              this.audio.currentTime = 1e101
              this.audio.ontimeupdate = () => {
                this.audio.ontimeupdate = () => {}
                this.audio.currentTime = 0
                this.totalDuration = parseInt(this.audio.duration) === 0 ? 1 : parseInt(this.audio.duration)
                this.loaded = true
              }
            } else {
              this.totalDuration = parseInt(this.audio.duration) === 0 ? 1 : parseInt(this.audio.duration)
              this.loaded = true
            }

            if (this.autoPlay) this.audio.play()
          } else {
            throw new Error('Failed to load sound file')
          }
        },
        _handlePlayingUI: function(e) {
          this.percentage = this.audio.currentTime / this.audio.duration * 100
          this.currentTime = formatTime(this.audio.currentTime)
        },
        _handlePlayPause: function(e) {
          if (e.type === 'play' && this.firstPlay) {
            // in some situations, audio.currentTime is the end one on chrome
            this.audio.currentTime = 0
            if (this.firstPlay) {
              this.firstPlay = false
            }
          }
          if (e.type === 'pause' && this.paused === false && this.playing === false) {
            this.currentTime = '00:00:00'
          }
        },
        _handleEnded() {
          this.paused = this.playing = false
        },
        init: function() {
          this.audio.addEventListener('timeupdate', this._handlePlayingUI)
          this.audio.addEventListener('loadeddata', this._handleLoaded)
          this.audio.addEventListener('pause', this._handlePlayPause)
          this.audio.addEventListener('play', this._handlePlayPause)
          this.audio.addEventListener('ended', this._handleEnded)
        }
      },
      mounted() {
        this.audio = this.$refs.player
        this.init()
  },
      beforeDestroy() {
        this.audio.removeEventListener('timeupdate', this._handlePlayingUI)
        this.audio.removeEventListener('loadeddata', this._handleLoaded)
        this.audio.removeEventListener('pause', this._handlePlayPause)
        this.audio.removeEventListener('play', this._handlePlayPause)
        this.audio.removeEventListener('ended', this._handleEnded)
  }

    }
</script>

<style scoped>
  .slider {
    display: inline-block;
    width: 100px;
    position: relative;
    top: 13px;
    margin-right: 8px;
    margin-left: 10px;
  }
  .minibtn {
    padding: 3px 3px;
    width: 20px;
    height: 20px;
    border-radius:10px;
  }
</style>
`
调用方式：
<vueaudio :file="scope.row.fileurl"></vueaudio>

**Comment by gangyahaidao** [comment]
音频播放代码插件代码如下，有需要的可以参考一下：
[vuetifyaudio.txt](https://github.com/PanJiaChen/vue-element-admin/files/2281801/vuetifyaudio.txt)

调用方式：
<vueaudio :file="scope.row.fileurl"></vueaudio>

**Comment by gangyahaidao** [comment]
纠结了几个小时之后，最终采用了一种很扎眼的方式实现：
this.$refs.transactionTable.$el.childNodes[2].childNodes[0].childNodes[1].childNodes[1].childNodes[1].childNodes[0].childNodes[0].childNodes[4].click()
      this.$refs.transactionTable.$el.childNodes[2].childNodes[0].childNodes[1].childNodes[1].childNodes[2].childNodes[0].childNodes[0].childNodes[1].focus()
