### ISSUE TITLE
更换主题之后，页面上的一些自定义的样式被修改了

### ISSUE THREAD

**Issue by gangyahaidao** [PanJiaChen/vue-element-admin#957]
你好，我对页面上的一些样式进行了自定义修改，如果不更改主题是没有问题的，但是如果更改了主题我自定义的样式就不见了，具体如下：

我修改之后的样式：
![image](https://user-images.githubusercontent.com/25075558/44076875-58baf41c-9fd4-11e8-8096-db158cef85ab.png)
主要是修改了一下el-button的样式，加了一个自定义样式class="minibtn"
```
  .minibtn {
    padding: 3px 3px;
    width: 20px;
    height: 20px;
    border-radius:10px;
  }
```
主要修改是默认的圆形按钮太大，修改成了比较小的样式

更换了主题之后我自定义的样式就消失了，截图：
![image](https://user-images.githubusercontent.com/25075558/44077073-ff315dae-9fd4-11e8-93a3-c7711a224415.png)

不太清楚主题更换的原理，这个是什么原因引起的
修改小的圆形按钮有没有其他不受主题切换影响的方式呢，是必须在scss文件中修改样式吗？

**Comment by PanJiaChen** [comment]
自己看一下css不就知道，是谁导致了么。

**Comment by gangyahaidao** [comment]
更换主题之后就成了这样的了，还在看是哪个地方引起的，暂时没发现

**Comment by gangyahaidao** [comment]
发现是因为切换主题之后按钮的大小被改变了，之前是20x20，我自定义样式设置的，更改主题之后就变成了26x26
![image](https://user-images.githubusercontent.com/25075558/44079046-a7ee5a5a-9fda-11e8-87ee-587b5c2ddb89.png)
这个可能是什么原因引起的，主题除了修改背景颜色还会更改样式的大小？

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/44079591-0c2d1c44-9fdc-11e8-92d9-1da1a432531d.png)

**Comment by gangyahaidao** [comment]
对比了一下style样式的变化，发现在更改主题之后，我自定义的部分样式被禁用了，如下：
![image](https://user-images.githubusercontent.com/25075558/44082625-58e6f7be-9fe4-11e8-9e83-6cccfe90a978.png)
标红的两个样式，请教一下这个怎么回事？

**Comment by PanJiaChen** [comment]
不就是简单的css权重覆盖么。

你提高minibtn的权重就好了。
方法自行搜索。

**Comment by gangyahaidao** [comment]
!important
把这个忘记了，谢谢
