### ISSUE TITLE
npm run dev报错，复制了一段报错内容

### ISSUE THREAD

**Issue by meizilove258** [PanJiaChen/vue-element-admin#959]
PS E:\vue-element-admin> npm run dev
> vue-element-admin@3.7.3 dev E:\vue-element-admin
> cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 94% asset optimization

 ERROR  Failed to compile with 54 errors                                                                        15:39:44

 error  in ./src/views/excel/exportExcel.vue

Syntax Error: Unexpected token {

 @ ./src/router/index.js 412:15-51
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:9527 webpack/hot/dev-server ./src/main.js

 error  in ./src/App.vue

Syntax Error: Unexpected token {

 @ ./src/main.js 11:0-24
 @ multi (webpack)-dev-server/client?http://localhost:9527 webpack/hot/dev-server ./src/main.js

**Comment by PanJiaChen** [comment]
你修改过任何代码么？看着像不兼容es6的问题。

**Comment by meizilove258** [comment]
我把  index.html  中的    注释掉了，不注释掉会有如下两个报错：报错一：http://localhost:9527/%3C%= 400 (Bad Request)  ；报错二：  Refused to execute script from 'http://localhost:9527/%3C%=' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.   其它的没有改动，我想着也是不兼容es6，但module中rules 有配置babel-loader。 windows系统

**Comment by meizilove258** [comment]
我把 index.html 中的 一个script引入注释掉了，不注释掉会有如下两个报错：报错一：http://localhost:9527/%3C%= 400 (Bad Request) ；报错二： Refused to execute script from 'http://localhost:9527/%3C%=' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled. 其它的没有改动，我想着也是不兼容es6，但module中rules 有配置babel-loader。 windows系统

**Comment by kaisawind** [comment]
很大的概率是 修改了文件名，但是仍然有地方import 旧的文件。
