### ISSUE TITLE
封装axios请求时，设置了‘axios.defaults.withCredentials = true’，但是发请求时请求头内没有带上cookie信息

### ISSUE THREAD

**Issue by JiangDing1990** [PanJiaChen/vue-element-admin#962]
封装axios请求时，设置了`axios.defaults.withCredentials = true`，但是发请求时请求头内没有带上cookie信息。`request.js`代码如下：
```javascript
import Vue from 'vue'
import axios from 'axios'
import qs from 'qs'
import { Message } from 'element-ui'

// 超时
axios.defaults.timeout = 15000
axios.defaults.withCredentials = true

axios.interceptors.request.use(config => {
  return config
}, error => {
  console.log(error) // for debug
  Promise.reject(error)
})

axios.interceptors.response.use(
  response => response,
  error => {
    console.log('err' + error) // for debug
    Message({
      message: error.message,
      type: 'error',
      duration: 5 * 1000
    })
    return Promise.reject(error)
  })

// 封装的
const ajax = {
  get(url, data) {
    return new Promise((resolve, reject) => {
      axios.get(url, qs.stringify(data)).then((response) => {
        resolve(response.data)
      }, (response) => {
        reject(response.data)
      })
    })
  },
  
  post(url, data) {
    return new Promise((resolve, reject) => {
      axios.post(url, qs.stringify(data)).then((response) => {
        resolve(response.data)
      }).catch((response) => {
        reject(response.data)
      })
    })
  }
}

Vue.prototype.$ajax = ajax

export default axios
```
以上，找了很久原因，一直没找到。求助

**Comment by caojiwang** [comment]
供参考：


import axios from 'axios'
import { Message, MessageBox } from 'element-ui'
import store from '../store'
import { getToken } from '@/utils/auth'

// 创建axios实例
const service = axios.create({
  // baseURL: process.env.BASE_API, // api的base_url
  timeout: 40000 // 请求超时时间
})

// request拦截器
service.interceptors.request.use(config => {
  if (store.getters.token) {
    config.headers['X-Token'] = getToken() // 让每个请求携带自定义token
    config.headers['Authorization'] = getToken(); // 让每个请求携带token--['X-Token']为自定义key
  }
  // console.log('get token..config:', config)
  return config
}, error => {
  // Do something with request error
  console.log(error) // for debug
  Promise.reject(error)
})

// respone拦截器
service.interceptors.response.use(
  response => {
    /**
     * code为非20000是抛错 可结合自己业务进行修改
     */
    const res = response.data;
    if (response.status === 401 || res.status === 40101) {
      MessageBox.confirm('回话超时，可以取消继续留在该页面，或者重新登录', '确定登出', {
        confirmButtonText: '重新登录',
        cancelButtonText: '取消',
        type: 'warning'
      }).then(() => {
        store.dispatch('FedLogOut').then(() => {
          location.reload(); // 为了重新实例化vue-router对象 避免bug
        });
      })
      return Promise.reject('error');
    }
    if (res.status === 40301) {
      Message({
        message: '当前用户无相关操作权限！',
        type: 'error',
        duration: 5 * 1000
      });
      return Promise.reject('error');
    }
    if (res.status === 40001) {
      Message({
        message: '账户或密码错误！',
        type: 'warning'
      });
      return Promise.reject('error');
    }
    if (response.status !== 200 && res.status !== 200) {
      Message({
        message: res.message,
        type: 'error',
        duration: 5 * 1000
      });
    } else {
      return response.data;
    }
  },
  error => {
    console.log('err' + error)// for debug
    Message({
      message: '回话超时，请重新登录！',
      type: 'error',
      duration: 5 * 1000
    });
    return Promise.reject(error)
  }
)

export default service



caojiwang@126.com
 
发件人： JiangDing1990
发送时间： 2018-08-14 19:23
收件人： PanJiaChen/vue-element-admin
抄送： Subscribed
主题： [PanJiaChen/vue-element-admin] 封装axios请求时，设置了‘axios.defaults.withCredentials = true’，但是发请求时请求头内没有带上cookie信息 (#962)
封装axios请求时，设置了axios.defaults.withCredentials = true，但是发请求时请求头内没有带上cookie信息。request.js代码如下：
import Vue from 'vue'
import axios from 'axios'
import qs from 'qs'
import { Message } from 'element-ui'
// 超时
axios.defaults.timeout = 15000
axios.defaults.withCredentials = true
axios.interceptors.request.use(config => {
  return config
}, error => {
  console.log(error) // for debug
  Promise.reject(error)
})
axios.interceptors.response.use(
  response => response,
  error => {
    console.log('err' + error) // for debug
    Message({
      message: error.message,
      type: 'error',
      duration: 5 * 1000
    })
    return Promise.reject(error)
  })
// 封装的
const ajax = {
  get(url, data) {
    return new Promise((resolve, reject) => {
      axios.get(url, qs.stringify(data)).then((response) => {
        resolve(response.data)
      }, (response) => {
        reject(response.data)
      })
    })
  },
  
  post(url, data) {
    return new Promise((resolve, reject) => {
      axios.post(url, qs.stringify(data)).then((response) => {
        resolve(response.data)
      }).catch((response) => {
        reject(response.data)
      })
    })
  }
}
Vue.prototype.$ajax = ajax
export default axios
以上，找了很久原因，一直没找到。求助

**Comment by PanJiaChen** [comment]
#562

**Comment by JiangDing1990** [comment]
@PanJiaChen 谢谢提醒。我后来仔细检查发现是mock.js更改`XMLHttpRequest`为另外一个对象，导致无法携带cookie，我移除掉`mock文件夹`的引用时，发现代码报错了。。目前问题还没有得到解决，貌似是`main.js`文件下`permission.js`的引用导致的错误，明天再看看原因在哪里

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/963
