### ISSUE TITLE
npm run build   404 default build

### ISSUE THREAD

**Issue by BrunoAlencar** [PanJiaChen/vue-element-admin#971]
I just started to try it without config anything, and the build result doesnt work.

app.d8fd50aed9a85bb6be083de30d8439e9.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)

I used the basic template, and try to http-server on dist folder, and this doesnot work... 

can you guys help me?

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/fded36c99066d7ff3b27387a7ec36db9521ff1b9/config/index.js#L63

set to ` assetsPublicPath:'/'`
