### ISSUE TITLE
TreeTable组件渲染性能问题

### ISSUE THREAD

**Issue by souljessi** [PanJiaChen/vue-element-admin#974]
在渲染上千条甚至几百条数据树形结构数据的时候，treeTable组件点击展开行的操作都会很卡，能不能有效的优化一下性能

**Comment by PanJiaChen** [comment]
这主要是 `element-ui` table的问题。它的table数据量一多就卡。

**Comment by yumifen** [comment]
你们知道怎么给treeTable加formatter属性么？

**Comment by PanJiaChen** [comment]
element-ui 已发布 tree-table 所以本项目不在维护 tree-table.
