### ISSUE TITLE
关于打包成静态文件问题

### ISSUE THREAD

**Issue by yclnycl** [PanJiaChen/vue-element-admin#977]
之前运行npm run build:prod的时候dilst下会生成 
static/
vue-element-admin/
favicon.ico
index.html
直接上传部署会提示404 经过观察需要把static文件夹放到vue-element-admin下

今天在新机器上npm install之后再打包发现只会生成
static/
favicon.ico
index.html
这三个文件了
直接部署发现还会404 和之前的原因一样 目前的解决办法是把生成的静态文件里有关路径中的vue-element-admin全部替换掉 请问这是什么原因造成的呢

**Comment by PanJiaChen** [comment]
Duplicate of #971 

我之后会调整一下默认配置的。

**Comment by tilark** [comment]
我也碰到过，我是在/config/index.js中将
```
build: {
    assetsPublicPath: '/vueAdmin-template/', 
}
```
改成``assetsPublicPath: '' ``后恢复
