### ISSUE TITLE
可以让界面更紧凑吗？目前用大屏电脑的仍然是少数吧？

### ISSUE THREAD

**Issue by Chenberg** [PanJiaChen/vue-element-admin#978]
现在的布局在笔记本高分屏（1920）下是适合的，但在1366及以下的分辨率就显得太高太宽图标和文字太大了。目前主流的门户网站仍然按小屏设计的，以至于我会把高分屏笔记本放大125%显示（不放大屏幕文字太小了），所以感觉现在的后台布局很散不紧凑。
放一张图，传统后台界面与当前项目界面的对比：
![bj1](https://user-images.githubusercontent.com/37658900/44294975-cbc02800-a2d2-11e8-8da9-7353d02ebe50.png)
难道以后都要按高分屏设计界面了吗？能否提供一种方法修改几个样式变量，而实现紧凑的界面布局？

**Comment by PanJiaChen** [comment]
感谢你的建议，我会考虑一下这个问题的。

**Comment by axeon** [comment]
我们也有一样的问题，一页看不了几个订单，不如之前bootstrap的方案看着方便。

**Comment by ngxlua** [comment]
我们也有一样的问题

**Comment by PanJiaChen** [comment]
Add in https://github.com/PanJiaChen/vue-element-admin/pull/1024
