### ISSUE TITLE
怎么在 vue-cli3.0 中使用 svg-icon 组件？

### ISSUE THREAD

**Issue by fakaka** [PanJiaChen/vue-element-admin#980]

**Comment by fakaka** [comment]
我自己目前是用 vue-svg-loader 勉强使用 svg，很难受。搞不定 svg-sprite-loader 在vue-cli3.0 里面的配置

**Comment by fakaka** [comment]
这样配置了，但是还是会解析其他的svg文件

``` js
chainWebpack: config => {
    config.module
        .rule('url-loader')
        .exclude.add('./src/icons')
        .end()

    config.module
        .rule('svg')
        .test(/\.svg$/)
        .include.add('src/icons').end()
        .use('svg-sprite-loader')
        .loader('svg-sprite-loader')
        .loader('babel-loader')
        .options({
            symbolId: 'icon-[name]'
        })   
}
```

**Comment by fakaka** [comment]
@GitHdu 不行啊，还想加载的旧的svg格式

**Comment by PanJiaChen** [comment]
```js
chainWebpack: config => {
    config.module
        .rule('svg')
        .exclude.add('./src/icons')
        .end()

    config.module
        .rule('icons')
        .test(/\.svg$/)
        .include.add('src/icons').end()
        .use('svg-sprite-loader')
        .loader('svg-sprite-loader')
        .loader('babel-loader')
        .options({
            symbolId: 'icon-[name]'
        })   
}

```

**Comment by fakaka** [comment]
@PanJiaChen 可以了，谢谢！！！

**Comment by Fun005** [comment]
你好，方便看下你的vue.config.js配置吗，我的图标还是出不来，无法解析

**Comment by luggege** [comment]
请问我的svg-icon不出来,也没有任何报错,是为什么呢?(使用的vue-cli 3.0)
另外: 通过打印发现, 正常的req.keys().map(req)输出的是包装好的module数组, 而我的返回的是类似于"/img/404.cb2515ac.svg"这种格式的数组
 我的vue.config.js配置如下:
// vue.config.js
module.exports = {
    //修改配置
    chainWebpack: config => {
        config
            .resolve.alias
            .set('@', resolve('src'))
        config.module
            .rule('svg')
            .exclude.add(resolve('src/icons'))
            .end()

        config.module
            .rule('icons')
            .test(/\.svg$/)
            .include.add(resolve('src/icons'))
            .end()
            .use('svg-sprite-loader')
            .loader('svg-sprite-loader')
            .options({
                symbolId: 'icon-[name]'
            })
    }
}

var path = require('path')

function resolve(dir) {
    return path.join(__dirname, './', dir)
}

**Comment by MrTenger** [comment]
const resolve = dir => path.join(__dirname, dir);
加上它试试 @TianTang-TT 
eg：.include.add(resolve("./src/icons"))

**Comment by TianTang-TT** [comment]
@MrTenger 多谢，就是这么解决的

config.module
      .rule('svg')
      .exclude.add(path.resolve(__dirname, 'src/icons'))
      .end()

    config.module
      .rule('icons')
      .test(/\.svg$/)
      .include.add(path.resolve(__dirname, 'src/icons'))
      .end()
      .use('svg-sprite-loader')
      .loader('svg-sprite-loader')
      .options({
        symbolId: 'icon-[name]'
      })

**Comment by TianTang-TT** [comment]
@MrTenger 多谢，就是这么解决的

```js
config.module
      .rule('svg')
      .exclude.add(path.resolve(__dirname, 'src/icons'))
      .end()

    config.module
      .rule('icons')
      .test(/\.svg$/)
      .include.add(path.resolve(__dirname, 'src/icons'))
      .end()
      .use('svg-sprite-loader')
      .loader('svg-sprite-loader')
      .options({
        symbolId: 'icon-[name]'
      })
```

**Comment by libp** [comment]
补充一下，icons下的index.js  这段代码比不可少：
`import Vue from 'vue'
import SvgIcon from '@/components/SvgIcon'// svg组件

// register globally
Vue.component('svg-icon', SvgIcon)

-------下面的语句没理解怎么起作用的，但是绝对不能少的
const requireAll = requireContext => requireContext.keys().map(requireContext)
const req = require.context('./svg', false, /\.svg$/)
requireAll(req)
`

**Comment by Afbt** [comment]
我是这样配置  没报错  页面也引入  但是就是不显示图标

config.module.rule("svg").uses.clear();
    config.module
      .rule("svg1")
      .test(/\.svg$/)
      .use("svg-sprite")
      .loader("svg-sprite-loader")
      .options({
        symbolId: "icon-[name]"
      })
      .end()
      .include.add(resolve("src/icons"))
      .end();

**Comment by xcf007** [comment]
> @Fun005 我这样就行了，你把你的发出来看看
> 
> ```js
> module.exports = {
>     devServer: {
>         port: 3001
>     },
>     chainWebpack: config => {
>         config.module
>             .rule('svg')
>             .exclude.add(resolve('src/icons'))
>             .end()
> 
>         config.module
>             .rule('icons')
>             .test(/\.svg$/)
>             .include.add(resolve('src/icons'))
>             .end()
>             .use('svg-sprite-loader')
>             .loader('svg-sprite-loader')
>             .options({
>                 symbolId: 'icon-[name]'
>             })
>     }
> }
> 
> var path = require('path')
> 
> function resolve(dir) {
>     return path.join(__dirname, './', dir)
> }
> ```

解决了我的问题，thks

**Comment by bladeandmaster88** [comment]
> Vue.component('svg-icon', SvgIcon)

vue3这句会报错，如何改造？
