### ISSUE TITLE
Why the chart animations run every time when switch back from other tabs？

### ISSUE THREAD

**Issue by ansonhorse** [PanJiaChen/vue-element-admin#981]
Why the chart animations run every time when switch back from other tabs？
为什么每次从其他选项卡切换回时图表动画都会运行？

Can I turn this feature off?
可以关闭这个特性么？

**Comment by PanJiaChen** [comment]
Have you used keep-alive to cache pages?

**Comment by ansonhorse** [comment]
It turns out that the charts router config option `meta.noCache` is `true`.
Thanks!
