### ISSUE TITLE
升级webpack 4后，打包路径问题

### ISSUE THREAD

**Issue by moonose** [PanJiaChen/vue-element-admin#982]
打包后 资源都加了 vue-element-admin /前缀， 如果放在 web 根目录，会出现找不到资源问题。

**Comment by xwlaix** [comment]
怎么解决的哈？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/2938e33d0eac6b3dbbe842e08c367551e6565b07/config/index.js#L63
