### ISSUE TITLE
chrome 下 elememt-ui 的  table th td 没有正确对齐，发生了偏移，在 firefox 下表现正常

### ISSUE THREAD

**Issue by llyer** [PanJiaChen/vue-element-admin#984]
![image](https://user-images.githubusercontent.com/16920929/44331227-9286e400-a49b-11e8-80b9-43eb964d46cd.png)

chrome 下面 table 的表现如上图所示，我之前也在 chrome 下跑了不少 element 的 table 组件，但是都没有遇到过这个问题

**Comment by PanJiaChen** [comment]
看着像 `elememt-ui`的bug。

主要我这里也不能重现，所以也没啥办法。

**Comment by hanzhenchaoGit** [comment]
<style>
body .el-table th.gutter{
    display: table-cell!important;
}
</style>
@llyer 兄弟 拿走 不谢

**Comment by zengfan0605** [comment]
@llyer 你可以把表头的数据也组合到body的数据里嘛

**Comment by llyer** [comment]
@hanzhenchaoGit  亲测有效，感谢了老铁

**Comment by llyer** [comment]
@zengfan0605 这是饿了么 el-table 组件生成的啊，你这个思路不行吧

**Comment by llyer** [comment]
@zengfan0605 可以是可以，我是说直接用 el-table 就是默认按照标准的表格表头和内容来填充数据，自己写当然可以，麻烦了一点而已，直接用 饿了吗的组件不就是为了省事吗

**Comment by PanJiaChen** [comment]
这主要是 element-ui的问题，有需求可以去官方那里提bug。
