### ISSUE TITLE
其实我是个写后台的，好多warn，甚至还有提示ERR

### ISSUE THREAD

**Issue by wakaryry** [PanJiaChen/vue-element-admin#985]
我就是`clone`下来，然后`npm install`报一堆：

npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
WARN tar ENOENT: no such file or directory, open '/Users/wakaryredou/GitHub/vue-element-admin/node_modules/.staging/codepage-0d6ff06b/cputils.js'
WARN tar ENOENT: no such file or directory, open '/Users/wakaryredou/GitHub/vue-element-admin/node_modules/.staging/core-js-026cdf7b/client/library.min.js.map'
npm WARN script-ext-html-webpack-plugin@2.0.1 requires a peer of html-webpack-plugin@^3.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! Unexpected end of JSON input while parsing near '..."html-minifier":"./cl'
WARN tar ENOENT: no such file or directory, open '/Users/wakaryredou/GitHub/vue-element-admin/node_modules/.staging/font-awesome-027182e6/fonts/fontawesome-webfont.woff'
WARN tarball tarball data for node-gyp@^3.8.0 (sha1-VAMEJhwzDoDQ1e3OJTpoyzlkIYw=) seems to be corrupted. Trying one more time.
WARN tar ENOENT: no such file or directory, open '/Users/wakaryredou/GitHub/vue-element-admin/node_modules/.staging/xlsx-948e527c/dist/xlsx.core.min.map'
WARN tar ENOENT: no such file or directory, open '/Users/wakaryredou/GitHub/vue-element-admin/node_modules/.staging/element-ui-511e54e6/lib/dialog.js'
WARN tarball tarball data for clean-css@4.2.x (sha1-LUEe92uFabbQyEBo2r6FsKpeXBc=) seems to be corrupted. Trying one more time.
WARN tarball tarball data for ajv@^6.1.0 (sha1-caVp0Yns9PTzISJP7LFm8HHdkPk=) seems to be corrupted. Trying one more time.
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

**Comment by kaisawind** [comment]
看起来你需要  npm install  或者 yarn

**Comment by kaisawind** [comment]
网络不好。挂一下淘宝代理可能会好。

**Comment by wakaryry** [comment]
应该是吧。
老报错：
`npm ERR! Unexpected end of JSON input while parsing near '..."html-minifier":"./cl'
`
cache clean了一下：
`npm cache clean --force`
接着就install下来了。
感谢。
