### ISSUE TITLE
api封装灵活度

### ISSUE THREAD

**Issue by coke126** [PanJiaChen/vue-element-admin#989]
我对这里边的api封装理解是封装一个api成一个请求，调用时直接调函数名不用再手写多次axios，
但是像<el-upload>这样需要先显式写url属性，就不能直接取封装的api其中的url出来了，还是想集中管理api，这块请教下如何灵活解决呢？

**Comment by coke126** [comment]
el-upload标签需要显式写url属性（不知道怎么被吃了）

**Comment by PanJiaChen** [comment]
不懂你想表达什么。

**Comment by coke126** [comment]
```
export function createArticle(data) {
  return request({
    url: '/article/create',
    method: 'post',
    data
  })
}
```
比如发表文章，就直接createArticle(data)对吧，但是在文章中要带着上传图片，我这边现在是变成
```
<el-upload
 action="/article/create"
 :data="data">     
```   
就得硬编码一遍地址

我现在描述得清楚吗

**Comment by PanJiaChen** [comment]
这是element 组件设计这样，不然怎么写。

**Comment by PanJiaChen** [comment]
没懂有什么不方便的地方，你把url当做一个变量不就好了。

**Comment by kaisawind** [comment]
@coke126  你看我用的这个是否满足你的要求。
[pet-apis.js](https://github.com/kaisawind/vue-element-admin/blob/master/src/api/pet-apis.js)

这个文件是自动生成出来的。(将swagger.json文件自动生成为axios的js代码。)
对外提供了获取url的方法
```javascript
// domain
export const getDomain = () => {
  return domain
}
// api's url
export const addPet_RAW_URL = function() {
  return '/pet'
}
```

源码是[swagger-vue](https://github.com/chenweiqun/swagger-vue)
然后用grunt进行触发代码生成。

代码生成方法:
```bash
npm run build:swagger
```
或
```bash
yarn build:swagger
```

**Comment by xiaoyi8** [comment]
怎么连接后台接口？大神

**Comment by kaisawind** [comment]
@xiaoyi8  我的后台是用swagger-server将swagger.json 生成出的代码。

本质是使用swagger将前台和后台进行分离。代码都是自动生成的。

前端使用的时候跟正常的axios一样用。
注：**入参不需要区分是header，path，query，body, 生成的代码里已经有判断了**

大概是下面的样子。
```javascript
var params = {
  "id": 0,
  "category": {
    "id": 0,
    "name": "string"
  },
  "name": "doggie",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "status": "available"
}
addPet(params).then(response => {
  console.log(response.data)
}).catch(err => {
  console.log(err)
})
```

**Comment by nabaonan** [comment]
我就是只封装api接口，方法是哪里调用哪里再写，封装直接获取url地址的方法，感觉现在这么封装是有点不够灵活哈，但是貌似好多解决方案都是这么干

**Comment by Aysnine** [comment]
你可以在 axios 拦截器里对 url 进行二次分配，甚至动态分配。而 el-upload 的问题比较特殊，可以根据它的配置重写自定义请求，先放一放。
