### ISSUE TITLE
你好，请问在ElementUI框架下怎么给table加标签？

### ISSUE THREAD

**Issue by renruijun** [PanJiaChen/vue-element-admin#99]
![image](https://user-images.githubusercontent.com/28946184/27523755-f50481c6-5a61-11e7-87c7-024caf507471.png)

**Comment by PanJiaChen** [comment]
没懂什么意思

**Comment by WiXiM** [comment]
用v-modal,看可以参考src/views/example/table.vue

**Comment by AlenQi** [comment]
@renruijun 直接用element的标签

**Comment by renruijun** [comment]
好的，现在已经解决了问题。谢谢！！
