### ISSUE TITLE
关于element分页的问题

### ISSUE THREAD

**Issue by GUEThe** [PanJiaChen/vue-element-admin#990]
![image](https://user-images.githubusercontent.com/19553651/44393740-13abad00-a568-11e8-8057-2307b34073f4.png)
我在页面中这样使用element的分页，但是pager-count不起作用，是怎么回事呢？版本如下。

**Comment by GUEThe** [comment]
![image](https://user-images.githubusercontent.com/19553651/44393997-ad735a00-a568-11e8-838f-5bf37011d55a.png)

**Comment by PanJiaChen** [comment]
和本项目无关。
