### ISSUE TITLE
不用mock模拟，怎么连接后台登陆接口 

### ISSUE THREAD

**Issue by xiaoyi8** [PanJiaChen/vue-element-admin#992]
比如：
接口
https://aa.11.com/admin/login
参数
name=admin&pwd=1234
====================
返回结果
{"msg":"登录成功","status":1,"token":"1"}
点击然后登进项目首页，我是新手，能说说吗

**Comment by zarte** [comment]
api里的login.js对应的url改成https://aa.11.com/admin/login这样就可以了，mock对应的路由可以去掉

**Comment by xiaoyi8** [comment]
@zarte 谢谢大神，我改了，但是点击登录后不跳转到首页，查看控制台Network显示：
  Headers的General：
         Request URL: https://aa.11..com/admin/login
        Request Method: OPTIONS
        Status Code: 200 
        Remote Address: 11.11.11.11
        Referrer Policy: no-referrer-when-downgrade
 Preview显示
        {msg: "登录失败", status: 0, token: ""}
        msg:"登录失败",status:0,token:""
这是什么原因呀？

**Comment by xiaoyi8** [comment]
@zarte 
还有Request Headers
Provisional headers are shown
Access-Control-Request-Headers: content-type
Access-Control-Request-Method: GET
Origin: http://localhost:9528
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by xiaoyi8** [comment]
@zarte 大神
项目没改变之前，mock模拟，启动项目，点击登录跳转，查看控制台Network显示：
name-------info?t=1534906132394
   Headers的General：
        Request URL: http://localhost:9500/sockjs-node/info?t=1534906132394
        Request Method: GET
       Status Code: 200 OK
       Remote Address: 127.0.0.1:9500
       Referrer Policy: no-referrer-when-downgrade
 Headers的Resquest Headers:没有警告
 Headers的Query String Parameters:
	t: 1534906132394
改了项目api里的login.js对应的url为https://aa.11.com/admin/login后，输入账号admin,密码1234点击登录没反应，查看控制台Network显示：
name-------login
  Headers的General：
       Request URL: https://aa.11..com/admin/login
       Request Method: OPTIONS
       Status Code: 200
       Remote Address: 11.11.11.11
       Referrer Policy: no-referrer-when-downgrade
 Headers的Resquest Headers:有警告
 Headers里没有出现Query String Parameters
我想问问Request URL:怎么是https://aa.11..com/admin/login，为什么不是https://aa.11..com/admin/login?name=admin&pws=1234的形式？
https://aa.11..com/admin/login显示的是{msg: "登录失败", status: 0, token: ""}
如果https://aa.11..com/admin/login?name=admin&pws=1234就会显示{msg: "登录成功", status: 1, token: "1"}

**Comment by kaisawind** [comment]
跨域了。
- 1. 让后台支持跨域请求
- 2. web开发版中可以配置proxy

/config/index.js
例如：
```json
proxyTable: {
      '/v1': {
        target: 'http://192.168.1.192:30303',
        changeOrigin: true,
        secure: false,
        pathRewrite: {
          '^/v1': '/v1'
        }
      }

    },
```

**Comment by xiaoyi8** [comment]
@kaisawind 谢谢大神

**Comment by xiaoyi8** [comment]
@kaisawind 不好使，也不知道是哪我写的不对

**Comment by jhfkf** [comment]
去掉header里面的token试试，我的也是这样，加上就报跨域的错误，postman显示是好的

**Comment by PanJiaChen** [comment]
`mock.js` 会导致跨域失败。你移除试试。

**Comment by jhfkf** [comment]
需要后台配合调整一下  刚才测试 可以了

**Comment by xiaoyi8** [comment]
@jhfkf
在哪去掉header里面的token

**Comment by xiaoyi8** [comment]
@PanJiaChen 也不好使，是不是我哪写不对了？
大神，如果就您这个项目下载下来什么都不动，安装npm依赖，启动项目。
相与这个后台登陆接口https://aa.11.com/admin/login连接，参数是name=admin&pwd=1234
需要做什么呀？
最后输入admin和1234能进入项目首页

**Comment by kaisawind** [comment]
首先确认一下你这个后端服务是否好用。
我这边是ping不通的。

![1534930811](https://user-images.githubusercontent.com/4010613/44456184-779aa800-a632-11e8-911b-7f8c524e36dd.png)

**Comment by xiaoyi8** [comment]
@kaisawind 大神，非常抱歉，这个后端服务网址我是瞎写的，查了下说是点击登录时admin和1234这两字段数据没有请求上后端服务去，只向后台发出请求，没有提交数据，所以返回{"msg":"登录失败","status":0,"token":""},我搞蒙了，是不是校验的问题，没把数据请求上去。非常感谢你们对我这个新手这么耐心帮助

**Comment by kaisawind** [comment]
@xiaoyi8 
vue-element-admin默认的login方法是post方法，不会以挂参的形式传参。

query挂参例子
```javascript
export function fetchList(query) {
  return request({
    url: '/article/list',
    method: 'get',
    params: query
  })
}
```

FormData传参例子
```javascript
export function loginByUsername(username, password) {
  const data = {
    username,
    password
  }
  return request({
    url: '/login/login',
    method: 'post',
    data
  })
}
```

另外，OPTIONS 返回状态是200说明后端已经支持跨域请求
```
Request Method: OPTIONS
Status Code: 200
```

**Comment by xiaoyi8** [comment]
@kaisawind 大神，有什么QQ群交流群的吗？想加进去多请教你们

**Comment by xiangshuishicheju** [comment]
@xiaoyi8 请问您解决了吗，我也遇到了这个问题

**Comment by xiaoyi8** [comment]
@xiangshuishicheju  config里换上公共域名，api换上提交接口，看你传参的方式是什么，是get还是post,post用data形式，get用params形式，然后看下axios拦截，在utils\request.js，你可以把响应拦截改成reponse=>reponse(或reponse.data),看看reponse返回的数据
