### ISSUE TITLE
后端获取动态路由后 左侧菜单 国际化出现警告请问有什么好的处理办法吗

### ISSUE THREAD

**Issue by mc7qing** [PanJiaChen/vue-element-admin#996]
![default](https://user-images.githubusercontent.com/33148552/44447624-5aa6aa80-a61b-11e8-9a66-679c05f25d10.png)

RT中文菜单都是从后台获取的

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/lang/en.js

请配置国际化相应的key。

**Comment by denghp** [comment]
楼主，后台获取动态路由，点击能切换国际化吗？我这报错了，还没找到原因
```
You may have an infinite update loop in a component render function
```

**Comment by mc7qing** [comment]
> 楼主，后台获取动态路由，点击能切换国际化吗？我这报错了，还没找到原因
> 
> ```
> You may have an infinite update loop in a component render function
> ```

可以的啊 估计你的代码有问题  

给你参考下
src/store/modules/permission.js 

![snipaste_20181123_175031](https://user-images.githubusercontent.com/33148552/48937254-78e8b300-ef48-11e8-8ac0-95bd48c07a2d.png)

**Comment by denghp** [comment]
@mc7qing 我的实现方式跟你的没啥区别，下面的是我的实现方式
https://github.com/PanJiaChen/vue-element-admin/issues/1360
