### ISSUE TITLE
侧边栏的问题

### ISSUE THREAD

**Issue by Ttou** [PanJiaChen/vue-element-admin#997]
如果 dashboard 设置为 hidden，点击 dashboard 不会使当前激活的侧边栏项状态改变。
![20180822155620](https://user-images.githubusercontent.com/4298437/44450707-21bf0380-a624-11e8-9d24-c42117a4cf93.png)
![20180822155654](https://user-images.githubusercontent.com/4298437/44450712-2388c700-a624-11e8-8e6f-4f2899bf3a8d.png)

**Comment by Ttou** [comment]
@PanJiaChen 还真是，我用2.4.6就有问题，退回2.4.4就正常了

**Comment by PanJiaChen** [comment]
https://github.com/ElemeFE/element/pull/12178
