### ISSUE TITLE
期望能动态更换侧边栏的列表。

### ISSUE THREAD

**Issue by TothingWay** [PanJiaChen/vue-element-admin#998]
请问潘大如何动态更换侧边栏的导航

**Comment by PanJiaChen** [comment]
业务场景是什么？

**Comment by TothingWay** [comment]
@PanJiaChen 
业务场景简介：
一个利用爬虫爬取所有手机 app 信息的管理系统，在初始登录后台管理系统后，侧边栏含有一个allAppList页面，页面中为一个用户收藏app table list，点击某行，进入相应的 app 详情，同时更换侧边栏导航为如下几个板块：
1. app 总览
2. 下载量
3. 评分
4. 评论
5. ...

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/189e645b238d73d66cc6ac7adac1d96e3b0d2c97/src/views/layout/components/Sidebar/index.vue#L25

自己修改这个就行了

**Comment by TothingWay** [comment]
好的，谢谢
